### ISSUE TITLE
Opening dank storage crashing the game

### ISSUE THREAD

**Issue by DreaminBoi** [NillerMedDild/Enigmatica6#1]
**Modpack Version :** 
Enigmatica 6 0.1.3

**Issue** :
When opening the storage from the dank storage mod it's instantly freeze the game and then crashed tried with dank 1 & dank 2 i'm not sure about the other storage 

**Crashlog** :
https://paste.ee/p/r4G0h

**Comment by Darkere** [comment]
We are 3 versions behind on Dank Storage. It is probably fixed.
