### ISSUE TITLE
Mod Suggestion: Immersive Engineering

### ISSUE THREAD

**Issue by SQbuilder** [NillerMedDild/Enigmatica6#10]
https://www.curseforge.com/minecraft/mc-mods/immersive-engineering

**Comment by NillerMedDild** [comment]
It will be added, I just need to configure it to not crash frequently :P

**Comment by Kataiser9** [comment]
I added IE to my own E6 world; I do not recommend it until the next update, even with crash workarounds. The two main crash sources are a) the handbook and b) new worldgen creating IE mineral vein data. I "fixed" it by basically setting the mineral vein generation chance to 0%,, but of course that (presumably) means that all chunks I'm currently exploring are now permanently veinless.
