### ISSUE TITLE
The report bug link in the main menu opens the enigmatica 5 repo

### ISSUE THREAD

**Issue by mrDLSable** [NillerMedDild/Enigmatica6#100]
![image](https://user-images.githubusercontent.com/1783781/89691032-44797e00-d908-11ea-9217-25f34f9b889c.png)

**Comment by Shindur** [comment]
Well yes... if you had a bug with the pack you'd want to report it to the right place, no? :P

**Comment by Darkere** [comment]
Not sure if troll.. but that is the E6 pack linking to the E5 bug tracker.

**Comment by Shindur** [comment]
I click on the same thing and takes me to E6 repo. version 0.2.5 of the pack

**Comment by Darkere** [comment]
Yep can confirm. Links me to the correct place. @mrDLSable please make sure you are on the latest version.

**Comment by mrDLSable** [comment]
I recorded my screen as proof: https://youtu.be/5rvdjz0fWlA

**Comment by NillerMedDild** [comment]
Update the modpack. I have fixed this already.

**Comment by Darkere** [comment]
It's possible that updating twitch did not update this for you in some way. Might need a fresh instance to see it.
