### ISSUE TITLE
Wither Bee keeps killing itself (Fixed by setting size to 1 temporarily)

### ISSUE THREAD

**Issue by WoodenJoe** [NillerMedDild/Enigmatica6#1003]
**Modpack version**
0.3.6

**Describe the bug**
Every time I let a wither bee loose it kills itself after some time flying around. Just bred my 3rd bee and this one killed itself after only a couple of minutes of it being alive. The first 2 seem to kill themselves on the glass ceiling, this last one was taking damage every time it left the apiary, and then finally died flying into a glass wall.
Really frustrating seeing how many diamonds it costs to breed them. 

I was going to report directly to the mod author, but their bug report states:
_"If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code."_

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by prestonator** [comment]
This is also happening to my wither bees on version 0.3.7

**Comment by NillerMedDild** [comment]
@prestonator A clean reinstall ought to fix that :)

**Comment by NillerMedDild** [comment]
This was fixed in 0.3.7 :)

**Comment by NillerMedDild** [comment]
I need to read the issue properly before making a verdict, sorry :P We'll look into this issue, thanks for the report.

**Comment by NillerMedDild** [comment]
Screenshots of the Apiaries would be very helpful :)

**Comment by WoodenJoe** [comment]
I forgot to mention another odd side note, I have 2 Apiarys right now, side alongside, Light and dark. I released an Oreo bee into the light one. I came back to find the bee gone/missing/dead, and super oreos in both apiary storages. As if he was able to teleport over to the other apiary, and probably die on the wither roses.

This is the first Apiary (used to be alone):
![Screenshot 2021-01-23 094624](https://user-images.githubusercontent.com/77864505/105590563-183fa580-5d60-11eb-9d96-5c9c3a4e501e.png)

This is the second one with dark glass for night bees. Carpets down right now to keep my other bees from dying to the Wither roses.

![Screenshot 2021-01-23 094711](https://user-images.githubusercontent.com/77864505/105590685-21c90d80-5d60-11eb-980f-31a37b761801.png)

![Screenshot 2021-01-23 094659](https://user-images.githubusercontent.com/77864505/105591089-3e654580-5d60-11eb-842d-b64b49b4db30.png)

**Comment by NillerMedDild** [comment]
Is there an Apiary block between the Apiary multiblocks?

**Comment by WoodenJoe** [comment]
I'm not sure I understand the question. below is the current config. But the wither bee has died in a single apiary multiblock previously.
![Screenshot 2021-01-23 194646](https://user-images.githubusercontent.com/77864505/105618332-ece6a600-5db3-11eb-8164-838036bd1349.png)

**Comment by prestonator** [comment]
Sorry, can't post a screenshot right now :( but my apiary was made of: grass for the bottom, clear glass from the connecting glass mod, and spruce planks for the roof. I also had a spruce glass door next to the apiary controller.

**Comment by NillerMedDild** [comment]
Alright, hopefully this is fixed when the issue I linked is :)

**Comment by kosma** [comment]
I've temporarily fixed my private server by setting all bee sizes to be max 1.0 (the only affected ones I found were wither bee and ghast bee). Perhaps a similar temporary fix could be implemented in E6 until it's fixed upstream?

**Comment by NillerMedDild** [comment]
> I've temporarily fixed my private server by setting all bee sizes to be max 1.0 (the only affected ones I found were wither bee and ghast bee). Perhaps a similar temporary fix could be implemented in E6 until it's fixed upstream?

Sounds reasonable, sure :)

**Comment by jinkhya** [comment]
Hello,
I believe this issue is also happening with Oreo Bees. A friend of mine told me he keeps loosing his, he saw them killed themselves in a similar way as described in this issue. However I couldn't find the config for it to change the size ; I saw in code it is 1.25.

**Comment by NillerMedDild** [comment]
We cannot change the Oreo bee I'm afraid.

**Comment by jinkhya** [comment]
Yeah I know, :'( 
EpicOreo would have to do it but I'm not sure he would, he'll probably look for a way to fix this issue without having to reduce the size of bees. 
I was just letting you know in case other players encounter this problem :)

**Comment by WoodenJoe** [comment]
As I mentioned before, I too had an oreo bee in mine, that somehow teleported from one apiary to the other and then disappeared(I know this because both light and dark storages had super oreos and I only had one oreo bee), I just kinda gave up on them for a bit.
