### ISSUE TITLE
Add more fluids for Neromantic Prime

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1004]
Neromantic Prime is one of the Astral Sorcery endgame items, which is like an IE excavator but for fluids, in that it can used to obtain limited amounts of fluids under the bedrock. Currently it only fetches water and lava. 

Suggestions: 
 - Ether Gas (IF): ~5 buckets?
 - Pink Slime (IF): ~30 buckets?
 - Crude oil: or something that can easily be converted into RF. 100-500 buckets?
 - Experience (IF Essence or PnC Memory Essence): (no idea how much)
 - Liquid Lithium (Mek): (no idea how much)
 - Liquid Sulfuric Acid and Liquid Hydrochloric Acid (Mek): for Mekanism 5x, ~100 buckets?
 - fluid.bloodmagic.life_essence_fluid (Blood Magic) and 
 - fluid.bloodmagic.doubt_fluid (Blood Magic): (I'm not sure if those fluids have a use)

Amounts can be varied of course, also it is _very_ tentative list of suggestions

**Comment by MuteTiefling** [comment]
Oil I could see. And, really it could be in pretty huge quantities, given the Immersive pump will pump forever (though it slows down when the well is 'dry') 

The rest? They all have ways of automating them that are more interesting than this (other than doubt fluid, which isn't fully implemented yet anyway).

**Comment by NillerMedDild** [comment]
It doesn't only fetch water and lava at the moment though. We've already added quite a few fluids to the list:

```toml
fluid_rarities = [
  "minecraft:water;2147483647;2147483647;14000", "minecraft:lava;4000000;1000000;7500",
  "immersivepetroleum:oil;2500000,1000000,5000",
  "mekanismgenerators:flowing_fusion_fuel,1000000,500000,100",
  "industrialforegoing:sewage_fluid,10000000,5000000,250",
  "bloodmagic:life_essence_fluid_flowing,5000000,2500000,250",
  "industrialforegoing:sludge_fluid,1000000,1000000,200",
  "immersivepetroleum:napalm,500000,500000,100",
  "industrialforegoing:essence_fluid,500000,100000,300", 
  "mekanism:flowing_heavy_water,10000000,2000000,2500"]
```

**Comment by HaxtonSale1** [comment]
My bad, never checked if it was updated in the latest version
