### ISSUE TITLE
Reduced Sulfur ore weight of Astral Sorcery Mineralis ritual

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1005]
in version 0.3.7, Sulfur ore has a weight of 3000, higher than Coal (2400). 
(One use I see is for simplifying mekanism 5x)

**Comment by NillerMedDild** [comment]
I think there was one too many zeros added :P thanks for the report, will reduce to 300.

**Comment by MuteTiefling** [comment]
I think the Nature's Aura generator and IF lasers are at the same level, actually. Will check in a bit
