### ISSUE TITLE
Totem of Holding Restore Grave Command

### ISSUE THREAD

**Issue by toothmonsterr** [NillerMedDild/Enigmatica6#1006]
**0.3.7 BETA**

**Describe the bug**
When you pick up a tomb of holding after death, it puts everything back in your inventory in order and also equips your armor. However, your baubles just go into your inventory. If you had a full inventory at death, this leads to baubles being on the ground and potentially lost (including backpacks filled with goodies).

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it to Quark (see above)

**Comment by Merlo17** [comment]
On that note, someone on discord suggested this mod to replace the totems: https://www.curseforge.com/minecraft/mc-mods/gravestone-mod

Not sure if it warrants some looking into, but apparently the totems have some issues where they'll lose items sometimes. A main feature of that mod is also a command to restore inventory even if you lost the gravestone. Could be interesting to look up

**Comment by NillerMedDild** [comment]
We changed from the Gravestone mod to Quark because of glaring issues and closed source, but the command was nice.

**Comment by NillerMedDild** [comment]
Suggested commands here: https://github.com/Vazkii/Quark/issues/2929

**Comment by Merlo17** [comment]
Oh, didn't remember, must've been before I played E5. Carry on then ^^

**Comment by NillerMedDild** [comment]
Since Totem of Holding is going away in 0.4.0 I'll close this.
