### ISSUE TITLE
Refined Obsidian Dust and Obsidian Dust is Ore Dictionaried

### ISSUE THREAD

**Issue by NoraHanegan** [NillerMedDild/Enigmatica6#1009]
**Modpack version** 0.3.7

**Describe the bug**
The items are oredictioanried and as such you can skip the osmium compressor

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It's not though? Can't reproduce.
