### ISSUE TITLE
Certus/Fluix/Nether Quartz Crusher Recipes & Unification

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#101]
**Modpack version**
0.2.5

**Issue**
Enhancement, basically in the title. Unify the Nether Quartz dusts from AE2 and Mekanism to allow them to be made in the Mek crusher, and allow the Certus Quartz Dust to be crushed in the Mek Crusher. Currently can only get em from the AE2 grindstone.

**Comment by Shindur** [comment]
And Fluix dust as well :P

**Comment by NillerMedDild** [comment]
I'll get that done, hopefully this evening :)
