### ISSUE TITLE
Crash when putting labeled crate into sophisticated backpack.

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1010]
Enigmatica 6 - 0.3.7 (E6 server)

Tried to place a Engineer's decor labeled crate full of some sort of stone (not positive which it was) into a sophisticated backpack and it crashed my client.  Repeated once to confirm.

Crash report:
https://pastebin.com/iVxdz3ZD

**Comment by AdamNisbett** [comment]
Update: not sure that was the issue.  I logged back in a third time and didn't try to put it in my backpack, but still crashed.

https://pastebin.com/6ChzbLKT

**Comment by NillerMedDild** [comment]
What did you do when you crashed the first time? Open the labeled crate? What's in the label slot?

**Comment by AdamNisbett** [comment]
I had just broken a bunch of labeled crates full of different stones from my custom cobble gen setup, so I don't know which one I was trying to put into the backpack.  It would have been one of the 5 or 6 stones that are made via cobble gen method and not stone gen method, but since they'd all already broken and you can't tell them apart easily in the inventory I don't know which I was trying to place in.  Each was completely full of a single stone type with that also in the label slot as well.

The crash happened the first two times immediately upon trying to put it into the backpack, but then I crashed a third time without attempting to put anything in the backpack, so not sure what the cause was.  Upon loading in a 4th time I placed all the crates back in the world as blocks immediately and emptied them before moving them and did not see another crash.  I haven't done any further attempt to replicate the circumstances.

**Comment by NillerMedDild** [comment]
> I haven't done any further attempt to replicate the circumstances.

Excellent choice :P

Looks like an Engineer's Decor issue tbh, will relay to them.
