### ISSUE TITLE
Lost trinkets with right click activations don't work

### ISSUE THREAD

**Issue by toothmonsterr** [NillerMedDild/Enigmatica6#1014]
**0.3.7 BETA**

**Describe the bug**
Multiple players reporting on my server that trinkets with right click activation (such as Magneto, which right clicks on air to get all items in a 10x10 range) do not work.

**Comment by NillerMedDild** [comment]
Confirmed and relayed, thanks for the report :)

**Comment by NillerMedDild** [comment]
Your hand needs to be empty for it to work, could that be the issue?

**Comment by BlueAgent** [comment]
Oh yeah, forgot to mention. In an update, the Magneto trinket has an optional keybind now (unbound by default).
When you bind it, it'll disable the right click on air to collect and instead collect when you press the keybind.
