### ISSUE TITLE
Ars Nouveau Grow Spell Doesn't Function

### ISSUE THREAD

**Issue by toothmonsterr** [NillerMedDild/Enigmatica6#1015]
**0.3.7 BETA**

**Describe the bug**
The Ars Nouveau spell "Grow" will not function, intended to grow crops but currently does nothing.

**Comment by NillerMedDild** [comment]
It would appear it needs to be a touch spell. Asked the mod dev whether this was intended :)

**Comment by toothmonsterr** [comment]
That works, yup! Thanks for clearing that up.

**Comment by NillerMedDild** [comment]
Sure thing. The mod author intends to find a way to make projectiles work too :)

**Comment by oatmealmanFG** [comment]
3 years later and they must have forgotten. projectile, grow, aoe, aoe, aoe does NOTHING to crops but makes grass grow tall grass

**Comment by theboo** [comment]
> 3 years later and they must have forgotten. projectile, grow, aoe, aoe, aoe does NOTHING to crops but makes grass grow tall grass

Projectile by itself does not target non split blocks, if it did you would never be able to hit a mob in a grassy field... You need to add sensitive after projectile to target non-solid blocks, this is covered in ars' documentation

**Comment by oatmealmanFG** [comment]
> > 3 years later and they must have forgotten. projectile, grow, aoe, aoe, aoe does NOTHING to crops but makes grass grow tall grass
> 
> Projectile by itself does not target non solid blocks, if it did you would never be able to hit a mob in a grassy field... You need to add sensitive after projectile to target non-solid blocks, this is covered in ars' documentation

thank you. im trying to make a spell for the spell turrets that will 'bonemeal' an area and then harvest and pickup, but im having a difficult time getting it right
