### ISSUE TITLE
[Suggestion] SecurityCraft

### ISSUE THREAD

**Issue by XLuma** [NillerMedDild/Enigmatica6#1017]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/security-craft
**Mod description**
SecurityCraft adds... well, security features such as Security cameras, turrets, movement detection lasers, and much more. 

**Why would you like the mod added?**
Perfect to protect houses, nuclear reactors, stashes or your local village against any player that would like to take a look at your stuff, or if mobs are a problem in the area. Definetely usable with all the content Enigmatica adds (plus, its kinda rp)
**Screenshots if applicable.**
Available on the curseforge thread

**Comment by NillerMedDild** [comment]
I think this mod would be more suited for a PvP centric modpack, not so much E6 :)
