### ISSUE TITLE
Removed Create/Eidolon/Occultism Ores from the Astral Sorcery Mineralis Ritual

### ISSUE THREAD

**Issue by TheAnimaDust** [NillerMedDild/Enigmatica6#1019]
**Modpack version**
0.3.7
**Describe the bug**
Astral sorcery Minerallis ritual not generating nether quartz and ancient debris, not sure if it`s intentional or not but quartz and debris have minecraft tag.

**Comment by TheAnimaDust** [comment]
Also the ritual is also generating create, occultism and eidolon ores which i belived are disable in world gen.

**Comment by NillerMedDild** [comment]
Both intended as they are nether ores, but the second part of your issue I have fixed, thanks for reporting! :D

**Comment by TheAnimaDust** [comment]
:3
