### ISSUE TITLE
Tallow Unification

### ISSUE THREAD

**Issue by TheAnimaDust** [NillerMedDild/Enigmatica6#1020]
**Modpack version**
0.3.7
**Describe the bug**
The crafting of talllow can only be executed throught the blast furnace.

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm not sure if this is a bug or not, will investigate.

**Comment by NillerMedDild** [comment]
We could definitely improve Tallow that's for sure :) it will still only be smeltable in the Blast Furnace though, as I believe it is intended.
