### ISSUE TITLE
AS Starmetal suggestions

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica6#1025]
Two related suggestions:

- Good that we can stonecutter the iron chunks into ore for conversion, but is it possible to set it up so the chunk entity can be converted directly? Not sure if Astral can do this tbh, but it would be very cool. Maybe on the Starlight Infusion altar?
- I'd also suggest some alternate ways to go from Ingots -> dust. The cutting tool is obnoxious, and rewarding players for using say Create Crushing Wheels or the IE crusher by letting them avoid that mechanic (outside of crystals) would be nice. Makes it easier to automate, with the balance being no fortune/dup chance.

**Comment by NillerMedDild** [comment]
Good ideas, we'll have a look.
