### ISSUE TITLE
Silver, Nickel, and Zinc not accepted into enrichment chamber

### ISSUE THREAD

**Issue by nswerhun** [NillerMedDild/Enigmatica6#1027]
**Modpack version**
0.3.6
**Describe the bug**
Silver, nickel and zinc chunks (from *Emandatus Enigmatica*) will not go into *Mekanism* Enrichment chamber. However, they are able to go into the *Thermal Expansion* pulverizer. 
**Logs**
N/A, does not cause a crash

**Screenshots**

https://user-images.githubusercontent.com/24984195/105619959-47383480-5dbd-11eb-8751-1bb6ec21f21d.mov

**Comment by MuteTiefling** [comment]
You'll need to update. this has been fixed in the current release.

**Comment by nswerhun** [comment]
Oops, Thanks!
