### ISSUE TITLE
Biomes of Plenty sandstone variant recipes missing from custom stone gen.

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1028]
Enigmatica 6 0.3.7

Though the sandstone variants from BoP generate when using the diamond block stone generation, the recipes for using them as the catalyst stone to generate more are missing and they simply generate vanilla stone if used.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
