### ISSUE TITLE
Multiple Copper Ores Spawning

### ISSUE THREAD

**Issue by nsmuhic** [NillerMedDild/Enigmatica6#103]
**Modpack version**
0.25

**Issue**
Both Mekanism and Immersive Engineering Copper Ores spawn in Worldgen.
[2020-08-07_22 01 59](https://user-images.githubusercontent.com/69376061/89701189-1f7e0e80-d8fa-11ea-9816-170ae03a6e62.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Sorry about that, will be fixed asap!
