### ISSUE TITLE
Inventory HUD+

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#1030]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge

**Mod description**
More visual and useful HUD

**Why would you like the mod added?**
In my opinion, this mod can make the potion effects and inventory space more clearly displayed, without repeatedly opening the inventory to check the remaining duration of potion effects and inventory space, and this mod occupies very little memory
(I'm not good at English, there may be some wrong words and mistakes in grammar)

**Screenshots if applicable.**
https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge/screenshots

**Comment by Merlo17** [comment]
I'm not super sure this is needed, but on the other hand it seems pretty customizable, so you could just turn it off I guess. 
I'd probably have to play with it for a bit to see how I really feel about it. Might test it later

**Comment by TemperedFool** [comment]
Is this entirely client-side? If so people who want it could just install it.

**Comment by TGMax233Michael** [comment]
So I could just install it？(I've always thought that add a mod without permission would offend the author :I)

**Comment by Merlo17** [comment]
Of course you can, it's your playthrough after all :P

**Comment by NillerMedDild** [comment]
Feel free to add all the clientside mods you want, I won't take offence :P 
Adding mods yourself does occasionally make bug fixing harder though, so there's that.

**Comment by Merlo17** [comment]
I've had a look - it's honestly pretty neat, I like how modular it is and it's very customizable, you can even turn it off entirely if you wish. I'm especially a fan of the potion HUD, the armor HUD is also fine but I'd personally disable the inventory one by default. Otherwise, I think it might be neat to have in the pack, I see nothing wrong with it

**Comment by lunulu** [comment]
To the topic of client-side mods. Why is there no optifine by default?

**Comment by theboo** [comment]
Because optifine can cause more issues than it is worth for many people. Best to let the people who want it install it themselves

**Comment by jjspace** [comment]
There's actually an issue with status effects being hidden behind the FTBChunks minimap, this looks like it could solve that problem.

**Comment by NillerMedDild** [comment]
Oh good point

**Comment by NillerMedDild** [comment]
I didn't like it tbh :P

**Comment by Merlo17** [comment]
I just noticed it doesn't have a github tracker, but just in case I dropped the issue we were having as a suggestion, maybe it will get implemented

https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge/issues/25
