### ISSUE TITLE
Invisible mobs 

### ISSUE THREAD

**Issue by Z3r024** [NillerMedDild/Enigmatica6#1031]
**Modpack version**
0.3.6

**Describe the bug**
Basically, I was wandering around my world at night and suddenly got shot at by a skeleton, I look around and there is nothing yet a skeleton was still shooting at me, then I saw where the arrows were coming from so I tried to attack it but it seems to be invincible to any sort of damage. After reloading my world I could see the skeleton but the world seems to be blocked for some reason. (no mob movement, breaking block doesn't drop anything etc.) Tried to reload the world again but got stuck in the "saving world" screen

**Logs**
https://gist.github.com/Z3r024/75daa59df14407033a016e2b825b61dd

**Screenshots**

**Comment by Merlo17** [comment]
you can post the log on gist.github.com ^^

**Comment by Z3r024** [comment]
> you can post the log on gist.github.com ^^

Ow, I didn't know about this. I will upload it and edit my post. Thanks!

**Comment by Darkere** [comment]
Caused by optifine.

**Comment by Z3r024** [comment]
> Caused by optifine.

is there a setting I could toggle to prevent this from happening?

**Comment by soepie7** [comment]
It's something that happens even in vanilla with Optifine. It is not sure what causes it besides saying that Optifine causes it. The only solution is to not use Optifine.

**Comment by Z3r024** [comment]
> It's something that happens even in vanilla with Optifine. It is not sure what causes it besides saying that Optifine causes it. The only solution is to not use Optifine.

got it. Thanks!
