### ISSUE TITLE
Stone Bricks not valid Apiary block

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica6#1033]
**Modpack version**
0.3.8
**Describe the bug**
Stone Bricks are not tagged as valid_apiary, but stone brick slabs are.

![x2021-01-24_08 51 14](https://user-images.githubusercontent.com/46051093/105634024-987a0f80-5e21-11eb-8b89-fdc95075bf3d.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
