### ISSUE TITLE
Can't take items from Enchanting Apparatus

### ISSUE THREAD

**Issue by TokioDemon** [NillerMedDild/Enigmatica6#1041]
**1.9.0**

**Can't take items from Enchanting Apparatus**
When I right click on the Enchanting Apparatus with a fist I am unable to grab the item inside (item: Jar of Light) if that helps

**Logs**
N/A

**Screenshots**
N/A

**Comment by Merlo17** [comment]
...1.9.0??

**Comment by NillerMedDild** [comment]
There is no version 1.9.0 of the modpack, please try again :P
