### ISSUE TITLE
Question - Ask Permission for adding to Mcmod

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#1042]
**Mcmod** is a Chinese mods forum, similar to curseforge. It contains many mods and modpacks. I saw someone add the Enigmatica series before (only the corresponding curseforge link), and I also participated in a little editing ( (Added the corresponding github link). Although I have asked others about the inclusion, their answer is as long as they do not provide other unofficial download links, but I still want to ask for permission,.If this infringement, I will quickly let it be deleted. If it's possible, I want to let more Chines people play with the high-quality modpack you (your team) made
(My English is not good)

Mcmod Link: https://www.mcmod.cn/modpack/27.html

**Comment by NillerMedDild** [comment]
As long as downloading is done through CurseForge, they keep the versions up to date, and do not break CurseForge ToS, sure :)

**Comment by TGMax233Michael** [comment]
I've finished editing. have a look.
https://www.mcmod.cn/modpack/27.html
