### ISSUE TITLE
Different Brass Alloy Recipes

### ISSUE THREAD

**Issue by Toonlink264** [NillerMedDild/Enigmatica6#1043]
**Description**
Could you make the alloy numbers between the alloy furnaces match, it's odd having the induction smelter do one recipe for an alloy and the kiln having a better recipe for the same item

**Why would you like this added/changed?**
just, consistency

**Comment by Merlo17** [comment]
By alloys I'm assuming you mean Brass? The other ones seem in line to me

**Comment by Toonlink264** [comment]
was that the only one? it was the main one but yes
