### ISSUE TITLE
Thermal cultivation

### ISSUE THREAD

**Issue by Toonlink264** [NillerMedDild/Enigmatica6#1044]
---------------------------->

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/thermal-cultivation

**Mod description**
COFH farming mod

**Why would you like the mod added?**
watering cans. pretty much only reason

**Comment by Merlo17** [comment]
Just as a clarificationn, watering cans are nice to have but a lot of what the mod does is overlap with other mods in the pack. It would have to be heavily tweaked with most of the stuff removed. I'll let niller decide if it's worth it

**Comment by NillerMedDild** [comment]
I don't want to add it, too much stuff we don't need in it :( it was even removed from the pack for that reason.
