### ISSUE TITLE
Ores

### ISSUE THREAD

**Issue by Toonlink264** [NillerMedDild/Enigmatica6#1045]
**Modpack version**
0.3.9

**Describe the bug**
Occultism ores are showing up in world gen

**Screenshots**
![Screenshot 2021-01-26 01 40 12](https://user-images.githubusercontent.com/60859491/105724139-74c8dd80-5f77-11eb-95cc-5510b9b9c696.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I couldn't reproduce this issue, but I disabled the ores even harder now :P
