### ISSUE TITLE
Broken Undergarden

### ISSUE THREAD

**Issue by SeaSaltStar** [NillerMedDild/Enigmatica6#1049]
**0.3.9**

**Describe the bug**
Chunk generation and overall use of the Undergarden is incredibly broken. Upon entering the dimension on a server, only 2 chunks generated, I could not pickup items, and enemies were undamageable/had broken AI. I tried reentering the dimension multiple times and there was no resolve. However, when another player was present chunk gen appeared normal, and the other bugs resolved themselves. Another note is that when the other player was present entities on the outskirts of the genned chunks had broken AI.

**Screenshots**
https://imgur.com/a/f6DNc1Z

**Comment by SeaSaltStar** [comment]
After returning to my game after making this post a few more chunks had generated, but no where near the normal rate. The other bugs are also still present.

**Comment by theboo** [comment]
Similar issues are present on the official e6 server starting at 0.3.8.. Rid tried to figure out what was going on but said the big brain people were needed lol

**Comment by NillerMedDild** [comment]
This was causing by removing `virulent_mix_source` and `virulent_mix_source_flowing` from the `minecraft:water` fluid tag.

**Comment by r-mc2** [comment]
Would it be safe to assume that v0.3.9 is safe for the Undergarden? Or will this be in a special v0.3.9.1?

**Comment by NillerMedDild** [comment]
It will be 0.3.10 :) 

> Would it be safe to assume that v0.3.9 is safe for the Undergarden?

I don't really understand the question?

**Comment by r-mc2** [comment]
> It will be 0.3.10 :)
> 
> > Would it be safe to assume that v0.3.9 is safe for the Undergarden?
> 
> I don't really understand the question?

I have not had enough coffee today, I read the comment about v0.3.8 and missed the bug report was for v0.3.9 (deleted my comment to remove confusion... but not fast enough it would seem 😆)

**Comment by NillerMedDild** [comment]
Heh :P 0.3.10 should fix Undergarden, including the parts that have been generated already.

**Comment by SeaSaltStar** [comment]
It appears there's still issues with the dimension. After installing the update and entering the dim everything appeared fine. The dim was then reset to account for chunk errors upon updating, the dimension has some inconsistencies it seems that about every other time I enter the dimension the original issue turns back up, that being slow or no generation whatsoever and not being able to pick up items.
