### ISSUE TITLE
Charged certus quartz ore converts to normal certus quartz in Enrichment chamber

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#105]
**Modpack version**
0.2.5

**Issue**
as the title suggests, charged certus quartz ore processes to certus quartz in enrichment chamber
![2020-08-08_14 02 52](https://user-images.githubusercontent.com/59537798/89706080-39623480-d980-11ea-9d38-9f09f76039de.png)
![2020-08-08_14 02 53](https://user-images.githubusercontent.com/59537798/89706086-3f581580-d980-11ea-9ac8-23c3d0826689.png)
dont know if this is a bug or intentional, feel free to close it otherwise :)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by KrAzYGEEK32** [comment]
same tag for both ores might be the issue now that i think of it 
also, tags for both ores dont seem to work on a digital miner(ill make a new issue if required for this)

**Comment by NillerMedDild** [comment]
Merging with #101
