### ISSUE TITLE
KubeJS script errors on servers running 0.3.9

### ISSUE THREAD

**Issue by Drytchnath** [NillerMedDild/Enigmatica6#1050]
0.3.9

**Describe the bug**
Enigmatica 6 servers are displaying Kubejs error warnings on startup to players. This has been observed on both Apex and Bisect servers running the latest version.

These script errors are affecting multiple item recipes including multiple mekanism sawmill planks, the Ars Enchanter's Bow and multiple entries for items like mana jars are blank in the Ars manual just to name a few problems.

**Logs**
https://pastebin.com/a7ME609s

**Screenshots**
https://imgur.com/GoXP2Oq

**Comment by NillerMedDild** [comment]
Thanks for the report, this was caused by an oversight. Removing the kubejs folder and replacing it with a "fresh" copy should fix this. Would you mind letting me know whether that works for you?

**Comment by Drytchnath** [comment]
Loading a fresh copy fixed the issue, no longer getting the error upon logging in and I can now see the recipes for the items that were missing before.

**Comment by NillerMedDild** [comment]
Glad to hear it, sorry for the inconvenience :)
