### ISSUE TITLE
Sophisticated Backpacks Dupe Bug

### ISSUE THREAD

**Issue by Gooderness** [NillerMedDild/Enigmatica6#1060]
**Version**
Enigmatica 6 Version 0.3.2

**Bug Description**
Ability to duplicate items using sophisticated backpacks upgrades.
Having more than one Advanced Magnet Upgrade for a Sophisticated Backpack makes it duplicate items that are picked up by it.

**Screenshots**
https://clips.twitch.tv/ObliqueBlushingEggANELE

**Comment by NillerMedDild** [comment]
This was fixed a good while ago, you're 7 versions behind. Please update :)
