### ISSUE TITLE
Ores have stone texture in item form

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1063]
Enigmatica 6 0.3.9 (official E6 server)

When any ores (not chunks, but the ore blocks themselves) are in item form (not placed as block form) they look exactly like the normal stone that they're embedded in (i.e. stone, limestone, etc).  

![image](https://user-images.githubusercontent.com/9061144/105782302-e4b87300-5f39-11eb-8e33-55f63e45c41f.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Can't reproduce, are you using Optifine?

**Comment by AdamNisbett** [comment]
No, I've not added anything beyond the default. I use GDLauncher to download if it matters.

I suppose it's possible one of the files got corrupted in download, but not sure how I would determine which to test.

**Comment by NillerMedDild** [comment]
A reinstall should alleviate that, if you don't mind trying :)

**Comment by AdamNisbett** [comment]
Will do.  I've got slow internet, so I tend to avoid reinstalls, but I've got a while before I will be able to get back on anyway, so I'll start it working on the re-download.

**Comment by AdamNisbett** [comment]
By the time I'd gotten it downloaded the server had switched to 0.3.10 and I'm not still having the issue with that - so not sure what the issue was, but it seems to either be fixed in the latest version or the result of a corrupt download on my end.
