### ISSUE TITLE
Packed Ice dupe

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica6#1066]
**Modpack version**
0.3.5
**Describe the bug**
You can duplicate ice/packed ice/blue ice, starting with one ice block, as follows:

1 Ice block -> Botania Pure Daisy/Create Washing -> 1 Packed Ice -> Botania Pure Daisy -> Blue Ice -> Thermal Multiservo Press w/ Unpacking Dye -> 9 Packed Ice -> TE MSP w/ Unpacking Dye -> 81 Ice

Undoubtably harmless (especially in non-expert), but I would expect unintended (I'm guessing the unpacking recipes are standard TE). Would be very easy to set up a loop that places an ice block by the Daisy, silk touches the resulting blue ice, unpacks it, and repeats.

I only noticed it as I was working on Dry Ice manufacture for a Powah reactor, which is probably the only reason you might want to nerf it (probably by removing the unpacking recipes).

**Comment by BlueAgent** [comment]
I think the strange thing here would be the thermal multiservo press unpacking even though there's no unpacking recipe.
The loop given above is probably more efficient to just do the `packed ice -> blue ice (daisy) -> 9x packed ice (unpacking)`.

On a related note, ice itself is renewable through water and Pedestals allows for infinite packed ice at a pretty crazy rate when you place blue ice beneath and use silk cobble generator upgrade.
With Capacity V and Speed V it can produce 20 stacks of packed ice per second.

**Comment by NillerMedDild** [comment]
Thanks for the report, but we will not be fixing it - It's a pretty large processing chain for a block that is infinite anyways :)

**Comment by TemperedFool** [comment]
I didn't think it was much of an issue, but I agree that the unpacking recipes are a bit weird ^_^
