### ISSUE TITLE
Mod guidebooks not placeable on Builder's Addition bookshelves

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#1069]
**Modpack version**
E6 v0.3.9

**Describe the bug**
Two guide books do not count as "books" for Buildersaddition bookshelves (e.g. buildersaddition:bookshelf_oak) and thus cannot be stored in them:

- occultism:dictionary_of_spirits
- alexsmobs:animal_dictionary

**Logs**
n/a

**Screenshots**
n/a

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it :)
