### ISSUE TITLE
"Nou're"

### ISSUE THREAD

**Issue by Toonlink264** [NillerMedDild/Enigmatica6#1073]
**Modpack version**
0.3.9
**Describe the bug**
tier 6 tetra quest has "nou're" in the description

**Screenshots**
![Screenshot 2021-01-26 20 07 14](https://user-images.githubusercontent.com/60859491/105827599-1a308f80-6012-11eb-8e5e-69a5fc8597d5.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, fixed :)
