### ISSUE TITLE
Server Crash after modpack update.

### ISSUE THREAD

**Issue by bugzfighter** [NillerMedDild/Enigmatica6#1074]
**0.3.9**

**server crash, Singleplayer crash**
Updated my server and Mod pack to 0.3.9 and since Both have crashed Every attempt to login.

**Logs**
[crash-2021-01-26_07.01.19-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/5873193/crash-2021-01-26_07.01.19-server.txt)

**Screenshots**

**Comment by bugzfighter** [comment]
Update to the issue, Still no clue what is causing this, so any information would be Greatly valued, i run the server for me and my group of Friends, Not sure why the server just wont stay open, its crashed on its own now 8 times, with the same crash log information posted above, Most recent crash log below

[crash-2021-01-26_08.25.07-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/5873602/crash-2021-01-26_08.25.07-server.txt)

regarding Single player, the entire mod pack just crashes, it doesn't give me anything besides Error code -0 or error code -1 doesn't supply me with anything more.

**Comment by Darkere** [comment]
I'm not sure but I thought we removed tinkers mechworks?

Might be on the list for 0.4.0.

Your server is failing to read the data for a Drawbridge. If you know where it is you could remove it with nbt explorer.

Otherwise starting without tinkers mechworks replacing the block and relaunching with it should work. (make a backup)

**Comment by bugzfighter** [comment]
Alright, so, I'm a noob when it comes to All of this, How would one use nbt Explorer.

**Comment by Darkere** [comment]
Wrote a guide some time ago:
https://gist.github.com/Darkere/9e2ebda80a92a91d9257cfc2bcc016a5

**Comment by theboo** [comment]
Might be related to this https://github.com/SlimeKnights/TinkersMechworks/issues/109#issue-792554848

**Comment by bugzfighter** [comment]
So, if i dont manually fix, its just a matter of Time, waiting on the modpack updates?

**Comment by Darkere** [comment]
Yes. You could even try updating just those two mods.

**Comment by bugzfighter** [comment]
i use ScalaCube as my host for the server, i'm not sure if i can Just update the Two mods itself, given it loads the full ModPack from CurseForge itself.

**Comment by NillerMedDild** [comment]
I'll release an update tonight to fix this :)

**Comment by bugzfighter** [comment]
Wonderful, thank you @NillerMedDild i'll just find Manually fix the mods till then!

**Comment by bugzfighter** [comment]
Both SinglePlayer And my Server Client Side Still crash, The server no longer crashes anymore, the Manual mod fixs fixed that, but im not too sure as to Why the client side keeps crashing :/ Any help? 
![crash](https://user-images.githubusercontent.com/78025526/105881958-bcc52000-5fca-11eb-87f6-fb4411437933.png)
![Server online](https://user-images.githubusercontent.com/78025526/105881962-bd5db680-5fca-11eb-8e62-1ba5d29d6ec1.png)
not to sure what more i can do, even crashes with Single player (New worlds)

**Comment by theboo** [comment]
Got a crash report for this one?

**Comment by bugzfighter** [comment]
added the log to the last comment.

**Comment by theboo** [comment]
I can't do anything with that log on mobile, but are you using Optifine?

**Comment by bugzfighter** [comment]
Yes, i use optifine,  it was fine before but maybe bc i updated from 0.3.6 to 0.3.9?

**Comment by theboo** [comment]
Yes there is a bug with the latest 1.16.4 Optifine, latest forge and mekanism... Either don't use Optifine or install the latest 1.16.5 Optifine preview (works fine on 1.16.4)... The 1.16.5 version does not work with Optiforge if you are using that you have to remove it

**Comment by bugzfighter** [comment]
that has fixed the issue, thank you, never thought that it could have been Optifine compatibility issues.
