### ISSUE TITLE
[Suggestion] Allow Iron Chest quests to be done with the upgrade

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#1076]
I usually never directly craft Iron/Gold/Diamond Chests but rather craft their upgrade items to upgrade my existing chests. It would be nice to have the corresponding quests also work if you get the matching upgrade item instead of only working with the chests.

Modpack: 0.3.9

**Comment by NillerMedDild** [comment]
Sounds reasonable, sure thing.

**Comment by MuteTiefling** [comment]
I've got a number of quest tweaks I'd like to do, so I can knock this out with those.

**Comment by MuteTiefling** [comment]
Quests are now updated with the new tags. Should be all good for next update.
