### ISSUE TITLE
Terra Steel AIOT Deletes Bedrock

### ISSUE THREAD

**Issue by discodaemon** [NillerMedDild/Enigmatica6#1077]
**Modpack version**
 0.3.6

**Terra Steel AIOT Deletes bedrock with the built in AOE mining**
Terra Steel AIOT when the AOE mining (3x3 for a B grade AIOT) is turned on , if the block you mine touches bedrock, bedrock is deleted.

**Logs**
No crash reports

**Screenshots**
![test1](https://user-images.githubusercontent.com/78033424/105864285-64385780-5fb7-11eb-97a2-739ca43a75a7.png)
![test2](https://user-images.githubusercontent.com/78033424/105864279-63072a80-5fb7-11eb-8bc7-b3fc9541b0e7.png)
![test3](https://user-images.githubusercontent.com/78033424/105864274-626e9400-5fb7-11eb-9246-ae3f425b7e1a.png)
![test4](https://user-images.githubusercontent.com/78033424/105864267-613d6700-5fb7-11eb-8439-581011bbb5fa.png)

The screenshots show that only the first block has this bug when vein mining. However when not using vein mining, it is every block

**Comment by NillerMedDild** [comment]
Fixed in 0.3.9, please update :)
