### ISSUE TITLE
Returning to main menu immediately leads to the multiplayer menu

### ISSUE THREAD

**Issue by Copedizzle** [NillerMedDild/Enigmatica6#1079]
When I save and quit my world, instead of returning to the main menu, the multiplayer menu opens instead.

**Comment by Merlo17** [comment]
I've actually observed this as well, hadn't noticed before. Can confirm this is happening

**Comment by NillerMedDild** [comment]
This also happens to me, not sure what to make of it. Definitely a bug though, thanks for the report.

**Comment by MuteTiefling** [comment]
So, I can confirm it's not packmenu, or at least not with a default config

Made a fresh instance with only that, loaded into SP, exited and it took me back to the main menu properly. Not the Server list

**Comment by NillerMedDild** [comment]
Next up: Cherished Worlds mod?

**Comment by MuteTiefling** [comment]
Same instance, removed pack menu, added Cherished Worlds. No issue. Takes me back to main menu as expected.

**Comment by MuteTiefling** [comment]
Noticed this has apparently stopped in the dev instance.

**Comment by NillerMedDild** [comment]
Ah right! This was caused by Random Patches, and was - wait for it - patched.

**Comment by Copedizzle** [comment]
Ah, nice. Thanks for the hard work!

**Comment by NillerMedDild** [comment]
Our pleasure, we didn't do anything :P

**Comment by Copedizzle** [comment]
I meant in general. Enigmatica has been my go to modpack for years now, so I just thought I'd show my appreciation :)
