### ISSUE TITLE
String Too Big Error On Server Connection

### ISSUE THREAD

**Issue by Sable8654** [NillerMedDild/Enigmatica6#1080]
Latest 0.3.9

Just updated my server from 0.3.2 to the latest version and transferred the world we were using. Server starts up fine but no players can connect. Server log is saying 
[11:43:57] [Netty Server IO #1/ERROR] [minecraft/NettyPacketEncoder]: io.netty.handler.codec.EncoderException: String too big (was 33638 bytes encoded, max 32767)
I've googled all around for a fix but can't find any concrete answer or anything that works.

Also should add that this issue doesn't happen on the old version, only once I update it

If there's anyway to fix this it I'd love to know how, thanks

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5875080/latest.log)

**Comment by Merlo17** [comment]
Sounds similar to https://github.com/NillerMedDild/Enigmatica6/issues/824?

**Comment by Sable8654** [comment]
Oh yea wow thats the exact same issue, the png fix they said suprisingly fixed it. Thanks for linking that

**Comment by timename** [comment]
我也遇到了相似的问题：Internal Exception: io.netty.handler.codec.EncoderException: String too big
为了解决这个问题，我排查了许多文件。终于，我在服务器文件：server.properties 中发现了许多无意义的乱码，类似\u00C3\u0083\u00C2\u0083\u00C3\u0082\u00C2\u0083\u00C3\u0083 我将他们全部删除后，服务器就可以正常运行了。

Translate through Bing
I'm also having a similar issue: Internal Exception: io.netty.handler.codec.EncoderException: String too big
To solve this problem, I troubleshoot a number of files. Finally, I found a lot of meaningless garbled characters in the server file: server.properties, like \u00C3\u0083\u00C2\u0083\u00C3\u0082\u00C2\u0083\u00C3\u008. After I deleted them all, the server was running normally.
