### ISSUE TITLE
Cats crash the server

### ISSUE THREAD

**Issue by FancyBagel** [NillerMedDild/Enigmatica6#1081]
**Modpack version**
Enigmatica 6 0.3.8

**Describe the bug**
Whenever a tamed, sitting cat is clicked to stand up, the server completely crashes. Then it crashes whenever the cat-having chunk is loaded. Killing the cat with a command with chunk unloaded fixes the problem until someone else decides to adopt a killer pet.

**Logs**
https://pastebin.pl/view/3b4e103e

**Comment by Darkere** [comment]
Supplementaries is the most likely culprit

**Comment by NillerMedDild** [comment]
Fixed in 0.3.9 :)
