### ISSUE TITLE
Industrial Foregoing Ore Laser Empty Tag

### ISSUE THREAD

**Issue by Jkosio23** [NillerMedDild/Enigmatica6#1082]
E6-0.3.5

Using the Industrial Foregoing Ore Laser and 6 Yellow laser lenses in a Plains biome, I got a barrier block titled "Empty Tag forge:chunks/arcane"

Screenshot:
https://i.gyazo.com/d8a2fda1caa9a60eceec1dd135d7038e.png

And based on the fact that I haven't seen an entry on the changelog saying as such, I believe this to be unfixed as of yet.

**Comment by NillerMedDild** [comment]
This has been fixed :)

**Comment by Jkosio23** [comment]
Thank you for the quick reply!

**Comment by NillerMedDild** [comment]
Sure thing, thanks for the report.
