### ISSUE TITLE
Quest for Mekanism sodium-based cooling/Thermoelectric boiler, and example boiler blueprint

### ISSUE THREAD

**Issue by Starfang42** [NillerMedDild/Enigmatica6#1083]
**Description**
Add in a quest, possibly branching off the turbine quest, for sodium-based reactor cooling and specifically the Thermoelectric Boiler. Along with this quest, add a Building Gadgets blueprint for an example Thermoelectric boiler.

**Why would you like this added/changed?**
Right now, water-based cooling of the fission reactor is covered, but sodium-based cooling is not. The thermoelectric boiler is the primary addition to the setup needed for sodium-based cooling. A mention of how to get sodium (brine in an electrolyzer) as part of this proposed quest should be enough.

**Comment by NillerMedDild** [comment]
@MuteTiefling what do you think? :)

**Comment by MuteTiefling** [comment]
Quite doable. Need to sit down and figure out sodium cooling so it isn't just 'hur, you can use sodium too'

Basic boiler pattern should be super simple though.

**Comment by MuteTiefling** [comment]
Alright, I've added a single quest here explaining how the boiler is used for Sodium Cooling. The gadget is called out in the quest text as it is for the others. Hopefully it's clear enough :-D

![image](https://user-images.githubusercontent.com/9543430/106017652-ad0f0f80-608e-11eb-87d1-9ee1873bdb70.png)

**Comment by Starfang42** [comment]
Looks great to me. Thanks!
