### ISSUE TITLE
Minerallis ritual 

### ISSUE THREAD

**Issue by TheAnimaDust** [NillerMedDild/Enigmatica6#1088]
**Modpack version**
0.3.9
**Describe the bug**
I don`t think its intended but as the astral book refers to minerallis ritual the more you infuse starlight more often the change occurs but the more i infuse it only expands the range of the ritual.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Intended interaction. To anyone out there in the future: see linked issue for details.
