### ISSUE TITLE
Refined Storage Colored Crafters

### ISSUE THREAD

**Issue by jlong5795** [NillerMedDild/Enigmatica6#1091]
**CurseForge Link**

**Description**
Currently the colored crafters from Refined Storage cannot be used to upgrade to higher tiers.

**Why would you like this added/changed?**
Either include them in recipes for upgraded crafters or include a recipe to "un-color" the crafter (like water bucket + colored crafter gives an empty bucket and a crafter)

**Screenshots if applicable.**

**Comment by anivlys** [comment]
They actually can be converted back to the normal crafters. Just combine a colored version with light blue dye to get the default "Crafter".

**Comment by Ridanisaurus** [comment]
Still, being able to use them in the recipe without needing to convert them back would be pretty nice

**Comment by Darkere** [comment]
I'm pretty sure I added tags for all the colored blocks. So this should be pretty simple.

**Comment by Merlo17** [comment]
Can confirm, tags are there. Just a matter of editing the tiered recipes, should be easy enough
