### ISSUE TITLE
Trash Slot Issues

### ISSUE THREAD

**Issue by SeaSaltStar** [NillerMedDild/Enigmatica6#1093]
**Modpack version**
0.3.10
**Describe the bug**
The ender farmer's lead is not able to be trashed via the trash slot. Upon closing your inventory the ender lead pops onto the ground and leaves a ghost item in the slot.
**Screenshots**
https://cdn.discordapp.com/attachments/802988228688609330/803868073093365810/2021-01-27_01-03-21.mp4

**Comment by Merlo17** [comment]
Trying to replicate this, but this seems to happen with any item for me, not just the lead?

**Comment by NillerMedDild** [comment]
I can't reproduce this with any item, on a server.

**Comment by Merlo17** [comment]
Testing rn on E6 dev, latest commit in SP. Can't trash anything

**Comment by MelanX** [comment]
I think you understand the trash slot wrong. The trash slot saves the items until you put another item to it. The old one will destroyed, the new item saved. You could change that in config.

**Comment by SeaSaltStar** [comment]
But, the issue lies that the item drops instead of being voided/staying in the slot until replacement.

> I think you understand the trash slot wrong. The trash slot saves the items until you put another item to it. The old one will destroyed, the new item saved. You could change that in config.

**Comment by MelanX** [comment]
Oh sorry, just read the comments. Need to learn to read the initial issue report, too. :P
