### ISSUE TITLE
Nether Portal not working/ Nether not being generated

### ISSUE THREAD

**Issue by OdenShilde** [NillerMedDild/Enigmatica6#1095]
0.3.10

Nether Portal doesnt work and i believe the nether isnt being generated

**Comment by Merlo17** [comment]
Probably related to https://github.com/NillerMedDild/Enigmatica6/issues/1090, we're looking into a fix

**Comment by NillerMedDild** [comment]
Do you mean The End? We cannot reproduce the issue with the Nether.
