### ISSUE TITLE
Mining Gadget Silk Touch does not work on Spawners

### ISSUE THREAD

**Issue by fancysanta** [NillerMedDild/Enigmatica6#1098]
**Modpack version**
0.3.9
**Describe the bug**
Pretty much what it says on the tin; attempting to use the Mining Gadget with the Silk Touch module installed results in the beam doing nothing whatsoever to a spawner, not even mining it out in the regular fashion. Attempting without the module also results in the beam having no interaction. Also tested just smacking the spawner to death with it in either configuration just in case, and silk touch or not just results in breaking the block as if you had used your hands. Also attempted placing a spawner and then modifying it with Apotheosis modifiers in case that would alter the block state at all and produce any changes in results, but no dice.

**Logs**
Log not applicable.

**Comment by Toonlink264** [comment]
that would be because none of the gadget mods work on tile entities

**Comment by NillerMedDild** [comment]
This is by design, the Mining Gadget does not work on Tile Entities, as Toonlink264 said :)

**Comment by fancysanta** [comment]
Ah, was unaware of that. Thanks for the quick response :D
