### ISSUE TITLE
Machine alloying recipes for Eidolon Pewter

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#1099]
**Modpack version**
0.3.10

**Describe the bug**
Pewter from Eidolon is only craftable through Eidolon's recipe of Pewter Blend, which is 1 Iron + 1 Lead = 2 Pewter, smelt in a Furnace for ingots.

As the recipe is (seemingly) the first thing you do in the mod, it's not a complicated recipe, and it's an alloy, it would be nice to have it craftable using the various alloy smelters in the pack *(from what can craft invar/bronze it's IE's Alloy Kiln and Arc Furnace, Thermal's Induction Smelter, and Create's Mixer when heated)*.

~~Also the Pewter Ingots don't show up in JEI but I want to see on a fresh Eidolon instance to see where to make the issue for that.~~ That issue is #1100.

**Comment by NillerMedDild** [comment]
Sure thing. @MuteTiefling you want dibs on this? :P

**Comment by Merlo17** [comment]
I'll call dibs, seems easy enough that I won't screw anything up :P

**Comment by MuteTiefling** [comment]
Have fun!
