### ISSUE TITLE
Eidolon ingots and nuggets hidden in JEI

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#1100]
**Modpack version**
0.3.10

**Describe the bug**
Pewter Ingots and Pewter Nuggets from Eidolon are not visible in the JEI search, while the Block and Blend are. They are still visible through finding them with other recipes and do not have any equivalent that is displayed instead of them (and they are used in the recipes).

I checked and this does not happen in a fresh instance with Eidolon so I'm reporting here.

**Comment by NillerMedDild** [comment]
Yeah my bad, sorry :P

**Comment by Lykrast** [comment]
Just to update since I didn't check properly: Arcane Gold Ingots/Nuggets are also hidden (the recipe for the ingots also doesn't show up in JEI but I don't know if it's from the mod or a side effect).

**Comment by Merlo17** [comment]
Likely a side effect of a script. I think those two are the only ingots in the mod that should be unhidden, while lead should stay hidden. Correct?
