### ISSUE TITLE
Random Stone gen issue

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica6#1103]
**Modpack version**
0.3.10
**Describe the bug**
using the random cobblestone gen method of letting lava flow into water, i placed a Diamond block under the place they meet and it does not produce random stone, just standard cobblestone. The iron block produces random cobblestones as expected.
I was trying to get some basic diorite and granite since they were removed from world gen.

**Comment by soepie7** [comment]
Iron blocks works with what would normally create cobblestone, and diamond blocks if stone would be created. If you got cobblestone, then a diamond block has no effect on it.

**Comment by Dracos99** [comment]
restarted server with a fresh copy of config and default configs seems to have fixed my issue...it is now generating fine
