### ISSUE TITLE
Nature's compass not working

### ISSUE THREAD

**Issue by SeaSaltStar** [NillerMedDild/Enigmatica6#1105]
**Modpack version**
0.3.7 Onward
**Describe the bug**
The nature's compass does not lead the player to a warped forest. I have not tested any other biomes.
**Screenshots**
https://cdn.discordapp.com/attachments/802988228688609330/804083656456929399/2021-01-27_15-20-39.mp4

**Comment by SeaSaltStar** [comment]
I have also confirmed there is warped forests and it is not an issue with the biome not generating.

**Comment by NillerMedDild** [comment]
Does your world happen to have sharp borders between biomes in the nether?

**Comment by SeaSaltStar** [comment]
Could you define sharp borders please

**Comment by NillerMedDild** [comment]
![Uploading billede.png…]()

**Comment by SeaSaltStar** [comment]
There is what I would consider abrupt biome changes but thing similar to the image provided. 
![image](https://user-images.githubusercontent.com/37715497/106058174-e65f7380-60be-11eb-9cf5-15a0c31acfdf.png)

**Comment by NillerMedDild** [comment]
Alright that looks normal I think. Would you mind sending me your `level.dat` file?

**Comment by SeaSaltStar** [comment]
I'll have beaker send it.

**Comment by GarethCarew** [comment]
[level.dat](https://drive.google.com/file/d/183xtJ-56afGkaxbeQrOvvBaUZmnbrSVW/view?usp=sharing)

**Comment by NillerMedDild** [comment]
My guess is that both /locatebiome and the Nature's Compass are thrown off by the byg dimension type, will relay.

**Comment by NillerMedDild** [comment]
Actually, can't reproduce, not sure what to make of this.

**Comment by NillerMedDild** [comment]
Did you add any mods yourself?

**Comment by GarethCarew** [comment]
I only have Crash Utils and Mc2Discord, so nothing should affect it.

**Comment by NillerMedDild** [comment]
Dammit :P

**Comment by GarethCarew** [comment]
I'm not sure if my newer sever has the same issue but, my guess it has something to do with the fact that it's an older server, but other than that I'm out of ideas.

**Comment by NillerMedDild** [comment]
Can't reproduce this still, would it be alright with you if we chalk this up as old world weirdness and call it a day? :P
