### ISSUE TITLE
Click Machine lacks a recipie

### ISSUE THREAD

**Issue by TheAdamizer** [NillerMedDild/Enigmatica6#111]
**Modpack version**
0.2.5 + Rats

**Issue**
Click machine has no recipe

Maybe this is intentional (but I couldn't see any commits indicating as such) but I noticed Click Machine was added but there isn't currently a recipe for it.  After some investigation, it looks like there is a vanilla recipe that isn't working correctly.

**Comment by NillerMedDild** [comment]
We've found the cause of this issue and are working to resolve it, thanks for letting us know anyhow :)

**Comment by TheAdamizer** [comment]
Not sure where you are on your investigation, but I tried to debug the missing recipe a bit:  I'm able to reproduce the issue simply installing kubejs alongside click machine in an otherwise vanilla forge instance.  Debug log doesn't seem to indicate anything wrong with how ClickMachine is starting up outside of that.
