### ISSUE TITLE
Mekanism Oredictionifcator Doesn't Appreciate Certain Tags

### ISSUE THREAD

**Issue by r-mc2** [NillerMedDild/Enigmatica6#1110]
**Modpack version**
v0.3.6

**Describe the bug**
I do realize this is an older version of the pack, but in awaiting the eventual fallout of the Forge fun in v0.3.10 I'm trying to work around a few of the recipe bugs that I believe were fixed in later additions I wanted to make some IE copper wires in the Thermal press with the wire die (2 ingots for 1 wire, another issue I think was solved in 0.3.8). However, the recipe currently set only accepts Tinkers Mechworks copper at this version. So, I went to Mekanism's Oredictionifcator to swap some EE copper ingots to Tinkers' ingots, applying the tag filter `forge/ingots:copper` results in a `ResourceLocationException` due to a:
```
net.minecraft.util.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: forge/ingots:copper
```
Probably a Mekanism problem in not sanitizing inputs. But figured I'd report it here as it may have more traction coming from one of you fine pack authors 😉.

I should note this was on a server and resulted only in a client-side crash. Server chugged along just fine.

**Comment by MelanX** [comment]
The exception says that you used a character which isn’t something between a-z or 0-9 or _.-
Did you maybe type a space at the ending of the tag name? Because everything else looks fine.

**Comment by r-mc2** [comment]
I'm thinking it's because I derped up and swapped the `:` and the `/` in the correct Forge Tag format:

i.e. I typed `forge/ingots:copper` whereas the correct format is `forge:ingots/copper` although I feel a full-on client crash for something like that is rather severe and felt it worth the report.

**Comment by MelanX** [comment]
Oh true, it’s swapped :D But yes, a crash for this should be fixed.
