### ISSUE TITLE
Travel anchor oddity

### ISSUE THREAD

**Issue by SeaSaltStar** [NillerMedDild/Enigmatica6#1111]
**Modpack version**
0.3.10 And prior not sure what patch I noticed this
**Describe the bug**
Either the teleportation enchant is bugged and allows travel to anchors outside of range, or the label breaks after a certain range.

**Screenshots**
https://cdn.discordapp.com/attachments/621124399130476544/804241610669817866/2021-01-28_01-48-43.mp4

**Comment by NillerMedDild** [comment]
Thanks for the report. Any idea how far apart these two are?

**Comment by NillerMedDild** [comment]
Relayed here: https://github.com/castcrafter/travel_anchors/issues/13
