### ISSUE TITLE
autocrafting energizing rods could be easier (powah)

### ISSUE THREAD

**Issue by boneskull** [NillerMedDild/Enigmatica6#1112]
**Description**

Once you've powered an Energizing Rod, it appears Powah's lib (lollipop) assigns some NBT data to it.  This NBT data prevents RS from recognizing the rod as a valid recipe item.  For example, if I had a Basic Energizing Rod and wanted to make a Hardened Energizing Rod, attempting to automate crafting will cause a _second_ Basic Energizing Rod to be created; RS will not use the Basic Energizing Rod as the recipe item to craft the Hardened Energizing Rod.  You will end up with both rods.  

Note that completely discharging the rod first does _not_ work--it's still got some extra data. 

I think certain modules from Modular Routers also suffer from this issue.

**Why would you like this added/changed?**

It seems like it should work, but it doesn't.  :smile:  It can be tedious, since it affects every tier of rod.

ATM6 has a recipe where you craft an energizing rod _with itself_ which gives you a fresh rod w/ no NBT.  I don't know how that was implemented, but it seemed to work. 

**Workaround**

Craft them manually. 😝

**Comment by Merlo17** [comment]
While the recipe might be useful to implement, a cleaner fix would probably be to take a rod with the NBT and place it manually in the pattern, instead of using the one generated from JEI. A bit annoying to do at first but it should work after that

**Comment by Darkere** [comment]
Mekanism has somewhat recently fixed this issue. So getting the two devs in contact would be an option. 

The benefit of the additional recipe is that you do not need to have the item on hand to make the pattern for the item. A significant time saver.

**Comment by Merlo17** [comment]
Fixing that in the mod would definitively be the best option, not sure if you know the devs Darkere, but I'd leave getting them in contact up to you ;P

**Comment by boneskull** [comment]
Thanks; I’ll try _not_ refilling from JEI—didn’t know that was a thing. Having to craft one beforehand is better than nothing.

**Comment by Spongman** [comment]
yeah, something is broken. i'm playing enigmatica 6 and it's impossible to make a RS pattern that crafts hardened energizing rods: it just keeps saying that the basic rods are missing even though i have a bunch in my storage.

**Comment by NillerMedDild** [comment]
> While the recipe might be useful to implement, a cleaner fix would probably be to take a rod with the NBT and place it manually in the pattern, instead of using the one generated from JEI. A bit annoying to do at first but it should work after that

**Comment by Spongman** [comment]
doesn't work. i have tried both from JEI and manually. none of the reipes work.

**Comment by NillerMedDild** [comment]
I see it now I think - JEI is pulling in an Energizing Rod (Starter) for the recipe somehow. Setting hte Energizing Rod to be a Basic one fixes the issue.

**Comment by Spongman** [comment]
that's not what i'm seeing. i think my pattern is right:
![Uploading image.png…]()

**Comment by NillerMedDild** [comment]
Please reupload that image :)

**Comment by NillerMedDild** [comment]
May I see the Crafting Preview?
The recipe in that Pattern does not match any recipe in my instance, which version are you on?
