### ISSUE TITLE
Ars nouveau - Worn notebook not working (Server)

### ISSUE THREAD

**Issue by Sceptorrh** [NillerMedDild/Enigmatica6#1114]
**Version**
Enigmatica 6 ep6 - 0.3.9 running on server
Tested it on a local world and have no problems there.

**Describe the bug**
Unable to use the worn notebook, 90% of pages are empty
I tried reinstalling the modpack and to craft a new notebook. None of which helped.

**Logs**
https://pastebin.com/kqpymYde

**Screenshots**
![20210128_130143](https://user-images.githubusercontent.com/31596459/106136520-b7520c00-6169-11eb-9e86-15b1caf0276a.jpg)
![20210128_130153](https://user-images.githubusercontent.com/31596459/106136528-b91bcf80-6169-11eb-9bfa-26c1a02a87a9.jpg)

**Comment by Darkere** [comment]
Using optifine?

**Comment by NillerMedDild** [comment]
Same issue as #1050, download a fresh set of server files and replace your kubejs with the kubejs folder from the fresh copy :)
