### ISSUE TITLE
Potassium Nitrate Chunk gives itself when in crafting grid

### ISSUE THREAD

**Issue by soepie7** [NillerMedDild/Enigmatica6#1116]
**Modpack version**
E6 0.3.9

**Describe the bug**
While all ore chunks give the ore block when put in the crafting grid, Potassium Nitrate Chunk gives Potassium Nitrate Chunk instead of Potassium Nitrate Ore (but it is doable with a stonecutter).

**Screenshots**
![image](https://user-images.githubusercontent.com/21133200/106151947-31d85700-617d-11eb-99f8-3daa5ab648a6.png)

Edit: Fluorite Chunks have the same issue, and other chunks that worked (vanilla ores, sulfur, cinnabar, and bitumen) give the gabbro version of the ore, not the default stone version.

**Comment by NillerMedDild** [comment]
Thanks for the report, will relay to the mod author......

@Ridanisaurus EE bug for you here good sir!
