### ISSUE TITLE
Refactor Insolator, Botany Pots and Cloche recipes for easier balancing. 

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#1118]
Refactor Insolator and Cloche recipes for easier balancing.

**Comment by NillerMedDild** [comment]
#1152 
#1153
#1160

**Comment by MuteTiefling** [comment]
ah, thanks for linking them in

**Comment by MuteTiefling** [comment]
Getting close on this, by the way. Have the basic data structure created and populated, I'm just stumbling on the best way to implement the actual functions. BotanyPots and Insolator are done though.  Cloche is next.

**Comment by NillerMedDild** [comment]
Awesome!

**Comment by MuteTiefling** [comment]
I believe this is all set. There's a conflict I can't seem to see to fix, but that's probably due to the script moves we're doing.
