### ISSUE TITLE
0.3.10 - Multiservo recipes for IE wire(copper, electrum, etc) only take Tinker's Mechworks ingots, not Enigmatica Ingots

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica6#1121]
**Modpack version**
0.3.10
**Describe the bug**
The Multiservo press will not use the unified ingots for the wire recipes.

**Logs**
N/A
**Screenshots**
[image](https://user-images.githubusercontent.com/10382598/106203228-13785880-6189-11eb-9c91-2cb57e1f0bbe.png)

**Comment by Trostmm** [comment]
Seems to be at least partially similar to the issue they were trying to resolve in
https://github.com/NillerMedDild/Enigmatica6/issues/1110

**Comment by r-mc2** [comment]
Yep, that is what I was trying to work around. As I'm still on v0.3.6 (awaiting the Forge fix in v0.3.10) I'm curious if the recipes are still asking for 2 ingots for 1 wire or if that was correctly reversed by v0.3.10 to be in line with what the IE press gives?

**Comment by DarkAngel22579** [comment]
Yep still says two ingots to one wire. And adding on to this issue, none of the Multiservo press wire recipes accept EE ingots.

**Comment by NillerMedDild** [comment]
Will be fixed in 0.3.11, which will be released tomorrow (~24hours from now)
![billede](https://user-images.githubusercontent.com/21295394/106207475-1e9baa80-61c2-11eb-8c4d-aa8871eb1def.png)

**Comment by Merlo17** [comment]
aw did you fix this niller? I was about to PR it :P

**Comment by NillerMedDild** [comment]
Aw sorry, want me to discard? :P didn't commit yet or anything

**Comment by Merlo17** [comment]
I committed, might as well finish up the job ^^
