### ISSUE TITLE
Mod Suggestion: Torch Slabs Mod

### ISSUE THREAD

**Issue by Angular-Angel** [NillerMedDild/Enigmatica6#1123]
**https://www.curseforge.com/minecraft/mc-mods/torchslabs-mod**

**This mod allows you to put torches and lanterns on and beneath slabs. Nothing huge, but it adds some nice flexibility around using slabs in your builds, and still being able to put light sources on them.**

**Comment by NillerMedDild** [comment]
Nope, we removed this from E5 because it was annoying to torch everything you clicked instead of opening the GUI :P
