### ISSUE TITLE
Lexica Botania is not able to be traded

### ISSUE THREAD

**Issue by SeaSaltStar** [NillerMedDild/Enigmatica6#1126]
**Modpack version**
0.3.10
**Describe the bug**
The Lexica Botania cannot be traded through the Elven portal. The item instead disappears
**Screenshots**
https://cdn.discordapp.com/attachments/802988228688609330/804558732053708800/2021-01-28_22-48-28.mp4

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Cannot reproduce, the book popped out on the other side though. Could that be the issue?

**Comment by SeaSaltStar** [comment]
Not sure where they would be popping out to, not sure if I included the right clip but I did walk around the portal, and put on a magnet ring.

**Comment by NillerMedDild** [comment]
Hmm.. Maybe try without the magnet - Perhaps the new book was getting sucked back into the portal.

**Comment by SeaSaltStar** [comment]
https://cdn.discordapp.com/attachments/802988228688609330/804985024138575904/2021-01-30_03-02-27.mp4

**Comment by Merlo17** [comment]
I also tried, can't reproduce. Working fine for me on both SP and server
