### ISSUE TITLE
Refined Storage Fluid Grid not shown in JEI

### ISSUE THREAD

**Issue by willcheat** [NillerMedDild/Enigmatica6#1127]
**Modpack version**
0.3.10

**Describe the bug**
Searching for "@ref fluid grid" in JEI returns no result. 

The fluid grid was likely removed from JEI in 0.3.10 when the colored grids were also removed.

**Comment by Merlo17** [comment]
Will be fixed in next release ^^

**Comment by willcheat** [comment]
❤
