### ISSUE TITLE
Cave Root recipe (Quark Tortoises)

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#113]
Was wondering if it was possible to pull this from E5 as I haven't seen a recipe for them yet. If it was already in the works or is in 0.2.5 and I'm being dumb, I apologize for making an issue about it! Thank you in advance :) 
https://github.com/NillerMedDild/Enigmatica5/issues/414

**Comment by NillerMedDild** [comment]
Already fixed good sir :)
