### ISSUE TITLE
Some Eidolon recipes hidden in JEI on servers

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica6#1130]
**Modpack version**
dev

**Describe the bug**
Just like the title says, examples are

- arcane gold
- wicked weave
- calx of end
- lesser soul gem
- sprouting fungus
- the belt items
- glass hand

might be even more I didn't catch. I can confirm in dev with a SP world the recipes are showing up correctly, and also in SP with an eidolon only instance. I'm looking into it but I'm honestly not sure where to look, so I'll leave this here as well. I've noticed all of the items missing have either crucible or magic worktable recipes, all custom crafting mechanics by eidolon

**Comment by r-mc2** [comment]
Is it potentially something similar to what Niller mentioned in #1097 in this [comment here](https://github.com/NillerMedDild/Enigmatica6/issues/1097#issuecomment-768601397)?

**Comment by Merlo17** [comment]
It doesn't look like the same type of issue but I've also been wrong in the past :P

**Comment by NillerMedDild** [comment]
This is most likely caused by JEI: https://github.com/mezz/JustEnoughItems/issues/2217
