### ISSUE TITLE
Occultism Crafting errors

### ISSUE THREAD

**Issue by SeaSaltStar** [NillerMedDild/Enigmatica6#1131]
**Modpack version**
0.3.10
**Describe the bug**
I've noticed this issue on more than just this item, but when attempting to fill a recipe with JEI for certain Botania items this error pops up.
**Screenshots**
![image](https://user-images.githubusercontent.com/37715497/106315066-ade3a500-6238-11eb-9d1d-493b114f36f0.png)

**Comment by SeaSaltStar** [comment]
This occurs with the actuator and storage accessor, my apologies for not clarifying initially.

**Comment by theboo** [comment]
https://github.com/klikli-dev/occultism/issues/155#issue-797112280 klikli is looking in to it rn

**Comment by theboo** [comment]
mod should be updated shortly
