### ISSUE TITLE
Huge tick use from storagedrawers <-> refinedstorage

### ISSUE THREAD

**Issue by clienthax** [NillerMedDild/Enigmatica6#1136]
**Modpack version**
0.3.9

**Describe the bug**
When connecting refined storage exporters to storage drawers slaves, there is considerable tick usage by item lookups, causing a hefty tps drop.
Removing the exporters resulted in everything going back to running smoothly.
Setup in question was around 16 exporters into slave units.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![image](https://user-images.githubusercontent.com/1056270/106330370-03d93c80-627b-11eb-8a46-6ce05d982c78.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. We're sadly aware that RS and Storage Drawers do not play well together. It will most likely not be fixed, as Storage Drawers isn't very actively maintained. I recommend you use other alternatives, such as Mekanism Bins.

**Comment by r-mc2** [comment]
Would this be an acceptable place to ask about other SD<-->RS oddities?

Every time I reboot my server I have to break and replace my external storage bus on the drawer controller to get the RS system to see the drawer "wall". Would this be related to the lack of playing well together? Or maybe just a race condition of chunks loading? Or RS "booting" before the drawer controller does, so it reports "nothing"?

**Comment by NillerMedDild** [comment]
That is this issue: #976

**Comment by telemenar** [comment]
I've half considered trying to develop some sort of add on for RS/AE and Drawers to also fix the weirdness with their interaction with compressing drawers.

**Comment by NillerMedDild** [comment]
It does not. We've discussed removing Storage Drawers entirely in the past, but ended on keeping it.

**Comment by NillerMedDild** [comment]
Closing this, there's nothing we can do 😞
