### ISSUE TITLE
Master Issue for Quest Typos

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1139]
If you stumple upon a typo in our quests / jei descriptions and the like, please add a comment below to let us know. Screenshots are very welcome.

Note: If this issue becomes very large, 50+ comments for example, I will trim the fixed comments.

We appreciate the help! :)

**Comment by r-mc2** [comment]
In the Eidolon quest "Altar Upgrades", I'm pretty sure you meant `There are three different categories of upgrades` 😄 

![image](https://user-images.githubusercontent.com/36780233/106846301-9febb500-667a-11eb-8c16-d2b83aef7b35.png)

**Comment by Merlo17** [comment]
oof, that one's on me, fixed that up ty ^^

**Comment by natebc** [comment]
![image](https://user-images.githubusercontent.com/53818/107770748-e17a0100-6d07-11eb-9ca5-ab8da3598791.png)
This is the quest for small gears which my small brain has determined cannot in fact do the perpendicular trick. Large Cogwheel, yes. Cogwheel (small) no.

**Comment by MuteTiefling** [comment]
<.< oop

**Comment by MuteTiefling** [comment]
Opted to simply combine the two quests into one:

![image](https://user-images.githubusercontent.com/9543430/107774645-42f09e80-6d0d-11eb-907c-17e2bd582ba5.png)

**Comment by Skullmasta** [comment]
![2021-02-24_21 12 39](https://user-images.githubusercontent.com/50221101/109097524-20835b80-76e5-11eb-8f07-f369eeb5a61d.png)

Quest is unclear, and seems to suggest piping Liquid Lithium from the tower directly into Chemical Crystallizer, but you need to condensate it first so it becomes Lithium gas.

**Comment by wadeg-sait** [comment]
Nocturnal Powder quest quest description is bugged
![2021-02-25_21 20 13](https://user-images.githubusercontent.com/57008358/109254651-b1bf0480-77af-11eb-9f3f-80fead38cde3.png)
![2021-02-25_21 20 10](https://user-images.githubusercontent.com/57008358/109254653-b2f03180-77af-11eb-90ce-b3e7fea02dab.png)

**Comment by NillerMedDild** [comment]
Fixed in-dev, thanks :)

**Comment by Merlo17** [comment]
![109273619-6e30be80-77e0-11eb-8caf-0814487bbd4f](https://user-images.githubusercontent.com/62080872/109285887-e370b380-7821-11eb-94b9-e1bc271e85ed.png)

Happens here too

**Comment by MuteTiefling** [comment]
Both of those should already be fixed in Dec

**Comment by LaurentRivard1** [comment]
Pretty sure you meant "capable" instead of "cable" in the IF black hole quest. Every type of unit/tank has this typo.

![Quest_typo_E6](https://user-images.githubusercontent.com/79711324/109323402-6a715c00-7821-11eb-8dcc-159805e086e7.png)

**Comment by KrAzYGEEK32** [comment]
tetra stone hammer quest seems to check for the craft rather than the final item, this is redundant now as you can make a stone hammer in a crafting table, which doesnt complete the quest.

**Comment by NillerMedDild** [comment]
Finally figured out how to get around that, thanks for the reminder @KrAzYGEEK32 :D

**Comment by NillerMedDild** [comment]
Scratch that, the quest is unchanged. I use advancement triggers as FTBQ isn't able to detect NBT properly on items.

**Comment by MuteTiefling** [comment]
Note to self: Create quest for Clutch has no reward

**Comment by ochotonida** [comment]
Found a typo in the Schematicannon quest.
(On a related note, it would be nice to have a quest explaining The Mighty Architect)
![image](https://user-images.githubusercontent.com/37985539/110517208-d9489200-810a-11eb-86c8-228389479c2f.png)

**Comment by TemperedFool** [comment]
You've got me beat by not much - just fixed that in dev now! I'll also take a look at learning Mighty Architect well enough to write a quest about it, once I'm through with Pedestals.

**Comment by NillerMedDild** [comment]
Ah damn, sorry :P Thanks!

**Comment by Rodg88** [comment]
The powah ender gate quest says it takes up the same block space as the cable it's attached to, but it doesn't, it uses its own block space

**Comment by Xynariz** [comment]
I recently started a playthrough of Enigmatica 2: Expert, on version 1.82a, and I noticed a few things that were either inaccurate or gramatically incorrect in the quest book.  These are certainly not game-breaking issues.
* In the very first "Welcome" quest, the phrase "I advice that you automate" should be "I advise that you automate", since advise is a verb and advice is a noun.
* Also in the very first quest, "starterkit" should be "starter kit".
* The quest book states that the default keybind for OreExcavator is `GRAVE`, when it is in fact `BACKSLASH`.

I'm excited to start playing the pack!  Thanks for putting this pack together; it's still attracting new players (such as myself) years after its creation!

**Comment by Anthony6444** [comment]
![image](https://user-images.githubusercontent.com/59541967/115089087-2cb2ba80-9ed7-11eb-9297-ae071eafbf8e.png)
lithium quest, pretty sure you meant something along the lines of: 

> Before moving on, *please note* that...

**Comment by MuteTiefling** [comment]
Nah. That's quite intentional.

**Comment by Anthony6444** [comment]
oops
