### ISSUE TITLE
Middle click sorting inside Crafting Manager deletes patterns from Refined Storage

### ISSUE THREAD

**Issue by jjspace** [NillerMedDild/Enigmatica6#1140]
**Modpack version**
0.3.9, we are on a server

**Describe the bug**
We lost a ton of our patterns and weren't sure why. A short time later one of us accidentially middle click sorted within the Crafting Manager and we watched it delete a bunch of our patterns so that seems to be the cause.

**Comment by NillerMedDild** [comment]
Hmm, I thought I fixed this a long time ago, I'll have a look :)

**Comment by NillerMedDild** [comment]
I can't reproduce this - There's some odd behaviour, but items aren't being deleted for me. However, I will turn it off entirely inside that block :)

**Comment by NillerMedDild** [comment]
Hmm, I can't turn it off for some reason. Can you provide steps to reproduce the issue?
