### ISSUE TITLE
cannot craft most colored redstone-sensitive blocks from gauges & switches

### ISSUE THREAD

**Issue by boneskull** [NillerMedDild/Enigmatica6#1141]
**Modpack version**

v0.3.9

**Describe the bug**

You can create a white colored redstone-sensitive block using cyan--but you are unable to craft (via filling from JEI or using crafting tables) any of the other colors.  

The mod [should allow anything with a tag of `forge:dyes`](https://github.com/stfwi/rsgauges/blob/1.16/src/main/resources/data/rsgauges/recipes/sensitiveglass/stained_sensitiveglass.json), but only cyan is allowed (and it results in a white block, which is weird).  

**Screenshots**

![image](https://user-images.githubusercontent.com/924465/106343560-da101d80-625a-11eb-93ab-a69d9b8ce680.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
The recipe only accepting cyan was my mistake, reported the color issue here: https://github.com/stfwi/rsgauges/issues/40

**Comment by NillerMedDild** [comment]
There simply aren't colored variants, the fact that it accepts any dye is just a bit misleading, it will be changed to white only :)
