### ISSUE TITLE
Industrial foregoing issues after update to v0.3.11

### ISSUE THREAD

**Issue by Tyqhoon** [NillerMedDild/Enigmatica6#1145]
**Modpack version**
v0.3.11

**Describe the bug**
After updating server from v0.3.7 some Industrial Foregoing blocks appear with missing texture and cause client side crash when destroying the block. Machines still appear to work and interface can be accessed with right click.

Used JEI to give replacement machine after restarting client, same problem encountered. Fluid extractor, item placer, animal feeder all missing texture. Latex processing unit and dissolution chamber textures correct. All textures appear correct in inventory. Breaking animal feeder results in crash, while fluid extractor does not.

**Logs**
https://pastebin.com/CXLPiBQP

**Comment by olleman42** [comment]
I can confirm the texture issue - I haven't dared remove any machines though.
![image](https://user-images.githubusercontent.com/342185/106353211-29049400-62e9-11eb-871f-985548d92005.png)

**Comment by Merlo17** [comment]
@Buuz135 what did you do

**Comment by Buuz135** [comment]
If someone grabbed the latest versions this wouldnt be a problem 👀

**Comment by Merlo17** [comment]
Blame Curse then, not us c.c

**Comment by natebc** [comment]
I was in the same state. Breaking the machine crashed my client.
Updating IF and titanium to current versions seems to have fixed this.
```
industrial-foregoing-1.16.5-3.2.9.1-fbef27c.jar
titanium-1.16.4-3.2.5.jar
```

**Comment by Buuz135** [comment]
> 
> 
> Blame Curse then, not us c.c

I'm not blaming anyone.... weeell I blame CF a lil
