### ISSUE TITLE
Astral Sorcery Mineral Enrichment Perk can turn most stones into ores

### ISSUE THREAD

**Issue by BlackFlameMN** [NillerMedDild/Enigmatica6#1147]
playing on version 0.3.6 just before the new version came out, not sure if this has been seen or fixed yet

in astral sorcery, one of the perks in the aevitas path called "mineral enrichment" turns stone around the player into random ore at the cost of personal starlight. the problem comes from the fact that all stone types in enigmatica are considered open for ore. this shouldn't be a problem on paper, but the way it is implemented means that chiseled variants and other stone-like materials that could never have ore in them turn to ore anyway. I found this out the hard way as instead of turning jasper and stone blocks harmlessly into ore, i watched as it tore apart my astral multiblock structures made of chiseled marble, and my house made of polished granite. I definitely consider this a bug and think it should be fixed, maybe just add a filter specifying what stone can generate ore in the first place if you can. 
also a small minor note, but each time it turned a stone into an ore it chose a completely random stone type to place it in, plaguing normal looking caves with weird patches of nether and end ore for no reason. not as important, but if you can get to finding which block was replaced and placing an ore in that same type of stone, that would be another thing to think about.

sorry if i dont have any logs or screenshots, but nothing crashed. its not really an instability with the game, just an oversight with two specific mechanics.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Do you happen to know if this is still an issue on v0.3.13?

**Comment by BlackFlameMN** [comment]
i dont, but i can look into it. i would imagine if nothing happened to as since v0.3.6 then i would imagine it would still be broken, but thats just speculation.

**Comment by BlackFlameMN** [comment]
alright, from what i have gathered, it it still there.
![2021-02-15_00 06 25](https://user-images.githubusercontent.com/78265625/107911282-da2e3f80-6f21-11eb-9d04-8032d0743bbc.png)
this first screenshot shows the blocks i chose to do testing with, choosing them because they cannot have ore in them naturally and should not turn into ore.
![2021-02-15_00 14 31](https://user-images.githubusercontent.com/78265625/107911766-cdf6b200-6f22-11eb-8470-eeb634b9fe43.png)
this second one shows progress of my tests. i have decided to do the test in the air to only expose these blocks to the perk to remove variables. one polished jasper was converted to bitumin or in gravel (which is now floating interestingly), both marble bricks converted to ore, and one marble arch.

**Comment by BlackFlameMN** [comment]
continued more extensive testing with a wider block palette to understand just how many mods are affected by this.
![2021-02-15_00 45 23](https://user-images.githubusercontent.com/78265625/107914061-43648180-6f27-11eb-964c-d5f01b16382c.png)
 from left to right i now have livingrock from botania, vanilla cut sandstone, fancy gabbro bricks from create, sooty marble bricks from as, chiseled marble from as, marble pillar from as, vanilla prismarine bricks, red nether bricks, polished basalt from embellishcraft, vanilla bricks, vanilla stone bricks, polished jasper from quark, vanilla polished granite, marble brick from as, marble arch from as, sooty marble from as, runed marble from as, smooth basalt, slate, marble, gneiss, and jade from embellishcraft, cut stone from masonry, diorite small bricks from masonry, magma bricks from quark, polished blood stone from bloodmagic, dacite tile from biomes youll go, white chiseled sandstone from biomes youll go, and cracked shiverstone bricks from the undergarden. i know its a long list but i wanted to cover bases and see how much needs to be done.
 
![2021-02-15_01 01 31](https://user-images.githubusercontent.com/78265625/107915088-609a4f80-6f29-11eb-9f6a-5f3b3b6f6391.png)
i have been converting ores for about an hour now, so this should be pretty accurate results.
of the blocks present, all of the non-sooty as marble blocks, the polished blocks from quark, vanilla polished granite, and the cut stone from masonry all turned into ore even though all of the blocks are cut or chiseled and shouldnt be able to be converted.

**Comment by theboo** [comment]
It seems to be able to convert anything with the forge:stone tag..  tested in dev on all the astral marble variants and they all seem to convert
