### ISSUE TITLE
ore dictionary biomes youll go wood and planks

### ISSUE THREAD

**Issue by BlackFlameMN** [NillerMedDild/Enigmatica6#1148]
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go

you know the one. all of the biomes are great, but the wood only works aesthetically. barely any crafting recipes can use the wood or planks, you can't even make chests with them!

**Comment by NillerMedDild** [comment]
I have a guess, but why did you close this issue?

**Comment by BlackFlameMN** [comment]
been fixed
