### ISSUE TITLE
[Mod Suggestion] Simple Planes

### ISSUE THREAD

**Issue by SQbuilder** [NillerMedDild/Enigmatica6#115]
https://www.curseforge.com/minecraft/mc-mods/simple-planes

Old school wooden biplanes, reminiscent of the biplane from the "Ye Olde Pack" from Flan's Mod. These planes are furnace-powered and are upgradable. There is currently support for the modded wood-types of Biomes O Plenty.

Having additional transportation options is always nice, especially one that can be obtained rather early.

**Comment by NillerMedDild** [comment]
Hmm, I don't know, I'm always hesitant to add entity-based transport mods, I've been burned before :P

**Comment by NillerMedDild** [comment]
I'm going to pass on this, sorry.
