### ISSUE TITLE
Undergarden mushrooms can't be placed in Deepsoil in Botany Pots

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#1151]
**Modpack version**
0.3.11

**Describe the bug**
The 4 Undergarden Mushrooms (Blood, Indigo, Ink, Veiled) say in JEI that they can be planted in Botany Pots using Deepsoil, among other blocks. However in game they can't be planted in pots with Deepsoil. Using Depthrock (which is also in the list of soils shown in JEI) works fine.

I don't know if the correct behavior should be making them plantable in pots with Deepsoil or removing Deepsoil from that list.

**Screenshots**
![image](https://user-images.githubusercontent.com/8684850/106367497-4ebe8700-6343-11eb-983b-b2e358cebab3.png)

**Comment by MuteTiefling** [comment]
I _think_ this is fixed in 0.4.0, but I did forget to test it specifically in that instance will retest once the other changes can be merged.

**Comment by NillerMedDild** [comment]
All good :D
