### ISSUE TITLE
Deepsoil Farmland can't be crafted like other Farmlands

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#1152]
**Modpack version**
0.3.11

**Describe the bug**
Vanilla Farmland and Rich Soil Farmland can both be crafted using a hoe in a crafting table, but Deepsoil Farmland can't. This is mostly an issue because Gloomgourds can only use those as soil in Botany Pots (according to JEI).

EDIT: It's obtainable via silk touch BUT the Gloomgourd can't be Botany Potted with it.

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed.
