### ISSUE TITLE
Gloomgourd can't be cultivated in Botany Pots

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#1153]
**Modpack version**
0.3.11

**Describe the bug**
Gloomgourd can't be planted in Botany Pots with Deepsoil Farmland soil despite JEI saying it can be (and also not showing any other soil for it).

**Screenshots**
![image](https://user-images.githubusercontent.com/8684850/106367663-87129500-6344-11eb-8772-49cb402024e1.png)

**Comment by MuteTiefling** [comment]
It's on my list. This stuff is all getting reworked.

**Comment by MuteTiefling** [comment]
This is fixed in 0.4.0
