### ISSUE TITLE
ars noveau machine jitter issue

### ISSUE THREAD

**Issue by boneskull** [NillerMedDild/Enigmatica6#1155]
**Modpack version**

1.3.9

**Describe the bug**

Graphical jitter on several Ars Noveau machines; see baileyholl/Ars-Nouveau#163

Guessing it's a bad interaction somewhere.  Wonder if anyone else can reproduce...

**Screenshots**

Video in linked issue

**Comment by NillerMedDild** [comment]
I cannot reproduce this, I suspect it was fixed in `ars_nouveau-1.16.4-1.11.3`
