### ISSUE TITLE
Bad ordering on early Occultism quests

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#1156]
**Modpack version**
0.3.11

**Describe the bug**
The 5th quest in the Occultism quest line is the one that introduces Spirit Fire and asks for Spirit Attuned Gems. However, both the Divination Rod (quest 3) and the Impure White Chalk (quest 4) require materials that can only be obtained from Spirit Fire to be crafted (Spirit Attuned Gem and Otherworld Ashes).

It would make more sense for Spirit Fire to be presented before those 2 items as it's currently required to craft them. Though it might need adjustments on what items it asks then.

**Screenshots**
![image](https://user-images.githubusercontent.com/8684850/106368115-96471200-6347-11eb-9e7f-d75d04fd9ccb.png)

**Comment by Merlo17** [comment]
This is @theboo territory

**Comment by theboo** [comment]
ope... ill look at it this evening xD thanks for the feedback!

**Comment by theboo** [comment]
should be fixed in next release!
