### ISSUE TITLE
Reproducible crash with Backtools and Seals

### ISSUE THREAD

**Issue by TheCurle** [NillerMedDild/Enigmatica6#1158]
**Modpack version:** 0.3.11

**Describe the bug:**

On our server, if someone joins facing toward me while I am facing away, they crash instantly.  
It appears this is due to Backtools trying to render something strange on my back, and the Seals player renderer not knowing how to deal with this.  
It can only be fixed if I leave the game, or if the other person disables Backtools.  
If i leave the game, they join and turn around and I re-enter, they are okay until their game tries to render whatever is on my back, and then they immediately crash.  
We can reliably reproduce this problem on four computers. All of them crash instantly.  

The issue does not manifest in single player, not even in the inventory or in third person.

Note also that it crashes even when there is literally nothing in my inventory.

**Logs**
https://paste.gemwire.uk/view/raw/ce6f561d

**Comment by NillerMedDild** [comment]
Removed Back Tools as  a temporary fix.
