### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by RemcoMusic** [NillerMedDild/Enigmatica6#1159]
**Modpack version**
0.3.11
**Describe the bug**
We have a server with several friends and If a friend joins and goes into his base and stays there for a little time or does something there the server crashes. We think it is the chunk he is in with a faulty item but we can't tell which.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
Error log: https://pastebin.com/vhSWydFV

**Screenshots**
None

**Comment by Merlo17** [comment]
Please update to 0.3.13
