### ISSUE TITLE
Osmium can't be made into Osmium Dust in the AE2 grindstone

### ISSUE THREAD

**Issue by mrDLSable** [NillerMedDild/Enigmatica6#116]
**Modpack version**
0.2.5

**Issue**
I expect to be able to crush Osmium ore into Osmium dust in the AE2 grindstone, seeing as it is possible to grind it using other methods, such as the ore crushing hammer from IE.

**Comment by NillerMedDild** [comment]
Fixed in next update, thanks for the report :) #109
