### ISSUE TITLE
IE Garden Cloche does not accept Phyto-grow 

### ISSUE THREAD

**Issue by wadeg-sait** [NillerMedDild/Enigmatica6#1160]
**Modpack version**
3.13
**Describe the bug**
The IE Garden Cloche will not accept phyto-grow as a fertilizer

**Comment by NillerMedDild** [comment]
Thanks for the report, we will get that added :)

**Comment by MaxFirestorm** [comment]
Last I checked (admittedly a couple of versions ago) it also doesn't accept the IF fertilizer either.
