### ISSUE TITLE
Apotheosis armor refuses to be trashed.

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1162]
Enigmatica 6 0.3.13 (Official E6 server)

When I try to delete this armor with the inventory trash slot, it 'dupes' itself into the world as soon as I close my inventory (i.e. shows up still in the trash slot, but also drops into the world as an item.  Replicated repeatedly for this item, but does not replicate with other Apotheosis armor that I have or non-apotheosis stuff though, so not sure what the issue with this one is or how to recommend replicating the issue for testing.
![image](https://user-images.githubusercontent.com/9061144/106375412-68ff6180-6351-11eb-94c2-2f87b5083e1e.png)

**Comment by NillerMedDild** [comment]
Sounds like more info for #1093 :)
