### ISSUE TITLE
Ars Nouveau using mod specific mana gems

### ISSUE THREAD

**Issue by Tyqhoon** [NillerMedDild/Enigmatica6#1163]
**Modpack version**
v0.3.13

**Describe the bug**
Enchanting Apparatus recipe for Summoning Crystal requires Ars Nouveau Mana Gem Block and doesn't accept Emendatus Enigmatica Block of Mana Gems.

Crystallizer also produces Ars Nouveau Mana Gems while mining provides the generic gem.

**Comment by NillerMedDild** [comment]
We'll get that fixed, ty. You can exchange the two types with shapeless crafting for now.

**Comment by NillerMedDild** [comment]
> Crystallizer also produces Ars Nouveau Mana Gems while mining provides the generic gem.

Opened this issue about that: https://github.com/baileyholl/Ars-Nouveau/issues/166

Looking into the other issues now.
