### ISSUE TITLE
Diamond gear not craftable

### ISSUE THREAD

**Issue by Arkael** [NillerMedDild/Enigmatica6#1164]
0.3.13

diamond gear used in industrial foregoing recipes are not craftable
<details><summary>picture of gear</summary>
<p>
![gear](https://user-images.githubusercontent.com/141004/106380622-caf0b300-63b3-11eb-8133-00ab60c92bb3.jpeg)
</p>
</details>

**Comment by Merlo17** [comment]
You should use the Emendatus Enigmatica diamond gear. Is there some recipe that doesn't accept that?

**Comment by Arkael** [comment]
the same issue also applies to iron gear and gold gear, all from enigmatica, can craft cofh versions with recipes that used to make said gear in 0.3.9 version of the modpack

**Comment by Merlo17** [comment]
I can't reproduce this - playing in .13 I can craft the EE diamond gear just fine and it seems to me like IF recipes are using that one correctly. What are you trying to do specifically?

**Comment by Arkael** [comment]
this is on a server, just updated to 0.3.13, could be a snafu when it updated from 0.3.9, still can't see the recipe for them in jei, only applies for iron, gold and diamond gear from emandatus

**Comment by Arkael** [comment]
problem still persists after reinstalling server. i can craft thermals versions of the gears, though they are hidden in jei, and have to be manually put into the crafting table.

**Comment by Merlo17** [comment]
Try to replace your kubejs folder with one from a fresh install to make sure you have every script. In a fresh 0.3.13 instance I can't replicate this

**Comment by Arkael** [comment]
that helped, would seem that apex does not update that folder when you update the pack using their method
