### ISSUE TITLE
You can keep re-looting Lootr chests that are in minecarts.

### ISSUE THREAD

**Issue by Eneswar** [NillerMedDild/Enigmatica6#1165]
So Lootr chests that are in minecarts, you can loot them, close the window, and when you open again the same loot as respawned, and you can do this how ever many times you want.

Regular Loots chests, that are not in minecarts, are fine.

**Comment by Lartza** [comment]
https://github.com/noobanidus/Lootr/issues/13

**Comment by noobanidus** [comment]
This is fixed as on 0.0.4.15.
