### ISSUE TITLE
Botania Floating Hydrangea Deleted After Update

### ISSUE THREAD

**Issue by toothmonsterr** [NillerMedDild/Enigmatica6#1166]
**0.3.13**

**Describe the bug**
After updating to the latest version, floating hydrangeas from botania have been deleted from the world.

**Comment by Darkere** [comment]
IIRC the hydroangeas expire after some time. Any chance that's what happened?

**Comment by toothmonsterr** [comment]
That could be it, it was a report from one of my players.
