### ISSUE TITLE
Magic Feather and Angel Ring 

### ISSUE THREAD

**Issue by MissPotato** [NillerMedDild/Enigmatica6#1167]
**Description**
Use the Magic Feather in the Angel Ring's recipe. (And maybe a quest for both in the tools section.)  Maybe also include a potion of flight in the recipe. 

**Why would you like this added/changed?**
Personally, I feel like the Magic Feather is an amazing mod. Having creative flight tied to a small radius makes it useful for building and general QOL without breaking mods that are balanced around exploration. However, I feel like the angel ring really overshadows the angel ring for a multitude of reasons. Firstly, it not being tied to a beacon just makes it a craft-it and forget-it solution. Secondly, it has it's own special Curious spot, which saves it from conflicting with other very powerful charms. Thirdly, it's more well known, Magic Feather is a pretty unknown mod so players might not even know it exists. And lastly, it's easier to get, it's easy to get an elytra before even getting a full set of diamond gear.  

While all of these issues have individual solutions incorporating the magic feather in the angel ring fixes all of them at once and provides a bit of progression to creative flight, and makes the angel ring an upgrade.

**Comment by NillerMedDild** [comment]
Good idea, we will most likely be doing this - Thanks :)

**Comment by NillerMedDild** [comment]
Done! 
![billede](https://user-images.githubusercontent.com/21295394/108134170-fbc03000-70b5-11eb-88cf-780e6f015ce7.png)

**Comment by MissPotato** [comment]
Looks great!
