### ISSUE TITLE
Mod Suggestion: Quickstack

### ISSUE THREAD

**Issue by Angular-Angel** [NillerMedDild/Enigmatica6#1168]
**https://www.curseforge.com/minecraft/mc-mods/quickstack**

**Mod description**
This mod adds a couple buttons for stacking and dumping to chests - basically the same way that Quark used to in 1.12.

**Why would you like the mod added?**
Because I appreciated using Quarks quickstack back in 1.12 and I miss the feature.

**Comment by NillerMedDild** [comment]
I thought we had that already to be honest, will add it :)

**Comment by MissPotato** [comment]
It's already in the pack. Shift click the insert arrows. It's still from quark they just remade the icon.

**Comment by Angular-Angel** [comment]
I think that only works for when you;ve opened chests. Quickstack lets you just open your inventory and quickstack to all nearby chests. If you visit the quickstack page, it shows a conversation with the quark devs where they said they removed the functionality from quark and weren't gonna re-add it.

**Comment by MissPotato** [comment]
I forgot quark used to let you do it from your player inventory good call
