### ISSUE TITLE
It is a downgrade to put vanilla bees in tier 3 apiary, compared to tier 2

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1175]
**Modpack version**
0.3.8

**Describe the bug**
Vanilla honeycombs need 4 to make a block, Resourceful bees' need 9
T2 apiary makes 6 honeycombs, T3, 1 block

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
