### ISSUE TITLE
Minecart with chest able to dupe item in it.

### ISSUE THREAD

**Issue by hkpyro08** [NillerMedDild/Enigmatica6#1176]
**Modpack version**
0.3.13

**Describe the bug**
Minecart with chest can dupe the item inside it, and I able to take loot inside multiple time

here the video that I upload on YouTube
https://youtu.be/KJ1r2vo3wI0

**Comment by Merlo17** [comment]
Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/1165, thanks for the report though ^^

**Comment by hkpyro08** [comment]
i forgot to mention that i play LAN with my sister and my sister to can dupe the loot

**Comment by hkpyro08** [comment]
i forgot to mention that i play LAN with my sister and my sister to can dupe the loot
