### ISSUE TITLE
Infinite Farmland with RS Crafting Grid

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#1177]
**Modpack version**
E6 0.3.13

**Describe the bug**
The player is able to obtain infinite Farmland with RS Crafting Grid as the recipe does not consume the input dirt, or uses Hoe durability. It works correctly when using a Vanilla Crafting Table.

**Logs**
N/A

**Screenshots**
Video: https://drive.google.com/file/d/1MgRy8L9ZQ3d2ULCPUHOMrZjAIHJP7u4O/view?usp=sharing

**Comment by Darkere** [comment]
Not finding it but this is a duplicate. Fixed this for next version. Shift crafting should be working fine.
