### ISSUE TITLE
AS Crafting Starmetal dust with Starlight Infuser

### ISSUE THREAD

**Issue by FastHit** [NillerMedDild/Enigmatica6#1178]
**Modpack version**
0.3.13

**Describe the bug**
Starlight Infuse has 2 recipes for iron chunk(Iron Ingots and Starmetal dust), and everytime i used this recipe it output 3 iron ingot and not starmetal dust, making it impossible to get starmetal dust that way.

**Comment by NillerMedDild** [comment]
.. oh right. My bad :P
