### ISSUE TITLE
Mod Suggestion: Dwarf Coal

### ISSUE THREAD

**Issue by Angular-Angel** [NillerMedDild/Enigmatica6#1180]
**https://www.curseforge.com/minecraft/mc-mods/dwarf-coal**

**Mod description**
This mod adds the ability to break coal and charcoal into pieces that will cook precisely one item each.

**Why would you like the mod added?**
So I can cook individual items if I want to.

**Comment by NillerMedDild** [comment]
No thanks :) 
I suggest using Planks or Sticks.
