### ISSUE TITLE
Ars spells still a little wonky with other mods blocks. This time Resourceful bees with replace spell.

### ISSUE THREAD

**Issue by Flabort** [NillerMedDild/Enigmatica6#1181]
**Modpack version**
0.3.13

**Describe the bug**
I used the Ars spell Touch->Replace, with an Apiary Storage block in my hotbar, on a spruce planks. My client then froze up, and crashed out, but the server was unaffected.

**Logs**
https://gist.github.com/Flabort/50397672278c572909732e863b5376b3

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it here: https://github.com/Resourceful-Bees/ResourcefulBees/issues/142
