### ISSUE TITLE
Stonecutter plethora of same recipe

### ISSUE THREAD

**Issue by SeaSaltStar** [NillerMedDild/Enigmatica6#1182]
**Modpack version**
0.3.13
**Describe the bug**
The stonecutter & portable stonecutter seem to have a plethora of the same recipe for ore chunks. Haven't tested anything else yet.
**Screenshots**
https://imgur.com/a/Ouls3XU

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
