### ISSUE TITLE
Some villagers accept items that are not unified

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1187]
**Modpack version**
0.3.13

**Describe the bug**
It is not just Steel Ingots as in #280; It seems all IE villagers require IE items

 - Requires IE steel and aluminum rods instead of EE rods (Structural Engineer)
 - Requires IE slag instead of EE slag (Structural Engineer)
 - Requires IE coke instead of EE coke (Machinist)
 - Requires IE copper and aluminum instead of EE ingots (Machinist)

You can oredictionificator the ingots, but for the other items it is not possible

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I made an issue here requesting it, fingers crossed: https://github.com/BluSunrize/ImmersiveEngineering/issues/4629
