### ISSUE TITLE
Outfitter villager not obtainable?

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1188]
**Modpack version**
0.3.13

**Describe the bug**
Outfitter villager requires white banner for its profession, but I tried in Creative, surrounded the villager with white banners, and it still won't convert (they immediately convert to other professions)

**Screenshots**
![2021-02-02_18 59 24](https://user-images.githubusercontent.com/13237198/106585055-4441fe80-658a-11eb-8755-f01e3677e2a2.png)

**Comment by MuteTiefling** [comment]
It needs a banner made with a shader from IE.

**Comment by MuteTiefling** [comment]
Hrm, there might be something to this. I've tried banners made from every Banner Pattern provided by IE and the villager never picks it as a poi. All of the banner patterns are broken as well, just displaying a missing texture. 

Will have to test with just IE to see what happens. Might need reporting to them.

**Comment by MuteTiefling** [comment]
OK, so something in our pack is breaking the banner pattern. Fresh instance with just IE, Create, Mekanism, and JEI has no issues displaying them.

I still can't get the villager to take these banners as a POI, however.

**Comment by MuteTiefling** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/4627

**Comment by MuteTiefling** [comment]
Alright, to get your Outfitter Villager, you need to do the following:
1) Place down a banner on the ground.
2) Right Click the banner with a shader. 

This transforms it into the Shader Banner, which is the valid POI for this guy.

This is all briefly mentioned in the IE manual (just says Shaders can be applied to banners with right click. It does not say that this is the POI for villagers that I can see). 

I've tested this in a small test world and in Dev. Please give it a try in your world and let me know.

**Comment by MuteTiefling** [comment]
https://github.com/Mrbysco/JustEnoughProfessions/issues/1

**Comment by HaxtonSale1** [comment]
Thank you, I tried it and it worked.

**Comment by ricosolismario-del** [comment]
Alright, but it is still uncompatible with easy villager because you cant place a banner inside a trader

**Comment by MuteTiefling** [comment]
> Alright, but it is still uncompatible with easy villager because you cant place a banner inside a trader

You'll want to raise that with the easy villager mod authors as it is not part of our pack.
