### ISSUE TITLE
Dirty Nickel produces Pedestals Nickel dust in Enrichment chamber

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#119]
**Modpack version**
Input modpack version here
0.2.5
**Issue**
Input short description of the issue here

There's no smelting recipe for pedestals dusts, so when they're output by the 3x ore processing setup they can't smelt at the final step. 
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Oh god, not more of these issues >< thanks for the report. Should be fixed in 0.2.7
