### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by lunulu** [NillerMedDild/Enigmatica6#1191]
**Modpack version**
0.3.11 and 0.3.13

**Describe the bug**
The main server started to crash. I've tried to use "netsh winsock reset" in cmd, but it didn't help.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5911825/latest.log)

**Screenshots**
![1](https://user-images.githubusercontent.com/65171793/106614617-9b40d700-657c-11eb-89f0-2cb13dd23c4e.png)

**Describe the bug**
I also tried to create a new server but it crashes for a different reason.

**Logs**
[serverstart.log](https://github.com/NillerMedDild/Enigmatica6/files/5911841/serverstart.log)

**Screenshots**
![Безымянный](https://user-images.githubusercontent.com/65171793/106614798-cfb49300-657c-11eb-9841-92280f5672cd.png)

**Comment by Darkere** [comment]
Your first crash is because either a different server was running in the background on that port or because you have an IP in server.properties (that should be empty).

Second crash is due to an ongoing issue with the hosting company forge uses. Nothing we can do about that other than wait.

**Comment by lunulu** [comment]
Thank you, I had an IP in server.properties.`
