### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by drtrdr23** [NillerMedDild/Enigmatica6#1194]
**Modpack version**
0.3.13
**Describe the bug**
The main server will not run it just crashes on startup.

**Logs**
https://pastebin.com/F2B3hS0x

**Screenshots**

**Comment by Darkere** [comment]
It is not in the log file but forge's server host is currently experiencing issues causing broken downloads.

This is most likely your issue too, although I would need you to run from console to see the output.

**Comment by drtrdr23** [comment]
Here is a screenshot. 
![Screenshot (1)](https://user-images.githubusercontent.com/19785046/106643395-ad5c4e80-6557-11eb-908c-6eb7d4695593.png)

**Comment by Darkere** [comment]
Yep you are missing files. Ironically the library that is responsible for logging what happens :)
