### ISSUE TITLE
Quark Chests Override Lootr Chests in The End

### ISSUE THREAD

**Issue by r-mc2** [NillerMedDild/Enigmatica6#1197]
**Modpack version**
v0.3.13

**Describe the bug**
Not sure if it is intended to be this way or not, but my understanding of adding Lootr was to give the instanced loot chests for everyone on a server, so I'm reporting this under the assumption that Quark shouldn't be doing this in the vanilla structures generated in The End (ships, cities, etc).
If leaving these excluded was intentional, feel free to close! 🙂 

**Screenshots**
![image](https://user-images.githubusercontent.com/36780233/106681374-59209100-658e-11eb-866e-7a03064a7cee.png)

**Comment by NillerMedDild** [comment]
This is not intended, thanks for the report :)

**Comment by noobanidus** [comment]
Yeah, it does become a race condition unfortunately -- as to which of our conversion processes fire first.

**Comment by noobanidus** [comment]
@NillerMedDild Just a heads-up, Artifacts also has this as a "feature", not sure if you've disabled it.
