### ISSUE TITLE
Astral Marble to be removed from cobblestone crafting

### ISSUE THREAD

**Issue by SeaSaltStar** [NillerMedDild/Enigmatica6#1198]
**Description**
Astral Sorcery marble should be removed from cobblestone crafting recipes
**Why would you like this added/changed?**
It can be quite annoying to have an excess of marble variants in storage only for tags to turn them into furnaces when crafting.
**Screenshots if applicable.**
https://imgur.com/a/THHuhj4

**Comment by OneLemonyBoi** [comment]
Removing the stone tag from Marble would fix it, but that would remove lots of recipes that Marble would have previously worked for.

**Comment by NillerMedDild** [comment]
I don't think that would be a good idea to be honest, that could potentially block players from obtaining furnaces / stone tools if they have unlucky worldgen.
