### ISSUE TITLE
Various Cobblestones have a duplicated incorrect JEI information page

### ISSUE THREAD

**Issue by IllegalCharacter** [NillerMedDild/Enigmatica6#1199]
**Modpack version**

E6 0.3.13

**Describe the bug**
The below page shows up in JEI
 for the cobblestones from Create and EmbellishCraft. It appears to be inaccurate, as the mentioned recipe only results in regular cobblestone. Perhaps it's supposed to be a random result?

![javaw_7uMqTlyeJw](https://user-images.githubusercontent.com/7243508/106697523-e8d53800-65ac-11eb-982d-b4f0e23aea6f.png)

I've also included a quote from discord user MadAthey that may be useful below:

> It appears the forge tags, such as forge:cobblestone or forge:stone are affecting the "Information"(JEI) tab of the JEI recipes, resulting in the same recipe to "cobblegen" various ores showing up on each ore tagged as such. Other tabs, such as the CobbleGeneration tab, show the correct recipes to create these various stones - only the "Information" tab labeled as (JEI) seems to be giving misinformation.

**Comment by Merlo17** [comment]
JEI is correct, it's supposed to be a random result with an Iron Block. Something likely broke there

**Comment by MuteTiefling** [comment]
I had asked for a screenshot of your cobble gen in discord last night and wasn't able to stick around long enough to see it.

Can you upload it here please? I've been unable to reproduce this.

**Comment by MuteTiefling** [comment]
As an example of what this should look like: https://streamable.com/qrkog5

**Comment by NillerMedDild** [comment]
I'm not sure what the issue is here? Lack of the word random in the description? :)

**Comment by IllegalCharacter** [comment]
Apologies, I've been busy. The issue is that if it's supposed to generate random stones, it isn't. I can post a picture of my set ups I've tried again, I posted them in the discord the other day when trying to figure this out before I opened this issue.

![image](https://user-images.githubusercontent.com/7243508/106989188-9710e700-673f-11eb-97a6-830aeee0151e.png)
![image](https://user-images.githubusercontent.com/7243508/106989196-9c6e3180-673f-11eb-8154-176bf1c4d1e9.png)
![image](https://user-images.githubusercontent.com/7243508/106989209-a5f79980-673f-11eb-90e7-cec5a3fe5227.png)


These are all set ups I tried at the request of members of the discord. The block of iron is underneath the cobblestone that was created. The recipe only makes regular cobblestone.

**Comment by theboo** [comment]
what do u have placed under the cobble in these pictures?

**Comment by IllegalCharacter** [comment]
The block of iron.

Here:

![image](https://user-images.githubusercontent.com/7243508/106993912-c4fb2900-6749-11eb-94a2-ddd105b06d12.png)
![image](https://user-images.githubusercontent.com/7243508/106993938-cf1d2780-6749-11eb-8c16-5aaa6c4d0180.png)

Unless I'm impossibly unlucky, something isn't working here.

**Comment by theboo** [comment]
https://gyazo.com/10172b9115c7b4c281784f2818df5529

**Comment by IllegalCharacter** [comment]
Mine has been running since I posted that last image, still nothing but cobble.

**Comment by theboo** [comment]
looking at ur jei page, u seem to be missing the pedestals cobble gen recipes too? which stone are u looking at there?

**Comment by IllegalCharacter** [comment]
Basalt from EmbellishCraft

**Comment by IllegalCharacter** [comment]
So since updating to 0.13 I've been getting a kubejs warning. Everything has been working fine otherwise, so I had just dismissed it. However, running the command it tells me to gives me this 


![image](https://user-images.githubusercontent.com/7243508/106997195-77ce8580-6750-11eb-8241-e655cdb55499.png)

I...uh.... think I found the root of the problem.

**Comment by theboo** [comment]
Ah ha! Curse forge has been having issues getting everything actually in the download... What you can do is download the server files from here: https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/3187090, unzip, delete the kubejs folder on your instance and copy the one from the .zip into your instance.
