### ISSUE TITLE
forge 67+ command change crashing

### ISSUE THREAD

**Issue by Darkere** [NillerMedDild/Enigmatica6#12]
~~- Interactio https://github.com/MaxNeedsSnacks/Interactio/issues/14~~
~~- Default options https://github.com/blay09/DefaultOptions/issues/41~~
~~- KubeJS https://github.com/KubeJS-Mods/KubeJS/issues/18~~
~~- TheOneProbe https://github.com/McJtyMods/TheOneProbe/issues/398~~
- CosmeticArmorReworked https://github.com/zlainsama/CosmeticArmorReworked/issues/48

**Comment by NillerMedDild** [comment]
(Note to self) Temporarily removed CosmeticArmorReworked to continue development, hopefully it updates soon.

**Comment by Darkere** [comment]
And it's fixed
