### ISSUE TITLE
Netherite Crafter

### ISSUE THREAD

**Issue by Zencha15** [NillerMedDild/Enigmatica6#1202]
**Modpack version**

0.3.13

**Describe the bug**

the netherite crafter has a glitch where you shift click multiple things into it it dupelicates them, i left and rejoined my world to check it wasnt lag and it wasnt. i just have lots of patterns now lol

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by Merlo17** [comment]
I couldn't reproduce this, what steps did you take exactly? It seems to work fine for me
