### ISSUE TITLE
Crashing Issue With Mimicubes

### ISSUE THREAD

**Issue by HitmanKillsYou** [NillerMedDild/Enigmatica6#1205]
**Modpack version**
0.3.13 with 3 additional mods.
JustEnoughResources-1.16.4-0.12.0.103
SimplyJetpacks2-1.16.4-2.6.5.2
Cyclic-1.16.5-1.1.4

**Describe the bug**
Entity known as Mimicube attacked me, presumably tried to transform in to me and is now causing a crash loop.
Effects at the time were levitation from a Shulker
Equipped items to my knowledge were a full set of unenchanted Archmage robes from Ars Nouveau, the Archmage book from the same mod, a DANK, and a diamond sword with 5% chance to set something on fire from Apotheosis and an umbrella from some mod with a name that escapes me.
Upon trying to rejoin the world it goes: Joining Server, Encrypting, Loading Terrain, Saving World, Crash to Launcher with error

**Logs**
https://pastebin.com/3K2VNPpH

**Screenshots**
Sadly no screenshots.

**Comment by HitmanKillsYou** [comment]
Friend of mine told me, after reading my crash report, the umbrella cannot be equipped by the Mimicube after it copies my gear. So from what we can see that would be the reasoning for crashing upon loading.

**Comment by Darkere** [comment]
Correct. This goes to artifacts. The only solution I could give you is removing the entity. Peaceful mode might make that easy.

**Comment by HitmanKillsYou** [comment]
It’s a server so something like that would be at my friends discretion, and they want to avoid going full admin to help everyone with their problems which I understand.
