### ISSUE TITLE
IF Laser Lens

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica6#1206]
**Modpack version**
0.3.13
**Describe the bug**
Magenta / Pink / Cyan / Green Lenses from IF dont have a targeted ore or fluid...making them useless. maybe they could have undergarden ores and/or other fluids added to them.

**Comment by Merlo17** [comment]
I'll look into this tomorrow ^^ surprised green doesn't have emeralds tbh
