### ISSUE TITLE
Mod Suggestion: Create Crafts & Additions

### ISSUE THREAD

**Issue by Jams52** [NillerMedDild/Enigmatica6#1207]
https://www.curseforge.com/minecraft/mc-mods/createaddition

It's a mod in development by the builders crafts and additions dev that adds electric motors to bridge Create and FE mods.

I feel like adding it would make Create more accessible and I don't see a reason it would hurt the back because there is already OP technology so being able to power moving doors and such with FE wouldn't hurt.

**Comment by Merlo17** [comment]
https://github.com/NillerMedDild/Enigmatica6/discussions/1190
