### ISSUE TITLE
BlockCarpentry Chests Cause Excessive Log Spam & TPS Drops

### ISSUE THREAD

**Issue by r-mc2** [NillerMedDild/Enigmatica6#1208]
**Modpack version**
v0.3.13

**Describe the bug**
(Originally in the title: `BlockCarpentry Chest Fail In Certain Scenarios When Trying To Automatically Insert`)

I noticed this initially trying to do something fancy with an Illusion Chest from BlockCarpentry and having a hopper botany pot sitting on top. I had 19 of these set up and did not notice the logs were going crazy for about 30 minutes. But, when the plants finished growing and the pots tried to insert into the chest below them it resulted in roughly 4 million lines of log warnings/errors being generated in about 30 minutes. All the while this was going on the TPS on our server was dropped from an average of 40ms to upwards of ~70ms.

I've reported it over on BotanyPots [in this issue here](https://github.com/Darkhax-Minecraft/BotanyPots/issues/138) but it seems that the root cause is actually BlockCarpentry and how they handle their chest TE.
And I was eventually referred over to an similar issue on BlockCarpentry's Issue tracker where something [similar was experienced in XNet](https://github.com/PianoManu/BlockCarpentry/issues/21).

I'm reporting here in part due to @theboo's suggestion and in part to raise awareness of the BlockCarpentry chest when behaving like this.

**Logs**
(On original Issue [here](https://github.com/Darkhax-Minecraft/BotanyPots/issues/138))

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Would you mind reporting this to BlockCarpentry? Seems like you have a pretty good understanding of the issue.

**Comment by r-mc2** [comment]
Sure, I tagged on to the end of the "XNet" issue I linked above for now ([this one](https://github.com/PianoManu/BlockCarpentry/issues/21)), but do you think it would be worth a separate issue to be opened over there?

**Comment by NillerMedDild** [comment]
Oh my bad, no I think that will do just fine.

**Comment by r-mc2** [comment]
Just an FYI, BlockCarpentry's author just released a fix for this yesterday in [v0.3.5b](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry/files/3264543) \o/

Maybe the two chest blocks can come back after some testing with the pack in the dev env?
