### ISSUE TITLE
Silver ore + ore crushing hammer make silver grit instead of silver dust

### ISSUE THREAD

**Issue by mrDLSable** [NillerMedDild/Enigmatica6#121]
All the other ore processing stuff make Silver dust (from Pedestals) but this recipe makes SIlver grit (Immersive Engineering)

**Comment by mrDLSable** [comment]
Also, the SIlver Dust (from Pedestals) is not smeltable into a silver ingot...

**Comment by NillerMedDild** [comment]
It's meant to be IE actually :/ thanks for the report though. Should be fixed in 0.2.6
