### ISSUE TITLE
Terraforged investigation list

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica6#1215]
While our worlds already look super good here's what we should look into:

- [x] Investigate village count, Moto says it's fine but in my world I have a lot, might need some experimenting
- [x] Reduce Vanilla biomes weight and increase BYG weight, especially the ones that are a bit rarer
- [x] Reduce overall biome size a bit, leave them bigger than normal but currently they might be a bit too huge
- [x] Increase river count, MOAR RIVERS
- [x] Maybe increase mountains frequency a bit but honestly I'm just nitpicking at this point
- [x] Fix astral structures somehow
- [x] Remove diorite and granite from strata
- [x] remove ID biome from world gen

**Comment by Ridanisaurus** [comment]
I think the Mountain frequency is fine. We don't want everything to be mountains, as amazing as they are. We will should leave enough flat areas for the flat people. 
From investigating 3 worlds, I encountered enough mountains to keep is exciting, and worth exploring.

**Comment by Merlo17** [comment]
Agreed, I just wanted to mention everything to make sure we look into all of that before releasing, but I probably wouldn't touch it, maybe ever so slightly

**Comment by MuteTiefling** [comment]
personally, villages bring life to a lonely world. If there's a dial to make pillager outposts more common that would be sweet too.

We might need to double check structure gen as well. I explored a ways and saw 1 astral structure (a big one, no little ones) and one tower of the wild. Nothing else. No valhalesia structures, dungeons, etc.

**Comment by Merlo17** [comment]
I encountered some valhesia structures. I would turn them up significantly though, especially astral if we can since it's needed for progression

**Comment by Ridanisaurus** [comment]
yea, sadly Astral has a habit of generating in a floaty way with non-vanilla world gen. Not sure how much we can do about that. Even on the current version I found many floating structures with just the way BYG generates.

**Comment by Merlo17** [comment]
Yeah nothing we can do about them generating a bit weird, but I'd bump up the frequency significantly to make starting out less tedious

**Comment by theboo** [comment]
The astral structures were generating like 1 in every 10 chunks so I made them a bit less frequent.. might have gone too far tho

**Comment by Merlo17** [comment]
Here's something else to look into, removing vanilla mountains biomes from the pool. Now that almost any biome can potentially spawn on a mountain terrain, they're pretty much useless and duplicate content.
I.e. if a forest biome spawns on a mountain that's just like having a wooded mountains biome, so it's effectively two equal biomes that take up space in the pool. By default they're also not that interesting, since the cool features they have is spawning mountains and that's negated by TF

**Comment by sciguyryan** [comment]
> 
> 
> Yeah nothing we can do about them generating a bit weird, but I'd bump up the frequency significantly to make starting out less tedious

It might be worth putting in some feedback about that on AS's github page. I suspect that the issues would also be found with other biome-modification mods. As most modpacks use at least one, having that fixed could be nice to have - though isn't game breaking.

**Comment by Merlo17** [comment]
Astral structure issue: https://github.com/TerraForged/tracker/issues/34

**Comment by Merlo17** [comment]
oh by the way, we still have Diorite and Granite in strata

**Comment by theboo** [comment]
6 and 7 can be checked off... also removing ID biome needs to be on the list, ill do that tomorrow... anything else?

**Comment by Merlo17** [comment]
Why are we removing it? It looks pretty cool no?

**Comment by Ridanisaurus** [comment]
It does not. 
![image](https://user-images.githubusercontent.com/64355028/107237843-768aaa80-6a27-11eb-9bb1-4f4a89f6cecc.png)

**Comment by Merlo17** [comment]
Here's something that's worth considering imo: switching quark marble to AS marble in strata and worldgen

The texures look comparable imo, I personally prefer AS and would like to see it in worldgen (even if rid doesn't agree :P), but the problem to me is that you need AS marble specifically to build AS structures, and it doesn't make much sense to have that behind the stonecutter with players having to exchange every time they need it.
Since they both serve the same function but AS has more functionality, I'd argue that should be the default, so it's at least something to look into, depending how you guys feel about it too.

Texures for comparison:
![2021-02-10_12 28 39](https://user-images.githubusercontent.com/62080872/107507143-6dbce480-6b9f-11eb-90dc-30f4ab673a23.png)

**Comment by Ridanisaurus** [comment]
Regarding the above suggestion, Do note that replacing Quark Marble with Astral Marble, it would be worth tuning down massively due to it being a niche blocks, and it's mostly functional than decorative. 
Its reduction will also allow more ore spawning space with the other stones to compensate for the lose of Quark Marble.
If I remember correctly, this was discussed at some point on Discord a while back for E5.

**Comment by Merlo17** [comment]
> it being a niche blocks, and it's mostly functional than decorative

personally I don't agree, I find it pretty much the same with just added functionality. different viewpoints I guess ^^

**Comment by Ridanisaurus** [comment]
Boo just confirmed that it's not possible to turn down the amount of stone strata, at least not through TF due to the lack of weight control. If you design to go for Astral Marble, then let me know if you want me to modify EE and add it to compensate for the lose of valid ore spawn locations.

**Comment by Merlo17** [comment]
Fair, but to me it's still weird that you have to make special one somehow for the structures and it's not the one you would naturally already have

**Comment by NillerMedDild** [comment]
That's the case either way, since it requires like 6 versions of AS Marble?

**Comment by Merlo17** [comment]
I guess so, but it's still an extra step that can be confusing imo. I've seen a bunch of players on discord asking why they needed a different marble to progress, one today even :P

**Comment by TemperedFool** [comment]
I'll put in a vote for quark marble being ugly vs astral. I would say for world gen you really just need the raw form generated in the ground?

**Comment by MuteTiefling** [comment]
Quark marble does l nicer next to the other world gen stones though

**Comment by TemperedFool** [comment]
Hmm, that could definitely be true. Could the problem be solved with a quark marble -> astral raw marble recipe, rather than tinkering with worldgen?

**Comment by Ridanisaurus** [comment]
Yea, we can add a 1:1 Exchange Recipe in a crafting Grid if this is confusing people too much (I honestly don't understand why, but that's just me)

**Comment by TemperedFool** [comment]
Personally, using the stonecutter for this kind of thing can be annoying at times; if you can convert by crafting, it can be part of a crafting chain to make the various Astral marbles.

**Comment by theboo** [comment]
sounds like the perfect job for.............

![image](https://user-images.githubusercontent.com/3585761/107594914-13844980-6bc8-11eb-9751-b1c8566facbb.png)

**Comment by OneLemonyBoi** [comment]
if it ever gets used

**Comment by MuteTiefling** [comment]
> Personally, using the stonecutter for this kind of thing can be annoying at times; if you can convert by crafting, it can be part of a crafting chain to make the various Astral marbles.

The Create Saw can always be filtered to output a specific stonecutter recipe. So automating the conversion is quite simple. But they're both available as stone-gen outputs.

**Comment by TemperedFool** [comment]
Totally fair - I forget the create saw exists for that! Might be that I need to look through that and just set one up for conversions that need to be done en-masse. Is there a magic-friendly way of doing the same thing? Don't want to leave out the non-tech types ^_^

**Comment by Merlo17** [comment]
![2021-02-11_12 52 39](https://user-images.githubusercontent.com/62080872/107633789-dd4ad680-6c68-11eb-992c-e0f63a8b7cbf.png)
![2021-02-11_12 54 41](https://user-images.githubusercontent.com/62080872/107633792-dfad3080-6c68-11eb-9c69-6885042a4b0d.png)
![2021-02-11_12 55 28](https://user-images.githubusercontent.com/62080872/107633796-e0de5d80-6c68-11eb-82d7-5ea8f94e9f7f.png)

Some screenshots for comparison to show why I think astral marble would be an improvement overall based on looks alone. It comes down to personal preference clearly, but it's just something to look at I guess, imo it looks stellar in worldgen and it's much more interesting than quark's marble.
Conversion recipes are fun and all, but as Rid pointed out many players just don't check for this sort of stuff or read JEI, so having this extra step in the middle can be super confusing for them imo. They will still have to craft the other marble variants for the structures of course, but they'll be super confused as to why the marble they already have isn't good enough and they need another one, where if the AS one was default and builders had the option to switch it would make much more sense to me, since someone that invested in building likely understands the underlying mechanics already.

**Comment by KrAzYGEEK32** [comment]
I personally feel like AS marble is too smooth to be world gen, logically speaking :P. Gameplay wise I do agree with merlo though. It strikes a complete contrast to other stone types when you come across it in caves, whereas quark marble blends in perfectly.

**Comment by Merlo17** [comment]
The main point in my argument is that we should look at this gameplay wise. We can agree or disagree on which one looks better but in the end that matters very little to me, since that can be easily fixed later with a resource pack, even after 0.4 comes out. Gameplay wise though AS marble is straight up "better", since it does everything quark marble does but also has unique functionality to itself, so I'd argue it should be the one players find, with builders being able to select the other one if they so wish. We can fix textures whenever, but we can fix worldgen only now.

**Comment by Thiana** [comment]
Is the generation of BYG's Basalt Barrera as a beach alternative intended? It looks rather odd.

**Comment by theboo** [comment]
basalt barrera is a beach type biome from BYG, yes
```  "player_spawn_friendly": true,
  "forge:registry_name": "byg:basalt_barrera",
  "precipitation": "rain",
  "temperature": 0.85,
  "downfall": 0.75,
  "category": "beach",
  "depth": -0.2,
  "scale": 0.025
}```

**Comment by Thiana** [comment]
Perhaps the biome weight could be lowered then? It looks extremely odd as a beach biome and seems to be more common than the basic beach. 

![2021-02-12_08 20 22](https://user-images.githubusercontent.com/405832/107773570-daed8880-6d0b-11eb-87df-27316b9dfb8b.png)

**Comment by Ridanisaurus** [comment]
I love that Biome. I honestly think it's one of the best looking BYG Biomes.

**Comment by NillerMedDild** [comment]
I'm with the Dinosaur on this one, as per usual
