### ISSUE TITLE
Investigate possible Mining Dimension Mods

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1216]

**Comment by Merlo17** [comment]
https://twitter.com/McJty/status/1357396643834966020

I'll point to this since it seems to be happening pretty soon

**Comment by r-mc2** [comment]
Hmm, what about borrowing Stoneblock2's world gen, but turning ore gen back on and using that as the mining dimension? Dunno how portable that world gen and mod would be for 1.16 though. Or how easy it would be to give a player the "bubble" to safely teleport into it. Or if it's something you all would have access to, but throwing it out there.

**Comment by TemperedFool** [comment]
If RFTools dimensions is coming eventually, and there are a number of resource generation methods (mineralis, orechid, and bees come to mind), is a mining dimension strictly necessary?

**Comment by NillerMedDild** [comment]
I suppose not, no, though I can't really promise that RFTools will be added.

**Comment by r-mc2** [comment]
For me, I'd say yes, sometimes there's just something satisfying about digging up a huge world hole, but not wanting to ugly up the overworld with mass-mining.

Throwing it all into a single dimension has the added benefit of making it easier to nuke the dimension folder and start fresh with future pack updates that may affect world-gen. That said I do agree RFT Dimensions would grant a player that as well, just create a new world with the same dim settings, but RFT Dimensions is kinda high up there in a tech tree with power requirements unless you speedrun for it.

Although, I suppose in a server environment an admin could set up an RFTDim and put the teleporter in a community hub-like area, but that'd depend on the admins, I guess?

**Comment by TemperedFool** [comment]
Ok, so brings up a few questions for me then:

Is this intended to be similar to thinks like the Deep Dark and similar, where they're entirely underground dimensions?
If not, what kind of stuff will be on the "Surface" of the dimension?
Will there also be interesting underground worldgen, or will it basically be solid stone & ore to be dug up?

Not particularly pro or against personally, just have never played a pack where the "mining dimension" wasn't really just way to supply certain resources that weren't otherwise in the overworld.

**Comment by r-mc2** [comment]
The packs I've played with mining dimensions are usually either a direct clone of the Overworld, caves, ores, structures, etc. Or a semi-clone but super-flat at y=64/128 with the same ore gen but no structures; some are perma-day, some have day/night cycles.

My thought for a Stoneblock-style mining dimension was to simply provide what a dimension for mining would be directly for, mining ores. So 100% filled with stone and ores that someone could go into and veinmine it until it's swiss cheese and avoid tearing up the Overworld (more useful on a server, but the mining dimension usually is for server environments). The world being solid blocks also gets past the issue when a mining dimension mod makes it perma-day and people abuse solar panels over there.
For where to gen the ores in a dimension like this? I'd say leave it like it is now so you'd end up with a lot of empty (ore-wise) stone above y-64. Although I guess that could mess up the rarity of emeralds if stone goes all the way up to 256 for the ores to generate in... 🤔 

Deep Dark was included in E2, I think, but that has the bonus of extra ores for extra+harder mobs, although Astral's Cave Illuminator usually makes that trivial so a pure "like the overworld" ore-generation would grant everyone some dimension they can go crazy in via Ultimining, RFTools Builders, Mek's Digital Miner, or what-have-you while still providing a clean Overworld to build in and/or explore.

To touch on the idea of Astral's rituals, very true and can be really effective for the end goal, but what is it they say? "It's not the destination, it's the journey."
Sometimes, it's just fun to go out and mine it up yourself and see it, a sense of accomplishment for your efforts.
Bees and Botania could fulfill this, certainly, but having an option for those who may not want to touch either of those mods doesn't hurt either. (Full disclosure: I'm one of those people who doesn't want to touch bees or Botania 😆)

But that's just my $0.20 ($0.02 x 10 cause I can ramble lol).

**Comment by Merlo17** [comment]
I would love to see RFTools dim since it's much more than a mining dimension mod and can be used for super fun experiments and shenanigans. There's clearly a lag concern, but I hope it won't be too much (servers would likely disable it anyways).
Hard to tell without it being out though, so I'd wait for that

**Comment by MuteTiefling** [comment]
https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension

Could be interesting if we go for this. All caves and seemingly very customizable. 

That said, I really don't feel like this is necessary. We have loads of ways to renewably produce this stuff and many that are more interesting to automate than simply moving a giant 512x512 builder around every few hours >.>

**Comment by TemperedFool** [comment]
The biggest argument FOR in my mind is that every few days someone asks if there is one ^_^

**Comment by NillerMedDild** [comment]
This turned out to less wanted than I initially expected :P
