### ISSUE TITLE
Advancements not obtainable for specific players

### ISSUE THREAD

**Issue by soepie7** [NillerMedDild/Enigmatica6#1217]
**Modpack version**
E6 0.3.13

**Describe the bug**
Subspace Bubble (travel 7km via the nether) and How Did We Get Here (all vanilla obtainable effects) are not obtainable for some players. I even tested it here with the admin. Entering the same portal, exiting the same portal; he got the advancement, I did not, after travelling 16km via the nether. Earlier I got all potion effects, I looked to see if any effect went away before I got my last one, and while that didn't happen, no all-effects advancement either. Other advancements, both vanilla and modded, do still work for me,

**Comment by NillerMedDild** [comment]
There's not really anything we can do here, we didn't alter them nor alter how advancements trigger in any way :/

**Comment by soepie7** [comment]
Something to add; admin showed that with commands I can be given the advancements, and since I noticed not getting advancements when I should have, I did get others in a natural form.
