### ISSUE TITLE
Immersive Posts gold post destroyed when breaking

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1218]
Enigmatica 6 0.3.13 (Official E6 Server)

The gold posts from Immersive Posts get completely destroyed when mining rather than dropping the item.  This occurred using diamond pickaxes to mine the post (and the HUD indicated that it was mineable), and was tried both with and without silk touch. Repeating a similar test with iron posts form Immersive Posts yielded an item drop as normal.  No other testing was done on other Immersive Posts.

**Comment by OneLemonyBoi** [comment]
I can confirm that this issue is present and all fences from Immersive Posts break without dropping an item. A temporary fix would be adding loot tables via a datapack, but this seems like an Immersive Posts issue and should be reported there.

**Comment by MuteTiefling** [comment]
Relayed: https://github.com/TwistedGate/ImmersivePosts/issues/24
