### ISSUE TITLE
Can't use EE steel plate in multiservo press mold recipes

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1219]
**Modpack version**
0.3.13

**Describe the bug**
Making the "metal press mold: wire" in the thermal multiservo press requires the IE steel plates, it doesn't accept the emendatus enigmatica ones. Looks like the same for the rod mold, but haven't checked that one in-game.

**Comment by Merlo17** [comment]
Oh yeah, something definitively went wrong there, some of the other molds don't even have recipes. I'll look into it
