### ISSUE TITLE
Metallurgic Infuser not working

### ISSUE THREAD

**Issue by Searta** [NillerMedDild/Enigmatica6#1220]
Metallurgic Infuser won't begin process spezific materials. I tried to make a Basic Control Circuit. It takes the redstone and adds it to the reservoir but when i add an Osmium ingot nothing happens. The machine does have power. But it works when i tried to make an Infused Alloy.This is occurring in single player.

![MekanismBug](https://user-images.githubusercontent.com/71118391/107008123-b174b000-6793-11eb-8ba0-444955725c7e.PNG)

**Comment by Merlo17** [comment]
How much redstone did you put in? You need 20mb (or two pieces of dust) per circuit. It's working fine for me

**Comment by Searta** [comment]
In the beginning it work fine with redstone and iron ingots to make Infused Alloy. Ive play mekanism alot. I know how much redstone i need. But now when I add 4 Osmium ingot and 4 redstone to make 4 basic controll circuit nothing happens. Also now it dosent work with redstone and iron ingot anymore. The machine does have power from the wind turbines and the basic cables from mekanism. I dont know why it work after I started the modpack and after I maked the first stack (64) of Infused Alloy and then put in the materials for a basic controll circus it dosent do anything, nothing.

**Comment by Merlo17** [comment]
![2021-02-06_11 56 31](https://user-images.githubusercontent.com/62080872/107116324-9d53b000-6872-11eb-88cb-2c0e094b5c69.png)
![2021-02-06_11 56 22](https://user-images.githubusercontent.com/62080872/107116326-9fb60a00-6872-11eb-8b9c-a3ed648aac4c.png)

As you can see I tried your exact same setup in a fresh 0.3.13 instance and everything is working as expected.
Could it be that you added too many speed upgrades and your machine is unable to operate because you aren't feeding it enough power? Otherwise, I really have no idea what's happening here

**Comment by Searta** [comment]
ah I see there the problem, I play in version 0.3.8 maybe there a bug or so. i will change version and see if my bug is still there. also its interessting that when u download it, its version 0.3.8 and not the newest.

**Comment by Searta** [comment]
So im on the newest version 0.3.13, in my old world it doesnt work. I created a new world and set it up and boom i can make 1 infused alloy and when i try to make an basic controll circuit it dont do anything.
![2021-02-06_13 35 01](https://user-images.githubusercontent.com/71118391/107118287-4c4ab880-6880-11eb-8223-91560c4b40d9.png)
![2021-02-06_13 35 10](https://user-images.githubusercontent.com/71118391/107118298-5f5d8880-6880-11eb-9e9a-6853af253f55.png)
![2021-02-06_13 35 14](https://user-images.githubusercontent.com/71118391/107118308-713f2b80-6880-11eb-8840-7443c18fb1da.png)
![2021-02-06_13 35 17](https://user-images.githubusercontent.com/71118391/107118320-86b45580-6880-11eb-89b8-47eb7243c433.png)
as you can see, it dont work for me and i have no clue why.

**Comment by Merlo17** [comment]
Are you using Emendatus Enigmatica Osmium and not Mekanism Osmium?

**Comment by Anaphylaxis** [comment]
I just had the same issue.. your power is off. Look in the bottom right in your screenshot. It needs to be set to "INVERTED" -- if you hover over it it's not a power switch it's actually a redstone detection switch, meaning it needs redstone when set to "ON" -- inverted disables the redstone detection switch.
