### ISSUE TITLE
[Chisels and Bits] Increase Bit Bag Stack Size

### ISSUE THREAD

**Issue by dixonw2** [NillerMedDild/Enigmatica6#1223]
**CurseForge Link**

**Description**
Currently, as it stands, a single bit bag holds 3.375 full blocks I believe ((512 bits * 27 storage spaces)/(16 * 16 * 16 bits per block)).

**Why would you like this added/changed?**
I love playing with Chisels and Bits and using a pallet of 4-5 block types at a time, so between having 5 bit types in my inventory, food, tools, full block types to place/chisel down, and multiple bit bags, inventory management becomes a huge hassle, even with a diamond backpack.  Since Chisels and Bits also deletes excess bits that won't fit into a bag/the inventory, it makes me have to play incredibly slow when using more rare blocks/ones that take a bit of time to collect to ensure no bit gets deleted and I'm out an entire block.

I believe I played a pack that had a 2048/stack limit back in 1.11 and that greatly helped, as having a couple bit bags comfortably fit what I was attempting to juggle. If there are further implications to this then I understand why not to implement it, but it would allow users like me to be able to get a decent amount of bits before building and not worry about resupplying every couple minutes. Since Chisels and Bits is purely aesthetic, I don't think this should throw off any kind of balancing within the pack.

**Screenshots if applicable.**

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I increased the stack size to 16384, 32 times the current limit :)

**Comment by dixonw2** [comment]
> Thanks for the suggestion, I increased the stack size to 16384, 32 times the current limit :)

That's incredible, thank you so much! You made the builder in me very happy
