### ISSUE TITLE
 Guiana Shield Biomes hit Build Height on Amplified Worlds

### ISSUE THREAD

**Issue by Angular-Angel** [NillerMedDild/Enigmatica6#1225]
**0.3.13**

**Describe the bug**
 In amplified worlds, the Guiana Shield biomes hit the max build height. Not just occasionally, but rather, the entire biome will generate right up against build height, such that it cannot even generate trees. See: https://github.com/CorgiTaco/BYG/issues/274

**Screenshots**
![2021-01-29_19 41 06](https://user-images.githubusercontent.com/938571/106345007-5827f080-626a-11eb-9ecc-43df347cb57b.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, but my answer is the same as the mod devs. This is just something that you risk when running Amplified.
