### ISSUE TITLE
Pedestal - Cobble Generator Upgrade - Silk Touch

### ISSUE THREAD

**Issue by StaticButton** [NillerMedDild/Enigmatica6#1228]
**Modpack version**
0.3.13

**Describe the bug**
Cobblestone Generator Upgrade in Pedestal Mod.
Can't enchant via enchanting table or combine silk touch book with the cobblestone generator upgrade in the anvil. JEI shows that you can auto gen dolomite using the "silky touch gen" using a cobblestone generator upgrade in the pedestal.

**Comment by BlueAgent** [comment]
You can't apply it through normal enchanting or the vanilla anvil, you have to use the mod's EXP anvil.

**Comment by MuteTiefling** [comment]
You can read about the process here

https://github.com/Mowmaster/Pedestals/wiki/Exp-Anvil

**Comment by changhe3** [comment]
I wish it can be made so that you can enchant it with normal enchanting processes...

**Comment by MuteTiefling** [comment]
Feel free to suggest that to the author @changhe3
