### ISSUE TITLE
Immersive Engineering Weapons Do Not Work

### ISSUE THREAD

**Issue by zhg-kj** [NillerMedDild/Enigmatica6#123]
**Modpack version**
0.2.4

**Issue**
The revolver does not shoot, I fully loaded it and then right clicked and nothing happens.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Shindur** [comment]
Works fine on version 0.2.5 of the pack. So in theory should be fixed once the pack updates.

**Comment by NillerMedDild** [comment]
I'll close this then, if you can reproduce it on 0.2.5 I'll reopen it :)
