### ISSUE TITLE
Ars Nouveau - Harvest spell isn't work on server

### ISSUE THREAD

**Issue by koalalord9999** [NillerMedDild/Enigmatica6#1231]
**Modpack version** 3.13

**Describe the bug**
I create the spell Harvest on a projectile. I shoot tree. Spell just pops and tree still stands.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
This is my spell I using for this.

![](https://cdn.discordapp.com/attachments/400470621592485898/807509615469789184/unknown.png)

**Comment by koalalord9999** [comment]
According to the book, this is the spell that is used for it. However, there is another spell called Fell - which is probably the one I actually need.

**Comment by MuteTiefling** [comment]
Yes, tree harvesting was recently separated from harvest.

Which book are you saying tells you to use harvest? The quest book, or the mod's manual?

**Comment by koalalord9999** [comment]
mod manual

**Comment by MuteTiefling** [comment]
Looks like they've already taken care of this in the current version: 

![image](https://user-images.githubusercontent.com/9543430/107125983-10612480-687b-11eb-88cb-31dbbb6ae936.png)

![image](https://user-images.githubusercontent.com/9543430/107125996-1f47d700-687b-11eb-93c0-b7726c78e381.png)

Or are you referring to a different page?
