### ISSUE TITLE
Make Multithreaded Terrain Rednering Default?

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica6#1233]
**Description**
There are frequent questions on #performance about poor FPS in E6 with otherwise decent systems; these are frequently addressed by changing the following in forge-client.toml:

alwaysSetupTerrainOffThread=true

I'm not clear that there is a downside to making this the default; if I understand correctly the potential downside is with low core count systems, which for lots of reasons probably won't run E6 particularly well anyway.

**Comment by Darkere** [comment]
There are issues with chunks not rendering or even only partially rendering with this option. Which is why it is not default.

**Comment by TemperedFool** [comment]
Interesting. If it's unstable I suppose making it the default doesn't make sense. I suppose we can just keep pointing those with FPS issues at it when they ask ^_^
