### ISSUE TITLE
Facing game crash when exploring

### ISSUE THREAD

**Issue by useenzhekoay** [NillerMedDild/Enigmatica6#1235]
**Modpack version**
0.3.13

**Describe the bug**
Crash when exploring.

**Logs**
[crash-2021-02-06_21.39.22-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/5936918/crash-2021-02-06_21.39.22-server.txt)
[crash-2021-02-06_21.50.59-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/5936919/crash-2021-02-06_21.50.59-server.txt)

**Screenshots**
No screensho.

**Comment by Darkere** [comment]
Duplicate of #813
