### ISSUE TITLE
Farmers Delight Cooking Pot Recipes

### ISSUE THREAD

**Issue by nekachan61** [NillerMedDild/Enigmatica6#1238]
Recipes for food using the Farmers Delight cooking pot do not pull in JEI. It was working in previous versions, but as 3.10+ it is no longer available.

**Comment by NillerMedDild** [comment]
I believe they had to disable this as it was causing issue within JEI.

**Comment by NillerMedDild** [comment]
Yup looks like it's temporary: https://github.com/vectorwing/FarmersDelight/issues/148

**Comment by vectorwing** [comment]
Hi there! The issue should now be fixed as of version 0.3.2 (and also in a recent JEI update).
