### ISSUE TITLE
Add Simple Farming seeds to the Engineer's Tools Power Bar Press

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#124]
It looks like most vanilla seeds have a tag labeled engineerstools:musli_bar_seeds. Would it be possible to add the Simple Farming ones to this tag as well? Thank you! 

Pic of wheat seeds with the tag: https://i.imgur.com/MMFKqK8.png

This allows the Muslee Melange Power Bar Press to take in the seeds to make the power bars it produces :)

**Comment by NillerMedDild** [comment]
I'm afraid Engineer's Tools is being removed :/
