### ISSUE TITLE
Can't join LAN world

### ISSUE THREAD

**Issue by DuckTheCow** [NillerMedDild/Enigmatica6#1241]
When trying to join my friends LAN world via Hamachi after updating from 0.3.9 to 0.3.13 I get a Failed to syncronise registry data with server error.

We have both reinstalled the modpack multiple times and it hasn't fixed it.
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5937393/latest.log)

We made one change to the quark config to disable Totems of Holding and added the corail tombstone mod. However these changes were made before the update and it was working fine.

**Comment by NillerMedDild** [comment]
Industrial Foregoing Milk Bucket and Quark Biotite Block is missing the one of your instances, that's the issue. Reinstalls should have fixed it though. I recommend you discard your changes and try again.

**Comment by DuckTheCow** [comment]
Didn't change anything. Having tested with creating a new world with worked. I believe the error was cause by the update from 0.3.9 to 0.3.13.

**Comment by NillerMedDild** [comment]
That sucks :/

**Comment by DuckTheCow** [comment]
We are gonna try and roll back to 0.3.9 to see if that fixes it.
