### ISSUE TITLE
Farmer's Delight Failed to Load Correctly - Error on Launch

### ISSUE THREAD

**Issue by farnoods** [NillerMedDild/Enigmatica6#1242]
Farmer's Delight gives an error on startup. Says it failed to load correctly. Have not added any mods.

Using Enigmatica 6 - 0.3.13 and OpenJDK 8 (Open-J9) from AdoptOpenJDK

**Comment by Darkere** [comment]
OpenJ9 is no longer a valid option for forge 1.13+.

That said Forge will crash with an error telling you that before any mods are loaded. As such come by on discord and bring the crash report :)

https://discord.com/invite/xPPwaFx
