### ISSUE TITLE
Rats & Rats: Ratlantis

### ISSUE THREAD

**Issue by Zaakjin** [NillerMedDild/Enigmatica6#1243]
https://www.curseforge.com/minecraft/mc-mods/rats
https://www.curseforge.com/minecraft/mc-mods/rats-ratlantis

**Rats** adds rats that can be tamed and used for some automation with mechanic's similar to Thaumcraft golems

**Rats: Ratlantis** is a lush, tropical land home to extremely dangerous and powerful mobs. Using materials and drops from this dimension, one can craft extremely powerful Rat Upgrades. 

Rats are cool. 

Check screenshots on mods page.

**Comment by NillerMedDild** [comment]
#587 
#647
