### ISSUE TITLE
Tetra Extractor Unification

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#1245]
**Modpack version**
E6 0.4.0

**Describe the bug**
Current Tetra Extractor uses the forge tag for the ore generation which spawns ores from Thermal, IE, Occultism ..etc.

**Logs**
N/A

**Screenshots**
N/A

**Comment by Ridanisaurus** [comment]
Gonna update the loot table to use EE Ores, and will add the missing ores

**Comment by r-mc2** [comment]
Can confirm:
<img height="300px" src="https://user-images.githubusercontent.com/36780233/107134265-79b65700-68be-11eb-8173-d1f0f6d2259e.png" />
<img height="300px" src="https://user-images.githubusercontent.com/36780233/107134270-83d85580-68be-11eb-9121-1b3e737885a8.png" />

**Comment by Ridanisaurus** [comment]
Yea, the fix is done, just testing it now, and then will PR it for the next version. Thanks for the confirmation.
