### ISSUE TITLE
better diving

### ISSUE THREAD

**Issue by kitkat498** [NillerMedDild/Enigmatica6#1253]
---------------------------->

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/better-diving
**Mod description**
Some highlights:
- reworked movement in water 
- reworked oxygen system 
- breaking speed in/under water is equal to breaking speed outside of water
- use diving equipment to move faster, mine faster and dive longer
**Why would you like the mod added?**
it makes the water a bit more interesting :)
**Screenshots if applicable.**

**Comment by NillerMedDild** [comment]
No thanks, I don't they we need any of these things in the back, vanilla and current mods have it covered :)
