### ISSUE TITLE
Mod Suggestion: ItemZoom

### ISSUE THREAD

**Issue by slashLyt** [NillerMedDild/Enigmatica6#1255]
Hey guys! 

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/itemzoom

**Mod description**
Adds a zoom view left from the inventory which shows a zoomed version for a block. 

**Why would you like the mod added?**
For building it helps a lot imo to see a zoomed version of the block. 

Im using the mod with 60% zoom instead of the default 80%. Here u can see the difference if needed.
https://imgur.com/a/6TnOYwN

**Comment by NillerMedDild** [comment]
Hmm I'm not sure. Let me sleep on it :P

**Comment by NillerMedDild** [comment]
Awful awful bit of sleep, but I like the mod so it'll be added in 0.4.0 :P

**Comment by theboo** [comment]
With itemZoom installed we cannot see the bees from resourceful bees in JEI. 
issue here https://github.com/mezz/ItemZoom/issues/25
