### ISSUE TITLE
Structurize

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica6#1261]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/timber-framing

**Mod description**
simple timber framing, but a medieval build style

**Why would you like the mod added?**
In E5 we had Structurize (dependency for minecolonies) that added these type of decorative blocks, would be nice to get some back.

**Screenshots if applicable.**
![all_timberframes](https://user-images.githubusercontent.com/13875/107221880-82b93c80-6a14-11eb-95c7-25f8b9868e4d.png)

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by Ridanisaurus** [comment]
To be honest, if something like this was to be considered, I would go for Structurize (without the Minecolonies as it's not a set dependency).
Structurize adds a lot of other amazing building blocks along side the timber framing (it actually has a lot more Timber Framed Blocks) such as the Shingle Roof (hands done one of the best Minecraft looking roofs in the game) and just an overall good mod for builders.

**Comment by hvdklauw** [comment]
I'm fine with that too :)

**Comment by Merlo17** [comment]
Didn't that have massive overhead when logging into a world? Or was it only minecolonies?

**Comment by Darkere** [comment]
That was structurize. But as far as I know this got reduced down to like 3 seconds with a forge fix in 1.16

**Comment by Ridanisaurus** [comment]
I just tested it with the dev instance, and it does increase the pack load time a little bit (no where as major as how it was in E5) and the world joining loads at around the same speed.

**Comment by NillerMedDild** [comment]
Will have a look at Structurize :)

**Comment by NillerMedDild** [comment]
I'm not a big fan of either Structurize or Simple Timber Framing, because I think adding so many blocks with small variations is an inefficient approach - It's pretty RAM intensive. I'm afraid this is a no.
