### ISSUE TITLE
Tallow

### ISSUE THREAD

**Issue by Toonlink264** [NillerMedDild/Enigmatica6#1263]
**Modpack version**
3.13
**Describe the bug**
tallow not unified. killing pigs with butcher knife gives quark tallow but others give occultism tallow, also no smelting recipe for tallow.

**Screenshots**
![image](https://user-images.githubusercontent.com/60859491/107240476-ddd14a80-6a79-11eb-8164-a800b53e9138.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, fixed in dev :)
