### ISSUE TITLE
Wrong EE ore being chosen for outputs

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#1266]
**Modpack version**
inDev

**Describe the bug**
The output unification script is returning odd results in some cases. Specifically Chunk > Ore crafting

Not really sure how to go about fixing this one other than a silly override script. But that doesn't really solve the issue with unify_outputs.js

**Screenshots**

chunk > chunk

![image](https://user-images.githubusercontent.com/9543430/107272778-3245dd00-6a1c-11eb-9057-e3c8452fc0c1.png)

chunk > gabbro ore

![image](https://user-images.githubusercontent.com/9543430/107272846-4ab5f780-6a1c-11eb-83b6-8e62fbef7eb8.png)

**Comment by shubutime69** [comment]
just wanna ditto this. this is a nightmare for Refined Storage autocrafting
