### ISSUE TITLE
Netherite Scrap Sand 

### ISSUE THREAD

**Issue by shubutime69** [NillerMedDild/Enigmatica6#1267]
**Enigmatica 0.3.13**

**Describe the bug**
Might wanna nerf Netherite Scrap Sand from Blood Magic. You can turn Ancient Debris into 5 Netherite Scrap Sand with the Enrichment Chamber, then smelt that into 5 Netherite Scrap. Basically 5x processing for Ancient debris, seems OP af. Netherite scrap sand isnt even in the JEI. We're playing on Enigmatica 6, 0.3.13.

**Comment by NillerMedDild** [comment]
Do you happen to get errors in the chat when you join? Netherite Scrap Sand should not be obtainable.

**Comment by shubutime69** [comment]
Yes. We get a kubejs error every time we boot up. 

![image](https://user-images.githubusercontent.com/78760780/107311446-5a553080-6a5c-11eb-99a2-67154e743c42.png)

**Comment by MuteTiefling** [comment]
Ah, then your pack didn't fully download. You'll want to reinstall. Alternatively, you can copy the kubejs folder from a new fresh instance or the server files and replace yours with it. Be sure to delete the old folder before copying the new one in place.
