### ISSUE TITLE
Possible list of structure datapacks

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica6#1269]
WIll update the list here as I find more, will checkbox them once I investigate them. For now I'm leaving this here as a todo list of sorts

Niller: Edited original to be able to update checklist status of issue. Hope you don't mind Merlo!
- [x] Desert: https://www.planetminecraft.com/data-pack/1-14-x-improved-desert-village-datapack/
- [x] ~~Plains: https://www.planetminecraft.com/data-pack/maquis-shrubland-village/~~
- [x] Savanna: N/A
- [x] ~~Taiga: https://www.planetminecraft.com/data-pack/mountain-villages-new-structure-no-replacements-4901901/~~
- [x] Snowy: N/A
- [x] Swamp: ~~https://www.planetminecraft.com/data-pack/swamp-villages/~~ Multiple errors and not maintained

**Comment by MuteTiefling** [comment]
That maquis shrub land one looks great from the screen shots at least

**Comment by Merlo17** [comment]
going mostly off screenshots because it's too late for me to investigate rn :P will go through each individually tomorrow. Some are definitively more promising than others but I just dumped everything on here really. I expected planet minecraft to have much more, not a lot of activity over there it seems like

**Comment by Dracos99** [comment]
if datapacks from PM are possible, have you looked at some of the ones from Baroque Obama?
some good ones (in my opinion):
https://www.planetminecraft.com/data-pack/minecraft-lake-towns/
https://www.planetminecraft.com/data-pack/abyssal-villages/
https://www.planetminecraft.com/data-pack/minecraft-farmsteads/
This one might not fit, but cool idea https://www.planetminecraft.com/data-pack/sky-villages-4913434/

**Comment by MuteTiefling** [comment]
Really like that abyssal villages one. That's a fun concept.

**Comment by Ridanisaurus** [comment]
Just at a quick glance, the `Improved Desert Village` and the `Shrubland Village` have my vote. 
The rest are cool, but I feel that leave a bit to be desired if I'm being honest. If we can find Village Replacement on the same level as these 2 for the rest of them, that would be amazing as mixing and matching the styles between highly detailed and flushed out with minimal could be quite stark in my opinion.

**Comment by Merlo17** [comment]
So you mean it's either all villages change or none of them? I'd be fine using the really good ones and keeping the other villages as default. It might be a bit contrasting but having some cool and some underwhelming is better than having all underwhelming imo.

**Comment by Ridanisaurus** [comment]
I was mostly saying we should use the good ones as a standard, and continue looking. I should have at least 1 free hour tonight, so I'll look into some other datapacks and see if I can find something along the same level of details with the Shrubland and Desert villages

**Comment by Ridanisaurus** [comment]
Okay, so here is my list:
- Desert: https://www.planetminecraft.com/data-pack/1-14-x-improved-desert-village-datapack/
- Plains: https://www.planetminecraft.com/data-pack/maquis-shrubland-village/
- Savanna: N/A
- Taiga: https://www.planetminecraft.com/data-pack/mountain-villages-new-structure-no-replacements-4901901/
- Snowy: N/A

Additional:
- Swamp: https://www.planetminecraft.com/data-pack/swamp-villages/

There are other datapacks I found online, but to be honest, I would rather stick to Planet Minecraft as it's a bit more trusted than 9minecraft.
For the missing ones, we can run another contest for builders on Discord to create a custom village houses with these 2 themes. 
Until then, the Snowy biome villages actually don't look half bad as they are, and for the Savanna, we can use the Plains one, and change some of the colour palette for it.
I'll download these ones, and investigate them in the game, and see how they look.

**Comment by Merlo17** [comment]
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

worth investigating for structures too. looks really promising and customizable

**Comment by Merlo17** [comment]
I've contacted all the authors for the datapacks rid mentioned, except for the desert one who already gives explicit permission, so we could include that one already

**Comment by Merlo17** [comment]
I still think the abyssal one here https://www.planetminecraft.com/data-pack/abyssal-villages/ is cool, I've tried it in game: the structures are a bit underwhelming but the overall ambiance is still really cool imo, it's worth a look.

I also haven't heard back from the other authors, what do we do if we don't get a reply back? I would lean towards including with credit anyways, since they're still publicly available with no indication that something like this wouldn't be allowed, asking was more us being nice. I've looked around but neither planet minecraft nor the packs themselves seem to use some kind of license unfortunately

**Comment by NillerMedDild** [comment]
Yeah it is pretty damn cool. The question is, how frequently does it spawn?

If they don't reply I think we should include them with credit, and remove them immediately if we're ever asked to of course.

**Comment by Merlo17** [comment]
I haven't tested that far honestly, I wonder if we can configure that with TF?

**Comment by NillerMedDild** [comment]
No-hooo idea :P

**Comment by Merlo17** [comment]
Testing that rn. The ship one is weird though, I have no clue how to install it in game because I'm dum

**Comment by NillerMedDild** [comment]
Mm don't, I think one of those folders is supposed to replace your regions.

**Comment by Merlo17** [comment]
agreed, rip boats. I also couldn't get the other one to load with kube but that's probably because I'm dum x2 so I'd let you try it.
My guess is we can't use TF to control them since it seems to be editing the biome itself and not use a structure which might be a red flag. In my vanilla world I used for testing they weren't too common however

**Comment by NillerMedDild** [comment]
The way I see it it's not feasible to use village datapacks that add villages, as that would require editing biome.jsons for all biomes we want to hold the villages. Which also means, we need to make sure biome jsons stay up-to-date between BYG and TF updates :/

In the end, only village replacements are viable additions to E6 imo. Unless a mod could handle where to place the villages for us, that would be ideal.

**Comment by slashLyt** [comment]
What kind of mod exactly is needed? Basically something which add the Structure to the `BiomeGenerationSettings.Builder` ? I would assume it should be possible if the datapack adds the village to `StructureFeature` and `BiomeGenerationSettings.Builder` can be manipulate on runtime before generation.

**Comment by NillerMedDild** [comment]
I guess so, but I don't know to be honest :)
