### ISSUE TITLE
Simple Tomb

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica6#1270]
https://www.curseforge.com/minecraft/mc-mods/simple-tomb

One of the most repeated complaints in the e6 channel is the quark grave. Simple tomb is a fork of just the grave portion of corail tombstones, lothrazar forked it in to it's own mod after corail was open sourced and handed over to darkhax.

the only thing that is missing is the restore inventory commands but i spoke to lothrazar about it the other day and he apparently just missed that in the fork lol so should be added very soon.

anywho, would be nice for players who die over the void or something to have a base to build blocks around, as well as the restore inv command.

The only thing we are using from oddities now is the grave so this would be a 1:1 swap

https://github.com/Lothrazar/Tombstone-Fork/issues/7

**Comment by NillerMedDild** [comment]
Sounds good to me - Do you know if it places armor, baubles, backpacks etc in correct slots?

**Comment by theboo** [comment]
I haven't gotten that far in to testing it yet... Will test more tonight

**Comment by NillerMedDild** [comment]
not Baubles: https://github.com/Lothrazar/Tombstone-Fork/issues/8
