### ISSUE TITLE
[E6-0.3.9] Infinite power via Powah

### ISSUE THREAD

**Issue by Elvarion** [NillerMedDild/Enigmatica6#1274]
**Modpack version**
Enigmatica6 0.3.9
(If this has been fixed in the new version, just close this)

**Describe the bug**
Got a 'Powah' [Energy Cell (Nitro)] from a quest reward.
It came with full charge and has infinite energy.
Placed it down a day ago (irl), and its still at max capacity

**Screenshots**
https://prnt.sc/yu1t88 - Put a energy trash can next to it
https://prnt.sc/yu1vpy - Its outputting, but still full

**Comment by MuteTiefling** [comment]
That's not showing how much it's extracting, it's showing the max extraction rate. You'll note that even though the two batteries below are connected with a universal cable, the one on the right isn't actually receiving anything. 

![2021-02-09_12 55 06](https://user-images.githubusercontent.com/9543430/107406127-1737a380-6ad6-11eb-8204-623bb671fd0e.png)

![2021-02-09_12 55 10](https://user-images.githubusercontent.com/9543430/107406129-17d03a00-6ad6-11eb-9192-43470e115a6d.png)

To get this to actually extract, you need to do one of two things
1) Set the Energy Cell to Output only on the side where the cable is connected. 
2) Set the Universal Cable to Extract only on the side it's touching the Powah Cell. 

Similarly, if you are feeding energy into a Powah Cell with a Universal Cable, you need to set the side to input only or set the cable to input only.
