### ISSUE TITLE
Better End Compat

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica6#1276]
TODO list:

- [x] Add alloy recipes to better end furnace
- [x] Add better end alloys to other alloying machines
- [x] Hide duplicate items (ender dust) and replace input with the EE one (annoyingly it's not tagged as forge:dusts/ender so we gotta replace)
- [x] sapling compat with phyto/cloche/botany pots using proper grass/moss/mycelium for each sapling
- [x] Tetra Material
- [x] Tetra Replacements
- [x] Unify their sulfur (Remove it and it's recipes)
- [x] Add missing tags

**Comment by MuteTiefling** [comment]
I'm working on the pots/cloche/insolator integration. Should have it done tonight.

**Comment by MuteTiefling** [comment]
#1282

**Comment by MuteTiefling** [comment]
Leaving in their sulfur as it is actually rather unique. It grows on brimstone soaked in water and is harvested as a crystal with silk touch. I did add it to the sulfur gem tag, however, so that it can be ground down to sulfur dust in various recipes. 

There are more tags that need doing, I think.
