### ISSUE TITLE
Abnormal Mods

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1277]
Alright, alright. I cave.

We're adding the following Abnormal mods:

- [x] [Upgrade Aquatic]( https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic)
- [x] [Atmospheric](https://www.curseforge.com/minecraft/mc-mods/atmospheric)
- [x] [Autumnity](https://www.curseforge.com/minecraft/mc-mods/autumnity)
- [ ] [Environmental (Not yet released)](https://github.com/team-abnormals/environmental/issues)

Which means we need another large compat pass. Sorry guys :P

**Comment by Merlo17** [comment]
dumb compat dirty work? don't mind if I do :P

**Comment by Merlo17** [comment]
Also as far as I can tell swamp and bloomful are on 1.15 still but are being ported and combined into one mod at https://github.com/team-abnormals/environmental. something to keep an eye on I guess, not on curse yet

**Comment by CletusMAngo** [comment]
YAYYYYYYYY MY EFFORTS WERE SUCCESSFUL 
Thanks so much guys!

**Comment by MuteTiefling** [comment]
Gonna start collecting data for compat

- [ ]  Trees
- [ ]  Wood Types
- [ ]  Growables
- [ ]  Dyes
- [ ]  Other materials (already noticed new sandstone types that need crushing recipes)

**Comment by CletusMAngo** [comment]
Environmental just released for 1.16 https://www.curseforge.com/minecraft/mc-mods/environmental

**Comment by CletusMAngo** [comment]
They also added a mod that adds integration for Abnormals food and Farmers delight  
https://www.curseforge.com/minecraft/mc-mods/abnormals-delight
