### ISSUE TITLE
Mod Suggestion: MrCrayfish's Furniture Mod

### ISSUE THREAD

**Issue by CrownJoker** [NillerMedDild/Enigmatica6#1279]
Would it be possible to add in MrCrayfish's Furniture Mod?

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod

**Mod Description**
Includes over eighty pieces of furniture, with working functionality in some blocks.
Also has a mail system which allows send of items and blocks to players around servers.

**Why would you like the mod added?**
I've always enjoyed this mod's blocks/item appearances, and way of incorporating a bit of functionality into it's items compared to some other decorative mods.

**Comment by NillerMedDild** [comment]
duplicate of #203 :)
