### ISSUE TITLE
Certus Quartz unobtainable

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#128]
**Modpack version**
Input modpack version here
0.2.6

**Issue**
Input short description of the issue here
Everything still uses ae2 certus, but mining only gives emandatus certus
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Emendatus Certus works just fine for me, may I have your latest.log please? Re-installing ought to fix this :)

**Comment by MuteTiefling** [comment]
https://gist.github.com/MuteTiefling/821276a2b3a0e675cb5614924e7bf0c4

It's a fresh install. I switched over to GD launcher from Twitch to be able to update, so I just installed there and copied my world save over. 

I'll try reloading, but just prior to logging out I tried using the emendatus certus to make a shovel and it wouldn't take it.

**Comment by Darkere** [comment]
The only thing I found that might be problematic in there is
`[13Aug2020 10:01:23.651] [Render thread/WARN] [KubeJS Server/]: Error creating recipe appliedenergistics2:kubejs_generated_112_minecraft_air[appliedenergistics2:grinder]: com.google.gson.JsonSyntaxException: Unknown item tag 'forge:ingots/certus_quartz'`

forge:ingots/certus_quartz ?

**Comment by MuteTiefling** [comment]
Trying to install a second instance in GD launcher in order to start a fresh world to see if that makes any difference, but it seems to be having trouble... been stuck at 100% for like an hour now.

**Comment by MuteTiefling** [comment]
So I've installed a new instance, made a new world. Emendatus Certus has no uses other than to make blocks or to grind it to dust. 

![image](https://user-images.githubusercontent.com/9543430/90174648-5168f800-dd74-11ea-926c-e9bba911d9a3.png)


[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5070901/latest.log)

**Comment by NillerMedDild** [comment]
Shit, I was so sure it worked for me :/ I'll get it fixed, thanks for your help as always!

**Comment by NillerMedDild** [comment]
All recipes using Certus either uses a special AE2 tag or the item explicitly, I just expecting them to use forge tags, my bad :(

**Comment by NillerMedDild** [comment]
Alright I fixed it in-dev, I'll get a build out once the CurseForge API starts behaving again :) while we wait, you can copy the added lines from the above commit into the files it mentions, to remedy the issue.
