### ISSUE TITLE
Granite and Diorite not generating naturally in terrain

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#1280]
**Modpack version**
Enigmatica 6 v0.3.9

**Describe the bug**
I've played over a week on a world made using the "Realistic" terrain option, and have also checked/explored a "Default" terrain world. I have not come across _any_ naturally-occurring minecraft:granite or minecraft:diorite that wasn't part of a structure. Andesite does generate in occasional patches but seems to be rare.

**Logs**
n/a

**Screenshots**
![no-granite](https://user-images.githubusercontent.com/1171633/107450985-9b545000-6b03-11eb-8141-3bac7890ab7e.png)

**Comment by theboo** [comment]
This is actually by design... You can make diorite/granite using the randomized stone gen, and then when u get a piece, use the stone gen for that stone

**Comment by theboo** [comment]
Check recipes for granite in jei

**Comment by mouseas** [comment]
What, why is this by design? And if so, why is Andesite left in but only shows up rarely?

**Comment by MuteTiefling** [comment]
Mostly because granite and diorite look terrible in world generation.

**Comment by theboo** [comment]
and andesite is included because it is required for the create mod, for builders who want other stone variations, we have generator recipes for most any stone type

**Comment by florensie** [comment]
Is there a way to re-enable this? Generators are boring, slow and unintuitive. They might look like shit underground sometimes but they're pretty good building blocks.

**Comment by Merlo17** [comment]
They will be available in the material stoneworks factory in the next update I believe. As for right now you can very easily automate it with pedestals after you get one piece

**Comment by NillerMedDild** [comment]
I mean, Granite is craftable still, vanilla-style. But yes, you can re-enable it by editing the KubeJS worldgen scripts.

**Comment by theboo** [comment]
FYI pedestals stone gen can produce 2 stacks per tick fully upgraded
