### ISSUE TITLE
Add TEG values to Dry Ice

### ISSUE THREAD

**Issue by moostoet** [NillerMedDild/Enigmatica6#1285]
**CurseForge Link**
None

**Description**
Dry Ice from Powah should have a temperature value to work with the Thermoelectric Generator from Immersive Engineering.

**Why would you like this added/changed?**
Other ice types work with the Thermoelectric Generator, so Dry Ice would be a nice addition to the roster. (This could also possibly extend into adding other blocks to the list of temperature values).

**Screenshots if applicable.**
N/A

**Comment by OneLemonyBoi** [comment]
To accomplish this goal it took:
1 PR To. Immersive Engineering
1 PR to Powah
and...
1 PR to Forge themselves

**Comment by OneLemonyBoi** [comment]
but its almost done :)
