### ISSUE TITLE
machine access

### ISSUE THREAD

**Issue by darell35** [NillerMedDild/Enigmatica6#1286]
**Modpack version**
0.3.13

**Describe the bug**
I am having trouble accessing the vanilla furnace and the metallurgic infuser and the enrichment chamber

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5964138/latest.log)
[latest.zip](https://github.com/NillerMedDild/Enigmatica6/files/5964146/latest.zip)

**Screenshots**

**Comment by Darkere** [comment]
try restarting your client

**Comment by Darkere** [comment]
Assuming duplicate of #667
