### ISSUE TITLE
Resouece Bee

### ISSUE THREAD

**Issue by RickyGeo** [NillerMedDild/Enigmatica6#1287]
Modpack version 1.16.4

**Describe the bug**
1. My bee dispawn 
2. when i get in in jar it have a chance gone when i get it.
3. when I put in in some room they dispawn
**Logs**

**Comment by Ridanisaurus** [comment]
- 1.16.4 is the Minecraft version, and not the Modpack version. The latest Modpack version is E6 0.3.13m which is on 1.16.5. If you are on an older version, then please update.
- Bees will despawn if they can't find a valid Nest or a Flower within a specific set of time. Please make sure they are able to access an empty hive, and are able to access a flower for pollination.

**Comment by RickyGeo** [comment]
yop ty..
