### ISSUE TITLE
Tetranomicon

### ISSUE THREAD

**Issue by Syrikal** [NillerMedDild/Enigmatica6#1292]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/tetranomicon

**Mod description**
Adds Tetra compatibility to materials from Better End, BYG, BOP, Enderite, Quark, and Wyrmroost. (Does not depend on these mods, so it works fine if only a few are installed!) 

**Why would you like the mod added?**
Thought it might be useful- I know a few of these mods are in Enigmatica.

**Comment by NillerMedDild** [comment]
Looks awesome, very high chance this will be added in 0.4.0 - I'll check it out in-game asap :)

**Comment by CletusMAngo** [comment]
Also rly good for when wyrmroost gets added even tho most of its materials are getting removed

**Comment by Merlo17** [comment]
I don't think we plan on adding wyrmroost for now at least really

**Comment by CletusMAngo** [comment]
Yeah i was saying when the dimension gets added in the future

**Comment by Syrikal** [comment]
And if you're interested, then the Tetra/Undergarden Patch got a minor update as well, to allow Undergarden tools to be directly modified in workbenches.

**Comment by NillerMedDild** [comment]
I believe we're already on that version - Any idea when the need for the added datapack v1.2 brings will stop? :P

**Comment by Syrikal** [comment]
I'll fix that as soon as forge fixes the bug that makes Tetra load after my mod and overwrite my module folks :P
