### ISSUE TITLE
Save Your Pets interferes with Occultism drikwing summoning method.

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1293]
Enigmatica 6 0.3.13 (Official E6 server)

The occultism drikwing summoning indicates that sacrifice of either a parrot or a parrot familiar is required.  However the parrot familiar is considered a 'pet' and so is prevented from dying by the Save Your Pets mod.  I tried waiting the allotted time to expire for the parrot to actually die, but it is apparently not still considered a player caused death and so is not accepted by the Occultism ritual.

**Comment by theboo** [comment]
this is fixed in dev/0.4, occultism added a ritual for a wild parrot in latest release. Until then, the only option is to use a wild/untamed parrot

https://github.com/klikli-dev/occultism/commit/23e4a78e5f89fbfd503ec8ceb02d66c2bcc2145b
