### ISSUE TITLE
Server-Crash because of Ars_Nouveau

### ISSUE THREAD

**Issue by JayOlino** [NillerMedDild/Enigmatica6#1295]
**Modpack version**
0.3.13
**Describe the bug**
A User has hit a Carbuncle  with a Mana-Berry from ars_nouveau.
The Carbuncle had a Mana-Berry aswell.
Right after the Hit, the complete Server crashed.

We reproduced it 3 Times.

To stop the server crash, we killed every entity after a restart.

Server has following specs: 
AMD Ryzen 5 3600 Hexa-Core
2x 512 GB NVMe SSD
16GB of 64 GB DDR4  
**Logs**
Crash-Log:
https://pastebin.com/FK3cdJyt

**Comment by NillerMedDild** [comment]
Thanks for the report, the mod author has fixed this but not yet released it: https://github.com/baileyholl/Ars-Nouveau/issues/176
