### ISSUE TITLE
0.2.6 Botania rendering crash

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#130]
Pack version: 0.2.6

What happens?: I started to type glass into an AE2 crafting interface, after typing gla it crashed the game. Crash reports seem to point to Botania as the reason. This report here seems to point to Forge being at fault, though it could also be optifine. I'm gonna look into this a bit more, but wanted to get this here. Botania has been updated past what we're on now in the pack to fix this. https://github.com/Vazkii/Botania/issues/3387
[crash-2020-08-13_16.47.13-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/5071379/crash-2020-08-13_16.47.13-client.txt)

**Comment by Shindur** [comment]
Seems downgrading forge to 32.0.106 works fine for this.

**Comment by NillerMedDild** [comment]
Thanks for letting me know, I'll update Botania asap :)

**Comment by AngellusMortis** [comment]
[Optiforge](https://www.curseforge.com/minecraft/mc-mods/optiforge) solved this issue for me. 

[Optifine 1.16 is compatible with Forge 32.0.98](https://optifine.net/changelog?f=OptiFine_1.16.1_HD_U_G2.jar) so 32.0.108 probably introduce some breaking thing that Botania and AE2 are using.
