### ISSUE TITLE
dupe

### ISSUE THREAD

**Issue by Del1n0** [NillerMedDild/Enigmatica6#1302]
**enigmatica 6**

**Describe the bug**
if i place an comparator/repeater on a wall and then take it off i get one comparator/repeater extra

**Comment by NillerMedDild** [comment]
You're using a very old version, please update.

**Comment by Del1n0** [comment]
huh but i downloaded the newest version of 1.16.4

**Comment by NillerMedDild** [comment]
The newest version is for Minecraft 1.16.5, modpack version 0.3.13: https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/3187089 :)

**Comment by Del1n0** [comment]
k thx
