### ISSUE TITLE
Exit code 0 crash when loading an existing world

### ISSUE THREAD

**Issue by Random8001** [NillerMedDild/Enigmatica6#1308]
When loading in an existing world my game crashes. I am still able to create a world and play in that but loading a world won't work.

Having the game output log open the last message it gives before the crash is: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

I'm dedicating 8gb of ram to the game with 32gb in total on the pc. I don't know what could be the problem and am very confused. I will try reinstalling the pack but the issue still exists even if the reinstall fixes it.

**Comment by theboo** [comment]
do you have a crash report?
