### ISSUE TITLE
Can't craft the 16384k fluid storage part on 0.2.6

### ISSUE THREAD

**Issue by mrDLSable** [NillerMedDild/Enigmatica6#131]
You have to craft the drive and then extract the part from the drive...

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Fixed in-dev and made a pull request to fix the mod's recipe: https://github.com/MelanX/ExtraDisks/pull/17
