### ISSUE TITLE
Enable cosmetic curio slots

### ISSUE THREAD

**Issue by ochotonida** [NillerMedDild/Enigmatica6#1310]
Curios has an option to enable cosmetic slots (https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users). 
Most mod authors  leave these disabled, either because none of the curios they add are cosmetic, or because they only use a small subset of the available slots types, and it looks a bit out of place when some slots types have cosmetic slots while others don't. 

Since this modpack has multiple mods which add cosmetic curios (Botania, Artifacts, Industrial Foregoing, just to name a few), these would pair nicely with the cosmetic armor mod that's already present.

**Comment by NillerMedDild** [comment]
Sure thing!
