### ISSUE TITLE
BYG stone missing duplicating cobble/stone gen recipies

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1315]
**Modpack version**
0.3.13

**Describe the bug**
BYG stone/cobblestone, eg dactite/red rock/soapstone/scoria/sandstones, are missing the duplicating cobblegen recipes, where placing one of the stone under the cobblegen will make more of the same stone. They only have the iron/diamond block recipes.

**Comment by Merlo17** [comment]
I am seeing the correct recipes in dev at least, I'm unsure if this was fixed at some point, but it's more likely that something went wrong in your files. Can you try running` /kubejs errors`?

**Comment by NillerMedDild** [comment]
Those particular recipes come from the `cobblegenrandomizer-common.toml` config, so maybe something went wrong there.

**Comment by Rodg88** [comment]
Checked the config in Master and Dev branches, and does look like it's been fixed in dev already
