### ISSUE TITLE
Game Crash in Initial Opening

### ISSUE THREAD

**Issue by Candice0730** [NillerMedDild/Enigmatica6#1316]
I keep getting GLFW: Failure to find port for display, Exit code: 255. Is this because of incompatibility with a M1 MacBook? How do I solve this?

**Comment by Darkere** [comment]
Try adding `-Dfml.earlyprogresswindow=false` as java argument.

**Comment by Candice0730** [comment]
How and where do you add that?

**Comment by TemperedFool** [comment]
@Candice0730 head over to the Discord as the bot suggests, but I have the server running on a M1 mini, so that likely isn't the issue.
