### ISSUE TITLE
Artifacts Scarf of invisibility 

### ISSUE THREAD

**Issue by Chtholly-dev** [NillerMedDild/Enigmatica6#1322]
*0.3.13**

**Describe the bug**
There is a bug with the Scarf of invisibility at the moment where even if you have no armor on you and nothing in your hand mobs can still see you no problem.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by MuteTiefling** [comment]
Honestly, the fact the scarf remains visible seems more like an intentional troll than a bug 😜

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it.

**Comment by NillerMedDild** [comment]
Neither me nor the mod dev could reproduce this issue :)
