### ISSUE TITLE
ENTER THE BUMBLEZONE

### ISSUE THREAD

**Issue by Angular-Angel** [NillerMedDild/Enigmatica6#1327]
**https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge**

**Mod Description**
The bumblezone is an alternate dimension that can be entered by using an ender pearl on a beehive. It adds a number of new bee accessories, features compatibility with several other bee mods, and is generally kind of awesome looking.

**Why would you like the mod added?**
THE BUMBLEZONE. 'Nuff said. XD

I mean, we don't really need this, but it IS very cool.

**Screenshots if applicable.**
Behold: https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge/screenshots

**Comment by NillerMedDild** [comment]
While it's cool it's a bit sillier than what I usually like to add :P will think about it!

**Comment by Angular-Angel** [comment]
I mean it's a bit silly, but I don't think it's any sillier than the resourceful bees, and those are in. :/

**Comment by NillerMedDild** [comment]
Fine point 😄

**Comment by Merlo17** [comment]
I don't particularly like this one tbh, it feels a bit boring and underwhelming since it adds very few things to make up a whole dimension. On the other side, since it is all relegated to its own dimension players could just completely ignore it so it's really whatever

**Comment by Ridanisaurus** [comment]
I have to agree with Merlo on this one. It's extremely underwhelming, and we already have enough Bee content. 
Once we go for the custom dim idea, we could look into adding out own Honey based biomes, with honey flows and honeycomb blocks ..etc.

**Comment by NillerMedDild** [comment]
I've landed on a no for this :)
