### ISSUE TITLE
Quantum Storage items uncraftable

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#133]
**Modpack version**
0.2.6

**Issue**
Seems that the custom 'hard' recipes are no longer loading properly. The Quantum Tank and Quantum Storage items are simply uncraftable now. 

**Logs**

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5074479/latest.log)

**Comment by mrDLSable** [comment]
Can confirm. The crates and trash can are still craftable but the storage units are not.

**Comment by NillerMedDild** [comment]
Re-added the recipes, no idea where they went, code was poof :P
