### ISSUE TITLE
Infinite Exp Bug

### ISSUE THREAD

**Issue by fruitytoast** [NillerMedDild/Enigmatica6#1330]
**Modpack version**
Enigmatica 6 - 0.3.13

**Describe the bug**
If you put a torch on the top part of a mob spawner, you can farm it for infinite experience. It never breaks when you attack it.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I can't reproduce this, every spawner I've found breaks when I break it - Where did you find the spawner with this issue? :)

**Comment by fruitytoast** [comment]
Hi ya, ok so we discovered it's not actually putting a torch on top, but having the enchantment "acquisition" that stops it from breaking.

**Comment by fruitytoast** [comment]
Ah and thats from the mod charm which has nothing to do with the modpack, my bad :P

**Comment by NillerMedDild** [comment]
Heh alright :P
