### ISSUE TITLE
Diet

### ISSUE THREAD

**Issue by ochotonida** [NillerMedDild/Enigmatica6#1333]
https://www.curseforge.com/minecraft/mc-mods/diet

**Mod description**
Diet allows the creation and management of dietary food groups, which can be used to apply various effects, similar to Nutrition

**Why would you like the mod added?**
It's a very configurable alternative to Nutrition, which hasn't been updated past 1.12

**Comment by NillerMedDild** [comment]
Looks very well made, will consider it, thanks :)
