### ISSUE TITLE
When you click on the quest for anything it crashes

### ISSUE THREAD

**Issue by Master2Mind88** [NillerMedDild/Enigmatica6#1334]
**Modpack version**
Current Dev Relese for 4.0,0
**Describe the bug**
When you click on the quest for anything it crashes.

**Logs**
https://pastebin.com/9L2xLGgt

**Screenshots**
https://clips.twitch.tv/RudePeppyRatAMPEnergyCherry-jyx_FClkTyi5aD5y

**Comment by NillerMedDild** [comment]
I'm fairly certain this is fixed in a new version of ItemFilter, will update asap :)

**Comment by Master2Mind88** [comment]
Can you message me on Discord when you want me to try it again?

**Comment by NillerMedDild** [comment]
Should be fixed now, have yet to verify myself though, launching now :)

**Comment by NillerMedDild** [comment]
Yup, works now :)
