### ISSUE TITLE
Wormhole (Portals)

### ISSUE THREAD

**Issue by joshuathomas2** [NillerMedDild/Enigmatica6#1335]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/wormhole-portals

**Mod description**
Allows the player to make portals at a cost of RF and some of the mod's blocks.

**Why would you like the mod added?**
Helps the player get around to different places. I think this mod would be super cool, but I get the feeling that it might be content overlap. I figured I would post it anyways just to see what you guys think though.

**Screenshots if applicable.**
Here is a video of direwolf tinkering with it a bit: https://youtu.be/on_F1oZJ4hs?t=737

**Comment by NillerMedDild** [comment]
Maybe for Expert mode down the line, but at the moment I see it only as content overlap tbh. Thanks for suggestion though :)
