### ISSUE TITLE
Tetra's hammer not creatable with BYG Cika planks/hammers not searchable in JEI

### ISSUE THREAD

**Issue by shibeobi12** [NillerMedDild/Enigmatica6#1339]
**Modpack version**
0.3.13
**Describe the bug**
I'm unable to search for Tetras hammers, and when creating the first one it does not work with certain BYG tree types.

![image](https://user-images.githubusercontent.com/50844560/108437277-389d3b80-720a-11eb-9e53-a799ee61fcfa.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
