### ISSUE TITLE
Crash during Resource Pack activation

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#134]
**Modpack version**
E6 0.2.6

**Issue**
The game crashes completely when attempting to activate any resource pack, and it is related to a bug in AquaCulture. Seems to be fixed in 2.0.18 version of the mod.
https://github.com/TeamMetallurgy/Aquaculture/issues/130

**Logs**
https://pastebin.com/HEvCm3ju

**Comment by mrDLSable** [comment]
Looks like Aquaculture-1.16.1-2.0.18.jar fixes this.
