### ISSUE TITLE
Replace FTB Chunks Map with JourneyMap

### ISSUE THREAD

**Issue by TheAndrata** [NillerMedDild/Enigmatica6#1340]
**CurseForge Link**
[https://www.curseforge.com/minecraft/mc-mods/journeymap](https://www.curseforge.com/minecraft/mc-mods/journeymap)

**Description**
JourneyMap was recently updated to support 1.16 and has a lot more functionality than the current FTB minimap being used.

**Why would you like this added/changed?**
While FTB Chunks map is great and offers basic features, it’s definitely lacking in some areas. For one, there is no cave mapping which is extremely handy when underground. JourneyMap’s way pointing is also miles ahead of FTB Chunks. Being able to simply list your waypoints instead of having to scroll around and hover over each dot to find something is a great QoL feature. For the base kitchen sink pack, FTB Chunks map works fine but I feel E6E would benefit more from JourneyMap overall when the time comes.

**Comment by NillerMedDild** [comment]
We'll think about it, thanks for the suggestion :)

**Comment by TheAndrata** [comment]
Absolutely understandable, just wanted to throw it out there since it was updated. Thanks for taking it into consideration!

**Comment by Rodg88** [comment]
I've added it to my instance, and have noticed more lag when flying around, chunks not loading etc. So maybe not pack ready yet, but it is also easy to add yourself with minimal mod interactions etc for people who want to.

**Comment by Merlo17** [comment]
What worries me a little is that it would be more of a temporary solution until FTBChunks eventually evolves and gets more features to be on par with other map mods. It sure would be really nice now (and I'd probably add it to my own instance tbf), but imo it might be even worse to have it in the pack and then have to remove it later on, players would lose all waypoints/saved data. Now when and even if FTBChunks gets more features is another discussion, and depending on how long we think that would be we could look into adding it. Same could be said for Xaero's I guess, but everyone has their preference there so it's nice for map mods to be client side only, so any player can just choose the one they like.

**Comment by theboo** [comment]
I mean... I'm not arguing for JM to be in the pack (even though I'll prolly use it too)... Buuuuut... Do we really think the ftb map is gonna be updated before the next e6 big world breaking update? Lmao

**Comment by theboo** [comment]
There are bonuses to it being in the pack tho vs client side... It does have some nice server side options including admin options

**Comment by NillerMedDild** [comment]
Just to be clear JM would not replace the FTB Chunks map, the FTB Chunks map would just be disabled :P

**Comment by Akaitatsu** [comment]
Xaero's reportedly performs better than JourneyMap, at least older versions, and there is a 1.16 release.

Is there a alternative to FTB Chunks that just does chunk claiming and loading? If you're not going to use all the features of FTB Chunks, it might make sense to reduce the overhead and replace with a simpler mod.

@NillerMedDild , you're doing great work. I tried creating a 1.15 mod pack significantly smaller than this and was never able to get performance anywhere close to what you have done here.

**Comment by NillerMedDild** [comment]
> Is there a alternative to FTB Chunks that just does chunk claiming and loading?

Not afaik, and FTB Chunks is tried and tested.

Thank you, we try 😄

**Comment by Rodg88** [comment]
I will note that after the journeymap update on the 2nd of march, it does seem to be faster. I've been using it since then with no real issue.
