### ISSUE TITLE
Recutting with stonecutter

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1342]
**Description**
Recipes for the stonecutter to enable alreay "cut" stones to be recut. Could be an oredict list on the input to allow any of the 1:1 stonecutter crafting results for the particular stone. Eg, allowing polished variants to be put into the stonecutter to re-craft them into bricks.

**Why would you like this added/changed?**
Would allow the stonecutter to act like chisel used to, being able to change between block patterns freely.

**Comment by NillerMedDild** [comment]
Sure that seems reasonable, we'll have a look at setting that up :)

**Comment by NillerMedDild** [comment]
After having looked into this a bit, I realize that this would be extremely time consuming, the is no fast or easy way to find all these recipes, and they would all have to be manually added. I'll gladly apply the change if you find the stones that should apply to though.

**Comment by Rodg88** [comment]
Ok, I've looked through byg as well now, and if you were going to refactor the script anyway, here's the relevant blocks:

soapstone_cutables:
byg:soapstone
byg:polished_soapstone
byg:soapstone_bricks
byg:soapstone_pillar
byg:soapstone_tile

dacite_cutables:
byg:dacite
byg:dacite_bricks
byg:dacite_pillar
byg:dacite_tile

+ one way byg:dacite -> byg:dacite_cobblestone

+ one way byg:rockey_stone -> minecraft:cobblestone

red_rock_cutables:
byg:red_rock
byg:red_rock_bricks
byg:mossy_red_rock_bricks
byg:chiseled_red_rock_bricks
byg:cracked_red_rock_bricks

remove recipe ids: byg:(null/mossy_/cracked_)red_rock_(slab/wall/stairs)_from_stonecutting (they're all duplicates)

byg_scoria_cutables:
byg:scoria_stone
byg:scoria_pillar
byg:scoria_stonebricks

+ one way byg:scoria_stone -> byg:scoria_cobblestone

+ uncomment the recipes to swap between create and byg plain scoria I put in the original script if wanted.

byg_(black/white/blue/purple/pink)_sandstone_cutables:
byg:(black/white/blue/purple/pink)_(null/chiseled_/cut_/smooth_)sandstone

**Comment by NillerMedDild** [comment]
Hmm it seems I won't have time to refactor the script in the near future, could you perhaps add the above blocks to the existing script @Rodg88? :)

**Comment by Rodg88** [comment]
no problem!
