### ISSUE TITLE
Farmer's Delight knives not shown in fish fillet recipes

### ISSUE THREAD

**Issue by tplc10** [NillerMedDild/Enigmatica6#1343]
**Modpack version**
0.3.13
**Describe the bug**
Farmer's Delight knife not in fish fillet recipes

**Screenshots**
The only crafting recipe using the Farmer's Delight knife:
![javaw_2021-02-19_10-55-35](https://user-images.githubusercontent.com/18743032/108535474-fecb4400-72a0-11eb-96ae-dd4e768576ec.png)
but this recipe using the Farmer's Delight knife works:
![javaw_2021-02-19_10-57-28](https://user-images.githubusercontent.com/18743032/108535734-418d1c00-72a1-11eb-9f81-7b4827ef32b0.png)

**Comment by NillerMedDild** [comment]
Fixed in-dev, but thanks for the report :)
