### ISSUE TITLE
Natures Aura Imperceptible Builder unable to place items in claimed chunks

### ISSUE THREAD

**Issue by EvilGrinUK** [NillerMedDild/Enigmatica6#1344]
Mod pack version - 1.16.5

Steps to reproduce - 

Enable FTB Chunk claiming in a chunk
Place a Natures Aura Imperceptible Bulder in the chunk
Set up the Builder to place oak saplings on grass (item / block might not matter?)
The block will make a noise as if placing the item but is fails to do so.
(Optional) Disable the chunk claim and the block can now place oak saplings.

**Comment by NillerMedDild** [comment]
You should be able to set it as an ally through FTB Chunks :)

**Comment by EvilGrinUK** [comment]
Yes. There were a couple of 'fake players' requesting permission to my claim. Once I trusted them that appears to fix it.
