### ISSUE TITLE
[Mod suggestion] Enhanced Mushrooms

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#1347]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/enhanced-mushrooms

**Mod description**
It adds a wood decorative set for each of the vanilla minecraft mushrooms and quark glowshrooms, and also makes stem a bit easier to harvest.

**Why would you like the mod added?**
The decorative blocks are nice, though since it's only decorative I understand if it's not included.

Also of the updated and released Team Aurora mods it's the only one I'd suggest since Fruitful would overlap and I don't know if Better Badlands adds enough.

**Screenshots if applicable.**
https://www.curseforge.com/minecraft/mc-mods/enhanced-mushrooms/screenshots

**Comment by Merlo17** [comment]
I'm honestly not the biggest fan myself. It doesn't make too much sense thematically to me and I don't think we're short on plank colors and variants. It seems like mostly redundant content or more maintenance for us.
Ironically I find Better Badlands (https://www.curseforge.com/minecraft/mc-mods/better-badlands) much more interesting, it'd fit with our new TF worldgen well looking at the curse page

**Comment by NillerMedDild** [comment]
I'm not really feeling either tbh :P
