### ISSUE TITLE
Add CC:Tweaked (Computercraft)

### ISSUE THREAD

**Issue by mrDLSable** [NillerMedDild/Enigmatica6#135]
The main reason I would like this is to have a big screen in my base with a lot of information displayed on it. Several alpha releases have been made for 1.16.1 which can be found here: https://github.com/SquidDev-CC/CC-Tweaked/releases and here: https://www.curseforge.com/minecraft/mc-mods/cc-tweaked/files/all

I would understand it if you don't want to include the mod while it's still in alpha, but I think it would be really cool to add it.

**Comment by Shindur** [comment]
Please reference this issue here: https://github.com/NillerMedDild/Enigmatica6/issues/29 Tho I feel like if you wanted to add it to play during single player you could easily do that.

**Comment by mrDLSable** [comment]
Yeah, I was too lazy to search for it. Thanks for pointing it out :)
