### ISSUE TITLE
[QoL] If Possible, Default Recipes To Vanilla Components Rather Than Entire Forge Tags

### ISSUE THREAD

**Issue by r-mc2** [NillerMedDild/Enigmatica6#1352]
**Description**
It's come up a number of times over on the Discord, you go to craft something that needs stone, sticks, or cobble and shift+click into an RS crafting grid or RS patterns not set to "exact" mode will start to use PNC's reinforced stone, treated sticks, or BYG cobble variants instead of their vanilla counterparts.

**Why would you like this added/changed?**
It can be rather frustrating to have to either change what shows up in the crafting grid or your patterns as well as forgetting to set "exact" and come back to find that more complex items have been used in place of much easier to obtain resources.

I believe Merlo mentioned it could be possible to set default items. I would never suggest it be done per-recipe that's more work on your part than it would be on a player fixing their own RS patterns, but if there's some method of denoting the "default" item in a Forge tag? Or some other KubeJS magic?
```[...] I thiiiiiink we can specify defaults but I'm not sure```

**Comment by NillerMedDild** [comment]
I'm afraid this isn't something we have control over.

**Comment by r-mc2** [comment]
Fair enough! At least we have an existing issue to point back to now 😄

**Comment by NillerMedDild** [comment]
@Darkere tagging you just in case you know of some kind of black magic for tag prioritization in RS recipes.

**Comment by r-mc2** [comment]
One last minor note, but I think this would affect even just plain crafting tables if you have the resources in your inventory, so not entirely limited to RS. But leave it to you smarter people to noodle if there's a possibility 😉

**Comment by Darkere** [comment]
I have considered changing the patterns so that vanilla items will always be considered first. 

That said I'm not sure what this depends on, so there might be a solution somewhere else.
