### ISSUE TITLE
Game freezing for no reason, sometimes crashing

### ISSUE THREAD

**Issue by CaffeineHigh22** [NillerMedDild/Enigmatica6#1357]
**Modpack version**
0.3.13

**Describe the bug**
It's not really a bug, but the game freezes, sometimes crashing because of this at random points, I have 6,4gb allocated to it so it  should be fine since I'm not hosting a server or lan, I'm just playing on single player.
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
https://zerobin.esolia.com/?f9b57fac4d213b37#cMyRZKJvwLZ9Ut7u0PrLcRcYiLmjGBiw4pQkR74qqUQ= posted it in zerobin since pastebin doesn't allow more than 512kb

**Comment by Merlo17** [comment]
You could try bumping up the ram a bit if you can or add some JVM args for better gc. This is a discussion better suited for our discord server though
