### ISSUE TITLE
Tips for the ticker on map load up

### ISSUE THREAD

**Issue by miljersmodz** [NillerMedDild/Enigmatica6#1359]
"Holding left shift in JEI  recipe menu to pause recipe scrolling, use mouse wheel to scroll through recipies."

For example Botony pots with the different types of dirt.

**Comment by Merlo17** [comment]
https://forms.gle/3uCaRQWKDP991xqD6

Feel free to suggest tips here ^^

**Comment by NillerMedDild** [comment]
I take it you added this tip Merlo? :)

**Comment by Merlo17** [comment]
I did, but I generally wait to PR them in until I have a bunch at least to not spam with commits
