### ISSUE TITLE
Chunks not saving

### ISSUE THREAD

**Issue by GrownUpBaby** [NillerMedDild/Enigmatica6#136]
**Modpack version**
0.2.6

**Issue**
Chunks are not saving, I saw someone had the same problem in the closed issues. Anytime I leave a chunk or leave the game the chunks reset the progress I made. Anything stored on my character in saved but any building I do or anything used in a chest is reverted.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5075570/latest.log)

**Comment by mrDLSable** [comment]
Is the world you are using from 0.2.4 or earlier @GrownUpBaby ?

**Comment by GrownUpBaby** [comment]
Its from earlier than 0.2.4, not sure how much earlier though

**Comment by mrDLSable** [comment]
There is an issue with updating from 0.2.4 and earlier to 0.2.5 or later because of the removal of the rats mod. Readding rats might solve the problem. Before trying this, please backup your save.

**Comment by GrownUpBaby** [comment]
Ok, I will try that. Luckily I make backups every time I stop playing so I didn't lose much progress.

**Comment by GrownUpBaby** [comment]
Adding rats back seems to have fixed the issue, thanks for your help

**Comment by mrDLSable** [comment]
You're welcome. @NillerMedDild are you looking into a way for people like him to be able to safely remove the Rats mod?

**Comment by Shindur** [comment]
Probably to start a new world. It's probably better to do that anyway with the inclusion of Emendatus Enigmatica for custom ore generation.

**Comment by mrDLSable** [comment]
> Probably to start a new world. It's probably better to do that anyway with the inclusion of Emendatus Enigmatica for custom ore generation.

While I would normally agree, as a software engineer my mind screams that I have to advocate for compatibility until version 0.3.

**Comment by Shindur** [comment]
Oh I agree, but there's nothing Niller can do because it's a bug caused by Rats.

**Comment by mrDLSable** [comment]
Ah ok. Thanks for pointing that out. I'm looking at the Rats github and can't find a related issue. AM I blind?

**Comment by NillerMedDild** [comment]
I never made an issue, I cannot prove Rats has anything to do with it. The only thing I know is the issue goes away when Rats goes away. I can't give the developer anything to go on whatsoever :/

**Comment by mrDLSable** [comment]
Weird. Did you test just making a world with rats in it, making some changes to the world, removing rats, and then making some more changes and see if it saves?

**Comment by NillerMedDild** [comment]
Pretty much yeah
