### ISSUE TITLE
Problems with Mekanism nuclear waste and with radiation

### ISSUE THREAD

**Issue by LeviMon2** [NillerMedDild/Enigmatica6#1362]
Modpack Version 0.3.13

The bug happens with storing Mekanism nuclear waste. Tanks can't store it, and you can't remove it with nuclear waste barrels, so the level of radiation goes up. You can get rid of radiation with a command, but it's only temporary and i didn't find any config where I can turn off radiation.

Fix would be really appreciated!

**Comment by TemperedFool** [comment]
This is a little confusing. I believe you're required to store it in Waste Barrels by Mekanism, and the barrels themselves cannot be moved without emptying them (or spilling their contents). Pipes likewise will spill waste when broken with it in their buffers. All these spills cause radiation.

Waste is meant to be stored and aged in the barrels; it will decrease by 1mb/min per the wiki. You can also turn it into either antimatter, or other radioactive materials (plutonium/polonium), which produce spent waste which similarly needs to be aged.

For reference: https://wiki.aidancbrady.com/wiki/Fission_Reactor

**Comment by NillerMedDild** [comment]
TemperedFool is completely right, but we're aware the current process isn't great, MuteTiefling has taken steps to make it better, which will be a part of v0.4.0 :)

**Comment by MuteTiefling** [comment]
Mainly, waste in waste barrels will disperse much faster, so making sustainable reactors should be easier.

**Comment by LeviMon2** [comment]
@TemperedFool Waste barrels (or any other types of containers) couldn't hold the waste for me, that's what I wanted to report. Maybe it happened just for me, but even a restart didn't help me.

**Comment by TemperedFool** [comment]
That makes a little more sense! Sorry for the confusion.

**Comment by MuteTiefling** [comment]
Waste barrels only accept input from the top or bottom.

Waste is also considered a gas, so use pressurized pipes.

**Comment by LeviMon2** [comment]
@MuteTiefling I actually tried both pressurized and mechanical pipes. I also tried all sides, and it never worked, it wouldn't go in the barrel.

**Comment by BlueAgent** [comment]
How did you even try with mechanical pipes? Radioactive chemicals are only gases in Mekanism and doesn't have a liquid form.
The radioactive waste barrel accepts Nuclear Waste, Spent Nuclear Waste, Plutonium and Polonium only. Are you trying to put something else inside?

**Comment by MuteTiefling** [comment]
Are you even getting waste into the pressurized pipe? Almost sounds like your reactor doesn't have an output valve for waste. You need to use a configurator to change their mode.

**Comment by LeviMon2** [comment]
@BlueAgent I tried fluid pipes as I tried gas pipes. I quickly saw that it can't connect, so that isn't the problem.

**Comment by LeviMon2** [comment]
@MuteTiefling Yes, i can get the waste into the pressurized pipe. But for some reason, the containers won't accept the waste, only if you put a chemical tank into the extraction slot. It's a loophole.

**Comment by MuteTiefling** [comment]
> only if you put a chemical tank into the extraction slot. 

Gonna need screenshots. You don't store waste in chemical tanks. It only goes in Waste Barrels, and this last reply melted me suspect you're still using chemical tanks.

**Comment by LeviMon2** [comment]
@MuteTiefling I actually tried every container variant from every side, but nothing worked. I'm getting you those screenshots in a few minutes, i just need to set up something so you can see the waste level in the pipe but not in the container.

**Comment by LeviMon2** [comment]
So, as it turns out, I was the real problem. I tried to get the waste into the chemical tank, because there's a creative chem tank for the waste. The waste barrel works now, but yesterday even after 10 minutes the waste amount wouldn't decrease.

I am really sorry for wasting your time, probably something happened, but now it's working. I feel real embarassed for doing this.

Have a good day, I'm really sorry.

**Comment by Merlo17** [comment]
Don't worry about that, glad you could get your issue sorted :D
