### ISSUE TITLE
[Dupe+Void] RF Filter+Sorting Mod

### ISSUE THREAD

**Issue by Elvarion** [NillerMedDild/Enigmatica6#1363]
**Modpack version**
0.13.4

**Describe the bug**
Refined Storage Filter + Filter/Sort Mod causes duplication.
The gif cuts a bit short. But ive been able to replicate this every single time.
https://gyazo.com/33b1fa30e08350dc3db456af11b798d9

Place an item via dropping it from your cursor in the filter. Then click Extract > Duplicates the item.

**Void Version**
If you click the "Insert" it will pull items from your Inventory (Not hotbar). IF you then click them in the filter, the item is gone forever. You can extract them via Extract again to get them back atleast.

**Comment by NillerMedDild** [comment]
Fixed, thanks!
