### ISSUE TITLE
Eidolon quest reward gives wrong Ashes

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#1364]
**Modpack version**
0.3.13

**Describe the bug**
Eidolon quest "Rituals" gives 16x Arcane Ashes (bloodmagic:arcaneashes). Arcane Ashes is from the Blood Magic mod. Each one has 20 durability, they don't stack. I'm 95% sure the reward is meant to be 16x Enchanted Ash (eidolon:enchanted_ash).

**Logs**
n/a

**Screenshots**
n/a

**Comment by Merlo17** [comment]
Ty, it was an oversight indeed, it was already reported :D
https://github.com/NillerMedDild/Enigmatica6/issues/1174
