### ISSUE TITLE
[Void] Mekanism + Create

### ISSUE THREAD

**Issue by Elvarion** [NillerMedDild/Enigmatica6#1369]
**Modpack version**
0.13.4

**Describe the bug**
Mekanism fluid Tank filled with Create Milk
Right-Clicking the tank with a Bucket voids the bucket and removes 1 bucket worth of milk from the tank

**Comment by MuteTiefling** [comment]
Possibly already fixed, as I cannot reproduce this in the dev instance.

**Comment by Elvarion** [comment]
👍
