### ISSUE TITLE
Not really a bug?

### ISSUE THREAD

**Issue by Z3r024** [NillerMedDild/Enigmatica6#1383]
0.3.13

I started to experience something weird with a lot of modpacks lately. Was in my world and I wanted to create a new one, unfortunately, it loaded to 100% and then I got stuck there being forced to restart my game. It occurs on multiple modpacks when trying to interact with a world or create one after u already were in one and I have no idea why. It's kinda confusing cuz I have no idea how to explain it properly. I don't really have any recent logs from enigmatica but if necessary I can reproduce the bug and send the log.

**Comment by NillerMedDild** [comment]
We'd need a log to be able to do anything :)

**Comment by Z3r024** [comment]
> We'd need a log to be able to do anything :)

https://gist.github.com/Z3r024/0d89074f31f058f39c316530981df414 *sorry for taking so long*

**Comment by NillerMedDild** [comment]
Hmm, I can't see any obvious reason. Optifine perhaps? :P
