### ISSUE TITLE
Greater Eye of Ender

### ISSUE THREAD

**Issue by CrownJoker** [NillerMedDild/Enigmatica6#1384]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/greater-eye-of-ender-forge

**Mod description**
Similar to an Eye of Ender, but can locate structures other than strongholds.

**Why would you like the mod added?**
I often seem to have terrible luck when it comes to finding structures, and would like to avoid using /locate.

**Comment by MuteTiefling** [comment]
Nature's Aura provides us with the same functionality already.  One for pillager outposts, one for end cities, and one for nether fortresses

**Comment by CrownJoker** [comment]
I'll look into using Nature's Aura, thanks! This one seems have the main benefit of being compatible with modded structures since it seems to work using /locate.

**Comment by NillerMedDild** [comment]
It's a kinda cheesy way to bypass exploring though, imo :/ It's fine for a few things, but not all.

**Comment by CrownJoker** [comment]
That's fair. I guess the fallback of /locate does exist if it ever gets frustrating. Thanks!
