### ISSUE TITLE
Nuclear waste disappears when being transported into Solar Neutron Activator.

### ISSUE THREAD

**Issue by MrDName** [NillerMedDild/Enigmatica6#1387]
Enigmatica 6 v0.3.13 installed via GDL. Playing on a server hosted by myself.

Nuclear waste simply disappears when i try to move it to the solar neutron activator directly or from waste barrels.
I know it can act like this if you are trying to put it in an invalid storage that is not supposed to accept it but it shouldn`t do that with SNA (solar neutron activator) i believe, as it is the only way to make polonium out of it.
It still acts normal when being transported to waste barrels or between them but when i try to get it into the SNA it just disappears. I tried every pipe and tried tweaking the push/pull but it simply will not appear in the machine whilst still being depleted from barrels or reactor storage.

Screenshots:
1. Reactor`s storage has waste in it.

2. Trying to move the waste into the SNA with Mekanism`s pressurized tubes. (tried pipes from immersive but they would only connect to the reactor port and not the machine).

3-4. Both of them being completely empty shortly after.

5. Waste being successfully transported into the barrel.

![2021-02-23_23 46 35](https://user-images.githubusercontent.com/79543151/108907442-21f44b80-7633-11eb-82c3-9619a1f1d710.png)
![2021-02-23_23 46 55](https://user-images.githubusercontent.com/79543151/108907457-26206900-7633-11eb-854f-b4cc1d854019.png)
![2021-02-23_23 46 58](https://user-images.githubusercontent.com/79543151/108907461-27519600-7633-11eb-8b06-2ed89da36798.png)
![2021-02-23_23 47 00](https://user-images.githubusercontent.com/79543151/108907474-2a4c8680-7633-11eb-92f8-c8b59d5f9419.png)
![2021-02-23_23 47 36](https://user-images.githubusercontent.com/79543151/108907482-2caee080-7633-11eb-8e2b-b7f32d8fce71.png)

I am very sorry if I am just being very stupid and not noticing something obvious or if this issue was already discussed.
I wasn`t able to find a way to solve it or it being mentioned by the devs or other players anywhere so decided to ask here.

**Comment by MuteTiefling** [comment]
The SNA takes waste from the bottom.  It's not being lost, it's just sitting in your pipe.

The Waste Barrel, on the other hand, is meant to dissipate waste. This gives you a safe way to slowly get rid of your final waste products.
