### ISSUE TITLE
Cheaper Mekanism Bins

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1388]

**Comment by OneLemonyBoi** [comment]
If the bins become cheaper, then the Mekanism Upgrade item should either also be changed or somehow blacklisted from the Bins, as they can be used to upgrade the bins. Either Storage Drawers should be nerfed, or Bins should be buffed via configs.

**Comment by TemperedFool** [comment]
As a counter argument, the installers being more expensive than the bins would otherwise be is probably fine due to their versatility (they can also upgrade machines) and the fact that they can upgrade-in-place, avoiding disrupting an existing build.

**Comment by OneLemonyBoi** [comment]
The main issue with mek bins is that you need multiple external storages as well as not having much capacity as storage drawers do. Maybe multiply the storage by a factor of 4/8? AFAIK Drawers can handle up to approx 400k items, so having top tier mek bin have about 800k-1.6M item storage seems fair, as it would be more effort for a lot more compactness.

**Comment by MuteTiefling** [comment]
I could see the installers being made considerably cheaper too, honestly. Even with the side effect it making the machines cheaper to upgrade

**Comment by MuteTiefling** [comment]
Also, I know this would cause a riot, but the upgrades for storage drawers could also be made a touch more expensive

**Comment by TemperedFool** [comment]
To paraphrase something from the discord, you could always... accidentally... make the drawer upgrades uncraftable and keep forgetting to fix them...

**Comment by OneLemonyBoi** [comment]
I think the best philosophy is to always buff, not nerf. It would cause
less opposition if it was a Mekanism buff compared to SD nerf

**Comment by Merlo17** [comment]
I don't agree on making the upgrades cheaper honestly. It's not like they're crazy expensive already and they can be used on any mekanism machine, which would make mek even more powerful than it currently is which probably isn't healthy for the pack.
Making the bins cheaper is the solution here for me: that would also act as a drawers nerf since they'd be a valid alternative. I don't think nerfing the drawer upgrades recipes is needed though I wouldn't be opposed to that.

**Comment by MuteTiefling** [comment]
Really, it's probably the tiered vs not tiered craft that's the biggest issue. Want a big drawer? You'll go straight to the biggest size you can make.

A big bin, on the other hand, has to be upgraded.

Removing that requirement from the basic crafting recipe could work. Leave the upgrades alone (you're already wasting material if you use them on a bin anyway).

**Comment by Mendanbar** [comment]
Another thing that keeps me coming back to drawers (despite being a big Mek fan) is that drawers offer a void upgrade. So in cases like the PRC over producing substrate, it becomes a non issue with drawers. I just upgrade the drawer to the amount of substrate I want on hand and void the rest. Don't take this as an argument for removing the void upgrade from drawers.  I just really wish the Mek bins had that feature, and it's a big reason for me to look elsewhere for solutions.

**Comment by MuteTiefling** [comment]
The void issue is at least easily handled with a trash can as a default route on pipes. 

But that requires people to break their addiction to Drawers. Same with easy compacting.

**Comment by TemperedFool** [comment]
As with a lot of things, the only thing that would break the drawer addiction would be removing them. Seems untenable.
