### ISSUE TITLE
Quark Loot still provides vanilla ore blocks

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#139]
**Modpack version**
0.2.6

**Issue**

Maybe nothing you can do about it, but Quark loot areas in caves will still provide vanilla ores (just got one with diamond and emerald ore in it) and also spawn vanilla ores in the floor nearby. 

**Logs**

The redstone in the floor there by the crafting bench is actually vanilla redstone ore. 
![2020-08-15_08 05 34](https://user-images.githubusercontent.com/9543430/90311932-1ed31280-dece-11ea-963f-5a590837cd33.png)

**Comment by MuteTiefling** [comment]
Monsters spawned by Quark Monster Boxes as well.

**Comment by NillerMedDild** [comment]
We'll try to get that fixed, thanks! :)

**Comment by NillerMedDild** [comment]
Was this a huge cave?

**Comment by MuteTiefling** [comment]
It wasn't a huge cave, no. Just kind of a tunnel with these things found randomly.

**Comment by NillerMedDild** [comment]
Hm alright :/ well, should be fixed either way! Vanilla ores now drop EE stuff
