### ISSUE TITLE
Missing recipe for Pumpkin Slice

### ISSUE THREAD

**Issue by shibeobi12** [NillerMedDild/Enigmatica6#1391]
**Modpack version**
0.4.0
**Describe the bug**
Using the knife (in my case, iron) with a large pumpkin slice from Autumnity does not allow you to make a Pumpkin slice.
If this is intended behavior, I apologize.

**Screenshots**

![image](https://user-images.githubusercontent.com/50844560/108947628-134f6980-761e-11eb-9e3e-bb00faa6efe1.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I think this is intended :) Shears is the tool to use.

**Comment by shibeobi12** [comment]
Ooh, I'll give that a shot, thank you!

**Comment by shibeobi12** [comment]
Hey, so... by intentional, do you mean the intent is to not be able to turn the Autumnity "Large Pumpkin Slice" blocks into a Farmers Delight Pumpkin slice, through the cutting board and knife, like a regular pumpkin? Sorry to bug you, but I wasn't certain. Shears don't turn them into Pumpkin slices.

**Comment by theboo** [comment]
looking at this closer, autumnity already adds a recipe to convert pumpkins to large pumpkin slice(4 pumpkins=4 large slice) ill just add a recipe to convert them back 1:1 so u can make pumpkin slices. I think going back it makes more sense to go 1 large slice- 1 pumpkin.

**Comment by theboo** [comment]
fixed in #1428

**Comment by NillerMedDild** [comment]
I totally misunderstood this issue, sorry about that :P
