### ISSUE TITLE
Create Stone Variants & Tetra

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#1395]
**Modpack version**
0.4.0 beta
**Describe the bug**
Create stone variants are not valid for Tetra tool components. May be an additional issue, but hammer heads only have 6 valid stone variants and two metals.

**Logs**
N/A

**Screenshots**
N/A

**Comment by NillerMedDild** [comment]
We'll get that fixed, thanks!

**Comment by NillerMedDild** [comment]
As a workaround you can use the Tier 2 Hammer crafting recipe :)
