### ISSUE TITLE
Death loop dupe

### ISSUE THREAD

**Issue by Toonlink264** [NillerMedDild/Enigmatica6#1397]
**Modpack version**
0.4.0
**Describe the bug**
When you die with the balloon bauble from Bountiful Baubles equipped, it stays with you AND puts one in your grave

**Screenshots**
![image](https://user-images.githubusercontent.com/60859491/108998912-807fff00-76f1-11eb-9690-4f968cb5abda.png)

ignore the pokecubes, i have tested without and it's not that mod doing it

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I can't reproduce this, did you do anything special?

**Comment by Toonlink264** [comment]
nope. i had the balloon bauble equipped and died

**Comment by NillerMedDild** [comment]
Was it on a server?

**Comment by Toonlink264** [comment]
singleplayer. i just woke up so ill hop on and do some more testing in a moment

**Comment by Toonlink264** [comment]
hm. must be the mod i added. nevermind!
