### ISSUE TITLE
Entangled

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica6#1398]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/entangled

**Mod description**
Provides an Entangled Block and a binder tool. Bind the Entangled Block to another block (like a machine) and it acts as a copy, allowing access to otherwise blocked sides.

**Why would you like the mod added?**
I miss Phantomfaces. I'll be happy enough with AA if it ever really makes it to 1.16 and into the pack, but this is like Cupid's arrow to my hiding-ugly-cables-in-Astral-builds heart.

**Comment by Merlo17** [comment]
I think this one depends mostly on how much @Ridanisaurus thinks AA will take. They'd be really useful for sure, but I guess modular routers can help with stuff like that for now

**Comment by Ridanisaurus** [comment]
Well, Mikey was super busy, and he said that he has finalized the projects he was working on, and is now focusing on the AA port, so hopefully soon? I honestly don't know ¯\_(ツ)_/¯

**Comment by NillerMedDild** [comment]
I think we need this feature, but I'd like to wait for AA.

**Comment by Gcat101** [comment]
Well it's been a year, still no AA...

**Comment by MuteTiefling** [comment]
> Well it's been a year, still no AA...

And this mod was added ages ago. Why are you necroing old closed issues for no reason?

**Comment by Gcat101** [comment]
Wait really

**Comment by Gcat101** [comment]
I’m soo dumb
