### ISSUE TITLE
Windowlogging

### ISSUE THREAD

**Issue by real-chair** [NillerMedDild/Enigmatica6#1399]
https://www.curseforge.com/minecraft/mc-mods/windowlogging

Allows you to place glass panes, fences, etc., inside of various blocks, such as slabs and stairs, essentially waterlogging them, but with windows!

It's a very useful mod for builders. It doesn't change anything fundamentally in the game, but it opens up big opportunities for builds. If it helps any, it was originally an included feature with the Create mod, but it's since been moved to it's own download.

![image](https://user-images.githubusercontent.com/71352104/109019065-a4f2c180-7686-11eb-9e55-428ab450a9a4.png)

**Comment by NillerMedDild** [comment]
Cool mod, but looking at the issue tracker it's pretty much not maintained, and not marked for 1.16.5, so I'll pass for now :(

**Comment by real-chair** [comment]
Aww. I didn't realize  it had lagged so far behind ):
Sorry for not checking beforehand.

**Comment by NillerMedDild** [comment]
No worries!
