### ISSUE TITLE
Lighting issue

### ISSUE THREAD

**Issue by tonyvans** [NillerMedDild/Enigmatica6#14]
**Modpack version**
0.1.7 down to 0.1.3

**Issue**
seems to be an issue with lighting, Also dark patches about the size of a chunk randomly appear on over world surface during the day even while lit with torches which can cause monster spawning and prevent mechanism machines from running (wind and solar)

area affected can change on server reboot, added a sample 
 
![2020-07-19_09 15 15](https://user-images.githubusercontent.com/6739653/87879870-12789a00-c9a2-11ea-8c87-10b6540f0b70.png)

I can provide more info if needed but I have no idea how to reproduce it nor any idea what might be causing it. I changed resource packs with the ones provided, and 3rd party ones, no change noticed) 

Thanks and keep up the good work

**Comment by NillerMedDild** [comment]
Huh, that's odd. Can you repeat it with normal torches?

**Comment by tonyvans** [comment]
those are normal torches, I was just using a 3d texture pack at time of the screen shot (I figured you would notice that so I mentioned I got the same results with all the default texture packs)

**Comment by NillerMedDild** [comment]
Oh, dammit. I was hoping it was Dwarf Toches. I'll look into it :)

**Comment by Darkere** [comment]
There have been multiple reports on discord about lights acting weirdly. For example furnaces giving off light when not lit. Torches not working. 
Not really a clue how to investigate what's causing it though. The mining helmet maybe?

**Comment by tonyvans** [comment]
with the default texture packs
![2020-07-19_11 26 56](https://user-images.githubusercontent.com/6739653/87882170-1234ca80-c9b3-11ea-934d-4ce858ff2562.png)

if I pick up the torch and replace it, the issue goes away. 
![2020-07-19_11 27 13](https://user-images.githubusercontent.com/6739653/87882179-1cef5f80-c9b3-11ea-9fd8-5724f0e64d3f.png)

**Comment by tonyvans** [comment]
> There have been multiple reports on discord about lights acting weirdly. For example furnaces giving off light when not lit. Torches not working.
> Not really a clue how to investigate what's causing it though. The mining helmet maybe?

I have never made or used the mining helmet. so I know that isn't the case for me

**Comment by NillerMedDild** [comment]
I ruled out both Miner's Helm and Dwarf Coal.

**Comment by let-value** [comment]
I updated forge to version 32.0.70, updated all mods (had to remove Cosmetic Armor Rewoked, Laser Relays, The One Probe) and the problem went away. The lighting sources had to be re-placed. Also for me this fixed the issue of rolling back chunks and disconnecting pipes from Mekanism.

**Comment by Darkere** [comment]
Why did you have to remove laser relays? (The one probe got an update yesterday so you also don't need to remove that)

But it's good to know it might be fixed

**Comment by NillerMedDild** [comment]
It's not fixed for me, Furnaces still produce light despite being "unpowered"

**Comment by tonyvans** [comment]
after updating to Version: 0.2.0. the issue has gone away for me. I had to pick up and replace all the torches once, but has not been an issue since.
Thank you
