### ISSUE TITLE
[0.2.4][Aternos] Server Crash/Couldn't Launch.

### ISSUE THREAD

**Issue by Enethim** [NillerMedDild/Enigmatica6#140]
**Modpack version**
0.2.4

**Issue**
Server is crashing, can not be launched.
Aternos.org Host

**Logs**
https://mclo.gs/UNdswMM

**Comment by Enethim** [comment]
https://mclo.gs/QTFpvQa
Second try more errors.

**Comment by NillerMedDild** [comment]
I'm afraid none of those logs contain anything useful, as far as I can tell on mobile at least. Do you have the latest.log or crash report instead?

**Comment by NillerMedDild** [comment]
Also, you're 2 versions behind, updating and reading changelogs might help.

**Comment by Enethim** [comment]
Aternos Hosting Only has 0.2.4 Version available, I Just selected mod pack i wanted and it did the rest.

**Comment by Enethim** [comment]
Third try: https://mclo.gs/gR2YfQX
Has many errors regarding "rat"

**Comment by Enethim** [comment]
Here's how it looks when I'm selecting Modpack on server https://imgur.com/a/CkqtPU0

**Comment by Darkere** [comment]
>[15Aug2020 18:51:15.760] [modloading-worker-2/WARN] [Old Java Warning/]: User has less than the recommended amount of ram. They have 1771mb and the pack recommends 4096mb.

I don't think the server is gonna work with 1.7gb of ram.

**Comment by Enethim** [comment]
> > [15Aug2020 18:51:15.760] [modloading-worker-2/WARN] [Old Java Warning/]: User has less than the recommended amount of ram. They have 1771mb and the pack recommends 4096mb.
> 
> I don't think the server is gonna work with 1.7gb of ram.

I have used this Host for many other mod-packs which had as much or more ram requirement, had no issues.

**Comment by NillerMedDild** [comment]
The log you're supplying is the debug.log, which does not help for this issue.
I believe the amount of RAM Aternos gives you varies, that may be why you're having issues now.
If you can reproduce this issue on a non-free server host, or locally, I'll happily investigate further, but right now there's nothing we can do.

**Comment by Enethim** [comment]
![image](https://user-images.githubusercontent.com/69675392/90319608-acecde80-df4a-11ea-9d5e-4ff8bf6e803e.png)
What Host gave me

**Comment by NillerMedDild** [comment]
Thanks! The issue is they've have built their server files using the client package, which means it contains client-side only mods. The server files do not contain those 4 mods.

**Comment by Enethim** [comment]
> Thanks! The issue is they've have built their server files using the client package, which means it contains client-side only mods. The server files do not contain those 4 mods.

Oh god >.> What on earth... Can you contact them and explain the issue ?

**Comment by NillerMedDild** [comment]
I'd rather not to be honest. I don't have time to contact server hosts and tell them how to make server files :P I'd rather spend what limited time I have helping people who have downloaded the correct files tbh.

**Comment by Enethim** [comment]
I have contacted the support, let's hope for the best, it's just shameful how a Hosting service is giving you clientpack for server.
