### ISSUE TITLE
Crash on F2

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1400]
**Modpack version**
0.4.0
**Describe the bug**
Pressing F2 crashes the game. Possibly to do with the screenshot to clipboard mod added in 0.4 not working correctly on mac.

**Logs**
Crash report file:
https://gist.github.com/Rodg88/d34f29dc8bfd9dd43bc534162706ef36

Warning, 8.5MB log file ahead:
https://gist.githubusercontent.com/Rodg88/08fea2c46cd7e112f945208ee2377839/raw/f3eeeea08d30111474d588fccdfdf5c8b4bc4f62/screenshotcrash.log

**Comment by OneLemonyBoi** [comment]
Seems like this mod needs to change how they change the style of their text, as it has been changed between versions. Also seems as there has been no real update to the mod since September.

**Comment by NillerMedDild** [comment]
Damn, I'll remove it 😞
