### ISSUE TITLE
(Datapack suggestion) Incendium 

### ISSUE THREAD

**Issue by CletusMAngo** [NillerMedDild/Enigmatica6#1401]
https://www.planetminecraft.com/data-pack/incendium-nether-expansion/
(some of desc copied from datapack page)
Incendium is a datapack made to completely revamp the Nether, beyond what has already been done by the Nether Update.
It is also completely compatable with BYG so i feel like it wont cause many issues but thats up to u guys 
I really think this would fit the nether in E6 as the End and Overworld feel more finished and have more structures in the 4.0 update

**Comment by theboo** [comment]
Do you have a link to the datapack?

**Comment by CletusMAngo** [comment]
Oop so sorry here it is i edited the original post

**Comment by CletusMAngo** [comment]
May i also add that they have a standalone datapack of the Nether castle structure 
https://www.planetminecraft.com/data-pack/nether-castles-standalone/

**Comment by theboo** [comment]
Looks pretty sweet... I might look at it tonight if I can pull myself away from actually playing the pack haha

**Comment by Merlo17** [comment]
I looked at it when looking at possible datapacks but incendium itself looks extremely big and probably a bit out of scope for our pack imo. The castles are cool but I worry about those being a bit too much too

**Comment by theboo** [comment]
Looks like the castle is an extra structure and doesnt replace fortresses or anything... I don't know that it would be any more crazy than the giant dungeon crawlers dungeons in the overworld... But I'd have to see it in game first

**Comment by CletusMAngo** [comment]
It is a shame that the biomes are included with the structures, it wouldve been better if the structures were a standalone thing

**Comment by NillerMedDild** [comment]
I think this is too much for Enigmatica tbh, we already have plenty going on in worldgen.
