### ISSUE TITLE
Mekanism Ore Tripling Quest 

### ISSUE THREAD

**Issue by ManiacRobert1** [NillerMedDild/Enigmatica6#1403]
A small suggestion about that, can accept any tier of this machines like in powah questline?

![image](https://user-images.githubusercontent.com/39351347/109040901-1d816e80-76d7-11eb-8dfa-42e86f9f9d21.png)

**Comment by MuteTiefling** [comment]
Sure. Will change this up tonight.

**Comment by MuteTiefling** [comment]
Ready to go. Changes live in Dev.
