### ISSUE TITLE
Aluminum Ore Texture (World Generation)

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#1404]
**Modpack version**
0.4.0
**Describe the bug**
Aluminum Ore does not have any additional textures besides the default stone one when generating. The attached screen shot shows it standing out in jasper and I've seen it as the default one in marble (generated Astral Sorcery Temple) as well.

**Logs**
N/A

**Screenshots**
![2021-02-24_13 15 08](https://user-images.githubusercontent.com/41839144/109049334-2a399e80-76a6-11eb-942b-9a31f4c9df75.png)

![2021-02-24_13 46 34](https://user-images.githubusercontent.com/41839144/109049875-c2378800-76a6-11eb-822a-2bb22164458d.png)

**Comment by anivlys** [comment]
This does not happen 100% of the time as I have now run across ore that has generated with the appropriate texture in the world.

![2021-02-24_14 00 28](https://user-images.githubusercontent.com/41839144/109051613-ae8d2100-76a8-11eb-8a95-ae09222a73ea.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll try to figure out what's going on. I hope it's a TerraForged issue that was fixed in a recent update.

**Comment by Ridanisaurus** [comment]
Quick question, have you updated any configs, or any of the world settings? Is this a Terraforged world with our setup?
This happens every now and then, and it usually depends on the event firing order of generation stages. There is only so much control I have over it.
Hopefully the updated Terraforged will address some of those quirks. Thanks for the report.

**Comment by anivlys** [comment]
I've added two jars (InventoryHud+ and Mantle) and this world is default config in hardmode.

**Comment by anivlys** [comment]
Another Astral Sorcery Temple more ore generating without matching textures. This time it is copper ore not matching marble and granite. Two for one deal. This update is to mention that aluminum ore is not the only one effected.

![2021-02-24_14 34 54](https://user-images.githubusercontent.com/41839144/109055734-8eac2c00-76ad-11eb-9875-a4b94c231537.png)

**Comment by NillerMedDild** [comment]
I believe this is fixed, not entirely sure though. Not much more we can do in any case :)
