### ISSUE TITLE
Refined Storage payload kick error

### ISSUE THREAD

**Issue by sportsziggy** [NillerMedDild/Enigmatica6#1407]
Version: 0.3.9

Error: When trying to open refined storage inventory on our server we're now getting kicked.

Error Msg:
![image](https://user-images.githubusercontent.com/1366131/109061770-0fbaf180-76b5-11eb-8b47-aed5cbfada56.png)

**Comment by NillerMedDild** [comment]
Thanks for the report - Please try updating to 0.3.13 and see if the issue persists, or 0.4.0 if you don't mind resetting your world.

**Comment by sportsziggy** [comment]
Updating now to .13, fingers crossed.

**Comment by Darkere** [comment]
This is an issue with too many different items in the system with too much data on them. 

Usually caused by people dropping all their mob farm stuff into RS instead of trashing it :)

**Comment by sportsziggy** [comment]
> 
> 
> This is an issue with too many different items in the system with too much data on them.
> 
> Usually caused by people dropping all their mob farm stuff into RS instead of trashing it :)

Isn't that the point of having a 4+mil storage disk 😢 So what do? Can we use a different storage?

**Comment by sportsziggy** [comment]
> 
> 
> Updating now to .13, fingers crossed.

Still happening on .13 😭

**Comment by Darkere** [comment]
Well the solution is to reduce the number of different items that get sent to your client/are in your system.

As long as they stack it is not a problem at all, have a billion iron ingots or whatever.  But having armor each with different enchants and durability in the system can cause problems. 

It is a vanilla limit with how much data you can send to a client and circumventing that limit is complicated.

**Comment by sportsziggy** [comment]
> 
> 
> Well the solution is to reduce the number of different items that get sent to your client/are in your system.
> 
> As long as they stack it is not a problem at all, have a billion iron ingots or whatever. But having armor each with different enchants and durability in the system can cause problems.
> 
> It is a vanilla limit with how much data you can send to a client and circumventing that limit is complicated.

Welp just went ahead and deleted 20k+ mob farm items (hopefully just those lol) through NBTExplorer - what a PITA.

**Comment by sportsziggy** [comment]
FYI - Issue fixed
![image](https://user-images.githubusercontent.com/1366131/109069155-d38c8e80-76be-11eb-8654-3c24a67cab29.png)

**Comment by Darkere** [comment]
well. I should have probably mentioned that but... An exporter into a trashcan will work just fine as long as you know roughly what kind of items you have in there
