### ISSUE TITLE
Grape seeds (Simple Farming) don't work in the botany pot

### ISSUE THREAD

**Issue by mrDLSable** [NillerMedDild/Enigmatica6#141]

**Comment by NillerMedDild** [comment]
We'll look into adding compat for it :)

**Comment by NillerMedDild** [comment]
It makes sense that it doesn't work in the Botany Pot to be honest.

**Comment by mrDLSable** [comment]
I know it handles differently in the world, but it would still be nice to have it grow in the botany pots...

**Comment by NillerMedDild** [comment]
I'm not going to add this, it feels like cheesing a mod mechanic to me.
