### ISSUE TITLE
Ores generating in Astral Sorcery structures

### ISSUE THREAD

**Issue by eJar0k** [NillerMedDild/Enigmatica6#1410]
**Version:** 0.4.0

**Description:** Some ores are able to generate within the raw marble bases of Astral Sorcery structures. I have only seen tin in a large ancient shrine, but I assume more can spawn. They are integrated via Emendatus Enigmatica ore textures, which implies some unintended interaction.

**Screenshots:**
![2021-02-24_14 04 49](https://user-images.githubusercontent.com/21207875/109072801-5ce59600-76aa-11eb-9b86-e19cc0171f11.png)

**Comment by Merlo17** [comment]
Not really an issue, more like something we cant prevent if we want to use astral marble in worldgen :P I think this one is here to stay

**Comment by eJar0k** [comment]
Alright, makes sense. Doubt you could script that out very easily or at all, then.
