### ISSUE TITLE
Obsidian honeycomb cant be used in centrifuger

### ISSUE THREAD

**Issue by rjulib00** [NillerMedDild/Enigmatica6#1411]
**0.4.0**

**Describe the bug**
the obsidian honeycomb lost its recipe to be used in the centrifuger (now its juts a solid block)

**Comment by OneLemonyBoi** [comment]
Can confirm in Dev. Seems to be a Resourceful Bees issue, as there is nothing wrong with the JSONs.

**Comment by NillerMedDild** [comment]
There was something wrong with the JSON :P

**Comment by OneLemonyBoi** [comment]
Did the arrow get removed?

**Comment by NillerMedDild** [comment]
Apparently yeah :P

**Comment by MuteTiefling** [comment]
Ah, the fetching module from apotheosis. :D
