### ISSUE TITLE
Astral structures not generating Lootr chests

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#1412]
**Modpack version**
0.4.0

**Describe the bug**
Astral Sorcery structures aren't generating Lootr chests, but rather standard MC chests. Not sure if this was intentional or not, or even something that could be fixed.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
The fix has been submitted to AS, but the dev is busy atm sadly :)
