### ISSUE TITLE
Jerry Can fully crashes client when used on water (Immersive Engineering)

### ISSUE THREAD

**Issue by shibeobi12** [NillerMedDild/Enigmatica6#1415]
**Modpack version**
0.4.0
**Describe the bug**
When myself and another use the jerry can on water on our hosted server, the client crashes out entirely. My more knowledgeable server mate mentions this, "It mentions the item stack is unknown, wonder if it's not recognizing water as a stackable thing and just gets null, or if it's straight up activating the jerrycan". Not sure if that helps, but he describes better than me.

**Logs**
https://pastebin.com/VD4xTHQM

**Screenshots**
Here's a screenshot from the MC launcher describing the issue afterwards - 
![image](https://user-images.githubusercontent.com/50844560/109108998-d2288980-76f1-11eb-8dfb-c0887df7b435.png)

**Comment by Darkere** [comment]
From what I can tell IE forgot that the Jerry can could be empty.

**Comment by NillerMedDild** [comment]
Reported to IE here: https://github.com/BluSunrize/ImmersiveEngineering/issues/4672
Reported to Apotheosis here: https://github.com/Shadows-of-Fire/Apotheosis/issues/325

**Comment by NillerMedDild** [comment]
The Jerrycan crash is fixed, but is now rather useless. I've removed its recipes while we wait for a fix :)
