### ISSUE TITLE
StoneWork Factory (IF) - Hard to select stone type

### ISSUE THREAD

**Issue by AndreiPurcaru** [NillerMedDild/Enigmatica6#1420]
The StoneWork Factory from Industrial Foregoing now has a very big list of items that it can craft (basically the whole list of available stone materials) and that makes it really hard to go through (especially since you can't go back in the machine). So I suggest maybe allowing the scroll wheel to be used on the input or maybe some other way of selecting which type you want because right now it is really tedious to slowly click through each stone type.

**Comment by NillerMedDild** [comment]
@Buuz135 is this something you could consider implementing for the Material StoneWork Factory? :)

**Comment by NillerMedDild** [comment]
Added feature request here: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/discussions/1152
