### ISSUE TITLE
Thermal Quest Chapter missing a few rewards

### ISSUE THREAD

**Issue by Rodnock** [NillerMedDild/Enigmatica6#1421]
**Modpack version**
0.4.0

**Describe the bug**
Bug or oversight, Centrifugal Separator quest has no reward

**Logs**
n/a

**Screenshots**
https://imgur.com/a/LKrXSjm

**Comment by NillerMedDild** [comment]
Fixed, thanks!

**Comment by Dracos99** [comment]
Same quest line, the Crude Oil also has no reward
