### ISSUE TITLE
Cutting Board recipe using wrong item

### ISSUE THREAD

**Issue by gefailter71** [NillerMedDild/Enigmatica6#1422]
Pack Version: 0.4.0

Cutting Board using BetterEnd Armor Sets and Tools to strip the log( All Tools and Armors).
Also Quark Boomerang

![image](https://user-images.githubusercontent.com/20716525/109215651-c00f1f80-77b3-11eb-8ade-bd76506fd596.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I relayed the issue here: https://github.com/vectorwing/FarmersDelight/issues/206
