### ISSUE TITLE
Resourceful Bees JEI Problem

### ISSUE THREAD

**Issue by MRT-CO** [NillerMedDild/Enigmatica6#1424]
I don't know how really it's caused, but it's happening to me twice today and some players have same issue, the issue is fixed after restarting the game.

That is the JEI from bees.
![image](https://user-images.githubusercontent.com/39351347/109238496-53f4e180-77dc-11eb-8673-2c1c2b5c0775.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
As a temporary workaround, using the `/reload` command fixes it.

**Comment by Mizque** [comment]
Issue persists in 0.4.3

**Comment by NillerMedDild** [comment]
Really? O_o

**Comment by Mizque** [comment]
yes, further, the mechanical centrifuge does not show recipe's seems only the powered one does for that, JEI doesn't show any info on the bee mutation effects, and the book for the resourceful bee's doesn't either.
