### ISSUE TITLE
End Stone smelter has broken GUI

### ISSUE THREAD

**Issue by SeaSaltStar** [NillerMedDild/Enigmatica6#1426]
**Modpack version**
0.4.0
**Describe the bug**
The end stone smelter has a missing texture for a GUI. This occurs with and without ERP/Optifine
**Screenshots**
https://imgur.com/a/x87Csxu

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it :)

**Comment by NillerMedDild** [comment]
Woops, this was fixed in 0.4.2

**Comment by Payta2014** [comment]
https://www.reddit.com/user/Sad_Palpitation700/comments/1elbp6n/end_stone_smelter_betterend_mod/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by NielsPilgaard** [comment]
Do you have this issue on the latest version of E6 @Payta2014 ?
