### ISSUE TITLE
Some ores not generating in Nether

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1427]
**Modpack version**
0.4.0
**Describe the bug**
According to the into tab in JEI, only the following EE ores spawn in the Nether: Coal, Gold, Redstone, Copper, Lead, Uranium, Osmium, Fluorite, Bitumen, Cinnabar, Sulfur, Potassium Nitrate.
So it's missing Iron, Diamond, Emerald, Lapis, Aluminum, Silver, Nickel, Tin, Zinc, Apatite, and Arcane. Some of these may be intended, but it looks like they are mostly mistakenly omitted.

**Comment by theboo** [comment]
This is intended... There are some ores that generate in the nether and some that generate in the end as well, but neither dim has all ores

**Comment by Merlo17** [comment]
![Cattura](https://user-images.githubusercontent.com/62080872/109286213-406c6980-7822-11eb-8b7e-871f843b6ead.PNG)

Spreadsheet for reference
