### ISSUE TITLE
Botania Quest Text Error

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#1429]
**Modpack version**
0.4.0
**Describe the bug**
The quest for Livingwood and Livingrock has an invalid quest title.

**Screenshots**
![2021-02-26_03 10 44](https://user-images.githubusercontent.com/41839144/109273619-6e30be80-77e0-11eb-8caf-0814487bbd4f.png)

**Comment by Merlo17** [comment]
ty, I'll close this issue and move it over to https://github.com/NillerMedDild/Enigmatica6/issues/1139 :D
