### ISSUE TITLE
Crash Refine Storage access recipe Hardened glass thermal recip

### ISSUE THREAD

**Issue by KoloNiko** [NillerMedDild/Enigmatica6#1432]
**Enigmatica 6-0.4.0**

**Describe the bug**
Crash When access recipe Hardened glass of Thermal ->in Refined storageoor simply patern recip of hardened glass in inventory after breaking crafter of refined storage

**Logs**
https://pastebin.com/2m9zL0hF

Currently i'm stuck with recipe in my player inventory and crash when i open my inventory.

**Comment by NillerMedDild** [comment]
Thanks for the report.
@Darkere a penny for your thoughts on this :P

**Comment by Darkere** [comment]
Might be an emtpy tag?

**Comment by NillerMedDild** [comment]
I can't reproduce this at all - You'll have to either edit your player data, or delete it to fix the issue I'm guessing. Or simply die and don't pick up your stuff.
