### ISSUE TITLE
Emerald generation seems to not be working on 0.3.13

### ISSUE THREAD

**Issue by anagram3k** [NillerMedDild/Enigmatica6#1433]
**Modpack version**
Enigmatica 6 v0.3.13

**Describe the bug**
I found a very high mountain (Guiana Shield) and can't find any generated ore, much less emerald. 
I mined from 100y to 180y about 5k blocks, found nothing.

**Comment by NillerMedDild** [comment]
Most likely fixed in 0.4.0 :)

**Comment by adroslice** [comment]
I can't find any emerald ore generating in version 0.5.4. The world settings were left at default.

**Comment by NillerMedDild** [comment]
Where did you look? :)

**Comment by adroslice** [comment]
Various "Oh the biomes you'll go" biomes, especially mountainous ones, and in an rftools dimension relatively close to vanilla overworld, roofed forest and mountains. I checked using a Digital Miner from Mekanism set to the tag "forge:ores/emerald".

**Comment by Ridanisaurus** [comment]
I have found multiple (at least 50+) Emerald Ores in high mountains, at the peaks. I can confirm it spawns/generates as expected.

**Comment by anagram3k** [comment]
This bug is closed and was fixed in 0.4.0

Everything is working fine. Sorry if I didn't comment and made it clear this was the case.
