### ISSUE TITLE
Refined storage questline should accept any storage disk

### ISSUE THREAD

**Issue by Xferz1** [NillerMedDild/Enigmatica6#1435]
**CurseForge Link**

**Description**
Write a short description of your suggestion here.
Make it so that refined storage questline can accept any storage disk instead of just 1k storage disk.
**Why would you like this added/changed?**
I'm required to do a 1k storage disk to complete the questline when i really just want to do a 4k or higher because they are better and i have the resources for it. You can also not upgrade a 1K storage disk to a higher tier neither so you have to otherwise keep it or throw it away.
**Screenshots if applicable.**

**Comment by Chrisalisa** [comment]
You can just shift-right click with a storage disk in hand to retrieve the storage part and an empty housing which you can then use to craft higher capacity storage disks. Not an issue imho.

**Comment by Xferz1** [comment]
I didn't know that

**Comment by Chrisalisa** [comment]
No worries! The more you know! Perhaps could still be a good idea to point it out in the quest description since perhaps that line was removed at some point because I think I remember seeing it at some point in the past.

**Comment by MuteTiefling** [comment]
It already mentions the means of recovery

![image](https://user-images.githubusercontent.com/9543430/109372777-59ecd000-7879-11eb-9a55-41e603aa0639.png)

I've gone ahead and extended the item and fluid storage disk quests to accept any RS item of fluid storage disk, respectively.
