### ISSUE TITLE
Akashic Tome crashes game when used

### ISSUE THREAD

**Issue by UndoneDestiney** [NillerMedDild/Enigmatica6#1436]
ever since the update the akashic tome crashes my game when i try to use it and sometimes when i move it from
[crash-2021-02-25_12.49.31-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6051093/crash-2021-02-25_12.49.31-client.txt)
[crash-2021-02-25_14.23.12-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6051094/crash-2021-02-25_14.23.12-client.txt)
[crash-2021-02-25_15.54.13-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6051095/crash-2021-02-25_15.54.13-client.txt)
[crash-2021-02-25_16.54.59-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6051096/crash-2021-02-25_16.54.59-client.txt)
[crash-2021-02-25_19.18.07-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6051097/crash-2021-02-25_19.18.07-client.txt)
[crash-2021-02-25_19.45.21-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6051098/crash-2021-02-25_19.45.21-client.txt)

m one backpack to my inventory

**Comment by Mendanbar** [comment]
Not sure if this is related, but mine was doing this when I copied it from my old world to the updated one.  I fixed it by trashing the old one and creating a new one in the update.  New one works fine.

**Comment by NillerMedDild** [comment]
Huh, weird issue. Does Mendanbar's proposed solution work for you?

**Comment by Mendanbar** [comment]
FYI I had the same problem with the Morph-o-tool.  My best guess is that the tool/book IDs/data changed between updates and the all-in-ones that are copied from an old world are trying to reference invalid data? IDK

**Comment by P3pp3rF1y** [comment]
I can see this change in akashic tome https://github.com/Vazkii/AkashicTome/commit/69f1ff95fb4a9eab395da87ab09c4748cfb4d122 

So basically the way display name is stored has changed which means item created before this change will have the issue, probably makes sense to let people know to get a brand new one if they are updating their worlds

**Comment by UndoneDestiney** [comment]
Mendanbar's solution worked its fine now
