### ISSUE TITLE
Pedestal Linking tool can't be added to morpho tool

### ISSUE THREAD

**Issue by cameronfowler** [NillerMedDild/Enigmatica6#1437]
**Description**
Right now the pedestal linking tool can't be added to the morpho tool.  My proposal is to add it to the valid tools to be combined.
**Why would you like this added/changed?**
Like most other things that combine with the morpho tool, it would be nice to not have to go grab the separate tool just to link pedestals.  While it wouldn't work properly in crafting recipes, we already have hammers that can be combined that also are used in recipes, so like those, you would just need to make a second one to keep in your storage.

**Comment by Rodg88** [comment]
I wonder if the shift-right click feature of the linking tool to change to a reverse linking tool would break the morph-o-tool?

**Comment by Merlo17** [comment]
I believe the filled one you can craft should come with the linking tool already. I probably forgot to add it to the filter as well, my bad. Should be an easy fix ^^

**Comment by NillerMedDild** [comment]
Using the Linking Tool's shift ability turns it into a normal reverse linking tool, effectively destryoing the Morph'o'tool. I've reverted the PR and this issue will not be implemented :)
