### ISSUE TITLE
After a certain distance block overlays stop working.

### ISSUE THREAD

**Issue by Johnnycyan** [NillerMedDild/Enigmatica6#1439]
**Modpack version**
0.4.0
**Describe the bug**
My base is around 5 million blocks away from 0 0. Apparently this far out the overlay for everything gets broken. ultamine overlay is broken, light overlay is broken, chisel and bits overlay is broken. I know it has to do with the distance because going back to 0 0 it stops happening.
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
N/A
**Screenshots**
![image](https://user-images.githubusercontent.com/24556317/109333858-f38e9000-782d-11eb-84ae-a46a57939079.png)
![image](https://user-images.githubusercontent.com/24556317/109333964-1751d600-782e-11eb-9ba1-dc84d8feade5.png)

**Comment by NillerMedDild** [comment]
I believe this is a vanilla issue - Going past 400.000 blocks, the game starts to destabilize. I could be wrong here, though :P

**Comment by Johnnycyan** [comment]
I tested and it seems to happen even at 100,000 blocks out. It's mostly fine at 64,000 blocks out. And is fully stable at anything less than 32,000 blocks out.

**Comment by ochotonida** [comment]
This is indeed a vanilla issue, I get the same results with just Forge and Ultimine at z = ~5 million
![image](https://user-images.githubusercontent.com/37985539/109365752-34b88b80-7892-11eb-9742-3afe72c45a9e.png)

**Comment by Johnnycyan** [comment]
I guess technically it could be vanilla minecraft or forge to blame then. Oh well. Thank you for checking

**Comment by Darkere** [comment]
At 100k it might be worth a report. Not much hope for a fix though. The math for that is a pita.
