### ISSUE TITLE
Botany pot, time extended=

### ISSUE THREAD

**Issue by zululul** [NillerMedDild/Enigmatica6#1440]
**Modpack version**

Latest (0.4.0)

**Describe the bug**
If you didn't notice, I played from 03.13 and updated the modpack to the latest 0.4.0 and the botany pots have increased it's time. To grow for an example a mushroom, it took about 1 min, now it's increased to 10 more minutes.
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by r-mc2** [comment]
Slower botany pots was an intended nerf from the pack authors. They felt they were too OP and denied your ability to explore other methods of growing things. So rather than remove them from the pack they were slowed to their current state.

**Comment by Merlo17** [comment]
They also have increased yield to make up for the slower time. You can read all about it here https://github.com/NillerMedDild/Enigmatica6/issues/528#issuecomment-768620096

**Comment by zululul** [comment]
Yeah but it doesn't make sense that it takes 10 minutes? instead of 1 minute. Why not make the time as it is for an normal crop to grow then? how is it a nerf when they over nerfed it? then it's no point to have these in the modpack.

**Comment by TemperedFool** [comment]
They were left in to produce small amounts of stuff, but not be a replacement for actual farming, and because some people like them for making pretty builds. This was discussed to death in #528, so it would be a good idea to go read through that.

**Comment by theboo** [comment]
it actually produces more per minute than it did in .13... if you NEED STUFF NOW, time in a bottle works on it just fine :)

**Comment by Merlo17** [comment]
TDLR - this still makes them a passive source of crops/trees and as boo said it's actually really good. Having it take that long however makes it so you can't use it in automation setups (i.e. power a create flywheel) and need to explore more interesting options to have a faster income

**Comment by TemperedFool** [comment]
IMO the production-per-proc boost is too generous ^_^
