### ISSUE TITLE
Create Plus

### ISSUE THREAD

**Issue by runcreeper** [NillerMedDild/Enigmatica6#1442]
---------------------------->

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/create-plus
**Mod description**
Adds in Vanilla helmets with create engineers goggles, same for mekanism helmet, and adds support for putting engineers goggles in a curio slot
**Why would you like the mod added?**
So I can run around with full armor and the goggles for Create.

**Comment by NillerMedDild** [comment]
Sure thing, thanks for the suggestion.

**Comment by TemperedFool** [comment]
I very much want this, but I don't see any sort of issue tracker which is sad. Needs support for PNC armor... which I would report if I could find a tracker!

**Comment by Merlo17** [comment]
Curio support would be good enough imo

**Comment by MuteTiefling** [comment]
> I very much want this, but I don't see any sort of issue tracker which is sad. Needs support for PNC armor... which I would report if I could find a tracker!

I wonder if desht would be willing to add an upgrade to the helm actually...
