### ISSUE TITLE
Engimatica 4.1 Crates

### ISSUE THREAD

**Issue by MaxiStein** [NillerMedDild/Enigmatica6#1448]
**Enigmatic 6 4.1
With the new update to 4.1, I no longer see iron, gold and diamond crates in the storage quest.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by anivlys** [comment]
I think those crates were part of Quantum Storage, which was removed in 0.4.0 if I'm not mistaken.

**Comment by MaxiStein** [comment]
that's too bad. i liked those crates.
