### ISSUE TITLE
FTB Chunks introduces it's own overworld map

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#145]
**Modpack version**
0.2.7

**Issue**
With the addition of FTB chunks, pressing M opens its world map instead of Xaeros world map. This can be fixed by changing xaero's world map keybind, but that's about it. Not sure if possible to disable FTB chunks world map.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
It cannot be disabled sadly, and I have changed the default keybinding :) nothing more I can do without overwriting all keybindings sadly.
