### ISSUE TITLE
Allow other 'stone' to be used in PNC crafting

### ISSUE THREAD

**Issue by wadeg-sait** [NillerMedDild/Enigmatica6#1450]
**Description**
Trying to make Reinforced bricks for PNC chamber walls, and I'm in a biome that has very little stone. I've tried using Gabbro, Slate, Andesite but the recipe won't accept any of those, however, I can use them in place of stone in other recipes.

**Why would you like this added/changed?**
Make's it more playable when you are in a biome with little to no stone or to use up the reserves of other materials you may have

**Screenshots if applicable.**

**Comment by TemperedFool** [comment]
@wadeg-sait you could use either a silky gen from Pedestals (put stone under it) or a vanilla stone gen (falling lava hitting running water) with a silk touch block breaker (I recommend Modular Routers) to get as much stone as you'll need.

**Comment by NillerMedDild** [comment]
We'll look into it :)
