### ISSUE TITLE
[0.4.1] Can't create the "Feedthrough Insulator" multiblock

### ISSUE THREAD

**Issue by real-chair** [NillerMedDild/Enigmatica6#1451]
0.4.1

As of 0.4.1 I am unable to create the feedthrough insulator from Immersive Engineering. I've attempted it with all connector variants, the Engineer's hammer, the Enigmatic hammer, and the Engineer's screwdriver, in both horizontal and vertical orientations; nothing works. Unsure if others are having this problem, but no one has been able to help me figure it out.

![image](https://user-images.githubusercontent.com/71352104/109378812-7dc50b80-78a3-11eb-8054-e17a36923137.png)

**Comment by MuteTiefling** [comment]
That's not how you run power to those lamps. You just connect the wire straight into it.

I'm assuming that you think your connection is not working because the light isn't turning on, right?

**Comment by Rodg88** [comment]
I can confirm the bug - I had a passthrough setup in 0.4.0, and I broke it and tried to remake it in 0.4.1, and it wouldn't form at all.

**Comment by real-chair** [comment]
Sorry about that.
The demonstration is flawed but the bug still is applicable. Should I edit it with a new screenshot or add one in the comments?

**Comment by NillerMedDild** [comment]
I'm not familiar with this multiblock, what does it do? I was unable to find it in the manual.

**Comment by TemperedFool** [comment]
@NillerMedDild if you look at the screenshot, the "multiblock" connects the two connectors on either side of the block electrically, allowing you to pass power through a wall or floor without a wire through a hole.

**Comment by NillerMedDild** [comment]
Ahh cool.

**Comment by NillerMedDild** [comment]
The thing is, we didn't update IE between 0.4.0 and 0.4.1, so this is most likely something else.

**Comment by NillerMedDild** [comment]
Caused by FerriteCore apparently :P
