### ISSUE TITLE
Astral Sorcery Neromantic Prime - only water and lava is available despite configs

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1452]
**Modpack version**
0.4.0

**Describe the bug**
1) Ichosic Resonator shows only water and lava, despite other fluids available in configs
2) Neromantic Prime only fetches water and lava, as indicated by Ichosic Resonator

**Screenshots**
![2021-02-27_21 38 21](https://user-images.githubusercontent.com/13237198/109387333-380c4f80-7944-11eb-8b91-18f831ff0bef.png)

**Comment by NillerMedDild** [comment]
They are very very rare, how much did you look? :)

**Comment by HaxtonSale1** [comment]
I wouldn't call weight of 5000 (oil) or 2500 (heavy water) very very rare (compared to 14000 (water) or 7000 (lava))

![2021-02-28_09 30 21](https://user-images.githubusercontent.com/13237198/109404261-a7675b00-79a7-11eb-86bd-92d992349def.png)
![2021-02-28_09 30 23](https://user-images.githubusercontent.com/13237198/109404262-a8988800-79a7-11eb-8520-0cc75a99b676.png)
![2021-02-28_09 30 07](https://user-images.githubusercontent.com/13237198/109404260-a59d9780-79a7-11eb-9827-019137dd4525.png)

at least 10s of different locations across 2 savefiles, would that be enough?

to prove that there was something wrong I removed water and lava from the config table (in defaultconfigs folder), and made a new world. Those 2 still showed up

**Comment by NillerMedDild** [comment]
Fair enough, thanks for the thorough testing. And you're certain those two are water and lava?

**Comment by HaxtonSale1** [comment]
I assume those are, because I got nothing else from Neromantic Prime
