### ISSUE TITLE
[Suggestion] Bad Wither No Cookie

### ISSUE THREAD

**Issue by Buuz135** [NillerMedDild/Enigmatica6#1457]
https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded

Removes global wither sound

**Comment by NillerMedDild** [comment]
You can use Extreme Sound Muffler for that, the button is in your inventory :)

**Comment by NillerMedDild** [comment]
I was strong-armed into re-adding this :(
