### ISSUE TITLE
Block placer (industrialforegoing) wont place blocks!

### ISSUE THREAD

**Issue by zululul** [NillerMedDild/Enigmatica6#1458]
**Modpack version**
0.4.0
**Describe the bug**
When I put a block inside the block placer it wont place the block it just makes the sound of the block, for example I put wood in it, it makes wood sound but it wont place it. I tried with other blocks it doesn't work.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![image](https://user-images.githubusercontent.com/33579344/109398207-b0224780-793b-11eb-9b7c-9b229b767d1b.png)

**Comment by TemperedFool** [comment]
@zululul Is this in a claimed chunk? If so did you ally with the fake player for the placer? Hit e, teams button in the upper left.

**Comment by zululul** [comment]
Omg thank you, you saved my day :)

**Comment by TemperedFool** [comment]
Happy to help. Worth passing that kind of question through the discord ^_^

**Comment by zululul** [comment]
Oh there is a Discord for helps and stuff? I don't mind checking it out.
