### ISSUE TITLE
Give our Akashic Tome instead of all manuals separately

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1459]
While we're at it, may want to change intro quests for mods to be acquire the "first item", instead of checkmark.

**Comment by TemperedFool** [comment]
A.k.a the great mod quest tree intro refactor?

**Comment by NillerMedDild** [comment]
Yes :P

**Comment by MuteTiefling** [comment]
Quest added to Getting Started that gives the filled Akashic Tome and explains usage.

All manuals have been subsequently punted from their chapters. In many cases this had little impact as the starting quest had a couple items it gave out. In some cases, however, I couldn't find suitable items to give, so I just gave the bog standard 100 xp points.
