### ISSUE TITLE
Failed to sync registry error

### ISSUE THREAD

**Issue by marckyj** [NillerMedDild/Enigmatica6#1461]
**0.4.1**

**Describe the bug**
We have updated to the latest version and imported our 3.13 world but can no longer connect via Lan giving the failed to sync registry error. We can connect on a newly generated world just fine

**Logs**
https://pastebin.com/Zj1Sp99p

**Screenshots**

**Comment by Merlo17** [comment]
a world reset is highly recommended (if not needed) for 0.4.x. Please read the changelog

**Comment by marckyj** [comment]
Yeah I read that but was hoping there would be a way to continue with our existing save put way to many hours in to give up on it yet

**Comment by NillerMedDild** [comment]
If you both reinstall 0.4.1 and re-add the world you may be able to play together.
