### ISSUE TITLE
Green Dye crafting recipe from Yellow and Blue Dye

### ISSUE THREAD

**Issue by tipmon** [NillerMedDild/Enigmatica6#1467]
Both Minecraft's green dye and Pane in the Glass's Green Dye can be crafted from Yellow and Blue Dye. The first recipe, for Minecraft's dye, gives 2 dye which would be the expected amount based on dye mixing. The Pane in the Glass green dye recipe only gives 1 dye.

I would expect both of these recipes to produce 2 dye, regardless of the dye type made.

**Comment by NillerMedDild** [comment]
Thank you for the report!

I removed the PITG recipe and dye, so it's just the vanilla one now. I also submitted a PR to PITG to fix the output amount.
