### ISSUE TITLE
Re-add Ranged Pumps

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#147]
I thought it was duplicate content, but the Ranged Pump doesn't cause flowing blocks, so it's coming back.

**Comment by ben-mkiv** [comment]
Immersive Engineering Pump also places cobble

**Comment by NillerMedDild** [comment]
Immersive Engineering Pump doesn't seem to work very well, it's nearly impossible to get it to pump lava I find.
