### ISSUE TITLE
Undergarden SMP generation

### ISSUE THREAD

**Issue by shibeobi12** [NillerMedDild/Enigmatica6#1472]
**Modpack version**
0.4.1 (Client) with a local server also on 0.4.1
**Describe the bug**
Generating the undergarden results in.... nothing, aside from the dirt and stone variants. Screenshots attached. Some mobs seem to spawn, but overall I don't think this is the actual generation. Tried it in SP on creative and it was a completely different experience. (Which I believe is the right generation!)
I used a night vision effect so pardon the weird lighting.

**Logs**
Let me know if server logs help here, it just takes a bit to grab them.

**Screenshots**
![2021-02-28_09 45 31](https://user-images.githubusercontent.com/50844560/109426936-43e02c00-79ad-11eb-9f0f-e52bfe11b370.png)
![2021-02-28_09 59 22](https://user-images.githubusercontent.com/50844560/109426938-45115900-79ad-11eb-9840-64d5bf1978f9.png)

**Comment by 2xMJet** [comment]
In addition to it its know Immersive Engineering and The Undergarden Compat issue reported there:
https://github.com/BluSunrize/ImmersiveEngineering/issues/4642

**Comment by NillerMedDild** [comment]
Hmm, IE oregen is already off :/

**Comment by 2xMJet** [comment]
> Hmm, IE oregen is already off :/
> Edit: Thanks for the report!

i'm not entirely sure if ore-gen itself causes it but for that i've brought issue from IE issue-tracker with me

**Comment by shibeobi12** [comment]
Yeah, it's odd that the client can do it in SP just fine but not the server-side.

**Comment by Trostmm** [comment]
It throws a PILE of errors when you start a server about undergarden - 
[latest_under.log](https://github.com/NillerMedDild/Enigmatica6/files/6058604/latest_under.log)

Not sure what's causing them..

**Comment by NillerMedDild** [comment]
Looks like IE is causing them. This issue is fixed in IE, no need to comment :)
