### ISSUE TITLE
custom search terms

### ISSUE THREAD

**Issue by Trainzdriver** [NillerMedDild/Enigmatica6#1478]
**Description**
a way to search for enchanted books based on which items the enchantment can be applied to (example: $enchantedbook/sword) in the JEI search bar making use of the custom search format

**Why would you like this added/changed?**
it would make the enchanting of items easier and allow for players to have a better understanding of what enchantments can go on which items

**Comment by Merlo17** [comment]
JEI already has a tab that shows what enchants can be put on what?

**Comment by Trainzdriver** [comment]
ya i discovered that shortly after, tho it would still be nice i think to have it just in the menu

**Comment by NillerMedDild** [comment]
Too much work/maintenance for something that already exists, sorry :)
