### ISSUE TITLE
Granite not being created on top of diamond block

### ISSUE THREAD

**Issue by H4RV3Y2805** [NillerMedDild/Enigmatica6#1479]
**Modpack version**
0.4.1

**Describe the bug**
JEI Says: "Can be generated in a Vanilla Stone Generator. The block below where the stone generates needs to be a block of diamond." I've set this up and I still get cobblestone.

**Logs**
Not applicable.

**Screenshots**
https://ibb.co/KbN82NP

**Comment by Merlo17** [comment]
you will need to set up a stone generator according to vanilla's mechanics: lava needs to come from above
