### ISSUE TITLE
Same Ores on Overworld

### ISSUE THREAD

**Issue by MrCarlet** [NillerMedDild/Enigmatica6#148]
**Modpack version**
0.2.7
**Issue**
There are 2 different fluorite ores
One from Mekanism other from Emendatusenigmatica

**Logs**
![2020-08-16_17 41 03](https://user-images.githubusercontent.com/47258022/90337012-38687d00-dfe8-11ea-99ec-6d769cf0afe0.png)

**Comment by NillerMedDild** [comment]
thanks for the report, got it fixed in-dev, should be released this evening :)
