### ISSUE TITLE
Mekanism Lithium Quest is confusing

### ISSUE THREAD

**Issue by Rodnock** [NillerMedDild/Enigmatica6#1481]
**Description**
The Lithium quest in the Mekanism questline makes it sound like you can go directly from liquid lithium to a Chemical Crystallizer to produce lithium dust.  I could not get it to hook up so I looked on the Mekanism wiki and found that you need to pipe the liquid lithium from the thermal evaporation tower into a Rotary Condensentrator first to get Lithium (gas) from Liquid Lithium, and then you can pipe the lithium into the Chemical Crystallizer to get Lithium Dust.

Another paragraph about the Rotary Condensentrator would be helpful for people who have never worked with Lithium before, like myself.

**Why would you like this added/changed?**
Clarification.

**Screenshots if applicable.**
![Image of Quest](https://imgur.com/a/HWT5Baf)

**Comment by NillerMedDild** [comment]
Already fixed in-dev :) thanks for the report.
