### ISSUE TITLE
Make powah reactor upgrades cheaper

### ISSUE THREAD

**Issue by EPostill** [NillerMedDild/Enigmatica6#1482]
**Description**
make the recipe for upgrading reactors 4 tier n reactor blocks plus 4 tier n+1 capacitors in exchange for 4 tier n+1 reactor blocks, alternatively, 1 tier n reactor block + 1 tier n+1 capacitor

**Why would you like this added/changed?**
Right now, to upgrade a reactor requires 1 of the old tier plus 4 capacitors of the new tier in exchange for one upgraded reactor block. Alternatively, you can spend 1 dieletric casing and 4 uranium plus 4 capacitors to get 4 reactor blocks, getting 4x the reactor blocks for the same capacitor cost. I think it should be cheaper to upgrade than just create a whole new reactor.

**Comment by MuteTiefling** [comment]
Ah, right. I thought I had covered that...
