### ISSUE TITLE
Memory Leak or something. Slowly bringing server to a crawl.

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#1485]
**Modpack version**
0.4.1

**Describe the bug**
Some sort of memory leak or something that is slowly bringing the server to a crawl. Let me know how I can further pinpoint the problem and I will do so. Thanks!

**Logs**
https://gist.github.com/RevenantWendigo/b19aa79ff70918330f18c229f2a76d8c

**Screenshots**
![image](https://user-images.githubusercontent.com/1980813/109463909-0ae29e80-7a23-11eb-8dd1-9cefe3c64ef0.png)

**Comment by RevenantWendigo** [comment]
Spark heapsummary: https://spark.lucko.me/#nMxOmmL957

**Comment by RevenantWendigo** [comment]
Spark profiler: https://spark.lucko.me/#If16SoXcld

**Comment by Darkere** [comment]
Presumably a ton of animals are running around on some complex voxel shapes. Might be an idea to try and find them.

**Comment by RevenantWendigo** [comment]
I uhhh.... had too many cows. I went on a massacre and now my server is good again. Oops!
