### ISSUE TITLE
Elytra functions while broken

### ISSUE THREAD

**Issue by TheSnipingDwarf** [NillerMedDild/Enigmatica6#1490]
Enigmatica 6 Version 0.3.13 on CurseForge
(while playing on a dedicated server by myself)
The Vanilla Minecraft Elytra functions while broken. that's it. Mine was in an accessory slot when it broke.

![2021-03-01_11 35 08](https://user-images.githubusercontent.com/59490663/109528999-44e38d00-7a83-11eb-99d0-9cec111fb111.png)
![2021-03-01_11 34 48](https://user-images.githubusercontent.com/59490663/109529005-4614ba00-7a83-11eb-88f0-c9073a5f9a4e.png)
![2021-03-01_11 34 49](https://user-images.githubusercontent.com/59490663/109529010-46ad5080-7a83-11eb-8e9d-570c337a6ce3.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Moved to https://github.com/NillerMedDild/Enigmatica6/issues/1496 because that one is linked to the mod issue.
