### ISSUE TITLE
Add Create-native way to make zinc and copper?

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1491]
**Description**
Easy mode: 

> Scoria > (Crush) > Black Sand (BYG) > (Wash) > Zinc nuggets
> Gabbro > (Crush) > Orange Sand (BYG) > (Wash) > Copper nuggets

Hard mode (Idea stolen from Evelyn Ivy from the Create discord):

> Dirt > (Wash) > Zinc nuggets
> Clay > (Wash) > Copper nuggets

**Why would you like this added/changed?**
Create doesn't have native way to make copper or zinc; I think it'd be neat if there was a way

**Comment by Merlo17** [comment]
I don't see why a simple mixing recipe with copper and zinc wouldn't work?

**Comment by HaxtonSale1** [comment]
I meant a way to generate copper and zinc from nothing, the way Create can be used for generating iron and gold from nothing

**Comment by Merlo17** [comment]
okay, don't mind me. I completely swapped zinc and brass and thought you were talking about that, whoooooops

The problem with this is I don't see why we should give it to only copper and zinc, at this point might as well give it to all materials. not sure which recipes i'd use though

**Comment by TemperedFool** [comment]
I pointed out in #suggestions that this is something Create probably should do? That way all their metals would be renewable. Would still be cool to do either way, and expanding it out to other metals would also be cool if more design work (that maybe belongs in expert).

**Comment by HaxtonSale1** [comment]
Copper and Zinc are special in that those 2 are used in Create; those also aren't renewable with Create only
I'm now kinda on the fence about whether we should do this or not, because I agree with TemperedFool's argument, but on the other hand, this adds a way for those 2 metals to be renewable with create only

**Comment by HaxtonSale1** [comment]
On Create github, someone said the devs don't want brass to be renewable.

**Comment by NillerMedDild** [comment]
I don't think this is a good idea to be honest.
