### ISSUE TITLE
RFTools Quests - XNet Tutorial Link is timestamped

### ISSUE THREAD

**Issue by AtlasTheProto** [NillerMedDild/Enigmatica6#1494]
**Modpack version**
0.4.1

**Describe the bug**
The link provided to the user for redeeming the _XNet Tutorial Link_ quest is timestamped, resulting in the video starting halfway through.

**Offending code - Line 877**

https://github.com/NillerMedDild/Enigmatica6/blob/b7ef8cd0398a151aa1ac644645e4ab4c0c769e48/config/ftbquests/quests/chapters/rftools_wip.snbt#L872-L879

**Comment by NillerMedDild** [comment]
Thanks, fixed!
