### ISSUE TITLE
Ender Biotite has no use

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#1497]
**Modpack version**
0.4.1

**Describe the bug**
Ender Biotite (Quark) can be obtained by mining in the End, but the item itself is hidden in JEI and has no use besides being crushed into useless dust. Even blocks can't be crafted.

**Comment by NillerMedDild** [comment]
Interesting, Biotite is disabled in the config. I guess I'll disable it harder.
