### ISSUE TITLE
Chunk loading via FTB chunks doesn't work

### ISSUE THREAD

**Issue by localzuk** [NillerMedDild/Enigmatica6#1498]
**Modpack version**

Pack 0.4.1 (including running the server pack)

**Describe the bug**

The chunk loading in FTB Chunks doesn't work. When a player logs off, their machines shut down when the chunk is unloaded.

**To reproduce** 

Make some machines. I tested by having a vanilla Blast Furnace running, a Powah Furnator (Hardened) and a Mekanism Enrichment Chamber. I had coal in the furnator and furnace, and iron chunks and iron dust in the enrichment chamber and furnace.

I claimed some chunks via the FTB Chunks "Claim chunks" map, and then shift clicked to then force load them.

I put a full stack in each machine and logged off. I logged back on 25 minutes later. Only 6 dust had been processed into ingots, and 6 chunks into 12 dust. Sitting at the machines in person, the machines processed all the iron chunks/ore in a matter of a few minutes.

**Comment by TemperedFool** [comment]
The default config disables chunk loading while players are offline - you can change this in the ftbchunks-server config.

**Comment by localzuk** [comment]
There is no ftbchunks-server config file... Only a ftbchunks-client.toml

If there had been such a file, I would have looked at it?

![image](https://user-images.githubusercontent.com/998988/109558097-e04f1f00-7ad0-11eb-9626-e3f5a4263c81.png)

**Comment by TemperedFool** [comment]
@localzuk check the defaultconfigs folder - server configs are in there.

**Comment by localzuk** [comment]
Thank you.

**Comment by theboo** [comment]
Make sure you change it in world/serverconfigs/ftbchunks-server.toml

**Comment by localzuk** [comment]
Thanks @theboo. These extra config folders are new to me!
