### ISSUE TITLE
Rat duping

### ISSUE THREAD

**Issue by tonyvans** [NillerMedDild/Enigmatica6#15]
**Modpack version**
0.1.7

**Issue**
Server reboots are casing some Rats to get duplicated (example, this white rat with bucket, I have only ever created one of them
![2020-07-19_11 40 48](https://user-images.githubusercontent.com/6739653/87882676-93da2780-c9b6-11ea-92f9-5b0fc55687e8.png)

same with these rats. however the Remy rat seen here in the top left has never duplicated.
![2020-07-19_11 40 57](https://user-images.githubusercontent.com/6739653/87882502-27aaf400-c9b5-11ea-8509-ad1d1aea38df.png)

I presume only the original seems to get duplicated (which is why there are 3 and not 4) after 3 server reboots

(server is rebooted only to freshen up things and for manual backup since backups do not seem functional in this amazing but new forge pack)
 
Thanks and keep up the good work

**Comment by NillerMedDild** [comment]
I re-posted your issue on the Rats issue tracker, thanks for the report!

**Comment by tonyvans** [comment]
and thank you

remy just duplicated, no server reboot needed, just re-logged in
![2020-07-19_12 41 11](https://user-images.githubusercontent.com/6739653/87883616-82e0e480-c9bd-11ea-8d40-448ac33bb7e9.png)

**Comment by tonyvans** [comment]
This issue seems to have gone away. I am back to the original number of rats, and has been no issue since.
Thanks
