### ISSUE TITLE
ender io like conduit

### ISSUE THREAD

**Issue by Trainzdriver** [NillerMedDild/Enigmatica6#1500]
**Description**
a system similar to the ender io conduit that could move power, fluids, items, etc with the ability to have multiple different types be placed within the same block

**Why would you like this added/changed?**
it would be a very effective way to cut back on base management difficulties, and i have quite enjoyed using the conduit in previous packs, it could also be a nice functional way to make a base look nice

**Comment by NillerMedDild** [comment]
I recommend that you have a look at XNet :)

**Comment by Trainzdriver** [comment]
ill take a look at that its just not as pretty or simple as ender io was

**Comment by NillerMedDild** [comment]
Indeed, hopefully EnderIO cables get ported some day.
