### ISSUE TITLE
Amadron Tablet offers use non EE Aluminum

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1507]
Enigmatica 6 0.4.2 (official server)
The amadron tablet offers use the Immersive Engineering aluminum ingots rather than the EE aluminum ingots:
![image](https://user-images.githubusercontent.com/9061144/109593659-ffe94600-7ad6-11eb-9090-ab7652db28bc.png)

**Comment by Merlo17** [comment]
Those come for villager trades and as such this should be a duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/1187 and already reported to the mod. Hopefully it gets taken care soon or a feature is added that allows us to tweak that ^^

**Comment by NillerMedDild** [comment]
While this is technically a duplicate, I've reopened it for tracking and changelog purposes :)
