### ISSUE TITLE
Lootr & Dungeon Crawl Interaction

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#1508]
**Modpack version**
0.4.1
**Describe the bug**
Dungeon Crawl dungeons have "trap" rooms that have one or two trapped chests with TNT below them. However, because Lootr replaces all the chests in the dungeons the TNT can no longer be triggered.

Looking at Lootr's issue tracker it is noted that trapped Lootr chests should be an option (https://github.com/noobanidus/Lootr/issues/6), but these trapped chests are being replaced with normal versions.

The below shows TNT that will not be activated by opening the chest (when the block below isn't broken).

![2021-03-01_22 53 37](https://user-images.githubusercontent.com/41839144/109594577-0b416f00-7ae1-11eb-92e1-cb93e3b7aced.png)

**Comment by NillerMedDild** [comment]
@Noobanidus Got a Lootr issue here with a Dungeon Crawl Trapped chest that has been replaced by a non-trapped Lootr chest.

**Comment by noobanidus** [comment]
Tagging is fine. This is something I've fixed and I think it's in the release I'm making today.

**Comment by NillerMedDild** [comment]
Awesome, thanks!

**Comment by noobanidus** [comment]
And it's just been approved; I'd been delaying as one of the features I'd added was specifically requested and I wanted to get feedback from some people on it (custom chests), but unfortunately I haven't had any replies over the weekend, so I decided to just release now anyway.

**Comment by noobanidus** [comment]
And for the record, that *is* a trapped chest and it *does* attempt to trigger the redstone signal, there was just a bug where that wouldn't go through.

**Comment by NillerMedDild** [comment]
Thanks!
