### ISSUE TITLE
Two different crafting recipe

### ISSUE THREAD

**Issue by MrCarlet** [NillerMedDild/Enigmatica6#151]
**Modpack version**
0.2.7

**Issue**
Infinity Hammer has 2 different crafting recipe I don't know if it's Industrial Foregoing's fault but it won't hurt to say it

**Comment by NillerMedDild** [comment]
I only see one, could I have a screenshot please?

**Comment by MrCarlet** [comment]
I'm sorry Infinity Drill has 2 different crafting recipes
![Annotation 2020-08-17 041605](https://user-images.githubusercontent.com/47258022/90348909-6b3e5f80-e040-11ea-9984-845c57e58c2e.png)
![Annotation 2020-08-17 041615](https://user-images.githubusercontent.com/47258022/90348912-72656d80-e040-11ea-841d-5f3fcf76e000.png)

**Comment by NillerMedDild** [comment]
Fixed in 0.2.8 by an IF update :)
