### ISSUE TITLE
Block Drops

### ISSUE THREAD

**Issue by OneLemonyBoi** [NillerMedDild/Enigmatica6#1511]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/blockdrops
**Mod description**
Write a short description of the mod here.
This mod adds JEI Info about Block Drops.
**Why would you like the mod added?**
This mod adds JEI Info about Block Drops.

**Comment by theboo** [comment]
Seems cool but...How much longer are we talking for world load times in e6? Our load times are already pretty up there :/

**Comment by OneLemonyBoi** [comment]
The long load times only happen once, when the world/server is being created.

**Comment by OneLemonyBoi** [comment]
Haven't tried it, but i doubt it will take that long.

**Comment by OneLemonyBoi** [comment]
Also trying to calculate chances mathematically, instead of the current method, which uses a fake player AFAIK.

**Comment by NillerMedDild** [comment]
The old Block Drops mod increased load times dramatically, I'm a bit afraid this will do the same.

**Comment by OneLemonyBoi** [comment]
Ok, I can work on trying to reduce load times.

**Comment by OneLemonyBoi** [comment]
After some testing, by including blockdrops.txt with the modpack, which is generated at the start of any world, the load time for first bootup goes down a lot. I can stopwatch it later, but this should fix loadtimes.

**Comment by NillerMedDild** [comment]
Awesome, sounds promising :D

**Comment by OneLemonyBoi** [comment]
so 1st launch world creation times for E6 Dev went from 41 minutes without text file to 6 minutes with text file. I will try to make this even more efficient.

**Comment by NillerMedDild** [comment]
41 minutes, jesus christ :P but that is quite the improvement, nice.

**Comment by OneLemonyBoi** [comment]
Don’t worry! I’m trying to cut it down some more.
