### ISSUE TITLE
Untitled Duck Mod

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1515]
https://www.curseforge.com/minecraft/mc-mods/untitled-duck-mod-forge

Adds ducks to the game.

I highly suspect this will get vetoed as I know this pack is already large so the bar for entry is high and this mod appears in relatively early development stages.  But I also love ducks and there's none in the game so figured I also should at least suggest it.

**Comment by NillerMedDild** [comment]
Those ducks are freaking adorable :P Will think on it.

**Comment by Merlo17** [comment]
I would add it in a heartbeat but there's a bit of a concern for me: https://www.curseforge.com/minecraft/mc-mods/environmental also adds ducks :P

**Comment by NillerMedDild** [comment]
The issue with Environmental is it would mess up existing generation,  so.. :/

**Comment by NillerMedDild** [comment]
It's a no, since we'll add Envrionmental eventually ._.
