### ISSUE TITLE
Hostile mob spawn rates seem low

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#1517]
**Modpack version**
0.4.1

**Describe the bug**
It seems like hostile mob spawn rates are lower than they should be. Especially noticeable in nether fortresses. It could just be me thinking this, but I figured I would post this here in case others have noticed the same thing.

**Logs**
N/A

**Screenshots**
N/A

**Comment by Merlo17** [comment]
Are you playing on a server with many people online simultaneously?

**Comment by RevenantWendigo** [comment]
It's just myself and one other friend.

**Comment by NillerMedDild** [comment]
Hmm.. It could be that there are a bunch of mobs in a loaded chunk. Either way, I think this issue is more suitable for Discord. I've seen pleeeenty of mob spawns on our servers :P
