### ISSUE TITLE
Mob Duplicator no longer spawning mobs

### ISSUE THREAD

**Issue by Aquabrodie** [NillerMedDild/Enigmatica6#1518]
**Version**
The version of the modpack I'm using is the newest 0.4.2

**Describe the bug**
The bug is that it no longer works, its just broken, if a mob imprisonment tool is placed inside it just doesn't work regardless of the settings inside the mob duplicator

**Comment by NillerMedDild** [comment]
Thanks for the report :)
@Buuz135 I have a hot bug for you good sir!

**Comment by Buuz135** [comment]
Fixed in 3.2.10.2
