### ISSUE TITLE
Blast Furnace Smelt Iron Dust at Half Speed/Half Efficiency

### ISSUE THREAD

**Issue by telemenar** [NillerMedDild/Enigmatica6#1519]
**Modpack version**
0.4.2

**Describe the bug**
Blast Furnace Smelt Iron Dust at Half Speed/Half Efficiency

The first recipe in priority for the blast furnace is a 10s recipe which results in the blast furnace smelting at normal speed, and also using double the normal fuel.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![2021-03-02_17 08 27](https://user-images.githubusercontent.com/1326160/109737025-31671d80-7b7a-11eb-9224-3b5869ed9abc.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, should be fixed in-dev :)
