### ISSUE TITLE
World doesn't save, but player does

### ISSUE THREAD

**Issue by Nabegane** [NillerMedDild/Enigmatica6#152]
After updating from 0.2.6 to 0.2.7 the world doesn't save its state after Save and Quit but the players stats and inventory is saved.

**Comment by NillerMedDild** [comment]
Remember to read the changelog :) If your world begun in version 0.2.4 or prior, you will need to re-add the mod Rats. https://www.curseforge.com/minecraft/mc-mods/rats/files/3020258

**Comment by NillerMedDild** [comment]
If your world was not made in 0.2.4 or prior please let me know and I'll reopen the issue :)
