### ISSUE TITLE
[Mek-QuestLine]A small warning.

### ISSUE THREAD

**Issue by MRT-CO** [NillerMedDild/Enigmatica6#1523]
It should be a new warning or something about new Fission calculation.

I've made a big 18x18x18 boiler (sodium, not water cooledbuffer for 30mb/ and using the max value from basic-schematic) and the reactor blows up in like 30-60 seconds and i didn't notice turbine goes full, i talked with some people on SMP and they told me about the wiki thing.

I'm talking about this one in particular.

Energy per mb of Steam is reduced. This has a heavy impact on fission burn rate. Since less steam is produced, less water is recycled for cooling. Reactors will explode if they're running near their previous limits and do not have appropriate safety measures in place.

For instance, with the default configs, the basic fission reactor and turbine we provide in schematics produces 570k rf/t and can run at a **### _burn rate of 20mb/t_**. It now runs **### _stable at around 4mb/_t** and produces 114k rf/t. That's a pretty good step up from Powah reactors still, but a bit more in line.

**Comment by NillerMedDild** [comment]
We'll get that added, thanks :)

**Comment by MuteTiefling** [comment]
Should be good next update: 

![image](https://user-images.githubusercontent.com/9543430/110051716-59928000-7d24-11eb-848d-5f9b237e798d.png)
