### ISSUE TITLE
Terminite unobtainable through crafting 

### ISSUE THREAD

**Issue by erierika** [NillerMedDild/Enigmatica6#1524]
v0.4.2 
 
It is currently not possible to craft terminite as the end furnace alloying recipe requires the disabled ender dust. All other alternative dusts; ender/enderium dust from Emendatus Enigmatica, refuses to smelt. 

The only way of obtaining terminite afaik is to find it in certain end structures or to spawn it in.

**Comment by Merlo17** [comment]
Solved on discord, caused by the good old curse not copying our damn scripts
