### ISSUE TITLE
Thermoelectric Boiler quest gives no size.

### ISSUE THREAD

**Issue by EludeQ** [NillerMedDild/Enigmatica6#1525]
**Description**
In the Mekanism quest for the Thermoelectric Boiler, you are given the task to collect a certain number of blocks, but nowhere in the quest is actually mentioned how big the boiler should be with the materials that you've got. The only measurements you're given are the maximum dimensions of the boiler. (18x18x18, but I don't think that's the intended size.)
There _is_ a builder's gadget template, but I can't use it since it crashes my game. (Most likely related to #1172?)

**Why would you like this added/changed?**
It's pretty confusing as I now have a bunch of blocks but no idea what I'm supposed to do with them.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/28099249/109788695-d7189c00-7c0f-11eb-850d-045af9134f6c.png)
As you can see, no dimensions are mentioned except for the max dimensions.

**Comment by MuteTiefling** [comment]
The whole point is to use the building gadget, as it's too complicated to explain concisely.

There are create schematics now too that should be on 0.4.2. You can give those a try instead.

**Comment by EludeQ** [comment]
> The whole point is to use the building gadget, as it's too complicated to explain concisely.
> 
> There are create schematics now too that should be on 0.4.2. You can give those a try instead.

Thanks, good to know about the create schematics. I'll create a new instance on 0.4.2 because I'm too scared to update to it on my current server running 0.3.13 haha. 

I get that explaining exactly how to build it would be too hard, but just a quick note saying it's x by x by x would be nice, as I could then just use a guide/screenshot online to build it. But I guess that at that point, I might as well just follow those guides entirely instead.

**Comment by TemperedFool** [comment]
The quest text is already long, but I get that throwing in a one-liner about the expected size would help.

@MuteTiefling I can do that when I'm working on more Schematic stuff later.

**Comment by TemperedFool** [comment]
Fixed on the dev server.

**Comment by EludeQ** [comment]
Neat! Thanks for that, this is helpful.
