### ISSUE TITLE
Bees don't enter newly placed hives.

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1528]
Enigmatica 6 0.4.2 (official server)

Bees do not enter newly placed hives.  I've only done minor testing of this myself (was originally discovered by KrazyGeek), but am adding a bug report to make sure it gets attention.

In his testing he was unable to get any bees to go into his hives that he had recently made.

I have hives placed down in a previous update which the bees still use correctly.  When I crafted a new hive and placed it down and put down a captured bee in front of it with flowers, the bee went to the flowers and then left the nearby hive and went some distance away to another old hive that I had forgotten was in the area.  After the bee left that hive I broke it and re-placed the bee next to the newly placed hive.  It again went to the flowers, but then just wandered for the next 5-10 minutes and never went to the newly placed hive or any other hives additionally put down near it at the time of testing.

**Comment by Darkere** [comment]
This is most likely caused by an experimental mod that is only on the official server. We are already looking into it.
