### ISSUE TITLE
Cooking for Blockheads Book Recipe

### ISSUE THREAD

**Issue by Drunkender** [NillerMedDild/Enigmatica6#1529]
**Modpack version**
0.4.2

**Describe the bug**
Crafting "Cooking for Blockheads II" only takes fastworkbench Crafting tables

**Logs**
N/A

**Screenshots**
![1](https://user-images.githubusercontent.com/14418412/109884367-6f2f7900-7c42-11eb-9574-bfbd72c3a71b.png)
![2](https://user-images.githubusercontent.com/14418412/109884369-6fc80f80-7c42-11eb-82c0-6f01f3a2e90b.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
