### ISSUE TITLE
Crash when using Occultism machine operator

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1530]
Enigmatica 6 0.4.2 (official E6 Server)

I have an occultism storage system with the tablet for accessing it via distance.  The storage base and a Mek energized smelter are in a force loaded chunk in my base and a djinni machine operator is assigned to the smelter.  While away from my base I tried putting a stack of clay that I'd picked up while out and about directly into the smelter via the machine operator slot.  Caused a hard crash of my game. Logged back in and repeated once to confirm the cause of the crash.

[crash-2021-03-04_00.03.49-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6081204/crash-2021-03-04_00.03.49-client.txt)

**Comment by OneLemonyBoi** [comment]
Did you report to Occultism yet?

**Comment by AdamNisbett** [comment]
No I have not.
