### ISSUE TITLE
Building Gadget Duped

### ISSUE THREAD

**Issue by ColbyWhidden** [NillerMedDild/Enigmatica6#1531]
**Modpack version 0.4.2**

Unsure how I triggered it, but while I was crafting the Copy-Paste and Exchange gadgets from Building Gadgets using the Crafting Station and auto-filling the recipe from JEI; at some point my Building Gadget duplicated itself. Don't know if this is a fringe bug or could be used to dupe other items.

**Comment by brckts** [comment]
JEI shift clicking has some weird sync issues from what i've seen, was the extra building gadget actually or did it disappear when you tried using it ?

**Comment by ColbyWhidden** [comment]
It was entirely usable and stayed in my inventory until I had to restore the server to a earlier backup for reasons involving my own stupidity.

**Comment by NillerMedDild** [comment]
We'll try to reproduce it, thanks for the report :)

**Comment by NillerMedDild** [comment]
Can't reproduce, and I tried vigorously :P I'mma write this off as a fringe bug, unless someone manages to reproduce ofc.
