### ISSUE TITLE
Absence of Resourceful bees information in JEI

### ISSUE THREAD

**Issue by Vspall** [NillerMedDild/Enigmatica6#1532]
**Modpack version**
0.4.2

**Describe the bug**
if i understand correctly in JEI should be 3 or 4 tabs of Resourceful bees information but i have 1 or 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/80035456/109943229-04377e00-7ce6-11eb-9474-8fae6e150188.png)

**Comment by NillerMedDild** [comment]
Duplicate of #1424 most likely - `/reload` to fix it temporarily :)
