### ISSUE TITLE
Remove Natural Spawning of Cockroaches 

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1535]
Their count gets way too high on servers, I think it warrants a complete removal.

**Comment by Merlo17** [comment]
*cries in la cucaracha*

**Comment by NillerMedDild** [comment]
You what? :P

**Comment by theboo** [comment]
https://streamable.com/8mpgf8

**Comment by theboo** [comment]
Maybe we can add the eggs to the market? They are also currently the only way to craft that wonderful sombrero xD

**Comment by NillerMedDild** [comment]
Hmm, maybe we add a way to spawn them in. Birthing Altar perhaps?

**Comment by NillerMedDild** [comment]
I say both \o/

**Comment by Rodg88** [comment]
I've had fresh roaches spawn in the end in 0.4.3, on a newly built bridge. Maybe the alexmobs configs in the main cfg folder also need to be updated, not just config/alexsmobs/cockroach_spawns.json?

**Comment by Brewbeet** [comment]
Also spawns in the end in 0.4.3

**Comment by NillerMedDild** [comment]
fixed for realsies in https://github.com/NillerMedDild/Enigmatica6/commit/c7411055dcb21d03c46e079acbaa7f78ad89089a
