### ISSUE TITLE
Add ability to squelch or ignore players (MP)

### ISSUE THREAD

**Issue by SinKane-MC** [NillerMedDild/Enigmatica6#1536]
**Description**
having the ability to mute or ignore a player would be great! Or just having a way to stop excessive caps usage...

**Why would you like this added/changed?**
Some ppl love to keep caps lock on, be nice to be able to ignore them

**Screenshots if applicable.**

**Comment by NillerMedDild** [comment]
MC 1.16.5 adds this, check out the Social Interactions Screen (default keybind P, it is conflicting)
