### ISSUE TITLE
Add stack upgrades for PNC chamber interface

### ISSUE THREAD

**Issue by SinKane-MC** [NillerMedDild/Enigmatica6#1537]
**Description**
It would be really nice (and maybe more server friendly?) to have the ability to upgrade the PNC chamber interfaces with stack upgrades to prevent the ping/pong of items trying to enter the chamber for crafting. For instance, if I need to make a lot of slime, or transistors/capacitors in a batch, I need to have a (large) chamber with numerous inputs, and the mats will bounce around trying to go into one of the input until successful or return to input storage.

**Why would you like this added/changed?**
It would be a QoL upgrade as well and potentially help with TPS not having to update all the entities as they move around aimlessly...

**Screenshots if applicable.**

**Comment by NillerMedDild** [comment]
This is not where I recommended that you request it :P

**Comment by TemperedFool** [comment]
@SinKane-MC Beside the "maybe this should go to PNC" part, are you using Pretty Pipes with your Pressure Chamber? I'd recommend you try an OmniHopper, and otherwise come hang out on the discord and ask for help/suggestions ^_^

**Comment by SinKane-MC** [comment]
@NillerMedDild  Opps, sorry. Looked at the Git for PNC: Repressurized and didn't see a feature request option. I'll go back there.
@TemperedFool On the Discord, but haven't tried the other two. Will do so, thank you

**Comment by Merlo17** [comment]
Also this sounds like a suggestion for them, not for us :P we don't exactly have control over stuff like that

**Comment by SinKane-MC** [comment]
@Merlo17 Got it, sorry about that
