### ISSUE TITLE
Game crashes when rendering botania:mana_pylon

### ISSUE THREAD

**Issue by brckts** [NillerMedDild/Enigmatica6#154]
**Modpack version**
0.2.7

**Issue**
Game crashes when JEI tries to render mana pylon from botania

**Logs**
https://paste.ee/p/EcNoY <- full log, sorry I was too lazy to just copy the crashy bit

**Comment by NillerMedDild** [comment]
Thanks for the report! Could you please try reproducing this without Optifine? :)

**Comment by brckts** [comment]
Indeed removing optifine fixes it

**Comment by NillerMedDild** [comment]
Cool, thanks - I'll relay anyway :)

**Comment by brckts** [comment]
As suggested in #156 , adding optiforge fixes this issue.
