### ISSUE TITLE
Give Akashic Tome as quest reward

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1540]

**Comment by MuteTiefling** [comment]
I know I added this... I wonder if there's too much NBT data on it?

**Comment by MuteTiefling** [comment]
or did I really derp and make it the task and not the reward...

**Comment by NillerMedDild** [comment]
It was there as a Task, could that be it?

**Comment by theboo** [comment]
Starter quests sync commit happened after update, guessing that's the dealio?

**Comment by TemperedFool** [comment]
I believe it's a quest requirement rather than reward as you suggested @MuteTiefling

**Comment by MuteTiefling** [comment]
>.<

**Comment by MuteTiefling** [comment]
Fixed for real in dev now

**Comment by NillerMedDild** [comment]
Link to commit btw: https://github.com/NillerMedDild/Enigmatica6/commit/9bd8a57543b96e057578c3cc01513f81c7c1fe3b
