### ISSUE TITLE
Infinity Saw - Breaking problem

### ISSUE THREAD

**Issue by ManiacRobert1** [NillerMedDild/Enigmatica6#1541]
Infinity saw don't break the wood, but instead it gives you normal things from it.

Version : 0.4.3

https://user-images.githubusercontent.com/39351347/110048558-bd36a080-7d58-11eb-9f5b-f43582c4335a.mp4

**Comment by natebc** [comment]
If you keep going with it will bring down the whole tree. I think it works like the enchant 'smartass' from the old days. I.e. it takes from the top and gradually works down to you. At least this is the behavior i observed when working down a warped tree in the Nether today.

It is a bit counter intuitive and doesn't work with Ultimine AFAIR though. Likely something maybe addressed by our friends in InnovativeOnlineIndustries or maybe in the quest?

**Comment by ManiacRobert1** [comment]
Ok, it's cutting down the leaves in a bigger area, the quest was saying "can chop increasingly large area" so i tought it's a bug.
