### ISSUE TITLE
No recipe for smelting starmetal ore into ingots.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [NillerMedDild/Enigmatica6#1542]
**Modpack version**
0.4.3

**Describe the bug**
Starmetal ore can no longer be smelted into ingots (nor turned into starmetal dust directly from ore form, but that wasn't in to begin with). This breaks Astral Sorcery progression and makes it impossible to progress in the mod. The new recipe for turning iron dust directly into starmetal dust only works if you already have a starlight infuser, but that's an endgame mod item that's unavailable without starmetal ingots already.

**Comment by TemperedFool** [comment]
There is also apparently a smelting recipe to go from dust -> ingot, which presents a duplication issue since you can cut an ingot into more than one dust:

https://discord.com/channels/195234321836146688/726178356143456287/817207539237257216

**Comment by Scorch-Mechanic** [comment]
Here's the image. 
> There is also apparently a smelting recipe to go from dust -> ingot, which presents a duplication issue since you can cut an ingot into more than one dust:
![image](https://user-images.githubusercontent.com/5760760/110055091-298db180-7d11-11eb-8569-d00472d488de.png)

**Comment by MuteTiefling** [comment]
I knew I overlooked something here...
