### ISSUE TITLE
Endermite & Displacement Crashes Server

### ISSUE THREAD

**Issue by erierika** [NillerMedDild/Enigmatica6#1543]
v0.4.2 

So we had three consecutive crashes happen within a few minutes. The crash report said an endermite was the culprit, described as 'Ticking Entity'. After looking around I found Issue #1068 and figured it was the same bug, but the issue was closed. So whenever an endermite attacked someone with armor enchanted with displacement it would crash the whole sever. This was repeated once and bug was fixed after we removed displacement from the players armor. 

Crashlog-
https://pastebin.com/Ja0Ly2SF

**Comment by Brewbeet** [comment]
v0.4.3 

Same thing in thing in sp. x3

Crashlogs:
https://pastebin.com/RVwysGzj
https://pastebin.com/6h5zmaTm
https://pastebin.com/V3dpEXsz

**Comment by NillerMedDild** [comment]
Thanks for the added info guys 👍 
This issue has been reported on the Thermal Discord, seems like it might not get fixed though.
https://discord.com/channels/399037120930512897/434101214548852746/810687024516300860

**Comment by NillerMedDild** [comment]
Just got confirmation that they can't reproduce it, so it's almost certainly a mod interaction. https://discord.com/channels/399037120930512897/434101214548852746/817523447382147122

**Comment by NillerMedDild** [comment]
I've disabled the enchantment, that's all we can do I'm afraid.

**Comment by Merlo17** [comment]
Honestly it's a terrible enchant nobody wants anyways. I see this as a win win

**Comment by NillerMedDild** [comment]
I feel like I need 👌 as a reaction here.
