### ISSUE TITLE
Bees can replace marble blocks in player made structures

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#1545]
**Modpack version**
0.4.1

**Describe the bug**
Bees can replace marble blocks in player made structures.

**Logs**
N/A

**Screenshots**
![2021-03-04_22 43 12](https://user-images.githubusercontent.com/1980813/110072812-961da600-7d3b-11eb-94f9-92ccd282d084.png)

**Comment by RevenantWendigo** [comment]
This is the block they are changing: 
![javaw_wDm2yuegZl](https://user-images.githubusercontent.com/1980813/110073066-09271c80-7d3c-11eb-803f-04d2757ad613.png)

**Comment by Scorch-Mechanic** [comment]
I just had this happen earlier to me on 0.4.3, where a copper bee turned the runed and engraved marble blocks on the corner of my celestial gateway into copper ore.
![2021-03-05_05 21 40](https://user-images.githubusercontent.com/5760760/110082970-ee0bdb00-7d42-11eb-9da3-8581ed5d15a9.png)

**Comment by Merlo17** [comment]
Pretty sure that's intentional, since they can change every kind of stone via mutation. Just keep them away from the altar ^^

**Comment by RevenantWendigo** [comment]
Makes sense. Just wanted to make sure the Marble Arch had correct tags, would it still be forge:stone even if it is marble arches and not regular marble?

**Comment by NillerMedDild** [comment]
It would yes, atleast in my eyes :)

**Comment by RevenantWendigo** [comment]
Gotcha! Just wanted to make sure I was understanding it right. Thanks Niller!
