### ISSUE TITLE
Blocks of Uraninite Cannot be turn back into Uraninite

### ISSUE THREAD

**Issue by tipmon** [NillerMedDild/Enigmatica6#1546]
**Modpack version**
0.4.3
**Describe the bug**
Blocks of Uraninite can be craft from 9 pieces of Uraninite but those same blocks cannot be turned back into the individual pieces. There is no recipe listed in JEI either that the blocks are used in.

**Comment by tipmon** [comment]
Additionally, Blocks of Uraninite cannot be placed inside Powah! reactors instead of chunks.

**Comment by NillerMedDild** [comment]
Oversight on my part, thanks for the report, OneLemonyBoi has got it fixed for next update 😄
