### ISSUE TITLE
Add JEI info for Thermal elemental drops

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica6#1547]
Players have reported Thermal Elementals being pretty annoying to find, since they're biome specific and TF biomes are pretty huge, plus it's always a random chance if you're going to find one I guess.

The recipe to spawn them with the altar needs their drops currently, making it a bit useless. Tweaking them to use other items would help them be available without too much RNG involved

**Comment by TemperedFool** [comment]
Not sure what they're using now, but maybe go with their traditional secondary drops (sulfur dust/obsidian dust/snowballs)?

**Comment by Merlo17** [comment]
As pointed out by Motoko on discord, it might be a bit out of scope. A better option could be bringing back the 1.12 XP recipes for the drops

**Comment by MuteTiefling** [comment]
Indeed. The Altar of Birthing here is meant more for an actual mob farm where you'd fortune the drops to ensure you get enough to keep it going.

If we want to make this easier for people to obtain, it should be doable with Thermal only.

**Comment by MuteTiefling** [comment]
So, I just spent a single night running around a savanna killing everything I saw. Got one blitz in the night. Not great, but enough to get a spawner going.

**Comment by MuteTiefling** [comment]
Further testing. Nocturnal powder from Astral is a _great_ way to get some of these guys. Mechanical dirt as well. Both simply need to be used in the correct biome.

Badlands will get you blitz and basalz.
Blizz come from any child biome like snowy tundra.
