### ISSUE TITLE
Weird Bug when oppening vanilla chests

### ISSUE THREAD

**Issue by AndreiPurcaru** [NillerMedDild/Enigmatica6#1548]
Version 0.4.3 - Single Player World

Upon relogging into my single player world, all normal minecraft chest open without showing their GUI. Modded chests ( I have tried an iron chest) open just fine. I have linked a video to show the problem better. I don't have any mod installed besides the ones provided with the 0.4.3 version of the pack. I have tried relaunching the world but to no avail.

[Video of Issue](https://youtu.be/TWLB2WZUTxU)

**Comment by Merlo17** [comment]
Probably caused by https://github.com/NillerMedDild/Enigmatica6/issues/667. Try restarting the client entirely

**Comment by AndreiPurcaru** [comment]
Thanks! That worked.
