### ISSUE TITLE
Silk touch mining vanilla nether quartz ore doesn't give chunks

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1549]
**Modpack version**
0.4.3
**Describe the bug**
Mining vanilla nether quartz ore with silk touch just gives blocks of nether quartz ore. EE nether quartz ore, eg nether quartz in brimstone from byg, will give an EE chunk of nether quartz instead.

**Comment by Merlo17** [comment]
That is intentional, EE doesn't alter vanilla quartz in any way. Vanilla quartz shouldn't even exist, but since it was introduced after 0.4.0 some old chunks will still have it. new worlds/chunks won't have it generate at all

**Comment by Rodg88** [comment]
Yeah just realised i was only finding it in old chunks
