### ISSUE TITLE
Server won't boot up

### ISSUE THREAD

**Issue by ClockworkFountain** [NillerMedDild/Enigmatica6#155]
**Modpack version**
0.2.8
**Issue**
Server will not boot up, window closes immediately after opening.
**Logs**
N/A

**Comment by ClockworkFountain** [comment]
Is there a way I could pause the script to see what error it gives me before immediately shutting down?

**Comment by Darkere** [comment]
You can launch the script from cmd. You can also check the serverstart.log.

Please join our discord for support https://discord.com/invite/xPPwaFx. The Github is for bug reports.
