### ISSUE TITLE
Cooking for Blockheads eats knives

### ISSUE THREAD

**Issue by TheWooper** [NillerMedDild/Enigmatica6#1550]
0.4.2

When placing a Farmer's Delight knife in the tool rack of a Cooking for Blockheads kitchen setup, and making a recipe (in this case, bacon), the recipe will consume the knife.

- Put a knife in a tool rack and raw porkchop somewhere in the system.
- Use the Cooking for Blockheads cooking table with a Cooking for Blockheads book (I'm using the #NoFilter Edition)
- Shift+Left Click the raw bacon recipe.

**Comment by NillerMedDild** [comment]
Thanks for the report, I finally figured out the issue here ^^' I disabled the recipe and Simple Farming Bacon, as Farmer's Delight Bacon is a bit more fleshed out.
