### ISSUE TITLE
Random failures in crafting of Compact Machines

### ISSUE THREAD

**Issue by Mendanbar** [NillerMedDild/Enigmatica6#1552]
**Modpack version**
0.4.X

**Describe the bug**
Intermittently it seems like something about Compact Machines recipes just stop recognizing a valid craft.  For example, I place all of the machine walls in a 7x7x7 with an Enderium block in the center, drop in the flux dust and nothing happens.  But if I do the same in another world, or maybe after a restart of the current world, and maybe it works this time.

This might be related to [this issue](https://github.com/NillerMedDild/Enigmatica6/issues/1534) in part, but I've also seen it even when I place all of the machine walls perfectly.

I do know that in the previous ticket about the crafting recipes, Merlo and I were seeing some odd behavior where Black Hole units would work for me in some crafting recipes, and they would work for Merlo in others(see [this comment](https://github.com/NillerMedDild/Enigmatica6/issues/1430#issuecomment-787071071))... which _seems_ like maybe the same bug.  Really hard to reproduce consistently though.  I searched the Compact Crafting issue tracker but didn't see any reference that looked similar.  Hopefully a more repeatable pattern emerges.

**Logs**
N/A, no associated errors/crashes

**Comment by NillerMedDild** [comment]
Fingers crossed this is fixed in 0.4.4 by the other CM fix ^^
