### ISSUE TITLE
Ender Cells lose all their energy cells after update and subsequentially after logging out/in

### ISSUE THREAD

**Issue by ShadowMagnus000** [NillerMedDild/Enigmatica6#1553]
**Modpack version**

Enigmatica 6 0.4.2

**Describe the bug**

After server updated to 0.4.2, all the Powah Ender cells I am using lost all their Energy cells within them and went into a reset mode. After replacing energy cells into them and logging out/in, I verified to see that all ender cells in my ownership had once more lost the energy cells within.

**Comment by TemperedFool** [comment]
Duplicate of #1445 I think.

**Comment by NillerMedDild** [comment]
Should be fixed in 0.4.3 :)
