### ISSUE TITLE
Optifine Missing Textures

### ISSUE THREAD

**Issue by CptTbone** [NillerMedDild/Enigmatica6#156]
**Modpack version**
0.2.8

**Issue**
Missing textures from Mekanism & AE2 pipes/cables when I install OptiFine_1.16.1_HD_U_G2.
![2020-08-16_18 50 38](https://user-images.githubusercontent.com/46872696/90345789-c137e680-dff1-11ea-920c-64e46074cbbc.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Darkere** [comment]
Install optiforge

**Comment by CptTbone** [comment]
@Darkere Cheers - thx. That resolved the texture issue.
