### ISSUE TITLE
Recycling Issue

### ISSUE THREAD

**Issue by OneLemonyBoi** [NillerMedDild/Enigmatica6#1560]
**Modpack version**
Dev
**Describe the bug**
IE Recycling uses the first item of the first tag in order to determine the output ingot when recycling.
All examples:
Iron becomes Tin
Gold becomes Copper

**Comment by Darkere** [comment]
IE has redone the entire recycling thing a few days ago. Not sure what our current state is.

**Comment by NillerMedDild** [comment]
I've disabled recycling completely in 0.4.3 :)
