### ISSUE TITLE
Can't enable Core Components for PNC armor

### ISSUE THREAD

**Issue by SinKane-MC** [NillerMedDild/Enigmatica6#1561]
**Modpack version**
0.4.3 on Official E6 server

**Describe the bug**
For some reason if you disable core components for PNC armor (or have yet to enable them) you can not (re)enable them any longer. Happening to a few of us, we have tried restarting the client completely as well. AS far as we can tell this just started happening

**Comment by ManiacRobert1** [comment]
I create a problem here too

https://github.com/TeamPneumatic/pnc-repressurized/issues/753

**Comment by SinKane-MC** [comment]
Verified not working in SP either

**Comment by ManiacRobert1** [comment]
Removing from instance/config/pneumaticcraft/ArmorFeatureStatus.cfg will re-activate components and armor will be start working again. 

I talked with desht(pnc dev) and he said it's not pnc fault, but he will still look into it about that problem.

**Comment by NillerMedDild** [comment]
That's strange, we don't even supply that file, it's generated by the client.
