### ISSUE TITLE
magic feathers trinket disabled (recipe) beta 0.4.3

### ISSUE THREAD

**Issue by RaptorEatingDuck** [NillerMedDild/Enigmatica6#1563]
group of friends play on a 0.4.3 server and one of the guys noticed the recipe for the magic feathers trinket is now disabled. but on the previous version, it was not. with nothing in the change log in guessing it's a bug? Can Anyone confirm?

**Comment by NillerMedDild** [comment]
It should still exist, did you guys remember to include the kubejs folder on the server in the update? :)

**Comment by RaptorEatingDuck** [comment]
Seems we forgot that bit, one of the other guy found it this morning, cheer !
