### ISSUE TITLE
Project Vibrant Journeys

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica6#1564]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys
**Mod description**
Pointed out that it's in alpha by Mango_ on discord. Might be... a bit heavy... at this point, but worth getting on the radar I think just in case.

**Comment by theboo** [comment]
YESSSSSS!!! e6 has been missing this hardcore, will def have to wait until it is out of alpha but im excited

**Comment by CletusMAngo** [comment]
Yessir!

**Comment by Merlo17** [comment]
I just noticed - this doesn't add biomes anymore, just groundcover and decoration. It would be a perfect addition and shouldn't break anything hopefully

**Comment by Merlo17** [comment]
Tested this in dev and it seems like a no brainer. It now works natively in every biome so no config work for us and it adds some cool detail to the world, nothing more. I really like it
