### ISSUE TITLE
[Quark] Cannot insert seeds into Seed Pouch (Disabled Seed Pouch)

### ISSUE THREAD

**Issue by willbattel** [NillerMedDild/Enigmatica6#1565]
**Modpack version** 0.4.1

**Describe the bug**
Quark has a "Seed Pouch" item in which the player can store a large number of seeds. It seems this is not functioning properly in E6. Within the player's inventory, selecting seeds changes the Seed Pouch texture indicating seeds can be inserted, but right clicking the pouch with the seeds does nothing.

**Logs**
N/A

**Screenshots**
![sp01](https://user-images.githubusercontent.com/13490339/110191942-ec005580-7df0-11eb-851e-176602ce8abb.PNG)
![sp02](https://user-images.githubusercontent.com/13490339/110191944-edca1900-7df0-11eb-947b-a52da055ee3e.PNG)
![sp03](https://user-images.githubusercontent.com/13490339/110191948-ef93dc80-7df0-11eb-81b7-a8e8ecce14f9.PNG)

**Comment by NillerMedDild** [comment]
Thanks for the report. Would you mind checking if this is also an issue in 0.4.3?

**Comment by Merlo17** [comment]
it is, just reproduced in dev :/

**Comment by NillerMedDild** [comment]
Ah, most likely caused by a conflict with MouseTweaks: https://github.com/Vazkii/Quark/issues/3041

**Comment by Somiona** [comment]
Same issue persists in enigmatica 0.5.4. Is there any plan to make RMBTweak be disabled as default?

**Comment by NillerMedDild** [comment]
That is why this issue is still open :)

That isn't planned no, I'll look into whether it should be again.

https://github.com/Vazkii/Quark/issues/1987

**Comment by NillerMedDild** [comment]
To be honest I'd rather live with this bug (or disable the seed pouch) than disable the right mouse buttom tweak.
