### ISSUE TITLE
Chemical Thrower Crashes Clients, Throws Java Error

### ISSUE THREAD

**Issue by Nozsho** [NillerMedDild/Enigmatica6#1566]
**Modpack version**
E6 0.4.1
**Describe the bug**
Using the Chemical Thrower from Immersive Engineering with Napalm kicks all clients off of the server, and throws the "unknown serializer type 108" error. Repeated attempts to log in also throws the same error, for roughly 1-2 minutes. Replicable.

**Logs**
No applicable client logs (that I know of, if anyone knows where to look please LMK). I'll ask the server owner to check server logs.

**Screenshots**
It'll just be a screen of the error described above.

**Comment by NillerMedDild** [comment]
Thanks for the report. Would you mind updating to 0.4.3 and see if the issue persists?

**Comment by Nozsho** [comment]
As an intermediate update, I tried to replicate the problem on both 0.4.3 SP  & 0.4.1 SP, and it didn't happen. I've asked the server owner to update to 0.4.3, so I should get back to you later today/tomorrow. I also need to check which upgrades were attached at the time of usage, since it might have been a factor.

**Comment by Nozsho** [comment]
After updating the server to 0.4.3, I can confirm it still [boots clients to the server list](https://i.imgur.com/8G7INiJ.png), using the default Chemical Thrower. I was able to log back into the server immediately after the boot.
