### ISSUE TITLE
Using ftb optimine on underwater sand breaks the water

### ISSUE THREAD

**Issue by brckts** [NillerMedDild/Enigmatica6#157]
**Modpack version**
0.2.8

**Issue**
Sometimes when veinmining underwater sand, only one block of sand drops and the water blocks around it disappear, but only clientside, as you still take breathing damage if you stay in. Logging out and back in resyncs the water but doesn't drop the sandblocks you were supposed to get.

![image](https://user-images.githubusercontent.com/51674867/90387749-04906480-e087-11ea-97d1-7ffca2581df8.png)

**Logs**
Server log doesn't show anything suspicious, neither does client log

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Shindur** [comment]
I noticed this is a client side issue at times. As when you log out or quit the world and go back in, the water is perfectly fine. Perhaps it's Pretty Beaches causing it?

**Comment by NillerMedDild** [comment]
Could be!

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/FTBTeam/FTB-Ultimine/issues/25

**Comment by NillerMedDild** [comment]
Fixed by removing Pretty Beaches
