### ISSUE TITLE
Major Changes for 0.5.0

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1571]
# New Mods

- [FramedBlocks (replacing BlockCarpentry)](https://www.curseforge.com/minecraft/mc-mods/framedblocks)
- [Environmental](https://www.curseforge.com/minecraft/mc-mods/environmental)
- A new gravestone mod 

# Potential Changes

- BYG: Disable The Nether
- ~~BYG: Disable The End~~

# Mod Removals

- ~~Abnormals Delight~~
- Additional Lights
- Advanced Hook Launchers
- Ambientsounds3
- Autumnity
- Babel
- Bamboo Everything
- Bedspreads
- BlockCarpentry (Replaced by [FramedBlocks](https://www.curseforge.com/minecraft/mc-mods/framedblocks))
- Bountiful Baubles
- Builders Crafts & Additions
- Campfire Torches
- ChocolateFix
- Crafting Station
- CreativeCore
- EmbellishCraft
- EnderMail (Replaced by Mailbox system in MrCrayfish's Furniture mod)
- ItemZoom
- JAOPCA
- Mapper Base
- Miner's Helmet
- MoreVanillaLib
- OldJavaWarning
- ReloadAudioDrivers [(Replaced by SoundDeviceOptions)](https://github.com/NillerMedDild/Enigmatica6/issues/2191)
- Server Tab Info
- Storage for ComputerCraft
- Vanilla Excvators
- Vanilla Hammers

# Biome Yeet List
- `byg:lush_tundra`
- `projectvibrantjourneys:overgrown_spires`

**Comment by Merlo17** [comment]
For the record, I did try adding environmental to already generated worlds in TF and it resulted in pretty jarring chunk borders, so I think this one will have to wait sadly

![2021-03-07_00 38 22](https://user-images.githubusercontent.com/62080872/110224672-dddc3300-7edd-11eb-90ed-6a6da7c8f8b0.png)

![2021-03-07_00 39 11](https://user-images.githubusercontent.com/62080872/110224684-f8aea780-7edd-11eb-8171-42927a772a4b.png)

**Comment by CletusMAngo** [comment]
Oh i see that abnormals delight and abnormals core are on the possible removal list? is this a mistake orrrr?
Cause Upgrade aquatic,Environmental,Atmospheric,Autumnity and Abnormals delight require it

**Comment by NillerMedDild** [comment]
Upgrade Aquatic is now on the list too :) Abnormal mods are nice but I don't feel like the modpack really needs them. And they really lose some flair when the biomes shift from time to time, whatever is causing that it ^^'

**Comment by CletusMAngo** [comment]
I think there might be a mod that fixes this but it'd have to be tested 
https://www.curseforge.com/minecraft/mc-mods/biome-id-fixer
https://www.curseforge.com/minecraft/mc-mods/chocolate-fix
But i understand if the pack doesnt need them but i think they add a certain, Charm? they do alot of unique things that other mods cant do and they fit for me and alot of other people.
But i can understand if you guys want to remove it. :)

**Comment by NillerMedDild** [comment]
Those mods were picked up by Forge, and do not fix this issue.

**Comment by CletusMAngo** [comment]
Thats fair!
Maybe in the future... :)

**Comment by pm065** [comment]
> Upgrade Aquatic is now on the list too :) Abnormal mods are nice but I don't feel like the modpack really needs them. And they really lose some flair when the biomes shift from time to time, whatever is causing that it ^^'

Sad but understandable. Abnormals are at their best in vanilla+ packs where they add some sweet features that aren't overshadowed by other things. (: 
By the way, why are BYG's nether and end getting removed? They look really nice...

**Comment by NillerMedDild** [comment]
I think they're very cluttery/messy tbh.

**Comment by Kataiser9** [comment]
Haven't had time to play this pack in awhile, but I'm curious why Crafting Station is on the chopping block. I assume there's somme similar block from another mod that serves the same purpose, but I can't think of one off the top of my head (outside of TiCon, which isn't in yet).

Also curious why DungeonsPlus is going.

Finally, I take it "Storage for CC" is being nixed because it's relatively niche? Bummer, but understandable.

**Comment by NillerMedDild** [comment]
> Haven't had time to play this pack in awhile, but I'm curious why Crafting Station is on the chopping block. I assume there's somme similar block from another mod that serves the same purpose, but I can't think of one off the top of my head (outside of TiCon, which isn't in yet).

Tinkers will be added :)

> Also curious why DungeonsPlus is going.

We don't really need it tbh, we have enough dungeons as is. And it doesn't (didn't?) play nice with TF.

> Finally, I take it "Storage for CC" is being nixed because it's relatively niche? Bummer, but understandable.

It's functionality is also in the mod Advanced Peripherals, which we have.

**Comment by CletusMAngo** [comment]
Seeing as it looks like Tinkers will be added in this update. Will tetra be replaced in favor of it? or is that next next major update?

**Comment by NillerMedDild** [comment]
Tetra is not planned for removal at this time :)

**Comment by hron84** [comment]
Can I ask why Miner's Helmet is going? I love this helmet, especially early game it makes mining super simple.

**Comment by pm065** [comment]
Why is JAOPCA being 🔪? Sure, the dynamically generated items look ugly, but that shouldn't be a cause for removal.

**Comment by CletusMAngo** [comment]
Oh so i see you guys redecided on Upgrade aquatic? nice!

**Comment by pm065** [comment]
> Abnormals Delight
If UA is kept then Abnormals Delight should be too

**Comment by hron84** [comment]
@pm065 it depends on your machine. For me, it's not as laggy, but you could decide to not wear that helmet. I think it should not be removed just because it could be laggy for someone. Zombies should be disabled to spawn with it.

**Comment by hron84** [comment]
BlockCarpentry will be replaced or the entire 'Carpenter's Block' theme would be removed?

**Comment by CletusMAngo** [comment]
In my opinion i think Environmental should replace Atmospheric and Autmnity, I remember you guys testing it but it left chunk borders but could it still be reconsidered? i know its an abnormals mod but it adds so much more than the others and would fit into the pack really nicely

**Comment by MuteTiefling** [comment]
> Why is JAOPCA being 🔪? Sure, the dynamically generated items look ugly, but that shouldn't be a cause for removal.

Everything we need from it will be rolled into emendatus enigmatica.

**Comment by TemperedFool** [comment]
One less mod lengthening load times... and I think JAOPCA is an offender here.

**Comment by xATL4S** [comment]
Could I ask for the reason for potentially removing these?:
EmbellishCraft
ItemZoom

I personally quite like the decorative block options given through EmbellishCraft and use them regularly
As for ItemZoom - if it went, then it went. But I do find it is rather useful to get a much closer image on items than otherwise possible, It can also be disabled. So unless its something to do with load times or lag, I would much rather it stayed in the pack.

**Comment by hron84** [comment]
@xATL4S item zoom is purely client mod, if you really need it, you can put it back anytime. Curse and GDLauncher remembers custom mods between upgrades.

**Comment by pm065** [comment]
> Everything we need from it will be rolled into emendatus enigmatica.
nice!

**Comment by Scapulaunit12** [comment]
Are the nether Byg biomes going to be replaced, It would be cool to still have some new nether biomes.

**Comment by pm065** [comment]
> Are the nether Byg biomes going to be replaced, It would be cool to still have some new nether biomes.

Apparently they're just going to be gone, but hopefully once Infernal Expansion gets its first biome update it'll be added to replace them. I think that mod's going to bemcoe like the BetterEndForge of the Nether. Plus there's always Abnormals Nether Extension which I think will add a biome or two when it's released.

**Comment by Erysch** [comment]
> Are the nether Byg biomes going to be replaced, It would be cool to still have some new nether biomes.

totally agreeing

**Comment by CletusMAngo** [comment]
> > Are the nether Byg biomes going to be replaced, It would be cool to still have some new nether biomes.
> 
> Apparently they're just going to be gone, but hopefully once Infernal Expansion gets its first biome update it'll be added to replace them. I think that mod's going to become like the BetterEndForge of the Nether once it gets going. Plus there's always Abnormals Nether Extension which I think will add a biome or two when it's released.

Honestly i think this is kinda not needed seeing as if someone wants the Nether/End biomes they can just reenable them in the configs

**Comment by Erysch** [comment]
> > > Are the nether Byg biomes going to be replaced, It would be cool to still have some new nether biomes.
> > 
> > 
> > Apparently they're just going to be gone, but hopefully once Infernal Expansion gets its first biome update it'll be added to replace them. I think that mod's going to become like the BetterEndForge of the Nether once it gets going. Plus there's always Abnormals Nether Extension which I think will add a biome or two when it's released.
> 
> Honestly i think this is kinda not needed seeing as if someone wants the Nether/End biomes they can just reenable them in the configs

this is true

**Comment by CletusMAngo** [comment]
> In my opinion i think Environmental should replace Atmospheric and Autmnity, I remember you guys testing it but it left chunk borders but could it still be reconsidered? i know its an abnormals mod but it adds so much more than the others and would fit into the pack really nicely

Id also like to case atleast atmospheric to stay in the pack, Atmospheric plans to add new biomes that are so much more unique than the existing BYG biomes,I can understand Autumnitys removal but Atmospheric plans to add alot of new stuff, And could Environmental please be reconsidered? the mod adds so much more content than Autumnity and Atmospheric alot of people would like to see it in the pack :)

**Comment by skzskormz** [comment]
> > In my opinion i think Environmental should replace Atmospheric and Autmnity, I remember you guys testing it but it left chunk borders but could it still be reconsidered? i know its an abnormals mod but it adds so much more than the others and would fit into the pack really nicely
> 
> Id also like to case atleast atmospheric to stay in the pack, Atmospheric plans to add new biomes that are so much more unique than the existing BYG biomes,I can understand Autumnitys removal but Atmospheric plans to add alot of new stuff, And could Environmental please be reconsidered? the mod adds so much more content than Autumnity and Atmospheric alot of people would like to see it in the pack :)

The problem is that they plan, and each biome added has the possibility of breaking the whole world gen with each addition. I'd prefer that the mod is added at a much later development stage and we all require to do one world reset than one world reset per update.

**Comment by landretk** [comment]
I vote to remove Atmospheric. The biomes are ugly and it adds unnecessary extra types of sand and makes it less likely to find a desert that has cactus. Maybe not so much an issue in this pack since there are plenty of other ways to make green dye, but I still don't like when the vanilla biomes don't even spawn in an entire continent. Also they already broke the pack once with an update. They might break things again next time they add biomes.

I don't really like any of the Abnormals mods though, except for like endergetic expansion they don't really add any new gameplay, and they can break certain parts of vanilla gameplay. There's a reason the official minecraft updates are focused and small in terms of new blocks/etc.

**Comment by pm065** [comment]
YESSSS Atmospheric has returned :smile:

**Comment by Tyler-Jarret** [comment]
While I was in the camp of yeet the whole abnormal core (because of upgrading Biome shift), I am hoping that in the future, newer biomes added by those mods won't shift everything else. I think with Biome ID Fixer from the start it'll remain fixed, whatever may come so... exciting we get to keep some! I ran a single player through a modified terraforge config to remove ALL Autumnity and Atmospheric biomes and the worlds became so much less... diverse.

Now here's a quesiton! I noticed that Bountiful Baubles are on the yeet list. I know that's not the _only_ mod that adds the baubles. Was there a replacement in mind? Or just reducing the amount of Baubles?

**Comment by MuteTiefling** [comment]
I'd think dropping bountiful baubles would be mostly a way if removing some very powerful, but kind of boring, baubles. There's a few gems in there but they are mostly just very powerful and detract from some of the more interesting game play elements of other mods.

**Comment by Erysch** [comment]
For me: I like embellishcraft. Sure it has a bit too much of something (like another dozens of stone types) but also it has things other mods don't have, like the plain awesome plain doors or the steel beams *o*. Also some furniture would be lost, which is always good to have to not be in the need to use stairs as chairs... (wtf) Will we see another furniture mod or are these not wanted at all?

Greetings

**Comment by Tyler-Jarret** [comment]
> I'm think dropping bountiful baubles would be mostly a way of removing some very powerful, but kind of boring, baubles. There's a few gems in there but they are mostly just very powerful and detract from some of the more interesting game play elements of other mods.

I could understand that competely. Some members of the server I run are going to be sad those Terraria References are going to be gone. But C'est la vie. Thanks for the reply though!

Erysch, I _personally_ don't really do furniture in my builds but just about everyone else on my server loves it. So I do hope a different furniture mod comes along (or DecoCraft ever joins the 1.16.5 club 😛 )

**Comment by NillerMedDild** [comment]
We still have furniture from Builders' Crafts and Additions :)

**Comment by NillerMedDild** [comment]
Though tbf I'm thinking about scrapping that as well and adding Macaw's Furniture as a replacement.

**Comment by skzskormz** [comment]
> Now here's a quesiton! I noticed that Bountiful Baubles are on the yeet list. I know that's not the _only_ mod that adds the baubles. Was there a replacement in mind? Or just reducing the amount of Baubles?

My opinion on Bountiful Baubles: I avoid using them simply cause I got too op too fast. First end city I found I was completely immune to shulker's annoying effects. Cross necklace makes you pretty much able to take a dip on a lava pool and survive (same with Artifacts Cross necklace), the flight potion can be turned into a charm, which you can then get high unbreaking and have creative flight for the cheapest cost... Plus the potion that can crash players.

On the topic of balancing: Apotheosis towers and the extra books it has added on the last updates have made progression ridiculously easy. I made a new world and bumped into a tower and got a fortune 7 book. 

Embelishcraft has some interesting things, I like the selection of blocks and some additions that are somewhat unexpected (like stackable plates!)  https://imgur.com/a/KVMvlhy
Then again, i'm a builder, the more the better :P

**Comment by Erysch** [comment]
> Though tbf I'm thinking about scrapping that as well and adding Macaw's Furniture as a replacement.

mrcrayfish's furniture is cool, especially for multiplayer because it also has mail boxes which you can send items from mail box to mail box once you get access to shulkerboxes, the designs are also cleaner and the furniture is more easy to craft without adding another in-between-crafting-item like macaws furniture does 

macaw might be right as well, also because there are other macaws mods already included

i really love the shelfes and kitchen sinks n stuff of these mods, they are also functional

**Comment by PianoManu** [comment]
FramedBlocks is a pretty cool mod and the slopes are way better than the slopes of BlockCarpentry. The signs and panels are also great and the ladders work. However, it is missing some features that I liked about BlockCarpentry. On the one hand, that would be that you can make blocks glow by clicking on them with glowstone or coal/charcoal. On the other hand, there are many different designs for doors, trap doors, fences, walls, fence gates, chests and beds (there are no chests and beds in FramedBlocks) that can be changed with the chisel so that these blocks don't look quite so boring. There are also grass, snow and brick overlays that can be activated by clicking on a block of BlockCarpentry with a snowball, grass or gunpowder. In addition, at BlockCarpentry you have the option of deciding whether you would like a block with the same texture on all sides for blocks with different side textures (e.g. crafting table or furnace); or whether you want to keep the model (i.e. front remains front, sides remain sides). With FramedBlocks, only the latter is possible, although the models cannot be rotated (which works with BlockCarpentry, with the aid of the Texture Wrench).

Why can't we have both mods in parallel? Then you would have the choice between the better slopes, functioning ladders and signs (from FramedBlocks), and the "luminous feature", overlays, rotations and the chisel options (from BlockCarpentry). I would miss a few things from BlockCarpentry because there is no substitute for them at FramedBlocks.

In any case, thank you very much for your effort and that you keep developing these modpacks!

**Comment by MrBazlow** [comment]
There are a lot of similarities between FramedBlocks and BlockCarpentry, I guess that is to be expected when they are both trying to achieve the same goal; regarding glowing blocks, BlockCarpentry does actually support this feature so it is not a factor. I have made a table below that highlights the key differences between the mods.

|   | FramedBlocks  | BlockCarpentry |
| - | ------------- | ------------- |
| Illuminated Blocks | ✅ | ✅ |
| Horizontal Slopes | ✅ | ❌ |
| Climbable ladders  | ✅ | ❌ |
| Signs  | ✅ | ❌ |
| [Improved slope textures](https://user-images.githubusercontent.com/67396813/120078347-06239a00-c0a7-11eb-99aa-3712e1417681.png) | ✅ | ❌ |
| [Improved connected textures](https://user-images.githubusercontent.com/67396813/120078296-bcd34a80-c0a6-11eb-9c34-e58ea4c5e9d6.png) | ✅ | ❌ |
| Mimics block slipperiness | ✅ | ❌ |
| [Stackable Slabs](https://user-images.githubusercontent.com/67396813/120078405-5dc20580-c0a7-11eb-9f22-b3a46e9350bd.png) | ✅ | ❌ |
| [Double Slope block](https://user-images.githubusercontent.com/67396813/120078463-95c94880-c0a7-11eb-8dd6-d3206c513421.png) | ✅ | ❌ |
| Beds | ❌ | ✅ |
| Custom block designs | ❌ | ✅ |
| Multiple textures per frame | ❌ | ✅ |
| Overlay textures | ✅<sup>1</sup> | ✅ |


<sup>1</sup> Requires the addition of [Chipped](https://www.curseforge.com/minecraft/mc-mods/chipped)

**Comment by NillerMedDild** [comment]
> Why can't we have both mods in parallel? Then you would have the choice between the better slopes, functioning ladders and signs (from FramedBlocks), and the "luminous feature", overlays, rotations and the chisel options (from BlockCarpentry). I would miss a few things from BlockCarpentry because there is no substitute for them at FramedBlocks.

Because they're too similar to warrant keeping both, much like RS and AE2 :)

**Comment by PianoManu** [comment]
> > Why can't we have both mods in parallel? Then you would have the choice between the better slopes, functioning ladders and signs (from FramedBlocks), and the "luminous feature", overlays, rotations and the chisel options (from BlockCarpentry). I would miss a few things from BlockCarpentry because there is no substitute for them at FramedBlocks.
> 
> Because they're too similar to warrant keeping both, much like RS and AE2 :)

Sad but understandable

**Comment by PianoManu** [comment]
> I have made a table below that highlights the key differences between the mods.
Thanks @MrBazlow

**Comment by landretk** [comment]
Can `byg:basalt_barrera` be yeeted? It only spawns on coastlines with terraforged and it looks totally out of place. Also annoying early on cause you can fall in holes and it takes forever to mine out if you don't have diamond tools.

![image](https://user-images.githubusercontent.com/4535529/120082717-baaac500-c081-11eb-839c-2aeb65001858.png)

**Comment by pm065** [comment]
Shame it doesn't spawn right. That biome looks like it'd be really cool if it did.
But if a biome looks weird in TF it probably should go on the NillerMedDild Corp.® Yeet List™. After all, the Overgrown Spires are only getting removed because they look bad in the pack's default world type.

**Comment by theboo** [comment]
I personally like the look of the Barrera( and it seems everyone is split 50/50 on whether they like it or not)... As for overgrown spires, it will only be disabled in terraforged worlds, if someone makes a non TF world it will exist

**Comment by Merlo17** [comment]
I don't see the argument to remove basalt barrera because "it doesn't look good", since that's mostly personal preference. It's a small biome on a beach so you can very easily just move away a bit. Personally I like it and would be sad to see it go for no reason, nobody is forcing you to live there

**Comment by MuteTiefling** [comment]
Personally think the basalt barrier looks pretty sweet. Gives some variety to shorelines

**Comment by landretk** [comment]
But why is it beach? Seems like a bug to me. It'd be fine if it were in the normal biome list, but it only spawns as beach, which in TF can be like 1-3 blocks wide in some places. Makes sense with sand but not when it's basalt spires. Isn't basalt supposed to be a nether material too?

**Comment by NillerMedDild** [comment]
It is intended that it is marked as a beach.

**Comment by MuteTiefling** [comment]
> But why is it beach? Seems like a bug to me. It'd be fine if it were in the normal biome list, but it only spawns as beach, which in TF can be like 1-3 blocks wide in some places. Makes sense with sand but not when it's basalt spires. Isn't basalt supposed to be a nether material too? Ig I can edit my own biome weights to make it 0, just thought I'd point it out because I thought it was a bug that it's getting tagged as beach.

Try not to think of it as a beach. That's just the minecraft way of saying, making this part of the coastline. 

Not all coasts are sandy: https://www.smithsonianmag.com/smart-news/researchers-reveal-how-giants-causeway-was-formed-180968806/

**Comment by pm065** [comment]
Oh, yes! Giant's Causeway, of course! That's what it's supposed to look like! I feel stupid now :p

**Comment by pm065** [comment]
May I suggest a few more mods to throw in the TrashSlot?
- AIOT Botania - You don't really get much out of it, and most of the content is kind of cluttery
- Cake Chomps - I don't see much point. Usually, in Minecraft, you are not eating cake and a whole mod just for cake sounds seems weird.
- Cooking for Blockheads - There are WAY better cooking mods now, like Farmer's Delight (I'm also not a fan of Simple Farming - I much prefer Neapolitan + FD + AD but I know that no matter how much I push it no one will agree there) 
- Dark Utilities - Most of the things it adds are done better by other mods
- Framed Compacting Drawers - I see no need or use whatsoever
- Just Enough Beacons - Feels like an insult to intelligence
- Lost Trinkets - Very overpowered and weird to get extra powers randomly (this has been discussed previously though)
- Magic Feather - I don't see the need for multiple methods of flight
- Masonry - Chipped is better
- Neat - `is a mod by Vazkii` You can just point the One Probe at something, in my opinion. It also removes some of the challenge of mobs, sometimes, because you can see the plate through walls, right?
- Passthrough Signs - I don't see much point.
- Polymorph - While useful for conflicts, it tends to explode (last time I used the polymorph command my game crashed after hanging for a while)
- Storage Drawers - Might be time to consider removing this again?
- Tactical Fishing - I don't see much point.

Mods in the slot already that I don't think should be there
- Ambient Sounds 3 - It adds so much more vibrancy to a very silent world, in my opinion. Unlike Cake Chomps, you hear it all the time.

Mod that could possibly replace the inevitable endless amounts of tweak mods - Forgery https://www.curseforge.com/minecraft/mc-mods/forgery (CurseForge just died yesterday so you should probably look it up on the app, which is working)
Its name once it's downloaded is Fabrication because it's that mod but Forge-compatible.

**Comment by MuteTiefling** [comment]
Lemme try taking a stab at these


> * AIOT Botania - You don't really get much out of it, and most of the content is kind of cluttery
This is more of a mod parity issue by introducing multitools for higher tier materials to compete with lower tier stuff (Mek Paxels). I could see an argument for removing _all_ such multi-tools, but I don't think we're quite there yet. 

> * Cake Chomps - I don't see much point. Usually, in Minecraft, you are not eating cake and a whole mod just for cake sounds seems weird.
Fun, light weight, not harming anything

> * Cooking for Blockheads - There are WAY better cooking mods now, like Farmer's Delight (I'm also not a fan of Simple Farming - I much prefer Neapolitan + FD + AD but I know that no matter how much I push it no one will agree there)
Think of this one more as decorative. It lets you build out a nice looking kitchen, even if a lot of the functionality is lost without something like Pam's

> * Dark Utilities - Most of the things it adds are done better by other mods
Charms. Especially the Sleep and Gluttony Charms. The rest of it is also nice for making mob farms. Are there other options? Yes. Are they quite the same? No.

> * Just Enough Beacons - Feels like an insult to intelligence
More information for the player is good. A lot of effort has gone into this pack just to help bring more information into the face of the player to help them out. Not everyone is a minecraft pro :D

> * Lost Trinkets - Very overpowered and weird to get extra powers randomly (this has been discussed previously though)
These are fun to obtain. Some of the worst offenders are already disabled, however. 

> * Magic Feather - I don't see the need for multiple methods of flight
Think in terms of Expert where flight may well be gated to late game. This gives players a creative flight option they can use around their base for building purposes, without giving full flight all the time, everywhere. 

> * Masonry - Chipped is better
Different block coverage

> * Neat - `is a mod by Vazkii` You can just point the One Probe at something, in my opinion. It also removes some of the challenge of mobs, sometimes, because you can see the plate through walls, right?
Honestly this feels like one of those things that should be standard in the game by now. Knowing how much health a mob has doesn't really diminish the challenge (as much as we can call combat in Minecraft challenging). 

> * Passthrough Signs - I don't see much point.
QoL for folks who organize storage with signs. Lightweight, no harm.

> * Polymorph - While useful for conflicts, it tends to explode (last time I used the polymorph command my game crashed after hanging for a while)
Haven't seen any issues with this one yet. And while we'd love to be able to say every conflict has been removed by scripts, the reality is, that is going to take some time. Especially with mods shifting around.

> * Tactical Fishing - I don't see much point.
QoL. Some builders love putting aquariums in their builds. This adds a nice easy way to obtain fish in buckets when you can't find them in world. Options are good :D

> * Storage Drawers - Might be time to consider removing this again?
> * Framed Compacting Drawers - I see no need or use whatsoever

As long as storage drawers is in, Framed Compacting Drawers may as well be too. This largely comes down to building. It's nice for people to be able to make a nice storage room and theme their drawers the way they wish. 

Could Storage Drawers go? Certainly. I personally wouldn't miss them. But I know a lot of players would. 


As for Forgery, it looks like there are a few good features there but a lot would have to be disabled.

**Comment by PipeWizard** [comment]
I'd be really sad to see Storage Drawers added to the chopping block because the compacting drawers are so insanely nice for bulk storage and crafting of resources + they combo extremely well with Create's material processing chain just as an example of mechanical use.

**Comment by Erysch** [comment]
Definitely keep Storage Drawers. They are pretty and they are pretty need. 
I had fun creating a little workshop with them because everything looks so tidy and clearly designed with them. I prefer them instead of having a chest full of the same thing because i can also instantly see what's in there.

**Comment by Ruhart** [comment]
Maybe consider tweaking the craft for the creative flight lost trinket? I got crazy armor from the boss mobs that let me kill the ender dragon really early.  I took my jetpack and did like half an hour of hunting in the end, which resulted in infinite creative flight just barely into the mid game.

The hardest part of the craft was the artifact that drops from shulkers, but there are like a million shulkers spawners in one end tower, so you can farm it there or box a couple up for the road.

I hope we get the newest version of Create, too! I have a need for smart chutes and brass funnels that don't require conveyer belts to work!

This is my first Enigmatica pack, and my gf and I are having a great time playing it. Gonna try my hand at E2E after this. :D

P.S.: What's the mod that changes the darkness sound to music? It wreaks havoc on the Minecraft bgms.

**Comment by NillerMedDild** [comment]
> 
> 
> Maybe consider tweaking the craft for the creative flight lost trinket? I got crazy armor from the boss mobs that let me kill the ender dragon really early. I took my jetpack and did like half an hour of hunting in the end, which resulted in infinite creative flight just barely into the mid game.
> 
> The hardest part of the craft was the artifact that drops from shulkers, but there are like a million shulkers spawners in one end tower, so you can farm it there or box a couple up for the road.

I think creative flight is in a good place tbh, I feel like that amount of effort is sufficient for creative flight.

> I hope we get the newest version of Create, too! I have a need for smart chutes and brass funnels that don't require conveyer belts to work!

We will update all mods to their latest stable versions, we usually do :)

> P.S.: What's the mod that changes the darkness sound to music? It wreaks havoc on the Minecraft bgms.

**Comment by Ruhart** [comment]
> I think creative flight is in a good place tbh, I feel like that amount of effort is sufficient for creative flight.
>>
I'm probably just used to packs that give it really late, lol. I play a lot of massive kitchen sinks that take a heck of a long time to get flight (PO2, I'm looking at you... so much RAK...). I do really love that you can go magic or tech route to get it, too.
> We will update all mods to their latest stable versions, we usually do :)
>>
Awesome! My Create charcoal machine is so close to done, but I've been having trouble getting depots to work with pipes. Pretty Pipes can have fire blown through them, but they bug bad with Storage Drawers.
> Ambient Sounds perhaps, if you're on a version that still has that.
>>
Ah, I might remove it myself. I like the music itself and love the outside ambience, but the darkness music plays at the same time as Minecraft bgm sometimes. It cuts off so suddenly and most of the time takes the bgm with it and I never hear any bgm again (I like to add Infinite Music to the packs I play, and it even cut off the bgm forever with that installed).

**Comment by ZephyrWindSpirit** [comment]
With the removal of Babel, a library mod, Just Enough Piglin Bartering breaks. Just a heads up. I'm on 0.4.14 of E6 and disabled the mods that are going out. Tosses an error almost immediately.

**Comment by landretk** [comment]
> With the removal of Babel, a library mod, Just Enough Piglin Bartering breaks. Just a heads up. I'm on 0.4.14 of E6 and disabled the mods that are going out. Tosses an error almost immediately.

I think this list is out of date compared to the develop/ branch as JEPB and Babel are in the latest dev version of 0.5. 

If you are trying to future proof your copy of 0.4.14 I would cross reference against the develop/ minecraftInstance.json as that's the latest list of mods available until 0.5 is released.

**Comment by NillerMedDild** [comment]
We've discovered that, but thanks anyway 👍

**Comment by g0urra** [comment]
I saw that More Red is getting removed, with the motivation that Immersive Engineering already has those capabilities. What exactly in IE is going to replace a setup like this? Lever from Gauges and Switches remotely linked to another lever, and sending redstone signal through Red Alloy Wire when activated.
![image](https://user-images.githubusercontent.com/12349921/121968915-7c94ed00-cd73-11eb-8571-182475e57344.png)

**Comment by landretk** [comment]
> I saw that More Red is getting removed, with the motivation that Immersive Engineering already has those capabilities. What exactly in IE is going to replace a setup like this? Lever from Gauges and Switches remotely linked to another lever, and sending redstone signal through Red Alloy Wire when activated.

All you would need for that is Create redstone links, and i think vanilla redstone or repeaters(although a full strength signal to the middle spawner from a redstone link should also reach the other two)

**Comment by g0urra** [comment]
> All you would need for that is Create redstone links, and i think vanilla redstone or repeaters(although a full strength signal to the middle spawner from a redstone link should also reach the other two)

A Redstone Link would still need a redstone signal from another source to transmit. With a Gauges and Switches lever this is not needed.

**Comment by g0urra** [comment]
Either way, my points is I can't see More Red being too heavy of a mod to remove it from the modpack, and it still has its uses that other mods in the pack don't.

**Comment by landretk** [comment]
Yeah after looking at it more I would like to see it stay in just for the wire/cables, which seem unique to it. Being able to go up walls with redstone opens up a lot of possibilities.

**Comment by MuteTiefling** [comment]
Immersive Engineering recently overhauled their "Circuit" item. Previously this was just a crafting step for other things, but now it has a utility purpose: Programming logic gates.

With this, there's a new "Logic Gate" block. This block can accept up to 10 circuits. Each circuit is programmed in an Engineer's Circuit Table to create various common gates, such as NOT, OR, AND, XOR, NOR, NAND, and XNOR. These all accept color coded inputs and outputs, and all logic circuits inside a single gate will can interact with each other by way of Registers. This allows you to build up some impressive logic inside a single gate, or simply consolidate a bunch of logic processing through a single block.

The wires themselves can be routed practically however you wish, ignoring the need of placing them on surfaces every step of the way. And when combined with wireless redstone from things like Create or RFTools, it covers a lot of use cases. 

In reference to those spawners above, however, you can accomplish the same thing with Gauges and Switches combined with vanilla redstone. 

![2021-06-14_20 21 32](https://user-images.githubusercontent.com/9543430/121974779-282b4680-cd4e-11eb-92bd-d5901a14c8b3.png)
![2021-06-14_20 21 33](https://user-images.githubusercontent.com/9543430/121974780-28c3dd00-cd4e-11eb-98fc-4677a74dd6fd.png)

And no, More Red isn't a heavy mod. But it's also entirely replicated by (several) other mods so there's not much need for it.

**Comment by theboo** [comment]
more red did, however, get a CC:Tweaked integration mod recently xD 

https://www.curseforge.com/minecraft/mc-mods/more-red-computercraft-integration

**Comment by stylzm** [comment]
Seeing as you are planning on removing Bountiful Baubles, could you perhaps consider adding [Relics](https://www.curseforge.com/minecraft/mc-mods/relics-mod) in its place? The baubles it adds in are pretty unique, and it is also highly configurable.

**Comment by tangzixiang-hash** [comment]
I don't know why I want to remove Builders Crafts & Additions。
It provides some building blocks. I used the cubes it provided to repair some buildings, and I would be very frustrated without it.

**Comment by SirEdvin** [comment]
One more vote for More red and CC: Tweaked integration. please! :)

Also, what wrong with EmbellishCraft? Basalt block from there is one of my favorite black block in game ..

**Comment by SirEdvin** [comment]
Also, can we keep `Storage for Computer Craft`? I know, that advanced peripherals do the same, but on 0.4.14 it just cause RS storage to freeze on every request and I am not sure if someone test if it fine on big storages now.

**Comment by NillerMedDild** [comment]
> Also, what wrong with EmbellishCraft? Basalt block from there is one of my favorite black block in game ..

There's nothing wrong with it, but we cannot just have all mods in the pack, it would be a performance nightmare.

**Comment by SirEdvin** [comment]
Oh, very sad ( But I guess, if you say so, so I have no chance but to rework my base or build a new one)

**Comment by yagoplx** [comment]
I can vouch for keeping in AmbientSounds3! I like the mod a lot, it fits the whole terraforged scenery a lot more than vanilla.

One mod that I'd really like to see gone but isn't is Neat, it's made very much redundant by The One Probe, so I've removed it from my local copy :P
