### ISSUE TITLE
Chicken nests from farmingforblockheads

### ISSUE THREAD

**Issue by Chtholly-dev** [NillerMedDild/Enigmatica6#1572]
**Modpack version 04.3**

**Describe the bug**
Ok so the nests are broken. In the vicinity of a chicken they will pull out the eggs from them instead of it acting like an ender hopper for eggs. Even with no eggs on the ground it makes eggs out of thin air. Even Motoko saw this with me.

**Logs**
there is no crash log here

**Screenshots**
https://gyazo.com/bd50bad3c5d2850e5c4f1040eeaa8946

**Comment by NillerMedDild** [comment]
I can't reproduce this, nor can I view the video :/

**Comment by theboo** [comment]
I'm able to view the video... It's making eggs from essentially nothing haha... If moto saw it, does this mean official server? Could it be some weird lithium interaction?

**Comment by NillerMedDild** [comment]
Perhaps, but it's purpose is to collect eggs, so they may just not be in line of sight?

**Comment by MuteTiefling** [comment]
Nah, they're weren't any other chickens or eggs that I could see (and yes, was on our server).

It was only happening in that one spot and I think it eventually cleared up after a restart or something.
