### ISSUE TITLE
Botany pots enhancement and way to obtain bee-nest before silk touch.

### ISSUE THREAD

**Issue by 2xMJet** [NillerMedDild/Enigmatica6#1574]
**Description**
There is vanila way to farm bee-nests. Planting birch and oak tree sapplings with flowers around. Afaik every flower gives 5% probability roll, that grown tree will be with bee-nest on it.

But 2 things thats different between Vanila and Enigmatica:

* It Requires any silk touch tool, which slows your Resourceful bees-progression drastically.

* It can automated only on middle stages of the game.

I want to suggest similar botany pot way to get bee-nests through planting birch and oak sapplings. But since we cant put flowers with our tree in one botany pot together, we can set this chance lower than 5% and roll it only once per growth cycle.

Other way to realise this: Roll bee-nests on birch and oak with even higher chance than vanila but only with good soils.

**Why would you like this added/changed?**

* Vanila thing, but modded way

* This can be good way to obtain Bee Nests without needing to farm them all over the world or like described above.
 
* It can be good when you dont have silk touch enchant for obtaining nests.

* It can bee good passive way to get good amount of nests for the moment where you will need them if you wont jump straight into Resourceful bees mod.

**Screenshots if applicable.**

Dont think its needed.

**Comment by NillerMedDild** [comment]
Good suggestion, we'll think about it :)

**Comment by MuteTiefling** [comment]
Resourceful Bee's nests are easily crafted, appear all over the world, do not need silk touch to harvest, and work perfectly fine with Vanilla Bees. 

They're also easily automated with a dispenser and scraper, or various other means. 

Also regarding silk touch, vanilla nests can be easily moved with cardboard boxes long before getting a silk touch enchant. They're also quite common in the world.

I'm not sure I understand the problem that's attempting to be solved with this?

**Comment by NillerMedDild** [comment]
Based on Mute's comment above, this is a nope :)
