### ISSUE TITLE
Better looking Morph-O-tool?

### ISSUE THREAD

**Issue by Mendanbar** [NillerMedDild/Enigmatica6#1578]
**Description**
This is super silly, but can we change the look of the Morph-O-Tool?  The default look is just goofy IMO, and it makes me not want to hide all of my awesome looking wrenches behind a jester's wand.

**Comment by NillerMedDild** [comment]
@Ridanisaurus Does this peak your interest? :P

**Comment by NillerMedDild** [comment]
Could you perhaps convert that to a texture? I can't seem to get the intervals right.
