### ISSUE TITLE
[Request] OptiForge Addition

### ISSUE THREAD

**Issue by Enethim** [NillerMedDild/Enigmatica6#158]
**Modpack version**
0.2.7+

**Issue**
Please add "OptiForge" to the mod packs(0.2.7 and onward) Free hosting services like "Aternos" do not allow us to add separate mods to the mod packs. Without OptiForge on server I'm being kicked for mismatched mod list. 
(without OptiForge optifine has missing textures and crashes on Botania mod page in creative)

-T.y

**Comment by NillerMedDild** [comment]
Why did you close this?

**Comment by Darkere** [comment]
Optiforge is not needed on the server to connect with it.

**Comment by NillerMedDild** [comment]
In that case, this is a no :) thanks for the suggestion anyhow.
