### ISSUE TITLE
Create - Pretty Pipes Crash

### ISSUE THREAD

**Issue by PipeWizard** [NillerMedDild/Enigmatica6#1581]
**Modpack version**
0.4.3
**Describe the bug**
I had a Pretty Pipes pipe network hooked up to a diamond chest and Create's furnace engine's furnace block above Create's minecart converter.  Everything was superglued together.  I had several modules installed in the pretty pipes including Low Extraction, Low Retrieval, and Medium Retrieval on three sides of the furnace for logs and charcoal management.  There were no items currently being transferred through the pipe network when I flipped the lever.  Upon flipping the lever to convert, I immediately crashed to desktop.  I believe the chunk is now corrupt and thus the server has been soft-locked until I delete and regen the chunk which will be fun to learn.  I tested it many times before I installed the Pretty Pipes network and it had worked fine. 

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
https://paste.ee/p/we5oo
[crash-2021-03-07_16.27.32-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6097994/crash-2021-03-07_16.27.32-client.txt)

**Screenshots**
N/A.  Sorry, I didn't screenshot anything before I flipped the lever.

**Comment by OneLemonyBoi** [comment]
Fix the link please

**Comment by PipeWizard** [comment]
Link works now @OneLemonyBoi sorry about that.

**Comment by OneLemonyBoi** [comment]
It seems like a weird interaction between Pretty Pipes and Create. Definitely a Pretty Pipes issue as this is the error from Create: TileEntity prettypipes:pipe didn't want to render while moved.

**Comment by OneLemonyBoi** [comment]
Ok so there is a PR in for Create that should fix the issue:https://github.com/Creators-of-Create/Create/pull/846.

**Comment by NillerMedDild** [comment]
Thanks for the report, I also relayed it to Pretty Pipes :)

**Comment by PipeWizard** [comment]
Best to delete the region/chunk and go from there then?

**Comment by OneLemonyBoi** [comment]
Yes
