### ISSUE TITLE
Pack does not contain Quark Oddities

### ISSUE THREAD

**Issue by Zuthal** [NillerMedDild/Enigmatica6#1582]
**Modpack version** 0.4.3

**Describe the bug**
The Quark Oddities mod is not included in the pack's direct download off of Curseforge, while the changelong makes it seem like it should be included.
**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/12097745/110257731-6ff84000-7f9f-11eb-9836-c75cbd32bf2a.png)
QuarkOddities-1.16.3.jar should, going by the patchnotes mentioning it, be present here, but it isn't. Freshly installed E6 0.4.3 with MultiMC from the .zip file off of Curseforge.

**Comment by Merlo17** [comment]
it was removed in 0.4 due to us finding another grave mod afaik. where do you think the changelog implies it should be included?

**Comment by Zuthal** [comment]
The changelog doesn't mention that for Quark Oddities, nor anything about graves - the only mention of either Quark Oddities or graves I can find in the changelog is in 0.2.1 GraveStones being removed in favour of Quark Oddities graves, and in 0.3.0 the crafting of Quark Oddities pipes being disabled. There is currently in the pack no grave mod - or at the very least no mod with "grave" in its jar's name.

**Comment by theboo** [comment]
There should be "simple tomb"

**Comment by Zuthal** [comment]
Yes, the mod Simple Tombstone is in the pack - though then if the removal of quark oddities was intentional the changelog should be edited to mention that, to avoid other people being confused like I was.

**Comment by theboo** [comment]
Oh, I remembered what happened... These changelogs are mostly generated automatically, but when we removed quark oddities, curse decided to remove all of quark at the same time... Took a couple tries to get quark back in, and it probably just got missed in the shuffle

**Comment by Zuthal** [comment]
Ahhh, gotcha! Good that got cleared up, then!
