### ISSUE TITLE
Another way to make eggs

### ISSUE THREAD

**Issue by ManiacRobertWasTaken** [NillerMedDild/Enigmatica6#1584]
**Description**
We need another way to do eggs for things like : Botania kekimurus and alot of food recipes, adding 50 chickens and a vacuum it's not really tps efficient

**Why would you like this added/changed?**
I can't imagine that, but a "ChickenBee" or "EggBee"

**Comment by OneLemonyBoi** [comment]
I volunteer the name ChickBee

**Comment by Scorch-Mechanic** [comment]
The in-logic way to make cakes for the kekimurus is to use astral sorcery block transmutation (on pumpkins). It's even laid out in one of the pause screen tips.

**Comment by MuteTiefling** [comment]
I feel like a plant based egg substitute might work nicely here.

Apple sauce is a common substitute for egg in cakes, for instance. Not 100% sure what food items we have that could be suitable off the top of my head though.

**Comment by MuteTiefling** [comment]
So we have the following: 
Banana (normally mashed)
Apple (normally apple sauce)
Flax (normaly ground)
Tofu (wrong kind though)
Vinegar (normally mixed with Baking Soda)
Gelatine (Better End Forge, no clue how to acquire it, though I have gotten some)

**Comment by MRT-CO** [comment]
Idk if this will achieve your plan, but Ell added a new way to make eggs with apples https://www.curseforge.com/minecraft/mc-mods/natures-aura/files/3246921

**Comment by NillerMedDild** [comment]
That'll do ^ :)
