### ISSUE TITLE
Occultism Dimensional Mineshaft gives Nether Quarts Ore rather than Nether Quartz Chunks

### ISSUE THREAD

**Issue by telemenar** [NillerMedDild/Enigmatica6#1585]
**Modpack version**
0.4.3 

**Describe the bug**
Occultism Dimensional Mineshaft gives Nether Quarts Ore rather than Nether Quartz Chunks

**Comment by theboo** [comment]
If you silk touch nether quartz ore in the nether, do you get chunks or ore? I can't remember rn lol

**Comment by MuteTiefling** [comment]
we get chunks now. when I first set up compat for the mineshaft we didn't have chunks for quartz

**Comment by theboo** [comment]
I'll push my changes to this tonight and fix this at the same time

**Comment by Rodg88** [comment]
Looks like the IF laser drill also still does vanilla quartz ore

**Comment by MuteTiefling** [comment]
IF drill has also been updated
