### ISSUE TITLE
Unable to submit Farmer's Delight Crates to Bountiful

### ISSUE THREAD

**Issue by tphambusiness** [NillerMedDild/Enigmatica6#1586]
**Modpack version**
0.4.3

**Describe the bug**
There's only 1 type of crate for crops (ex. Beetroot, Potatoes) in JEI (Farmer's Delight), but they do not count towards the Bountiful objectives when requested in a bounty.

**Screenshots**
![image](https://user-images.githubusercontent.com/44181428/110284992-97a3d400-7fb0-11eb-92fb-a9ccea91a985.png)
![image](https://user-images.githubusercontent.com/44181428/110285086-bdc97400-7fb0-11eb-9214-ac2148a1be47.png)
![image](https://user-images.githubusercontent.com/44181428/110285106-c4f08200-7fb0-11eb-9722-55430ab80baf.png)

**Comment by tphambusiness** [comment]
[Bug]

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
