### ISSUE TITLE
Netherite Sophisticated Backpack does not drop when broken with fist (does not happen with any of the other tiers)

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#1587]
**Modpack version**
0.4.1

**Describe the bug**
Title

**Logs**
N/A

**Screenshots**
N/A

**Comment by P3pp3rF1y** [comment]
That is my bad, missed adding block loot for netherite backpack when adding it to the mod (probably missed it as I am almost always used to shift right clicking it back into my inventory). I will get fix for that in the next release, which will probably happen in a few days.

**Comment by P3pp3rF1y** [comment]
Alright I lied, new version that fixes this is up on CurseForge today.
