### ISSUE TITLE
Diamond knife turnable into iron and gold nuggets.

### ISSUE THREAD

**Issue by 2xMJet** [NillerMedDild/Enigmatica6#1588]
**Modpack version**
0.4.3

**Describe the bug**
Diamond knife seems like turnable into gold and iron nuggets from JEI.
I tested it with one knife in my SP world and it really turns diamond knife into gold nugget. Burned in Blast Furnace.

**Logs**
Not needed i suppose.

**Screenshots**
Thats how it looks, when i look recipes for diamond knife in jei.
![image](https://user-images.githubusercontent.com/26283528/110289427-fc484880-801b-11eb-84a1-d83afb83f3d4.png)

**Comment by OneLemonyBoi** [comment]
Patched in Dev already.
