### ISSUE TITLE
Biodiesel power balance

### ISSUE THREAD

**Issue by shengjie** [NillerMedDild/Enigmatica6#1589]
**Modpack version**
0.4.3

**Describe the bug**

Immersive engineering diesel generator generate 4096 RF/t in [250 ticks](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.16.5/src/main/java/blusunrize/immersiveengineering/common/IEContent.java#L773) with 1 bucket biodiesel. so total RF per bucket = 4096 RF/t * 250 t = 1 024 000 RF

However, 1 bucket biodiesel generates [10 000 000 RF](https://github.com/NillerMedDild/Enigmatica6/blob/develop/kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/dynamo/compression.js#L20) in thermal series compression dynamo: 10 times more than diesel generator. (notice the multiplier of 10 in script)

With 26 compression dynamo + tier 3 augment (160RF/t) i can get 4160 RF/t but runs 10 times longer (2403 ticks vs 250 ticks) than diesel generator.
This makes noisy diesel generator complete useless.

Since fuel value is hard-coded in immersive engineering. we can either buff diesel generator to 40960 RT/t or nerf compression to 1 000 000 RF.

**Logs**
no

**Screenshots**
![2021-03-08_11 10 03](https://user-images.githubusercontent.com/2143339/110307174-e7a98780-7ffe-11eb-81e0-c72643906b82.png)

**Comment by MuteTiefling** [comment]
Burning fuel slower frequently results in efficiency gains. You'll see the same with the thermal dynamos where you can run them at 640 rf/t at 73% efficiency, or 160 rf/t at 133% efficiency.

So you'd need 7 dynamos minimum to match the rate of the big generator. But that also means losing a lot of the Rf, resulting in only 7.3m Rf. Still a lot, but also at significant material cost. Ten dynamos, ten resonant integral components and thirty aux reaction chambers.

**Comment by MuteTiefling** [comment]
By contrast, the IE diesel takes roughly the following if I've calculated correctly. 

99 Steel Ingot
29 Copper Ingots
14 Iron Ingots
4 Gold Ingots
4 Silver Ingots
6 Redstone Dust

99 steel seems like a lot, but that's not too bad to craft if you use Mekanism. It's certainly easier to come by than all of those pearls, quartz, glowstone, diamonds, and metric ton of silver, lead, and copper. 

So you have a fair material trade off as well. You can build the cheap IE generator, burn fuel faster, but for less power. Or you can spend a huge amount of materials to build an equivalent set of dynamos for a decent efficiency gain when burning the fuel.

Or you can go even more crazy, stick to the 160 rf/t configuration, build 26 dynamos and all accompanying upgrades, and gain even more efficiency. I'm not going to calculate the cost there, but it's not going to be cheap to build 78 Multi-cycle Injectors for that.

**Comment by NillerMedDild** [comment]
Could you perhaps make a wiki entry about this Mute? :)

**Comment by MuteTiefling** [comment]
Sure. Shall I do a Thermal page dedicated to dynamos (leaving out exact material cost) and an Immersive page detailing it's various power rates?

**Comment by NillerMedDild** [comment]
Yes please!
