### ISSUE TITLE
Ocean Monuments spawn rate is quite high.

### ISSUE THREAD

**Issue by AndreiPurcaru** [NillerMedDild/Enigmatica6#1593]
This happens on the latest version (0.4.3)

Ocean Monuments are too frequent (right next to each other)

Maybe it could be possible to decrease their spawn rate. I have attached a screenshot showing how frequent they are. And this is only one ocean, they are as frequent in all other oceans I have encountered.

![image](https://user-images.githubusercontent.com/59032206/110386263-bfef0980-8068-11eb-864e-2a964547ce3c.png)

**Comment by OneLemonyBoi** [comment]
This is vanilla behavior, as in Deep Oceans (Dark Blue), there is 1 ocean monument every 4 chunks or so. This wasn't as common back in 1.12, but it was upped in 1.16.

**Comment by MuteTiefling** [comment]
I've oddly only found one, despite a lot of hunting. RNG and all that. 

Sometimes there's lots, sometimes none at all.
