### ISSUE TITLE
Supplementaries Crimson Lantern texture missing in inventory

### ISSUE THREAD

**Issue by 2xMJet** [NillerMedDild/Enigmatica6#1599]
**Modpack version**
0.4.3

**Describe the bug**
Not sure if its mod issue or modpack, but will report it there.
When i look up shroomlight-containing recipes in JEI, i see Crimson Lantern recipe with missing texture.
From discord i know that lantern itself looks fine, when placed.
 
**Logs**
Can provide a log, but dont think its needed now.

**Screenshots**

Inventory:
![image](https://user-images.githubusercontent.com/26283528/110427535-7b9c5180-80da-11eb-9287-ee7e6fb7456a.png)

Tooltip:
![image](https://user-images.githubusercontent.com/26283528/110427952-172dc200-80db-11eb-9052-fe1239ce0917.png)

Motoko's Screenshot of this lanterns in-game:
![image](https://user-images.githubusercontent.com/26283528/110427898-02512e80-80db-11eb-8746-2d6750b563c4.png)

**Comment by NillerMedDild** [comment]
Gonna go ahead and close this, I'm fairly certain the item just isn't finished.
