### ISSUE TITLE
Can't make charged certus quartz

### ISSUE THREAD

**Issue by hdn6371** [NillerMedDild/Enigmatica6#160]
**Modpack version**
0.2.8

**Issue**
I'm trying to put in EE certus quartz into AE2 charger machine to get charged certus. But I can't seem to place the certus into the charger no matter what I do. I tried in the regular AE2 certus quartz and it accepted it. Was looping through jei for any other recipe that produces charged quartz but was not coming up with any that didn't require crushing ores of the charged quartz. 

Someone on discord suggested the powah mod, I tried a setup in creative with the power orb and connect it to the rods but nothing happens. 

Is there a recipe that I am missing?

**Comment by NillerMedDild** [comment]
Oversigt on my part, will be fixed in 0.2.9 :)
