### ISSUE TITLE
End oregen y-levels

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1601]
**Modpack version**
0.4.3

**Describe the bug**
Some of the ores set to generate in the end only generate in y-levels which aren't solid in the biomes they are set to generate in. Eg Aluminium ore, generates at y 70-90 in ivis fields, but that biome maxes out at about 65. I've also not seen any iron in the ivis fields, even though i'm looking at the right y-level, basically only seeing dimentional shards and the BetterEnd ore.

Maybe if all the oregen in the end is set to y 10-60 it would fix it?

**Comment by NillerMedDild** [comment]
Some of the End biomes generate too late during worldgen to spawn our ores in sadly :/ Will fix aluminum ore y level though.
