### ISSUE TITLE
BYG Nether biomes Compatibility changes.(part 1, probably)

### ISSUE THREAD

**Issue by 2xMJet** [NillerMedDild/Enigmatica6#1602]
- [x] Quartz Sand Gravel->Flint-like recipes (Quartz Sand drops Quartz in the same fashion as Gravel drops Flint)

**Description**
Some suggestions on compatibity of BYG and modpack recipes:

- [x] Brimstone and Blue Netherack:

Add tags for BYG's colored Nether bricks and Netherrack variatons to behave as common vanila Nether Bricks and Netherack in crafting-recipes (not smelting), since there is 2 more colored variants of netherrack(and nether bricks) in the nether now, and they applicable only for decorating.

- [x] Embur Gel:

 Add Embur gel as Slime in recipes since Embur gel blocks behave like slime and this Gel now is useless. Only decorating purposes too.

- [x] Quartz biomes:

Add some ways to get quartz from quartzite sand and Raw quartz blocks from BYG Quartz biome. Maybe some machinery recipes for it not to be imbalance. Since now it can be used only as decoration too.

**IDs of mentioned things:**
Netherack and Nether Bricks:
```
byg:blue_nether_brick
byg:blue_nether_bricks
byg:blue_netherrack
byg:yellow_nether_brick
byg:yellow_nether_bricks
byg:brimstone
```
Slime:
```
byg:embur_gel_ball
byg:embur_gel_block
```
Quartz:
```
byg:quartzite_sand
byg:raw_quartz_block
```

**Why would you like this added/changed?**

* Currently most of this things is useless, except decorating purposes.
* More Cross-compatibility with BYG and modpack recipes.
* More sence in BYG biomes in the nether.

**Screenshots if applicable.**
All things mentioned above:
![image](https://user-images.githubusercontent.com/26283528/110431913-fff1d300-80e0-11eb-9eeb-f3a0903c507b.png)

**Comment by Merlo17** [comment]
taking care of the rest probably tomorrow ^^

**Comment by MuteTiefling** [comment]
Just a note on quartzite sand: It already produces quartz. You just need to break it like gravel.

That said, some recipes similar to the various Gravel > Flint recipes could be interesting.

**Comment by NillerMedDild** [comment]
Roger, reopened and added the gravel -> flint task to the main comment.

**Comment by NillerMedDild** [comment]
Updated Quartzite Sand -> Quartz recipes to be similar to Gravel -> Flint recipes
