### ISSUE TITLE
Integrated Dynamics book tutorial rewards/advancement issue

### ISSUE THREAD

**Issue by Seceroth** [NillerMedDild/Enigmatica6#1603]
**Modpack version**
Version 0.4.3

**Describe the bug**
Doing the tutorial in the ID book is supposed to give you rewards after completing each section. The prerequisites can be  completed and then the Reward button can be clicked and it will show that the rewards are completed with green check marks. However, the rewards never reach the inventory and upon closing and opening the book again, the rewards button can be clicked again and this goes on forever. This happens on a server. Server only outputs one line, see below.

Did test on a single-player world and it does work in single-player. Rewards enter inventory upon closing the book, not as soon as the button is clicked if that's relevant.

**Logs**
Only relevant log entry would be (This is upon clicking the very first tutorial reward button (Menril Basics)):

 [Server thread/WARN] [cyclopscore/]: Received an invalid advancement reward id 'integrateddynamics:meneglin_basics' from Seceroth.

**Screenshots**
![2021-03-09_11 59 05](https://user-images.githubusercontent.com/20866237/110461041-dfb51a80-80c6-11eb-93d4-6883f433dd47.png)
![2021-03-09_11 59 09](https://user-images.githubusercontent.com/20866237/110461074-e80d5580-80c6-11eb-8df8-b80653d6a23e.png)
![2021-03-09_11 59 16](https://user-images.githubusercontent.com/20866237/110461088-eb084600-80c6-11eb-8f2a-e348b6bdea93.png)

**Comment by NillerMedDild** [comment]
Thanks for the report!

This is asking quite a lot, but would you mind checking if you can reproduce this issue with just Integrated Dynamics and perhaps JEI?

**Comment by Seceroth** [comment]
Alright, tested in single-player and on server with only the following mods:

jei-1.16.4-7.6.1.71.jar
IntegratedDynamics-1.16.5-1.5.1.jar
CyclopsCore-1.16.5-1.11.4.jar
CommonCapabilities-1.16.5-2.5.6.jar
Using forge version 36.0.45

Both single-player and on the server it is working. Nothing is reported in the server console. Second tutorial also works so I assume it all works like this.

**Comment by NillerMedDild** [comment]
Damn, I guess it's something we're doing or another mod then :P

**Comment by NillerMedDild** [comment]
Rewards for both Integrated Dynamics native and FTBQ ID chapter seems a bit excessive anyway, I've disabled rewards from the ID book :)
