### ISSUE TITLE
Missing Pumpjack recipe.

### ISSUE THREAD

**Issue by Esteria** [NillerMedDild/Enigmatica6#1604]
**Modpack version**
0.4.3
**Describe the bug**
Need Immersive Engineering's Block of Steel to prepare Pumpjack (multiblock), but no recipe because of Emendatus.

**Comment by Darkere** [comment]
Did you try using the EE Steel block?

**Comment by Merlo17** [comment]
the recipe is also available in the stonecutter (like for any EE block to convert to other mods' blocks)

**Comment by Esteria** [comment]
I should have been more careful. thank you. close
