### ISSUE TITLE
Mod request: Building Gadgets by Direwolf20

### ISSUE THREAD

**Issue by tonyvans** [NillerMedDild/Enigmatica6#161]
Mod request: Building Gadgets by Direwolf20

Mod request https://www.curseforge.com/minecraft/mc-mods/building-gadgets

Was one of my favorite mods from Enigmatica 5

Thanks

**Comment by brckts** [comment]
It has already been added in 0.2.7 iirc

**Comment by NillerMedDild** [comment]
duplicate of #137

**Comment by tonyvans** [comment]
Amazing.Thank you.
