### ISSUE TITLE
RSInfinityBooster

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica6#1612]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/rsinfinitybooster

**Mod description**
Adds an infinite range card and dimension card for longer range access.

**Why would you like the mod added?**
Has come up a few times in Discord; potentially worth a look, and if it isn't lag/crash inducing may be worth adding.

**Comment by Merlo17** [comment]
I would be for this, nice QoL in E6 and a nice challenge item for E6E in the future. We might even gate it behind some stuff in E6, kinda like the flight trinket

**Comment by Mendanbar** [comment]
> How about a quantum entagleporter in the recipe?

Too bad the Mek quests are literally giving those away for free

**Comment by MuteTiefling** [comment]
Having another big power drain would be nice. I like the idea of making it costly to run.

**Comment by TemperedFool** [comment]
Imo the recipe is fine for normal mode - I do think I said that ^_^ - and the ongoing cost is actually the interesting part. If it's configurable, that's even something we could turn up for Expert.l, but for normal I think it's reasonable to just throw in at default.

Someone made a comment I read somewhere that we'll also need to turn up the size of the energy buffer for the RS controller - something to confirm and then adjust before adding this.

**Comment by r-mc2** [comment]
Oh, I totally agree TF, I think this item is just a purely nice QoL for normal mode. I'd love to see it added unaltered as well.

The rest of all that was if there was a *need* to push for a balancing that I'd suggest looking at the power option rather than "what random hard to make item can we jam in the recipe with Kube?" 😆

**Comment by Ridanisaurus** [comment]
> Having another big power drain would be nice. I like the idea of making it costly to run.

I like this. If you want infinite range, and cross Dim access, then you better build a Nuclear Reactor

**Comment by Halfdeaf** [comment]
I like the power req in theory but keep in mind that occultism offers access anywhere storage for no continuous cost

**Comment by Merlo17** [comment]
but no autocrafting afaik right?

**Comment by Halfdeaf** [comment]
Indeed, that sounds good to me

**Comment by NillerMedDild** [comment]
Approved! The default recipe does seem fine for normal mode, same goes for energy usage.
