### ISSUE TITLE
Bayou blues,Abundance And Better badlands

### ISSUE THREAD

**Issue by CletusMAngo** [NillerMedDild/Enigmatica6#1613]
https://www.curseforge.com/minecraft/mc-mods/better-badlands
https://www.curseforge.com/minecraft/mc-mods/bayou-blues
https://www.curseforge.com/minecraft/mc-mods/abundance

**Mod description**
These 3 mods add new biomes that pair beautifully with the BYG biomes and add more variety to the existing vanilla biomes.

**Why would you like the mod added?**
I think these mods would add more life and more decoration types for E6 and i really think they have some potential to be in the  pack.

**Comment by NillerMedDild** [comment]
We'll investigate Bayou Blues & Abundance along with Environmental when we move closer to 0.5.0 :) Moved this suggestion to #1571
