### ISSUE TITLE
Quartz Enriched Iron should have a shapeless recipie

### ISSUE THREAD

**Issue by TheAdamizer** [NillerMedDild/Enigmatica6#1615]
**Modpack version**
0.4.3

**Describe the bug**
Quartz Enriched Iron has a shaped recipe.  That seems weird since it's a 2x2 recipe of  iron and quartz.  Nothing intuitive about needing quartz to be in the bottom right, imo.  Maybe people agree with me that it should be shapeless.

Thanks for your contributions!

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed :)
