### ISSUE TITLE
Compact Machines Teleporting Outside

### ISSUE THREAD

**Issue by ManiacRobertWasTaken** [NillerMedDild/Enigmatica6#1616]
0.4.3

You can teleport outside the compact machine box using Staff Travel or Teleporting enchant (Travel anchors)

![image](https://user-images.githubusercontent.com/39351347/110522593-ba053100-8119-11eb-8dd0-635961905e27.png)

**Comment by OneLemonyBoi** [comment]
I don't think this can currently be fixed, but this is definitely a mod issue.

**Comment by NillerMedDild** [comment]
Ah right, nope.
