### ISSUE TITLE
Pressurized Reaction Chamber shuts down with more than 2 speed upgrades

### ISSUE THREAD

**Issue by FancyBagel** [NillerMedDild/Enigmatica6#1617]
**Modpack version**
Enigmatica Server 0.4.3

Whenever more than two Speed Upgrades are inserted into Mekanism's Pressurized Reaction Chamber, it shuts down and stops producing anything. No other Mekanism device seems to share the problem.

**Comment by telemenar** [comment]
You need to add energy upgrades. The electrolytic separator has the same behavior in default configs.
