### ISSUE TITLE
All slimes have a full-sized hitbox

### ISSUE THREAD

**Issue by ochotonida** [NillerMedDild/Enigmatica6#1619]
**Modpack version**
0.4.3
**Describe the bug**
All slimes, including magma cubes and end slimes (and possibly any other slimes I might have missed) have a hitbox the size of a big slime, regardless of their actual size.

**Screenshots**
![image](https://user-images.githubusercontent.com/37985539/110528954-f84e2080-8118-11eb-97c4-aacba4e89572.png)

**Comment by NillerMedDild** [comment]
Huh, that's a strange one :P

**Comment by NillerMedDild** [comment]
Hmm, do you happen to be using the EntityCulling mod?

**Comment by ochotonida** [comment]
Nope, I'm not using any extra mods

**Comment by ochotonida** [comment]
After looking at it for a while, I noticed that when you spawn a slime, the hitbox starts normal but grows as soon as it starts jumping. This reminded me very much of [this issue](https://github.com/gigabit101/Shrink/issues/19) I reported to Shrink a few days ago, and it just so happens that this issue also occurs with just Shrink and Forge installed.

**Comment by NillerMedDild** [comment]
Ah cool :D
