### ISSUE TITLE
Duplicated recipe for steel dust smelting

### ISSUE THREAD

**Issue by brckts** [NillerMedDild/Enigmatica6#162]
**Modpack version**
0.2.8

**Issue**
The steel dust to steel ingot smelting is duplicated in JEI and shows two different xp yields

![image](https://user-images.githubusercontent.com/51674867/90426768-e3993500-e0c1-11ea-8ddb-8756892cd0f6.png)

**Comment by NillerMedDild** [comment]
Mm I know :/ I'll try to find the cause.

**Comment by NillerMedDild** [comment]
I know this is a bit annoying, but it would take a long time to fix properly to be honest, so I'm going to spend my time on other parts of the modpack. I hope that's understandable.
