### ISSUE TITLE
[Dupe/Save Failure] Lead Interraction

### ISSUE THREAD

**Issue by Elvarion** [NillerMedDild/Enigmatica6#1622]
**Modpack version**
0.4.3
**Describe the bug**
If you place a Lead on a fence that is not tied to anything and then rightclick it again your character wont save and your character is unable to break blocks or interract with anything until relogged.

Instructions to Replicate (Worked for 2 people, and also after full server restart)
Right-Click with a Lead on a Fence Post
Right-Click it again, the lead pops off
Your character is now Glitched.

This can be used to Dupe items very easily

**Logs**
https://pastebin.com/7Qra5yNY

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Ricket** [comment]
Was this closed accidentally? I just bumped into this issue with latest pack version 0.5.25...

I was trying to tie up my new horse to a fence post. I right-clicked the post with the lead, then tried to right click the horse but nothing was responding, I was totally stuck. Then I disconnected, and the server logs say:

```
[00:29:21] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: Ricket lost connection: Disconnected
[00:29:21] [Server thread/INFO] [minecraft/DedicatedServer]: Ricket left the game
[00:29:21] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 87decce1-81cf-469e-8780-dba5acbdaa19
[00:29:21] [Server thread/WARN] [minecraft/PlayerData]: Failed to save player data for Ricket
```

And when I logged in, I was in a location and with inventory from a minute ago.

**Comment by NillerMedDild** [comment]
It's marked as unresolved, meaning there's no hope of getting it fixed 😅
