### ISSUE TITLE
Block Carpentry Chests Crash Servers when Broken

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#1623]
**Modpack version**
0.4.3

**Describe the bug**
Block Carpentry Chests Crash Servers when Broken. Happened twice in a row on the official server.

**Logs**
[crash-2021-03-10_01.59.59-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6112432/crash-2021-03-10_01.59.59-server.txt)
[crash-2021-03-10_02.16.39-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6112433/crash-2021-03-10_02.16.39-server.txt)

**Comment by NillerMedDild** [comment]
Thanks for the report.
I chose to remove the Frame Chest due to general instability #1208
