### ISSUE TITLE
Occultism Storage crafting eats honey bottles

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1624]
Enigmatica 6 0.4.3 (official server)

If more than 4 honey bottles are placed in the crafting grid of the occultism storage (was using tablet to access storage - did not test directly with the primary unit) and the output is shift-clicked rather than individually clicked, it only returns one honey block and 4 empty bottles and the remainder of the honey bottles disappear.

Have not tested with any other crafting systems to see if it is limited to Occultism.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
At long last reported here: https://github.com/klikli-dev/occultism/issues/211 😄
