### ISSUE TITLE
Potatoes don't work in TPP to make Ethanol

### ISSUE THREAD

**Issue by telemenar** [NillerMedDild/Enigmatica6#1625]
**Modpack version**
0.4.3

**Describe the bug**
When you put the potatoes in a TPP with Yeast, pressure, and correct heat. Vegtable Oil is made instead.

I suspect this is because the oil recipe accept any forge:crop and potato has that tag. Ethanol can be made with other options (sweet berries for example).

**Comment by MuteTiefling** [comment]
You're not supposed to apply pressure for ethanol. Just light heating. 

With pressure, you'll end up with oil, yeah. 

it does still look like the oil recipe is wrong though, since it's asking for more than -273... seems a bit off

**Comment by telemenar** [comment]
I could swear this worked in 0.3 because if you have a compact setup pressure moved through connections between the machines. I’ll test with just PNC when I get the chance.

**Comment by MuteTiefling** [comment]
Actually, sorry just tested with only heat in game and the TPP says it wants pressure. It also doesn't work for making Chips. 

Think there's something wrong with the recipe detection, honestly, as I know this was all working fine in 0.3 too.

**Comment by MuteTiefling** [comment]
Confirmed in a simple test world, these are working. So it's probably something to do with the custom recipes we're adding more than anything wrong with PNC. Looking into it.

**Comment by MuteTiefling** [comment]
the weird temp display is also working fine in this test world, so... yeah probably my script for adding more stuff. >.<

**Comment by MuteTiefling** [comment]
So, this is absolutely related to our KubeJS scripts. If I disable the `kubejs\server_scripts\enigmatica\kubejs\base\recipetypes\pneumaticcraft\thermo_plant.js` script and `/reload`, the original recipes still do not work. But if I restart completely after disabling our script, the originals start working. 

Have opened a ticket now with PNC, hopefully Desht can offer some insight at least. It's feeling more like a race condition or recipe detection issue than anything.

https://github.com/TeamPneumatic/pnc-repressurized/issues/758
