### ISSUE TITLE
🔍 Jade 

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#1628]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/jade

**Mod description**
Jade is a fork of HWYLA that includes many additional features and bug fixes. Which means it is incompatible with Hwyla (because it has included it)

**Why would you like the mod added?**
I think that this mod is more concise and clear than top, and the function is not worse than top.

**Screenshots if applicable.**

https://www.curseforge.com/minecraft/mc-mods/jade/screenshots

![1](https://user-images.githubusercontent.com/61337794/110630103-eb483480-81df-11eb-9ce9-f977a33871f7.png)
![2](https://user-images.githubusercontent.com/61337794/110630112-ed11f800-81df-11eb-8d30-a654b15a89b1.png)
![3](https://user-images.githubusercontent.com/61337794/110630128-ef745200-81df-11eb-9146-1ab0535a369c.png)

**Comment by TGMax233Michael** [comment]
I really like the block damage status display, very clear

**Comment by Merlo17** [comment]
It looks nice I guess but I don't see anything it does ToP doesn't do? Or at least nothing important I guess. Any particular reason why we should switch?

**Comment by TGMax233Michael** [comment]
The final decision is not my decision, I just feel that this module is really excellent :)

**Comment by NillerMedDild** [comment]
I don't see much point in switching to be honest. It does look nice though.
