### ISSUE TITLE
EE Fluix unobtainable

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#163]
**Modpack version**
0.2.8

**Issue**
Charged Certus from EE cannot be used to make Fluix crystals from EE. The in world crafting recipe shows up in JEI but does not work.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Darkere** [comment]
Works in SP but is broken on Servers

**Comment by NillerMedDild** [comment]
Well shit. Thanks for the report.

**Comment by NillerMedDild** [comment]
I pinged the mod dev on discord :P

**Comment by ben-mkiv** [comment]
still not working (tested on official server with 0.2.9)

**Comment by NillerMedDild** [comment]
Yup, for now
