### ISSUE TITLE
Possible misscalculation in burntimes with Mapper Base bituminous coal.

### ISSUE THREAD

**Issue by 2xMJet** [NillerMedDild/Enigmatica6#1631]
**Modpack version**
0.4.3

**Describe the bug**

One coal burns 8 items, one EE Bitumen burns 8 items, but bituminous coal form Mapper Base burns 1.25 items
Wich means by crafting bituminous coal you lose 8x9-1.25x8= 62 possible burned items
Seems illogical.
It looks logical only if bitumen is unburnable. Afaik it was intended in Mapper Base.

**IDs:**
```
minecraft:coal - obvious
emendatusenigmatica:bitumen_gem - EE Bitumen
mapperbase:bituminous_coal - Craft result
```
**Logs**

Not sure if its loggable.

**Screenshots**
![image](https://user-images.githubusercontent.com/26283528/110656689-c01b1080-81f2-11eb-870c-f177497a4698.png)
![image](https://user-images.githubusercontent.com/26283528/110656712-c8734b80-81f2-11eb-8409-7a4a99ebb8dd.png)
![image](https://user-images.githubusercontent.com/26283528/110656742-d0cb8680-81f2-11eb-9010-e549c7d137a5.png)
![image](https://user-images.githubusercontent.com/26283528/110656767-d628d100-81f2-11eb-8558-13d32c0a0070.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, we're gonna remove Bituminous Coal completely, as EE Bitumen can smelt 8 items by itself :P

**Comment by 2xMJet** [comment]
I would suggest to add coal tag to EE bitumen then, since mapper base bituminous coal is great "coal" multiplicator when it comes to crafting recipes such as dielectric paste:)
