### ISSUE TITLE
No teleporter name showing - Astral

### ISSUE THREAD

**Issue by Helkbird** [NillerMedDild/Enigmatica6#1633]
Changed names in anvil, they showed in inv. as individual items, names correct.  Names of destinations are not showing in teleporters themselves when teleporting.

**Comment by NillerMedDild** [comment]
Please use the bug template for bugs. Which version are you on?

**Comment by Helkbird** [comment]
It occurred to me while I was out that I am actually on a slightly older version for server reasons.  0.4.1

**Comment by NillerMedDild** [comment]
No worries, 0.4.3 and 0.4.1 use the same version of Astral :)

**Comment by Helkbird** [comment]
And I'll use those labels ;)  Thank you

**Comment by NillerMedDild** [comment]
That helps, thanks :)

**Comment by NillerMedDild** [comment]
I wasn't able to reproduce this I'm afraid.
