### ISSUE TITLE
Menril Logs can be burned in vanilla Blast Furnace for charcoal.

### ISSUE THREAD

**Issue by 2xMJet** [NillerMedDild/Enigmatica6#1634]
**Modpack version**
0.4.3
**Describe the bug**

Looked up charcoal recipes and decided to try burn oak to charcoal in vanila blast furnace for faster results, but only wood compatible to do so is Menril logs.

Not sure, should this be in Suggestions-section or considered as a bug.

**Logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/26283528/110670635-31ad8b80-8200-11eb-96b7-251fb8201433.png)

**Comment by Merlo17** [comment]
Likely a bug, I don't think charcoal should be available in the blast smelter

**Comment by 2xMJet** [comment]
> Likely a bug, I don't think charcoal should be available in the blast smelter

I would suggest more woods to be possible to burn in blast furnace then, since it can be applicable only for earlygame, to speedup things a bit. In my opinion it wont hurt balance so much, but will make charcoal making 2 times faster earlygame.

**Comment by Merlo17** [comment]
It just doesn't really fit thematically imo. It's supposed to be the one to smelt ores faster, so I don't really see why it should be there besides convenience. Plus, if you really want to speed things up early game, use time in a bottle :D

**Comment by 2xMJet** [comment]
Ok, i looked recipe of TiB and your statement makes sense, will craft it ASAP^_^

**Comment by Merlo17** [comment]
actually nevermind, we still need to remove that recipe, whoops
