### ISSUE TITLE
How to increase max force loaded chunks ? 

### ISSUE THREAD

**Issue by atgytiq** [NillerMedDild/Enigmatica6#1636]
Is there a possible way to load more chunks ?

**Comment by theboo** [comment]
Worldsavefolder/serverconfigs/ftbchunks-server.toml

**Comment by NillerMedDild** [comment]
In your world's folder `serverconfig/ftbchunks-server.toml` line 10 :)

**Comment by NillerMedDild** [comment]
Nooo I missed it by 5 seconds 😄

**Comment by theboo** [comment]
Ninjad
