### ISSUE TITLE
More recipes for the IE industrial fermenter

### ISSUE THREAD

**Issue by DarkAngel22579** [NillerMedDild/Enigmatica6#1637]
**Description**
Currently the fermenter only accepts potatoes, melons, tomatoes, apples, and sugarcane. It would be nice to be able to use the crops from simple farming/ farmers delight to make ethanol, instead of just those five. 

**Why would you like this added/changed?**
Having more options to choose from would be nice. The industrial squeezer already has simple farming recipes, so it makes sense for the fermenter to have them too.

**Comment by DarkAngel22579** [comment]
Adding more crops didn't seem too difficult, so I ended up trying it myself. I can PR it if that's ok? I'm not super familiar with the PR process/etiquette.

**Comment by OneLemonyBoi** [comment]
Think it'd be fine to PR, just mention this issue in PR.
