### ISSUE TITLE
Mountains

### ISSUE THREAD

**Issue by Helkbird** [NillerMedDild/Enigmatica6#1638]
First off, Fantastic mod!  Most immersive Minecraft has, well, ever felt.  Just jumped on a few days ago with v. 6  The ambient sounds alone keep me going out for more.  Exploration is fun!  Please keep up the great work.  But, the mountains seem to have a basic, conical shape.  We've lost the crazy sky towers.  Not sure if it's linked with the rivers and biomes (which I don't want to lose) but...  Enh.  I wish I had a third arm to give another thumbs up for Enigmatica.

**Comment by NillerMedDild** [comment]
Thank you very much :D

It is linked to rivers and biomes, it's all TerraForged generation. I'm not sure there's anything we can do about the mountain shape unfortunately, though I too would like to see more diverse mountains.

**Comment by NillerMedDild** [comment]
@theboo Can probably answer better though, he set up our TerraForged configuration - Can the shape of mountains be tweaked? Less conical/gradual perhaps?

**Comment by Halfdeaf** [comment]
The conical mountains are only one of the shapes they come in. It seems to be the most common one but I've seen vast ridges and sharp cliffs as well. It would require some testing but I doubt we would drastic changes

**Comment by Helkbird** [comment]
Thank you both.  A small price to pay for all the others I'm reaping!  Cheers!  I'd rather keep Terraforged in a choice.  And I guess I credit the "stratification" of rock layers to this mod, too?  Very nice touch.

**Comment by Lyx2k** [comment]
TF does not have many options for mountains. You can change the global vertical height scale for everything, which makes everything more rough what I really like. Increase the weight and the vertical scale for hills and mountains is possible but 99% of all mountains looks still the same, some were only higher. I don't really know why this is the case. 

I would love to see more "crazy" mountains formations but I guess its not possible with TF configs.

**Comment by theboo** [comment]
I'll take a look at it!

**Comment by Seceroth** [comment]
Would love to see something like the Guiana Shield biome in default generation, but in Terraforged. Really missing that.

**Comment by Lyx2k** [comment]
> 
> 
> Would love to see something like the Guiana Shield biome in default generation, but in Terraforged. Really missing that.

I wonder if its possible to hook into TF API to block specific biomes to generate through TF. I love Guiana Shield Biome

**Comment by Halfdeaf** [comment]
> boosting erosion might help with that

Boosting erosion would not affect stone types. Erosion affects the top layer only. Possibly reducing erosion would leave more top layer up the mountains to make for a more interesting generation.

> I wonder if its possible to hook into TF API to block specific biomes to generate through TF. I love Guiana Shield Biome

That would not be possible with the way TF generates. The height map is generated before biomes are considered

**Comment by Lyx2k** [comment]
I thought maybe they provide some events with the heightmap and give options to intersect the heightmap with a second one. Or they provide the heightmap but u dont need to use it.

**Comment by boneskull** [comment]
@theboo did you ever figure out if erosion helped?  I have an "alps" biome which is just gentle, rolling hills.

**Comment by landretk** [comment]
Personally I like to drop the horizontal scale down, will give you some steeper slopes and helps keep terrain in view even on servers with view distance at 8-10. Just have to be careful not to drop it too low or you'll get lots of structures generating in the sides of cliffs.
