### ISSUE TITLE
Create - Refined Storage Network Receiver Crash

### ISSUE THREAD

**Issue by PipeWizard** [NillerMedDild/Enigmatica6#1640]
**Modpack version**
0.4.3

**Describe the bug**
The server immediately crashes when a Refined Storage Network Receiver is placed on a Create rotational complex and it attempts to move.  In this case, it was a mechanical bearing complex.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
https://pastebin.com/XJqtJ6zG

**Screenshots**
N/A

**Comment by PipeWizard** [comment]
I know this isn't something you guys handle but you'll know best where to send it and to who.

**Comment by NillerMedDild** [comment]
Thanks for the report! I think the solution would be not to use RS on contraptions :P Thoughts @Darkere?

**Comment by Darkere** [comment]
Yep. I think there is a way to blacklist things for create (might be a forge tag?).

I don't expect this to be fixed in the near future.
