### ISSUE TITLE
Astral Sorcery Starmetal ore unsmeltable, uncrushable, and uncuttable

### ISSUE THREAD

**Issue by HappyBigFun** [NillerMedDild/Enigmatica6#1644]
**Modpack version**
0.4.3

**Describe the bug**
Astral Sorcery starmetal ore can be obtained, but once obtained has no use and cannot be turned into starmetal ingots.

**Logs**
n/a

**Screenshots**
![image](https://user-images.githubusercontent.com/80448510/110751646-02475080-81f9-11eb-9946-799b19b451b4.png)

**Comment by NillerMedDild** [comment]
Fixed in https://github.com/NillerMedDild/Enigmatica6/pull/1544
