### ISSUE TITLE
IE quest for water wheel maybe shouldn't be a pre-req for squeezer/fermenter quest

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1645]
**Description**
The Squeezer and Fermenter quest has the waterwheel quest as a dependency, but it should probably just depend on blast furnace for steel.

**Comment by NillerMedDild** [comment]
If any Contributor could have a look at the mess I've made of the IE chapter that'd be great :P thoughts?

**Comment by MuteTiefling** [comment]
Will take a peek in a bit

**Comment by MuteTiefling** [comment]
Looks good, though I took the liberty of making the Improved Blast Furnace quest not microscopic.

I'm tempted to move the tools into the actual Tools quest section too and do a bit better coverage of the upgrades, similar to the PNC and Mek armor/tools stuff.

**Comment by NillerMedDild** [comment]
I think that'd be a good choice, they don't really fit in the IE chapter.

**Comment by MuteTiefling** [comment]
Alright. I'll work on that a little later tonight then.

**Comment by NillerMedDild** [comment]
> Looks good, though I took the liberty of making the Improved Blast Furnace quest not microscopic.

Cool, I wasn't sure whether that was a cool way to show an upgrade or not :P

**Comment by MuteTiefling** [comment]
Alright, tools has been expanded with the IE tools now.
