### ISSUE TITLE
Eidolon Enchanter, Achievement Issue

### ISSUE THREAD

**Issue by Elvarion** [NillerMedDild/Enigmatica6#1648]
**Modpack version**
0.4.3
**Describe the bug**
Enchanting with the Eidolon Enchanter unlocks every Apothesis Achievement related to enchanting items.
(Enchanted the Spear Hook Launcher with Unbreaking I)

**Screenshots**
https://gyazo.com/5214e39811b7c6bd437ec22ba1018a26

**Comment by NillerMedDild** [comment]
Duplicate of #756
