### ISSUE TITLE
Bee Smoker is unbreakable

### ISSUE THREAD

**Issue by 2xMJet** [NillerMedDild/Enigmatica6#1649]
**Modpack version**
0.4.3
**Describe the bug**
On Bee Smoker from Resourceful bees shown its durability, suppose it should lose it on use, but it isnt. 

**Logs**
Do i need to provide logs about this?

**Screenshots**
After about 100 uses its still 1000/1000
![image](https://user-images.githubusercontent.com/26283528/110791729-23fe1180-82a5-11eb-87b4-9f2d23780ded.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it :)

**Comment by Epic428** [comment]
This is in the current dev build with no changes made to the smoker. Are you in creative mode by chance? Otherwise, I have no clue why it wouldn't lose durability since it's a vanilla method


https://user-images.githubusercontent.com/291578/110848643-55aeb280-827c-11eb-9120-e5ee0f996fb8.mp4

**Comment by 2xMJet** [comment]
For sure i play survival. Thats how it looks form my perspective
https://user-images.githubusercontent.com/26283528/110851605-d8b72380-82e3-11eb-828c-388b822fe094.mp4

**Comment by 2xMJet** [comment]
Addition: by clicking on the ground i damaged smoker by one durability with smoke effect i've never seen in my playthrough before. But after that it still not getting damage at all.
Seems like durability damage happens only with smoke appearing, which not happened on my first video at all.
Another round of testing:

https://user-images.githubusercontent.com/26283528/110854446-91329680-82e7-11eb-9946-ddb9dbd0053b.mp4

**Comment by NillerMedDild** [comment]
Issue was concluded on the linked issue on their issue tracker, should be fixed when they release next update :)
