### ISSUE TITLE
Make common Honeycombs eatable

### ISSUE THREAD

**Issue by 2xMJet** [NillerMedDild/Enigmatica6#1650]
**Description**

Make minecraft:honeycomb eatable as all other modpack Honeycombs.

**Why would you like this added/changed?**

All Resourceful Bees combs is eatable, why common ones !tastiest! isnt? :)

**Screenshots if applicable.**

Dont need.

**Comment by NillerMedDild** [comment]
This isn't something we have control over, I suggest you suggest this to Resourceful Bees or vanilla :D
