### ISSUE TITLE
Explain how Habanero is obtained

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1652]
**Description**
In simple farming, the habanero is a rare drop from the pepper plant (0.1%? from looking at https://github.com/cweckerl/simplefarming/blob/1.15/src/main/resources/data/simplefarming/loot_tables/blocks/pepper_crop.json)  Maybe it could get added as a low chance output to botany pots/cloches/insolators when growing peppers?

**Comment by MuteTiefling** [comment]
I kinda left this one out of the crop unification intentionally. I thought it was more rewarding to have it only available from an actual farm under the sun.

**Comment by NillerMedDild** [comment]
I gave the Golden Habanero a JEI description to inform players it can drop from farming.

**Comment by NillerMedDild** [comment]
![Uploading billede.png…]()

**Comment by NillerMedDild** [comment]
I totally misunderstood this issue, will fix the desc ^^'

**Comment by NillerMedDild** [comment]
And in conclusion, we will not be adding the Habanero to cloche/pots etc, sorry.

**Comment by NillerMedDild** [comment]
It is 😄
