### ISSUE TITLE
Distiller tower crashes the gane

### ISSUE THREAD

**Issue by sauphle** [NillerMedDild/Enigmatica6#1653]
version 4.3

**Describe the bug**
When I put a bucket of **crude oil (from pneumaticCraft)** into the _* distiller tower (from immersive engineering)**_ It crashes the game.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![image](https://user-images.githubusercontent.com/80305735/110821254-80394500-8255-11eb-9c69-b307e5fff05b.png)
![crash report](https://user-images.githubusercontent.com/80305735/110822218-77953e80-8256-11eb-9f24-6203cb647892.PNG)
![details of reort](https://user-images.githubusercontent.com/80305735/110822224-79f79880-8256-11eb-8dfa-9c77b96406fe.PNG)

**Comment by Darkere** [comment]
immersive petrolium crashing. Needs an update to work with the new IE version I imagine.

**Comment by Darkere** [comment]
Fix was released 3h ago :D
