### ISSUE TITLE
More ways to get Driftwood

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1661]
**Description**
(Any log) > (Create Washing) > Driftwood

**Why would you like this added/changed?**
Driftwood has unique set of textures, and is one of the many building materials, but there are no way to get driftwood other than generating more ocean/river

**Comment by NillerMedDild** [comment]
Sure thing.

**Comment by Merlo17** [comment]
Adding these currently. Would log -> driftwood log suffice or do we need wood, planks, stripped etc.? They kinda seem redundant honestly

**Comment by NillerMedDild** [comment]
I agree, Log -> Driftwood log would be just fine

**Comment by Scorch-Mechanic** [comment]
My Industrial Foregoing Marine Fisher is outputting driftwood logs. It's not very many, but the method does exist.
