### ISSUE TITLE
Add low passive generation to Mekanism fusion

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1662]
Depending on how the config works, perhaps 100-150krf/t

**Comment by MuteTiefling** [comment]
Aww, went a bit too far? 

Should be able to dial in just about any value you want with a bit of testing.

**Comment by NillerMedDild** [comment]
Yeah it seems like it :( People are asking what's wrong on the Mekanism discord very frequently, so I think that means we need a slight adjustment. I still think the passive generation should be a fraction of the default though.

**Comment by NillerMedDild** [comment]
Would be good with a warning-style tooltip, but I also think we need to bring back passive generation.

**Comment by MuteTiefling** [comment]
PR ready for approval. I'll get the quest text re-re-modified in a bit too.
