### ISSUE TITLE
Baby RGBee killing itself

### ISSUE THREAD

**Issue by RjazzProductions** [NillerMedDild/Enigmatica6#1667]
Modpack version: 0.4.3, singleplayer world

When I'm breeding RGBees, I've noticed that the baby ones will rapidly start to lose health and eventually die. I think it's because they're suffocating in the ground, as I've noticed they only lose health when they're touching the ground from pollinating flowers or if I'm holding a flower to breed them. Makes it really hard to breed more RGBees, unless I want to spend all day chucking potions of healing on them or setting up some other form of rapid AoE health regen.

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please show your setup? :)

**Comment by RjazzProductions** [comment]
Sure thing! They'd always die from the grass blocks around the hive, but not because they'd exit the hive underneath and burn in the campfire or anything like that. I don't think it's the flowers either, because the adults can pollinate them perfectly fine without taking damage. Funnily enough, I'm pretty the small damage on my two adults came solely from them suffocating on the roof before I switched it to glass.

![2021-03-12_12 32 32](https://user-images.githubusercontent.com/42901594/110989361-04133000-832f-11eb-9d55-cdccbf1d3be3.png)
![2021-03-12_12 32 46](https://user-images.githubusercontent.com/42901594/110989368-08d7e400-832f-11eb-8193-7780453bfe5d.png)

**Comment by NillerMedDild** [comment]
I think you're right about the size, I'm gonna go ahead and set the size to 1, since we've seen this size issue a few times now.
