### ISSUE TITLE
PSA: Update Chisels & Bits yourself to fix the id swap between updates

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1668]
The issue with Chisels & Bits that caused Bits to change between updates has been resolved in C&B - manually updating Chisels & Bits and *only* Chisels & Bits will fix the issue without it breaking in the process. 
When the modpack updates to incoorporate the fix, the ids will change one last time if you have not manually updated Chisels & Bits. We're sorry for the immense frustration this has caused for some.

See this comment by the developer for details: https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/578#issuecomment-797318331

**Comment by Rodg88** [comment]
It might be worth posting this in the discord announcement channel
