### ISSUE TITLE
Powah tiering recipes accept any tiered mechanisms of the same type.

### ISSUE THREAD

**Issue by 2xMJet** [NillerMedDild/Enigmatica6#1671]
**Modpack version**

0.4.3

**Describe the bug**

Wanted to craft 4 hardened energizing rods from basic ones, and after first craft by moving items to Crafting grid, using JEI, fresh crafted hardened one moved to craft another hardened one.

After lil investigation i've discovered that upgrade recipes using any powah:energizing_rod instead or previous tier one.

Maybe that works for other tier upgrades.
UPD: it is.

**Logs**
Dont think its needed.

**Screenshots**
Thats how it moved:
![image](https://user-images.githubusercontent.com/26283528/110989326-4fb3f100-83a4-11eb-84af-d96806f74d3a.png)
Investigation results:
![image](https://user-images.githubusercontent.com/26283528/110989341-55a9d200-83a4-11eb-8b33-1f726614dc13.png)
Issue is present for Furnators too:
![image](https://user-images.githubusercontent.com/26283528/110990190-9229fd80-83a5-11eb-90e2-a4e25c807470.png)

**Comment by MuteTiefling** [comment]
This is intentional. 

You'll note that there are two recipes for each. One is a direct craft that doesn't require any 'tiering' and the other allows you to upgrade old machines/items to higher tiers by simply adding in the new components.

**Comment by 2xMJet** [comment]
> This is intentional.
> 
> You'll note that there are two recipes for each. One is a direct craft that doesn't require any 'tiering' and the other allows you to upgrade old machines/items to higher tiers by simply adding in the new components.

I mean you can craft lower tier, using higher tier and JEI auto-move can move higher tier mechanism to recraft, which potentially can cause resource loss.

**Comment by MuteTiefling** [comment]
It's also possible to accidentally use your one and only pink slime making a sticky piston. This is a risk when multiple inputs are accepted. 

The easy way to 'fix' this is to remove the upgrade path entirely.  But that means you may end up with a lot of useless old blocks later. 

The hard way involves a lot of manual recipe work...

**Comment by 2xMJet** [comment]
glad we understood eachother, but would suggest to add some entries in quests about that "thing" with upgrading then, for at least little fool-proof for this kinda errors :)
Since i think not all people will check for right mech, and you will need to explain it multiple times in the future.

**Comment by MuteTiefling** [comment]
Found a decent way to do this without getting crazy complicated.

**Comment by 2xMJet** [comment]
Thats what I like in enigmatica dev process :) You're cool, keep it up :)
