### ISSUE TITLE
Cannot craft crafting station using tetra axe

### ISSUE THREAD

**Issue by Anniebe11** [NillerMedDild/Enigmatica6#1675]
I am unable to craft the crafting station with a tetra axe.  The axe I am attempting to use has a stone axe head, stone butt, and spruce handle however I suspect the problem may apply to all tetra axes.  obviously this is not game breaking but it would be convenient if tetra axes worked.

Pack version is 0.4.3 and no alterations have been made to the pack

**Comment by NillerMedDild** [comment]
I'm afraid this isn't something we can do, crafting with tetra is hell :P
