### ISSUE TITLE
Game keeps crashing after equipping 2 sets of living armor

### ISSUE THREAD

**Issue by Caelie0** [NillerMedDild/Enigmatica6#1677]
**Modpack version**
0.4.3

**Describe the bug**
Game Crash after I equipped 2 sets of living armor. A normal living armor set on my main slot. And a upgraded set on my glamour armor slot. The server disconnects when I try to get back in. But my friends can get back into the same server.

**Logs**
https://pastebin.com/hxG6miNJ
https://pastebin.com/BZqYF52C

**Screenshots**

**Comment by NillerMedDild** [comment]
Thanks for the report. Do you happen to have another latest.log we can see? The ones you linked to are missing information as far as I can see.
