### ISSUE TITLE
Enhanced seed recipe is broken for 2 of them

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#168]
**Modpack version**
0.2.9

**Issue**
Fluix seed produces Pure Nether Quartz crystal in enrichment chamber, and Nether Quartz Seed makes Pure Fluix crystal.

https://i.imgur.com/DUYnmps.png
https://i.imgur.com/aLaWKal.png

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
That's embarrassing ^^' will be fixed in 0.2.10 this evening, most likely.
