### ISSUE TITLE
Tree Felling Demon from Occultist causes tickrate crashing

### ISSUE THREAD

**Issue by DrCuddless** [NillerMedDild/Enigmatica6#1680]
**Modpack version**
0.4.3

**Describe the bug**
After spawning an Occultist demon that handles tree felling and the cleaning up of said trees the server suffered massive tickrate issues and caused everything else to slow down when the chunk he was in was loaded, even crashing the server on multiple occasions.
After inspecting the spark log I discovered this and killed the demon which completely fixed the issue.

**Logs**
https://spark.lucko.me/LeqLDp4JXk

**Screenshots**
Not applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I've gone ahead and relayed the issue to the mod dev :)
