### ISSUE TITLE
mod are not working?

### ISSUE THREAD

**Issue by KaraLoverDJ** [NillerMedDild/Enigmatica6#1684]
somehow from 0.4.3 some are the mod are not here the search is not there not like 0.3.13 and the Biome are not here??

**Comment by florensie** [comment]
Yes?

**Comment by NillerMedDild** [comment]
Sounds like you've got a bad install, re-install :)

**Comment by Merlo17** [comment]
Are you looking for Biomes O Plenty? That got removed in 0.4

**Comment by KaraLoverDJ** [comment]
> Sounds like you've got a bad install, re-install :)

and I don't how you do it on minecraft??

**Comment by KaraLoverDJ** [comment]
> Are you looking for Biomes O Plenty? That got removed in 0.4

like back in 0.3.13 I did see all it

**Comment by NillerMedDild** [comment]
Ah now I understand. This is not an issue, we removed mods between 0.3 and 0.4. This was described in great detail in the change log.
