### ISSUE TITLE
Alfsteel AIOT can't break grass.

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#1687]
Enigmatica 6 0.4.3 (official server)

I have an Alfsteel AIOT with a variety of enchantments (see attached image) and it essentially treats grass (not grass block), tall grass, ferns, flowers, etc as bedrock and will not break them. Not sure if it's the tool itself or some sort of combo of the enchants that's causing the issue.

![image](https://user-images.githubusercontent.com/9061144/111044120-40688e00-840c-11eb-8136-62baf3b725e6.png)
![image](https://user-images.githubusercontent.com/9061144/111044147-524a3100-840c-11eb-817e-92f09a7a1d88.png)

**Comment by NillerMedDild** [comment]
The issue is Miner's Fervor: `You will mine very fast, but never instant`

**Comment by AdamNisbett** [comment]
From that description I would have thought instant would be slowed to slightly less than instant - not turned into unbreakable.

**Comment by NillerMedDild** [comment]
Grass can only be broken instantly.
