### ISSUE TITLE
Change Immersive Engineering Excavator quest

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1689]
**Description**
Excavator body uses what is written: 

- 6 Steel Scaffolding
- 16 Steel Sheetmetal
- 3 Radiator Block
- 9 Light Engineering Block
- 1 Redstone Engineering Block
- 4 Heavy Engineering Block

But Excavator can't function without the Wheel, which need:

- 9 Steel Block
- 20 Steel Scaffolding

Another (separate) issue I had, is that the Steel scaffolding blocks needed are not the normal variant, but is its "cage top" variant. I want it to be changed to its normal variant also, because you don't have to craft Scaffolding one more time for the quest to accept it.

**Comment by MuteTiefling** [comment]
Fixed in Dev
