### ISSUE TITLE
InstanceSync deosn't download ftb-chunks, ftb-teams, ftb-ranks and ftb-gui-library

### ISSUE THREAD

**Issue by brckts** [NillerMedDild/Enigmatica6#169]
**Modpack version**
0.2.9

**Issue**
Followed the server and client setup from the readme to update more easily. Neither on the server or in the client do these mods download.

I don't know how it works so I'm not sure but not having downloadUrls in minecraftinstance.json might have something to do with it

**Comment by Darkere** [comment]
The ftb mods are directly on github in the thirdparty mods folder.

**Comment by brckts** [comment]
oh true, my bad then !
