### ISSUE TITLE
Blacksmith's Delight seem to give nothing

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1690]
**Modpack version**
0.4.3

**Describe the bug**
Tetra Hammer Tier 2 and 3 rewards contain Blacksmith's Delights; However they don't seem to give you anything

**Comment by NillerMedDild** [comment]
Why did you close this? :)

**Comment by HaxtonSale1** [comment]
I confused it (gives weapons) with Miner's Delight (gives ores)

I don't know why I never noticed two new weapons in my inventory, but yeah
