### ISSUE TITLE
MoreVanillaLib Config changed 

### ISSUE THREAD

**Issue by MelanX** [NillerMedDild/Enigmatica6#1691]
**Description**
You really should look at the changed config as I already mentioned on discord here: https://discord.com/channels/195234321836146688/726178356143456287/820276274609651712
Messages content:
`For the next update: if you update the mods, look at the new config values of MoreVanillaLib. They changed a lot. Here you can see what happens if you update from 1.3.x to the new 1.4.0 version: <https://gist.github.com/MelanX/d0e2016daa93d5b903ed0691cb6214a4/revisions#diff-d69e221799c119f1bc60e64ab3047e6592a83d2912bf6b12d35d1272f703ab8f>
The chances for extra drops increase to 100%. I don't know if I should ping a mod for that or not. I report it just to prevent inflation 🙂 Because most of the users don't read changelogs 😄`

**Comment by NillerMedDild** [comment]
Thanks for making the issue, I did miss this changelog, I occasionally skip them for library mods :P
