### ISSUE TITLE
Garden cloche can't produce sugar cane as a crop?

### ISSUE THREAD

**Issue by stijnvcp** [NillerMedDild/Enigmatica6#1693]
**Modpack version**
4.01

**Description**
The IE Garden Cloche can't produce sugar cane as a crop.
Suggestion to add the ability for it to grow sugar cane.

**Why would you like this added/changed?**
Only makes sense it could grow sugar cane since the garden cloche can pretty much grow every other crop in the game.

**Comment by MuteTiefling** [comment]
Odd, yeah it should. I'll have a look in a bit.

**Comment by NillerMedDild** [comment]
It seems to be all the `cane_like` crops.

**Comment by MuteTiefling** [comment]
I feel like I had a reason for excluding that group. Perhaps I need to regroup them a bit...

**Comment by NillerMedDild** [comment]
I found the reason, I think I did it :P

**Comment by Merlo17** [comment]
#RogueNillerRegex?

**Comment by NillerMedDild** [comment]
Yeah It's fixed :P not Regex this time, just a mistake I think.
