### ISSUE TITLE
[Suggestion] recipes for legendary varients of infinity tools

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#1694]
**Description**
Crafting recipe for legendary varients of infinity tools in a nucleosynthesizer with any tool plus 2 (arbitrary amount) buckets of antimatter and power.

**Why would you like this added/changed?**
Would be a nice endgame challenge and a worthy reward for producing anti matter.
**Screenshots if applicable.**

**Comment by MuteTiefling** [comment]
Really like this idea. Only trouble is that I really doubt we'd be able to keep NBT, so enchants and things would be lost if they weren't removed first. Plenty of ways to do that, however.

**Comment by TemperedFool** [comment]
Is it possible to require that an unenchanted Infinity tool is used? That way there's no way they can lose a bunch of enchants in the process.

**Comment by NillerMedDild** [comment]
This will need a bit more work - The recipe isn't visible in JEI, and I wasn't able to make it show. We may need to add some JEI info about the recipe.

**Comment by MuteTiefling** [comment]
Odd, it was showing for me as a separate item in jei.
