### ISSUE TITLE
Mekanism UU matter 

### ISSUE THREAD

**Issue by CletusMAngo** [NillerMedDild/Enigmatica6#1696]
https://www.curseforge.com/minecraft/mc-mods/mekanism-matter

**Mod description**
This mod adds Ic2 style UU matter to mekanism thats very different from the original Mekanism Antimatter

**Why would you like the mod added?**
This mod would be really great for E6 because it allows you to replicate things that you cant replicate with the existing Mekanism antimatter mechanics and i think if it can be gated it would really fit into the pack 

Another suggestion for it to be gated: maybe you guys could use Mimicube cream from Alexs mobs to actually craft the UU matter? i think that would make sense

**Comment by NillerMedDild** [comment]
We'll think about it :)

**Comment by MuteTiefling** [comment]
Personally, I'd prefer simply making better use of the new antimatter mechanic as per Robert's suggestion. I feel we could potentially put a lot of interesting things there as a place for people to dump their power and uranium.

**Comment by CletusMAngo** [comment]
> Personally, I'd prefer simply making better use of the new antimatter mechanic as per Robert's suggestion. I feel we could potentially put a lot of interesting things there as a place for people to dump their power and uranium.

I still think this mod can coexist along with the normal Meka recipes like maybe you guys can make it so the Meka antimatter can duplicate rarer things and the UU matter cheaper things like Machine casing,PCBs etc etc

**Comment by NillerMedDild** [comment]
I don't think we need this :)
