### ISSUE TITLE
Unbalanced Botania Orechid (oregen)

### ISSUE THREAD

**Issue by MRT-CO** [NillerMedDild/Enigmatica6#1698]
Botania orechid gen it's not balanced, using 5 orechid flowers, in 4-5 hours waiting time, i've got next materials (+300 iron, i've done a small withdraw).

![image](https://user-images.githubusercontent.com/39351347/111123929-95c1ae00-8578-11eb-8cb6-57ac7addedf3.png)

I mean... 1093 coal chunks and 5 uranium it's not really a good thing.

**Comment by NillerMedDild** [comment]
I'm afraid there's nothing we can do about that :/
