### ISSUE TITLE
[Mod update request] Engineer's Decor Ladder climbing issue

### ISSUE THREAD

**Issue by stfwi** [NillerMedDild/Enigmatica6#1699]
**Modpack version**
(affects E6 with Forge >=36.0.45)

**Describe the bug**
Hi NillerMedDild, can you include `engineersdecor-1.16.4-1.1.9` in the next pack version? I fixed a bug in there where climbing ladders broke as of Forge 36.0.45 - which also affects E6. The mod is already pushed to Curse. Cheers, wile.

**Logs**
-/-

**Screenshots**
-/-

**Comment by NillerMedDild** [comment]
Of course, thanks for the the heads up :) We usually update all mods if possible.
