### ISSUE TITLE
Suggestion: Masonry

### ISSUE THREAD

**Issue by ZilgornZeypher** [NillerMedDild/Enigmatica6#17]
This one adds on a bunch more decorative blocks craftable from the stonecutter.
[Masonry](https://www.curseforge.com/minecraft/mc-mods/masonry)

Engineers Decor to add as I saw in another post your adding Immersive Engineering. (Just noticed this is already in the pack)
[Engineers Decore](https://www.curseforge.com/minecraft/mc-mods/engineers-decor)

**Comment by NillerMedDild** [comment]
I'll have a look, thanks for the suggestion.
