### ISSUE TITLE
[BUG]1k drive parts (AE2) can only be crafted with charged

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#170]
**Modpack version**
0.2.9

**Issue**
1k drive part only accepts charges certus to make it. I believe in standard AE2 you can use pure certus and regular certus to make them :)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Shindur** [comment]
Same thing is happening to the 1k fluid drive part as well :)

**Comment by NillerMedDild** [comment]
Thanks for letting me know, guess my recipe replacements were a bit too efficient :P
