### ISSUE TITLE
Any non TF world only spawns with stone in their worldgen

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica6#1701]
**Modpack version**
0.4.3

**Describe the bug**
Obviously a side effect of us killing every stone type to put it back in with TF strata. Is there any way we can prevent this from happening in non TF worlds?

**Comment by NillerMedDild** [comment]
There's no good way to do this sadly, the only way I see is to generate prior to TF strata gen, so TF would override but other worldtypes would have the generation we specify. That would be baaaad for worldgen performance in TF worlds though.

**Comment by NillerMedDild** [comment]
Yeah there's nothing that we can do without messing up TF :(
