### ISSUE TITLE
Multiservo Press Missing Recipes for 3x3 Packing Die

### ISSUE THREAD

**Issue by Outlaw-Star** [NillerMedDild/Enigmatica6#1702]
E6 0.4.3

**Describe the bug**
 The multiservo press is missing recipes for the 3x3 packing die: osmium ingot->Block of Osmium, Aluminum Ingot-> Block of Aluminum, Uranium Ingot -> Block of Uranium

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
