### ISSUE TITLE
Hole Filler Mod

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1704]
https://www.curseforge.com/minecraft/mc-mods/hole-filler-mod

**Comment by Merlo17** [comment]
quickly hide this before buuz makes a that's what she said joke

**Comment by r-mc2** [comment]
Ooo, is this finally out of initial dev? This looked amazing from the teaser like 6-8 weeks back.

**Comment by MuteTiefling** [comment]
black magic, I say
