### ISSUE TITLE
[0.4.3] Autocrafting Bacon Crash

### ISSUE THREAD

**Issue by Scooke96** [NillerMedDild/Enigmatica6#1707]
Server crashes when using a RFTools Crafter and RS crafter to craft bacon

https://pastebin.com/X1yufh6V

**Comment by Scooke96** [comment]
![image](https://user-images.githubusercontent.com/36442282/111215941-aa7b6180-85cb-11eb-8670-0e08a6706be1.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. I've removed that bacon recipe, so this has sorta been fixed :P
