### ISSUE TITLE
[0.4.3] Pneumaticraft drones

### ISSUE THREAD

**Issue by LoneWolf137** [NillerMedDild/Enigmatica6#1708]
0.4.3

when you damage a pneumaticraft drone directly, the game crashes. tested it in a single player world. No idea of how it is on servers. when you restart the game the drone took the damage and knockback. i did manage to hit the rotors of a drone and everything was fine, though i was breaking a torch in the process. lava and cacti work normally

[crash-2021-03-15_21.26.59-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6144302/crash-2021-03-15_21.26.59-client.txt)

**Comment by NillerMedDild** [comment]
Thanks for the report, this has been fixed by the mod dev and should be released soonish :)
https://github.com/TeamPneumatic/pnc-repressurized/issues/760
