### ISSUE TITLE
Cow in a Jar does not work 'Cooking for Blockheads Mod'

### ISSUE THREAD

**Issue by JeremyTrammer** [NillerMedDild/Enigmatica6#1710]
Version 0.4.3

**Description**
Cow in a Jar from Cooking for Blockheads mod does not fill with milk, or add to the kitchen multiblock to be used.

![image](https://user-images.githubusercontent.com/80727272/111239152-95500400-85c6-11eb-9959-2551895ae399.png)

**Comment by Elvarion** [comment]
The Jar does fill with Milk over time.
It is possible to craft recipes that uses Buckets & Bottles of Milk that have been placed in the Kitchen Multiblock.

It is however **not** possible to craft Milk Buckets/Bottles from Empty Buckets or Empy Bottles via the Cooking Table.

**Comment by NillerMedDild** [comment]
> The Jar does fill with Milk over time.
> It is possible to craft recipes that uses Buckets & Bottles of Milk that have been placed in the Kitchen Multiblock.
>
> It is however not possible to craft Milk Buckets/Bottles from Empty Buckets or Empy Bottles via the Cooking Table.

Working as intended :)
In the next update you will however also be able to pipe out of it, that will allow you to make buckets.
