### ISSUE TITLE
Abyssal depths

### ISSUE THREAD

**Issue by Scapulaunit12** [NillerMedDild/Enigmatica6#1711]
https://www.curseforge.com/minecraft/mc-mods/abyssal-depths

A cool mod that makes the ocean a bit more interesting by adding swordfish and a new hostile mob called the sea serpent. 

If I am gonna be honest the main selling point of this mod is the sea serpent as it adds a great creature that makes exploring underwater a bit more interesting as you have to watch out for something. It also leaps out of the water when attacking which is neat.

![abyssal depths](https://user-images.githubusercontent.com/56084328/111243494-90478080-85d7-11eb-84da-e38ed9f33d25.png)

**Comment by NillerMedDild** [comment]
I don't think this is something we need tbh, and the amount of entities it seems to spawn is troubling :P Also, Sea Serpents are probably my least liked hostile creatures, as they potentially ruin a world if you spawn on an island.
