### ISSUE TITLE
[Enigmatica6] Door opening bug

### ISSUE THREAD

**Issue by Zskhay** [NillerMedDild/Enigmatica6#1712]
**Enigmatica6**

I'm having problems with door sensor to work properly. The issue I encounter with door sensor from the mod Gauges and Switches, where the sensor only opens half of the door(s) and sometimes doesn't work at all. Anyone know any fixes?
![image](https://user-images.githubusercontent.com/80734112/111251047-78263000-85dc-11eb-9af2-117c576c45c6.png)

**Comment by NillerMedDild** [comment]
Thanks for the report.
Does this also happen with vanilla doors?

**Comment by Zskhay** [comment]
> Thanks for the report.
> Does this also happen with vanilla doors?

**Comment by Zskhay** [comment]
yes, this happens to all doors vanilla and modded  with oe without the sensor.

**Comment by NillerMedDild** [comment]
I can't reproduce this I'm afraid.

**Comment by Zskhay** [comment]
would you like to join the world I'm playing on to see what's going on?

**Comment by NillerMedDild** [comment]
I see you're using multiple door sensors, and they're not placed correctly. Have a look at their tooltip :)
