### ISSUE TITLE
Use for Resourceful Beeswax

### ISSUE THREAD

**Issue by Mizque** [NillerMedDild/Enigmatica6#1713]
Currently there is no use later on for the massive amount of beeswax produced by resourceful bees (yes, I know about candles but their applications are very limited in scope).  With that said, perhaps adding them as a tallow equivalent fuel (smelts one item) would be a good thing, making it still useful, to an extent, allow some decent smelting precision prior to using redstone furnaces, and make it so people aren't stockpiling thousands of the things or void dumping them.

**Comment by NillerMedDild** [comment]
I think that's a good idea, perhaps you could suggest it to Resourceful Bees? :) We don't really have control over that.

**Comment by Merlo17** [comment]
We could add it to candle recipes I guess?

**Comment by 2xMJet** [comment]
they arent there already?
![image](https://user-images.githubusercontent.com/26283528/111273299-3b9f1680-8666-11eb-8667-fef67377582d.png)

**Comment by Merlo17** [comment]
Shhhh you saw nothing

**Comment by NillerMedDild** [comment]
Rid suggested making Lubricant of it through Thermal processing or the like, I quite like that idea.

**Comment by Mizque** [comment]
That'd be fine as well, the big problem is after making a few candles you just have more and more and more beeswax, even compressing it just, isn't enough as you endlessly make it in high ammounts by just, processing combs/comb blocks
