### ISSUE TITLE
Exploding Undergarden Mobs

### ISSUE THREAD

**Issue by Tapirgott** [NillerMedDild/Enigmatica6#1714]
I had the Problem that parts of the Undergarden were generated around a undergarden Portal and the Mobs were exploding in the Overworld instead of a byg:twilight valley biome. deleting the chunks and reloading with mcaseselector did generate them normaly.

looks like another problem when you port a 3.0 World to 4

**Comment by NillerMedDild** [comment]
So... mobs went through your Undergarden portal and blew up in the Overworld?

**Comment by Tapirgott** [comment]
No, the whole biome is not an - byg:dense forest -  as it should be but an Undergarden:dense forest biome and the undergarden mobs are spawning like normal hostile mobs and they explode….

In singleplayer the same biome is a normal as ByG:Twilight forest 

Von: Niels Pilgaard Grøndahl
Gesendet: Dienstag, 16. März 2021 20:10
An: NillerMedDild/Enigmatica6
Cc: Tapirgott; Author
Betreff: Re: [NillerMedDild/Enigmatica6] Exploding Undergarden Mobs (#1714)

So... mobs went through your Undergarden portal and blew up in the Overworld?

**Comment by Merlo17** [comment]
Biomes ID shifting maybe?

**Comment by Tapirgott** [comment]
Gesendet von Mail für Windows 10

Von: Niels Pilgaard Grøndahl
Gesendet: Dienstag, 16. März 2021 20:10
An: NillerMedDild/Enigmatica6
Cc: Tapirgott; Author
Betreff: Re: [NillerMedDild/Enigmatica6] Exploding Undergarden Mobs (#1714)

So... mobs went through your Undergarden portal and blew up in the Overworld?

**Comment by theboo** [comment]
Yup sounds like a biome ID shift happened when you updated from 0.3.x to 0.4.x ... This is part of why it was recommended to start with a fresh world, not much we can do about this.

**Comment by Tapirgott** [comment]
I fixed it by changing the existing biome with the mcaselector tool, thanks you very much for your time and your fantastic work with Enigmatica 6
