### ISSUE TITLE
Astral - Starlight Infuser not showing depleted pool

### ISSUE THREAD

**Issue by Helkbird** [NillerMedDild/Enigmatica6#1716]
Enig 6 0.4.1 - Astral appropriate

Light buggy thing, only a bit of a hassle.  But when the liquid starlight pools around the infuser deplete, center pools do not show depletion. The end pools (in the row of three) show an obvious dip.  Many blessings and may your mod persevere through world domination!  Muwhahaha!  (And I need to get with servers, see if they can't throw out a little Enig update, too :) )

**Comment by OneLemonyBoi** [comment]
That’s just how fluids work, it just looks like that. AFAIK you can’t do anything about that.

**Comment by Helkbird** [comment]
Seems it didn't in Sergecraft 2.  'Course my memory isn't the best these days.  Kinda came into this report half-hearted and completely ready to just work with it.  ;)

**Comment by TemperedFool** [comment]
It's subtle, but the lines give away the difference:

Full: ![image](https://user-images.githubusercontent.com/13169307/111334670-24523000-864a-11eb-9df8-3ce6eb1dc6a0.png)

Empty: 
![image](https://user-images.githubusercontent.com/13169307/111334743-3502a600-864a-11eb-9d78-cd9e8d5b5594.png)
