### ISSUE TITLE
Rebalance Mob Weights for Alexs Mobs in The Nether

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1717]
**Description**
> I think Alex's might need to be rebalanced again. I've not encountered a single crimson mosquito in three crimson biomes so far yet the basalt delta is crawling with straddlers.
Reported by Thiana through Discord

**Why would you like this added/changed?**
General balance / quality I guess

**Comment by Mendanbar** [comment]
Are crimson mosquitos supposed to spawn naturally?  I've always just brought flys to the nether to mutate them. 🤷

**Comment by NillerMedDild** [comment]
They are yes :P I just nuked them.

**Comment by Mendanbar** [comment]
Ah, i see 😂

**Comment by NillerMedDild** [comment]
A crimson dude spawned pretty quickly, but only 1, I'm happy :P
