### ISSUE TITLE
Fusion Reactor not generating any energy

### ISSUE THREAD

**Issue by ShadowMagnus000** [NillerMedDild/Enigmatica6#1718]
**Modpack version**
Enigmatica 6 ver 4.2

**Describe the bug**
Mekanism Fusion Reactor is not producing any power even on full stable reaction and max rate. Have attempted all ways of troubleshooting the multiblock and even re-built it with the same outcome. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22862080/111393742-bcbed380-868f-11eb-90ec-8369098e93e8.png)

**Comment by anivlys** [comment]
This looked related to #1662 with no passive generation currently and will be added in a later version.

**Comment by telemenar** [comment]
Yeah the pack’s intent is that the reactor must be water cooled. In the next release it will get some passive generation but very nerfed from Mekanism defaults.
