### ISSUE TITLE
Questing Order - Storage

### ISSUE THREAD

**Issue by xATL4S** [NillerMedDild/Enigmatica6#1719]
I posted this in discord - so will be a direct copy and paste.

Im going through the "storage" section of the modpack and i dont know if this was an oversight or something but under the pretty pipes (bottom of the page) the "low crafting module" comes after the quest "crafting terminal" , this quest in my opinion should be moved to after "low crafting module" as that acts as a lead into the crafting terminal. 

As stated above I believe this to be an oversight but I may be wrong on this, to me it just seems more logical sequence of events. 

A proposed fix to this would be to place "low crafting module" then "crafting Terminal" instead of the current "Crafting Terminal" then "low crafting module"

**Comment by telemenar** [comment]
Though you do need to craft one to make the crafting terminal I think the quest afterwards is trying to walk you through how to use the crafting module for auto-crafting. Which is something that you would usually do after having something like the crafting terminal.

**Comment by NillerMedDild** [comment]
Sounds intended to me :)
