### ISSUE TITLE
[Mod Suggestion] Chem lib

### ISSUE THREAD

**Issue by set92** [NillerMedDild/Enigmatica6#172]
I was playing a modpack about progression and I saw https://www.curseforge.com/minecraft/mc-mods/chemlib. And I thought of it for E6 to have more flavour or choices in tech, but not sure if it fits or you have other direction, more magic or idk.

I couldn't try it, but in the other modpack (brass(1.15) ) there was a tech mod for early (create), for mid (immersive engineering), and for late (chem lib). 

And I thought that having Chem lib would help to have more choices, since I liked creating ore processing from Mekanism, I thought chem lib would provide more ways to play with liquids. But I haven't play it so not sure how OP it is, I saw that you can transform coal to diamonds, but I suppose that is in late game, although I suppose earlier than mekanism.

------------------------------------------------

To not create other issues and fill up too much, I also had a couple observations.
-  Personally I added [MekanismAdditions](https://www.curseforge.com/minecraft/mc-mods/mekanism-additions), but only to have the plastic stairs and stuff, and have more things in which to use the HDPE Pellets, because if not they are only useful for some late late machines in mekanism.
- In all versions I tend to modify "quark-common.toml" to enable sort button in inventory, and I don't know why is false by default, I think is a cool feature to have.
- Extra one I thought right now. For arc furnace in immersive engineering you need graphice electrodes for which you need or crafting them at 50% durability, or find the schematic in some village. But this is like too random, or if you don't explore much you will never find it, not sure if you thought on leaving like this, or is an oversight and could be better to give the schematic by default, or have some quest/advancement to get it for sure.
- In brass they also had ProductiveBees and they [told him](https://www.reddit.com/r/feedthebeast/comments/iasec6/brass_the_1152_progression_modpack_has_been/g1r10m7/) it was better [another one](https://www.curseforge.com/minecraft/mc-mods/resourceful-bees) because it was more customizable.

**Comment by NillerMedDild** [comment]
Thanks for the suggestions!

* I've checked out Chem Lib and didn't really like it tbh.
* I would like to avoid adding mods that add a large amount of stairs, slabs and sorta generic looking blocks, as I'm hoping for Carpenter's Block type mod so the RAM overhead isn't insane.
* I think most people just use middle-click for sorting, a bit easier/faster than a button imo.
* You can trade with the Engineer villager to get it I believe, far less random than loot. I do know it's on the annoying side though, so maybe.
* We will make the switch at some point, but not before we're ready to customize bees ourselves.
