### ISSUE TITLE
[0.4.3] Multiservo Press, Gearworking Die and Gear Mold

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1722]
**Modpack version**
0.4.3

**Describe the bug**
Gear Mold (IE) can't go into Multiservo press, and Gearworking Die (TE) doesn't appear on JEI, though it has a recipe
Given how Gearworking die is not on JEI and how TE press molds can be inserted into Multiservo press, I expected the Gear Mold would be able to be used in the Multiservo Press also

**Screenshots**
![2021-03-17_11 41 50](https://user-images.githubusercontent.com/13237198/111406523-cf7beb80-8715-11eb-9bb2-52f75e899dcf.png)

**Comment by telemenar** [comment]
Oh, I bet this is hidden by the same script that hides the native to thermal gears to try to expose only the gears from EE
