### ISSUE TITLE
Cobblestones from Create can't be smelted back to stone variants

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1725]
**Description**
`create:*_cobblestone` blocks (eg dolomote, gabbro, and their vanilla versions too like granite) don't have any smelting recipes, and could be good to be able to smelt them to the plain stone variants.

**Why would you like this added/changed?**
It would make sense. lol

Otherwise I can add them to my stonecutter script to turn them into the other variants, but that bypasses the need for a silky cobblegen to bulk produce them.

**Comment by Merlo17** [comment]
just encountered this too lol, a smelting recipe is definetly needed
