### ISSUE TITLE
[Mod Suggestion] Advanced Peripherals

### ISSUE THREAD

**Issue by vtvz** [NillerMedDild/Enigmatica6#1728]
**CurseForge Link**

https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals

**Mod description**
Good replacement for "Storage for ComputerCraft" with additional features like Player Detector, Envrionment Detector and ability to work with chat

**Why would you like the mod added?**

It's interesting to automate some things with chat box and. Envrionment Detector allows to show clocks and predict moon eclipse in Astral

**Comment by Thiana** [comment]
For the purposes of comparison, the APIs each provides for RS:

- https://github.com/uecasm/rs4cc/wiki/Refined-Storage
- https://docs.srendi.de/Peripherals/rsbridge/

Advanced Peripherals has less features for RS integration but it covers most of the same use cases. Most of the deficiency is related to fluid handling unless the import/export item functions will also handle fluids properly.

**Comment by Seniorendi** [comment]
I added a lot of features in the last 20 days. 
We have a lot of new turtles, new peripheral blocks and pocket computers.
The Mod is stable, and I will add more features in the future.

**Comment by NillerMedDild** [comment]
Impressive 😄 I wonder, is Advanced Peripherals compatible with `Storage4ComputerCraft`? I'd like to have both temporarily as to not mess up existing programs.

**Comment by Seniorendi** [comment]
It will not mess up with Storage4ComputerCraft, everyone can decide which mod they want to use.
