### ISSUE TITLE
Basic Logistical Sorters does not send items into Storage Drawers

### ISSUE THREAD

**Issue by new-3** [NillerMedDild/Enigmatica6#173]
**Modpack version**
0.2.9

**Issue**
Basic Logistical Sorters(Mekanism) don't send items into Drawers(Storage Drawers)
1. BLS doesn't send items from Mek machines to Drawers
2. BLS doesn't send items from vanilla chest to Drawers
3. BLS DOES send items from Drawers to vanilla chest
4. If Drawer is attached into Mek machines and auto-eject is enabled, items are sent.

![2020-08-19_17 29 20](https://user-images.githubusercontent.com/28271599/90611638-f76ba500-e241-11ea-964a-13a232544781.png)
🔼this does not work
![2020-08-19_17 30 04](https://user-images.githubusercontent.com/28271599/90611661-fcc8ef80-e241-11ea-8110-8b59cfd5f9cb.png)
🔼opposite works

**Logs**
There is no logs about this.

**Comment by new3MC** [comment]
https://github.com/jaquadro/StorageDrawers/issues/811
It seems to be problem of Storage Drawers mod

**Comment by Shindur** [comment]
@new3MC Have you tried it where an item was in a drawer already and then sending from chest to drawer?

**Comment by new-3** [comment]
https://github.com/jaquadro/StorageDrawers/pull/881
It have been fixed on latest version of Storager Drawers :)
