### ISSUE TITLE
[0.4.3: No Mutation/Flower info for Resourceful Bees

### ISSUE THREAD

**Issue by Mizque** [NillerMedDild/Enigmatica6#1732]
**Modpack version** - 0.4.3

**Describe the bug**
JEI does not show Mutation or Flower info for bees, attatched is all JEI will provide on some bees, which is the 'right click' option for the Kitten bee, other bees do allow you to see what they breed with and what that produces, but no 'this mutates this' or 'this needs this to work' info is listed
-edit- Added additional screenshot with info from a bee that can breed to show what's all available

**Screenshots**
![2021-03-17_23 54 51](https://user-images.githubusercontent.com/56565719/111575390-42b84880-877c-11eb-988c-b5da7d294878.png)
![2021-03-17_23 55 11](https://user-images.githubusercontent.com/56565719/111575395-451aa280-877c-11eb-9be4-ef400313dcd4.png)

**Comment by NillerMedDild** [comment]
Kitten bee? We don't add that :P
Anywho, this is fixed in the next release, #1424
