### ISSUE TITLE
[0.4.3] Cloche doesn't have randomised outputs?

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1734]
**Modpack version**
0.4.3
**Describe the bug**
It might just be a feature that doesn't exist, but there doesn't seem to be any randomness for the cloche output for recipes that normally have low chance secondary outputs. Eg potatoes produce 3 potatoes and 1 poison potato every cycle, instead of 2+chance of 1 bonus, and a rare poisonous potato.

**Comment by Rodg88** [comment]
Just tested a phytogenic insolator too, and potatoes are giving a poisonous potato each cycle, sometimes two, with no fertilizer. I'm guessing 'additional chance 10%' in that case means 10% chance of a 2nd one on top of the base.

**Comment by NillerMedDild** [comment]
> Just tested a phytogenic insolator too, and potatoes are giving a poisonous potato each cycle, sometimes two, with no fertilizer. I'm guessing 'additional chance 10%' in that case means 10% chance of a 2nd one on top of the base.

I think you're right, I'm seeing the same thing.

**Comment by MuteTiefling** [comment]
Yeah, I think I might have them at 1.10 chance instead of 0.10... Gonna have to go take a look in a bit

**Comment by NillerMedDild** [comment]
It doesn't look like the Cloche supports chance based secondaries, at least not based on their own JSONs

**Comment by MuteTiefling** [comment]
Removed the poison potatoes from the cloche entirely and greatly reduced their rate in the insolator.
