### ISSUE TITLE
A way to make more Faint Amaranth

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1736]
**Description**
Easy recipe: on Starlight Crafting Table, (Any flower + 4 Glowstone dust surrounding it) = Faint Amaranth
Hard alternative recipe: same as Easy, but 8 glowstone dusts instead

**Why would you like this added/changed?**
It's a pretty flower! That's all.

**Comment by MuteTiefling** [comment]
I could get behind a recipe that combines BYG Amaranth with glowstone to make more of these. 

The trouble is breaking these is affected by fortune, and even Fortune III yields about 8.5 glowstone per flower on average.

Maybe a block transmutation with a glowstone bee would be more appropriate to avoid a simple crafting loop.

**Comment by Trostmm** [comment]
How about using a bucket of liquid starlight for it instead?
