### ISSUE TITLE
[Suggestion] Iron Shulker Boxes (or Metal Barrels)

### ISSUE THREAD

**Issue by telemenar** [NillerMedDild/Enigmatica6#1738]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/iron-shulker-boxes
OR
https://www.curseforge.com/minecraft/mc-mods/metal-barrels

**Mod description**
Adds tiered Shulker Boxes or tiered Barrels in the same ways as as the Iron Chest Mod mod does for chests

**Why would you like the mod added?**
I mainly was looking for anything that provided larger than vanilla storage in whole block form for decorative reasons. (Attaching external storages to diamond chests is ugly.) Currently the only option of something like a barrel or shulker above vanilla size is the labeled crate. But that breaks inventory tweaks, no sorting, etc. 

We used to have the crates from Quantum Storage but those are gone. Open to other ideas as well. Mainly any interested in anything that has 54 (or more) slots in a single whole block.

**Comment by telemenar** [comment]
I thought about proposing Iron Barrels instead but that is from another author that doesn’t seem to be as active in maintenance.

**Comment by OneLemonyBoi** [comment]
> I thought about proposing Iron Barrels instead but that is from another author that doesn’t seem to be as active in maintenance.

Tfarcenim's?

**Comment by OneLemonyBoi** [comment]
If so, its just that it has literally no issue on the Github page

**Comment by telemenar** [comment]
I looked at this without spending much time: https://www.curseforge.com/minecraft/mc-mods/metal-barrels

Noticed the complaints about 1.16.5 compat in the comments and the no update since September and decided iron shulkers was an easier recommendation. But I’d be happy with either.

**Comment by boneskull** [comment]
I'm missing Iron Barrels in particular. You know the tip about how barrels are basically better than chests? That's why 😀

**Comment by NillerMedDild** [comment]
I don't think we need this tbh.
