### ISSUE TITLE
Waystone Naming UI

### ISSUE THREAD

**Issue by Stereo528** [NillerMedDild/Enigmatica6#174]
**Modpack version**
2.10

**Issue**
Waystone Naming UI has the "Enter Waystone Name:" and "Inventory" text to the left of the screen as if it was an inventory like that of a chest.
(Waytstone)
![image](https://user-images.githubusercontent.com/52116771/90669939-a8a51780-e20f-11ea-8289-45754e5709bf.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
