### ISSUE TITLE
[Enigmatica 6] Crafting Tweaks and Sophisticated Backpacks

### ISSUE THREAD

**Issue by zarkat** [NillerMedDild/Enigmatica6#1740]
**Modpack version**

0.4.3

**Describe the bug**

I was crafting with a diamond sophisticated backpack, had the majority of crafting ingredients inside the backpack and the last ingredient (lava bucket) was inside my personal inventory, I pressed tab to refill the crafting recipe and my game proceeded to freeze for about a minute, save progress and crash.

**Logs**

https://pastebin.com/d8HdNScx

**Screenshots**
none

**Comment by NillerMedDild** [comment]
Thanks for the report, I have relayed it here: https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/92
