### ISSUE TITLE
Chiseled

### ISSUE THREAD

**Issue by Scapulaunit12** [NillerMedDild/Enigmatica6#1741]
https://www.curseforge.com/minecraft/mc-mods/chiseled

Chiseled is a WIP port of the chisel mod for 1.16.5. It so far only includes stone variations and the factory and science blocks

While this mod is still WIP it already adds a nice variety of existing blocks and the ever so loved factory blocks which I feel like is enough to justify it being added in the pack and if not now at least in the foreseeable future.

![image](https://user-images.githubusercontent.com/56084328/111846510-5dee9980-88dd-11eb-9cd0-eb86cb6e654d.png)
![image](https://user-images.githubusercontent.com/56084328/111846518-634be400-88dd-11eb-8072-50ff253533fe.png)

**Comment by NillerMedDild** [comment]
We'll consider it, I'm a against adding it because it's almost an exact copy of Chisel, which is being ported afaik.

**Comment by NillerMedDild** [comment]
It's gonna be a no, it seems a tad unstable, and I'd rather wait out for the original Chisel mod. 
If Chiseled at some point obtains written permission from the maintainer or Chisel I will reconsider.
