### ISSUE TITLE
[0.4.3] TemptGoal Crash on Load From Simple Farming

### ISSUE THREAD

**Issue by Shamadruu** [NillerMedDild/Enigmatica6#1742]
**Modpack version**
Engimatica 6   0.4.3
**Describe the bug**
TemptGoal crash on load (repeatedly) after planting Simple Farming crops. Rectified by removing Simple Farming. Was able to safely readd Simple Farming after loading the world once without it.

**Logs**
https://pastebin.com/B2tCJvJh

**Comment by Merlo17** [comment]
Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/1606, but thanks for reporting ^^
