### ISSUE TITLE
[0.4.3] Server crash as soon as anybody joins the server

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#1744]
**Modpack version**
0.4.3

**Describe the bug**
As soon as anybody joins the server, it crashes. Something involving ftb ranks and computercraft? kinda weird. Not sure how to fix that one :)

**Logs**
https://gist.github.com/jinkhya/94dd90e7febaa4d1da1480d7e46753c0

**Comment by Darkere** [comment]
try redownloading the computercraft jar.
