### ISSUE TITLE
[E6/dev] Rabbits

### ISSUE THREAD

**Issue by Thiana** [NillerMedDild/Enigmatica6#1748]
Between the rattlesnakes and the roadrunners, it appears that rabbits have no or extremely low chance to spawn in deserts. I've gone through 2 vanilla deserts and 4 more BYG variants without finding a single one. Thanks.

**Comment by NillerMedDild** [comment]
You mean vanilla rabbits right?

**Comment by Thiana** [comment]
Yes.

**Comment by NillerMedDild** [comment]
Lowered roadrunner/rattlesnake spawn weight a bit, hope it helps.

**Comment by Thiana** [comment]
Thanks :)

**Comment by NillerMedDild** [comment]
Sure thing. It'd be nice if you report back with findings :)

**Comment by Thiana** [comment]
Reloading with changes now :) I want rabbits for my garden.

**Comment by Thiana** [comment]
Ok, 2nd new desert and I found my rabbits :) The changes have reduced the rattlesnakes significantly though they are quite common. The roadrunners are still very common and now we have flies showing up occasionally.

Thank you for the fix :)
