### ISSUE TITLE
Stripped Logs 

### ISSUE THREAD

**Issue by hdn6371** [NillerMedDild/Enigmatica6#175]
**Modpack version**
2.10

**Issue**
I was trying to make stripped logs using a axe and the appropriate log. But instead of giving me the stripped version it gave me ta Valhalla post instead.

https://user-images.githubusercontent.com/69807244/90670504-e8243180-e218-11ea-825c-9af0990dac67.png
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
I'll get that fixed, thanks :)

**Comment by NillerMedDild** [comment]
I suggested to ability to change/remove Wooden Post recipes here: https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/26

If they'd rather not implement that, I'll change the stripping recipe.

In the mean time, you can craft the Wooden Logs into Wood by filling the inventory crafting table with Logs, and then using the axe on that:

![billede](https://user-images.githubusercontent.com/21295394/90820667-0598ee80-e332-11ea-94d1-02e508148312.png)
![billede](https://user-images.githubusercontent.com/21295394/90820679-0a5da280-e332-11ea-94e6-eb3a77919e29.png)
