### ISSUE TITLE
[0.4.3] Crash on Startup - Fixed

### ISSUE THREAD

**Issue by Metrakon** [NillerMedDild/Enigmatica6#1753]
**0.4.3**

Modpack crashes on startup with Error: 0

I fixed it by updating resourceful bees to the latest version (1.16.5-0.6.5b)

**Logs**
-

**Screenshots**
-

**Comment by NillerMedDild** [comment]
Did you modify anything prior to the crash? :)

**Comment by Metrakon** [comment]
I added Optifine but then it crashed, so I removed Optifine but it still crashed so I dont think Optifine was the reason.
Biggest problem was I never got a crash-report so I had to try differend things.

**Comment by NillerMedDild** [comment]
Interesting. The crash reason is usually in the latest.log :)

**Comment by Metrakon** [comment]
crash-reports:
[2021-03-18-6.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/6177887/2021-03-18-6.log.gz)
[2021-03-21-1.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/6177888/2021-03-21-1.log.gz)
[2021-03-21-2.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/6177889/2021-03-21-2.log.gz)

with updated resourceful bees:
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6177891/latest.log)

I can change to the old version of resourceful bees and updload that log too if you want

**Comment by NillerMedDild** [comment]
OptiForge is needed to use Optifine afaik, fyi. Looks like you accidentally removed `kotlinforforge-1.10.0-obf` when removing Optifine, that's what caused the second crash. No idea how updating Resourceful Bees fixed that though.
