### ISSUE TITLE
[Enigmatica 6 0.4.3] Bee nests above ocean

### ISSUE THREAD

**Issue by Aghanimoff** [NillerMedDild/Enigmatica6#1761]
Enigmatica 6 0.4.3

 Bee nests gonna spawn above ocean

![javaw_jElEOACqWa](https://user-images.githubusercontent.com/81116726/111921060-97710180-8aa3-11eb-9f5e-a3ad479a7605.png)

![javaw_D8VpZ8Y5fC](https://user-images.githubusercontent.com/81116726/111921062-98a22e80-8aa3-11eb-9573-594fba600525.png)

**Comment by NillerMedDild** [comment]
This is intended I believe :)

**Comment by Aghanimoff** [comment]
🙁
