### ISSUE TITLE
Custom Loot Tables For Structures

### ISSUE THREAD

**Issue by MysteryGhost21** [NillerMedDild/Enigmatica6#1763]
So for certain mods, such as the somewhat-recently added dungeon crawl mod, and in all the vanilla structures, I feel that they are a bit lacking in the loot department. A lot of the structures that are present in the mod pack (excluding structures in mods such as Astral Sorcery) only have vanilla loot tables. It is kind of unfortunate to get all the way down a dungeon, only to find around 20 iron and a few diamonds in some chests, whereas we COULD find something along the lines of:

-Machine pieces from mods such as Create, Mekanism, Immersive Engineering, etc..
-Ingots such as steel, brass, arcane gold, manasteel, etc...
-If you're really lucky, in rare cases, maybe even tools such as the IE drill, or the Mekanism Atomic Disassembler 

My point is, once you've reached diamond tools and gear, exploration becomes moot. There is no reason to get to the bottom of that dungeon, there is no reason to go find a shipwreck, there is no reason to go to the top of that pillager outpost, all because you know that whatever is in there, it is not worth your time.

Please consider this, as exploration and discovery is a fun part of Minecraft, but with mods installed, needs a little more incentive to do so.

**Comment by NillerMedDild** [comment]
We'll try to implement this as we go :)
