### ISSUE TITLE
Absent by Desing and Glassential

### ISSUE THREAD

**Issue by viper7804** [NillerMedDild/Enigmatica6#1764]
https://www.curseforge.com/minecraft/mc-mods/absent-by-design

Basically adds slabs, stairs, and fences, etc for blocks that dont have them

https://www.curseforge.com/minecraft/mc-mods/glassential

Adds in abunch of cool glass

I would like both for building and a good bit of Building Gadget 9x9 builds I like use them

**Comment by telemenar** [comment]
Glassential is already on the pack and absent by design has been declined twice. You can get stairs for those blocks using blockcraftery. 

https://github.com/NillerMedDild/Enigmatica6/issues/1597

https://github.com/NillerMedDild/Enigmatica6/issues/330
