### ISSUE TITLE
[0.4.4] Missing Goggles Slot

### ISSUE THREAD

**Issue by Khramium** [NillerMedDild/Enigmatica6#1766]
**Modpack version**
Enigmatica 6 0.4.4
**Describe the bug**
While I know this version is not a stable version, and was only up for a little, I just wanted to bring to attention the missing Curios goggles slot. 

**Screenshots**
Curios Menu: https://imgur.com/a/mE9LnHw

**Comment by NillerMedDild** [comment]
Ah damn - Take off all baubles and use the command `/curios reset playername`
