### ISSUE TITLE
Oddity bush

### ISSUE THREAD

**Issue by Chtholly-dev** [NillerMedDild/Enigmatica6#1769]
**Description**
Can we get a way to grow oddity bushes for design purposes? We got the rest of the Atmospheric trees who aren't in the game yet so why not get a way to produce these guys?

**Screenshots if applicable.**
![Enigmatica 6 - Minecraft 1 16 5 - Multiplayer (3rd-party Server) 22_03_2021 10_48_55](https://user-images.githubusercontent.com/52564247/111963986-cebfcc80-8afc-11eb-84bd-e0ca0d831e6e.png)

**Comment by MuteTiefling** [comment]
Meant to do this one earlier, but forgot! Sorry, will be in for next release, however.

**Comment by Chtholly-dev** [comment]
Thank you Motoko! Don't worry about it. I'm just happy that an idea of mine made it's way in the pack in one way shape or form.
