### ISSUE TITLE
Change many recipes to allow any forge:stone input instead of only vanilla "stone"

### ISSUE THREAD

**Issue by Scorch-Mechanic** [NillerMedDild/Enigmatica6#1770]
**Description**
There's a bunch of random recipes that call for and allow only minecraft's natural stone that reasonably could be changed to use any equivalent natural stone, but don't for whatever reason.

**Why would you like this added/changed?**
Given the changes to stone generation, generic natural stone is suddenly much less common than it used to be. Most recipes that call for natural stone will take anything tagged "forge:stone" but there's a few that could be that way and don't. It makes sense in the grander scheme of the modpack to be able to use any variety of natural stone to make my comparators and repeaters, like I can for stone tools or furnaces.

**Things wot take stone that I fink should take forge:stone**
stonecutter
redstone comparator
redstone repeater
redstone randomizer (quark)
redstone inductor (quark)
wallpaper (all colors, embellishcraft)
coralstone (upgrade aquatic)
drawer controller (storage drawers)
drawer controller slave (storage drawers)
compacting drawer (storage drawers)
demagnatizer (demagnatize)
liquid trash can (trash cans)
item trash can (trash cans)
energy trash can (trash cans)
pedestal (pedestals)
industrial block category detector (gauges and switches)
blank plate (dark utilities)

**Notes**
I compiled this list by looking at all recipes that asked for vanilla minecraft stone. Hopefully I didn't miss anything. I left several things off the list that require vanilla minecraft stone that also look like they're made out of the stuff, or are obviously variations on the theme of vanilla minecraft stone.

**Comment by TemperedFool** [comment]
@Scorch-Mechanic - I don't disagree in principle, but in the meantime there are easy methods for generating generic stone - a vanilla stone generator, the Pedestals Cobblestone Generator, and the Industrial Foregoing Material Stoneworks Factory come to mind.

I do see the irony of needing some stone to make a pedestal to make some stone...
