### ISSUE TITLE
[0.4.3] Uranite Blocks have no use

### ISSUE THREAD

**Issue by LiabilityBryony** [NillerMedDild/Enigmatica6#1771]
**[0.4.3]**

**Describe the bug**
Uranite blocks from Powah don't have any use. I imagine the intention is for them to be able to be turned back into individual uranite, much in the same way that iron blocks can be returned to iron, etc. At the moment they are purely decorative.

**Comment by TemperedFool** [comment]
Fixed in 0.4.4 j believe.
