### ISSUE TITLE
Amber ore from Better end 

### ISSUE THREAD

**Issue by Chtholly-dev** [NillerMedDild/Enigmatica6#1772]
**Modpack version 0.4.3**

**Describe the bug**
The amber ore isn't affected by fortune at all or by the scorching heat enchantment. It only drops the raw amber and not Amber crystals with scorching heat.

**Comment by NillerMedDild** [comment]
Thanks for the report. I fixed this, but not in the way you had probably hoped :P The Ore -> Gem smelting recipe was not intended, it was meant to be Ore -> Shard only.
