### ISSUE TITLE
[0.4.3] Missing crafting recipes on ranked Botania Terra Shatterer 

### ISSUE THREAD

**Issue by SkyChotik** [NillerMedDild/Enigmatica6#1773]
**Modpack version 0.4.3**

**Describe the bug**
Botania Terra Shatterer cannot be upgraded to AIOT, upgraded with Elementium Pickaxe, or made into the MythicBotany Alf Shatterer if it has been ranked up at all.

**Comment by NillerMedDild** [comment]
I believe this was fixed in 0.4.4, as I cannot reproduce any part of it.
