### ISSUE TITLE
[0.4.3] create-client.toml in use by another process

### ISSUE THREAD

**Issue by xSvenHD** [NillerMedDild/Enigmatica6#1775]
**Description**: 
My game crashes after a roughly 10 seconds of being in my world that has create blocks placed. Happens on a dedicated server and singleplayer. 
The create config is not open by a text editor, tried deleting it to let forge create a new config.
EDIT: Done more testing, it happens when I look at a create machine. I see my config folder filling up with new configs from create and after it made the 5th one it crashes. *see picture*
**Log**: https://pastebin.com/UWm9YJxL
**Picture**: https://imgur.com/a/laTsXoI

**Comment by Darkere** [comment]
Check your antivirus software maybe?

**Comment by xSvenHD** [comment]
> 
> 
> Check your antivirus software maybe?

I'm not using an extra antivirus software on top of windows 10 defender. But I will try excluding the config folder in defender.

**Comment by NillerMedDild** [comment]
This was fixed in 0.4.4 by removing Create Plus :)
