### ISSUE TITLE
[0.4.4] Goggle Curio Slot Not Present on Curio Reset Command

### ISSUE THREAD

**Issue by NoMoreStars** [NillerMedDild/Enigmatica6#1779]
**Modpack version**
0.4.4

**Describe the bug**
Upon updating and loading in a world that was creating on version 0.4.x, and doing the command {/curios reset [player]}, no curio slot for goggles is loaded as is instructed in the changelog for 0.4.4. The armor stand slots also mentioned in the changelog are present however. Changing dimensions seems to remove them as well as the cosmetic curio slots. Interestingly, items like the Night Vision Goggles and the goggles from Create are listed as being able to be inserted into a goggles curio slot.

**Comment by NillerMedDild** [comment]
You don't see it at the top? It doesn't have a proper icon :P

**Comment by NillerMedDild** [comment]
Ahh I know what went wrong. Fixed in 0.4.5 :)
