### ISSUE TITLE
Mining Gadget Beam Doesn't Render

### ISSUE THREAD

**Issue by MaxFirestorm** [NillerMedDild/Enigmatica6#178]
**Modpack version**
0.2.10

**Issue**
When using the Mining Gadget, the beam doesn't render at all, even after changing colour settings

Video - https://www.youtube.com/watch?v=L19jVKuIExI

**Comment by Darkere** [comment]
Are you using optifine?

**Comment by MaxFirestorm** [comment]
I am not. I'm only using what comes in 0.2.10. No changes, additions or removals.

**Comment by NillerMedDild** [comment]
Dammit, I was hoping I was the only one with this issue :P

**Comment by Darkere** [comment]
Modlist from launch day: https://pastebin.com/GXzL7b1W

**Comment by NillerMedDild** [comment]
Huh, it now works in my dev instance. Would you mind checking 0.2.11 and see if the issue persists, after I make it in about 20 minutes? :)

**Comment by MaxFirestorm** [comment]
Can do! I'll let you know what happens.

**Comment by MaxFirestorm** [comment]
So I checked out the pack update and it uh.... *kinda* fixed it? 
![2020-08-20_22 05 15](https://user-images.githubusercontent.com/11296552/90827824-d9cb3800-e334-11ea-916c-7c4475e1c622.png)

**Comment by Darkere** [comment]
I believe that is an issue with FoV

**Comment by MaxFirestorm** [comment]
Aha, you're correct. I set my FoV to normal and it's connected correctly. Thank you!

**Comment by NillerMedDild** [comment]
Awesome!
