### ISSUE TITLE
[0.4.3] client crashes on join 

### ISSUE THREAD

**Issue by skythebro** [NillerMedDild/Enigmatica6#1780]
**Modpack version**
- [0.4.3]
**Describe the bug**
- When i try to join my server my client crashes with error nullpointerexception

**Logs**
client log
- https://pastebin.com/5A2P2zPW
on server it also gives error but doesn't crash itself
- https://pastebin.com/Vf61kUMw

**Comment by NillerMedDild** [comment]
The crash seems to be caused by PneumaticCraft's Armor HUD - Try deleting the file `config\pneumaticcraft\PneumaticArmorHUDLayout.cfg` :)

**Comment by NillerMedDild** [comment]
Ah you added DynamicSurroundings, that is the cause.

https://github.com/TeamPneumatic/pnc-repressurized/issues/752
https://github.com/OreCruncher/DynamicSurroundings/issues/685

**Comment by skythebro** [comment]
ah my appologies thanks for the help though! My bad!
