### ISSUE TITLE
[0.4.3] Drikwing quest from Occultism quest tree not completing

### ISSUE THREAD

**Issue by NoobGamerHD** [NillerMedDild/Enigmatica6#1786]
**0.4.3**

It simply doesn't get the "complete" status for me, even after i do the ritual right, set the items up and kill a wild parrot i spawned from the altar of birthing, when the mob (drikwing) spawns, nothing happens.

**Comment by theboo** [comment]
I don't really have the time these days to work on this, but I am assuming that when occultism added the wild versions of the drikwing and parrot rituals, the advancement names got changed(these quests are advancement based).. should be an easy fix if someone can give it a look...

**Comment by NoobGamerHD** [comment]
i'm currently trying to complete all the quests from enigmatica 6 so fixing that quest would be appreciated! 👍

**Comment by NillerMedDild** [comment]
There are two now:
- `occultism:familiar_otherworld_bird`
- `occultism:familiar_parrot`

Which one should the quest trigger on?

**Comment by NoobGamerHD** [comment]
I guess that the quest should trigger on the "otherworld_bird" one, since the drikwing mob is called that in the occultism mod as well.

**Comment by NillerMedDild** [comment]
Seems to be working fine in-dev.

**Comment by theboo** [comment]
Can you provide a screenshot of your quest tasks?

**Comment by NoobGamerHD** [comment]
sure, lemme just boot up the game rq

**Comment by NoobGamerHD** [comment]
![image](https://user-images.githubusercontent.com/77063641/112481233-8d762980-8d55-11eb-85e1-b4460dd94959.png)

**Comment by NoobGamerHD** [comment]
i even tried summoning another drikwing, still didn't work :(

**Comment by theboo** [comment]
edited quest description and title on dev server to show that you must summon the familiar and not the wild version.
