### ISSUE TITLE
[0.4.5] Mending enchant broken

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1788]
**Modpack version**
0.4.5
**Describe the bug**
Vanilla Mending enchant just doesn't work in 0.4.5. I have mending enchanted armor, and mending sword, but none of them repair themselves when picking up XP orbs.

**Comment by Bubble0seven** [comment]
Having the same issue as well on my server.

**Comment by Rodg88** [comment]
Looks like it's ensorcellation, and should be fixed in the next version.

**Comment by Merlo17** [comment]
![](https://media.discordapp.net/attachments/726178356143456287/823914992876257300/Screen_Shot_2021-03-24_at_12.43.47_am.png)

couldn't find an issue tracker for it to reference, let's keep an eye out for it

**Comment by Rodg88** [comment]
cofh_core has updated to 1.2.1, which fixes the issue.
