### ISSUE TITLE
[0.4.3] Astral Sorcery: Starmetal Unobtainable

### ISSUE THREAD

**Issue by ninjabunny66** [NillerMedDild/Enigmatica6#1790]
Enigmatica 6 - 0.4.3

Starmetal, a material required for progressing in Astral Sorcery is unobtainable. The ore can be obtained through the usual astral sorcery method, but the smelting recipe to turn said ore into an ingot is missing.

**Comment by Rodg88** [comment]
this is fixed already in 0.4.5

**Comment by Merlo17** [comment]
https://github.com/NillerMedDild/Enigmatica6/issues/1644 please update the pack
