### ISSUE TITLE
[0.4.5] Create goggles in new curio slot don't work

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1791]
**Modpack version**
0.4.5
**Describe the bug**
After using the reset curios command, and relogging to actually get the slot to appear, it turns out the create goggles just aren't active when placed in the goggles slot. 

With goggles in head slot, the kinetic stress popup is showing correctly:
![2021-03-24_00 53 16](https://user-images.githubusercontent.com/2611674/112157912-c91cd080-8c3b-11eb-94df-c1ad9ccbb384.png)

With them in curio slot:
![2021-03-24_00 53 06](https://user-images.githubusercontent.com/2611674/112157833-b4403d00-8c3b-11eb-88ab-3f6635946c44.png)
no popup:
![2021-03-24_00 53 09](https://user-images.githubusercontent.com/2611674/112157854-b86c5a80-8c3b-11eb-83e7-15a8290ed78a.png)

**Comment by NoMoreStars** [comment]
Can also confirm the Create goggles only work in the head Armor slot in 1.4.5

**Comment by Buuz135** [comment]
Yeah, just by tagging something to be accepted in a slot it won't make it work @NillerMedDild there needs to be explicit compat because Create can't check if it has the item to make it work :P

**Comment by KrAzYGEEK32** [comment]
it did work in the last version though

**Comment by NillerMedDild** [comment]
Well shit, I thought I was being smart. Guess I'll re-add Create Plus :/
