### ISSUE TITLE
[0.4.5] Botany Pots losing crops on update (0.4.3 to 0.4.5)

### ISSUE THREAD

**Issue by shibeobi12** [NillerMedDild/Enigmatica6#1794]
**0.4.5**

**Describe the bug**
My users are reporting all their botany pots have lost their crops, and logs seem to support that. For now I'm replacing all of their crops but this could be a bit more annoying if you have players that use more than two or three like mine.

**Logs**
[2021-03-23-1.log](https://github.com/NillerMedDild/Enigmatica6/files/6191887/2021-03-23-1.log)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
