### ISSUE TITLE
[0.4.5] Shifting/Missing Biomes

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#1796]
**Modpack version**
E6 0.4.5

**Describe the bug**
It seems that some biomes have shifted, while some biomes have gone completely missing. It was initially reported by Haru on the official server for the Dunes where it's now flagged as a Rain Forest. It rains there, the grass is greener, and all of that. The issue can be replicated in Single Player as well. Not 100% what other biomes might have gone missing.

**Logs**
N/A

**Screenshots**
N/A

**Comment by NoobGamerHD** [comment]
same problem here, might be linked to changing forge versions, as well as the biomes the chunks of my world are mixed, it's like the world began to generate different chunks to what it was supposed to be.

**Comment by HaxtonSale1** [comment]
Same problem on GarethCarew's server, where Petrified Dunes biome became Rainforest Plateau

**Comment by Merlo17** [comment]
Could it be related to BYG adding new biomes in the new version?

**Comment by NillerMedDild** [comment]
That shouldn't have an effect, Forge fixed that.

**Comment by NillerMedDild** [comment]
Alright the Forge update by itself does not shift biomes.

**Comment by NillerMedDild** [comment]
Not caused by adding Repurposed Structures, not caused by our changes to the TerraForged Enigmatica preset.

**Comment by NillerMedDild** [comment]
Actually I can't even find a Dune in 0.4.3. I can't reproduce the issue either, at all.

**Comment by jinkhya** [comment]
Hello!
I believe it's the atmospheric biomes that shifted. BYG and vanilla biomes seem fine.
This used to be what I think was Dunes and is now rainforest (or my notions about what a rainforest should look like is all wrong :) ): 
![](https://i.imgur.com/HH0chLK.png)

**Comment by NillerMedDild** [comment]
Seems like Dunes are missing from TerraForged worlds entirely. No such issue for default worldgen.

**Comment by theboo** [comment]
That's so weird, neither TF nor atmospheric updated between 0.4.3 and 0.4.5... atmospheric released their first update since December the day after 0.4.5 was released, it does have some dune related stuff in the changelog

**Comment by NoobGamerHD** [comment]
I'm almost sure that the problem is only happening to new worlds (the biome shifting i mean), as i said before, it's like the world was "rewritten" from changing modpack versions :/

**Comment by NillerMedDild** [comment]
I made a world in 0.4.3 and updated to 0.4.5 as a part of my tests, that didn't change anything :/
The Dunes biome was missing from TF even in 0.4.3

**Comment by jinkhya** [comment]
On our server the map was made on 0.4.2, then updated to 0.4.3 then 0.4.5. 
It looks like Dunes is not that easy to get when creating a world ; I made a small modpack with about 10 mods including atmospheric, byg and terraforged with the versions that were included in 0.4.2 (and same forge version 36.0.40) and it took me 3 worlds before getting one where locatebiome would find Dunes.

**Comment by jinkhya** [comment]
Gonna keep testing things, I'll let you know if I find a way to reproduce this :)

**Comment by NoobGamerHD** [comment]
Yeah the world i'm playing at that is having this issue is very old, i think i created it back in version 0.2.x and the problem began before update 0.4.3 even, this detail makes it more complicated for me to find its source :(

**Comment by NoobGamerHD** [comment]
One more thing, user @jinkhya, is the nature compass locating wrong biomes in the world that you're having the problems on? because it's happening to me sometimes, for example: i choose to locate an ocean biome and when i get to it it's actually a prairie biome .-.

**Comment by jinkhya** [comment]
it's happening with the shifted biomes yes, I didn't have this issue until 0.4.5.
And I can't reproduce either, I made a new world on 0.4.2, updated to 0.4.3 then 0.4.5 and my dunes biome is still showing as dunes and not something else, so weird.
Niller if you wanna to test some more, here is a seed that has some dunes -6638461434865088967

**Comment by NoobGamerHD** [comment]
This is not happening to all the biomes, the first loaded biome in my world wasn't changed, but some other biomes farther away have, it's really inconsistent tbh...

**Comment by jinkhya** [comment]
mh... gotta love inconsistent issues :/

**Comment by HaxtonSale1** [comment]
Experienced on a server, Petrified Dunes turned into Rainforest Plateau

**Comment by willbattel** [comment]
I got this too, upgraded from 0.4.1 to 0.4.7, now this has become a Rainforest...
![2021-03-26_23 37 42](https://user-images.githubusercontent.com/13490339/112710080-80a82180-8e8c-11eb-8db9-6b4c241ca8e2.png)

**Comment by SkyChotik** [comment]
This used to be 'Rainforest' but is now 'Stone Forest' after update from 0.4.2 -> 0.4.7
![Image1](https://cdn.discordapp.com/attachments/308008312291721216/825426753824358400/unknown.png)

**Comment by NoobGamerHD** [comment]
i've just watched a youtuber's video on the modpack and it seems that the nether biome are changing too! wth?!

**Comment by NoobGamerHD** [comment]
![image](https://user-images.githubusercontent.com/77063641/112740440-73a23580-8f53-11eb-9a59-9f256d413823.png)

**Comment by NoobGamerHD** [comment]
freaking creepers on the nether lol

**Comment by HaxtonSale1** [comment]
> 
> 
> Experienced on a server, Petrified Dunes turned into Rainforest Plateau

Also an Autumnity biome turned into a Steppe
