### ISSUE TITLE
[0.4.5] BooBee honeycombs won't process in a Centrifuge

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1799]
**Modpack version** 0.4.5

**Describe the bug**
Got someone compaining on discord, I tested it myself. After about 15 minutes of waiting, it won't process
![2021-03-24_11 52 15](https://user-images.githubusercontent.com/13237198/112247356-7d981000-8c97-11eb-8078-e2b8e2579830.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MRT-CO** [comment]
Check if centrifuge have a fluid like honey, BooBee produce milk, not honey, try adding some bottles @HaxtonSale1

**Comment by HaxtonSale1** [comment]
The person reported that, putting in bottles and "going away from the centrifuge" made it process, but I don't know what that _exactly_ means
Also, I placed it straight from Creative tab, it should be empty?
![2021-03-25_11 05 53](https://user-images.githubusercontent.com/13237198/112408049-6c640780-8d5a-11eb-80d0-2dfa22341178.png)

Would this be enough proof? From left, Vanilla, BooBee, Catnip, Diamond, RGB. Everything EXCEPT BooBee is processing
![2021-03-25_11 11 02](https://user-images.githubusercontent.com/13237198/112408234-cc5aae00-8d5a-11eb-9fd7-830d8a3268a8.png)

**Comment by HaxtonSale1** [comment]
![2021-03-25_11 16 01](https://user-images.githubusercontent.com/13237198/112408636-83efc000-8d5b-11eb-895c-d9ae22693661.png)
![2021-03-25_11 16 04](https://user-images.githubusercontent.com/13237198/112408638-8520ed00-8d5b-11eb-8b12-9571a2d525c4.png)

**Comment by NillerMedDild** [comment]
It started working for me after a while :s

**Comment by NillerMedDild** [comment]
I figured it out, the order in which you place bottles and combs matters because Boobee Combs had no non-bottle recipe like all the other Comb Centrifuge recipes. Adding a non-bottle recipe resolved the issue.
