### ISSUE TITLE
Crafting Tweaks "Compress All" With Honey Bottles Doesn't Return Empty Bottles

### ISSUE THREAD

**Issue by MaxFirestorm** [NillerMedDild/Enigmatica6#180]
**Modpack version**
0.2.10

**Issue**
When using Crafting Tweaks "Compress All" function (Default Shift+K) with Honey Bottles to turn them into Honey Blocks, you don't get given any empty bottles back. If doing the "compression" normally/manually, you're given back the four empty bottles you used to make the block for each craft.

Video - https://youtu.be/HWbgNiI4kHA

**Comment by NillerMedDild** [comment]
Thank you for yet another excellent bug report :)

**Comment by MaxFirestorm** [comment]
You're welcome!

**Comment by NillerMedDild** [comment]
This will be fixed when the modpack upgrades to 1.16.2 :)
