### ISSUE TITLE
Mowzie's Mobs

### ISSUE THREAD

**Issue by Scapul23** [NillerMedDild/Enigmatica6#1801]
https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs

The mod adds neat new mobs and some bosses to your Minecraft world. This mod is well very well known in the mc modded community and it just ported to 1.16

I would like this mod to be added for the bosses it adds and the mobs. Some of them are simply beautiful and fun to battle. It just ported so it might be a bit buggy but I hope it one day gets added to the pack.

**Comment by NillerMedDild** [comment]
I really like the look of this mod, I'll have a look when I get more time for suggestions :)

**Comment by CletusMAngo** [comment]
I feel like this kinda falls under the category of "if you spawn in next to one of these creatures it could ruin your experience" dont ya think?

**Comment by NillerMedDild** [comment]
Yes 😞

**Comment by Scapulaunit12** [comment]
I mean it's only really the nagas that pose a constant threat, the rest are locked in a certain area, easy to escape, stationary, or are asleep until you attack them.

**Comment by Mendanbar** [comment]
You can also config the nagas to only spawn under certain conditions... Like night

**Comment by Mendanbar** [comment]
I played with this a bit in the Uncle Genny pack, and we got the worst possible spawn and almost immediately encountered a naga, and honestly it did not ruin the experience. It was actually kind of fun to find a way to defeat the thing that seemed immortal, and very rewarding when we actually succeeded.

**Comment by Mendanbar** [comment]
We did end up adjusting them to only spawn at night, but not because they posed a threat at that point... They were just annoying when they could spawn during the day once home base was established.

**Comment by Mendanbar** [comment]
My one complaint about the mod is that the rewards for defeating the mobs aren't really all that good, and they would seem really underwhelming in E6 I think. But it's no different than meet your fight in that regard, and the battles themselves are still really fun.

**Comment by Scapulaunit12** [comment]
Yeah, basically all the tough mobs are optional to fight so even if you spawn near one it should be no problem. The exception is Nagas but as Mendanbar said it can be set to only spawn at night.

**Comment by 2xMJet** [comment]
> My one complaint about the mod is that the rewards for defeating the mobs aren't really all that good, and they would seem really underwhelming in E6 I think. But it's no different than meet your fight in that regard, and the battles themselves are still really fun.

Cant KubeJS adjust drops for keep up with other loots of modpack? I think its interesting idea to give them something good in drops if this mod will finaly get to E6.

**Comment by MuteTiefling** [comment]
Grottol may need to be blacklisted from spawners unless we're OK with having Diamonds from mob spawning. They also, oddly, spawn constantly under my platforms in my void world. Super strange.

**Comment by CletusMAngo** [comment]
I actually play on a few other servers with mowzies installed and we've had issues with serious chunk corruption with wroughnoughts spawning in the End and Nether

**Comment by NillerMedDild** [comment]
Thanks for the heads up Cletus! I'll mark this as blocked until this is resolved: https://github.com/BobMowzie/MowziesMobs/issues/375#issuecomment-812574854

**Comment by BobMowzie** [comment]
Hey, saw this referenced! Working on the fix now, please keep an eye out for patch 1.5.16 of Mowzie's Mobs afterwards.
(Also @Mendanbar the strength of the rewards and the mob health/attack damage can be configured to match the power levels of other mods in the pack)

**Comment by Scapulaunit12** [comment]
Ay, I noticed on the github for mowzies the bug is fixed for the next version release

**Comment by BobMowzie** [comment]
Yes, I believe so! I have not been able to personally reproduce it but I’m fairly confident this will stop it.

**Comment by BobMowzie** [comment]
Please check out my latest patch when you get the chance! Thanks! https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs/files/3268939

**Comment by NillerMedDild** [comment]
Very very cool entities, but I feel like they're a bit too dangerous in general for the overworld. I may consider adding the mod if we make a more dangerous adventure type dimension down the line, but for now it's a no thank you.
