### ISSUE TITLE
[Suggestion] On servers, single waystone on first join per player

### ISSUE THREAD

**Issue by eliminat** [NillerMedDild/Enigmatica6#1803]
**Description**
When joining a server, many packs will automatically spawn a quest book or similar into the inventory. I think there should be an option to spawn a single waystone into a newly joined player's inventory.

**Why would you like this added/changed?**
Players would still have to explore and travel to everyone's base by foot to activate them, could still keep them super rare, but would encourage people visit each other. Right now early game visiting is restricted due to the time/distance required.

**Screenshots if applicable.**

**Comment by LloydSev** [comment]
+1

This would make setting up bases in far away places much easier in early game if you still wanted to have social interactions.

**Comment by theboo** [comment]
There is always /tpa to visit someone... And can't say that feels too cheaty when you're asking for a free waystone haha

**Comment by LloydSev** [comment]
Does that not require moderator permissions?

**Comment by eliminat** [comment]
Unlike /tpa, a waystone requires you to visit and activate the other waystone at least once and does not require to be op. It would also still encourage exploration to find additional locations and waystones, or eventual tech progression to make them. I do not find a single waystone for people to place at their base for social reasons to be too "cheaty" when the pack already allows for /sethome and /home for individuals.

**Comment by theboo** [comment]
/tpa does not require OP... /tp does, I wasn't saying giving a single waystone would be too cheaty, I was saying it's no more cheaty than /tpa which we already have and anyone can use to teleport to someone else with that person's permission

**Comment by eliminat** [comment]
While I'll accept /tpa is legitimate knowing that, I still think it's a bit more cheaty as that allows to go to where the player is regardless of where they are, not to a fixed location you must have already visited before.
Just thought maybe instead of popping it in the inventory, an alternative could be an early quest reward instead.

**Comment by NillerMedDild** [comment]
To be honest I don't really like our /back, /home /tpa etc commands, doing something like this is a tempting alternative.

**Comment by Scorch-Mechanic** [comment]
Back when SKCraft was still a thing, the server had custom interactions with ender pearls: Throw one at your feet and get sent to your /home, throw one at your feet while standing in water and you'd get teleported back to the spawn village (where you could trade iron with a custom NPC for more). I'm not suggesting custom code like that, but I think that embracing that kind of attitude towards teleportation is a good thing. 

Perhaps a onetime free waystone pillar and a pile of return scrolls? Return scrolls are extremely cheap compared to waystones (or more expensive scrolls), requiring only purple dye and gold. In addition to waystones, there is also the magic mirror (and derivatives), Mekanism's teleport blocks and item, there's warp scrolls from ars noveau, and Astral Sorcery has dimensional gateways. And more besides, I'm sure. There's lots of ways to teleport and most of them are relatively accessible. I wouldn't be sad to see /back and /home go the way of the dodo.

**Comment by Lyx2k** [comment]
For servers who wants to play without these cheaty teleporting, commands can be easy deactivated through the config. A start item to provide teleporting would force the server to manipulate the kubejs files afaik. On updates this can lead to more problems for some people compared to simple config files in my opinion. And waystones are not hard to get.  The recipe is really simple. I think giving the players position in the world some value would be cool. Maybe a reason why I like the BetterEnd portals because you have to work for them.

**Comment by NillerMedDild** [comment]
> For servers who wants to play without these cheaty teleporting, commands can be easy deactivated through the config.

No they can't :P

**Comment by Lyx2k** [comment]
> 
> 
> > For servers who wants to play without these cheaty teleporting, commands can be easy deactivated through the config.
> 
> No they can't :P

Arent the commands the ftbessential stuff? I thought they can be deactivated.  So only through ftbranks I guess
