### ISSUE TITLE
[0.4.3] Obsidian Dupe with IE Crusher

### ISSUE THREAD

**Issue by Ashrahl** [NillerMedDild/Enigmatica6#1805]
**0.4.3**

**Obsidian Dupe**
Attempting to make Crushed Obsidian for Mekanism stuff.  Throw partial stack of obsidian into an IE crusher.  Outputs crushed obsidian in the amount input, and partial amount of regular obsidian.  

My IE Crusher is powered by Powah cables, manually input, feeds into a copper chest which then empties via basic mekanism logistic pipes.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I don't really see how this is a dupe. 25% of the time you lose the Obsidian block. I have removed the 9x Obsidian Dust -> Obsidian recipe though, just in case someone gets very very lucky and manages to dupe a few :P

**Comment by Ashrahl** [comment]
Maybe i am misunderstanding.  I was under the impression that 1 obsidian block grinds into 1 obsidian dust, which means the block should be always removed.  

Either way, thank you for your time.
