### ISSUE TITLE
[0.4.5] Server crash when upgrading Dank

### ISSUE THREAD

**Issue by Lavan** [NillerMedDild/Enigmatica6#1806]
**Modpack version**

Enigmatica 6 0.4.5

**Describe the bug**
Server crashed when I tried to upgrade a Dank 3 to 4, 5 and finally 6. 

I created the upgrade items and just right-clicked on the dank in its dock.

The dank is a part of my tier 3 mekanism ore processing so it receives and ejects items constantly.

**Logs**
19:05 https://pastebin.com/hW3qXUrk
19:12 https://pastebin.com/Qe7aRQyB
22:42 https://pastebin.com/3mr75fni

**Crashlogs**
19:01 https://pastebin.com/cFFLy8nJ
19:05 https://pastebin.com/v88XGkye
19:12 https://pastebin.com/MYwhyAEY
22:42 https://pastebin.com/3mr75fni

**Screenshots**
This is the dank that I upgraded. 

https://imgur.com/a/02XjzQO

The machines surrounding it auto-ejects to the left.

**Comment by NillerMedDild** [comment]
Sorry what is the bug here?

**Comment by Lavan** [comment]
Sorry, my bad. Mentioned it in discord and I got distracted while typing. Updating main post.

**Comment by NillerMedDild** [comment]
Do you have the crash report as well? :)

**Comment by Lavan** [comment]
Updated main post. Didn't know those logs existed. 😆

**Comment by telemenar** [comment]
If you apply the upgrade without the logistical sorter attached does it still crash?

**Comment by Lavan** [comment]
Updated with new logs. A simpler scenario as well.

1. Place Dank #1
2. Upgrade Dank #1
3. Place Dank #2
4. Place Ultimate Logistical Transporter between them (at least this is what I used)
5. Configure Transporter to pull from Dank #1 to #2
6. Crash

After restart of server, continuing on same setup.
7. Remove Transporter
8. Upgrade Dank #2
9. Pick up Dank #2
10. Place Dank #2
11. Place transporter
12. Configure transporter to pull from #2 to #1.
13. No problem

14. Remove and place Transporter to reset it.
15. Configure transporter to pull from #1 to #2
16. Upgrade Dank #1
17. Crash
18.

**Comment by Lavan** [comment]
More logs and crashreports are available, but I don't think they'll show anything new.
