### ISSUE TITLE
[0.4.5] RTP In Nether results in long distance overworld travel

### ISSUE THREAD

**Issue by zontreck** [NillerMedDild/Enigmatica6#1808]
**0.4.5**

If you issue the `/rtp` command while in the nether you will be transported to the overworld, but the position appears to reflect the 8/1 block travel rule for the nether.

My portal is at roughly:  3313, 100, -766
Nether position: 408, 75, -92

I end up after RTP from the nether position at: 3982, 73, 1284 in the overworld

**Comment by Merlo17** [comment]
that's... how the nether works?

**Comment by NillerMedDild** [comment]
Reported the dimension change here: https://github.com/FTBTeam/FTB-Essentials/issues/13
