### ISSUE TITLE
Update Interactio

### ISSUE THREAD

**Issue by TrainzCS** [NillerMedDild/Enigmatica6#181]
Interactio has a hotfix avaliable that stops a log clogger as dev forgot to remove debug stuff in release.

Link to hotfix: [https://www.curseforge.com/minecraft/mc-mods/interactio/files/3036266](url)

**Comment by NillerMedDild** [comment]
No you :P https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/3037923

**Comment by TrainzCS** [comment]
<3 watching jesters stream he was saying about it, we figured it was the mod didnt see the hotfix :+1:
