### ISSUE TITLE
Shared Quests

### ISSUE THREAD

**Issue by Pixelingot** [NillerMedDild/Enigmatica6#1810]
Please could u add shared quests for those people who are working as a team on servers etc it's really hlepful rather than accidentally re-doing the same quests multiple times

**Comment by Merlo17** [comment]
Not something we have control over, this is a feature that needs to be added by FTB quests themselves. I know they're working on them so they should be here pretty soon ^^

**Comment by TemperedFool** [comment]
It's not yet implemented in FTBQuests. Not much we can do about it. The FTBQuests team is aware of the desire and working on it: https://github.com/FTBTeam/FTB-Quests/issues/470
