### ISSUE TITLE
[0.4.5] Refined Storage: Non-Exact mode not working properly

### ISSUE THREAD

**Issue by zontreck** [NillerMedDild/Enigmatica6#1813]
**0.4.5**

**Describe the bug**
When setting up crafting patterns, if you use non-exact mode, such as i did in my example, sand->glass, then using other variants of Sand will result in it saying it does not have the components. See my screenshot for more information, but, the exact mode toggle does not appear to be functioning.

**Screenshots**
![2021-03-25_11-46](https://user-images.githubusercontent.com/1643882/112532832-886da600-8d66-11eb-9c2c-a49f793b4001.png)
![2021-03-25_12-28](https://user-images.githubusercontent.com/1643882/112532836-89063c80-8d66-11eb-98ed-93742569d6ca.png)
![2021-03-25_12-29](https://user-images.githubusercontent.com/1643882/112532837-899ed300-8d66-11eb-912d-52d19e8b86f3.png)

**Comment by MaxNeedsSnacks** [comment]
Processing patterns don't support non-exact mode, you will have to define tag replacements explicitly (to my knowledge, right(?) click the input item and set "Alternatives" forge:glass in this case
