### ISSUE TITLE
[0.4.5] Crash Report

### ISSUE THREAD

**Issue by Scorch-Mechanic** [NillerMedDild/Enigmatica6#1814]
**Modpack version**
[0.4.5] singleplayer, with yung's better caves kept in and COFH-Core updated to 1.2.1 to address the looting enchantment issue.

**Describe the bug**
A random CTD. What I was doing when it happened (which may be unrelated): I had just opened the gui of a Thermal Expansion Fluid Cell that was mostly full of milk, and my mouse was over a cake that I had in my inventory. Are these related to the crash? I doubt it!

I thought cockroaches weren't supposed to spawn in the overworld? 

**Logs**
[crash-2021-03-25_14.28.32-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6207967/crash-2021-03-25_14.28.32-server.txt)

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it :)

**Comment by Scorch-Mechanic** [comment]
Not sure if they're spawning anyways or they're simply not despawning. After reloading my game I used `/kill @e[type=alexsmobs:cockroach]` and got `Killed 16 entities`.

**Comment by ochotonida** [comment]
The kill command only kills entities in loaded chunks, so there's a good chance it missed a few

**Comment by Scorch-Mechanic** [comment]
> The kill command only kills entities in loaded chunks, so there's a good chance it missed a few
Right, which is why I set my render distance to 32 and waited a minute before trying again (and only getting one extra kill). And then went to the nether and did it a third time.

**Comment by NillerMedDild** [comment]
Seems to be a one-off :)
