### ISSUE TITLE
[0.4.5] Piston movement results in glitched blocks

### ISSUE THREAD

**Issue by zontreck** [NillerMedDild/Enigmatica6#1817]
**0.4.5**

**Describe the bug**
Using vanilla mechanics to create a very simple piston setup to retract a flush floor results in glitched blocks, right clicking the blocks makes them re-appear.

**Screenshots**
![2021-03-25_18-42](https://user-images.githubusercontent.com/1643882/112565399-38a8d200-8d9a-11eb-9415-950f9f30172d.png)
![2021-03-25_18-43](https://user-images.githubusercontent.com/1643882/112565401-39416880-8d9a-11eb-8f00-8ecc4d88bfe9.png)

**Comment by OneLemonyBoi** [comment]
Desync?

**Comment by zontreck** [comment]
Relogging does not resolve the issue.  They will reappear yes, but after the pistons are reactivated, the blocks disappear again

**Comment by NillerMedDild** [comment]
I can't reproduce this issue. Which blocks are you pushing, and how is the redstone going into the pistons?
