### ISSUE TITLE
/tank/null

### ISSUE THREAD

**Issue by SkyChotik** [NillerMedDild/Enigmatica6#1818]
https://www.curseforge.com/minecraft/mc-mods/tank-null

It's a fluid storage mod similar to the dank we have in this pack, by the same dev!
It's not the easiest to use, but it comes in very handy when placing fluids by hand, as to not waste fluids, and has a sponge function that automatically grabs fluids and places them inside with a toggle.

**Comment by NillerMedDild** [comment]
I'll think about it :)
