### ISSUE TITLE
[0.4.6] Crash on world load

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1821]
**Modpack version**
0.4.6
**Describe the bug**
Crash on loading my main world after updating from 0.4.5 to 0.4.6, maybe related to the dev version of ftbchunks?

**Logs**
crashlog:
https://gist.github.com/Rodg88/afcd10a2e18480128b8a424dd3013791

latest:
https://gist.github.com/Rodg88/2addbbca5e1e3ccd6e0cce85c9af09f6

**Comment by Rodg88** [comment]
I just downgraded ftbchunks and it fixed it

**Comment by NillerMedDild** [comment]
I updated to a dev-only build ^^' ty!
