### ISSUE TITLE
[Enigmatica6-0.4.3] Netherite backpack from sophisticated backpacks dissapears

### ISSUE THREAD

**Issue by skythebro** [NillerMedDild/Enigmatica6#1824]
Enigmatica6-0.4.3

I had a full netherite backpack from sophisticated backpacks full of ores and items
I accidentally placed it but when i broke it nothing happened the backpack disappeared.
I started to debug it spawned in multiple backpacks and surely every netherite backpack would not drop itself
when any other backpack(diamond etc.) would. is there some mechanic i don't know about or is this a bug?

No logs to see server doesn't even note anything wrong.

**Comment by NillerMedDild** [comment]
This is a known bug and has been fixed in recent versions, I recommend you update to 0.4.7 :) 
Sorry to hear about the loss of stuff, that sucks.

**Comment by skythebro** [comment]
oh thanks!
Sorry i always thought it would note when there was an update!
Much thanks

**Comment by NillerMedDild** [comment]
It only does that for releases, this latest one is marked as beta because we've had a bit of a rough patch with instability :P 0.4.7 should be good though.

**Comment by telemenar** [comment]
If you are willing to trawl through nbt, the stuff still exists an a random UUID in the sophisticatedBackpackts nbt file, and you can /give yourself back the pack
