### ISSUE TITLE
Crash when rendering entities

### ISSUE THREAD

**Issue by Darkere** [NillerMedDild/Enigmatica6#183]
**Modpack version**
0.2.11

https://gist.github.com/MaxFirestorm/916243949f4c9356db3bd44555eccd2a

This happens on thrown potions, ghast fireballs, thrown eggs...

Most likely caused by Apotheosis (or a conflict between it and another mod). Mod dev already tried to unsuccessfully fix it. 

Correction: apparently a forge issue. They are investigating. 

EDIT: Dev is saying he can hotfix the hotfix to make it at least not crash anymore.

**Comment by indygwyn** [comment]
I'm seeing the same, went to the nether and evertime a blaze shoots a fireball my client crashes

**Comment by Darkere** [comment]
Update apotheosis to 4.1.2 to fix the issue.
