### ISSUE TITLE
[0.4.7] Inventory appears on HUD after update from 0.4.3 to 0.4.7

### ISSUE THREAD

**Issue by Sourceshard** [NillerMedDild/Enigmatica6#1830]
**0.4.7**

**Visual Bug**
After updating my client and server I was presented with this visual. Moving the items in my inventory changes the location of the icons but all items remain visible on the screen. The main item bar is never shown. Items taken from the main bar and placed in the inventory are shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/37197624/112717117-e31b1500-8ec0-11eb-92f4-30178f021401.png)

**Comment by hvdklauw** [comment]
Bind a key to the Open config of Inventory HUD+ click the button and turn the Inventory Hud off.

**Comment by Sourceshard** [comment]
Fixed! Many thanks!

**Comment by NillerMedDild** [comment]
Has this happened for anyone else?

**Comment by KrAzYGEEK32** [comment]
yea, alot of people reported this on discord as well

**Comment by kman3107** [comment]
Yes. This happened to me too. Thankfully I saw Artemis mention the inventory hud in the discord support channel.

**Comment by MuteTiefling** [comment]
Happened to me too

**Comment by TemperedFool** [comment]
Is the client config getting overwritten durning the update? The default config does have it on by default I think.

**Comment by telemenar** [comment]
Some of the launchers overwrite the client config on update probably depends on the launcher.

**Comment by Scorch-Mechanic** [comment]
I use MultiMC, which is only manually updated, and when I launched 0.4.7 for the first time the inventory hud+ inventory hud... thingy was on by default. The only configuration file I carried over was options.txt though, so I was able to immediately open its menu and disable the overlay with the keybind I established back when I started over with 0.4.0.

**Comment by NillerMedDild** [comment]
I updated the changelog to reflect this issue and will hotfix this evening, thanks for the help everyone.
