### ISSUE TITLE
Silicon problem

### ISSUE THREAD

**Issue by matesz** [NillerMedDild/Enigmatica6#1832]
Hi,

I cann't crafting a raw processor because the emendatus silicon is not allowed in the crafting grid.

Thanks,

**Comment by MuteTiefling** [comment]
Please be sure to follow the brief template when opening issues like this.

Version and logs are very important for things like this.

**Comment by matesz** [comment]
Oh sorry,

Version is 0.4.7
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6215912/latest.log)

**Comment by MuteTiefling** [comment]
I cannot replicate this and I'm not seeing any KubeJS errors in your logs that would suggest this is broken in the pack.

**Comment by telemenar** [comment]
If this was focusing on a crafting recipe you might get the wrong silicon in the recipe but you can replace it with the EE variant and things will work.
