### ISSUE TITLE
[0.4.7] Crafting Combined Pedestal Upgrade Deletes Enchantments

### ISSUE THREAD

**Issue by SkyChotik** [NillerMedDild/Enigmatica6#1833]
**E6 0.4.7*

**Describe the bug**
Combining an enchanted magnet upgrade with a filter upgrade crafts an unenchanted upgrade.

**Screenshots**

![Image 1](https://cdn.discordapp.com/attachments/308008312291721216/825399736894095360/unknown.png)
![Image 2](https://cdn.discordapp.com/attachments/308008312291721216/825399796344160287/unknown.png)

**Comment by OneLemonyBoi** [comment]
Isn’t that because crafting can’t write nbt?

**Comment by NillerMedDild** [comment]
Crafting can write NBT, just not through the shaped/shapeless recipes vanilla provide afaik.

**Comment by Mowmaster** [comment]
Using an item in a recipe generally voids its enchants, this isnt a new thing, SOME mods do have a way to keep enchants, but thats a custom thing they do, there is no default behavior for this in the base game.

PLUS all filtered upgrades are being deprecated in the next update(and removed in the one after that), so this wont be an issue going forward.
The new system will be the normal magnet, with a filter item inserted into the pedestal with the filter swapper tool. Filters will be set by crouch + right clicking the filter item on an inventory.

**Comment by TemperedFool** [comment]
Nice - this would be the changes I totally am going to look at but haven't had time for yet. Sounds like "awaiting mod update" then.

**Comment by Mowmaster** [comment]
https://www.curseforge.com/minecraft/mc-mods/pedestals/files/3258445
