### ISSUE TITLE
[0.4.7] Music plays when muted in Sounds menu

### ISSUE THREAD

**Issue by Etrogann** [NillerMedDild/Enigmatica6#1838]
**0.4.7**

**Describe the bug**
Music is off in Options>Music&Sounds. A mod is bypassing this and playing music. 

**Logs**
n/a

**Screenshots**
n/a

**Comment by Tyler-Jarret** [comment]
I actually just had this issue when testing the pull. The music was mutable in Jukebox/Soundblocks setting. Randomly happened when I placed a Steel Slab. I'll be testing again tomorrow.

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm thinking it might be Ambient Sounds.

**Comment by Blatts12** [comment]
What about Sophisticated Backpacks?

https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/3248281

**Comment by KrAzYGEEK32** [comment]
it occurs due to sophisticated backpacks yes. some random mobs spawn with backpacks, and they have a chance of spawning in with the jukebox upgrade, i killed one and the music stopped intantly.

**Comment by P3pp3rF1y** [comment]
The music from those mobs plays under the same sound category that jukeboxes play so Jukebox/note blocks sound level is the one that allows you to set how loud it plays.
Anyway I know that some mods have very loud music on music discs compared to vanilla so if this is the case and you can identify the disc that's playing there is an option to block some of the discs in config `discBlockList` . (I had to put botania ones in the default as those are definitely very loud)

**Comment by NillerMedDild** [comment]
I found the overly load music disc and turned it off :P  ` "eidolon:music_disc_parousia"`
However, this is intended for the most part, as you probably guessed.

**Comment by NillerMedDild** [comment]
Hmm, the config reverts everytime I save, even if I change it with the game closed, the config reverts when it loads. Any ideas @P3pp3rF1y?
The entire line is `discBlockList = ["botania:record_gaia_1", "botania:record_gaia_2", "minecraft:music_disc_cat"]`
Cat chosen here to show that it happens with vanilla discs.

**Comment by P3pp3rF1y** [comment]
ohh, I can see the derp that I made in the regex that checks for correct entries - it wasn't smart to reuse the regex that I use for entity to loot mapping as it has an additional pipe symbol in there. I will get this fixed and a new release out today/tomorrow.

**Comment by NillerMedDild** [comment]
Sweet, thanks!

**Comment by P3pp3rF1y** [comment]
this is fixed in https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/3254223
