### ISSUE TITLE
Recipes for Project Vibrant Journey's ground clutter

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#1840]
**Description**

Twigs: 1x Leaves, 3x sticks = 3 Twigs

Various Rocks: Hammer the appropriate material to get 4. Like hammer + cobble gets 4 rocks. Hammer and Ice gets 4 ice chunks.

Pine Leaves with shears in crafting table = pine cones

The two shrooms need to be added to crops and tagged as mushroom.  Also need to add sea oats and cattails to crops. probably Crimson and Warped Nettle too. 

Can't think of a recipe for sea shells, honestly. They craft down to prismarine shards, so maybe a cross of 5 shards gets 5 shells. 

**Why would you like this added/changed?**
Just think the builders would appreciate these being renewable. They're all mostly decorative anyway.

**Screenshots if applicable.**

**Comment by OneLemonyBoi** [comment]
Did you do bones?

**Comment by NillerMedDild** [comment]
> 
> 
> Did you do bones?

He did indeed.
