### ISSUE TITLE
[0.4.8] Unable to make wheat flour from wheat in Mekanism crusher

### ISSUE THREAD

**Issue by Truhard** [NillerMedDild/Enigmatica6#1848]
Title. The second recipe shown in the screenshot cannot be crafted; Wheat always produces bio fuel in a crusher.
![image](https://user-images.githubusercontent.com/72954250/112761709-915eb180-8fca-11eb-9bbb-ac14d7d8676d.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. I'll disable the flour recipe :)

**Comment by MuteTiefling** [comment]
Flour could maybe go to the enricher, actually.

**Comment by NillerMedDild** [comment]
Excellent idea!
