### ISSUE TITLE
Standard backpacks missing in upgrade to 0.4.8

### ISSUE THREAD

**Issue by AdventureJon** [NillerMedDild/Enigmatica6#1850]
Hi
I upgraded from 0.3.13 to 0.4.8 and standard backpacks disappear along with the inventory.  Can this be fixed or is it a one way street?  Keep up the fantastic work.

**Comment by NillerMedDild** [comment]
If your backpack was from Useful Backpacks it is lost, because that mod was removed in 0.4.0 :)

**Comment by TemperedFool** [comment]
Not to mention upgrading from 0.3.x to 0.4.x is a Bad Idea™️

**Comment by AdventureJon** [comment]
Thanks team.  TemperedFool, is there a reason upgrading from 0.3.x to 0.4.x is a bad idea?  Looking to see what other mods might have been dropped or affected so I can decide if the new mods are worth the loss.

**Comment by TemperedFool** [comment]
@AdventureJon - It's in the release notes for the first few versions of 0.4.x; that represented a world-breaking change to not only the mod list, but also how world gen is done. 0.4.0 moved to using Terraforged for world generation, which results in some really pretty landscapes.

**Comment by AdventureJon** [comment]
Much appreciate what you guys do.  Looks like I'll need to start a new world.
