### ISSUE TITLE
[0.4.8] Alex's Mobs Cave Centipedes still spawn in caves

### ISSUE THREAD

**Issue by Truhard** [NillerMedDild/Enigmatica6#1853]
Title. Centipede was a boss mob, may or may not relate to its spawn in this version.

![2021-03-28_22 07 03](https://user-images.githubusercontent.com/72954250/112778424-80d22980-9012-11eb-9c8b-1e896d12d426.png)

![image](https://user-images.githubusercontent.com/72954250/112778467-a101e880-9012-11eb-8de7-ba51f45479f7.png)

**Comment by Merlo17** [comment]
I'm pretty sure apo bosses override normal spawn rules, so that should be good. Have you found naturally spawning normal ones?

**Comment by Truhard** [comment]
No, this is the only one I have seen in the past couple hours. Don't think this is a bug then since you said boss spawns override rules.
