### ISSUE TITLE
[0.4.8] Resourceful Bees crowd around a single flower

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#1855]
**Modpack version**
0.4.8 via Overwolf/CurseForge

**Describe the bug**
As of updating from 0.4.3 to 0.4.8 all of the the bees in my apiary multiblock structure which pollinate any flower (as opposed to specialized flowers) now all crowd around a single flower instead of each picking a different flower. They continue to try to reach the same flower, pushing each other aside and slowing honeycomb production to a near standstill. They'll also target flowers just outside the apiary which they cannot reach, continuing to try to reach them indefinitely until I remove the flower they've targeted. The specialized flower bees do the same thing with their flowers, but because I only have 1-2 of each it's less of a problem and they're still able to produce at normal-ish levels.

**Logs**
n/a

**Screenshots**
![Screenshot 2021-03-29 162916](https://user-images.githubusercontent.com/1171633/112908414-b6c3ec00-90ac-11eb-9d14-48c7ec3076a9.png)

**Comment by mouseas** [comment]
I had between 25 and 30 bees in there all targeting one flower. Even after taking 20 of them out they are still getting each others' way as shown in my screenshot.

**Comment by CletusMAngo** [comment]
I have also been experiencing the same issues over the last few updates
![2021-03-26_01 02 32](https://user-images.githubusercontent.com/76655777/112913578-37f5a000-90fa-11eb-9586-d4a05a23f9b3.png)

**Comment by OneLemonyBoi** [comment]
I have also had this issue.

**Comment by NillerMedDild** [comment]
Thanks for the report. Just to be sure, you haven't added any mods right?

**Comment by Leftoveru** [comment]
> Thanks for the report. Just to be sure, you haven't added any mods right?

Have had the same issue, no additional mods installed. Completely halted ressource production as a result

**Comment by SkyChotik** [comment]
Have also had this issue. I have a feeling it's due to the bees AI targeting the nearest flower. Have bypassed the issue by not having any flowers near corners.

**Comment by OneLemonyBoi** [comment]
Temporary fix is to use honey dipper to manually assign bees different flowers

**Comment by NillerMedDild** [comment]
Turns out this isn't a bug, it's intended - The dev explains why here: https://github.com/Resourceful-Bees/ResourcefulBees/issues/190#issuecomment-802195461
