### ISSUE TITLE
0.4.8 Block Placers not working

### ISSUE THREAD

**Issue by LogueTheRogue** [NillerMedDild/Enigmatica6#1859]
Enigmatica 6 - 0.4.8

Block Placers from Industrial and Routers from Module Routers will not place blocks.

**Comment by OneLemonyBoi** [comment]
Did you ally the fake players?

**Comment by OneLemonyBoi** [comment]
Instructions:
Press M on your keyboard, on the top left you click the button with 2 figures. Then you should ally the players with brackets in their name, so [Insert Name Here]

**Comment by LogueTheRogue** [comment]
Thank yo, that worked.  I have never seen that before.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by OneLemonyBoi** [comment]
Make sure to close the issue :)
