### ISSUE TITLE
[0.4.8] Dimentional shard crusher recipes

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1861]
**Modpack version**
0.4.8
**Describe the bug**
There's two different recipes for dimensional shard crushing:
![image](https://user-images.githubusercontent.com/2611674/112966911-67f28100-9196-11eb-8c16-5303aaadd198.png)

The pulverizer also gives a lot less shards than the mekanism/IE/pedestals/occultism equivalents, and starlight infusion is also worse than most others, maybe about equal to a pulverizer with basalz

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Rodg88** [comment]
In the same vein, fluorite has two pulverizer recipes, one from jaopca and one from thermal/mek compat

**Comment by NillerMedDild** [comment]
Fixed both, thanks again :)
