### ISSUE TITLE
[enigmatica6-0.3.13] Mekanism laser crash-loop

### ISSUE THREAD

**Issue by MartinLangerod** [NillerMedDild/Enigmatica6#1862]
**Modpack version**
enigmatica6-0.3.13
Enigmatica 6 - E6 - 1.16.5

**Describe the bug**
I accidentally removed a laser amplifier (Mekanism) with several lasers (Mekanism) pointing into it. This caused the world to crash after a few seconds, and now I'm stuck in an infinite crash loop whenever I log back on. Not sure if this is because the lasers are buggy or because my computer is bad, but I wanted to report it.

**Comment by NillerMedDild** [comment]
Thanks for the report. You're about 9 updates behind I'm afraid, it's highly likely that this issue no longer exists in recent versions. If you decide to update, please read the changelog for 0.4.0 thoroughly.
