### ISSUE TITLE
[enigmatica6-0.3.13] Refined Storage crafting grid-crash

### ISSUE THREAD

**Issue by MartinLangerod** [NillerMedDild/Enigmatica6#1863]
**Modpack version**
enigmatica6-0.3.13
Enigmatica 6 - E6 - 1.16.5

**Describe the bug**
Refined Storage Crafting Grid: I accidentally clicked the redstone-activation-torch in the top left corner of the crafting grid, and the game crashed. The game also crashes if I unpower the refined storage system and double click inside the crafting grid when it is grayed out. Not sure if anyone else have experienced this, or if it's because of my computer.

**Comment by OneLemonyBoi** [comment]
Logs?

**Comment by NillerMedDild** [comment]
Thanks for the report.
I'm afraid you're about 9 updates behind, it's very likely this bug no longer exists in recent versions. If you decide to update, please make sure to read the changelog for 0.4.0 carefully.
