### ISSUE TITLE
0.4.8 Ctrl+crafting makes half of output rather than multiplying it

### ISSUE THREAD

**Issue by quasarea** [NillerMedDild/Enigmatica6#1864]
0.4.8

**Describe the bug**
When crafting from multiple stacks and holding ctrl while clicking on output to get the whole lot, it yields only half of single craft output. I.e:

![image](https://user-images.githubusercontent.com/10334982/113001985-462ed500-9169-11eb-994e-ecbbd29e9bc6.png)
when ctrl+clicked should deploy 8 stairs to my inventory, instead I'm getting just 2, but it takes all the crafting resources and vanishes it.

shift+click works fine

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
