### ISSUE TITLE
Quest Suggestion: A quest for mechanical dirt

### ISSUE THREAD

**Issue by Scapulaunit12** [NillerMedDild/Enigmatica6#1865]
It would be really neat if we had a quest for mechanical dirt in the industrial foregoing section. I feel that a lot of people playing this mod pack aren't aware of mechanical dirt and it is a cursed earth substitute, as I didn't a well. It would be a nice way to let them know that it exists and maybe a small description of how it works.

Thank you

**Comment by Tyler-Jarret** [comment]
I would second this suggestion. I'm running a server for some of my Discord friends and one player was _very_ familiar with Blood Magic and was confused when there wasn't any Cursed Dirt. Fortunately, I was super familiar with Industrial Foregoing from a previous mod pack I was playing and was able to walk him through it. Yet I think a quest line would make it much easier for people who are either familiar or not to start to automate Blood Magic (which I think is rule 1 or 2 of Modded Minecraft 😋).
