### ISSUE TITLE
Tactical Fishing

### ISSUE THREAD

**Issue by BlazingPL** [NillerMedDild/Enigmatica6#1866]
https://www.curseforge.com/minecraft/mc-mods/tactical-fishing

Makes it possible to get Buckets of Fish via a different way; by fishing!
As simple as it sounds, hold a water bucket in your other hand during fishing to put the fished up fish into it.

Simple, lightweight mod that will enhance fishing with fish adding mods already in the pack. 

https://user-images.githubusercontent.com/25771200/113017970-530af300-9180-11eb-9120-4862f50e7e2a.mp4

**Comment by NillerMedDild** [comment]
While that looks like a solid mod, the fact that it's All Rights Reserved, closed source and has no issue tracker worries me a lot.

**Comment by Fuffled-Fuffles** [comment]
> While that looks like a solid mod, the fact that it's All Rights Reserved, closed source and has no issue tracker worries me a lot.

Sorry for that, I just have no idea what to select and stuff, I'd be happy to see it in the pack! (Added everything you requested)

**Comment by NillerMedDild** [comment]
Oh cool thanks, I'll add it then 😄 
I don't mind if you change the license back to All Rights Reserved btw, it's just the combination of Closed Source and All Rights Reserved that makes it hard to troubleshoot mod compatibility issues.
