### ISSUE TITLE
[E6 0.4.8] Sophisticated Backpacks - Item void bug

### ISSUE THREAD

**Issue by TheRealWebGremlin** [NillerMedDild/Enigmatica6#1867]
**Modpack version**
0.4.8

**Describe the bug**
While inside the UI of a backpack, if you hold down "W" and shift-click an item to transfer it, it will instead void the stack and all other stacks of that item in the player's inventory and backpack. Reproduceable in a SP test world as well as by fellow players on my server. Additionally, I've created a new instance running only Forge, Sophisticated Backpacks, and the Curios mod using the same versions as in E6 0.4.8. In that instance the bug was not reproducible. Hope this helps.

**Comment by Scorch-Mechanic** [comment]
There's something funky going on here. I use ESDF and as a result my W key is bound to "open inventory", and I just replicated the bug by holding down E (my "forwards" key) and shift-clicking some netherrack.

**Comment by P3pp3rF1y** [comment]
new release on CF fixes this issue https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/3256043

**Comment by NillerMedDild** [comment]
Damn you're fast, thanks!
