### ISSUE TITLE
More effective cooling (or heating) options for PNC?

### ISSUE THREAD

**Issue by BlueStriker101** [NillerMedDild/Enigmatica6#1869]
**Description**
I noticed that new coolants were added to Powah that are semi-compatible with PNC compressor cooling. However, through my testing with something like the dry ice, the only thing that really seems to be affected by it is the vortex tube. This is very nice for generating a lot of heat, but it seems that active cooling for compressors just isn't a thing. Perhaps this could be changed? That and some sort of opposite to dry ice that provides massive heat and a long heat capacity to generate very low temps on a vortex tube.

**Comment by MuteTiefling** [comment]
A lot of heating and cooling blocks were recently added to PNC, and we've added a few as well. Most anything that makes sense as a source is pretty much already there. 

They're now listed in JEI for convenience. Check uses on Heat Pipes to see a full list.

Dry Ice, for instance, is -100 C, but has a highish thermal resistance of 200. So it transfers cooling into a compressor very slowly. It doesn't take much for a compressor to overwhelm it. 

Active cooling is somewhat viable if a Grate is pointed at your heat sinks at -very- low pressure, however. If you just let it run wild, however, you'll be spending so much air on cooling that you would have been better off just running a second compressor instead. 

As for very high heat, maybe take a look at the Blaze Burner from Create. There's compatibility there now and it gets -very- hot when super-heated with a blaze cake.
