### ISSUE TITLE
0.4.7 Integrated Dynamics Squeezer

### ISSUE THREAD

**Issue by Chrysheart** [NillerMedDild/Enigmatica6#1870]
0.4.7
I don't know if this has been fixed or if anyone else has mentioned the issue, but when I have a dank in my inventory I can't place menril logs into the integrated dynamics squeezer. I am not trying to put them in there FROM the dank, just put them in there at all. I have to put the dank in my backpack and then I can do it.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I can't reproduce this on 0.4.8, so I hope it's fixed - Please let me know if not and I'll reopen :)

**Comment by corsetry** [comment]
Still an issue. Just tested this.

Steps:

Have max rank Dank in inventory
Try to add anything to the squeezer
Nothing happens

Remove Dank from inventory
Works normally

Running 0.4.8

**Comment by OneLemonyBoi** [comment]
If i had to guess, that is a dank null issue, it may be overriding something improperly

**Comment by NillerMedDild** [comment]
I still can't reproduce the issue. Do you have anything in your offhand or something? Could you perhaps make a video of it?

**Comment by NillerMedDild** [comment]
Closed due to lack of response. Will re-open if someone can explain how to reproduce it, the outlined steps do not reproduce the issue for me.
