### ISSUE TITLE
[0.4.8] Tetra goes off screen

### ISSUE THREAD

**Issue by Rocksnotch** [NillerMedDild/Enigmatica6#1873]
**Modpack version**
E6 0.4.8

**Describe the bug**
Tetra materials list and what they do in the mods 'book' goes off screen. see this issue from E5 as well but that seemed fix, so no idea why it's super happening again. Screenshot below will show it better.

**Screenshots**
![Oa6mKn5](https://user-images.githubusercontent.com/25090722/113072077-219c2280-9194-11eb-98b3-ac7d252a9b22.png)

**Comment by NillerMedDild** [comment]
Scroll to see the rest :)
