### ISSUE TITLE
0.4.8 Mod interaction? causing enchant levels to rise on items unintentionally.

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica6#1874]
0.4.8

**Describe the bug**
Wearing a resplendent prism from Astral with +# to existing enchants(maybe others) and having an ars spell book in your offhand w/ a break spell involving fortune. The item in your mainhand, will increase levels on its enchants everytime you use the break spell in your offhand.

**Screenshots**
![image](https://user-images.githubusercontent.com/10382598/113074781-b6554f00-9199-11eb-8d59-ff36817e37c8.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
