### ISSUE TITLE
Broken Heart Charm is broken

### ISSUE THREAD

**Issue by CryoChick** [NillerMedDild/Enigmatica6#1877]
**Modpack version**
Enigmatica 6 v 0.4.8

**Describe the bug**
Bonus hearts from Spice of Life get permanently destroyed when the Broken Heart charm from Bountiful Baubles activates. Sleeping does not regenerate like the item states.

**Screenshots**
The saturation should be healing to 13 hearts according to the food book but it doesn't heal past 11
![image](https://user-images.githubusercontent.com/81686836/113135062-4372c500-91e7-11eb-8241-7c0e0d721e6d.png)

**Comment by TemperedFool** [comment]
Known issue since at least 1.15 I think. Relogging should fix it.

**Comment by NillerMedDild** [comment]
Sleeping only regens 4 half hearts per time, does sleeping more help?
