### ISSUE TITLE
[0.4.8] Pneumaticcraft drone not doing right click when dispensed by dispenser on a loaded ftb chunk

### ISSUE THREAD

**Issue by aqpoyo** [NillerMedDild/Enigmatica6#1878]
**Modpack version**
Version 0.4.8

Hi. this morning I just updated from 0.4.5 to the latest version, I have an automatic system with eidolon and pneumatic craft drone to automate to pass the night. It was working perfectly before I updated in a chunk loaded with the ftb loader. I try many different things to make it work again and I realized if I was the one putting the drone in the ground it was working good but if the drone was dispensed from a dispenser it didn't made the right click to put the items in the stone hand. I rewrite the drone code from scratch and still only working if I was the one placing the drone myself instead of the dispenser.  I tried to move the hand to a different place in the same chunk and still the same, Then I moved the hand to another chunk which wasn't loaded with the ftb loader and it worked.

So if a drone is dispensed with a dispenser it will not do the right click action on a loaded chunk with the ftb loader. I try with a  quantum entangloporter with an anchor upgrade and it does work with the dispenser. So there must be an issue with the ftb loader and the permissions of the drone when dispensed from a dispenser.

Thanks and keep up the good work, love this pack!

**Comment by MuteTiefling** [comment]
This sounds like an issue with the fake player. It's likely getting a different fake player ID when dispensed, and so needs to get allied again.

**Comment by NillerMedDild** [comment]
Does the above fix work for you? :)

**Comment by aqpoyo** [comment]
What fix? the thing MuteTiefling said? I don't know what is a fake player id or how to get allied it again. For now I just changed the ftb loader chunk to the quantum entangloporter and it does work.
