### ISSUE TITLE
[0.4.8] stone slabs and stairs overly eager to be crafted

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1879]
**Modpack version**
0.4.8
**Describe the bug**
You are able to craft plain stone slabs/stairs with non "stone" stone. eg gabbro can make plain stone stairs, or pnc reinforced stone can make plain stone slabs. I presume due to the catchall recipe additions for being able to use non-plain stone for other recipes.

**Comment by NillerMedDild** [comment]
This would be rather hellish to fix, I'd rather leave it in tbh, it's not doing much harm imo :D

**Comment by Random832** [comment]
Can reinforced stone at least be excluded from the tag? I dont' know how many times I've almost made regular stone bricks instead of reinforced ones, or reinforced stone out of other reinforced stone, and I've actually done it several times.

**Comment by NillerMedDild** [comment]
Due to a recent update in KubeJS this is no longer hellish to fix 😄 will work on it.

**Comment by Erysch** [comment]
> Can reinforced stone at least be excluded from the tag? I dont' know how many times I've almost made regular stone bricks instead of reinforced ones, or reinforced stone out of other reinforced stone, and I've actually done it several times.

Have the same issue and I am too lazy to  take the correct stone out of the system 😂 so I then waste the reinforced stone
