### ISSUE TITLE
[0.4.8] Chisel and Bits textures messed up

### ISSUE THREAD

**Issue by WitchyKippy** [NillerMedDild/Enigmatica6#1884]
**1.16.5 0.4.8**

**Describe the bug**
After updating, majority of my chisel and bits are now the incorrect texture. for instance. anything that was created out of Ebony planks, is now a mostly transparent texture for the "Demon Seed" plant
![bug1](https://user-images.githubusercontent.com/81736264/113250752-f4c03c00-9275-11eb-95a9-868503487d22.jpg)
![bug2](https://user-images.githubusercontent.com/81736264/113250754-f558d280-9275-11eb-970e-9418dda1220d.jpg)
![bug3](https://user-images.githubusercontent.com/81736264/113250756-f558d280-9275-11eb-945e-9c05668c9ef4.jpg)
![bug4](https://user-images.githubusercontent.com/81736264/113250757-f558d280-9275-11eb-8b47-848d60fff82b.jpg)
![bug5](https://user-images.githubusercontent.com/81736264/113250758-f5f16900-9275-11eb-822a-e23c0fd7988e.jpg)
![the pine used to be Lament](https://user-images.githubusercontent.com/81736264/113250759-f5f16900-9275-11eb-9d5a-cb8af87c790c.jpg)

**Screenshots**

**Comment by Merlo17** [comment]
If you have backups, see https://github.com/NillerMedDild/Enigmatica6/issues/1668

**Comment by Rodg88** [comment]
I had minor issues with C&B updating from 4.3 to 4.8, even when I updated C&B manually. But it was just limestone bricks to polished limestone. So still might have issues, but if you revert the pack back to .4.3 (or whatever it was when it was good), restore from a backup so your bits are correct again, then manually update C&B, and finally update the pack to .4.8, the bits might at least be *less* weird
