### ISSUE TITLE
Increase Thermodynamic Output Between Fusion Reactors and Thermoelectric Boilers

### ISSUE THREAD

**Issue by RobuxShooters** [NillerMedDild/Enigmatica6#1885]
**Description**
In the questline for Mekanism, Thermoelectric Boilers are used to cool down heated sodium and produce cooled sodium and steam to be used for generating energy and cooling the fission reactor. After a fusion reactor is built, the heat produced from the fusion reaction can instead be used to heat water externally through the thermoelectric boiler to generate steam as opposed to piping water directly into the fusion reactor. The steam produced from the thermoelectric boiler can then be piped into the industrial turbine for energy generation. This secondary use of the thermoelectric boiler with the fusion reactor is not mentioned in the quests.

My suggestion here is to increase the amount of heat that can be conducted from the fusion reactor to the thermoelectric boiler while not changing passive fusion rates such that more steam is produced from using the thermoelectric boiler as opposed to just piping water into the fusion reactor and extracting steam from it.

In addition, another suggestion would be to mention that the thermoelectric boiler has this secondary use of heating water with the heat from the fusion reactor in the quests.

**Why would you like this added/changed?**
Currently as it stands, piping water into the fusion reactor (at an injection rate of 40) and extracting steam from it generates around 825000 mB/t of steam whereas having heavier infrastructure (the thermoelectric boiler, using thermodynamic conductors, and also using more space) with the same burn rate only generates 605000 mB/t of steam. This results in an overall loss in generation of 150-200 kFE/t although heavier infrastructure is used.

Besides, in default Mekanism, using a thermoelectric boiler can generate 3,000,000 mB/t of steam with a base injection rate of 2 (air cooled) while an injection rate of 80 is required for the same amount of steam when water cooled, showing that a thermoelectric boiler greatly increases the efficiency of steam production.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/16001607/113289620-057abb80-9323-11eb-8ce4-551e398fd160.png)
![image](https://user-images.githubusercontent.com/16001607/113289661-13304100-9323-11eb-83b5-e8e8fc4989ff.png)

**Comment by telemenar** [comment]
How are you connecting your fusion reactor to your boiler? The Mekanism Thermodynamic cables are /very/ lossy. You likely want 0-1 blocks of space between your reactor and your boiler. (Or possibly Quantum Entangloporters) 

If you are not losing a bunch of heat to the cables I’ve found this to produce like 10x rates of feeding water directly into the reactor. (Though the last time I tested this was in E6 0.2)

**Comment by telemenar** [comment]
Oh interesting. Actually looking at your screenshots, your are limited by the construction of the boiler. Not sure whether it is a size limit or related to the number of super heating coils.

**Comment by RobuxShooters** [comment]
> How are you connecting your fusion reactor to your boiler? The Mekanism Thermodynamic cables are /very/ lossy. You likely want 0-1 blocks of space between your reactor and your boiler. (Or possibly Quantum Entangloporters)
> 
> If you are not losing a bunch of heat to the cables I’ve found this to produce like 10x rates of feeding water directly into the reactor. (Though the last time I tested this was in E6 0.2)

I'll try using the Quantum Entangloporters to check whether it's due to the loss of heat to the environment. As of now, I have 6 ultimate thermodynamic conductors conducting heat from the fusion reactor to the boiler.

> Oh interesting. Actually looking at your screenshots, your are limited by the construction of the boiler. Not sure whether it is a size limit or related to the number of super heating coils.

I don't think this should be the case. Let me add a few more screenshots for the statistics of the boiler and the turbine.
![image](https://user-images.githubusercontent.com/16001607/113331524-a896f980-9352-11eb-9f12-731d347b3fa6.png)
![image](https://user-images.githubusercontent.com/16001607/113331577-b77dac00-9352-11eb-8115-3ef68bebfc8f.png)

I've adjusted the injection rate from 40 to 42 to test whether the temperature bar on the left in the boiler being maximum indicates 'maximum temperature achievable'. Increasing the injection rate to 42 allows the temperature to continue increasing, so it shouldn't be limited by the boiler.

**Comment by RobuxShooters** [comment]
Okay, I didn't think the thermodynamic cables were **that** lossy. After building the boiler right up against the reactor ports, I'm getting a temperature of around 3.82 kK instead of 2.5 kK. This increased the amount of steam output from 605,000 mB/t to 978,000 mB/t with the same injection rate of 40, hence providing an extra 150,000 mB/t of steam compared to water cooling. So, it's not exactly an extreme efficiency improvement, but still fine I guess.

Still, should the temperature output to the thermoelectric boiler be increased, considering the resource investment to build a boiler? I'll leave that up to the devs to decide. (Just a note: building the boiler right up against the fusion reactor brought down the plasma temperature from 330 MK to 134 MK, so it's very risky to set this up at a minimum injection rate of 14, since the plasma should be above 100 MK at all times.)

I think the quests should also mention you can make steam production a little more efficient with a thermoelectric boiler and to build the thermoelectric boiler close to the fusion reactor to prevent heat loss.

**Comment by telemenar** [comment]
@MuteTiefling — If you wanted to buff this I think that tuning this config higher would boost the ability to transfer heat out to the boiler: https://github.com/NillerMedDild/Enigmatica6/blob/master/config/Mekanism/generators.toml#L88

**Comment by MuteTiefling** [comment]
I love that this discussion is even a thing and feel that it wouldn't be if the base numbers were higher. How often do people even bother to try to maximize the output of their fusion by building this extra infrastructure?

That said, I honestly think power is in a pretty good spot here. It's not absurd, but you can get decent gains by putting in some work as shown above, or by using d-t fuel. 

That was, in fact, one of my goals with the reduction in output, both passive and otherwise. If you are still interested in getting big numbers, you've got to put in some effort. You won't get there simply by slapping down a fusion reactor and using the passive generation. 

I will add a note to the Fusion Reactor quest though. It already mentions using d-t fuel as a way to boost it and adding a mention for this is simple enough.

**Comment by MuteTiefling** [comment]
Quest has now been updated.
