### ISSUE TITLE
{Mod Suggestion} Tinkers construct

### ISSUE THREAD

**Issue by CletusMAngo** [NillerMedDild/Enigmatica6#1886]
I know you guys have been keeping an eye on this so im just putting it here cause it finally ported :P 
https://www.curseforge.com/minecraft/mc-mods/tinkers-construct

**Comment by shibeobi12** [comment]
I might be missing it but I just see 1.12 versions in the downloads?

**Comment by CletusMAngo** [comment]
> I might be missing it but I just see 1.12 versions in the downloads?

![image](https://user-images.githubusercontent.com/76655777/113329041-60111900-931d-11eb-8f40-af8cb6b2a396.png)
Look closer friend

**Comment by CletusMAngo** [comment]
![2021-04-01_17 49 18](https://user-images.githubusercontent.com/76655777/113329134-8040d800-931d-11eb-8dcf-6cdf9d9d238f.png)
Heres also some more proof that its not an april fools joke

**Comment by shibeobi12** [comment]
Sneaky all files....
I swear.
![image](https://user-images.githubusercontent.com/50844560/113329518-e9ebc280-92da-11eb-8a9e-e8e758516e53.png)
Exciting news!

**Comment by NillerMedDild** [comment]
I'll have a look tomorrow if the file is still there :P

**Comment by MuteTiefling** [comment]
Bit unfortunate that they skipped the documentation. Seems like enough has changed that even cursory documentation would be very helpful. 

![image](https://user-images.githubusercontent.com/9543430/113538697-e3df3580-95a9-11eb-89c6-7f342567649b.png)

That's not even in >.<

**Comment by Chtholly-dev** [comment]
This is just a small error on their side. The mod just got released and it still has a way to go so better leave it like this for now.

**Comment by MuteTiefling** [comment]
Yeah, I'd vote for waiting, personally.

**Comment by Pixelingot** [comment]
Is there any futher information on this?

**Comment by TemperedFool** [comment]
It's being evaluated. It's still in alpha, so probably a little early for inclusion, but that will probably depend on how stable and functional an alpha it is.

**Comment by DarkAngel22579** [comment]
I don't think it should be added until phase two at least. A lot more content is being added, including some minor worldgen changes, and the documentation should be finished by then.

Temporary documentation is [here](https://github.com/SlimeKnights/TinkersConstruct/wiki/New-in-Tinkers%27-Construct-3).
And the roadmap for planned changes is [here](https://github.com/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-Roadmap).

**Comment by NillerMedDild** [comment]
We're gonna wait a bit :)

**Comment by pm065** [comment]
I'm curious; will TiC, when added, get custom materials done with datapacks? Because I'm not sure that functionality is completely implemented, as I don't see any way of making new molten substances in the wiki. Does that have to be done with an actual mod?

**Comment by NillerMedDild** [comment]
We haven't discussed that atm :)

**Comment by pm065** [comment]
> We haven't discussed that atm :)

It's now possible thanks to the wonders of KubeJS: https://github.com/NillerMedDild/Enigmatica6/discussions/2294
