### ISSUE TITLE
[0.4.8] See through / fully transparent quark slate block when placing using building gadget

### ISSUE THREAD

**Issue by chloecoding-git** [NillerMedDild/Enigmatica6#1890]
**Modpack version**
0.4.8
**Describe the bug**
When using the building gadget or copy and paste gadget, with the block Slate - from the mod quark, thus Quark Slate specifically, it will cause the blocks to render in as transparent (seeing through the texture of the block) or fully transparent (seeing no block texture at all, but the block still being present, yet able to see the world as if it was not there).

**Screenshots**
https://discord.com/channels/195234321836146688/544589452492931076/827469362877038622 - A link to the #support channel in the discord for the modpack, I attempted to get help here but it appears I was ignored.

**Comment by Rodg88** [comment]
I've had this happen with other blocks too, at least engineer's decor dark shingle blocks, and panzer glass

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by mouseas** [comment]
I've had this with Quark's Slate, and Quark's Iron Plate blocks.

**Comment by NillerMedDild** [comment]
Someone beat me to it and reported the bug here: https://github.com/Direwolf20-MC/BuildingGadgets/issues/625 😄
