### ISSUE TITLE
[0.4.8] Kinetic Dynamo not Working

### ISSUE THREAD

**Issue by JeanRdSz** [NillerMedDild/Enigmatica6#1894]
4.0.8

I tried everything, but Kinetic Dynamo doesn't generate any FE

![image](https://user-images.githubusercontent.com/81846511/113469903-a2268180-9427-11eb-94b9-b709a56f2c19.png)

https://user-images.githubusercontent.com/81846511/113469925-c5e9c780-9427-11eb-86e6-480e902880ef.mp4

**Comment by TemperedFool** [comment]
You need to place the dynamo, and then attach the windmill or water wheel to it. Also, have you tried wiring it to anything (like a battery)? TOP generally won't indicate there's power in the dynamo in my experience.

**Comment by JeanRdSz** [comment]
> You need to place the dynamo, and then attach the windmill or water wheel to it. Also, have you tried wiring it to anything (like a battery)? TOP generally won't indicate there's power in the dynamo in my experience.

I used the Energy Cube as you can see in the video, and I attached the mills to the dynamo tho, but none of these worked

**Comment by TemperedFool** [comment]
Ah, didn't see the video. The orange spot on the dynamo is the output, so I think you have the cube against the wrong side.

Fwiw, this kind of issue is best dealt with on the Discord: https://discord.gg/GxXsSCNK
