### ISSUE TITLE
Elemental Craft

### ISSUE THREAD

**Issue by jmarakelian** [NillerMedDild/Enigmatica6#1896]
https://www.curseforge.com/minecraft/mc-mods/elemental-craft

**Mod description**
Magic/Tech mod that combines the two to give something unique but flavored. Has an elemental source based system that draws elemental energy from sources found out in the world in order to create new materials and powerful machine-like shrines. Has some rewarding systems like Pure Infusion which is similar to Empowering from Actually Additions.

**Why would you like the mod added?**
I personally really enjoyed the mod in my own play through of ATM 6 when I decided to start a new world off with ElementalCraft as a big focus for myself to learn about the mod. I think that one of its real sources of potential is the Pure Infuser. Works very similarly to the Empowerer from Actually Additions.

The power system from ElementalCraft is also very unique, and encourages quite a lot of work exploring depending on the decided upon rarity of the elemental orbs.

Another couple of very cool systems are the different shrines, which provide in-mod solutions to different world interactions like crop growth, mining of a chunk, vacuum collection and more.

Another source for gating or something along that route is the different infusing processes based on the source element as well as element binding to do multi-item larger scale crafts.

Two unique ingots for gating through the mod as well.

Mod itself is well balanced. It is definitely rewarding for the time put in for the different systems it gives access to.

**Screenshots if applicable.**

**Comment by NillerMedDild** [comment]
I checked it out for the third time, and I'm still not a fan I'm afraid. It just feels off to me.
