### ISSUE TITLE
astral sorcery crystal ore

### ISSUE THREAD

**Issue by noa12390** [NillerMedDild/Enigmatica6#1897]
**Description**
as is astral crystal ore will only spawn in normal minecraft stone and nothing else and that is kind of rare to the point that finding the ore is very hard any more this gets more fun when you take in that astral crystal breeding now needs you to active mine more to get crystals to split and merge for what you need which is rather hard to do if the or is next to non existant in the over world since that is the only place it spawns

**Why would you like this added/changed?**
if you could please set other stone types to have it also spawn in since as is your going to need to search a good chunk of the over world to find what you need and ya that will be frowned on for servers

**Screenshots if applicable.**

**Comment by HaxtonSale1** [comment]
you can grow crystal clusters, even with Celestial crystals.

**Comment by noa12390** [comment]
to grow the crystal clusters which are the blue crystals you need the normal rock crystals and the ore for that only spawns in normal minecraft stone and then only in the over world if you can't find that you will never grow the crystal clusters which are the tech 2 for the crystals where you then need to go through the whole splitting and merging all over again with the old system all you needed to do was just find some crystal ore mine it and grow more in star light it now can't be done that way any longer 

you now need to mine up a lot of rock crystal ore to get the rock crystals to split and merge for the new sytem

**Comment by noa12390** [comment]
the quest rewards so 8 chunks of ore which unless you have a pick with looting 3 you may get 6 crystals and even then there is rather good chance those will need have addons that are needed or can be merged i would know went through that then needed to track down around 30 more ore and that still not enuff unlike the ore in sand which you can make there is no way to make more rock crystal ore

**Comment by HaxtonSale1** [comment]
> to grow the crystal clusters which are the blue crystals you need the normal rock crystals

I just stated that: 
> you can grow crystal clusters, even with Celestial crystals

**Comment by CuboidDroid** [comment]
An alternative might be to add a recipe. Something like nether quartz chunk, dimensional shard chunk and diamond chunk in an energizing orb with 2 mil RF for a rock crystal ore. I.e. Not cheap or simple, but an achievable alternative that can be used on servers

**Comment by HaxtonSale1** [comment]
- Split celestial crystals to minimum size
- Make them into crystal clusters
- Harvest
- Repeat

works pretty well imo

**Comment by TemperedFool** [comment]
@noa12390 have you tried using the resonating wand at night to find the ore? You'll see sparkles over where the ore is, and you can dig down to bedrock from there.

You also don't need many crystals, as already mentioned. Split a crystal down to the point where each resulting crystal has one attribute; soak one of them in starlight to increase its size, and split it again. Easy way to grow and make more crystals.

**Comment by NillerMedDild** [comment]
Rock Crystal is not limited to spawning in Stone, it can spawn in any block with the tag `minecraft:base_stone_overworld`
