### ISSUE TITLE
Mekanism fission reaction meltdown upon world load

### ISSUE THREAD

**Issue by EPostill** [NillerMedDild/Enigmatica6#19]
**Modpack version**
0.2.0

**Issue**
3 attempts of loading my world result in my fission reactor melting down instantly
only fix I have for now is disabling meltdowns in the mekanism config

**Comment by NillerMedDild** [comment]
Well that sucks, I'll try to figure out why :)

**Comment by NillerMedDild** [comment]
I found this is the changelog: `Don't allow external heat transfer from Fission Reactor (only environmental)`, could that be the issue you were experiencing?

**Comment by Kataiser9** [comment]
Just to provide another data point - my fission reactor has not suffered this problem. Maybe it has more of a coolant buffer, or it's something to do with the fact that it's contained in a single chunk?
