### ISSUE TITLE
[0.4.8] Basalz not spawning in mountain biomes

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1900]
**Modpack version**
0.4.8
**Describe the bug**
I've been looking at mountain biomes for basalz, checked cika mountains and alps, which were the closest options to me, but no basalz spawned. There were blizzes in alps. I have In-Control installed blocking normal vanilla mob spawns, so thermal mobs are quite common in my instance, but badlands seems to be the only biome type that basalz spawn in. So maybe a spawning bug in thermal, or a TF thing? Not sure if it's configurable on E6's side

**Comment by NillerMedDild** [comment]
I think you will need a mesa or something like that, I'm not sure the few mountain types we have really count.

> The Basalz spawns naturally in barren or mountainous biomes.

**Comment by NillerMedDild** [comment]
Ah, look for the Badlands biome - their spawn weight seems to be a bit low though.
