### ISSUE TITLE
[0.48] Server Crashes when breaking Pneumeticraft Multiblock

### ISSUE THREAD

**Issue by Pixelingot** [NillerMedDild/Enigmatica6#1901]
for 0.48

After using the machine that turns a fluid into Biodesiel etc when broken it causes a server crash

**Comment by anivlys** [comment]
Do you mean the Fluid Mixer with Ethanol & Vegetable Oil making Biodiesel or the Refinery Multiblock that makes up to four different fluids from oil?

If it is the refinery it has already been reported in #1887 and already fixed in a PneumaticCraft update (not yet updated in E6).
