### ISSUE TITLE
No Recipe For Sap or Syrup Bottles

### ISSUE THREAD

**Issue by Tsilkani** [NillerMedDild/Enigmatica6#1906]
Version 0.4.8

The only recipes in JEI for Syrup Bottles are various ways of cooking Sap Bottles, and there is nothing in JEI for making Sap Bottles. Trying to use a Glass Bottle on an Arboreal Accumulator or tank of Sap doesn't work, and neither does Create's Spout or Thermal's Fluid Encapsulator.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
Sap is obtained from the Arboreal Extractor on Maple and Dark Oak trees. The fluid can be sent to a Fluid Encapsulator to bottle it. 

Don't know if this is showing in 0.4.8 but it's effectively fixed next version :D

**Comment by HaxtonSale1** [comment]
Team Abnormals' way of obtaining Sap is using a glass bottle on a stripped maple log, if it has different texture then you can get Sap. 
But yeah, Thermal way removes a significant tedium

**Comment by MuteTiefling** [comment]
Yep. I've actually just added a JEI description to describe that process and am in the process of double checking some recipes surrounding sap, syrup, and tree extraction in general.
