### ISSUE TITLE
Decorative Blocks Compat

### ISSUE THREAD

**Issue by pm065** [NillerMedDild/Enigmatica6#1908]
Link:
https://www.curseforge.com/minecraft/mc-mods/tetra-pak

Description:
This mod appears to add cross-compat between Tetra and Create, which I don't think is in Tetranomicon nor Tetra.

Reasoning:
It would be pretty cool to be able to make a Shadow Steel sword (: 
It seems to have appeared only three days ago so I guess no one's noticed it yet.
The description says it adds support for Andesite Alloy, Brass, Shadow Steel and Refined Radiance, with SS and RR having special abilities (sadly, with FTB Ultimine, Refined Radiance's ability becomes useless, as it gives axes and adzes the ability to chop down whole trees at once like the Deforester does.)
The only known issue is:

> Known Issues: Refined Radiance and Shadow Steel's effects don't synergize as expected. This is because Refined Radiance tools use the exact same code as Create's Deforester, which currently doesn't check anything about the tool you're using. Don't go bug them about it, though. It's on their list. :)

which appears to be a problem with Create, if I'm understanding it correctly.

EDIT: Here's a couple more compat patches you may be interested in:
https://www.curseforge.com/minecraft/mc-mods/decorative-blocks-modded-compat
Decorative Blocks support for a couple of the Abnormals mods

https://www.curseforge.com/minecraft/mc-mods/farmers-delight-compats
Adds FD support for a couple mods other than Abnormals (Aquaculture, BYG, BetterEnd, Decorative Blocks, Quark, Valhesia Structures...)

**Comment by NillerMedDild** [comment]
>  https://www.curseforge.com/minecraft/mc-mods/tetra-pak
We already have Tetra compat in the pack, through a datapack. It's not as interesting as the compat Tetra-pak offers though, so maybe we'll add it down the line, but it won't be before a major update.

> https://www.curseforge.com/minecraft/mc-mods/decorative-blocks-modded-compat
Sure

> https://www.curseforge.com/minecraft/mc-mods/farmers-delight-compats
Duplicate #1655
