### ISSUE TITLE
Twilight Forest

### ISSUE THREAD

**Issue by CletusMAngo** [NillerMedDild/Enigmatica6#1909]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest

**Mod description**
I feel like the description is pretty much known at this point :p 

**Why would you like the mod added?**
Even though its not finished i believe the mod can actually have a new approach to the modpack with its new databased spawning, you guys can make the twilight forest have worth while loot in the final castle such as: Antimatter,Polonium,Totems of undying, Machine casing, Artifacts anything that would make actually progressing through the twilight forest worth whole, you guys could even buff the bosses up so it makes the fights alot more challenging 

Hope it makes it into the pack :)

**Comment by NillerMedDild** [comment]
I'll check out it's state but I will most likely not add it to be honest. It has been very performance heavy in the past, and I'd like to stear clear of that.

**Comment by NillerMedDild** [comment]
Loading my test world after having added Twilight took 3-5 minutes longer than usual, I'll just mark this as blocked for now.

**Comment by CletusMAngo** [comment]
Best to wait for it to have a full release, i understand :)

**Comment by EightBitRG** [comment]
They did update the mod just 4 days ago, and it isn't showing that it is a beta version of it. I would love to have some option for hard bosses to fight for the endgame

**Comment by CletusMAngo** [comment]
Honestly this would feel like a bit much now seeing as we're gonna have Undergarden And Atum but its down to you guys at the end of the day

**Comment by MuteTiefling** [comment]
> I would love to have some option for hard bosses to fight for the endgame

I would too, but TF isn't that. The bosses are only tough if played standalone with no access to anything from other mods.

**Comment by CletusMAngo** [comment]
> Honestly this would feel like a bit much now seeing as we're gonna have Undergarden And Atum but its down to you guys at the end of the day

**Comment by CletusMAngo** [comment]
Oops sry i accidentally closed this uh thats my bad XD

**Comment by CletusMAngo** [comment]
I was gonna make a comment on how this would effect the load times with Atum and Undergarden included in the pack

**Comment by NillerMedDild** [comment]
We'd rather go with different dimensions this time around, and leave TF out to avoid increasing load times and such :)

**Comment by NillerMedDild** [comment]
The increased load on CPU and startup time seems neglible now tbf, just in case anyone is lurking here trying to spot issues :P

**Comment by g0urra** [comment]
Now with RFTools Dimensions removed as part of the pack, and Twilight Forest having a 1.16.5 Release candidate on August 5, has there been any reconsideration whether Twilight Forest might be added to the pack?

**Comment by theboo** [comment]
Have they finished the final castle?

**Comment by g0urra** [comment]
Nevermind, the latest "Release" for 1.16 says "THIS IS THE LAST BETA FOR 1.16" and that they are moving to 1.17. Disregard this.
