### ISSUE TITLE
[0.4.8] Better End Stones Stonecutting

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1911]
**Modpack version**
0.4.8
**Describe the bug**
Plain soapstone from byg byg:soapstone can only be turned into slabs/walls/stairs in the stonecutter, so the smooth/brick etc variants are unobtainable

Also speaking of stonecutter, BetterEnd Forge stone should probably get a stonecutter pass too - flavolite/violecite/sulphuric_rock polished/bricks/tiles/pillar

**Comment by NillerMedDild** [comment]
> Plain soapstone from byg byg:soapstone can only be turned into slabs/walls/stairs in the stonecutter, so the smooth/brick etc variants are unobtainable

That is fixed in-dev, probably by ochotonida :D

**Comment by MuteTiefling** [comment]
taking a look at these.
