### ISSUE TITLE
[0.4.8] Nether quartz chunks give more quartz in enrichment chamber

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#1913]
**Modpack version**
0.4.8
**Describe the bug**
Enrichment chamber recipe for nether quartz ore/chunks seems unbalanced compared to the other options in the pack, giving 6 per ore, vs about 3 (+sulfer) for a pulverizer with basalz, or 4 (plus sulfer) in an induction smelter with cinnabar, 3 from IE or pedestals crushing, and ~4 from create crushing

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
