### ISSUE TITLE
Nature's Starlight

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1914]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/natures-starlight

**Mod description**
Write a short description of the mod here.

**Why would you like the mod added?**

**Screenshots if applicable.**

**Comment by Flabort** [comment]
Well, I made the mistake of not searching for if this suggestion already existed.

Glad to see it's already on your radar
