### ISSUE TITLE
RS Large Patterns

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1915]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/rslargepatterns

**Mod description**
Write a short description of the mod here.

**Why would you like the mod added?**

**Screenshots if applicable.**

**Comment by TemperedFool** [comment]
But why would we need large patterns? 😉

**Comment by KrAzYGEEK32** [comment]
Expert mode hype!? \o/
