### ISSUE TITLE
Iron Jetpacks

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#1916]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/iron-jetpacks

**Mod description**
Extremely configurable Jetpack mod, investigating in stead of #1488 

**Why would you like the mod added?**
More flight options.

**Screenshots if applicable.**

**Comment by MuteTiefling** [comment]
wow these are still so fast as to be nearly unusable for building. But at least that can be modified.

**Comment by MuteTiefling** [comment]
Alright, been playing with them for a bit here and I think I've got some nice numbers to share. 

I've created our own progression. No side tiers, just straight upgrades.  Tier order and numbers are all easily changed, as I've made myself a spreadsheet to generate the JSON files. 

With this initial setup, I had a couple of goals: 
1. Make them costly to run and with a target flight time. This is, of course just on internal power. It's kind of expected that a player will either make a player transmitter from Powah or carry some form of portable storage. So the base tier would get about 2.5 minutes of actual flight time with no external source.
2. Make them feel... jumpy. That is to say, they are jet packs. they should move vertically pretty well. so vertical speed has been boosted a fair bit from default ranges. Even the lowest tier will help you quickly climb out of a hole or ravine.
3. Bring horizontal speeds down. By default they're silly fast, going 100+ meters per second at the top tier. I've instead aimed for roughly 32 m/s at the top end with an additional 30% sprint bonus at that tier. Lower tiers have considerably lower 'sprint bonuses' and are very inefficient while sprinting. Even at the top tier, sprinting will cost you. 

Having played around with them a bit in a test world, they feel pretty good. The early tiers would be pretty accessible to build early on, but difficult to power. They'd be for occasional use, effectively. Would be good incentive to upgrade power generation, I think. 

Numbers below:

| name      | disable | tier | color  | armorPoints | enchantability | craftingMaterial           | rarity | flight time (minutes) | capacity      | usage | speedVertical | accelVertical | target speed (m/s) | speedSideways | speedHoverDescend | speedHover | sprintSpeedMulti | sprintSpeedMultiVertical | sprintFuelMulti |
|-----------|---------|------|--------|-------------|----------------|----------------------------|--------|-----------------------|---------------|-------|---------------|---------------|--------------------|---------------|-------------------|------------|------------------|--------------------------|-----------------|
| bronze    | false   | 1    | ec9e3f | 5           | 9              | tag:forge:plates/bronze    | 0      | 2.5                   | 1,536,000     | 512   | 0.7           | 0.1           | 3.5                | 0.004         | 0.05              | 0.192      | 1.02             | 1.00                     | 2.94            |
| iron      | false   | 2    | c1c1c1 | 6           | 9              | tag:forge:plates/iron      | 0      | 5                     | 12,288,000    | 1024  | 0.77          | 0.1           | 7                  | 0.013         | 0.1               | 0.147      | 1.02             | 1.00                     | 2.94            |
| invar     | false   | 3    | 929d97 | 6           | 10             | tag:forge:plates/invar     | 1      | 7.5                   | 41,472,000    | 1536  | 0.84          | 0.11          | 10.5               | 0.028         | 0.15              | 0.108      | 1.02             | 1.00                     | 2.94            |
| osmium    | false   | 4    | 9fa4d0 | 6           | 10             | tag:forge:plates/osmium    | 1      | 10                    | 98,304,000    | 2048  | 0.91          | 0.12          | 14                 | 0.044         | 0.2               | 0.075      | 1.02             | 1.00                     | 2.94            |
| steel     | false   | 5    | 565656 | 7           | 12             | tag:forge:plates/steel     | 1      | 12.5                  | 192,000,000   | 2560  | 0.98          | 0.13          | 17.5               | 0.060         | 0.25              | 0.048      | 1.02             | 1.00                     | 2.94            |
| diamond   | false   | 6    | 4aedd1 | 8           | 15             | tag:forge:plates/diamond   | 2      | 15                    | 331,776,000   | 3072  | 1.05          | 0.14          | 21                 | 0.075         | 0.3               | 0.027      | 1.05             | 1.00                     | 2.85            |
| netherite | false   | 7    | 494649 | 8           | 15             | tag:forge:plates/netherite | 2      | 17.5                  | 526,848,000   | 3584  | 1.12          | 0.15          | 24.5               | 0.091         | 0.35              | 0.012      | 1.10             | 1.00                     | 2.70            |
| lumium    | false   | 8    | d9d26a | 5           | 25             | tag:forge:plates/lumium    | 2      | 20                    | 786,432,000   | 4096  | 1.19          | 0.16          | 28                 | 0.107         | 0.4               | 0.003      | 1.15             | 1.20                     | 2.55            |
| enderium  | false   | 9    | 0a4949 | 8           | 15             | tag:forge:plates/enderium  | 3      | 22.5                  | 1,119,744,000 | 4608  | 1.26          | 0.17          | 31.5               | 0.123         | 0.45              | 0.000      | 1.20             | 1.30                     | 2.40            |

**Comment by MuteTiefling** [comment]
Configs: [jetpacks.zip](https://github.com/NillerMedDild/Enigmatica6/files/6259588/jetpacks.zip)

**Comment by telemenar** [comment]
Is the Enderium intentionally less enchantable than the previous tier?

**Comment by MuteTiefling** [comment]
On second thought, for the tiers... maybe like this:

Basic (Powah)
Hardened (Powah)
Infused (Mek)
Blazing (Powah)
Reinforced (Mek)
Niotic (Powah)
Spirited (Powah)
Atomic (Mek)
Nitro (Powah)

**Comment by TemperedFool** [comment]
That is a lot of jetpacks...

**Comment by MuteTiefling** [comment]
kinda, yes :D

**Comment by sciguyryan** [comment]
One other advantage with Iron Jetpacks is that there is a curio for them too. Who doesn't love more curios?

**Comment by NillerMedDild** [comment]
> 
> 
> On second thought, for the tiers... maybe like this:
> 
> Basic (Powah)
> Hardened (Powah)
> Infused (Mek)
> Blazing (Powah)
> Reinforced (Mek)
> Niotic (Powah)
> Spirited (Powah)
> Atomic (Mek)
> Nitro (Powah)

Perhaps we should use Thermal over Mekanism, since Mekanism already offers flight natively:

- Basic (Powah)
- Invar (Thermal)
- Blazing (Powah)
- Signalum (Thermal)
- Niotic (Powah)
- Lumium (Thermal)
- Spirited (Powah)
- Enderium (Thermal)
- Nitro (Powah)

**Comment by ManiacRobertWasTaken** [comment]
Maybe it's worth take a look at https://www.curseforge.com/minecraft/mc-mods/curious-jetpacks too?
