### ISSUE TITLE
pneumaticcraft drone and mending tools

### ISSUE THREAD

**Issue by aqpoyo** [NillerMedDild/Enigmatica6#1918]
Hi. I don't know if this could be possible or not bur I am just gonna ask. I made a drone set up in which mobs are killed by a drone with a sentient sword and they pick up raw will with a tartaric gem and they when its full they leave it in a chest and they pick up a new one to keep on collecting will. The issue is that the sentient sword is enchanted with mending but it doesn't get repaired while the mobs are killed, I don't know if it's like that or it could be done so that the sword gets repaired.
Thanks in advance!

**Comment by MuteTiefling** [comment]
PNC drones don't even pick up XP unless specifically programmed to do so. The suggestion could certainly be made to PNC that picked up XP applies to mending enchanted items held by the drone. However, you've got some fancy tools for doing this within the pack already, fully automatically. 

First, a smart drone can periodically check the damage of the held item, dropping it off somewhere to await repair. 
That 'somewhere' could be an inventory below an XP Anvil Pedestal. When supplied with XP through the Pedestals network, this will auto repair items using only the XP.  The repaired item is then brought into the Pedestal's inventory itself. 

Finally, the drone could be programmed to wait for that fully repaired item in the pedestal, extract it, and continue on it's way. Two swords could be used instead so it only has to drop one off and pick up the previously repaired one. That results in less downtime.

**Comment by aqpoyo** [comment]
Yep that was what I though about doing if the tool could not be repaired bye itself. Thanks!

**Comment by NillerMedDild** [comment]
Closed this too fast :P 
I've suggested that mending works for drones here: https://github.com/TeamPneumatic/pnc-repressurized/issues/784

**Comment by aqpoyo** [comment]
Actually all this would be easier if the blood magic had the Gathering of Forsaken Souls back. Let's hope it's added in the future.

**Comment by aqpoyo** [comment]
Well I finally made the full automation with the drone with 2 swords, some pedestals, some modular routers and I get all the 4 different will automated. Here is an image of the drone program if someone is interested.

![image](https://i.imgur.com/4W2LloQ.png)

**Comment by MuteTiefling** [comment]
On the left of your screen there is an option to export that as a text file. Highly recommend saving it out, uploading it to something like Gist and sharing it in the PNC Discord: https://discord.gg/Zf5XwbfBRj

I'm sure it'll help some folks :D
