### ISSUE TITLE
Mobs don't drop experience in other dimensions than overworld

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#192]
**Modpack version**
0.2.12

**Issue**
Hello,
In the nether and the end (and ratlantis), mobs killed by a player don't drop xp. 
It's pretty easy to reproduce, just go in any dim but the overworld and kill a mob. You sometimes see the xp orb but it instantly vanishes.
thanks :)
Jin

**Comment by Darkere** [comment]
Reported here: https://github.com/jaredlll08/Clumps/issues/39
