### ISSUE TITLE
[0.4.8] Map does not change when going underground and waypoints missing

### ISSUE THREAD

**Issue by Taubin** [NillerMedDild/Enigmatica6#1920]
**Modpack version**

Enigmatica 6 - 0.4.8

Server: 
Enigmatica 6 Server - 0.4.8

**Describe the bug**
The map in game does not change when going underground and there is no option for way points. The map will only show the above ground no matter what level I'm at. There are no map options other than opening the map in the options as well. 

**Logs**
latest.log:
https://gist.github.com/Taubin/2781f2912b580310848923e709634691

**Screenshots**
![2021-04-05_11 33 06](https://user-images.githubusercontent.com/8891792/113616234-f2f8dd00-96a8-11eb-9cf0-8a3c8e6cdf47.png)
![2021-04-05_13 52 29](https://user-images.githubusercontent.com/8891792/113616244-f5f3cd80-96a8-11eb-943c-0579fa7853cb.png)
![map](https://user-images.githubusercontent.com/8891792/113617374-5afbf300-96aa-11eb-9158-60d744d1a9cd.jpg)

**Comment by TemperedFool** [comment]
We are currently using the map from FTBChunks; there is no "view underground" functionality for it. You can right-click on the full-screen map to set waypoints.

**Comment by Taubin** [comment]
Thank you very much. I'll go ahead and close this. Cheers.

**Comment by TemperedFool** [comment]
You can always add Journeymap (or something else) client-side if you prefer that!
