### ISSUE TITLE
[0.4.8] Cannot put Immersive Engineering (maybe others) fluids into Refined Storage

### ISSUE THREAD

**Issue by eliminat** [NillerMedDild/Enigmatica6#1921]
Upgraded from 0.4.3 -> 0.4.8
Pneumatic fluids (Kerosine, Gasoline, Diesel, lubricant) already exist in Refined Storage system.
Importing fluids into system appears to work: 

- Pump into fluid interface and watch it drain.
- put filled bucket into fluid grid
- Use importing to "import fluids"

However, the fluids never appear in the system and fluid disk usage never grows. It appears the fluids get voided.

Put fluids in Dynamic tanks and attached Refined Storage External Storage bus -> Fluids appear in the Fluid Grid as expected.

Let me know if logs, world backup, etc is needed.

**Comment by eliminat** [comment]
Had to edit title to add others because I just tried Crude Oil from Pneumaticcraft and it also didn't show up in the system. Did not have this issue with 0.4.3.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Toonlink264** [comment]
do you have an external storage on a sink by any chance? those completely screw up how refined storage handles fluids

**Comment by eliminat** [comment]
Well <Expletive>.
I'll do some additional testing, but that may be it.

**Comment by eliminat** [comment]
Moved it from the sink to a tank taking water from a pipe attached to the sink and things appear to be working better.

Crude Oil seems to be dictionaried, but Gasoline and Lubricant aren't.
