### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by Sc1031** [NillerMedDild/Enigmatica6#1922]
Version
0.4.8

Thermal series machines and Create brass + andesite casing textures missing with Optifine installed (This isn't an issue in other modpacks)

**Screenshots**
![image](https://user-images.githubusercontent.com/81571713/113655122-71fb0f00-96c3-11eb-9f42-457265ab0d0d.png)

![image](https://user-images.githubusercontent.com/81571713/113655289-b686aa80-96c3-11eb-90ea-0478feadca7e.png)

**Comment by 2xMJet** [comment]
Try to change Mipmap levels back and forth. It Helped some people to solve messed up textures with optifine.

**Comment by Sc1031** [comment]
Alright I've messed around with the settings and the cause appears to be both anisotropic filtering and antialiasing. Oddly enough mipmap settings had no effect
