### ISSUE TITLE
Clearing Radiation with Nature's Aura / Botania Items

### ISSUE THREAD

**Issue by ManiacRobertWasTaken** [NillerMedDild/Enigmatica6#1925]
**Description**
Using Nature's aura  / botania items, you could clear the Mekanism Radiation using a expensive crafting like "Fully charged Aura Trove", Blocks of Ingot of the Skies, Botania Runes, AlfSteel Ingots etc (New item using KubeJS)

**Why would you like this added/changed?**

I know Mekanism questline have a "Don't Panic button", but, a nature way sounds fun, maybe a harder recipe even in expert mode.

**Comment by MuteTiefling** [comment]
Would this even be possible for us to implement a one time use item that runs a command?

It's an interesting idea for sure. But the command would need to be executed by something other than the player to work.

**Comment by NillerMedDild** [comment]
I think this would be possible, but frankly I think it's out of scope for us. Definitely something you should suggest on NA's tracker though.
