### ISSUE TITLE
[0.4.8] Builder stopping at mining

### ISSUE THREAD

**Issue by SexyRoyalBlue** [NillerMedDild/Enigmatica6#1927]
0.4.8

The Builder from RFTools is mostly used as a quarry and is really good too but with the newest update, you, at least I think it was you, added these "multiplayer friendly" loot chests which you can loot and then destroy while sneaking

The Builder can't sneak tho and thus he stops and displays a red warning and breaks

Footage will be attached

**Comment by SexyRoyalBlue** [comment]
Sadly I don't have the footage right now and I need to wait until the builder catches another chest...

**Comment by SexyRoyalBlue** [comment]
https://user-images.githubusercontent.com/48829979/113836570-480e1f00-978d-11eb-817c-827e9d700711.mov

**Comment by SexyRoyalBlue** [comment]
As you can clearly see, the builder stopped and as soon as I destroy the chest the builder starts again

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed the issue.

**Comment by noobanidus** [comment]
That's a bit of an odd one. I would've assumed if it was unable to break the block it would simply move on to the next block. Is there a blacklist that allows for you to specify all blocks in the "lootr" domain should just be skipped? My preferred option would be that the quarry just leaves the chests there, "floating" as it were.

**Comment by Trostmm** [comment]
There's an option in the quarry to do just that noobanidus, it'll move on and 'ignore' the failed block.

**Comment by noobanidus** [comment]
This is my preferred option. Mostly I think about how it would interact with the digital miner from Mekanism -- there's nothing that gets encoded in the tile state, so it would just be invalid...

**Comment by NillerMedDild** [comment]
That would make it ignore all tile entities though, and prevent it from placing them.

**Comment by noobanidus** [comment]
Oh, I thought that meant it would ignore blocks that it would be unable to break.

**Comment by Trostmm** [comment]
yeah, I was referring to the existing function in the builder interface that talks about 
"Don't wait on a position" if it can't do anything with it. It'll just skip that position and move to the next. 
Which would simply leave things like lootr chests or bedrock in place.

**Comment by NillerMedDild** [comment]
Right! I didn't realize that was a thing 😄
