### ISSUE TITLE
Experience farm with ore chunks back to ores blocks

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#193]
**Modpack version**
0.2.12

**Issue**
I don't know if this is intended but since ores give xp and you can craft the ores back from the chunks with the stonecutter, you can farm levels of experience really easily. Especially if you use the building gadgets to place all the ores at once and then veinmine them, you get to lvl30 in a matter of a minute or 2. :)

**Comment by NillerMedDild** [comment]
Ahem, woops, forgot about that :P thanks

**Comment by AdamNisbett** [comment]
Not sure if or how you plan to correct this, but presently the digital miner drops diamond chunks rather than ore when on silk touch mode, so if the option to easily convert chunks to ore is removed, that would also need to be corrected.

**Comment by NillerMedDild** [comment]
To be perfectly honest, I can't think of a good fix for this.

**Comment by jinkhya** [comment]
Is there any purpose to the ores blocks you get back from stone cutter? is it for other mods compatibility? 
Could the stonecutter give an ore with a different tag/nbt data that doesn't drop experience when placed?

**Comment by NillerMedDild** [comment]
Nope, it's just if people want to use them as decoration, or mine with Fortune. That would require registering almost 100 extra blocks, which I feel like is overkill to fix this.

**Comment by jinkhya** [comment]
haha yeah just a bit. I mean we can also just say not everybody is gonna do this to farm experience. There are other ways to get xp in the pack that are not that hard. :)
Only thing I could think of is make it harder to get the ores back. Like using mekanism machines for example, forcing you to use energy to get the ores back, but again that'd be 100 script lines, probably not worth it. 
Or remove the xp completly and people have to go another route to get experience. It's not too hard with apotheosis.

**Comment by Darkere** [comment]
We believe to have it figured out. Silk touching ores should not give XP in the first place. We will get that fixed.
