### ISSUE TITLE
Make Tetra-made hoe tillable rich soil

### ISSUE THREAD

**Issue by Lachert3391** [NillerMedDild/Enigmatica6#1933]
**Description**
A hoe which is made (or converted) by tetra mod can't till the rich soil of farmer's delight mod.
Would be better if compatible. 

...or use the hoe tier parameter to decide the tillable soil?

**Comment by NillerMedDild** [comment]
I requested the feature here: https://github.com/mickelus/tetra/issues/391 :)

**Comment by Lachert3391** [comment]
Appreciate to vectorwing, mickelus, and NillerMedDild.
