### ISSUE TITLE
Crash when clicking Show all recipes while in (ID) Logic Programmer GUI with JEI

### ISSUE THREAD

**Issue by Seceroth** [NillerMedDild/Enigmatica6#1935]
**Modpack version**
Version 0.4.8

#### Short description:

Was adding some items to a list using JEI while in the Integrated Dynamics Logic Programmer (block) and clicking the "Show all recipes" bar at the top for in this case solid coolant options for the Powa mod reactor, Minecraft crashed instantly.
Only the client will crash, the server is fine.
As a side effect, if you have a variable inside the programmer, it will be duped upon logging back in.

#### Steps to reproduce the problem:

1. Open Logic Programmer
2. Go to the List operator
3. Lookup Dry Ice in JEI
4. Go to the solid coolants for Powa tab
5. Click the top bar "Solid Coolants" to show all recipes
6. Crash

**Logs**
Crashlog with Optifine installed:
[crash-2021-04-07_18.43.04-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6273303/crash-2021-04-07_18.43.04-client.txt)

Crashlog without Optifine installed:
[crash-2021-04-07_19.18.55-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6273401/crash-2021-04-07_19.18.55-client.txt)

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it :)

**Comment by Seceroth** [comment]
https://github.com/CyclopsMC/IntegratedDynamics-Compat/commit/b0748fbe693158aea4a90f9237dd07a10718b39e
