### ISSUE TITLE
Possible bug noticed while looking at scripts in Git

### ISSUE THREAD

**Issue by BrisingrAerowing** [NillerMedDild/Enigmatica6#1936]
**Modpack version**: Git

**Describe the bug**
[This line](https://github.com/NillerMedDild/Enigmatica6/blob/a115d963ca53895b21316c0ef5713925d32a3545/kubejs/server_scripts/enigmatica/kubejs/constants/general.js#L60) is the same as the next one. Shouldn't that be comparing against the string 'normal' (or using !=)? Or am I reading that wrong?

**Logs**
N/A

**Screenshots**
N/A

**Comment by NillerMedDild** [comment]
Yes you are absolutely correct :P I fixed that a few days ago on the developer branch. Luckily it doesn't do much yet.
