### ISSUE TITLE
[0.4.8] spell break veinvanishes blocks

### ISSUE THREAD

**Issue by Tyrokas** [NillerMedDild/Enigmatica6#1939]
**Modpack version**
0.4.8
**Describe the bug**
Casting a spell containing "break" with the spell book from Ars Nouveau while the spell book is in the offhand plus holding the key for FTB Ultimine causes blocks to disappear into nothingness

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Reported to @MaxNeedsSnacks on Discord :)
