### ISSUE TITLE
Maknism Crusher not accepting ore chunks

### ISSUE THREAD

**Issue by chaoaretasty** [NillerMedDild/Enigmatica6#194]
**Modpack version**
2.13

**Issue**

I am unable to place ore chunks in to the crusher, despite the recipe being available according to the UI. Tried with a few different chunks (iron, copper, osmium). Able to crush ingots fine.

**Update**

Just tried converting chunks to ores to try them directly and it also failed to accept those ores.

**Comment by Darkere** [comment]
Are you sure it does say it goes into the enrichment chamber?

**Comment by chaoaretasty** [comment]
My mistake, I confused the Mekanism crusher with the immersive engineering crusher.
