### ISSUE TITLE
thaumcraft 6

### ISSUE THREAD

**Issue by noa12390** [NillerMedDild/Enigmatica6#1940]
**Description**
just asking so have warning a head of time but any plans to add the weirdness that is latest thaumcraft to pack in time

**Why would you like this added/changed?**

**Screenshots if applicable.**

**Comment by OneLemonyBoi** [comment]
Thaumcraft 6 is not on 1.16.

**Comment by MuteTiefling** [comment]
We can't even consider it until it exists (if ever). So, gonna have to close this one up.

For simple questions like this, you're better off asking in discord.
