### ISSUE TITLE
Recipe suggestion: Add a recipe for converting rusty iron to iron

### ISSUE THREAD

**Issue by calvss** [NillerMedDild/Enigmatica6#1942]
**Description**
Add a smelting/blasting/etc recipe that allows converting `dustrial_decor:rusty_iron_ingot` into `minecraft:iron_ingot`.
Not sure if the rusty metals have an OreDict tag associated with them, might work.

**Why would you like this added/changed?**
In my MP server, we kept accidentally making rusty iron nuggets when bulk washing ores for too long in Create, and none of us want to use rusty iron. So we thought of adding a recipe for converting rusty iron into regular iron.

Making it a smelting recipe would introduce a coal cost that, in my opinion, should make a fair balance in difficulty. Also, it's a little bit of realism, in terms of re-smelting rusty metals into shiny metals.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/13447929/114001290-5e4fd400-988e-11eb-81ac-8eb07e7ca775.png)

**PS.**
I've already made a simple KubeJS script on my side that does this, I could create a Pull Request if the idea is accepted.

**Comment by MuteTiefling** [comment]
Was thinking it might be better to use interactio for the rusting aspect, actually.

This way it doesn't inadvertently gum up a create machine processing ore.

**Comment by calvss** [comment]
Create washing isn't really a problem once you automate it with belts, since rusting takes place only after washing the iron ore. If you make sure that you don't wash your ores for too long, you won't make rusted metal.

We mostly encountered this when manually waiting for the washing to finish, sometimes the iron nugget gets left behind and rusts.

**Comment by MuteTiefling** [comment]
It's just the kind of thing that's very likely to trip up someone new to the process. Consider that they start their journey with Create Ore processing with something like copper. They get their stuff all set up and then they toss in some iron and walk away.

And come back to rusted iron... 

Worse, this recipe will actually break some of Create's powerful filtering. There's a simple filter for 'smeltable' items that makes it easy to sort ingots out from their ore. With iron now being smeltable too, that option is gone. But just for one recipe... again it leads to confusion more than anything.

By moving the rusting process to an interactio recipe, you remove the chance confusion entirely.

**Comment by ochotonida** [comment]
The smelting recipes actually wouldn't break the 'smeltable' filter since iron is the output, not the input. The rusting recipes should still be removed from the washer though, since it breaks the 'washable' filter for iron nuggets.

**Comment by calvss** [comment]
Yeah, I'm in favor of removing iron nugget washing, but I still think there should be a way to turn rusty iron back into regular iron.

**Comment by mouseas** [comment]
So if I understand correctly, this will cause iron items left in water to turn into their rusty equivalents? How long does the process take?

I'm concerned that killing zombies in water is going to cause some problems if their rare iron ingot drop gets immediately turned into rusty iron. Is there a way to add a time factor?

**Comment by MuteTiefling** [comment]
It's pretty quick but... Do people actually rely on that very uncommon iron drop? By the time I usually even see one I'm progressed enough to not care about a single ingot.

Seems like a very unlikely edge case. First to find and kill a zombie in water (that hasn't already converted to a drowned), second for that zombie to drop an ingot.

**Comment by NillerMedDild** [comment]
I'm okay with Zombies rarely dropping Rusty Iron, I think it's kinda cool even :D
