### ISSUE TITLE
Suggestions for Challenge Quests

### ISSUE THREAD

**Issue by Scapul23** [NillerMedDild/Enigmatica6#1947]
It would be cool if we had more challenges that encouraged the player to go out and try to do new things. I saw one that was accepted called the zoology challenge and I was wondering if we can go more challenges as well.

I was thinking for a challenge we can have a simple rf challenge where if the player submits a butt-ton of rf they can get an award. This would be a neat bonus to getting end-game power generation I feel.

**Comment by TemperedFool** [comment]
That specifically is actually already in the questbook but hidden; submitting FE for quests isn't currently implemented. Very good idea though ^_^

**Comment by NillerMedDild** [comment]
We're all for more challenges we've just been focusing on other stuff I guess 😄

**Comment by telemenar** [comment]
Could implement the FE challenge as a filled Ultimate Induction Cell (1.6 TFE)  if the NBT matching can be made to match. (There might be an owner NBT field that complicates thing there is for some Mekanism blocks.)

**Comment by Buuz135** [comment]
Black hole unit filled with clay

**Comment by NillerMedDild** [comment]
> Could implement the FE challenge as a filled Ultimate Induction Cell (1.6 TFE) if the NBT matching can be made to match. (There might be an owner NBT field that complicates thing there is for some Mekanism blocks.)

@telemenar Nice idea, we did just that :) this new one is in the Powah chapter though.

**Comment by NillerMedDild** [comment]
And now also as a Challenge in the challenge chapter. It'll be unhidden later on, when we've added more.

**Comment by OneLemonyBoi** [comment]
Is there a challenge for black hole tank full of fluid?

**Comment by NillerMedDild** [comment]
Not yet, but why not 😄

**Comment by NillerMedDild** [comment]
> Is there a challenge for black hole tank full of fluid? Like one for water, lava, and oil.

Done in-dev!

**Comment by Scapul23** [comment]
A challenge for a black hole unit with items would be cool!

**Comment by MuteTiefling** [comment]
One for all the artifact tier infinity tools as well. To point people to that process.

**Comment by SQbuilder** [comment]
Here are some random Challenge Quest ideas i've come up with. This includes silly quests, and some long term/niche goals.
-(Master Chef) Eat all 476 Unique Meals in Spice of Life
-(Capitalist Collector) Trade with every villager profession (even ones added by mods)
-(Poacher's Apparel) Get a full set of animal armor (crocodile chest-plate, road runner boots, cave centipede leggings, antler's headdress, spiked turtle shell, frontiersman's cap)
-(Full Setlist) Obtain all 21 music discs

Silly quests
-(Oops! All Potato!) Obtain some big number of all potato related items (Tiny Potato, Tiny Potato Mask, Potato, Poisonous Potato, Capacitato, Potato Crate, Potato Knish, Stuffed Potato, Wild Potatoes) [Note: You can use bonemeal and shears to get more Wild Potatoes]
-(Sips Co.) Obtain some big number of all dirt related items (Dirt, Coarse Dirt, Dense Grit Dirt, DirtChest 9000!, Meadow Dirt, Rocky Dirt, Deepsoil, Coarse Deepsoil, Soul Soil, Rich Soil, Ether soil, Nylium Soul Soil, Dirty Glass, Dirty Glass Pane) [Note: You would have to create a recipe for dirty glass]
-(Honeydew Inc.) Obtain one black hole unit of Jaffa Cakes, Cookies, and Cake

**Comment by MuteTiefling** [comment]
Lol, I love the tater one. I'll sit down and work through some of this in a little bit.
