### ISSUE TITLE
items disappear after reloading game

### ISSUE THREAD

**Issue by saleemc** [NillerMedDild/Enigmatica6#1949]
after playing couple of weeks, I noticed that items like sword, dank-null disappeared after reloading the game when I tried to continue to play from where I left off. Anyone else notice items disappearing.
Also sometimes you spawn in new location when you reload the existing game.

could there be some memory corruption going on?

thanks

**Comment by MuteTiefling** [comment]
sounds more like someone else is playing your account. Local game? Server? Version?

**Comment by saleemc** [comment]
its local game, 0.4.7 version
