### ISSUE TITLE
Client crash while idle

### ISSUE THREAD

**Issue by Infinoid** [NillerMedDild/Enigmatica6#195]
**Modpack version**
211835e (Hotfix 0.2.13)

**Issue**
Client crash, singleplayer mode.  I was idle (tabbed out) at the time.

**Logs**
https://paste.ee/p/2GJCR

**Comment by Darkere** [comment]
Something is doing something with the skeleton horse (changing their AI). I've seen this one pop up multiple times on discord.

**Comment by Infinoid** [comment]
I copied off the save files.  Let me know if you have any experiments to try, to narrow it down further.

**Comment by Infinoid** [comment]
I only saw it the once, and that was before I upgraded to 0.2.14.

Maybe @darkere can attest to whether this still pops up on discord.

**Comment by NillerMedDild** [comment]
Closing for the time being :)
