### ISSUE TITLE
Mod suggestion: More Red

### ISSUE THREAD

**Issue by xSvenHD** [NillerMedDild/Enigmatica6#1951]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/more-red

**Mod description**
A redstone mod that adds a bunch of logic gates, redstone wire (like IE) and redstone alloy wire that can also be colored. It's like a lite version of the good old Project Red mod.

**Why would you like the mod added?**
RFtools is lacking quite a few logic gates and being able to place redstone on a wall or ceiling is really convenient especially when you can run redstone wire next to each other without connecting (different colors). It makes for much more compact redstone contraption that can control many other mods like Create contraptions.

**Screenshots if applicable.**
![68747470733a2f2f6375626963696e746572706f6c6174696f6e2e6e65742f696d616765732f6d6f72657265642f62756e646c65645f6361626c65732e706e67](https://user-images.githubusercontent.com/5203461/114153562-b97dd700-991f-11eb-849f-13d3bd806527.png)
![68747470733a2f2f6375626963696e746572706f6c6174696f6e2e6e65742f696d616765732f6d6f72657265642f6c6f6769635f706c617465732e706e67](https://user-images.githubusercontent.com/5203461/114153639-d1edf180-991f-11eb-8045-1317fdd19386.png)

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)
