### ISSUE TITLE
Immersive Portals

### ISSUE THREAD

**Issue by SuperKnux** [NillerMedDild/Enigmatica6#1952]
---------------------------->

**https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge**

**Mod description**
This mod basically makes it so you can go through portals seamlessly

**Why would you like the mod added?**
Personally, I think this mod looks really cool and I would like if it was added. I do think seamless portals are a pretty cool idea. You should add a recipe for the portal helper because using it with Create can be a very creative duo. I tested the modpack loading with the mod added and it seemed similar, but my PC isn't that good or bad so someone should test it themselves.
**Screenshots if applicable.**

![image](https://user-images.githubusercontent.com/34802236/114196905-6dc72f80-9917-11eb-9082-30504ed42ba6.png)

**Comment by 2xMJet** [comment]
**`The mainly supported version is the Fabric version. Fixing Forge-version-specific issues is in low priority.`**
Thats what i see on the mod page. Pretty sure that can be the "-" in discussion about adding it to modpack xD

**Comment by SuperKnux** [comment]
Well sure, but I'm pretty sure there haven't been any bad issues messing with it on my own yet but yeah that can be a problem

**Comment by NillerMedDild** [comment]
Immersive Portals is cool as hell, but I'm worried it will tank performance... and fairly certain it will :P

**Comment by NillerMedDild** [comment]
Sorry but this is a no. Too much can go wrong with this.
