### ISSUE TITLE
[0.4.8] Mapple Ladder doesnt work as a ladder

### ISSUE THREAD

**Issue by TiuTalk** [NillerMedDild/Enigmatica6#1958]
**Modpack version**
0.4.8

**Describe the bug**
Autumnity Mapple Ladder doesn´t work as a ladder, it cannot be climbed up or down.

**Screenshots**
![](https://i.imgur.com/v7T9mC5.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It'll be in their next update :)
https://github.com/team-abnormals/autumnity/issues/78
