### ISSUE TITLE
[0.4.8] Some Ars Nouveau spells can bypass FTB chunk protection

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#1959]
**Modpack version**
0.4.8 via CurseForge/Overwolf

**Describe the bug**
Some of the Ars Nouveau spells can still take effect inside another player's protected chunks. Ones I've identified so far:

- Ignite - creates flames
- Intangible - makes blocks temporarily non-solid. Can break doors, mess up other connected blocks, and allow access to closed areas.
- Conjure Water - 'nuf said
- Phantom - creates temporary phantom blocks
- Light - creates floating lights
- Smelt - can smelt protected logs for infinite charcoal, ores for infinite ingots, and can transform stuff like sand into glass.
- Gravity - causes blocks to be affected by gravity like sand. Can be combined with Light to steal blocks.
- Interact - bypasses interaction protection, allowing full access to containers, machines, etc

**Logs**
n/a

**Screenshots**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Can they be cast inside the protected chunks, or does it only work when casting a projectile in?

**Comment by ManiacRobertWasTaken** [comment]
You can cast the spells outside the protected area to a protected area.

**Comment by NillerMedDild** [comment]
> 
> 
> **Modpack version**
> 0.4.8 via CurseForge/Overwolf
> 
> **Describe the bug**
> Some of the Ars Nouveau spells can still take effect inside another player's protected chunks. Ones I've identified so far:
> 
>     * Ignite - creates flames
> 
>     * Intangible - makes blocks temporarily non-solid. Can break doors, mess up other connected blocks, and allow access to closed areas.
> 
>     * Conjure Water - 'nuf said
> 
>     * Phantom - creates temporary phantom blocks
> 
>     * Light - creates floating lights
> 
>     * Smelt - can smelt protected logs for infinite charcoal, ores for infinite ingots, and can transform stuff like sand into glass.
> 
>     * Gravity - causes blocks to be affected by gravity like sand. Can be combined with Light to steal blocks.
> 
>     * Interact - bypasses interaction protection, allowing full access to containers, machines, etc
> 
> 
> **Logs**
> n/a
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by mouseas** [comment]
As of 0.4.8 you can cast while inside a protected area, as well as into it from outside.
