### ISSUE TITLE
Lag that seems to be caused by Interactio

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#196]
**Modpack version**
0.2.12 with Interactio 2.0.6
(Used to have Interactio 2.0.5, Darkere suggested to update it since it has some performance improvements)
 
**Issue**
After a while the server starts lagging whether it's with Interactio 2.0.5 or Interactio 2.0.6. Latest version of interactio is better but doesn't fully fix the lag issue.
Here's what a spark report looks like when it starts lagging and afaik, every time I've seen lag starting happening and have ran spark it always shows Interactio high in the list. Our world is about a week old and people are still early game with not that many things running.
https://spark.lucko.me/#onkOYTVwbS

Is Interactio handling any recipes atm? I could potentially disable it and see if it behaves better to compare but I don't want to break the pack either :)

**Comment by Darkere** [comment]
Can you please check how many items are on the ground? /forge entity list

Then also please try without Performant as that is somewhat known for doing some weird stuff. 

Interactio is currently only used for making fluix quartz.

**Comment by jinkhya** [comment]
Hm there are 816 items on the floor... Fair enough I'll disable Performant

**Comment by jinkhya** [comment]
wait no, 81 my bad

**Comment by jinkhya** [comment]
Here's a spark report without performant, 40 items on the floor : https://spark.lucko.me/#zRUN2Qq6xj

**Comment by jinkhya** [comment]
Just to confirm, I've been running the server for a few hours now with a couple of people playing in and out without Interactio and the tps is a strong 20 at all times (no "Can't keep up! Is the server overloaded? Running ..ms or .. ticks behind" message in console) compared to going between 15 and 20 constantly when Interactio is in.

**Comment by MaxNeedsSnacks** [comment]
Hey o/ Mod dev here!

I've been trying my best for the past couple of hours to figure out where the issue's coming from and while there are... *a lot* of probably minor things that might've hit performance a bit, I can't for the life of me figure out what exactly is going on right now.

Would you mind testing one of these two dev jars on your server for a couple of hours? They contain all of the minor fixes I was able to come up with in this limited timespan and should hopefully yield at least more than nominal performance improvements if I didn't mess anything up.

The only difference between the two jars is the implementation of ONE thing i need to compare itemstacks against recipe inputs, so it shouldn't matter which of these you choose, but please do let me know which one it is either way so I can further evaluate it

https://cdn.discordapp.com/attachments/730169148294037544/748279913387130983/Interactio-1.16.1-2.0.6-dev.jar
https://cdn.discordapp.com/attachments/730169148294037544/748279916797362237/Interactio-1.16.1-2.0.6-dev-approach-2.jar

(Obviously, both of these jars are server side so your players won't have to change a thing)

**Comment by MaxNeedsSnacks** [comment]
Also, maybe as an added question, does the lag accumulate over time or is it just constant / in the background?

**Comment by jinkhya** [comment]
Sure thing we'll test those ! Appreciate it :) 
It seems to accumulate as time goes and more people join in and out. I've been doing a lot of testing before saying anything, disabling other mods, running around, loading different chunks to try to pin down when it starts "breaking". I've also noticed that after a while even with nobody on the tps still fluctuates. All the testing has not been really conclusive beside when interactio is disabled the tps is better sadly.

**Comment by jinkhya** [comment]
After some testing :
here's spark for 2.0.6-dev.jar
https://spark.lucko.me/#qrIPC6oLJR
here's spark for 2.0.6-dev-approach-2.jar
https://spark.lucko.me/#zNcg3ACbGl

so it's about the same as before sorry :(

**Comment by MaxNeedsSnacks** [comment]
Hm...

there are some more things I could try out still, I'll let you know if I find anything that (hopefully) makes a meaningful difference!

**Comment by jinkhya** [comment]
Okay if you got more jars to test feel free to ask, happy to help!

**Comment by MaxNeedsSnacks** [comment]
I actually just got done porting things over to Mixins, so if you wanna try that out and see whether that improves performance, be my guest ^^

https://cdn.discordapp.com/attachments/730169148294037544/748863600021602364/Interactio-1.16.1-3.0.0-dev.jar

If this still doesn't work, that's not ***too*** big of a deal, but I guess then I'd have to rethink some major things about how the mod works

**Comment by jinkhya** [comment]
Nice, testing it right now. I will let you know how it does in a couple of hours.

**Comment by MaxNeedsSnacks** [comment]
Just as a heads up, if you're on the latest version the mod has been temporarily removed to fix the lag issues, so you'll probably have to re-add a fluid crafting recipe of some kind with datapacks to properly test things out I guess?

**Comment by jinkhya** [comment]
Yeah I did see Niller disabled it temporarily, I added it back and told my
friends to put it back in. Thank you though!

**Comment by MaxNeedsSnacks** [comment]
No worries ^^ Also, you don't actually need the mod client-side, it's a "server utility" sort of thing (only thing you'll be lacking is the particles, which... I guess is stomachable)

**Comment by jinkhya** [comment]
Oh right! I actually thought it was needed both sides since when I disabled it on the server and had it on the client it was giving me a mod matching error. I assumed the other way around wouldn't work either.

**Comment by MaxNeedsSnacks** [comment]
> when I disabled it on the server and had it on the client it was giving me a mod matching error
was it a soft crash / disconnect? that shouldn't be a thing... oh dear

**Comment by jinkhya** [comment]
It was just not letting me connect on the server, can't remember the exact error message. Just a mismatch I guess.

**Comment by MaxNeedsSnacks** [comment]
Oh yeah, I see what I messed up. Fixing that asap!

**Comment by jinkhya** [comment]
Awesome! :)

**Comment by jinkhya** [comment]
The server has been running for a few hours now and Interactio-1.16.1-3.0.0-dev.jar is wonderful! Haven't seen any tps fluctuation, the console is not indicating anything taking too much time either. I checked spark and there's no sign of interactio methods. I even started doubting it was actually on the server and tested Niller's fluix crystal recipe which worked fine :) so good job !

**Comment by MaxNeedsSnacks** [comment]
Awesome! ^^
I have noticed in userdev the console occasionally had "fetching removed entity" warnings, have you noticed any sort of uptick in those?

**Comment by jinkhya** [comment]
I didn't notice but we do have some yes. It seems to only be air ItemEntity and it doesn't happen a lot. I checked the debug log and there are 6 of those for a 6 hours session so far. They all happened within the same 10 minutes.

**Comment by MaxNeedsSnacks** [comment]
Just released 3.0.0 on CurseForge \o/ Thanks again for testing this for me, I unfortunately don't have any server infrastructure I could use to stress test this ^^

https://www.curseforge.com/minecraft/mc-mods/interactio/files/3044676

(cc @NillerMedDild, it MIGHT also need updating in E5 if you plan on using it there)

If there's anything else I can do or another issue with the mod, feel free to open an issue over on my GitHub tracker (or here if you want Niller to forward it to me), I'll be sure to try and find a fix for it!

**Comment by jinkhya** [comment]
Awesome! Out of curiosity did you also make the mod server only? :)

**Comment by MaxNeedsSnacks** [comment]
Yup, the mod‘s completely server-side now ^^

**Comment by jinkhya** [comment]
```
[29Aug2020 14:28:57.251] [Netty Client IO #2/ERROR] [net.minecraftforge.fml.network.NetworkRegistry/NETREGISTRY]: The server is likely to require channel [[interactio:particles]] to be present, yet we don't have it
[29Aug2020 14:28:57.252] [Netty Client IO #2/DEBUG] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Received FML ping data from server at 138.201.57.151: FMLNETVER=2, mod list is compatible : false, channel list is compatible: false, extra server mods: {interactio=1.16.1-3.0.0}
```
Erm you're sure? ^^

**Comment by MaxNeedsSnacks** [comment]
> *pain*

You know, the worst part about that is I haven't been using that network channel for a LONG time (since I discovered ServerWorld.spawnParticle is a thing) so I'll just get rid of it for now. Other than that there HOPEFULLY shouldn't be anything preventing you from only having this on server-side
