### ISSUE TITLE
Grow/expand Oh The Biomes You'll Go ground coverings with bonemeal

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#1960]
**Description**
Better End Forge adds a bunch of new ground coverings, but there doesn't seem to be a way to grow them, either passively or actively. Warped/Crimson Nylium can be grown onto Netherrack from adjacent Nylium blocks using bonemeal. Could the same process be used to induce Better End ground coverings to grow onto neighboring End Stone blocks? Alternately, could some sort of seed/spore item be added for each type which grows the corresponding ground coverings?

**Why would you like this added/changed?**
Currently the Better End ground coverings are, to my knowledge, non-renewable. If I want more, I have to go back to the End and harvest some with silk touch. When growing Better End trees/mushrooms, often some of the ground covering is destroyed in the process.

**Screenshots if applicable.**

**Comment by mouseas** [comment]
Also worth mentioning; the Nether has some new ground coverings, those should be renewable as well.

**Comment by MuteTiefling** [comment]
I recall most of these being growable with bone meal on the appropriate end stone variants when I was testing to determine what needed to go into cloches and insolators.

Can you provide some specific examples?

**Comment by mouseas** [comment]
- Vermillion Skulk onto Ether Stone (byg)
- Nightshade Phylium onto Ender Stone (byg)
- Shulkren Phylium onto Ender Stone (byg)
- Bulbis Phycelium onto Ender Stone (byg)
- Ether Phylium onto Ether Soil (byg)
- Imparius Phylium onto Ender Stone (byg)

So....apparently it's the Oh The Biomes You'll Go ground coverings, *not* the Better End ones which are the problem. I'll, uh...I'll update the title.

The Better End ones won't grow up or down a Y level, but that's far less of a problem then not growing with bonemeal at all.

**Comment by MuteTiefling** [comment]
Cool, thanks. I'll take a second look at these and see what can be done.

**Comment by MuteTiefling** [comment]
There, fixed as much as we can. The suggestion has been made to the BYG team to allow natural spreading such as with grass.
