### ISSUE TITLE
Give concrete blocks the valid apiary tag

### ISSUE THREAD

**Issue by ShakterNano** [NillerMedDild/Enigmatica6#1964]
Concrete blocks don't have the valid apiary tag. A few other blocks also don't have this tag and might be worth looking into

**Comment by TemperedFool** [comment]
If you have any other suggestions add them to this - I'll take a pass at adding them tomorrow.

**Comment by vstvg** [comment]
Terracota blocks also would be nice to have as an eligible ones. And Illuminated block from Simply light is a nice source of white light that is not viable right now
