### ISSUE TITLE
[0.4.8] Induction Smelter Netherite Ingot Recipe

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#1967]
**Modpack version**
[0.4.8]
**Describe the bug**

The netherite ingot has three recipes for Thermal's Induction Smelter, but one of them does not work and appears to be a duplicate.

Gold Ingots (2) + Netherite Scrap(4) = Netherite Ingot (1) -- The Induction Smelter does not actually process this recipe.
Gold Ingots/Dust (4) + Netherite Scrap (4) = Netherite Ingot (1) -- Works
Netherite Dust (1) -- Works

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
