### ISSUE TITLE
Fix Life-Mending from Enchanting Tables

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#1968]
**Description**
Either (a) make Life-Mending not a curse, or (b) remove it from the possible enchantments which an Enchanting Table can bestow.

**Why would you like this added/changed?**
The Life-Mending enchantment can be bestowed randomly when enchanting an item at the Enchanting Table. It's also a curse.

Because it's a curse, it can't be removed at a grindstone; you have to use a prismatic web and 30 levels to remove it from an item. And any item with any enchantment on it, even just a curse, can't be enchanted again.

No other curses come from an Enchanting Table. Risking a curse when enchanting a nice affixed item really sucks. Having it happen about 25% of the time with a fully-upgraded enchanting station *really* sucks.

**Screenshots if applicable.**
n/a

**Comment by MuteTiefling** [comment]
> Because it's a curse, it can't be removed at a grindstone; you have to use a prismatic web and 30 levels to remove it from an item. And any item with any enchantment on it, even just a curse, can't be enchanted again.

There are other ways to remove enchants :D Including these. 

It does kinda suck to get from random enchanting though.

**Comment by NillerMedDild** [comment]
I've relayed, thanks for the suggestion :)

**Comment by NillerMedDild** [comment]
The mod author has fixed it in-development, by allowing things enchanted with just curses to be re-enchanted.
