### ISSUE TITLE
Ancient Debris Tags

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#197]
**Modpack version**
E6 0.2.13

**Issue**
The lack of tags on Ancient Debris makes it inconvenient when you are trying to use the Mekanism Digital Miner. Currently I think the only way is to find one in a normal vanilla way, and then use it as an item stack. Could be beneficial to maybe add a Forge tag of some kind to it.
Suggestions:
forge:nether_ores |  forge:nether_ores/ancient_debris 
The above can also be added to all the nether ores such as Quartz, Gold Ore, Gilded Blackstone, and Ancient Debris.

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/64355028/91348004-75502300-e7e3-11ea-87b2-4eae0ead654f.png)
![image](https://user-images.githubusercontent.com/64355028/91348043-81d47b80-e7e3-11ea-8b81-70e278cfc220.png)
![image](https://user-images.githubusercontent.com/64355028/91348085-9153c480-e7e3-11ea-98b8-6640c0ad3aa4.png)

**Comment by NillerMedDild** [comment]
I'd prefer going with `forge:ores` + `forge:ores/ancient_debris`, is there any particular reason you'd prefer `nether_ores` over `ores`?

**Comment by Ridanisaurus** [comment]
Not really. I just think because Ancient Debris is not really supposed to be an ore per se. However, I guess it is processed the same way. I think `forge:ores` is not a bad idea.

**Comment by Ridanisaurus** [comment]
Nop, nevermind. IT IS classified as an ore. `forge:ores` is the correct move indeed.

`Ancient debris is an extremely rare ore found in the Nether, and is the main source of netherite scrap. Its high blast resistance makes it immune to normal explosions. In item form, it floats on lava and cannot be burned by any form of fire.`
