### ISSUE TITLE
[0.4.8] Bottle use on Fractioning Still causes CRASH

### ISSUE THREAD

**Issue by r007ed** [NillerMedDild/Enigmatica6#1972]
**0.4.8**

**Describe the bug**
Right clicking a **_Fractioning Still_** which contains Syrup. (byproduct of sap)
causes the server to crash. I was able to repeat this many times.

The **_Fractioning Still_** contains both Syrup and Water.
Dumping the water does not correct the issue.

**Comment by NillerMedDild** [comment]
Please include the crash report :)
