### ISSUE TITLE
Change Config of sophisticatedbackpacks-common

### ISSUE THREAD

**Issue by Zyferus** [NillerMedDild/Enigmatica6#1974]
playJukebox = true - Request change to False.

This music becomes very disturbing, as it starts as soon as the mob spawns, and is VERY difficult to locate, especially if the mob spawns in an inaccessible nearby cave.

**Comment by NillerMedDild** [comment]
I moved your issue from E2E 😄 https://github.com/NillerMedDild/enigmatica6/issues/1973
