### ISSUE TITLE
Enigmatica 6 0.4.8

### ISSUE THREAD

**Issue by Weisincht** [NillerMedDild/Enigmatica6#1977]
0.4.8

Server crash by distroing pneumatic craft refinery
after wron placing i try to reorganice the refinery in the correct order. By distroing the block the server crashed several times.

[crash-2021-04-13_20.21.49-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6305929/crash-2021-04-13_20.21.49-server.txt)

![2021-04-13_20 36 55](https://user-images.githubusercontent.com/67184054/114603483-0fdc7400-9c98-11eb-8b0e-90211c40fafd.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, this has been fixed in a PNC update, so this will be fixed in the next E6 version :)
