### ISSUE TITLE
Add quests for mod addon items [Suggest addons in comments please :D]

### ISSUE THREAD

**Issue by ShakterNano** [NillerMedDild/Enigmatica6#1978]
There are a lot of mod addon items that are not really shown to the player, such as the RS requester and infinite range card . The only way you would know about these is if you accidentally found them while looking through JEI, or if someone told you about them, as you can't look them up by searching by mod due to them being from different mods. Adding quests for these items in the relavant chapter would help, or some other way of easily looking up all mod addon items relevant to a mod.

**Comment by MuteTiefling** [comment]
I'll give these a poke next time I'm able to get on Dev. Unless, is it safe now to just push quest updates in a PR?

**Comment by NillerMedDild** [comment]
It is safe to push quest updates in a PR, even for new chapters :)

**Comment by MuteTiefling** [comment]
super!

**Comment by aqpoyo** [comment]
Oh thats a good one, didn't know about the infinity range. thanks a lot! By the way is there something like the angel block? so you can place a block in mid air?

**Comment by werwerwsx** [comment]
@aqpoyo [Bottled cloud from Quark is a pretty good replacement](https://twitter.com/vazkiimods/status/1266770114600488961?lang=en), just nerd pole up to the cloud layer with some empty bottles.

**Comment by MuteTiefling** [comment]
Cool thanks for the suggestions. I've got RS stuff added. Added the cloud bottle. Also added the time in a bottle.

Will add immersive petroleum stuff too and push.

**Comment by r-mc2** [comment]
@aqpoyo & @werwerwsx There's also IE's [Balloon](https://ftbwiki.org/Balloon_(Immersive_Engineering)). A little more work than Quark's option, but depends on what infrastructure you got going already (or what you've raided from the local villager 😆).

| Block | Recipe |
| -- | -- |
| [<img src="https://ftbwiki.org/images/a/aa/Block_Balloon_%28Immersive_Engineering%29.png" alt="Immersive Engineering's Balloon Block" />](https://ftbwiki.org/Balloon_(Immersive_Engineering)) | <img width="251" alt="Screen Shot 2021-04-15 at 8 13 56 PM" src="https://user-images.githubusercontent.com/36780233/114953779-21a05180-9e27-11eb-9a33-e9bad8dfae81.png"> |

**Comment by aqpoyo** [comment]
I always had the doubt about this balloon, I thought it was just decoration. Thanks it works as I wanted.
