### ISSUE TITLE
[0.4.3] Random Enderman Aggro

### ISSUE THREAD

**Issue by HardstyleIsMyXTC** [NillerMedDild/Enigmatica6#1979]
**0.4.3**

So me and my mate hopped in the end for the first time on our private server. within 1 minute we had 20 endermen chasing us for no reason. It wasn't normal aggro, we didn't look at any endermen or at least not at 20. I went into creative, cleared my whole inventory (armor, baubles and even trinkets) nothing happened. But as soon as i went into survival a random enderman from the edge of my screen comes running at me, and so 10 join in

Here is a pic of me after going into survival. Didnt move a muscle.
![image](https://user-images.githubusercontent.com/82482260/114638471-f6551f80-9ccb-11eb-8dec-757f2bce6f8e.png)

**Comment by OneLemonyBoi** [comment]
Why was this issue closed?

**Comment by BergieSM** [comment]
Reporter commented in the discord here: https://discord.com/channels/195234321836146688/726178356143456287/831699241592291339

Quote:
i added a mod to this pack called "ImprovedMobs"
I thought of this already and checked if it had anything to do with the enderman but couldnt find anything. Not on CurseForge and not in the configs
But APPARENTLY there is this 1 little line in the config that says: "Chance of neutral mobs becomming hostile"
