### ISSUE TITLE
Centrifuge Tiers

### ISSUE THREAD

**Issue by starforcraft** [NillerMedDild/Enigmatica6#1980]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/centrifuge-tiers

**Mod description**
Centrifuge Tiers adds 4 new Centrifuges for Resourceful Bees. The better ones are faster, have Output Multiplier, more Output Slots and more "Item Max Stack Size". (Everything is configurable).

**Why would you like the mod added?**
It is a really cool addon mod for Resourceful Bees and gives a big goal because the Creative Centrifuge is pretty much OP and really expensive.

**Screenshots if applicable.**
![grafik](https://user-images.githubusercontent.com/60074805/114661445-4bf2f180-9cf7-11eb-8308-cc5e6823a9d6.png)
All Centrifuges

**Comment by NillerMedDild** [comment]
These kinda invalidate tiering up with apiaries, so it's a pass :)
