### ISSUE TITLE
Subterranean Wilderness

### ISSUE THREAD

**Issue by SailHatan** [NillerMedDild/Enigmatica6#1981]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/subterranean-wilderness

**Mod description**
Subterranean Wilderness adds several cave biomes, and some blocks and items with them.

**Why would you like the mod added?**
1) This mod adds some much needed variety to caves, making exploring them less repetitive. 
2) Compatible with yung's better caves and mine shafts
3) Has config options for some features that spawn in the cave biomes

**Screenshots if applicable.**
https://www.curseforge.com/minecraft/mc-mods/subterranean-wilderness/screenshots

**Comment by NillerMedDild** [comment]
This looks pretty cool, but I'd rather not increase the performance load on worldgen any further.
