### ISSUE TITLE
[0.4.8] Compact Machines don't have crafting recipies

### ISSUE THREAD

**Issue by Draccsos** [NillerMedDild/Enigmatica6#1983]
**Modpack version**
0.4.8

**Describe the bug**
In JEI there are no crafting recipies for Compact Machines and Compact Machine Walls. 
Following the  instructions in the modpack folder under `/building_gadgets_patterns/compact_crafting` don't work for crafting the machines.

**Comment by MuteTiefling** [comment]
Already fixed in dev. Thanks for the report :D
