### ISSUE TITLE
Creative Apiary

### ISSUE THREAD

**Issue by starforcraft** [NillerMedDild/Enigmatica6#1986]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/creative-apiary

**Mod description**
This Mod adds a Creative Apiary and a Creative Apiary Storage.

Creative Apiary: instant, non unique, 100x slots, 100 Honeycomb output by default
Creative Apiary Storage: 108x slots

**Why would you like the mod added?**
It adds a new Goal for the Tiered Apiaries. It is really OP but also really expensive.

**Screenshots if applicable.**

**Comment by NillerMedDild** [comment]
No thank you, on the exact same basis as #1980 :)
