### ISSUE TITLE
Cable Tiers

### ISSUE THREAD

**Issue by starforcraft** [NillerMedDild/Enigmatica6#1987]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/cable-tiers

**Mod description**
This mod adds Better Importer, Exporter, Constructor, Destructor from Refined Storage.

Elite: 9 more filter slots, 2x faster
Ultra: 27 more filter slots, 6x faster, Stack Upgrade Integrated
Creative: 45 more filter slots, Instant, Stack Upgrade Integrated

**Why would you like the mod added?**
It adds better importer, exporter for Refined Storage. The normal ones from Refined Storage are too slow.

**Screenshots if applicable.**

**Comment by NillerMedDild** [comment]
Thanks for the suggestion. I don't really think this is needed to be honest, but I'll think it over some more.

**Comment by Tyler-Jarret** [comment]
Not that I'm opposed to the mod however, I believe speed and stack upgrades apply to the importer and exporters? And I think you can insert more than one of each.

**Comment by starforcraft** [comment]
> Not that I'm opposed to the mod however, I believe speed and stack upgrades apply to the importer and exporters? And I think you can insert more than one of each.

Yeah you have 4 Update Slots for the Refined Storage Exporter and Importer but its not really fast.

**Comment by excodex** [comment]
Not because of the speed, but the bigger filter slots are handy!

**Comment by MuteTiefling** [comment]
We already have bigger importers and exporters though.

**Comment by starforcraft** [comment]
> We already have bigger importers and exporters though.
There is Extra Storage that adds 2 filter rows but thats literally not enough. 😅

**Comment by NillerMedDild** [comment]
To be honest I think you should just come up with a different solution if you run out of filter rows :P This is gonna be a no thank you.
