### ISSUE TITLE
Treated wood Planks recipe not giving Big Buckets back

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#199]
**Modpack version**
0.2.12

**Issue**
It is currently possible to craft IE treated wood with big buckets, however it "eats" the bucket no matter the size or how much liquid was in it and returns 8 treated planks.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
https://github.com/williambl/bigbuckets/issues/5
