### ISSUE TITLE
Outvoted

### ISSUE THREAD

**Issue by pm065** [NillerMedDild/Enigmatica6#1990]
https://www.curseforge.com/minecraft/mc-mods/outvoted

**Mod description**
Adds the Hovering Inferno, Monster of the Ocean Depths and Great Hunger from that MC Live mob vote where the Phantom was selected.

**Why would you like the mod added?**
It adds a couple of cool mobs with good mechanics, it's fully customisable and has loads planned from other Live votes like the biome revamps.

**Screenshots if applicable.**
These screenshots are from the mod's page, they have shaders on them so not 100% accurate:

Wildfire (Hovering Inferno)
![image](https://user-images.githubusercontent.com/81559564/114874170-f7816c00-9df3-11eb-91d0-f3619d76f637.png)

Hunger (Great Hunger)
![image](https://user-images.githubusercontent.com/81559564/114874189-fe0fe380-9df3-11eb-9bd2-29bee9eea263.png)

Kraken (Monster of the Ocean Depths)
![image](https://user-images.githubusercontent.com/81559564/114874306-1e3fa280-9df4-11eb-8917-110e042aaffd.png)

**Comment by NillerMedDild** [comment]
To be honest I think they look a bit meh, with the exception of the Hovering Inferno. I don't think we really need this mod either.
So no, but thanks for the suggestion :)
