### ISSUE TITLE
Mimic farm with rftools spawner

### ISSUE THREAD

**Issue by aqpoyo** [NillerMedDild/Enigmatica6#1997]
**Description**
So i was trying to make a farm with the mimic because I don't like to explore a lot because later the world gets too big and I don't like big worlds and I was trying to make a farm with the mimic from artifact, I tried with the PNC spawner but it doesn't get absorbed, I tried also with the mod duplicator which I don't like I think is a bit too op but It doesn't work, the loonium from botanic doesn't get the same loot, (actually this one only gets a type a loot chest, not all) and finally I tried with the rftools spawner and it does get into the syringe but after it doesn't ask for the materials to put in the beamer so it doesn't work. Maybe the materials to get it spawned could be hard to get, I don't know what, maybe nether stars or  netherite blocks or something harder. I imagine it could be done but I don't know if it is even possible.

**Why would you like this added/changed?**

Just a suggestion it could be nice.

If there is another method that already exist please let me know.

Thanks!

**Comment by MuteTiefling** [comment]
These were intentionally removed from spawners due to the power of their mimicream.

**Comment by aqpoyo** [comment]
I am not talking about the mimicube from alexmob but the mimic from artifacts, the one that looks like a chest.

**Comment by MuteTiefling** [comment]
Also intentionally excluded.

**Comment by r-mc2** [comment]
Also should be noted because Mimicubes were disabled, Mute moved the mimicream drops to Mimics themselves which is why he mentioned it.
