### ISSUE TITLE
Relics

### ISSUE THREAD

**Issue by Scapulaunit12** [NillerMedDild/Enigmatica6#1998]
https://www.curseforge.com/minecraft/mc-mods/relics-mod

A mod that adds  25 relics to the game with unique and useful mechanics that can help both in battles against hordes of monsters and in peaceful farmer or miner life.

I feel like this mod is a lot more unique than some of the other trinket/artifact mods in enigmatica 6, I feel like this one should be added as it stands out compared to the others.

**Comment by NillerMedDild** [comment]
We have Bountiful Baubles, Artifacts and Lost Trinkets, I don't think we need more mods like this :)

**Comment by KrAzYGEEK32** [comment]
i just want add my thoughts on this mod, i've been recently playing with it and all the baubles it has are so unique and well thought out. not the bland ones we have which go "here, take night vision, wither immunity, water breathing, speed boost etc.". all the baubles i used are so fun and fill a lot of niches or add new gameplay aspects. please do reconsider it :D .

for example, there is a unique flight option it the mod which lets to hover a little bit at cost of consuming fire around you, and there is another bauble which swaps you with the enderman you are looking at, at a cooldown ofc. great and such a fun option to explore end imo.
