### ISSUE TITLE
Integrated Dynamics crashes the game when reading AS crystal stats

### ISSUE THREAD

**Issue by greatmonkey** [NillerMedDild/Enigmatica6#1999]
Having Integrated Dynamics read an AS crystal stats on a display panel causes the game to crash in a single player world. Crash log attach to this.

[crash-2021-04-11_16.01.55-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6328201/crash-2021-04-11_16.01.55-server.txt)

**Comment by NillerMedDild** [comment]
Fixed in next update, suprisingly this is the same issue as #1883
