### ISSUE TITLE
Crashes when i make a world

### ISSUE THREAD

**Issue by iceman-06** [NillerMedDild/Enigmatica6#2]
**Modpack version**
0.1.3

**Issue**
when i try to make a world it crashes and it made one after the crash when i load it it crashes

**Logs**
this is the one when i tried making the world [crash-2020-07-14_11.33.49-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/4919734/crash-2020-07-14_11.33.49-server.txt)

**Comment by iceman-06** [comment]
i  might have found the problem (its not with the pack if i did find it)

**Comment by Darkere** [comment]
Yeah don't create a world with a ? in it's title :D

**Comment by iceman-06** [comment]
ok
