### ISSUE TITLE
Vanilla Torches place, remove themselves and replace themselves.

### ISSUE THREAD

**Issue by Atlasatron** [NillerMedDild/Enigmatica6#20]
**Modpack version**
Enigmatica 6 0.2.0

**Issue**
Placing vanilla torch, removes itself and then places again after a bit of delay.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/4961894/latest.log)

**Comment by NillerMedDild** [comment]
Thanks for the report! I'm going to go out on a limp and guess that this is tied to #14
