### ISSUE TITLE
Vanilla Hammers destroy the digital miner

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#200]
**Modpack version**
0.2.12
**Issue**
When you break the digital miner (tried multiple "blocks" of it) with the Vanilla Hammers (I tried iron, diamond, emerald and obsidian but it's probably the same for others) it just destroys it.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
