### ISSUE TITLE
[0.4.8] Quick transfer to "Transport" inventory, client freeze.

### ISSUE THREAD

**Issue by r007ed** [NillerMedDild/Enigmatica6#2001]
**0.4.8**

**Describe the bug**
While playing on a server. (single player untested)

I access the inventory of a modular cart from "Transport".

Shift+Left Click an item in to put it in the inventory and the client will freeze.

I have tested this in the 3 inventories I have access to in my cart (inventory, chest, and smelting engine).
All 3 variations caused Minecraft to become unresponsive for an indefinite amount of time.

Note:
The inventory functions properly when left clicking to pick up and item and then clicking it into the slot.

**Logs**
No crash report because the system hangs, not crashes.
latest.log also does not update during this process.

**Comment by NillerMedDild** [comment]
Thanks for the report, will be fixed in the next update :)
https://github.com/BrassGoggledCoders/Transport/issues/43
