### ISSUE TITLE
[0.4.8] Sophisticated Backpack Compacting  endless loop and crash.

### ISSUE THREAD

**Issue by r007ed** [NillerMedDild/Enigmatica6#2003]
**0.4.8**

**Describe the bug**
The recipe for Marble Bricks (Astral Sorcery) uses 4 of any Astral Sorcery Marble blocks.
This includes Astral Sorcery Marble Bricks.

When you combine this with Sophisticated Backpacks compacting upgrade and tell it to compact anything possible it results in an endless loop which crashes the server.

In single player testing it never quite got to the crash portion, but did make all further actions unavailable. (no chest opening)

**Screenshots**
![image](https://user-images.githubusercontent.com/14995453/115123575-bae87880-9f8b-11eb-96b5-7714eb8590e4.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please provide the crash report? :)

**Comment by r007ed** [comment]
https://pastebin.com/28YEYCeu

**Comment by NillerMedDild** [comment]
@P3pp3rF1y Blocks that can be continuesly compacted (product 1 -> product 2 -> product 1) cause server crashes, and freezing on singleplayer. I hope it's alright to get the report like this 😄

**Comment by P3pp3rF1y** [comment]
Yes that's alright, I can see what's going on there and will fix it so that compacting upgrade doesn't try to compact item into the same item. As well as check for something like a series of compacting recipes ending in a loop as by looking at this I can see that happening at some point.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest sbp release on curseforge
