### ISSUE TITLE
[Suggestion] Architect's Palette

### ISSUE THREAD

**Issue by stylzm** [NillerMedDild/Enigmatica6#2004]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/architects-palette

**Mod description**
This mod adds plenty of building blocks that fit with many different building styles and aesthetics.

**Why would you like the mod added?**
Some of the blocks that this mod adds are really unique, and I would like to be able to utilize them in builds on my server.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/46853295/115131348-5f7ab280-9fac-11eb-9ac5-fbe9275a6ed5.png)
![image](https://user-images.githubusercontent.com/46853295/115131357-702b2880-9fac-11eb-8dcd-62f8488f09f9.png)
![image](https://user-images.githubusercontent.com/46853295/115131361-791bfa00-9fac-11eb-958c-c6727712e126.png)

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by NillerMedDild** [comment]
Love it, very unique, adding it :)
