### ISSUE TITLE
[0.4.8] Ender Tank Causes visible entities through blocks

### ISSUE THREAD

**Issue by Barlease** [NillerMedDild/Enigmatica6#2005]
**Modpack version**
0.4.8

**Describe the bug**
Once an Ender Tank is placed in the world, being near it, and looking toward it causes other entities to be visible through blocks. Attached are a few screenshots. I am using OptiFine: preview_OptiFine_1.16.5_HD_U_G8_pre1

Here is another thread on the topic and someone asked about that looks like they have the same issue as me: https://www.reddit.com/r/feedthebeast/comments/letuno/seeing_entities_through_walls_with_modded/

![ender tank in view 2](https://user-images.githubusercontent.com/82740540/115132028-43820b80-9fc2-11eb-9fba-dc443033fa7a.png)
![ender tank in view 1](https://user-images.githubusercontent.com/82740540/115132029-441aa200-9fc2-11eb-9d5c-7382fe9a0015.png)
![ender tank out of view](https://user-images.githubusercontent.com/82740540/115132030-441aa200-9fc2-11eb-912b-14c43696f5bc.png)

The last screenshot is an example of the Ender Tank no longer being visible, causing it to go back to normal.

**Comment by MuteTiefling** [comment]
Optifine causes all sorts of issues with rendering. Nothing et can do about it.

**Comment by xSvenHD** [comment]
Turn off fast render.
