### ISSUE TITLE
[0.4.8] Serverlist shows 'no connection' but can join

### ISSUE THREAD

**Issue by Culumpia** [NillerMedDild/Enigmatica6#2006]
**0.4.8**

**Describe the bug**
Serverlist shows 'no connection' but I can join the server. Others can join the Server too, but have the same Problem.
![photo_2021-04-18_11-15-22](https://user-images.githubusercontent.com/82754139/115140400-669ad280-a037-11eb-965c-03f81f1e638c.jpg)

**Comment by NillerMedDild** [comment]
For reference this issue is the same as #824, the solution is here: https://github.com/NillerMedDild/Enigmatica6/issues/824#issuecomment-757359968
