### ISSUE TITLE
[Suggestion] YUNG's Better Strongholds

### ISSUE THREAD

**Issue by BlueNexus** [NillerMedDild/Enigmatica6#2007]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds
**Mod description**
Along the lines of YUNG's Better Caves and YUNG's Better Mineshafts, this mod tries to greatly improve vanilla strongholds. I'm a bit lightheaded atm so I can't give a better description, sorry

**Why would you like the mod added?**
I've enjoyed the rest of YUNG's mods and think it'd fit, seeing as we already use his mineshafts mod (I think)
**Screenshots if applicable.**
https://i.imgur.com/DlaTuyp.png
https://i.imgur.com/8Hniubp.png
https://i.imgur.com/pt9Zz1B.png

**Comment by NillerMedDild** [comment]
Tested thoroughly by BlueNexus, I'll make a quick pass and add it. Expect to see it in 0.4.10 :)
