### ISSUE TITLE
Digital miner not mining

### ISSUE THREAD

**Issue by cc3768** [NillerMedDild/Enigmatica6#201]
**Modpack version**
0.2.14

**Issue**
Digital miner not mining

**Logs**
https://drive.google.com/file/d/1u4B-IY4i9VQXDY7iPsea7x3EoeVs6sF0/view?usp=sharing

**Notes**
Also reported this on mekanism git as well

**Comment by Shindur** [comment]
Are you claiming your chunks with FTB Chunks? If so you need to set mekanism as an ally via the ftb chunks menu

**Comment by cc3768** [comment]
it was not claimed at the time for the problem

**Comment by NillerMedDild** [comment]
Thanks, I'll check it out.

**Comment by NillerMedDild** [comment]
I can't reproduce this :/ I'll re-open if I manage to reproduce it later on, or if someone else does.
