### ISSUE TITLE
[0.4.8] Crash when exploring world

### ISSUE THREAD

**Issue by Lielac** [NillerMedDild/Enigmatica6#2014]
**Modpack version**
0.4.8

**Describe the bug**
On singleplayer, I explore the world and get a crash; right now it happens nearly as soon as I log in.

**Logs**
https://pastebin.com/YFHLEFk0 

**Screenshots**
N/A

**Comment by NillerMedDild** [comment]
Thanks for the report. This is a very rare issue caused by Supplementaries, manually updating it to the [latest version](https://www.curseforge.com/minecraft/mc-mods/supplementaries/files/3281805) should fix it :)
