### ISSUE TITLE
[0.4.8] Occultism Strorage NBT Overflow

### ISSUE THREAD

**Issue by Sourceshard** [NillerMedDild/Enigmatica6#2015]
**Modpack version**
0.4.8

**Describe the bug**
Related to issue #1752

I clicked my Occultism tablet in my inventory while it was in use. I assume it got put in the Occultism system. I am locked out of my server with a constant error message on login.

Rolling back character data allows me to access the server but if I use my hand held Occultism tablet I am immediately disconnected and cannot get back on. Server does not crash.

**Logs**
No errors in log. Sourceshard for reference. 
Paste just incase I missed something. https://pastebin.com/9PrvTfKN

**Screenshots**
![image](https://user-images.githubusercontent.com/37197624/115299937-667cfe80-a12d-11eb-83e8-6d7aacef3888.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. I doubt this will be fixed to be honest, as it has been an issue for these kinds of storage systems for ages.
What you can do is try to extract the tablet from the storage using automation, or load a backup.
