### ISSUE TITLE
Vanilla Hammers drop extra materials when mining

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#202]
**Modpack version**
0.2.12

**Issue**
Hello,
I dunno if this is intended or not but Vanilla hammers seem to occasionally drop extra materials based on what they're made off when you mine blocks https://i.imgur.com/e9yAlvV.png (this screenshot shows I was mining netherrack but it does the same with stone).
Diamonds with a diamond hammer and Tiled obsidian(from masonry) with an obsidian hammer.

**Comment by NillerMedDild** [comment]
That's not a bug, but it seems a bit broken if you got 4 diamonds from losing that little durability, is that the case? :)

**Comment by jinkhya** [comment]
It's the case yeah ^^
For testing purposes, on a brand new hammer :
https://i.imgur.com/V8aBiPM.png 
First row is how many blocks I mined to get the first diamond on
second row, 9 more blocks for second diamond
third row, again 9 more blocks for 3rd diamond :)

**Comment by NillerMedDild** [comment]
I'm going to go ahead and disable that :P thanks for testing!
