### ISSUE TITLE
[0.4.8] Tetra - Forge Hammer Stopped Working After...

### ISSUE THREAD

**Issue by Obsidian-Vanir** [NillerMedDild/Enigmatica6#2020]
**Modpack version**
0.4.8

**Describe the bug**
My Forge Hammer, 2 full batteries, 1 Combustion Upgrade 1 Other upgrade, managed to make 3 Obsidian Hammer heads without issue, and then stopped. I now have one full obsidian hammer and one with only one head. It doesn't appear to be a lack of materials, or integrity, is there another hidden requirement? Honed status level?

The hammer action functions, but the materials are not consumed. I've tried it multiple times, but it appears as if the hammer doesn't want to work, it won't get stuck and require a slap to un-jam. I want to try picking up the Forge Hammer and replacing it to see if that works, but I don't know if there's a way to do it without breaking it.

To confirm, it worked fine for 3 parts, and then stopped.

**Comment by NillerMedDild** [comment]
Thanks for the report. Please recharge the batteries and try again :)

**Comment by Obsidian-Vanir** [comment]
Ahah... figured out the issue. It's some sort of lag/disconnect issue. 

I'm playing on a server, and it seems the forge hammer was stuck in the jammed position. I had thought I cleared the jam, but the server did not. Re-log in, reload the blocks and the hammer was stuck in the jammed position, clear that and try again, no problem.
