### ISSUE TITLE
[0.4.8] immersive excavator

### ISSUE THREAD

**Issue by Toonlink264** [NillerMedDild/Enigmatica6#2021]
**Modpack version**
0.4.8

**Describe the bug**
unsure if it's a bug or an oversight or on purpose but the excavator from Immersive Engineering gives you ore blocks not ore chunks. 

**Logs**
n/a

**Screenshots**
n/a

**Comment by NillerMedDild** [comment]
That is indeed an oversight, thanks for the report :)

**Comment by MuteTiefling** [comment]
Went ahead and got these transferred in. Thought we could spruce things up a bit with new mineral deposits as well, but I'm a bit short of ideas for names. I've added Abyssalite already which brings in Thallasium and Ender Ore

The End could potentially use nodes for the following:
Amber: [Xyloretinite ](http://webmineral.com/data/Amber.shtml)?
End Silt type deposit with End Stone Dust and... others?
Aura Crystals?

Overworld could maybe use a diamond node? Kimberlite.

Could expand Igneous Rock node and possibly add Metamoprhic/Sedementary rock? Could use some help with a list of appropriate stones to add to these. 

Fossil dig site with Bone Blocks, Ammonite. Maybe some other things like Thrasher Teeth?

Can also add them for Undergarden ores. Just need fancy names.

**Comment by NillerMedDild** [comment]
> Amber: Xyloretinite ?
End Silt type deposit with End Stone Dust and... others?
Aura Crystals?

Perhaps one with Amber and Aurora Crystal / Crystal Shards

> Overworld could maybe use a diamond node? Kimberlite.

Sure why not 😄 

> Could expand Igneous Rock node and possibly add Metamoprhic/Sedementary rock? Could use some help with a list of appropriate stones to add to these.

What about Metamorphic stones from Botania?

> Fossil dig site with Bone Blocks, Ammonite. Maybe some other things like Thrasher Teeth?

Good idea with Thrasher Teeth. Perhaps Bone Serpent Teeth, Shark Teeth, Cachalot Whale Teeth.

> Can also add them for Undergarden ores. Just need fancy names.

I think these should just match the ore names, since they're fantasy materials.
