### ISSUE TITLE
[Suggestion] Flamboyant Recrafted

### ISSUE THREAD

**Issue by stylzm** [NillerMedDild/Enigmatica6#2024]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/flamboyant-recrafted

**Mod description**
Adds 16 new dye colors

**Why would you like the mod added?**
The new dye colors are all very nice and can have a variety of uses in building. The mod greatly expands the available color palette.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/46853295/115485504-bb8e4280-a209-11eb-8179-d6f0089faf88.png)

**Comment by NillerMedDild** [comment]
I think this is bound to cause issues with mods down the line to be honest, I'd rather not add it.
