### ISSUE TITLE
[0.4.8] Salvaging Tetra metal scrap gives duplicate metal types

### ISSUE THREAD

**Issue by Lielac** [NillerMedDild/Enigmatica6#2027]
**Modpack version**
0.4.8

**Describe the bug**
When I salvage Tetra metal scrap, I get ingots and nuggets from many different mods, e.g. copper from five or six different mods instead of them being unified under just EE. This rapidly fills up my inventory and then I need to do some annoying crafting to turn them into the EE metals.

**Logs**
N/A

**Screenshots**
https://i.imgur.com/GbcoeHn.png
I can barely get through half a stack of scrap before my inventory fills up.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
