### ISSUE TITLE
[0.4.8] Preparing Spawn Hangs Server

### ISSUE THREAD

**Issue by maca134** [NillerMedDild/Enigmatica6#2028]
**Modpack version**
0.4.8 (server windows 10)

**Describe the bug**
When the server is boot up it is hanging on "Preparing spawn area: X%"

**Logs**
https://pastebin.com/SmX2YmfE

**Comment by NillerMedDild** [comment]
Hmm, I'm not seeing anything actually go wrong in the log, other than the hanging of course.

How much RAM is allocated, and which version of Java are you using? 

I'm going to tag this as support, but feel free to continue here if you prefer GitHub over Discord.

**Comment by maca134** [comment]
It was all default settings, fresh from curseforge. The server was on a ESXi virtual machine with 16gig ram, I ended up moving the server elsewhere and no problems.
