### ISSUE TITLE
[suggestion] MrCrayfish's Furniture Mod

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#203]
As a builder it's always nice to have extra options to decorate interiors :)

**Comment by NillerMedDild** [comment]
In the past it has been highly unstable, do you know if that has changed? :)

**Comment by jinkhya** [comment]
Unstable as in crashes the server? if yes when ? (crafting, interaction with other mods, etc)

**Comment by NillerMedDild** [comment]
I crashed simply by placing some of the blocks, the last I tried was the mirror.

**Comment by jinkhya** [comment]
I tried a lot of them, and open their gui as well, it seemed fine. It's not fully ported yet though, I didn't find a mirror. This is what it adds for now, I'm guessing there is more to come : 
https://i.imgur.com/GOsXahD.png

**Comment by NillerMedDild** [comment]
Alright then, I'll try it out.

**Comment by NillerMedDild** [comment]
Correction: I'll try it out once it's out of alpha :)

**Comment by jinkhya** [comment]
Fair enough no worries :)

**Comment by NillerMedDild** [comment]
Still no new version, I'mma close this for now :)
