### ISSUE TITLE
[0.4.8] Black Transparent bar on right side of screen

### ISSUE THREAD

**Issue by LordDabbus** [NillerMedDild/Enigmatica6#2034]
0.4.8

There seems to be a black transparent bar at the side of the screen, disabled minimap to see if that was causing the issue but it is still present without. Nothing really game breaking, just a minor annoyance. 

![2021-04-21_18 45 10](https://user-images.githubusercontent.com/82982182/115631144-e391aa80-a2ca-11eb-9c2d-38198a0e6b83.png)

**Comment by MuteTiefling** [comment]
You`ve got a tracked quest that you`ve hidden instead of untracking.
