### ISSUE TITLE
[0.4.8] Pedestals Cobble Gen upgrade not entchantable with Silk Touch

### ISSUE THREAD

**Issue by Draccsos** [NillerMedDild/Enigmatica6#2037]
**Modpack version**
0.4.8

**Describe the bug**
The Cobble Generator Upgrade can not be combined with a silk touch in an anvil.

**Comment by TemperedFool** [comment]
@Draccsos you need to use the XP Anvil from Pedestals; there is an error in the quest for the Cobblegen that has been corrected in dev.
