### ISSUE TITLE
[ModpackVersion] bug claimed chunk

### ISSUE THREAD

**Issue by MrPandaYTB** [NillerMedDild/Enigmatica6#2039]
Hello we have found a bug related to your mod pack: enigmatica 6. we have tried to claim a chunk and when we are not in it, the chunk does not stay loaded. we would like to continue on this mod pack in order to complete it in full, hoping that this bug will be fixed.

On a Minecraft server with friends.

**Comment by NillerMedDild** [comment]
Did you also force load it? Claiming does not chunk load :)

**Comment by MrPandaYTB** [comment]
how did in this time to keep it loading?

**Comment by MrPandaYTB** [comment]
ok thanks
