### ISSUE TITLE
FTB Utilities claims don't show anymore

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#204]
**Modpack version**
0.2.14

**Issue**
Hello!
Claims don't show anymore in ftb map. There are claims where I'm standing in that screenshot : 
https://i.imgur.com/vtUXOEX.png

**Comment by Darkere** [comment]
Due to a crashing bug we had to downgrade FTBChunks to not crash anymore. 

At this point we can look into updating FTBTeams onto the 1.16.2 version as that fixes the issue (and "should" work with 1.16.1).

**Comment by NillerMedDild** [comment]
FTB Teams 1.16.2 is not marked as 1.16.1 compatible, so it wouldn't be approved in E6 as it stands :(

**Comment by jinkhya** [comment]
It's ok, it's not game breaking, it's not practical but it's better than no crash ^^
What about jenkins builds? (I don't know what's the policy about external mods for distribution on Curseforge)
https://i.imgur.com/GOsXahD.png

**Comment by NillerMedDild** [comment]
If the jenkins build file is also on CurseForge, it will not get approved :(

**Comment by MaxNeedsSnacks** [comment]
FTBChunks build 25 is still compatible with 1.16.1 from what I can tell, and has a couple of bugfixes ready, maybe this'll fix the claim overlay issue?

**Comment by Darkere** [comment]
Crashes on servers. You looked into that crash...

**Comment by MaxNeedsSnacks** [comment]
Oh yeah, ack.... I dealt with so many issues and crashes over the last two weeks I honestly forgot :p
