### ISSUE TITLE
Change MultiMC installation instruction to pull master branch instead of development branch

### ISSUE THREAD

**Issue by ZeMilkmann** [NillerMedDild/Enigmatica6#2044]
**Description**
In the README.md the MultiMC installation instructions advise the user to install the development branch, I recommend you change the instructions to install the master branch

**Why would you like this added/changed?**
A development branch is generally less stable and if fetched at the wrong time may cause issues which are specific to the development branch. Most users should be using the stable master branch.

**Screenshots if applicable.**

**Comment by MuteTiefling** [comment]
Do you mean the instructions for setting up a testing environment?

Those aren't meant for play. That's what curseforge files are for and those mirror the master branch.

The dev branch is specifically for testing new features prior to release and making PRs to enhance things or fix bugs.

**Comment by ZeMilkmann** [comment]
Ah yes, I read past the "For Contributors and Testers" line. 

I thought they were general instructions for people who would like to use MultiMC over the Curseforge launcher (for example because of the current delay between a version being published and Curseforge deciding to greenlight it)
