### ISSUE TITLE
Mekanism hover text shows "total" FE without taking upgrades into account

### ISSUE THREAD

**Issue by Infinoid** [NillerMedDild/Enigmatica6#205]
**Modpack version**
bd78d02 (v0.2.14)

**Issue**
![image](https://user-images.githubusercontent.com/50254/91612189-e5c58400-e94a-11ea-99e4-db73abb5382a.png)

160k out of 16k?

The hover text lists the current amount of energy, but the total it lists is not the real total.  The total is affected by energy upgrades, but the value shown in popup text is the original before upgrades.

Procedure to reproduce:
* make a mekanism digital miner
* insert 8 energy upgrades
* charge it up
* break it and pick it up
* move your mouse over it
* hold left-shift for details

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Infinoid** [comment]
Probably related: if you use a Powah Energy Cell's tool-charging slot to charge up the machine, it only charges up to the original energy level before upgrades.

![image](https://user-images.githubusercontent.com/50254/91645969-6aca9f00-ea18-11ea-8e62-556ea75c41c4.png)

![image](https://user-images.githubusercontent.com/50254/91645993-ad8c7700-ea18-11ea-9a32-5323fc448e79.png)

**Comment by Infinoid** [comment]
It is not specific to the digital miner.  It happens with the enrichment chamber too.  I suspect it affects any mekanism machine that takes energy upgrades.

![image](https://user-images.githubusercontent.com/50254/91646039-2e4b7300-ea19-11ea-9afe-0986ec319e9f.png)

![image](https://user-images.githubusercontent.com/50254/91646040-33102700-ea19-11ea-86e2-141d4fd59bee.png)
