### ISSUE TITLE
[0.4.8] Wheat Flour from putting Wheat in Pneumaticcraft pressure chamber

### ISSUE THREAD

**Issue by Lubscurum** [NillerMedDild/Enigmatica6#2051]
Currently using [0.4.8] and obtained the PneumaticCraft wheat flour. I put wheat in a 5x5x5 pressure chamber, out popped their wheat flour, reporting it as requested on the item.

**Comment by MuteTiefling** [comment]
Thanks for the report. Should be all fixed up.
