### ISSUE TITLE
[0.4.9] Compact Crafting Recipes are still missing

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#2056]
**Modpack version**
0.4.9 

**Describe the bug**
Compact Crafting Recipes from Normal Packmode scripts are still not working :(

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6381176/latest.log)

**Screenshots**

**Comment by MuteTiefling** [comment]
Can't reproduce this in Dev or single player. But I'm seeing it on the server for some reason. So I probably just Fd something up with the update. 

Does appear to be missing Item Tunnel Recipes, however. Looking into that.

**Comment by MuteTiefling** [comment]
Machines with a central block still do not craft after the updated recipe. Reported: https://github.com/CompactMods/CompactCrafting/issues/20

**Comment by MuteTiefling** [comment]
Still no clue why these don't show up on servers, however. Possibly related to #2057

**Comment by NillerMedDild** [comment]
We've seen so many mods with JEI that doesn't work on servers at this point, it's probably just another one of those :P

**Comment by MuteTiefling** [comment]
Eh, maybe. Il test on dev once it updates. But things still aren't working correctly in SP even with these fixes.
