### ISSUE TITLE
[0.4.9] Gears cannot be crafted

### ISSUE THREAD

**Issue by BlueNexus** [NillerMedDild/Enigmatica6#2057]
**Modpack version**
0.4.9 Alpha
**Describe the bug**
Gears can only be crafted with the multiservo press, which requires gears to craft. In addition, the gear form for the press requires gears.

**Screenshots**
![2021-04-27_02 40 28](https://user-images.githubusercontent.com/12956760/116172204-340d6b80-a702-11eb-9e2f-69998ca0619d.png)
![2021-04-27_02 40 25](https://user-images.githubusercontent.com/12956760/116172210-35d72f00-a702-11eb-890b-84bf6e77513b.png)

**Comment by MuteTiefling** [comment]
This appears to be a server issue. These recipes work for me in Dev and on my SP world, but I'm not seeing them on the official server either.

**Comment by NillerMedDild** [comment]
I'm guessing I messed up the normal recipes, I didn't test those as much as the expert ones.

**Comment by NillerMedDild** [comment]
It seems recipe loading on servers is messed up by outside sources, awaiting a fix.
