### ISSUE TITLE
[0.4.9] Server pack changes overworld biome

### ISSUE THREAD

**Issue by 0xicl33n** [NillerMedDild/Enigmatica6#2058]
[**This server pack**](https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/3290166)

**Describe the bug**
An overworld biome is changed, in singleplayer the biome does not change.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6381557/latest.log)

**Screenshots**
Server:
https://cdn.discordapp.com/attachments/544589452492931076/836409755052015646/unknown.png

Loading a backup of the world before the biome was changed in singleplayer:
https://cdn.discordapp.com/attachments/544589452492931076/836413948533538826/unknown.png

**Comment by NillerMedDild** [comment]
Which update did you update from? This is very similar to #1796

**Comment by 0xicl33n** [comment]
Updated from 0.4.8

**Comment by NillerMedDild** [comment]
... shit

**Comment by NillerMedDild** [comment]
Did you remember to change `server.properties` to Terraforged?

**Comment by 0xicl33n** [comment]
I was using the `server.properties`  file from 0.4.8 which already had terraforged

**Comment by NillerMedDild** [comment]
Alright, thanks! This is the same issue as #1796 it seems, just... again >_<

**Comment by NillerMedDild** [comment]
Would it be possible for you to update BYG in the old instance where the biome hasn't shifted yet, and see if the BYG update does it?

**Comment by NillerMedDild** [comment]
https://github.com/team-abnormals/atmospheric/issues/114

**Comment by NillerMedDild** [comment]
I don't think there's anything I can do about this issue now that is has happened, but I've added a mod that should prevent this in the future. Sorry for the inconvenience :/

**Comment by 0xicl33n** [comment]
We lost nothing for our server world since i took very good backups. I wanted to report this just in case someone else ever encounters it :D appreciate the support!

**Comment by NillerMedDild** [comment]
There's a possible sucky workaround btw:
> Downgrade to 0.4.8, load a backup, add the mod Chocolate fix, visit all places you want not to change and then update to 0.4.10
