### ISSUE TITLE
No slate generating (And possibly Jasper?)

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#206]
**Modpack version**
0.2.14

**Issue**
Slate is not generating in worlds, not sure when this started. Not sure on Jasper tho, haven't tested that. This was tested on a new world using the above modpack version, using a digital miner with itemstack filter set to slate.

**Comment by NillerMedDild** [comment]
I don't think Digital Miner testing is reliable enough tbh, it has had issues finding existing blocks in the past. But I'll look into it :)

**Comment by Shindur** [comment]
Noted on that. I've also explored a bit through some cold biomes by hand and with the mining laser. Maybe I'm just unlucky, but not sure. Does world stripper help show the block? I'm not 100% sure how to use it if it does.

**Comment by NillerMedDild** [comment]
It should yes, just press Delete while in Creative, it'll remove all stone, gravel, dirt etc below you. Don't do it anywhere you like though :P

**Comment by Shindur** [comment]
I've tried the delete key and it does indeed strip the few chunks it does. I was more curious if I can say "Strip this chunk but don't remove this particular block" as it seems to remove stone variants (granite, diorite, andesite) not sure on slate/jasper tho

**Comment by NillerMedDild** [comment]
You would have to change it's config to do that.

**Comment by jinkhya** [comment]
There seems to be an issue when big stones cluster is false (which is the case in enigmatica 6 quark's config), then none of the quark stones generate.
I know this is 1.14 put considering the issue is still open it's possible the bug is also present in 1.16.
https://github.com/Vazkii/Quark/issues/1830

**Comment by Shindur** [comment]
Interesting to note. Thanks for the relay of that report :) Niller any way to turn this feature back on, or are you bringing over what you did in E5 with the stone variants spawning outside of their usual biomes?

**Comment by NillerMedDild** [comment]
I'll be enabling the big stone clusters master switch config, and then disable them individually, hopefully that does the trick :)
