### ISSUE TITLE
Suggestion for compact machines recipe tweaks and quest line

### ISSUE THREAD

**Issue by mlpcoder** [NillerMedDild/Enigmatica6#2061]
**Description**
Applying the fix to enable CM recipes suggests some concerns to me. I suggest adjusting the recipe so that the walls required is evenly divisible by 32, and stagger the costs for less extreme progression, and add a quest line to introduce the mod and offer the first CM as an early quest reward. I see CM as an important option for reducing lag when setting up systems for automated production of resources and see a lot of benefits even before the player has gotten to the end and/or secured a good supply of ender pearls.  

**Edit: Updated in response to excellent suggestions below**

**Why would you like this added/changed?**

1. The recipes should require number of walls that are evenly divisible by 32.  _[WITHDRAWN]_

2. The number of walls required for each CM size should be adjusted as follows: _[WITHDRAWN, and look forward to slightly cheaper recipes]_

3. Add a new quest line introducing the mod and its benefits. I have included details below for a suggested quest progression which will help introduce the basic progression of the mod and make it slightly less grindy. See the sample quest line included at the end of this suggestion.

**Screenshots if applicable.**

**Sample Quest Line for Compact Machines**

Quest 1: Title: "Honey I Shrunk Everything"
Submit PSD and receive Normal Size CM

Description: "Compact Machines is a mod that allows you to create inter-dimensional "pocket" spaces to house your systems and machines, which can be helpful for reducing lag."

Quest 2: Title: "Begin the big work of working small"
Submit 4 projectors and receive a Large Size CM

Description: "To craft Compact Machines, you'll need to set up a multi-block with four "projectors".  A hollow cube is assembled with the required resources (check JEI) -- so for example a 5x5x5 cube for the smallest size machine. Then a catalyst item applied to initiate the process. The finished Compact Machine will pops out when the cycle is complete."

Quest 3: Title: "Tunnel Vision"
Submit 1 item tunnel to receive another item tunnel
Description: "You will want to pass materials into (and out of your Compact Machines) to the overworld which is accomplished with tunnels. The item tunnel allows you to pass items back and forth, and the redstone tunnel allows you to transmit power."

Quest 4: Title: "Lag-free gardens"
Submit the following items to receive a Normal compact machine as a reward
- 4 pedestals
- Pedestal upgrades: (1) Harvest, (1) Planter, (1) Export, (1) Filtered Import
- 8 wheat seeds
- 1 bucket water
- 1 block of glowstone
- 8 blocks of dirt
- 1 chests

Description: "Setting up a system like an automated farm in the compact machine allows you to generate resources without lagging the over world.  Gather the ingredients for a small automated farm and we'll give you a decent sized compact machine to put them in. We are using the Pedestal mod to automate the planting/replanting of seeds, the harvesting of wheat, and export of the wheat to a chest but you could use other mods and systems depending on your preferences. "

Quest 4: Title: "Size Matters"
Submit 1 Giant Compact Machine for random food reward
Description: "You will need the larger size machines to set up truly elaborate systems. "

**Comment by MuteTiefling** [comment]
Exact numbers would be ... difficult. Note that you do not just 'toss things down' in the middle and it goes. You build a shape.

In this case, it's a hollow cube. 

A hollow 5x5x5 cube is 98 blocks. 7x7x7 is 218. It just works out that way. They don't have to be cubes, of course, but it does complicate things a lot to use different shapes. Besides, the craft is already quite generous in providing 32 walls per, considering it's 2 pearls. The extra ones will almost certainly be used later in another machine, however. 

Pearls are also extremely accessible prior to opening The End, not that that takes long to get to either. But you can get them from villagers or hunting endermen in the overworld/nether (very easy in some biomes in the nether). Early game, it does represent a choice: Do I use these for a CM? Something else? Having to make those sorts of decisions isn't a bad thing. 

I do think we're going to need to adjust the recipes anyway, just to get around a bug. This will likely make them cheaper. 

Quests could be quite doable, however. More quests are always good :D

**Comment by mlpcoder** [comment]
@MuteTiefling hey thanks for the response. I've updated my quest suggestions accordingly based on your correct explanation.
