### ISSUE TITLE
[0.4.9] Rods can't be crafted in a metal press

### ISSUE THREAD

**Issue by DarkAngel22579** [NillerMedDild/Enigmatica6#2062]
**Modpack version**
0.4.9

**Describe the bug**
Rods can't be crafted using the metal press mold, can only be crafted through the crafting table recipe.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/74909944/116291099-1edd1f00-a78c-11eb-8728-f16862ae784e.PNG)

**Comment by NillerMedDild** [comment]
I've been informed that this issue is caused by recipes failing to load on servers because of a mod interaction, and a fix is being worked on :)
