### ISSUE TITLE
[0.4.9] Osmium Compressor

### ISSUE THREAD

**Issue by Athycer** [NillerMedDild/Enigmatica6#2065]
**Modpack version**
Enigmatica 6 - 0.4.9

**Describe the bug**
Upgrading the Osmium Compressor or its factory versions with speed upgrades causes the Liquid Osmium to be used at an increased rate but the progress speed is not is not affected resulting in the craft not finishing.

**Comment by xATL4S** [comment]
The osmium compressor is affected by efficiency, more speed upgrades = quicker machine but less efficient use of osmium 
 as noted in the following issue from the mek github

https://github.com/mekanism/Mekanism/issues/6787
