### ISSUE TITLE
[0.4.8] Pneumaticraft Refinery tank bug

### ISSUE THREAD

**Issue by TheOnlyMann** [NillerMedDild/Enigmatica6#2067]
**Modpack version**
0.4.8
**Describe the bug**
When breaking pneumaticraft refinery tank right next to the refinery controller, the game disconnected and shows me this: 

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6391638/latest.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/82017462/116400183-b6ae3c00-a864-11eb-930a-877dbc19f8f7.png)

**Comment by MuteTiefling** [comment]
Thanks for the report. This is a known issue and fixed already in 0.4.9
