### ISSUE TITLE
[0.4.8] Crash with Pedestal Fluid Exporter

### ISSUE THREAD

**Issue by TNehmke** [NillerMedDild/Enigmatica6#2068]
**Modpack version**
0.4.8

**Describe the bug**
Using pedestals to transfer an empty bucket from one pedestal to another one with the fluid export upgrade causes the game and server to crash. Loading into the world causes the same crash again.

**Logs**
https://ghostbin.co/paste/gjmxr
Ghostbin since pastebin is under maintenance right now

**Screenshots**
Not able to make sinc ethe game crashes instantly,

**Comment by NillerMedDild** [comment]
Thanks for the report, I've relayed it.

**Comment by Mowmaster** [comment]
oof, this has been fixed nearly a month, updating to pedestals 0.8s hotfix 3 is my only recommendation

**Comment by TemperedFool** [comment]
Which I think would make updating to 0.4.9 of the pack the recommended fix.
