### ISSUE TITLE
[0.4.9] Andesite Alloy with Mechanical Mixer goes wrong with 9 or more Andesite blocks.

### ISSUE THREAD

**Issue by kman3107** [NillerMedDild/Enigmatica6#2069]
**Modpack version**
0.4.9 from GDLauncher (Curseforge)

**Describe the bug**
I just threw, 12 Iron Nuggets and 12 Andesite into a Basin with a Mechanical Mixer (from Create) on top. Instead of getting Andesite Alloy, I got back 12 Iron Nuggets, 3 Andesite and 9 Heavy Stone Bricks.
I can make the Andesite Alloy if I use less than 9 Andesite.

**Video**
https://www.youtube.com/watch?v=QQVUUipSc30

**Screenshot**
![vlcsnap-2021-04-30-12h42m23s856](https://user-images.githubusercontent.com/10728652/116684794-b2dc0000-a9b1-11eb-94e5-bb7d925c8957.png)

**Comment by TemperedFool** [comment]
That sounds like a valid mixer recipe (9x andesite -> heavy stone brick) iirc, but I'd have to double-check JEI to be sure. If that's the case, the mixer will do whatever valid recipe it sees first.

To prevent this, filter the basin to andesite alloy, either with the alloy itself or a Create filter. That way it won't be allowed to run the Heavy Stone Brick recipe.

**Comment by kman3107** [comment]
It's not a valid mixer recipe according to JEI.

![Untitled](https://user-images.githubusercontent.com/10728652/116687207-187dbb80-a9b5-11eb-8848-b354cbd2f89a.png)

**Comment by MuteTiefling** [comment]
If I recall correctly, your can set a recipe filter on the basin, so it'll only craft the recipes you want, regardless of what goes in.

**Comment by kman3107** [comment]
It's a work around. But it's still a bug that should be fixed. Which is why I posted here.
I was going to acknowledge that part of your previous post but forgot. Though it's not going to do much for my automation unless I want a mixer for just that one recipe. I like doing things in bulk. So would be awesome if that was fixed since the mixer recipe is literally half the cost of the crafting table recipe.

**Comment by TemperedFool** [comment]
If you use an item filter, you can also blacklist heavy stone brick.

**Comment by TemperedFool** [comment]
It also isn't immediately clear, but we also didn't close the issue out ^_^

I imagine someone will look at the recipes soon...

**Comment by kman3107** [comment]
I made a new profile with kubejs, kubejs-create, create, create-plus, jei, ftb library and their dependencies.
Used the same modloader and mod versions. And the mixer is still making the Heavy Stone Bricks even though there is no recipe for it. So it's not an Enigmatica created problem.

**Comment by kman3107** [comment]
This is no longer an issue. I have tested in a new clean test pack with only necessary mods, and also in Enigmatica 6, and I've found that it's working as intended now.

**Issue has been resolved**
