### ISSUE TITLE
[ModpackVersion] Short_Bug_Description

### ISSUE THREAD

**Issue by trudruchocolatemilk** [NillerMedDild/Enigmatica6#2070]
0.3.13

I installed optifine so i could play with shaders. But when loading shaders, the skybox kinda freaks out. And it's different for different shaders. Like with Kuda the clouds just fade away and the sky turns white when you look up at it and with SEUS v11.0 there are random lines everywhere in the sky. Both of these shaders work fine in normal optifine 1.16.5. Any help would be appreciated (except just saying like "just dont play with shaders" because enigmatica is sick but even better with shaders)

[screenshot is SEUS v11.0]
![bruh moment h](https://user-images.githubusercontent.com/43690740/116717774-43611300-a9a7-11eb-9ea1-1ba25344ac07.png)

**Comment by TemperedFool** [comment]
Rendering issues with Optifine are pretty common, given that it messes with rendering to add the shaders. It's pretty impossible to provide troubleshooting/support for, as it's closed source so there's no way to know what it's messing with.

**Comment by OneLemonyBoi** [comment]
1. Did you install optiforge? if not, please install
2. Did you turn off the astral skybox, do so by following these steps:
        ```
Go into \config\astralsorcery-client.toml and move "minecraft:overworld" from skyRenderingEnabled to 
        skyRenderingConstellations. If that still doesn't work remove it entirely from both
```

**Comment by trudruchocolatemilk** [comment]
LETS FUCKING GOOOOOOOOOO
thanks bro very epic and it worked

![image](https://user-images.githubusercontent.com/43690740/116722492-722db800-a9ac-11eb-9b38-c05e2500086b.png)
