### ISSUE TITLE
Enigmatica6-0.4.8.zip Can't load pack

### ISSUE THREAD

**Issue by sid-marie** [NillerMedDild/Enigmatica6#2071]
Enigmatica6-0.4.8.zip

**Describe the bug**
When I go to open the modpack it comes up with the screen that I put in the screenshot area. Even if I choose to open in a vanilla it won't work

**Screenshots**
![image](https://user-images.githubusercontent.com/82244224/116728713-dd2abf00-a9ab-11eb-8ba1-8b713a698b9d.png)

**Comment by sid-marie** [comment]
Sorry it wont screenshot the right thing. It says word per word "Errors in currently selected datapacks prevented the world from loading......"

**Comment by NillerMedDild** [comment]
Why did you close the issue? :) 
If it is not resolved, please provide your latest.log.
