### ISSUE TITLE
[0.4.8] Insert Kangaru mob to IF mob duplicator make server crash.

### ISSUE THREAD

**Issue by AlphaP2712** [NillerMedDild/Enigmatica6#2072]
**Modpack version**
0.4.8
**Describe the bug**
Using IF mob duplicator with  Kangaru Crashing server

**Logs**
https://pastebin.com/JDpDBvuB?fbclid=IwAR093i_08QM8f5erGavKotfnu7lu6gBItg2FjVa07x3Qt3y9uZxSt1FuuS0

**Screenshots**

**Comment by NillerMedDild** [comment]
I believe this is fixed in 0.4.9 and 0.4.10 which will be releasing soon :)
