### ISSUE TITLE
[0.4.8] Vein mining grass with shears makes items stop dropping

### ISSUE THREAD

**Issue by Exekyel** [NillerMedDild/Enigmatica6#2073]
**Modpack version**
0.4.8

**Describe the bug**
When I vein-mine grass using shears, nothing drops, and then I am not able to make any items drop in the world at all: not left-clicking grass with shears, not punching dirt, and not throwing items from my inventory. I am no longer able to make items drop in the world in any way. This persists in single player after quitting and restarting. It persists through death as well.

I first encountered this last night playing on a server, so I logged off for the night. Today I logged in again and things were working normally, until I tried vein-mining grass with shears again (I need grass for redstone roots in Botania lol).

**Logs**
It happened around \[19:50:39]
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6408790/latest.log)

**Screenshots**
Targeting grass with livingrock shears and vein-mining enabled
![2021-04-30_19 53 30](https://user-images.githubusercontent.com/11582491/116769121-be99e780-a9ee-11eb-8888-b42aa9bb3895.png)
Nothing dropped and no items in inventory
![2021-04-30_19 53 39](https://user-images.githubusercontent.com/11582491/116769117-bd68ba80-a9ee-11eb-971b-53a7fa7a39cd.png)
Same for dirt
![2021-04-30_19 53 39_2](https://user-images.githubusercontent.com/11582491/116769120-be99e780-a9ee-11eb-9e80-a1d64947a8b1.png)

**Comment by Exekyel** [comment]
It actually just lasted into a new single player world, but I quit to desktop, closed curseforge, and restarted from there and it stopped happening. Will try logging into the server again.

**Comment by NillerMedDild** [comment]
You have to restart the server most likely :)

**Comment by NillerMedDild** [comment]
Reported the issue here: https://github.com/MelanX/aiotbotania/issues/65
And disabled both shears from AIOT Botania.
