### ISSUE TITLE
It is very easy to accidently craft all of your coal into "Fire For Standing Torch"

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#2074]
**Description**
When you craft something with coal, like torches, you can very easily accidentally craft all of your coal into Fire For Standing Torch (especially on a server). 

**Why would you like this added/changed?**
I've turned all of my early game coal into these little fires more times than I can count on my hands. Going way back to September of last year. Finally got sick of it and made this issue. A fix could be changing the Fire For Standing Torch recipe.

**Screenshots if applicable.**
N/A

**Comment by NillerMedDild** [comment]
It is indeed 😄 about time we change it.

**Comment by pm065** [comment]
maybe coal + flint and steel without consuming the flint and steel?

**Comment by NillerMedDild** [comment]
That particular recipe is not possible at this time sadly.
