### ISSUE TITLE
[0.49] Game crashing when loading worlds

### ISSUE THREAD

**Issue by adjctve** [NillerMedDild/Enigmatica6#2076]
**0.49**

**Describe the bug**
When loading single player worlds, the game crashes and returns an exit code 0.

**Comment by pm065** [comment]
You'll need to get the latest.log file from (user)/curseforge/minecraft/instances/Enigmatica 6 - E6 - 1.16.5/logs :)

**Comment by adjctve** [comment]
> You'll need to get the `latest.log` file from `(user)/curseforge/minecraft/instances/Enigmatica 6 - E6 - 1.16.5/logs` :)

not sure if this is it, but here it is.
[Uploading latest.log…]()

**Comment by NillerMedDild** [comment]
You pressed submit too fast :P please try again

**Comment by adjctve** [comment]
> You pressed submit too fast :P please try again
haha my bad
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6410403/latest.log)

**Comment by NillerMedDild** [comment]
There's no crash in there, but there are a number of others issues. I recommend that you try with [version 0.4.10](https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/3295284) in stead, but also make sure to follow this TL;DR guide about setting up modpacks: https://github.com/NillerMedDild/Enigmatica6/wiki/Recommended-Settings-for-Enigmatica#TLDR
