### ISSUE TITLE
[0.4.9] Lag spike when crossing claimed chunks while travelling west

### ISSUE THREAD

**Issue by maca134** [NillerMedDild/Enigmatica6#2077]
**Modpack version**
0.4.9

**Describe the bug**
When crossing claimed chunks in the west direction, there is a noticeable lag spike. It only happens the first time you cross in west direction, until you cross over another chunk going east. It only seems to be happening in claimed chunks and only when traveling west.

**Screenshots**
I can provide a video if needed.

**Comment by NillerMedDild** [comment]
Thanks for the report, a video would be very helpful :)
@maxneedssnacks Got any idea about what might be causing this?

**Comment by MaxNeedsSnacks** [comment]
Nope, there's no reason why it should happen (or at least why, if claimed chunks are responsible, it's restrained to this one specific case)

**Comment by maca134** [comment]
Retested again, its seems alittle more intermittent but still only happening when crossing chunks while going west.
Also it is happening in non-claimed chunks.
https://dl.dropboxusercontent.com/s/ox6h98nqltbexi2/zfpTfmMxKAgAaIRfbSFu.mp4

**Comment by NillerMedDild** [comment]
I can reproduce it in several directions sadly, it seems to be worldgen lag.

**Comment by NillerMedDild** [comment]
I can no longer reproduce this in 0.5.0, gonna mark it as fixed :P
