### ISSUE TITLE
[0.4.9] Mobs spawn switch between nether and overworld

### ISSUE THREAD

**Issue by AEJJH** [NillerMedDild/Enigmatica6#2078]
0.4.9

I've just updated my server to the 0.4.9 version. And since it seems that there is a problem in mob spawning.
- I see pigmen and magma cubes spawning in the overworld and it seems that other hostile mobs has disappeared
- And I see Zombies and Creepers spawning in the nether...

Is this a bug or a new feature ? Is it a configuration problem ?

Could someone help me to deal with this ?

Thanks,

AEJJH

**Comment by NillerMedDild** [comment]
I'm guessing the biomes have shifted in those particular biomes? Could you check their names?

**Comment by AEJJH** [comment]
in the overworld => byg:black_forest_clearing
in the nether => atmospheric:rainforest_basin and atmospheric:rainforest_mountains

**Comment by NillerMedDild** [comment]
Dammit :/ I don't think there's anything I can do about it now, but I've added a mod that should prevent this in the future.

**Comment by NillerMedDild** [comment]
There's a possible sucky workaround btw:
> Downgrade to 0.4.8, load a backup, add the mod Chocolate fix, visit all places you want not to change and then update to 0.4.10
