### ISSUE TITLE
Abnormals Core (abnormals_core) encountered an error during the common_setup event phase: null

### ISSUE THREAD

**Issue by Infinoid** [NillerMedDild/Enigmatica6#208]
**Modpack version**
bd78d02 (v0.2.14)

**Issue**
The game failed to launch.  Before it reached the main menu, it died with this error:

![image](https://user-images.githubusercontent.com/50254/91638905-bbbea100-e9e0-11ea-8c30-e2d0c1c4b787.png)

I have seen this happen exactly once.  I have been able to launch this version 4 or 5 times so far with no other issues.

**Logs**
https://paste.ee/p/CGa3S#s=0&l=852

The exception occurs on line 852.

**Comment by NillerMedDild** [comment]
Thanks for the report, I've relayed it :)
