### ISSUE TITLE
[0.4.10] Entering nether portal kills the player and does not create a gravestone

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#2082]
**Modpack version**
0.4.10

**Describe the bug**
When my friend leaves the nether it says he suffocated in a wall and he does not get a gravestone (his items are completely gone).

**Logs**
N/A

**Screenshots**
N/A

**Comment by RevenantWendigo** [comment]
![image](https://user-images.githubusercontent.com/1980813/116803428-cdf36080-aad4-11eb-9b32-280d3d13f8b3.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by RevenantWendigo** [comment]
Also wanted to mention that this happened to my friend the other day on 0.4.9, he died somehow (to a mob or something) and he got the same message and his items were voided. 

Thanks for looking into this Niller, I deeply appreciate it!

**Comment by NillerMedDild** [comment]
I can't reproduce it, I'm guessing your buddy just has a very very unlucky nether portal spawn, or someone "pranked" him. I've requested that our grave mod adds a command to restore inventories.

**Comment by RevenantWendigo** [comment]
I can guarantee there is no pranking going on. It's just myself and two other close friends and we're all teamed up together.

Here is a video I recorded: https://www.youtube.com/watch?v=gIsW1eaL3qw

**Comment by NillerMedDild** [comment]
What the actual ****
Thanks for the video, that helps greatly. I'll try to figure out what's going on here.

Do you have any baubles on? Any lost trinkets active?

**Comment by RevenantWendigo** [comment]
No baubles and I have the wither nail trinket equipped.

**Comment by KrAzYGEEK32** [comment]
fwiw i have the issue pretty frequently on the official server, nether portals are my bane. it mostly occurs when players are stuck in a loop while going trough a portal, the player then gets teleported 5k blocks from the portal either in the nether or (mostly)overworld, spawns inside a wall and suffocates to death. atleast the quark totem got force placed so i never lost my inventory. happens mostly because of lag and some mod messing with nether portal logic.

**Comment by RevenantWendigo** [comment]
That's interesting that you mention that Krazy, we play with a world border so I wonder if it is teleporting us outside of it and insta killing us. That actually might be it!

I guess we need to find out why it is teleporting us so far in these recent updates. My friends and I have played with a world border for many worlds going back to 0.2 and have never had this happen until now.

**Comment by RevenantWendigo** [comment]
I doubled the size of my world border and now it doesn't seem to happen anymore.

Still wondering what is causing the portal to teleport players to weird places before going to the intended location. I guess my problem is solved though.

**Comment by NillerMedDild** [comment]
> Still wondering what is causing the portal to teleport players to weird places before going to the intended location.

That has been happening for years sadly, I think it has something to do with the player's connection to the server, and/or lag?

**Comment by RevenantWendigo** [comment]
Is there a specific place it teleports players to first? It's just so bizarre to me that this is the first time I've experienced this problem. I've been playing with smaller world borders for a while now.

**Comment by NillerMedDild** [comment]
Not that I know of :/ could you perhaps try removing the mod NetherPortalFix, decrease your worldborder and see if the issue is still there? :x

**Comment by RevenantWendigo** [comment]
Yeah I'll try it on a new instance. Don't know if I will get around to it today though. I'll report back when I do try it.

**Comment by SQbuilder** [comment]
Me and everyone on my server is having the exact same problem.

**Comment by RevenantWendigo** [comment]
Do you guys have a world border that is smaller than the default?

**Comment by SQbuilder** [comment]
We do not have a world border. Players are guessing its a network problem, as I (server owner) tried going through the nether portal on the same machine the server is running and everything was fine.

**Comment by SQbuilder** [comment]
Update: I removed NetherPortalFix from my server and it did not fix the issue. One of my players cannot leave the nether.

**Comment by SQbuilder** [comment]
For people that have a similar problem with Nether Portals, there is a work-around. Place a Waystone in the nether in creative mode, and set it to be global, so all players have the Waystone entry be default. Then simply use Waystones to travel to and from the Nether.

**Comment by ckhawks** [comment]
I am experiencing the same issues on my server -- am running a worldborder, multiple people experiencing the suffocation even with 0 ping to the server.

**Comment by NillerMedDild** [comment]
We're working on getting this fixed :)
