### ISSUE TITLE
[ModpackVersion] Short_Bug_Description

### ISSUE THREAD

**Issue by ArseniyHope** [NillerMedDild/Enigmatica6#2084]
Enigmatica6-0.4.10
Have a 10-30 fps on rx6700xt and r5 2600 16gb RAM, what i need to do? That a last version of mod.

**Comment by ArseniyHope** [comment]
Have a 10-30 fps on rx6700xt and r5 2600 16gb RAM, what i need to do? That a last version of mod.

**Comment by TemperedFool** [comment]
@ArseniyHope The discord (https://discord.gg/Uxrzcz8V) has a #performance channel, which would be the place to get help for issues like this.

**Comment by NillerMedDild** [comment]
https://github.com/NillerMedDild/Enigmatica6/wiki/Recommended-Settings-for-Enigmatica would also be a good thing to read :)
