### ISSUE TITLE
[0.4.10] Crashutilities... crash

### ISSUE THREAD

**Issue by Seceroth** [NillerMedDild/Enigmatica6#2085]
**Modpack version**
0.4.10

**Describe the bug**
After running the command
`/crashutilities chunks byTicket 1`
The server crashes.

**Logs**
[crash-2021-05-02_18.54.58-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6411863/crash-2021-05-02_18.54.58-server.txt)

**Comment by Darkere** [comment]
...what type of ticket is "1" ?

**Comment by Seceroth** [comment]
Supposedly, Dimension, so would expect it to refer to The End.

**Comment by Darkere** [comment]
...
In 1.16 dimensions are no longer used by ID. 1 for the end is now not a thing anymore. It's "minecraft:the_end".

Tickets is what mods create when they load a chunk. They assign a ticket to the chunk to make it possible to figure out what caused a chunk to be loaded. For example the "minecraft:start" ticket that gets assigned to the world spawn chunk. 

I will fix the crash tho.

**Comment by Seceroth** [comment]
I see. Was just checking out the various commands of the mod. And still relatively new to 1.16 and saw this:
![Knipsel](https://user-images.githubusercontent.com/20866237/116821906-810e9900-ab6b-11eb-93a6-66f8e0f70cb5.PNG)
So decided to try 1, assuming "dim" refers to dimension.

**Comment by Darkere** [comment]
Ah I see. Yeah that is in the wrong place. Misplaced a bracket :) Thanks for bringing it to my attention.
