### ISSUE TITLE
Slime Farm Problem

### ISSUE THREAD

**Issue by keremlov** [NillerMedDild/Enigmatica6#209]
**Modpack version**

0.214
**Issue**
I built a vanilla slime farm but it's not functional. I lit up all the caves around it with feral flare lanterns and no result, no spawns... Can someone help?

**Comment by NillerMedDild** [comment]
Possibly silly question, are the chunks slime chunks?

**Comment by keremlov** [comment]
Yes ofcourse, I double checked it with the xareo's map and online slime chunk finder. I got 26 slime balls in 2 hours. Its a 5 layer farm starting from y level 25 to 8. There is no dark space around 20 block radius I checked it with spectator mode. I don't know what am I doing wrong honestly

**Comment by douyabian** [comment]
vanilla mob spawning mechanics is that mobs that spawn out of a sphere of 128 blocks will despawn immediately, 
in that case for a higher efficiency in your slime farm you'd have to light up more than 20 blocks away from your character, preferably up to 128 blocks

**Comment by keremlov** [comment]
Yeah but like I watch the person who was showing the farm and while he was building it he got 5 stacks of slimeballs. It can't be about just lighting you know? Maybe it's because quark adds a lot of caves or something? I don't know

**Comment by NillerMedDild** [comment]
If slimes are spawning then the farm is functional imo :D
E6 does not modify slime spawning, so this is most likely caused by other mobs spawning near the farm, as douyabian suggests.

**Comment by keremlov** [comment]
OK then thanks, I just thought I must've doing something wrong. Do you know how far do I have to go to afk?

**Comment by NillerMedDild** [comment]
24-32 blocks away :)
https://www.dataless822.net/mobile/forum/viewthread/m/12923691/id/19726486-help-slime-farm

**Comment by HalJordan** [comment]
Sadly, the only other way to get slime balls in E6 is to go the bee route. No way to farm them yet(sobs in Tinker's Construct).

**Comment by Merlo17** [comment]
I can name probably 5 other ways to get slime

**Comment by TemperedFool** [comment]
I was going to say - create plus a botany pot with lime green plants in it has solved this problem for me...
