### ISSUE TITLE
[0.4.10] Biomes Change when updating to new version

### ISSUE THREAD

**Issue by Vidanox** [NillerMedDild/Enigmatica6#2090]
0.4.10

All biomes changed when updating from 0.4.8 to 0.4.10
Tried removing chocolatefix before starting the server, no difference 
![030521](https://user-images.githubusercontent.com/20267225/116858545-d3e56080-abfe-11eb-8880-ea3406f728dc.png)

pic rel was a jungle biome and now its a marshland

**Comment by Vidanox** [comment]
sorry i didnt see 
https://github.com/NillerMedDild/Enigmatica6/issues/2058#issuecomment-830853923
i'll try it now

**Comment by Vidanox** [comment]
> sorry i didnt see
> [#2058 (comment)](https://github.com/NillerMedDild/Enigmatica6/issues/2058#issuecomment-830853923)
> i'll try it now

does not work

**Comment by tangzixiang-hash** [comment]
是的，我们所在服务器从0.4.8升级到0.4.10时也出现了这个问题。
目前需要您的帮忙

**Comment by NillerMedDild** [comment]
> does not work

Could you please walk me through what you did? :)

**Comment by Vidanox** [comment]
> > does not work
> 
> Could you please walk me through what you did? :)

put chocolatefix in the server files, booted the server up, walked around for a while, removed all files except the "world" folder, upadated to 0.4.10, ran the server and thats that
i also tried using the /forge generate command and this other mod 
https://www.curseforge.com/minecraft/mc-mods/biome-id-fixer
nothing worked

also since you're reading this just a quick thanks, my friends and i are really enjoying your pack :)

**Comment by NillerMedDild** [comment]
Did you load a backup first? Chocolate fix doesn't fix anything once it's broken sadly, it works by making sure ids don't shift in areas that the user has been in while Chocolate Fix is present.

**Comment by MuteTiefling** [comment]
Got a tip from Snipps on Discord that they were able to fix this by reverting to backup and installing biomeidfix before updating again.

**Comment by Vidanox** [comment]
> Did you load a backup first? Chocolate fix doesn't fix anything once it's broken sadly, it works by making sure ids don't shift in areas that the user has been in while Chocolate Fix is present.

i installed chocolatefix before updating the server files, yes

> Got a tip from Snipps on Discord that they were able to fix this by reverting to backup and installing biomeidfix before updating again.
> 
> https://www.curseforge.com/minecraft/mc-mods/biome-id-fixer

do you know whether they installed biomeidfix alongside chocolatefix or removed it?
i tried to  get it to work and the server just wouldnt boot

**Comment by Vidanox** [comment]
ok it worked this time for some reason, thread closed
