### ISSUE TITLE
Mod files, ... are missing from the server files (since v0.4.10).

### ISSUE THREAD

**Issue by TarantelFaser** [NillerMedDild/Enigmatica6#2091]
**Description**
The server files are missing mod files, ... .

**Why would you like this added/changed?**
Well there are no server files and I'd like to start a server with my friends.

Sorry if this isn't the right type of Issue, I didn't wanted to report this as a bug...

**Comment by Darkere** [comment]
The serverfiles come with a script that downloads all the mods for you. 

This is quite a bit easier for us to set up and should help some people speed up their server setup if they can run the script on the server instead.

**Comment by NillerMedDild** [comment]
Also, there's a guide in the server files that explains what to do :)

**Comment by TarantelFaser** [comment]
Yeah sorry, I was confused because the other server files were larger, I actually read the other files but apparently I didn't get that It would auto-download everything. 
My bad :)
This modpack is awesome, just wanted to say thanks!

**Comment by NillerMedDild** [comment]
Glad you like it! 😃
