### ISSUE TITLE
Genetic Animals

### ISSUE THREAD

**Issue by Theamara** [NillerMedDild/Enigmatica6#2093]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/genetic-animals

**Mod description**
Fairly lightweight mod that adds genetics and a ton of new models/variations to only the vanilla animals, i.e. cows, sheep, pigs, llamas, chickens, rabbits (currently). 

**Why would you like the mod added?**
I know this is quite a niche area of the game, but I feel that something like this would certainly appeal to the humble ranchers/farmers among us :) The genetics part of the mod is really fun to play with, and I feel that the newly introduced behaviors and models compliment Alex's Mobs and Resourceful Bees quite well. 

As far as I can tell, nothing else in this pack currently touches vanilla animals, and after a few days of playtesting thus far on our server it seems to work just fine. The only consideration might be a few minor recipe incompatibilities for some of the new animal products, possibly within Farmer's Delight or other farming/cooking related mods.

Thank you for any consideration on this :) I hope something like this isn't so niche as to cause annoyance.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, but I think this is a bit outside the scope of Enigmatica 6 :)
