### ISSUE TITLE
[0.4.10] Ametrine Gem is dropping.

### ISSUE THREAD

**Issue by kman3107** [NillerMedDild/Enigmatica6#2097]
**Modpack version**
0.4.10

**Describe the bug**
Ametrine Gems are dropping. Information section says to report it here.
Found on a floating island in the Shattered Viscal Isles biome.

**Screenshots**
![2021-05-04_16 28 15](https://user-images.githubusercontent.com/10728652/117019552-cb238600-acf5-11eb-9955-a2396fd81504.png)

**Comment by CletusMAngo** [comment]
This isnt a bug. BYG has reworked ametrine and moved it into the end. this is fully intentional :/

**Comment by MuteTiefling** [comment]
Well, we disabled them, I'm pretty sure. Config is probably in need of a double check

**Comment by NillerMedDild** [comment]
I think this has since been fixed, I can't reproduce it.

**Comment by kman3107** [comment]
I downloaded a clean E6 profile version 0.4.10, started up a new world and went for the end.
Again I find Ametrine Ore and can mine it. Therefore I'm assuming you've done something in your 0.4.11 to fix this.

**Comment by NillerMedDild** [comment]
At long last I found one 😄
