### ISSUE TITLE
[0.4.10] Seeds can be used to repair tools

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#2099]
**Modpack version**
0.4.10, replicated in Dev

**Describe the bug**
Diamond swords (possibly others) can be repaired with any seed...

**Screenshots**
![image](https://user-images.githubusercontent.com/9543430/117030595-cba82680-accd-11eb-8d37-701ed344ffd0.png)

**Comment by MuteTiefling** [comment]
actually, this appears to accept -any- item. I cna repair with chalk, plant oil, polished andesite...

**Comment by NillerMedDild** [comment]
What on earth 😄

**Comment by MuteTiefling** [comment]
I know, right?!

**Comment by BlueAgent** [comment]
Reproducible with just Apotheosis (and Placebo) installed.

Mods:

- Apotheosis-1.16.4-4.5.2
- Placebo-1.16.4-4.4.2

<details>
<summary>Screenshot</summary>

![Repairing a diamond sword in an anvil using seeds](https://user-images.githubusercontent.com/630920/117455871-2ebde580-af7a-11eb-919e-a3908aefdcb0.png)
</details>

**Comment by MuteTiefling** [comment]
Thanks Blue!
