### ISSUE TITLE
Fortune III addon in Mining gadgets doesn't seem to work properly, returning 1 item every time

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#210]
**Modpack version**
0.2.14

**Issue**
https://github.com/Direwolf20-MC/MiningGadgets/issues/102 
For info :)

**Comment by jinkhya** [comment]
It seems that there is an incompatibility with laser relay mod. I've been running the server and the client without laser relay for a while now and there's no problem with Fortune III or the laser not showing properly anymore. I asked my friends who were having the issue as well to disable it on their clients and as soon as they disabled it, it was fixed.

I wanted to test an instance with just mining gadget and laser relay but it seems like laser relay doesn't even load by itself ; that's the error I get on a fresh instance with forge 108 and laser relay 1.7
https://i.imgur.com/QjyJyek.png
I'm not sure how Enigmatica 6 loads with it if the mod alone doesn't ^^

**Comment by Darkere** [comment]
Looks like the mod has an unintentional Mekanism dependency.

**Comment by jinkhya** [comment]
Interesting. Then I can confirm that mekanism + laser relay + mining gadget breaks the laser beam of the mining gadget but the fortune III addon works as intended, so I'm not sure about that (unless that one is not consistent  which is possible)

**Comment by NillerMedDild** [comment]
I'm seeing neither of those issues in-dev :/

**Comment by jinkhya** [comment]
mh... your laser beam is still working with mekanism + laser relay + mining gadget?

**Comment by NillerMedDild** [comment]
Yup, unless I have to place down some specific blocks?

**Comment by jinkhya** [comment]
Not really no.
This is what it used to look like before disabling laserrelay : https://streamable.com/fp5y3t
For the fortune 3 I couldn't reproduce it easier. When it was not working I was testing on quartz ores and diamond ores.

**Comment by NillerMedDild** [comment]
Hm, I guess this may have been fixed by updating in-dev, fingers crossed.

**Comment by jinkhya** [comment]
Alrighty I'll check it out when next release is out and will let you know :)

**Comment by NillerMedDild** [comment]
E6 0.2.15 is now available :) https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/3049817

**Comment by jinkhya** [comment]
Yup yup I'll be updating server and clients this weekend, thanks for the heads-up! :D

**Comment by jinkhya** [comment]
Well the fortune 3 seems to still be working, however my laser beam is gone again :)
And disabling laser relay mod fixed it. I don't know how or why it interacts with it and not for you. :cry:

**Comment by NillerMedDild** [comment]
Me neither, but I'll call this issue fixed :)
