### ISSUE TITLE
[0.4.10] Elite Centrifuge Bug

### ISSUE THREAD

**Issue by ColdDead** [NillerMedDild/Enigmatica6#2106]
**0.4.10**

**Describe the bug**
Processing with the Elite Centrifuge BeeBoo HoneyComb does not work

**Logs**
No Crashes, no logs

**Screenshots**
https://i.imgur.com/ECi0fqK.png

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by ColdDead** [comment]
I think the Problem is whit the elite, i have multiple items now thats not working

**Comment by ColdDead** [comment]
FUCK sry, my system jam, is working...         That with the pipe still a issiu

**Comment by NillerMedDild** [comment]
As a temporary workaround, but bottles in there and place the combs again.

**Comment by NillerMedDild** [comment]
Actually that's.. just the fix 😄
