### ISSUE TITLE
[0.4.10] Ender Shard recipe conflict

### ISSUE THREAD

**Issue by kman3107** [NillerMedDild/Enigmatica6#2107]
**Modpack version**
0.4.10

**Describe the bug**
Ender Shard recipe is in conflict with two other items on several machines.

**Screenshots**
![2021-05-05_14 51 44](https://user-images.githubusercontent.com/10728652/117145072-02a43800-adb3-11eb-8fa3-1cdbcbd77b69.png)
![2021-05-05_14 51 28](https://user-images.githubusercontent.com/10728652/117145085-05069200-adb3-11eb-9569-96f3a414e498.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
