### ISSUE TITLE
SushiGo Crafting

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica6#2108]
https://www.curseforge.com/minecraft/mc-mods/sushigocrafting/files

FESH!!!

**Comment by Merlo17** [comment]
Oo

**Comment by MuteTiefling** [comment]
But does it have sushi singularities?

**Comment by theboo** [comment]
@Buuz135 does it?

**Comment by NillerMedDild** [comment]
Already in on the dev branch 😄

**Comment by NillerMedDild** [comment]
Will be added in 0.5.0 hopefully.
