### ISSUE TITLE
[0.4.10] Server crash Integrated Crafting, IF

### ISSUE THREAD

**Issue by Seceroth** [NillerMedDild/Enigmatica6#2109]
**Modpack version**
0.4.10

**Describe the bug**
I have a Crafting writer set up to autocraft Nether Stars using the IF Wither builder. The IF Wither builder wasn't building the Wither even though it has all the requirements are met. It was working a few times before, but stopped working seemingly randomly. I tried to remove a Wither Skull and then the server crashed.

**Logs**
[crash-2021-05-05_18.23.03-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6428841/crash-2021-05-05_18.23.03-server.txt)

**Screenshots**
The moment the client froze because the server crashed before returning to the main menu:
![Knipsel](https://user-images.githubusercontent.com/20866237/117178355-777e6e80-adc1-11eb-8d24-be07ec7d16bc.PNG)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
