### ISSUE TITLE
TellMe mod using gold nugget as debug item

### ISSUE THREAD

**Issue by douyabian** [NillerMedDild/Enigmatica6#211]
Enigmatica 6 - 0.2.14

The TellMe mod uses the golden nugget as a debug item in the config by default and is shipped as such, can't interact with anything while holding a gold nugget, just a minor inconvenience

Might wanna remove or change it to a creative-only item or something

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I disabled both debug items :)
