### ISSUE TITLE
[0.4.10] Looking up ascends ladders

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#2111]
**Modpack version**
0.4.10

**Describe the bug**
When you're in contact with a ladder, if you look upwards you rapidly ascend the ladder. I'm not sure which mod adds this behavior, but it's new since 0.4.8, and it makes building while on a ladder really difficult. It may also be redundant on whatever mod in 0.4.8 caused looking down while descending a ladder to descend faster.

**Logs**
n/a

**Screenshots**
n/a

**Comment by NillerMedDild** [comment]
The mod that does that is clienttweaks, you can disable it in it's config, it will not be overriden by updates :)
