### ISSUE TITLE
Mekanism universal cable problem

### ISSUE THREAD

**Issue by sauphle** [NillerMedDild/Enigmatica6#2112]
The universal cables from mekanism stop the energy from flowing through. Using the configurator helps but where you use the configurator becomes the new stop point.

![2021-05-05_17 27 07](https://user-images.githubusercontent.com/80305735/117218489-de535600-adc8-11eb-956a-272076d25ef6.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
> The universal cables from mekanism stop the energy from flowing through.
Stop the energy from flowing through what?

**Comment by sauphle** [comment]
The energy "fluid" seems to stop at the intersection where you can use the configurator to change it from normal to push to pull to none. Relogging fixes the problem as well.
-------- Original message --------From: Niels Pilgaard Grøndahl ***@***.***> Date: 2021-05-09  15:59  (GMT-06:00) To: NillerMedDild/Enigmatica6 ***@***.***> Cc: sauphle ***@***.***>, Author ***@***.***> Subject: Re: [NillerMedDild/Enigmatica6] Mekanism universal cable problem (#2112) 

The universal cables from mekanism stop the energy from flowing through.
Stop the energy from flowing through what?

**Comment by NillerMedDild** [comment]
Can you reliably reproduce it somehow?

**Comment by sauphle** [comment]
My computer is very slow and sometimes I get HUGE lag spikes when playing.
I know it's not a chunk error because it's not on a chunk. I used to play
many hours at a time and that's when the problem happened.
My base also has a lot of things working with a lot of items and Mekanism
machines working.
It might be just a problem for me and I thought at least sharing it will
help
sorry if I could not help

**Comment by NillerMedDild** [comment]
Thanks for sharing, I'll be on the lookout for this issue, if I manage to reproduce it I'll reopen this :)
