### ISSUE TITLE
Change/Adjust Recipes of Quark Chest Variants

### ISSUE THREAD

**Issue by TheAndrata** [NillerMedDild/Enigmatica6#2114]
**Description**
Maybe it’s just me but crafting chests is driving me nuts because of the different Quark chests. For example, making a chest from Oak logs results in an Oak Chest from Quark. This chest, for whatever reason, doesn’t seem to ore dictionary with the regular minecraft:chest and causes auto-crafting recipes to fail and JEI to report the item is missing.

However, crafting a chest from Baobab planks, for example, makes a normal chest, not a baobab chest that works with crafting (however a baobab crafting table doesn’t but that’s a separate issue itself).

**Why would you like this added/changed?**
General quality of life, really. Either all chests should be ore dictionaried to minecraft:chest or the Quark variants disabled.

**Comment by NillerMedDild** [comment]
Thanks for the report.
The Oak Chest from Quark works perfectly fine for me, I'm not sure what the issue there is. It has the correct tags, as do all other wooden chests.

The normal chest also works just fine with crafting. Which exact recipes are giving you trouble? :)

**Comment by TheAndrata** [comment]
You can see it happen here in my play through of the pack: [https://youtu.be/GB4xDVaS6gw?t=103](https://youtu.be/GB4xDVaS6gw?t=103)

This time it was with the recently added Entangled mod but it happens every so once in a while to be a nuisance but not game breaking, if you know what I mean.

**Comment by Darkere** [comment]
As we do not have the entagled mod in the pack we cannot adjust their recipes to accept all types of chest.

That said there should be a recipe to craft a Quark oak chest into a vanilla chest.

**Comment by TemperedFool** [comment]
Entangled was added in 0.4.11 iirc.

**Comment by Darkere** [comment]
oh. Well then we got stuff to do I guess :D

**Comment by NillerMedDild** [comment]
Submitted a PR to fix it in the mod and fixed it for E6 👍
