### ISSUE TITLE
[0.4.10] Apotheosis Towers

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#2115]
**Description**
Reduction in the spawn generation of the Apotheosis Tower. I do not know if they're added by Apotheosis itself or another mod, but they're the towers with apotheosis tomes and a trapped chest at the top.

**Why would you like this added/changed?**
They seem a bit too common. I can see two from my base and have marked at least seven in a 500 block radius from my base.

![2021-05-06_12 49 43](https://user-images.githubusercontent.com/41839144/117335854-99333080-ae69-11eb-9b86-03b9bdba91a3.png)

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/Shadows-of-Fire/Apotheosis/issues/366

**Comment by Shadows-of-Fire** [comment]
Fair warning fixing that issue the way TF wants it requires rewriting the structure, probably best to just reduce the rate in the apo config for now

**Comment by NillerMedDild** [comment]
I don't think the config has any effect in TF, that's sorta the issue 😄

**Comment by Shadows-of-Fire** [comment]
Really?  That's weird - its part of the feature declaration, I was assuming the default level was just too high for TF since the amount of flat land is higher.

The spawn requirements for these things is just a flat 9x9 area, which is uncommon in vanilla, but if its on another level I guess there's no workaround

**Comment by NillerMedDild** [comment]
I'll try amping it up a ton and see if it changes anything :) Does /reload work with the `deadly.cfg` config?

**Comment by Shadows-of-Fire** [comment]
Not that specific line, as its used at registration time

Apo configs are selectively reloadable, but I dont really communicate what can/can't be
