### ISSUE TITLE
[0.4.10] Compact Machines Quest and Construction

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#2116]
**Modpack version**
0.4.10

**Describe the bug**
The "Compact Machine (Tiny)" quest lists a whole host of unnecessary materials in order to make said Compact Machine (Tiny). It even notes to use the Field Projectors like normal, but they are not actually listed as having any use in JEI.

Currently all Compact Machines are just 8 Compact Machine Walls around a different block for the various sizes inside a crafting table.

I'm guessing the material requirements is for a more expert focused recipe and the field projectors being useless is not intended.

**Comment by NillerMedDild** [comment]
We had to disable our cool recipes because of a bug, and I forgot to update the quests accordingly :)
