### ISSUE TITLE
[0.4.10] undergarden CTD

### ISSUE THREAD

**Issue by Toonlink264** [NillerMedDild/Enigmatica6#2117]
**Modpack version**
0.4.10

**Describe the bug**
i'm not sure but i was trying to explore undergarden and it just crashed

**Logs**
[crash-2021-05-07_05.57.13-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6437518/crash-2021-05-07_05.57.13-client.txt)

**Screenshots**

**Comment by MuteTiefling** [comment]
Looks like you've added mods to the pack. We can't really support that.

`Entity Type: pokecube:egg (pokecube.core.items.pokemobeggs.EntityPokemobEgg)
	Entity ID: 56775
	Entity Name: Pokémob Egg
	Entity's Exact location: 86.50, 23.54, -18.50
	Entity's Block location: World: (86,23,-19), Chunk: (at 6,1,13 in 5,-2; contains blocks 80,0,-32 to 95,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.10, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null`
