### ISSUE TITLE
0.4.10 Null Pointer Exception from Message In A Bottle

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#2118]
**Modpack version**

0.4.10

**Describe the bug**

"Null Pointer Exception: Aquaculture.MessageInABottle (String) cannot be Null." in chat. The logs don't contain the stack trace, so I'm guessing that Message In A Bottle's code catches exceptions and uses their message string as the bottle's message.

**Logs**

> .....
> [19:59:21] [Render thread/INFO]: [CHAT] Can't teleport yet! Cooldown: 1 minute and 58 seconds
> [20:01:54] [Render thread/INFO]: [CHAT] Null Pointer Exception: Aquaculture.MessageInABottle (String) cannot be null.
> [20:02:09] [Server thread/INFO]: Saving and pausing game...
> ...

**Screenshots**

![image](https://user-images.githubusercontent.com/1171633/117387374-08c71100-aea6-11eb-8f6d-f1f46d3946a7.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Its intentional apparently o_o
