### ISSUE TITLE
[0.4.10] Remove fluid to item recipe: Driftwood > Driftwood 

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#2119]
**Modpack version**
0.4.10

**Describe the bug**
Blahramewe — Today at 4:26 PM
Is it possible to remove driftwood logs from things to wash into driftwood?  As it is now, dropping any logs into water turns them into driftwood that keeps bouncing on the surface of the water and can't be collected.

Looks like a pretty annoying bug, and potentially dangerous to server TPS. Blahramewe didn't have a github acc so I posted it instead

**Screenshots**
![2021-05-07_16 45 03](https://user-images.githubusercontent.com/13237198/117415874-c2c88680-af53-11eb-8eb8-1c76598ec84c.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
