### ISSUE TITLE
[0.4.10] Industrial Foregoing machines don't work if placed in claimed chunks.

### ISSUE THREAD

**Issue by TarantelFaser** [NillerMedDild/Enigmatica6#2120]
**Modpack version**
0.4.10
**Describe the bug**
When claiming chunks (with FTBUtilities), Industrial Foregoing machines placed in them don't work (i.e. the block placer can't place blocks, ...). Unclaiming the land fixes the issue and the machines work again. 
This is especially frustrating on multiplayer servers, where it's important to protect your land.

**Comment by MuteTiefling** [comment]
You need to ally them. You'll find the option in your map.
