### ISSUE TITLE
0.4.10 - 'Crafting' lens of ender works but then it 'poofs'

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica6#2121]
0.4.10

**Describe the bug**
Take a photoelectric pane, right click on enderman with it, you'll get the quest completion but the lens will not appear in inventory. 
(Was done on a server)

**Comment by NillerMedDild** [comment]
Are you in a claimed chunk or something? I can't reproduce this, but it has been reported before #438

**Comment by Trostmm** [comment]
Hmm, no the first time I tried was in the End, the second time was near my base(so that one might have been claimed).

**Comment by Trostmm** [comment]
Yeah, I relogged and its working perfectly now, so who the *bleep* knows.

**Comment by choekstr** [comment]
FWIW, I just happen to me on v0.5.8 both times I tried, but a restart fixed it.  Not sure why either, some weirdness for sure.

This was far-ish from my base (maybe 30 chunks away) and not protected, in the overworld.
