### ISSUE TITLE
Disabled blocks in RFTools dimensions

### ISSUE THREAD

**Issue by AngelsSaber** [NillerMedDild/Enigmatica6#2122]
**Modpack version**
1.16.5
**Describe the bug**
Using RFTools Dimensions it is possible to create dimensions full of sugar cane blocks and ruby ore, which i am told is supposed to be disabled in the mod pack

**Comment by mouseas** [comment]
As an aside, is there a reason rubies are disabled? Could they be made available as a mainly-cosmetic option?

**Comment by NillerMedDild** [comment]
They're disabled because they're very close to useless, and we don't want to add an entire ore for only 2 purposes :)
