### ISSUE TITLE
Nature's Compass quest bug

### ISSUE THREAD

**Issue by GregariousJB** [NillerMedDild/Enigmatica6#2125]
**Modpack version**
0.4.10 (I think? How do I tell?)

**Describe the bug**
In quests > Adventure > Nature's Compass quest, clicking on the recipe opens JEI to a different item. I think to a random tree sapling.

![image](https://i.imgur.com/MHE4WBF.png)

**Comment by MuteTiefling** [comment]
Bit of a known issue. For whatever reason it ends up clicking twice, once on the compass, once on the sapling in the  compass recipe.

Can happen with any item in the quests.

Just hit backspace to return to the previous recipe.

**Comment by GregariousJB** [comment]
Okie dokie. Same problem with the Tools > Mining Helmet and Portable Stonecutter. Only clicked on a handful of quests so far, so I suspect it's all over the place. _FTB Quests_ bug perhaps?

**Comment by GregariousJB** [comment]
Think I found the bug reported here: https://github.com/FTBTeam/FTB-Quests/issues/517

Interesting, so holding down the mouse button instead of clicking quickly will also "fix" this issue. So it could be a JEI problem.

**Comment by Seceroth** [comment]
Should be fixed in https://github.com/mezz/JustEnoughItems/commit/5097e3df0cc15dbc9d45195cf2bf3fde44c2a0ee
But E6 v0.4.10 is on one JEI version before the fix.

**Comment by GregariousJB** [comment]
Cool, thanks for the info, @Seceroth. Closing this.
