### ISSUE TITLE
End city for "Better End" Datapack

### ISSUE THREAD

**Issue by Scapulaunit12** [NillerMedDild/Enigmatica6#2127]
Would be really cool if the modpack included this datapack: https://www.planetminecraft.com/data-pack/end-city-for-better-end-forge-port/.

It replaces end cities with new and improved ones!

![image](https://user-images.githubusercontent.com/56084328/117584392-ab67d580-b0da-11eb-819a-be5335b0ae0b.png)
![image](https://user-images.githubusercontent.com/56084328/117584395-b3277a00-b0da-11eb-8106-e2ac03fdea86.png)

**Comment by NillerMedDild** [comment]
We do have that datapack in the modpack.
