### ISSUE TITLE
Darker Depths

### ISSUE THREAD

**Issue by Scapulaunit12** [NillerMedDild/Enigmatica6#2129]
https://www.curseforge.com/minecraft/mc-mods/darker-depths

Darker depths is a cave expansion mod that includes well sought-after features for the Minecraft caves, along with a lot of our own ideas.  It also adds two new cave biomes, the Molten Cavern, which is meant to be a molten and ash-ridden place, almost like a volcano. The second, the Sandy Catacombs, which is an arid and dead underground desert.

I would love to see this mod added as it adds more sights to see underground other than improved cave gen. This mod is also compatible with yungs better caves so it would be a really cool addition. 

![image](https://user-images.githubusercontent.com/56084328/117584875-5da09c80-b0dd-11eb-8be2-8efd20af46cf.png)

**Comment by NillerMedDild** [comment]
I don't want to stress worldgen further, no thank you.
