### ISSUE TITLE
Mekanism Armored Jetpack Enchantability 

### ISSUE THREAD

**Issue by NoMoreStars** [NillerMedDild/Enigmatica6#213]
**Modpack version**
0.2.14

**Issue**
According to JEI, the Armored Jetpack from Mekanism is supposed to be compatible with most chest plate enchantments. However it upon trying to enchant it in enchanting table, anvil, robit, etc. the Armored Jetpack seems to be un-enchantable. If it is intended behavior for the Jetpack to be un-enchantable then the JEI entry for the Armored Jetpack is incorrect.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I've asked on the Mekanism discord, and JEI is incorrect, it could be a bug on their end. For now I'll add a description letting players know it is not enchantable :)
