### ISSUE TITLE
Freeze on start-up when trying to use Optifine

### ISSUE THREAD

**Issue by SvenssonGD** [NillerMedDild/Enigmatica6#2133]
Enigmatica 6 v0.4.8

Hi, I'm having an issue when trying to install and start Enigmatica 6 with optifine. I have tried installing optifabric, update java and different versions of optifine but I can't make it work and I can't find any answers online. It starts loading in normally but freezes when it is just about to be done.  

Didn't get a crash report. It gave me "Exit Code 0" but no file in the crash-report folder.

Hope anyone can help me play with optifine. Been trying for way to long. 

Have a great day

**Comment by NillerMedDild** [comment]
You need [OptiForge](https://www.curseforge.com/minecraft/mc-mods/optiforge) to use OptiFine in Forge modpacks :)
