### ISSUE TITLE
Grimwood tree spawns as ghost block

### ISSUE THREAD

**Issue by Cireric120** [NillerMedDild/Enigmatica6#2135]
Version: Enigmatica 6 0.4.10
Host: Bisect Hosting

On my server, when one places a grimwood sapling and applies bone meal, the tree becomes a set of ghost blocks for everyone in the area. This doesn't happen in singleplayer but happens consistently in multiplayer. This does not happen with other trees. Just ones from Atmospheric.

**Comment by Cireric120** [comment]
Closing as it is not marked as a bug.

**Comment by NillerMedDild** [comment]
Very considerate of you :D We don't mind putting the label there though, so no worries if it happens in the future.
