### ISSUE TITLE
Can drown while in spectator

### ISSUE THREAD

**Issue by corhean** [NillerMedDild/Enigmatica6#214]
go into spectator, chill under water.  I can attach a video if strictly necessary.  2.14 client/server versions.

**Comment by NillerMedDild** [comment]
Can you down more than once in spectator?

**Comment by corhean** [comment]
I can't reproduce it this morning, which means its probably some client/server sync issue with lag.  I'll see if I can try to replicate it later if I notice similar lag (we were in the multiples of thousands of for ping when this occurred) but i'm not sure this is worth leaving open right now.

**Comment by NillerMedDild** [comment]
I'll leave it open for the time being, wanna see if I can reproduce it :)

**Comment by jinkhya** [comment]
You also get attacked and can die from mobs or drowning or burning in lava in creative. The way to reproduce the issue for creative mode as I couldn't reproduce it for spectator but I'm guessing it's the same issue. (this method is singleplayer) :
- go in creative
- exit the world
- re open the world 
The zombies I left next to me started attacking when I was in creative. Also tried stepping in lava on relog and I died. Note that after dying or if you swap back to survival then creative, you're no longer vulnerable in creative. It's like re-logging doesn't register properly in which mode you were on.

**Comment by corhean** [comment]
honestly it might have been the relog that I was missing in the testing I did.  I'll try again after work today.  I know I did relog a number of times in an attempt to garner a fresh ping.

**Comment by NillerMedDild** [comment]
Nice work, thanks! Now the question remains, which mod is doing this... My first guess would be Ma' Essentials changing something with gamemode.

**Comment by jinkhya** [comment]
It is indeed Ma essentials. :)
https://streamable.com/juthog

**Comment by NillerMedDild** [comment]
Thanks for the video, really gets the point across :D 
will relay to Ma' Essentials.
