### ISSUE TITLE
Atum 2

### ISSUE THREAD

**Issue by Scapulaunit12** [NillerMedDild/Enigmatica6#2140]
https://www.curseforge.com/minecraft/mc-mods/atum

Atum 2 is a brand new desert dimension filled with loot, bosses, and many structures.

Atum 2 is a well-known dimension mod for 1.15/1.12 and it just ported to 1.16. Seeing as this mod pack only has one dimension being the Undergarden it would be cool to have another one.

![image](https://user-images.githubusercontent.com/56084328/117882104-fe2ac400-b277-11eb-9263-6a708bea9f8a.png)
![image](https://user-images.githubusercontent.com/56084328/117882134-0682ff00-b278-11eb-974d-db1229dcb3ce.png)

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by NillerMedDild** [comment]
I had a look and liked what I saw, this will most likely be added in 0.5.0 in 4-5 weeks time :)

**Comment by MuteTiefling** [comment]
Will have a look through here for integrations. 

Off the top of my head, plants/trees need to be added to the various registries
new Excavator nodes could be made for the special ores and other nodes extended to spawn here as well.

**Comment by NillerMedDild** [comment]
At the moment I'd say I'm 85% sure I like this mod enough to add it :)
