### ISSUE TITLE
[0.4.10] Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1

### ISSUE THREAD

**Issue by nsowers11** [NillerMedDild/Enigmatica6#2142]
Enigmatica 6 - 0.4.10

Just updated the server from 0.4.8 and keep getting this error: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1, when trying to log in to the server. I attached some screenshots of the client side error and then the error the server console is giving. I have had two people on my server test this as well and they get the same error.

![Capture](https://user-images.githubusercontent.com/22422819/117904202-86b85d00-b296-11eb-9f1f-12ec8a2b5ab6.PNG)
![Capture1](https://user-images.githubusercontent.com/22422819/117904251-9fc10e00-b296-11eb-9740-daf54ac44870.PNG)

I also noticed that as an admin, my user gets a different error on the server console:
![image](https://user-images.githubusercontent.com/22422819/117915060-203d3a00-b2aa-11eb-8c71-cb529bba236b.png)

**Comment by Darkere** [comment]
This error likely means you have leftover files from the previous version in your kubejs folder.

@NillerMedDild did we not include an empty file that overrides this? ... kind of weird its the 3rd person with this i see

**Comment by NillerMedDild** [comment]
We did yeah, its completely commented out. I suspect the issue is forgetting to replace the kubejs folder on the server.
