### ISSUE TITLE
Some Tetra Levels are Unobtainable

### ISSUE THREAD

**Issue by Hotgandalf2** [NillerMedDild/Enigmatica6#2143]
**Enigmatica 6 1.16.5 **

In the tetra modpack there is a max hammer tier of 7, whilst exploring the materials on the tetra Akashi tome I've noticed that Gaia ingots and alfsteel ingots require tier 9 to infuse into any piece of a tool when I tried putting them together on the bench and, those tiers don't exist. I even checked the material hammer tiers in the tome saying a tier 6 is only needed for Gaia and alfsteel which is contradictory. Please let me know if this is a bug in the mod pack.

**Comment by NillerMedDild** [comment]
Did you perhaps look at bow parts only?

**Comment by BlueAgent** [comment]
IIRC you need to find and upgrade a Forge Hammer (not a handheld tool but the in-world multi block or structure) to reach higher tiers. You can eventually move them with a silk touch hammer with high enough tier.

**Comment by NillerMedDild** [comment]
I alerted the dev of this ages ago, it's caused by bows adding to the tier specified :/
Which version are you actually using? Cause Alfsteel is set to require hammer level 4 in the current config.

**Comment by BlueAgent** [comment]
Enigmatica 6 v 0.4.10
![image](https://user-images.githubusercontent.com/630920/118082195-50dabc00-b3ef-11eb-9c60-0f6a4db5bc74.png)

Although using GDLauncher so it may not have updated properly.

**Comment by Hotgandalf2** [comment]
@NillerMedDild  Im currrently on version 36.1.0 As Im playing on a modded server  with some friends I did some digging and found someone who needed to changes values in the files to fix this solution but since this is on a modded server Im not sure how to do it. I could ask the owner since hes well versed in coding so yea any help is appreciated,

**Comment by Hotgandalf2** [comment]
@BlueAgent Tiers 8 and 9 or not achievable in my mod pack version I'm 100 sure its weird tier coding mix up.

**Comment by NillerMedDild** [comment]
No need to ping, we're subscribed to the issue :)
I don't know where the Alfsteel material is coming from, the one Enigmatica adds is Tool level 4 :s

**Comment by Hotgandalf2** [comment]
Its from botania

**Comment by NillerMedDild** [comment]
Botania does not add Alfsteel as a Tetra material, it's coming from somewhere else. Unless they're adding it some other way than through datapack.

**Comment by BlueAgent** [comment]
> I don't know where the Alfsteel material is coming from, the one Enigmatica adds is Tool level 4 :s

I think the `toolLevel` is the harvest level of the material.

Changing Alfsteel's `requiredTools: { hammer: 6 }` to `requiredTools: { hammer: 4 }` fixes the bow parts required hammer level for me (unfortunately it also makes it easier to make the other parts...).

![Fixed Alfsteel Bow Stave](https://user-images.githubusercontent.com/630920/118390311-ea5cd480-b660-11eb-9aa8-f4c489006f5d.png)


Now that I think about it, materials added in the scripts with `requiredTools: { hammer: X }` where `X` is greater then `4` (`terrasteel, gaia, alfsteel, iesnium`) won't be able to be turned into bow staves. If only you could configure the requirements for each part, or perhaps remove the hammer requirement increases for the parts...

![Gaia Bow Stave](https://user-images.githubusercontent.com/630920/118390288-d0bb8d00-b660-11eb-8c3d-2a95c0d37aa1.png)

**Comment by NillerMedDild** [comment]
Thanks for the thorough investigation, excellent work 👍 I think we'll be going with adding additional Hammer possibilities, as it'll change Tetra the least and be the least amount of work.
