### ISSUE TITLE
Render Problem with Quark Blocks

### ISSUE THREAD

**Issue by DraGonFiirE** [NillerMedDild/Enigmatica6#2146]
**Modpack version**
1.16.5 0.4.10
**Describe the bug**
Using the create blockzapper and 3x3 replacing an area with any block from quark replaces it but it wont render for the client unless you left or right click the replaced blocks. Same with using a mechanical bearing, for example after rotating when it tries to place a quark block it turns invisible
I dont think its a problem thats exclusive to quark, because I added an extra mod called "chiseled" and it has these problems aswell
It only started happening after updating from 0.4.8 to 0.4.10
The bug only happens online on a server though, offline everything works fine

**Comment by Cireric120** [comment]
Hey @DraGonFiirE! I am running into a similar problem with saplings growing into invisible trees. If you remove the mod XNet (and XNet gases) do you still have this problem?

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by DraGonFiirE** [comment]
@Cireric120 removing Xnet and Xnet gases didnt solve this issue

**Comment by OneLemonyBoi** [comment]
most likely a syncing issue, probably on create's end, they should force a block update.

**Comment by DarkAngel22579** [comment]
Happens in https://github.com/NillerMedDild/Enigmatica6/issues/1890 with building gadgets too, so its probably not just something Create's doing.

**Comment by DraGonFiirE** [comment]
Youre right, building gadgets causes this too so it must be some kind of universal render sync issue, but since many mods have that problem, Im taking a guess at forge 
I tried reverting back to the quark and create versions I had in 0.4.8 and it didnt help

**Comment by OneLemonyBoi** [comment]
Well it seems like both mods are telling server to rerender, so that’s not the issue

**Comment by OneLemonyBoi** [comment]
Can someone try reloading chunks with f3+a?

**Comment by DraGonFiirE** [comment]
> 
> 
> Can someone try reloading chunks with f3+a?

It has no effect

**Comment by DraGonFiirE** [comment]
I've found a workaround when dealing with these ghost blocks
https://www.curseforge.com/minecraft/mc-mods/antighost
Just press G while running around a few times instead of having to click every block or relogging everytime

**Comment by landretk** [comment]
> I've found a workaround when dealing with these ghost blocks
> https://www.curseforge.com/minecraft/mc-mods/antighost
> Just press G while running around a few times instead of having to click every block or relogging everytime
> 

Oh that's handy, I've always just left and rejoined when I get desync'd with the server

It really can happen with anything that modifies multiple blocks in a server tick. Hammers, excavators, mining gadget, etc. It's been that way since at least 1.12

**Comment by DraGonFiirE** [comment]
I never had that issue when breaking blocks though, it only seems to happen when using tools that can place/replace multiple blocks like you said.
But even then only a few mods have that problem, the ones I've found so far are: Quark, Chiseled and Storage Drawers
Unfortunately Performant doesnt work with Resourceful Bees :(

**Comment by NillerMedDild** [comment]
Performant is indeed incompatible with E6 :( Bees don't really work with it.

**Comment by TheMushroomMan47** [comment]
I have done some just minor testing on a private server and it seems that create contraptions will make most of the moved blocks ghost blocks if any blocks attached are from either Quark or Chisel if there aren't any of these blocks the contraption wont have any ghost blocks. This is also the same with the building gadgets.

**Comment by Hootling** [comment]
A bit of further info on this.  

When using Construction Wand I get ghost blocks from both Quark and Tinker's Construct.  Only one of the blocks placed via the wand shows up until I leave the chunk and come back.

Quark also has crystal blocks that grow, Corundum crystals.  If you place one block up to 4 more will grow above it.   The blocks that grow are invisible until you leave the chunk and come back.

**Comment by MuteTiefling** [comment]
> The blocks that grow are invisible until you leave the chunk and come back.
Are you sure you haven't added anything here? I've done quite a bit of testing with these crystals and never had issues with them displaying.

**Comment by Hootling** [comment]
I have not added anything. (I disabled optifine for testing).

Both the issue with the construction wand, and growing corundum crystals do not happen in single player.  Only multi player.

It would be very easy to miss the issue with corundum crystals.  Since you don't know they are there unless you happen to bump into an un-rendered block.  I am farming them for a project, so I've got a room full of them spaced 3 blocks apart.  I was doing some rearranging when I started bumping into ghost blocks.

Hope that is helpful.  I am on version 0.5.4

**Comment by Cireric120** [comment]
This is very exciting! What was the solution?

**Comment by NillerMedDild** [comment]
This: https://github.com/NillerMedDild/Enigmatica6/issues/2862#issuecomment-893736572

**Comment by Cireric120** [comment]
Yay! This was one of the main things keeping me from playing on my own server. Thank you all for your hard work!
