### ISSUE TITLE
AE2/JEI/FTB - Recipe causes payload error

### ISSUE THREAD

**Issue by corhean** [NillerMedDild/Enigmatica6#215]
open functional AE2 system, change search to JEI syncronized, search for chest.  Attempt to use the "+" button to move the chest (with logs) into inventory. you will recieve "Internal Exception: io.netty.handler.coded.decoderException: java.ioException: Payload may not be larger than 32747 bytes.

.......possible case of too much NBT? Note, this does not happen for the chest with planks recipe. I see related enteries in AE2 .... https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3820

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I cannot reproduce this issue, do you happen to remember which logs you had in the system, or how many different kinds?

**Comment by corhean** [comment]
Let me see if I can still reproduce it in our current environment and also from a fresh single player.  We were using fir, birch, and dark oak, primarily at the time.

**Comment by corhean** [comment]
so I just tested again on my camera account which had never signed into the server before and received the same error.  at the time the recipe in JEI at the time that I hit the "+" was on umbran wood.

from the console:
[10-Sep-2020 21:00:41] [INFO] CorheanCam lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 32767 bytes

[10-Sep-2020 21:00:41] [INFO] CorheanCam left the game

**Comment by NillerMedDild** [comment]
Aha, might be server only then, thanks :)
