### ISSUE TITLE
Shipwrecks spawn without a treasure map, instead spawn with vanilla empty map item. [0.4.8]

### ISSUE THREAD

**Issue by Zeure** [NillerMedDild/Enigmatica6#2151]
**Modpack version**
0.4.8

**Describe the bug**
Shipwrecks spawn in the ocean with 1-3 of the "loot" treasure chests in them as expected, however I have yet to find a buried treasure map in any of them.  Instead I seem to find a lot of the vanilla empty map items that you can right click to turn into a map of the area you're in.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Zeure** [comment]
So, I did some more research in my server's world to see if I was truly unlucky, I have now combed through 31 shipwrecks, all of them had empty maps.

**Comment by NillerMedDild** [comment]
That is some truly awful luck. However, it doesn't seem to happen in new worlds, so I guess it has been fixed by a mod update between 0.4.8 and now :)

**Comment by Zeure** [comment]
Also, I guess it was just that ocean.  I have now traveled a few hundred blocks away from my base in a new direction and have managed to find a buried treasure map that led me to a heart.  That was some seriously weird RNG.  Fully closed issue, I guess.
