### ISSUE TITLE
Ametrine Gems Located

### ISSUE THREAD

**Issue by NeedSomeWizardHelp** [NillerMedDild/Enigmatica6#2152]
**Modpack version**
4.10
**Describe the bug**
Found them in The End at the biome "Shattered Viscal Islands" inside of "Ametrine Ore" having an "Etherstone" block aesthetic. Once found I was told to send this to here as a bug report. 
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![image](https://user-images.githubusercontent.com/70040745/118070106-509cdb00-b373-11eb-88b1-c6d51931d15e.png)

**Comment by NillerMedDild** [comment]
Thanks for letting us know, but someone beat you to it 😄 #2097
