### ISSUE TITLE
4.10 doesn't include the building gadgets patterns directory structure

### ISSUE THREAD

**Issue by DoomSquirter** [NillerMedDild/Enigmatica6#2156]
**Modpack version**
4.10

**Describe the bug**
downloaded 4.10 using mmc and I didn't have the above mentioned directory in my install

**Logs**
n/a

**Screenshots**
n/a

**Comment by TemperedFool** [comment]
Dupe of #2113 - this is addressed in dev and will be fixed in the next update ^_^

**Comment by DoomSquirter** [comment]
sorry, I should have searched first.  I usually do that actually.  -1 to gryffindor

**Comment by TemperedFool** [comment]
Nah, it's not a big deal - easy to answer a duplicate issue, hard to deal with one that's unreported!
