### ISSUE TITLE
FastSuite

### ISSUE THREAD

**Issue by pm065** [NillerMedDild/Enigmatica6#2160]
https://www.curseforge.com/minecraft/mc-mods/fastsuite

Optimization mod that claims to act like FastWorkbench/Furnace, except it optimises JSON recipes in general. According to the description, it does not make those mods entirely useless, only less effective.

**Comment by NillerMedDild** [comment]
I've tried it and saw no improvement tbh, removed it after getting a weird non-related crash. Will probably try again :)

**Comment by pm065** [comment]
Weird how everyone claims that these optimisation mods are so brilliant and yet when some people (including me) try them they see no difference...

**Comment by yagoplx** [comment]
> Weird how everyone claims that these optimisation mods are so brilliant and yet when some people (including me) try them they see no difference...

This mod doesn't improve FPS, it just makes repeated crafting take slightly less time to show up on your GUI so you can click the result item. You will only see this making a tickrate difference on servers with players and machines doing lots of crafting simultaneously, otherwise you might only ever see slightly lower "latency" on repeated crafting.

**Comment by TemperedFool** [comment]
It also causes easy-to-reproduce CTD's with at least one of the mods we use; we tested it and removed it because of them.

**Comment by yagoplx** [comment]
Then don't include it, i'm just explaining what this does.

You already have FastWorkbench and FastFurnace, which do almost the same, you aren't missing out on much.

**Comment by DarkAngel22579** [comment]
I think the confusion here is that you're commenting on a closed issue, and that implies that you want it reopened/added to E6.
