### ISSUE TITLE
[0.4.10] Skyseeker's Pickaxe Quest Unattainable

### ISSUE THREAD

**Issue by Taelsolos** [NillerMedDild/Enigmatica6#2163]
Enigmatica 6 0.4.10

**Description**
Making the Skyseekeer's Pickaxe does not complete the "Skyseeker's Pickaxe" quest

**Logs**
N/A

**Screenshots**
![Skyseeker issue](https://user-images.githubusercontent.com/84159015/118199266-4d0f5f80-b418-11eb-830a-b2a698df958c.png)

**Comment by Taelsolos** [comment]
This also occurs with "Skyseeker's Mantle" Quest. All parts of the quest were made, but it's not completing:
![image](https://user-images.githubusercontent.com/84159015/118199556-fd7d6380-b418-11eb-82ae-8e931aeef5b1.png)
![image](https://user-images.githubusercontent.com/84159015/118199595-053d0800-b419-11eb-81a1-eb34f69e5ab8.png)

**Comment by Taelsolos** [comment]
Found the little chevron that showed a pre-req, but there's nothing on the main page indicative of there being one. Looks to be a quest that's able to be completed on its own. Perhaps something like this would help:

![image](https://user-images.githubusercontent.com/84159015/118200087-015db580-b41a-11eb-9d90-7b3b92fbb450.png)

I'll close the bug, sorry for wasting time here.

**Comment by LatvianModder** [comment]
This will be eventually "fixed" when mirrored cross-chapter quests will be added
