### ISSUE TITLE
Mini Utilities

### ISSUE THREAD

**Issue by OneLemonyBoi** [NillerMedDild/Enigmatica6#2164]
[https://www.curseforge.com/minecraft/mc-mods/miniutilities](https://www.curseforge.com/minecraft/mc-mods/miniutilities
)

Mini Utilities is a mod inspired by XU1 and XU2 which takes features from each of them, while adding its own features. https://i.imgur.com/kquNOoy.png

Information about each block and item in this mod:
 

Spoiler (click to hide)
Angel Block - A Block that can be placed without needing any support blocks
Cursed Earth - Spawns Hostile Mobs
Blessed Earth - Spawns Passive Mobs
Blursed Earth - Spawns All Mobs
Ender Ore - Naturally generating ore that drops Ender Dust, and is affected by fortune
Ender Pearl Block - Storage block for Ender Pearls, and grows Ender Lilies faster
Lapis Caelestis - Blocks that do not require light in order to look bright, similar to AntiBlocks, inspired by Lapis Caelestis from XU1. There are 16 types, corresponding to the 16 colors of Minecraft
Drums - 5 types of Drums:
    Stone Drum - Holds 16 Buckets
    Iron Drum - Holds 256 Buckets
    Reinforced Metal Drum - Holds 4096 Buckets
    Netherite Reinforced Drum - Holds 65536 Buckets
    Unstable Drum - Holds 2,147,483.647 Buckets
Spikes - 5 types of spikes:
    Wooden Spikes - 1 Damage Point per 10 ticks, does not kill
    Iron Spikes - 2 Damage Points per 10 ticks
    Gold Spikes - 4 Damage Points per 10 ticks, mobs drop EXP
    Diamond Spikes - 8 Damage Points per 10 ticks, mobs drop Player Kill items. Example: Pigmen drop Gold Ingots
    Netherite Spikes - 16 Damage Points per 10 ticks, mobs drop Player Kill items and EXP
Ender Dust - Drops from Ender Ore and can be crafted into Ender Pearls 4:1
Ender Lily Seeds - Obtained by breaking Ender Lilies in the End, or crafting it with 8 ender pearls and 1 seed. Grows on Dirt, End Stone, and Ender Pearl Block. When harvested, drops Ender Pearls
Flame Lily Seeds - Obtained by breaking Flame Lilies in hot biomes with a temperature over 2.0. A couple examples are desert biomes and the Nether. Grows on Sand, Netherrack, and Magma Blocks. When harvested, drops Flame Lilies
Flame Lily - Obtained by harvesting Flame Lily plants. It can be used in place of Blaze Rods.
Angel Rings and Derivatives - Allows player to fly in Survival Mode, and the different types allow the player to have their own wings rendered on the back of the player
Unstable Ingot - Crafted with an Iron Ingot, a Stick, and a Diamond. There are 3 modes for the ingot, which can be set in the config:
    0: Slowness while holding
    1: After 10 seconds, slowly ramps up the damage
    2: Explodes after 10 seconds
Unstable Block - Storage Block for Unstable Ingots, but can not be crafted back into Ingots, solely for decoration.
Etheric Sword - Does the same damage as Netherite, but does 1 damage point of armor-piercing damage
Healing Axe - On hit, does 4 extra damage to undead mobs, otherwise heals for 8 damage. No matter what, player gets hit for 2 damage
Reversing Hoe - On right click, turns cobblestone into stone
Destruction Pickaxe - Mines stone-like blocks 5x faster than other blocks
Precision Shears - On shift right-click, instantly harvests all blocks that can be mined by Iron Pickaxes.
Unstable Armour - Similar to Netherite Armor
Infused Armour - Double the Protection of Netherite, 5x the Knockback Resistance, and 6x the Toughness
Opinium Cores - Crafting Ingredients
Kikoku - Allows Players to stack enchantments higher than the maximum defined by Vanilla Minecraft & Mods. VERY OP!
Mechanical Miner - Mines Blocks and can be upgraded with Speed Upgrades
Mechanical Placer - Places Blocks and can be upgraded with Speed Upgrades
Speed Upgrade - Allows you to speed up the Mechanical Miner and Placer

Quantum Quarry - Allows you to generate ores from an alternate dimension
Solar Panel Controller - Controlls the Solar/Lunar Panels
Solar Panel - Generates power when attached to a Controller. Works during the Day!
Lunar Panel - Generates power when attached to a Controller. Works during the Night!

**Comment by muqsit-0010** [comment]
Just thought to mention the server crash from the mod here...
https://github.com/OneLemonyBoi/MiniUtilities/issues/32

**Comment by OneLemonyBoi** [comment]
fixed it in dev

**Comment by NillerMedDild** [comment]
To be completely honest, I'm not really seeing any features in Mini Utilities that are missing from the modpack at the moment. It looks like a great mod, but it doesn't really fit into E6. Sorry :/
