### ISSUE TITLE
[0.4.11] Diamond Honeycomb has no Centrifuge recipe

### ISSUE THREAD

**Issue by MrBazlow** [NillerMedDild/Enigmatica6#2166]
**Modpack version**
4.11

**Describe the bug**
You can not centrifuge diamond honeycomb to get anything from it.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

![image](https://user-images.githubusercontent.com/67396813/118220671-2121c780-b474-11eb-8770-34c3b495fb7f.png)
What should be there

![image](https://user-images.githubusercontent.com/67396813/118220723-33036a80-b474-11eb-91eb-c034001b1e01.png)
What is there

**Comment by TemperedFool** [comment]
🤦‍♂️

This one's mine. Looks like I gave "mana_chunk" rather than "arcane_chunk" - was easily distracted by the shiny chunk's display name. Will push a fix to dev this morning.

@MrBazlow you can fix this pretty easily yourself if you're so inclined, and are either playing single player or have access to your server. Change "mana" to "arcane" on line 44 of the following file: config/resourcefulbees/bees/gem/Diamond.json

**Comment by Brendan-James** [comment]
I believe there is a identical problem with enderbees naming "dimensional_shard_chunk" instead of "dimensional_chunk".

**Comment by NillerMedDild** [comment]
Fixed ty :D

**Comment by MrBazlow** [comment]
> I believe there is a identical problem with enderbees naming "dimensional_shard_chunk" instead of "dimensional_chunk".

I didn't even notice that but yeah, no recipe there either. Quick glance at [Ender.json](https://github.com/NillerMedDild/Enigmatica6/blob/8f30b8701a2e8bafc5b2cc69616d5b9e22db043e/config/resourcefulbees/bees/natural/Ender.json#L40) looks like `emendatusenigmatica:dimensional_shard_chunk` should be `emendatusenigmatica:dimensional_chunk`.

**Comment by TemperedFool** [comment]
Ty, sorry about the mistakes. Was I drunk when I made those modifications or something? I'll take another pass ASAP and confirm I didn't break anything else, if no one else notices before I can...

**Comment by aqpoyo** [comment]
the end bee honeycomb also doesn't seem to work in the centrifuge

**Comment by TemperedFool** [comment]
> the end bee honeycomb also doesn't seem to work in the centrifuge

@aqpoyo Niller fixed this in the commit above. Same sort of problem, and fixed the same way. You could just download and replace the referenced file to fix it until the next release comes out.

**Comment by aqpoyo** [comment]
no problem I'll wait, I play on the e6 server now.
