### ISSUE TITLE
Clay blocks to clay balls missing recipe?

### ISSUE THREAD

**Issue by maca134** [NillerMedDild/Enigmatica6#2169]
**Description**
No recipe for clay blocks to balls in crafting table. Not sure if its intended or not as there is balls to blocks.

**Comment by Merlo17** [comment]
Pretty sure that's just how vanilla works?

**Comment by Wntermute** [comment]
You can always either place the clay blocks and break them to get clay balls... or use a Compacting Drawer if you want to pick & choose between the two forms.

**Comment by MuteTiefling** [comment]
Automation would still likely use something like the unpacking dyes, but this should be a nice QoL recipe to be able to convert them quickly in the field.
