### ISSUE TITLE
Neat healthbars disable themselves

### ISSUE THREAD

**Issue by kartoffelsaretasty** [NillerMedDild/Enigmatica6#217]
**Modpack version**
0.2.5; 0.2.8; 0.2.14

**Issue**
Healthbars of Neat seem to disable themselves - They reappear if I close Minecraft, delete the mod.jar, readd the mod.jar and restart the game. The next launch they're disabled again. The hotkey does not work.

**Logs**
[latest_client.log](https://github.com/NillerMedDild/Enigmatica6/files/5147074/latest_client.log)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MaxFirestorm** [comment]
I have to wonder if this is connected in some way to the Mining Gadget beam rendering issue that's been floating around...

I've notinced that they either both work or both *don't* work. It's never one or the other.

**Comment by NillerMedDild** [comment]
Funny enough, I can reproduce this but not the Mining Gadget issues :P
