### ISSUE TITLE
Chipped

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica6#2170]
https://www.curseforge.com/minecraft/mc-mods/chipped

Suggested earlier on discord and looks pretty interesting, but it seems super recent so it probably needs some quality testing to see if it's up to par. Has a lot of cool potential though

**Comment by NillerMedDild** [comment]
Looks cool, can't be played on Forge 36.1.x though: https://github.com/CookieCNetwork/Chipped/issues/20

**Comment by Erysch** [comment]
I just added it to the Mod Pack and it works at least in single player. Couldn't test it in MP yet but I don't think it will cause an issue tbh. :o

**Comment by Erysch** [comment]
> I just added it to the Mod Pack and it works at least in single player. Couldn't test it in MP yet but I don't think it will cause an issue tbh. :o





> I just added it to the Mod Pack and it works at least in single player. Couldn't test it in MP yet but I don't think it will cause an issue tbh. :o

But like it the link you send, it really didn't work on the server for some reason. I just tried with forge 36.1.18.

**Comment by MrBazlow** [comment]
This mod is worth a second look, they just [released 1.0.3](https://www.curseforge.com/minecraft/mc-mods/chipped/files/3312077) with support for 1.16.5 + Forge 36.1

Tested server and single player with Enigmatica 6 0.4.12 and seems to be working.

**Comment by NillerMedDild** [comment]
Love it, accepted 👍
