### ISSUE TITLE
StepUp

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2174]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/stepup

**Mod description**
"StepUp allows you to walk up one block height without jumping."

**Why would you like the mod added?**
It's a nice QoL feature and it's pretty good combined with terraforged to walk up the height mountains without smashing the space button to the ground. It's a good replacement for the weird auto-jump feature included in vanilla minecraft.

**Known mod incompatibilities?**
- Environmental (currently not included in your pack)

**Comment by NillerMedDild** [comment]
We have items that provide this effect 🙂
