### ISSUE TITLE
Carry On

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2175]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/carry-on

**Mod description**
"Carry On is a simple mod that improves game interaction by allowing players to pick up, carry, and place single block Tile Entities (such as Chests, Furnaces, Droppers, Spawners, and your favorite machines from other Tech Mods) using only their empty hands. No items (or pickaxes) required. States, meta data, inventory and NBT data are retained. It also allows you to carry around smaller mobs!" - from mod page

**Why would you like the mod added?**
It's a nice QoL mod making Minecraft feel more immersive when having the ability to move chests (e. g.) with your hands without needing to break them. Of course it is a matter of taste.
I don't know if there is already something like that in your mod pack.

**Screenshots if applicable.**
![2017-08-12_13](https://user-images.githubusercontent.com/81813584/118362614-718e4780-b590-11eb-8d29-7dfdc18e405a.png)
- stolen from the mod page

**Comment by NillerMedDild** [comment]
Carry On is a bit of a nightmare to maintain, because its incompatible with a ton of things. I recommend using a cardboard box from Mekanism instead :)
