### ISSUE TITLE
Presence Footsteps

### ISSUE THREAD

**Issue by pm065** [NillerMedDild/Enigmatica6#2177]
https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge

Adds dynamic footstep sounds to the game.

They sound so much better than the vanilla sounds and I sometimes find myself subconsciously running about on the grass listening to it.

This description is from the Fabric version's page. The Forge version is an unofficial port, but it's 1:1.

```
Expect to see a more rich and immersive Minecraft world, one where Presence Footsteps adds new and more dynamic sounds for every block the player walks on. Every block has its own material assigned to it, and can make their own, customized sounds to better match what they're made of.

Wooden chests are creaky and old, stone is dusty and rough. Piston heads sound like wood, whilst the bodies are stone, and even cake sounds like you might destroy if you step in the frosting! Tall grass and bristles make a dry, rustling sound as you step through them, and magma sounds like it's literally cooking your souls!

Not only that, but the latest version includes step sounds for certain non-block entities:

Shulkers make the same creaky box noises and Shulker boxes, boats sound like wood, and armour stands creak and produce a stone stepping sound as you walk on their stone slab base.
```

**Comment by Erysch** [comment]
You can use Dynamic Surroundings instead, it adds the same footsteps but also nice ambient sounds and more

**Comment by pm065** [comment]
does it? huh, okay. I'll see if their ones sound nicer.

**Comment by pm065** [comment]
you're right (:

**Comment by Erysch** [comment]
Will you post the dynamic surroundings suggestion now? (:

**Comment by NillerMedDild** [comment]
I'd rather not add Presence Footsteps or Dynamic Surroundings tbh.

**Comment by Erysch** [comment]
> I'd rather not add Presence Footsteps or Dynamic Surroundings tbh.

Is there a reason? It adds great ambient sounds which let the world feel more alive, which is awesome. But if you don't want to it's okay. It's a client side only mod and ppl can add it on their own if they want to. :)

**Comment by NillerMedDild** [comment]
Because it's a clientside only mod and people can add it if they want to 😄 We had Ambient Sounds up until 0.4.10~ and I grew a bit tired of the added sounds.
