### ISSUE TITLE
Feral Lamps

### ISSUE THREAD

**Issue by cc3768** [NillerMedDild/Enigmatica6#218]
**Modpack version**
2.14

**Issue**
Placing 6 near each other causes a server to lock up
With no crash or logs just a full halt on the server end

**Logs**
https://drive.google.com/drive/folders/102ZLM8dtvT0oT8D56B6FNi9ADWqe1YXI?usp=sharing

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I was not able to reproduce this issue.
