### ISSUE TITLE
Compacting drawers and Crusher

### ISSUE THREAD

**Issue by Kinniku713** [NillerMedDild/Enigmatica6#2183]
The Mekanism crusher will not pull from a compacting drawer (melon slices). A pipes system with module could

**Comment by RobuxShooters** [comment]
Most Mekanism machines do not auto-pull from adjacent inventories. This means that other machines or devices are required to insert items into Mekanism machines.

**Comment by Kinniku713** [comment]
Sorry, I used a transport tube from Mekanism...as seen in many videos.

**Comment by RobuxShooters** [comment]
If you used the logistical transporters, did you configure the pipes to extract from the compacting drawers?

**Comment by Kinniku713** [comment]
hello, I used the tool but it didn't have any effect.  Reloaded the pack
and it's working now. The transporters actually bulge and say pull....

Thank you and it's been really fun playing the pack with my daughter.

Sam
