### ISSUE TITLE
Acquired a disabled item

### ISSUE THREAD

**Issue by DrDiamond21** [NillerMedDild/Enigmatica6#2184]
**Modpack version**
0.4.8
**Describe the bug**
Turned in a bounty to a Bountiful bounty board and the reward was a Gold Fillet Knife from the Aquaculture 2 mod, which in the info screen said it was a disabled item and directed me to this page
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![eng6 bugreport](https://user-images.githubusercontent.com/84263384/118388364-dec5cb00-b5d8-11eb-8716-37cad5ed6909.png)

**Comment by pm065** [comment]
Update the pack, see #2040
