### ISSUE TITLE
Making a Team option to share quest lines/rewards not working or hidden?

### ISSUE THREAD

**Issue by NOOTLORD** [NillerMedDild/Enigmatica6#2185]
**Modpack version**
Enigmatica 6 0.4.10 for both client and server 

**Describe the bug**
I am not sure if this bug is known already but the problem is we cannot make teams and share the same quest lines/rewards,
they are all tracked separately for each player even though we added eachother as Allies trough the map it still didn't allow us to share the same quest lines/rewards. 
As far as i remember some other modpacks do have this feature so could it be a bug or is it still a WIP feature?

**Logs**
Not applicable

**Screenshots**
Not applicable

**Comment by pm065** [comment]
https://github.com/FTBTeam/FTB-Quests/issues/470
