### ISSUE TITLE
Minecolonies

### ISSUE THREAD

**Issue by Jonnhis** [NillerMedDild/Enigmatica6#2186]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3106617

Minecolonies was rejected 10 months ago, maybe now is a good time to add it.
Could work well with The Mighty Architect / Schematicannon to create lively villages.

**Comment by NillerMedDild** [comment]
Still a no :)

**Comment by Jonnhis** [comment]
Reason?

**Comment by NillerMedDild** [comment]
We've had it in other Enigmaticas and this time I'd like to go without it.
