### ISSUE TITLE
Cycle Paintings

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2187]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/cycle-paintings

**Mod description**
>Cycle Paintings is a minimalistic mod which allows players to cycle through placed paintings by right-clicking them with another painting in their right hand. Also works with modded paintings.

**Why would you like the mod added?**
It's a good and small QoL mod. :)

**Comment by NillerMedDild** [comment]
Sure thing, now that it's open source :)
