### ISSUE TITLE
Suggestion: Temporarily disable CTM

### ISSUE THREAD

**Issue by pm065** [NillerMedDild/Enigmatica6#2188]
Reasoning: see 
https://github.com/vectorwing/FarmersDelight/issues/169
https://github.com/team-abnormals/abnormals-core/issues/69
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/149

These issues are caused by CTM acting funny with Neapolitan thatch and FD pie models.
This has occurred while starting up E6 since it contains Farmer's Delight. Until this bug is fixed, it might be better to disable CTM.

**Comment by NillerMedDild** [comment]
I think I'd rather have slightly increased load times instead of temporarily ruining builds :P Storage Drawers has had this issue since.. forever? anyway.
