### ISSUE TITLE
(Mod suggestion) Frozen up!

### ISSUE THREAD

**Issue by CletusMAngo** [NillerMedDild/Enigmatica6#2189]
https://www.curseforge.com/minecraft/mc-mods/frozen-up

**Mod description**
This mod adds a new mob called the chilloo! this mob is found in snowier biomes and is absolutely adorable, these creatures can be used to collect various crops as they occasionally dig into the ground to find carrots,potatos or truffles!
Truffles can be used to tame chilloos and also make other various food types 

**Why would you like the mod added?**
Cuteness
(In all seriousness tho) from what im seeing in the botania recipe changes for expert mode i think these could be used progression-wise maybe for Winter runes a chilloo feather can be used or maybe even a truffle and other than progression these add a pretty qol/unique way of getting crops.
May i also add that a new tree type is planned for the mod and alot more will come in the future 

**Screenshots if applicable.**

![image](https://user-images.githubusercontent.com/76655777/118407569-9dd5c100-b681-11eb-8deb-d43d3449d183.png)

**Comment by pm065** [comment]
Probably a little too vanilla+ and small for this pack but I'm not in charge

**Comment by CletusMAngo** [comment]
Eh i wouldnt really call it Vanilla+ but it does add a fair bit of stuff for its size

**Comment by NillerMedDild** [comment]
I don't know, I'm not really feeling it tbh :P

**Comment by CletusMAngo** [comment]
Could you guys give it a try? It might fit

**Comment by NillerMedDild** [comment]
Alright :/

**Comment by CletusMAngo** [comment]
Some of my pretty good friends develop the mod and they would love the mod to be in the pack :)

**Comment by NillerMedDild** [comment]
Alright I checked it out. The little fellas are very cute, but I don't see a need for this in the modpack tbh, so no thank you.
