### ISSUE TITLE
[Suggestion] Silent's Mods

### ISSUE THREAD

**Issue by Surnyy** [NillerMedDild/Enigmatica6#219]
Set of mods, essentially an alternative to Tinker's, adds its own fair share of machines and stuff and obviously a ton of materials to make and customize your gear with
Had fun messing around with it a little bit and the possibilities are just as endless as with Tinker's

dunno if you plan on waiting for Tinker's or would want to give these a try but yeah

https://www.curseforge.com/minecraft/mc-mods/silent-gear
https://www.curseforge.com/minecraft/mc-mods/silents-mechanisms

**Comment by NillerMedDild** [comment]
Thanks for the suggestion.

I've tried out Silent Gear many times, but I always end up disliking it :/
Silent's Mechanisms is a bit on the bland side, although it has nice textures and stuff.
