### ISSUE TITLE
Resource Pack not included by default

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2190]
**Description**
Hey, your mod pack is awesome!
Tbh, I found your resource pack first, then the mod pack. But I wonder why the resource pack is not included in the mod pack by default.

Greetings (:

**Comment by NillerMedDild** [comment]
Thank you 😄 It's a limitation of the method I use for putting the pack on CurseForge, hopefully it'll be fixed down the line.
