### ISSUE TITLE
Sound Device Options

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2191]
Sorry for spamming mod suggestions!

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/more-sound-config

**Mod description**
>Sound Device Options is a very small but handy mod. It allows you to switch the active sound output device while the game is running! This is useful for people who have a speaker and headphones attached to their PC and want to switch between them without needing to restart and chaning the primary sound device in your operating system.

**Why would you like the mod added?**
Another little QoL mod:
Loading mod packs takes some time. But when you forgot to change the correct sound device in the beginning you need to restart and this takes even more time. (:
This mod helps out really much.

Greetings

**Comment by falcoresaissore** [comment]
F3 + R reloads the sound if you need to change sound output

**Comment by Erysch** [comment]
> F3 + R reloads the sound if you need to change sound output

Ah, didn't know yet. Thank you!
It's still a handy Mod so you can play minecraft on a seperate audio device than your windows might be on (niche case).

**Comment by NillerMedDild** [comment]
I'd rather have it just work than the user having to know the reload audio keybinding :)
