### ISSUE TITLE
[0.4.12] Updating from 0.4.9 has resulted in the world becoming corrupted.

### ISSUE THREAD

**Issue by mkjeller** [NillerMedDild/Enigmatica6#2195]
**Modpack version**
0.4.12

**Describe the bug**
Upon upgrading to 0.4.12 from 0.4.9 and copying my "world" folder over from my 0.4.9 installation I have discovered that biome IDs have become scrambled.
My home biome, formally a savannah plains of some kind is now an End biome, the "Imparius Clearing".
Nearby biomes are similarly impacted, but terrain data is not. Minecraft "knows" I'm in the overworld, but the biomes have the spawn rates and environmental effects of their scrambled variant.

**Logs**
https://pastebin.com/NCvUZVFA

**Screenshots**
![image](https://user-images.githubusercontent.com/421534/118415017-cff61b80-b69f-11eb-89a0-7ef55f1d6d9e.png)

**Comment by MuteTiefling** [comment]
If you have a copy of the old world still, do the following:

1) revert back to 0.4.9
2) add [Biome ID Fixer](https://www.curseforge.com/minecraft/mc-mods/biome-id-fixer)
3) load the world in 0.4.9. this'll generate a biome map for Biome ID Fixer
4) shut down normally and update.

At this point, assuming your backup was still in good shape, you should be back to normal.

**Comment by mkjeller** [comment]
Success, that resolved the issue and all is well now.
Thank you for responding so quickly :)
