### ISSUE TITLE
No Recipe For Beehives

### ISSUE THREAD

**Issue by Tsilkani** [NillerMedDild/Enigmatica6#2196]
0.4.12

With the removal of basic honeybees in favor of more specialized tier 1 bees, there is no longer any bee that makes regular honeycomb. This means that the Beehive recipe in Resourceful Bees, which uses 3 honeycomb, cannot be made.

**Comment by MuteTiefling** [comment]
Minecraft Bees have not been removed.

**Comment by Tsilkani** [comment]
Oh, then they don't have any JEI info.
