### ISSUE TITLE
Looking at PneumaticCraft Spawner Agitator results in crash

### ISSUE THREAD

**Issue by occidentalis** [NillerMedDild/Enigmatica6#2198]
**Modpack version**
0.4.12

**Describe the bug**
Looking at a spawner with a spawner agitator from PneumaticCraft applied results in an immediate freeze and crash on server. The server was recently updated from 0.4.10 to 0.4.12, and player reports it worked on previous version.

**Logs**
https://pastebin.com/BhYtiZJ7

**Comment by NillerMedDild** [comment]
Thanks for the report, it should be fixed soon: https://github.com/TeamPneumatic/pnc-repressurized/issues/806#event-4753399653
