### ISSUE TITLE
Crash on world creation 0.2.0

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#22]
**Modpack version**
0.2.0

**Issue**
1) Go to create a new world
2) Wait for world to load
3) Game crashes out due to swap things mod
4) ... profit?

**Logs**
https://gist.github.com/Shindur/b1fd25108219d8db2f3ea0a724c35342

**Comment by Shindur** [comment]
It seems updating the mod to 1.0.1 from 1.0.0 fixes this issue. Tried redownloading the modpack version 0.2.0 and it has 1.0.0 included it seems.

**Comment by NillerMedDild** [comment]
Err.. I don't recall adding that mod. Are you sure this happens in default E6?

**Comment by Shindur** [comment]
I.... don't remember ever adding this to my instance.. I just downloaded a fresh copy to check and yea it's not in by default.. well then. Apologies!

**Comment by NillerMedDild** [comment]
No worries :)
