### ISSUE TITLE
MrCrayfish's Vehicle Mod

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2200]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-vehicle-mod

**Mod description**
>MrCrayfish's Vehicle Mod is about creating fun and useful vehicles. In this mod you can find an assortment of vehicles that will help you explore, farm, transport, race, and even fly! Every vehicle can be customised with different engines and wheels to change the speed and effective surfaces the vehicles can drive on. Using a spray can you change the colour of your vehicle to any combination of dyes. The mod also includes a simple fuel production system, great for beginners to start learning about machines and fluid pipes.

>-Adds over 20 vehicles (including powered vehicles and useful trailers)
>-Customise vehicles with different colours, wheels and engines
>-Simple and straightforward fuel production system (also supports 3rd party fluid pipes)
>-Tons of configuration options to adjust the mod to your liking
>-Support for datapacks to add and change machine/vehicle recipes (Minecraft 1.15+ only)
>-Optional support for Controllable (allows you to drive vehicles using a gamepad)
>-Bonus vehicles when installed with MrCrayfish's Furniture Mod
>-Most importantly traffic cones you can place on the ground or wear as a hat

**Why would you like the mod added?**
You can build so much with your mod pack. Even good looking towns, which wasn't really possible in vanilla minecraft. But I couldn't find any real modern vehicle which would suit to a town. This mod adds many vehicles, really lovely modelled and useful as well. Some vehicles are rideable for more than one player which is nice for roleplaying.
It would be nice if you could take a look. It doesn't add any ores ore something. You might consider tweaking the recipes (vehicles are pretty cheap and early to achieve imo) and the fuel generation (can be achieved when having access to blaze rods and ender pearls as well as glowstone dust) which might be okay but maybe some fuels from other mods may be integrated here. I already checked the config and it seemed that you can change the generated fuel as well, so you might remove those extra liquids created by the the Vehicle Mod and replace it with something from Thermal Series or something like that..

**Comment by NillerMedDild** [comment]
To be honest I don't think this would fit into E6.
