### ISSUE TITLE
Missing recipes for IE Wire Cutters and Wire Coils in expert mode

### ISSUE THREAD

**Issue by McJeffr** [NillerMedDild/Enigmatica6#2201]
**Modpack version**
0.4.10 (server)

**Describe the bug**
No recipes for Immersive Engineering Wire Coils and Wire Cutters when the mode is set to "expert" in `mode.json`. There is no alternative recipe, using JEI to show the recipe simply results in no results. When switching the mode back to "normal", several recipes for the Wire Cutters and all Wire Coils will show up again in JEI.

**Comment by NillerMedDild** [comment]
Thanks for letting us know, will be fixed in 0.4.13 :)
