### ISSUE TITLE
PNC:R Pressure gauge tube module

### ISSUE THREAD

**Issue by LoneWolf137** [NillerMedDild/Enigmatica6#2202]
Version
0.4.12

placing a pressure gauge tube module on a pressure tube crashes the game and i am unable to relaunch the world as long as someone is looking at it. Seems to be consistent with other Moduels as well.

[crash-2021-05-17_18.19.17-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6495433/crash-2021-05-17_18.19.17-server.txt)

**Comment by NillerMedDild** [comment]
Duplicate of #2198 - Will be hotfixed asap :)
