### ISSUE TITLE
[0.4.12] Pillagers don't spawn with crossbows

### ISSUE THREAD

**Issue by ShakterNano** [NillerMedDild/Enigmatica6#2203]
[0.4.12]

Pillagers don't spawn with crossbows, someone mentioned that it might be Tetra disabling it but I can't find it in the configs

**Comment by NillerMedDild** [comment]
I can't seem to reproduce this, where did you encounter them? :)

**Comment by ShakterNano** [comment]
Pillagers spawned in outposts, raids and patrols don't have crossbows

**Comment by ShakterNano** [comment]
This also happens on my testing world, and spawn eggs also don't spawn pillagers with crossbows, maybe one of my config files is borked?

**Comment by NillerMedDild** [comment]
Either that or it was fixed in the updates I've done since 0.4.12, I'll release them very soon so I guess we'll see 😄
