### ISSUE TITLE
Server crash on looking at Pneumaticcraft machines

### ISSUE THREAD

**Issue by Barlease** [NillerMedDild/Enigmatica6#2206]
E6 0.4.12

Updated server from 0.4.10 to 0.4.12. Entering an area with pneumaticcraft machines causes no issues, but looking at them causes the server to crash (see attached crash logs). It saves that player looking at them, so the next time that player joins, the server crashes again. These machines were built in 0.4.10 and no changes have been done to them in 0.4.12.

I see that 0.4.13 is out now. I will try updating to that and reporting back.

Crash 1 - https://pastebin.com/p1cqPYEa
Crash 2 - https://pastebin.com/BhnDMLrw

**Comment by TemperedFool** [comment]
This is a large reason for 0.4.13's release - an interaction between PNC and TOP was causing a CTD. Should be resolved by updating.

**Comment by Barlease** [comment]
FYI, updating to 0.4.13 did resolve this issue. Thank you for the fix.
