### ISSUE TITLE
[0.4.13] RS Pattern Grid no modded recipes via JEI

### ISSUE THREAD

**Issue by Skar78** [NillerMedDild/Enigmatica6#2207]
**0.4.13**

**Describe the bug**
Tried to add a recipe form JEI to add it to a pattern in the Pattern Grid of RS.  Specific example was the Megatorch from Torchmaster.

As long as the pattern grid is open there is no "pop-up" of the recipe. (Meaning the normal behaviour of clicking the item in JEI to get the recipe to click on the plus to add it does not show up.)
Instead of showing the recipe it will highlight the pattern grid green and nothing happens.

For vanilla items this does work (right click on JEI, left click on the item, plus to add) in the pattern grid.
For modded items its left/right click show absolutely no pop-up.

Was wondering whats up. Without being in the Pattern Grid it works - so for example in a workbench.

However, if i open a vanila recipe while pattern grid is open and manage to "click through" to the modded recipe i can add it.

Considered if this is somehow related to the config of JEI so i tried to click the wrench icon in JEI on the bottom right.
Nothing happens but the message appears: "Install FTB Library for install config" - i belive this had a menue in earlier versions of the pack.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
https://www.dropbox.com/s/htd8jnjuaqrwt7z/2021-05-18_08.01.28.png?dl=0
https://www.dropbox.com/s/2fm7bgi5ubo3zeu/2021-05-18_08.01.39.png?dl=0

**Comment by NillerMedDild** [comment]
Thanks for the report, this is probably caused by the latest JEI update. Downgrading it should fix the issue :)

**Comment by NillerMedDild** [comment]
You can bypass this issue by clicking `R` for recipe on the item. I'll hotfix this evening though :)

**Comment by NillerMedDild** [comment]
https://github.com/mezz/JustEnoughItems/issues/2359

**Comment by NillerMedDild** [comment]
Not hotfix after all, this seems more and more like an intended feature tbh. I expanded a bit on the issue I reported, it's a feature request now I guess?

**Comment by Darkere** [comment]
This was a feature he had for a while (you can downgrade to JEI 87) but he broke it when he refactored his mousehandler recently. 

:P https://github.com/mezz/JustEnoughItems/issues/2352
