### ISSUE TITLE
Crash & JEI Config 

### ISSUE THREAD

**Issue by Ludwigthedragon** [NillerMedDild/Enigmatica6#2209]
Latest, 0.4.13

Not really sure, had the minecraft window minimized and it just crashed. I do have optifine. Also, I can't open the JEI config despite having the FTB GUI library, and the JEI menu changed sizes when updating from 0.4.10 to 0.4.13

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6498276/latest.log)

**Comment by NillerMedDild** [comment]
Hmm, I think this is an Optifine issue, but try downgrading JEI to the last version if possible :)

**Comment by Ludwigthedragon** [comment]
Will do! I'll see if it's fixed, and I'll reply again if I crash for whatever mysterious reason

**Comment by NillerMedDild** [comment]
Part of it reported here: https://github.com/mezz/JustEnoughItems/issues/2355

**Comment by Ludwigthedragon** [comment]
Game crashed again, although this time I was in the nether trying to mine ore and it crashed. Here's the log 
[crash-2021-05-18_19.43.59-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6505123/crash-2021-05-18_19.43.59-client.txt)

**Comment by NillerMedDild** [comment]
Are you using OptiForge in addition to OptiFine?

**Comment by Ludwigthedragon** [comment]
Oh, no. I'm not sure what optiforge is

**Comment by NillerMedDild** [comment]
Ah, that's probably the issue 😄 OptiForge is pretty much required to use OptiFine on Minecraft 1.15+ https://www.curseforge.com/minecraft/mc-mods/optiforge/files/3248738

**Comment by Ludwigthedragon** [comment]
Ah, thanks. The crashing wasn't very often or repeatable, but I'll let you know how it goes.

**Comment by greatmonkey** [comment]
I just updated to 0.4.13 and anytime I try to go into the config of JEI it says to install FTB Library to access in game config.

**Comment by liamthorell** [comment]
This is the problem:
https://github.com/FTBTeam/FTB-Library/issues/28

**Comment by MaxNeedsSnacks** [comment]
This issue is no longer valid now as the previously "unstable" releases of FTB Mods have been released and incorporated into this pack ^^
