### ISSUE TITLE
Issue with the new Memory Stick item

### ISSUE THREAD

**Issue by SylviaGrim** [NillerMedDild/Enigmatica6#221]
**Modpack version**
2.13

**Issue**
When using the Memory Stick item in a server and a singleplayer world, if I remove the memory stick from my offhand/main hand at all, any EXP stored inside the memory stick will be permanently deleted and unretrievable. If you log out of the SP world or the server, it also becomes unretrieveable and is essentially gone. The memory stick doesn't show how much EXP is in the device, so you can't tell if it is saving or not saving. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
The only part I could reproduce was `The memory stick doesn't show how much EXP is in the device, so you can't tell if it is saving or not saving.`
