### ISSUE TITLE
Misleading mod page information

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2210]
**Modpack Version**
0.4.12

**Describe the bug**
Your mod page says YUNG's better caves is included, saying "YUNG's better caves/mineshafts" but it's not. You might consider it removing from the mod page or adding the mod again. I really thought this was included haha. Took a while to notice due to the beautiful stone generation. 

Why did you actually remove this mod or did I remove this one accidently? Was it to excessive? 

**Screenshot**
![Screenshot_20210518_081757.jpg](https://user-images.githubusercontent.com/81813584/118600668-9a415780-b7b1-11eb-8266-b7bdb3b9e300.jpg)

Greetings (:

**Comment by MaxNeedsSnacks** [comment]
YUNG's had some massive tick time issues in combination with TerraForged, so it was later removed after the original 0.4 release ^^

**Comment by pm065** [comment]
> YUNG's had some massive tick time issues in combination with TerraForged, so it was later removed after the original 0.4 release ^^
Wait it does????
This.... explains a lot. (My WIP modpack was having tick issues and I had no idea why. Thanks, even though you didn't intend to help '-')

**Comment by Darkere** [comment]
Our issue was more like the world pretty much stopped loading. Nothing to do with ticking. But yes we should remove it from the description.. I don't think the dev was able to figure out the exact cause (or if it even was better caves or another mod causing it)

**Comment by NillerMedDild** [comment]
Thank you kindly, I gave it a once over :D
