### ISSUE TITLE
[Mod Suggestion] Pretty Pipes: Fluids

### ISSUE THREAD

**Issue by Quarris** [NillerMedDild/Enigmatica6#2211]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/pretty-pipes-fluids

**Mod description**
Addon to Pretty Pipes which allows handling of fluids within the pipe network

**Why would you like the mod added?**
Allows expanding the Pretty Pipes network with a centralised system of fluids, helping with transportation.
Has planned crafting with fluids.

**Comment by NillerMedDild** [comment]
@Merlo17 Do you have time to investigate whether PP Fluids should have new recipes for E6? :)

**Comment by MuteTiefling** [comment]
Yeah, I think these should be Thermalized like we did for base Pretty Pipes. Lots of rubber and such.
