### ISSUE TITLE
Add a crafting recipe for the Flux Efficiency augment

### ISSUE THREAD

**Issue by DarkAngel22579** [NillerMedDild/Enigmatica6#2212]
**Description**
This originally didn't have a recipe as KL was worried it would be a little too OP. It isn't, and the next Thermal update is probably a while away so it'd be nice to be able to craft it. This is the planned recipe afaik:

```json
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    " L ",
    "EXE",
    " L "
  ],
  "key": {
    "E": {
      "tag": "forge:plates/electrum"
    },
    "L": {
      "tag": "forge:gears/copper"
    },
    "X": {
      "item": "thermal:rf_coil"
    }
  },
  "result": {
    "item": "thermal:machine_efficiency_augment"
  },
  "conditions": [
    {
      "flag": "machine_augments",
      "type": "thermal:flag"
    }
  ]
}
```

**Comment by NillerMedDild** [comment]
I'd rather wait for them to add it themselves to be honest, we're still a few weeks away from 0.5.0 anyway :)
