### ISSUE TITLE
Trofers

### ISSUE THREAD

**Issue by ochotonida** [NillerMedDild/Enigmatica6#2213]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/trofers

**Mod description**
Adds customizable tropies, might come in handy as rewards for the challenge quests

**Why would you like the mod added?**
Because I made it :p

**Screenshots if applicable.**
![](https://user-images.githubusercontent.com/37985539/118311814-af3b9380-b4f0-11eb-8e90-714ea53f2dcb.png)

**Comment by NillerMedDild** [comment]
Yesssss, thank you 😄
