### ISSUE TITLE
[Suggestion] Dynamic trees

### ISSUE THREAD

**Issue by snaiperskaya** [NillerMedDild/Enigmatica6#2214]
This mod is amazing and recently got updated to 1.16.5: https://www.curseforge.com/minecraft/mc-mods/dynamictrees

I didn't see this suggested anywhere else, so I wanted to include it as a possible for 0.5.0, especially since I'm sure some people (like myself) will also be starting new worlds for 0.5.0 with all the biome changes.

If you do pick up this mod, make sure to also get any appropriate add-ons:
![image](https://user-images.githubusercontent.com/4693814/118668477-e6e15e80-b7c2-11eb-9023-f99128a958cc.png)

**Comment by pm065** [comment]
It'd be a little weird with BYG trees and such not being dynamic, but once it gets an absurd amount of addons like in 1.12 I'd 1000% agree

**Comment by CletusMAngo** [comment]
I dont think its compatible with Terraforged actually, i also think with the devs trying to reduce load times this would contribute significantly to extra long load times

**Comment by snaiperskaya** [comment]
I hadn't heard it was incompatible with terraforged, but that would be unfortunate. 

I've used it before in 1.12 and it was surprisingly performant, but I'm not sure the end-goal of 0.5.0 to say if this would fit or not. If this doesn't get added officially, I might add this myself, but then I'm (more-or-less) restricted to playing alone.

**Comment by CletusMAngo** [comment]
> I hadn't heard it was incompatible with terraforged, but that would be unfortunate.
> 
> I've used it before in 1.12 and it was surprisingly performant, but I'm not sure the end-goal of 0.5.0 to say if this would fit or not. If this doesn't get added officially, I might add this myself, but then I'm (more-or-less) restricted to playing alone.

Issue is,This is 1.16 it performing well in 1.12 doesnt mean itll perform well in 1.16. these are two very VERY different versions we're talking about here

**Comment by snaiperskaya** [comment]
Oh, I get that and I was just speaking anecdotally. Obviously, this would need to be tested, but I just wanted to point out that performance is important to the mod dev and s/he had done well in the past to make it as performant as possible.

**Comment by NillerMedDild** [comment]
I really like Dynamic Trees, but I am concerned that this will have a negative impact on performance, as mentioned above. I know it performed well in 1.12, but I never tested it with anything near 300 mods. I'll think about it.

**Comment by theboo** [comment]
I've never used this, but to add it/test it we would most likely need to turn off custom features in terraforged preset

**Comment by CletusMAngo** [comment]
Awww 

> I've never used this, but to add it/test it we would most likely need to turn off custom features(which is just TF's version dynamic trees) in terraforged preset

I love the variety of the Terraforged trees :/

**Comment by pm065** [comment]
> Awww
> 
> > I've never used this, but to add it/test it we would most likely need to turn off custom features(which is just TF's version dynamic trees) in terraforged preset
> 
> I love the variety of the Terraforged trees :/

Aren't the TF trees incompatible with Nature's Aura or something? Or is that just the small ones?
Actually, that's made me remember something; Dynamic Trees' Nature's Aura addon doesn't yet allow the Ritual of the Forest to work with dynamic ones, so if DT was confirmed to be added they'd need to wait for that to be done.

**Comment by NillerMedDild** [comment]
>  And aren't the TF trees incompatible with Nature's Aura or something? Or is that just the small ones?

Nope

**Comment by CletusMAngo** [comment]
> > Awww
> > > I've never used this, but to add it/test it we would most likely need to turn off custom features(which is just TF's version dynamic trees) in terraforged preset
> > 
> > 
> > I love the variety of the Terraforged trees :/
> 
> ![image](https://user-images.githubusercontent.com/81559564/118759474-016e1300-b869-11eb-85cf-837484bc472a.png)
> This looks more like variety than those trees ever were... The only problem, in my view, is the current lack of compatibility addons compared to 1.12.
> And aren't the TF trees incompatible with Nature's Aura or something? Or is that just the small ones?
> Actually, that's made me remember something; Dynamic Trees' Nature's Aura addon doesn't yet allow the Ritual of the Forest to work with dynamic ones, so if DT was confirmed to be added they'd need to wait for that to be done.

Huh nice! I guess the only concern would be performance which could be an issue

**Comment by NillerMedDild** [comment]
It's gonna be a no for the time being, based on lack of addons, and having no real need for it in the pack. We may re-evaluate later on.
