### ISSUE TITLE
crash on create new world with biomeidfixer on certain Linux distros

### ISSUE THREAD

**Issue by picareta171** [NillerMedDild/Enigmatica6#2216]
**Modpack version**
0.4.13, new installed
installed on multimc 5 - 0.6.12, single player

**Describe the bug**
happens in 0.4.11 and 0.4.12 too
game crash after create new world process is 100%.
remove de mod biomeidfixer, solve the problem.

**Logs**
i can not open pastebin site for the crash file, i have (DNS_PROBE_FINISHED_NXDOMAIN).

**Screenshots**
0.4.13:
![enigmatica_crash](https://user-images.githubusercontent.com/75444425/118693952-ed330300-b7e1-11eb-91fd-93774cd9b4ef.png)

**Comment by desagas** [comment]
I think I have fixed it. If anyone is available to test in Linux and Windows, in https://github.com/desagas/Biome-Id-Fixer/commit/b48825797d439947dd68b43376c2235a6559a21e

1.0.1.1s should be on Curse very shortly, if not already.

**Comment by picareta171** [comment]
i tested and had no crash, creating a new world or loading a previous one.
thank you!

**Comment by desagas** [comment]
@NillerMedDild, I have reduced the required Forge dependency version to 36.1.16, down from 36.1.23, because I noticed a lot of mods have not updated that high yet. This should make the Linux fix more accessible to everyone.
