### ISSUE TITLE
(Mod suggestion) Malum

### ISSUE THREAD

**Issue by CletusMAngo** [NillerMedDild/Enigmatica6#2225]
**CurseForge Link**

https://www.curseforge.com/minecraft/mc-mods/malum

**Mod description**

Malum is a dark magic mod that brings huge Thaumcraft/Dark magic vibes, its spells/magic rely on souls which are obtained by doing rituals on mobs

**Why would you like the mod added?**

I feel like this mod would go amazingly with eidolon in the pack and i think it adds some interested mechanics that are alot different than the current magic mods 
I also feel that the mod is very fleshed out so theres not alot of loose ends to the mod.
Edit: the creator of eidolon Elucent did also help with this mod so thats a plus aswell :)

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/76655777/118974213-da9c0380-b972-11eb-8554-d280699f9370.png)
![image](https://user-images.githubusercontent.com/76655777/118974239-df60b780-b972-11eb-8e73-518522b2559b.png)
![image](https://user-images.githubusercontent.com/76655777/118974257-e5ef2f00-b972-11eb-9072-4f06c383b0a3.png)

**Comment by NillerMedDild** [comment]
Looks very promising, but I don't think it has enough to add just yet :)

**Comment by CletusMAngo** [comment]
Oh really? i honestly think its pretty fleshed out, has a whole ritual system,infusion crafting, a soul gathering system, it has almost as much as eidolon at this point.

**Comment by NillerMedDild** [comment]
Ahem. I thought the last screenshot on the mod page was all added items, I read wrong :P

**Comment by pm065** [comment]
Poking around in their github reveals it has no datapack support :(

**Comment by CletusMAngo** [comment]
> Poking around in their github reveals it has no datapack support :(

Dude, the mod was released yesterday give em a bit. buy the time 0.5.0 releases i think they'll have datapack support

**Comment by NillerMedDild** [comment]
I like what I'm seeing, but don't think it has enough to warrant being added yet. We will be keeping a close eye on Malum as it updates though :)
