### ISSUE TITLE
Game in Limbo

### ISSUE THREAD

**Issue by zLc362** [NillerMedDild/Enigmatica6#2226]
After updating from 4.9 to 4.12 and then 4.13. My game enters a sort of limbo state after playing for a couple of minutes, new chunks don't load, commands don't work, one probe says "waiting for server", blocks don't drop, but i can move around and break blocks, open my inventory etc. If i save and quit it gets stuck on saving world and i have to close it with task manager.

![2021-05-19_20 38 13](https://user-images.githubusercontent.com/70441747/118986790-15b12d80-b999-11eb-8c4d-b89033763276.png)
![2021-05-19_20 38 22](https://user-images.githubusercontent.com/70441747/118986800-1649c400-b999-11eb-9992-46adf6a3ecba.png)
Here's the log after force closing it
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6516248/latest.log)

**Comment by zLc362** [comment]
[debug.log](https://github.com/NillerMedDild/Enigmatica6/files/6517916/debug.log)

I have 8GB total, i downloaded 4.9 again and copied my save over and it works fine

**Comment by NillerMedDild** [comment]
Hmm, something odd is definitely going on at the end of both of those logs, but there's no real indication as to what :/

**Comment by NillerMedDild** [comment]
You're on Windows right?

**Comment by zLc362** [comment]
Yes, i'm on windows 10

**Comment by NillerMedDild** [comment]
Please feel free to reopen if new information becomes available.
