### ISSUE TITLE
Mod Suggestion - AIOT Botania

### ISSUE THREAD

**Issue by MaxFirestorm** [NillerMedDild/Enigmatica6#223]
Mod Link: https://www.curseforge.com/minecraft/mc-mods/aiot-botania

I'm not normally one for mods that just add stuff like AIOTs (All In One Tools), but this also adds hoes for Manasteel, Elementium and Terrasteel as well as a full suite of tools for Livingwood and Livingrock.

The main reason I suggest this though is for the hoes. With a decent handful of blocks in the 1.16 update having hoes as their preferred tool for breaking (most notably the Warped/Nether Wart Blocks and Shroomlights that make up the huge Nether Fungi trees, as well as target blocks, hay bales and so on), Botania on its own doesn't have a hoe for *any* of its materials. This means if you're using Botania as your main mod, you'll still need something vanilla-y or other mod to break these blocks efficiently.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion! Have you verified that AIOT Botania hoes harvest Warped Blocks faster? :)

**Comment by MaxFirestorm** [comment]
Can confirm that the hoes themselves harvest hoe-type blocks faster than hands or other tools. Tested on Warped Wart Blocks and Hay Bales.

Strangely though, despite the AIOTs taking the hoes as part of their recipes and WAILA saying that the AIOTs are the correct tool, they *don't* harvest faster.

But considering the hoes were the main thing I wanted, I guess that's still a success =B

**Comment by NillerMedDild** [comment]
Heh alright, I'll add it :)
