### ISSUE TITLE
Applied Energistics 2

### ISSUE THREAD

**Issue by zMigueel** [NillerMedDild/Enigmatica6#2231]
You have any plans to add this again? I know RS is good, but, actually I have more preference on use AE2 instead of RS

---------------------------->

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2

**Mod description**
Basically a more complexity version of Refined Storage

**Why would you like the mod added?**
For have 2 options of logistics mods, I think have players who prefer use AE2 instead of RS

**Comment by MuteTiefling** [comment]
Has been discussed at length:
https://github.com/NillerMedDild/Enigmatica6/issues/761
https://github.com/NillerMedDild/Enigmatica6/issues/845

At this point it's duplicate content that we don't need.
