### ISSUE TITLE
Consider alternate minimap/worldmap mods

### ISSUE THREAD

**Issue by Gotolei** [NillerMedDild/Enigmatica6#2233]
**Description**
Consider disabling the FTB Chunks minimap by default and instead include a map mod(s) that is functional and familiar.

**Why would you like this added/changed?**
The common mods that are used for mini/world mapping are JourneyMap and Xaero's set, for good reasons: they're incredibly configurable, people are familiar with them, and they're snappy and fluid to use. FTB Chunks is, as far as I can tell, none of these. The impression I get from FTB Chunks is that it was created as an interface for chunkloading first and foremost, and everything else is still in its infancy and lacks the polish and quality of life that other mods had figured out years ago. The entire scope of its configuration consists of about 25 options, and even common ones like having a square map instead of a circle one and adding waypoints using a hotkey aren't available.

A quick search of the discord server `minimap in:enigmatica6` shows no shortage of people puzzled by how to use the minimap and/or asking how to replace it with a different one.

I see JourneyMap has been considered and dismissed in the recent past due to performance concerns (#1340), but that says nothing conclusive about Xaero's minimap and worldmap. Other than just using FTB Chunks because it's already included for its chunkloading functionality, is there a reason for the omission of mapping mods that do the job so much better and don't make the pack more confusing to use?

**Comment by NillerMedDild** [comment]
Yes, the reason is that map mods are heavy performance wise. Having two running would have a very negative impact on performance. 

That being said I'll reconsider Journeymap for 0.5.0, maybe the performance has improved since last time.

**Comment by NillerMedDild** [comment]
I've re-opened #1340 :)
