### ISSUE TITLE
Some Assembly Required

### ISSUE THREAD

**Issue by pm065** [NillerMedDild/Enigmatica6#2235]
https://www.curseforge.com/minecraft/mc-mods/some-assembly-required

It's a sort-of-port of the popular Fabric mod Sandwichable, adding sandwiches that can be constructed with any kind of food. It would require a little setting up since it adds its own cutting board and knife which would need to be disabled, but that shouldn't be too difficult.
Using the tags, you can customise it a bit:
`someassemblyrequired:sandwich_breads` allows you to add items that can be used as bread
`someassemblyrequired:toaster_metals` allows you to add items that you probably shouldn't put near a toaster
There may be a blacklist tag I haven't found yet.

sammidge setup:
![2021-05-21_07 08 38](https://user-images.githubusercontent.com/81559564/119090822-00bdb400-ba04-11eb-80a1-3d07235af0d5.png)

redstone-powered toaster:
![2021-05-21_07 08 48](https://user-images.githubusercontent.com/81559564/119090853-0d420c80-ba04-11eb-93ed-77f16b2457cb.png)

sammidge about to be eaten:
![2021-05-21_07 09 34](https://user-images.githubusercontent.com/81559564/119090877-1632de00-ba04-11eb-96c7-dd3052632828.png)

meta-sammidge (sammidge containing Farmer's Delight sammidge)
![2021-05-21_07 12 27](https://user-images.githubusercontent.com/81559564/119090915-264abd80-ba04-11eb-9db3-5a3233756cb4.png)

**Comment by ochotonida** [comment]
Mod author here! To be fair, this mod could use a bit more work, but I've been putting it off for quite some time now while I've been working on other stuff. The main thing I still need to do is proper Diet support. It's possible that it's already partly compatible, but I don't think it shows any nutrition values. Doing it properly will likely require me to rewrite a couple of things though.
Right now it also doesn't show the right hunger/saturation when used with AppleSkin, but I'm waiting for a forge PR for that one.
(There's some other things I'd like to rewrite as well, but most of it will have to wait until 1.17)

**Comment by NillerMedDild** [comment]
Very cool mod, but I think we're set for food-type mods tbf :)
