### ISSUE TITLE
woot

### ISSUE THREAD

**Issue by yuri0r** [NillerMedDild/Enigmatica6#2236]
[woot](https://www.curseforge.com/minecraft/mc-mods/woot)

i know it has been refused in #590 but not much reason has been given and it looks like woot has not been updatet to 1.16.5 at that time wich is not the case anymore. if the reason was simply a feeling that it didnt fit or wasnt liked it would be nice know, the pack is awesome with or without it.

**Mod description**
in short a multiblock structure that enables entity-less mobfarms.

**Why would you like the mod added?**
honestly ever past 1.7.10 any mod that helps with lag on servers (less entitys -> less lag) i want to see it in large packs. it even interacts with bloodmagic wich is present in the pack so thats a nice bonus.

**Comment by pm065** [comment]
I think when the pack author just says 'nah' it's mainly because they just don't like it, but I could be wrong. Woot, in my opinion, feels a little off and I don't know why.

**Comment by yuri0r** [comment]
idk, it takes some effort, but can do any mob drop, has unique crafting mechanics, and is a challancge to decorate in a way that looks nice. also the multiblock is easy to build because it does the thing with a tool wich autoplaces the needed blocks as long as they are in your inventory. i am fine with "nah, i dont like it" as an answer but  "This is gonna be a nope :)" kinda does not give any reason. i know i am not obligated to be given a reason but if id like to know i shall feel free to ask. :)

**Comment by NillerMedDild** [comment]
Fair enough, I'll rephrase: I don't like the premise of the mod, and that's why I will not add it :)
