### ISSUE TITLE
Sleep Mod in Multiplayer causes time to be set to Day in Hammock

### ISSUE THREAD

**Issue by IdioticProphet** [NillerMedDild/Enigmatica6#2241]
**Modpack version**
Latest as of 5/21/21, running the latest server on forge "out-of-the-box"

**Describe the bug**
So the Hammock from `comforts` is supposed to set the time to night (when it is day), this works as intended, unless you are: in a multiplayer server **and** there is another person in the server.

When there is a second person, the time is instead set to day because ~~the mod~~ ~~Mobius~~ Morpheus sees it as sleeping in a bed (This mod used to be called Insomnia back in 1.7).

Fix?: Make it so that the insomnia (edit: ~~Mobius~~ Morpheus) mod recognizes the hammock separate from the bed, maybe this needs to be with comforts not inheriting the vanilla bed class? maybe it needs to be with the sleep mod/plugin where it recognizes the hammock as something different and sets it to night? forgive the vagueness I'm not super familiar with modding minecraft in particular, and I'm not sure this is the packs problem specifically.

**Video**

https://user-images.githubusercontent.com/20072862/119201346-57eb7500-ba54-11eb-8b02-50616b20a5e1.mp4

First I slept with 2 players in the game, then I made my alt leave and slept with only one. notice that the orange text only appears when there are two players and the bug is only present with two.

two edits later mod is called Morpheus not mobius

**Comment by NillerMedDild** [comment]
Great bug report, thanks for reporting - I've relayed it :)

**Comment by landretk** [comment]
I've just noticed Quark is configured with 
> 	"Improved Sleeping" = true
> ...
> 		"Percent Req" = 1.0

But Morpheus is also in the pack and configured to run. Should Quarks Improved Sleeping be set to false? Or is it enabled for a reason?

Quark's sleep is compatible with Comforts hammocks as far as I know, so maybe should just let quark handle it and drop Morpheus. I don't have an alt to test with to be sure though.

**Comment by NillerMedDild** [comment]
Err yeah that's supposed to be off ^^'

**Comment by NillerMedDild** [comment]
I've removed Morpheus in-dev and will verify it at some point :)
