### ISSUE TITLE
Sushi Go crafting prawns and tuna spawning on bedrock

### ISSUE THREAD

**Issue by aqpoyo** [NillerMedDild/Enigmatica6#2242]
**Modpack version**
0,4,14

**Describe the bug**
A lot of sushi fish spawn in bedrock, they die, and they leave a lot od entities.
It was a big laggy on e6 server and we found under the base of one of the players where he had been mining under the ocean, a lot of prawns and tuna spawning in bedrock. Don¡t know if it was the problem of the lag but it strange that they don't spawn in water.

![2021-05-21_23 50 28](https://user-images.githubusercontent.com/81689755/119201935-1bd60580-ba90-11eb-8ea1-3a71a9b1d4ea.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, I also found it here: https://github.com/Buuz135/SushiGoCrafting/issues/4
