### ISSUE TITLE
Dupe bug with occultism

### ISSUE THREAD

**Issue by wolfdances** [NillerMedDild/Enigmatica6#2245]
**Modpack version**

**Describe the bug**

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

Version 4.12 and 5.0

Firelight transporter from occultism when used with mechanism never uses up item giving infinite resource. Like uranium for reactor.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Closing this as the newer report is more descriptive.
