### ISSUE TITLE
Pretty Pipes oversending causing dropped items

### ISSUE THREAD

**Issue by Cyler1992** [NillerMedDild/Enigmatica6#2248]
**Modpack version**
0.4.13

**Describe the bug**
Items that are being pulled out by pretty pipes but return because the point where they
should be stored is filled before they reach it can be dropped.
As of now i am not sure if this is repeatable.
But as a matter of fact it dropped me ~4k of lapis honey bottles in an instant.

**Logs**
If log is needed then i need a step-by-step where to find it. (possible log time: 23/05/21 ~14:17-14:22, noted for myself)

**Screenshots**
![centrifuge_bug_setup](https://user-images.githubusercontent.com/42421344/119260343-ade62700-bbd2-11eb-85f6-ced0d670da9c.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I have been unable to reproduce this I'm afraid. Has it happened more than once?

**Comment by MuteTiefling** [comment]
This is normal, actually. It picks a destination as it extracts and if that inventory fills up or otherwise disappears (like if you broke it) before the items get there, they'll spill out on the ground.

Bit odd that you got 4k at one time though...

**Comment by NillerMedDild** [comment]
> This is normal, actually. It picks a destination as it extracts and if that inventory fills up or otherwise disappears (like if you broke it) before the items get there, they'll spill out on the ground.

That didn't happen for me, they just bounced back and returned to the "sender" - Does it depend on Extraction tier or something? I used the Low one.

**Comment by MuteTiefling** [comment]
They'll go back to the extraction point of they can yeah, but in the case of a centrifuge they wouldn't be allowed back in
