### ISSUE TITLE
valid apiary block suggestions

### ISSUE THREAD

**Issue by yuri0r** [NillerMedDild/Enigmatica6#2249]
**Description**
right now the list of valid apiary blocks is rather short so id like to propose the following additions:

**vanilla**
- blackstone bricks variants (polished blackstone brick stairs are already valid its weird that the bricks themselves are not)
- basalt (has woodlog-esk texture and makes for a nice addition

**blood magic has plenty of decorative blocks**
- all "path" 
- demonic bricks (and variants)
- runes (basic and all upgrades makes for very evil looking apiaries)
- ritual blocks (and variants)

jei search term to find the blocks more easily
`@bloodmagic safe | @bloodmagic path | @bloodmagic Demon bricks| @minecraft polished blackstone bricks | @minecraft basalt`

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by yuri0r** [comment]
may i add to my suggestions? IE treated wood planks and the botania grass blocks (jei search `@botania grass -aiot`) those grasblocks also disable passive mob spawns wich is usefull, gets anoying to remove sheeps from apiary. :)

<details>
  <summary>a few screenshots using some of the suggested blocks so you dont have to play around with all that many of them</summary>

![2021-05-23_23 56 01](https://user-images.githubusercontent.com/9966894/119277918-96cf2580-bc22-11eb-9b64-ade18ec457be.png)
![2021-05-23_23 56 07](https://user-images.githubusercontent.com/9966894/119277920-99317f80-bc22-11eb-9c55-b16034e31869.png)
![2021-05-24_00 03 08](https://user-images.githubusercontent.com/9966894/119278105-7c497c00-bc23-11eb-95ba-e545b6e9e20b.png)

</details>

**Comment by TemperedFool** [comment]
Those should be covered once #2257 is closed. Any others I can add before that (and this) are closed @yuri0r?

**Comment by yuri0r** [comment]
thats all i am aware of right now. i guess if engeniers decor is in the pack than just about anything that one adds is beatifull
