### ISSUE TITLE
Occultism/Mekanism Duplication Glitch

### ISSUE THREAD

**Issue by Lithnane** [NillerMedDild/Enigmatica6#2250]
**Modpack version**
0.4.14
**Describe the bug**
Using the Foliot Transporters from occultism you can import materials into mekanism Machines and Infinitely dupe them using a chest as an export and the machine as the import the Foliot will not use any materials in its hand and will fill the machine indefinitely
**Logs**
Does not cause a crash so my logs wont be very helpful
**Screenshots**
Full videos on my stream Twitch.tv/Lithnane
![2021-05-23_13 10 48](https://user-images.githubusercontent.com/84678623/119269964-580c8180-bbc8-11eb-9e9a-9f50afd1f010.png)
![2021-05-23_13 10 53](https://user-images.githubusercontent.com/84678623/119269966-5a6edb80-bbc8-11eb-9b78-758ba5e5a70f.png)

**Comment by NillerMedDild** [comment]
you mean like #2245 ? 😄 Closing that one though, as this is more descriptive. Thanks for the report!

**Comment by NillerMedDild** [comment]
I have a dupe bug for you @klikli-dev :) I hope you don't mind the ping.

**Comment by Lithnane** [comment]
Yeah hes one of my followers i requested that he report it because i didnt have a github account but he put firelight so i had to make an account XD

**Comment by Lithnane** [comment]
if you would like i could show you the glitch in discord or something, Idk if that would help

**Comment by NillerMedDild** [comment]
No thanks :)

**Comment by klikli-dev** [comment]
@NillerMedDild thanks for the mention!

**Comment by yagoplx** [comment]
the fix for this has been in the modpack for a while, you can close it :)
