### ISSUE TITLE
Storage Drawer Value Issue

### ISSUE THREAD

**Issue by Cyler1992** [NillerMedDild/Enigmatica6#2252]
**Modpack version**
0.4.13

**Describe the bug**
The storagedrawer has a negative underfloat value for its content.
Found it like this at random. Dont know how to repeat this issue.
//EDIT: Its impossible to draw sth out of it. It does not accept a new item as input. If I break it and place it it shows the snowballs again with this value. The block is broken and not usable anymore.

**Logs**
 none

**Screenshots**
![storagedrawer_snowballs](https://user-images.githubusercontent.com/42421344/119275950-4b177e80-bc18-11eb-8fee-e1539fb45054.png)
![storagedrawer_snowballs2](https://user-images.githubusercontent.com/42421344/119276131-6a62db80-bc19-11eb-984e-c2100d89eece.png)

**Comment by NillerMedDild** [comment]
I'm afraid Storage Drawers doesn't really.. bug fix anything. There's nothing we can do here :( thanks for the report anyway.
