### ISSUE TITLE
Broken Heart bauble functionality

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#226]
Using Enigmatica 6 0.2.14

The broken heart bauble description states that taking lethal damage will destroy health heart containers instead, but that they will regenerate after sleeping.  In a fight with an apotheosis guardian boss the lethal damage effect of the bauble went into effect and I was reduced to 1.5 hearts max health.  However, sleeping (initially in a Comforts sleeping bag and later in my bed) did not restore the original max health but remains at 1.5 hearts.

**Comment by AdamNisbett** [comment]
Update - max health did return to normal after dying though.

**Comment by NillerMedDild** [comment]
Thanks for the report, I confirmed the issue and will relay it :)

**Comment by NillerMedDild** [comment]
https://github.com/CursedFlames/BountifulBaubles/issues/40

**Comment by anontaco** [comment]
i noticed this, seems to correct itself after a relog
