### ISSUE TITLE
Gantry carriage kills the server

### ISSUE THREAD

**Issue by aqpoyo** [NillerMedDild/Enigmatica6#2266]
**Modpack version**
0.4.14

**Describe the bug**
So I have a veggie farm with the piston extender in create and harvesters and it was working fine, but I updated it using Gantry carriage to move it and when I connected the gantry to the windmill it killed the e6 server. When the server was up again the gantry carriage, the chassis and the harvesters where gone. I assembled it again in a different set up and when I connected the contraption with the gantry shaft to the windmill it crashed again. It is the first time I use the gantry in a contraption.

**Comment by Darkere** [comment]
Likely lithium, which is only on the official server.

**Comment by aqpoyo** [comment]
Lithium? From Mekanism? I haven't got any.

**Comment by CletusMAngo** [comment]
> Lithium? From Mekanism? I haven't got any.

Hes talking about the performance mod lithium XD
It causes some issues here and there
