### ISSUE TITLE
[Mod Suggestion] Pam's HarvestCraft 2 - Food Core

### ISSUE THREAD

**Issue by novaexe** [NillerMedDild/Enigmatica6#227]
updated to 1.16.1/.2 more options for a balanced diet, full compatibility with cooking for blockhead's and simply farming, and it's pam's :) 

https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core/files/3017324

**Comment by NillerMedDild** [comment]
I don't plan to do anything special with food for E6 (at the moment at least), so I think having Simple Farming is plenty :)

**Comment by chaoaretasty** [comment]
For what it's worth, I hope this gets looked at again once E6 is more mature.

**Comment by Placid-Storm** [comment]
I have to agree, I keep looking at the four slots on the oven and want to put something there. Without Harvestcraft it feels a little naked. I'm enjoying the mod pack, thanks for making it.
