### ISSUE TITLE
Server Crash issue 

### ISSUE THREAD

**Issue by nakarumadra** [NillerMedDild/Enigmatica6#2275]
**Modpack version**
Enigmatica 6 0.4.13

**Describe the bug**
server keeps crashing

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
[crash-2021-05-25_19.15.12-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6542889/crash-2021-05-25_19.15.12-server.txt)

**Screenshots**

**Comment by nakarumadra** [comment]
[crash-2021-05-25_19.27.56-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6542936/crash-2021-05-25_19.27.56-server.txt)
latest crash issue, I really can't tell what the error is from these crash reports.

**Comment by NillerMedDild** [comment]
Looks like something went wrong during installation, I recommend trying a clean reinstall :)

**Comment by NillerMedDild** [comment]
So... did a reinstall help?
