### ISSUE TITLE
Quest updates: Mythic Botany and Thermal

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#2277]
Review Thermal Quests

- Aqueous Accumulator
- Igneous Extruder
- Vaccumulator
- Nullifier
- XP Crystals
- Blast Chiller
- Magma Crucible
- Energetic Infuser

Review Botania Quests

- Branch of Yggdrasil
- Gjallarhorn
- Water from the Well of Mimir
- Gaia 2
- Rune Tablet of Fibultyr
- Blood of Kvasir
- Mead of Kvasir
- Going to Alfheim

**Comment by pm065** [comment]
Maybe also a quest on that new ring you can find in Alfheim?
