### ISSUE TITLE
Can't copy banners

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2279]
**Modpack version**
0.4.14

**Describe the bug**
You seem to not be able to copy banners anymore. Usually you put the banner with the pattterns to copy with another patternless banner with the same base color in the grafting grid to get a copy. But this doesn't work for me. Is this intended?

**Screenshots**
![Banner_Bug](https://user-images.githubusercontent.com/81813584/119699583-9d43e400-be52-11eb-81ac-0b2ed43827a3.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
trying to figure this one out right now. It's not a script issue, at least. So now it's on to pulling apart mods.

**Comment by MuteTiefling** [comment]
seems like this might be a multi mod issue... 
Remove all these and it's still an issue: [list.txt](https://github.com/NillerMedDild/Enigmatica6/files/6595020/list.txt)
Remove Better End Forge and it goes away.

Remove _only_ Better End Forge, and it does not fix it.
Test with _only_ Better End Forge, and cannot reproduce it.

**Comment by MuteTiefling** [comment]
[list.txt](https://github.com/NillerMedDild/Enigmatica6/files/6595295/list.txt)

Narrowed it down to this list. 

Issue goes away if I drop Better End Forge or drop the S mods. Can pick it up again tomorrow and try to narrow it further.

**Comment by Erysch** [comment]
Well, finding multi mod issued is a nightmare, I know this. Would it be possible to add a similiar or the same recipe to fix this?

**Comment by MuteTiefling** [comment]
Seems to be a conflict between BetterEnd Forge and Supplementaries. 

Can't reproduce with one or the other, but can reproduce with only those two mods installed.

**Comment by MuteTiefling** [comment]
Reported to both mod authors:
https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/84
https://github.com/Beethoven92/BetterEndForge/issues/135

**Comment by NillerMedDild** [comment]
Damn, good work!!

**Comment by MuteTiefling** [comment]
Supplementaries has fixed this it seems.

**Comment by NillerMedDild** [comment]
Awesome! I didn't see it in the changelog though.

**Comment by Erysch** [comment]
Hats up!
