### ISSUE TITLE
Mining gadget with addon fortune III only returns flint from gravel 

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#228]
For info :)
That issue is present in Enig 6 and also if you make an instance with just mining gadget.
https://github.com/Direwolf20-MC/MiningGadgets/issues/107

**Comment by Darkere** [comment]
That's.. Default vanilla behavior?

**Comment by jinkhya** [comment]
*facepalm*
I completly forgot it is, I tend to use silk touch all the time on a shovel on vanilla and forgot this is actually a thing with fortune III. I'll close it. Sorry about this.
