### ISSUE TITLE
Server Crashing Issue

### ISSUE THREAD

**Issue by commanderslimmy** [NillerMedDild/Enigmatica6#2281]
**Modpack version**
Enigmatica 6 ver 0.4.14

**Describe the bug**
Out of memory error when launching server - No idea what caused the issue or why its persisting, sometimes the server will start fine and sometimes it will not but it always gives an out of memory. We're using bisect hosting if that helps wit ha 12 gb RAM server. There are about 15 people who play on the server with 3-6 on at any given. We originally got the error when using the set position wand from ARS Nouveau - Reverting to a backup fixed the issue the first time, but after we reproduced the issue, a rollback didn't fix it, only restarting the server several times did. Since that secondary rollback we have been having the server crash from memory leaks every half hour to an hour and sometimes it is able to be restarted but not every time. Not sure what our course of action should be (whether its new world or not) but I wanted to submit this for you incase you guys could do anything for us, thanks in advanced. It should be noted that I've tried a clean install of the pack with the same world and get the same issue.

**Logs**
(https://github.com/NillerMedDild/Enigmatica6/files/6549938/server100325.-.26.May.2021.18_27_11.zip)
**Screenshots**

**Comment by NillerMedDild** [comment]
The position wand has a memory leak #2271 - have you stopped using it completely? Perhaps even delete it :P

**Comment by commanderslimmy** [comment]
The player doesn't have the wand and hasn't since the reproduction which we only did to confirm that it was the issue and the bug could be reported as I assumed that would be appropriate. If I understand what youre saying to me right now is you believe it is still causing the issue? I'm not sure how thats possible when its been removed from the world altogether. I can look into removing the item from the pack entirely, that doesn't bother me, it just doesn't make sense that it's still causing an issue when it isn't in world.

**Comment by NillerMedDild** [comment]
I just wanted to make sure that it could no longer be causing issues, I highly doubt it's still the cause of your issues. Those logs are... strange to say the least. I'm not sure what to do to be honest.

I recommend you show Bisect support those logs though, they may be able to help.

**Comment by NillerMedDild** [comment]
What did you do with the Position Wand btw? :)
