### ISSUE TITLE
[0.4.12 & 0.4.14] Create mod mekanism schematic crash

### ISSUE THREAD

**Issue by Dissssy** [NillerMedDild/Enigmatica6#2282]
Enigmatica 6 version 0.4.14 (initial crash happened on 0.4.12 but i updated to check if it had been fixed yet)

Hard clientside crash on placement of the "MEK_basic_fission_reactor.nbt" schematic. i was gonna post without doing any more testing but i went through, every single schematic besides the mekanism schematics were fine, but the moment i tried another mekanism schematic (MEK_basic_fusion_reactor.nbt) my game crashed again, same error

its only a clientside crash, my server did not need a restart. the schematic hadnt been placed when i logged back in

https://pastebin.com/s3vSqGwa

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
If you have time, could you perhaps remove Astral Sorcery + ObserverLib and see if there's still an issue?

**Comment by Dissssy** [comment]
I had to also remove naturesstarlight because it had a dependancy for astral sorcery, but I removed all 3 mods and still got the same crash
```
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Should always be able to create a chunk!
Exit Code: -1
```

**Comment by NillerMedDild** [comment]
Perfect, thank you - Could you give me the full crash from it please? :)

**Comment by Dissssy** [comment]
here's the crash report for when i didnt have those mods installed :) 
https://pastebin.com/0UPXx6N5
