### ISSUE TITLE
Mega Torch crafting doesn't accept normal diamonds

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2285]
**Modpack version**
0.4.14

**Describe the bug**
The Megatorch can't be crafted with normal diamonds. You need enriched diamonds, diamond blocks or mana diamonds. Vanilla Diamonds aren't accepted somehow even the recipe says "accepts any enigmatica:crafting_material/diamond". So the diamond might not have the said tag yet. Is this a bug?

**Screenshot**
![mega_torch_bug](https://user-images.githubusercontent.com/81813584/119850543-f15fce80-bf0d-11eb-8322-5debe7bdfb09.png)

**Comment by pm065** [comment]
I don't see any reference to an `enigmatica:crafting_materials/diamond` tag anywhere in kubejs/data or kubejs/server_scripts...

**Comment by pm065** [comment]
Oh, wait, I see the Mega Torch recipe in normal/recipes/shaped.js
Weird that I can't find any place where it's defined...

**Comment by NillerMedDild** [comment]
That is intended :)
