### ISSUE TITLE
Crate of Apples Obtained (sorry if already known)

### ISSUE THREAD

**Issue by Edac2002** [NillerMedDild/Enigmatica6#2286]
**Modpack version**
0.4.10
**Describe the bug**
When generating a random RFTools dimension the Crate of Apples can be obtained (in JEI says to report this as a bug) 

Edit: same applies for Beetroot Crate (found in same dimension)

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
N/A
**Screenshots**
![2021-05-27_15 44 43](https://user-images.githubusercontent.com/31592893/119887856-aab8a700-bf02-11eb-827f-7538c3711d05.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, we're aware and it has been fixed in more recent updates of the pack :)
