### ISSUE TITLE
[0.4.14] Immersive Engineering garden gloche not working

### ISSUE THREAD

**Issue by leonbeer** [NillerMedDild/Enigmatica6#2288]
Version 0.4.13

I recently wanted to setup a biodiesel production, but the garden gloches dont seem to work.
They wont show the seeds inside otf the Gloche and will not consume anything.
Not even the flax seeds of immersive engineering itself work.

Screenshots of the Garden gloche setup
![2021-05-28_01 29 53](https://user-images.githubusercontent.com/45829532/119909111-635b0680-bf54-11eb-9cf4-331363cb1dbb.png)
![2021-05-28_01 29 43](https://user-images.githubusercontent.com/45829532/119909115-648c3380-bf54-11eb-91de-cd02c0a57dfb.png)

**Comment by MuteTiefling** [comment]
They're working fine on my end. 

If you check the uses for the cloche, do you see any recipes?

It sounds like your pack didn't install right, as all of these are handled by custom scripts. re-downloading the pack should fix it.

If this is a server, check in single player. It happens frequently that your local pack will be fine, but the server didn't update properly. In which case, uploading the kubejs folder from your local instance to the server should fix it.
