### ISSUE TITLE
Most recent version of Enigmatica 6 (Yes The unobtainable tier 8 and 9 are still a thing)

### ISSUE THREAD

**Issue by Hotgandalf2** [NillerMedDild/Enigmatica6#2289]
![image](https://user-images.githubusercontent.com/84067979/119912390-40a6fe80-bf10-11eb-8126-7e106092fa19.png)

**Comment by Hotgandalf2** [comment]
Is there any news on this fix? I've made a post about this issue awhile and so I updated my mod pack to see if it got patched and to my surprise it didn't. So I'm sitting wondering how to fix this problem.  (Before you ask yes this hammer has both combustion chambers for a max hammer level 7. And no you can only put 2 combustion chambers in the hammer. And yes you can grind the regular hammers to hone a tier, but the netherite hammer can reach tier 7 and I'm not sure if its possible to reach tier 8 let alone 9 for Alf steel ingots as I've never seen evidence of this in game.
![image](https://user-images.githubusercontent.com/84067979/119912815-07bb5980-bf11-11eb-8659-38d771bcf3e2.png)

**Comment by Hotgandalf2** [comment]
This all on a modded server that me and my friends pay on on the recent version so yea that's all the info I got this issue. A lot of other info was presented in my previous thread discussion on the topic.

**Comment by NillerMedDild** [comment]
Your issue is still open and is not marked as fixed nor closes, that means it's not fixed :)
https://github.com/NillerMedDild/Enigmatica6/issues/2143

**Comment by Hotgandalf2** [comment]
Ah I see..
