### ISSUE TITLE
Uraninite Ore through RFtools dimension can't be utilized

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2292]
**Modpack version**
0.4.10

**Describe the bug**
Uraninite Ore created with an RFtools dimension can't be processed: the ore block has no uses, and the Raw Uraninite mined from the block can't be processed (apart from changing it smaller or larger pieces).

![image](https://user-images.githubusercontent.com/12349921/119989312-51667b80-bfc7-11eb-87e1-ae0ded232583.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, Uranitite Ore will no longer be available for RFTools Dimensions in 0.5.0 :)
