### ISSUE TITLE
Remove Red Alloy and replace it with Signalum.

### ISSUE THREAD

**Issue by pm065** [NillerMedDild/Enigmatica6#2295]
Who calls their fancy new modded metal Red Alloy???
Also, 4 redstone + iron is (again) a little unimaginative.
Signalum is much better suited to the job.

**Comment by NillerMedDild** [comment]
> Who calls their fancy new modded metal Red Alloy???

People who want their fancy new mod to sound like Project Red? 😄 

Anywho, good suggestion, I'll think about it.

**Comment by lythowastaken** [comment]
I like the suggestion a lot. People should stop creating for every small thing a new uncommon material.

**Comment by pm065** [comment]
Actually you could even go a step further and remove the gatecrafting station thing. I hate the idea of an entirely new crafting station for a niche use. Plus if I'm not mistaken it prevents automating the components, right?
We have signalum gears, plates, ingots, nuggets and dust, plus redstone dust itself. We could stuff all those things in different configurations and see what happens :smile:

`also it means one less molten metal for me to create`

**Comment by MuteTiefling** [comment]
from what I saw, the gate crafter uses a lot of dupe recipes. making individual unique 3x3 crafts would be a fair amount of work.

**Comment by pm065** [comment]
If it's agreed that it would be a good idea ignoring the amount of effort needed, once I finish the molten metals I'll attempt it. There isn't THAT many:
https://gyazo.com/b55decd643de39ed3bfe91541effbb11
I think the only reason it looks like a lot in the gatecrafter is because it uses the shoddy vanilla trade interface.

**Comment by MuteTiefling** [comment]
Not to discount what's being done here, but one of the recent IE updates just added basically this entire mod into base IE.

It now has a Circuit Table that's used to program circuit boards
![image](https://user-images.githubusercontent.com/9543430/120408671-7dfafa00-c31d-11eb-9e05-be04c55b33d6.png)

Programmed boards can then be inserted into a Logic Unit, which can store up to 10 of them. you can use this to do simple logic such as an AND gate, or you can use it for more complicated circuits... like 2 AND gates that then feed into an OR to send an output if either of the two sets of AND signals is on.

With that considered, More Red seems rather redundant at this point.

**Comment by NillerMedDild** [comment]
Hmm.. What about bundled/colored redstone cables? Does IE have something similar?

**Comment by lythowastaken** [comment]
> Hmm.. What about bundled/colored redstone cables? Does IE have something similar?

IE does it with wires. Where you can choose between 16 colors. Can be used on walls and looks cool :D 
Colored wires does not exists, maybe because there are other wire types but it "bundles" this way:
![image](https://user-images.githubusercontent.com/29131229/120464942-c528cf80-c39d-11eb-96f8-28fdb3e6a631.png)

**Comment by MuteTiefling** [comment]
Yeah, the ie wire just naturally carries all 16 color signals. Which is also how you interact with the logic block. White signal as and red signal in, for instance, can go out as blue depending on how the circuits are programed

**Comment by NillerMedDild** [comment]
Alright, no reason to keep More Red then, yeeting it shall be. Thanks guys 👍

**Comment by pm065** [comment]
yay i don't have to put effort into this anymore :smile:
