### ISSUE TITLE
Mekanism laser crashing server

### ISSUE THREAD

**Issue by TheAnimaDust** [NillerMedDild/Enigmatica6#2297]
**Modpack version**
4.14
**Describe the bug**
Accidentaly a mekanism laser destroyed something in my refined storage network triggering a crash loop in the server.

**Logs**
[crash-2021-05-29_08.46.30-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6564635/crash-2021-05-29_08.46.30-server.txt)

**Comment by NillerMedDild** [comment]
@Darkere This RS crash looks very familiar, you know about this one, right?

**Comment by Darkere** [comment]
Yes. We have like 15 issues on the main tracker for it.... From what I'm hearing RS2 won't be quite as anal about removing blocks while circumventing the security system.

**Comment by NillerMedDild** [comment]
Alright thanks!
I guess you'll just have to remove the erroring block @TheAnimaDust :)

**Comment by TheAnimaDust** [comment]
Thanks for the response, i couldn't remove the block the server Just insta-crash, maybe something in the base was loading without players online, Just returned the server for an early backup.
