### ISSUE TITLE
Sound error.

### ISSUE THREAD

**Issue by Ixy18** [NillerMedDild/Enigmatica6#2298]
**Enigmatica6-0.4.14**

**Describe the bug**
I play the modpack, create the world, and dont have sounds, I only listen to a few

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by Ixy18** [comment]
If someone knows how to fix it, please put it here in comments

**Comment by Darkere** [comment]
Try running F3 + R.
