### ISSUE TITLE
Game difficulty is set to Normal, even if you select Hardcore

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#230]
**Modpack version**
E6 0.2.14

**Issue**
I can confirm this works correctly on Vanilla, and on other Modded instances, but not on E6. If you start a world in Hardcore, the difficulty of the game is set to Normal instead of Hard. Possibly some mod/config somewhere is overriding this.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Singleplayer right?

**Comment by Ridanisaurus** [comment]
Yes. I was on DeadPine's stream when I noticed it, and I confirmed on my E6 Instance that the behavior is the same. When you select Hardcore, it does show that Difficulty is set to Hard in the menu, but when you join the game, the Difficulty is set to Normal.

**Comment by NillerMedDild** [comment]
Which modded instances did you see this working in? Did they have Ma' Essentials? :)

**Comment by Ridanisaurus** [comment]
It did not. Let me try to download that, and test it again.
I tested it on multiple dev instances I have with a variety of different mods.

**Comment by Ridanisaurus** [comment]
Ma Essentials was not the cause. Just tested it. I'll download E6 mods 1 by 1 tomorrow, and keep testing it until I see what caused it. Will let you know as soon as I figure it out.

**Comment by NillerMedDild** [comment]
Might wanna do a binary search instead of 1 by 1, should be faster :) unless there are specific mods that you think could be the cause of course.

**Comment by Ridanisaurus** [comment]
Thanks to Darkere's insight, he narrowed it down to couple mods, and I can confirm that it is caused due to DefaultOptions mod.

**Comment by NillerMedDild** [comment]
Or rather, my configuration of it ^^'
