### ISSUE TITLE
Questing Bugs

### ISSUE THREAD

**Issue by Michi2670** [NillerMedDild/Enigmatica6#2300]
Enigmatica 6 0.4.14 on a server

1) Loot Boxes arent in the game, so if i complete a quest where the reward is a loot box, or in my case a "rear create loot box" i get nothing
2) the iron/gold/diamond chest quest line has as  Tast just a question mark and the text "tag a filter"

![image](https://user-images.githubusercontent.com/47424253/120079396-daf37780-c0b3-11eb-9034-0e60d14de7b0.png)
Iron chest problem

![image](https://user-images.githubusercontent.com/47424253/120079409-ecd51a80-c0b3-11eb-893d-5e03ce4df01a.png)
Create loot box

**Comment by TemperedFool** [comment]
@Michi2670 Sounds like something is broken in your install; I would re-install your instance (after backing your worlds up).
