### ISSUE TITLE
On scaling tetra tools and weapons to the end-game and OP-ness of Mekanism tools

### ISSUE THREAD

**Issue by Larandar** [NillerMedDild/Enigmatica6#2301]
**Description**
Tetra tools and weapons are quite outdated as soon as mid-game, and it does make sense because they are balanced for vanilla. But in a pack where fighting the ender dragon is mid-game, it feels cheap to abandon them so soon.

There are IMO two offenders here for that imbalance:

- Refined Obsidian OP-ness (already discussed in #907 but I will speak of it a little)  
- Magic capacity in tetra is balanced for vanilla enchants, but should be scaled up to account for the new limit set by Apotheosis

**Longer description**

The balance in Tetra is mostly based on exploration (finding an ancient structure, looting the nether for warforged patterns, etc...) which is a good balance mechanism (on par with vanilla and finding ancient debris to get netherite) which by the time you invested the time is not rewarding for long. 

We come here to the first offender: refined obsidian, which is cheaper than diamond and better than netherite: 3 diamond + 6 obsidian + 24 osmium get you a full armor set that is better in every aspect to netherite and can be achieved much much earlier. And same goes for every weapon or tool. 

Add to that that their enchantability is **BETTER THAN GOLD FFS** (`refined_obsidianEnchantability = 40` gold being 25 for armor and 22 for tools) and **4 TIME MORE THAN DIAMOND** ( 10 for diamond, 15 for netherite). 

If refined obsidian took netherite as an ingredient and required a long process to make it I would understand, but if you are quick it's a few hours from start on a pure mekanism run, and with powah for early power, it's even less. In contrast, a Gaia sword does less damage and is much more involved to get, the same goes for Aeternium (which to be fair has better armor than refined obsidian, but the sword is not a simple craft and only .5 more damage than netherite.

And the second part is Apotheosis enchants: the last levels are basically impossible to have on a sword, at best for Alfsteel, or Gaia blade (the best magic capacities with... drumrolls... refined obsidian) you can get Knowledge or the Ages VII but no damage or looting enchant, even with Gild V (for which you would need to explore a lot) maybe you can get KoA VII + Looting V.

But on a regular sword, you can have Sharpness + Damage specific to one mob + looting + KoA and every mob you kill is an XP farm (KoA VII is tradable with villagers, so I don't think it should be seen as edge case)

**Why would you like this added/changed?**

1. Nerfing mekanism tools: all tiers are basically better than vanilla (even bronze as better stat than diamond), for example
  - Refined obsidian should be the same base stats as diamond max, with lowered enchantability to iron level but the added knockback resistance
  - Bronze should be a little better than iron but less durable
2. Boost tetra magic capacity in config: I think a sweet spot would be between `magic_cap_multiplier = 2.0` and `3.0` so that the last Apotheosis enchants require to use Gild V upgrade
3. Boost Botania's materials magic capacity two-fold, they are made for magic use after all

Sorry if it feels a little bit too ranty, but I think 0.5.0 could be a good time the rebalance a little all that :)

EDIT: PS: Don't get me started on paxel, the meta is "just gets a refined obsidian paxel for everything"

**Comment by pm065** [comment]
It would probably be for the best to disable the obsidian/glowstone paxel

`or just remove mek tools what is anyone getting out of it apart from stupid OP stuff`

**Comment by NillerMedDild** [comment]
Putting Fortune VII on an Iron Pickaxe (Tetra-ized) now uses 115 / 210 magic capacity, seems good to me. We may need to tweak it a bit though.
