### ISSUE TITLE
Macaw's Furniture

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#2302]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/macaws-furniture

**Mod description**
Write a short description of the mod here.

**Why would you like the mod added?**

**Screenshots if applicable.**

**Comment by pm065** [comment]
Oh? Why not?

**Comment by NillerMedDild** [comment]
I dislike the hundreds of parts that only vary ever so slightly, I suppose. Not sure why ^^' I'll check out MrCrayfish's Furniture mod next and see how I feel.

**Comment by pm065** [comment]
Makes sense
