### ISSUE TITLE
Change Rock Crystal Ore to Rock Crystal Cluster to prevent it feeling out of place in the midst of non-vanilla stone

### ISSUE THREAD

**Issue by pm065** [NillerMedDild/Enigmatica6#2306]
**Description**
The Rock Crystal ore has no variants, so I propose using a lang file to change it into a Rock Crystal Cluster and update its texture accordingly (so that no stone can be seen on it).

**Why would you like this added/changed?**
To prevent situations like this:
![2021-05-30_12 31 44](https://user-images.githubusercontent.com/81559564/120102469-1d17ca00-c143-11eb-8b64-06d56f6527ca.png)
_that is some strange-looking scoria_

**Comment by NillerMedDild** [comment]
You mean change the model and everything?

**Comment by pm065** [comment]
No, I mean just the texture to remove all traces of stone

**Comment by NillerMedDild** [comment]
And replace it with what? :P

**Comment by pm065** [comment]
In the Enigmatica lang file:
`'block.astralsorcery.rock_crystal_ore': 'Rock Crystal Deposit'` (or Rock Crystal Cluster)

and then edit the texture to look something like this (please excuse my horrifying art):

![New Piskel-1 png (8)](https://user-images.githubusercontent.com/81559564/120120285-254c2580-c194-11eb-99af-22258b7d04e4.png)

This looks horrible, of course, so I don't mean to make it exactly this, but I hope you get what I mean from it (:

**Comment by NillerMedDild** [comment]
I don't think that would help tbh. Making it look like actual Rock Crystals might though.

**Comment by pm065** [comment]
That is... `kind of what I meant all along` :smile:

**Comment by TemperedFool** [comment]
That actually sounds cool; I'm imagining a "geode" 5-9 blocks in diameter, shell of obsidian, with a few rock crystal clusters (would need to be custom models, I'm imagining a model similar to BM daemon will clusters) inside.

**Comment by pm065** [comment]
So, something like this:

![image](https://user-images.githubusercontent.com/81559564/120122891-9b0bbd80-c1a3-11eb-811c-e3728a2011ae.png)

but with a nicer texture?

**Comment by luxidoptera** [comment]
I _think_ what this person is attempting to suggest is making Rock Crystals compatible with Emendatus Enigmatica- i.e., giving them unique ore variants for each rock type. New model would probably be overkill.

**Comment by NillerMedDild** [comment]
> That actually sounds cool; I'm imagining a "geode" 5-9 blocks in diameter, shell of obsidian, with a few rock crystal clusters (would need to be custom models, I'm imagining a model similar to BM daemon will clusters) inside.

We would need a mod for that I'm afraid, can't do it through KJS and EE atm.

The model I think we can do :D 


> So, something like this:
> 
> ![image](https://user-images.githubusercontent.com/81559564/120122891-9b0bbd80-c1a3-11eb-811c-e3728a2011ae.png)
> 
> but with a nicer texture?

Yes!

**Comment by pm065** [comment]
> We would need a mod for that I'm afraid, can't do it through KJS and EE atm.
It may not be possible through Kube, but what about worldgen datapacks? Would that work?

**Comment by NillerMedDild** [comment]
> It may not be possible through Kube, but what about worldgen datapacks? Would that work?

I don't think they give that level of control, no.

I like the model, but the z-fighting concerns me - Please send it though, the dear @Ridanisaurus will have a look at fixing the z-fighting :)

**Comment by Ridanisaurus** [comment]
On it!

**Comment by pm065** [comment]
> I like the model, but the z-fighting concerns me - Please send it though, the dear @Ridanisaurus will have a look at fixing the z-fighting :)

stupid github doesn't like jsons:
This file has the rubbish texture, the okay model and the exported json
[Crystal.zip](https://github.com/NillerMedDild/Enigmatica6/files/6582452/Crystal.zip)

**Comment by NillerMedDild** [comment]
We went with a full block after all, because the crystal model had an xray glitch :P

**Comment by Ridanisaurus** [comment]
Indeed. The problem with custom models is that they require custom voxelshapes, which can't be done through assets/data, and therefore weird things like this would occur 
![image](https://user-images.githubusercontent.com/64355028/120442690-30ff3e00-c386-11eb-86bb-3b195131a324.png)

**Comment by pm065** [comment]
> Indeed. The problem with custom models is that they require custom voxelshapes, which can't be done through assets/data, and therefore weird things like this would occur

Makes sense 👍
