### ISSUE TITLE
Alex's Mobs Falconry Hood crashes the client upon use.

### ISSUE THREAD

**Issue by Elliot-Blanchard** [NillerMedDild/Enigmatica6#2307]
Playing on an Enigmatica 6 server, I encountered this crash (repeated it to make sure it was possible to replicate):
[crash-2021-05-30_14.44.05-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6566228/crash-2021-05-30_14.44.05-client.txt)
[crash-2021-05-30_14.55.36-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6566229/crash-2021-05-30_14.55.36-client.txt)
Replication steps:
- Equip a falconry hood on a tamed falcon
- Grab the falcon using a falconry glove
- Punch the air to send the falcon out <- crash occurs at this point

**Comment by pm065** [comment]
It's more helpful for the devs if you paste the log into a paste site, but at least you didn't embed it into the post (:

Anyway, unless I'm reading this wrong (which is likely tbh, I don't have much/any experience in this field) this looks like a conflict between Tetra and Alex's, somehow:

> java.lang.NullPointerException: Unexpected error
> 	**_at se.mickelus.tetra.effect.gui.RevengeGui.update(RevengeGui.java:47) ~[?:3.10.0] {re:classloading}
> 	at se.mickelus.tetra.effect.gui.AbilityOverlays.onRenderOverlay(AbilityOverlays.java:40) ~[?:3.10.0] {re:classloading}_**

**Comment by pm065** [comment]
It's a known issue: https://github.com/mickelus/tetra/issues/422
