### ISSUE TITLE
ResroucefulBees beepedia backspace issue

### ISSUE THREAD

**Issue by IdioticProphet** [NillerMedDild/Enigmatica6#2309]
**Modpack version**
Latest (4.14)

**Describe the bug**
Alright, this one is fun... also hello I'm back to terrorize you with a super ephemeral bug that has a non straight-forward solution :)

So, in the Beepedia item there is a search button, this button is initialized like this inside of [the code](https://github.com/Resourceful-Bees/ResourcefulBees/blob/1.16.5/src/main/java/com/resourcefulbees/resourcefulbees/client/gui/screen/beepedia/BeepediaScreen.java#L150)

`
searchBox = new TextFieldWidget(Minecraft.getInstance().font, x + 10, y + 143, 98, 10, new TranslationTextComponent("gui.resourcefulbees.beepedia.search"));
`

Thats cool and should work, the `TextFieldWidget` is something that minecraft uses for its creative search, so whats the issue? glad you asked.

So you search in the beepedia search bar, it works fine. but then you go to delete your text, by **hold**ing backspace, it only deletes ONE character! this is obviously not intended, as the creative search bar continues to delete characters as long as you hold the backspace, until they are gone.

I have reported this to the ResourcefulBees devs, the only issue is: both Oreo and Dawn cant replicate it!

**What I have Tried**
* Loading into single player, issue remains
* Loading into multiplayer, issue remains
* deleteing all mods *but* resourcefulbees, issue remains

**What the bees devs have done**
Loading into their in-dev big update tm: bug doesnt exist
Loading into the latest version: bug doesnt exist

What I could be trying: Deleting all E6 configs and trying default, ?

So that leads me to this hypothesis that someone with more skill needs to solve: Something with the E6 configs futz's with the search bar, somehow, not sur where or how or why.

**Video**
Here's a video of Oreo failing to replicate the bug

https://user-images.githubusercontent.com/20072862/120115770-dded7700-c14a-11eb-9420-167f4962c63d.mp4

Here's a video of me showing off the bug (I press, hold then tap backspace)
![Bee](https://user-images.githubusercontent.com/20072862/120115655-4b4cd800-c14a-11eb-951a-83546a7f48ca.gif)

**Comment by NillerMedDild** [comment]
Thanks for the report/short story 😄 I'll see what I can do.

**Comment by NillerMedDild** [comment]
I was able to reproduce it on E6 as well, but to be honest this is so minor that I'm not willing to spend a long time on it. I'd rather work on Expert :P

**Comment by IdioticProphet** [comment]
fair enough
