### ISSUE TITLE
Crashing Clients on Server via PneumaticCraft

### ISSUE THREAD

**Issue by SylviaGrim** [NillerMedDild/Enigmatica6#231]
**Modpack version**
2.13

**Issue**
This is sort of a general issue and may be pretty niche, but thought it may be useful to put in. I am new to modded MC and am playing on a server with friends at the moment, and one of them was really getting into PneumaticCraft. There was an issue though, when we were near their base sometimes, or when they used some of the items from PneumaticCraft (The Minigun, the Armor, etc), people's clients would crash. Probably not specific enough but we knew it was PneumaticCraft causing the issue. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Darkere** [comment]
If they are crashing we need crashlogs.
