### ISSUE TITLE
Better textures for a few lil gadgets 

### ISSUE THREAD

**Issue by CletusMAngo** [NillerMedDild/Enigmatica6#2313]
**Description**
Id like to suggest better textures for these items
**Personal shrinking device**
**Magic feather**
**Time in a bottle**

**Why would you like this added/changed?**
Honestly this is kinda more qol than anything and since the morph o tool got a better texture maybe these items can get one aswell :D

**Comment by pm065** [comment]
which personal shrinking device? :smile:

**Comment by NillerMedDild** [comment]
I don't know, I think those textures are all fine tbh. Rid would never get any sleep if we ask him to do stuff like this 😄
