### ISSUE TITLE
Ores are generating in Astral Sorcery structures

### ISSUE THREAD

**Issue by luxidoptera** [NillerMedDild/Enigmatica6#2314]
**Modpack version**
0.4.14

**Describe the bug**
Because the current world gen/Emendatus Enigmatica uses Astral Sorcery's unique marble as opposed to another mod's type, Astral Sorcery structures that use raw marble are having ores generate in them. Oops.

**Screenshots**
![image](https://user-images.githubusercontent.com/15697751/120214467-84488380-c202-11eb-9edf-7a65fa5422ba.png)

**Comment by NillerMedDild** [comment]
Known and intended :) thanks for the report anyhow.
