### ISSUE TITLE
Book o' Enchanting trinket is obtainable but non functional

### ISSUE THREAD

**Issue by SlyCedix** [NillerMedDild/Enigmatica6#2326]
**Modpack version**
0.4.14

**Describe the bug**
The Book o' Enchanting from Lost Trinkets can be obtained randomly, but when it is equipped it does not increase eterna in the apotheosis enchanting table. This is probably not fixable, but the trinket should be disabled if that is the case.

**Screenshots**
![](https://files.catbox.moe/l99lnr.png)
![](https://files.catbox.moe/zvsfvm.png)

**Comment by theboo** [comment]
can confirm it is useless with apo installed... thought we disabled it already lol

**Comment by Katon152021** [comment]
I can second this, I thought it was pretty annoying having that equipped but it not working. Any way we could integrate it with Apotheosis installed?

**Comment by NillerMedDild** [comment]
Possibly, but I think that would be too OP anyway.
