### ISSUE TITLE
Refined Storage Fluid Issues

### ISSUE THREAD

**Issue by MaxFirestorm** [NillerMedDild/Enigmatica6#233]
**Modpack version**
0.2.14

**Issue 1**
A Cooking for Blockheads Sink is hooked up to Refined Storage with an External Storage set to Fluids mode. When any fluid enters the RS system, it puts that fluid into the Sink, effectively voiding it as the Sink will only report Water in its "container". If the External Storage is set to whitelist Water, this is changed and fluids enter the RS system as normal. 

**Issue 2**
When autocrafting with the Industrial Foregoing Dissolution Chamber, RS takes the bucket of fluid required for the craft and puts it into the machine, crafts with it, outputs the proper item (in this case a Speed Addon Tier 2) and then outputs over 64 buckets worth of latex back into the fluid disk drive, completely overfilling my 64k fluid disk.

This is what I get for trying to automate Industrial Foregoing, I guess =P

**Comment by Darkere** [comment]
1: The sink accepts fluids and voids them effectively acting as a fluid trashcan. That's a feature (if you know about it). IIRC it was removed by the dev, and got readded after backlash?

> , outputs the proper item (in this case a Speed Addon Tier 2) and then outputs over 64 buckets worth of latex back into the fluid disk drive,

What? I'm not aware of any fluid dupe bugs. Can you explain further?

**Comment by Darkere** [comment]
Explained on stream. Apparently the crafting task seems to dupe the latex fluid somehow. Will investigate (as it's my code).

**Comment by NillerMedDild** [comment]
Any news on this @Darkere ?

**Comment by Darkere** [comment]
I've not been able to reproduce the issue nor heard of any further reports. 

But since fluid autocrafting was reworked during 1.16.2 I don't think it's going to be an issue anymore.

**Comment by NillerMedDild** [comment]
Sweet, thanks.

**Comment by Snappiestjack** [comment]
> I've not been able to reproduce the issue nor heard of any further reports.
> 
> But since fluid autocrafting was reworked during 1.16.2 I don't think it's going to be an issue anymore.

Just wanted to let you know that I'm playing DW20 1.4.1 and I've encountered this exact same issue. However, whilst gathering data and trying to reproduce it, I was not able to be so using a new system. I was only able to reproduce it using the storage setup I already had in the world, I kept comparing new and old system to see what I had different, the only thing was the side of the CookingForBlockHeads sink I had my external storage attached too, front on new systems, side on the old (duping one), so I changed it and my system now no longer dupes latex. 

Unfortunately changing back does not reproduce the dupe. Maybe the Sink needed updating for some reason, but breaking and placing it again has resolved this for me.

**Comment by Darkere** [comment]
Can you check which RS version you are running? I found and fixed a potential cause in 1.9.10.

**Comment by Snappiestjack** [comment]
> Can you check which RS version you are running? I found and fixed a potential cause in 1.9.10.
I'm running 1.9.11, however after posting I had an idea, following which I can reproduce the issue consistently and in a new world.

Place down a Sink, place down a external storage set to fluid (Do not configure whitelist) insert some fluid into the system (in this case Latex). Latex will be voided as it tries to insert it into the Sink. Configure the external storage on the Sink to whitelist water, insert more Latex, Latex is correctly stored on a disk.

Use latex in autocrafting, (in this case Tiny Dry Rubber) view mass amount of Latex being produced in the Crafting Monitor and cells being filled.

**Comment by Darkere** [comment]
The issue would be present in Enigmatica too. So no worries on that front. Will investigate.

**Comment by Snappiestjack** [comment]
> The issue would be present in Enigmatica too. So no worries on that front. Will investigate.

Shout if you need anything.

**Comment by Darkere** [comment]
Thank you was able to reproduce. It's an issue with Cooking for blockheads sink.
