### ISSUE TITLE
Adapt Undergarden Compat to new Major Update

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#2335]
https://www.curseforge.com/minecraft/mc-mods/the-undergarden/files/3334271

**Comment by MuteTiefling** [comment]
Huh, doesn't seem bad from the changelog. Mostly texture changes.

Need to double check tags on the glass and sediment, I think, and reclassify grongle as a tree in the registries. Will check it out.

**Comment by MuteTiefling** [comment]
Yep, didn't seem too bad  :D new textures are pretty sweet too.
