### ISSUE TITLE
Inventory Tweaks sorting X AE2 crafting terminal

### ISSUE THREAD

**Issue by douyabian** [NillerMedDild/Enigmatica6#234]
E6 0.2.14

Sorting within the crafting terminal includes the 3x3 crafting grid and ignores all sorting rules

Not sure if its an issue with configs or an issue with mod compatibility between the two

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Yikes, that is one annoying issue.

**Comment by NillerMedDild** [comment]
I'm fairly certain it can be fixed by the configs of Inventory Tweaks Renewed, not sure how though. Made this issue asking about it: https://github.com/reo-ar/InvTweaksRenewed/issues/16

**Comment by Darkere** [comment]
Hmm. I can do that. Do we have more inventories that need that treatment?

**Comment by NillerMedDild** [comment]
Ah nice, thanks, I'll check RS.

**Comment by NillerMedDild** [comment]
A'yup Crafting Grid too
