### ISSUE TITLE
[Enigmatics 6 0.4.14 ] Possible Recipe oversight

### ISSUE THREAD

**Issue by ErisyaleLancaster** [NillerMedDild/Enigmatica6#2347]
**Description**
There seems to be a small oversight relating to Recipes. Mekanism and Immersive Engineering both add a way to craft Paper from Sawdust. IE's recipe however is more expensive for less payout (4 Sawdust + 1 Water for 2 Paper) compared to Mekanism's recipe (3 Sawdust for 6 paper)

**Why would you like this added/changed?**
It doesn't seem right to me that IEs recipe should be so easily overshadowed by the one from Mekanism.

**Screenshots if applicable.**
Mekanism: https://media.discordapp.net/attachments/536424254116462614/850345525881995314/unknown.png
IE: https://media.discordapp.net/attachments/536424254116462614/850345533188472832/unknown.png

**Comment by NillerMedDild** [comment]
Thanks for the report, that is indeed an oversight :)

**Comment by MuteTiefling** [comment]
Rebalances Mek's paper recipe to be equal to sugar cane
Boosts IE's paper recipe (requiring water) to be 1.5x output.

![image](https://user-images.githubusercontent.com/9543430/120894630-72425880-c5e7-11eb-8f54-1a0844bd1279.png)
