### ISSUE TITLE
Some clusters not craftable into ores by hand (0.4.8)

### ISSUE THREAD

**Issue by Rika-TH** [NillerMedDild/Enigmatica6#2348]
**0.4.8**

I hear that the system is different now in newer versions but just incase it was missed
Osmium, potassium nitrate, fluorite, and uranium (certus too but eh) clusters cannot be shapeless crafted into ore, and so must be stonecut into their ores

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm fairly certain this is fixed in newer versions, please update :)
