### ISSUE TITLE
AE2 annihilation plane annihilates concrete

### ISSUE THREAD

**Issue by douyabian** [NillerMedDild/Enigmatica6#235]
E6 0.2.14

AE2 annihilation planes destroys concrete blocks for some reason instead of mining them
same for identity annihilation plane

No issues with concrete powder or IE concrete, just all 16 vanilla minecraft colored concrete blocks

(I tend to use formation+annhilation planes to autocraft concrete)

Not sure if problem is with AE2 or other mods interfering with it

**Comment by NillerMedDild** [comment]
Huh, that's an interesting bug, I'll investigate :)

**Comment by NillerMedDild** [comment]
I reported the issue here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4692
