### ISSUE TITLE
AgriCraft

### ISSUE THREAD

**Issue by ModernGamingWorld** [NillerMedDild/Enigmatica6#2350]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/agricraft/files/3338391

**Mod description**
AgriCraft is a mod which aims to bring crop breeding to Minecraft, this includes both improving your existing crops, or cross-breeding to mutate into new species of crops. 

**Why would you like the mod added?**
I would like to see this mod added as it got a lot of new improvements and mod computability from what the older 1.12 version had back in the day

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/75923060/120873969-ffdf6300-c569-11eb-8adf-5fdb398801cc.png)

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by NillerMedDild** [comment]
I can't join worlds with AgriCraft because of a compat issue with Botania, so we won't be adding it :)
