### ISSUE TITLE
Obsidian bee does not have the Wither Trait

### ISSUE THREAD

**Issue by ZuluFoxy** [NillerMedDild/Enigmatica6#2358]
**Modpack version:
0.4.14**

The Obsidian bee does not have the Wither trait

![image](https://user-images.githubusercontent.com/41246872/120896850-a2a7e800-c623-11eb-9191-16658f67a0d0.png)
![image](https://user-images.githubusercontent.com/41246872/120896856-ae93aa00-c623-11eb-8e3f-733202134b99.png)

**Comment by TemperedFool** [comment]
This is a good excuse for me to take a pass on bee traits...

**Comment by NillerMedDild** [comment]
Hmm.. Why should it?

**Comment by ZuluFoxy** [comment]
> Hmm.. Why should it?

I was told it was supposed to have it and to report it

![image](https://user-images.githubusercontent.com/41246872/120903723-1c51cd00-c648-11eb-8652-0c02f2876681.png)

**Comment by NillerMedDild** [comment]
Ah I see 😄 thanks!

**Comment by TemperedFool** [comment]
> Hmm.. Why should it?

My memory was that it used to pollinate wither roses, so needed the wither trait. Someone changed it over to chorus... I could be guilt there.

Either way I'd like to take a pass at traits anyway; needing to segregate the wither and netherite bee away from the other bees is a feel-bad situation I think, so some other bees could use the wither trait. Could probably add some other appropriate traits to various bees while I'm at it.

**Comment by NillerMedDild** [comment]
Fair enough, I made a new issue for you: https://github.com/NillerMedDild/Enigmatica6/issues/2363 so intent is clear :)
