### ISSUE TITLE
Prismarine Shard dupe bug

### ISSUE THREAD

**Issue by ZuluFoxy** [NillerMedDild/Enigmatica6#2359]
**Modpack version:
0.4.14**

**Describe the bug:**
With 4 Prismarine Shards, a stonecutter and a Multiservo Press with a Metal Press Mold: Unpacking you can create infinite Prismarine Shards

**Screenshots:**

Step 1:
![image](https://user-images.githubusercontent.com/41246872/120897184-26ae9f80-c625-11eb-8fb6-77e1ae6f34e6.png)

Step 2:
![image](https://user-images.githubusercontent.com/41246872/120897213-40e87d80-c625-11eb-887d-ac742b908ac9.png)

Step 3:
![image](https://user-images.githubusercontent.com/41246872/120897222-49d94f00-c625-11eb-81a1-3f354bd0fbd3.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
