### ISSUE TITLE
MrCrayfish's Furniture Mod WITH MrCrayfish's More Furniture Mod

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2361]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod
in combination with
https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-more-furniture-mod

**Mod description**
>MrCrayfish's Furniture Mod is all about adding functioning and useful furniture and decorations. You will be able to find furniture for every part of your house, including the kitchen, bedroom, dinning, outdoors, and more! Currently adding over eighty unique blocks, the mod in continuely growing with new updates.

>MrCrayfish's More Furniture Mod is an addon to MrCrayfish's Furniture Mod that introduces support of modded wood types from popular mods. Each wood type will add new variants of Tables, Chairs, Coffee Tables, Cabinets, Bedside Cabinets, Desks, Desk Cabinets, Blinds, Upgraded Fences, Upgraded Gates, Crates, Park Benches, Mail Boxes, Kitchen Counters, Kitchen Drawers and Kitchen Sinks.

**Why would you like the mods added?**
The furniture is looks pretty clean and fits pretty good to the vanilla style. It's also useful and there are some funny things for role playing like player bound mail boxes with item transfer options to other player's mail boxes. Having these could possibly replace other furniture mods. Since the addon came out it might be more interesting than before since it contents many wood variants from other mods in the mod pack like Oh The Biomes You'll Go or Autumnity.

**Screenshots**
![image](https://user-images.githubusercontent.com/81813584/120907857-609f9600-c665-11eb-9a93-debdbd04dcf9.png)
![image](https://user-images.githubusercontent.com/81813584/120907861-70b77580-c665-11eb-9869-ef265397ff5f.png)
![image](https://user-images.githubusercontent.com/81813584/120907966-68136f00-c666-11eb-82b2-ce9674f95656.png) ![image](https://user-images.githubusercontent.com/81813584/120907959-592cbc80-c666-11eb-979d-250bbff14782.png)

**Comment by NillerMedDild** [comment]
I'll think about it, thanks for the suggestion :)
