### ISSUE TITLE
World crashed, new Overworld generated

### ISSUE THREAD

**Issue by TT10** [NillerMedDild/Enigmatica6#2368]
**Modpack version**
0.4.14

**Describe the bug**
Playing local single player.
I was in the Nether, went back to Overworld using a Nether Portal.
Game froze, "(Not responding"), so after some time I closed game window.
When re launching, a new Overworld was generated.

**Logs**
Not sure what logs are relevant but here are those I think may be relevant, not sure if they match crash time. (Also I have anonymised player name, replaced with "[Player_name]".)

[Logs-crash-20210606T2311_approx.zip](https://github.com/NillerMedDild/Enigmatica6/files/6604990/Logs-crash-20210606T2311_approx.zip)

**Comment by TT10** [comment]
(I think I managed to get back most of the world by selecting files from an old backup and files from latest broken world. Most of the chunk files of my initial world were still there except some overwritten near spawn. I mainly use the old world so that it would use the initial seed. Except for my player inventory I think, yet I consider this very experimental. But I didn't spot anything that would give a hint about the bug).

**Comment by TT10** [comment]
> We use the issue tracker exclusively for bug reports, development and feature requests. However, this issue appears to be a support request. Please use the [support channel on our Discord](https://discord.gg/kZ7RdrD) to get help.

It's actually a bug report...

**Comment by NillerMedDild** [comment]
The only thing we can provide for this is support tbf, the log doesn't have anything useful and this isn't something I can reproduce :(

**Comment by IdioticProphet** [comment]
Well the strange thing has to do with this 
```
[23:09:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Enigmatica20210530T2029]'/minecraft:overworld
[23:09:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Enigmatica20210530T2029]'/minecraft:the_nether
[23:09:14] [Thread-62/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ArrayIndexOutOfBoundsException: 325
[23:09:14] [Thread-62/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.sunekaer.mods.sdrp.discord.discordipc.IPCClient.read(IPCClient.java:492)
[23:09:14] [Thread-62/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.sunekaer.mods.sdrp.discord.discordipc.IPCClient.lambda$startReading$0(IPCClient.java:367)
[23:09:14] [Thread-62/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.sunekaer.mods.sdrp.discord.discordipc.IPCClient$$Lambda$26490/832898523.run(Unknown Source)
[23:09:14] [Thread-62/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)
```

I'm no expert but it seems like it saved and did something weird?

**Comment by IdioticProphet** [comment]
Other than that not really reproducible, sorry for the loss of whatetver you had ://

**Comment by NillerMedDild** [comment]
Ah I missed that, yes that's a bit odd - Reported above ^

**Comment by Darkere** [comment]
That error you got there is just the discord richpresence crashing. This runs completely separate from the main game and should not be able to cause any issues.

**Comment by IdioticProphet** [comment]
> That error you got there is just the discord richpresence crashing. This runs completely separate from the main game and should not be able to cause any issues.

That is true.. my guess is that his game crashed so hard it ever finished saving. But that barely makes sense since minecraft saves pretty much constantly (to my knowledge)

**Comment by TT10** [comment]
Oh ok, I mainly posted in case the logs could help identifying some bug.

> That error you got there is just the discord richpresence crashing. This runs completely separate from the main game and should not be able to cause any issues.

What do you mean by "discord richpresence crashing" ? (does the bug have to do with discord or do you mean this is seen a lot on support discord?  English is not my main language so I may be missing details in this sentence.)

**Comment by IdioticProphet** [comment]
> What do you mean by "discord richpresence crashing" ? (does the bug have to do with discord or do you mean this is seen a lot on support discord? English is not my main language so I may be missing details in this sentence.)

Discord rich presence is a mod in the modpack, when crashing it had a weird issue, it probably isnt what caused the world to reset, but it definitely had a weird error

**Comment by Darkere** [comment]
> That is true.. my guess is that his game crashed so hard it never finished saving. But that barely makes sense since minecraft saves pretty much constantly (to my knowledge)

Minecraft saves every 5 min. But it does not keep the old version while saving. So if you crash while the game is saving corruption will occur. 

The "weird" error is the mod trying to update its info even though the game has already crashed. Nothing to worry about.
