### ISSUE TITLE
Crash after loading World

### ISSUE THREAD

**Issue by Spiderboy0** [NillerMedDild/Enigmatica6#2375]
**Modpack version**
-36.1.16

**Describe the bug**
-Crash while opening World, Blocks can be seen but closes game after ~1sec
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
-[crash-2021-06-07_19.03.45-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6610844/crash-2021-06-07_19.03.45-server.txt)

**Screenshots**

**Comment by NillerMedDild** [comment]
Thanks for the report. Has this happened more than once? 
It seems to be a conflict between the mod Ding and OptiFine, removing either would most likely fix the issue :)
