### ISSUE TITLE
Pedestals broken

### ISSUE THREAD

**Issue by JFMillerUSA** [NillerMedDild/Enigmatica6#2376]
4.14

Pedestals broken

Can't add and upgrades to pedestals also all upgrades say need advanced enchantment to unlock

**Comment by IdioticProphet** [comment]
hey... I think you misunderstand what the pedestals are really for and how to use them

To put on an upgrade you put it on your offhand and right click... the advanced enchantment flavor text just means to unlock certain effects in some pedestals you need to enchant it with the advanced enchantment (it means nothing)
