### ISSUE TITLE
No milk block recipe and liquid milk recipe

### ISSUE THREAD

**Issue by Mr-PenguinMan** [NillerMedDild/Enigmatica6#2378]
Done on 0.14.14 which is latest as the time of writing
![image](https://user-images.githubusercontent.com/63758798/121103168-44b70400-c7cd-11eb-9324-7f94eec38de2.png)
Both the block and honeycomb of BooBee and Soupy honeycombs and honeycomb blocks do not have the centrifuge recipe to make liquid milk. In contrast here is the RGBBEE recipe
![image](https://user-images.githubusercontent.com/63758798/121103234-8051ce00-c7cd-11eb-8aec-468c9d9a0361.png)
You can see it produces a liquid, which these two do not. This makes you unable to export the liquid without turning it into bottles. 
Once the liquid is added it will need to be able to be, and this list is not fully complete: Encapsulated, chilled, compacted, filled by spout and may have a block heat property

**Comment by TemperedFool** [comment]
I'm not entirely sure we DON'T want to correct this, but we definitely were aware that there's no liquid milk (thus preventing processing without bottles). There are a few bees that require bottles for processing (ender comes to mind), so needing to automate bottle supply isn't unique to them.

**Comment by NillerMedDild** [comment]
Now that we can make custom fluids, I think fixing this is feasable :)
