### ISSUE TITLE
Allow colored honey blocks in tier 4 beehive recipe

### ISSUE THREAD

**Issue by ItsAMemeMario** [NillerMedDild/Enigmatica6#2380]
Tier 4 beehive's recipe calls for only vanilla honey blocks which is a bit of an oversight by the mod author in my opinion. Allowing RB honey block variants to be used in this recipe will remove the need to farm vanilla bees and give us more reason to craft honey into blocks.

**Comment by TemperedFool** [comment]
Oh don't blame Epic and the RB team, this is an oversight on my part. Easy fix, will PR it this morning.
