### ISSUE TITLE
Shrinking device makes x-ray possible

### ISSUE THREAD

**Issue by aqpoyo** [NillerMedDild/Enigmatica6#2387]
**Modpack version**
0,4,14

**Describe the bug**
When you shrink yourself and you push yourself into a block you have x-ray and you can see the caves in front of you.

**Screenshots**
![2021-06-09_21 35 10](https://user-images.githubusercontent.com/81689755/121418183-fccde380-c96a-11eb-87c5-f8406c8eb19c.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, I've relayed it :)
