### ISSUE TITLE
Wireless grid (refined storage

### ISSUE THREAD

**Issue by Toonlink264** [NillerMedDild/Enigmatica6#2390]
**Description**
could we add the wireless grids from refined as curios? 

**Why would you like this added/changed?**
they have keybinds and get annoying just sitting in the inventory

**Screenshots if applicable.**

**Comment by NillerMedDild** [comment]
I'm afraid we can't implement that, I suggest requesting this on the Refined Storage issue tracker :)

I've tried just adding one of the Curio tags to a terminal, and it goes in just fine, but Refined Storage does not detect it when using the keybinding.
![billede](https://user-images.githubusercontent.com/21295394/121742981-e5c0fa00-cb00-11eb-9d8b-8a9276c08129.png)
