### ISSUE TITLE
Trample no more

### ISSUE THREAD

**Issue by Scapulaunit12** [NillerMedDild/Enigmatica6#2393]
https://www.curseforge.com/minecraft/mc-mods/trample-no-more

A mod that adds a couple of quality of life changes when it comes to trampling over crops and harvesting them prematurely. 

I would like this mod added as it adds some nice configurable changes to crop trampling. My favorite being that boots with feather falling prevent farmland from being trampled.

**Comment by MuteTiefling** [comment]
>  My favorite being that boots with feather falling prevent farmland from being trampled.

I'm quite certain something is already doing this. Quark, I think.

**Comment by MuteTiefling** [comment]
Ah, here et go : https://www.curseforge.com/minecraft/mc-mods/trample-stopper

**Comment by DarkAngel22579** [comment]
>>My favorite being that boots with feather falling prevent farmland from being trampled.

>I'm quite certain something is already doing this. Quark, I think. Or one of the farm mods.

Yeah CoFH Core already does this

`#If TRUE, Feather Falling will prevent Farmland from being trampled. This option will work with alternative versions (overrides) of Feather Falling.`
	`"Improved Feather Falling" = true`

**Comment by MuteTiefling** [comment]
Lol, right. So we should probably drop that other one

**Comment by TemperedFool** [comment]
If so we should probably mention the feather falling thing in quests somewhere...

**Comment by MuteTiefling** [comment]
Seems more like a startup tip

**Comment by TemperedFool** [comment]
That'd work too, can add one later.

**Comment by NillerMedDild** [comment]
No, since we already have existing features like that :)
