### ISSUE TITLE
Integrated Proxy

### ISSUE THREAD

**Issue by DraGonFiirE** [NillerMedDild/Enigmatica6#2394]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/integrated-proxy

**Mod description**
 It allows you to redirect the part's target (Integrated Dynamics readers and writers) to another position. 

**Why would you like the mod added?**
Its possible to do truely wireless redstone with the proxy + redstone writer/reader without a receiver on the block you want to write/read from. Plus reading remote NBT data is cool too. Allows for much cleaner builds

**Comment by NillerMedDild** [comment]
Sounds like a solid addition, I'll check it out.

**Comment by TemperedFool** [comment]
Out of curiosity, can we mimic this functionality with Entagled blocks? Either my mimicking the target block or the ID reader/writer

**Comment by NillerMedDild** [comment]
Good question :o

**Comment by RobuxShooters** [comment]
> Out of curiosity, can we mimic this functionality with Entagled blocks? Either my mimicking the target block or the ID reader/writer?

Even if the functionality of the proxy could be imitated using Entangled blocks for blocks (I did not test this), I don't think there's any way to read entities or write to air blocks or drop items at a specific location from a distance / wirelessly.

**Comment by DraGonFiirE** [comment]
> 
> 
> Out of curiosity, can we mimic this functionality with Entagled blocks? Either my mimicking the target block or the ID reader/writer?

No that doesnt work, ID readers cant read blocks mimicked by entangled blocks. never tested it mimicking the readers/writers itself but that wouldnt make a clean/wireless build anyway

**Comment by NillerMedDild** [comment]
I've set it's range to 64 blocks, in a square radius :)
