### ISSUE TITLE
Create Live Schematic

### ISSUE THREAD

**Issue by TheMiCraft** [NillerMedDild/Enigmatica6#2395]
**Modpack version**
0.4.14
**Describe the bug**
When I place a schematic of Create Live the World saves, and the game crashed.

**Logs**
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Should always be able to create a chunk!
Exit-Code: -1

**Comment by NillerMedDild** [comment]
We need your crash report in order to help :)

**Comment by landretk** [comment]
The crash from Mekanism blocks is fixed in the next release

**Comment by TheMiCraft** [comment]
[crash-2021-06-12_11.39.17-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6642265/crash-2021-06-12_11.39.17-client.txt)
[crash-2021-06-12_11.46.56-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6642266/crash-2021-06-12_11.46.56-client.txt)

**Comment by NillerMedDild** [comment]
Thanks - This should be fixed in the next update of Create :)

Duplicate of #2282
