### ISSUE TITLE
Create Pewter

### ISSUE THREAD

**Issue by TheOnlyMann** [NillerMedDild/Enigmatica6#2399]
**Modpack version**
0.4.13
**Describe the bug**
At this version, create mixer uses shapeless crafting of pewter mix and not the mixing recipie of pewter ingots, even when the basin is heated, unless you specifically state that pewter ingot is made
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

https://user-images.githubusercontent.com/82017462/121815968-e8b01c00-ccb3-11eb-8673-173d4562bacd.mp4

**Comment by NillerMedDild** [comment]
Thanks for the well-made report, fixed in-dev :)
