### ISSUE TITLE
Move from JAOPCA to EE

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#2401]
Currently missing, I think:

- [x] ~~Clumps (magic 5x) a lot are missing from lightning crafting~~ My bad, I totally forgot 😄 
- [x] Crystals (from Mek processing)
- [x] Dirty Dust (from Mek processing)
- [x] Shard (from Mek processing)
- [x] Crushed Ores (from Create)
- [x] Fragments (Blood Magic)
- [x] Gravel (Blood Magic)
- [x] Clean Slurry (mek)
- [x] Dirty Slurry (mek)
- [x] ~~Molten Liquids~~ Nothing concrete to do for that one

**Comment by NillerMedDild** [comment]
Mana byproducts are currently listed as Arcane, needs a little bug fix.
![billede](https://user-images.githubusercontent.com/21295394/121821989-d5de1d00-cc9c-11eb-81a5-ffc3aa0aa67f.png)

**Comment by NillerMedDild** [comment]
Alloys don't need processing materials like crystals, shards, slurries - These can and should be removed from:
- Bronze
- Constantan
- Invar
- Signalum
- Lumium
- Enderium
- Steel
- Electrum

**Comment by MuteTiefling** [comment]
Note on magical 5x. My intent was to register new materials with the new EE art assets, so that whole thing will be to redo. it's Expert only, however, so can wait till after 0.5.0.

Also found some missing dusts in EE: 

- cloggrum
- froststeel
- regalium
- utherium
- cobalt
- nebu

**Comment by NillerMedDild** [comment]
Just missing Thallasium Dust now \o/
