### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by bilgehanakn** [NillerMedDild/Enigmatica6#2405]
0.14.4

I can start the game but when i try to join my world it chrashes.

[crash-2021-06-14_08.51.35-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6647261/crash-2021-06-14_08.51.35-client.txt)

**Comment by NillerMedDild** [comment]
Would you mind updating the mod BiomeIdFixer manually and see if that fixes the issue? :)

**Comment by bilgehanakn** [comment]
I think i found the root of the problem. I accidently downloaded some setups in mods folder. I delete them all and replaced BiomeIdFixer with the newest version and still the same crash note.

[crash-2021-06-14_20.55.33-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6650355/crash-2021-06-14_20.55.33-client.txt)

**Comment by NillerMedDild** [comment]
Odd :/ could you try a reinstall perhaps?

**Comment by landretk** [comment]
If this is a new world you made in 0.4.14, you should be safe deleting the Biome id fixer files, `NewWorldBiomeIdFixer.json` in the instance folder and `<world>/biomeidfixer/BiomeIdFixer.json`, but back them up just in case. Or you may be able to fix them manually if it's obvious what the problem is in the file.

Probably one of the files somehow got corrupted, or interrupted while writing a file.

**Comment by bilgehanakn** [comment]
My world was made in 0.3.4 so it's not a new world.I deleted modpack and reinstall for Niller's request and it send same crash report. Then I deleted biomeidfixer's files and it worked out.

Goods: I can play now it fixed. I like to play this mp a lot.

Bads: My settings and map markers has been removed beacuse of I deleted pack and reinstall.
But anyway thank you guys a lot it fixed.

**Comment by theboo** [comment]
> Bads: My settings and map markers has been removed beacuse of I deleted pack and reinstall.
> But anyway thank you guys a lot it fixed.

If you have to do this again some time, make sure to bring over the "local" folder and options.txt from the old instance/pack location... That's where the ftb map info(local folder) and ur keybinds(options.txt) are located

**Comment by bilgehanakn** [comment]
oh i didn't know thank you boo
