### ISSUE TITLE
Wisdom V and Ender Dragon bug

### ISSUE THREAD

**Issue by Grant-K** [NillerMedDild/Enigmatica6#241]
**Modpack version**
0.2.14

**Issue**
When killing the Ender Dragon with a wisdom V enchants on any sword the final blow stop all entity's from moving but animations continue (dragons wings keep flapping) when you save quit it wont go past saving world. Replicated 3 times with 2 different swords. All done in single player.

**Logs**
Game doesnt crash so no logs appplicable.

**Comment by Darkere** [comment]
Does this happen to the first dragon kill or dragons that you summoned yourself?

**Comment by Grant-K** [comment]
First Dragon

**Comment by NillerMedDild** [comment]
Relayed here: https://github.com/Maciej916/Ma-Enchants/issues/21
Thanks!

**Comment by Darkere** [comment]
I was actually unable to reproduce this :/

**Comment by NillerMedDild** [comment]
... oh

**Comment by Darkere** [comment]
@Grant-K anything else on the sword?

**Comment by Grant-K** [comment]
Yes

**Comment by Grant-K** [comment]
Sword had Sharpness V Sweeping Edge III Mending Faster attack V Lifesteal Wisdom V and timless
Bow which i used to get the dragon low had Power V Infinity Quick Draw III true Shot and timless
Dragon was fought in creative mode

**Comment by Darkere** [comment]
Ah. We still don't have true shot disabled?

**Comment by NillerMedDild** [comment]
We do have true shot disabled :s

**Comment by NillerMedDild** [comment]
You will need to edit a server config to fix the issue: the file is `ma-enchants-server.toml`, you need to set 

[true_shot]
	enable = true

to

[true_shot]
	enable = false

**Comment by Grant-K** [comment]
is true shot the reason for the issue?

**Comment by NillerMedDild** [comment]
This is my fault for not using server config updater on the file, but this issue will be "fixed" once we move to 1.16.2

**Comment by NillerMedDild** [comment]
Yes True Shot is the cause.

**Comment by Grant-K** [comment]
Weird considering the final blow was always with the sword

**Comment by Darkere** [comment]
Arrows get "stuck" outside of loaded chunks and cause the game to freeze forever. It is most likely unrelated to you killing the dragon. 

If you can reproduce in a fresh world without true shot we need to reconsider.
