### ISSUE TITLE
Crash On New World Dev 

### ISSUE THREAD

**Issue by Master2Mind88** [NillerMedDild/Enigmatica6#2414]
**Modpack version**
1.16 Dev 5.0
**Describe the bug**
When I click on a new single player the game crash. This is with packmode expert on and off. I created the new instance 1 hour ago. 
**Logs**
https://pastebin.com/N2wTdGgs
**Screenshots**
N/A

**Comment by NillerMedDild** [comment]
Huh, that's odd. Have you added any mods?

**Comment by Master2Mind88** [comment]
I have not added any mods other that citadel-1.7.1-1.16.5.jar since Alex Mobs Needs this mod to run.

**Comment by billyty08** [comment]
I had the same thing-crash on clicking single player- I had to add the citadel mod that was requested by alex's

**Comment by NillerMedDild** [comment]
It seems Towers of the Wild has vanished from the dev instance, readding it fixes this issue :)

**Comment by theboo** [comment]
Ahhh yup, terraforged really doesn't like having structures in the preset that aren't there xD
