### ISSUE TITLE
Unused EE Items still showing in JEI

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#2419]
**Modpack version**
E6 0.5.0

**Describe the bug**
A lot of the items added in the latest EE Compat Version which have no recipes (i.e. Crushed Diamond Ore, Fluorite Gravel ..etc.) are still showing in JEI.
Also, I noticed the Crushed Alloys have no recipes. I added them as Create already does the Brass though the Mixing Recipes. Not sure if these are something to be considered. 
I noticed the the Lang entries for those Alloys is cursed, so I'll fix them in the next version.

**Comment by MuteTiefling** [comment]
The following are going to need some smelting/casting love too. 

Need recipes for melting ores, dust, ingots, etc 
Could also use recipes for the alloys like 

Will similarly require casting recipes. 


- emendatusenigmatica:molten_utherium
- emendatusenigmatica:molten_thallasium
- emendatusenigmatica:molten_signalum
- emendatusenigmatica:molten_regalium
- emendatusenigmatica:molten_nebu
- emendatusenigmatica:molten_lumium
- emendatusenigmatica:molten_iesnium
- emendatusenigmatica:molten_froststeel
- emendatusenigmatica:molten_enderium
- emendatusenigmatica:molten_cloggrum
-
- emendatusenigmatica:molten_sulfur
- emendatusenigmatica:molten_redstone
- emendatusenigmatica:molten_quartz
- emendatusenigmatica:molten_potassium_nitrate
- emendatusenigmatica:molten_lapis
- emendatusenigmatica:molten_fluorite
- emendatusenigmatica:molten_dimensional
- emendatusenigmatica:molten_coal
- emendatusenigmatica:molten_cinnabar
- emendatusenigmatica:molten_bitumen
- emendatusenigmatica:molten_arcane
- emendatusenigmatica:molten_apatite
