### ISSUE TITLE
Suggestion: Remove PNC client side configs from the pack

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#242]
Specifically these two: 

- ArmorFeatureStatus.cfg

- PneumaticArmorHUDLayout.cfg

The first is just used by PNC to track what armor features a player has turned on. The second deals with the location of HUD elements. Both get overwritten with each update and neither actually need to be included in the pack.

**Comment by NillerMedDild** [comment]
Good idea, I'll get that done, thanks!
