### ISSUE TITLE
Very powerful computer craft addons

### ISSUE THREAD

**Issue by SirEdvin** [NillerMedDild/Enigmatica6#2423]
- https://www.curseforge.com/minecraft/mc-mods/nbt-peripheral
- https://www.curseforge.com/minecraft/mc-mods/more-red-computercraft-integration 

This mods expand power of computer craft usage. First mod allow to read nbt data from blocks and entities (which can be really cool) and second mod add integration between more red and computer craft to allow multichannel redstone output.

More red integration will allow better control of environment (currently, you can get only 4 control lines from one computer side via ID bit mask on redstone output of computer) and nbt peripheral will allow to receive more information about world and make cool automation

**Comment by SirEdvin** [comment]
I am just curios, if I provide merge request, will it help?)

**Comment by MuteTiefling** [comment]
More red is being removed. And we can already read machine nbt with ID.

**Comment by SirEdvin** [comment]
No, why more red will be removed?) 

And main problem that there is no communication between ID and CC: Tweaked.

But I guess, if more red will be removed there is no meaning of this issue(

**Comment by SirEdvin** [comment]
And just for note, https://www.curseforge.com/minecraft/mc-mods/nbt-peripheral allows to read block state, currently nothing in E6 can do this, as far, as I know ...

**Comment by SirEdvin** [comment]
Also, does it really necessary to remove `Storage for Computer Craft`? I know, that Advanced Peripherals do the same thing, but on 0.4.14 it causes RS storage freezes(

**Comment by SirEdvin** [comment]
And just to provide more justification for https://www.curseforge.com/minecraft/mc-mods/nbt-peripheral 

It actually, allows integration between ComputerCraft and Integrated Dynamics with delayer usage which is ... super useful.

**Comment by MuteTiefling** [comment]
Out of curiosity, what would you do with these that can't be done with other mods?

**Comment by SirEdvin** [comment]
@MuteTiefling 

Main problem that my setup cannot be done with other mods without killing server.

I am working on some RS restock machine 

![Main computer](https://i.imgur.com/vW96BNK.png)

From RS via Computer craft I get information about what item stored inside RS and filter it with items I want. For [example](https://gitlab.com/SirEdvin/darkos/-/blob/master/stored/controlRoom.lua) here is my room configuration.

I can't do this with detectors and ID, because it will need a catastrophically big setup of it. And pure ID will just crash server on big RS setups. I also can limit queries like 1 in 20 seconds. 

But, then I need to enabled production lines for this products (and production lines cannot be converted to `crafting recipes` because they are actually generate items instead of convert it). And with computer craft you can emit redstone only from computer.

So I build redstoneSlave computer and mixup it with ID to achieve output 4 control signals per side (basically, with bit masks, like converting redstone power to 4 bit positions)

![setup](https://i.imgur.com/KadQsVd.png)

More red will help to get rid of complex ID setup and archive 16 output signals per side.

**Comment by SirEdvin** [comment]
Accoring to nbt peripheral, it will allow to collect data to CC and display it in very nice way. Like creating tps graphics (achievable now actually), player lists, and another nice informations.

**Comment by MuteTiefling** [comment]
> Main problem that my setup cannot be done with other mods without killing server.

Looks like a pretty neat setup. I can think of a number of ways to do this without CC or ID that would be quite friendly for the server, but ultimately the decision is in Niller's hands. Making your case in a detailed way like this will certainly help with the decision, however. 

If I'm understanding, however, the only real difference for you in this setup would be that it would be more compact, no? You've already got it working, you'd just be able to condense the redstone signals down right?

**Comment by SirEdvin** [comment]
> Looks like a pretty neat setup. I can think of a number of ways to do this without CC or ID that would be quite friendly for the server, but ultimately the decision is in Niller's hands. Making your case in a detailed way like this will certainly help with the decision, however.

On my calculation this will need like 80 detectors (and I still want to expand my setup) which will scan RS storage every update, which is not server friendly. 

In my setup every item has to limits `target` and `excessive`. When item count is lower than `target` it will enable production line fro this product. When item count is bigger than `excessive` product line will wipe this item instead of putting it to storage (this part is useful for tree production to get rid of leaves, for example, but collect sampling. Or to stop collecting seeds when you need only wheat). 

> If I'm understanding, however, the only real difference for you in this setup would be that it would be more compact, no? You've already got it working, you'd just be able to condense the redstone signals down right?

Is would be more compact and more server friendly. Now I have complex ID operators to extract exact bit of information and with more red integration I will have only simple redstone bundled signal. And even call allow me to remove second computer that only exists for redstone firing purpose)

**Comment by NillerMedDild** [comment]
To be honest I think you should just add these to your world. I just don't see it getting used often enough to warrant being added to the pack.

**Comment by SirEdvin** [comment]
Eh, very sad :(
