### ISSUE TITLE
Weird invisible texture bug

### ISSUE THREAD

**Issue by Merthew** [NillerMedDild/Enigmatica6#2428]
**Modpack version**
0.4.14

**Describe the bug**
Hands and mekanism liquids are invisible, as well as a few mekanism blocks.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![image](https://user-images.githubusercontent.com/23420800/122318086-8c840c80-ceec-11eb-8f13-40512e021e46.png)
![image](https://user-images.githubusercontent.com/23420800/122318112-93ab1a80-ceec-11eb-88c7-097aa476701c.png)

I had just copied in a template from building gadgets and was trying to figure out how to use it when these things suddenly disappeared. I can't find a keybind that would do this, and deleting the options file hasn't helped.

**Comment by NillerMedDild** [comment]
Thanks for the report. Are you using Optifine? :)

**Comment by Merthew** [comment]
I am not using optifine, probably should have mentioned that. It fixed itself after 3 separate relogs so I'm unsure what is going on.

**Comment by NillerMedDild** [comment]
That is.. super weird 😄 I'll keep a lookout for the issue.

**Comment by NillerMedDild** [comment]
I still haven't seen this since the original report, has it happened again for you?

**Comment by Merthew** [comment]
I have not, after that time it hasn't happened again though I stopped playing the pack soon after that as I was waiting for the new version to come out. Still haven't played the new version yet XD

**Comment by NillerMedDild** [comment]
Oh alright ^^'
