### ISSUE TITLE
Refined Curios

### ISSUE THREAD

**Issue by starforcraft** [NillerMedDild/Enigmatica6#2429]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/refined-curios

**Mod description**
Adds the compatibility between RS Grids and Curios 

**Why would you like the mod added?**
Really great addon and works fine

**Screenshots if applicable.**
![grafik](https://user-images.githubusercontent.com/60074805/122342028-68ecb080-cf44-11eb-8570-d21f0a355480.png)

**Comment by MrBazlow** [comment]
Functionality has been merged into the main Refined Storage mod via https://github.com/refinedmods/refinedstorage/commit/038661f5eee4141606a58601de265eaf6ddfe236

**Comment by NillerMedDild** [comment]
Refined Curios will not be added after all, then :)
