### ISSUE TITLE
Mod Suggestion:EmbellishCraft

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#243]
EmbellishCraft
A Minecraft 1.16.1 / 1.15.2 / 1.14.4 Forge mod that adds decorative blocks and items.
https://www.curseforge.com/minecraft/mc-mods/embellishcraft

**Comment by NillerMedDild** [comment]
I checked it out on 1.14, but will try it out once more :)

**Comment by TGMax233Michael** [comment]
Now this mod supports Minecraft 1.16.3, can it be added into modpacks?
https://www.curseforge.com/minecraft/mc-mods/embellishcraft/files/3074023

**Comment by TGMax233Michael** [comment]
I found that you are ready to add this mod, so I will turn this suggestion off .
