### ISSUE TITLE
E6 0.5 latest version loading issue

### ISSUE THREAD

**Issue by viper7804** [NillerMedDild/Enigmatica6#2430]
Enigmatica 6 0.5 latest from git

Upon loading up the latest version of the pack from git the mod loader has a problem with the cycle paintings mod saying it is not a .jar file
![not a jar but is a jar](https://user-images.githubusercontent.com/49590726/122359317-134fde00-cf1b-11eb-879f-de8d13c1ca3d.PNG)

**Comment by viper7804** [comment]
It could just be that when I installed the latest version I put it on the latest forge that came out instead of a slightly older one

**Comment by Darkere** [comment]
that is likely just a failed download.
