### ISSUE TITLE
[0.5.0] Obsolete Vanilla Hammer quest reward

### ISSUE THREAD

**Issue by Rottastic** [NillerMedDild/Enigmatica6#2431]
**Modpack version**
0.5.0 (Downloaded via Git. Had to manually add Citadel)

**Describe the bug**
Quest reward from the Tetra tree, for crafting a shield, is set to be a Stone Hammer from Vanilla Hammers.

**Screenshots**
![Desktop Screenshot 2021 06 17 - 02 08 19 60](https://user-images.githubusercontent.com/4677358/122367836-a4ba5280-cf11-11eb-8ea7-921c57856ce0.png)
![Desktop Screenshot 2021 06 17 - 02 05 43 36](https://user-images.githubusercontent.com/4677358/122367841-a71cac80-cf11-11eb-8677-34732f3051be.png)

**Comment by MuteTiefling** [comment]
Thanks for the report!
