### ISSUE TITLE
[0.5.0] Soggyguns 9.0.jar is for an older version of Forge

### ISSUE THREAD

**Issue by Tyler-Jarret** [NillerMedDild/Enigmatica6#2435]
**Modpack version**
0.5.0 (Github pull - with custom CurseForge Profile)

**Describe the bug**
Upon loading into Minecraft, the game warns of "soggyguns 9.0" not being compatiable with the current version of forge.

I did some investigating of the manifest.json that came along with the server setup (as I had to download the client side mods (ReAuth, Ding, Toast Control, Neat, and PackMenu) and it does indeed appear that this mod was called in that manifest.

Edit: It doesn't prevent the game from loading, it just rejects the mod in loading.

**Logs**
See attached latest (too big for pastebin) AND manifest.json

[Enigmatica 0.5.0 - soggyguns - latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6672258/Enigmatica.0.5.0.-.soggyguns.-.latest.log)

[manifest 0.5.0.txt](https://github.com/NillerMedDild/Enigmatica6/files/6672261/manifest.0.5.0.txt)

**Screenshots**
![Screen Shot 2021-06-17 at 1 41 45 PM](https://user-images.githubusercontent.com/81480235/122449083-0079ef80-cf95-11eb-85d0-ca45ab92bece.png)
![Screen Shot 2021-06-17 at 1 51 37 PM](https://user-images.githubusercontent.com/81480235/122449086-01128600-cf95-11eb-9654-0b5f088beb95.png)

**Comment by NillerMedDild** [comment]
Fixed in-dev yesterday iirc :)
