### ISSUE TITLE
[0.5.0] Crash when generating Tetra structure

### ISSUE THREAD

**Issue by CyberNDX** [NillerMedDild/Enigmatica6#2436]
**Modpack version**
0.5.0 take 2

**Describe the bug**
While pre-generating our server world it encountered some kind of Tetra structure which causes a hard crash as soon as it loaded those chunks. I haven't yet tested if manually going into those chunks will have the same effect.

**Logs**
https://pastebin.com/qcRw5bbG

**Comment by NillerMedDild** [comment]
Thanks for the report - What makes you think it's a Tetra structure?

**Comment by CyberNDX** [comment]
Line 28: Caused by: com.terraforged.mod.profiler.watchdog.UncheckedException: Critical error detected whilst generating Feature [tetra:feature] 

So I'm guessing it's either Tetra or something to do with Terraforged.

**Comment by NillerMedDild** [comment]
Ahh I missed that, ty. It also mentions Valhelsia Structures further down. Perhaps this is a general issue with pregen, I'll investigate :)

**Comment by Darkere** [comment]
I'm careful about worldgen now as things are getting a bit complicated in dependencies but I think in this case it should go to vahesia structures or terraforged.

They are expecting to read a world after a dungeondoor is placed but are given what I can only assume is some hackfix from terraforged.
