### ISSUE TITLE
Increase Cobalt spawn rate in The Nether

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#2439]
**Modpack version**
E6 0.5.0

**Describe the bug**
Cobalt is currently extremely rare to spawn. Some number tweaking might be required.

**Comment by NillerMedDild** [comment]
Fixed in https://github.com/NillerMedDild/Enigmatica6/commit/708de9e52602f330750133bced2bf48c8e7a2868 (way down at the bottom)
Might need more tweaking though.
