### ISSUE TITLE
[0.5.0] Beepedia crash

### ISSUE THREAD

**Issue by Rottastic** [NillerMedDild/Enigmatica6#2440]
**Modpack version**
0.5.0

**Describe the bug**
While using the Beepedia to access potential Children of the Zombee, attempting to turn to page 2/3 causes a client crash.

**Logs**
https://pastebin.com/E0DPerC5

**Screenshots**
![image](https://user-images.githubusercontent.com/4677358/122468673-dadaef00-cf70-11eb-8a47-a38765c7788a.png)

**Comment by NillerMedDild** [comment]
Most likely caused by Optifine, I'll relay it though :)

**Comment by surfacelevelspeck** [comment]
I'm also getting this issue, not using Optifine or any other performance mod. Happens with any bee that has multiple children.
