### ISSUE TITLE
No recipe in JEI for volcanic accumulator from ARS

### ISSUE THREAD

**Issue by billyty08** [NillerMedDild/Enigmatica6#2441]
**Modpack version**0.5 alpha

**Describe the bug**
A clear and concise description of what the bug is. I am not sure if it is a big issue but there is no recipe in Jei for the volcanic accumulator. When you use control to look at it in the book the book has the recipe and it actually makes it.  It is just not very intuitive when you are so used to seeing it in Jei and all others recipes I checked from Ars was in there. Clicking on it in the questline didn't bring up recipe is how I noticed it
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by MuteTiefling** [comment]
Can you do a search for `$gold_brass` in JEI and let me know what you see?

**Comment by MuteTiefling** [comment]
nevermind, figured out the cause.

**Comment by anivlys** [comment]
Is this the same issue that also effects Botania's Spark? No recipe in JEI, but has the working recipe.

**Comment by MuteTiefling** [comment]
Yes, it was the same issue.
