### ISSUE TITLE
[Mod Suggestion] TOP Addons

### ISSUE THREAD

**Issue by DarkAngel22579** [NillerMedDild/Enigmatica6#2442]
https://www.curseforge.com/minecraft/mc-mods/top-addons

**Mod description**
Adds extra info to The One Proble.
>Forge:
>- Customizable fluid tank info display on all FluidHandler tile entities

>Vanilla:
>- Beehive and composter progress display
>- Note Block pitch and instrument display
>- Beacon effect display
>- Blast Furnace, Furnace and Smoker progress and fuel display
>- Animal breeding cooldown

>Storage Drawers:
>- Detailed drawer contents display

**Why would you like the mod added?**
Mainly because it:
- Makes the fluid bar look nicer/easier to read
- Shows the exact amount of fluid in a tank
- Prevents the text from extending out of the bar 

**Screenshots if applicable.**
With TOP Addons

![2021-06-17_21 58 56](https://user-images.githubusercontent.com/74909944/122473884-59a84a00-cfba-11eb-8333-8b7377d2038f.png)

Without
![2021-06-17_21 57 57](https://user-images.githubusercontent.com/74909944/122473891-5e6cfe00-cfba-11eb-9bd2-c170b1d4f002.png)

**Comment by NillerMedDild** [comment]
Sounds good to me, will be added in 0.5.1 :)
