### ISSUE TITLE
ItemZoom

### ISSUE THREAD

**Issue by emmanoel1** [NillerMedDild/Enigmatica6#2445]
This mod make me give me intense good look at how good is this modpack please add back

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/itemzoom

**Mod description**
Great for builders looking for the right materials!

**Why would you like the mod added?**
It's sooo good looking for any item zoomed please add back !   or  i can add this mod manually whitout giving me issues??

**Screenshots if applicable.**

![O5l9byo](https://user-images.githubusercontent.com/54756177/122487731-501ae400-cfb2-11eb-872c-4335ad9f8cb7.png)

**Comment by theboo** [comment]
This mod was literally just removed from the pack as most people were just shutting it off, it works client side so u can feel free to install it yourself :D

**Comment by emmanoel1** [comment]
ok thanks
