### ISSUE TITLE
Reduce frequency of Tinker's Construct floating islands

### ISSUE THREAD

**Issue by surfacelevelspeck** [NillerMedDild/Enigmatica6#2446]
**Description**
The frequency of Tinker's Construct flying islands (sky slime, earth slime, clay, etc.) should be reduced or disabled.

**Why would you like this added/changed?**
It feels like there's quite a large number of floating slime and clay islands from Tinker's Construct, enough that in most of the worlds I'm generating I have at least 2 or 3 visible from where I'm standing. They don't really add much to the experience, either.

**Comment by Thiana** [comment]
I've yet to see any tinker island on this seed so perhaps wait for more feedback on this issue to see which of us is having the normal experience?

**Comment by theboo** [comment]
was this world generated on a dev build or not using a terraforged world type? The islands were insanely common by default but we toned them down quite a bit using the terraforged preset.

**Comment by Thiana** [comment]
They do seem to be fairly common on/over oceans. I'm seeing them every 10-15 chunks now that I'm looking for a warm ocean biome. This is with the terraforged preset but using the 0.5 dev up to the cobalt change.

**Comment by surfacelevelspeck** [comment]
This was generated on the 0.5.0 alpha release. Here are the values I had by default:
[worldgen.slime_islands.earth] separation = 25
[worldgen.slime_islands.sky] separation = 30
[worldgen.slime_islands.clay] separation = 100
[worldgen.slime_islands.blood] separation = 13
[worldgen.slime_islands.end] separation = 25

**Comment by hofmannk69** [comment]
I had to travel quite a distance to find my first one and then a quite aways for the second one.  They dont seem very common to me.

**Comment by NillerMedDild** [comment]
I've done pretty extensive testing on this, both during 0.5.0 development and after release, and I think the slime island rates are in a good place to be honest. It takes me a good while to find one.
