### ISSUE TITLE
Mod Suggestion: Builders Crafts & Additions

### ISSUE THREAD

**Issue by Thiana** [NillerMedDild/Enigmatica6#245]
Since Bibliocraft is still on 1.12, `Builders Crafts & Additions (Forge)`  might be a nice alternative. It adds basic furniture like stools, tables, bookshelves, drawers, cabinets, display shelves and some garden type things. 

https://www.curseforge.com/minecraft/mc-mods/buildersaddition/screenshots

Thanks :)

**Comment by NillerMedDild** [comment]
I'll check it out :)

**Comment by NillerMedDild** [comment]
It adds a bunch of pretty good looking blocks and furniture pieces, I will add it. Not sure it's going to stay in the long run though, I'm kinda hoping BlockCarpentry will make customizable furniture.
