### ISSUE TITLE
Glowstone bee in world spawning has no Biome

### ISSUE THREAD

**Issue by billyty08** [NillerMedDild/Enigmatica6#2451]
**Modpack version**0.5.0

**Describe the bug**
A clear and concise description of what the bug is. Looking at info in jei for the glowstone bee says it spawns in crimson gardens, glowstone gardens, or wailing garth all BYG biomes which appear to have been removed from current nether generation and it can only be bred from itself rendering it impossible to get

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by TemperedFool** [comment]
Easy fix; I suppose they can just generally spawn in the nether. Might be worth checking Pigman bees too, and culling BYG nether biomes from the biome dictionary.
