### ISSUE TITLE
[Mod Suggestion] Vampirism & addon

### ISSUE THREAD

**Issue by yagoplx** [NillerMedDild/Enigmatica6#2454]
**CurseForge Link**
a - https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire
b - https://www.curseforge.com/minecraft/mc-mods/vampirism-integrations
c - https://www.curseforge.com/minecraft/mc-mods/vampires-need-umbrellas

**Mod description**
This mod allows players to choose between three factions: **human** (by doing nothing), **vampire** (through hit by the mob or item), **vampire hunter** (through a specialized villager). The last two offer a leveling system with rituals that grant players unique powers. I think you can figure out what it means to be a vampire, which comes with weaknesses and all. Overall it doesn't hit me as a power-creep mod in any way either. It's just a plain fun & interesting twist on gameplay, the leveling is another goal to look up to. It is a configurable mod. Doesn't seem to be heavy either, but it adds a biome.

Now I talk about the optional add-ons that can be included with the mod. I will only speak of these that have also been in MCE since I can vouch for their quality:
* Vampirism Integration (dependency of below mod)
* Vampires Need Umbrellas 

This small addon adds multi-tiered, multicolored wool umbrellas that can protect vampires from direct sunlight and the flowing water of rain. Their limited durability means they have to be replaced once in a while, but they allow the vampire player to go outside at daytime and do the stuff they need to do, at the cost of their off-hand (since it needs to be held, not a bauble). This alone does will cover all of their weaknesses, like fire.

**Why would you like the mod added?**
I became aware of this very cool mod through playing the MC Eternal (MCE) 1.12.2 modpack. However, I want to have a look at a 1.16.x modpack, and due to my great past experiences with E2:E, I went with E6. That said, ever since playing with the aforementioned mod, I think it would be a nice ingredient to mix in with the magic aspect, which is where MCE placed it with quests/rewards for the Vampirism mod by Maxanier, plus the addon Vampires Need Umbrellas.

**Screenshots**
A vampire player with eye overlay but no fang overlay.
![A vampire player has customizable eye and fang overlays.](https://user-images.githubusercontent.com/57966308/122624308-fd0a6500-d075-11eb-8587-925fdf1f6b3f.png)

**Comment by yagoplx** [comment]
Right now I'd still like to see this mod and Diet have some kind of integration so I'll submit issues to both for disabling/tweaking how it works for a vampire player. You can find the issues here:

**Comment by yagoplx** [comment]
You can make camps a little rarer by changing the Enigmatica preset to include:

      "vampirism:hunter_camp": {
        "spacing": 18,
        "separation": 7,
        "salt": 14357719,
        "disabled": false
      }
      
This is just so it doesn't feel too "spammed" with the more spacious terrain of Terraforged. I guess.

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by yagoplx** [comment]
Note: This doesn't use Patchouli, so https://www.curseforge.com/minecraft/mc-mods/guide-api-village-and-pillage/ is required for having the mod put up its content instruction book thing.

**Comment by yagoplx** [comment]
> On a very basic level, this can be accomplished. Ideally, from Vampirism Integration's side. What they would do is call DietCapability.get(player).setActive(false) when the player becomes a vampire to disable the diet tracking. This will keep the button and GUI available, but the values will all be grayed out to indicate that none of them are active.

Since this integration leaves the button there, and the diet button does in fact get plopped on top of the vampire look/skills button (when you are one), we need to edit vampirism-client.toml and change the button offset to 105 from 125:
```     
        	#Force the guiSkillButton to the following x position from the center of the inventory, default value is 125
		#Range: > -2147483648
		overrideGuiSkillButtonX = 105
```

If you hate buttons you can still disable it, it gets replaced by a keybind.

**Comment by yagoplx** [comment]
Vampirism has a negative interaction with the pack's BedBenefits mod.

What happens: if you sleep in a bed while afflicted with Sanguinaire Vampiris, you will lose the effect and not get turned. This doesn't make a lot of sense, and is intended to only be cleared with a milk bucket in the base mod. Beds removing the effect just led me to being confused until I learned this mod existed.

What do: Disable potion effect removal from BedBenefits if Vampirism is present, the healing can be kept.

Fix: Change `config/bedbenefits-common.toml` so that remove-bad-effects and remove-positive-effects are both false:
```
#General settings for the mod.
[general]
	remove-bad-effects = false
	remove-positive-effects = false
	restore-health = true
	#Range: 0.0 ~ 1.7976931348623157E308
	restore-health-amount = 10.0
```

**Comment by yagoplx** [comment]
Help needed :D

In my quest to get this mod into the pack I'd like to unify bloods into the drinkable vampirism blood liquid. So far the only other blood is Tinker's blood, I'd like to replace it with Vampirism's.

Does anybody know how I get into accomplishing this? Thanks.

**Comment by NillerMedDild** [comment]
To be honest I don't think this mod would fit into E6 at all :/ I get that you really like it, and it looks like a cool mod, but it would clash with the other content. 

... I don't want Vampires spawning at night :P

**Comment by Darkere** [comment]
The mod is cool. However I've made the experience in a previous pack that had it that this mod would really benefit to be the focus of the pack. It has a lot of content that unfortunately only interacts with itself.  As a side mod it doesn't really work that well as it's difficult to integrate into progression. 

That's unfortunately not what E6 is about.

**Comment by yagoplx** [comment]
So E6 cannot have side mods? Oof, that's rough

**Comment by yagoplx** [comment]
And even if it could- I'm trying my best to have some integration and configuration ready before adding the mod. Are you sure you cannot reconsider your stances?

**Comment by NillerMedDild** [comment]
I'll have another look, but I don't think it'll change my mind tbh 😕

**Comment by yagoplx** [comment]
Fine. I'm gonna replace this with a PR so that I can do more work on finely integrating the mod into the pack like you would like to see. Having a PR allows me to do a lot of work on a remote branch and actually see how the finished E6+V would look like.

I also benefit from this because I can play with the mod on my local pack \*and* get E6-quality integration, even if nobody else would ever get to.

Don't mind me, I enjoy editing text files and testing the result as much as I enjoy playing the game itself.

**Comment by NillerMedDild** [comment]
> I'll have another look, but I don't think it'll change my mind tbh 😕

I did not change my mind, it's still a no on adding Vampirism, just in case that isn't clear :)

**Comment by yagoplx** [comment]
> > I'll have another look, but I don't think it'll change my mind tbh confused
> 
> I did not change my mind, it's still a no on adding Vampirism, just in case that isn't clear :)

Would be cool if you moved the discussion to the PR. All you need to do is give are your concerns about the mod, and see what has been done so far, and we will see what can be done about your concerns, a smiley is not very helpful here. I believe the mod is a great fit still.
