### ISSUE TITLE
Quests dont work if in /ftbteam

### ISSUE THREAD

**Issue by mawatson115** [NillerMedDild/Enigmatica6#2455]
**Modpack version**
.50 alpha
**Describe the bug**
Quests will not complete if in a team.  Brand new server with new world and files, no edits to files.

Create a new team with /ftbteams party create nameofteam
After you issue this command the quest book no longer functions, if you click the welcome checkmark a toast goes off but it does not turn green or allow you to get reward or move on.  You must delete the team and it works.

Easy to replicate as it happens even if no one is in your team.  You have to leave the team for the checkmark to complete and turn green.  I think it is a bug with /ftbteams mod.

**Comment by Splutty** [comment]
When you create the team and have other people join it, the quest log seems to work (I just took all the rewards for Mek that another team member completed).

I think it only works when you're actually online, though. As for the welcome part, I am unsure when we did that, so that could very well be bugged.

And yes. It's all a bit wonky it seems.

**Comment by mawatson115** [comment]
Well i don't know about it if you are already mid way through the quest book.  I am talking brand new.

If you create a team, have your friend join.  The quests cant be completed and you cant get the rewards until you leave the team, no matter who does it.

**Comment by EPostill** [comment]
The solution for me and my friends was to all join a team, leave the server and reconnect. Everyone except for the person who owns the team will lose all their quests, but that does mean they get the reward again when they complete it.

**Comment by NillerMedDild** [comment]
@MaxNeedsSnacks could you have a look at this when you get time? It's sounding like a desync when joining a team.

**Comment by MaxNeedsSnacks** [comment]
> @MaxNeedsSnacks could you have a look at this when you get time? It's sounding like a desync when joining a team.

Yup, this one's known, but Lat still needs to fix it

**Comment by MaxNeedsSnacks** [comment]
Just pushed a fix, should be out shortly!

**Comment by NillerMedDild** [comment]
All cleared up, great work :D
