### ISSUE TITLE
[0.5.0] Pulverizer Osmium Ingot to Dust Recipe

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#2456]
**Modpack version**
0.5.0

**Describe the bug**
Most of the ingot to dust recipes for the pulverizer accept forge:ingots/type, except for Osmium which is specifically the Mekanism and not Emendatus Enigmatica version (or generic forge:ingot/osmium).e

**Comment by MuteTiefling** [comment]
Ah, yep, forgot to re-implement the gem/ingot crushing scripts when re-writing this. Will have it fixed in no-time
