### ISSUE TITLE
Create Piston "Ghosting" blocks

### ISSUE THREAD

**Issue by marblemastery** [NillerMedDild/Enigmatica6#2458]
**Modpack version**
0.4.14
**Describe the bug**
So when using Create piston on private multiplayer server to push blocks, they seem to move at first, but as soon as they reach their designated place, they dissapear, losing their hitboxes and everything, yet you aren't able to pass through them. When I leave and join the server again, blocks magically appear back. When I move them again, they seem to come back, but as soon as they stop they become ghosted again.

**Logs**
Attached.

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6680799/latest.log)

**Screenshots**
Attached.

https://user-images.githubusercontent.com/21339733/122644777-3cd55900-d117-11eb-8feb-cb2114a25a2d.mp4

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by marblemastery** [comment]
UPDATE: I found the issue. This seems to do with Quark. 

I tested other mods' blocks, and it turns out only Quark blocks dissapear. I tested multiple - slate, marble, mossy cobblestone bricks, and all of them dissapear, whereas blocks from other mods just simply work.

**Comment by NillerMedDild** [comment]
Alright, this is the same issue as #2146 then, thanks :)
