### ISSUE TITLE
[Suggestion] Remove Neat

### ISSUE THREAD

**Issue by yagoplx** [NillerMedDild/Enigmatica6#2459]
**Description**
Consider removal of the mod by Vazkii, because the mod by Vazkii contains only features that are made redundant with The One Probe. Well, that is unless you like having two health bars on top of your mobs. Thus the removal of the mod by Vazkii is surely neat.

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by DarkAngel22579** [comment]
I'm going to argue against that. TOP only show the health of the mob you're looking at, while Neat shows the health of all mobs in your fov. Neat also shows the exact health, total health, and percentage of health remaining.

**Comment by yagoplx** [comment]
And why do you want to clutter your screen with more health bars? 🤔

There is only one mob whose health I need to see, and that's the one right on the crosshairs. TOP also displays exact health and total health, it just switches between numerical and hearts display depending on HP.

**Comment by yagoplx** [comment]
If people prefer Neat, then can we remove the one probe's display mobs feature in the config? This also solves my complaint of redundancy since Neat is not a bad mod and can also be configured to just show the bar on the mob on the crosshairs.

**Comment by yagoplx** [comment]
Closed because removing neat fully is not the way
