### ISSUE TITLE
[Suggestion] Unremove AmbientSounds3

### ISSUE THREAD

**Issue by yagoplx** [NillerMedDild/Enigmatica6#2460]
**Description**
AmbientSounds3 was removed in 0.5.0

There's nothing that I appreciate more in a pack than some good ambiance for good looking scenarios. If you went this far to make the world look good, make it sound good too. AmbientSounds3 makes the world more alive, and while I like to use it at a low volume, I still use it every time, and it does make a difference.

Doesn't really make any sense to have all these vibrant biomes and realistic mobs when you take away from the auditory experience :o

This also unremoves CreativeCore.

**Comment by theboo** [comment]
ambient sounds is great, and i add it to my instance when i play, but the mod is 73mb... and it can be installed client side just fine

**Comment by yagoplx** [comment]
I understand that E6 is trying to be featureful whilst being lightweight, but as someone with an i3 from 2011 with 8GB of RAM I don't see any performance loss from having this mod on my instance. It's fine.

**Comment by NillerMedDild** [comment]
The issue isn't performance, it's the fact that downloading an additional 73mb can take a very long time if your internet is slow.

**Comment by yagoplx** [comment]
Thanks for the clarification. That makes more sense to me now :)

-------- Mensagem Original --------
Ativo 19 de jun. de 2021 4:13 PM, Niels Pilgaard Grøndahl escreveu:
