### ISSUE TITLE
Mobs have weird names

### ISSUE THREAD

**Issue by Katon152021** [NillerMedDild/Enigmatica6#2462]
**5.0 Version**

**Describe the bug**
I noticed this labeling of a frog and thought I should let ya'll know. Maybe there's more mobs out there with this issue but I haven't found any. 

![2021-06-19_11 34 19](https://user-images.githubusercontent.com/85213540/122652991-64242a00-d107-11eb-8a3a-be56ff714e5a.png)

**Comment by Katon152021** [comment]
Although not a mob, here is another instance where an item is labeled weird. Take a look

![2021-06-19_14 11 48](https://user-images.githubusercontent.com/85213540/122653133-5f13aa80-d108-11eb-856f-2faea56458ac.png)

**Comment by NillerMedDild** [comment]
Known and fixed in-dev, thanks for the report anywho. The item in JEI is not finished yet, and that is why it has no name.

**Comment by Katon152021** [comment]
> Known and fixed in-dev, thanks for the report anywho. The item in JEI is not finished yet, and that is why it has no name.

Thanks! You're awesome, Just thought I'd bring that to your attention as I didn't know you had already identified the issue

**Comment by geezerbahl** [comment]
@NillerMedDild - did you also catch some villagers with messed up names?  If not, I'll screenshot one..

**Comment by NillerMedDild** [comment]
The Computer Scientist?

**Comment by geezerbahl** [comment]
> The Computer Scientist?

Yup... that was the one.  :)

**Comment by NillerMedDild** [comment]
Yup got him as well 😃
