### ISSUE TITLE
Recipe Oversight for String?

### ISSUE THREAD

**Issue by Katon152021** [NillerMedDild/Enigmatica6#2464]
Version 5.0 Alpha

I was looking through the recipes for string and I noticed what may be a recipe oversight regarding Flax from the mod Supplementaries. Refer to screenshots for context. I also included the hemp fiber recipe just for reference. As you can tell, using 1 flax will get you 1 string which is essentially rendering all other recipes in-game worthless for string.

Just food for thought :)

![2021-06-19_16 05 17](https://user-images.githubusercontent.com/85213540/122655517-81adbf80-d118-11eb-9de8-c19a1494f012.png)
![2021-06-19_16 05 19](https://user-images.githubusercontent.com/85213540/122655519-82deec80-d118-11eb-99e2-7c1985381cfe.png)
![2021-06-19_16 05 27](https://user-images.githubusercontent.com/85213540/122655521-84101980-d118-11eb-91db-895b1e64e6c7.png)

**Comment by MuteTiefling** [comment]
Hemp is probably fine like this, to be honest. It has other uses. 
Kenaf might benefit from a boost to match Flax. Would have to test though to see about output rates.

**Comment by NillerMedDild** [comment]
Boosted Kenaf :) Flax and Kenaf are 1:1, Hemp is still 3:1
