### ISSUE TITLE
[mod suggestion] Pipez

### ISSUE THREAD

**Issue by DamienTC** [NillerMedDild/Enigmatica6#2467]
https://www.curseforge.com/minecraft/mc-mods/pipez

This mod adds simple and highly configurable pipes that are designed to create as little lag as possible.

Only extracting pipes have block entities
Pipes don't load unnecessary chunks
Server friendly
Efficient rendering

**Screenshots if applicable.**

**Comment by NillerMedDild** [comment]
This looks like a pretty solid mod, but I don't think we have a real need for it tbh.

**Comment by yagoplx** [comment]
Does E6 already have a performance oriented pipe mod like E2 had Xnet? I remember Xnet really helped me in place of thermal's ducts then to avoid lag. Don't throw this one in the bin just because you already have pipes.

**Comment by theboo** [comment]
yes e6 has xnet

**Comment by yagoplx** [comment]
Thanks, that will do for me
