### ISSUE TITLE
[0.5.0] Soul Shroom

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#2468]
**Modpack version**
0.5.0
**Describe the bug**
With the removal of BYG biomes from the nether there is no apparent way to get a Soul Shroom in new worlds. The Soul Shroom is used by the BooBee as its only "flower".

While the Market from Farming for Blockheads does contain BYG saplings it does not contain the Soul Shroom.

**Comment by MuteTiefling** [comment]
I'm thinking a little crafting recipe might make more sense for these and other BYG resources that are no longer available. Will have a look later to see what can be done.

**Comment by g0urra** [comment]
Soul Shroom seems to be available now to craft (as of 0.5.2) but it's locked long behind Nature's Aura. Any plans to replace Soul Shroom as the BooBee flower, or put in more sources for Soul Shroom?

**Comment by TemperedFool** [comment]
Yeah, Boo & I were talking about it and we've got a plan that matches his preferences. It's still not going to be... straightforward... but possibly less annoying than the Soul Shroom fix. I will say, it IS a bonus/secret bee, not part of bee "progression", so the intent isn't for it to be easy...

**Comment by TemperedFool** [comment]
Alright, hopefully that should do it...

**Comment by TemperedFool** [comment]
Mmm, right, Fixed in Next Release for tracking... sorry about that 😰

**Comment by NillerMedDild** [comment]
I forgive you :P
