### ISSUE TITLE
[Mod Suggestion] XL packets

### ISSUE THREAD

**Issue by Hurricaneforces** [NillerMedDild/Enigmatica6#2474]
**CurseForge Link**

https://www.curseforge.com/minecraft/mc-mods/xl-packets

**Mod description**

Fixes https://bugs.mojang.com/browse/MC-185901 by raising the packet size limit from 2MB to 2GB, so that servers with large datapacks, packets, etc don't kick the client. 
This mod is needed clientside for any connecting clients.

**Why would you like the mod added?**
It could help high Ping player while play on server
**Screenshots if applicable.**

**Comment by Darkere** [comment]
The specific recipe bug is fixed by forge. It does not help with ping. 

There might be other potential benefits, however it is generally a good idea to NOT send packets that are too big. That usually indicates a bug which could if ignored cause problems in different places (lag, datacaps?).

**Comment by yagoplx** [comment]
Hmm, no, this won't help ping, that's literally impossible if you're sending even bigger packets. This mod will be useful though if we ever reach a point where playerdata inflates to the point players can't join servers. Ever heard of book banning? This would solve that, too.

**Comment by NillerMedDild** [comment]
I don't think including this is a good idea, if we ever do need the mod I want the error to display load and clear, so we can look for the culprit 😄
