### ISSUE TITLE
Slight Change to MekaSuit Helmet Quest

### ISSUE THREAD

**Issue by RobuxShooters** [NillerMedDild/Enigmatica6#2475]
**Description**
The bullet point for "Status Effect Protection" should be changed to "Magic Damage and Status Effect Protection".

**Why would you like this added/changed?**
The tooltip of the Inhalation Purification Unit is slightly misleading as it states that it "prevents selected potion effect types" but it also nullifies magic damage. This can be easily tested with a Damage Trap from Dark Utilities. With the unit active, the player takes no damage (damage is nullified), but with the unit disabled, the player will continuously take damage, even with the MekaSuit on.

This also prevents confusion as I've seen some players stating that the MekaSuit does not protect against magic damage.

**Screenshots if applicable.**
N/A

**Comment by MuteTiefling** [comment]
Ah thanks. This wasn't the case when these quests went in.
