### ISSUE TITLE
[Mod Suggestions] BPeripherals

### ISSUE THREAD

**Issue by SirEdvin** [NillerMedDild/Enigmatica6#2476]
https://www.curseforge.com/minecraft/mc-mods/bperipherals

Addon for CC:Tweaked that add cryptographic's, magnet cards and databases. 

Addon provide solid cryptographic for CC (which is very important in SMP), database toolkit and magnets cards, that allow to create economics and payment cards.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion. This would probably only be used by a tiny fraction of our playerbase, and for that reason I do not want to add it.
