### ISSUE TITLE
[0.5.0] Sulphur Ore Does Not Generate Naturally In-World

### ISSUE THREAD

**Issue by RobuxShooters** [NillerMedDild/Enigmatica6#2477]
**Modpack version**
0.5.0

**Describe the bug**
Sulphur ore does not seem to generate naturally in the Overworld and in the Nether. I have not checked for sulphur ore in the End but I expect the Sulphur Springs biome to at least have some sulphur in it.

As a result of this issue, cured rubber from Thermal is gated behind accessing the End (if sulphur generates there) as Mekanism sulphur cannot be used for making cured rubber (sulphur required to be in gem form).

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/16001607/122671903-5d76df00-d1fb-11eb-9cea-b114af19a81b.png)

**Comment by MuteTiefling** [comment]
Intended. You can still get it from processing ore or from mekanism. There are two routes to manufacture it there, one starting from cobble and another starting from wood.
