### ISSUE TITLE
Treated Wood is no longer obtainable by crafting

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#248]
**Modpack version**
E6 0.2.15

**Issue**
Treated Wood is no longer obtainable by crafting, the recipe for Bucket of Creosote Oil with planks all around is not working. The only way to obtain it now is with Villager Trades.

**Logs**
N/A

**Screenshot**
Provided by Darkere.
![image](https://user-images.githubusercontent.com/64355028/92310112-60c21680-efab-11ea-92ac-6570bae3df54.png)

**Comment by Ridanisaurus** [comment]
Scratch that, I forgot to `/reload`. It works after the reload. False alarm

**Comment by Docteh** [comment]
Is the `/reload` mentioned in the instructions? I fired up the pack to check something for a friend, and didn't notice any instructions to `/reload`

**Comment by NillerMedDild** [comment]
It's in the changelog :)
