### ISSUE TITLE
[Issue] [Resourceful Bees] Hellish Zombees can sometimes break your portal

### ISSUE THREAD

**Issue by yagoplx** [NillerMedDild/Enigmatica6#2483]
**Modpack version**
0.5.0

**Describe the bug**
Reporting this here because Resourceful Bees has this message in the issue template:

> If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.

If your Nether Portal ends up spawning somewhere with Hellish Zombees nearby, that have pollen and hives (if you want to reproduce this occourence), you might be surprised to find that your portal has been converted into crying obisidian after some time explorating, and no longer works. This is because these bees convert obsidian to crying obsidian. Fortunately for me only the top 2 blocks were converted and I was able to unscrew it up by using the corner blocks in place, since I had a diamond pickaxe on hand. This occourence still really annoyed me though.

**Screenshots**
https://user-images.githubusercontent.com/57966308/122684959-07943e00-d1df-11eb-860a-e3e2821e110a.mp4

Yeah.

**Comment by NillerMedDild** [comment]
Thanks for the report, fixed in https://github.com/NillerMedDild/Enigmatica6/commit/9015db5bca644f28c069a56addff625ba8176f99 :)
