### ISSUE TITLE
Reduce default spawn rates for Archwood Forest biome

### ISSUE THREAD

**Issue by stylzm** [NillerMedDild/Enigmatica6#2485]
**Description**
Currently, the spawn weight for the Archwood Forest biome in the Terraforged config is set to 7, which leads to the biome spawning relatively frequently. My suggestion would be to lower the spawn rate of the biome to around 3.

**Why would you like this added/changed?**
The Archwood Forest biome (at least in my opinion) doesn't really fit with the look of most other biomes. The similar looking enchanted grove biome only has a spawn rate of 3, and archwood trees spawn in other biomes so there isn't a need to go to the Archwood Forest biome if you are in need of archwood trees. Even if there is a different reason that someone needs to visit the biome, I don't think that it should spawn as frequently as it does. The documentation book for Ars Nouveau even says that the biome is supposed to be rare.

**Comment by NillerMedDild** [comment]
I'm afraid changing the weight now would cause ugly chunk borders between old and new terrain, so it's not really worth it imo. Maybe for the next major update.

**Comment by yagoplx** [comment]
> I'm afraid changing the weight now would cause ugly chunk borders between old and new terrain, so it's not really worth it imo. Maybe for the next major update.

Just to see if changing biome weights would break stuff, I made a Terraforged world, then quit the game. I then changed a bunch of values on config/terraforged/biome_weights.conf and zeroed some, opened up the world and flew a big distance, but couldn't see any kind of chunk border between new gen and old gen, so I can't say I could reproduce this.

**Comment by NillerMedDild** [comment]
Really? I'm fairly certain we've reproduced that issue recently, but I guess it's time for another look 👍

**Comment by yagoplx** [comment]
> Really? I'm fairly certain we've reproduced that issue recently, but I guess it's time for another look +1

You might be thinking about this: https://github.com/NillerMedDild/Enigmatica6/issues/1571#issuecomment-792119717, which was caused by adding a new biome mod.

**Comment by NillerMedDild** [comment]
Yeah you were right 👍 no weird chunk borders from changing the biome weights.
