### ISSUE TITLE
Remove Project: Vibrant Jouneys

### ISSUE THREAD

**Issue by stylzm** [NillerMedDild/Enigmatica6#2486]
**Description**
I feel that the mod Project: Vibrant Journeys should be removed from the modpack.

**Why would you like this added/changed?**
The ground cover (twigs, rocks, fallen leaves, bones) have too many voxels and don't fit too well with the look of the game, and they don't really serve too much purpose. The shelf mushrooms also make it very annoying to chop down trees, as they clutter the inventory and are not very useful. Out of the 8 mobs added, only 1 actually drops items, and 2 of the mobs are single pixel in size, fly around sporadically, and make annoying noises, making them annoying and hard to kill. 3 of the mobs are also added in by other mods but with more function to them.

**Comment by yagoplx** [comment]
Wouldn't mind if this one got the boot tbh.

Not sure what would happen if the biomes it adds get removed from a world along with the mod, but we could at least disable the tree mushrooms. For me the ground decorations are just fine and, I kind of do like them.

Did you mention mobs? Are they spawning in the pack?
They are supposed to be disabled by default in the pack config: 
```
	[Settings."Mob Settings"]


		[Settings."Mob Settings"."Mob Toggles"]
			"Enable Flies" = false
			"Enable Fireflies" = false
			"Enable Starfish" = false
			"Enable Clams" = false
			"Enable Snails" = false
			"Enable Slugs" = false
			"Enable Small Spiders" = false
			"Enable Frogs" = false

```

**Comment by theboo** [comment]
Personally I love PVJ, I think it brings a bunch of life to an otherwise barren ground cover

**Comment by yagoplx** [comment]
Environmental was added on 0.5.0 and has some content overlap with this. I'm noticing that there's like three kinds of cattails in rivers now for example... BYG, environmental, PVJ.

That said if we keep the mod, can we at least disable the tree mushrooms.

**Comment by stylzm** [comment]
All the mobs are disabled in the config but I have seen frogs spawning in world despite this fact

**Comment by Tyler-Jarret** [comment]
This mod was only added around 4.8 (ish). And while the items that you get may not serve a purpose. Using them as decoration is nice as it adds like to the land that you ultimately have to clear to build something. I know when my server was updated and this mod was in. It was very exicting new to most of the player base :P Small details that do no harm. I like the tree mushrooms myself. I'd vote for keeping.

**Comment by CletusMAngo** [comment]
Honestly id also second to keep it seing as the duplicate foliage/items can just be disabled and the foliage adds ambience to the barebones ground. Most of the mobs are already disabled anyways and are meant to be ambient, they dont really need to have an actual use. this suggestion seems a bit nit-picky to me.

**Comment by NillerMedDild** [comment]
The mobs will be removed eventually, if not we can reconsider removing PVJ. At this time, we're gonna keep it. We may disable the Cattails though ^^'

**Comment by Thiana** [comment]
Please don't disable them. The added visual variety from the different cattails is nice. We had a similar discussion a while ago about only keeping a single variant of the duplicated vegetables, the variant cattails are the same thing.

**Comment by MuteTiefling** [comment]
Yeah, the extra cattails aren't really hurting anything. If anything we should just make sure they're tagged and any recipes that use them can use any one of them. Like making Cattail Thatch

**Comment by NillerMedDild** [comment]
Ah right, that makes sense 👍 
Ideas for tag name? `forge:cattail` or under some group?

**Comment by MuteTiefling** [comment]
`forge:cattails` should do

**Comment by theboo** [comment]
I did something similar for beach grass awhile back
.. I used enigmatica:crafting_materials/beach_grass ... Idk if we wanna stay consistent or change the one I used or whatever

**Comment by NillerMedDild** [comment]
I'd like to change `enigmatica:crafting_materials/beach_grass` to `forge:beach_grass` tbh :x
