### ISSUE TITLE
Ars Nouveau questline cannot be completed due to unobtainable Tome of Blood

### ISSUE THREAD

**Issue by Jafner** [NillerMedDild/Enigmatica6#2487]
**Modpack version**
0.5.0

**Describe the bug**
The Ars Nouveau quest, Tome of Blood, requires the version of the Tome of Blood item which cannot be obtained.

**Comment by MuteTiefling** [comment]
Ooh, fancy hadn't noticed they added tiered books. Thanks! All fixed up.
