### ISSUE TITLE
Project Vibrant Journeys frogs spawn despite being disabled in config

### ISSUE THREAD

**Issue by stylzm** [NillerMedDild/Enigmatica6#2488]
**Modpack version**
0.5.0

**Describe the bug**
Frogs from the Project: Vibrant Journeys mod will frequently spawn near rivers in large groups, despite the fact that the config has frog spawning set to be false.

**Screenshots**
![image](https://user-images.githubusercontent.com/46853295/122707835-b18bbe80-d20f-11eb-9fec-39a18d133dad.png)

**Comment by NillerMedDild** [comment]
Thanks for reporting, known issue: https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/issues/145
