### ISSUE TITLE
Modded fluids (besides from Create) cannot be swam in + molten fluids do not damage

### ISSUE THREAD

**Issue by stylzm** [NillerMedDild/Enigmatica6#2489]
**Modpack version**
0.5.0

**Describe the bug**
Any fluid added by a mod (besides Creates honey and chocolate for whatever reason) have the same collision as air, you cannot swim in them, you just fall right through them without an overlay even showing up. Molten metal also does not damage/set the player on fire.

**Screenshots**
![2021-06-20_22 55 58](https://user-images.githubusercontent.com/46853295/122713892-43e58f80-d21b-11eb-9752-af575538c32d.png) Expected result.

![2021-06-20_22 56 07](https://user-images.githubusercontent.com/46853295/122713772-0da81000-d21b-11eb-903f-8182a64995dc.png) No water particles when jumping into fluid, fluid has no collision (not pushing player or anything).

![2021-06-20_22 54 10](https://user-images.githubusercontent.com/46853295/122713619-d46fa000-d21a-11eb-84d7-1d541744b44d.png) Molten Soul Steel not doing any damage nor setting the player on fire in survival mode

**Comment by RobuxShooters** [comment]
From what I've read, only fluids tagged as water push players in-world. This has the side effect of those fluids becoming 'water' and usable in many crafting recipes that require water as an input (for instance, many Pressurized Reaction Chamber recipes accept Create honey and chocolate as an input, even though it's only supposed to accept water as an input). Hence, many mods do not tag their fluids as water (or lava perhaps) for collision physics.

**Comment by MuteTiefling** [comment]
Yep. Known issue that Forge needs to take care of on their end.
