### ISSUE TITLE
Using Fluid transporters with tinkers smeltery there is a loss of fluid

### ISSUE THREAD

**Issue by memyselfandcj** [NillerMedDild/Enigmatica6#2492]
**Modpack version**
0.5.0
**Describe the bug**
When smelting ores in the smeltery and using IFs fluid transporters to automate there is a loss of fluid.... Putting in 10 chunks will get you 19 ingots and then some left over but its never exact. Not sure if its a bug or if there is an actual loss with using them.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![2021-06-21_12 00 06](https://user-images.githubusercontent.com/40968814/122792691-65309500-d288-11eb-95be-50047adcf2e7.png)

**Comment by NillerMedDild** [comment]
Thanks for the report.

I was unable to reproduce this issue - It seems you're casting something in that screenshot though?

**Comment by memyselfandcj** [comment]
So I can put in a bunch of chunks and let them smelt...Casting them using the transporters is netting a loss. Same amount of chunks smelted without using the transporters you get the exact amount.

**Comment by memyselfandcj** [comment]
I am at work right now when I get off will piece together a video of what is happening

**Comment by memyselfandcj** [comment]
https://user-images.githubusercontent.com/40968814/122934528-961ed180-d33d-11eb-95fc-75e7d03aaed5.mp4

Video of what is happening

**Comment by MuteTiefling** [comment]
Yep. Can reproduce this too. Leaving me with about 138 mb after the first ingot casts. I am getting 288 from the smelt, however. So it seems like it's oversending and the excess is getting lost. Incidentally that's 6mb lost, which makes me think it's maybe sending in packets of 10mb (144 for the ingot, fills to 140, then sends 10 more for the last 4 and loses the remainder)
