### ISSUE TITLE
Manuals in Akashic Tome do not have titles

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2494]
**Modpack version**
0.5.0

**Describe the bug**
The manuals showing when using an Akashic Tome do not have titles, just shows which mod it's a manual for. This is the Akashic Tome that's given as a quest reward.

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/122816064-8b7d2180-d2d6-11eb-87a1-0ba0bd622d8b.png)
![image](https://user-images.githubusercontent.com/12349921/122816111-9a63d400-d2d6-11eb-8fb8-532304ea9943.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed.
