### ISSUE TITLE
The Ars Nouveau Crystalizer has no recipe

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica6#2498]
**Modpack version**
0.5.0

**Describe the bug**
The Ars Nouveau Crystalizer has no recipe

**Comment by mouseas** [comment]
The Volcanic Accumulator also has no recipe. I didn't report it earlier because I had assumed both V.A. and Crystalizer had been disabled as OP. Buuuut now that I think about it the V.A. also has a quest tied to it so that should maybe have clued me in that either one or the other was a bug.

**Comment by MuteTiefling** [comment]
> The Volcanic Accumulator also has no recipe. I didn't report it earlier because I had assumed both V.A. and Crystalizer had been disabled as OP. Buuuut now that I think about it the V.A. also has a quest tied to it so that should maybe have clued me in that either one or the other was a bug.

Yep, that's the other ticket linked. All the same root cause

**Comment by mouseas** [comment]
Just noticed, if you follow the recipe in the *Ars Nouveau* guide book for both those items, the recipe works, it just doesn't show up in JEI. @hvdklauw if you want one while waiting for the next update, follow the recipe in the Tattered Notebook.
