### ISSUE TITLE
Teleport not working

### ISSUE THREAD

**Issue by Earendilgrey** [NillerMedDild/Enigmatica6#25]
**Modpack version**
0.2.0

**Issue**
Teleport option not working from map or command
![2020-07-23_21 43 02](https://user-images.githubusercontent.com/7344454/88356691-49e2a000-cd2e-11ea-90b4-310ec6b2efae.png)
![2020-07-23_21 49 34](https://user-images.githubusercontent.com/7344454/88356733-6d0d4f80-cd2e-11ea-8e59-4d0753c09889.png)

**Comment by Darkere** [comment]
Do you have cheats enabled or if you are on a server are you opped with at least op level 2?

**Comment by Earendilgrey** [comment]
Omg, it was the cheats off thing.  I didn't even remember doing that!  Thanks
