### ISSUE TITLE
[0.5.0] Skeleton Bee has no breeding ingredient

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#2500]
**Modpack version**
0.5.0 via CurseForge

**Describe the bug**
The JEI recipe listings for breeding with Skeleton Bees is lacking a material, making it impossible to breed Osmium and Copper bees and therefore also all the many bees which require Osmium and Copper bees.

**Screenshots**
![bonebee_bug](https://user-images.githubusercontent.com/1171633/122969569-06cbeb00-d34a-11eb-8a63-9247a643274d.png)

**Comment by TemperedFool** [comment]
Fixed in dev!
