### ISSUE TITLE
Gear Cast not showing up in JEI on servers

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2503]
**Modpack version**
0.5.0

**Describe the bug**
Gold Gear Cast does not show up in JEI even though it's craftable.

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/123012251-36b6d500-d3c2-11eb-81c0-ceb3c37740dc.png)
![image](https://user-images.githubusercontent.com/12349921/123012234-2ef73080-d3c2-11eb-9d33-5797b4540b1f.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed :)

**Comment by MVethana** [comment]
![image](https://user-images.githubusercontent.com/17278251/123107455-908dbe00-d407-11eb-967a-e2e8b6cafb29.png)

![image](https://user-images.githubusercontent.com/17278251/123108862-c8e1cc00-d408-11eb-9f8e-c857988dee61.png)

Could not reproduce in 0.5.0 master or dev. In both gold gear cast shows in jei and recipe shows aswell.

**Comment by TemperedFool** [comment]
More to the point - this is latest dev, searching JEI for "gear":

![image](https://user-images.githubusercontent.com/13169307/123114244-30017f80-d40d-11eb-96c6-73c4adfc1875.png)

**Comment by NillerMedDild** [comment]
Hmm... Server or singleplayer?

**Comment by g0urra** [comment]
This is on server.

**Comment by NillerMedDild** [comment]
Yep, can be reproduced on a server. No idea what's going on there :P

**Comment by MuteTiefling** [comment]
Probably the same weirdness as the fluid bug with invar not showing on servers
