### ISSUE TITLE
Replace "shift right click" with "crouch right click" in all quests.

### ISSUE THREAD

**Issue by Splutty** [NillerMedDild/Enigmatica6#2504]
**Description**
Replace "shift right click" with "crouch right click" in all quests.

**Why would you like this added/changed?**
For everyone having crouch rebound, the 'shift right click' makes no sense, and might even be confusing.

**Screenshots if applicable.**

**Comment by MuteTiefling** [comment]
Thanks for that, thought they all already were. the convention has been Sneak Right-Click where appropriate. Do note, some Shift references remain where it is actually shift and not tied to the sneak key. For example, requests in Pretty Pipes, or installing energy cells in ender cells.

**Comment by Splutty** [comment]
I think I was actually looking at the Ender Cells at that moment, so you might have already caught them all.. Time for a grep!
