### ISSUE TITLE
Merge Wither Skeleton bones

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2507]
**Description**
Replace source and functionality of Necrotic Bone (Tinker's Construct) with Withered Bone (Architect's Palette), or vice versa.

**Why would you like this added/changed?**
Both items drop from the same mob (Wither Skeleton), however the first one currently only drops when using the Severing modifier (basic modifier on the Cleaver, and can be applied in Tinker's Anvil and Tinker's table). Necrotic Bone is also only used to convert into regular Bone, while Withered Bone has many more functionalities.

The name of the item may have to stay the same, due to the Necrotic Bone parts that currently exists from Tinker's Construct. Withered Bone Block may have to be renamed.

**Comment by MuteTiefling** [comment]
In the interest of not changing Tinker's progression, a tag should probably just be made to allow both to be used for architect's palette without changing how they're used for Tinkers. Can take a look later to see how that'll work out.
