### ISSUE TITLE
FTB Ultimine causing lag

### ISSUE THREAD

**Issue by yagoplx** [NillerMedDild/Enigmatica6#2508]
**Modpack version**
0.5.0

**Describe the bug**
FTB Ultimine is causing me to suffer lag spikes every time I press alt. Moving the camera around of course extends the lagging even further since it has to recalculate the 128 blocks to break. Reducing the amount of maximum blocks resolves this but since my PR was rejected consider finding a solution to this, like a more performant alternative or configuration changes that are less aggressive than what I proposed.

**Comment by MVethana** [comment]
Since this is dependent on hardware and I haven't heard anymore people complain about having an issue with this why not just change this on your ultimine config

 "renderOutline": false

**Comment by Thiana** [comment]
Why not just only press your ultimine key when you have the correct block targeted? Or reduce the number of blocks it scans in your local configuration? This doesn't require a pack level change. If the pack was changed for every _potential_ lag issue it would have no mods at all.

**Comment by yagoplx** [comment]
> Since this is dependent on hardware and I haven't heard anymore people complain about having an issue with this why not just change this on your ultimine config
> 
> "renderOutline": false

Completely fixed my issue \*and* let me keep the cool 128 block tree destroyer feature. Thanks, now we just need to get this in the pack as default.

**Comment by yagoplx** [comment]
> Why not just only press your ultimine key when you have the correct block targeted?  

Still lags once the correct blocks are ultimined.

> This doesn't require a pack level change. If the pack was changed for every potential lag issue it would have no mods at all.

Not a potential issue, it's happened to me and is not far fetched to consider it happening on similar setups. Unlike the forge tweak to always setup terrain off-thread, this change is guaranteed to have a benefit for everyone performance wise.

**Comment by MVethana** [comment]
Not necessarily since I've never had any issues with it on older-ish hardware and prefer to see the outline like I'm sure most people would. Config changes should be for the majority of players.

**Comment by theboo** [comment]
I wouldn't say this change needs to be in the pack by default when the vast majority of players don't seem to have the same issue... If your hardware handles it fine the outlines are great, if someone struggles with it they can change the config as you have, it is a client side config so doesn't affect server play

**Comment by NillerMedDild** [comment]
I'm sorry but I do not think disabling the outline would benefit the majority of players.
