### ISSUE TITLE
Mod suggestion: Guns Without Roses

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#251]
https://www.curseforge.com/minecraft/mc-mods/guns-without-roses

It's a small mod that adds a few ranged weapons that behave like guns in Terraria, with multiple ammos and enchantments. I'm mostly curious to if it plays well and if it's roughly balanced or if it needs changes.

**Comment by NillerMedDild** [comment]
I'll have a look :)

**Comment by NillerMedDild** [comment]
I'm starting to move development to 1.16.2, are you planning to port? :)

**Comment by Lykrast** [comment]
I wanted to wait for forge rb but if you need it I'll try to do it in the coming days.

**Comment by Lykrast** [comment]
The coming days was today : https://www.curseforge.com/minecraft/mc-mods/guns-without-roses/files/3050578

Hope having a 1.16.1 and 1.16.2 version on the cf page won't cause issues with the app or something. Make sure you get the correct older one if you add it to the 1.16.1 version.

**Comment by NillerMedDild** [comment]
That was fast! The app handles it well, as long as the files are marked for the correct versions. 1.16.2 mods cannot be downloaded from a 1.16.1 instance.

**Comment by NillerMedDild** [comment]
I finally tested Guns Without Roses out and it's awesome, it's definitely going in E6
