### ISSUE TITLE
Mekanism enriched tin results in resource loop

### ISSUE THREAD

**Issue by MVethana** [NillerMedDild/Enigmatica6#2510]
**Modpack version**
0.5.0 Dev

**Describe the bug**
There is currently a tin resource loop that can generate infinite tin with FE

1 Tin Ingot -> 1 Enriched Tin (Worth 8 Tin in Metallurgic Infuser) -> Combine with copper in Metallurgic Infuser to create 32 Bronze -> Crush/Pulverize to Bronze Dust -> Centrifugal Separator = 8 Tin and All copper back

Since Enriched Tin isn't used for anything else but making bronze in the infuser and the fact that it results in 8x the value of tin when alloying it should just be removed and force users to use tin dust in the metallurgic infuser instead.

**Comment by MVethana** [comment]
Resolved in #2511

**Comment by NillerMedDild** [comment]
We usually don't close until the fix is available in an update :)
