### ISSUE TITLE
Mod suggestion: Turf

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#252]
https://www.curseforge.com/minecraft/mc-mods/turf

It recently got ported to 1.16.1 (will port to 1.16.2 in the coming days if needed), it's a straightforward "small" decoration mod with dyeable turf (the quark one isn't dyeable). If someone wants to do cool builds with it, it's nice.

Though by default it has the same recipe as the quark turf, so quark configs/recipes need to be changed around to accomodate for that if the mod is added.

**Comment by NillerMedDild** [comment]
I'll consider it, but not likely since we already have the one kind of Turf.

**Comment by NillerMedDild** [comment]
Sorry but nope, Quark Turf is fine :)
