### ISSUE TITLE
Phrasing in Tinker's Anvil description

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2521]
**Description**
Change the description of Tinker's Anvil to "Craftable with almost any **alloyed** metal block."

**Why would you like this added/changed?**
The current description is "Craftable with almost any metal block", which is misleading as the amount of metal blocks that can't be used (24) to make the Anvil is more than those that can (15). Changing it to include "alloyed" would be more accurate.

**Comment by MVethana** [comment]
From Splutty#4917 testing on a clean server with just TC installed these are the materials that did end up working so it looks like its a Tinkers issue and not us

Slimesteel, Tinker's Bronze, Rose Gold, Pig Iron, Queen's Slime, Manyullyn, Hepatizon, Netherite, Bronze, Brass, Electrum, Invar, Constantan, Pewter, Steel

**Comment by KnightMiner** [comment]
That is because those are the materials that are supposed to work. You are free to add more using the tag, but its intentionally only alloys.

**Comment by Splutty** [comment]
Yeah. Small communication error. The actual text is from the modpack, the list of anvils is from 'clean'. Sorry.

**Comment by NillerMedDild** [comment]
Hmm, does it accept all alloys in E6 atm?

**Comment by KnightMiner** [comment]
If not, add the alloy's tag to the item tag `tconstruct:anvil_metal`. Tinkers adds a bunch based on the metals we natively support, but that list was mostly copied from Immersive Engineerings list

**Comment by MuteTiefling** [comment]
Cool, I'll just add to that tag then instead of what I was doing :D

**Comment by Splutty** [comment]
A happy ending after all!
