### ISSUE TITLE
[Mod Suggestion] Better Biome Blend

### ISSUE THREAD

**Issue by yagoplx** [NillerMedDild/Enigmatica6#2522]
Can't find this on the issues or modlist so I assume it's never been brought up.

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/better-biome-blend
https://github.com/FionaTheMortal/Better-Biome-Blend

**Mod description**
Performance mod. Implements faster biome color blending, increasing performance on the client only, especially while moving around and loading chunks. Sodium has a similar optimization.

**Why would you like the mod added?**
speed

**Screenshots if applicable.**
One from curseforge, max blend setting is increased:
![better-biome-blend-maximum](https://user-images.githubusercontent.com/57966308/123315422-1726c600-d502-11eb-99ad-2301cd1dfca0.jpg)

**Comment by yagoplx** [comment]
Mod is missing from 0.5.1 ;/

**Comment by NillerMedDild** [comment]
It's not though :P

**Comment by yagoplx** [comment]
wot
