### ISSUE TITLE
[Mod Suggestion] Get It Together, Drops

### ISSUE THREAD

**Issue by yagoplx** [NillerMedDild/Enigmatica6#2523]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops
https://github.com/bl4ckscor3/GetItTogetherDrops

**Mod description**
Performance mod, but situational. Like clumps (which is already here), but for item drops. Reduces lagginess of explosions and the likes. Needs to be in the server, but might only improve performance for the client. Behavior of this mod is configurable.

Replacing this mod, clumps, and dynview with https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks may be more suitable for a server, but it can conflict with other mods and changes mob spawning behavior. Thus I'm suggesting this one to complement Clumps and Dynview since it's smaller and safer.

**Why would you like the mod added?**
Is tiny, might help someone somewhere sometime

**Comment by NillerMedDild** [comment]
While potentially helpful for performance, it could become very annoying, especially in dungeons with tight spaces and many walls. It could make loot inaccessible in some cases :/

**Comment by yagoplx** [comment]
> While potentially helpful for performance, it could become very annoying, especially in dungeons with tight spaces and many walls. It could make loot inaccessible in some cases :/

The situation you described is unlikely, since by default item entities will only check a 2 block radius to merge (can be changed to 1.0 if paranoid, vanilla is 0.5). Not to mention that, for this to happen you'd need the exact same item on the other side of the 1 block thick wall as well, and the item will need to be stackable.

**Comment by yagoplx** [comment]
Just tested it myself. This changes item behavior in a way that might be confusing to people who don't know about the mod (eg. merging into an item entity beside you), so I no longer think it is a good idea to add this to the pack. 

About what you said, the inaccessible loot probably wouldn't be a problem since the merge radius is only 2 blocks and only applies to identical items that are stackable. So that rare loot you were looking for is very unlikely to phase through the wall.
