### ISSUE TITLE
Double the Output for the Production of D-T Fuel in the Chemical Infuser

### ISSUE THREAD

**Issue by RobuxShooters** [NillerMedDild/Enigmatica6#2525]
**Description**
Currently, the recipe for making D-T fuel is 1 mB of deuterium + 1 mB of tritium to make 1 mB of D-T fuel. The recipe should be changed so that the amount of D-T fuel produced is double, i.e. 1 mB of deuterium + 1 mB of tritium to make 2 mB of D-T fuel.

**Why would you like this added/changed?**
The Mekanism developers have confirmed that this is a bug and have changed the recipe to output 2 mB of D-T fuel instead of 1 mB of D-T fuel. However, the version containing this fix has not been released yet as it is most likely scheduled for v10.1 of Mekanism, so I propose this suggestion while waiting for the new version to be released.

By doubling the output for this pack, all setups for D-T fuel production can be cut in half. This will both improve the FPS and TPS of individual worlds and servers as there need not be so many tile entities like pumps and thermal evaporation plants.

**Comment by MuteTiefling** [comment]
I've been thinking of speeding up some of these machines/processes too so folks don't need such huge processing lines. Mostly as a lag fix. 

Thinking Pumps need a boost in producing heavy water, evap towers should evap faster, and solar neutron activators could probably use a bit of a boost too, though those aren't nearly as bad as the rest.

**Comment by NillerMedDild** [comment]
We did that in E2E too, I think it's a good idea.
