### ISSUE TITLE
Arboreal Extractor not extracting latex from Eucalyptis Tree

### ISSUE THREAD

**Issue by Katon152021** [NillerMedDild/Enigmatica6#2526]
V 0.5

I was trying to get Latex using the Arboreal extractor and I couldn't get it to drain latex no matter where I placed it along the tree. Pictures for reference. It did seem to work with Jungle. 
![2021-06-24_15 57 06](https://user-images.githubusercontent.com/85213540/123332011-979af600-d505-11eb-9fb8-7aa6c65d09e3.png)
![Uploading 2021-06-24_15.56.52.png…]()

**Comment by MuteTiefling** [comment]
It's working fine for me on a tree I planted. That looks like a world-gen tree, which Thermal may not be able to recognize. Does it work for you if you plant a sapling and tap that?

**Comment by Katon152021** [comment]
You are correct. It does work!

**Comment by MuteTiefling** [comment]
Super! Enjoy your new latex farm :D
