### ISSUE TITLE
Change Badlands Terraforged generation rules

### ISSUE THREAD

**Issue by surfacelevelspeck** [NillerMedDild/Enigmatica6#2527]
**Description**
In vanilla, the Badlands biome (and its related biomes) is an extremely varied biome in comparison to others. It's one of the few biomes that has steep walls and canyons with flat plateaus. Terraforged's style of generating terrain is generally to flatten things into perlin hills, which renders every biome to be very same-y. If it's possible, biomes like Badlands, and possibly others, should have their terrain generation altered so they match vanilla's style.

**Why would you like this added/changed?**
Badlands is easily my favourite vanilla biome, it's amazingly fun to build towns in and provides plateaus and canyons that don't really appear in other biomes. I'd love to see an attempt to return them to their natural state!

**Screenshots if applicable.**
Badlands in my current world. These are the only ones I've found, and are very flat with some slopes.
![2021-06-24_16 02 41](https://user-images.githubusercontent.com/17912442/123335980-daab9800-d50a-11eb-8053-5be073459aa7.png)

Badlands as shown in the Minecraft wiki and google image sources
![Badlands](https://user-images.githubusercontent.com/17912442/123336141-10e91780-d50b-11eb-8e1f-c2b2958438ef.png)
![1 16 4_Minecraft_mesa_seed_and_eroded_badlands](https://user-images.githubusercontent.com/17912442/123336263-3d049880-d50b-11eb-83c8-f6ab65dab435.jpg)

**Comment by yagoplx** [comment]
From https://github.com/TerraForged/TerraForged/wiki/Mod:-Biomes

> Due to TerraForged's approach to generating the world's heightmap, Biomes do not contribute height/variance as they do in the Vanilla (and most other 'normal') world generators. As such, modded Biomes may not look as the author intended.
Surface builders, features, ores, structures, carvers are used as normal.

I didn't find a way to override it either. A workaround for this would be playing on a normal type world.

**Comment by NillerMedDild** [comment]
I'm afraid there's nothing we can do about this, it's a one of the tradeoffs when using TF. Choosing default worldgen would be the way to "fix" it :)
