### ISSUE TITLE
BlockCarpentry blocks not rendering

### ISSUE THREAD

**Issue by douyabian** [NillerMedDild/Enigmatica6#253]
Enigmatica 6 - 0.2.15

BlockCarpentry blocks are not rendering once filled in, becomes invisible, only the frame button and frame stairs work
tried with both vanilla and modded blocks

**Comment by Darkere** [comment]
Are you using optifine?

**Comment by douyabian** [comment]
Nope, no optifine installed

**Comment by douyabian** [comment]
might've something to do with his attempt to fix transparency since that was the missing chunk of code in the button and stairs files, but the dev seems to be having his exams so it can't be confirmed when this could be fixed

**Comment by NillerMedDild** [comment]
Damn, I guess this mod isn't ready for modpacks just yet.

**Comment by douyabian** [comment]
So i saw that the author actually ported to 1.16.2 and updated 1.16.1 several hours ago and thought maybe the it isn't a problem with the mod, decided to further investigate

pinpointed the issue to forge-client.toml

setting "experimentalForgeLightPipelineEnabled" to true breaks the rendering of the mod, keeping it false would fix it.

not sure what other mods it would affect if it's kept at false, i assume setting it to true was to fix something else so just letting you know for your action @NillerMedDild

**Comment by NillerMedDild** [comment]
That is very helpful, thank you! Sadly that doesn't fix the server crash :/
I changed it to true to fix Mekanism's Digital Miner appearing dark on the top.
