### ISSUE TITLE
[Worldgen] Investigate BYG + terraforged weird interaction

### ISSUE THREAD

**Issue by yagoplx** [NillerMedDild/Enigmatica6#2530]
**Modpack version**
0.5.0

https://github.com/TerraForged/tracker/issues/103

Seen this one in person while playing with the worldgen. Especially the red rock biomes, they all look quite jarring. You might want to look into the issue (eg. reporting to byg, removing the biomes from the weights file or do nothing) whatever you think is best.

**Comment by NillerMedDild** [comment]
Thanks for the report - We're aware, and okay with it :)
