### ISSUE TITLE
Vanilla mobs not spawning or extremely rare.

### ISSUE THREAD

**Issue by hofmannk69** [NillerMedDild/Enigmatica6#2537]
**Description**
Vanilla mobs not spawning or extremely rare.  

I  have created 4 different worlds using the TerraForged world gen and the Enigmatica preset in pack version 0.5.  I flew around in creative mode (thousands of blocks) and never found a cow, chicken or sheep.  I did find pigs in the villages that have animal pens in them and then only 2 pigs in the pens.  I think Alex's mobs are stopping or really slowing down the spawning of cows, chickens and sheep.  

My suggestion is to have Alex's mobs spawn less allowing the above animals to spawn more.

**Comment by hofmannk69** [comment]
Well, it's not Alex's mobs.  I removed the mod and started a new world, flew around in creative and still found no cows, chickens or sheep.  I am at a loss as to what it could be.

**Comment by NillerMedDild** [comment]
Thanks for the report! Could you try removing the mod Citadel please?

**Comment by yagoplx** [comment]
Ah, yeah, I was wanting to report this as well but i wasn' sure, maybe you wanted to have food scarcity be miserable.

Yep. Vanilla animals are very rare.

This was actually gonna be pretty impactful with the vampirism mod because if you were unlucky i guess you would starve to death a lot, since you cannot use plants for food while searching for animals.

Will look into this issue more on a bit

**Comment by hofmannk69** [comment]
> Thanks for the report! Could you try removing the mod Citadel please?

I am out for the day, will try when I get home tonight.

**Comment by yagoplx** [comment]
> I am out for the day, will try when I get home tonight.

I got you. Let me do this for you.

> Thanks for the report! Could you try removing the mod Citadel please?

Alexsmobs wants Citadel, so it goes out as well. Trying this out without both it and Citadel still didn't solve the very uncommon animals issue.

**Comment by hofmannk69** [comment]
> 
> > I am out for the day, will try when I get home tonight.
> 
> I got you. Let me do this for you.
> 
> > Thanks for the report! Could you try removing the mod Citadel please?
> 
> Alexsmobs wants Citadel, so it goes out as well. Trying this out without both it and Citadel still didn't solve the very uncommon animals issue.
> 

In the worlds I tested on, the pigs and chickens were very uncommon. The cows and sheep were nonexistent. Thanks for testing this for me.

**Comment by g0urra** [comment]
Is this on single player or server? I have found many sheep, pigs, chickens and cows on my world with same presets.

**Comment by yagoplx** [comment]
> Is this on single player or server? I have found many sheep, pigs, chickens and cows on my server world with same presets.

Single player, are you on 0.5.0?

**Comment by g0urra** [comment]
> 
> 
> > Is this on single player or server? I have found many sheep, pigs, chickens and cows on my server world with same presets.
> 
> Single player, are you on 0.5.0?

Server, 0.5.0.

**Comment by yagoplx** [comment]
Good thing I have this two liner as `find-text-in-folder` script: 
```
#!/usr/bin/env bash
for i in $(find "$1" -type f) ; do test=$(cat $i | grep -ai "$2"); [[ "$test" != "" ]] && printf "$i: \n$test \n"; done
```
That way I could just do `find-text-in-folder . spawn > ~/search-results` and read the relevant lines in the configs.
I found that citadel has a config option for bumping up passive mob spawn on chunk generation.

On citadel-common.toml:
```
#Multiplies the count of entities spawned by this number. 0 = no entites added on chunk gen, 2 = twice as many entities added on chunk gen. Useful for many mods that add a lot of creatures, namely animals, to the spawn lists.
#Range: 0.0 ~ 100000.0
chunkGenSpawnModifier = 0.5
```

Changing this option had no effect on how often pig sheep cows spawn however, it just made the packs mobs spawned in too big. But if you like what it does you can set this to 0.8 at maximum to prevent mob spam.

Lowering alexmobs spawn weights, I think it helped a bit but didn't solve the issue as well... I'm out of time to investigate this now so that's all I have

**Comment by hofmannk69** [comment]
> Is this on single player or server? I have found many sheep, pigs, chickens and cows on my server world with same presets.

Single player for me.

**Comment by RobuxShooters** [comment]
I can also confirm this issue and I'm on single player. Alex's Mobs animals seem to spawn quite frequently for me as opposed to vanilla animals, for instance gazelles, elephants, kangaroos, emus, and so on near where I live compared to a herd of sheep around 250 blocks away from where I am currently, with that herd of sheep being the only vanilla animals I've seen so far (making beds immensely difficult to craft on the first night unless you find string and make wool out of it).

**Comment by hofmannk69** [comment]
> I can also confirm this issue and I'm on single player. Alex's Mobs animals seem to spawn quite frequently for me as opposed to vanilla animals, for instance gazelles, elephants, kangaroos, emus, and so on near where I live compared to a herd of sheep around 250 blocks away from where I am currently, with that herd of sheep being the only vanilla animals I've seen so far (making beds immensely difficult to craft on the first night unless you find string and make wool out of it).

Is your world new or updated from a previous version. I ask because I had no problems finding sheep/cows in my world that was updated to v0.5 but in a brand new world I can't find any cows /sheep and only a couple pigs/chickens

**Comment by RobuxShooters** [comment]
> > I can also confirm this issue and I'm on single player. Alex's Mobs animals seem to spawn quite frequently for me as opposed to vanilla animals, for instance gazelles, elephants, kangaroos, emus, and so on near where I live compared to a herd of sheep around 250 blocks away from where I am currently, with that herd of sheep being the only vanilla animals I've seen so far (making beds immensely difficult to craft on the first night unless you find string and make wool out of it).
> 
> Is your world new or updated from a previous version. I ask because I had no problems finding sheep/cows in my world that was updated to v0.5 but in a brand new world I can't find any cows /sheep and only a couple pigs/chickens

I had started a brand new world for version 0.5.0.

**Comment by Katon152021** [comment]
I can attest to this. Last night I spent two hours searching for cows. And it wasn’t until I found like my 15th village that I found 1 cow in a pen

**Comment by NillerMedDild** [comment]
Environmental configs may be the culprit here:

```toml
[entities]
	#Make farm animals spawn in less biomes to allow new mobs to take their place and diversify biome spawns
	"Limit farm animal spawns" = true
	#Make biome variants of mobs like Husks always spawn in place of their original in their biomes
	"Biome variants always spawn" = true

**Comment by yagoplx** [comment]
> Environmental configs may be the culprit here:
> 
> ```toml
> [entities]
> #Make farm animals spawn in less biomes to allow new mobs to take their place and diversify biome spawns
> "Limit farm animal spawns" = true
> #Make biome variants of mobs like Husks always spawn in place of their original in their biomes
> "Biome variants always spawn" = true
> ```

I think you pretty much got it, I'm making a PR for this. Also thinking about nerfing https://github.com/NillerMedDild/Enigmatica6/commit/f88e128a5213318c22b86ffe4bbb7850e0e1ab8b

**Comment by NillerMedDild** [comment]
No thanks on the PR, working on it now :)

Nerfing as in setting it higher?

**Comment by yagoplx** [comment]
yep set it to 0.8

**Comment by NillerMedDild** [comment]
Fine by me 👍

**Comment by yagoplx** [comment]
Can confirm these changes solve the issue, **even on worlds generated on 5.0**.
However you will need to do a little exploration and new chunk gen before you see animals spawning like vanilla once again.

Once that is done however, animal spawns feel just right. That is just great if you need ahem, some blood to suck. Or some cows to subject to industrial style animal cruelty, whatever is your style.

**Comment by yagoplx** [comment]
Now with that out of the way, @NillerMedDild can you look at this option?
```
./projectvibrantjourneys-common.toml: 
			#Bats spawn outside at night
			nightBats = true 
```

Sometimes I'm seeing way too many bats outside, even at day under some canopies, worse at night, is that intentional?

**Comment by hofmannk69** [comment]
You guys are awesome thanks a lot for all the help and support.

**Comment by yagoplx** [comment]
![2021-06-26_15 41 43](https://user-images.githubusercontent.com/57966308/123522666-13777880-d695-11eb-8196-25f0b0ddf57d.png)
Were you eager to see these? Here they are, spawning as normal. Cows and pigs too.

**Comment by yagoplx** [comment]
> ok, yep set it to 0.8

not happy with this one?

**Comment by NillerMedDild** [comment]
I think 0.5 is fine tbh, animals are spawning, and I don't want lag 😄

**Comment by Derekm122** [comment]
How do you guys change to 0.5 for your world I’m so confused

**Comment by Derekm122** [comment]
> Environmental configs may be the culprit here:
> 
> ```toml
> [entities]
> #Make farm animals spawn in less biomes to allow new mobs to take their place and diversify biome spawns
> "Limit farm animal spawns" = true
> #Make biome variants of mobs like Husks always spawn in place of their original in their biomes
> "Biome variants always spawn" = true
> ```

How do you even use this where do I go to put something like this and which one would I write the # or “
