### ISSUE TITLE
Cannot make tetra hammers with most stones

### ISSUE THREAD

**Issue by yagoplx** [NillerMedDild/Enigmatica6#2538]
**Modpack version**
develop branch

**Describe the bug**
Quest book says you just replace the wooden head with any stone type, but the stone found in the world doesn't work, like quark jasper, create scoria, etc. Is this intended? Definitely a little confusing.

Or maybe my local setup has some weirdness going on

**Comment by NillerMedDild** [comment]
Not intended, we have a recipe that should be overriding that, I'll investigate tonight :)
