### ISSUE TITLE
Mod suggestion: Improved Stations 

### ISSUE THREAD

**Issue by Jams52** [NillerMedDild/Enigmatica6#254]
A pretty small mod, it basically adds tinkers style stations. I feel like it'd be a good addition. 

https://www.curseforge.com/minecraft/mc-mods/improved-stations-forge

**Comment by NillerMedDild** [comment]
I don't really see the point of the mod, other than the crafting tables tbh.

**Comment by Shindur** [comment]
Agreed with Niller ^ I've seen some comments saying how the crafting tables don't even hook into the chest inventory like that one mod from 1.15.2 used to.

**Comment by Darkere** [comment]
It kind of makes sense on a skyblock map. But yeah... I think we have IItemStacks crafting station already?

**Comment by NillerMedDild** [comment]
We don't, it crashed servers when I tried adding it, haven't tried since :P
