### ISSUE TITLE
Molten Invar not in JEI search

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2540]
**Modpack version**
0.5.0 Server

**Describe the bug**
Molten Invar can be crafted in Tinker's Construct Smeltery - either by alloying or smelting Invar items - but recipe doesn't show up in JEI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/123513877-fee4b180-d68f-11eb-8442-bd5d48c06ce5.png)

**Comment by MuteTiefling** [comment]
Trying to reproduce this in Dev and I'm seeing Tinker's Invar without issue. We are hiding EE's molten invar, however, but that's intentional since it's extra.

**Comment by NillerMedDild** [comment]
Server only issue perhaps?

**Comment by MuteTiefling** [comment]
Perhaps. I spun up my 0.5.0 instance and it's fine there too.

**Comment by MuteTiefling** [comment]
Updating the dev server, will check it out there

**Comment by MuteTiefling** [comment]
It is indeed server only. Just spun up a server on 0.5.0 and am seeing the same thing...

**Comment by MuteTiefling** [comment]
well, it's not KubeJS scripts at least. Removed everything from Dev and my local instance and I'm still not seeing Tinker's Invar. Only EE's

**Comment by MuteTiefling** [comment]
Looks like this is on Tinker's itself unless we have a config somewhere that's breaking it. 
Stripped the server to just tinkers and JEI and still don't see invar.

**Comment by MuteTiefling** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/4556
