### ISSUE TITLE
In E6 0.5.1 Terraforge Version Creates Crashes.

### ISSUE THREAD

**Issue by Ryan-Is-A-Person** [NillerMedDild/Enigmatica6#2543]
**Modpack version**
E6 0.5.1

**Describe the bug**
With the current version of Terraforge, it causes crashes when interacting with Repurposed Structures.

**Logs**
https://pastebin.com/ETxjbP0z

**Screenshots**
N/A

A way to fix this bug is to update to the latest version of Terraforge which prevents crashing. 

https://github.com/TerraForged/tracker/issues/132

**Comment by theboo** [comment]
sadly the TF version that fixed this released an hour after 0.5.1 did haha, pretty much instacrash on servers it seems
