### ISSUE TITLE
Crash terraforged - Exception ticking world

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#2547]
**Modpack version**
0.5
**Describe the bug**
Hello,
Sometimes the server crashes with the crashlog below. Looks like some world gen with terraforged (I don't think that's the same issue than what was fixed for 0.5.2, it doesn't mention structures but something that ticks too much. After 500 seconds the watchdog kills the server, as set in server.properties).
Thanks in advance!
**Logs**
https://gist.github.com/jinkhya/e5d06071ad26bae0ac452b230d783b17

**Comment by jinkhya** [comment]
That's another crash we had a few hours before; this one involves byg and nature's aura : 
https://gist.github.com/jinkhya/597af7796c846c2b75b3f4c4fc9c56e1

**Comment by Won-Ton** [comment]
It's an issue between forge and java-15. They only officially support java-8

**Comment by NillerMedDild** [comment]
Could you downgrade to Java 8 and see if that resolves the issue? :)

**Comment by jinkhya** [comment]
Yep I just changed it I'll let you know if it happens again :)

**Comment by jinkhya** [comment]
Looks like that did the trick, so far it hasn't crashed because of terraforged. I'll close this, thanks :)
