### ISSUE TITLE
Blackstone Hammer only accepts Gilded Blackstone

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2548]
**Modpack version**
0.5.2 Server

**Describe the bug**
Trying to craft a Blackstone hammer head with Blackstone makes it a regular Stone hammer head instead. In order to upgrade to a Blackstone hammer head it instead needs Gilded Blackstone, even though Holosphere says both can be used to make a Blackstone hammer head.

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/123542263-fb613100-d748-11eb-815a-34a5d63572e3.png)

**Comment by NillerMedDild** [comment]
@mickelus Hey again :sweat_smile:
We have a material with two tags: `forge:blackstone` and `quark:stone_tool_materials`

The blackstone tag procudes blackstone parts, the stone_tool_materials tag procudes stone parts.

Blackstone has both of these tags. Is there any way to prioritize one over the other?

**Comment by mickelus** [comment]
If you add this [somewhere after](https://github.com/NillerMedDild/Enigmatica6/blob/master/kubejs/data/tetra/schematics/double/basic_hammer/basic_hammer.json#L17) your `quark:stone_tool_materials` entry it should take precedence over the stone outcome.
```json
{
    "material": {
        "tag": "forge:blackstone"
    },
    "requiredTools": {
        "hammer": 3
    },
    "moduleKey": "double/basic_hammer",
    "moduleVariant": "basic_hammer/blackstone"
}
```

**Comment by NillerMedDild** [comment]
Worked perfectly, thank you ❤️
