### ISSUE TITLE
Server failed to startup

### ISSUE THREAD

**Issue by LiquidLighter** [NillerMedDild/Enigmatica6#2549]
**Server Version:**
Enigmatica6Server-0.4.14

1. Extracted Fresh Server file 
2. Opened "serverstarter-2.0.1.jar" 
3. Accepted EULA when prompted
4. Mods get downloaded
5. Right as the server is about to start launching, error is split out: shown in screenshot
(Error is re-obtained even when closing the server and reopening)

**latest log:**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6721624/latest.log)

**Screenshot:**
![image](https://user-images.githubusercontent.com/36366744/123545902-d77c0a80-d79d-11eb-9e5a-8ce01fa9fdb2.png)

**Comment by Darkere** [comment]
To use Java 16 with minecraft forge below 1.17 you need the `--illegal-access=permit` java argument. 

It is generally recommended to use Java 8 as that is what all mods are build with.

**Comment by LiquidLighter** [comment]
Yeah, sorry about that, wasn't sure where to submit a support ticket. I also just noticed the discord was written in the server launch client and went there. Saw someone else had the same issue and was fixed when they used a version of java other than 16. Thanks anyways.

**Comment by NillerMedDild** [comment]
- That being said, we recommend using Java 11 or Java 15 for the sake of performance :)
