### ISSUE TITLE
Mod suggestion: Good Night's Sleep

### ISSUE THREAD

**Issue by Jams52** [NillerMedDild/Enigmatica6#255]
An interesting dimension mod, which is something I think the pack could use. It is on 1.16.2 as well, since you said you were moving development to there. 

https://www.curseforge.com/minecraft/mc-mods/good-nights-sleep

**Comment by NillerMedDild** [comment]
Will try it out asap :)

**Comment by NillerMedDild** [comment]
Cool and strange mod, will add.

**Comment by NillerMedDild** [comment]
After having it in-development for a while I'm afraid we've decided against it. It's a cool concept, but it doesn't really fit in.
