### ISSUE TITLE
Tinker's Construct axe consumed when crafting sticks

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2550]
**Modpack version**
0.5.2

**Describe the bug**
Using a Tinker's Construct axe together with logs or planks in a crafting grid to make sticks consumes the axe. Using a vanilla axe uses 1 durability.

**Screenshots**
First shows the vanilla process, second one shows what happens when using a Tinker's Construct axe.

![image](https://user-images.githubusercontent.com/12349921/123547030-6289e000-d75f-11eb-9c61-1ed3f3862777.png)
![image](https://user-images.githubusercontent.com/12349921/123546913-e8f1f200-d75e-11eb-86d7-c70669ef14fe.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
