### ISSUE TITLE
Atum game tips has its own formatting

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2553]
**Modpack version**
0.5.2

**Describe the bug**
Atum game tips don't follow the same formatting as other game tips.

**Screenshots**
Screenshots show one regular game tip formatting, followed by two Atum game tips.
![image](https://user-images.githubusercontent.com/12349921/123555856-97f6f380-d788-11eb-9b89-9fa960b01e45.png)
![image](https://user-images.githubusercontent.com/12349921/123555860-9c231100-d788-11eb-8bce-5104862fe55d.png)
![image](https://user-images.githubusercontent.com/12349921/123555864-a04f2e80-d788-11eb-8bf7-2308af74162b.png)

**Comment by NillerMedDild** [comment]
Not a bug, they simply decided to make it like that :)
