### ISSUE TITLE
Paraglider tip still exist

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2554]
**Modpack version**
0.5.2

**Describe the bug**
Paraglider game tip still exists even though the item has been removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/123555886-b78e1c00-d788-11eb-80f3-cb50570df57f.png)

**Comment by NillerMedDild** [comment]
Fixed, thanks for the report :)
