### ISSUE TITLE
Players generating lag

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#2561]
**Modpack version**
0.5 (but I've seen this issue in 0.4 worlds as well)

**Describe the bug**
Hello,
I've noticed that players tick a lot. You can see it in forge track reports : 

> forge track start entity 30
> forge track entity
minecraft:player - minecraft:overworld [7,105, 10, 2,934]: 3195.91ms
minecraft:player - minecraft:overworld [-438, 67, 3,664]: 2927.46ms
minecraft:player - minecraft:overworld [-4,593, 73, -6,211]: 2037.14ms
minecraft:player - minecraft:overworld [-6,180, 11, 1,064]: 1816.13ms
minecraft:player - minecraft:overworld [-7,486, 66, -6,279]: 1750.01ms
minecraft:player - minecraft:overworld [912, 16, 4,083]: 435.44ms
minecraft:villager - minecraft:overworld [-5,757, 66, 8,445]: 315.16ms
resourcefulbees:nether_quartz_bee - minecraft:overworld [-4,590, 74, -6,225]: 249.45ms
minecraft:villager - minecraft:overworld [-4,582, 74, -6,211]: 218.85ms
minecraft:villager - minecraft:overworld [-5,763, 66, 8,433]: 162.85ms

which is confirmed by spark : https://spark.lucko.me/LObfwc4cbm 
Not quite sure what's causing this but it becomes more and more of a problem, the more players log on. 
Thanks in advance,
Jin

**Comment by Darkere** [comment]
Advancements :/ 

Do you run any datapacks?

Otherwise I could imagine a player rapidly inserting and extracting through the player inventory causing this.

**Comment by jinkhya** [comment]
We do have some datapacks : 
'anti creeper grief v1.1.0.zip'   
'confetti creepers v2.2.0.zip'               
'track raw statistics v1.4.0.zip' 
'track statistics v1.1.0.zip'
'anti enderman grief v1.1.0.zip'  
'more mob heads v2.8.1.zip'  
'anti ghast grief v1.1.0.zip'
'wandering trades v1.4.0.zip'

those 2 for Emojiful : 
stc-emojiful-datapack.zip
wsssu-colon857684635767799819-emojiful-datapack.zip

**Comment by jinkhya** [comment]
I use those datapacks (beside emojiful) on other servers too, and I don't see players come up like this in reports. Could be a mod interaction that being said, maybe the 2  tracking stats ones.

**Comment by jinkhya** [comment]
I disabled the 2 track datapacks and it's still the same.

**Comment by NillerMedDild** [comment]
>  'anti enderman grief v1.1.0.zip'

You can remove that one, E6 has that functionality already.



The actual issue I'm not really sure we can do anything about tbh :/
