### ISSUE TITLE
Potassium Nitrate Chunk+ enrichment chamber recipe has been removed

### ISSUE THREAD

**Issue by Mr-PenguinMan** [NillerMedDild/Enigmatica6#2564]
Hello! It seems to be that the recipe for Potassium Nitrate Chunk in a enrichment chamber has been removed.

Why this is a issue: Like items such as redstone and coal the enrichment chamber offers a way to turn them into thier item form without smelting them, with the benefit of producing more items then just smelting it. This chunk is the same and it used to have the recipe but it does not as of 5.2. I have verified it had it as of 4.4.14 and that this change is not intentional

<p align="center">
Modpack version
</p>
5.2
<p align="center">
 Screenshots
</p>

![image](https://user-images.githubusercontent.com/63758798/123691689-ec9b7c80-d823-11eb-9d32-4234cb7f43a7.png)
In this image we can see that the recipe into an enrichment chamber does not exist

![image](https://user-images.githubusercontent.com/63758798/123691755-fd4bf280-d823-11eb-9a38-598ed96ce0af.png)
In this image we can see me attempting to place it in, there is also a exporter trying to put it in aswell

![image](https://user-images.githubusercontent.com/63758798/123691810-0d63d200-d824-11eb-84c2-73efa576188f.png)
In this image we can see that the recipe existed in 0.4.14 and once I updated this chunk stopped being enriched

**Comment by NillerMedDild** [comment]
Thanks for the report, I've fixed it in-dev :)
