### ISSUE TITLE
Various rice unification

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2568]
**Description**
1. Add Sushi Go Crafting to list of "forge:grain", like Rice from Environmental and Simple Farming.
2. Make it possible for any "forge:grain/rice" to be used for Villager trades.

**Why would you like this added/changed?**
Rice unification for everyone!

**Comment by NillerMedDild** [comment]
I'm not sure 2) is possible, but 1) we can do 😄
