### ISSUE TITLE
BlockCarpentry crash when using the Frame

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#257]
**Modpack version**
0.2.15

**Issue**
1. Make Frame from BlockCarpentry
2. Place down Frame
3. Right click Polished Blackstone Bricks (vanilla block) into Frame
4. Server crashes, unsure of single player.

**Logs**
[crash-2020-09-05_21.34.12-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/5178969/crash-2020-09-05_21.34.12-server.txt)

**Comment by Shindur** [comment]
Upon re-entering my server I can see the block is not rendering, could be related to this report? https://github.com/NillerMedDild/Enigmatica6/issues/253

**Comment by NillerMedDild** [comment]
Damn, thanks for the report :/ works fine in SP, for me at least.
