### ISSUE TITLE
Experience orbs disappearing instantly

### ISSUE THREAD

**Issue by Discusser** [NillerMedDild/Enigmatica6#2571]
**Modpack version**
0.5.2 (I'm not using the release because it crashed my game whenever I entered my world)

**Describe the bug**
Whenever experience orbs are spawned, and with no exception, they disappear instantly making it impossible to pick up.
I tested this on multiple cases:
- Ender dragon
- Regular mob
- Grindstone
- Furnace

All of them had the same results, the experience orbs disappeared. This is very annoying as I'm trying to do some enchanting and currently my only way of getting experience is by using `/xp` and assuming the experience amount I was supposed to get.

**Logs**
Probably not needed, but here it is anyway.
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6732339/latest.log)

**Comment by Discusser** [comment]
Just went in a brand new creative world to try this, same thing happens.

**Comment by yagoplx** [comment]
Can you delete the Clumps mod and see if it still happens?

**Comment by yagoplx** [comment]
Also, you are using an ancient version of Java 8. I highly recommend that you update.

Download here: https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot (OpenJDK 8, Hotspot 292)

**Comment by Darkere** [comment]
Not the issue and just downloading it will not make minecraft use it. The message is just fine and appears when you use the java version that ships with the game. 

Since this happens in a creative world for him we would just need someone to confirm this?

**Comment by Discusser** [comment]
> You are using an ancient version of Java 8. I highly recommend that you update.
> 
> This message should not be appearing on your log: `[main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED`
> 
> Download here: https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot (OpenJDK 8, Hotspot 292)

I could've sworn I updated, I'll try updating again.

**Comment by yagoplx** [comment]
> I could've sworn I updated, I'll try updating again.

As Darkere said this probably isn't the issue, my bad. Also even if you update you will have to configure the launcher to use that so idk do it if you want

**Comment by Discusser** [comment]
I know, but either way it's better to have the latest version.

**Comment by yagoplx** [comment]
> Since this happens in a creative world for him we would just need someone to confirm this?

I'm not being able to reproduce the issue in creative or survival.

**Comment by Discusser** [comment]
> > I could've sworn I updated, I'll try updating again.
> 
> As Darkere said this probably isn't the issue, my bad. Also even if you update you will have to configure the launcher to use that so idk do it if you want

Yep updating java changed nothing.

**Comment by NillerMedDild** [comment]
Can't reproduce this in creative or survival either. 

Could you please provide your latest.log? :)

**Comment by Discusser** [comment]
The log was already provided in the original post. I can provide my current log if needed.

**Comment by NillerMedDild** [comment]
Oh derp, my bad.

**Comment by NillerMedDild** [comment]
> [12:37:52] [Server thread/INFO]: Enable clustering of items with a radius of 4 blocks.
[12:37:52] [Server thread/INFO]: Enable clustering of Experience Orbs with a radius of 4 blocks.
[12:37:52] [Server thread/ERROR]: Clumps groups XP orbs together into a new single entity, which will conflict with the XP Orb feature of this mod. Don't use both optimizations together!

Found this in the log. Seems there's an extra mod in your instance :)

**Comment by Discusser** [comment]
Ah thanks, forgot I had that installed.

**Comment by yagoplx** [comment]
> > [12:37:52] [Server thread/INFO]: Enable clustering of items with a radius of 4 blocks.
> > [12:37:52] [Server thread/INFO]: Enable clustering of Experience Orbs with a radius of 4 blocks.
> > [12:37:52] [Server thread/ERROR]: Clumps groups XP orbs together into a new single entity, which will conflict with the XP Orb feature of this mod. Don't use both optimizations together!
> 
> Found this in the log. Seems there's an extra mod in your instance :)
> This one specifically: https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops

O.o I have these two both, for some reason it still didn't happen to me, the error isn't in my logs either.
Maybe this is some configuration file shenanigans, I don't even remember editing mine.
