### ISSUE TITLE
Powered Resistive Heater freezes game

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2573]
**Modpack version**
0.5.2 server

**Describe the bug**
Mouseover on a placed powered Resistive Heater - powered either in-world or while in inventory - causes the game to freeze for up to 10 seconds. Letting it discharge the stored power (and removing any power source) makes it possible to mouseover again. Most likely caused by TOP Addons.

**Screenshots**
Mouseover on Resistive Heater powered by a Spirited Ender Gate, screenshot taken while game was frozen. Removing the Ender Gate lets it discharge the power and make it possible to mouseover again.
![image](https://user-images.githubusercontent.com/12349921/123800127-40bc6480-d8e9-11eb-95a0-718694189514.png)

Mouseover on a newly crafted and placed Resistive Heater, partly charged by a Batter (Blazing) in inventory. Placing it and thus mouseover automatically froze the game for up to 10 seconds, after which the Resistive Heater had powered down and it was possible to mouseover without freezing.
![image](https://user-images.githubusercontent.com/12349921/123800322-795c3e00-d8e9-11eb-93b2-5c87f1743138.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. 

Mekanism is actually disabled from the TOP Addons gauge, so I'm not sure what's going on here, I'll investigate.

**Comment by NillerMedDild** [comment]
I can't reproduce this, I suspect either you or the server is missing E6's custom configs - Could you please verify that your `topaddons-common.toml` matches this:

```toml

[forge]
	#List of mod IDs for which no TOP Addons fluid gauge should be shown
	gaugeModBlacklist = ["mekanism", "mekanismgenerators", "fluidtank"]

[storagedrawers]
	#Hide info when drawer is concealed
	hideConcealed = false

[bloodmagic]
	#Seeing blood/incense altar info requires holding a divination or seer sigil in any hand
	altarsRequireSigil = false

**Comment by g0urra** [comment]
Correct, I can verify that the file matches that, both local and on the server.

**Comment by NillerMedDild** [comment]
Alright ty, might be server only then, will have another look.

**Comment by g0urra** [comment]
Must be something temporary - either solved by restarting the server and/or my client - but it seems to be fixed now as mouseover works. I'll update if it happens again.
![image](https://user-images.githubusercontent.com/12349921/123871626-2bb8f300-d934-11eb-8277-d6d02b872813.png)

**Comment by Splutty** [comment]
It's a completely fresh install, and they match. I restarted 3 times none of which helped.

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/mekanism/Mekanism/issues/7195
I'm just gonna remove TOP Addons.
