### ISSUE TITLE
Simple Farming seeds do not drop from grass

### ISSUE THREAD

**Issue by Geariko17** [NillerMedDild/Enigmatica6#2575]
**Modpack version** 
0.5.2 and 0.5

**Describe the bug**
I am unsure if the method to obtain them changed between updates, but it appears the simple farming seeds have been removed from the drop table for breaking grass? I haven't found any after using veinminer to break a bunch of grass.

**Screenshots**
I have a small video/gif I recorded breaking some grass and not getting any but it was too big to attach

Apologies if this was made in error I am not familar with how Github works and I dont know if this was intended :X

**Comment by NillerMedDild** [comment]
Thanks for the report - This was done on purpose :) Simple Farming generates wild crops throughout the world, you can get seeds that way.

If you're less patient, you can buy them from the Market 😄

**Comment by Geariko17** [comment]
Okay! Thank you! Just wanted to make sure. I had a feeling it was something like that.
