### ISSUE TITLE
Doubleclick to search inventory feature no longer present

### ISSUE THREAD

**Issue by IllegalCharacter** [NillerMedDild/Enigmatica6#2578]
**Modpack version**

0.5.1 with manually updated terraforged (server version wasn't available on our host at the time of update)

**Describe the bug**
Double-clicking the search bar in JEI used to highlight it in yellow and made it search your inventory, or the inventory of a chest you were looking in. This no longer happens.

**Screenshots**

![s0AD5Pk19w](https://user-images.githubusercontent.com/7243508/123843520-fbe00000-d8df-11eb-83f1-2cd766931476.png)

**Comment by NillerMedDild** [comment]
Sorry about that, CurseForge has picked up a nasty habbit of removing mods from my development instance, this time More Overlays was removed ^^' will be fixed in 0.5.3
