### ISSUE TITLE
Multiple chunks are unable to be enriched

### ISSUE THREAD

**Issue by Mr-PenguinMan** [NillerMedDild/Enigmatica6#2579]
**Modpack version**
0.5.2

**Describe the bug**
Hello! It seems to be that the recipe for Mana chunks, Coblat, Cinibar, Apitite, bitumen and sulfur chunks in a enrichment chamber has been removed.

It is simler to [this issue ](https://github.com/NillerMedDild/Enigmatica6/issues/2564) but I have discovered that more chunks were affected by whatever removed the pottasiums chunk into an enrichment chamber recipe

**Comment by g0urra** [comment]
Cobalt Chunk is an ore and can't be processed in an Enrichment Chamber.

**Comment by NillerMedDild** [comment]
I fixed this when you reported the Potassium issue, but thanks for the bug report :D

> Cobalt Chunk is an ore and can't be processed in an Enrichment Chamber.

Ores can be doubled in the Enrichment Chamber
