### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by Terminator81** [NillerMedDild/Enigmatica6#258]
Server Version 0.2.15

debug.log:
https://privatebin.net/?b62156129dbe956d#DeyBbLS4Z61JcU7nQn4M4K8Cm9Jm5zf7c2DzNCWjtKSG

serverstart.log:
https://privatebin.net/?1b8ff7f03cfac38e#AeeWvW1ADPfLHe81pJ4vBhRU6vYjHoibXF7wLoLkqpH7

latest.log:
https://privatebin.net/?4b80f9b07faf1a6a#npoboxeAyWD3iW8CqYxnDtZEn4hi7msEB2x5VkjLHA1

can someone help me?

**Comment by Darkere** [comment]
Although not in those logs. Botania had a hotfix for a servercrash. Update botania :)

**Comment by NillerMedDild** [comment]
Re-download the server files :) I made a mistake and uploaded the wrong one, fixed it about 10 hours ago.

**Comment by Darkere** [comment]
They still contain the crashing Botania version :/

**Comment by NillerMedDild** [comment]
They do, but not the config that causes the crash.

**Comment by Darkere** [comment]
Hmm. There have been at least 3 cases in discord today.

**Comment by NillerMedDild** [comment]
It took me about 24 hours from release till I fixed the server files, 24 server downloads in the meantime, so that could account for it.

**Comment by Darkere** [comment]
It could. But the download I made 3 hours ago crashes ;)

**Comment by NillerMedDild** [comment]
Err what? You downloaded the server files 3 hours ago, and they crashed?

**Comment by Darkere** [comment]
Yes. I downloaded them 3 hours ago to check on the botania version. Then I just tried them, and they do crash with botania.

**Comment by NillerMedDild** [comment]
Oh. Sorry.
