### ISSUE TITLE
Tinkers lanterns not functional on walls

### ISSUE THREAD

**Issue by groverfield** [NillerMedDild/Enigmatica6#2584]
**Modpack version**
0.5.2

**Describe the bug**
When a Scorched or Seared lantern is placed, it loses its fluid inventory when converted to a Supplementaries version of that lantern, also losing its light.  (only tested with Blazing Blood, incase it works with other fluids

**Comment by MuteTiefling** [comment]
Looks like this'll be fixed in the next release of supplementaries by black listing in the config by default. So we should probably just go ahead and update our config to do the same.
