### ISSUE TITLE
Right-side of Mekanism Questline (Fissile fuel production) makes no sense

### ISSUE THREAD

**Issue by Katon152021** [NillerMedDild/Enigmatica6#2585]
**5.2**

**Describe the bug**
The right side of the questline in Mekanism has all checkmarks to complete the quests making it extremely easy to bypass all of the important steps in the quest line. It looks like there is no rewards at the moment but this still makes no sense. The bigger issue is that for the Chemical Oxidizer, it grants you 64 Pellonium pellets, a creative energy Cube, and 64 Netherite ingots. 

![2021-06-30_01 31 09](https://user-images.githubusercontent.com/85213540/123912593-dafcc680-d942-11eb-90e3-e22a91d415f5.png)
![2021-06-30_01 14 16](https://user-images.githubusercontent.com/85213540/123912598-ddf7b700-d942-11eb-9a11-96beccc3963e.png)

**Screenshots**

**Comment by g0urra** [comment]
I just looked through the quest book and it does not give those rewards for me. It does, however, look like you added it through editing mode?
![image](https://user-images.githubusercontent.com/12349921/123939830-db27b100-d998-11eb-802b-2fe3193963bd.png)

**Comment by g0urra** [comment]
The chain is not even meant to be a quest chain with goals that rewards. Like the first step says:
![image](https://user-images.githubusercontent.com/12349921/123941809-cfd58500-d99a-11eb-9e16-565d550c3bb6.png)

**Comment by hofmannk69** [comment]
I dont have those quest rewards either in the Mekanism quest chain.  Version 0.5.2 single player world.

**Comment by MuteTiefling** [comment]
As g0urra correctly pointed out, these aren't meant to be quests, nor give rewards. Though I did throw in a few cheeky cookies at the very end for people that clicked through it all.

It's strictly there as a guide to fissile fuel. I could have probably put it together in some flow chart software, took a screenshot, and just included that instead, but I felt this looked nicer while doing the same job of relaying inputs, outputs, and intermediate products (does x machine output a gas or a liquid?).

None of those quests, however, grant anything close to what you're showing in your screenshot. Rewards are generous, but not free-creative-energy-cube generous.

**Comment by Tyler-Jarret** [comment]
> As g0urra correctly pointed out, these aren't meant to be quests, nor give rewards. Though I did throw in a few cheeky cookies at the very end for people that clicked through it all...

Okay but can I say I _love_ clicking through all the of "non-quests" and reading everything. The jokes and references are on point :P
