### ISSUE TITLE
Buddycards

### ISSUE THREAD

**Issue by ImreLammers** [NillerMedDild/Enigmatica6#2586]
**CurseForge Link**
[Link](https://www.curseforge.com/minecraft/mc-mods/buddycards)

**Mod description**
Adds a collectible card game to Minecraft where you and your friends can find, collect and trade them!

**Why would you like the mod added?**
1) I personally love collecting.
2) It's a really fun mod with friends
3) It made me wanna go out and explore to find more packs
4) It's a super light mod
5) I tested it in Singleplayer and as far as I could tell, everything was working fine. The drop rate of the packs might need to be increased slightly.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/22069807/123939624-98fe6f80-d998-11eb-84f5-09051b3afa02.png)

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by NillerMedDild** [comment]
I think this is a cool mod, but I don't think it really fits in well enough to warrant adding it.
