### ISSUE TITLE
LogIn Protection Invulnerability might be too short for older machines

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2589]
**Description**
I noticed that `invulnerabilityTime` ist set to `300` in `logprot-common.toml`. When I play online with other friends with mid- to low-end tier PCs it sometimes or oftenly takes about one minute until you can fully move in the world. `300` might be too short then where as `100` stands for 5 seconds. You might consider increasing the value at least up to `1200`, don't you?

Edit: I died in the nether once because I stucked in a wall without even noticing it, so I died when fully logged in. 
Good that you can just type `/back` after that one. ;)

Greetings (:

**Comment by NillerMedDild** [comment]
Good idea, I died to this just last night on our development server :P

**Comment by Erysch** [comment]
I sometimes feel that `1200` is not enough as well, so I set it up to a crazy amount (`20000`). Since you break invulnerability when you move it should be fine.
