### ISSUE TITLE
Pedestal with filter deleting items

### ISSUE THREAD

**Issue by forbidword** [NillerMedDild/Enigmatica6#2593]
**0.5.2*

**Pedestal extracts and deletes items that are not in whitelist of the inserted filter**
I had a chest with a number of items in it, some of which had been added to a Pedestal's Filter. I placed a pedestal with an import upgrade on top of the chest, linked it to another pedestal on another chest with an export upgrade, and inserted the filter which is in whitelist mode. The pedestal moved over the items which were included in the filter properly but it also took the other items which were not in the filter and just deleted them instead of move them. I switched things around and moved the whole contraption and the behavior is unchanging. The receiving pedestal has no filter.

**Comment by NillerMedDild** [comment]
Thanks for the report, found it reported here: https://github.com/Mowmaster/Pedestals/issues/88

**Comment by Mowmaster** [comment]
fixed in new version: https://www.curseforge.com/minecraft/mc-mods/pedestals/files/3397977
