### ISSUE TITLE
Terrasteel (Botania) recipe mismatched in Lexicon and JEI

### ISSUE THREAD

**Issue by Katon152021** [NillerMedDild/Enigmatica6#2594]
5.2.b

The recipe on JEI shows a Terrasteel honeycomb in the JEI recipe vs the Lexica Botania book. See pictures for reference.

![2021-07-01_02 19 35](https://user-images.githubusercontent.com/85213540/124082997-fd5e1500-da12-11eb-9b9b-ea874ec73af4.png)
![2021-07-01_02 19 42](https://user-images.githubusercontent.com/85213540/124083003-ff27d880-da12-11eb-9854-196634a7c24c.png)

**Comment by MuteTiefling** [comment]
Look at the second page of the recipe in jei.

**Comment by g0urra** [comment]
Maybe a suggestion then to make the Manasteel Ingot recipe the first one in JEI?

**Comment by MuteTiefling** [comment]
I don't believe we have control over the order, sadly.
