### ISSUE TITLE
Terrasteel Cannot be Crafted Using Terrestrial Honeycombs in a Mana Infuser

### ISSUE THREAD

**Issue by RobuxShooters** [NillerMedDild/Enigmatica6#2595]
**Modpack version**
0.5.2

**Describe the bug**
The Mana Infuser tab in JEI shows the crafting recipes for both terrasteel and alfsteel. However, the other recipe for creating terrasteel (involving a terrestrial honeycomb instead of a mana ingot) is missing from the Mana Infuser while it is present in the Terrasteel Agglomeration Plate tab of JEI.

**Screenshots**

**Comment by TemperedFool** [comment]
Hmm, good point and easy fix. Coming right up!
