### ISSUE TITLE
Mod suggestion: Enderchests/tanks

### ISSUE THREAD

**Issue by Jams52** [NillerMedDild/Enigmatica6#260]
Another thing I think the pack could use right now, they're pretty useful for different build designs. 

https://www.curseforge.com/minecraft/mc-mods/enderchests
https://www.curseforge.com/minecraft/mc-mods/endertanks

**Comment by Thiana** [comment]
Maybe you should pin that you're waiting for the original mod to be ported @NillerMedDild ?

**Comment by NillerMedDild** [comment]
I'd rather not to be honest, people that miss duplicate issues could miss the pins too.

**Comment by NillerMedDild** [comment]
We're waiting for the original EnderStorage mod to update :)
