### ISSUE TITLE
Flourite can't be crafted with pulverizer

### ISSUE THREAD

**Issue by 0xdreadnaught** [NillerMedDild/Enigmatica6#2600]
**Version 0.4.14**

**Describe the bug**
JEI shows flourite as craftable in the pulverizer (Thermal Series) with either flint or basalz powder as the optional catalyst. Adding either reagent to the pulverizer does nothing.

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/983663/124208127-eb34b300-dab4-11eb-8490-aa66765e39e4.png)
![image](https://user-images.githubusercontent.com/983663/124207984-9f820980-dab4-11eb-9b6f-bd7106a81757.png)
![image](https://user-images.githubusercontent.com/983663/124208006-ae68bc00-dab4-11eb-9611-1c6cd5f946ca.png)
![image](https://user-images.githubusercontent.com/983663/124208037-c0e2f580-dab4-11eb-81b2-5e0cb6830bb7.png)

**Comment by RobuxShooters** [comment]
The JEI tab isn't actually showing you how to craft fluorite, rather it is showing you how to crush fluorite chunks so you get better yields for each chunk. That being said, the input item seems to be missing and hence why you might think that you can get fluorite from just flint or basalz powder.

I'm currently playing in v0.5.2 (singleplayer) and the JEI display seems like it's working as intended:
![image](https://user-images.githubusercontent.com/16001607/124221858-19f16e80-db33-11eb-8c19-312854f1923c.png)
