### ISSUE TITLE
Flies are too common

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#2601]
**Description**
Write a short description of your suggestion here.

Remove flies.

**Why would you like this added/changed?**

When you're out and about hunting for (wild) bees flies constantly grab your attention since they fly in the same matter as bees, the only difference being that they are smaller & useless, the human brain doesn't really like being distracted like this.

**Screenshots if applicable.**

![2021-07-02_10 45 17](https://user-images.githubusercontent.com/3179271/124247933-a6476580-db22-11eb-9a0d-33262f164638.png)

![5f839q](https://user-images.githubusercontent.com/3179271/124242759-6467f080-db1d-11eb-8118-f224c3100cd4.jpg)

![Screen Shot 2021-07-02 at 10 45 54](https://user-images.githubusercontent.com/3179271/124247988-b2cbbe00-db22-11eb-9b00-a91d481b6ba4.png)

**Comment by Tyler-Jarret** [comment]
This is why with the server I run, we turned off the fly spawns via config. We also discovered that they were taking a too high of a precentage of the passive mob cap. I think it adds a bit of realism that I don't really mind in the Single Player. Alex's Mobs would be amazing if more of the mobs added had _more_ functional bits to them. But I realize that is a LOT more coding for the mod author. And making custom models is clearly the forte there.

But with my server it's just a QOL they wanted. Fortunely with E6 and Alex's Mobs, changing configs is very easy.

**Comment by MuteTiefling** [comment]
They do seem rather common, but not so common as to disable them entirely in the pack.

Remember that all of Alex's mobs go in fact have uses. Flies are food for several mobs. Sure, we could take the same route as we did with roaches, but they also aren't quite on the same level of "omg they are everywhere" either.

**Comment by TemperedFool** [comment]
Maybe drop the spawn weight from 2 to 1? Tbh I was surprised to see how low it was in the first place, but given they can spawn anywhere it may just make them feel common.

**Comment by Tyler-Jarret** [comment]
I think it's the "they can spawn everywhere" that makes them feel **very.** And you're right the weight isn't a lot.

However, TIL flies are food for some mobs o.O.

**Comment by TemperedFool** [comment]
Yep, Alex's let's spiders eat them. Wolves can eat moose too.

**Comment by MuteTiefling** [comment]
You also need flies to tame and breed warped toads, if I recall correctly
