### ISSUE TITLE
Light Level Ovelay

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2602]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/light-overlay

**Mod description**
You had a mod like this in your pack. It was removed in 0.5.0+ Why?
Do you have a substitution mod now? (:

**Why would you like the mod added?**
For me it's one of the essential client mods in minecraft. It's strongly needed for checking light levels until you can get a mega torch :^)

Greetings (:

*This post refers to version 0.5.2.*

**Comment by MuteTiefling** [comment]
It was removed because curse is cursed and has been randomly removing mods from the manifest.

So, not intentionally :D

It'll be back, don't worry.

**Comment by Tyler-Jarret** [comment]
> It was removed because curse is cursed and has been randomly removing mods from the manifest.

CursedForge, "the most cursed mod provider this side of the century."

**Comment by Erysch** [comment]
Love to you <3

Happened to me once as well x)
