### ISSUE TITLE
Double Maps

### ISSUE THREAD

**Issue by Purpledennyson** [NillerMedDild/Enigmatica6#2607]
**Modpack version**
0.5.3 E6
**Describe the bug**
After updating to beta version 0.5.3, have 2 different map versions that are overlapping.

Added screenshot of issue.

![2021-07-03_01 59 11](https://user-images.githubusercontent.com/86135547/124346331-c9662980-dba3-11eb-9e59-a7dcfb154496.png)

**Comment by hofmannk69** [comment]
You can press M and at the bottom is a settings button where you can disable the FTB mini map or you can press J and disable the Journey map one.

**Comment by Larandar** [comment]
Found the issue (config format changed in ftb-chunk) will do a PR today

**Comment by NillerMedDild** [comment]
We can yes :)
