### ISSUE TITLE
"Could not deserialize error" Can't join server

### ISSUE THREAD

**Issue by leonbeer** [NillerMedDild/Enigmatica6#2608]
Version 0.4.14

Every time i try to join my E6 server, it starts spamming the console with
 "Could not serialize dev.maxneedssnacks.interactio.command.RegistryArgument@4553683e (class dev.maxneedssnacks.interactio.command.RegistryArgument) - will not be sent to client!"

The client also says it could not deserialize minecraft:
The server has been running for a while before the eroor, until i went into an rftools dimension, which didnt load so i killed the game and restarted.It didnt load anymore, so im stuck in "loading terrain"

[2021-07-03-1.log](https://github.com/NillerMedDild/Enigmatica6/files/6758001/2021-07-03-1.log)

also, heres the client log
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6758098/latest.log)

**Comment by leonbeer** [comment]
also tried in the 0.5.3 version. same thing

**Comment by NillerMedDild** [comment]
I'm thinking your best bet would be to move your player by editing it's playerdata, and delete the rftools dimension :) If that's not possible, please provide the server's log.
