### ISSUE TITLE
World Chunk Errors on 0.5.3

### ISSUE THREAD

**Issue by dusieq95** [NillerMedDild/Enigmatica6#2609]
**Modpack version**
0.5.3
**Describe the bug**
I created world in 0.5.2, vanilla preset and after upgrading world to 0.5.3 i got those chunk errors on new generated chunk's.

**Logs**

**Screenshots**
![unknown-1](https://user-images.githubusercontent.com/59163540/124350233-c5fa8e80-dbf3-11eb-889c-47a6de4cbb19.png)
![unknown](https://user-images.githubusercontent.com/59163540/124350241-c98e1580-dbf3-11eb-93c9-8791e97fc52b.png)

**Comment by NillerMedDild** [comment]
Oh no >< I'll investigate.

**Comment by dusieq95** [comment]
Maybe it's caused because i didn't delete configs before updating.

**Comment by NillerMedDild** [comment]
That wasnt required for 0.5.2 to 0.5.3 :) could you please check if you have the mod BiomeIdFixer?

**Comment by dusieq95** [comment]
Yeah, i have this mod biomeidfixer-1.16.5-1.0.1.s4

**Comment by NillerMedDild** [comment]
Damn :P did you install 0.5.3 as a new instance and moved your files?

**Comment by dusieq95** [comment]
I just updated the pack through CurseForge and i didn't move any files, probably that's why i got those errors ( ｡_｡)

**Comment by NillerMedDild** [comment]
Nah you did exactly what you should have done :) I'll try to find the cause.

**Comment by NillerMedDild** [comment]
Alright, I wasn't able to reproduce this.
- Are you on a server?
- Did you modify the modpack in any way? Added/deleted mods?

**Comment by dusieq95** [comment]
Singleplayer

In 0.5.2 i added OptiFine_1.16.5_HD_U_G8
After updating to 0.5.3 i deleted optifine and replaced it with sodium-forge-2.7+rev.168f15b

I will try run old world (0.5.2) with new instance (I could try upload my world but i have rly slow upload speeds and it could took a few hours so)

**Comment by NillerMedDild** [comment]
I'm about 95% sure Sodium is the reason here :P

**Comment by dusieq95** [comment]
Yeah, it was caused by Sodium i didn't know that this mod can cause chunk errors, problem solved :)

**Comment by landretk** [comment]
Can it cause chunk errors on servers too or is this a singleplayer thing?

**Comment by NillerMedDild** [comment]
Probably both. I do not recommend using it.

**Comment by landretk** [comment]
Oof, removing Sodium screwed up new chunks for me. It appears that worldgen is just different with/without it so if you start without it you don't want to add it and if you start with it you want to keep it. Readded Sodium and deleted the incorrect chunks and they generated correctly with it back in.

**Comment by Erysch** [comment]
> Probably both. I do not recommend using it.

My old secondary pc doesn't like to hear that :'(

**Comment by Erysch** [comment]
> Oof, removing Sodium screwed up new chunks for me. It appears that worldgen is just different with/without it so if you start without it you don't want to add it and if you start with it you want to keep it. Readded Sodium and deleted the incorrect chunks and they generated correctly with it back in.

You should still be able to use it without problems when the server is rendering the world and not your client.
