### ISSUE TITLE
Split Distillation Tower quest

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2611]
**Description**
Distillation Tower quest requires Bucket of Diesel to complete, however the Distillation Tower gives Sulfurized Diesel. In order to get Diesel, the Sulfurized Diesel need to be processed first in a Sulfur Recovery Unit.

I would suggest that the quest instead requires Sulfurized Diesel, and then another quest is added between Distillation Tower and Diesel Generator that details Sulfur Recovery Unit. This one would have its building materials and require Bucket of Diesel to complete.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion :)

**Comment by MuteTiefling** [comment]
Left it as optional since both Sulfurized Diesel and normal Diesel burn for the same amount of energy in the Diesel Generator. The SRU is simply an optional way of producing extra sulfur.
