### ISSUE TITLE
Jerrycan uncraftable

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2612]
**Modpack version**
0.5.2 server

**Describe the bug**
Jerrycan from Immersive Engineering cannot be crafted as it has no recipe in JEI. The usual recipe - 4 Iron Plates and 4 Buckets - does not work.

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/124358063-d8d68880-dc1e-11eb-9ab2-63718b9f1479.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Fixed, we disabled it a while ago because it was a bit crashy iirc.
