### ISSUE TITLE
Atum 2 crashing the game

### ISSUE THREAD

**Issue by TheBlackNight1** [NillerMedDild/Enigmatica6#2613]
[crash-2021-07-03_18.48.33-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6758675/crash-2021-07-03_18.48.33-server.txt)

there is a villager in Atum 2 causing crashes

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it here: https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/98
