### ISSUE TITLE
Mishandled Death by Enigmatic Graves

### ISSUE THREAD

**Issue by landretk** [NillerMedDild/Enigmatica6#2614]
**Modpack version**
0.5.3

**Describe the bug**
I am trapped outside my own body after respawning. Only happened after using the Title screen button which I'm not sure anyone actually uses but maybe fixing this bug will handle other edge cases. I can't move, but I can punch my body and the body does the punching animation. It's like the camera entity is separate from my body by maybe 1/10 of a block.

Steps to reproduce:
1. Start new singleplayer survival world
2. Die (/kill or dying to a mob both work)
3. Hit 'Title Screen' button
4. After returning to the main menu, reopen the world
5. Hit 'Respawn'
6. Respawn displaced from your own body. I also spawned right on top of my grave somehow if that matters.

**Logs**
Here's the error part of the latest.log:
https://pastebin.com/qWNpcnb5

I'm not sure where I can upload the whole log but that seems to be the only interesting part of it.

**Screenshots**
![2021-07-03_11 14 32](https://user-images.githubusercontent.com/4535529/124362425-ed505c00-dbf1-11eb-8729-c5ba7f9da2b4.png)

**Comment by theboo** [comment]
Reported to EG github, was able to reproduce using title screen option. Should be fixed soon! Thanks for the report!!

**Comment by CynicalRoses** [comment]
This also seem to occur when the gamerule keepInventory is set to true.

**Comment by theboo** [comment]
the keepinventory bug should have been fixed in a previous release of EG that was included in enigmatica v0.5.4, what pack version are you on?

**Comment by landretk** [comment]
I tested keepInventory on this version(0.5.3) and it was fine fwiw

**Comment by CynicalRoses** [comment]
I'm on v0.5.4, I'll see if I can replicate it. It was on a server, so I'll see if I can pull the log from when it happened.
