### ISSUE TITLE
(Mod Suggestion) Hats

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2617]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/hats

**Mod description**
A mod that adds hats that can be applied to both players and mobs (including villagers and pets).

**Why would you like the mod added?**
Everyone like hats, but mostly because I want these on my cats. The hats are all purely cosmetic and it also seem possible to add custom hats through configs.

**Comment by g0urra** [comment]
@NillerMedDild Sorry to ping you, but have you taken a look at this? :)

**Comment by NillerMedDild** [comment]
No worries. I haven't yet, no :)

**Comment by NillerMedDild** [comment]
To be honest I think it's a bit too meme-y :P
