### ISSUE TITLE
Regular honey blocks can't upgrade beehive

### ISSUE THREAD

**Issue by ManInTheMists** [NillerMedDild/Enigmatica6#2620]
Attempting to upgrade a tier 3 beehive to tier 4 will not work if the player attempts to use regular honey blocks.  Only honey blocks from other types of bees can be used to create a beehive, which creates an unnecessary gating issue.

**Comment by MuteTiefling** [comment]
Unnecessary gating? That you need to use resourceful bees to progress in resourceful bees?

**Comment by TemperedFool** [comment]
Hrm, this was originally JUST vanilla honey blocks. Let me see if I can squish this problem once and for all.

**Comment by anivlys** [comment]
> 
> 
> Unnecessary gating? That you need to use resourceful bees to progress in resourceful bees?

Well a bunch of resourceful bees only give regular honey when you centrifuge their combs. Going through JEI and 23 Bees, not include the vanilla bee, give regular honey as an output. Something like 26 out of 63 honeycomb types give a honey product that can be used to make a honey block that can upgrade hives.

**Comment by ManInTheMists** [comment]
In my case I was using Beepers to get the wax and honey.

**Comment by TemperedFool** [comment]
This is just an oversight from #2381; it'll be fixed in dev later today.
