### ISSUE TITLE
Acacia Log gives 1mb of Latex per operation, only Dark Oak Log listed in Fluid Extractor JEI

### ISSUE THREAD

**Issue by TheKapec** [NillerMedDild/Enigmatica6#2621]
**Modpack version**
0.5.4

**Describe the bug**
Acacia Log gives you 1mb of Latex per operation (Industrial Foregoing) while it should be a lot more, it eves says it in the quest. Also, in JEI of Fluid Extractor there is only "Dark Oak Log" and it also shows 1mb/operation and there is no any other logs listed.

**Logs**
---

**Screenshots**
![mc1](https://user-images.githubusercontent.com/86537997/124383048-bef27f80-dcca-11eb-94a3-3c5cdd367201.png)

**Comment by Splutty** [comment]
Yep. 0.5.2 shows 7 wood types.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
