### ISSUE TITLE
JEI shows 2 uses for raw quartz block in the crushing wheels but there is no way to choose

### ISSUE THREAD

**Issue by TzarTz** [NillerMedDild/Enigmatica6#2622]
0.4.14

JEI shows 2 uses for raw quartz block in the Create crushing wheels. 1 of them makes quartz with a bonus output of quartz and the other once creates quartzite sand. When actually using the crushing wheel it creates quartzite sand when i want it to create quartz instead.

Here is JEI view. The bottom recipe is the ones that takes effect
![2021-07-04_12 51 01](https://user-images.githubusercontent.com/86915860/124384786-d16cb900-dcca-11eb-8744-4b2f72ba6623.png)

**Comment by NillerMedDild** [comment]
Fixed in 0.5.0+ :)
