### ISSUE TITLE
[0.5.3] Armored Jetpack nerf

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2623]
**Description**
Reduce armored jetpack armor points

**Why would you like this added/changed?**
Refined Obsidian Armor was nerfed in order to give other armors more air to breath. The armored jetpack has been untouched yet. It still has 12 armor points like the refined obsidian chestplate had before (which now has 9 on chestplate) but the armored jetpack doesn't even consist of refined obsidian ingots AND it gives you a huge mobility boost.
Maybe it should be also tweaked.

**Screenshots if applicable.**
![Armored Jetpack](https://user-images.githubusercontent.com/81813584/124384989-1fd28580-dcd4-11eb-8e1a-ed95b6a45782.png)
![Refined Obsidian Chestplate](https://user-images.githubusercontent.com/81813584/124385014-3d9fea80-dcd4-11eb-8918-b631c861a4c4.png)

Greetings! (:

**Comment by RobuxShooters** [comment]
While I do agree the armour points for the Armored Jetpack should be reduced, consider the fact that the Armored Jetpack is somewhat more expensive than the Obsidian Chestplate.

For the Obsidian Chestplate, you need:
- 2 Obsidian blocks, enriched into 8 Obsidian Dust
- 1 Diamond, enriched into 1 Enriched Diamond
- Enrichment Chamber
- Metallurgic Infuser
- Osmium Compressor
- 8 Osmium Ingots

For the Armored Jetpack, you need:
- Jetpack (obtainable from quests)
- Metallurgic Infuser
- Enrichment Chamber
- Crusher
- Energized Smelter
- 9 Steel Ingots
- 2 Bronze Ingots (3 Copper Dust + 1 Tin Dust makes 4 Bronze Ingots)
- 2 Diamonds, crushed into dust

**Comment by MuteTiefling** [comment]
The armored jet pack can't be enchanted, can it? And it's horizontal movement is terrible.

**Comment by Erysch** [comment]
For me I would be fine when nothing changes. I just thought about it because I just made on in my singleplayer survival world :)
