### ISSUE TITLE
[0.5.4] Potential Mob Pathfinding Issues (Bee's, Zombified Piglins, etc.?)

### ISSUE THREAD

**Issue by NoMoreStars** [NillerMedDild/Enigmatica6#2625]
**Modpack version**

Enigmatica 6 0.5.4

**Describe the bug**
When moved over long distances, bees also do not recognize new hives in the area. I've also noticed resourceful bees tend to fly high into the air and remain completely stationary. This may be a mob pathfinding issue as I tested if Zombified Piglins will still pathfind to turtle eggs only for it to be confirmed that they do not. Not sure if the latter situation is relevant or not, just an observation.

**Comment by NillerMedDild** [comment]
Thanks for the report. Was this observed in singleplayer, or on a server?

**Comment by NoMoreStars** [comment]
Singleplayer

**Comment by NillerMedDild** [comment]
Did you modify the modpack in any way, added mods or something like that? :)

**Comment by NoMoreStars** [comment]
The only new mod added originally Sodium Reforged mod initially (which I thought was causing the problem initially) but disabled it, started a flat world for testing purposes, and discovered the Piglin pathfinding issue. I also relogged into another world that was made when Sodium Reforged was enabled and I still had problems with bees not recognizing nests in the area. Thanks for the fast replies by the way!

**Comment by NillerMedDild** [comment]
To be honest I wouldn't rule out Sodium Reforged even if it's disabled. I've tested on my local development server, and Zombified Piglins go straight for turtle eggs. Inconsistent bee behaviour is also more or less a trademark for performance mods :P

**Comment by Blatts12** [comment]
https://github.com/spoorn/sodium-forge/commit/faa7fd806bcde35f8c8efa0ee4487e11ad85dfba
