### ISSUE TITLE
Quest Book Reset on server when updated

### ISSUE THREAD

**Issue by BloodyBacca** [NillerMedDild/Enigmatica6#2627]
**Modpack version** Version 0.5.4

**Describe the bug**
I just recently updated my server that I run for a couple of friends this morning to the latest version of the modpack. When I joined the server after it had finished updating, I noticed that all the quests I had completed in the book previously have been reset. Is there any way to regain that progress without having to redo the quests over again? Also, what could have caused the book to be reset for all of my players?

**Comment by NillerMedDild** [comment]
I'm afraid any progress you had in 0.4.x versions of the modpack does not transfer to 0.5.x :/ I should've made that clear in the changelog, my apologies.

**Comment by BloodyBacca** [comment]
Alright, ill let my players know that. Thank you for the quick response!

**Comment by NillerMedDild** [comment]
Sure thing. I've been told that you will also need to delete the `ftbquests` folder from your world :)

**Comment by BloodyBacca** [comment]
Okay, Thank you!
