### ISSUE TITLE
Amadron Ordering Scam

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#263]
Enigmatica 6 0.2.16

Amadron tablet was offering a 1 emerald for 4 iron ingot deal.  When I try to submit an order for that deal 32x over and leave 2 stacks of iron ingots, a single drone takes away 1 stack of iron and does not leave any emeralds.  If I limit the order to 16x, then it retrieves 1 stack of iron and a drone comes and leaves the emeralds. If I make an order for selling iron 16x as well as a sale of wool it will send two drones and sends two more drones to leave emeralds successfully.  If I make the order for iron 17x (1 stack + 4 ingots) it sends a single drone and takes away 1 stack and does not leave emeralds. So it would seem that each drone cannot carry more than one stack and it doesn't properly handle things if it needs to send more than one drone for a given material.

**Comment by MuteTiefling** [comment]
For reference: https://github.com/TeamPneumatic/pnc-repressurized/issues/608

**Comment by desht** [comment]
Just to note, PNC:R 2.2.1 fixes this bug.
