### ISSUE TITLE
Tank null when put in sponge mode crashes client

### ISSUE THREAD

**Issue by Roukurai** [NillerMedDild/Enigmatica6#2631]
**Modpack version**
.5.4
**Describe the bug**
Setting the tank null in sponge mode causes interna server errors. Unable to load back in as it generates error.

**Logs**
https://gist.github.com/Roukurai/10349c1f4bbd71879d86fc3d2eaf8d63

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm not seeing any trace of the issue in the logs. Could you provide the server log?
