### ISSUE TITLE
My Game Is Crash

### ISSUE THREAD

**Issue by ReCaree** [NillerMedDild/Enigmatica6#2632]
**Modpack version**
Enigmatica 6 0.5.4 

**Describe the bug**
My Game Is Crash. i copy all mods to mods folder, i use sk launcher btw

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
This Is The Google Drive Link https://drive.google.com/file/d/1a8HJn2j_ydPDkivZaOYk2xQ024wCJqyn/view?usp=sharing .Pastebin give Me A Limit

**Screenshots**
No Screenshot

**Comment by ReCaree** [comment]
btw i dot have a premium account. in sklauncher is still work?

**Comment by MuteTiefling** [comment]
> btw i dot have a premium account. and is possible to play in sklauncher ?
> 

That's a hacked launcher. We won't support it. 

Buy the game from Mojang.
