### ISSUE TITLE
Sushi go crafting rice tag typo

### ISSUE THREAD

**Issue by Gambigobilla** [NillerMedDild/Enigmatica6#2633]
**Modpack version**
Enigmatica 6 0.5.3

**Describe the bug**
Small typo in "sushi go crafting" rice tags

Recipes check for "forge:grain" & "forge:grain/rice" tags, but sushi go crafting rice has  "forge:grains" & "forge:grains/rice" tags (notice the plural suffix)
can be found in file;
kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/grains.js

**Comment by NillerMedDild** [comment]
Ahh! Good catch, ty 😄
