### ISSUE TITLE
My POV is not where its supposed to be, it looks like im sneaking when im not. 

### ISSUE THREAD

**Issue by vnnnyy** [NillerMedDild/Enigmatica6#2635]
**Modpack version**
0.5.4

**Describe the bug**
my pov is very low, it seems as if im sneaking, even if i am not. On the 3rd pic, i am standing next to a crafting bench and i am not pressing shift.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![2021-07-05_21 04 10](https://user-images.githubusercontent.com/86977940/124502505-acfd0380-ddd4-11eb-843f-aa8199682b48.png)

![2021-07-05_21 06 33](https://user-images.githubusercontent.com/86977940/124502722-08c78c80-ddd5-11eb-863c-68f84d9e7020.png)

![2021-07-05_21 06 58](https://user-images.githubusercontent.com/86977940/124502732-0cf3aa00-ddd5-11eb-964e-4198c193fc55.png)

**Comment by Buuz135** [comment]
Press Ctrl + Z

**Comment by theboo** [comment]
pretty sure this is the shrink bug still present... i think we need to figure out a clear way to repro this for the dev to fix cuz i brought it up the the dev again and they closed my new issue almost immediately lol

**Comment by Darkere** [comment]
Any chance this is just the sitting feature? Had a similar issue when I accidentally hit that keybind

**Comment by vnnnyy** [comment]
i pressed CTRL and z and it just made me even lower.( 1st pick withoutctrl+z, 2nd pic with ctrl+z).

![2021-07-06_00 12 12](https://user-images.githubusercontent.com/86977940/124514815-f3f7f280-ddee-11eb-9ca5-76a10711955d.png)

![2021-07-06_00 12 17](https://user-images.githubusercontent.com/86977940/124514826-f6f2e300-ddee-11eb-98c0-b5c613e5346e.png)

**Comment by vnnnyy** [comment]
i also tried the shrinking device, and was hoping that was the case but no :(

**Comment by NillerMedDild** [comment]
For now I recommend that you remove the mod Shrink and restart the game.

**Comment by vnnnyy** [comment]
ok. one last thing, your POV should move whenever you sneak right, when i sneak my POV does not change, i dont really know how to explain it without recording a video though. Its like im on constant sneak.

**Comment by General-Mudkip** [comment]
Seems to be related to #2545

**Comment by Purpledennyson** [comment]
Removing the Shrink mod got rid of the sneak POV issue for me. Definitely an issue with that mod after using the shrinking device.

**Comment by vnnnyy** [comment]
i just removed it, and yeah it fixed itself! however can i still make compact machines and go in them?

**Comment by theboo** [comment]
Yes, this mod is unrelated to compact machines even if their devices have similar names xD

**Comment by NillerMedDild** [comment]
This might've been fixed in the Shrink mod, so it won't be removed in 0.5.5 after all - fingers crossed.
