### ISSUE TITLE
Livingwood Avatar (Botania) isn't working with the rods

### ISSUE THREAD

**Issue by Katon152021** [NillerMedDild/Enigmatica6#2638]
Version: 5.4

Using a Livingwood Avatar with a mana spreader binded to it and a healthy flow of mana flowing, the avatar should use whichever rod is has in its hand and perform a certain function. I utilized a "Rod of the Lands" to place down dirt using mana and it wouldn't work. I unclaimed my land and still not working. The Rod of the Skies also didn't work with the avatar. This was working in 5.2 prior to updating to 5.4. 

See pictures for reference. 

![2021-07-05_20 52 57](https://user-images.githubusercontent.com/85213540/124535843-7a570900-dddc-11eb-9bf3-2c5a914078c8.png)
![2021-07-05_20 54 52](https://user-images.githubusercontent.com/85213540/124535844-7c20cc80-dddc-11eb-8a78-08316939e17d.png)
![2021-07-05_20 55 52](https://user-images.githubusercontent.com/85213540/124535848-7d51f980-dddc-11eb-9ea8-0f663a1b9691.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
Can reproduce this one with only Botania.
