### ISSUE TITLE
[Mod Suggestion] Mystical World

### ISSUE THREAD

**Issue by General-Mudkip** [NillerMedDild/Enigmatica6#2639]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/mystical-world

**Mod description**
Adds in 9 new mobs, ores (silver, copper, and amethyst + their tools), Aubergines (a new crop), as well as 2 (3?) new small structures. There are some other small miscellaneous stuff.

**Why would you like the mod added?**
I feel like E6 is lacking somewhat in overworld mobs, and so I believe that this mod adds a great variety of balanced mobs without going completely overboard into the OP territory, like I&F or Mowzie's Mobs. _(And you can get a beetle to ride on your shoulder)_

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/70416146/124576812-942c3680-de44-11eb-8aa0-985ad0b7f327.png)
_Owls, Silk worms, Deer, Lava cats, Beetles (pog), Frogs, Foxes, Enderminis, and Sprouts_
![image](https://user-images.githubusercontent.com/70416146/124576892-adcd7e00-de44-11eb-8d68-6d2133644eb9.png)
_Barrow_

**Comment by MuteTiefling** [comment]
I'd love to see the sprouts back, but almost every other feature of this mod is directly duplicated by another mod in the pack.

**Comment by NillerMedDild** [comment]
Too much duplicate content, and I don't think we really need any of the things the mod adds tbh.
