### ISSUE TITLE
Flowers have extreme offsets

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#264]
**Modpack version**
0.2.16

**Issue**
Flowers (including Botania flowers, and I assume everything else that gets an offset) have extreme offsets. Much larger than the normal vanilla ones.

**Logs**
No crashing

As you can see in the center of the picture, three flowers are almost merged together despite being placed on different blocks. Never seen this in vanilla. Something seems to be making the offsets even larger.

![2020-09-10_01 53 30](https://user-images.githubusercontent.com/1980813/92699111-681a5480-f30a-11ea-9981-932d096795a5.png)

![2020-09-10_02 01 29](https://user-images.githubusercontent.com/1980813/92699210-884a1380-f30a-11ea-8c5a-88e42999df53.png)

**Comment by NillerMedDild** [comment]
Do you have the Enigmatica Resource Pack enabled?

**Comment by MuteTiefling** [comment]
I can confirm this was happening to me before installing ERP. It continued afterwards, as well.

**Comment by NillerMedDild** [comment]
Hmm, could be Botania then. I don't see it as a much of an issue though to be honest.

**Comment by Ridanisaurus** [comment]
I can confirm that it is not related to ERP. This is from a YouTube video, someone playing E6. 
![image](https://user-images.githubusercontent.com/64355028/92794125-8c7c3c80-f3af-11ea-883b-3c66b79b4d9d.png)

**Comment by Ridanisaurus** [comment]
The flower can spawn up to 1-2 blocks away sometimes :D

**Comment by NillerMedDild** [comment]
...Yeah alright :P

**Comment by NillerMedDild** [comment]
This is with only Botania + JEI + Patchouli:
![billede](https://user-images.githubusercontent.com/21295394/92803174-73778980-f3b7-11ea-9057-084e146882d0.png)

Same offset or less?

**Comment by MuteTiefling** [comment]
That actually looks normal, for the most part. They're offset, but not overlapping. I'll try to get some better screenshots together and tearing mods out of the pack. It's not only with Botania flowers, however. It's all plants. Grass, vanilla flowers, etc.

**Comment by MuteTiefling** [comment]
Ok, first test: Here's default E6:

![2020-09-10_21 06 05](https://user-images.githubusercontent.com/9543430/92835655-82573f80-f3a9-11ea-8798-2485e8c6090d.png)

You can see some of the goofier spots like this:

![2020-09-10_21 06 53](https://user-images.githubusercontent.com/9543430/92835741-9ac75a00-f3a9-11ea-82e7-b731a473e5fe.png)

And this, where the flower is visibly off the block:

![2020-09-10_21 07 46](https://user-images.githubusercontent.com/9543430/92835843-c0ecfa00-f3a9-11ea-89fc-27213b763444.png)

By contrast, here's a shot with just JEI and Building Gadgets (used to copy/paste the layout).

![2020-09-10_21 15 43](https://user-images.githubusercontent.com/9543430/92836865-e595a180-f3aa-11ea-9493-c21a79e54218.png)

I pasted it a few times and scanned around and can't find anything that's overlapping like in the first set. 

![2020-09-10_21 17 01](https://user-images.githubusercontent.com/9543430/92836944-fe05bc00-f3aa-11ea-9438-2bf7fdec0ba9.png)

I'll now try pulling out mods and see if I can narrow it down.

**Comment by MuteTiefling** [comment]
Alright, have not found the mod yet, but I have discovered it is a config option. One of the first things I did before I started ripping out mods was to delete all of the configs. Regenerating basic configs immediately resolved the issue. So it's probably some decorative option or some such in one of the terrain mods or more decorative mods.

**Comment by MuteTiefling** [comment]
.... And it's Forge itself. 

experimentalForgeLightPipelineEnabled = true

**Comment by NillerMedDild** [comment]
Ah lovely, that explains why I'm not seeing it in-dev. Fixed in 0.2.17 when that gets out.
