### ISSUE TITLE
Vitality Enchantment bonus hearts don't stay upon relogging

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#2641]
**Modpack version**
0.5.4

**Describe the bug**
Hello,
Every time I relog, my extra hearts from my Vitality VI enchant are gone. So I need to eat to regain them every time.

**Screenshots**
Before relogging : 
https://imgur.com/a/siBUOlI
After relogging : 
https://imgur.com/a/1kaEeMp

**Comment by NillerMedDild** [comment]
Known issue, caused by how vanilla Minecraft handles health, unfortunately nothing can be done to fix it :(
https://discord.com/channels/399037120930512897/434101214548852746/840301085600120863

**Comment by jinkhya** [comment]
Ah fair enough, thanks for the answer !
