### ISSUE TITLE
[Mod Suggestion] More Crafting Tables for Forge

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2643]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/more-crafting-tables-for-forge

**Mod description**
Make every Crafting Table with their respective wood type so it can fit with your style, and do fun and good looking decorations with it without ruining the look of your house.

**Why would you like the mod added?**
Simple, little and clean mod that adds more wood types of crafting tables: I felt that this one was missing. I suppose, for compatibility with recipes it is needed to make a conversion recipe to the normal crafting table like it's already done with the vanilla chest.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/81813584/124636030-62d55a00-de88-11eb-903f-99da776d57a8.png)

**Comment by NillerMedDild** [comment]
Hmm.. Sure I guess :P
