### ISSUE TITLE
Make XP fluids compatible

### ISSUE THREAD

**Issue by Fuggschen** [NillerMedDild/Enigmatica6#265]
**Modpack version**
0.2.16

**Suggestion**
The XP Fluid from Industrial Foregoing (from a Mob Crusher e.g) has to be slurped with a straw while the Essence from Pneumaticcraft can be directly inserted into the player with the Aerial Interface. 
But vice versa we can extract the XP from a player into Essence but can't use it in an Enchanter from Industrial.
It would be nice, if we can convert these fluids into each other

**Comment by MuteTiefling** [comment]
As long as you're extracting Industrial Foregoing Essence from the Aerial Interface, this should already be possible: 

![image](https://user-images.githubusercontent.com/9543430/92779059-ba419100-f36f-11ea-8ebc-48aaba0e928f.png)

In fact, this would let you convert any source of XP into IF Essence by using the player as an intermediary.

**Comment by NillerMedDild** [comment]
We'll see if we can make some explicit conversion :)

**Comment by douyabian** [comment]
this would be nice, since modular routers XP augments don't do IF essence atm

**Comment by NillerMedDild** [comment]
![billede](https://user-images.githubusercontent.com/21295394/98734540-5ef94280-23a2-11eb-8d6c-491241a6441f.png)
