### ISSUE TITLE
BUG - Loading into self-destructing Bamboo forest

### ISSUE THREAD

**Issue by Xenthori** [NillerMedDild/Enigmatica6#2651]
**Modpack version**
0.4.14
**Describe the bug**
Having loaded into a world started the previous night and after an uneventful game closure and boot u p, there was a large lag spike and suddenly all bamboo in the nearest Bamboo Forest biome begin to slowly destroy themselves at the base and further exploring into the biome continued this behavior. All the bamboo did not break at once, instead a few breaking at a time until all bamboo in the chunk was destroyed. Performance was obviously poor during the bug's duration due to the number of bamboo items on the ground

**Logs**
latest.log https://pastebin.com/7iJCCjzj

**Screenshots**

![](https://cdn.discordapp.com/attachments/671111454606491658/862188372259766292/unknown.png)
bamboo forest during 1st launch of world, non-anomalous

 
![image](https://user-images.githubusercontent.com/86328460/124776744-4d524580-df05-11eb-9262-44a69eb61273.png)
decimated bamboo forest, bamboo in background slowly self-destructing

https://user-images.githubusercontent.com/86328460/124777077-8ee2f080-df05-11eb-98e4-98af9c72f081.mp4
bamboo actively self-destructing, framerate low due to number of items on ground

https://user-images.githubusercontent.com/86328460/124777130-9aceb280-df05-11eb-884a-d149801ae32e.mp4
destroyed biome with tons of dropped bamboo all over the ground, framerate low due to number of items on ground

**Comment by g0urra** [comment]
Can you update to the latest version (0.5.4) and see if the problem persist?

**Comment by Xenthori** [comment]
Was not aware I wasn't on latest release, updated and the the ecological damage has been halted. Thanks.

What a bizarre bug.
