### ISSUE TITLE
Unable to extract Ender Farmer's Lead from Storage Scanner

### ISSUE THREAD

**Issue by EvaisaGiac** [NillerMedDild/Enigmatica6#2652]
It seems to be impossible to remove the Ender Farmer's Lead from a Storage Scanner in the latest version of Enigmatica 6.
This was not a problem in the 4.0 version as far as I can remember.
I saw someone else also reported this issue but it was closed, I also commented on that report but since it is closed I thought I should open a new issue.
Note that the original issue said it was when using the tablet but neither using the tablet or interacting with the Storage Scanner directly lets you retrieve them. You can only retrieve them when grabbing directly from the Modular Storage units
#1265 

Here is a video:
https://www.youtube.com/watch?v=XoMubmCCYQw

**Comment by NillerMedDild** [comment]
I'd rather have comments on old issues than having duplicates, will answer in the other issue :)
