### ISSUE TITLE
Max Health Fix

### ISSUE THREAD

**Issue by ochotonida** [NillerMedDild/Enigmatica6#2653]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/max-health-fix

**Mod description**
Max Health Fix fixes a [vanilla bug](https://bugs.mojang.com/browse/MC-17876) that causes the `Max Health` attribute to be ignored when a player joins the game.

**Why would you like the mod added?**
It fixes #2641

**Comment by NillerMedDild** [comment]
Oh awesome, thanks!
