### ISSUE TITLE
Recipe to craft sawdust block [alternate recipe for sawdust flooring]

### ISSUE THREAD

**Issue by Random832** [NillerMedDild/Enigmatica6#2654]
**Description**
Recipe for Thermal Expansion sawdust block. Currently Thermal sawdust item is unobtainable, and Emendatus sawdust item 3x3 is 9 Immersive Engineering sawdust flooring. My suggestion would be to make sawdust flooring a 2x3 recipe instead.

**Why would you like this added/changed?**
Sawdust blocks are a more efficient fuel than charcoal for the amount of wood used

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
