### ISSUE TITLE
Some new quest ideas to Mekanism questline

### ISSUE THREAD

**Issue by TheKapec** [NillerMedDild/Enigmatica6#2655]
**Description**

Couple of ideas for some more Mekanism quests:

- Robit > Digital Miner (There was a meme including popular Rick and Morty scene how Robit's only purpose is to be crafted into Digital Miner, but unfortunately I can't find it, was quite hilarious tho as this is pretty much always true for me lmao)
- Ultimate Induction Cell + Ultimate Induction Provider
- 3x Ore Processing (Any Ore Clump)
- 4x Ore Processing (Any Ore Shard)
- 5x Ore Processing (Any Ore Crystal)
- Precision Sawmill > Cardboard Box (Cheap and fast way of picking up Spawners)
- Teleporter + Teleporter Frame
- Any Tier Installer (or all of them)

**Why would you like this added/changed?**

I feel like the Mekanism questline doesn't really show quite everything good that the mod has to offer (looking at you Digital Miner), while I don't feel like this list is complete, it definitely adds some interesting stuff to achieve. The machines/tasks needed to get the reward obviously are subject to change, however developers feel.

**Screenshots if applicable.**

---

**Comment by MuteTiefling** [comment]
- [ ] Robit > Digital Miner (There was a meme including popular Rick and Morty scene how Robit's only purpose is to be crafted into Digital Miner, but unfortunately I can't find it, was quite hilarious tho as this is pretty much always true for me lmao)
- [ ]  Ultimate Induction Cell + Ultimate Induction Provider
- [ ]  3x Ore Processing (Any Ore Clump)
- [ ]  4x Ore Processing (Any Ore Shard)
- [ ]  5x Ore Processing (Any Ore Crystal)
- [ ]  Precision Sawmill > Cardboard Box (Cheap and fast way of picking up Spawners)
- [ ]  Teleporter + Teleporter Frame
- [ ]  Any Tier Installer (or all of them)
