### ISSUE TITLE
Balanced Enchanting

### ISSUE THREAD

**Issue by EnigmaticaGH** [NillerMedDild/Enigmatica6#2656]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/balanced-enchanting

**Mod description**
This mod makes vanilla enchanting and anvils cost the same amount of XP regardless of level. I.e. they cost X levels of XP rather than X levels.

**Why would you like the mod added?**
This mod would make vanilla enchanting and anvils more convenient to use and not 'waste' experience levels if you have a lot of levels.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion. I think this would more or less break the balance of Apotheosis, so it's gonna be a no :)
