### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by Garebear13** [NillerMedDild/Enigmatica6#2657]
**Modpack version**
Server 0.5.4

**Describe the bug**
Server cannot start, crashes every time i try to launch through start-server.bat.

**Logs**
https://pastebin.com/5T7dAMc1

**Comment by Darkere** [comment]
You are trying to run with java 16.

Java 8 is still a recommended. Up to 15 works. but 16 requires  some special arguments to work. Easier to downgrade.
