### ISSUE TITLE
Game crash when using IF recipes in JEC

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2658]
**Modpack version**
0.5.2

**Describe the bug**
Trying to add an IF recipe, possibly with fluid (in this case Latex), when using the Just Enough Calculations calculator can cause the game to crash ("Saving World" and exiting). In my case it was looking up Efficiency Addon +2 and Simple Machine Frame.

**Logs**
Crash report: https://pastebin.com/ENjUsN6E

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it :)

**Comment by Towdium** [comment]
I can't really reproduce it. Does the crash always happen? But whatever, I can add some protection to prevent the crash.

**Comment by NillerMedDild** [comment]
To be honest I'm not sure how the Crafting Calculator works, couldn't really figure it out to test it 😅

**Comment by NillerMedDild** [comment]
This might've been fixed on IF's side as well 😄
