### ISSUE TITLE
electrolytic separator wont register the energy upgrades

### ISSUE THREAD

**Issue by tiltedmatt** [NillerMedDild/Enigmatica6#2659]
**Modpack version**
0.5.4

**Describe the bug**
The Electrolytic Separator accepts Energy Upgrades but they don't actually do anything. With 8 Speed Upgrades the machine uses 40k RF/t and it does not budge with any amount of Energy Upgrades.

**Comment by Darkere** [comment]
This is intended. The energy upgrades only increase the size of the buffer. This is done by mekanism to avoid positive power loops with the gas burning generator. 

(this is stupid yes, but what the mek devs decided on)
