### ISSUE TITLE
Game Crash - Clicking on the Dank Dock with a Mekanism Configurator

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#266]
**Modpack version**
E6 0.2.16

**Issue**
While it's not that likely to open, it is still possible that someone might click with the Meka Configuration Tool on a Dank Dock.
The game crashes as per the attached log.
This issue was reported by Nunbear on Discord, and I was able to replicate it.

**Logs**
https://gist.github.com/Ridanisaurus/d2fa4995e8c4c32f7d4322fd0e33b78f
https://gist.github.com/Ridanisaurus/5689415a410b6f7616e2edeacb175164

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
relayed here: https://github.com/Tfarcenim/Dank-Storage/issues/71

**Comment by NillerMedDild** [comment]
Will be fixed when we move to 1.16.2/3 :)
