### ISSUE TITLE
Repurposed Structures crash on startup

### ISSUE THREAD

**Issue by Fabizocker456** [NillerMedDild/Enigmatica6#2660]
**Modpack version**
0.5.4
**Describe the bug**
Starting the server crashes it while startup, due to Repurposed structures.
I've started the server multiple times now, crashed every time

**Logs**
https://hastebin.com/lujiyikoka.md

**Comment by Darkere** [comment]
`Invalid character 'a' after key [ns]`

Any chance you've modified the config? Otherwise are you maybe on a non english system language?

**Comment by Fabizocker456** [comment]
Nope--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 09.07.21, 16:50 schrieb Darkere ***@***.***>:

   
  Invalid character 'a' after key [ns] 
  Any chance you've modified the config? Otherwise are you maybe on a non english system language?

**Comment by Fabizocker456** [comment]
No
I could try fixing it myself, though.

**Comment by Fabizocker456** [comment]
I'VE FREAKING FOUND IT
It was a line break in the comment where it says aout the end islands
