### ISSUE TITLE
PSA - Server Crash with Crusher Demon and Emendatus Enigmatica

### ISSUE THREAD

**Issue by MokahTGS** [NillerMedDild/Enigmatica6#2661]
We are getting a bad server crash with the Enigmatica 6 modpack and using the crusher demon. Giving the demon an ore chunk from the Emendatus Enigmatica mod causes the crash.

I posted a bug report on the Occultism Github: https://github.com/klikli-dev/occultism/issues/287

**Comment by NillerMedDild** [comment]
Thanks for the report. The next time you report a bug, please use the bug template, and specify modpack version :)

**Comment by MokahTGS** [comment]
Ah...well it wasn't your big, but ok
