### ISSUE TITLE
quests reset when joining new ftbteams team

### ISSUE THREAD

**Issue by Consumate-z** [NillerMedDild/Enigmatica6#2662]
my quests were reset when i joined a new ftbteams team, as the title says.

proof quests were reset
![2021-07-09_12 37 29](https://user-images.githubusercontent.com/61160533/125110412-8845ac00-e0b2-11eb-9d10-f8617a672b08.png)

proof i had completed them in the first place
![2021-07-09_12 37 38](https://user-images.githubusercontent.com/61160533/125110579-c17e1c00-e0b2-11eb-8d29-f2798483a323.png)

**Comment by TemperedFool** [comment]
I'm not sure what's going on in the second screenshot; what pack version is this, and what version was the world created in?

**Comment by Consumate-z** [comment]
the latest for both of them, the second picture was to show that i have mekanism machines while none of the quests were complete

**Comment by NillerMedDild** [comment]
@MaxNeedsSnacks halp?

**Comment by MaxNeedsSnacks** [comment]
Non-issue, quest progress is bound per team, and the player only transfers their own *personal* progress upon joining another

(Anything other than this would make cheating the progression just a little **too** easy lol)

**Comment by TemperedFool** [comment]
> Non-issue, quest progress is bound per team, and the player only transfers their own _personal_ progress upon joining another, so unless this was you creating your first party, this is working as intended ^^

@MaxNeedsSnacks if someone on a team complete's a quest that has a dependency THEY didn't complete, will they still have credit for it if they leave the team?

**Comment by MaxNeedsSnacks** [comment]
No, every quest completed as part of a team will stay part of the team's progress.

**Comment by NillerMedDild** [comment]
Alright, thanks for clearing that up.

**Comment by Consumate-z** [comment]
my bad i didnt realize it was intended functionality
