### ISSUE TITLE
Remove trash function from Quark

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2667]
**Description**
Disable the Quark trash function on lava buckets in the inventory.

**Why would you like this added/changed?**
There is already a trash slot in the inventory.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/12349921/125144477-536f3e80-e11e-11eb-960a-0c5643075efc.png)

**Comment by Katon152021** [comment]
Disagree, I think this is a good feature. Plus, you can disable on mouse tweaks :)

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll consider it :)

**Comment by NillerMedDild** [comment]
Done, it didn't work anyway due to a conflict with mouse tweaks.
