### ISSUE TITLE
Crash related to gravestones on Enigmatica 6 0.5.4

### ISSUE THREAD

**Issue by MonoHutas** [NillerMedDild/Enigmatica6#2668]
Enigmatica 6 0.5.4

When i die i respawn like im outside of my body, i cant interact whit anything, i can even kill myself, i can see my body close to me and when i try to eat or do something the game crashes

**Logs**
https://gist.github.com/MonoHutas/1f71c768e3be2bcb259476781289de2e

![2021-07-09_21 01 13](https://user-images.githubusercontent.com/87212673/125145740-eac19b00-e0f8-11eb-92ca-6ad8f4b184f8.png)
![2021-07-09_21 01 17](https://user-images.githubusercontent.com/87212673/125145746-ed23f500-e0f8-11eb-9dc0-1064cd2222f3.png)
![2021-07-09_21 01 21](https://user-images.githubusercontent.com/87212673/125145748-ee552200-e0f8-11eb-8788-21272a41ee4b.png)

**Comment by MuteTiefling** [comment]
I notice you're using an old version of Java. Could you update it please and see if this behavior continues?

**Comment by TeezeR-22** [comment]
same problem #2704 fix in next update
