### ISSUE TITLE
Remove the Interactio logs->driftwood fluid recipe

### ISSUE THREAD

**Issue by Zennle** [NillerMedDild/Enigmatica6#2669]
**Description**
Removing that particular recipe from the pack would allow for breaking submerged logs without them turning into driftwood.

**Why would you like this added/changed?**
I placed logs underwater to act as decorative support beams before realizing I misplaced them. Breaking them to replace them in the right spot caused the logs to immediately turn to driftwood, which is annoying. There's also already a Create washing recipe for turning logs to driftwood.

**Screenshots if applicable.**

**Comment by MuteTiefling** [comment]
I do rather like this recipe, but maybe it needs a catalyst to prevent this sort of interaction. Or maybe have it require 32 so it really can't happen accidentally very easily?

**Comment by NillerMedDild** [comment]
Requiring 32 would be a good temporary fix, when Interactio updates it'd be cool to have it only convert after a minute or two.
