### ISSUE TITLE
Minor KubeJS recipe errors

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica6#267]
**Modpack version**
0.2.16

**Issue**
Some of the generated KubeJS recipes fail to register, either because of faulty syntax, or because they're being called for invalid tags like `forge:gems/iron`. This probably isn't much of an issue on its own, but it bloats log files with loads of warnings and, as the amount of total "materials" in scripts increases, it might also increase reload times by a fair bit.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5201987/latest.log)

**Comment by MaxNeedsSnacks** [comment]
Also, those triple equals should probably be replaced with double equals, as the variable `air` may be a different instance of the string "minecraft:air" than the one returned by `getPreferredItemInTag(tag).id`.

Nashorn checks equality using `.equals()` if you do double equals (`==`), while triple equals makes it expect strict equality.

**Comment by NillerMedDild** [comment]
Ahh that explains it, thanks :D
