### ISSUE TITLE
(Mod suggestion) Muffle

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2670]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/muffle

**Mod description**
A minecraft mod which adds the Sound Muffler, a block which mutes nearby sounds.

**Why would you like the mod added?**
Enables the player to muffle sound in certain areas, unlike the Muffler mod that changes sounds in general. One example would be to silence mob farms, but still be able to hear the mobs while in the overworld (e.g. wither skeletons).

**Comment by theboo** [comment]
you can set anchors in ESM to disable sounds in a certain radius

**Comment by g0urra** [comment]
While I understand that is something that is possible, that seems incredibly convoluted to the normal user.

**Comment by NillerMedDild** [comment]
Good point, I'll have a look.

**Comment by NillerMedDild** [comment]
Erhm... this is a fabric mod
