### ISSUE TITLE
Recipe conflict processing end stone in crushing wheels

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#2677]
**Modpack version**
0.5.4
**Describe the bug**
Processing End stone in crushing wheels from create have two different outputs, end sand from byg and crushed end stone from occultism. 
Possible workaround could be to change one input or the other to endstone bricks. So for example processing endstone bricks would give you the byg end sand while normal end stone would give occultism crushed end stone. (I imagine there are more people making occultism stuff than the byg end sand)

**Screenshots**
![image](https://user-images.githubusercontent.com/10158963/125160074-4f253e80-e17b-11eb-8e46-c15a4bd08f7e.png)

**Comment by MuteTiefling** [comment]
All the other crushing recipes are making the occultism dust. Removed the end sand crushing recipe and added a stonecutter recipe to swap between byg/betterend endstone sands.

**Comment by jinkhya** [comment]
sounds good ! ty
