### ISSUE TITLE
Artifacts being deleted on opening grave

### ISSUE THREAD

**Issue by Sarelth** [NillerMedDild/Enigmatica6#2683]
Version 0.5.4

I had several artifact trinkets in my trinkets slots, all with soulbound, when I died. I replaced the trinkets in their slots as they were soulbound and then went to regain my grave. As I activated the grave, the trinkets were thrown out of the slot and with all the other items filled my inventory, there was slightly less space in my inventory due to my grave and 3 of the artifacts vanished from existence. If they were the unlucky ones that never made it into my inventory, they just poofed.

**Comment by theboo** [comment]
The latest version of enigmatic graves fixed a similar issue.. it isn't in e6 yet.. I'll test this in a bit to see if it's still an issue, if it's fixed you can just update to latest version in your pack

**Comment by theboo** [comment]
Can confirm that the curios no longer get deleted after death with a full inventory, they now get dropped on the ground... I'll make an issue on the EG tracker for the soulbound interraction though

**Comment by theboo** [comment]
Just tested soulbound enchant on curios without enigmatic graves installed, and they do not remain in the curio slots, so i think this is more of an issue for enscorcellation than EG xD Which being a cofh mod, prolly not much chance of that interaction happening this century, also no github to suggest it in lol

**Comment by Darkere** [comment]
Lemming kind of hid the 1.16 github of the cofh mods. You can find them github here: https://github.com/KingLemming/1.16

**Comment by Sarelth** [comment]
Added a probably badly worded issue to KingLemmings git. I forgot to put on my glasses so I hope it was at least mildly readable.
