### ISSUE TITLE
can not open server

### ISSUE THREAD

**Issue by Holy-Fak** [NillerMedDild/Enigmatica6#2684]
server 0.5.4

just stuck at version check, like the picture.

![image](https://user-images.githubusercontent.com/63405709/125170819-74e62e00-e1e3-11eb-8ab8-cbee61c14b76.png)

**Comment by NillerMedDild** [comment]
Please fill out the issue template, logs and modpack version are missing.

**Comment by Holy-Fak** [comment]
modpack version: Enigmatica 6 Server 0.5.4
