### ISSUE TITLE
[0.5.4] IF Ore Laser gives unprocessable Aquamarine Shale

### ISSUE THREAD

**Issue by Rottastic** [NillerMedDild/Enigmatica6#2686]
**Modpack version**
E6 - 0.5.4

**Describe the bug**
When mining for Aquamarine Shale, using the Industrial Foregoing Ore Laser, the world-gen ore is produced. There are no processing recipes associated, so the only option is to place it in-world and dig it up for the resulting gem. Processing is of course possible via placers and breakers, but seems very off-theme and therefore unintended.

**Screenshots**
![image](https://user-images.githubusercontent.com/4677358/125171483-56435100-e169-11eb-9583-e3019cc5ba2a.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I gave it a smelting recipe only, the best way remains fortune-ing it :)
