### ISSUE TITLE
Nuclear Waste not going into Chemical Tank

### ISSUE THREAD

**Issue by Purpledennyson** [NillerMedDild/Enigmatica6#2689]
E6 0.5.4

Nuclear waste is not going into a chemical tank even though there is an item in JEI for it stating it can, do not know if this was supposed to be removed or is not working correctly.

Added screenshots of issue.

![2021-07-10_19 30 23](https://user-images.githubusercontent.com/86135547/125179602-4cdfd600-e1b5-11eb-8aa6-8de17f64f69a.png)
![2021-07-10_19 30 24](https://user-images.githubusercontent.com/86135547/125179603-4e110300-e1b5-11eb-9614-4c92ab29d28c.png)
![2021-07-10_19 27 57](https://user-images.githubusercontent.com/86135547/125179590-376aac00-e1b5-11eb-985d-d33ef660fd3f.png)

**Comment by MuteTiefling** [comment]
intended by mekanism. you can't store nuclear waste in chemical tanks. only in pipes/waste barrels. it also cannot be passed through entangloporters
