### ISSUE TITLE
Misspelling in Lexica Botania

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2691]
**Modpack version**
0.5.2 server

**Describe the bug**
Misspelling in Lexica Botania tome for Generating Flora.

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/125186495-f1502f80-e22a-11eb-9694-10fdda4d3923.png)

**Comment by MuteTiefling** [comment]
Ooops!
