### ISSUE TITLE
Problems placing torches on walls

### ISSUE THREAD

**Issue by SirTwsted** [NillerMedDild/Enigmatica6#2692]
Hi, I am playing the latest Enigmatica 6 (v6 0.5.4) on minecraft v1.16.5 using Curseforge
And I cant place torches on walls occasionally.  sometimes it will do it.  and then sometimes it wont.
Preventing me from spelunking while mining.   Just thought I would let someone know.

Anyways, thanks for reading 😎

**Comment by NillerMedDild** [comment]
Thanks for the report. Were you in a specific place when it failed, a dungeon or the like?

**Comment by SirTwsted** [comment]
No, I was in the overworld mining at level 13 thru 11.

**Comment by NillerMedDild** [comment]
Alright - I'm fairly certain this was a bug with Supplementaries cancelling some block placements, which has now been fixed :)

**Comment by SirTwsted** [comment]
Thank you 😊

**Comment by lexx1191** [comment]
hi, v0.5.9, the problem is still present, the torch should not be placed at any level of the mine and the surface, at any level of illumination

**Comment by NillerMedDild** [comment]
Singleplayer or server? It works just fine for me in 0.5.10

**Comment by lexx1191** [comment]
single, where to get 0.5.10?

**Comment by NillerMedDild** [comment]
It's available on CurseForge / GDLauncher etc, it's just an update :)

**Comment by lexx1191** [comment]
addition, hammer, excavator, cleaver, broad ax, torches are not placed, crafted kama, torches are placed

**Comment by lexx1191** [comment]
update 0.5.10, Likewise, maybe this is a feature of two-handed weapons and one-handed weapons?

**Comment by NillerMedDild** [comment]
It is indeed :)
