### ISSUE TITLE
(Mod suggestion) Blue skies

### ISSUE THREAD

**Issue by Mang0z** [NillerMedDild/Enigmatica6#2693]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/blue-skies

**Mod description**
Blue Skies adds two dimensions called the Everbright and the Everdawn. It includes lots of new unique features, blocks, weapons, mobs and even massive dungeons! Each dimension has its own theme, with the Everbright being very bright, snowy and cold while the Everdawn is typically darker and warm. Each of these dimensions currently has two dungeons to explore, totaling up to 4 dungeons, with more planned on the way!

**Why would you like the mod added?**
This mod is too good not to have in the pack tbh. I know we have Atum and Undergarden but i think this mod would be an amazing addition to the pack and would work perfectly alongside Undergarden and Atum the sheer amount of content it has is honestly amazing aswell. It brings vibes of the Aether while also maintaining the feel of vanilla mc 

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/76655777/125195404-b9aaad00-e255-11eb-85e2-c1f6df818c40.png)
![image](https://user-images.githubusercontent.com/76655777/125195408-bfa08e00-e255-11eb-85e7-1805e3b890a3.png)
![image](https://user-images.githubusercontent.com/76655777/125195417-c8915f80-e255-11eb-9c02-73312700b588.png)
![image](https://user-images.githubusercontent.com/76655777/125195423-d0510400-e255-11eb-9f92-5df24609c659.png)

**Comment by NillerMedDild** [comment]
That does look pretty amazing. I'll have a look.

**Comment by Erysch** [comment]
just wow! what's that

**Comment by QStinger** [comment]
Amazing dimension. Hope to see it in the next update!

**Comment by MuteTiefling** [comment]
Played around with it a bit, seems really cool. Tough bosses too

**Comment by NillerMedDild** [comment]
Agreed, it'll be quite a task to integrate it properly though. I'll mark this as accepted, so we can begin on integration :) I can't promise it'll be in the next update though.

**Comment by Mang0z** [comment]
So has integration started already? its been a while so im just checking in but i see you guys are really busy :)

**Comment by NillerMedDild** [comment]
I like this mod a lot, but I'm afraid it would be too much work to add at this point, and we don't really see how it would fit. If/when Blue Skies is ported to 1.18, it will be added to Enigmatica 8 :)
