### ISSUE TITLE
Craft marble and limestone from the Chisel mod using other variations

### ISSUE THREAD

**Issue by milibucket** [NillerMedDild/Enigmatica6#2694]
**Description**
A crafting recipe to convert one marble/limestone variant to another.  
For example: 
- put a single marble from quark into the crafting grid to convert it to the Chisel or Create variant. (since there is Polymorph the recipe conflict will not be an issue). 
- Or add a similar recipe in the stonecutter.

**Why would you like this added/changed?**
Currently inorder to use the Chisel mod's variant of marble and limestone, the player has to specifically look for the variant they want underground. 
Ways of switching between Quark and Create's variant is available in stonecutter but not for Chisel.

**Comment by TemperedFool** [comment]
Chisel marble generating in-world is actually a mistake (see #2636), but we do need to add stonecutter recipes for converting, if we haven't already in dev. Would have sworn there was already an issue about this...

**Comment by NillerMedDild** [comment]
Basalt, Limestone and Marble from Chisel can now be interchanged with other variants using a Stonecutter.

**Comment by NillerMedDild** [comment]
and our basalt, limestone and marbles variants can now be interchanged with the Chisel as well
