### ISSUE TITLE
Crashes on fresh install in the ATLauncher

### ISSUE THREAD

**Issue by Daenyth** [NillerMedDild/Enigmatica6#2695]
**Modpack version**
0.5.4

**Describe the bug**
I did a fresh install in the ATLauncher and created a new instance.

When I launched it, with all the default configuration, it crashed with `java.lang.NoClassDefFoundError: Could not initialize class malte0811.ferritecore.mixin.config.FerriteConfig`

First using AdoptOpenJDK 11, and then I changed to use AdoptOpenJDK 8, and it crashed similarly

**Logs**
With java 11: https://paste.atlauncher.com/view/207b442f-9c5d-45e6-b625-392993f0014e
With java 8: https://paste.atlauncher.com/view/03891bdd-3943-4451-8c32-55bc6d9fc8c0

**Comment by TemperedFool** [comment]
This would best be handled on the Enigmatica discord: https://discord.gg/mzRZhgRM
