### ISSUE TITLE
lag after update world to 0.5.4

### ISSUE THREAD

**Issue by GorrionCojonero** [NillerMedDild/Enigmatica6#2696]
**Modpack version** 0.5.4

Since I updated the world, when I explore new places, lag appears. I usually have  90-100 fps, but when I explore de world it drops to 0  every 4 or 5 seconds. That not happen before last update. I like this last update changes and I hope the solution isn´t back to previous version.

**Comment by NillerMedDild** [comment]
I'm afraid we can't do anything based on that alone. Your latest log might help a bit. 

Which version did you update from?

**Comment by GorrionCojonero** [comment]
Sorry for the poor info I gave you, I´m not sure how and what info share to you for help. Is my latest log  registered in any place? I was looking for that, but I´m a bit noob in this.

**Comment by NillerMedDild** [comment]
Your latest log is found in your minecraft instance, in the logs folder - It's called `latest.log` 
Updating from 0.4.x to 0.5.x could be causing issues, it was recommended to make a new world :)

**Comment by GorrionCojonero** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6797656/latest.log)
 
Is this usefull?

**Comment by NillerMedDild** [comment]
Hmm a bit. I see your Java is outdated, and that there may be some left over files from before the update. A fresh install might help, and so would updating Java :)

**Comment by GorrionCojonero** [comment]
I followed you tips and now my world works perfectly.Thank you so much!!!
