### ISSUE TITLE
 internal exception io.netty.handler.codec.decoderexception

### ISSUE THREAD

**Issue by EndyJGB** [NillerMedDild/Enigmatica6#2704]
**Modpack version**
0.5.4
**Describe the bug**
i am trying to join a friends sever and for some reason every time try it gives me this error  internal exception io.netty.handler.codec.decoderexception java,lang.indexoutofboundsexcpetion(51)+length(2) exceeds indexwright(51) pooledunsafedirectbytebuf( ridx51 widx51 cap51) i have tried looking up the error and saw it had to do with username length so i tried making it shorter and that didnt work and i dont really have any idea how to fix this, i had tried it with a fresh install of the modpack and it still gives me the error
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please provide your latest.log and the server's latest.log? :)

**Comment by TeezeR-22** [comment]
I had the same problem, it comes from "enigmaticgrave". Normally the problem is solved in the next update but to fix now it you have to delete enigmaticgraves_graves.dat path: world / data / enigmaticgraves_graves.dat

**Comment by EndyJGB** [comment]
alright thanks for letting me know, sorry i didnt respond til now, i ended up sending in the report just beofre i went to sleep.
