### ISSUE TITLE
Akashic Tome - No Driftwood Bookshelf Recipe

### ISSUE THREAD

**Issue by Isaac-Pollack** [NillerMedDild/Enigmatica6#2706]
0.5.4

Cannot craft Akashic Tome recipe using Driftwood Bookshelf

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
err, modpack version 1.82a? Which modpack are you playing?

**Comment by Isaac-Pollack** [comment]
E6, that is the version Curseforge displays sorry! Its the latest version :)
