### ISSUE TITLE
GH PR/Contribution Guidelines

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica6#2707]
**Description**
Would be helpful to have guidelines (like "PR to develop branch" in the readme: https://github.com/NillerMedDild/Enigmatica6

**Why would you like this added/changed?**
Suggestion by Droxo on discord; just a simple statement that PR's are allowed/welcome, and to PR to the dev branch, is probably sufficient. If there are other suggestions they'd be good to put in writing.

**Comment by NillerMedDild** [comment]
Done :) https://github.com/NillerMedDild/Enigmatica6/commit/db7bec22ac755dc17754c2056a8ca564d6d3bafe
