### ISSUE TITLE
Pressurized Reactor Chamber Speed

### ISSUE THREAD

**Issue by Paraxdq** [NillerMedDild/Enigmatica6#2708]
**Modpack version**
Latest (0.5.4)

**Describe the bug**
The Pressurized Reactor Chamber is extremly slow compared to the one in Valhelsia 3 (both without upgrades) or none modpack at all, despite it beeing the same mod version of mekanism and I also didn't find anything in the config files about it.
I have to build at least about 10 (with 5x speed and 8x energy upgrades) to sustain one gas-burning generator from mekanism.

**Logs**
No logs needed, they are no error reports during the gameplay

**Screenshots**
Its just the gui of the prc.

**Comment by MuteTiefling** [comment]
https://github.com/NillerMedDild/Enigmatica6/wiki/Mekanism

This is intentional
