### ISSUE TITLE
Patchouli mod manuals text formatting

### ISSUE THREAD

**Issue by ecomorg** [NillerMedDild/Enigmatica6#271]
**Modpack version**
Version: 0.2.16

**Issue**
Text of mod documentation books as delivered through Patchouli has formatting issues such that the text spills off the page, making it difficult to read. Also any links in the text have tons of white space around them.

![bug1](https://user-images.githubusercontent.com/69400824/92975294-ef281380-f455-11ea-858b-f234d093c1ba.png)
![bug2](https://user-images.githubusercontent.com/69400824/92975296-efc0aa00-f455-11ea-8b3f-25a4ed84580e.png)

**Comment by NillerMedDild** [comment]
Which mod docs have you checked so far? :)

**Comment by ecomorg** [comment]
Sorry, should have specified in my OP. The two screenshots are from the two books I've used so far from Patchouli, from PNC:R and Botania, respectively. I haven't investigated it further than that.

**Comment by AdamNisbett** [comment]
I can confirm that this error is also present in the Modular Routers, Transport, and Modded for Dummies books.  Seems to be consistently in all Patchouli guides that I've seen so far.  I would also note that there seems to be a larger margin on the right side of the page than needed which may be responsible for causing the overflow.

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/Vazkii/Patchouli/issues/306

**Comment by thephoenixlodge** [comment]
This was identified in Vazkii's discord a while ago to be a bug caused by emojiful

**Comment by NillerMedDild** [comment]
I see, thanks for the info - Has it been relayed to the Emojiful dev? Do you know what's causing it?
