### ISSUE TITLE
Shift n Scroll on Mac

### ISSUE THREAD

**Issue by hipsterjazzbo** [NillerMedDild/Enigmatica6#2716]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/shift-n-scroll-on-mac

**Mod description**
This mod make shift+scrolling actually work on MacOS 🎉 

**Why would you like the mod added?**
I use a Mac, and not being able to shift+scroll (for example to change the FTB Ultimate shape) is really annoying.

**Comment by TemperedFool** [comment]
I'm a mac guy myself and love this idea, but it may be a little niche...

**Comment by theboo** [comment]
Good news is it 100% works client side

**Comment by TemperedFool** [comment]
Yeah, I'm downloading it when I get back to my computer...

**Comment by hipsterjazzbo** [comment]
Agreed, just thought it might be a nice addition to save having to A) install it manually and B) know it exists at all. Mac Minecrafters aren't THAT uncommon.

**Comment by NillerMedDild** [comment]
@TemperedFool would you mind testing this out? It's in-dev :)

**Comment by TemperedFool** [comment]
Totally, will test tomorrow.

**Comment by TemperedFool** [comment]
Seems to work as advertised...
