### ISSUE TITLE
abnormals_core high impact on server CPU

### ISSUE THREAD

**Issue by SirArevacoso** [NillerMedDild/Enigmatica6#2717]
**Modpack version**
E6 0.5.4 Server

**Describe the bug**
In the server, while everything else works relatively smoothly, mobs move at like 1 frame per second. It affects mostly the whole world, but it is more noticeable in some areas. We tried clearing all the entities and various restarts to no avail. Spark showed abnormals_core taking more than 25% of the cpu usage, and it was almost entirely caused by EntityTrackingEvent. At one point mobs were mostly unresponsive and not a lot of entities were present, as can be seen in the mob list.

**Logs**
Spark profile of the server: https://spark.lucko.me/ypNP5dwCth
Forge Entity Mob List: https://pastebin.com/hHsdTGmX

Thanks for everything and keep up the great work.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
They replied here: https://github.com/team-abnormals/abnormals-core/issues/121#issuecomment-879970314

Could you try take another sample or 3 please?

**Comment by SirArevacoso** [comment]
Hello and thanks for the help.
After a lot of investigation we tracked the issue to a chunk loaded compact machine with a rftools spawner that should have been inactive for a long time due to consuming the little resources it had. Entering the compact machine caused an instant server crash, as a tick took more than 60 seconds to load. After finding the correct compact machine and deleting its related file, everything started working better.

Here are the .mca file from the deleted compact machine and a new spark profile, for if it could help tracking a possible bug. Also one of the crash reports caused by the compact machine has been attached.
https://pastebin.com/PknuNb2k
https://we.tl/t-O0Dzz5USGi
https://spark.lucko.me/ToYGZk5hYT

Again thanks for the help and sorry for being unable to provide more information.
