### ISSUE TITLE
Cardboard Box Can Dupe Constellation Papers

### ISSUE THREAD

**Issue by studkid** [NillerMedDild/Enigmatica6#2718]
**Modpack version**
0.5.4

**Describe the bug**
If you have constellation papers stored in a chest, then use a cardboard box on the chest, the constellation papers will pop out of the chest.  When removing the cardboard box, the original constellation paper will still be inside the chest.  Works on both vanilla and iron chest's chests.  Haven't tested it with any other inventories as of yet.

**Screenshots**
Before: 
![2021-07-13_21 46 23](https://user-images.githubusercontent.com/9309016/125552839-cb3547f2-4aab-413b-8e0f-132ca0f7511f.png)
![2021-07-13_21 46 27](https://user-images.githubusercontent.com/9309016/125552857-a84b4dde-c7c2-495c-af3e-5850fa9bd22b.png)
After:
![2021-07-13_21 46 37](https://user-images.githubusercontent.com/9309016/125552866-a63a5c17-f11b-43e9-9183-3e893768605d.png)

**Comment by MuteTiefling** [comment]
Has been reported to Mek/Astral. Not much more to be done about it.
