### ISSUE TITLE
Mod: Construction Wand

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica6#272]
https://www.curseforge.com/minecraft/mc-mods/construction-wand

Works akin to `Better Builders Wands` back in 1.12, could be a nice energy-less alternative to building gadgets ^^

**Comment by Ridanisaurus** [comment]
I think building wands while cool, they are a clutter while we have a much better option such Building Gadgets. I know it requires power, but I think that what makes it balanced
Maybe in a SkyBlock settings, then sure, building wand could come in handy until the Building Gadget is obtained
but for standard E6, I think Building Gadget is more than sufficient to fill that role. Just my opinion.

**Comment by NillerMedDild** [comment]
I completely agree with Rid I'm afraid.
