### ISSUE TITLE
(Mod Suggestion) Botanical Machinery

### ISSUE THREAD

**Issue by ecco-tony** [NillerMedDild/Enigmatica6#2723]
**CurseForge Link**
[https://www.curseforge.com/minecraft/mc-mods/botanical-machinery](https://www.curseforge.com/minecraft/mc-mods/botanical-machinery)

**Mod description**
Botanical Machinery - will help you automate basically everything from Botania. Quite uncommon in the world of Botania, this mod adds plenty of machines. Helps take the chore out of making all the redstone, crates, droppers, etc.

**Why would you like the mod added?**
With Mythic Botany, why not allow us to automate everything we did to get to Myhtic Botany. Automating runes and even mana batteries would be awesome. This would just help us that like to be minimal and compact or those of us that want to automate all the things.

**Screenshots if applicable.**
![all-machines](https://user-images.githubusercontent.com/42568579/125587539-96b3f6f4-2cc2-45e5-a92e-4566f2da857d.png)

**Comment by NillerMedDild** [comment]
I do not like the premise of this mod one bit, Im afraid it's a no.
