### ISSUE TITLE
modpack manifest 5.0+

### ISSUE THREAD

**Issue by monk64** [NillerMedDild/Enigmatica6#2724]
version 5.0+

recive error 'failed to get modloader from manifest' when trying to download pack via curseforge any lower versions work

![failed](https://user-images.githubusercontent.com/65339482/125655964-e9f22909-72f9-4728-9031-9a252b4c0e90.JPG)

**Comment by Darkere** [comment]
Curseforge is having issues right now. Nothing we can do but wait for them to fix it.
