### ISSUE TITLE
Limestone chest with wrong tags

### ISSUE THREAD

**Issue by 12-4-25** [NillerMedDild/Enigmatica6#2725]
**Modpack version**
Enigmatica6-0.5.4

**Describe the bug**
Limestone chest should not have the forge:armor/chest and forge:armor tag

**Screenshots**
![image](https://user-images.githubusercontent.com/79115447/125656653-0df44602-819e-4fc0-8a14-1b623f8e9fa1.png)

**Comment by NillerMedDild** [comment]
Fixed, ty!
