### ISSUE TITLE
ftbchunks-server configs incorrect.

### ISSUE THREAD

**Issue by Splutty** [NillerMedDild/Enigmatica6#2728]
**Modpack version**
0.5.X

**Describe the bug**
defaultconfigs/ftbchunks-server.toml is not being properly populated in worldsave/serverconfig, the file there is ftbchunks-server.json5, and has different default values than the one in defaultconfigs (so assumedly gets written by FTB with their default settings)

**Comment by Darkere** [comment]
I may or may not have passed this on already. https://github.com/NillerMedDild/Enigmatica6/commit/d4627d9fc53ff01f1d23fd4125138eddd3159506

**Comment by Splutty** [comment]
Heh. Based on my comment in Discord I take it :) Okay good!
