### ISSUE TITLE
Enigmatica graves bug

### ISSUE THREAD

**Issue by Robbiiieee** [NillerMedDild/Enigmatica6#2729]
**5.4**

**Enigmatica graves**
Basically the player died and upon death instead of hitting respawn was logged out of the game, Upon relog player could not respawn, after restart player could respawn but could not do anything but hit himself. Upon death player then became ghostlike and unable to access anything in the server.

**Logs**
Attached files I have. Had to go to a different modpack currently until fixed because world is currently broken. Don't worry, I'll be back, 

[2021-07-14-1.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/6818235/2021-07-14-1.log.gz)
[2021-07-14-2.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/6818239/2021-07-14-2.log.gz)

**Comment by Darkere** [comment]
This is why 5.6 was released.

**Comment by Robbiiieee** [comment]
It's in Alpha. Bisect doesn't like alpha, So yeah..... delt with it all morning.
