### ISSUE TITLE
Emandatus enigmatica blocks cannot be used for RFTools dimlet creation

### ISSUE THREAD

**Issue by Roukurai** [NillerMedDild/Enigmatica6#2730]
**Modpack version**
0.5.6
**Describe the bug**
the blocks tagged from Emandatus enigmatica are not usable for the creation of RF Tools dimlets for dimension creation. They have to be stonecut into the other mod variants, causing for the need to have separate versions of the same ore, as the dimensions will generate with the other mod's block.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Fixed in-dev, also submitted a pull request to add compat to RFTools Dimensions directly: https://github.com/McJtyMods/RFToolsDimensions/pull/369
