### ISSUE TITLE
Bug pedestal import rf screen

### ISSUE THREAD

**Issue by Ptituf** [NillerMedDild/Enigmatica6#2732]
**Modpack version**
Enigmatica 6 0.5.4
**Describe the bug**
I don't know if i am missing something and guess yes but my
Pedestal export using 5000/t on transfer but the Pedestal import get 200/t 
so im loosing 4800 rf /tick and i dont know why

**Logs**
No needed

**Screenshots**
![5000bananas](https://user-images.githubusercontent.com/28937889/125699187-3e28a5d5-46cd-406c-9f5c-d5c15cdcc3ed.PNG)
![5000proof](https://user-images.githubusercontent.com/28937889/125699208-e0398742-f1c9-4caa-8ac4-8379cce22ec1.PNG)
![200fe](https://user-images.githubusercontent.com/28937889/125699226-d0d1b43b-2d05-4b4b-849c-64573968eb84.PNG)
![1Million](https://user-images.githubusercontent.com/28937889/125699249-f25971aa-6ca0-46c1-a26d-05734bc58b57.PNG)
![borred](https://user-images.githubusercontent.com/28937889/125699268-29bc4ea4-d793-430d-905a-1bdd066ff48c.PNG)

**Comment by Ptituf** [comment]
Its a multiple test , that why you can see "3 pedestal" but its  only 2 , i moved and relinked to proove the -5000 on the energy cell

**Comment by RobuxShooters** [comment]
One thing I noticed is that your upgrades aren't enchanted with Pedestal Speed, meaning that at Normal operational speed, the upgrade works once every second. This means that it should export 5000 FE/s (250 FE/t) from the pedestal network instead of 5000 FE/t, which might explain the loss you're experiencing.

Also, can you confirm that the pedestal is actually importing 5000 FE/t into the pedestals network or 5000 FE/s?

**Comment by Ptituf** [comment]
Talked with the creator of pedestal too and yes im on fe/s so that explain 200 instead of 5000 (i don't have 250/s so i dont know where the 50 left go ). But the interaction Powah - pedestal is bugged
![maybeabug](https://user-images.githubusercontent.com/28937889/125774914-e71e93eb-6568-458d-be8e-638288d07764.PNG)

**Comment by NillerMedDild** [comment]
For reference: https://github.com/Mowmaster/Pedestals/issues/99

**Comment by Mowmaster** [comment]
This is fixed in dev, there will be a hotfix 4 build out later this week probably

**Comment by Mowmaster** [comment]
fixed in new version: https://www.curseforge.com/minecraft/mc-mods/pedestals/files/3397977
