### ISSUE TITLE
Occultism Questline - Soul Gem

### ISSUE THREAD

**Issue by Celebnasse** [NillerMedDild/Enigmatica6#2734]
**Modpack version**
0.5.4

**Describe the bug**
In the Occultism Questline, The Soul Gem has Golden Chalk as the only pre-req, but the Ritual to create it needs Purple Chalk, which is further up the questline.

**Comment by NillerMedDild** [comment]
@theboo good sir, please halps.

**Comment by theboo** [comment]
I'll look at it tonight/tomorrow, have some other changes I need to make now that I've actually played through it in actual survival xD
