### ISSUE TITLE
Suggestion - Morphing Tool Additions

### ISSUE THREAD

**Issue by Isaac-Pollack** [NillerMedDild/Enigmatica6#2736]
Some things I think would make sense being able to be added to the morphing tool:

- Pedestals Linking Tool
- Pedestals Color Pallet
- Advanced Peripherals Computer Tool
- Resourceful Bees Beepedia
- Mekanism Network Reader
- Occultism Divination Rod

**Comment by Isaac-Pollack** [comment]
Potentially even a full morphing tool recipe, akin to the Akashic Tome?

**Comment by NillerMedDild** [comment]
I believe `Resourceful Bees Beepedia` is in the Akashic Tome
Will look into the rest, but 

I'd rather not add a full morphing tool recipe, because a lot of the "wrenches" are expensive and/or requires a bit of progression.

**Comment by NillerMedDild** [comment]
After having reviewed the suggested items, I've come to the conclusion that I don't think any of them should be in the morph-o-tool.

... With the exception of the Pedestals Linking Tool, but that one can't be added because of it's shift-right-click ability.
