### ISSUE TITLE
Obsidian dust crafting through crafting table

### ISSUE THREAD

**Issue by brckts** [NillerMedDild/Enigmatica6#274]
**Modpack version**
0.2.16

**Issue**
Crafting obsidian by itself in a crafting table gives more obsidian dust than using an enrichment chamber
![image](https://user-images.githubusercontent.com/51674867/93023515-cfc4ee00-f5ef-11ea-9c4a-fdbbbe045e09.png)
![image](https://user-images.githubusercontent.com/51674867/93023506-c63b8600-f5ef-11ea-8293-024b2014780d.png)

**Logs**
none

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
