### ISSUE TITLE
0.5.6 has bleedthrough recipes from Expert through GD Launcher

### ISSUE THREAD

**Issue by MrGrimmReaper28** [NillerMedDild/Enigmatica6#2740]
0.5.6 was uploaded with some expert mode recipes active in normal mode through GD Launcher. Not sure if affects other sources. 
Noticed via IF pity machine frame.

![image](https://user-images.githubusercontent.com/70997523/125758575-0837ae8c-248f-4fd5-b7c4-9a897ac2e1fa.png)

**Comment by natebc** [comment]
![image](https://user-images.githubusercontent.com/53818/125762920-1673c122-da6a-42a9-a152-e1435c12cc83.png)
same recipe default in pack launched from multimc import of the 0.5.6 zip file as well.
