### ISSUE TITLE
Taking damage from Personal Shrinking Device (from Shrink. mod)

### ISSUE THREAD

**Issue by ApeSpork** [NillerMedDild/Enigmatica6#2743]
Enigmatica 6 Version 0.5.6

After updating from 0.5.4 to 0.5.6 player is taking what seems to be suffocation damage after shrinking using the Personal Shrinking Device from the Shrink. mod and beginning to move around and jumping (first person view turns black as well).  Rolling Shrink. mod back from version 1.1.1 to 1.1.0 fixes the issue, going back to 1.1.1 from 1.1.0 causes the issue to reappear.

This is my first bug posting, let me know if you need more information!

**Comment by NillerMedDild** [comment]
Thanks for the report, and welcome to GitHub :D the issue was very easy to reproduce, I'll relay it. I'll most likely just remove the mod tbh.

**Comment by ApeSpork** [comment]
Awesome! Glad I could help, and glad it's an easy fix
