### ISSUE TITLE
Out of Memory Crashes with 8 GB allocated

### ISSUE THREAD

**Issue by ArtOfCombat** [NillerMedDild/Enigmatica6#2745]
Enigmatica 6 0.5.4

**Describe the bug**
When loading new chunks, or teleporting, or just at random, Minecraft crashes with an Out of Memory error, despite having 8 GB of RAM allocated.

**Logs**
[Link](https://paste.ee/p/zgVbe) (too big for pastebin)

**Screenshots**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report. How much RAM does your PC have in total?

**Comment by ArtOfCombat** [comment]
12 GB, and I have never had this issue.

**Comment by Darkere** [comment]
C:\Users\music\Desktop\MultiMC\instances\Enigmatica6-0.5.4\minecraft\hs_err_pid14608.log

Can you post that? Also ideally we would do this on discord for better correspondece.
