### ISSUE TITLE
Shovels are missing from Tinker's Construct

### ISSUE THREAD

**Issue by PiggyWhiskey** [NillerMedDild/Enigmatica6#2748]
**Modpack version**
0.5.6

**Describe the bug**
Tinker's Construct has all the basic tools except for Shovels

I'm not sure if this is a config clash from other mods, but I couldn't find anything is TiCon configs for this.
I'm also not sure if TiCon 1.16 just doesn't have shovels (I can't imagine why though)

**Screenshots**
![image](https://user-images.githubusercontent.com/9373995/125892067-619e5868-421c-4c86-a973-e6e20735528b.png)

**Comment by RobuxShooters** [comment]
You're probably looking for the Mattock, as it has replaced the shovel in 1.16 Tinker's Construct.
