### ISSUE TITLE
#!/bin/sh^M

### ISSUE THREAD

**Issue by Fabizocker456** [NillerMedDild/Enigmatica6#2755]
**Modpack version**
Latest (0.5.6)
**Describe the bug**
Most systems running bash (.sh file ending) are unix style and therefore unix-style line ending must be used

**Logs**
None available
(Only error message about #!/bin/sh^M)

**Screenshots**
None

The problem would be easily fixed, but is nonetheless fatal as the server can't be started

**Comment by NillerMedDild** [comment]
Which file is an issue? :)

**Comment by Fabizocker456** [comment]
InstanceSyncSetup.sh(Run in a linux debian vm via ssh)Am 16.07.21, 20:43 schrieb "Niels Pilgaard Grøndahl" ***@***.***>:

   
  Which file is an issue? :)

**Comment by NillerMedDild** [comment]
Ah so it is! Fixed in-dev :) thanks!
