### ISSUE TITLE
Extra Armor

### ISSUE THREAD

**Issue by JFMillerUSA** [NillerMedDild/Enigmatica6#2758]
[https://www.curseforge.com/minecraft/mc-mods/extra-armor](https://www.curseforge.com/minecraft/mc-mods/extra-armor)

Available Armor Types

NEW (*)

Oak Wood
Birch Wood
Jungle Wood
Spruce Wood
Dark Oak Wood
Acacia Wood
Melon
Obsidian (BONUS: Blast Protection)
Magma
Cactus (BONUS: Thorns)
Quartz
Bone
Molten (SET BONUS: Fire Resistance)
Pumpkin
Ghost (SET BONUS: Invisibility) (BONUS: Soul Speed)
Crying Obsidian (BONUS: Blast Protection)
Phantom (SET BONUS: Slow Falling)
Ice (SET BONUS: Frost Walker)
Glowstone (SET BONUS: Night Vision)
Snow
Prismarine Shard (SET BONUS: Water Breathing)
Prismarine Crystal (SET BONUS: Dolphins Grace)
Emerald (SET BONUS: Luck)
Ender (SET BONUS: Speed)
Honeycomb
*Slime (SET BONUS: Projectile Protection)
*Feather (SET BONUS: Jump Boost)
*Lapis (SET BONUS: Mending)

It would add more customization to the pack

![image](https://user-images.githubusercontent.com/9157611/126008968-49b0d4ef-4414-48b4-82cc-98566da3ce42.png)

**Comment by MuteTiefling** [comment]
I think we've got some pretty interesting armor in the pack already. I'm all for options but these don't bring anything new to the table.

**Comment by NillerMedDild** [comment]
I agree with Mute, no thanks :)
