### ISSUE TITLE
Materialis

### ISSUE THREAD

**Issue by stylzm** [NillerMedDild/Enigmatica6#2759]
https://www.curseforge.com/minecraft/mc-mods/materialis/files/3389947

Materialis is a mod that adds Tinker's Construct support to many other mods, which has been just recently updated for 1.16. It adds materials from Create, Eidolon, Astral Sorcery, Industrial Foregoing, The Undergarden, Mekanism, Quark, and Thermal Foundation, with many of the new materials having their own unique tool traits.

I think this mod would be great to have because it makes Tinker's feel more "complete" with having more tool materials from other mods added in, and the unique tool traits added by these materials open up interesting possibilities for tools and even play styles.

**Comment by g0urra** [comment]
It feels too early to add this kind of compatibility mod since Tinker's Construct is still in alpha.

**Comment by CletusMAngo** [comment]
> It feels too early to add this kind of compatibility mod since Tinker's Construct is still in alpha.

The person who made it actually waited for tinkers to be stable enough to make this mod so i dont think it should be that buggy

**Comment by DarkAngel22579** [comment]
Yeah so Knightminer has said that Tinkers material API is basically stable at this point, so future updates shouldn’t cause any major issues.

Adding this would also knock about 20 materials off the list that I’m adding support for, so I may be biased in wanting it :P

**Comment by MuteTiefling** [comment]
Yeah, if the materials are well balanced, this could be nice

**Comment by NillerMedDild** [comment]
Seems good :D

**Comment by KnightMiner** [comment]
For the record, the Materialis dev is a member of our discord, we have been in communication with him about new APIs and he tends to be on top of things when I do make breaking changes. Plus the addon is quite cool, he seems to have a good understanding of Tinkers balance.

**Comment by NillerMedDild** [comment]
Awesome!

**Comment by ArMoReDfUrY** [comment]
New version up to date with TC 3.1.1.252
have added to my copy.
will let you know if any issues pop up.
