### ISSUE TITLE
IE Treated Wood Uncraftable

### ISSUE THREAD

**Issue by Syrasar** [NillerMedDild/Enigmatica6#276]
**Modpack version**
0.2.16

**Issue**
Immersive engineering treated wood not craftable 
standard recipe does not work and jei shows no use beside fuel for creosote

**Comment by MaxNeedsSnacks** [comment]
duplicate of #248, please `/reload` the world/server

**Comment by Syrasar** [comment]
first try /reload java crash second try also a java crash
java.util.ConcurrentModificationException: null
Exit Code: -1

third try reload worked and fixed the issue

**Comment by NillerMedDild** [comment]
Yikes :/ do you happen to have the full crash reports?

**Comment by MaxNeedsSnacks** [comment]
It might be a similar crash to the one we're getting on our server with ProductiveBees?

In SMP, people get kicked and cannot rejoin after a /reload, while in SSP, the game apparently just straight up crashes
