### ISSUE TITLE
Improved Sleep from Quark broken.

### ISSUE THREAD

**Issue by MFWalter** [NillerMedDild/Enigmatica6#2761]
We are on E6 0.5.6.

Quark Improved Sleep seems to be broken. It is set to 0.25 in the modpack by default. If even a single person sleeps the night passes. If we change it to 0.50 if even a single person sleeps the night passes. If we set it to 0.75 if even one person sleeps it the night passes. If set to 1.0 the night only passes if the whole server sleep.

More than one person is on the server at the time during testing.

**Comment by Quezler** [comment]
how many people in total were online during testing?

**Comment by MFWalter** [comment]
We tested with 3 people and with 2 people.

**Comment by MFWalter** [comment]
The issues was first noticed with 4 people online when 1 person slept and progressed time, but we waited to do testing until all the players were off and we could get just the server ops around in voice.

**Comment by MFWalter** [comment]
We think it might be something to do with player counting. We are noticing that sometimes it does call for a vote, but often the second number {total player count} is wrong.

**Comment by MFWalter** [comment]
![image](https://user-images.githubusercontent.com/56056783/126429932-c9547b0e-292e-4cd9-84e5-0347f86f36d6.png)
![image](https://user-images.githubusercontent.com/56056783/126429948-317b8979-49d8-42de-9762-102f1bbecc37.png)

**Comment by MFWalter** [comment]
You can see the number of players online does not match the number of players the sleeping claims are needed. No one was afk in these instances either.

**Comment by NillerMedDild** [comment]
Thanks for the report, I found a similar issue on Quark's issue tracker and commented.
