### ISSUE TITLE
Some Wood Types Cannot be Used in Certain Crafting Recipes

### ISSUE THREAD

**Issue by RobuxShooters** [NillerMedDild/Enigmatica6#2762]
**Modpack version**
0.5.6

**Describe the bug**
Certain types of wood, such as archwood or menril, when turned into planks, cannot be used to craft certain items like crafting tables and bookshelves for both of these log types and buttons for menril.

I suspect the crafting table issue occurs due to the recently added mod More Crafting Tables for Forge that makes it so that instead of accepting any items tagged with `minecraft:planks`, it only accepts oak planks specifically for the default crafting table. This means there is no fallback recipe that generically accepts any `minecraft:planks` for wood types that the mod does not support (for instance menril and archwood).

A similar issue occurs for bookshelves as the default bookshelves have been replaced with an oak variant, which only accepts oak planks.

As for menril planks not being able to be crafted into buttons, this could probably be an Integrated Dynamics issue as the base mod does not seem to have menril buttons unlike archwood.

**Screenshots**
![image](https://user-images.githubusercontent.com/16001607/126032213-5f298f16-fc1c-455a-93b8-0c0d71704500.png)
![image](https://user-images.githubusercontent.com/16001607/126032224-4ef71544-f3d1-4945-b760-782ec61429ee.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, fixed in-dev :)
