### ISSUE TITLE
Incorrect Latex values for Fluid Extractor

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2767]
**Modpack version**
0.5.6

**Describe the bug**
JEI says that Acacia gives 8mb/12ticks of Latex, but the machine gives 8mb/40ticks (see linked gif).

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/126070199-f1b404ba-35a4-4d09-8cc1-1b3f0dd521fc.png)

https://cdn.discordapp.com/attachments/726178356143456287/866316349214818335/t3H3fui8yk.gif

**Comment by MuteTiefling** [comment]
This is the fully upgraded/powered speed of the machine.
