### ISSUE TITLE
Default terrain lag? (0.5.6)

### ISSUE THREAD

**Issue by ariosos** [NillerMedDild/Enigmatica6#2768]
I was trying to create a new world only using the default terrain to see if there were any performance improvements, and was promptly met with essentially 10 seconds per frame. (also island spawn, per usual.) Game essentially froze trying to recreate the world to find the seed, but did manage to snag it from nbtExplorer: 5090064259528637307

![image](https://user-images.githubusercontent.com/7917753/126087497-ac06029c-e71b-471d-8b3a-94652c78d957.png)

PC Specs: z77 ASRock motherboard, i7 2600k CPU, GTX 1070.

**Comment by ariosos** [comment]
I tried going to the discord before posting this, but got an error that messages failed to load.
![image](https://user-images.githubusercontent.com/7917753/126314084-70c85493-52a5-4fb8-ae4c-25e47adaaf80.png)

**Comment by Darkere** [comment]
Looks like you haven't accepted the rules yet. Go to #welcome-rules
