### ISSUE TITLE
Death waypoints not removing when deleted.

### ISSUE THREAD

**Issue by GelsGit** [NillerMedDild/Enigmatica6#2769]
**Modpack version**
0.56
**Describe the bug**
Death way-points not being removed once its deleted in journeymaps. A white way-point is left once I pick up my grave. (see Attached Screenshot) 

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![way point issue](https://user-images.githubusercontent.com/87049488/126154512-c7aea725-de66-48e1-b5e4-96c01fe55f82.png)

**Comment by TemperedFool** [comment]
The waypoints are a feature of Journeymap, not Enigmatic Graves. You'll need to remove them via Journemap's waypoint list.

**Comment by theboo** [comment]
There is a setting in journeymap to auto remove death points when you get within a certain range that you can turn on

**Comment by KrAzYGEEK32** [comment]
those death waypoints  are from the ftb maps btw, you can remove them from the map which shows up if you press 'm'. just right click on the waypoint.

**Comment by GelsGit** [comment]
> 
> 
> those death waypoints are from the ftb maps btw, you can remove them from the map which shows up if you press 'm'. just right click on the waypoint.

yeah it was thanks, to many cooks adding way-points. lol

**Comment by NillerMedDild** [comment]
@MaxNeedsSnacks may I suggest FTB chunks waypoints get auto disabled when the minimap is off? :)

**Comment by scotty9090** [comment]
Just searched this issue since I'm having it as well.  Even when I remove the death marker in the FTB Chunks map, I still have the waypoint showing in world.  

I'm assuming the waypoints are from FTB Chunks vs. the grave mod.  I'm playing with keepInventory = true so graves never appear.
