### ISSUE TITLE
Modded for Dummies missing texture

### ISSUE THREAD

**Issue by Meryl** [NillerMedDild/Enigmatica6#277]
**Modpack version**
0.2.16

**Issue**
The 'Modded for Dummies' book shows a missing texture. It worked fine the first time I loaded the pack, then I quit the pack and changed an option on the mouse tweaks mod. The second (and third, and fourth) time it showed the purple/black placeholder texture.

**Logs**
N/A

**Comment by ChromeMystic** [comment]
I had this issue as well, but only when I ran optifine, without Optiforge.
