### ISSUE TITLE
Fermented Raw Ore Meat recipes crash

### ISSUE THREAD

**Issue by Golfavel** [NillerMedDild/Enigmatica6#2771]
**Modpack version**
0.5.6

**Describe the bug**
Attempting to look at recipes involving any Fermented Raw Ore Meat that is used in the Fluid Sieving Machine will crash the game (JEI)

**Logs**
[Crash Log](https://pastebin.com/bTP1AVJ7)  [latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6841620/latest.log)

**Comment by FailPail** [comment]
This still happens in 5.8, specifically when right clicking the sieving machine in JEI from a different set of recipes of an item 

i.e
right click sieving machine in JEI
right click a fermented ore type from provided recipes (crash provided happened with redstone)
left click on fluid sieving machine tab from the fermented ore's provided recipes
*crash*

log:
https://paste.ee/p/jWTDH

**Comment by NillerMedDild** [comment]
@Buuz135 halp? :D

**Comment by Merthew** [comment]
Just had this happen so can confirm its an issue XD

**Comment by NillerMedDild** [comment]
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1158
