### ISSUE TITLE
Nether Wart output mismatch/duplication

### ISSUE THREAD

**Issue by Golfavel** [NillerMedDild/Enigmatica6#2772]
**Modpack version**
0.5.6

**Describe the bug**
Nether Wart Blocks can be created with 4 Nether Wart, however with Immersive Engineering's Crusher, you can get 9 Nether Wart from one Nether Wart Block. This doesn't seem intentional as the Nether Wart Sack is what is used to compact 9 Nether Wart.

**Screenshots**
![nwbcraft](https://user-images.githubusercontent.com/32048635/126177760-c67e189d-97d5-4290-bffa-0c49a49aec05.png)
![nwcrush](https://user-images.githubusercontent.com/32048635/126177764-39342c5e-9a55-4454-a52e-3933642174ac.png)

**Comment by MuteTiefling** [comment]
Thanks! Got this all fixed up.
