### ISSUE TITLE
Geodes give wrong nuggets

### ISSUE THREAD

**Issue by Fabizocker456** [NillerMedDild/Enigmatica6#2773]
**Modpack version**
0.5.6
**Describe the bug**
Tetra Geodes give nuggets lke copper, lead etc when smashed. Those are however from different mods
(e.g. Mekanism, Thermal) and can't be easily converted into Emendatus Enigmatica nuggs. I would see two solutions to this:
1. Changing tetras geode loot table or
2. Allow crafting other nuggets into Emendatus Enigmatica ones
The last one would mean more KubeJS, but would fix all similar wrong-resource bugs.

**Comment by MuteTiefling** [comment]
Thanks! Should be all fixed up next release

**Comment by MuteTiefling** [comment]
Totally not fixed. Forgot this had been moved to a script. Script is breaking and the delete of the override file is still in place.

**Comment by MuteTiefling** [comment]
NOW it's fixed for reals
