### ISSUE TITLE
Infustrial Foregoing - Enchantment Applicator - Cannot combine enchanted books

### ISSUE THREAD

**Issue by ecco-tony** [NillerMedDild/Enigmatica6#2774]
**Modpack version**
0.5.6

**Describe the bug**
Cannot combine 2 enchanted of same type to improve book
i.e. Efficiency V + Effiency V to get Eff VI
Can only add 1 book and not the second

**Logs**
N/A

**Screenshots**
<img width="540" alt="2021-07-19 17_41_26-Enigmatica 6 - Minecraft 1 16 5 - Singleplayer" src="https://user-images.githubusercontent.com/42568579/126187976-8d431cf2-ca80-4659-961f-31d2b19d7f91.png">
<img width="598" alt="2021-07-19 17_42_47-Enigmatica 6 - Minecraft 1 16 5 - Singleplayer" src="https://user-images.githubusercontent.com/42568579/126187981-ce6932eb-ffad-4d32-9d12-312b04bf57f2.png">
<img width="562" alt="2021-07-19 17_42_51-Enigmatica 6 - Minecraft 1 16 5 - Singleplayer" src="https://user-images.githubusercontent.com/42568579/126187983-fbc1439e-e0f9-4ffd-b88b-520de8ddd2c7.png">

**Comment by ecco-tony** [comment]
I am under the impression it should work like an anvil to combine the 2.

**Comment by anivlys** [comment]
> 
> 
> I am under the impression it should work like an anvil to combine the 2.
> 
> Please close if i am wrong. Splutty explained it a different way to use the approach, so, understandable if this is working as intended.

I may be wrong, but it probably only goes up to vanilla limits. That means that Efficiency VI wouldn't be possible and that is why it doesn't work with two Efficiency V books. You could try it with two lower leveled books (e.g. two Efficiency I) and see if they combine.

**Comment by Golfavel** [comment]
> > I am under the impression it should work like an anvil to combine the 2.
> > Please close if i am wrong. Splutty explained it a different way to use the approach, so, understandable if this is working as intended.
> 
> I may be wrong, but it probably only goes up to vanilla limits. That means that Efficiency VI wouldn't be possible and that is why it doesn't work with two Efficiency V books. You could try it with two lower leveled books (e.g. two Efficiency I) and see if they combine.

It doesn't allow enchanted books at all to enter the first slot. It is definitely confusing as JEI groups the Enchantment Applicator with the likes of anvils and the anvil pedestal upgrade, and it is capable of doing non-enchantment anvil tasks (e.g.: repairing a tool)

**Comment by RobuxShooters** [comment]
> > I am under the impression it should work like an anvil to combine the 2.
> > Please close if i am wrong. Splutty explained it a different way to use the approach, so, understandable if this is working as intended.
> 
> I may be wrong, but it probably only goes up to vanilla limits. That means that Efficiency VI wouldn't be possible and that is why it doesn't work with two Efficiency V books. You could try it with two lower leveled books (e.g. two Efficiency I) and see if they combine.

You may want to try this to get Efficiency VI. Enchant a tool with Efficiency V first, then insert that tool into the first slot with an Efficiency V book in the second slot. The Enchantment Applicator should combine those two Efficiency enchantments into Efficiency VI on the resulting tool.

**Comment by ecco-tony** [comment]
If you do tool + book of same level, it will upgrade. That does work. I was just confused on the applicator acting like an anvil.
I think this can be closed as a misinterpretation of the applicator working like an anvil.
