### ISSUE TITLE
My character is out of its body.

### ISSUE THREAD

**Issue by kuba44** [NillerMedDild/Enigmatica6#2777]
**Modpack version**
0.54
**Describe the bug**
Everytime i respawn my character is out of it's body. I can't move or do anything, but try to break things around me (they don't break) and use commands, i can also kill my self but every time i respawn it happens again.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6849200/latest.log)

**Screenshots**
![2021-07-20_16 56 12](https://user-images.githubusercontent.com/58076757/126346749-f2964f05-3779-46d8-b7af-892ec0ec8850.png)
![2021-07-20_16 56 13](https://user-images.githubusercontent.com/58076757/126346776-9a9c844a-c2c1-4bf1-8e5c-0602665ccde4.png)
![2021-07-20_16 55 26](https://user-images.githubusercontent.com/58076757/126346791-59f84f1b-936d-4106-bd13-05af742eb255.png)
![2021-07-20_16 55 29](https://user-images.githubusercontent.com/58076757/126346795-a90069eb-6f88-4810-b273-9df4ba0e68f8.png)
![2021-07-20_16 55 31](https://user-images.githubusercontent.com/58076757/126346803-9efc2066-08f6-406b-b202-f434de009a83.png)
![2021-07-20_16 55 32](https://user-images.githubusercontent.com/58076757/126346831-e72a7277-5b9b-4711-a7fe-48e37db84c54.png)
![2021-07-20_16 55 58](https://user-images.githubusercontent.com/58076757/126346854-87cafb13-e856-4743-8742-59c265bc3fbf.png)

**Comment by Darkere** [comment]
Update.
