### ISSUE TITLE
Wandering trader selling air.

### ISSUE THREAD

**Issue by Jofedder** [NillerMedDild/Enigmatica6#2778]
**Modpack version**
0.5.4

**Describe the bug**
A wandering trader spawned and he wanted an iron axe for air.

**Logs**
-

**Screenshots**
![image](https://user-images.githubusercontent.com/87721668/126379196-e77de22c-14d2-4681-a610-bf483e12f798.png)

**Comment by MuteTiefling** [comment]
Hrm, odd. I was able to reproduce this in 0.5.6 by spawning a bunch of traders and checking them. got an Iron Chest to Air trade.

Not sure which mod might be introducing these broken recipes, however. Several are touching the loot table for this guy though.

**Comment by Splutty** [comment]
There's also a Bounty Board request that wants Air, so you can buy it to turn it in! :D

**Comment by NillerMedDild** [comment]
Fixed by an Apotheosis update.
