### ISSUE TITLE
Wither builder no longer building anything after upgrading to 5.6

### ISSUE THREAD

**Issue by FailPail** [NillerMedDild/Enigmatica6#2786]
**Modpack version**
5.4 to 5.6
**Describe the bug**
wither builder which used to work in 5.4 stopped working when I updated to 5.6 instead of placing soul sand and wither skeleton skulls, nothing happens. This happens on all redstone settings
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
https://paste.ee/p/nO8u2

**Comment by NillerMedDild** [comment]
Is it in a claimed area?

**Comment by Darkere** [comment]
We've already mostly investigated this one. Left to try is looking if it is caused by another mod (trying without other mods installed). Buuz was also notified.
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1140

**Comment by FailPail** [comment]
it is not in a claimed chunks area, I also tried it in a creative flat world and that also didn't work
