### ISSUE TITLE
Unable to step up single blocks with either the [Mekanism] Free Runners or the [Lost Trinkets] Horseshoe

### ISSUE THREAD

**Issue by DizzyDJW** [NillerMedDild/Enigmatica6#2789]
**Modpack version**
Ver. 0.5.4

**Describe the bug**
It does not seem to matter whether I have the [Mekanism] Free Runners or the [Lost Trinkets] Horseshoe equipped, my character refuses to step up single block heights.

**Comment by NillerMedDild** [comment]
Duplicate of #2472
Will be fixed soon hopefully :)

**Comment by Erysch** [comment]
> Duplicate of #2472
> Will be fixed soon hopefully :)

actually a reason why I didn't update the server yet x)
