### ISSUE TITLE
immersive engineering mod and create mod error

### ISSUE THREAD

**Issue by BLACKPOWDER127** [NillerMedDild/Enigmatica6#2791]
**Modpack version**
E6 0.5.6
**Describe the bug**

[If steel is tried to be made in a furnace, the rope pulley will not function normally. The blocks are turning transparent and the pulley is broken and not functioning properly.]

**Comment by NillerMedDild** [comment]
We're going to need screenshots of your setup. Why do you need a Rope Pulley to make Steel?
