### ISSUE TITLE
Stuck in world loading screen

### ISSUE THREAD

**Issue by MahoXD2** [NillerMedDild/Enigmatica6#2792]
**Modpack version**
enigmatica 6- 0.3.4
**Describe the bug**
When i created new world in enigmatica 6 it stuck on "100%" on world loading screen i tried to wait 1hour but still stuck in the same place i closed the game and tried to join the world again but still the same problem i even tried to reinstall the modpack but no use (i use tLauncher with 8gb ram allocated)
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by NillerMedDild** [comment]
You're using a very old version of Enigmatica 6, we no longer support 0.3.x, or 0.4.x for that matter.
Additionally, we do not offer support to anyone who has not paid for Minecraft. We do not condone piracy.
