### ISSUE TITLE
Only Looking

### ISSUE THREAD

**Issue by Asgart0916** [NillerMedDild/Enigmatica6#2793]
**CurseForge Link**

https://www.curseforge.com/minecraft/mc-mods/onlylooking/files

**Mod description**

Change mob AI so that it can only detect players in its sights.

**Why would you like the mod added?**

Offering a more ninja like combat style.

The Backstab enchant and Tetra's shortblades is kinda meaningless if player cannot hide from monsters.

**Comment by ct-klein** [comment]
The thieves hood offers up to 75% stealth and the ability to hide from monsters, that is part of the 'explorers' outfit.

**Comment by Asgart0916** [comment]
> The thieves hood offers up to 75% stealth and the ability to hide from monsters, that is part of the 'explorers' outfit.

Yeah, I know that cool hood, but at the same time I can't equip better armor sets that provides higher protection or useful functions

**Comment by NillerMedDild** [comment]
While this is a really cool mod, I do not want to add a mod that modifies mob AI just to make combat nicer, it has the potential to cause a ton of bugs.
