### ISSUE TITLE
Upgrade Aquatic's Thrasher spawns too frequently

### ISSUE THREAD

**Issue by CynicalRoses** [NillerMedDild/Enigmatica6#2795]
**Modpack version**
0.5.6
**Describe the bug**
Thrashers from Upgrade Aquatic spawn in huge batches and wipe out all the fish in the area, increasing the entity count dramatically. While attempting to spawn more entities, it spams the console with the warning: "[Server] Server thread/WARN [minecraft/ServerWorld]: Tried to add entity upgrade_aquatic:thrasher but it was marked as removed already"

**Logs**
N/A

**Screenshots**
![2021-07-22_11 00 59](https://user-images.githubusercontent.com/21284670/126662242-4ca18acc-f627-4815-be4f-643f0722d774.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, I've decreased the weight from 90 to 30.
