### ISSUE TITLE
Botany pot consumes water bucket on use 

### ISSUE THREAD

**Issue by CynicalRoses** [NillerMedDild/Enigmatica6#2796]
**Modpack version**
0.5.6
**Describe the bug**
When using a water bucket on a hopper botany pot, it consumes the whole bucket instead of leaving an empty bucket.

**Logs**
NA

**Screenshots**
NA

**Comment by theboo** [comment]
Yup, that's how the recipe works, if you break the pot it gives back the full water bucket

**Comment by CynicalRoses** [comment]
Oh, my bad, I completely forgot to check for that!

**Comment by Erysch** [comment]
> Oh, my bad, I completely forgot to check for that!

Just had the same "issue" 2 days ago
