### ISSUE TITLE
Crashed when seeing recipes for sand in the Fluid Sieving Machine

### ISSUE THREAD

**Issue by TiuTalk** [NillerMedDild/Enigmatica6#2798]
**Modpack version**
0.5.6, with no extra or removed mods

**Describe the bug**
Crashed when seeing recipes for sand in the Fluid Sieving Machine

**Logs**
https://paste.ee/p/Sff9P
https://paste.ee/p/w5195

#### Possible duplicate issue of:

* https://github.com/NillerMedDild/Enigmatica6/issues/2776
* https://github.com/NillerMedDild/Enigmatica6/issues/2771

**Comment by NillerMedDild** [comment]
Yep, duplicate :)
