### ISSUE TITLE
IE Engineer Villager accepts only IE Steel (Steel conversion recipe added)

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#280]
**Modpack version**
E6 0.2.16

**Issue**
IE Villager accepts only IE Steel for one of its trades, which is no longer obtainable.
I've tested with EE and Meka Steel, and they are both not acceptable for the trade. Is this something that can be modified through Enigmatica Companion mod?

**Screenshot**
![image](https://user-images.githubusercontent.com/64355028/93183306-1e32d380-f73b-11ea-91bf-d38b7b47c18a.png)

**Comment by NillerMedDild** [comment]
Unfortunately we can only replace all recipes for that villager >< but I don't think villager trades can use tags anyway. I'll investigate though

**Comment by Ridanisaurus** [comment]
Let me know if you want me to look into something from my end. I could build his loot table from scratch if need be

**Comment by NillerMedDild** [comment]
Well I'd like you to, but only if you have the time for it :)

**Comment by Ridanisaurus** [comment]
Sure. I'll look into it tomorrow, and PR it once ready

**Comment by Ridanisaurus** [comment]
Alright, slight issue. The OreVienMap from IE Traders does not exist as an item, so re-writing all its trades is not possible, at least as far as I understood.
I guess we can add a recipe to exchange EE Steal for IE Steal for such situations, which is not something I'm personally fund of as it feels like going backward with our Unification process. However, I can't think of any other solution. Denying players access to that Trade also doesn't feel nice. 
Maybe we add a trade to the Engineer where he trades IE Steal for EE Steal but with no EXP so it can't be used to level them up, just a straight up 1:1 exchange.
What do you think?

**Comment by NillerMedDild** [comment]
I don't like that fix, cause it could be on villagers that don't have the map trade, and vice-versa. I think we're forced to do the ugly-conversion :(
