### ISSUE TITLE
[0.5.6] Astral's Marble Pillar

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#2800]
**Description**
Recommending adding Astral's Marble Pillar to the other general types that every other marble block is part of (e.g. chisel:marble, enigmatica:stonecuttables, etc).

**Why would you like this added/changed?**
I'm still used to 1.12 where you could chisel the pillar back to the base marble and this way the marble pillar isn't all by itself. Don't leave it all alone out in the cold! Though mostly I just want to be able to convert all my marble into a singular type (typically Astral's) and the pillar is an outlier in this case.

**Comment by NillerMedDild** [comment]
Good idea, done :)
