### ISSUE TITLE
Shrink broken in latest pack update

### ISSUE THREAD

**Issue by L0rdLogan** [NillerMedDild/Enigmatica6#2804]
**Modpack version**
0.5.6

**Describe the bug**
Shrink on 0.6 or lower forces you to see 'inside' the block and hurts you

**Logs**
no error in console

**Screenshots**

**Comment by BigBarza** [comment]
[https://github.com/NillerMedDild/Enigmatica6/issues/2743](url)
Looks like a known thing. An upcoming(?) patch of the Shrink mod should fix that.
But to better explain what's happening, the player's point of vision gets shifted down way more than intended, and it can also go inside blocks. Notably, if you keep crouching when shrinking, you'll get the correct pov and it'll only sink down when you release shift.
It also applies in reverse when going the other way. You can have a pov dozens of blocks high up.
