### ISSUE TITLE
Change Teleportation Core for [Mekansim] Quantum Entangloporter to require Ender Pearls in place of the current Lapis.

### ISSUE THREAD

**Issue by DizzyDJW** [NillerMedDild/Enigmatica6#2807]
**Description**
Mekanism's Quantum Entangloporters are designed to TELEPORT items, energy, gas, etc... It would make much more sense for the cores to require Ender Pearls to craft. 

Also, not a fan of the new change to [Industrial Foregoing] Pity Machine Frame crafting recipes. They require too much for 1 resulting craft. The craft should, at the very least, output 2 Pity Machine Frames, with my preference being 4. Balance for items in compared to items out needs to be accounted for.

**Why would you like this added/changed?**

Balance and immersive reasons

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/26727521/126871850-3e7fddde-ff62-4750-997f-f4f91e478cca.png)
![image](https://user-images.githubusercontent.com/26727521/126871870-30aa8ff4-ac9a-4ecd-82cc-96b43d6caabd.png)

**Comment by MuteTiefling** [comment]
The pity machine recipe wasn't intended for normal. It's a bug and already fixed for the next release. 

Also, not a fan of the 'everything that teleports needs to use ender pearls' idea. In this case you're leaning on tech instead of the magical nature of endermen. That's fair, I think.

**Comment by NillerMedDild** [comment]
I agree with Mute, thanks for the suggestion anyhow :)

**Comment by DizzyDJW** [comment]
> The pity machine recipe wasn't intended for normal. It's a bug and already fixed for the next release.
> 
> Also, not a fan of the 'everything that teleports needs to use ender pearls' idea. In this case you're leaning on tech instead of the magical nature of endermen. That's fair, I think.

I get this, but how would Lapis be technological in literally any way? At the very least, maybe some silicon from smelted quartz then? Makes more sense than the Lapis. Also, how is a major recipe change a "bug"?

**Comment by KrAzYGEEK32** [comment]
that recipe change is for expert mode, it somehow creeped its way into normal, that's why its a bug. also, not many recipes are changed in normal mode by default, i feel like you should take this recipe change up with the mod dev itself, if you are unhappy with it. rest assured it will be definitely changed and way more pricey in expert mode (entangloporter recipe).

**Comment by MuteTiefling** [comment]
> I get this, but how would Lapis be technological in literally any way? At the very least, maybe some silicon from smelted quartz then?

Circuits. Apart from that, they did the best they could with the vanilla/mek components they had to work with, without making it too micro crafty.

You can expect something more fitting for Expert, to be sure.

**Comment by DizzyDJW** [comment]
> that recipe change is for expert mode, it somehow creeped its way into normal, that's why its a bug. also, not many recipes are changed in normal mode by default, i feel like you should take this recipe change up with the mod dev itself, if you are unhappy with it. rest assured it will be definitely changed and way more pricey in expert mode (entangloporter recipe).

Glad to hear, look forward to that.

> > I get this, but how would Lapis be technological in literally any way? At the very least, maybe some silicon from smelted quartz then?
> 
> Circuits. Apart from that, they did the best they could with the vanilla/mek components they had to work with, without making it too micro crafty.
> 
> You can expect something more fitting for Expert, to be sure.

I just might make a few suggestions in the Mekanism repository, but I know it's hard to be noticed because of how popular the mod is.
