### ISSUE TITLE
Suggestion - Limit Break XP Anvil

### ISSUE THREAD

**Issue by Mowmaster** [NillerMedDild/Enigmatica6#2808]
**Description**
`onEvent(item.tags' event => {
	event.get('pedestals:enchant_limits/advanced_blacklist').remove('pedestals:coin/xpanvil')
})`

**Why would you like this added/changed?**
The IF Applicator (and other blocks) allows players to combine up to like, fortune XX, but then beyond that if they just put a black hole tank of essence on top, so to give players an alt option, unlocking the xp anvil would be that other option.

**Screenshots if applicable.**
N/A

**Comment by NillerMedDild** [comment]
I'm not overly fond of being able to combine enchants that high to begin with, to be honest ^^'

**Comment by Mowmaster** [comment]
I expected as much, I do feel like currently its balanced nicely since the limit does restrict players to consider if they want 1 or 2 low rarity high level enchants on an item , just a nice all-around slightly better than vanilla could enchant item, or lots of low leveled enchants on an item.
I do also have plans in the future to add an element of exploration/mob fighting to increase the 'cost' of this system too, as well as additional controls for the cost of the 'rarity modifier', but I can understand your current concerns with 'Limit Breaking' its potential.

Are you looking into ways to balance other mods enchanting, or is there always going to be a disparity between this, and other mods unbridled enchanting methods?

**Comment by MuteTiefling** [comment]
Personally would love to see some configs for IF, but that's up to Buuz. At the end of the day, however, it's always going to be an arms race for who's best, unfortunately.
