### ISSUE TITLE
Thermal Series and Integrated Dynamics Machine/Crafting-Terminal Negative TPS Interaction

### ISSUE THREAD

**Issue by ejgibs** [NillerMedDild/Enigmatica6#2810]
**Modpack version**
Enigmatica 6 0.5.6

**Describe the bug**
Have Integrated Dynamics storage system connected to Thermal Series Induction Smelter for auto crafting of Signalum, etc.. When Induction Smelter is set to auto-input via the IN/OUT face of machine, TPS skyrockets as the machine tries to pull from the crafter, which is not a thing it can do. Easily avoidable by disabling the auto-input. Took a minute to diagnose.

**Logs**
No crash.

**Screenshots**
N/A, easily reproduced.

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it on their discord here: https://discord.com/channels/399037120930512897/434101214548852746/868957048098947073

**Comment by Darkere** [comment]
A spark profile would be helpful here to see what is causing it exactly. Just set it up run /spark sampler --timeout 50 and post the output.

**Comment by KingLemming** [comment]
If I had to guess (and I am atm), the Crafter iterates over its entire inventory (or returns the entire inventory) and then denies when an extraction request is made on the slot. This would be incorrect behavior on their part.

If the intent is that auto-extract isn't allowed at all, then the block should return as such and not doing so would be an error on their part. (Hint: you won't see TPS lag with a smelter next to a dirt block).

If auto-extract IS allowed by their block but you simply don't have a compatible ingredient, then what you have already done (disabling) is in fact the correct solution. It's also possible that their logic simply returns far too many slots.

**Comment by NillerMedDild** [comment]
Thanks for the help KingLemming.

(note to self)
We need to check if other in/output methods cause lag with the Integrated Crafting Crafter, and eventually relay to https://github.com/CyclopsMC/IntegratedCrafting/issues

**Comment by NillerMedDild** [comment]
I can't reproduce this, could you please provide screenshots of your setup?

**Comment by ejgibs** [comment]
> I can't reproduce this, could you please provide screenshots of your setup?

Thermal Induction Smelter is receiving power from Integrated Dynamics. Top face set to I/O, with Crafting Terminal on top. When Auto input is disabled, fine TPS. When input enabled, spike TPS.

![1](https://user-images.githubusercontent.com/74204512/127213246-833cb51b-ae74-4aaf-80ed-fe84d7a90bf9.png)
![2](https://user-images.githubusercontent.com/74204512/127213266-a0d1a84d-d1a4-4dd1-bdb2-2d3f208d66a7.png)
![3](https://user-images.githubusercontent.com/74204512/127213278-bf049a7d-0955-4f3d-89f3-9b5fce017fc0.png)
![4](https://user-images.githubusercontent.com/74204512/127213287-1910fa76-e69b-4363-b422-e555755c474f.png)
![5](https://user-images.githubusercontent.com/74204512/127213292-eda14883-2a8c-446b-93ee-f4d0303ee7ba.png)
![6](https://user-images.githubusercontent.com/74204512/127213299-6380458e-3ce0-4f62-89b4-c7c65e42c0a0.png)
![7](https://user-images.githubusercontent.com/74204512/127213312-b348afa3-e496-47d9-9e44-3890afd95e45.png)

**Comment by ejgibs** [comment]
Those screenshots didn't order themselves very well. I tried a video but its too large to upload here.

**Comment by ejgibs** [comment]
These were taken on a server that I play alone on, but issue is present in identical single player world.

**Comment by Darkere** [comment]
Since you are here again. Does this require a larger setup?

Also please run `/spark sampler --timeout 50` while autoinput is on. This would allow the devs to easily find the problem.

**Comment by ejgibs** [comment]
Spark without issue: https://spark.lucko.me/JYPGvy0lh5
Spark with issue: https://spark.lucko.me/poYqgBcm5c

I will build a separated system in other chunks to see if issue persists without larger system.

**Comment by ejgibs** [comment]
It does seem that this only causes issues when connected to my larger integrated dynamics system which controls my entire base. I cannot replicate it on small scale.

**Comment by NillerMedDild** [comment]
Ah alright, maybe a false alarm then?

**Comment by ejgibs** [comment]
I mean the auto-input does still cause the TPS spike. I think (along the lines of what Lemming mentioned) it has something to do with the number and diversity of items that the crafter has access to in my particular setup. It isn't game-ending after I realized what the issue was.
