### ISSUE TITLE
RFTools Builder Quarry - Lootr Compatibility Fix

### ISSUE THREAD

**Issue by Merthew** [NillerMedDild/Enigmatica6#2811]
**Description**
At the current moment with the most recent build of 0.5.6, RFTools Builder Quarries cannot mine Lootr chests. The reason being is because Lootr requires a sneaking player to break them and the RFTools Builder fake player isn't sneaking (at least this is what I assume after doing some digging). There is no good "fix" for this in game as swapping the builder mode to "If the operation is not possible skip to the next position", causes it to not pause when the inventory is full. If there is some way to make the Lootr chests no longer require a shifting player to break or if there is a way to make the RFTools Builder skip over just those, that would be amazing. Currently I will either have to babysit the quarry, or set it to skip and hope that I have enough buffer storage to hold the items that are mined. Preferably making it just mine the Lootr chests would be nice but knowing how the mods are just in conflic means that it would be much harder to do.

**Why would you like this added/changed?**
Adding this would make quarries much easier to use, comparable to standalone instillations of RFTools.

**Comment by NillerMedDild** [comment]
I've tried making it easier to filter past the Loot Chest, but for some reason the Builder just gets stuck anyway. Not sure what I can do here tbh.

**Comment by NillerMedDild** [comment]
I've reported the issue here: https://github.com/McJtyMods/RFToolsBuilder/issues/64

**Comment by Merthew** [comment]
Ah, well that is good to know, it does seem like something that would have to be hard coded with how lootr does the chest replacement.
