### ISSUE TITLE
Mekanism fission reactor

### ISSUE THREAD

**Issue by EnderJGB** [NillerMedDild/Enigmatica6#2812]
So my friend an i were setting up a fission reactor and as we were looking at what we could use for coolant, my friend had seen that you could use sodium in the mek wiki, but when i looked at jei in game, i didnt see sodium as a coolant. just wanting to know if you can use it or not

**Comment by NillerMedDild** [comment]
I'm fairly certain you can use Sodium as coolant:

https://www.youtube.com/watch?v=8HwhqPjIllE
https://www.youtube.com/watch?v=yQzm5Ou5Bps
