### ISSUE TITLE
Sodium Reforged

### ISSUE THREAD

**Issue by lunulu** [NillerMedDild/Enigmatica6#2813]
https://www.curseforge.com/minecraft/mc-mods/sodium-reforged

Mod for FPS Boost.

I don't know if there are other optimizing mods in the modpack, but this mod gives a really big performance boost.

16 chunks without mod:
![16-](https://user-images.githubusercontent.com/65171793/126964597-4d2af543-9085-4084-a7b5-0be9aa2055c7.png)

16 chunks with mod:
![16+](https://user-images.githubusercontent.com/65171793/126964635-ccd0c19b-6e50-48a1-8083-d843a8db7ac0.png)

32 chunks without mod:
![32-](https://user-images.githubusercontent.com/65171793/126964670-2d3b1931-49d0-45a5-be4a-8be3c5ff64f8.png)

32 chunks with mod:
![32+](https://user-images.githubusercontent.com/65171793/126964692-ae1c2aab-0d67-4c3f-8379-2e095cfd2c2e.png)

Cool graphics settings menu:
![menu](https://user-images.githubusercontent.com/65171793/126965278-2e1fb89e-5b14-4b6c-b98e-fa36f74a2ce0.png)

**Comment by NillerMedDild** [comment]
To be honest I don't trust this mod. We've received reports from people experiencing weird issues and crashes, who added Sodium Reforged.

I'm all for a mod that improves performance, but I don't think adding this one is safe.
