### ISSUE TITLE
RFTools Environmental Controller No Teleport Module not preventing enderman from teleporting

### ISSUE THREAD

**Issue by kevincy75** [NillerMedDild/Enigmatica6#2814]
**Modpack version**
Enigmatica 6 0.5.6

**Describe the bug**
The No Teleport module of Environmental Controller does not prevent enderman from teleporting

**Logs**
No crashes involved

**Screenshots**
Mob Killer Setup
![image](https://user-images.githubusercontent.com/76750032/126986596-6c6c5015-a052-4ec2-9d2d-1c50529e1dee.png)
![image](https://user-images.githubusercontent.com/76750032/126986608-a238b030-5670-4133-b10d-89da38b06e4c.png)

Environmental Controller Setup
![image](https://user-images.githubusercontent.com/76750032/126986971-f9ed7027-4b8f-4c84-974b-08c38cc04283.png)

Video showing the bug
https://streamable.com/jgeryx

**Comment by NillerMedDild** [comment]
Thanks for the excellent report, I confirmed it locally and relayed it here: https://github.com/McJtyMods/RFToolsUtility/issues/90
