### ISSUE TITLE
Crash when creating/generating rftool dimension

### ISSUE THREAD

**Issue by Evan91380** [NillerMedDild/Enigmatica6#2817]
**0.5.6**

When i'm either creating dimension, or generating new chunk in dimension of rftool. The server sometime freeze for a long time and then crash. The crash seem to come from dungeon generation of DungeonCrawl.

**Logs**
https://pastebin.com/x0wZZJbD

and 

https://pastebin.com/R0hXJL3k

**Comment by NillerMedDild** [comment]
Thanks for the report, I am however unable to view your logs, it says they're private.

**Comment by Evan91380** [comment]
Oh my bad, i'v edit to put them public

**Comment by NillerMedDild** [comment]
Thanks! Could you perhaps make [this config change](https://github.com/NillerMedDild/Enigmatica6/commit/70ff1957987a483e5485f50d6e4a5f11991e8d8c) locally and see if that fixes the issue for you?

**Comment by Evan91380** [comment]
I try but it still crash without any error in log, i tried regenerating the dimension.
Which make me believe that there one particular structure from donjon crawl that make the server crash or something related to a structure that make the server lag

**Comment by NillerMedDild** [comment]
> it still crash without any error in log

Not sure what you mean, the error was very much present in your earlier logs. May I have the new logs please?

**Comment by Evan91380** [comment]
[2021-07-26-2.log](https://github.com/NillerMedDild/Enigmatica6/files/6887944/2021-07-26-2.log)

**Comment by NillerMedDild** [comment]
I can't reproduce the issue I'm afraid. Dungeon Crawl dungeons do not spawn in RFTools dimensions with that config changed, so I'm hopefully the fix works.
