### ISSUE TITLE
Cross - Compat for IE and PNC bio diesel

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#282]
**Modpack version**
0.2.16

**Issue**
a small QOL suggestion, for processing cross compatability of both PNC and IE bio diesel. they both have similar crafting methods
and IE is a bit bulky but also faster, having a choice for progressing in PNC would be nice, instead of waiting a lot for  the PNC way

alternative:
maybe make IE to output PNC bio fuel as the product, the only use of IE biofuel in the mod is for the drill but ive not tested other fuels with it. so its up to you :P
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
I was unable to get this to work :/ I tried making PNC recipes with IE Biodiesel, but no luck. I'm guessing the fluid system isn't really ready for something like this yet.

**Comment by KrAzYGEEK32** [comment]
:( bummer. I might reopen this on a later date tho ;)

**Comment by Darkere** [comment]
We might be able to convince the devs to use a tag for these.
