### ISSUE TITLE
JEI Addon: Range Tier 12

### ISSUE THREAD

**Issue by rolsch8026** [NillerMedDild/Enigmatica6#2822]
**Enigmatica6-0.5.6**

When clicking on a JEI bookmark of Addon: Range Tier 12, the recipe is not shown. However it is shown when clicking on a Addon: Range Tier 12 in JEI.

![2021-07-27_07 10 18](https://user-images.githubusercontent.com/82458985/127146832-5b11be0e-07d1-46af-9f33-d73b5595d0cc.png)

![2021-07-27_07 10 27](https://user-images.githubusercontent.com/82458985/127146849-136b4b9f-1116-4862-9917-2762594e3680.png)

**Comment by MuteTiefling** [comment]
I can't reproduce this. Are you adding anything to the pack? Can you try removing those things and see if you can reproduce the issue?

**Comment by rolsch8026** [comment]
I had Mob Grinding Utils installed. After removing it. I could not reproduce the issue.
