### ISSUE TITLE
JEI Addon: Range Tier 12

### ISSUE THREAD

**Issue by rolsch8026** [NillerMedDild/Enigmatica6#2823]
Enigmatica6-0.5.6

Can bookmark Addon: Range Tier 12 twice.

![2021-07-27_07 58 49](https://user-images.githubusercontent.com/82458985/127150539-10ba5d26-e22a-487d-9d59-947337e33f63.png)

**Comment by MuteTiefling** [comment]
duplicate #2822

**Comment by rolsch8026** [comment]
I had Mob Grinding Utils installed. After removing it. I could not reproduce the issue.
