### ISSUE TITLE
Integrated Crafting operations stuck 0.5.6

### ISSUE THREAD

**Issue by NoMoreStars** [NillerMedDild/Enigmatica6#2824]
**Enigmatica 0.5.6**

**Describe the bug**
Autocrafting using Integrated Dynamics Integrated Crafting addon seems to be bugged and will frequently get stuck on simple one-stage crafting recipes that cannot be cancelled without manually cancelling them with the Crafting Job Terminal. I created a setup which simply autocrafts a single coal block and outputs it into a nearby chest. The inventory connected to the system containing the coal is a locked Storage Drawer filled with coal with the only other inventory connected to the system being an empty chest.

Autocrafting will work once or twice as items are pulled out of the output chest, however after one or more times of items being pulled out of the system, crafts will get stuck with the Crafting Job Terminal, when examined displays the text: "Job started: waiting for outputs". This can be bypassed but only by manually cancelling the craft from the Job Terminal, making automated crafting impossible.

**Screenshots**
Initial setup I used:
![2021-07-27_11 49 122](https://user-images.githubusercontent.com/38673759/127200165-8973df88-5392-423b-960c-d076c961ac19.png)
![2021-07-27_12 01 272](https://user-images.githubusercontent.com/38673759/127200180-a1163c88-b160-4e7a-a26f-1b943b614710.png)

**Comment by NillerMedDild** [comment]
Thank you for the report. Would you mind relaying it here? https://github.com/CyclopsMC/IntegratedCrafting/issues

It seems like you'd be better equipped to answer follow-up questions than me 😄

**Comment by NoMoreStars** [comment]
Will do!

**Comment by vermz99** [comment]
This is still an issue in the latest E6 release. Is it supposed to be fixed?

**Comment by Darkere** [comment]
Which version is "latest" E6?

**Comment by vermz99** [comment]
0.5.11
