### ISSUE TITLE
Crash when attempting to break Immersive Engineering Feedthrough Insulators

### ISSUE THREAD

**Issue by Legohead259** [NillerMedDild/Enigmatica6#2825]
Enigmatica6 0.5.6

Fatal crash following attempts to break Immersive Engineering feedthrough LV insulator
![2021-07-27_20 06 59](https://user-images.githubusercontent.com/8077426/127243031-6b9bdb3a-46b1-41fb-ad0e-ccc3c3cbe59e.png)

**Logs**
https://pastebin.com/R2FZngtj

**Comment by JoaGamo** [comment]
it also happens with HV ones, didnt test with MV.

**Comment by NillerMedDild** [comment]
Thanks for the report, I believe it's fixed in dev: https://github.com/BluSunrize/ImmersiveEngineering/issues/4879

**Comment by Legohead259** [comment]
Just FYI, this bug is not fixed in 0.5.9 as is stated in the change logs.

**Comment by NillerMedDild** [comment]
Yeah my bad :P I tested it in creative, which doesn't cause the crash. We have this issue about it now, just to be confusing: #2836
