### ISSUE TITLE
SushiGo Crafting crops should be usable in other recipes

### ISSUE THREAD

**Issue by ManInTheMists** [NillerMedDild/Enigmatica6#2826]
Crops grown for the SushiGo mod should be usable in other recipes that use the same item from other mods.  Examples include cucumbers, soybeans, and rice.

**Comment by NillerMedDild** [comment]
Which version are you on? :)

**Comment by NillerMedDild** [comment]
Which recipes in particular are you thinking of? :)

**Comment by ManInTheMists** [comment]
I'm on 0.5.6, I play on the official E6 server.

In particular I was thinking of the Farmer's Delight and Simple Farming recipes.
