### ISSUE TITLE
JEI search by color function not working

### ISSUE THREAD

**Issue by Pactastic** [NillerMedDild/Enigmatica6#2828]
I might be missing something but enabling the search by color option in JEI does not seem to work. Tried enabled and with prefix, neither seem to do anything other than a normal search for things with the color in the name.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It works perfectly fine for me :)
![billede](https://user-images.githubusercontent.com/21295394/127382166-71000176-74b7-4ad2-b048-3276c23d6a3e.png)

Did you try on a server or in singleplayer?

**Comment by Pactastic** [comment]
In single player. Just realized I was playing on an older version as well.
Updated, will try again tomorrow to see if that helps
