### ISSUE TITLE
Safe of Supplementaries Duping

### ISSUE THREAD

**Issue by Strovo** [NillerMedDild/Enigmatica6#2833]
**Modpack version**
Enigmatica6-0.5.6
**Describe the bug**
Supplementaries safes are doubled (dupe) with everything in your interior

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
https://streamable.com/mu9gac

https://prnt.sc/1h7z1au

**Comment by Trostmm** [comment]
I just tried this and can confirm. In both claimed and unclaimed chunks.

**Comment by NillerMedDild** [comment]
Thanks for the report and confirmation, I've relayed it here: https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/109
