### ISSUE TITLE
Immersive Engineering crash when trying to break feedthrough

### ISSUE THREAD

**Issue by JoaGamo** [NillerMedDild/Enigmatica6#2836]
**Modpack version**
0.5.7
**Describe the bug**
When you try to break an Immersive Engineering feedthrough (HV/MV/LV) IN SURVIVAL (this does not happen in creative) you will see the missingtexture colors and a crash. This may seem duplicated from another closed issue, but even with the new update it's happening again.

**Logs**
https://pastebin.com/ZQgvWsXj

**Screenshots**
https://streamable.com/y5f2md

**Comment by NillerMedDild** [comment]
Ah damn, I only tested in creative ^^'
