### ISSUE TITLE
[0.5.7] Sophisticated Backpacks incompatible with Tinker's Construct Crafting Station

### ISSUE THREAD

**Issue by kman3107** [NillerMedDild/Enigmatica6#2837]
**Modpack version**
0.5.7

**Describe the bug**
Game crashes to desktop when putting a Sophisticated Backpack in to the Tinker's Construct Crafting Station.

**Logs**
https://pastebin.com/FASs8azt

**Screenshots**
![UpgradeCrash-v0 5 7](https://user-images.githubusercontent.com/10728652/127435930-420ab01b-d8f0-475a-982d-8fc1947d944d.png)

**Other**
I don't know which of the two mods are at fault. Therefore I don't know who to report to. Hope you can help out here :)

**Comment by NillerMedDild** [comment]
Should be fixed in a newer version of Sophisticated Backpacks :)
