### ISSUE TITLE
Clocks acquired from fishing loot not recognized by JEI/autocrafting.

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#284]
E6 0.2.16

Clocks acquired via fishing loot apparently have an extra NBT tag on them that prevents them from stacking with clocks that are crafted directly.  JEI and RS autocrafting also do not recognize the fishing loot clocks as valid recipe ingredients to automatically put in a recipe even with the 'exact' option turned off.  If the fishing loot clocks are manually inserted into the crafting table, they work properly in creating the object desired, they just are not recognized in the inventory by JEI and autocrafting.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Can you remember what the tag is?

**Comment by NillerMedDild** [comment]
I believe I've fixed it by disabled quark:tweaks.compasses_work_everywhere

**Comment by AdamNisbett** [comment]
I'm not sure how to check the value of the NBT tags.  I just noted that it said it had 1 NBT tag, while the crafted one did not.

**Comment by NillerMedDild** [comment]
Hmm... How do I verify this without fishing for hours...

**Comment by Darkere** [comment]
IF fisher?

**Comment by NillerMedDild** [comment]
![billede](https://user-images.githubusercontent.com/21295394/93390579-38210300-f86e-11ea-9682-75ec21bd3778.png)

**Comment by AdamNisbett** [comment]
Yeah, the IF fisher is how I acquired the clocks in the first place.  Though since it's via the loot boxes anyway I didn't figure it mattered what form of fishing it was.

**Comment by NillerMedDild** [comment]
Oh it's from a lockbox ^^' fixed, thanks.
