### ISSUE TITLE
[Expert] Ediolon/Blood Magic Gating Potentially backwards/Crafting Recipe issue

### ISSUE THREAD

**Issue by Raeis-Eikr** [NillerMedDild/Enigmatica6#2840]
**Modpack version**

**Describe the bug**
Weak Blood Orb from Blood Magic is required to craft Unholy Symbol from Eidolon.

Eidolon is above Blood Magic in the gating though. Is this intended?

![2021-07-30_00 41 59](https://user-images.githubusercontent.com/86083555/127523399-dffa6426-e7e6-4f00-b4ab-3f82d68b822f.png)
![2021-07-30_00 41 38](https://user-images.githubusercontent.com/86083555/127523414-8cb3c29f-e239-4174-bf2f-31a77eb7d519.png)

**Comment by TemperedFool** [comment]
Assuming this is from expert mode; I'll take a quick guess that it's intentional. The progression path will be nested - progress in mod one a bit, hit a roadblock that requires progression in mod 2 to continue mod 1, then hit a roadblock in both that requires mod 3 to continue in 1 and 2...

**Comment by Raeis-Eikr** [comment]
> Assuming this is from expert mode; I'll take a quick guess that it's intentional. The progression path will be nested - progress in mod one a bit, hit a roadblock that requires progression in mod 2 to continue mod 1, then hit a roadblock in both that requires mod 3 to continue in 1 and 2... @MuteTiefling would know for sure in this case.

Yeah, it's in expert, the thing is that eidolon is the first line of gates and blood magic is the third, Just seems a bit odd to me,

**Comment by RobuxShooters** [comment]
I think you're supposed to get the Unholy Symbol through one of the chants from Eidolon first before using it in Blood Magic. Then the recipe for the Unholy Symbol in the ARC Furnace is an easier (and automatable) method of acquiring it later down the line as opposed to having to continuously use the chants for an Unholy Symbol.

**Comment by MuteTiefling** [comment]
Probably best to keep this in the testing channel in Discord. 

Blood magic has a mechanic now where the ARC can be used to recycle unwanted blood orbs back into their input component. That's what you're seeing here.

The actual creation of the Unholy Symbol is done through Eidolon's crafting mechanics and this step has no JEI integration. You'll have to refer to the book. The quests also guide you towards making one. 

![image](https://user-images.githubusercontent.com/9543430/127529233-9631d364-3d33-4c1c-ae88-8300be8796e9.png)
