### ISSUE TITLE
`compactmachines:wall` uncraftable on expert mode

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#2842]
**Modpack version**

0.5.7

**Describe the bug**

the default recipe gets removed (2nd page), and only recipes for it get added to normal mode (1st page)
https://github.com/NillerMedDild/Enigmatica6/search?p=1&q=compactmachines%3Awall

**Comment by NillerMedDild** [comment]
Please stop reporting Expert mode issues :P it should be kept in Discord for now.

**Comment by Quezler** [comment]
which channel? (reports might get buried in #enigmatica6)

**Comment by NillerMedDild** [comment]
Invited to super secret channel of doom.
