### ISSUE TITLE
Duplication Bug using Unpackagers

### ISSUE THREAD

**Issue by Alec-KB** [NillerMedDild/Enigmatica6#2844]
Modpack version: 1.82a

If you're holding an unpackager using CarryOn, placing it down will place an exact copy of the unpackager down but tell you that it experienced an error in placing, so you end up still carrying one, and can repeat this to gain infinite of any recipe pack that's in there

**Comment by Darkere** [comment]
This is the enigmatica 6 github?

**Comment by Alec-KB** [comment]
Woops my bad
