### ISSUE TITLE
RFTools Builder no longer working for some reason

### ISSUE THREAD

**Issue by Merthew** [NillerMedDild/Enigmatica6#2845]
**Modpack version**
0.5.8

**Describe the bug**
I set up an RFTools Builder Quarry in the nether and used FTB Chunks to load it. It worked fine in 0.5.6 except for the bug with it not skipping lootr chests, when I updated to 0.5.7 to fix that it stopped working correctly though it does skip over the lootr chests. After leaving it alone in the nether for a little bit, it bugs out and has the "there is not enough room above or below the builder" message, even though the ender chest I am using is completely empty. Honestly I have no idea what is directly causing the problem and since its not like its a crash there's not really a way to check.

**Logs**
No crashes, just broken RFTools stuff

**Screenshots**
![image](https://user-images.githubusercontent.com/23420800/127622178-fc891634-ef08-4833-b77a-a5758b72cf17.png)
![image](https://user-images.githubusercontent.com/23420800/127622228-a89674f7-7560-49bc-8bd3-5fe9ea4f6ae5.png)

**Comment by Merthew** [comment]
Update: It happened again while I was standing right next to it. I reset the entire thing, unloaded and reloaded the chunk, broke and replaced everything and sat there and watched it. It ended up with this 
![image](https://user-images.githubusercontent.com/23420800/127623108-8d6dc029-5738-49d0-87ef-8a92ea052141.png)
after only a few chunks. The ender chest is still empty

**Comment by NillerMedDild** [comment]
May I have a screenshot of the Builder GUI, and a screenshot where the block below the Builder is visible please?

**Comment by NillerMedDild** [comment]
Perhaps try with a chest instead of an EnderChest.

**Comment by Merthew** [comment]
Alright, here you go: 
![image](https://user-images.githubusercontent.com/23420800/127624886-a7b0ffeb-5234-4659-be9c-61abfa4727b6.png)
![image](https://user-images.githubusercontent.com/23420800/127624979-655dff95-6241-4192-a898-f7e07b2c5a81.png)
I got it running again I think but I haven't left the nether yet and that's when the problems tend to happen.

**Comment by NillerMedDild** [comment]
Hmm.. perhaps stop chunkloading it. It's supposed to chunkload on it's own now.

**Comment by Merthew** [comment]
It did not stay loaded after unloading the chunk, so that seems like a different problem

**Comment by NillerMedDild** [comment]
Oh I must've misread the config: The Builder chunkloads the chunk it's working on, not it's own chunk.

**Comment by Merthew** [comment]
I left it running overnight and it doesn't seem to have happened again, but I haven't reloaded the game so I'm not 100% sure.

**Comment by NillerMedDild** [comment]
I'm gonna optimistically close this then :P feel free to comment further if it happens again, we can always reopen.
