### ISSUE TITLE
Potential bug with copy paste gadget

### ISSUE THREAD

**Issue by Equitime77** [NillerMedDild/Enigmatica6#2849]
Enigmatica 6 1.16.5 0.5.8

Ive just started this modpack in the past few days and updated it today. Ive used the copy paste gadget before a couple of times. This time I wanted to paste in Howester84's Waterwheel cottage/farm. I was in creative and couldnt even get it to preview nor build.

https://pastebin.com/huY6JyTy

**Comment by NillerMedDild** [comment]
Thanks for the report. Have you been able to paste that before? :)

**Comment by Equitime77** [comment]
Ive pasted another schematic of his on a different mod pack

**Comment by NillerMedDild** [comment]
Could you perhaps try the schematic out in an instance with just Building Gadgets? This might be a schematic issue, and not a modpack one.

**Comment by Equitime77** [comment]
Just tried it and nothing worked. I did notice that the template manager gui was different so maybe thats the difference? Resonant Rise (working) is at  2.8.3. Yours (not working) 1.16.5-3.8.0. Tested the same creator's arched house in both modpacks. Ive just started playing this modpack.

**Comment by MuteTiefling** [comment]
The format changed from 1.12 to 1.16. Old templates won't work.
