### ISSUE TITLE
unable to craft `material stonework factory` with crafting table variants

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#2850]
**Modpack version**

0.5.7

**Describe the bug**

some recipes that need a crafting table allow any variant (e.g. refined storage crafting grids, tinker tables, etc), the material stonework factory however only accepts `minecraft:crafting_table`, i believe this is not intended pack behavior:

(dunno if the pack or the mod's own tags are to blame, but since @Buuz135 is here as well he'll see it either way 🤔)

**Screenshots**

with a baobab crafting table:
![Screen Shot 2021-07-30 at 15 11 24](https://user-images.githubusercontent.com/3179271/127657811-7dddaeec-ba0d-4c96-92cd-08d542ca8d43.png)

with a vanilla crafting table:
![Screen Shot 2021-07-30 at 15 11 43](https://user-images.githubusercontent.com/3179271/127657813-c6644537-9f35-410b-91c6-75573b38760f.png)

**Comment by Erysch** [comment]
referring to #2643:
That's what I've warned about when adding the crafting table mod.

You should be allowed to convert the birch crafting table (and any other crafting table) into an oak crafting table (the default one) via the inventory crafting grid, or the crafting table tag should be added to these tables and to the recipes which is more annoying to set up. I don't know if some of this was implemented yet, couldn't test it for now.

**Comment by Quezler** [comment]
@Erysch yea i have that, i just find it silly to have crafting recipes for crafting tables to craft baobab and convert to normal:
![Screen Shot 2021-07-30 at 19 07 37](https://user-images.githubusercontent.com/3179271/127687939-91790643-ee03-4b94-9dc6-42a681769484.png)

**Comment by Erysch** [comment]
> @Erysch yea i have that, i just find it silly to have crafting recipes for crafting tables to craft baobab and convert to normal:
> ![Screen Shot 2021-07-30 at 19 07 37](https://user-images.githubusercontent.com/3179271/127687939-91790643-ee03-4b94-9dc6-42a681769484.png)
> 

agreeing, but this might be the easier way to implement
Let's see what the masters say. Of course it would be nice, if any crafting table would be compatible

**Comment by NillerMedDild** [comment]
I've tried to fix this by overriding the recipe in KJS, but without luck. I think the conditionals are messing with it, or something. @MuteTiefling I know you got this working for the Pity Machine Frame, would you mind having a look here as well?

**Comment by MuteTiefling** [comment]
Sure thing
