### ISSUE TITLE
Crash with 0.5.8

### ISSUE THREAD

**Issue by MushuPlatypus** [NillerMedDild/Enigmatica6#2851]
Game fails to load after update to 0.5.8

[crash report.txt](https://github.com/NillerMedDild/Enigmatica6/files/6907795/crash.report.txt)

**Comment by NillerMedDild** [comment]
Thanks for the report - It seems like something might've gone wrong during updating. Could you please reinstall and see if the issue persists?

**Comment by MushuPlatypus** [comment]
Think I found out what it was.  I had installed the Refined Curious mod, once it was disabled it worked.

That will teach me to meddle :)
