### ISSUE TITLE
Rftool fluorite ore

### ISSUE THREAD

**Issue by Evan91380** [NillerMedDild/Enigmatica6#2852]
0.5.6

**Describe the bug**
When you want to use fluorite to make an dimlet, rftool want mekanism fluorite ore but there is no way to get fluorite ore from mekanism, we can only get ore from emandatus enigmatica. That make it impossible to make dimension with fluorite ore

![Screenshot_3](https://user-images.githubusercontent.com/32957194/127668316-2bb55f19-4b8c-4aad-99de-fef971a29959.png)

**Comment by NillerMedDild** [comment]
This should be fixed in 0.5.7 :)
