### ISSUE TITLE
Framed Block crashes game when broken with chisel block in

### ISSUE THREAD

**Issue by LooLooAsuna** [NillerMedDild/Enigmatica6#2853]
**Modpack version**
0.5.7
**Describe the bug**
Game crashes when breaking a framed slope block.
Have not tested other framed blocks, and it had a chisel block in at the time

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
https://pastebin.com/YZY3UEPz
**Screenshots**

**Comment by NillerMedDild** [comment]
Thanks for the report. Can you reproduce this without Optifine? :)

**Comment by NillerMedDild** [comment]
Nevermind, very easy to reproduce ^^'

**Comment by NillerMedDild** [comment]
Relayed here:
https://github.com/Chisel-Team/Chisel/issues/887
https://github.com/XFactHD/FramedBlocks/issues/42

**Comment by XFactHD** [comment]
New release of FramedBlocks has just been approved on CurseForge.
