### ISSUE TITLE
Thermal mode change key does not work

### ISSUE THREAD

**Issue by ManInTheMists** [NillerMedDild/Enigmatica6#2854]
Version 0.5.8

Pressing the mode change key when holding a Thermal item in your hand does nothing.  I've seen this with the Insightful Crystal and the Flux Capacitor.  I've also changed the mode change key but there was still no response from the item.

**Comment by NillerMedDild** [comment]
You need to set it to a key that is otherwise unused. Could you please try that, and report back? :)

**Comment by ManInTheMists** [comment]
It's still a problem because any key that's used for something else disables Thermal items even if the other keybind doesn't affect the Thermal item at all.  For example, sharing a key with opening an Ars Noveau spellbook or switching item modes for Mekanism.  The latter does not have any issues with sharing a keybind.

**Comment by NillerMedDild** [comment]
Known and not considered a bug by the mod author, nothing we can do :)
https://discord.com/channels/399037120930512897/463062159866462219/871117156740374540

**Comment by NillerMedDild** [comment]
The mod dev found a workaround, that should be in the next Thermal update \o/
