### ISSUE TITLE
Shift clicking an upgrade into the Thermal Series Tinker's Workbench makes the upgrade disappear 

### ISSUE THREAD

**Issue by greggdogg** [NillerMedDild/Enigmatica6#2855]
**Modpack version**
Version 0.5.8

**Describe the bug**
Title of the post describes it all

**Comment by DarkAngel22579** [comment]
Click on the green "augmentation" tab in the top right corner of the GUI, you should find the augment in there

**Comment by greggdogg** [comment]
> Click on the green "augmentation" tab in the top right corner of the GUI, you should find the augment in there

Ohh I see them now, thank you
