### ISSUE TITLE
Infinity Tools Challenge Quest not registering properly

### ISSUE THREAD

**Issue by kingofrunes** [NillerMedDild/Enigmatica6#2859]
**Modpack version**
0.5.6

**Describe the bug**
The Infinity Tools Challenge Quest under Challenges is not registering items properly. I have an Infinity Drill, Infinity Hammer, Infinity Trident, Infinity Saw, and Infinity Backpack all at Artifact tier and it's not registering them. I also went ahead and made a fresh Infinity Hammer and used the Mekankism method to create another one at Artifact Tier and it still didn't register. Additionally clicking on the items in the challenge quest gives a No Valid Items message.

I also notice this happens with the Limitless Water Challenge Quest as well.

**Logs**
N/A

**Screenshots**
Infinity Tool at Artifact Tier
https://puu.sh/I0oBp/51b9db5669.png

No Valid Items
https://puu.sh/I0oCi/5be1ba548a.png

Report Bug to Mod Author
https://puu.sh/I0oBN/49f8c07a60.png

Challenge Pre-req completed
https://puu.sh/I0oD6/adcb274b01.png

Supreme Black Hole Tank filled with Water
https://puu.sh/I0oIM/55f42be1d2.png

Supreme Black Hole Tank w/ Water Invalid
https://puu.sh/I0oKK/31439bc9ca.png

**Comment by MuteTiefling** [comment]
Very odd. I just tested these when I added the launcher and nuke... Can you try updating please?

**Comment by kingofrunes** [comment]
We are using the latest version 0.5.6. I tested on Singleplayer and it does work. However on the 0.5.6 Multiplayer Server it's not registering on there.

**Comment by MuteTiefling** [comment]
If it's not working on the server, this seems like more of an installation issue with the server itself.
