### ISSUE TITLE
Crash when near skeletal horse {maybe just trap}

### ISSUE THREAD

**Issue by Hraefin** [NillerMedDild/Enigmatica6#286]
**Modpack version**
Enigmatica 6 0.2.16

**Issue**
Server crashes if player gets near a skeleton horse
This is a new world, we have had this happen twice in different locations.  Basically we believe that if you trigger a skeletal horse trap, the server crashes.  On reload skeleton horse seems to be gone.

**Logs**
Sadly I was not able to copy current log

**Comment by NillerMedDild** [comment]
Could it be the same as this issue perhaps? :)
https://github.com/NillerMedDild/Enigmatica5/issues/482

**Comment by Hraefin** [comment]
This does look similar.
However, we did not have to intervene other than restarting the server both times it occurred.  
Mostly just wanted to let you know it was happening.  I could try the tick time modification, but I am not entirely clear if there are potential side-effects to making that change.

**Comment by NillerMedDild** [comment]
I recommend making the tick time modification regardless, the recommend server.properties have it set to 0 or -1 :) I find it's a good idea on modded servers.
Anywho, this should be fixed in 1.16.3 I believe 🤞

**Comment by Hraefin** [comment]
Thank you!

**Comment by Celant** [comment]
@NillerMedDild Looks like we've just experienced the same thing. The player was near a horse, and then the horse was struck by lightning creating a skeleton horse, immediately crashing the server.

Logs: https://pastebin.com/JRwtDEEB

The fix in our case was to NBT edit the player to different world coordinates, and let the horse despawn. The server by default had `max-tick-time` set to `-1`, and I worry that setting it to `0` as mentioned in the other issue will cause the slightest hitch to kill the server.

**Comment by Darkere** [comment]
Minecraft checks for max-tick-time > 0 before starting the watchdog. So -1 is just as good as 0 :)
