### ISSUE TITLE
Wall Jump! and Elenai Dodge 2

### ISSUE THREAD

**Issue by P0TA70** [NillerMedDild/Enigmatica6#2861]
https://www.curseforge.com/minecraft/mc-mods/wall-jump 
https://www.curseforge.com/minecraft/mc-mods/elenai-dodge-2

light mods related to ingame movement. Wall Jump! adds two major new things- wall clinging (jumping towards a wall and pressing shift to "cling" on the wall), and jumping (jumping from a wall), and a few other configurable stuff
elenai dodge 2 adds a new dodge mechanic that can be used if the dodge bar is filled enough, which regenerates over time

i think these new movement mechanics can be just neat little stuff in the pack

**Comment by NillerMedDild** [comment]
No thank you, too much can go wrong with movement mods imo :P
