### ISSUE TITLE
Create builds - blocks vanish when contraptions stop.

### ISSUE THREAD

**Issue by sinfuldarkus** [NillerMedDild/Enigmatica6#2862]
**Modpack version**
Enigmatica 6 0.5.7

**Describe the bug**
When stopping Create builds, the blocks simply vanish.
They are still 'there', but do not show.
Right-clicking with an empty hand makes them reappear.
This was also reported on the Create github issues page, the other people affected appear to also be using Enigmatica 6.
https://github.com/Creators-of-Create/Create/issues/2029

**Screenshots**
https://github.com/Creators-of-Create/Create/issues/2029

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please update Create and see if the issue persists?

**Comment by NillerMedDild** [comment]
I haven't been able to reproduce this issue, does it only happen for some contraptions?

**Comment by sinfuldarkus** [comment]
I haven't built too much yet (New to Create.) so right now I only have a simple spinning harvester setup for wheat (Campfire, Encased Fan, Mechanical Bearing, Linear Chassis, and some Harvesters.)
I'll try to record and provide a video of what happens when I get back home today.

**Comment by NillerMedDild** [comment]
Sounds good, thank you :)

**Comment by sinfuldarkus** [comment]
https://www.youtube.com/watch?v=4iEqtjOGDxk

**Comment by NillerMedDild** [comment]
Thanks! Are you playing on a server?

**Comment by sinfuldarkus** [comment]
Yes, although it's self-hosted using Docker (itzg/minecraft-server)
I am the only player at the moment.

**Comment by NillerMedDild** [comment]
Did you try updating manually? :)

**Comment by sinfuldarkus** [comment]
I tried to update to the newest release of Create and Flywheel, but the container kept crashing on start afterwards.
I've reverted back to the original versions for now.
Unfortunately I do not have logs available for it.

**Comment by NillerMedDild** [comment]
I cannot reproduce this on a server with Create & Flywheel updated, so I'm hopeful that the issue is fixed :)

**Comment by ArMoReDfUrY** [comment]
> I cannot reproduce this on a server with Create & Flywheel updated, so I'm hopeful that the issue is fixed :)

what versions of create and flywheel are they?

**Comment by NillerMedDild** [comment]
- create-mc1.16.5_v0.3.2c
- flywheel-1.16-0.2.0
- kubejs-create-1605.1.2-build.7

**Comment by ArMoReDfUrY** [comment]
ok thanks. will use flywheel 0.2.1 though as 0.2.0 has a lot of CTD issues i hear.

**Comment by NillerMedDild** [comment]
So will the next release, it just wasn't available during my test :)

**Comment by ArMoReDfUrY** [comment]
all good, i just wasn't sure as the OP is using the outdated beta.
iv'e been keeping up with the issue page here and implementing the fixes your team has in the repo on my copy of this fine pack.
this is the 1st time iv'e needed any clarification. your team does a great job keeping this thing smooth as butter 👍

**Comment by simibubi** [comment]
In investigating this issue further, I saw that this pack has a very large amount of blockstate ids, which not all of vanilla's netcode is prepared for.
You can run into this same issue by simply using the /fill command with certain modded blocks. 
For instance, cobblestone bricks from Quark with the id 603769 reached the client as -444807

The modder someaddons has created a mod which addresses this issue, consider adding it to the pack: 
(Mind the extra configuration it requires in order to work alongside 'randompatches')
https://www.curseforge.com/minecraft/mc-mods/connectivity
Cheers!
