### ISSUE TITLE
Coal Conversion Issue

### ISSUE THREAD

**Issue by TheCowKing-moo** [NillerMedDild/Enigmatica6#2864]
0.5.6

Using the campfire recipe (apotheosis) stick -> torch one can automate coal production from only wood

crafting loop -> 
 - create deployer puts a stick into a farmers delight stove
 - stove makes torch from stick
 - 4 torches into Mekanism sawmill to get 1 coal and 1 stick

this conversion then costs 3 sticks + rf to power the sawmill

one can also convert any torch recipe inputs into coal such as charcoal, lignite, etc

**Comment by TemperedFool** [comment]
Imo, if you're bloodyminded enough to set this up I'm not sure it's really a problem - a tree farm from one of like 50 mods we have will yield a ton of charcoal. Is a very creative loop!

**Comment by MuteTiefling** [comment]
There's very little that explicitly requires coal too. Charcoal works for most things and is way easier to automate.

**Comment by TheCowKing-moo** [comment]
while true there are two recipes to be wary of in this pack. 

1. Coal Block to Diamond recipe from pneumaticcraft  
2. Coal Block to Steel Block thru bees 


Felt like a hacky way of getting diamonds(despite the huge infrastructure costs) so i thought id bring it up.

**Comment by NillerMedDild** [comment]
I'm fine with this existing tbh, but thanks for reporting it anyway!
