### ISSUE TITLE
Implement Planks to Sticks / Sticks to Sawdust Recipes in Various Sawing Devices

### ISSUE THREAD

**Issue by RobuxShooters** [NillerMedDild/Enigmatica6#2865]
**Description**
Various sawing implements like the Mechanical Saw from Create, IE's Sawmill, and Thermal's Sawmill should be able to carry out recipes similar to Mekanism's Precision Sawmill, for instance 1 plank to 6 sticks and 1 stick to 1 sawdust.

**Why would you like this added/changed?**
This provides a bonus to stick yields from planks and an easier way to obtain sawdust than by luck from sawing logs down to planks. It also provides parity with the Precision Sawmill for those who do not want to use Mekanism.

**Comment by MuteTiefling** [comment]
Never did care for that stick to dust one, honestly. You know how hard it is (and unsafe) to grind a stick down to only saw dust with a saw?

Better to stick it in a crusher of some sort.

**Comment by NillerMedDild** [comment]
After investigating a bit, I'd rather remove the Mekanism recipes tbh :P plank -> stick and stick -> sawdust is a bit too easy of a way to get massive amounts of sawdust.

**Comment by NillerMedDild** [comment]
I spoke too soon, I'll give this some more thought.

**Comment by TemperedFool** [comment]
Seems to work as advertised...
