### ISSUE TITLE
[expert] bone smelting has two recipes

### ISSUE THREAD

**Issue by redgoblin88** [NillerMedDild/Enigmatica6#2866]
**Modpack version**
0.5.8

**Describe the bug**
when smelting bones, you are meant to get 2 "enchanted ash" from eidon, however there is already a furnace recipe which yields 3 bonemeal, that takes priority

**Screenshots**
![2021-08-01_18 26 19](https://user-images.githubusercontent.com/13396472/127780094-a3a26416-b7d6-4e6c-99f6-d0b57ce12644.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I can't reproduce this, might've been fixed in-dev?
