### ISSUE TITLE
FPS reduced pretty dramatically going from 0.5.6 to 0.5.8

### ISSUE THREAD

**Issue by DoomSquirter** [NillerMedDild/Enigmatica6#2867]
**Modpack version**
0.5.8
**Describe the bug**
was playing on a server (0.5.6).  server was updated to 0.5.8 and my main base was previously 120+ fps (varying from 90-120 at times)
after I log in now, I'm getting 30-40 fps

I carried over my options.txt so all my settings are intact.  

if you really need logs I can get you logs but I don't see anything that I wasn't seeing in 0.5.6 in there

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
A sample of the client thread from spark would be very helpful, please use the command `sparkc profiler --timeout 50` and paste the resulting link here.

**Comment by DoomSquirter** [comment]
did you guys add spark in update?  
here's link:
https://spark.lucko.me/Xy0dzjik3n

doesn't look like much.

**Comment by NillerMedDild** [comment]
Nope, it's been in the pack for a good while. Thanks for the sample!

Could you perhaps downgrade to 0.5.6, and take another sample so we have something to compare with?

**Comment by DoomSquirter** [comment]
I can't.  server's on 0.5.8, my world is on 0.5.8 now.  ssp experience would guaranteed to be different than I had on server.  sorry.  all I got to say is that there were no mod adds, a couple of changes that shouldn't affect fps (increased claims, waystone to not needing xp, enderchests to bigger size internally).  that's it.    tps is always 20.  my connection to server is usually good to perfect.  there was 30-40 minutes difference between when fps was good/normal to not (cause of updating).  so no clue.  

never used spark.  does it have a fps profiler?  I'll look into it

**Comment by NillerMedDild** [comment]
The FPS profiler is the one you used :)

Alright, fair enough. I'm afraid there's not much more I can do at the moment, but I'll keep an eye out for this issue.
