### ISSUE TITLE
lapis chunks show 2 recipes in the mekanism enricher

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#2868]
**Modpack version**

 0.5.7

**Describe the bug**

checking the `U`sage of a lapis chunk shows 2 possible enrichment chamber recipes, the 2nd screenshot was obtained by pressing `R`ecipe on lapis, which shows the chunks & blocks alternating places, putting a chunk in seems to always return 9.

**Screenshots**

![Screen Shot 2021-08-01 at 17 50 46](https://user-images.githubusercontent.com/3179271/127781700-70e8fa6a-4ee2-4324-bf91-9c4bbb6e75f9.png)

![Screen Shot 2021-08-01 at 17 52 14](https://user-images.githubusercontent.com/3179271/127781702-f265f009-d7f9-43a7-8653-192fdd067bec.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, fixed :)
