### ISSUE TITLE
Mod suggestion: Glassential

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#287]
https://www.curseforge.com/minecraft/mc-mods/glassential

It's the special glass mod that was in Enigmatica 4 and 5. It's ported to 1.16.2 and .3 (but not .1), and it should work with CTM (which is already in the pack if I read correctly).

~~I sadly do not have mods from other people to suggest yet.~~

**Comment by NillerMedDild** [comment]
It'll be added :)
