### ISSUE TITLE
Mekanism Pressurized Reaction Chamber don't work with speed upgrade

### ISSUE THREAD

**Issue by LilPatato** [NillerMedDild/Enigmatica6#2871]
**Modpack version:** 0.5.8

**Describe the bug**
Pressurized Reaction Chamber does't want to work with the 8 speed upgrades. It can work with a maximum of two speed upgrades. This problem was not there in 0.5.6 (last version of my game before I upgrade to 0.5.8).

**Screenshots**
![Bug_Meka_1](https://user-images.githubusercontent.com/68117243/127786623-70103aa7-9edd-42f4-ba0d-4f32d6457dd6.PNG)
![Bug_Meka_3](https://user-images.githubusercontent.com/68117243/127786736-d801648d-5f8c-44ce-9205-60d281f11560.PNG)

**Comment by Merthew** [comment]
You need energy upgrades because the fe/tick cost is higher than the total buffer when you have that many speed upgrades

**Comment by MuteTiefling** [comment]
Make Machines don't run if the cost of the recipe exceeds the total power buffer. Add Energy upgrades.
