### ISSUE TITLE
rftools builder won't place saplings anymore after update to 0.5.8

### ISSUE THREAD

**Issue by DoomSquirter** [NillerMedDild/Enigmatica6#2874]
**Modpack version**
0.5.8

**Describe the bug**
I had a 2 builder mega spruce tree farm going in 0.5.6 no issues

just noticed that the saplings aren't being placed.  I grabbed the shape card out, reset it's coordinates and put it back in builder and it just does nothing.  changed the soil from podzol to dirt (it'll change anyways to podzol) and still won't place.  I tried placing saplings in a different part of my base, still nothing.  

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please provide screenshots of your farm?

**Comment by DoomSquirter** [comment]
https://i.imgur.com/en7JHg1.png

again, worked fine before.  now it doesn't.  I have > 1 million charcoal to prove it :)

**Comment by DoomSquirter** [comment]
damnit, I was about to take another pic to show that saplings grow fine if manually placed, which I did.  and for shits and giggles, turned on the builder with shape card on and boom, it placed the saplings now.  /tableflip

NO clue!  sorry to waste your time I guess.  don't know what was causing the issue initially.  seems to be gone now.  closing.
