### ISSUE TITLE
1Gold Ingot in Stone Cutter is 4 Light Weighted Pressure Plate

### ISSUE THREAD

**Issue by kman3107** [NillerMedDild/Enigmatica6#288]
**Modpack version**
0.2.16
No settings changed, and no mods added or removed.

**Issue**
Gold Ingot can be used in Stonecutter to make Light Weighted Pressure Plate.
There are 2 options. First option makes 1 Light Weighted Pressure Plate from 1 Gold Ingot, 
Second option makes 4 Light Weighted Pressure Plate from 1 Gold Ingot.

![Gold_PressurePlateX4](https://user-images.githubusercontent.com/10728652/93407605-e048c300-f892-11ea-84bf-49cff5624f31.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get that removed.

**Comment by NillerMedDild** [comment]
Reported to the mod dev responsible :) https://github.com/Rohzek/Actually-Useful-Stonecutter/issues/7
