### ISSUE TITLE
Upgrade Aquatic's Thrasher still overspawning

### ISSUE THREAD

**Issue by SilverRuin** [NillerMedDild/Enigmatica6#2881]
**Modpack version**
0.5.8

**Describe the bug**
Despite Thrasher spawn weight being reduced to 30 in the recent build, there's still quite a lot of them spawning in cold ocean biomes with sufficient depth and open space. In shallower areas only a few will spawn in chasms, but these wide open areas still have tons spawning, with the same issues reported in #2795 

**Screenshots**
![2021-08-02_18 44 37](https://user-images.githubusercontent.com/88354170/127938430-dc8fd1c1-9fc2-4c75-bad0-886446403828.png)

**Comment by NillerMedDild** [comment]
I don't think there's anything we can do about it tbh, seems like they're the only mobs that spawn in that biome, no matter what their weight is you'll see many spawns.
