### ISSUE TITLE
Redstone Pen

### ISSUE THREAD

**Issue by ArMoReDfUrY** [NillerMedDild/Enigmatica6#2884]
https://www.curseforge.com/minecraft/mc-mods/redstone-pen

very similar to the redstone paste mod.
allows more control for redstone placement and lets it be placed on walls and roofs.
very low impact mod, vanilla themed, basic switches & bridge for lowering the footprint of contraptions. 
mod is made by wilechaote, same author of engineers decor & Gauges & Switches 

i would like this for cleaner smaller redstone builds with less block updates and lower server impact on contraptions not suitable for immersive engineering redwires & it's a good early tier before getting into wireless redstone via Gauges & Switches.
i have tested it in my copy of enigmatica 0.5.8 with no issues, recipe conflicts or visible impact on TPS.

Screen shots are provided on the mod link above.

thanks for your consideration.

**Comment by NillerMedDild** [comment]
Looks like a solid mod, I'll test it in-game and hopefully add it.
