### ISSUE TITLE
Orcinus's Caves Mod

### ISSUE THREAD

**Issue by TheMegaOverlord** [NillerMedDild/Enigmatica6#2885]
https://www.curseforge.com/minecraft/mc-mods/orcinuss-caves

**Description**
So, I've been playing Better Minecraft over the last couple of days and got to really explore the mining side of this pack, and the cave and underground biome gen of this mod has some serious potential. It integrates the underground biomes of Quark and the Caves and Cliffs backport super well, evenly distributes different types of stone and ore (which would be perfect for Emendatus Enigmatica), and the best part is the mod's cave generation is compatible with Terraforged. 

**Why would you like this added/changed?**
Not only would this mod spice up spelunking and make caving more interesting, it already works well with a lot of underground generation mods without destroying any structures. If you pair this with the Caves and Cliffs backport (which is entirely optional but would make caves 2x better as they would be with just Orcinus's alone) then you could be looking at your pack simulating the best parts of the caves and cliffs update long before part 2 is even out. You guys never failed on adding the best of the best in terms of mods, and I believe this is it! At the very least, I'll appreciate y'all for experimenting with this mod and seeing how it works with underground generation and everything else. 

**Screenshots if applicable.**

![image](https://user-images.githubusercontent.com/29565420/128194374-71e11e9b-ba62-455c-8dd0-d9a8403c281e.png)

![image](https://user-images.githubusercontent.com/29565420/128194397-ff0886e5-a074-4862-8d9c-c4b072bd5918.png)

**Comment by NillerMedDild** [comment]
I'm afraid this is a no based on the following:
- The mod is closed source. This makes troubleshooting harder for us, as we cannot investigate the code.
- The mod is licensed as All Rights Reserved. This further limits us when troubleshooting, and means that it cannot be picked up again if the mod author should ever abandon the mod.
- The mod has no issue tracker.
- Enigmatica 6 is already fairly heavy, adding to cave generation will undoubtedly have a negative impact on performance.

**Comment by TheMegaOverlord** [comment]
Understand, thank you Niller!
