### ISSUE TITLE
Enigmatica 6 Server crashing almost every other day

### ISSUE THREAD

**Issue by NaruTeribery** [NillerMedDild/Enigmatica6#2887]
**Modpack version**
0.5.6

**Describe the bug**
I am hosting a server of Enigmatica 6 for friends of mine who had initially hosted it on Bisect, and after working through a lot of issues and weeding through the codes, I thought I finally had them fixed, but the server still crashes almost ever other day. The crash logs I've been seeing lately are all the same, and I can't figure out why. Any help would be appreciated. **NOTE** The only code in the modpack I DID change was the code that restricted the max RAM to 5GB and raised it to 10GB.

**Logs**
https://pastebin.pl/view/cefee182

**Screenshots**

**Comment by jkirkpatrick** [comment]
Computer Craft / cc-tweaked was added (see lines 70, 76, and 851) and in the crash dump. The files ComputerThread.java:364 and ComputerThread.java:463 are referenced in the dump, the problem may be a bug in a player lua script running? Perhaps try removing that mod?

` cc-tweaked-1.16.5-1.97.0.jar                      |CC: Tweaked                   |computercraft                 |1.97.0              |DONE      |Manifest: NOSIGNATURE` 

For me, Computer Craft has been nothing but trouble for all versions after 1.6.8, especially on servers; OpenComputers is a lot more stable IMO but I haven't used it after 1.10
