### ISSUE TITLE
Mekanism Step Assist Not Working

### ISSUE THREAD

**Issue by rodin88** [NillerMedDild/Enigmatica6#2890]
**Modpack version**
0.5.6

**Describe the bug**
The mekanism free runners, as well as the meka-boot hydraulic propulsion upgrade, both have step assist features, however this does not work for me. I am on a server. Do note the botania sashes do work with regards to enabling step assist. I have ensured the client tweaks "step assist disabled" is OFF. 

**Logs**
n/a

**Screenshots**
n/a

**Comment by NillerMedDild** [comment]
Duplicate of #2789
