### ISSUE TITLE
Ender Block sharing recipe, prevents Compact Machine Wall from being crafted

### ISSUE THREAD

**Issue by Chintagious** [NillerMedDild/Enigmatica6#2892]
**Modpack version**
0.5.6

**Describe the bug**
Crafting a 2x2 Ender Pearl results in an "Ender Pearl Block" (Architect's Palette) instead of "Ender Block" (BetterEnd Forge) which prevents creating "Compact Machine Wall" (Compact Machines 4) in the "Metallurgic Infuser" (Mekanism).

**Logs**
N/A

**Screenshots**
N/A

**Comment by Ridanisaurus** [comment]
You can cycle through conflicted recipes. 
![image](https://user-images.githubusercontent.com/64355028/128434775-23a12408-aeb9-495f-b342-0c940c3945df.png)

**Comment by Chintagious** [comment]
Oh I had no idea @Ridanisaurus! Thanks for the heads up. 👍 I'll close this ticket then.
