### ISSUE TITLE
[Mod Suggestion] ColorUtility

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#2895]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/colorutility

**Mod description**
>Make handling ColorCode more easily. 
>
>
>
>
>- ColorUtility makes minecraft receive "§" character.
>- When you edit signs or books, Useful colorpad support you to edit them with color string.
>- ColorUtility works in Server and Client.
>- If you have to paint text and make text bold or italic at the same time, you should push ColorButton before push >- TextFormButton.

**Why would you like the mod added?**
Lightweight and easy to use mod which should be a no-brainer. It let's you format when sign editing, anvil renaming and when book and quill'ing. The handy GUI makes it pretty straight forward.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/81813584/128512002-3955ba75-8943-477b-bc00-c5b6c758f466.png)
![image](https://user-images.githubusercontent.com/81813584/128512011-510530a0-3e00-45e2-9bed-4a5f59b0b557.png)
![image](https://user-images.githubusercontent.com/81813584/128516281-714b0624-0e3c-4ae9-b3ac-d4f8013e764c.png)

**Comment by ArMoReDfUrY** [comment]
sounds cool, but it might conflict with the Apotheosis affix system for tools & armour.
repairing them can cause them to go a bit broken as is.

**Comment by NillerMedDild** [comment]
This mod feels a bit bloaty to be honest, I'd rather not include it.

**Comment by Erysch** [comment]
> This mod feels a bit bloaty to be honest, I'd rather not include it.

aye sir

It actually uses the vanilla coloring system. So when loading the world without mods the color should be still there.
