### ISSUE TITLE
[Mod Suggestion] CC:Tweaked (Computer Craft)

### ISSUE THREAD

**Issue by SQbuilder** [NillerMedDild/Enigmatica6#29]
https://www.curseforge.com/minecraft/mc-mods/cc-tweaked

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, but I would rather not added CC: Tweaked, as I feel the vast majority of users don't use it.

**Comment by ManiacRobert1** [comment]
Since mekanism structures added support for CC:Tweaked, can you maybe reconsider it?

**Comment by NillerMedDild** [comment]
I'll reconsider, but no promises :)

**Comment by Darkere** [comment]
There is also an RS addon floating around ;).

**Comment by NillerMedDild** [comment]
Screw it, I yield :P

**Comment by Thiana** [comment]
https://www.curseforge.com/minecraft/mc-mods/refined-storage-for-computercraft/files/3158056

The RS integration mod. Has a nice API that will be really useful for expert mode later.

**Comment by NillerMedDild** [comment]
> 
> 
> https://www.curseforge.com/minecraft/mc-mods/refined-storage-for-computercraft/files/3158056
> 
> The RS integration mod. Has a nice API that will be really useful for expert mode later.
> 
> > **[Attention Required! | Cloudflare](https://www.curseforge.com/minecraft/mc-mods/refined-storage-for-computercraft/files/3158056)**

already added :D
