### ISSUE TITLE
Payload may not be larger than 1048576 bytes

### ISSUE THREAD

**Issue by Petapaka** [NillerMedDild/Enigmatica6#2904]
**Modpack version**
0.5.4

**Describe the bug**
When the Refined Storage system has more than about 128k items, the client crashes trying to access it. Attempted using different combinations of disks, but couldn't prevent the bug from occurring.

**Logs**
latest.log was too large for pastebin and there weren't any crash logs on the client. If there's something else I can provide, please let me know.

**Screenshots**
![image](https://user-images.githubusercontent.com/27441639/128555365-26b399d2-fa4c-429d-8938-a3654b7e2591.png)

**Comment by Darkere** [comment]
Remove some items with lots of NBT from the disk. Usually mob drops or bees are the biggest contributers to the problem.

**Comment by NillerMedDild** [comment]
It's possible that this issue is no longer present on modpack version 0.5.9, if you could report back whether it's fixed that'd be nice :)

**Comment by Darkere** [comment]
It is :(

**Comment by Petapaka** [comment]
I updated to 0.5.9, but had already mitigated the issue by moving the excess armor and weapons pieces to a separate network. I'm no longer having the issue. I believe Darkere's comment was the exact problem, collecting too many mob drops (armored wither skeletons from roguelike dungeons) in the same refined storage system.

I can attempt to replicate the issue if it would be absolutely helpful to you, but separating the systems seems to have done the trick to resolve it.

**Comment by NillerMedDild** [comment]
It would be pretty helpful if you could replicate it, but if you'd rather not that's totally fine👍
