### ISSUE TITLE
Oh the Biomes you'll go nether blocks/Items

### ISSUE THREAD

**Issue by TzarTz** [NillerMedDild/Enigmatica6#2905]
**Description**
There are many blocks, plants and items that are no longer obtainable due to the removal of the BYG nether.

**Why would you like this added/changed?**
They would be nice to have. one of the plants are also useful for slimeball alternatives which can be automated.

**Screenshots if applicable.**

**Comment by MuteTiefling** [comment]
Most of these should be available through other means. Check the market for the tree, for instance.

If not, just let us know what specific items are missing.

**Comment by TzarTz** [comment]
for the moment, the only one i can think of that is useful is the ember wart sapling

**Comment by NillerMedDild** [comment]
You can get that through Natural Altar Infusion, it's in JEI :)
