### ISSUE TITLE
Crash when checking JEI for uses with Red Arid Sand and Fluid Sieving Machine

### ISSUE THREAD

**Issue by Tirimisu** [NillerMedDild/Enigmatica6#2906]
[crash-2021-08-06_19.24.41-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6948494/crash-2021-08-06_19.24.41-client.txt)

0.5.6

Crash when checking JEI for uses with Red Arid Sand and Fluid Sieving Machine.
Was able to replicate crash.

https://pastebin.com/BYW3cDra

**Comment by NillerMedDild** [comment]
Duplicate of #2771
