### ISSUE TITLE
Bookshelf break = Cooking for Blockheads Book > Normal Books

### ISSUE THREAD

**Issue by xxbones21xx** [NillerMedDild/Enigmatica6#2907]
**Modpack version**
5.6

**Describe the bug**
Breaking bookshelves returns a single cooking for blockhead book instead of a chance of normal books.

**Logs**
No log entries for this issue.

**Screenshots**
N/A

**Comment by RobuxShooters** [comment]
Did you happen to have any autosmelting tools / trinkets / curios / etc. active? This is because the recipe for the Cooking for Blockheads book is obtained by smelting a book in a furnace, which your tool / trinket / etc. may be smelting the books from the broken bookshelves into.

**Comment by MuteTiefling** [comment]
This is absolutely an auto smelt scenario. Cooking for blockhead's book is made by smelting a regular book.

**Comment by xxbones21xx** [comment]
Apologies. I totally thought the trinket only applied to things "mined" as it states in the trinkets description. Did not put two and two together. Thanks!
