### ISSUE TITLE
client crashes when opening a world

### ISSUE THREAD

**Issue by istoOi** [NillerMedDild/Enigmatica6#2908]
**Modpack version**
6-0.3.6

**Describe the bug**
crash when opening a world. spawn preparation progress gets to 100%

**Logs**
[pastebin](https://paste.ee/p/wJriG )

--------

It was running fine the first time i run the modpack. After installing java 16 and adding a 1.17. instance i was running into issues with Enigmatica. First the pack wouldn't even load. After deleting and reinstalling java 8 and installing the (at that time) newest version of Enigmatica i got it to at least load again. but it won't open even a newly created world.

**Comment by Darkere** [comment]
Why are you running .... 20 versions behind? Running with `-Djava.net.preferIPv4Stack=true` might help you in this case.
