### ISSUE TITLE
Mekanism Cardboard Box "deleting" waystones

### ISSUE THREAD

**Issue by oof2win2** [NillerMedDild/Enigmatica6#2909]
**Modpack version**
0.5.6
**Describe the bug**
When a Mekanism Cardboard Box is used on a Waystone, only the bottom part of said waystone is left and it is removed from your discovered and named waystones. When the bottom part is mined, it doesn't give back anything either.

**Screenshots**

![](https://i.imgur.com/Id0u8dh.png)
This waystone was previously named *Nuclear Power* and discovered, however after boxing and unboxing it, only the bottom part is left.

**Comment by NillerMedDild** [comment]
Thankd for the report, fixed in-dev
