### ISSUE TITLE
Mod suggestion: Reload Audio Driver

### ISSUE THREAD

**Issue by chaoaretasty** [NillerMedDild/Enigmatica6#291]
Minecraft hates when you change audio devices, simple mod here to let you easily reload just the audio driver rather than needing to restart MC

https://www.curseforge.com/minecraft/mc-mods/reload-audio-driver-rad

**Comment by Darkere** [comment]
The mod is already in the pack?

**Comment by chaoaretasty** [comment]
It is? I didn't see anything with "audio" in the modlist

**Comment by Darkere** [comment]
the mods filename is "rad"

**Comment by chaoaretasty** [comment]
D'oh, thank you. I've been reloading Minecraft like a chump haha
