### ISSUE TITLE
Recipe collision between CC wired modem, and Chisel's Futura blocks

### ISSUE THREAD

**Issue by RealGrep** [NillerMedDild/Enigmatica6#2910]
**Modpack version**
0.5.9

**Describe the bug**
It's impossible to craft ComputerCraft's wired modems with Refined Storage patterns, because the recipe is the same for various Chisel Futura blocks, and it finds them first.

Easily replicated by trying to make a pattern for the wired modem in the pattern grid, or you can see the clash by pulling the recipe in from JEI in the crafting grid, and clicking the little recipe clash resolver button above the output.

**Comment by NillerMedDild** [comment]
Thanks for the report, I fixed it in-dev.
