### ISSUE TITLE
Travel Anchor Can't Be Seen through Blocks

### ISSUE THREAD

**Issue by MFWalter** [NillerMedDild/Enigmatica6#2911]
**Modpack version**
0.5.8

**Describe the bug**
The Entity Culling mod is blocking the tile entity Travel Anchor from being able to be seen through blocks when using a travel staff or standing on another travel anchor.

**Logs**
N/A

**Screenshots**
N/A

**Comment by DraGonFiirE** [comment]
Also while we are at Entity Culling: 
```
#Tile entities with a width or height greater than this value will always get rendered.
#Range: 0.0 ~ 128.0
skipHiddenTileEntityRenderingSize = 3.0
```
Changing this to `128.0` did boost my fps quite a bit while around create blocks 
Didnt observe any negative impact of it yet

**Comment by NillerMedDild** [comment]
I don't think the `skipHiddenTileEntityRenderingBlacklist` config actually does anything, did you experience the same OP?

**Comment by RealGrep** [comment]
I just tested it. I edited config/entity_culling-client.toml and changed that entry to this:

`skipHiddenTileEntityRenderingBlacklist = ['travel_anchors:travel_anchor']`

And now I can see all my travel anchors through the hempcrete floors, and I can look at them while holding the travel staff, turn them from white to orange by looking at them, and teleport right there. So yep, seems to fix it for me.

**Comment by MFWalter** [comment]
To be 100% honest. I can see the travel anchors through walls, which mostly defeats their purpose, so I asked in Discord and apparently the issue is known by the Discord community, but had not been reported. So I came here to report it. In the original post I posted the solution Discord gave me, but as I had not actually tested it I edited the post to remove said solution.

**Comment by NillerMedDild** [comment]
I can only see the name through walls, not the block itself. Is that the same for you?

**Comment by MFWalter** [comment]
Depends on the block. Through the glass I can see names. 
![image](https://user-images.githubusercontent.com/56056783/128641506-ed927846-c5e8-48f4-bcc9-20d1cc63698a.png)
Through the logs and grass blocks I can see neither.
![image](https://user-images.githubusercontent.com/56056783/128641519-c7549343-ad37-43ae-980e-3585c4e4ec2c.png)
The Travel staff will still take me to the travel anchor without seeing either though.

**Comment by NillerMedDild** [comment]
Alright, I'll mark this is fixed then, working for me, I guess 😄
