### ISSUE TITLE
No output recipes for molten redstone

### ISSUE THREAD

**Issue by sssssss340** [NillerMedDild/Enigmatica6#2914]
**Modpack version**
0.5.9

**Describe the bug**
Molten redstone from Tinkers Construct has no output crafting recipes. This results in the smeltery being able to melt down redstone and redstone blocks, but not pour them into a casting basin or other non-tank items. If possible, please add recipes for casting redstone blocks in basins.

**Logs**
N/A

**Screenshots**

![Melting](https://user-images.githubusercontent.com/8406195/128610012-33c69a40-8963-4a20-954e-106bd47aaa45.png)

![No Casting](https://user-images.githubusercontent.com/8406195/128610014-18a66dc0-7cb0-4523-b18d-f459436b329f.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that added.
