### ISSUE TITLE
Vanilla Nether Quartz and Gold Ore can still spawn

### ISSUE THREAD

**Issue by Golfavel** [NillerMedDild/Enigmatica6#2918]
**Modpack version**
0.5.9
**Describe the bug**
Vanilla Nether Quartz ore and Nether Gold ore are still able to spawn despite the overrides established by Enigmatica; but seems to only be within in Basalt Deltas.
**Screenshots**
![nqo](https://user-images.githubusercontent.com/32048635/128615299-ba29d37a-fa1d-468b-94c0-8504214d2e72.png)
![ngo](https://user-images.githubusercontent.com/32048635/128615302-d807ab76-2bb3-41b8-a4cc-43852e9789af.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
@Ridanisaurus got a bug for you I'm afraid :(

**Comment by NillerMedDild** [comment]
I fixed it for Enigmatica, but the bug may still be in EE

**Comment by Ridanisaurus** [comment]
That's due to these ores being part of a the Basalt Deltas feature, and not the standard ore feature. (Thanks Mojang, you the best)
Thanks for the report, I will look into it.
