### ISSUE TITLE
[Mod Suggestion] RF Tools Base, Builder and Utility 

### ISSUE THREAD

**Issue by Dyllan2000alfa** [NillerMedDild/Enigmatica6#292]
RF Tools base and the separate mods for everything recently had a release version for 1.16 posted. I didn't add all the RF Tools mods because of content overlap, but the three above I think would add a lot to the current pack. Specifically RF Tools Builder since the builder could be used to make a quarry something I feel enigmatica 6 is really lacking.

RF Tools Base: https://www.curseforge.com/minecraft/mc-mods/rftools-base
RF Tools Builder: https://www.curseforge.com/minecraft/mc-mods/rftools-builder
RF Tools Utility: https://www.curseforge.com/minecraft/mc-mods/rftools-utility

Thanks for making such a good pack

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, it will be added once we upgrade to 1.16.3 :) 

you're very welcome, thank you :D
