### ISSUE TITLE
no Lightning Audio

### ISSUE THREAD

**Issue by Scarlightgirl** [NillerMedDild/Enigmatica6#2920]
**Modpack version**
5.6
**Describe the bug**
In any instance whether the weather is thunder or a mod is spawning lightning no audio occurs when the lightning strikes. No errors appear when playing the game, and this bug is present in both single player and multiplayer.
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by theboo** [comment]
Lightning sound is turned off by default in bad wither no cookie reloaded config... Un sure if this is intended or not, but you can turn it back on in bwncr-common.toml

**Comment by NillerMedDild** [comment]
Not intended, I didn't realise that was a thing:P
