### ISSUE TITLE
Enviromental Controller from RFTools crashing server

### ISSUE THREAD

**Issue by Dolvur** [NillerMedDild/Enigmatica6#2923]
Version 0.5.6

When using a module like the regen module or the night vision module and using all types the server crashes and starts restarting. Upon rejoining the server crashes again and you have to roll back the world.

**Comment by Darkere** [comment]
Crashlogs please.

**Comment by taillow40** [comment]
We had the same problem, occurring immediately after placing the flight module into the controller. Corrupted the server and needed to load a backup.

[crash-2021-08-05_06.23.51-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6951479/crash-2021-08-05_06.23.51-server.txt)

**Comment by Darkere** [comment]
This bug has been fixed already. Please update.
