### ISSUE TITLE
Hellshelf and Endshelf recipes missing in JEI

### ISSUE THREAD

**Issue by Chris5302** [NillerMedDild/Enigmatica6#2928]
**0.5.9**

**Describe the bug**
When attempting to look up the basic end shelf bookcase recipe it doesnt exist according to my JEI, It is however still craftable you just have to figure out what the recipe is by moving the ingredients around the crafting table till it shows up.

*Note* it was showing up in 0.5.6 even with the additional mods i have added. 
Extra added mods:
CalemiUtils V1.1.3
Cyclic V1.3.5
JAMD V1.1.9 Beta
Minecolonies V0.14.311 Beta
MysticalAgradditions V 4.2.0
MysticalAgriculture V4.2.1
Structurize V 0.13.202 Alpha
Torcherino V 14.0.0+

**Screenshots**
![2021-08-08_23 05 53](https://user-images.githubusercontent.com/88632873/128653823-4eff5cfb-7f70-4d04-b4db-4a1123d0bb1e.png)
![2021-08-08_23 08 47](https://user-images.githubusercontent.com/88632873/128653926-54da486b-6ad3-40e3-bdb2-fb81df815933.png)
![2021-08-08_23 08 58](https://user-images.githubusercontent.com/88632873/128653929-f43d556f-1beb-42e9-85ff-8e6dc8977cd2.png)

**Comment by MuteTiefling** [comment]
Out of curiosity, are the sea and hell shelves craftable? I suspect my expert recipes are causing an issue here

**Comment by NillerMedDild** [comment]
I believe I have this fixed, it's a bit hard to test though. The issue should only occur in some cases when joining a server from a client that has not connected to a SP world or server in the same session.

**Comment by Chris5302** [comment]
Okay cool, ill test it tonight when i get home. Im assuming i need to update in order to have the fix? Sorry im at work lol

Sent from my IPhone
________________________________

**Comment by NillerMedDild** [comment]
I'm afraid the update won't be available until in a few days :/

**Comment by Chris5302** [comment]
Ok no problem, i figured that would be the case but doesn’t hurt to ask

Sent from my IPhone
________________________________

**Comment by NillerMedDild** [comment]
I..hope this works. Haven't been able to find time to test it.

**Comment by NillerMedDild** [comment]
It doesn't work when the client is in expert mode and server is in normal mode, I know that much ^^'
