### ISSUE TITLE
kicked for flying when spawning above an ocean

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#2929]
**Modpack version**

0.5.9

**Describe the bug**

if you spawn above an ocean, the mod that is responsible for keeping you in statis can kick you for flying.

(possibly a result of #2589 , afb3cc3fdb795d48e6dfb8a82d6edf95024dc2db & 901fa942bc5469355fc789b3a540505b0fe9145b which is keeping the player floating for longer than vanilla anti-fly allows)

suggested fix: just allow flying in server.properties by default, i ended up setting that to true on several e6 playthroughs. 🙂 

**Logs**
```
[minecraft/PlayerList]: Quezler[/{$my-ipv4}:52476] logged in with entity id 379 at (1152.5, 59.0, 1152.5)
[minecraft/DedicatedServer]: Seed: [4300897813941175010]
```

**Screenshots**

taken after the server kicked me for flying the second time, client in the process of being kicked: (showing the ocean)
![Untitled](https://user-images.githubusercontent.com/3179271/128695721-41529c91-3ea1-4d0b-84de-8b19c4c2ceb3.png)

mere seconds later:
![Screen Shot 2021-08-09 at 12 50 02](https://user-images.githubusercontent.com/3179271/128695729-89b38c20-8233-449e-859a-7f062a5cba6d.png)

**Comment by NillerMedDild** [comment]
We cannot add a default server.properties file, it makes the server starter fail :/
