### ISSUE TITLE
Industrial Foregoing potion brewer crash

### ISSUE THREAD

**Issue by porkchop713** [NillerMedDild/Enigmatica6#293]
**Modpack version**
0.2.17

**Issue**
Trying to shift click potions from the output slots of the IF potion brewer crashes client to desktop and continues to crash every time world is loaded. I reproduced this after restoring from backup with the same result.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5259076/latest.log)
[crash-2020-09-21_23.39.27-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/5259080/crash-2020-09-21_23.39.27-server.txt)

**Comment by NillerMedDild** [comment]
Thanks for the report, it has been reported a while ago, hopefully it'll be fixed soon :)
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/827
