### ISSUE TITLE
Quantum Entangleporter doesnt work well with Refined Storage controller [Increased Controller Buffer Size]

### ISSUE THREAD

**Issue by TzarTz** [NillerMedDild/Enigmatica6#2931]
**Modpack version**
0.5.9

**Describe the bug**
Quantum entangleporters don't seem to agree with Refined Storage controllers. When i have one connected to my controller to provide power, the controller doesn't fill up all the way but the entangleporter still continues to feed it power which in turn voids my power supply no matter how much I am producing.

the controller works perfectly fine when a cable is connected directly to it but as soon as the entagleporter is connected, then it stops working correctly.

from what i could tell this happens when i have a dimension card in my wireless transmitter.

i have not tested this with other wireless power transmitters. 

**Screenshots**
With the entangleporter:
![2021-08-09_15 08 34](https://user-images.githubusercontent.com/86915860/128720578-25c6726c-58f3-4007-a3be-b56cbbb55d51.png)

Directly with cable:
![2021-08-09_15 09 13](https://user-images.githubusercontent.com/86915860/128720618-e955434e-d6dc-468e-ae27-bac3c37336f6.png)

**Comment by Darkere** [comment]
Did you check how much power the dimension card costs?. 

The entangloporter only outputs every few ticks, while the controller consumes every tick. This causes the controller to temporarily run out of power when you go above a certain threshhold. 

The only real fix is to go into the RS config and increase the Controllers buffer size.

**Comment by RobuxShooters** [comment]
I wonder if the sequence of events of providing energy will influence the UI.
If the sequence is `entangloporter provides energy -> controller uses energy` in one tick, then I'm thinking the bar will always seem half full, since the controller uses the energy after it has been provided, then the process repeats next tick.
If the sequence is `controller uses energy -> cables provide energy` in one tick, then it would probably always look full, since the energy bar is filled after the controller uses energy.

**Comment by TzarTz** [comment]
the problem isnt the controller running out of power, its that when using the porter to power it, my power gets voided.
as soon as i switched to cable my power reserve instantly started increasing again.

you can see in the screenshot how much power is required by the whole system (the system is small so most of it is from the dimension card)

i am fairly certain i can keep up with the demand since i have 2 ethylene gas burners being supplied by a max upgraded PRC each.

**Comment by NillerMedDild** [comment]
How much energy/t do you produce?

**Comment by TzarTz** [comment]
im not really sure. i currently have 3 ethylene burners going and from what the UI says, i would say around 18kfe/t

**Comment by theboo** [comment]
In e6 it takes multiple PRCs to fuel one GBG... Ethylene production is nerfed considerably... Saying u have 3 GBGs running is not saying much tbh

**Comment by TzarTz** [comment]
i am aware of this. i just told u how much energy they produce. is that not useful enough?

**Comment by NillerMedDild** [comment]
Could you perhaps try using an Energy Cell of some sort as buffer, and see how that fluctuates with and without the additional cable at the Entangloporter?

**Comment by TzarTz** [comment]
i have my network connected directly with my power cables and i am not having issues anymore

**Comment by NillerMedDild** [comment]
Alright then - I have increased the buffer size of the Controller to hopefully prevent this from happening in the future.
