### ISSUE TITLE
Infinitely duplicating diamonds

### ISSUE THREAD

**Issue by Lostone666** [NillerMedDild/Enigmatica6#2932]
I doubt this was intended, but with a combo of mods, you can duplicate diamonds.  You can use the crusher demons from Occultism (higher tier ones) to crush diamonds into dust resulting in 2+ dust piles per diamond.  Then you put the dust into the enrichment chamber from Mekanism to turn it into a diamond.  Rinse and repeat for more.

Again, I don't know if this is an actual issue or not.  Definitely not a big one at least.  Just thought I'd mention it

**Comment by NillerMedDild** [comment]
Should be fixed in 0.5.9 :)

**Comment by MuteTiefling** [comment]
This should be fixed already. Can you please update?
