### ISSUE TITLE
Advanced Machine Frame not obtainable

### ISSUE THREAD

**Issue by WorldTeacher** [NillerMedDild/Enigmatica6#2935]
**Modpack version**
v0.5.9
**Describe the bug**
The Advanced Machine Frame is not obtainable using the Dissolution Chamber
**Screenshots**
![bug](https://user-images.githubusercontent.com/41587052/128755122-152306a7-3d0d-4512-b312-d00ffcd7f1de.PNG)

I restarted the Server and tired in a Single-player World, but the Machine frame will not be crafted.

**Comment by NillerMedDild** [comment]
The recipe requires a Diamond Gear, not Gold.
