### ISSUE TITLE
Occultism Quest with hidden dependency

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#2936]
**Modpack version**

0.5.9

**Describe the bug**

cannot complete the occultism crusher quest since the advancement(s) that unlock it appear to have fallen into the void.

**Screenshots**

trying to give root & summon miner both say i have already unlocked it:
![Screen Shot 2021-08-10 at 11 58 33](https://user-images.githubusercontent.com/3179271/128847751-972c5abc-2677-4504-aef9-da082389362f.png)

yet this quest does not complete:
![Screen Shot 2021-08-10 at 12 01 07](https://user-images.githubusercontent.com/3179271/128847932-17986847-8a0a-4f2a-81e0-29d3a93de173.png)

there also doesn't appear to be an advancement tab for occultism:
![2021-08-10_11 59 11](https://user-images.githubusercontent.com/3179271/128847806-3813b252-2ee2-4f5a-85a3-5e8c00a63cfb.png)

symptoms are similar to https://github.com/klikli-dev/occultism/issues/111, yet the only fix that suggest is random over time 🤔

**Comment by theboo** [comment]
The advancements are hidden, klikli added them just for pack devs and quest triggers, you will not find them in the advancement menu, nor will you get a message saying you completed an advancement... You can find the advancements in the /advancement command tree, should be one for each summon-able spirit

As for why your quest isn't completing when you summon the spirit, idk I would have to test myself. I'm at work for the next 12hr but I'll look at it when I get home.

**Comment by Quezler** [comment]
> The advancements are hidden, klikli added them just for pack devs and quest triggers, you will not find them in the advancement menu, nor will you get a message saying you completed an advancement...

good to know 👍

**Comment by NillerMedDild** [comment]
There's a hidden dependency on the `Golden Sacrificial Bowl`, I'm guessing that's the issue. I'm making that dependency less hidden :)
![billede](https://user-images.githubusercontent.com/21295394/129257231-8a4c084e-7bfc-42e5-9626-0eca57a8b7ba.png)
