### ISSUE TITLE
Pressing "E" in quests crashes game

### ISSUE THREAD

**Issue by Fury-Caramels** [NillerMedDild/Enigmatica6#2937]
**Modpack version**
0.5.9 W10 jre1.8.0_291
**Describe the bug**
When you press "E" with opened quests game crashes. happened 2 times in Thermal Expansion part of quests. Game saves and nothing is lost,

Added mods
Optifine
Optiforge
MixinBootstrap
WorldEdit
WorldEditCUI Forge Edition 3
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
[2021-08-10-2.log](https://github.com/NillerMedDild/Enigmatica6/files/6960731/2021-08-10-2.log)
[crash-2021-08-10_12.07.51-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6960736/crash-2021-08-10_12.07.51-client.txt)
[crash-2021-08-10_12.53.32-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6960737/crash-2021-08-10_12.53.32-client.txt)

**Screenshots**
![Crash-Freeze](https://user-images.githubusercontent.com/16158147/128847746-4ded7e07-8103-4a24-977e-18e5946e71f9.jpg)
![Launcher](https://user-images.githubusercontent.com/16158147/128847857-7af06883-9d7b-416c-a855-b77cfdf84bf8.jpg)

**Comment by Buuz135** [comment]
It's a WorldEdit CUI issue, not in the pack. Remove it to fix it or report it to the appropiate repo.
