### ISSUE TITLE
Astral Sorcery Crystals compatibility with Tetra

### ISSUE THREAD

**Issue by Neffrex** [NillerMedDild/Enigmatica6#2938]
**Modpack version**
0.5.9
**Describe the bug**
When trying to use celestial or rock crystals as material for Tetra, for the tools that need more than 1 crystal, is impossible to use it as a material as crystals can't be stacked.

**Screenshots**
![image](https://user-images.githubusercontent.com/52071446/128909496-e8406077-24cb-43c0-9b9a-cd2b3a3bffae.png)
Celestial Crystal working as a valid material in a hoe

![image](https://user-images.githubusercontent.com/52071446/128909193-5390964b-f3bb-46bc-bbc3-35be5383d1f4.png)
Celestial Crystal not working as a material in an axe as it needs 2 pieces

**Comment by NillerMedDild** [comment]
Hmm, I'll try to find a solution. Thanks for the report!

**Comment by NillerMedDild** [comment]
I don't see a way to fix this tbh, sorry :/
