### ISSUE TITLE
[Mod Suggestion]: Prefab

### ISSUE THREAD

**Issue by Venom1987** [NillerMedDild/Enigmatica6#294]
Not sure what to write here other then that i kinda like that mod. Making your own Village made easy with that mod i guess.

Curseforge Link: https://www.curseforge.com/minecraft/mc-mods/prefab?page=4

**Comment by NillerMedDild** [comment]
I'll have a look, thanks for the suggestion.

**Comment by NillerMedDild** [comment]
I like it, will add it but disable the starter item :)
