### ISSUE TITLE
Tetra Quest partial stall

### ISSUE THREAD

**Issue by Aelphais** [NillerMedDild/Enigmatica6#2940]
**Modpack version**
0.5.9

**Describe the bug**
Tetra Quest: "The Forge" requires you to pick up the actual Forge Hammer block. You cannot pick it up without crafting a few tiers of hammers that require the block. I'm pretty sure the required hammer is Tier 6 with Silk Touch, but haven't double checked that just yet.

Unless you craft the Forge Hammer, you'll end up crafting a Tier 6 hammer before being able to progress the quest and claim rewards for the following quests: "The Forge", "Thermal Cells", "Tier 5", and "Tier 6". Considering the quest text encourages you to go exploring rather than craft it, this is a mild problem.

Tying quest progression into the Tetra advancement "Restored Machinery" should fix it both for crafting and for exploring.

**Comment by NillerMedDild** [comment]
Thanks for the report and fix :)
