### ISSUE TITLE
JEI Recipes Missing

### ISSUE THREAD

**Issue by MFWalter** [NillerMedDild/Enigmatica6#2945]
**Modpack version**
0.5.9

**Describe the bug**
We are finding some JEI recipes no longer work. The Volcanic Accumulator from Ars was the first item I found that when I click in JEI no longer gives a recipe. I also found 2 items in Botania that no longer give recipes when using JEI. The items were still craftable and I could find the recipes in the Ars guide book and the Botania guide book. I know I have clicked these recipes in previous versions of the modpack. If I get a chance I will try to go back through my VoD and see if I can find the two Botania recipes that no longer work.

**Logs**
N/A

**Screenshots**
The segment where I discovered the issue with the Volcanic Accumulator is too long to clip so here is a link to the VoD at the spot where I first discover the issue. I go on to check the book and craft it despite JEI showing no recipe.
https://www.twitch.tv/videos/1114457017?t=00h28m16s

**Comment by NillerMedDild** [comment]
This should be fixed in 0.5.10, thanks for the report :)
