### ISSUE TITLE
Quantum tank voids liquids from (Mekanism?) pipes

### ISSUE THREAD

**Issue by Altreus** [NillerMedDild/Enigmatica6#295]
**Modpack version**
0.2.17

**Issue**
Connected a small tank of honey via Mekanism fluid pipes to a quantum tank and all the fluid disappeared.

Filling the quantum tank by hand with a bucket works as expected.

Other fluid delivery methods (AE, for example) were not tested, but I'm sure someone will do so and add more info to the bug.

At some point I'll be able test more thoroughly with varied setups to see if it's consistently Mekanism pipes.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by kman3107** [comment]
I've tested this and it works just fine for me. I've been filling a Quantum Tank with Ethylene for a while now.
For this test I used Honey just to make sure it wasn't something specific like that.
I'd like to remind you that there is something funky with the Quantum Tank's GUI update.
So you might have to force a block update, maybe pick up and put down the tank.
Even if the Quantum Tank GUI doesn't show anything you can always see the amount of liquid by holding SHIFT when looking at the Quantum Tank.

Of course, non of this matters if things are the same 7 days later (i.e now).

**Comment by NillerMedDild** [comment]
>  Connected a small tank of honey via Mekanism fluid pipes to a quantum tank and all the fluid disappeared.

Which small tank did you use? :)

**Comment by ChromeMystic** [comment]
I had a similar issue with a Mekanism Tank and Industrial Foregoing essence - Didn't really check it as I was testing something different. Will try If I remember when i get on my server later today.
