### ISSUE TITLE
Can't craft Manyullyn in an Induction Smelter

### ISSUE THREAD

**Issue by NobodyShinyHunter** [NillerMedDild/Enigmatica6#2950]
**Modpack version**
Enigmatica 6 0.5.9

**Describe the bug**
The manyullyn recipe in the Induction Smelter asks for Tinker's Construct's Cobalt witch can't be obtained in the modpack. However it works just fine in the other machines such as the Arc Furnace.

**Screenshots**
![Capture d’écran (1)](https://user-images.githubusercontent.com/88782166/129036288-980bde75-57d9-4f0a-a9f9-99b4a43b5e43.png)
![Capture d’écran (2)](https://user-images.githubusercontent.com/88782166/129036293-187f3c13-7eb2-45b6-90df-42c1d7ce6cae.png)
![Capture d’écran (3)](https://user-images.githubusercontent.com/88782166/129036294-a4d5f0b9-0564-4895-99ba-320bb39c9c90.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
