### ISSUE TITLE
Pollinated bees cause flower supporting blocks to be converted

### ISSUE THREAD

**Issue by ShyNieke** [NillerMedDild/Enigmatica6#2952]
**Modpack version**
0.5.9
**Describe the bug**
Ghast bees (and possibly other bees) convert the block under the flower for the bee breaking the flower and making the bee stop functioning

Example for the ghast bee
Ghast bee uses crimson fungi to pollinate
crimson fungi are placed on warped or crimson nylium
when ghast bee is pollinated it converst any netherack block to tnt
nylium blocks are now seen as netherack blocks
nylium gets converted to tnt
tnt does not support the fungi
fungi breaks
bee has no flower

**Logs**
No log for this one

**Screenshots**
![2021-08-11_17 59 54](https://user-images.githubusercontent.com/7694658/129063287-a8e711dd-3242-41fc-8ff6-8c33272bf046.png)
workstation is infront of the beehive to prevent the ghast bees of coming out of the hive

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed somehow - can you name any other bees with the same issue?
@TemperedFool do you have any ideas for a fix for this? Perhaps have the TNT conversion be vanilla Netherrack only?

**Comment by TemperedFool** [comment]
It's already calling out netherrack specifically, but I'll look into it. Will likely just change which block it needs to mutate to something unlikely to be in the apiary.

**Comment by ShyNieke** [comment]
> Thanks for the report, we'll get that fixed somehow - can you name any other bees with the same issue?
> @TemperedFool do you have any ideas for a fix for this? Perhaps have the TNT conversion be vanilla Netherrack only?

I will definitely keep an eye out on this, so far I have only had the issue with the ghast bee

**Comment by TemperedFool** [comment]
Was actually calling out the netherrack tag (whoops), but changed it over to Sand to be safe within the bee.

**Comment by ShyNieke** [comment]
> Was actually calling out the netherrack tag (whoops), but changed it over to Sand to be safe within the bee.

May I suggest soul sand instead of regular send, that way it is still thematic to the nether?

**Comment by ShyNieke** [comment]
I totally get that, although it would add a slightly more puzzle element to the bee-keeping, like how you can't have certain bees together as bee X may convert bee Y to bee Z, I must say I love the little puzzle aspect of figuring out which bees will play together ;)

**Comment by NillerMedDild** [comment]
We'll get that fixed as well, thanks :) Unsure what to change their block to though. Maybe only ordinary netherrack.
