### ISSUE TITLE
Game Crash with Eidolon and Ars Nouveau Interaction

### ISSUE THREAD

**Issue by sesgoe** [NillerMedDild/Enigmatica6#2953]
**Modpack version**
0.5.6

**Describe the bug**
If you activate an Eidolon Brazier for the ritual for obtaining soul shards near an Ars Nouveau Mana Jar, the game will crash.

**Logs**
[2021-08-11-1.log](https://github.com/NillerMedDild/Enigmatica6/files/6969978/2021-08-11-1.log)

**Comment by NillerMedDild** [comment]
Would you mind updating to 0.5.9 and see if the issue persists? :)

**Comment by sesgoe** [comment]
Crash confirmed does **not** happen on `0.5.9`. Will close!
