### ISSUE TITLE
Legendary Create Loot Boxes don't seem to give any reward.

### ISSUE THREAD

**Issue by Aelphais** [NillerMedDild/Enigmatica6#2955]
**Modpack version**
0.5.9

**Describe the bug**
Completed both the Furnace Engine and Brass Funnel quest. I was mostly sure that the Furnace Engine loot box didn't give me anything, so I double checked by emptying my inventory for the Brass Funnel quest and definitely didn't receive anything. These are the only two I've tried so far, so not sure if the issue extends to any other Legendary Create loot boxes or loot boxes from other mod questlines.

**Comment by MuteTiefling** [comment]
Hrm. I wonder if some items in the pool no longer exist. Script is probably erroring on them.
