### ISSUE TITLE
Recipe clash between tofu(simple farming) and soy sauce (sushi go crafting)

### ISSUE THREAD

**Issue by Jack3552** [NillerMedDild/Enigmatica6#2958]
0.5.9

It seems smelting soy beans defaults to the simple farming recipe (tofu) and not the SGC one (soy sauce). Soy sauce seems to be a pretty essential ingredient for making the high tier foods in SGC.

![image](https://user-images.githubusercontent.com/29699182/129099206-4fdc02a3-fba3-427b-8e86-ac60030e93d9.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm thinking we can turn the Soy Bean -> Tofu recipe into a Press or Crush type of recipe.

**Comment by theboo** [comment]
Soy sauce will be made in a fermentation barrel next update with the new fesh mod update

**Comment by MuteTiefling** [comment]
Even with buuz's update, pressing makes more sense for tofu than roasting anyway.

Create press recipe maybe?

**Comment by NillerMedDild** [comment]
Sounds good to me, unless Buuz updates before us :P

**Comment by theboo** [comment]
Buuz updated a couple days ago xD but yeh I like the mechanical press recipe, but might need to find a couple other recipes from other mods as well, seems silly to lock this to create

**Comment by MuteTiefling** [comment]
Ie metal press, thermal press, etc.
