### ISSUE TITLE
Aurora Crystal Uses JEI + Crusher Spirit Tab = Crash

### ISSUE THREAD

**Issue by ReducedRose** [NillerMedDild/Enigmatica6#2959]
As stated, looking at the uses of Better End's Aurora Crystal block in JEI, and going into Occultism's Crusher Spirit's tab leads to a game crash.

Crash log attatched.

[crash-2021-08-11_16.41.37-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6971375/crash-2021-08-11_16.41.37-client.txt)

**Comment by NillerMedDild** [comment]
This might be fixed in 0.5.10, would you mind verifying when it's released? :) I hope to have it out tomorrow evening, in around 24 hours.
