### ISSUE TITLE
Crash when attempting to rename an item in a Robit that's not docked.

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#296]
**Modpack version**
0.2.17

**Issue**
Crash when attempting to rename an item in a Robit that's not docked.

I use Robit's all the time as anvils, but they're typically docked when doing so. The last two times I've tried renaming something, I had the Robit in follow mode and it resulted in a crash.

**Logs**
[crash-2020-09-22_11.04.52-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/5262381/crash-2020-09-22_11.04.52-client.txt)

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it.
