### ISSUE TITLE
Thermal quest text review

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#2960]
**Modpack version**
0.5.9

**Describe the bug**
Arboreal extractor quest still references acacia for resin and gives acacia saplings. Should probably point at a new tree type instead as acacia does latex now.

**Comment by NillerMedDild** [comment]
It seems good to me tbh, it doesn't reference Acacia for Resin

**Comment by MuteTiefling** [comment]
Ah, cool. Someone had mentioned it in discord and couldn't post to Github immediately.
