### ISSUE TITLE
[RFTools: Dimensions] Block Absorber Not Working On Emendatus Enigmatica Blocks

### ISSUE THREAD

**Issue by DizzyDJW** [NillerMedDild/Enigmatica6#2962]
**Modpack version**
0.5.9

**Describe the bug**
No matter how many times I place one down or on what block, the block absorber only absorbs air, and it does so in an instant.

**Comment by NillerMedDild** [comment]
I relayed the issue, thanks for the report :)

**Comment by DizzyDJW** [comment]
So far, unable to be reproduced outside the modpack

**Comment by NillerMedDild** [comment]
Dammit :P Which metals did you try with?

**Comment by NillerMedDild** [comment]
Roger, I'll try to figure out how I misconfigured it 👍

**Comment by DizzyDJW** [comment]
Any fix for this yet?

**Comment by NillerMedDild** [comment]
It's fixed :D
