### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by lunulu** [NillerMedDild/Enigmatica6#2965]
**Modpack version**
0.5.9

**Describe the bug**
Everything was fine yesterday, but after restarting the server, my friend cannot log into the server.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6974184/latest.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/65171793/129170880-ba98f5f2-35a2-4a57-a212-89d855900a96.png)

**Comment by Darkere** [comment]
Something is blocking the world files from being read. (some backup software maybe?)

This has potentially corrupted stuff and you might need to load a backup. Would try without first though.
