### ISSUE TITLE
Cika Crafting Tables not subbing for Oak Crafting Tables

### ISSUE THREAD

**Issue by HokieStone** [NillerMedDild/Enigmatica6#2967]
I started on Enigmatica 6 - Build 0.5.9 today.  My seed set my spawn in a slime island in the Cika Mountains.  I started with Tetra and my wooden hammer would not transform a cika crafting table into the workbench.  I moved on to Astral Sorcery, found a large temple and cleared the ceiling.  Again the starlight did not affect the Cika Crafting Bench.  However once I set creative mode, and pulled in Oak Crafting tables both worked as intended.  I'm not certain if you intended the pack to use all crafting tables, or just "vanilla" oak ones.

Thank you

**Describe the bug**

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by NillerMedDild** [comment]
That's a rough start :/ Any Crafting Table can be converted to the standard Oak Crafting Table.
I've requested compatibility from Tetra for transforming other workbenches, but no luck yet.
I'll see what I can do about Astral and Workbenches from other mods.

**Comment by HokieStone** [comment]
Thanks for the quick reply.  I tried very hard to look for other alternatives before I reported.  I apparently did not however look to see if I could convert *insert wood type* here to a normal one.  Thanks!

**Comment by NillerMedDild** [comment]
Not much we can do about the AS / Tetra issues I'm afraid :/
