### ISSUE TITLE
Datapack failure

### ISSUE THREAD

**Issue by Sunconure11** [NillerMedDild/Enigmatica6#2969]
**Modpack version**
0.5.9

**Describe the bug**
Server refuses to boot up due to a bug with the datapack

**Logs**
https://pastebin.com/Nq4975Ey

**Screenshots**
N/A

**Comment by Sunconure11** [comment]
Yeah so I'm trying to get support, but so far, no one has aided me. The issue appears to be a conflict between Bayou Blues and Abundance in the datapack.

**Comment by NillerMedDild** [comment]
I recommend that you remove the mod(s) you added :)

**Comment by Sunconure11** [comment]
The closest to adding another mod I did was adding Mohist.

**Comment by NillerMedDild** [comment]
Enigmatica does not have Bayou Blues or Abundance.

**Comment by NillerMedDild** [comment]
Ah I see the error you mean now. Would you mind supplying your full latest.log?
Also, a reinstall might do the trick.

**Comment by Sunconure11** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6984793/latest.log)

**Comment by NillerMedDild** [comment]
For the sake of traceability, we've continued the debugging on Discord.
