### ISSUE TITLE
AE will not allow removal of IE Revolver or Revolver Speedloader

### ISSUE THREAD

**Issue by corhean** [NillerMedDild/Enigmatica6#297]
When placing  a revolver or revolver speedloader (immsersiveengineering:resolver; immsersiveengineering:speedloader) into an AE system, the items cannot be removed.

Additional items with identical NBT can be added and AE will stack them, it will also create separate stacks for unique NBT, but specifically those two items cannot be removed.  Other sampled IE items can be stored and retrieved without issue.  Occurred in both .14 and .17

**Comment by NillerMedDild** [comment]
Thanks for the report. This has been happening since 1.12.2, no idea why tbh.
