### ISSUE TITLE
BotanyPots crops being destroyed upon completion, and not growing with bonemeal

### ISSUE THREAD

**Issue by Jack3552** [NillerMedDild/Enigmatica6#2970]
**0.5.9**

**Describe the bug**
When crops inside a hopper botany pot reach the end of their growth timer, there's a crunch noise like the crop is being harvested, but it disappears. Using bonemeal consumes the bonemeal but has no apparent effect. I setup the simplest system I could think of (see below) to test it and the same thing still happens. If this is user error I apologise (it is my first time using the mod), but I can't find any information online to suggest I'm doing anything wrong.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6981887/latest.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/29699182/129347320-480c9604-6ac9-4e5b-b9b7-d58c7423e439.png)

**Comment by Jack3552** [comment]
The items are now appearing in the chests, and I'm not sure why now and not before, but I'm going to close the issue so as not to waste anyone's time.

**Comment by MuteTiefling** [comment]
The first growth cycle after a restart always seems to be lost.
