### ISSUE TITLE
Cardbox duplicates Tetra crystals

### ISSUE THREAD

**Issue by reyahao** [NillerMedDild/Enigmatica6#2973]
**Modpack version**
0.5.9

**Describe the bug**
Apparently when wraping a chest that contains tetra's rock crystals in it in a cardbox, crystals literally fall out from the chest. Then, when you unpack the chest, crystals are still in it, but those that fell out previously are still in-game too.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by reyahao** [comment]
Chest, by the way if this is important, was golden.

**Comment by MuteTiefling** [comment]
Duplicate of #1847
