### ISSUE TITLE
Ars Nouveau knockback projectiles cause server crash

### ISSUE THREAD

**Issue by circee** [NillerMedDild/Enigmatica6#2977]
E6 0.5.9

The spellbook "Knocked out of orbit" can sometimes cause a server crash. 

One user reported this crash after using the spellbook and running into another player, the other user encountering this crash reported using the spellbook and then interacting with a boat. I have not been able to personally replicate the crash through any means.

![book](https://i.imgur.com/J04W3BX.png)

Full crash reports:
https://pastebin.com/EtNuzTsD
https://pastebin.com/pQeKSghL

**Comment by NillerMedDild** [comment]
Fixed in-dev of Ars, will be fixed in 0.5.10 :)
https://github.com/baileyholl/Ars-Nouveau/issues/326
