### ISSUE TITLE
Waystones generating in open void in End

### ISSUE THREAD

**Issue by corhean** [NillerMedDild/Enigmatica6#298]
pretty self explanatory - waystones generating at y=1 /0  in the middle of the Void in the end.  

![image](https://user-images.githubusercontent.com/70460842/93938979-186b5e00-fcf8-11ea-873f-a0e9cbb767fc.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, known issue :)
https://github.com/blay09/Waystones/issues/280

**Comment by corhean** [comment]
bueno, thanks.  I searched for waystones and didn't immediately find it ;)

**Comment by blay09** [comment]
Unable to reproduce this on 1.16.5, waystones are only spawning on the endstone platforms for me.

**Comment by NillerMedDild** [comment]
Good enough for me, this issue is ancient anyhow.
