### ISSUE TITLE
Industrial Foregoing Fluid Sieving Machine crash

### ISSUE THREAD

**Issue by GaborPalinkas** [NillerMedDild/Enigmatica6#2980]
**Modpack version**
0.5.9.
**Describe the bug**
I was browsing JEI, pressed U while the mouse was over fermented ore meat (redstone), and then clicked on the Fluid Sieving Machine and the game crashed.
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
https://pastebin.com/7BuNCx9N
**Screenshots**
![crash](https://user-images.githubusercontent.com/57747490/129427528-b320609d-aedf-4047-a31f-27f8eb79cc73.png)

**Comment by NillerMedDild** [comment]
Duplicate of countless others, please use the search function before reporting :)
