### ISSUE TITLE
Several compostable items

### ISSUE THREAD

**Issue by sauphle** [NillerMedDild/Enigmatica6#2981]
**Description**
### A couple of Items I would like to be compostable:
-Bamboo (apotheosis)
-rice seeds (sushi go crafting)
-rice (sushi go crafting)
-cucumber seeds (sushi go crafting)
-cucumber (sushi go crafting)
-wasabi root (sushi go crafting)
-wasabi seeds (sushi go crafting)
-soy seeds (sushi go crafting)
-soy bean (sushi go crafting)
-sesame seeds (sushi go crafting)
-sesame seed (sushi go crafting)

**Why would you like this added/changed?**
This would improve immersion and encourage players not to throw out seeds they don't want at the moment. 
I also noticed that bamboo is compostable in vanilla but it is not in this modpack. I assume it's because of the insane amounts of bamboo you can create but I will stand by my decision to make them compostable. I don't expect it to happen but, it would be nice if you could compost them

**Screenshots if applicable.**

![compostables](https://user-images.githubusercontent.com/80305735/129428881-1aebc6d5-5fc8-476b-aa7c-9862a1f5766b.png)

**Comment by MuteTiefling** [comment]
Thanks for the reminder telemenar :D
