### ISSUE TITLE
`ether gas` temprature rebalancing for pneumaticraft

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#2984]
**Description**

`Ether Gas` is the best liquid coolant for powah reactors by far (-96), however `Liquid Starlight` only is -9. 

for the pneumaticraft mod however its considered to be at room temperature, whilst starlight is waaaay colder there.

i would suggest an entry to be added [here](https://github.com/NillerMedDild/Enigmatica6/blob/develop/kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/block_heat_properties.js), possibly as the coldest liquid? (or at the very least a bit colder than liquid starlight)

(not sure enough about the heat capacity & thermal resistance numbers myself to make it a pull, so its a suggestion)

**Why would you like this added/changed?**

seems a bit silly they switch the rank of coldest based on the mod. (and i would like to use this as pnc coolant :3)

**Screenshots if applicable.**

![Screen Shot 2021-08-14 at 12 11 38](https://user-images.githubusercontent.com/3179271/129442706-de0c484c-2186-4416-b4a6-f00b0b052851.png)
![Screen Shot 2021-08-14 at 12 11 49](https://user-images.githubusercontent.com/3179271/129442707-023a8f2c-b75c-40a5-a439-8f6cc9d2fd3d.png)
![Screen Shot 2021-08-14 at 12 12 07](https://user-images.githubusercontent.com/3179271/129442709-ddfaf7cc-297c-4219-81b5-c436c9286e6d.png)

**Comment by MuteTiefling** [comment]
Block heat properties only handles blocks, to my knowledge. Not fluids.

For fluids, pneumaticcraft pulls directly from the native fluid heat value, so whatever is set by the mod author.

It might be possible to change this, but I'm not sure the effort is with it : liquid cooling in PNC is kinda bad.

Just take a look at.... I think liquid hydrogen. It's as cold as it gets, but still considerably worse than simply cooling a block with a vortex tube.

**Comment by Quezler** [comment]
> liquid cooling in PNC is kinda bad.

i know, that is why i abuse heat syncs since the other colder fluids are more annoying to get in bulk:

![2021-08-14_12 50 13](https://user-images.githubusercontent.com/3179271/129444003-808dcb74-e85e-4160-b233-b94aaaa4fc94.png)

> For fluids, pneumaticcraft pulls directly from the native fluid heat value, so whatever is set by the mod author.

still feels a bit weird that powah is [configured](https://github.com/NillerMedDild/Enigmatica6/blob/0809287f4fa22f3344892c5c38fab4d0779b90ae/config/powah/general_common.toml#L32) it to be way colder than liquid starlight, feels like it should at least match 🤔

**Comment by MuteTiefling** [comment]
Yeah. When I set up the Powah one, I wanted it to be a little silly. It was one of the few nobs I had to turn for rebalancing Powah reactors.

I know starlight has been 'traditionally' the coldest liquid in modded, but I don't see why it should have to remain that way.

I guess you can look at it as Ether gas bring very efficient at moving heat, but only in a confined space like a reactor or thermal generator. Like the stuff we used to use in refrigerators.

**Comment by Quezler** [comment]
> For fluids, pneumaticcraft pulls directly from the native fluid heat value, so whatever is set by the mod author.

@Buuz135 what is your take on the confined temperature in powah vs in world coldness? (aka: how special is ether gas?)

**Comment by NillerMedDild** [comment]
@MuteTiefling you updated this very recently, right?

**Comment by MuteTiefling** [comment]
Yep. I think I put it in expert only though

**Comment by NillerMedDild** [comment]
Ah alright, wouldn't it be fine in base too?

**Comment by MuteTiefling** [comment]
Ah, nope, it's in base already :D
