### ISSUE TITLE
Change the order of the mycelial generator quests

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#2985]
**Description**

While building the mycelial generators one by one i noticed that at first the left column followed the same order as by searching "mycelial" in JEI, but it very quickly starts jumping all over the place, ideally the order should be the same.

**Why would you like this added/changed?**

Because it would just be cleaner if the orders matched up, i already did the hard work of mapping the orders:

| JEI | Quest | Mycelial |
|-----|-------|----------|
|  01 |   01  | furnace |
|  02 |   02  | slimey |
|  03 |   03  | culinairy |
|  04 |   04  | potion |
|  05 |   05  | disenchantment |
|  06 |   08  | ender |
|  07 |   06  | explosive |
|  08 |   10  | frosty |
|  09 |   11  | halitosis |
|  10 |   13  | magma |
|  11 |   12  | pink |
|  12 |   14  | netherstar |
|  13 |   08  | death |
|  14 |   15  | rocket |
|  15 |   16  | crimed |
|  16 |   09  | meatalurgic |

Now all someone has to do is swap their positions and claim all the glory 🏆 (and perhaps change the weird v shape)

**Screenshots if applicable.**
![Screen Shot 2021-08-14 at 12 48 21](https://user-images.githubusercontent.com/3179271/129444956-3223a6f9-9c71-4659-aae7-98185c8d8133.png)

**Comment by MuteTiefling** [comment]
V shape is because the whole thing is an infinity drill :D

**Comment by NillerMedDild** [comment]
To be honest I don't really see why the quest order should be the same as the order in JEI, that's not logical to me.
It wouldn't hurt either, but :P

**Comment by Quezler** [comment]
well if you look them up in jei and do them one by one it would be weird to see the completed quests jump around, i don't mind randomness but this pattern is just akward 😅

**Comment by NillerMedDild** [comment]
To be frank I think implementing this would be a waste of time.

**Comment by Quezler** [comment]
and if i were to do that part myself as well and make a pull, would you click the green button to merge?

**Comment by NillerMedDild** [comment]
Yeah sure :)

**Comment by Quezler** [comment]
> To be frank I think implementing this would be a waste of time.

you were right btw, thought it was just a matter of dragging them to the exact coordinates, turns out i needed to edit each x/y coordinate through right clicking, luckily it used 0.5 increments, but it is done now 😆

**Comment by theboo** [comment]
Middle click is drag and drop xD

**Comment by NillerMedDild** [comment]
We do not close issues until the fix is released :)

**Comment by Quezler** [comment]
~~i thought it reopened automatically because of the linked merge~~
