### ISSUE TITLE
Blackstone from Cobblegens

### ISSUE THREAD

**Issue by Thiana** [NillerMedDild/Enigmatica6#2989]
**Modpack version**

develop/head

**Describe the bug**

At the moment the only way to generate minecraft blackstone is via entities (pigman trading and bee block mutation). For completeness and server friendliness it would be nice if it could be generated via pedestals or some other non-entity method. Thanks!

**Comment by MuteTiefling** [comment]
This was a bit of an intentional exclusion due to tetra being gated behind the nether by way of blackstone.

Might be worth reconsidering though.

**Comment by Thiana** [comment]
Make the catalyst something that comes from the nether? ie, the quark blaze block, glowstone, etc

**Comment by NillerMedDild** [comment]
I think we can add it as basalt style generation :)

**Comment by NillerMedDild** [comment]
I could not add it as basalt style generation ._. It's vanilla style cobblegen now, but only if you already have the block, and only with the vanilla-style cobblegen. I hope that works for you
