### ISSUE TITLE
Blocks placed by Building Gadgets "Building Gadget" are often translucent, but solid as expected

### ISSUE THREAD

**Issue by Chaise91** [NillerMedDild/Enigmatica6#2990]
**Modpack version**
0.5.6

**Describe the bug**
On a server, when using the "Building Gadget" tool from the Building Gadgets mod, some blocks will "place" but remain translucent until:
a) players logs out then back in
or b) player "hits" the block (or even right-clicking when the block is "selected")

As mentioned, the block is solid, and the tooltip shows the correct information, it is simply translucent. I have not tested this on a SP world. I have also discovered vanilla MC blocks seem to function fine.

**Screenshots**
![2021-08-14_16 49 26](https://user-images.githubusercontent.com/11702717/129460953-49c800f7-bed8-4734-9893-5361dc3b1abb.png)

**Comment by theboo** [comment]
this should hopefully be fixed in the 0.5.9 and later versions of the pack, please update

**Comment by Chaise91** [comment]
> this should hopefully be fixed in the 0.5.9 and later versions of the pack, please update

Was there another report of this issue? I checked the issue history but wasn't able to fine another report.

**Comment by theboo** [comment]
i believe #2862 is the same underlying issue, simibubi has a good description to what is going on(will happen with quark blocks and construction wand too)

**Comment by Chaise91** [comment]
> i believe #2862 is the same underlying issue, simibubi has a good description to what is going on(will happen with quark blocks and construction wand too)

Could be related - I will update later tonight and report back.

**Comment by Chaise91** [comment]
Confirmed this is fixed in v0.5.9 of the modpack. :)

**Comment by eliebele** [comment]
This happens again in v0.5.11
Tested with building and exchanging gadget with chisel blocks on a server.
Blocks appear translucent until I click them, change dimension or log off.
Vanilla blocks seem to work as intended.
