### ISSUE TITLE
Refined Storage Requester not working

### ISSUE THREAD

**Issue by jkelley2** [NillerMedDild/Enigmatica6#2991]
0.5.9

**Describe the bug**
Refined Storage Requester saying missing ingredients and not keeping items stocked even when the system can craft the items if requested manually

**Screenshots**
![javaw_0PaMB7dpF5](https://user-images.githubusercontent.com/2477585/129461989-b85eeabb-780c-444e-99e2-7e02cc980cb9.png)
![javaw_cUFcCVEphm](https://user-images.githubusercontent.com/2477585/129461990-a4713dc4-b7e8-4c46-b6f3-b9707bbd0407.png)
![javaw_fuSGbpF2ZO](https://user-images.githubusercontent.com/2477585/129461991-77fb3d70-b15d-4544-b8c1-cfa195daf0d1.png)

**Comment by NillerMedDild** [comment]
Would you mind updating manually and see if that resolves the issue?

**Comment by jkelley2** [comment]
ok manually updating from the bundled version of RSRequestify 2.1.1 to 2.1.3 fixed the issue
