### ISSUE TITLE
I can't get Phantoms to spawn.

### ISSUE THREAD

**Issue by Zickzii** [NillerMedDild/Enigmatica6#2992]
Version 0.5.9

Phantoms aren't spawning. Haven't slept in like 10 days. I'm standing out in darkness with no blocks above me. Gamerule: doInsomnia = true. Difficulty: Hard. Playing in Singleplayer.

**Comment by theboo** [comment]
do you happen to have a pillow of secrets trinket or a sleep charm on you?

**Comment by Zickzii** [comment]
No armor equipped. Nothing in my curios slots. No pillow of secrets trinket. If I /summon phantoms they're not aggro, they just fly around and ignore me.

**Comment by Thiana** [comment]
Are you using something that makes you invisible?

**Comment by Zickzii** [comment]
I did wear a thief's hood a while ago but I've taken it on and off and worn other helmets too.

**Comment by Zickzii** [comment]
I just noticed there's a "Time since last rest" statistic. I also noticed it doesn't seem to change with "/time add".. Let me just AFK for an hour or two..

**Comment by Zickzii** [comment]
Well, phantoms are spawning now. No idea how I messed up so much. Very sorry for the false alarm.
