### ISSUE TITLE
Atum world keeps crashing

### ISSUE THREAD

**Issue by tye425** [NillerMedDild/Enigmatica6#2994]
**Modpack version**
0.5.9
**Describe the bug**
Every time I build and enter the atum portal. It crashes about 10 seconds after arriving in the portal
**Logs**
https://pastebin.com/yjEz9yy9

**Screenshots**
Local server output: https://i.imgur.com/iOdpgpf.png

I have tried deleting the dimension and restarting the server. Doesn't work unfortunately.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by tye425** [comment]
Just an update - I deleted the dim again, started another server, built another portal on the new server and created another atum dim. I copied that dim to my main world and it works fine now.

**Comment by NillerMedDild** [comment]
Glad to hear it, cause I cannot reproduce this at all :P
