### ISSUE TITLE
Thermal Unpacking Die has no recipe

### ISSUE THREAD

**Issue by MrGrimmReaper28** [NillerMedDild/Enigmatica6#2995]
0.5.10 version - Thermal die sets are required to unpack magma blocks. Die set has no recipe and is not oreDictionary'd for IE press molds.

![image](https://user-images.githubusercontent.com/70997523/129469510-b3ea8318-c09c-4c69-8102-cc7f5f5ce7f4.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
