### ISSUE TITLE
Quest description for Thermal Resin includes Acacia

### ISSUE THREAD

**Issue by MrGrimmReaper28** [NillerMedDild/Enigmatica6#2996]
0.5.10 - Acacia gives latex, not resin and the quest requires update. 

![image](https://user-images.githubusercontent.com/70997523/129469560-b234463d-bce7-4c64-831a-cb69c0cd898f.png)
![image](https://user-images.githubusercontent.com/70997523/129469567-db34ac97-f90e-4275-add0-2127cdb4eddc.png)

**Comment by NillerMedDild** [comment]
Oh that's the quest I was supposed to update 😅
