### ISSUE TITLE
Recipe for silicon is broken

### ISSUE THREAD

**Issue by BornaKelemenic** [NillerMedDild/Enigmatica6#2997]
**Modpack version**
0.5.10

**Describe the bug**
Can not craft with silicon anymore. For example, when trying to craft Raw Basic Processor the recipe does not accept the silicon that is produced when smelting nether quartz.

**Screenshots**
Here is a screenshot when trying to craft with this version of the silicon.
![Vnb28gxEya](https://user-images.githubusercontent.com/34454621/129470769-5f724f06-c2be-4cf8-837c-07a060e0f74c.png)

Also, there is only one crafting recipe with this silicon.
![22wIWdpTz1](https://user-images.githubusercontent.com/34454621/129470817-84d43826-7988-42fa-b655-ba0a22b8bb06.png)

Here is the silicon that Raw Basic Processor accepts (and all other recipes that use silicon)
![tkP3TGZSjQ](https://user-images.githubusercontent.com/34454621/129470922-02453fb6-cbab-48e0-9043-6c51ab69757d.png)

Here is the quartz getting smelted.
![WVBHdm1ZZB](https://user-images.githubusercontent.com/34454621/129471015-b3997cc7-0899-4bdd-8557-3096e8929d10.gif)

**Comment by NillerMedDild** [comment]
Huh, so it is. I wonder what happened to it O_o

**Comment by bouncingjohn** [comment]
I believe the problem is in kubejs - I've rolled back to kubejs-forge-1605.3.14-build.67 and Silicon is working again.

**Comment by NillerMedDild** [comment]
Thanks for that 👍 agreed
