### ISSUE TITLE
Elemental Craft (new mod suggestion)

### ISSUE THREAD

**Issue by vegon** [NillerMedDild/Enigmatica6#3]
https://www.curseforge.com/minecraft/mc-mods/elemental-craft
https://www.reddit.com/r/feedthebeast/comments/hr361a/presentation_of_elemental_craft/

New mod. So new that the first version is directly for 1.16.1. Looks like ThaumCraft lite and the "shrines" are a really cool idea.

**Comment by NillerMedDild** [comment]
We're keeping our eyes on it as it develops, thanks for the suggestion :)

**Comment by Dasavanth** [comment]
i would love to see the mod added, has a lot of neat automation features and a unique take on ore processing
