### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gzcwnk** [NillerMedDild/Enigmatica6#30]
**Modpack version**
Input modpack version here

how to determine this?
ERP-v1.5R ?

**Issue**
Input short description of the issue here

Placing crafting table as a sheep passes through the square and crafting table disappears, not in inventory.  Restarted game and crafting table in inventory, minecraft bug not mod bug?

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Yeah that's a Minecraft bug :) or not so much a bug as a thing that happens due to timing.
