### ISSUE TITLE
Higher Turtle Spawn Chance

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#3000]
**Description**
I suspect turtles are excessively rare due to biome changes, making them nearly impossible to find. We should probably make the Nature's Aura summon a little easier to accommodate. From memory, it requires a scute... Could maybe use the aquaculture turtle items instead.

**Comment by NillerMedDild** [comment]
We can also beef up their spawns in beach and warm ocean biomes?

**Comment by MuteTiefling** [comment]
Sure! I have no idea how that works, honestly. But more natural spawns would be great

**Comment by NillerMedDild** [comment]
I think it's like this in a startup script:
```js
onEvent('worldgen.add', (event) => {
    event.addSpawn((spawn) => {
        spawn.category = 'water_creature';
        spawn.entity = 'minecraft:turtle';
        spawn.weight = 20;
        spawn.minCount = 1;
        spawn.maxCount = 3;
        spawn.biomes.blacklist = false;
        spawn.biomes.values = ['#beach'];
    });
});

```
