### ISSUE TITLE
Rftools fluid absorber considers non source blocks to be source blocks when absorbing fluid

### ISSUE THREAD

**Issue by Decemberhawk** [NillerMedDild/Enigmatica6#3001]
**Modpack version**
0.5.9
**Describe the bug**
When using the Rftools fluid absorber to absorb fluids in order to make specific dimlets it will absorb non source blocks and treat them as though they were source blocks while attempting to absorb the 256 source blocks it needs to become usable in making a fluid dimlet
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by NillerMedDild** [comment]
Thanks for the report - Which fluids did you try with?

**Comment by Decemberhawk** [comment]
I first discovered it with liquid sodium in order to make a sodium dimlet then I found that it also worked with liquid ethylene, and water.

**Comment by NillerMedDild** [comment]
Cool, thanks!

**Comment by NillerMedDild** [comment]
Oh, could you perhaps try again on version 0.5.10, if it's not too much trouble?

**Comment by Decemberhawk** [comment]
sure let me update to a new profile and relaunch real quick

**Comment by Decemberhawk** [comment]
yes it still seems to consider non source blocks to be source blocks in 0.5.10

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/McJtyMods/RFToolsDimensions/issues/373
Also reproduced in-dev
