### ISSUE TITLE
Hose Pulley will consider mekanism fluids infinite

### ISSUE THREAD

**Issue by Decemberhawk** [NillerMedDild/Enigmatica6#3002]
**Modpack version**
0.5.9
**Describe the bug**
The hose pulley from create will consider fluids from mekanism to be infinite despite them supposedly being blacklisted.
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it here: https://github.com/Creators-of-Create/Create/issues/2117
