### ISSUE TITLE
Tetra tools have wrong mining levels

### ISSUE THREAD

**Issue by Fabizocker456** [NillerMedDild/Enigmatica6#3003]
**Modpack version**
0.5.10
**Describe the bug**
Tetra tools can't mine stuff they're supposed to
a) Tetra hammers can't be used for forged blocks
(Full-iron double-sided hammer with string binding and silk touch)
b) Iron pick head can't mine diamond ore, lead ore etc.
(Also I have an obsession with tetra :) )

**Comment by NillerMedDild** [comment]
I believe you need two Iron Pick Heads to be able to mind Diamond - It works for me in-dev at least.
What are you trying to do with the Hammer exactly?

**Comment by Fabizocker456** [comment]
I was trying to mine forged walls with a double-sided iron hammer with silk touch.

**Comment by NillerMedDild** [comment]
Hmm, it seems like only Netherite Hammers and up can mine Forged Walls. Was it usually Iron and up?

**Comment by Larandar** [comment]
Hammers, by design, need to be netherite with silk touch to mine forged walls

**Comment by Fabizocker456** [comment]
So Mischief of Mice showed wrong information...

**Comment by NillerMedDild** [comment]
I think Tetra has been updated quite a bit since that showcase.
