### ISSUE TITLE
Create .3.2

### ISSUE THREAD

**Issue by Fabizocker456** [NillerMedDild/Enigmatica6#3004]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/create
**Mod description**
The update added the precision mechanism, brass bells, diving gear and more

**Why would you like the mod added?**
This update will break many automation setups, as integrated circuits were removed, but I feel like if this pack showcases the "latest and greatest" mods, it can't forget create.

**Screenshots if applicable.**

**Comment by theboo** [comment]
this is already in the pack...
