### ISSUE TITLE
Unsmeltable Smeltables

### ISSUE THREAD

**Issue by tali713** [NillerMedDild/Enigmatica6#3005]
**Modpack version:**
Enigmatica6 0.5.9

**Bug Description:**
Apatite is listed as smeltable in tinkers smeltery, however it's melt temperature exceeds the temperature of blazing blood/blazing honey.  Apatite has a melt temperature of 1660, however blazing blood is at 1500.  For such a commonplace material, it's weird for it to be harder to melt than diamond.

**Comment by NillerMedDild** [comment]
That melting point is correct though 😅

**Comment by NillerMedDild** [comment]
Fixed in-dev, thanks for letting us know!
