### ISSUE TITLE
Dimension Builder redstone control does not persist

### ISSUE THREAD

**Issue by coolbot100s** [NillerMedDild/Enigmatica6#3008]
**Modpack version**
0.5.9 (modded)
**Describe the bug**
RFToolsDimensions Dimension Builder Redstone control button not working.
when clicked it will cycle between on/off etc. however the selection doesn't actually persist, as soon as the inventory is closed it reverts back to "redstone ignored."

Tested with and without dimension cards, full power, no power, and as many other variables as I can come up with.
**Screenshots**
![javaw_fcPHXalCt3](https://user-images.githubusercontent.com/76798835/129492809-5c5cc4ca-36bd-4960-b93b-eaf7504b3a9d.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, I was able to easily reproduce it, so I relayed it here: https://github.com/McJtyMods/RFToolsDimensions/issues/374
