### ISSUE TITLE
Item status on right side of screen wont disappear when item is no longer in inventory

### ISSUE THREAD

**Issue by Crozzner** [NillerMedDild/Enigmatica6#3009]
Version 0.5.6

The status of an item (Diamond Backpack) from Sophisticated Backpacks that isn't equipped is showing on the right side of the screen. I noticed this shortly after I upgraded the Diamond Backpack to the Netherite Backpack.  Maybe I accidentally clicked a hotkey but I've tried every key combo and browsed the entire control config in an attempt to get rid of it.  Additionally, I can't find the mod that is associated with this display.  Please see the circled item in the screenshot below. 

![Game Error](https://user-images.githubusercontent.com/88989288/129494086-8598f837-06df-4c96-a766-d8c6dae164c4.jpg)

**Comment by NillerMedDild** [comment]
That comes from a quest you have pinned :)

**Comment by Crozzner** [comment]
I feel like such a fool but thank you so much for the quick response.
