### ISSUE TITLE
Ultimine not respecting config?

### ISSUE THREAD

**Issue by lost-RD** [NillerMedDild/Enigmatica6#3013]
**Modpack version**
0.5.9

**Describe the bug**
Ultimine is being capped at 64 blocks despite the config saying 128.

I'm using a stone axe on an ebony tree and the overlay in the top left says shapeless, 64 blocks, and only 64 blocks are being cut as per the overlay.

I've tried increasing the config further above 128 but that does nothing.

I'm unsure if this is a bug or a feature but my research hasn't shown any features that would cause this.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Fixed in-dev :)

**Comment by lost-RD** [comment]
For anyone else, to apply the fix to your current world, see info here: https://github.com/FTBTeam/FTB-Ultimine/issues/90
Essentially you must change the config in you world's serverconfig folder.

**Comment by NillerMedDild** [comment]
No need to do that, update 0.5.11 will sort it for you.

**Comment by Mortal195** [comment]
It happens to me that installing ftb ultimine correctly I try to change the type of mining with the mouse wheel and it doesn't work and neither does it work with the arrow keys on the keyboard and it doesn't let me use it either, I leave the key pressed and it says not active and that's how the whole thing looks. time they told me that they don't allow tlauncher I think and I changed and it won't let me either, please help me.

**Comment by MuteTiefling** [comment]
@Mortal195 We don't support cracked launchers either. Please buy the game and see if the issue persists.
