### ISSUE TITLE
Linux server start wrapper doesn't connect STDIN properly

### ISSUE THREAD

**Issue by draeath** [NillerMedDild/Enigmatica6#3015]
**Modpack version**
0.5.9

**Describe the bug**
On an ARM64 Linux system with Amazon Corretto JDK 8 (none of that matters AFAIK, providing just in case) the [startup wrapper](https://github.com/BloodyMods/ServerStarter) doesn't seem to connect STDIN, making server setup / management impossible. Note that the server starts up and runs as expected, but command input such as 'list' or 'stop' doesn't do anything and you must CTRL-C to bail out. Occasionally I notice some additional output after seeing my prompt, suggesting that something is playing around with I/O streams.

To work around this, one has to inspect `cat /proc/####/cmdline | tr '\000' ' '` output (where #### is the started game java process) and start the server manually with the same arguments.

I'm reporting this here as I don't see any issues (open or closed) on the upstream repo, so either nobody else seems to be running into it, or they weren't able to figure out upstream for that. I'm also not sure if this is specific to this pack. Best to check with you first?

**Logs**
N/A

**Screenshots**
N/A

**Comment by draeath** [comment]
Strange. I can't replicate this anymore.

**Comment by NillerMedDild** [comment]
Yay, easy fix I guess :P
