### ISSUE TITLE
Project Red

### ISSUE THREAD

**Issue by musialny** [NillerMedDild/Enigmatica6#3017]
**CurseForge Links:**
- https://www.curseforge.com/minecraft/mc-mods/project-red-core
- _Modules:_
  - https://www.curseforge.com/minecraft/mc-mods/project-red-illumination
  - https://www.curseforge.com/minecraft/mc-mods/project-red-integration
  - https://www.curseforge.com/minecraft/mc-mods/project-red-transmission
> _Exploration is probably useless_
- _Dependencies:_
  - https://www.curseforge.com/minecraft/mc-mods/scorge
  - https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8
  - https://www.curseforge.com/minecraft/mc-mods/cb-multipart

**Mod description:**
A collection of Minecraft Forge mods that aim to bring vastly improved Redstone circuitry through wiring, logic gates, integrated circuits, and more. 

**Why would you like the mod added?**
Mod can be really helpful while building complex redstone structures, especially when you have to focus on performance issues and available space.

**Comment by NillerMedDild** [comment]
I don't think we have a need for any of it's features tbh, maybe Transmission a bit. But.. too many libs for that one thing. No thank you :)
