### ISSUE TITLE
Change Ghast Bee Block Mutation

### ISSUE THREAD

**Issue by MFWalter** [NillerMedDild/Enigmatica6#3019]
**Description**
Please either change the block mutation for the ghast bee or change the flower for the ghast bee.

**Why would you like this added/changed?**
Currently the Ghast Bee can block mutate Crimson Nylium into TNT blocks. The only flower they will pollinate from is the Crimson Fungus. The Crimson fungus can only be planted on Crimson Nylium. As such, the ghast bee will the block its flower is on into TNT then the flower will unplant itself and the ghast bee will no longer be able to collect pollen.

**Screenshots if applicable.**
N/A

**Comment by NillerMedDild** [comment]
Please update, this has already been fixed :)

**Comment by MFWalter** [comment]
Please update? We are on 0.5.9. That is the latest update.

![image](https://user-images.githubusercontent.com/56056783/129796237-33d8cabc-dd90-471d-83d9-4547f38fe1e0.png)
![image](https://user-images.githubusercontent.com/56056783/129796261-28c0c7e2-f30f-4bdc-8fb9-2b907ed99a23.png)
![image](https://user-images.githubusercontent.com/56056783/129796286-1bf9dd6b-3588-476a-9a65-e5c2a44bff9d.png)

**Comment by NillerMedDild** [comment]
0.5.10 is the last update.

**Comment by MFWalter** [comment]
OH! My apologies. When I looked at CurseForge the "Main File" is still 0.5.9. I didn't see 0.5.10. Thanks for all the great work and putting up with us when we pester you because of our own mistakes.

**Comment by NillerMedDild** [comment]
You're very welcome, and no worries :)
