### ISSUE TITLE
Productive Bees ruins everything

### ISSUE THREAD

**Issue by JaisDK** [NillerMedDild/Enigmatica6#302]
**Modpack version**
0.2.17

**Issue**
I might have exaggerated the title a little ;), but there's a problem in the current version of PB in the pack with client recipes being reloaded with an empty recipe manager. This affects other mods like IE. I've uploaded a fixed version https://www.curseforge.com/minecraft/mc-mods/productivebees/files/3065350

**Logs**
related issues:
https://github.com/JDKDigital/productive-bees/issues/86
https://github.com/BluSunrize/ImmersiveEngineering/issues/4325

**Comment by kman3107** [comment]
I've tried the new Productive Bees 0.3.5.1 and it's working fine for me now.
I tried it in the Enigmatica 0.2.17 pack and also in an instance with only jei, ie and productive bees.
2 different clients, 2 different servers. Still no crashes.

Finally I can rest..

**Comment by JaisDK** [comment]
Thank you for the testing :)

**Comment by NillerMedDild** [comment]
Thanks for letting us know :)

**Comment by JaisDK** [comment]
0.3.5.2 fixes another problem where recipes are reloaded for every single config bee instead of once for all the bees cause /reload to hang and use a lot of resources.

**Comment by NillerMedDild** [comment]
oh that issue was from you :P glad it's fixed, that slowed down development time so much.
