### ISSUE TITLE
Summon Greedy Familiar quest is broken

### ISSUE THREAD

**Issue by Meegooo** [NillerMedDild/Enigmatica6#3020]
**Modpack version**
0.5.9

**Describe the bug**
"Summon Greedy Familiar" quest is not completing after summoning the familiar.

Looking at `/advancement grant` commands, advancement `occultism:familiar_greedy` is not there, while being required by the quest.

**Comment by Quezler** [comment]
> ill fix this when we can edit quests again

editing quests is broken?

**Comment by NillerMedDild** [comment]
For some, sometimes, yeah

**Comment by Meegooo** [comment]
> editing quests is broken?

When I tried to edit this quest the game crashed for me.

**Comment by MuteTiefling** [comment]
This appears to be working fine now in dev. Presumably corrected by occultism.

**Comment by Ieldra2** [comment]
The same problem appears with the Drikwing familiar quest.

**Comment by MuteTiefling** [comment]
That also appears fixed in Dev, likely at the same time they fixed the rest of the advancements
