### ISSUE TITLE
TiCon Melting/Tank Upgrade/Ability Not Stacking Fluid Capacity Correctly

### ISSUE THREAD

**Issue by MaxFirestorm** [NillerMedDild/Enigmatica6#3021]
**Modpack version**
0.5.10

**Describe the bug**
While making a TiCon sword, I added the Melting ability to it, giving it 1296mb fluid capacity for the weapon to melt fluid into. When adding a Seared Tank, this should add another 1296mb to the capacity. When doing so, however, the fluid capacity only goes up to 2448mb instead of the 2592mb that math says I should get.

**Logs**
N/A

**Screenshots**

![2021-08-17 18_59_16-Window](https://user-images.githubusercontent.com/11296552/129777346-9ef01428-4e53-4451-92f8-ea3b9f693300.jpg)
![2021-08-17 19_01_11-Window](https://user-images.githubusercontent.com/11296552/129777350-9a48b469-5ac9-4d7b-9263-513cce782933.jpg)
![2021-08-17 19_00_57-Window](https://user-images.githubusercontent.com/11296552/129777351-1702c3da-3d91-4bf4-9722-69ba8c27485c.jpg)
![2021-08-17 18_59_25-Window](https://user-images.githubusercontent.com/11296552/129777352-2cb8eec7-2b38-4cc2-95e5-7bac9a1f2971.jpg)

[At time of report, I'm currently livestreaming at http://twitch.tv/MaxFirestorm if you want/need to see anything happening live]

**Comment by NillerMedDild** [comment]
Thanks for the report, nice and detailed 👍 I relayed it here: https://github.com/SlimeKnights/TinkersConstruct/issues/4605

**Comment by NillerMedDild** [comment]
Would you mind testing it in an instance with only Mantle and Tinkers Construct? :x

**Comment by MaxFirestorm** [comment]
Can do once my stream is over in around 15 minutes or so!

**Comment by NillerMedDild** [comment]
Thank you very much :)

**Comment by NillerMedDild** [comment]
DarkAngel22579 tested it for us, you're off the hook :D

**Comment by MaxFirestorm** [comment]
*Just* as I'd finished xD No worries! Thanks for letting me know x3
