### ISSUE TITLE
Fire hurts when put out

### ISSUE THREAD

**Issue by xATL4S** [NillerMedDild/Enigmatica6#3023]
Description
Whenever you try to put out a fire it hurts you by putting you on fire - have tried with fists and a variety of tools.

Either some equipment - please leave a comment if there is an existing work around - that will stop you from being put on fire from this.
Or to just disable this.

**Comment by NillerMedDild** [comment]
I believe you need to use a Water Bottle:

https://www.curseforge.com/minecraft/mc-mods/better-burning

I think I'll disable the feature that makes the player burn when punching normal fire though.
