### ISSUE TITLE
ComputerCraft Modem recipe conflict

### ISSUE THREAD

**Issue by xBlizzDevious** [NillerMedDild/Enigmatica6#3024]
### Modpack Version

0.5.9

### Describe your issue

I have just built myself a Mekanism Fission reactor and wanted to monitor and control it from a computer. Went to make a modem so I can connect several items together and the recipe comes up with `Futura (Uber wavy)` from Chisel. It's redstone dust surrounded by stone.

### Have you modified the modpack?

Yes

### User Modifications

Nothing relevant to this issue - just removed XP costs for Waystones and tweaked FTBUltimine.

### Did the issue happen in singleplayer or on a server?

Server

### 

- [X] Confirm you have checked the wiki and issue tracker for your issue

**Comment by NillerMedDild** [comment]
Duplicate of #2910, I thought it was fixed in 0.5.9 though. I'll double check later.

**Comment by xBlizzDevious** [comment]
> Duplicate of #2910, I thought it was fixed in 0.5.9 though. I'll double check later.

That would explain why it didn't show up when I searched. Default search is for open topics. 

Tested it in Refined Storage pattern and crafting grids. Tested in a Tinkers' crafting table, a spruce table and an oak table. All come up with the same Chisel recipe.

**Comment by NillerMedDild** [comment]
Alright, I'll get that fixed 👍 ty!

**Comment by NillerMedDild** [comment]
Ah it was fixed in 0.5.10, please update :)
