### ISSUE TITLE
Server crashes on startup, unable to run server.

### ISSUE THREAD

**Issue by Pactastic** [NillerMedDild/Enigmatica6#3025]
### Modpack Version

0.5.9

### Describe your issue

On first run server fails to load correctly. error says Sophisticated Backpacks and Silmple Farming failed to load correctly. Restarting ends in the same result.

### Crash Report

[crash-2021-08-17_18.38.13-fml.txt](https://github.com/NillerMedDild/Enigmatica6/files/7003405/crash-2021-08-17_18.38.13-fml.txt)

### Latest Log

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7003414/latest.log)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### 

- [X] Confirm you have checked the wiki and issue tracker for your issue

**Comment by NillerMedDild** [comment]
Thanks for the report, please try to reinstall, as this issue normally does not occur :)
