### ISSUE TITLE
Issues with Terraforged Worlds

### ISSUE THREAD

**Issue by Ieldra2** [NillerMedDild/Enigmatica6#3028]
### Modpack Version

0.5.10

### Describe your issue

There are various issues with the Terraforged world type:
(1) Villages in worlds with the Terraforged world type are inevitably boring and simplistic compared to villages in default worlds, and rarely, if ever, contain houses from mods. I never get the almost city-like settlements I see in default worlds.
(2) With the Terraforged world type, the Nether contains only vanilla biomes (I tried this three times to the same effect), compared to a great variety of modded biomes if you use the default world type.
(3) The quest description on where to find Tetra's precursor forges does not apply to worlds with the Terraforged world type.
(4) Some vanilla biomes are very hard to find in Terraforged world types. It appears that in every world you generate, there is at least one vanilla general type (counting variants like "Edge" as one) you will not find within a distance of 10 blocks (using Nature's compass).
(5) I have had one instance where a biome had the size of one block. 

 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### 

- [X] Confirm you have checked the wiki and issue tracker for your issue

**Comment by MuteTiefling** [comment]
1) can't say I've encountered this. I've certainly come across many sprawling villages with terraforged. Pretty sure the only thing terraforged even does for villages is help with the terrain under them to avoid holes 

2) this has nothing to do with terraforged. It was our decision to disable the byg biomes in the nether.

3) it certainly should, as this has nothing to do with terraforged. The biome types are set by the mod adding the biome and tetra simply keys in on those types. Will need investigation however. 

4) between the very large biome size we've set and the number of biomes added by different mods, this is inevitable. Thankfully, you're not limited to a 10k x 10k world.

If you'd like to reduce biome size in your terraforged setup, however, you certainly can without much issue.

It's possible too that some biomes are weighted too heavily and show up more frequently than they should. 

5) this happens in vanilla too. Not much to do about it. Just depends on how the biomes end up generating and overlapping.

**Comment by RobuxShooters** [comment]
I've noticed that Savanna-type biomes and Cherry Blossom-type biomes appear way too frequently. Granted, I have only made about 4 worlds in Terraforged so far, but in every single world Savanna biomes seem to span a very wide area and you have to travel long distances to find any other biome type and variety.

I think that the weightage of Savanna biomes should be dropped somewhat to provide more diversity as opposed to wide areas of yellow-green grass. Even wide areas of lush green grass might be better.

**Comment by MuteTiefling** [comment]
Savanna and cherry blossom groves might be suffering a bit from multiple similar biomes that all have similar features. Like baobab extending savanna.

Still, yeah. They might be a little too common

**Comment by NillerMedDild** [comment]
I agree with Cherry Blossom groves being way too common, I'll have a look at the weights for update 0.5.12 :)
