### ISSUE TITLE
Tick Accelerator Block

### ISSUE THREAD

**Issue by yavuzselim313** [NillerMedDild/Enigmatica6#3029]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/tick-accelerator-block

**Mod description**
The Tick Accelerators need Redstone to be activated.
The Tick Accelerators only accelerate the Blocks above and below.
The Features of the Tick Accelerator Blocks:
Tier 1 Tick Accelerator Block: Makes the Block 4x times fast.
Tier 2 Tick Accelerator Block: Makes the Block 8x times fast.
Tier 3 Tick Accelerator Block: Makes the Block 12x times fast.

Tier 4 Tick Accelerator Block: Makes the Block 16x times fast.

**Why would you like the mod added?**
It adds Tick Accelerator Blocks and has better performance than rats.

**Screenshots if applicable.**
![grafik](https://user-images.githubusercontent.com/79061657/129925272-b9f3d2f0-b703-4990-8cb3-7ef549ede495.png)

**Comment by NillerMedDild** [comment]
No thank you, has the potential to be both very OP and very buggy.
