### ISSUE TITLE
Farmland Added to Valid Apiary

### ISSUE THREAD

**Issue by MFWalter** [NillerMedDild/Enigmatica6#3032]
**Description**
Please add Farmland from Aquaculture 2 to the valid apiary blocks.

**Why would you like this added/changed?**
We need to plant crops like corn and wasabi for some of the bees to use as a flower. The farmland made using the aquaculture hoe is automatically hydrated and remains hydrated so it is a great hoe/block to use to plant single random crops on

**Screenshots if applicable.**
N/A

**Comment by TemperedFool** [comment]
I'd actually like to refrain from doing this; the next version of RBees removes the floor as part of the multiblock, which means these won't need to be tagged to work.

**Comment by MFWalter** [comment]
That's a pretty nice reason. My first instinct is that the removal of floors will solve the problem, but I know at least one person on my server stacks their apiaries vertically on top of each other. The floor of the second apiary is the ceiling of the first apiary.

**Comment by MuteTiefling** [comment]
You can always include the farmland as a block within the bounds of the apiary structure.

**Comment by TemperedFool** [comment]
Hrm. That seems like a pretty good reason to want it tagged anyway - I hadn't thought of going vertical! The other reason I'm a touch hesitant to do so is that most solid blocks are automatically being tagged by the aforementioned new version of RBees, including the various farmland bocks. This appears to be properly tagging it - I stuck a dirt block in the roof of an apiary in my test world, and the apiary validated just fine.
