### ISSUE TITLE
Ars Nouveau Chapter Overhaul

### ISSUE THREAD

**Issue by RobuxShooters** [NillerMedDild/Enigmatica6#3035]
**Description**
With the latest version of E6 (v0.5.11), Ars Nouveau has gotten a major naming overhaul with Mana being renamed into Source and the addition of a few new Sourcelinks (Source generators) along with the removal of passive generation of Source from Volcanic Sourcelinks (was 'Volcanic Accumulator').

Most quests need to be re-written to fit with the new naming scheme and a few quests for the new Sourcelinks should be added to introduce new and older players alike to other forms of Source generation, notably the Mycelial Sourcelink.

**Why would you like this added/changed?**
This should be done to keep up with the latest changes by Ars Nouveau and to not confuse newer players between the disparities in the quest book and the in-game manual.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/16001607/130045776-e349710b-105a-443c-9079-edd95f3790cb.png)

**Comment by MuteTiefling** [comment]
Thanks. Had plans fit this soon, but this serves as a nice reminder.
