### ISSUE TITLE
Changed Advancement Received Message

### ISSUE THREAD

**Issue by jamesos10** [NillerMedDild/Enigmatica6#3037]
### Modpack Version

0.5.11

### Describe your issue

![ảnh](https://user-images.githubusercontent.com/88141875/130059873-2bbe1952-7147-4f62-b8ae-5a9ca4062fed.png)
When i get a create advancements the "made the advancements get" not show only the advancements name show

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MaxFirestorm** [comment]
Pretty sure this isn't limited to Create as I was getting the same thing with some TiCon quests on Saturday.

**Comment by RobuxShooters** [comment]
This might be due to a mod that was recently added in v0.5.10 - Clickable Advancements.

**Comment by NillerMedDild** [comment]
Issue reported here: https://github.com/someaddons/ClickableAdvancements/issues/1

**Comment by NillerMedDild** [comment]
Turns out it was misconfiguration on my part, will be fixed in the next update 👍
