### ISSUE TITLE
Precision Sawmill quest broken

### ISSUE THREAD

**Issue by Jan-aka-q0** [NillerMedDild/Enigmatica6#3038]
### Modpack Version

0.5.9

### Describe your issue

In the mekanism precision sawmill quest, the basic factory shows twice, and the advanced one doesn't show at all, and can't be used for the quest.

[Screenshot](https://jan.has-no-bra.in/57y2Lpnnc)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
