### ISSUE TITLE
'Dustrial Decor recipe conflict with vanilla iron nugget to ingot

### ISSUE THREAD

**Issue by Aiva418** [NillerMedDild/Enigmatica6#3039]
### Modpack Version

0.5.11

### Describe your issue

I tried compressing a stack of iron nuggets in a crafting table to form an iron ingot, but instead I received a block called "Wrapped Ice Chains" from 'Dustrial Decor. Upon investigating in JEI, the recipe appears to have been added by 'Dustrial Decor, but based on the respective recipes for the other types of chain blocks, I can only assume that it was unintentional.

### Have you modified the modpack?

Yes

### User Modifications

I have added Optifine (with bsl shaders) as well as Xaero's map mods, and I have disabled Journeymap.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Found it reported here: https://github.com/BlueDuckYT/DustrialDecor/issues/8

**Comment by Aiva418** [comment]
The github issue hasn't been closed yet on the other side, but as of a few days ago, the latest version of the mod has the correct recipe.

**Comment by misterzirillo** [comment]
Do recipes receive updates aside from when I update the pack manually? I swear I didn't have this problem when playing a week or two ago.

**Comment by NillerMedDild** [comment]
No :)
