### ISSUE TITLE
AE2 Certus Quartz duplication

### ISSUE THREAD

**Issue by KacproPL132** [NillerMedDild/Enigmatica6#304]
**Modpack version**
_0.2.17_

**Issue**
After crafting from 2 normal Certus Quartz 4 Pure Certus Quartz you can craft a block of Certus quartz from 4 Pure, then you can craft from it 4 normal certus quartz. (SS attached)
_**![2020-09-26_11 36 40](https://user-images.githubusercontent.com/60540476/94337663-9e372400-ffec-11ea-9604-e5210f50e0b8.png)
![2020-09-26_11 36 45](https://user-images.githubusercontent.com/60540476/94337664-9f685100-ffec-11ea-962f-90f33b8105ea.png)**_

**Comment by NillerMedDild** [comment]
Woops! Thanks for letting me know.

**Comment by KacproPL132** [comment]
No problem.
