### ISSUE TITLE
Industrial Foregoing's Enchantment Applicator doesn't see Apotheosis extra levels

### ISSUE THREAD

**Issue by Scaietele** [NillerMedDild/Enigmatica6#3040]
### Modpack Version

0.5.11

### Describe your issue

I was trying to obtain a **Sea Infusion 7** sword by combining a **Sea Infusion 6** sword with a **Sea Infusion 6** book in the Industrial Foregoing Enchantment Applicator. What I got was a  **Sea Infusion 5** sword.

Initially I tried doing this combination with pedestals but even with a **Pedestal Capacity 5** enchant on the Exp Anvil Upgrade, it wouldn't let me. It has 105 Exp Levels Stored in it and it asks for over 200 levels. I do have diamonds in a nearby pedestal hoping to override the limit.

### Have you modified the modpack?

Yes

### User Modifications

- Builders Crafts & Additions: added back for the shelves
- MmmMmmMmmMmm: this one I already had for testing weapons, but I saw was added in 0.5.10
- AmbientSounds 3: added back for the ambiance
- Optifine: for better FPS

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Quezler** [comment]
a recent change to that mod added a config option that prevents enchantments from going over their vanilla cap (it can still be disabled in one of the industrial foregoing config files), it (currently) doesn't check if other mods allow ways to get higher-than-vanilla enchantments

**Comment by MuteTiefling** [comment]
> Initially I tried doing this combination with pedestals but even with a Pedestal Capacity 5 enchant on the Exp Anvil Upgrade, it wouldn't let me. It has 105 Exp Levels Stored in it and it asks for over 200 levels.

Additionally, this is totally normal. Pedestals is capped at 105. Anything that requires more is out of reach.
