### ISSUE TITLE
Smeltery Fuel not working

### ISSUE THREAD

**Issue by Oofthe3rd** [NillerMedDild/Enigmatica6#3043]
### Modpack Version

1.16.5

### Describe your issue

I have lava in my melter and it says "Invalid Fuel." There is a KubeJS error for it, if that means anything.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment]
The best place to get this sort of support is our Discord (https://discord.gg/enigmatica). Please post in the support channel with the following info:

- Modpack Version (1.16.5 is the Minecraft version)
- Details of the KubeJS error
- latest.log file (in the logs folder)

Thanks!
