### ISSUE TITLE
Marid's duplication using IF

### ISSUE THREAD

**Issue by albyalex96** [NillerMedDild/Enigmatica6#3045]
### Modpack Version

0.5.11

### Describe your issue

Occultism's Marid Spirits can be duplicated using mob imprisonment tool and a duplicator. Duplicated spirits are not bound to the player and can not perform tasks . 
![trolo](https://user-images.githubusercontent.com/72573722/130246214-bc7f9023-0680-4e39-acf8-22a8a6cb3841.PNG)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, I've fixed it in-dev :)
