### ISSUE TITLE
Unable to Join Server : Took to long to join server

### ISSUE THREAD

**Issue by WorldTeacher** [NillerMedDild/Enigmatica6#3046]
### Modpack Version

0.5.11

### Describe your issue

When trying to join a locally hosted server, I get the message in the console:
Took to long to join server, Disconnected
This repeats until I exit the running minecraft instance.

### Have you modified the modpack?

Yes

### User Modifications

I added tickcontrol, but removing the mod didn't resolve the issue.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by WorldTeacher** [comment]
[log.txt](https://github.com/NillerMedDild/Enigmatica6/files/7023089/log.txt)

**Comment by NillerMedDild** [comment]
Thanks for the report. What kind of log is that?

**Comment by WorldTeacher** [comment]
it is the latest.log, but I had to upload it this way because I can't grab it from the server
