### ISSUE TITLE
Mekanism Digital Miner not collecting some ores

### ISSUE THREAD

**Issue by hsim-bml** [NillerMedDild/Enigmatica6#3048]
### Modpack Version

0.5.9

### Describe your issue

Mekanism Digital Miner is not mining all available ores.

Attached two videos showcasing the initial problem and then what happens after resetting and checking the config etc.

https://user-images.githubusercontent.com/84426533/130312822-5d9686d7-5d6f-492b-96a0-9dfeba438884.mp4

https://user-images.githubusercontent.com/84426533/130312823-c147171f-f7d2-46b9-8146-a97cd68392ba.mp4

### Have you modified the modpack?

Yes

### User Modifications

Added PeacefulSurface
Added FallingTrees

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I cannot reproduce this at all, can you still reproduce it?
