### ISSUE TITLE
Draconic Evolution (Beta Ver.)

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#3049]
**CurseForge Link** 
https://www.curseforge.com/minecraft/mc-mods/draconic-evolution

**Mod description**
This is a mod that adds a lot of high-tier items such as tools and armor as well as some high-tier energy storage and a lot of other random features.

**Why would you like the mod added?**
It is an Epic mod!

**Screenshots if applicable.**
Null

**Comment by Honhk** [comment]
All the random features you've mentioned are already present in some sort of form.

**Comment by TGMax233Michael** [comment]
> All the random features you've mentioned are already present in some sort of form.

I Know

**Comment by TGMax233Michael** [comment]
> All the random features you've mentioned are already present in some sort of form.

I see(sorry my English is not good)

**Comment by TemperedFool** [comment]
I'll put in my own opinion - as already stated the pack already has all those things in spades. The only purpose it's previously served imo is adding a high-tier boss to justify the tools it adds, and some high-tier crafting to act as a power sink at the end of Expert packs. Not sure we need either of those things, unless something major has changed.

**Comment by NillerMedDild** [comment]
I will have a look at it's current state, but the odds of DE being added are low tbf.

**Comment by NillerMedDild** [comment]
I'm sorry but I see no place for DE as it is right now in Enigmatica 6.
