### ISSUE TITLE
[Mod Suggestion] Charm

### ISSUE THREAD

**Issue by SQbuilder** [NillerMedDild/Enigmatica6#305]
https://www.curseforge.com/minecraft/mc-mods/charm

**Comment by MaxNeedsSnacks** [comment]
Currently a Fabric-only release, so unfortunately off the table right now

**Comment by SQbuilder** [comment]
Darn, didn't see that on first glance

**Comment by SQbuilder** [comment]
Forge versions of Charm released late November, check Curseforge recent files. https://www.curseforge.com/minecraft/mc-mods/charm/files

**Comment by NillerMedDild** [comment]
Hmm, looks like quite a bit of duplicate content. I'm not sure tbh.

**Comment by NillerMedDild** [comment]
We decided no on this :)
