### ISSUE TITLE
Compact Machine strips player XP

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica6#3050]
### Modpack Version

0.5.9

### Describe your issue

when using the personal shrinking device to enter a compact machine, all player xp is removed

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
And if you gain/lose any xp after this, what happens? Does it all come back?

**Comment by Dracos99** [comment]
yes it does show back up once you get more exp

**Comment by Honhk** [comment]
While this bug doesn't mean much it would be nice if CM stopped doing that.

**Comment by kjj194** [comment]
This is a vanilla bug, the same thing happens when switching between any dimension.

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/CompactMods/CompactMachines/issues/482

**Comment by MuteTiefling** [comment]
Yep. Totally a vanilla bug. Same happens when you leave The End.

**Comment by NillerMedDild** [comment]
Would be nice regardless :P
