### ISSUE TITLE
Wither Builder Not Placing Blocks

### ISSUE THREAD

**Issue by dbridle** [NillerMedDild/Enigmatica6#3051]
### Modpack Version

Enigmatica 6.0.5.11

### Describe your issue

The Wither Builder is not placing the soul sand and skulls.  This was fixed previously but appears to be broken again in v11.

Tried with and without FTB chunks, also in creative world, same issue.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. I've been unable to reproduce this on 0.5.11, I suggest you reinstall the pack :)
