### ISSUE TITLE
Can't install the modpack via Curseforge Client

### ISSUE THREAD

**Issue by incenargo** [NillerMedDild/Enigmatica6#3052]
### Modpack Version

Enigmatica6-0.5.11

### Describe your issue

Hey, I dont really know if this is the right place to report this issue but i cant install the modpack via the Curseforge Client.
Its downloading like usual but when it finishes theres this red bar at the bottom of the window which say "Mindestens ein Fehler ist aufgetreten." which basically translates into "At least one error has occured.".
Can't download old versions aswell tho.

Greetings

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm afraid there's nothing we can do about that, CurseForge will fix it eventually, I'm guessing it's caused by very high load on their servers.
