### ISSUE TITLE
Blacklist Legendary Blob from Spawners

### ISSUE THREAD

**Issue by xBlizzDevious** [NillerMedDild/Enigmatica6#3054]
### Modpack Version

0.5.11

### Describe your issue

Industrial Foregoing Mob Duplicators are unable to spawn a Legendary Blob from RFTools.

Initially I assumed it was a space restriction but I now have a 9x9x9 area in which it can spawn. After some Googling, it looks like it might be due to the fact the Legendary Blob has so much health that the internal tank of the mob duplicator can't hold enough essence. Is this a feature you want to possible? Is it possible to fix?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment]
These are the things that drop the legendary knowledge, right? If so this seems like more feature than bug - do we want that to be farmable?

**Comment by NillerMedDild** [comment]
This isn't intended, but I want it to be 😄

**Comment by Honhk** [comment]
Aren't legendary blobs the ones that drop legendary dimensional essence?

**Comment by xBlizzDevious** [comment]
Yes, they drop the legendary essence. I spent about 10 minutes killing one and decided I wasn't doing that again. Haha!

I did have a feeling it wasn't intentional but also not desired. Thanks for confirming, at least.

**Comment by NillerMedDild** [comment]
> Yes, they drop the legendary essence. I spent about 10 minutes killing one and decided I wasn't doing that again. Haha!

Understandable 😄 I guess one needs to make some sort of killing contraption for them.

**Comment by xBlizzDevious** [comment]
Oh, I have a killing contraption. It was my mob crusher. I tested it with my useless mob imprisonment tooled blob. But if I have to farm them manually, that's tedious. Wondering if RFTools spawners can produce them.... Or something else?

**Comment by NillerMedDild** [comment]
I'm fairly certain RFTools Spawners can't, and I blacklisted them from Apotheosis, PNC and IF.

It took your Mob Crusher 10 minutes to kill it?

**Comment by NillerMedDild** [comment]
Also, how many do you realisticly need?

**Comment by xBlizzDevious** [comment]
No, took me 10 minutes to kill it. Next one I found went in an imprisonment tool and the crusher insta-killed it.

As for how many I realistically need, considering the amount of dimlets I've gathered from quarrying RFTools dimension worlds, I probably won't ever use them.

**Comment by NillerMedDild** [comment]
Cool, they shall remain blacklisted then 👍
