### ISSUE TITLE
PNC Block Heat Properties: Permafrost temperature conversion seems backwards

### ISSUE THREAD

**Issue by fayk** [NillerMedDild/Enigmatica6#3055]
### Modpack Version

0.5.11

### Describe your issue

Permafrost blocks (Quark) seem to have the wrong Block Heat Properties for PNC. According to the diagram when you inspect 'u'sage for the blocks, they are cold blocks (-50ºc) but 'freeze' to cobblestone. Nothing happens in the UI if you heat them. 

For comparison, inspect 'ice' and see that it cools to a denser form of ice and heats/melts to water.

STEPS TO REPRODUCE:
1. Load into a world
2. Type 'permafrost' into JEI
3. Right click or 'U' on permafrost, then switch to the Block Heat Properties tab.

### Have you modified the modpack?

No

### User Modifications

N/A

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thanks for the report, it does seem to be reversed, I'll get that fixed :)

**Comment by NillerMedDild** [comment]
Submitted a PR to fix it in PNC :)
