### ISSUE TITLE
Chunk error exploring new terrain

### ISSUE THREAD

**Issue by ariosos** [NillerMedDild/Enigmatica6#3056]
### Modpack Version

0.5.11

### Describe your issue

Looks like half of a mountain generated.

Seed:-909185449
Coords: 866, 112
![image](https://user-images.githubusercontent.com/7917753/130337835-f2cd60b1-fbac-4e8d-be11-172c917e0fef.png)

![image](https://user-images.githubusercontent.com/7917753/130337842-deb69592-520b-45e9-b998-042610ec2a1c.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report.
Are you sure you didn't modify the modpack in any way? That HUD in the top left is not default.

**Comment by ariosos** [comment]
No - I think the HUD was one of the fps options.

**Comment by ByteTemplar** [comment]
> 
> 
> No - I think the HUD was one of the fps options.

That is Optifine, that has been added, you can see it in second picture too as listed. 
Although it shouldnt affect terrain generation, but nobody knows what it actually does, being Closed source and not recomended.

Is this world been generated in earlier versions of the pack? Im not sure, if there has been any changes to generation, that could have made that.

**Comment by NillerMedDild** [comment]
Was this with default terrain generation, TerraForged?

**Comment by ByteTemplar** [comment]
I loaded 0.5.11 and created a world with that seed and teleported to the coordinates, everything is fine, so something has changed world gen in your savegame at some point.

Here is screenshot and you can clearly see in minimap that bottom is identical to yours:
![2021-08-22_16 16 19](https://user-images.githubusercontent.com/26749860/130356788-4808e685-d498-431a-b86f-9d6a9384eeda.png)

**Comment by NillerMedDild** [comment]
> I do wonder, if this change in latest update could be the reason:
Adjusted biome weights to make the most common biomes a bit less common.

It shouldn't be, we've tested this before, and switching biome weights in TerraForged does not alter existing worlds.

**Comment by ThePB** [comment]
Some kind of terrain generation change happened in the transition between 0.5.6 and 0.5.7 (tested with my own world seed, spawn is quite different). I tested it when i noticed the change in my 0.5.6 world after updating to 0.5.9 and chalked it up to the usual "mods updated, generation changed".

This is the provided seed/coords in a fresh 0.5.6 instance.

![2021-08-23_16 36 02](https://user-images.githubusercontent.com/5775528/130466200-fdd2ef55-4a17-4748-8c62-c2a7c5b70f01.png)
![2021-08-23_16 36 06](https://user-images.githubusercontent.com/5775528/130466335-31b2ed8f-c4ab-48ba-b445-6994011bc2d0.png)
