### ISSUE TITLE
No Life Essence from Indûstrial Foregoing Fluid Laser

### ISSUE THREAD

**Issue by waechtet** [NillerMedDild/Enigmatica6#3057]
### Modpack Version

0.5.11

### Describe your issue

You get no Life Essence from Fluid Laser.

- in The nether (Basalt Deltas)
- Use a Stasis Chamber from IndForegoing and put a Villager into it (no profession, full grown, full health)
    - Stasis Chamber is on Level 4, Villager on Level 5
- Build Fluid Laser Base above (on Level 8 with eff 2 addon and with four surrounding laser drills filled with eff 2 and speed 2 add ons)
- Put a red Laser Lens in the Laser Base and set depth in the GUI to 7 (Depth 5 to 10 should work for this)

Laser system is powered and running (as can be seen in the GUI of the Laser Base), but no fluid is generated.

I tried it first on a higher level and changed it later down near bedrock level, but that makes no difference. No fluid (life essence) is generated.

### Latest Log

Added lastlog as attachment on the User modifications text

### Have you modified the modpack?

Yes

### User Modifications

Changed config for lost trinkets in folder losttrinkets on file general_common.toml:

unlockCooldown = 3600 (was set to 36000 as standard i think)
maxSlots = 20 (was set to 10 as standard)
------------------------------------------------------------------------

Added OptiFine_1.16.5_HD_U_G8.jar to the mods folder.

Added two screenshots to show the setup of the laser system with villager below and the GUI of the laser base with empty fluid tank.

![fluid_laser_setup](https://user-images.githubusercontent.com/48352292/130345945-0f8da3cd-d5ff-4460-ad11-33ff45090ee1.jpg)
![fluid_laser_base_config_in_gui](https://user-images.githubusercontent.com/48352292/130345947-d4663e38-c4d5-404b-b5c2-6b8988aa8279.jpg)

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7026712/latest.log)

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Quezler** [comment]
the fluid laser may have to be directly ontop of the villager, no 1 block air gap

**Comment by waechtet** [comment]
Ok, that helped. I placed the stasis chamber (and the villager) one block higher, and it worked.
Thank you.
