### ISSUE TITLE
Forge Hammer quest not completing when crafting it

### ISSUE THREAD

**Issue by Crossfade87** [NillerMedDild/Enigmatica6#3058]
### Modpack Version

0.5.11

### Describe your issue

I was up to the forge hammer part of the tetra quests and when I crafted it, the quest did not complete.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thanks for the report, I've removed the misleading title from the quest: You're supposed to power and upgrade the Forge Hammer.

**Comment by Crossfade87** [comment]
Oh thank you heaps for that
