### ISSUE TITLE
IE steel rod recipe conflict

### ISSUE THREAD

**Issue by porkchop713** [NillerMedDild/Enigmatica6#306]
**Modpack version**
0.2.17

**Issue**
The crafting table recipe for IE steel rods conflicts with the conversion recipe between different mods' steel ingots (2 steel ingots arranged vertically). Also, the crafting table recipe currently yields the same as using an IE metal press, so perhaps the yield of one or the other could be adjusted to incentivize using the metal press?

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Patrick1358** [comment]
![image](https://user-images.githubusercontent.com/37535840/102104052-68a91680-3e36-11eb-87fe-a03cf9cc264f.png)
The same issue persists in the latest update, that bein 0.3.0 .

**Comment by NillerMedDild** [comment]
Thank you for the feedback, we are now tracking this issue in #417 :)
