### ISSUE TITLE
"create has failed to load correctly" on launch

### ISSUE THREAD

**Issue by Ratterrieroflazy** [NillerMedDild/Enigmatica6#3060]
### Modpack Version

v0.5.11

### Describe your issue

Every time I launch the modpack it encounters an error and says "create has failed to load correctly" as in the attached image, I have tried installing v0.5.9 to see if that version also has the issue and it also does. I have reinstalled the modpack 3 times and it has the issue each time. Is there a solution? ( I apologize for not being able to link the latest log or crash report, I cant figure out how to get a link to it)
![image](https://user-images.githubusercontent.com/89349278/130360330-a80c388b-a7b8-438f-8e02-36ae652cd905.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. We're gonna need your latest.log for this one: Simply drag and drop it into the text area :)
