### ISSUE TITLE
Server is crushing my internet connection

### ISSUE THREAD

**Issue by lunulu** [NillerMedDild/Enigmatica6#3061]
### Modpack Version

0.5.9/0.5.11

### Describe your issue

I'm hosting a server. Until a certain moment everything worked fine, but then the server began to break my wired Internet connection, only restarting the computer helps.

[2021-08-22-1.log](https://github.com/NillerMedDild/Enigmatica6/files/7028099/2021-08-22-1.log)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm guessing this is tied to something in your world. A ComputerCraft program perhaps?

**Comment by lunulu** [comment]
> Thanks for the report. I'm guessing this is tied to something in your world. A ComputerCraft program perhaps?

No, we don't use ComputerCraft.

My computer is on 24/7. Today I turned off the server at night and everything was fine. As soon as I turned on the server in the morning, the internet was gone as soon as my friend joined the server.
I tried to move this server to another computer, the Internet disappeared there too.

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7030426/latest.log)
[debug.log](https://github.com/NillerMedDild/Enigmatica6/files/7030427/debug.log)
[server.txt](https://github.com/NillerMedDild/Enigmatica6/files/7030429/server.txt)

Also, for the first time this server was launched on Windows 10, then I updated the system to Windows 11, but due to problems with CurseForge, I rolled the system back to Windows 10.

Server: https://drive.google.com/file/d/135pMQugTmMzoH7b_0tb446OxzZvX8fWB/view?usp=sharing

**Comment by NillerMedDild** [comment]
I don't think there's anything we can do to help here I'm afraid, the windows upgrade-and-rollback could be causing all sorts of unknown issues. I recommend you do a clean reinstall of the server.

**Comment by lunulu** [comment]
I already did a clean install with the world transfer, unfortunately it didn't help(

**Comment by NillerMedDild** [comment]
I mean with a new world :/

**Comment by lunulu** [comment]
Oh, ok((
