### ISSUE TITLE
Recipe changes for expert to add some gating to mekanism.

### ISSUE THREAD

**Issue by jmarakelian** [NillerMedDild/Enigmatica6#3065]
**Description**
Just some simple changes to recipes to make Mekanism be properly gated so that expert testing can't be bypassed via Mekanism. In my personal server, I replaced five items in the steel casing recipe in order to gate Mekanism behind industrial foregoing and RFTools. The steel casing had the osmium ingot changed to an RFTools machine frame, and the glass was replaced with pink slime. I then updated the infuser recipe to use a steel casing instead of the osmium ingot. In the quest tab, I altered the quest dependencies for the Mekanism gate to use both industrial foregoing and RFTools instead of just RFTools.

**Why would you like this added/changed?**
Currently expert can be cheesed by using Mekanism machines instead of going the actual gated path. This adds the requirement for two tech mods to be worked through prior to getting to mekanism. I would also recommend some further changes to infusion recipes along the lines of altering what is needed for the different infusion recipes, like instead of osmium, have some complex object with an osmium base, or instead of an iron ingot, an iron block, etc.

**Additional Info.**
I can add an additional comment later with the code I added to the server scripts for the recipe changes, but I have yet to figure out how the quest changes are tracked on the code side, so that would likely be up to someone else to come up with. Something worth noting is the quest for starting the gates seems to be missing a check box and maybe a description to get started (I know this is nitpicky considering the fact that this is still in development, but when else will I have a chance to gripe).

**Comment by TemperedFool** [comment]
Expert is still in development, and not really a complete experience (as you've noticed). I don't believe we've actually worked on progression for Mekanism yet; tech progression in generally is mostly a "normal" experience rather than having progression yet.

**Comment by MuteTiefling** [comment]
We'll get there, don't worry.

As tempered says, the tech side is very incomplete and not ready for testing.

Thanks for the suggestions, just the same.
