### ISSUE TITLE
Crash checking result for Elementium ore using Crusher Spirit

### ISSUE THREAD

**Issue by gildiarz** [NillerMedDild/Enigmatica6#3068]
### Modpack Version

0.5.11

### Describe your issue

Repetitive game crash when trying to check result for MythicBotany Elementium ore using Crusher Spirit from occultism.
Seems to only affect this one ore.

Below screen in moment of crash:
![image](https://user-images.githubusercontent.com/24914007/130655607-61d1e7cb-4314-415f-9e38-c8d4bb59544a.png)

### Crash Report

https://paste.ee/p/tkFxe

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it to Occultism. Not sure that's where it should go, but I didn't see anything helpful in the crash report ^^'

**Comment by DarkAngel22579** [comment]
Ah thats probably my fault for adding elementium to materials.js and unify_materials.js. Its the same type of crash I was getting when the input/result for one of the recipes was air.

**Comment by Skeet91** [comment]
Might be related, but I'm getting server crashes when handing the Crusher Spirit MythicBotany Elementium ore

Server running 0.5.11

Crashlog:
https://paste.ee/p/GUzfE
