### ISSUE TITLE
WOOT

### ISSUE THREAD

**Issue by odog221** [NillerMedDild/Enigmatica6#3071]
**Mod Link:** 
[Curse Forge Link](https://www.curseforge.com/minecraft/mc-mods/woot)
                 [FTB Fandom](https://ftb.fandom.com/wiki/Woot)
                 [Git Hub](https://github.com/Ipsis/Woot)

**Description:** 
Server friendly mob farms that overall benefit the TPS and reduce the amount of crashes. 

**Note:** 
This mod, while can be used to make mob farming super easy, can have its configs changes to not make it as good as it comes by default. its a fairly simple mod and allows for servers to handle the farming of multiple mob types extremely easily.   I know this was suggested before, but I was wondering if we could have a better explanation than just "nope" for why this mod can not be added? 1.16 is terribly optimized for servers and the addition of a mod like this greatly helps them run.  Now, all of the images and most of the guides I can find are from 1.12, however, the 1.16 version is seriously worth taking a look at, and I believe the resources about the 1.16 version of this mod are limited and far between. Even their own Wiki is outdated. however, I did link their GIT, CURSE, and the FTB Fandom page for it.

**P.S.** I saw this issue has been posted before, but I was unsatisfied with the explanation given. If you could elaborate more that would be beneficial. Thank you.

**Comment by TemperedFool** [comment]
For reference, previous issues #590 and #845. I told the OP on Discord we wouldn't just reflexively close it as dupe (those issues are pretty old, Tbf), but actually give it a quick rethink at least.

**Comment by odog221** [comment]
The only reason I want to resuggest this mod is due to the benefits on server performance and player experience when it is added.  On the server which I help moderate, modpacks with WOOT have noticeably higher performance and maintain a higher TPS due to the fact that one WOOT can replace 20 spawners of 4 mob types, where each spawner needs to tick, check spawn conditions, spawn 3-5 mobs which count as entities, and multiple that by 50 for the players on the server.   WOOT just eliminates these issues, and is compatible with IF for pink slime, liquid meat, essence and ether gas, as well as a few other specialized outputs seen by other big mods with mob farming.

**Comment by MuteTiefling** [comment]
Just my two cents, but I don't think TPS can be the only qualifying argument here.

The pack doesn't use a huge number of mob drops for anything and we already have a few really good spawn systems that can all be disabled, saving ticks. Players should be sensitized to the effects of their farms and turn things off when they have enough, or only run them on demand. I know, that's very controversial of me but I don't believe every issue can be resolved by a mod. Some things can only effectively be resolved by education.

**Comment by Honhk** [comment]
Very agreed, Motoko.

**Comment by odog221** [comment]
I do agree yes, all of that is true. But when education fails we try to find alternatives. The main reason for this thread is for Powah using nether stars and blaze rods, or wither skeletons or even just bones. We try to have our players steer away from mekanism power generation due to its nature of ticking despite not being loaded, and adding it would fix a few issues. I agree it isn’t an “end all be all” but I feel as if it would solve more issues than it would cause.

**Comment by odog221** [comment]
I see this mod as more of a catalyst to remove the pathways of various not-so-server friendly means of production and resource generation, as it can bypass the need for separate generations for a multitude of resources.

**Comment by NillerMedDild** [comment]
While the performance benefit of this mod is nice, I simply don't agree with outclassing "classic" mob farms, they're an intregal part of Minecraft imo.

That being said, I'll mow it over some more. If we gate Woot to be dependant on the endgame of several mods it might be worth it.

**Comment by odog221** [comment]
Vanilla mob grinding, I agree, is an i reveal part of the game. But it is also terribly inefficient on server performance at large scales. It could easily be gated behind ether gas or something just as difficult. Either way, I only wanted you to reconsider, and by this message above, I am satisfied. Thank you.
