### ISSUE TITLE
Gold Dupe

### ISSUE THREAD

**Issue by ztk4** [NillerMedDild/Enigmatica6#3072]
### Modpack Version

0.5.11

### Describe your issue

You can use Eidolon's cauldron to make a Golden Apple from: 1 Apple, 2 Gold, 1 Enchanted Ash (and a bucket of water).
You can then use the TCon Smeltery to melt the Golden Apple into 8 Gold.

I haven't tried automating the cauldron yet, but it seems easy enough with some kind of user (fake player), a timer, a dropper, and a hopper. Assuming you can do this, apples and enchanted ash are pretty easily automated via standard game mechanics.

Since this lets you 4x your gold relatively quickly, it seems like a dupe to me ;)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by ztk4** [comment]
Oh BTW looks like this also holds for Golden Carrots and Glistering Melons. They're both crafted in the cauldron for 2 nuggets, and can then be smelted in the smeltery to 8 nuggets. So same 4x ratio, but on the scale of nuggets.

**Comment by TemperedFool** [comment]
This is definitely a dupe - you can automate the cauldron. OTOH, I'm not sure how much of a threat this is; it doesn't sound like it's apt to be all that fast, compared to setups with things like ore generators and bees. It's also a PITA to automate the cauldron.

**Comment by darkphan** [comment]
Ok, so you have all this gold (which cost a bit other materials/fuel to get), now what?

**Comment by ztk4** [comment]
Yeah, I wouldn't say this is game breaking or anything. But making infinite gold from apples and bones _feels_ wrong to me LOL.
~Even though gold is the least useful metal that I always have way too much of ;)~

This def doesn't have to be patched, but I figured it'd gone under the radar and wasn't intentional so I wanted to at least bring light to it.
