### ISSUE TITLE
Nether Ores Spawning on Overworld surface with Basalt Barrera biome

### ISSUE THREAD

**Issue by Golfavel** [NillerMedDild/Enigmatica6#3077]
### Modpack Version

0.5.11

### Describe your issue

Ores including Dimensional Shard, Nether Quartz, and Uranium are spawning exposed in the Basalt Barrera biome.
![overnether](https://user-images.githubusercontent.com/32048635/130821820-3d4d4b9d-b4cb-4c1b-a0e5-59856871a39c.png)

### Have you modified the modpack?

Yes

### User Modifications

Added mod: Optifine

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Known and intended, thanks for the report anyway :)
