### ISSUE TITLE
Reintroduce BYG Nether Biomes (v1.3.2)

### ISSUE THREAD

**Issue by Thiana** [NillerMedDild/Enigmatica6#3079]
**Description**

Reintroduce BYG Nether Biomes since their spawn rates can be adjusted now.

**Why would you like this added/changed?**

They were initially removed because they were too busy/common for the nether. However v1.3.2 of byg allows you to adjust their spawn weights so they could be added back as uncommon biomes. Thanks.

**Comment by Mendanbar** [comment]
> All the trees ought to be available in the market already.

Just to follow up, I haven't found anything other than the Hypogeal Imperium that isn't available from the market.  Personally, though,  I think it might be nice to introduce some variety to the Nether as long as it can be fairly sparse. I prefer to use the market as a last resort, as it's much more fun to go on an adventure for materials. 🤷‍♂️

**Comment by Thiana** [comment]
It's not just about the materials or exploration either, the new biomes are new environments to build in.

**Comment by MuteTiefling** [comment]
For sure, some of them are nice.

If you had to pick a few, which would you say are your favorites?

**Comment by Mendanbar** [comment]
I personally like the Warped Desert, and also the one with the yellow fog (can't recall the name offhand).  I'd vote to completely eliminate the all quartz one (quartz desert?).  I like the white color theme, but getting poked by the quartz is super annoying and I think it takes away some of the challenge of gathering quartz in the nether.

**Comment by Mendanbar** [comment]
and of course I'd vote for the subzero hypogeal because of the (currently) unobtainable item... though I don't really know anything else about that biome

**Comment by Thiana** [comment]
To answer @MuteTiefling:

Include:
* Wailing Mire - I built a dark magic base on an island surrounded by this biome in 0.4
* Crimson Gardens - It's a less dense version of the crimson/warped forests so would be better for building and it looks nicer too.
* Wailing Garth - This one is so alien it's a nice change from the other biomes.

Maybe:
* Embur Bog - This fits well with other nether biomes (vanilla and above) but I dislike it personally, too much orange in one place.

Exclude: 
* Subzero Hypogeal - It's too empty, a wip maybe? Plus cold type biomes in the nether always seems silly.
* Sythian Torrids - It looks more like an overworld biome and looks completely out of place.

There are a few other biomes but I don't think they are sufficiently unique/interesting to include in the 'favorites'.

**Comment by Thiana** [comment]
Quick Followup, these byg blocks/plants (at least) are currently not available via any method in develop.

Weeping Roots
Lament Vine
Wailing Bell Blossom

Nylium Soul Sand/Soil
Overgrown Crimson Blackstone

**Comment by dudeloony** [comment]
How would one go about doing this (re-introducing byg nether biomes) on an individual basis?

**Comment by theboo** [comment]
You would need to set byg as the nether dimension generator in our terraforged preset, then use BYG's configs to enable/disable individual biomes

**Comment by dudeloony** [comment]
Thank you for the help theboo! I'll be sure to implement that next time I have some time.

**Comment by NillerMedDild** [comment]
We will not be doing this I'm afraid, maybe we'll do something special with the nether in future packs.
