### ISSUE TITLE
Botiania flowers easily duplicated with bonemeal

### ISSUE THREAD

**Issue by telemenar** [NillerMedDild/Enigmatica6#308]
**Modpack version*
Enigmatica 6 0.2.17

**Issue**
If you bonemeal an advanced botania flower you get a copy. Even for expensive flowers like Orechid

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Yikes, I'll get that fixed, thanks!
