### ISSUE TITLE
Refined storage autocraft conflicts

### ISSUE THREAD

**Issue by Thelm76** [NillerMedDild/Enigmatica6#3089]
### Modpack Version

0.5.11

### Describe your issue

I was not able to autocraft raw tuna from sushi go crafting with the ressourceful bee recipe.

There are multiple results from the same craft (cucumber, nori sheets and raw tuna) :
![image](https://user-images.githubusercontent.com/25480150/131042212-d981ddd9-2a40-4fae-bc7a-d8fee1d3cffa.png)

And the pattern doesn't allow to choose between results :
![image](https://user-images.githubusercontent.com/25480150/131042609-7b9e1dc9-5158-4c8c-9fd4-cd844156406f.png)

I think it is related to the fact the patterns don't store the result in its NBTs :
```
{
    Input_4:
    {
        id:"resourcefulbees:wax",
        Count:1b
    },
    Version:1,
    Input_0:
    {
        id:"resourcefulbees:wasabee_honeycomb",
        Count:1b
    },
    Exact:0b,
    Input_6:
    {
        id:"resourcefulbees:wasabee_honeycomb",
        Count:1b
    },
    Processing:0b
}
```

This applies to every other "multi-result" crafting recipe that I tried.
The easy fix would be to make an unique crafting recipe for every item, to make autocrafting available.

### Have you modified the modpack?

Yes

### User Modifications

**Server :** 
Installed server-side optimisation mods : 
- starlight-forge-1.0.0-RC2-1.16.5.jar
- sodium-forge-2.9.10.jar

Updated server starter to 2.1.0

**Client :**
Unmodified

### Did the issue happen in singleplayer or on a server?

Both

**Comment by TemperedFool** [comment]
I've fixed the main issue; I'm not positive that we've touched those BLT recipes, but I'll take a peek later.
