### ISSUE TITLE
Gas Dupe (again)

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#309]
**Modpack version**
0.2.17

**Issue**
Repeat of #44

Place two chemical tanks, link them with gas nodes and set one to input. The source tank never drains, even with the destination set to dump excess.

**Logs**
Not Applicable

This was discovered while testing the range of Gas Nodes. It seems they also have no limit, as long as the end points are chunk loaded (I went over 20k blocks away and it was transferring no issue). This might not seem that bad (other than them being dirt cheap) but Nuclear Waste is a gas and can be moved. So it would be feasible to build a contraption far from your base that breaks/places a waste barrel, thus effectively voiding the waste with no dire consequences for your base. You just make a wasteland far far away.

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm thinking we'll remove this in the move to 1.16.3, so it'll be "fixed" then :P
