### ISSUE TITLE
Sushi go crafting - cooler box combines to 0g

### ISSUE THREAD

**Issue by Thelm76** [NillerMedDild/Enigmatica6#3093]
### Modpack Version

0.5.11

### Describe your issue

When crafting ingredients for sushi go crafting using the wasabee, There no quantity stored in NBT.

Thus when putting these ingredients in the cooler box, it considers them to be 0g, and combines them all into a 0g ingredient :

![image](https://user-images.githubusercontent.com/25480150/131133468-fbbfba51-c255-4612-b2ad-c203ea826845.png)
![image](https://user-images.githubusercontent.com/25480150/131133440-d9945315-5015-437a-8ced-5e78110f5abe.png)

I don't know if this issue is SGC related (cooler box should consider max quantity) or enigmatica6 related (crafts should provide max quantity in NBT)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
I can't seem to reproduce this in the current dev build, but I'm not sure I'm doing the same thing to reproduce the issue.

To test, I placed down a fermentation barrel, inserted 64 soy beans and piped in water. All of the resulting soy sauce was sent to a cooler and combined properly. Doing this manually didn't change anything, it all still worked.

Similarly, I repeated the test with wasabi. First manually chopping it, then setting a modular router to chop it for me. All resulting items combined properly in a cooler. 

Lastly, I tried using some to craft sushi, then put the remainders back in the cooler. These combined without fault.

Is there anything in particular that you're doing different?

**Comment by Thelm76** [comment]
Sorry, the soy sauce I use result from the centrifuges from resourceful bees using wasabee combs. Same thing with the shrimps (using the craft with wasabee combs)

**Comment by TemperedFool** [comment]
This reminds me that I need to peek at Soy Sauce NBT generally - that may help some of this.

**Comment by MuteTiefling** [comment]
Yep. Dunno if you can add nbt to the resourceful bees config though. Might need a custom recipe?

The crafting table one for shrimp should be simple though

**Comment by TemperedFool** [comment]
Shouldn't be an issue; there's a `"mainNBTData": {}` tag for centrifuge outputs (and similar for the other outputs), so I've just got to figure out the exact NBT I want to supply.
