### ISSUE TITLE
Client Crash upon looking up Cooking Pot recipes for Ink Sacs

### ISSUE THREAD

**Issue by Scironex** [NillerMedDild/Enigmatica6#3095]
### Modpack Version

0.5.11

### Describe your issue

When, in multiplayer, looking in JEI for recipes that use Ink Sacs, then clicking on the Cooking Pot tab, the client will crash. Does not appear to affect the server. Has happened twice in a row now.

### Crash Report

https://pastebin.com/jzWwWDLv

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by tangzixiang-hash** [comment]
是的，我也遇到了这个问题。

**Comment by MuteTiefling** [comment]
I'm not currently able to reproduce this in Dev

**Comment by Scironex** [comment]
Followup: Asked another player on the server to follow these steps as well; It crashed their client, too.

Their crash log should be attached to this comment.
[crash-2021-08-27_19.34.22-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/7069798/crash-2021-08-27_19.34.22-client.txt)

**Comment by NillerMedDild** [comment]
I'm guessing this has been fixed in-dev by a JEI update :)
