### ISSUE TITLE
Iron Bars Conflicting Recipes

### ISSUE THREAD

**Issue by minecrafterseppe** [NillerMedDild/Enigmatica6#31]
**Modpack version**
e6 0.2.0

**Issue**
conflicting recipy
![unknown](https://user-images.githubusercontent.com/13523046/88478820-82ab9080-cf4b-11ea-9967-ae9aeaedb001.png)
![reee](https://user-images.githubusercontent.com/13523046/88478823-84755400-cf4b-11ea-8161-e7e52bc54955.png)

**Comment by NillerMedDild** [comment]
Those are the tiniest pictures I have ever seen, what are those 2 recipes? :P

**Comment by minecrafterseppe** [comment]
idk why they so tiny lol  its just a printscreen and cropped

**Comment by NillerMedDild** [comment]
Because it's just a printscreen and cropped perhaps ^^
