### ISSUE TITLE
[Mod Suggestion] Repurposed Structures (Forge)

### ISSUE THREAD

**Issue by SQbuilder** [NillerMedDild/Enigmatica6#310]
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

Vanilla-esque randomly generated structures.

**Highly** configurable. Includes further customization with datapacks. 

_May_ require some work to be compatible with modded biomes.

**Comment by NillerMedDild** [comment]
We will add this or something like it in the future, but it's currently blocked by a few other things :)

**Comment by Merlo17** [comment]
As half mentioned on discord I think this should be looked at again for 0.4. Iirc what was blocking it was that we were doubtful it would update further but it seems like it's being maintained

**Comment by NillerMedDild** [comment]
Couldn't really get it to work?

**Comment by theboo** [comment]
in my adventures trying to figure out why valhelsia structures arent generagting outside of player houses, i found that TF and Repurposed structures works together well now!! (here's a snowy mansion)
![image](https://user-images.githubusercontent.com/3585761/109749474-95e0a780-7b8f-11eb-9fed-2bc68e48a709.png

added it to latest dev and having no issues with the structures generating or locating. Definitely worth another look for sure.

https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files

**Comment by Thiana** [comment]
Can we get an update about this? Right now the astral temples are excessively common since the structure pool only contains 3 structures. Thanks.

**Comment by NillerMedDild** [comment]
We will look into this for 0.4.4
