### ISSUE TITLE
Sophisticated backpacks crash

### ISSUE THREAD

**Issue by Frostthejack** [NillerMedDild/Enigmatica6#3108]
### Modpack Version

0.5.9

### Describe your issue

Placed a tank upgrade in the backpack while having a time in a bottle in my inventory i clicked the tank tab then noticed that the tank upgrade changed to the time in a bottle i hovered my mouse over it and the game froze.

![image](https://user-images.githubusercontent.com/348599/131204743-b05849b1-3936-4536-8370-24752c7410c8.png)

Here is the latest log it didnt seem to want to let me post it below but ill copy the link it created and post it in that box as well.
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7070081/latest.log)

### Crash Report

https://pastebin.com/VHNbcyCT

### Latest Log

https://github.com/NillerMedDild/Enigmatica6/files/7070081/latest.log

### Have you modified the modpack?

Yes

### User Modifications

Adjusted the ftbranks on the server to allow more chunks claimed and modified entity culling to fix travel anchors. 

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Frostthejack** [comment]
oh back in game looking at it and looking at my above screenshot i see that it is actually the advanced void upgrade that was replaced by the time in a bottle

**Comment by P3pp3rF1y** [comment]
Did you perhaps click with the bottle on the upgrade? In the version that you have there was a bug that cause deletion of items if they were clicked on upgrades. I just wonder if in that version of enigmatica there's something that makes the slot ignore the condition that only upgrades are supposed to go in there.

**Comment by NillerMedDild** [comment]
Would you mind updating to 0.5.11 and see if that resolves the issue?

**Comment by P3pp3rF1y** [comment]
That is not going to resolve the crash as I have removed logic that drops invalid items from upgrade slots. It may however prevent this from happening to another backpack. 
That said I am still not sure how this could have happened in the first place as there's logic on two different levels that prevents non upgrade items from getting in (slot itself and item handler that stores the items both have condition that only allows upgrade items).

**Comment by Frostthejack** [comment]
> Did you perhaps click with the bottle on the upgrade? In the version that you have there was a bug that cause deletion of items if they were clicked on upgrades. I just wonder if in that version of enigmatica there's something that makes the slot ignore the condition that only upgrades are supposed to go in there.

I did not. I clicked on the tank upgrade tab on the side then looked over noticed it looked funny then simply hovered my mouse over the bottle and it froze. I immediately took a screenshot incase it did not happen again.

**Comment by Frostthejack** [comment]
> Would you mind updating to 0.5.11 and see if that resolves the issue?

I do not mind doing so however i should point out that i have not been able to recreate this issue on the version i am useing.

**Comment by Frostthejack** [comment]
> That is not going to resolve the crash as I have removed logic that drops invalid items from upgrade slots. It may however prevent this from happening to another backpack.
> That said I am still not sure how this could have happened in the first place as there's logic on two different levels that prevents non upgrade items from getting in (slot itself and item handler that stores the items both have condition that only allows upgrade items).

If you look the screenshot you will see two bottles, On in my inventory and one in that slot. I only had one bottle though. I did not shift click that bottle or attempt to drag it into the backpack. Honestly i have 0 ideas on how this could have even happened. Its like the void upgrade transmuted itself into the bottle or just took the image of the bottle. On restart the void upgrade was back in its place and i could not recreate the issue. I am entirely confused as to why it happened.

**Comment by NillerMedDild** [comment]
Alright, I'll close this for the time being, not much more we can do atm :)
