### ISSUE TITLE
Metallurgic Infuser nylium recipe conflict

### ISSUE THREAD

**Issue by Aiva418** [NillerMedDild/Enigmatica6#3109]
### Modpack Version

0.5.11

### Describe your issue

The only way to create warped nylium in the metallurgic infuser is with fungus and crimson nylium, but crimson nylium is accepted as a substitute for netherrack in the recipe for crimson nylium, which is prioritized, so it always makes crimson nylium. This means the machine wastes fungus, time, and energy on a recursive recipe instead of warped nylium.

### Have you modified the modpack?

Yes

### User Modifications

Updated 'Dustrial Decor to 1.2.5 (to fix the wrapped ice chain recipe).
Added Optifine (+Optiforge) and Dynamic Surroundings.

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
