### ISSUE TITLE
MythicBotany Mana Infuser creates an unusable Terrestrial Bee

### ISSUE THREAD

**Issue by zedekblue** [NillerMedDild/Enigmatica6#3110]
### Modpack Version

0.5.11

### Describe your issue

Crafting a Terrestrial bee using the Mythic Botany Mana Infuser rather than the regular Botania Terrestrial Agglomeration Plate results in a bee which disappears immediately when placed.

Edit: Modified as I discovered exactly why this is happening

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment]
Hmm, just the MythBot method is broken? I'll take a look at it tonight. I know I saw similar behavior on the agglomeration plate at first and got it fixed, must not have done so for the mana infuser...
