### ISSUE TITLE
[Mod Suggestion] Ice and Fire

### ISSUE THREAD

**Issue by mthp1999** [NillerMedDild/Enigmatica6#312]
Ice and Fire: Dragons in a whole new light!
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons
Adds a bunch of cool mobs, and also dragons

**Comment by NillerMedDild** [comment]
I will think about it, I'm not sure I want E6 to go in the I&F direction :P

**Comment by Jams52** [comment]
I think Ice and Fire would but good for the pack if you disabled the spawn of most things except maybe the Dragons and Cyclops?

**Comment by NillerMedDild** [comment]
That feels like a waste tbh, Ice and Fire has sooo much more

**Comment by NillerMedDild** [comment]
It's a no for the time being, might re-evaluate later on :)

**Comment by pd93** [comment]
I really enjoyed I&F in E2E, but I did feel like they were a bit common/easy to find. Would you consider this if the spawn rates (and world gen) were turned way down?

I feel this would better reflect the mythical theme of the mod and make it more of a late game (hard to find / rare) thing. This also means it wouldn't interfere with players who don't want to be chased down by a dragon early game (or at all).

Totally understand if this isn't the direction you want to go in though.
