### ISSUE TITLE
Crystal glass smelting

### ISSUE THREAD

**Issue by SplendidTulip** [NillerMedDild/Enigmatica6#3123]
### Modpack Version

0.5.6

### Describe your issue

Hi!
When smelting strange sand, output is vanilla glass instead of crystal glass. I've tried using the redstone furnace and smelting factories and neither are working. 

### Have you modified the modpack?

Yes

### User Modifications

OptiFine 1.16.5

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report! Please update to 0.5.11 and see if this is still an issue :)

**Comment by MuteTiefling** [comment]
Tried it in a few things. Mixed results.

Vanilla Furnace: Crystal Glass
Redstone Furnace: Crystal Glass
Smelting Factory: Vanilla Glass


There is a conflict here since strange sand has the `#forge:sand` tag which vanilla glass is looking for... Will see what I can put together to fix this.

**Comment by SplendidTulip** [comment]
Thank you for your time and effort!
