### ISSUE TITLE
Rougelike Dungeon spawned made out of Create brass casings and andesite casings. Progression Breaking bug.

### ISSUE THREAD

**Issue by Hazmatik** [NillerMedDild/Enigmatica6#3127]
### Modpack Version

0.5.11

### Describe your issue

I was exploring a new singleplayer world and found a Rougelike Dungeon that was generated out of Create Brass Casings and Andesite Casings. This could cause a very big break in progression since it skips the whole process of creating the brass in Create.

Screenshot: https://i.imgur.com/DqCTJru.jpg

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
This is intended. We added this dungeon type ourselves.
