### ISSUE TITLE
Construction Wands don't work with Quark blocks

### ISSUE THREAD

**Issue by jatutterow** [NillerMedDild/Enigmatica6#3130]
### Modpack Version

0.5.11

### Describe your issue

When trying to use a construction wand with a quark block, it just places the entire line of blocks, but the blocks that aren't under the cursor are ghost blocks.
![2021-08-29 23-16-03](https://user-images.githubusercontent.com/70618553/131284806-f4c3ac62-d430-4906-8476-b14e6ad57ca8.gif)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Could you please check whether the mod Connectivity is on the server?

**Comment by jatutterow** [comment]
It's not, it was before the server was updated to 0.5.11, but not anymore.

**Comment by NillerMedDild** [comment]
Would you mind re-adding it and see if the issue persists? :)

**Comment by jatutterow** [comment]
That fixed it!

**Comment by NillerMedDild** [comment]
Awesome, thanks for testing. Connectivity will no longer be removed from server files starting from version 0.5.12.
