### ISSUE TITLE
Ore Chunks are disappeaning in Refined Sorage System

### ISSUE THREAD

**Issue by LordAegis** [NillerMedDild/Enigmatica6#3131]
### Modpack Version

 Enigmatica 6 0.5.11

### Describe your issue

When Ore Chunks are imported in my Storage System by Refined Storage, these ore chunks are disappearing.

### Have you modified the modpack?

Yes

### User Modifications

Added OptiFine_1.16.5_HD_U_G8

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
This very much sounds like you are just exporting them somewhere.
