### ISSUE TITLE
Mod Suggestion: Integrated Additions

### ISSUE THREAD

**Issue by RobuxShooters** [NillerMedDild/Enigmatica6#3134]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/integrated-additions

**Mod description**
Integrated Additions provides a few new components (Dynamic-Setter Reader, essentially a Randomizer) and utilities (a Huge Display Panel) in Integrated Dynamics networks as well as some QOL features to clear, duplicate, set, and show a variable card's relation with other variable cards as well as dragging and dropping items into the Logic Programmer from JEI.

It also adds the Coordinate Inserter that can copy a targeted block's coordinates and is useful when paired up with the other addon mod in this modpack, Integrated Proxy.

**Why would you like the mod added?**
It provides players with a Huge Display Panel which can be useful when working on certain projects that require displaying the variable card's output (or a long NBT output) on a screen. It also provides shortcut functionality to duplicate variable cards and clear variable cards quickly for faster programming. Lastly, it also provides a drag-and-drop functionality in the Logic Programmer so that players don't need to have random blocks and items in their inventory before they can make a list to filter out items. Alternatively, players also do not need to clog their inventory with many different kinds of blocks and items before they can filter out specific items.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/16001607/131355882-f8d2fa9e-9387-4880-b854-f88676ee251e.png)
![image](https://user-images.githubusercontent.com/16001607/131355847-775f6567-892b-47a2-a50c-d33aa57d833a.png)

**Comment by DraGonFiirE** [comment]
This mod makes the world of a difference when "programming" with ID imo. Especially the shortcuts and the cordinate inserter are really nice when using Integrated Proxy!

**Comment by NillerMedDild** [comment]
Seems like a good addition, I am however worried about this part in the CF description:

> This is just the beginning. I'm going to make the integrated additions extremely powerful!

I'd like to wait and see how that plays out :P

**Comment by RobuxShooters** [comment]
> Seems like a good addition, I am however worried about this part in the CF description:
> 
> > This is just the beginning. I'm going to make the integrated additions extremely powerful!
> 
> I'd like to wait and see how that plays out :P

I feel like it may be an unintentional 'lost in translation' sort of thing as the mod author seems to be Chinese and does not have the best of English language skills, as indicated here on the mod page:

> ... my English is very poor, so the translation of this article and mod will be very bad, so if there is something wrong with it, please correct me.

It has also been about 2 months since that description on the modpage was last written, so that's waiting for quite a while :p 

The addon seems to be pretty solid with no bugs found so far since it adds mostly QOL features. Some bugs may be found as more people play with it, but that's true of any other mod.
