### ISSUE TITLE
PNC pressure chamber/pipes exploding on world startup

### ISSUE THREAD

**Issue by robbbiee** [NillerMedDild/Enigmatica6#3135]
### Modpack Version

0.5.11

### Describe your issue

I logged off my world with a 4x4x4 pressure chamber filling with air from an air compressor. I also made sure to add security upgrades in both the chamber and compressor as well as the redstone loop on the compressor that is on the github wiki under "PneumaticCraft: Safe Compressor Usage". When I logged back onto my world I heard a hissing sound and saw my pipes were missing and air pressure was decreasing in my chamber. I patched up the chamber (valve block was broken and on the ground) but continued hearing hissing and noticed the air pressure was going into negative numbers. I broke one block of the multiblock and replaced it to reform the chamber and noticed the base value went up really high, so I did it again and it went even higher - did it again and this time the base value was a negative number. I ended up breaking the entire multiblock and rebuilt it from scratch and the base value went back to the normal 128k.

### Have you modified the modpack?

Yes

### User Modifications

angel ring mod
optifine

changed "alwaysSetupTerrainOffThread" from false to true in forge.client.toml

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Hmm, it sounds similar to this issue: https://github.com/TeamPneumatic/pnc-repressurized/issues/874
Can you reproduce the issue?
