### ISSUE TITLE
Crash when viewing cooking recipes with Sushi Go Crafting rice

### ISSUE THREAD

**Issue by whizvox** [NillerMedDild/Enigmatica6#3146]
### Modpack Version

0.5.11

### Describe your issue

1. Via JEI, press U to view uses for Sushi Go Crafting rice
2. Navigate to the Cooking tab provided by Farmer's Delight
3. UnsupportedOperationException

### Crash Report

https://pastebin.com/cBAz0cpy

### Latest Log

https://www.dropbox.com/s/lnbgios42har6ug/latest.log?dl=0

### Have you modified the modpack?

Yes

### User Modifications

I have Optifine G8 installed as well

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, the bug has been fixed in-dev :)
