### ISSUE TITLE
Energy Upgrade on Elctrolytic Separator does not working

### ISSUE THREAD

**Issue by krakel** [NillerMedDild/Enigmatica6#3148]
### Modpack Version

0.5.11

### Describe your issue

I can use Energy Upgrades on any Mekanism Machine except the Electrolytic Separator.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment]
Energy upgrades on the Electrolytic Seperator only increase the power buffer, they don't decrease energy cost. This is by design, and is native to Mekanism.
