### ISSUE TITLE
Mod suggestion: Goo 

### ISSUE THREAD

**Issue by Jams52** [NillerMedDild/Enigmatica6#315]
https://www.curseforge.com/minecraft/mc-mods/goo
It's a really interesting equivalent exchange type mod that I think would be a nice fit for the pack.

**Comment by NillerMedDild** [comment]
I'll have a look, thanks.

**Comment by Spman1130** [comment]
https://www.curseforge.com/minecraft/mc-mods/silents-gems
for a 1.16 tinkers construct

**Comment by Spman1130** [comment]
http://www.9minecraft.net/silent-gear-mod/
1.16 tinkers construct

**Comment by NillerMedDild** [comment]
@Spman1130 
Please do not highjack other people's issues.
Please do not use 9minecraft.net, that website and others like it are stealing mods for profit, and are doing so illegally.

**Comment by Spman1130** [comment]
i thought it was all the mods suggestion go there and that was the first
google web page that showed up more playing first time suggesting sorry.

**Comment by NillerMedDild** [comment]
No worries :) 
I'm afraid I won't add Silent's Gear, I'm not overly fond of it. Here's a bit more context: https://github.com/NillerMedDild/Enigmatica6/issues/219

**Comment by NillerMedDild** [comment]
Tbh I don't want a mod of this type, not yet at least :) might revisit it for Expert version
