### ISSUE TITLE
Invisible Sunny Blossom leaves

### ISSUE THREAD

**Issue by skybix** [NillerMedDild/Enigmatica6#3150]
### Modpack Version

0.5.11

### Describe your issue

When growing a sunny blossom sapling the leave do not render. They still decay and drop saplings like normal when the trunk is chopped.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report, this ought to be fixed in 0.5.12 by re-adding Connectivity to server files.
