### ISSUE TITLE
Emendatus Enigmatica Clusters craft into random ores

### ISSUE THREAD

**Issue by Golfavel** [NillerMedDild/Enigmatica6#3152]
### Modpack Version

0.5.11

### Describe your issue

Clusters become random ores when uncompressed via crafting, instead of turning back to chunks.
![eesulfur](https://user-images.githubusercontent.com/32048635/131603332-ea9d6211-425c-4eb4-8a32-7f5e42c12f0e.png)
![eediamond](https://user-images.githubusercontent.com/32048635/131603334-d630d6cb-b5d0-4282-a2b0-b81ff7986693.png)
![eecoal](https://user-images.githubusercontent.com/32048635/131603335-a58bc437-3df0-418a-b809-dff89d41267d.png)
![eecopper](https://user-images.githubusercontent.com/32048635/131603337-0077da0c-a13d-4020-90be-27eb4a56b030.png)

### Have you modified the modpack?

Yes

### User Modifications

Optifine

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
