### ISSUE TITLE
Emendatus Enigmatica Fluids

### ISSUE THREAD

**Issue by Kename** [NillerMedDild/Enigmatica6#3159]
### Modpack Version

0.5.11

### Describe your issue

Emendatus Enigmatica fluids in the TiCon smeltery have no castable recipes. For example: emendatusenigmatica:molten_emerald can only be "cast" into other containers/tanks.

For context, the fluids are appearing in RFTools dimensions.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed :)

**Comment by NillerMedDild** [comment]
Removed RFTools Dimensions, which fixed this issue 😄
