### ISSUE TITLE
Tinkers Construct Materials are added to the wrong namespace

### ISSUE THREAD

**Issue by KnightMiner** [NillerMedDild/Enigmatica6#3161]
### Modpack Version

0.5.11

### Describe your issue

Enigmatic 6 adds its custom materials to the Tinkers Construct namespace. This causes us as the devs to receive support requests asking how to make the materials when we have no idea as the tooltip is now wrong, which is why I told you not to do it. Yes, the support requests have already started.

In general you should add all datapack contents to your own namespace (not just materials but also recipes) to give a proper trace to the end user where this came from. Only content that should be in the `tconstruct` namespace is changes to content we add such as tags or materials. For this issue specifically, you should move your materials to your own namespace.

----

For the sake of documentation, Tinkers will automatically convert the domain ID you give it to a display name by capitalizing words and replacing underscores with spaces, so if you use an ID of `enigmatica_6`, it will display as "Enigmatica 6". Alternatively, you can define `domain.<domain_name>.display_name` in your lang file to override the display name to anything you want, in case you want to use something like `enigmatica6` as the ID.

----

For the sake of migrating old users as you already released a version with the wrong namespace, you can define a JSON as follows:

File `data/tconstruct/materials/definition/my_material.json`
```json
{
  "redirect": [
    {
      "id": "enigmatic_6:my_material"
    }
  ]
}
```

This will redirect any existing tools using `tconstruct:my_material` to `enigatic_6:my_material`. At this time the redirect will not change the tool NBT unless parts are swapped, but in a future build I plan to ensure any tool stat rebuild should make the redirect permeant allowing you to eventually remove these redirects.

Let me know if it ends up not working, you can reach me on your discord. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
I think this is already fixed in dev

Parts show they're added by Enigmatica Mod
![image](https://user-images.githubusercontent.com/9543430/131943154-bbeb6fc1-9b24-4bba-bc10-2f62d9c039e4.png)

And Fluids show as from KubeJS
![image](https://user-images.githubusercontent.com/9543430/131943197-b8f38aac-8bf2-4d96-939d-f70145c6e702.png)

**Comment by KnightMiner** [comment]
Good to see its fixed in dev already, I was looking at the master branch. Hopefully you find the information on redirecting materials useful. if you choose to redirect, all you need is the definition file to handle that.

If you choose to not redirect them, tools crafted with the material will not be permanently broken (a part swap will fix the missing material), but its a bit less ideal.

**Comment by NillerMedDild** [comment]
The redirect is very useful, we'll definitely use that, thanks 👍
