### ISSUE TITLE
Engineers Workbench is not working

### ISSUE THREAD

**Issue by add1ct3dd** [NillerMedDild/Enigmatica6#317]
**Modpack version**
Latest Release - though this bug is specific to Immersive Engineering or its implementation into the modpack.

**Issue**
Attempt to put the blueprints and required steel into the Engineers Workbench, it is meant to show the output recipe but it doesn't and does all sorts of UI-glitched duplications of items occurs (fixes itself once you reconnect). Also, the blueprints do not list their type when you hover over them.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Quezler** [comment]
@NillerMedDild would you happen to have manual instructions on how to patch this since the next build isn't out yet?

**Comment by NillerMedDild** [comment]
@Quezler Updating Immersive Engineering should do the trick :) Sorry for the long delay.

**Comment by Quezler** [comment]
> Sorry for the long delay.

a response within 6 hours is perfectly fine ❤️ 

> Updating Immersive Engineering

to which version would you recommend? (also, does it need a config/file/etc update, or just its jarfile?)

(probably this one i suppose: `ImmersiveEngineering-1.16.3-4.1.0-124.jar`)

**Comment by NillerMedDild** [comment]
The most recent 1.16.1 version: https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/3101422
No other changes should be required :)

**Comment by Quezler** [comment]
many thanks 👍
