### ISSUE TITLE
Wilden Chimera Null Point Exception

### ISSUE THREAD

**Issue by Thorandan** [NillerMedDild/Enigmatica6#3171]
### Modpack Version

0.5.11

### Describe your issue

When fighting the Wilden Chimera from Ars Nouveau (required for the tier 3 spell book) the game freezes and crashes with listed reason as "Null point Exception".

### Crash Report

https://pastebin.com/mbaY5rsU

### Latest Log

latest log is too large for pastebin

### Have you modified the modpack?

Yes

### User Modifications

Added Passable Foliage mod - https://www.curseforge.com/minecraft/mc-mods/passable-foliage - version 1,16,5-2.2.1

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, this has been fixed in an update of Ars Nouveau, and will be included in 0.5.12 :)
