### ISSUE TITLE
Dupe Glitch 

### ISSUE THREAD

**Issue by ruyuna0** [NillerMedDild/Enigmatica6#3172]
### Modpack Version

0.5.11

### Describe your issue

So, moving chests I used a cardboard box from Mekanism. Inside the chest is a Constellation Paper from Astral Sorcery, specifically this paper was Aevitas. When I place the cardboard box onto the chest, it produces a constellation paper outside the cardboard box. I remove the cardboard box from the chest and the original is inside.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Dupe #1847
