### ISSUE TITLE
Pneumaticcraft TNT Compressed Iron crafting not working

### ISSUE THREAD

**Issue by NemoracStrebor** [NillerMedDild/Enigmatica6#3174]
### Modpack Version

0.5.11

### Describe your issue

I was trying to start into Pneumaticcraft, and was trying to use the method of blowing up TNT near iron to get compressed iron.  I tried with a full stack of iron, and with only 8 iron, and in both cases the TNT completely blew up all the iron and not a single piece of compressed iron was given.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. You're not in expert mode right?

**Comment by NemoracStrebor** [comment]
> Thanks for the report. You're not in expert mode right?

No I'm not.  Wasn't even aware there was an expert mode.

**Comment by NillerMedDild** [comment]
I cannot reproduce this I'm afraid, could you supply screenshots or perhaps a video?

Expert is still in development, and hasn't been announced yet or anything, so.. there's not really an expert mode :P

**Comment by NemoracStrebor** [comment]
https://imgur.com/a/iPbuQDC

**Comment by NillerMedDild** [comment]
Hmm odd.. Could you perhaps try without the Luck buff?

**Comment by NemoracStrebor** [comment]
Okay, I figured out what it was.  I apologize for not mentioning it as I'd forgotten, but I'd put in Sodium Reforged into the modpack to try to make it run smoother from me.  I pulled it out and apparently that fixed it somehow.

**Comment by NillerMedDild** [comment]
Ah alright, that explains it :P
