### ISSUE TITLE
[Mod Suggestion] Tidbits

### ISSUE THREAD

**Issue by BlueDuckYT** [NillerMedDild/Enigmatica6#3175]
https://www.curseforge.com/minecraft/mc-mods/tidbits

**Mod description**
Tidbits is a collection of various miscellaneous features, most prominently being the four new villager professions (Engineer for redstone-based trades, lumberjack which sells wood-types from all mods, contractor which buys/sells building blocks, and the disc jockey which buys/sells discs and music-related items), and flint and sulfur (gunpowder) ores.  It also adds chainmail, charcoal blocks, and biome-exclusive music discs.  

**Why would you like the mod added?**

The new villagers make the village aspect of the game much more interesting.  It is also compatible with a multitude of mods.  Every feature in this mod is toggleable via the config, so you can disable any features you dislike or have overlap of.

**Screenshots if applicable.**

[Picture of mod features](https://media.forgecdn.net/attachments/thumbnails/392/397/310/172/tidbitsshowcase.png)

**Comment by Thiana** [comment]
10MB filesize seems rather extreme for the listed feature set?

**Comment by MuteTiefling** [comment]
Looking over the feature set, there really doesn't seem like much there that isn't already covered. The villagers seem like they'd be interesting for a Vanilla+ pack, certainly, but with the variety of mods already in the pack they seem rather redundant.

**Comment by BlueDuckYT** [comment]
The 10MB file size is due to the music discs.  I know some features are covered by other mods (such as the block of charcoal mod), but this bundles these features together.  I will admit that the mod is a bit light on features currently.

**Comment by NillerMedDild** [comment]
Looks like a neat mod, but it does seem pretty redundant in Enigmatica 6 tbf :/ 
Which additional foods can be used to breed villagers?

**Comment by BlueDuckYT** [comment]
Currently, it just adds the ability to feed them other fruits (such as melon slices) (tag support will be added in the next patch), baked goods (cookies, cakes, pumpkin pies) for higher food points, and golden food items which have enough food points to instantly breed villagers.

**Comment by NillerMedDild** [comment]
Ah cool. 

I'm afraid it's gonna be a no though, maybe for a future Enigmatica pack :)
