### ISSUE TITLE
no refined storage silicon

### ISSUE THREAD

**Issue by jackyboy1992** [NillerMedDild/Enigmatica6#3181]
### Modpack Version

0.5.11

### Describe your issue

when it comes to crafting silicon it makes the emendatus enigmatica silicon and wont let me use it for refined storage crafting

### Crash Report

-

### Latest Log

-

### Have you modified the modpack?

Yes

### User Modifications

changes the flux mod recipe back to default 

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
This issue was reported in version 0.5.10 and fixed in 0.5.11, are you sure you're using 0.5.11? :)
https://github.com/NillerMedDild/Enigmatica6/issues/2997

**Comment by jackyboy1992** [comment]
ive 100% sure the server is running 0.5.11

**Comment by NillerMedDild** [comment]
I recommend that you reinstall both client and server, it's working just fine for me, I  can craft all of the processors.

**Comment by jackyboy1992** [comment]
ok i have a question then if i reinstall the pack and it works how do i go about resetting the flux network recipes to default as im not a fan of the custom ones

**Comment by NillerMedDild** [comment]
How did you go about changing it the first time?

**Comment by jackyboy1992** [comment]
i went in to the kubejs folder and changed the recipe in there

**Comment by NillerMedDild** [comment]
You can do that again :)

**Comment by jackyboy1992** [comment]
so a reinstall of the pack got it to work i think there might have been an old kubejs folder already in the server from past versions
