### ISSUE TITLE
OreGen not workling properly on private server

### ISSUE THREAD

**Issue by Dsorum** [NillerMedDild/Enigmatica6#3182]
### Modpack Version

0.5.11

### Describe your issue

It seems like there is no ore generation in different stones, except vanilla stone. Is this intended?
I kind of like can't find ores in marble, limestone or other stones.

I did some testing for my own on my private server and the following screenshots shows exactly what i described:

![2021-09-05_20 47 55](https://user-images.githubusercontent.com/10497903/132138312-9958d86f-aca9-4f5d-b9b3-ce9fc95e8472.png)
![2021-09-05_20 47 57](https://user-images.githubusercontent.com/10497903/132138319-537f7676-ea6f-42d0-982a-ec01ce7590e8.png)

Latest log:
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7112184/latest.log)

### Latest Log

https://github.com/NillerMedDild/Enigmatica6/files/7112184/latest.log

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Trostmm** [comment]
Did you change the world type when you created the world? What is it set to?

**Comment by Dsorum** [comment]
I didn't changed it, it is Terraforged.
"level-type=terraforged\:terraforged"

**Comment by theboo** [comment]
im gonna hazzard a guess that your configs did not download properly... world type shouldnt matter here
try reinstalling the pack

**Comment by Dsorum** [comment]
Can u recommend a download place or i just use curseforge again?

**Comment by theboo** [comment]
for your server i recommend following these steps... makes updating a breeze https://github.com/NillerMedDild/Enigmatica6#server-automation

**Comment by theboo** [comment]
sry to send u here then back to discord xD but yeh #support in the discord server would be a good place for this
