### ISSUE TITLE
Delete mod Project: Vibrant Journeys or change its configuration

### ISSUE THREAD

**Issue by Zaakjin** [NillerMedDild/Enigmatica6#3184]
**Delete mod Project: Vibrant Journeys**

**or disable this features:**

cattails = true //BYG have cattails

_This all is creates many useless garbage in inventory and that is annoying_.
barkMushrooms = true
rocks = true
twigs = true
fallenLeaves = true
bones = true
charredBones = true
iceChunks = true
pinecones = true
seashells = true

**Please change all of this to false.**

P.S. Sorry for my bad english.

**Comment by Honhk** [comment]
All I want is the god damn seashells, gone, please, they are so ANNOYING. They make clearing areas of water a nightmare. I do not want to have to set up an RFtools quarry for the seashells every time I want to clear a small water body that would've been fine with just sponges.

**Comment by TemperedFool** [comment]
What exactly makes them a nightmare?

**Comment by Honhk** [comment]
They can be waterlogged. Since the water can't be removed from waterlogged blocks by all the methods I've tried, the water just flows back. When I was clearing an ocean monument once, the RFtools builder couldn't remove the water thanks to the seashells. Once they were gone, the builder could easily remove the water.

**Comment by TemperedFool** [comment]
In that context, why not just use something like the builder, or better a digital miner, to remove the sea shells? Seems like it wouldn't take long.

**Comment by Honhk** [comment]
I had no idea initially why the hell the builder was struggling so bad. Till I saw a seashell with water flowing from it and no water at its level except for itself.

**Comment by TemperedFool** [comment]
So problem solved?

**Comment by Honhk** [comment]
I mean I guess, I just don't like having to deal with seashells. They are useful for prismarine earlier on, but I never needed them.

**Comment by NillerMedDild** [comment]
PVJ is in the modpack intentionally, we're not gonna remove it for the time being I'm afraid 😄
