### ISSUE TITLE
Hot key 

### ISSUE THREAD

**Issue by MisticaX** [NillerMedDild/Enigmatica6#3185]
### Modpack Version

0.5.11

### Describe your issue

Hello everyone!  
It's not exactly issue. 
But problem is, that I can't bind a hot key because it's (mod) not exist in controls menu.  Especially I need it for magnet from Thermal series. Maybe is it possible to add some string in options.txt file? But i don't know what exactly i must  write there, and if it's really would help.  Or maybe possible to change it using command?
Thank you!

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MaxFirestorm** [comment]
If memory serves, Thermal controls come under the listing for CofH

**Comment by MuteTiefling** [comment]
It is indeed:

![image](https://user-images.githubusercontent.com/9543430/132234285-694d9f48-5d15-4630-811d-b3dea34e4940.png)

**Comment by MisticaX** [comment]
Thanks! it helped but with other hot keys!
