### ISSUE TITLE
Game crash when attacking entity (in nether)

### ISSUE THREAD

**Issue by SachiraChin** [NillerMedDild/Enigmatica6#3186]
### Modpack Version

`develop` branch, commit: [2bfa017d7b](https://github.com/NillerMedDild/Enigmatica6/commits/2bfa017d7bad6019ff7beeff4b0efd561533aad3)

### Describe your issue

This happened right after I started the game. I went to nether and there was an animal I could attack, I tried to attack it, game crashed as soon as I tried to attack.

I tried to reproduce this again, but I couldn't. I was able to attack and kill entities in overworld and nether without any issue.

Steps:
1. `git stash`
2. Took latest version from `develop` branch, commit: [2bfa017d7b](https://github.com/NillerMedDild/Enigmatica6/commits/2bfa017d7bad6019ff7beeff4b0efd561533aad3)
2. `git stash apply` and fixed some conflicts
   - This happens sometimes when I apply stashed files. These files are not changed by me, but by game
   - I always revert changes to conflicted files to make sure it's as same as on latest commit
3. Made changes to files in `User Modifications` section
4. Launched the game from `MultiMC`
5. Loaded the last save
6. Went to nether soon as save was loaded
7. Attacked the entity which was right next to the gate
8. Game crashed on first attack

### Crash Report

https://paste.ee/p/E4BaV

### Latest Log

https://1drv.ms/u/s!AhHMmdVs5WzdgaYc0ZxVLjJt6YIATg?e=hHLiUR

### Have you modified the modpack?

Yes

### User Modifications

I have updated the below configs hoping I could get chunk loading.

defaultconfigs\ftbchunks.snbt
```
	chunk_load_offline: true
	max_claimed_chunks: 1000
	max_force_loaded_chunks: 100
```

defaultconfigs\ftbranks\ranks.snbt
```
{
	member: {
		...
               ftbchunks.max_force_loaded: 100,
               ...
	}
	...
}
```

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
i had a very similar crash yesterday, reported to sophisticated backpacks

**Comment by SachiraChin** [comment]
Ohh, gotcha, thank you! I think I saw sophisticated backpacks on error log as well. Hopefully this won't happen very frequently. :D
