### ISSUE TITLE
Create mechanical press recipe conflict for resourceful bee honey types

### ISSUE THREAD

**Issue by NamarienB** [NillerMedDild/Enigmatica6#3187]
### Modpack Version

5.11

### Describe your issue

JEI shows two recipes for liquid honey when using a mechanical press to turn 1000mb of, for example, redstone honey into a block.
It shows both a redstone honey block, and a vanilla honey block.
![image](https://user-images.githubusercontent.com/90112729/132255365-0a07613d-1bfd-4fd2-9d9d-4b4a389627a1.png)
![image](https://user-images.githubusercontent.com/90112729/132255423-94b7cf65-42d1-4960-96c2-2936b347a5a4.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thanks for the report, it's fixed for 0.5.12 :D
