### ISSUE TITLE
Tinker Crafting Station missing from JEI

### ISSUE THREAD

**Issue by geezerbahl** [NillerMedDild/Enigmatica6#3188]
### Modpack Version

0.5.11

### Describe your issue

While you can craft the Tinker Crafting Station with a pattern on top of a normal crafting table, it does not show up in JEI with with version 0.5.11.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thanks for the report. Can you see the slab form of it?

**Comment by geezerbahl** [comment]
Sorry Niels.. not sure what you mean by "slab form".  Can you elaborate?

**Comment by geezerbahl** [comment]
Note - this only seems to be with search.  If you type "crafting station" in JEI it won't show up, but if you press 'u' (Show Uses) on a log, the crafting station does show up.

**Comment by theboo** [comment]
Pretty sure this is fixed in dev when we switched from jei hide scripts to tinkers config to hide the extra stations
