### ISSUE TITLE
[Industrial Foregoing] [1.16.5] Revert the change to the enchantment applicator

### ISSUE THREAD

**Issue by kjj194** [NillerMedDild/Enigmatica6#3192]
**Description**
Write a short description of your suggestion here.
The newest update to industrial foregoing added a config option to make it respect vanilla max enchant level for applying enchantments and set its default to true. Previously this was a nice alternative to the pedestals xp based system that could be used off of essence instead without having to convert it.
**Why would you like this added/changed?**
Doesn't effect the balance as theres already other mods with similar functionality and was enabled by default in all previous versions before they added the config option.
**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/5005560/132320294-977198ba-06be-4bd5-9fea-d17ca711e8f4.png)

**Comment by RobuxShooters** [comment]
Pedestals has a limit on the max number of levels you could apply onto any one item whereas with IF you could go up to absurdly high levels with enough essence, enchantment books, and time. For instance, with Pedestals you could go up to Fortune 8 but with IF you used to be able to go up to over a hundred levels of Fortune. So, setting that config to true will absolutely affect balance.

It might be better instead if it were to respect Apotheosis enchantment levels and scale its 'max vanilla level' accordingly.

**Comment by kjj194** [comment]
I mean you can already get to fortune 16 using other mods in the pack. Being able to go over that might be neat as a challenge but doesn't really affect balance imo, if you're to the point of dumping millions of buckets in essence per book combination the extra resources gained are just a flex not really affecting anything else. Tbf though when I suggested this I didn't realize that it was able to combine to increase level I've only ever used it to apply an enchantment to an already enchanted item which is where I think it shines.

**Comment by NillerMedDild** [comment]
> It might be better instead if it were to respect Apotheosis enchantment levels and scale its 'max vanilla level' accordingly.

That'd be great indeed :P

We requested the config for IF because it was too powerful, we would do the same for the other methods if it was possible :)

**Comment by kjj194** [comment]
Ah alright fair enough.
