### ISSUE TITLE
Storage Quest Not Marked As completed

### ISSUE THREAD

**Issue by kjj194** [NillerMedDild/Enigmatica6#3194]
### Modpack Version

0.5.11

### Describe your issue

When completing all objectives in the Storage logistics quest the category is not marked as complete. If you go into quest editing mode there seems to be a hidden quest for field projectors from Compact Machines that only shows up in expert mode that has not been marked as optional in normal mode. Because it has the expert mode quest as a dependency before unlocking it is impossible to complete even when making the item in normal mode.
![image](https://user-images.githubusercontent.com/5005560/132339088-77578200-240d-4a8f-a910-444ca9456baa.png)
![image](https://user-images.githubusercontent.com/5005560/132339261-5665b73e-3d1e-4a53-beca-06c3abf2156b.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Woops ^^' we'll get that fixed, ty!

**Comment by MuteTiefling** [comment]
fixed!
