### ISSUE TITLE
Crash Issue when using Nether Portal

### ISSUE THREAD

**Issue by Earendilgrey** [NillerMedDild/Enigmatica6#320]
**Modpack version**
0.2.17

**Issue**
Game crashes when going through Nether Portals.  "The game crashed whilst unexpected error
Error: java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
Exit Code: -1" is the error code given
[crash-2020-10-09_13.24.28-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/5356885/crash-2020-10-09_13.24.28-client.txt)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report, the issue is most likely caused by Optifine. Would you mind removing it and seeing if it persists?

**Comment by LeoBeliik** [comment]
Did this happen on a server?

**Comment by Earendilgrey** [comment]
No, single player world. 

Will try to remove Optifine and see if it still happens

**Comment by LeoBeliik** [comment]
I can't reproduce this crash, neither with nor without Optifine.. I still don't know why this happens...

**Comment by NillerMedDild** [comment]
This is with `extremeSoundMuffler-2.0.5_Forge-1.16.1` btw.

**Comment by Darkere** [comment]
Probably caused by Abientsounds and a specific sound that was muffled

**Comment by Earendilgrey** [comment]
Removing Optifine seems to have fixed the problem for the moment.
