### ISSUE TITLE
Aquaculture/Tinkers/Artifacts unintended mod interaction

### ISSUE THREAD

**Issue by Kename** [NillerMedDild/Enigmatica6#3202]
### Modpack Version

0.5.11

### Describe your issue

I hesitate to mention this as it is non-functional and unintentionally _hilarious_, but combining Neptunium Leggings (Aquaculture), Slime Boots (Tinkers) and the Charm of Sinking (Artifacts) results in unbelievable g-forces when entering the water.

https://youtu.be/Ua6q3v1Dm3I

### Have you modified the modpack?

Yes

### User Modifications

I use Halogen for client side rendering.

### Did the issue happen in singleplayer or on a server?

Both

**Comment by theboo** [comment]
Personally I hope this never gets fixed... What a fantastic interaction!

**Comment by Kename** [comment]
Good catch on the slime boots. It also needs at least 2 blocks of water, 1 deep doesn't do anything.

**Comment by MuteTiefling** [comment]
I'm with boo. It's hilarious and harmless.

**Comment by MuteTiefling** [comment]
Well, mostly harmless. I suppose you could die from it

**Comment by NillerMedDild** [comment]
Damn that is awesome, we can't remove that :P
