### ISSUE TITLE
alternate setup energizing orb faulty

### ISSUE THREAD

**Issue by cas-haaijman** [NillerMedDild/Enigmatica6#3203]
The 'alternate' setup using industrial foregoing on the wiki page for automating the energizing orb from powah [https://github.com/NillerMedDild/Enigmatica6/wiki/Powah:-Automating-the-Energizing-Orb](https://github.com/NillerMedDild/Enigmatica6/wiki/Powah:-Automating-the-Energizing-Orb) doesn't work when a recipe results in multiple items: the conveyer belts only extract one item at a time which triggers the crafter too often.

**Comment by MuteTiefling** [comment]
Yeah. It's not perfect. The idea is to show some concepts you can use, not necessarily perfect solutions for every use case.

I'll add a note on the though to warn people.

**Comment by MuteTiefling** [comment]
article updated
