### ISSUE TITLE
not getting specific quest rewards

### ISSUE THREAD

**Issue by the-slothman** [NillerMedDild/Enigmatica6#3205]
### Modpack Version

v0.5.11

### Describe your issue

I have this issue that I'm not getting quest rewards which involve random items like crates and delights I downloaded the modpack from curseforge app and I tried deleting all the files and redownloading the pack and installing it again but it didn't help i don't know if it helps or not but i'm using optifine because I kinda have a low spec computer I hope there would be a way to fix this cuz i'm literaly in love with the enigmatica series thanks for your attention and good content you are providing

### Have you modified the modpack?

Yes

### User Modifications

I added optifine

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
Specific examples of quests that did not give their rewards would be greatly appreciated

**Comment by MuteTiefling** [comment]
I know you've reinstalled, but this really sounds like an installation problem.

The loot tables you're mentioning are all made with custom kubejs scripts. If those scripts didn't download, that's the cause. You need to reinstall again and hope that curseforge doesn't fail on you in the middle.
