### ISSUE TITLE
Occasional crashes in the Nether due to an Immersive Engineering LV Wire Connector in the Overworld

### ISSUE THREAD

**Issue by jchoi071** [NillerMedDild/Enigmatica6#321]
**Modpack version**
0.2.17

**Issue**
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Loading connector blusunrize.immersiveengineering.common.blocks.metal.EnergyConnectorTileEntity@5f58273a... (see log for more info)

The connector is placed onto the side of an LV Capacitor, which is powered directly from below by a Kinetic Dynamo. The wire connected to the LV Connector leads to another LV Wire Connector powering a Refined Storage controller.

OptiFine is installed (the pack is unplayably slow without it) and Ambient Sounds is disabled.

**Logs**
https://pastebin.com/CCF2ggUD

**Comment by NillerMedDild** [comment]
That's odd, I thought that issue had been fixed already. Would you mind updating IE and see if it persists?

**Comment by jchoi071** [comment]
It looks like an IE specific crash; someone mentioned the same problem in the IE Github Issues page, and it was fixed in 4.0.1-120. I switched to 4.0.1-123 and the crashing appears to be fixed.

**Comment by NillerMedDild** [comment]
Hmm, are you certain you're using 0.2.17 of E6?

**Comment by jchoi071** [comment]
Yes, I am.

**Comment by NillerMedDild** [comment]
Alright then. This will be fixed in the update to 1.16.3 :)
