### ISSUE TITLE
Dissolution Chamber + Insightful Crystal interaction

### ISSUE THREAD

**Issue by blockingHD** [NillerMedDild/Enigmatica6#3211]
### Modpack Version

0.5.11

### Describe your issue

If the dissolution chamber has a liquid in its buffer and the Insightful crystal is placed into the bucket input slot it will process adding ~0.4k 'xp' to the crystal. Further to this if you right click the crystal on the chamber it will have the same effect. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Also covered in #3290, closing this as duplicate as I reported the other one :)
