### ISSUE TITLE
Iron bar and Wrapped Ice chains have the same recipe

### ISSUE THREAD

**Issue by C0WB0Y-Ducky** [NillerMedDild/Enigmatica6#3214]
### Modpack Version

0.5.11

### Describe your issue

When crafting iron nuggets to iron bar, wrapped ice chains have the same recipe 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Duplicate of #3039
