### ISSUE TITLE
Some Farmer's Delight addons 

### ISSUE THREAD

**Issue by Mang0z** [NillerMedDild/Enigmatica6#3215]
---------------------------->

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/immersive-cooking
https://www.curseforge.com/minecraft/mc-mods/nethers-delight
https://www.curseforge.com/minecraft/mc-mods/simple-delights
https://www.curseforge.com/minecraft/mc-mods/the-irregular-chef
https://www.curseforge.com/minecraft/mc-mods/copper-pot

**Mod description(s)**
These mods all add Compat/New food items and really make Farmers delight more diverse and expansive

**Why would you like the mod added?**
Alot of people (Including myself) love Farmers delight and would love to have more foods to cook and consume.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/76655777/132775389-f8c3ce71-58df-4dbb-b1d1-1a330355892a.png)
![image](https://user-images.githubusercontent.com/76655777/132775406-4813af98-ea67-4f29-b28e-9ff583f913b4.png)
![image](https://user-images.githubusercontent.com/76655777/132775430-6b8e1eb9-22ad-43c9-bd5b-de134b1f357c.png)
![image](https://user-images.githubusercontent.com/76655777/132775460-9111e508-f3c8-44df-a94d-1f7933c8169a.png)

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by HaxtonSale1** [comment]
I was going to suggest Nether's Delight, but it seems someone already have suggested it.

**Comment by NillerMedDild** [comment]
Testing all but these:

https://www.curseforge.com/minecraft/mc-mods/the-irregular-chef
https://www.curseforge.com/minecraft/mc-mods/copper-pot

Because of lack of support / unhandled issues.
