### ISSUE TITLE
[macOS-specific] Crash during Mojang load screen after modpack folder opened in Finder

### ISSUE THREAD

**Issue by purrloftruth** [NillerMedDild/Enigmatica6#3219]
### Modpack Version

0.5.11

### Describe your issue

**Steps to reproduce:**
1. In the Curseforge client, right-click the listing for Enigmatica 6 and click "Open Folder".
2. (Possibly optional) In the Finder window that opens, open one of the folders displayed, such as `logs`, `crash-reports`, or `mods`.
3. Close the Finder window.
4. In the Curseforge client, click the Play button on the listing for Enigmatica 6.

**Expected behavior:**
- The game loads properly and shows the title menu.

**Observed behavior:**
- The game crashes during the Mojang logo loading screen.

**Notes:**
- Upon a cursory glance, the issue seems to have to do with Tinker's Construct having an issue with .DS_Store files that Finder creates when opening a folder. After investigating further (by deleting the .DS_Store files created one-by-one), it seems specifically the .DS_Store file located at `<modpack>/kubejs/assets/.DS_Store` is the one that causes the crash if present. From what I can glean, the crash log doesn't seem to say anything specifically about kubejs, only Tinker's. After closing the Finder window, using Terminal to delete that file, or all .DS_Store files anywhere within the subtree of the modpack directory enables the pack to be started successfully again (until the directory is re-opened in Finder). The command `find . -name ".DS_Store" -delete` run within the modpack's directory can be used for this purpose. Crash report & latest.log both submitted within the gist.

### Crash Report

https://gist.github.com/purrloftruth/d5b594306bd9ed0bd6fb1c8a9e22b7cf

### Latest Log

https://gist.github.com/purrloftruth/d5b594306bd9ed0bd6fb1c8a9e22b7cf

### Have you modified the modpack?

Yes

### User Modifications

sodium-forge-2.9.10+rev.ea6353c added, but issue occurs without any mods added.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment]
As a Mac user also I'm familiar with this, but I think there's literally nothing to be done about it. The issue isn't just with Tinkers, as I've had this issue prior to its addition. Minecraft just isn't expecting a bunch of garbage strewn about it's directories.

Luckily people don't frequently open all those folders, and I just avoid doing so from the finder personally.
