### ISSUE TITLE
Occasional server crash on player login when aerial interface is fed by universal cable

### ISSUE THREAD

**Issue by glubo** [NillerMedDild/Enigmatica6#322]
**Modpack version**
0.2.17

**Issue**
Sometimes the server crashes with attached exception when player logins while his/her aerial interface is fed by Mekanism's ultimate universal cable.

It seems to happen more when there is more cpu load on the server, but I was unfortunately unable to pinpoint more specific conditions how to reproduce.

**Logs**
https://pastebin.com/wFSd2gBY

**Comment by glubo** [comment]
It seems like this line is the source of that nullpointer
https://github.com/TeamPneumatic/pnc-repressurized/blob/31157e3f40786108c87a6f51a60cb0bd3cb0795c/src/main/java/me/desht/pneumaticcraft/common/tileentity/TileEntityAerialInterface.java#L326

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it :)

**Comment by glubo** [comment]
Thanks for the relay, I was unsure where I should report this :)

**Comment by NillerMedDild** [comment]
Good thing you decided to report it :D
