### ISSUE TITLE
Fermented ancient debris ore meat does not produce anything when used in fluid sieving machine

### ISSUE THREAD

**Issue by CLASIX** [NillerMedDild/Enigmatica6#3220]
### Modpack Version

0.5.11

### Describe your issue

Hello! Thanks for the work you have put into the pack, it is really fantastic. 

Small problem with Industrial Foregoing's Liquid Meat ore processing and Ancient Debris. As I'm sure you know, from the washing factory creates Raw ore meat. Then into the Fermentation station for fermented ore meat. Finally into the Fluid sieving machine for a dust that can be processed. However, when this process is done with ancient debris, on the final step in the fluid sieving machine, it processes but nothing is produced. JEI says Nethrite dust from Mekanism is supposed to be produced. I've done this with 1000 ancient debris in a SP creative world just to make sure it wasn't a chance output and I was getting unlucky.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I can reproduce it, but.. I have no idea why it's happening ^^' not sure how to fix it. The mod dev doesn't know how it's happening either. @Buuz135 halp!
