### ISSUE TITLE
Wither able to pass through Astral Sorcery Illuminated blocks

### ISSUE THREAD

**Issue by SilverRuin** [NillerMedDild/Enigmatica6#3222]
**Modpack version**
Enigmatica6 0.5.11

**Issue**
After spawning a Wither will pass through blocks that have been wither-proofed by the Illumination Wand once it has spotted a target. It would float up and through the ceiling as soon as it sees a valid target (within the box). In this case it's a 9x9x5 box made of Astral Sorcery marble that has been proofed. I used a few different colors for the wand but that shouldn't affect the blocks' property, as the tooltip always says it renders blocks immune to the Wither regardless of the wand's color. It's projectiles were also able to pass through the box as well.

![2021-09-11_01 31 26](https://user-images.githubusercontent.com/88354170/132938970-70822e48-3b87-4cf7-b8ad-c5895f6d9460.png)

**Comment by NillerMedDild** [comment]
Yoink :P

**Comment by NillerMedDild** [comment]
I've relayed the issue, thanks for the report 👍

**Comment by NillerMedDild** [comment]
The response from the Astral team was that this is normal behaviour for the most part, and they couldn't produce projectiles going through the blocks. They recommend you make the box 9x9x6 minimum, so the Wither can't float out :D
