### ISSUE TITLE
Tinker's Planner

### ISSUE THREAD

**Issue by tiffit** [NillerMedDild/Enigmatica6#3223]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/tinkers-planner/

**Mod description**
Tinker's Planner is an addon to Tinkers' Construct that allows you to easily preview the stats of TiCon tools with any tool parts. This mod allows you to test different tool material and modifier combinations very easily.

**Why would you like the mod added?**
(Just as a note, I am the author of this mod) Especially with so many materials available, it can be difficult to find the one you are looking for. Going back and forth through the book is quite time-consuming. This mod simplifies the entire process and makes finding the material you are looking for very easy. Additionally, you can try and find which modifiers could work best for your tool before you irreversibly apply the modifier. 

**Screenshots if applicable.**
Many screenshots showcasing the mod's features can be found at https://www.curseforge.com/minecraft/mc-mods/tinkers-planner/screenshots

**Comment by NillerMedDild** [comment]
Already added in-dev :D

**Comment by theboo** [comment]
very cool mod btw

**Comment by tiffit** [comment]
> Already added in-dev :D

Ah alright, awesome! The modifier update was released just today so I assume you still have the first version of the mod. I've already tested the new update with E6 specifically and didn't find any issues so I do suggest updating to the latest version. 

Very excited that the mod is being considered!
