### ISSUE TITLE
pretty pipes crafting terminal doesnt use oredict items

### ISSUE THREAD

**Issue by ht67810** [NillerMedDild/Enigmatica6#3230]
### Modpack Version

0.5.11

### Describe your issue

Shift-clicking a recipe into the pretty pipes crafting terminal will sometimes give ore dictionary versions of the same item, but the system will not then request valid versions of those items. A couple examples are that recipes that use stone will always show stone in the crafting window and only stone will ever be requested even if there are other valid items that could be used. A second is that an inaccesible non-emendatus version of copper nuggets were shift-clicked into the crafting window, and the emendatus nuggets in the system were not subsequently requested. There is also no way to enter items into the crafting window other than via JEI

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
> There is also no way to enter items into the crafting window other than via JEI

You can move items into the crafting grid, it stores them. That's also why ore dictionary doesn't really work, it's actual items in the crafting grid not placeholders.

It might be possible to optimize this behaviour though...

I shall try to summon the developer, wish me luck.

@Ellpeck - Do you have any insights into this issue, and whether it's possible to improve the Crafting Terminal? :x

**Comment by NillerMedDild** [comment]
While this behaviour isn't the greatest, I don't really see it is a bug, more of a design choice really. I don't think there's anything we can do in the modpack to improve it.
