### ISSUE TITLE
[Astral Sorcery] Mineralis Ritual generates wrong copper ore

### ISSUE THREAD

**Issue by gath875** [NillerMedDild/Enigmatica6#3235]
### Modpack Version

0.5.11

### Describe your issue

When setting up a Mineralis ritual to generate ores, I noticed that copper ore from Tinker's Construct occasionally generates. This ore doesn't drop an ore chunk when mined, it drops the actual ore block. Not a huge deal, but I assume this is not intended. Also, normal copper ores from Emendatus Enigmatica still generate just fine, it seems to generate the Tinker's ore in addition.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Fixed in-dev, thanks for the report!
