### ISSUE TITLE
Pedestals unable to accept Clumps large XP orbs

### ISSUE THREAD

**Issue by DoomSquirter** [NillerMedDild/Enigmatica6#3236]
**Description**
so, not a bug per se but an issue nonetheless....

if you are using rosas as your xp to mana farm and whatever method you use ends up making a clump of xp orbs that are too big for the rosa to gobble on, it just ignores the big clump and lets it sit there.

**Why would you like this added/changed?**

I'm assuming the orbs clump together based on another mod in pack?  Is there a way to limit the size of the xp orbs somehow?  I'm not sure how big that needs to be or anything.

**Screenshots if applicable.**

**Comment by Honhk** [comment]
Could also increase the internal buffer of the rosa to allow it to eat chunky ones. Don't think it's too unbalanced.

**Comment by Quezler** [comment]
i am not sure if its possible to customize the max mana through a config, perhaps kubejs but i doubt it:

https://github.com/VazkiiMods/Botania/blob/fc5715456d9e28506fb0da20172975d72f3e556a/src/main/java/vazkii/botania/common/block/subtile/generating/SubTileArcaneRose.java#L154

**Comment by DoomSquirter** [comment]
a bunch of ppl were trying to help out someone else with this problem a week or so ago.  Essentially, all the orbs in various parts were just sitting there not getting touched ...  shit... I just realized, I should have made the ticket back then when it was more fresh in my mind.  

Thinking about this, I think I'm referring to the wrong mod item.  It may have been pedestals unable to pick up, not rosas.  I blame beerb lol  

Yeah, the more I think about it, it was a pedestal issue not rosa.  
I think this is where the conversation started
https://discord.com/channels/195234321836146688/726178356143456287/880414192430116925

big brain moment
https://discord.com/channels/195234321836146688/726178356143456287/880469710297255997

changing title of issue to reflect this.

**Comment by Honhk** [comment]
Beerb is dumb dumb and poo poo head it wasn't about Rosa it was about something like the xp dropper from pedestals made xp orbs too big for the modular routers.

**Comment by NillerMedDild** [comment]
This report is kinda all over the place...

**Comment by DoomSquirter** [comment]
I have no clue who honhk is lol or why they added to this

ignore the mention of botania rosa.  I was confused cause it was a week or more ago when the issue happened and person that had the issue never made a github issue here so I'm doing it.

essentially, pedestals and possibly modular routers both have this issue (look at links previously in there from discord for where the discussion happened).  

person was using a KOA enchanted sword and the orbs it was dropping were enormous in visual size.  I think they contained more levels than either of those 2 mods could absorb individually.

So my request was trying to see if whatever mod is being used to clump like entities into a group could be configured to limit the size of the max sized xp orb it morphs into.  

If not, I guess git issues need to be sent to both pedestal and modular router then to allow them to absorb huge xp balls.

**Comment by NillerMedDild** [comment]
> So my request was trying to see if whatever mod is being used to clump like entities into a group could be configured to limit the size of the max sized xp orb it morphs into.

Not possible I'm afraid.

Is it possible that the Pedestal's internal buffer could not hold the amount of xp that was in the huge xp orb?

**Comment by DoomSquirter** [comment]
I would have to scan discord which I can't spend the time right now doing.  or test it myself but I don't know the exact setup they used to do all of this.  close this if you wish.  I'm sure if this comes up again from someone else, this issue can be referenced.

**Comment by BooBeerb** [comment]
Doom, it's me Beerb, how could you not recognise me :(

**Comment by zedekblue** [comment]
I've been using KotA 7 + Looting 7 with pedestals for ages and never had an issue with it not absorbing exp.
In fact it seems to pick up exp even if the buffer is full, I've had a single magnet fill up several tanks after I added extra.
I would doubt the original setup that caused this issue.
