### ISSUE TITLE
Botany Pots Tiers

### ISSUE THREAD

**Issue by yavuzselim313** [NillerMedDild/Enigmatica6#3237]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/botany-pots-tiers

**Mod description**
Adds Better Botany Pots from Botany Pots

**Why would you like the mod added?**
It makes Botany Pots faster and more useful actually.

**Screenshots if applicable.**
![grafik](https://user-images.githubusercontent.com/79061657/133197536-848d9573-bdef-410f-b55b-2e437ced6860.png)

**Comment by NillerMedDild** [comment]
Thanks for the suggestion. We do not want to make Botany Pots faster, so no thanks 😄
