### ISSUE TITLE
Can't "shear" grass with Ars Nouveau

### ISSUE THREAD

**Issue by ThePB** [NillerMedDild/Enigmatica6#3238]
### Modpack Version

0.5.11

### Describe your issue

I can't find a way to "abracadabra" my way into obtaining the grass item with spells.

Break with the silk touch (sorry, don't remember the name of the component) can gather leaves, but leaves me with nothing when used on grass - it breaks but gives nothing.

Cut, that says it is used to shear entities and blocks, doesn't work on leaves or grass (i suppose because you don't "shear" them but normally break them with shears?), silk touch component or not.

(also, i did check the releases for Ars Nouveau for info in changelogs, but i might be blind and did not see any possible relevant change.

I did however see that there was a "Extend time" fix for potions (i suppose effects) to make it so that the time extention is more than the 1 second that it is now... I don't think i should report THAT, but know that in E6 0.5.11 the duration reduction component is bugged to 1 second only, too, and i don't know if newer AN versions does fix that or not....)

[latest Cut Spell.log](https://github.com/NillerMedDild/Enigmatica6/files/7161990/latest.Cut.Spell.log)

### Crash Report

N/A

### Latest Log

Above, didn't let me paste it here.

### Have you modified the modpack?

Yes

### User Modifications

Nothing significant i suppose. Basic config changes such as Waystones/JM integration, N° of backups...
Just Tetra spears counting as swords for enchantment purposes is the major point.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by BooBeerb** [comment]
Grass and silktouch have no relation, even in vanilla silk ain't work.

**Comment by ThePB** [comment]
The issue isn't that silk touch isn't working, but it is still worth mentioning because the component does more than that already and there are reasons to believe it might help.

The issue is that i've found no way to replicate both ways shears can be used: left click and right click. Left click is to break blocks - the Break spell replicates breaking blocks. One could assume that it might work as shears too... nope. Right click is shearing - the Cut spell replicates this behaviour, so given that Break doesn't work... nope.

The silk touch component (Extract iirc, but don't trust my memory too much) in itself does more than just "silk touch". It can be used with the Explosion spell to avoid having blocks destroyed, and with the Cut spell for... i have really no idea. Given that no description is given to what it would even do in conjunction with Cut and to my knowledge shears can't have silk touch to begin with, so maybe that's needed to harvest blocks with Cut... but nope.
For the same reason prehaps Break/silk touch component was worth mentioning: not because i believe that silk touch tools can harvest grass, but because prehaps the component was meant to be used to replicate shear behaviour in the first place (alas, nope).

The issue is that "I can't find a way to". Prehaps it would be more of a suggestion than a bug, true. Or even a support requrest? Or an oversight, prehaps. Or the modmaker doesn't want to replicate shear left click for reasons. I don't know, i can only provide as much info as i can. I just believe that it is something that is missing and i don't think it's intended for it to be.

**Comment by MuteTiefling** [comment]
![Screenshot_20210914_111518_com.discord.jpg](https://user-images.githubusercontent.com/9543430/133284930-884d5e0c-8668-4883-9745-d5bdada52e0d.jpg)

Seems like there's some technical limitations

**Comment by MuteTiefling** [comment]
Version 1.23.9 has been released: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3461714
Adds Spell Prisms - a new block that will redirect spell projectiles the direction the block is facing
Carbys now only take out as many items as will fit in the target inventory.
**Break can now simulate shears with Sensitive**
Renames Light to Conjure Magelight
Renames Phantom Block to Conjure Mageblock
Fixes dupe with Toss
