### ISSUE TITLE
Placing Backpack on Armor Stand crashes the game

### ISSUE THREAD

**Issue by NoxianExile** [NillerMedDild/Enigmatica6#3243]
### Modpack Version

0.5.11

### Describe your issue

When you shift + rightclick a sophisticated backpack on an armorstand, it appears to corrupt the chunks around the armor stand, instantly crashing the user who placed it, and any other players who come within render distance of the chunk the armor stand is in.

### Crash Report

https://pastebin.com/Qb3AspBy

### Latest Log

https://zerobin.net/?69a561ee70d4405a#ptvyuMtd8Se4Xs3g806EPNbA+NGpLfyH+jEjkfmfjhU=

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It's fixed already, we just have to update it seems :D
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/208

**Comment by NoxianExile** [comment]
Okay, I wasn't sure if it was the updated version or not, because you can place the backpack on an armorstand fine with a regular right click. But when you shift + right click (the keybind to place a backpack on the ground) onto the armorstand is when it crashes.

**Comment by NillerMedDild** [comment]
Looking at the crash log from the linked issue, the issues should be one and the same :)
