### ISSUE TITLE
Refined Storage Controller Buffer Inaccurate

### ISSUE THREAD

**Issue by The-Tarkol** [NillerMedDild/Enigmatica6#3251]
### Modpack Version

0.5.11

### Describe your issue

Once the Controller from Refined Storage exceeds 16k FE, the network shuts off entirely. The buffer still displays 32k FE as the maximum, and I've verified I have enough power going into the machine that it's not a throughput issue. Being at or below 16k shows no signs of problems, but as soon as the power usage topples that 16k it all shuts off, then will flicker as it tries to turn on continually (causes a fair bit of lag as well).

For now we're just taking out the Dimensional card since it takes a sizable amount of power, but figured y'all should know there's an issue. The server config for Refined Storage shows a 32k FE maximum, so I don't think it's an issue with the server and client desyncing (unless there's another config overriding it maybe)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report. 

We increased the buffer quite a bit in a previous update, the `refinedstorage-server.toml` server config was supposed to update on it's own, I guess it didn't :/ 

I recommend that you delete your `refinedstorage-server.toml` server config (found in the world/serverconfig folder) and let it regenerate, hopefully that'll fix it.

**Comment by The-Tarkol** [comment]
![RefinedStorageUsage](https://user-images.githubusercontent.com/24594751/133554766-e5204ce3-78d9-4081-a289-9af5ff1d760c.PNG)
Still having the same issue, here's a screenshot of when it went over the 16k and everything shut off. We have regenerated the server's config, I can attach it if you need

**Comment by The-Tarkol** [comment]
I imagine there's probably a config or other file somewhere that's not properly updating maybe? I've made sure the world/serverconfig/refinedstorage-server.toml was regenerated, it's showing a buffer size of 32k

**Comment by NillerMedDild** [comment]
Ah, your server hasn't updated the defaultconfigs folder I think.

**Comment by The-Tarkol** [comment]
Just checked, it's got 3 config files listed, but none are refined storage-related. diet-effects, diet-groups, and travel_anchors-server (all .toml of course)

**Comment by NillerMedDild** [comment]
It's supposed to have 65 files and one folder ^^' a reinstall ought to help.

**Comment by The-Tarkol** [comment]
The default config folder doesn't seem to actually be overwriting the serverconfig folder.

Though the defaultconfig folder did fill up after reinstalling the pack.

**Comment by Darkere** [comment]
When the world gets created, the default configs from that folder get copied into world/serverconfig.

You can delete the serverconfigs to make it regenerate.

**Comment by The-Tarkol** [comment]
Found the issue, for some reason the defaultconfigs was actually blank. I downloaded the server on my end and manually stuck the configs over, then regenerated the folder and it's all good now.
