### ISSUE TITLE
Server kick on PneumaticCraft item charge change

### ISSUE THREAD

**Issue by kd8lvt** [NillerMedDild/Enigmatica6#326]
**Modpack version**
Enigmatica 6 v0.2.17

**Issue**
Hosting a server for a few friends, and starting today we've been getting kicked from the server when any of us go near each-other. Originally, we thought it was PneumaticCraft, but we removed all our PC items, and it's still occurring. The only error message we get is:
`Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: LazyOptional is empty or otherwise returned null from getValue() unexpectedly`
We're not sure what the problem is, but the trigger to start it seems to have been PC, and now it's just happening whenever players congregate. **Note it still (seems to) happen whenever the pressure level changes in a PC item or armor, kicking all players within render distance, apart from the one who did it.**

**Logs**
Server latest.log: [https://pastebin.com/RDTdASXc](https://pastebin.com/RDTdASXc) (A join/kick happens at line 15. The panel I use truncates the latest.log, annoyingly...)
Client latest.log: [https://gist.github.com/kd8lvt/0b57c26bf4d4ba79826b9d2e457d1786](https://gist.github.com/kd8lvt/0b57c26bf4d4ba79826b9d2e457d1786) (The final log spam about the sound engine is unrelated, I think.)

**Comment by NillerMedDild** [comment]
Thanks for the report, can you reproduce this without Optifine? :)

**Comment by kd8lvt** [comment]
Thanks for the swift response!
It's kicked everyone who's played, so it's likely not Optifine, but I know that OF is dumb - here's a client log, from a player who doesn't have Optifine installed. [https://gist.github.com/kd8lvt/724142ba1b2430e613de2efee3533c19](https://gist.github.com/kd8lvt/724142ba1b2430e613de2efee3533c19)

**Comment by NillerMedDild** [comment]
Hmm, I see a number of issues at the end of that log, most of which I think will be fixed in the 1.16.3 update :)

**Comment by kd8lvt** [comment]
Good to know! Any idea on an ETA or just 'when it's done'?

**Comment by NillerMedDild** [comment]
ETA this saturday evening, so ~3 days :) it may change though, if we run into issues or mod releases are postponed.

**Comment by kd8lvt** [comment]
Thanks :) We're all having fun, apart from the occasional hiccups - good to hear we're updating soon :D

**Comment by NillerMedDild** [comment]
I'm glad :D 
Just so you know, while we recommend you start a new world in the coming update to 1.16.3, it's not required, but we cannot guarantee you won't run into weird issues :/
