### ISSUE TITLE
RFTools Dimensions crash

### ISSUE THREAD

**Issue by SteamDragon** [NillerMedDild/Enigmatica6#3260]
### Modpack Version

0.5.11

### Describe your issue

The server crashed after some time of entering RFTools Dimension when the server already contains dimension (first one not crashing server) 

### Crash Report

https://drive.google.com/file/d/1HWtSXIppXNcXmMFD6c6Qk7Uk1TvvUs_6/view?usp=sharing

### Latest Log

https://drive.google.com/file/d/1U5CjN8tZrHga_RpfQvhLC7oTpgPaIVng/view?usp=sharing

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
The generated dimension was most likely made up of laggy blocks, falling sand for example. We're in the process of fixing this #3226
