### ISSUE TITLE
Equipment Compare

### ISSUE THREAD

**Issue by AHilyard** [NillerMedDild/Enigmatica6#3261]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/equipment-compare

**Mod description**
A simple quality of life mod that allows you to easily compare currently equipped items to those in your inventory with a keybind.  Useful for comparing high-level equipment and curios when it's not immediately obvious which is better.

**Why would you like the mod added?**
Full disclosure, I wrote the mod and I find it to be a valuable addition to large modpacks like Enigmatica.  It is highly compatible and doesn't detract at all for players that don't need to use it.

**Screenshots if applicable.**
![2021-07-10_16](https://user-images.githubusercontent.com/12298785/133706790-1214e0e3-7695-4f96-b3ac-87050eb05927.png)
![2021-07-16_16](https://user-images.githubusercontent.com/12298785/133706788-04d932fa-c9a2-4cd0-a823-2676cd9c4b97.png)

**Comment by NillerMedDild** [comment]
I'll give it a try, thanks for the suggestion :)
