### ISSUE TITLE
Mob Imprisonment Tool through a Create Deployer crashes the game.

### ISSUE THREAD

**Issue by Iris-6** [NillerMedDild/Enigmatica6#3263]
### Modpack Version

Enigmatica 6 - E6 - 0.5.11

### Describe your issue

Right clicking with a mob imprisonment tool on a mob does nothing, even on a brand new world. I don't know whether this is related to the crash, but might as well mention it. 
**Putting the mob imprisonment tool in a create deployer and having it be used on a mob crashes the game.** _(I managed to do this while trying to get around at first issue)_

**Both issues still occur in brand new worlds.**

The crash does **NOT** take place in a custom new instance **with only Industrial Foregoing, Create, and dependencies installed.** (Using the same versions of the jar files included with the pack)

### Crash Report

https://hastebin.com/ohikejohud.rb

### Have you modified the modpack?

Yes

### User Modifications

Removed Alex's mobs, disabled BYG on nether.
No mods added, no relevant config changes (as far as I can tell), haven't done any sort of script tweaks.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
> java.lang.IllegalStateException: Tag industrialforegoing:mob_imprisonment_tool_blacklist used before it was bound

We have a couple mobs from Alex's blacklisted in IF. I would not be surprised if their absence is causing the crash.

I've been unable to replicate the issue in an unmodified instance of the pack. Can you please try again with a fresh unmodified install?

**Comment by Iris-6** [comment]
Both issues disappear in a newly downloaded instance of the pack. Apologies for the unnecessary report, I never thought removing Alex's mobs would have anything to do with this. 
I'll disable Alex's mobs through configs/other methods and try to test things out in a clean instance also next time.
