### ISSUE TITLE
Ore Gen

### ISSUE THREAD

**Issue by TsudoUmeko** [NillerMedDild/Enigmatica6#3264]
### Modpack Version

0.5.11

### Describe your issue

Ore is only generating in stone. Plain Minecraft stone. No other variations. what so ever. Mined for roughly an hour or so and found 15or so iron and 10 diamonds and whatever other small amount of ores/dusts until i noticed no generation was happening only in basic stone. Wasn't doing this before from what i remember at all. on the last update i was on. This is also a fresh Hardcore world.

### Have you modified the modpack?

Yes

### User Modifications

I have added few other mods that i like to play with "Inventory Pets", "Tiny mob farm". Maybe a couple other smalls ones. Used to play perfectly fine though.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
I recommend you reinstall, ideally without the added mods :)
