### ISSUE TITLE
Replace ReAuth with OAuth

### ISSUE THREAD

**Issue by bobzenmate** [NillerMedDild/Enigmatica6#3265]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/oauth

**Mod description**
OAuth is just like ReAuth but adds Microsoft Login support. ReAuth seems to be abandoned and hasn't been updated in a long time.

**Why would you like the mod added?**
It'd be nice to have a way to relogin to my account since I got my account after migrations were forced.

**Comment by NillerMedDild** [comment]
The author of ReAuth is planning to update to support Microsoft accounts: https://github.com/TechnicianLP/ReAuth/issues/35#issuecomment-906609181

I'd prefer keeping ReAuth if that update comes soon-ish :)
