### ISSUE TITLE
Limitless Lava challenge not registering

### ISSUE THREAD

**Issue by atlgeek007** [NillerMedDild/Enigmatica6#3267]
### Modpack Version

0.5.11

### Describe your issue

I have a supreme black hole tank full of lava thanks to a Quark lava lake and a Create hose pulley, but it is not registering for the Limitless Lava challenge.  I've move the lava back and forth twice via mechanical pipes, and I've even take the time to fill a second supreme black hole tank without any success.

The quest is not registering, but i had no issue with the limitless water and limitless power challenges.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll try to figure out the issue.

Could you please pick up the tank, hold it in your hand and use the command `/kubejs hand`, click the green text output, and paste it here? :D

**Comment by atlgeek007** [comment]
`Item.of('industrialforegoing:supreme_black_hole_tank', '{BlockEntityTag:{filter:{Type:"WHITELIST",Pointer:0,Filter:{}},tank:{FluidName:"minecraft:lava",FacingModes:{TOP:"ENABLED",LEFT:"PULL",RIGHT:"ENABLED",FRONT:"ENABLED",BACK:"ENABLED",BOTTOM:"ENABLED"},Amount:2147483647}}}')`

**Comment by NillerMedDild** [comment]
I have that exact same item, but for me it completed O_o

**Comment by atlgeek007** [comment]
I can try in a single player world but cheating by doing /kill @e[type=minecraft:ender_dragon] seems to have bypassed unlocking challenges so I can't really try it.  I've moved lava back and forth a few times and it doesn't seem to want to trigger for me at all :(

**Comment by NillerMedDild** [comment]
Oh, try changing the left side from pull to enabled.

**Comment by atlgeek007** [comment]
That did it!

**Comment by NillerMedDild** [comment]
Woohoo! I'll try to fix it up still.

**Comment by NillerMedDild** [comment]
I.. can't seem to make it better tbh ^^' I'll add a note in the quest

**Comment by atlgeek007** [comment]
That works for me, may want to add it to all of the "fill up a supreme black hole tank" quests :)
