### ISSUE TITLE
random 3 second lag

### ISSUE THREAD

**Issue by Fabizocker456** [NillerMedDild/Enigmatica6#3268]
### Modpack Version

.5.11

### Describe your issue

I am running this on a linux debian server. Every once in a while, the server lags for approx. 60 ticks. It also idisconnects all connected players, and rejoining takes a lot of time, 30 sec aren't unusual.

### Latest Log

Nothing but "Can't keep up"

### Have you modified the modpack?

Yes

### User Modifications

Yes, a custom kubejs recipe, but it also happens without.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report. We need your latest log to have any chance of solving this :P

Also, I'm afraid 30+ seconds of login time is normal.

**Comment by Fabizocker456** [comment]
I figured out, it is always 63 ticks

**Comment by Fabizocker456** [comment]
Also can I blur out the uuids?

**Comment by NillerMedDild** [comment]
err.. sure

**Comment by Fabizocker456** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7187895/latest.log)

**Comment by NillerMedDild** [comment]
Do you have a RFTools Builder standing idle somewhere? If so, please break or disable it.
The massive amount of filling you're doing could also be the source of lag tbh. Can I see a player's latest log from when the disconnect happened?

**Comment by joshuasuperboy** [comment]
> Do you have a RFTools Builder standing idle somewhere? If so, please break or disable it.
> The massive amount of filling you're doing could also be the source of lag tbh. Can I see a player's latest log from when the disconnect happened?

The same thing also happens to me. I posted it to the enigmatica discord.
