### ISSUE TITLE
Occultism lumberjack causes massive server lag

### ISSUE THREAD

**Issue by bthomp23** [NillerMedDild/Enigmatica6#3269]
### Modpack Version

0.5.11

### Describe your issue

When the occultism lumberjack is in the world the server falls 400+ ticks behind

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
reported here: https://github.com/NillerMedDild/Enigmatica6/issues/3269

**Comment by theboo** [comment]
just realized this is a dupe of https://github.com/NillerMedDild/Enigmatica6/issues/3269

**Comment by NillerMedDild** [comment]
Duplicate of #1680 not #3269 :P

**Comment by theboo** [comment]
wow, i literally linked this issue... i should go to bed lmao
