### ISSUE TITLE
Better Nether Reforged

### ISSUE THREAD

**Issue by dudeloony** [NillerMedDild/Enigmatica6#3278]
---------------------------->
[BetterNether Reforged](https://www.curseforge.com/minecraft/mc-mods/betternether-reforged)

**Mod description**
It expands the Nether's content quite a bit, adding beautiful structures and scenery as well.

Quote from curseforge page:
"So far, BetterNether Reforged is compatible with all tested Nether Biome Mods, including (but not limited to), Infernal Expansion, Cinderscapes Reforged and Oh The Biomes You'll go."

It's worth noting that unlike BetterEnd Reforged, BetterNether Reforged is an unofficial port. It is also a beta that has only been out for <24 hours, so it may be wise to wait for implementation until further content is added and playtesting has occurred. It is also missing nether cities.
I guess just put this on your radar as a potential nether-altering world generation mod to utilize.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion.

I've already checked this out, and to be honest I'm not really a fan, I'd rather keep a minimalistic nether 😄

**Comment by dudeloony** [comment]
Okie, not a bad idea considering you have a limited amount of mods you can add.
