### ISSUE TITLE
Block Absorber breaking bedrock

### ISSUE THREAD

**Issue by Jappie3** [NillerMedDild/Enigmatica6#3279]
### Modpack Version

0.5.11

### Describe your issue

https://cdn.discordapp.com/attachments/344761800707014658/888870356830523442/unknown.png
I placed down the block absorber from RFToolsDimensions and it started breaking (or absorbing xD) the bedrock below it. (screenshot linked)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, I've relayed it here: https://github.com/McJtyMods/RFToolsDimensions/issues/383
