### ISSUE TITLE
Mod Suggestion - Tips (1.16.3)

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#328]
It's just a small mod. It might be nice to see these tips when world loads. 
https://www.curseforge.com/minecraft/mc-mods/tips

**Comment by NillerMedDild** [comment]
Already added in-dev

**Comment by TGMax233Michael** [comment]
:O

**Comment by TGMax233Michael** [comment]
The response was too fast XD

**Comment by NillerMedDild** [comment]
Sorry :P
