### ISSUE TITLE
Magical Feathers (from Lost Trinkets) does not accept Elytra

### ISSUE THREAD

**Issue by SachiraChin** [NillerMedDild/Enigmatica6#3282]
### Modpack Version

commit [a7cd80098379f247](https://github.com/NillerMedDild/Enigmatica6/commits/a7cd80098379f2474ff758c499d1bea0173301fb) from `develop` branch

### Describe your issue.

I have been trying to get Magical Feathers (from Lost Trinkets), and I was able to get all items required for it. But when I tried to create it, it seems like it does not identify Elytra to create it. First I thought it's because the Elytra I had had enchantments in it, so I tried removing them and trying again, but still it doesn't allow me to create it.

One observation was, refined storage says the Elytra is not in storage while I had both enchanted and unenchanted ones in storage. 

**Screenshots**
- Refined Storage
![refined-storage-with-unenchaned-elytra](https://user-images.githubusercontent.com/467272/133937371-0d2c67d9-410f-47c3-b0a8-64bace99fece.jpg)
![refined-storage-with-enchaned-elytra](https://user-images.githubusercontent.com/467272/133937372-fad16453-6158-4ef3-98ed-d460f459ddcc.jpg)
- Vanilla crafting table
![vanilla-crafting-table-with-unenchanted-elytra](https://user-images.githubusercontent.com/467272/133937373-f633ecd4-338f-4226-abf1-d870218c08a8.jpg)

### Crash Report

N/A

### Latest Log

https://1drv.ms/u/s!AhHMmdVs5WzdgaZOFIjk40OZPTR15A?e=RUssZj

### Have you modified the modpack?

No

### User Modifications

N/A

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Got it fixed up for next update :)

**Comment by SachiraChin** [comment]
Awesome and thank you! :D Let me know if you commit it to develop branch, will pull it and give it a try.

**Comment by NillerMedDild** [comment]
Oh I forgot to push 😅 should be good to pull now.

**Comment by SachiraChin** [comment]
Thank you sir! I'm outside right now, will pull it as soon as I'm at home.
