### ISSUE TITLE
[Expert] Come up with an interesting way of creating bricks from multiple ingredients

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#3283]
This would be used for:

- Kiln Brick
- Blast Brick
- Coke Brick

And probably more down the line. 

Input / ideas are very welcome here :)

**Comment by MuteTiefling** [comment]
Not quite what you're asking for :D but just an idea off the top of my head here that could be combined with the current recipes. 

Regular brick:

Machine: Create Mixer (no heat)
Inputs:
4 sand
1 lime sand
1 clay block
1 aluminum dust
500 mb water

Output: 1152 mb "Brick Mixture" fluid. 144 mb casts to 1 brick. Air dried, so nothing fancy here. 8 bricks output


Nether Brick
Machine: Create Mixer (no heat)
Inputs:
5 soul sand
4 cinder flour
1 lead dust
500 mb water

Output: 1152 mb "Nether Brick Mixture" fluid. 144 mb casts to 1 Wet Nether Brick. Blasted to Nether Brick

Mortar
Machine: Create Mixer (no heat)
1 lime sand
1 ground prismarine 
250 mb liquid concrete

Output:  1000 mb mortar

Assembling Brick Blocks
Create Sequential Assembly

Start item = 1 paper (just something cheap to lay everything out on)
Sequence 
1. deploy brick
2. deploy brick
3. spout 50 mb of mortar

repeat 2x 

output 1 brick block

Similar concept for nether bricks and assembling other brick types. 

Idea would be that you could have a 'generic' brick assembly machine that could receive all recipes and use the same sequence to create the final block(s)

**Comment by NillerMedDild** [comment]
That is super evil for bricks alone :P

I like the concept though, could totally be used for IE multiblock bricks.

**Comment by NillerMedDild** [comment]
@argenisRO I'd love your input on this if you have any :D

**Comment by noa12390** [comment]
well there is an evil way to make the coke brick using shadow steel and a tinkers smeltery look at chroma tech 2 it bad enuff

**Comment by NillerMedDild** [comment]
That doesn't really fit into the available mods at that progression point too well I'm afraid, but thanks for the idea!

**Comment by noa12390** [comment]
if you can gate the coke brick rescipe it will not matter if you leave the blast brick the same same for the tinkers hammer by the way would keep that from being on any immersive building or they can skip semi to immersive well but still will do little good if you can't make the multi block buildings or well steel with out coal coke
