### ISSUE TITLE
Quest panel crashes when e is pressed

### ISSUE THREAD

**Issue by Rhinemann** [NillerMedDild/Enigmatica6#3287]
### Modpack Version

0.5.11

### Describe your issue.

When I try to exit the quest tab using the 'e' key the game lags and then crashes, but it doesn't happen when I exit it with escape key. The crash report states the problem with keyPressed event handler.

### Crash Report

https://pastebin.com/8WBHSTNf

### Have you modified the modpack?

Yes

### User Modifications

I added thermal cultivation and worldedit, worldedit items and worldedit CUI. When last three mods are removed the issue is gone.

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Darkere** [comment]
Seems to be caused by WorldEdit CUI
