### ISSUE TITLE
Enhancement for Refined Storage

### ISSUE THREAD

**Issue by MagisterXero** [NillerMedDild/Enigmatica6#3295]
### URL

https://www.curseforge.com/minecraft/mc-mods/cable-tiers

### Why would you like the mod added?

Sometimes the RS importers are just a bit too slow for large import/export tasks.
Cable Tiers implements some nifty new enhanced tiers that could be useful for situations like this.

**Comment by NillerMedDild** [comment]
Why did you remove the mod? :)

**Comment by BooBeerb** [comment]
What happened here?

**Comment by MagisterXero** [comment]
There was already a closed issue from before detailing things.
