### ISSUE TITLE
Cant use Prismatic cobweb on some tools

### ISSUE THREAD

**Issue by jaypitti** [NillerMedDild/Enigmatica6#3300]
### Modpack Version

0.5.11

### Describe your issue.

I found a Radial Iron Pickaxe and crafted a Refined Obsidian Picaxe when enchanted both received life mending when trying to remove it with Prismatic cobweb it does not work, I tried on a vanilla tool and it works as expected. 

I also tried on a refined obsidian helmet and again it does not work

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
Seems to be working fine in Dev.
![image](https://user-images.githubusercontent.com/9543430/134502598-7dafaddc-b27d-4eb0-977d-a9bed8226931.png)

![image](https://user-images.githubusercontent.com/9543430/134502614-d2a4d833-2ae8-4b15-93d4-db68f14d29d8.png)

![image](https://user-images.githubusercontent.com/9543430/134502646-244d890f-0dcd-405a-a9d8-fab91793954f.png)

Possibly a bug that's already been fixed?

**Comment by NillerMedDild** [comment]
Very likely, dev is a few Apotheosis versions ahead 👍
