### ISSUE TITLE
Crash to title screen with Rice of Sushi mod and farmers delight.

### ISSUE THREAD

**Issue by Slowwloriss** [NillerMedDild/Enigmatica6#3302]
### Modpack Version

0.5.11

### Describe your issue.

I have Rice of sushi mod in chest, when i press U for recipes, and i go to farmers delight tab the game crash. 

### Crash Report

https://pastebin.com/eEmzFbEX

### Have you modified the modpack?

Yes

### User Modifications

I have Passive mobs installed too. 

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Fixed in-dev, thanks for the report though :)
