### ISSUE TITLE
Stackable Batteries = Infinte Power

### ISSUE THREAD

**Issue by 1Yunis1** [NillerMedDild/Enigmatica6#3306]
### Modpack Version

0.5.11

### Describe your issue.

Power Dupe through Integrated Dynamics Batteries, Stack them and put them somewhere to Charge

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Reproduced and reported issue here: https://github.com/CyclopsMC/IntegratedDynamics/issues/1100
