### ISSUE TITLE
[0.5.12] Wrenches and Block Rotation

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#3310]
### Modpack Version

0.5.12

### Describe your issue.

When using certain wrenches or wrench like items they seem unable to rotate blocks by 90 degrees and instead will only rotate 180 degrees or more. This behavior was immediately noticed when I was attempting to rotate a Dynamo by 90 degrees.

Affected tools: Crescent Hammer (Thermal), Wrench (Refined Storage), Engineer's Hammer (Immersive), & Pneumatic Wrench (PneumaticCraft)
Unaffected tools: Wrench (Integrated Dynamics), Configurator (Mekanism), & Smart Wrench (RFTools)

Wrenches tested against a Reinforced Chest, Redstone Furnace, Pulverizer, Lapidary Dynamo, Furnace, and Lootr chest.

I loaded my 0.5.11 instance and all the wrenches rotate blocks correctly.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I.. have no idea what's causing this 😅

**Comment by anivlys** [comment]
> 
> 
> I.. have no idea what's causing this 😅
If it was just one mod it would certainly simplify it, but my only (uneducated) guess is maybe some forge interaction. Though that just leads to testing each mod with just forge installed to see if it happens with just say Thermal + Forge. Don't know if you've already tried that though.

Wild guess, do you know what caused the double click issue with the quest book and clicking on items previously? Maybe it is something similar here with the wrenches now doing double right clicks.

At least it isn't all the wrenches, though I'm sad that my default block rotater (Thermal's) is affected.

**Comment by tiffit** [comment]
My (uneducated) guess is that two different mods rotate the block 90 degrees. This ends up causing the block to rotate 180 degrees. Maybe some mod adds in the ability for wrenches to rotate blocks but that ability already exists so it doubles up?

**Comment by daniilsan347** [comment]
I want to add that because of this bug, you also can't flip Powered Lantern from IE with Engineer's Hammer. It flips two times immediately, so nothing changes.

**Comment by NillerMedDild** [comment]
Fixed by https://github.com/TheIllusiveC4/Diet/issues/87
