### ISSUE TITLE
Can't join Server since 0.5.12 update

### ISSUE THREAD

**Issue by Firefly0402** [NillerMedDild/Enigmatica6#3311]
### Modpack Version

Enigmatica 6 - 0.5.12 alpha

### Describe your issue.

Since the update we can no longer join the server. Several players get the error: "Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException". Server and clients have the same Version (0.5.12). I'll attach the "latest.log" file. Perhaps it helps finding a solution. 
Thanks :)
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7229427/latest.log)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Oh sorry about that, forgot to test whether servers on normal mode work ^^'
