### ISSUE TITLE
unable to plant grapes in botany pots

### ISSUE THREAD

**Issue by BigAngelUK** [NillerMedDild/Enigmatica6#3313]
### Modpack Version

0.5.11

### Describe your issue.

I unable to plant grapes seeds in the botany pots.

### Have you modified the modpack?

Yes

### User Modifications

[angelring-1.16.5-1.3.4.1.zip](https://github.com/NillerMedDild/Enigmatica6/files/7229912/angelring-1.16.5-1.3.4.1.zip)

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
That is known and intended, as grape growth doesn't really make sense in a Botany Pot :)
