### ISSUE TITLE
[0.5.12] Create Cogwheels placing

### ISSUE THREAD

**Issue by daniilsan347** [NillerMedDild/Enigmatica6#3317]
### Modpack Version

0.5.12

### Describe your issue.

When placing a cogwheel next to another one, looking at it (when arrow with direction appears), two cogwheels are placed. For example, when you try to place a Cogwheel next to a Large Cogwheel, two small ones are placed, one correctly and one misplaced. It looks that this issue may be related to a bug with wrenches which rotates blocks by 180 deg. So, it looks like double click issue.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Fixed by https://github.com/TheIllusiveC4/Diet/issues/87
will hotfix asap

**Comment by daniilsan347** [comment]
I don't understand, how Diet mod was causing this issue? It feels illogical but it is somehow true.
