### ISSUE TITLE
Missing recipe compatibility chest

### ISSUE THREAD

**Issue by Terminator81** [NillerMedDild/Enigmatica6#3325]
### Modpack Version

0.5.13

### Describe your issue.

since the update to 0.5.13 the crafters like Netherite-Crafter are no longer producible, because you can't produce a normal chest.

In the update the new version of Extra-Storage is inserted and this has only neural processors and chests as a new recipe.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
You can turn any chest into a normal chest by crafting it.

**Comment by NillerMedDild** [comment]
I submitted a PR fixing this issue: https://github.com/Edivad99/ExtraStorage/pull/36

**Comment by Edivad99** [comment]
@NillerMedDild I released an update to the mod, this issue should be closed

**Comment by NillerMedDild** [comment]
Thank you kindly :)
