### ISSUE TITLE
Getting a crash report for a invalid file name

### ISSUE THREAD

**Issue by SyButter** [NillerMedDild/Enigmatica6#3331]
### Modpack Version

0.5.14 (beta)

### Describe your issue.

I was on my Mac and had just downloaded the CurseForge launcher as well at Enigmatica 6 5.11. I wanted to make sushi and because of the bugged recipes I thought I would update and so I went ahead and did it. once launching I came across this crash error:
![image](https://user-images.githubusercontent.com/61396233/135128831-f656afe7-54d2-4a06-ab8e-5bf853ca4463.png)

I would like to think that since I had installed the 5.11 version before the 5.14 windows may have added a 2 to signify the second copy. 

Fixed by removing modpack and completely reinstalling directly to 5.14 (beta) instead of downloading 5.11 then 5.14 

### Crash Report

https://cdn.discordapp.com/attachments/551915524226023427/892449676563972166/crash-2021-09-28_11.54.44-client.txt

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
This issue is almost certainly caused by the CurseForge App, nothing we can do about it. Thanks for the report though.
