### ISSUE TITLE
Game crashes when i rightclick a stack of items

### ISSUE THREAD

**Issue by 0dikpah** [NillerMedDild/Enigmatica6#3338]
### Modpack Version

0.5.11

### Describe your issue.

Game crashes when i rightclick a stack of items, can someone tell me what cause it to happen.
Or tell me if a mod is causing the crash and if yes, which one?

### Crash Report

https://ufile.io/qrv1komb

### Have you modified the modpack?

Yes

### User Modifications

added some mods to the pack

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
caused by the creative crafter mod. you can downgrade to fix it.

**Comment by 0dikpah** [comment]
thank you so much for helping me
