### ISSUE TITLE
Datapack error loading world

### ISSUE THREAD

**Issue by tuca1234567890** [NillerMedDild/Enigmatica6#3348]
### Modpack Version

0.5.14

### Describe your issue.

World gives a datapack error if you try to join it. Latest.log mentions cyclops-core and kubejs so it may be an incompatibility?

### Latest Log

https://gist.github.com/tuca1234567890/99a958ecb76c9083e27b806a69f85c99

### Have you modified the modpack?

Yes

### User Modifications

Removed FPS Reducer, tweaked Alex's Mobs spawns.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
I recommend that you reinstall, this doesn't happen on 0.5.14 normally :)
