### ISSUE TITLE
Server memory leak

### ISSUE THREAD

**Issue by Neryss** [NillerMedDild/Enigmatica6#3349]
### Modpack Version

0.5.11

### Describe your issue.

Server crashes making my physical one shutdown. No trace from neither the server modpack crash reports nor from my server logs. Only thing I have is an "out of memory" caused by Java which can be seen [here](https://imgur.com/a/mzbnl8R).
The crash only happens when the Enigmatica server stays on and we play for 5-6 hours sometime less. Makes the whole system shutdown whitout any logs.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Please update to 0.5.14 and see if the issue persists.

I'm afraid the most likely cause of this issue is some extremely inefficient setup on the server. I don't believe this is something that happens normally on Enigmatica 6 servers, at least not on any of mine.

**Comment by Neryss** [comment]
Thanks for the answer, I just tried with the 0.5.14 but I can't event connect to the server, client side, it's telling me that a token is missing after "t" when I first tried to connect, then I'm just stuck at "Encrypting".
Server side I had [this](https://imgur.com/a/CJyhFq1).

**Comment by NillerMedDild** [comment]
Yikes. Could you please provide both client and server latest.logs? :)

**Comment by Neryss** [comment]
Ok so I tried again and 0.5.14 seems to be working fine now I don't know why, I'll try with people joining me tomorrow !
