### ISSUE TITLE
I updated the modpack and it crashes on startup

### ISSUE THREAD

**Issue by Dragon77mathbye** [NillerMedDild/Enigmatica6#3351]
### Modpack Version

0.5.14

### Describe your issue.

I open the modpack, and the game opens, but then after a few seconds it crashes with no log or context as to why it crashed.

### Crash Report

no crash report even though it did crash

### Latest Log

https://pastebin.com/0tHAQfSf

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
A reinstall ought to fix that, looks like something went wrong in the update :)

**Comment by Dragon77mathbye** [comment]
Reinstalling it fixed it, thank you ;)
