### ISSUE TITLE
Substrate wont craft

### ISSUE THREAD

**Issue by ExpertNugget** [NillerMedDild/Enigmatica6#3352]
### Modpack Version

0.5.14

### Describe your issue.

![image](https://user-images.githubusercontent.com/73802442/135698627-29096e5f-daab-4aa2-846f-304f71d008b1.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by ExpertNugget** [comment]
Replacing the reaction chamber fixed it idk why tho

**Comment by RobuxShooters** [comment]
If you have lots of speed upgrades, consider adding energy upgrades too, or take out some of the speed upgrades. Energy consumption for the PRC is massively increased in this pack, so adding too many speed upgrades causes the required amount of energy used per tick to exceed the machine's energy buffer and cause it to not start.
