### ISSUE TITLE
RSInfinityBooster Infinite Range Card not working

### ISSUE THREAD

**Issue by Oreo735** [NillerMedDild/Enigmatica6#3353]
### Modpack Version

0.5.11

### Describe your issue.

So I finally crafted the Infinite Range Card from RSInfinityBooster mod for my Refined Storage setup, and suppled it with plenty of energy to sustain it,
however I get "There is no Wireless Transmitter in range" message when I'm more than 128 blocks away from the transmitter, I tried applying it to the transmitter on it's own and with additional 3 Range Upgrade that didn't work either, maybe I'm missing something or it is indeed a bug,
any help or fix would be much appreciated.       

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by RobuxShooters** [comment]
Did you chunkload your Wireless Transmitter and your energy setup that feeds into your Refined Storage network?
