### ISSUE TITLE
Chisel + Inventory Dupe

### ISSUE THREAD

**Issue by lumoize** [NillerMedDild/Enigmatica6#3354]
### Modpack Version

0.5.11

### Describe your issue.

This might have been fixed since this version, sincere apologies if it has. Found this playing on a server.

1) Select any item with the chisel (I used the smart chisel, unknown if others work), up to a stack
2) Click the extract inventory button
3) Item(s) are duplicated, fully working with all metadata copied

See gif for demonstration: https://gyazo.com/bd5a3a0e045ebb8fed4e9b1c7313a0da

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by RobuxShooters** [comment]
Duplicate of issue #3330.
