### ISSUE TITLE
Infinite exp bug with insightful crystal

### ISSUE THREAD

**Issue by Fredi355** [NillerMedDild/Enigmatica6#3356]
### Modpack Version

0.5.11

### Describe your issue.

Right click an insightful crystal on a sink completely fills it up with exp.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by RobuxShooters** [comment]
Sounds like a duplicate of issue #3290.

**Comment by Fredi355** [comment]
My bad didn't see it I will close this then.
