### ISSUE TITLE
[0.5.14] Portality Portal causes random crashes when going through them.

### ISSUE THREAD

**Issue by KacproPL132** [NillerMedDild/Enigmatica6#3366]
### Modpack Version

[0.5.14]

### Describe your issue.

Sometimes when going through Portality Portal it just crashes the game. Happend to me and few other friends few times in like hour or so. There is fair bit of a distance bettwen them (like 125km) so this could be something but. Worth reporting right :D?

### Crash Report

https://paste.ee/p/utsCN

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it.

**Comment by NillerMedDild** [comment]
Could you try reproducing this on 0.5.21 when it's out? :)

**Comment by KacproPL132** [comment]
Sure :D That shouldn't be a problem I think.
