### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by Delloid** [NillerMedDild/Enigmatica6#3370]
### Modpack Version

0.5.14

### Describe your issue.

Just after the game finishes loading it crashes before entering the title screen.

Somewhat strangely, if I try to open the modpack enough times it sometimes succeeds at loading the title screen without crashing.

### Crash Report

[crash-2021-10-03_19.53.00-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/7274289/crash-2021-10-03_19.53.00-client.txt)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. This can be fixed by updating the mod `MmmMmmMmmMmm`, I recommend you do so as 0.5.15 won't be out for a few days :)

**Comment by Delloid** [comment]
Thank you for the advice!
