### ISSUE TITLE
Missing chisel tags

### ISSUE THREAD

**Issue by Firefly0402** [NillerMedDild/Enigmatica6#3377]
### Modpack Version

0.5.14

### Describe your issue.

Some blocks can't be chiseled due to missing "chisel:xxxxx" tag. Like redstone blocks (don't have the "chisel:redstone" tag) or emerald blocks. Don't know if this is supposed to be like that and you're supposed to find already chiseled blocks in order to be able to chisel them yourself? Because using commands giving me an already chiseled block (that has the "chisel:redstone" tag) I can then put this block into the chisel and change it. 
First I thought it was a bug within the chisel mod so I created this: https://github.com/Chisel-Team/Chisel/issues/900
But now I think it's more of an issue within this modpack's settings or something. I'd appreciate anyone looking into this because I don't know much about this stuff. Thank you very much :)

### Have you modified the modpack?

Yes

### User Modifications

I have changed some things but they shouldn't be affecting this issue. The changes I've made:
- increasing max. slots for losttrinkets to 25
- increasing max. force loaded chunks to 100 (because we're only 4 people playing in the same team)
- disabling vanilla level limit in industrial foregoing enchantment applicator

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I'm pretty sure this issue is not caused by us, I'm guessing the way Chisel adds tags to it's own tags doesn't work. I could be wrong though, I've never seen that particular method before.

**Comment by Firefly0402** [comment]
I'm sorry if I falsely opened this issue here. Thank you for looking into it :)

**Comment by NillerMedDild** [comment]
No worries, I'd rather get a few extra tickets than miss a bug :P

**Comment by Firefly0402** [comment]
Love your attitude and how devoted you are about making this modpack a great experience for everyone. So far it's the modpack my friends and I are enjoying to play for the longest time now :3
