### ISSUE TITLE
When In Inventory and shift+clicking dismounts you

### ISSUE THREAD

**Issue by NetIsPrograming** [NillerMedDild/Enigmatica6#3382]
### Modpack Version

0.5.14

### Describe your issue.

Title says it all.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Cannot reproduce, possibly fixed by mod updates though :)
