### ISSUE TITLE
Several Neptunium pieces show recipes for smelting into Neptunium nuggets, but do not work

### ISSUE THREAD

**Issue by godefroi** [NillerMedDild/Enigmatica6#3383]
### Modpack Version

0.5.14 (1.16.5)

### Describe your issue.

For example, the Neptunium pickaxe and shovel (and possibly others). These recipes show in JEI, but do not work (the item cannot be placed into a Mekanism smelter or blast furnace).

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
I'm having no trouble smelting these down in a Vanilla Blast Furnace or a mek furnace in Dev. I suspect whatever caused this has already been fixed.

**Comment by MuteTiefling** [comment]
Actually, for that matter, I can't even reproduce this in 0.5.14. Would you mind trying to re-install?

**Comment by HeavyDeception** [comment]
@MuteTiefling I can't smelt these Items in the Blast or normal Furnace, I can only smelt them in the TE Furnace do they smelt. @godefroi Do you have optifine installed?
I have Optifne, Friendly Fire, Better than Mending, and Better F3.

**Comment by MuteTiefling** [comment]
@HeavyDeception Could you also try with a freshly installed and unmodified instance? godefroi has indicated they've added no mods.

**Comment by MuteTiefling** [comment]
While we're validating, you're really on single player and not a server, right?

**Comment by NillerMedDild** [comment]
I can't reproduce this either :/

**Comment by godefroi** [comment]
It works in a Thermal redstone furnace. It does not work in a vanilla blast furnace, and it doesn't work in a Mekanism elite smelting factory.

**Comment by MuteTiefling** [comment]
I'm legit stumped then. 

What launcher? OS? I've had super weird issues happen on GD launcher, for instance, that didn't happen on Curse. 

Also, is Java up to date?
