### ISSUE TITLE
Missing valid_apiaries tag list.

### ISSUE THREAD

**Issue by KaizoThom** [NillerMedDild/Enigmatica6#3384]
### Modpack Version

Enigmatica6-0.5.14

### Describe your issue.

When placing a Tier 1 apiary, it does not register any blocks as valid to be used in an apiary. Looking further, when going into the config files for the modpack (Enigmatica 6 - E6 - 1.16.5\config\resourcefulbees\resources\data\resourcefulbees\tags\) there is no valid_apiary.json file to be found, which should be present based on the default installation of Resourceful Bees.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by KaizoThom** [comment]
Should be noted - this is both after an upgrade from 0.5.11, and a complete fresh install - tried with two seperate instances.

**Comment by TemperedFool** [comment]
We never added tags via configs, we were using a KubeJS script. We've removed that as RBees now auto-detects valid blocks, so whether or not blocks appear tagged any solid blocks will work.

The only complication is fixed in-dev; we initially had to remove the tag from most stuff as ore chunks were getting tagged as valid (breaking tag-based automation). This produced the lack of tagging you are seeing in JEI, but the blocks should still work.

**Comment by KaizoThom** [comment]
Ah, this makes sense. It's very possibly a user error in this case - my apiary containment is made of oak logs, glass and grass for the floors, but a red block appears over all of them when enabling the validity check. Possibly an unrelated issue, but definitely not due to lack of tags if this is the case.

**Comment by theboo** [comment]
Correction... I will be fixing it in dev in about an hour lol

**Comment by TemperedFool** [comment]
Well fine then, I stand corrected! For some reason I thought you already pushed this... easy enough though.

**Comment by KaizoThom** [comment]
Ah, apologies! I was unaware, I will keep it open.
And yes! I can confirm that the apiary is the correct way round - using the visualisation feature shows the area that I had planned out is in the required field, but the blocks appear to be considered invalid (specifically vanilla glass, oak logs, an oak door and an always lit redstone lamp from quark).
