### ISSUE TITLE
Change the Quark config of the Trowel for unlimited uses.

### ISSUE THREAD

**Issue by HeavyDeception** [NillerMedDild/Enigmatica6#3390]
### Describe your suggestion

Changing the config of the Trowel to be unbraking.

### Why would you like this added/changed?

One of the most used items I use from Quark is the Trowel. But it has a really small durability when you using it to place thousands of blocks and if you going to [Add a Decorations quest tab}(https://github.com/NillerMedDild/Enigmatica6/issues/3344) I feel like it should be unbreakable and added to that tab as it is such a great tool.

**Comment by MuteTiefling** [comment]
It's already added to the deco quests ^_~ 

Personally not sure how I feel about making it unbreakable. They're exceptionally cheap as it is and resources aren't exactly difficult to come by in the pack. 

If you want a more robust version, you can use the Construction Wands. These have a random placement option too (taking items from your hotbar) and have higher durability. Even one that's unbreakable.
