### ISSUE TITLE
Enchanting Apparatus allows extracting during crafting, duping the item

### ISSUE THREAD

**Issue by Pix-egirl** [NillerMedDild/Enigmatica6#3392]
### Modpack Version

0.5.12

### Describe your issue.

a logistical sorter pulling from an enchantment apparatus with a filter for the item being put into the enchantment apparatus will repeatedly try to extract that item while it's being used, creating multiple duplicates. tested with creating warper relays while source relays were in the sorter's filter and with crafting sylph charms while sylph shards were being filtered

### Have you modified the modpack?

Yes

### User Modifications

I've added the mana and artifice mod and added a few ores to the occultism miner and crusher tables, none of which I think should cause this bug

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. Was able to replicate this easily with both Mekanism and Pretty Pipes extracting. Will relay to Ars Nouveau
