### ISSUE TITLE
Crafting Dense Construction Blocks in the Mekanism CIC is impractical

### ISSUE THREAD

**Issue by s0urdough** [NillerMedDild/Enigmatica6#3400]
### Describe your suggestion

I am currently playing E6 0.5.10, so this might have been changed in later updates. Currently, it takes 40,000 mB of Water Vapor or Steam to craft Building Gadgets' Dense Construction Block in the Mekanism Chemical Injection Chamber. This is much more expensive than vanilla concrete, which takes 200mB and has nearly the same mechanic for crafting in the world (placing water near the powder in order to harden the block). Decreasing the Water Vapor cost would ease crafting times massively, and wouldn't impact the material costs for the block at all, assuming water is automated. I suggest lowering the amount to at max 400-800mB, which would be more in line with the other recipes using Water Vapor.

### Why would you like this added/changed?

This is by far the most expensive recipe (as far as water vapor goes), costing 40 times the next most expensive CIC water recipes (rehydrating dead coral blocks, 1000mB). 

It requires a highly upgraded Rotary Condensentrator and maximum Gas Upgrades in order to automate in any reasonable amount, and is overall a slowdown in general.

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by NillerMedDild** [comment]
I believe it was a bug, apparently the gas amount in the recipe gets multiplied by 40 ^^'
