### ISSUE TITLE
Nebu Ore via Resourceful Bees

### ISSUE THREAD

**Issue by Firefly0402** [NillerMedDild/Enigmatica6#3407]
### Describe your suggestion

Would be nice to have a bee that can produce nebu ore (chunk). Like a cute little pharaoh bee or something :3

### Why would you like this added/changed?

ATM there's almost no resource you can't get from bees and there's almost a bee for every mod that can produce at least the mod's base resource. Would be really nice to have a bee to work with atum :)

**Comment by NillerMedDild** [comment]
@TemperedFool @MuteTiefling 
You're our Atum / Bee experts, what do you think? 😄

**Comment by TemperedFool** [comment]
We were discussing it last night on Discord; have some ideas. I think we'll probably avoid just straight up making nebu ore (for expert balance reasons), but I think we came up with a few ideas for an Atum bee.

**Comment by NillerMedDild** [comment]
An atum bee was added in #3765 :)
