### ISSUE TITLE
Travel Anchors

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica6#341]
https://www.curseforge.com/minecraft/mc-mods/travel-anchors

found this while snooping on curseforge, could be fun to include

**Comment by NillerMedDild** [comment]
Do you happen to know if Ender IO will be ported or not?

**Comment by Darkere** [comment]
They are still doing work on the 1.12 version. Not anytime soon.

**Comment by Merlo17** [comment]
From their discord pins:

EnderIO will be ported eventually, But there is only one person working on EnderIO and he doesn't want to port EIO alone, bc it's huge mod, So the other dev's have there own mods first, So don't expect EnderIO for 1.15.x and Future Version of minecraft includes other forge version past 1.13+ for awhile and won't be backported.

**Comment by NillerMedDild** [comment]
Alright, thanks!

**Comment by Merlo17** [comment]
Appears to be suffering from lighting issues right now on our server

https://imgur.com/a/vNQUI6w

**Comment by Darkere** [comment]
Do you have experimental Lighting Pipeline enabled Merlo?

**Comment by Merlo17** [comment]
I do yeah

```
#EXPERIMENTAL: Enable the Forge block rendering pipeline - fixes the lighting of custom models.
	experimentalForgeLightPipelineEnabled = true
	#Enable the Forge block rendering pipeline - fixes the lighting of custom models.
	forgeLightPipelineEnabled = true
```

Assuming it's that one

**Comment by NillerMedDild** [comment]
Reported to the dev :)

**Comment by Thiana** [comment]
This fix has been released for a while now. Any chance of pushing it to dev? Thanks.

**Comment by NillerMedDild** [comment]
It's not marked as 1.16.4 compatible, I'll update once that changes :)
