### ISSUE TITLE
Extreme Server/Client Lag After Accidental Nocturnal Dust Discharge

### ISSUE THREAD

**Issue by Subtle-Banshee** [NillerMedDild/Enigmatica6#3411]
### Modpack Version

0.5.14

### Describe your issue.

While I was working on the Astral Sorcery questline using a friend's setup on our server, I had Nocturnal Dust in my hand while attempting to use his teleportation array to get to the temple he made. As a result, I "used" the dust, which spread a large black cloud over our solar panels and my Nature's Aura shrine, and ever since, being in/near the area causes extreme lag on both the client and server side (the client of the person in the area lags, but not clients of people away from the area, but the server also goes through some stress while the client is there, just not enough so that it causes problems for others on the server).

The friend tried removing both dirt and solar panels from the area, in case the blocks glitched out, and it helped some, but when he put the solar panels back, the lag returned.

Is there a way for us to fix this "cursed" area, or will we have to just quarantine the area? Is it possible to "refresh" the world without losing all of our progress?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Subtle-Banshee** [comment]
The server owner will have to be the one running the command, so I'll get that link for you within the next day or so.

**Comment by NillerMedDild** [comment]
Sounds good, thanks!

**Comment by Subtle-Banshee** [comment]
When the server owner tries to run it in Minecraft, he says he doesn't have permission, despite being recognized as the owner. When he ran the command via the server console, he said that there were no links given.
