### ISSUE TITLE
Lithium crashing the game whenever I join my server

### ISSUE THREAD

**Issue by Cheremenin** [NillerMedDild/Enigmatica6#3413]
### Modpack Version

0.5.14

### Describe your issue.

A new issue surfaced in 0.5.14 (after updating from 0.5.11), and it seems to be related to the new mod Lithium.
Whenever I join my server now the game has a VERY high chance of crashing with either ticking entity or unexpected error. Sometimes I can join but most of the time it will crash instantly.
I've been told by someone who analyzed the logs that one of the issues could be connected to a blaze farm. There is indeed one where I spawn after joining. The unexpected error crash seems to be harder to track, though. And that one can happen at essentially any time - for example the last time I teleported into a friend's base I was only able to stay there for a few seconds before another unexpected error crashed my game.
Is there a fix besides removing either blaze industry or Lithium from my server?

Also, I run Optifine. No shaders at the moment, but Optifine is installed. Could it be adding to the issue?

### Crash Report

https://drive.google.com/file/d/121huYk5F_hCFavLISJFqtKED8Hb5oAwh/view?usp=sharing - example of Ticking entity

https://drive.google.com/file/d/12-iK3KxB7ZaNZxtFBbmO2iqq58iIC_mT/view?usp=sharing - example of Unexpected error

### Latest Log

https://drive.google.com/file/d/12-Pi8fr10PaH9Y_LvT-k9ryRPdnVdYHR/view?usp=sharing

### Have you modified the modpack?

Yes

### User Modifications

OptiFine HD U G8

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment]
Remove Optifine and retest please.

**Comment by NillerMedDild** [comment]
The launcher you're using (I'm guessing CurseForge) isn't picking up on that unfortunately, head into the Minecraft settings and select the correct one.

**Comment by Cheremenin** [comment]
> The launcher you're using (I'm guessing CurseForge) isn't picking up on that unfortunately, head into the Minecraft settings and select the correct one.

Huh, the more you know. So the official launcher that is used to launch modpacks from Curse could have been using some internalized Java versions of its own instead of actually running on the latest Java machine installed on my system the whole time?

Thanks, I have pointed the thing to use javaw from its installation folder. Maybe it will change something. Will test soon.

**Comment by ken-long** [comment]
> Interestingly enough I am seeing a pattern in my lag. The spikes happen when you turn most of the time. So you could run 50-100 blocks forward with stable, smooth FPS but then it would just grind down to 1 or begin micro-stuttering or freezing whenever you turn by 90 degrees. Even worse when turning full 180.
> 
> Edit: Yep, did some more testing and for some reason my game lags specifically when you look into different directions - which does not happen when using Optifine. Going to need to investigate that one further.

FWIW, 0.5.14 will boot with OF/OForge with RoadRunner updated to **1.2.2** -- I'm not sure if I'm secretly ruining my game as OF often does :) but that's alright -- maybe check it out if you've got a potato? I've had some decent success here -- I've also turned 'smart animation' on just now after reading this post, perhaps I'll get even more performance?


I also have FTBChunks disabled -- it was wrecking my performance when 0.5.14 first dropped -- less so updated to build 65 -- but overall my experience is smoother without it.
