### ISSUE TITLE
Expert Quest Line showing in normal E6!

### ISSUE THREAD

**Issue by Kanzaji** [NillerMedDild/Enigmatica6#3419]
### Modpack Version

0.5.15

### Describe your issue.

Expert Quest tab is visible... there is nothing else to say. It has no description on any of quests and no rewards... but it is there... only magic tho.
![obraz](https://user-images.githubusercontent.com/60540476/136981894-af3ed105-daa0-4c19-8954-09694d42f901.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by KacproPL132** [comment]
Another thing I saw and its a little related to this... New Bulding Quest line isn't visible as well! ~~And I think I know what happend there and why expert is visible~~

**Comment by NillerMedDild** [comment]
Oh boy, I need to step up my game a bit. Can't you find some easy bugs? :P

**Comment by KacproPL132** [comment]
All of the easy bits are taken from me before I found them... and I found hard ones bc of that.
