### ISSUE TITLE
Modded for Dummies fixes

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica6#342]
More a reminder for myself:
-with Xaero's gone I should change the entry in the Modded for Dummies book to talk about FTB instead.
-quests chapter also needs to be edited to now actually talk about them instead of just coming soon
-in general a chapter about all the FTB mods (ultimine, chunks etc.) could be very useful.
-Frikkle still needs to write the bugs and troubleshooting chapter :o poke him!

**Comment by Merlo17** [comment]
There also seem to be some weird blank spaces before bold and colored text now. Need to investigate that. Will do after I'm done with Powah Quests

**Comment by Darkere** [comment]
For formatting issues in Patchouli books, try without Emojiful. It's causing problems.

**Comment by NillerMedDild** [comment]
Formatting issue link: https://github.com/InnovativeOnlineIndustries/Emojiful/issues/8

**Comment by Merlo17** [comment]
#348 fixes this
I can also confirm that emojiful latest (version 2.1.1) fixes formatting
