### ISSUE TITLE
Immersive Engineering Mineral Deposit with Fluorite

### ISSUE THREAD

**Issue by ht67810** [NillerMedDild/Enigmatica6#3420]
### Describe your suggestion

An IE mineral deposit for the excavator containing fluorite. Not sure what other resources could go with it.

### Why would you like this added/changed?

Fluorite is one of the few ores you can't find using an IE excavator, which is a shame when you can get a large amount of the rest of the ores with the same setup

**Comment by MuteTiefling** [comment]
Hrm, short of adding a new type altogether, I'm thinking maybe either adding this to the already existing diamond node and reducing the basalt there...

or possibly adding it to the quartz node? That'd mean it could only be mined in the nether though.

**Comment by MuteTiefling** [comment]
alright. sounds good
