### ISSUE TITLE
Building quest without description!

### ISSUE THREAD

**Issue by KacproPL132** [NillerMedDild/Enigmatica6#3434]
### Modpack Version

0.5.16

### Describe your issue.

Some quests from Building Line doesn't have descriptions or have names of files probably that should be loaded in them. There is list of them and example!:
Example: 
![obraz](https://user-images.githubusercontent.com/60540476/137214732-53859c93-e643-471c-aadd-2802a076dccb.png)

List:
Its.. its actually just this one that is in Example... General Building Tools

~~You see Niller :D? There is something easy to fix x3~~

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Ridanisaurus** [comment]
Oops. Good call. I was indeed looking at the incorrect quest.
I had nothing planned for that quest section, but I'll push something for it later on today.
Sorry everybody :D
