### ISSUE TITLE
Custom Generation Lava Gen Not working with andesite.

### ISSUE THREAD

**Issue by HeavyDeception** [NillerMedDild/Enigmatica6#3437]
### Modpack Version

0.5.16

### Describe your issue.

When a block of andesite placed it does not spawn andesite.

### Crash Report

No crash.

### Latest Log

No Log.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment]
Can you post a screenshot of your generator?

**Comment by HeavyDeception** [comment]
Not the first time I have made this and it worked before. https://puu.sh/IioMt/da0f5382e7.png

**Comment by HeavyDeception** [comment]
https://puu.sh/IioRU/e17e05dfd3.gif

**Comment by HeavyDeception** [comment]
If you ponder on it it shows a cobble gen and how to make it.
