### ISSUE TITLE
Create has lost its ability to make bread.

### ISSUE THREAD

**Issue by HeavyDeception** [NillerMedDild/Enigmatica6#3438]
### Modpack Version

0.5.16

### Describe your issue.

Wheat Flour can no longer be turned into bread.

### Crash Report

No crash.

### Latest Log

No Log.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
welp, no clue where they got off too, but they'll be back next update
