### ISSUE TITLE
Magic Feather

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#344]
https://www.curseforge.com/minecraft/mc-mods/magic-feather/files/3043612

**Comment by NillerMedDild** [comment]
That didn't go great :P https://github.com/Ephys/CookieCore/issues/10

**Comment by kil0byt3** [comment]
If you use the previous version of CookieCore, the mod works with E6. The author seems to be busy IRL so I'm not sure a newer version of CookieCore will release anytime soon.

**Comment by NillerMedDild** [comment]
I'd rather not add a mod that requires a workaround just to not crash :P

**Comment by kil0byt3** [comment]
Fixed here: https://github.com/Ephys/CookieCore/issues/10

Update file: https://www.curseforge.com/minecraft/mc-mods/cookiecore/files/3158118

**Comment by kil0byt3** [comment]
Thanks for taking another look! To add to this - I've found [Configurable Beacons](https://www.curseforge.com/minecraft/mc-mods/configurable-beacons) to be helpful alongside Magic Feather - the default range of Vanilla beacons is quite restrictive for flight (especially on the vertical axis). 

With the right config changes this might be a fun "harder" Angel Ring replacement, but I leave the full implementation up to you :)
