### ISSUE TITLE
World Generation Issue: Random Stone Spikes

### ISSUE THREAD

**Issue by Erysch** [NillerMedDild/Enigmatica6#3442]
### Modpack Version

0.5.14

### Describe your issue.

World randomly generates huge stone spikes. I saw this happening in Singleplayer as well as in Multiplayer. 
You can see I used OptiFine: but this happens on the untouched server world as well. So OptiFine is no reason ;^)

![Base Profile Screenshot 2021 10 14 - 19 27 33 63](https://user-images.githubusercontent.com/81813584/137367428-b9d91b64-6d0b-419f-9dbd-cc3f0b5d987e.png)
![Jre-legacy Screenshot 2021 10 13 - 21 02 30 95](https://user-images.githubusercontent.com/81813584/137367352-76b95cf0-71d2-48a4-bb41-1867c7e3c117.png)
)
![Jre-legacy Screenshot 2021 10 13 - 20 56 16 57](https://user-images.githubusercontent.com/81813584/137367367-4ade790d-11e6-4d35-8ef6-f6703e6c2bb2.png)

Greetings! (:

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Erysch** [comment]
Aye thanks for the information

**Comment by theboo** [comment]
Yup both byg and terraforged add similar biomes to this... Modeled after these stone forests in China I believe 
![03](https://user-images.githubusercontent.com/3585761/137371945-bbe184f2-30aa-4822-a7f8-b6f3b714cb9a.jpg)

**Comment by Erysch** [comment]
Aah, cool stuff B-)
