### ISSUE TITLE
Waterlogged @Chipped lantern

### ISSUE THREAD

**Issue by MikeMikey200** [NillerMedDild/Enigmatica6#3443]
### Modpack Version

Enigmatica6-0.5.14

### Describe your issue.

Server crashed and when starting up again, the server is fine but only crashed when join. I have stated the issue on the FTB server and they have told me: "Water flowed into a chipped:special_lantern_1 and it tried to see if that block was waterlogged and failed :p report to the Enigmatica 6 github, they'll take care to send the error to the developer for fixing. As for now, most likely restore a backup if you can't join in and avoid using that block until the E6 devs solve it. Also visit their Discord, here it's for FTB modpacks!", so I assumed it was the @Chipped mod doesn't interact well being waterlogged.

### Crash Report

https://paste.feed-the-beast.com/view/7daf0bb4#L14

### Latest Log

https://paste.feed-the-beast.com/view/064df637

### Have you modified the modpack?

Yes

### User Modifications

I have added Carry On mod version 1.16.5-1.15.5.15

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Gabriel8579** [comment]
Fixed at https://github.com/WillowWorks/Chipped/pull/82
