### ISSUE TITLE
Advanced Rocketry / FuturePack

### ISSUE THREAD

**Issue by yoyotam3** [NillerMedDild/Enigmatica6#3449]
### URL

https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry

### Why would you like the mod added?

I just really want a space mod. Advanced rocketry for 1.16 seems like it isn't being focused on, but advanced rocketry seems a bit more polished than FuturePack, but either one works.

**Comment by BooBeerb** [comment]
Look at previous issues before requesting new mods. I believe Adv rocketry was declined exactly because it's unpolished and incomplete and blah blah.

**Comment by NillerMedDild** [comment]
We also really want a Space mod, but I don't think either AR or FuturePack are polished/complete enough to be added at the moment :)
