### ISSUE TITLE
More Enchantments

### ISSUE THREAD

**Issue by HeavyDeception** [NillerMedDild/Enigmatica6#3451]
### URL

https://www.curseforge.com/minecraft/mc-mods/more-enchantments_

### Why would you like the mod added?

There are some really good ideas for some enchants and as of right now you kind of blow through the ones that are in the game at this time. Need a nother reason to us xp.

**Comment by NillerMedDild** [comment]
I think we have more than enough enchantments as it is, no thank you :)
