### ISSUE TITLE
Immersive Engineering Sawmill Quest using wrong steel Scaffolding

### ISSUE THREAD

**Issue by HeavyDeception** [NillerMedDild/Enigmatica6#3461]
### Modpack Version

0.5.16

### Describe your issue.

When you make the scaffolding it doesn't detect it, you have to craft it on its self to get the correct stuff for the quest.

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, Quezler fixed it in-dev :D
