### ISSUE TITLE
`kubejs:alchemists_delight` item texture missing

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#3465]
### Modpack Version

0.5.16

### Describe your issue.

the icon for the `kubejs:alchemists_delight` is showing the missing texture in jei & quest rewards:
![Screen Shot 2021-10-16 at 13 46 56](https://user-images.githubusercontent.com/3179271/137586074-034b487c-99bf-46e8-89a9-73e489293e17.png)
![Screen Shot 2021-10-16 at 13 47 12](https://user-images.githubusercontent.com/3179271/137586075-04dcc406-546a-4334-9467-8cec4b57aeff.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment]
That sounds like a bad download? Check to see if you have the textures - they live at `kubejs/assets/kubejs/textures/items`, like the one below:

https://github.com/NillerMedDild/Enigmatica6/blob/master/kubejs/assets/kubejs/textures/item/alchemists_delight.png

**Comment by MuteTiefling** [comment]
that seems odd to me that they're all listed as `'kubejs:name#inventory'`...

**Comment by Quezler** [comment]
well i have no idea what exactly that means, but if i can be of any help debugging this let me know here or ping on discord 😋

**Comment by NillerMedDild** [comment]
Nice :D will close it for now, can always re-open if need be.
