### ISSUE TITLE
Mod Suggestion - MythicBotany

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#347]
**MythicBotany** is a mod that expands botania a little bit.
https://www.curseforge.com/minecraft/mc-mods/mythicbotany
https://www.curseforge.com/minecraft/mc-mods/libx (Lib)

**Comment by NillerMedDild** [comment]
I don't like the direction it's going.

Please do not suggest so many mods, it's tiresome to have to explain why I haven't added every other mod.

**Comment by Darkere** [comment]
Try posting them in discord so you can have a discussion with the players/team before officially submitting a suggestion here :)

**Comment by NillerMedDild** [comment]
I changed my mind :) I hope I wasn't too harsh.

**Comment by TGMax233Michael** [comment]
I really like your modpacks, especially when it is upgraded to 0.3.0. Thank you for accepting my suggestion. :D
