### ISSUE TITLE
Pondering about Dry rubber crashes your game.

### ISSUE THREAD

**Issue by GalaxinTM** [NillerMedDild/Enigmatica6#3473]
### Modpack Version

0.5.14

### Describe your issue.

Pondering about Dry rubber crashes your game after showing you that you can extract other fluids from logs.

### Crash Report

https://cdn.discordapp.com/attachments/458404635527610368/899199238687305728/crash-2021-10-17_10.31.55-client.txt

### Latest Log

https://cdn.discordapp.com/attachments/458404635527610368/899199654795821086/latest.log

### Have you modified the modpack?

Yes

### User Modifications

BetterPVP, Xaero's World Map and Optifine

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Please update, this was fixed in 0.5.15 :)
