### ISSUE TITLE
Add more armor loot options from Apotheosis bosses

### ISSUE THREAD

**Issue by RegulusImpact99** [NillerMedDild/Enigmatica6#3474]
### Describe your suggestion

Not sure when it changed but named bosses now only drop Botania, Immersive Engineering or Undergarden loot.  Please consider reverting them back to a few versions ago when the loot was better.

### Why would you like this added/changed?

None of the botania, ie, or undergarden gear is very good even the mythic stuff doesn't seem to be very useful. A few versions ago you could get some nice stuff.

**Comment by NillerMedDild** [comment]
Ah alright, forget I said anything then. 



....Gold for giggles?

**Comment by BooBeerb** [comment]
Yes, throw in cardboard armour!
