### ISSUE TITLE
Honey Bottle does not increase sugar when consumed

### ISSUE THREAD

**Issue by staviq** [NillerMedDild/Enigmatica6#3495]
### Modpack Version

0.5.16

### Describe your issue.

Honey Bottle does not increase sugar when consumed, contrary to the item description.

Honey Bottle item description says +7.5 Sugars, hovewer, drinking 10+ bottles of Honey sugar did not increase sugar levels at all ( the food button in the inventory ).

https://i.imgur.com/Vx1MV4X.jpg

Eating Bread does predictably increase Grains level.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Quezler** [comment]
drinking honey bottles whilst your hunger is full does not trigger any dietary changes 🐝

**Comment by staviq** [comment]
Ok i tested with more hunger and it works, my bad :)
