### ISSUE TITLE
Stonecutter Dupes

### ISSUE THREAD

**Issue by zzyzzyzzx** [NillerMedDild/Enigmatica6#35]
**Modpack version**
0.2.0

**Issue**
take a bone block and put it through the stone cutter to get 4 bones, take those 4 bones and put them back through the stone cutter for 16 bonemeal then craft a bone block with the bonemeal which leaves you with 7 bonemeal

**Comment by NillerMedDild** [comment]
Thanks for the report :D that is one easy dupe.

**Comment by NillerMedDild** [comment]
Made a pull request to fix it here: https://github.com/Rohzek/Actually-Useful-Stonecutter/pull/4

**Comment by NillerMedDild** [comment]
He just closed it, so I guess it's on purpose :s
I'll just fix it in the modpack then.
