### ISSUE TITLE
Resourceful bee, BEEHIVE and honeycombs.

### ISSUE THREAD

**Issue by xXDob3rManXx** [NillerMedDild/Enigmatica6#3502]
### Modpack Version

0.5.16

### Describe your issue.

1 - The honeycombs of the bee: Wasabee, Clockwork and Spelling, are not centrifuged by the machine. (FIXED UP)
2 - It does not allow the BEEHIVE to be upgraded and the apiary does not allow upgrade.
3 - There are bees that do not indicate how to get them, or the spaw or how to mutate them.

thanks greetings

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by xXDob3rManXx** [comment]
> Necesitas botellas para todos esos bloques de nido de abeja.
> 
> Eso es lo que dice JEI para los usos de esos bloques de panal.
> 
> Si no desea embotellar la miel de otros panales (presumiblemente va a su sistema RS), entonces querrá otra centrífuga que también reciba botellas.

I have a fluid panel which collects all the fluids released by the combs and does not require flasks

**Comment by atlgeek007** [comment]
For those honeycombs though, bottles are *required* for the centrifuge, as JEI will tell you, as the outputs are not fluids.
