### ISSUE TITLE
You cannot ultimine ore veins that span different stone types

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#3514]
### Modpack Version

0.5.16

### Describe your issue.

as can be seen on this screenshot, you cannot use ultimine to dig up the entire vein in one swing:
![2021-10-14_13 08 41](https://user-images.githubusercontent.com/3179271/138250171-d681b930-6820-423f-aab8-4302e2831f96.png)

but i did come up with a way to automatically solve this issue without having to add every forge:ores/ to the config:
https://github.com/FTBTeam/FTB-Ultimine/pull/95

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Quezler** [comment]
update: merged by @MaxNeedsSnacks a few days ago, currently awaiting a merge to the main branch & cf release 😇

**Comment by FireBoy00** [comment]
I know this is an old issue, but... how do I make it so it merges the deepslate variant of the ore with it's normal one?

**Comment by Quezler** [comment]
@FireBoy00 check your `ftbultimine-server.snbt` file for the prescence/absense of a tag like forge:ores/*.

**Comment by FireBoy00** [comment]
I have it like 
```
# These tags will be considered the same block when checking for blocks to Ultimine in shapeless mining mode
	# Default: ["minecraft:base_stone_overworld", "c:*_ores", "forge:ores/*"]
	merge_tags: [
		"c:*_ores"
		"forge:ores/*"
	]
```

I removed the `"minecraft:base_stone_overworld"` because I wanted andesite/stone/granite and the rest to be separated.

**Comment by Quezler** [comment]
now check with f3 both blocks of the same ore (but different stone) to see which (if any) tags they share

**Comment by FireBoy00** [comment]
Nvm... apparently it now works... Maybe I was just dum and did not see it before? Idk. Thanks for the help anyway and sorry to disturb :P

**Comment by FireBoy00** [comment]
Yeah, it shows it merges them. Both have same tag, but... if I mine the normal (stone ore) I get only the normal one mined. If I mine the other type (deepslate ore) I get both...

**Comment by Devilaux** [comment]
> Yeah, it shows it merges them. Both have same tag, but... if I mine the normal (stone ore) I get only the normal one mined. If I mine the other type (deepslate ore) I get both...

Same issues here. And they dont accept bug reports either, so going to find a different mod.
