### ISSUE TITLE
Otherworld goggles don't go into the goggles slot

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica6#3518]
### Modpack Version

0.5.16

### Describe your issue.

The otherworld goggles don't go into the goggle slot like the create goggles do.

Saw this issue: #1654 but maybe something got changed because it does not work.

P.S. see @Ridanisaurus I did the thing ;-)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
Tried adding these to the goggles slot, and while it does let us equip there when added, they still only function in the head slot. Reported to occultism to see if they are interested in adding support for this here:

https://github.com/klikli-dev/occultism/issues/487
