### ISSUE TITLE
Investigate Botania Additions

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#352]
https://www.curseforge.com/minecraft/mc-mods/botania-additions

**Comment by MuteTiefling** [comment]
Minor issue, but tagging here as well. https://github.com/ToMe25/Botania-Additions/issues/1

Mod seems fun. Small overlap with AIOT Botania (shovel) but the two other items it adds feel like nice additions. Especially Timeless Ivy, which lets anything be repaired with mana.
