### ISSUE TITLE
Please add Draconic Evolution

### ISSUE THREAD

**Issue by LuciusV** [NillerMedDild/Enigmatica6#3521]
### URL

https://www.curseforge.com/minecraft/mc-mods/draconic-evolution

### Why would you like the mod added?

I miss 9,223,372,036,854,775,807 energy storage so much

**Comment by BooBeerb** [comment]
No effort whatsoever! Just please add x, I want it, I am totally more important than balance and the fact that the mod is probably not even wanted! No reasons provided even!
