### ISSUE TITLE
Simple Farming not giving hearts 

### ISSUE THREAD

**Issue by Smoogles** [NillerMedDild/Enigmatica6#3531]
### Modpack Version

Enigmatica 6 - E6 - 1.16.5 (Forge 36.2.4) (mc 1.16.5)

### Describe your issue.

When eating new food, Simple Farming normally gives hearts for certain food. It says 'Eaten: Assisted in Adding Hearts' but not actually giving me the hearts. So far have at least two foods that should give hearts but still normal health bar.
![Hearts](https://user-images.githubusercontent.com/50223826/138383374-52a412f5-227d-4d8a-8318-3239fbce8d53.jpg)

Could find on wiki or issues, sorry if I couldn't see it. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
Simple farming is not the mod adding hearts for food, it is `Spice of Life: Carrot Edition`, and you don't get hearts for every food eaten, you get one heart for every 25 unique foods you have eaten maxing out at 10 hearts gained from food in the latest versions of e6.

When you eat a unique food, it will give that message saying it assisted in adding hearts meaning it assisted in counting towards your next heart from eating unique foods.

You can check the `Food Book` from SOL:CE to see your progress :)

also, the minecraft and forge versions are not the pack version, currently the latest version of e6 is 0.5.17
