### ISSUE TITLE
PneumaticCraft Error "Not Enough Refineries"

### ISSUE THREAD

**Issue by Valirius** [NillerMedDild/Enigmatica6#354]
![Screenshot 2020-11-05 09405223](https://user-images.githubusercontent.com/22143019/98206713-6c01d600-1f4b-11eb-8fd8-ded8f73af456.jpg)
![Screenshot 2020-11-05 094053](https://user-images.githubusercontent.com/22143019/98206718-6efcc680-1f4b-11eb-85e7-17045a17e70d.jpg)

**Modpack version**
E6 0.2.17

**Issue**
I cannot understand what is the matter. I think that somehow the mod is not working correctly.

Error on the controller that the refineries are missing. Although I hung them around the controller like a Christmas tree

I tried to make a tower from behind and from above.

**Comment by MuteTiefling** [comment]
Those are the wrong blocks. You're putting ThermoPneumatic Processing plants when you need Refinery Outputs as shown below.

![2020-11-05_14 55 06](https://user-images.githubusercontent.com/9543430/98289936-e98f0b80-1f76-11eb-83b6-a821e58d83f5.png)

That's the basic structure. Oil goes in the Controller at the bottom, your 4 outputs come out the top in their own separate output. You need to insulate them as well to keep your heat in. Insulation is done by putting any non heat transmitting block on each face. The easiest/cheapest option is usually trap doors, but you can use the mod's own Thermal Lagging for the purpose too. 

Pipes also insulate, so you'll be able to use whatever pipes you like for automation.
