### ISSUE TITLE
Lootr not replacing quark chests in The End.

### ISSUE THREAD

**Issue by HeavyDeception** [NillerMedDild/Enigmatica6#3553]
### Modpack Version

0.5.17

### Describe your issue.

Heading says it all.

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Where did you find a chest that wasn't replaced? I haven't been able to find any.

**Comment by HeavyDeception** [comment]
The end.

**Comment by NillerMedDild** [comment]
..Right.. Please be more specific.

**Comment by HeavyDeception** [comment]
The towers and end ships did not have the loots chests.

**Comment by NillerMedDild** [comment]
Can't reproduce I'm afraid, all I'm seeing is Lootr.

![image](https://user-images.githubusercontent.com/21295394/139556661-bcc8c8fa-3e82-494a-8891-39b119ff5891.png)

**Comment by HeavyDeception** [comment]
odd I will try to load another end city and see what's happening.

**Comment by HeavyDeception** [comment]
Just made a new world and it's not happening to this one. I apologize on my single-player game the first 2 I found the lootr was not working but it looks fine now.

**Comment by HeavyDeception** [comment]
must have been a glitch or something when loading that chunk
