### ISSUE TITLE
item frames refuse to accept items

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#356]
**Modpack version**
`Enigmatica6-0.2.17`

**Issue**
cannot put anything inside vanilla itemframes.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Huh, that's odd. I'll check it out :)

**Comment by NillerMedDild** [comment]
What about if you hold shift? and make sure the item frame is "targetted" like this:
![billede](https://user-images.githubusercontent.com/21295394/98412882-014eb880-2079-11eb-8a67-8442f5cfac43.png)

**Comment by Quezler** [comment]
> What about if you hold shift?

doesn't really change anything

(also, while on the subject of shifting, trying to dismantle ae2 stuff with a wrench sometimes simply doesn't work randomly)
