### ISSUE TITLE
Abnormals Delight Meals Can't be Crafted

### ISSUE THREAD

**Issue by Subtle-Banshee** [NillerMedDild/Enigmatica6#3587]
### Modpack Version

0.5.16

### Describe your issue.

Looking through the Food Book, there are Abnormals Delights meals listed as being some of the foods that we can eat, but according to the JEI, they can't actually be crafted. I'm using Cooked Venison Shanks for my example, but it includes things like Banana Cake and Apple Pie, among many others.
![Abnormals](https://user-images.githubusercontent.com/91931913/138980874-7b03a5e3-6a49-454e-b4d1-dc6185bcf256.PNG)
![JEI](https://user-images.githubusercontent.com/91931913/138980893-19b03671-263f-40ec-a81f-d422ef69a11c.PNG)
![Cooked Shanks](https://user-images.githubusercontent.com/91931913/138980910-eb5b911f-be29-4dc7-961a-d7ab9b571fb0.PNG)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
It seems like we've disabled those foods, but not the spice of life entries ^^'

**Comment by Subtle-Banshee** [comment]
Ah, okay. Just trying to get all the meals eaten, lol.
