### ISSUE TITLE
Mod Suggestion - Framed Compacting Drawers

### ISSUE THREAD

**Issue by eutropius225** [NillerMedDild/Enigmatica6#359]
Framed Compacting Drawers is a mod that adds Framed (Compacting and other) Drawers that are tragically missing from Storage Drawers on 1.16.
https://www.curseforge.com/minecraft/mc-mods/framed-compacting-drawers

**Comment by NillerMedDild** [comment]
Sure, I'll cave :P

**Comment by eutropius225** [comment]
Believe it or not there's already a newer version ^^'

**Comment by NillerMedDild** [comment]
Say, how does one actually apply textures to the Framed Drawers? I see no framing table.

**Comment by eutropius225** [comment]
There's a crafting table recipe for it, as shown on the mod page.

**Comment by NillerMedDild** [comment]
Ahh, thanks!
