### ISSUE TITLE
Hide unobtainable trinkets from jei

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica6#3601]
### Describe your suggestion

hide all the lost trinkets we have in the random unlock blacklist and disabled list outside of magical feathers.

### Why would you like this added/changed?

We get a lot of people asking how to craft these trinkets and I keep forgetting to do this when I get home lol

**Comment by MuteTiefling** [comment]
Forgot I already took care of this: 192b893864666d34923fa8aa988d2e6f3d242e2b
