### ISSUE TITLE
Concealment Key from Storage Drawers has no recipe 

### ISSUE THREAD

**Issue by ghostie69** [NillerMedDild/Enigmatica6#3605]
### Modpack Version

0.5.16

### Describe your issue.

Cannot craft concealment key, it is important for that key to exist because too many unconcealed drawers cause major fps drop.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
I'll get that fixed, thanks for reporting!

**Comment by NillerMedDild** [comment]
Fixed in-dev 👍 
![image](https://user-images.githubusercontent.com/21295394/139501249-157a4771-08a7-4e60-9b0c-5d3077a1a654.png)

**Comment by ghostie69** [comment]
thank you! i love you and your development and discord team!

**Comment by theboo** [comment]
Fyi we don't like to close issues before they make it in to an actual release, helps us keep track of what is fixed in release vs just fixed in dev :)

**Comment by ghostie69** [comment]
alrighty!
