### ISSUE TITLE
Botany pots not allowing seeds to be planted

### ISSUE THREAD

**Issue by dontsavethesehoes** [NillerMedDild/Enigmatica6#3611]
### Modpack Version

0.5.17

### Describe your issue.

When using botany pots, I am unable to plant any kind of seeds/saplings (both vanilla & modded) even with the proper soil inserted. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Quezler** [comment]
mind hopping on the discord? it will probably be easier to troubleshout it there vs chatting on github i suppose 🤔
