### ISSUE TITLE
Mob Farming

### ISSUE THREAD

**Issue by afolk2** [NillerMedDild/Enigmatica6#3612]
### URL

https://www.curseforge.com/minecraft/mc-mods/woot

### Why would you like the mod added?

It would be nice to have a mob farm without spawning mobs. I would have loved to suggest Deep Mob Learning, but it's for 1.12 and the Refabricated version is only for fabric. I'm just not a fan of having spawners setup for mob farms and, unless I'm missing a mod that already does this in the pack, there is no option to do that.

**Comment by Quezler** [comment]
previously suggested & rejected i'm afraid: https://github.com/NillerMedDild/Enigmatica6/issues?q=is%3Aissue+woot

**Comment by theboo** [comment]
Ars nouveau drygmies are an option for mob farms without spawning a bunch of mobs to kill... They pull from the loot tables of mobs around them without hurting or killing them
