### ISSUE TITLE
Crash on World Load Farmer's Delight and Industrial Foregoing - Can't Load World

### ISSUE THREAD

**Issue by DizzyDJW** [NillerMedDild/Enigmatica6#3616]
### Modpack Version

0.5.17

### Describe your issue.

Game crashed now am unable to load same world without instant crash to desktop with no launcher error.

### Crash Report

https://pastebin.com/RTHwZGXU

### Latest Log

https://pastebin.com/iYJNEtSQ

### Have you modified the modpack?

Yes

### User Modifications

Added back RFTools Dimensions, unrelated to crash

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Pretty sure this is fixed by Farmer's Delight already. Can you update that one mod and see if you're able to load the world again?

**Comment by DizzyDJW** [comment]
That fixed it! New crash problem now will make new issue
