### ISSUE TITLE
Map Crash to Desktop

### ISSUE THREAD

**Issue by DizzyDJW** [NillerMedDild/Enigmatica6#3617]
### Modpack Version

0.5.17

### Describe your issue.

Opening map freezes game then crashes to desktop

### Crash Report

https://pastebin.com/BXjD1wDk

### Have you modified the modpack?

Yes

### User Modifications

RFTools Dimensions Re-added

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Duplicate of #2922

To fix the crash, delete `/world/ftbchunks` from the server :)
