### ISSUE TITLE
YUNG's Better Dungeons

### ISSUE THREAD

**Issue by dudeloony** [NillerMedDild/Enigmatica6#3618]
### URL

https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons

### Why would you like the mod added?

It adds 3 new dungeons (Catacombs, Fortresses of the Undead, and Spider Caves) that replace vanilla dungeons.
I feel like it would add a fairly simple enhancement to vanilla dungeons and improve caving in general. Also, you know Yung's stuff is really consistent in both quality and performance. I could see an argument that it is more demand on cpu (for worldgen) than it's worth, but I'd like to hear your thoughts; you know much more about hardware demands than I do.
(Also, I believe Quark may have a similar structure to replace vanilla dungeons already, even if Quark's are a bit less engaging than these ones.)

**Comment by NillerMedDild** [comment]
I'm afraid I won't add any more Yung mods as long as we're using TerraForged, we've seen too many weird issues between them in the past :/ 

But for the record, I think the mod looks great and I would've added it when it was released if we were not using TF.
