### ISSUE TITLE
applied energistics crystal conversion issue

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#362]
**Modpack version**
`Enigmatica6-0.2.17`

**Issue**
applied energistics molecular assemblers cannot change charged certus quartz back to the emendatus variant:

![Screen Shot 2020-11-07 at 12 53 34](https://user-images.githubusercontent.com/3179271/98440336-78776180-20f8-11eb-9855-95b4146e28cd.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Quezler** [comment]
and neither the other way around apparently:

![Screen Shot 2020-11-07 at 13 21 37](https://user-images.githubusercontent.com/3179271/98440953-32240180-20fc-11eb-923e-3339777a935a.png)

**Comment by NillerMedDild** [comment]
Fixed in next release, because we're removing AE :)

**Comment by Quezler** [comment]
what's the underlying reason for removing ae2? the pack does have refined storage but automating ae2 is preferable 🤔

**Comment by NillerMedDild** [comment]
That we don't need 2 digital storage mods, support for Refined Storage is very good, and the contributors to E6 greatly prefer RS. And to try new things for my sake :D

**Comment by Quezler** [comment]
i completely agree, looking forward to whenever the next release will drop! ❤️
