### ISSUE TITLE
Integrated Additions log spam with key unbound

### ISSUE THREAD

**Issue by MisterWuff** [NillerMedDild/Enigmatica6#3622]
### Modpack Version

Enigmatica 6 v0.5.17  Using Forge-1.16.5-36.2.4

### Describe your issue.

Upon changing the key binding for 'show variable card relation' to anything but the default left alt, an error message gets posted into the logs indefinetely until switched back to default value.

 Error Message: [Render thread/ERROR] [minecraft/MainWindow]: ########## GL ERROR ##########
[17:14:01] [Render thread/ERROR] [minecraft/MainWindow]: @ Render
[17:14:01] [Render thread/ERROR] [minecraft/MainWindow]: 65539: Invalid key -1

### Latest Log

https://drive.google.com/file/d/1JA1k-jDJ7TuwV-Gl4If7Ar72ANVQMSI5/view?usp=sharing

### Have you modified the modpack?

Yes

### User Modifications

I disable catjammies and emojiful upon first opening the mappack for unnecesarry bloat. I also tried to disable journeymap and journeymap integrations as a possible solution after first error occurence before i pinpointed the issue in the keybindings.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Nice and easy to reproduce, I've relayed it 👍
