### ISSUE TITLE
Enigmatica 6 server pack 0.5.17 has leaked expert recipes

### ISSUE THREAD

**Issue by glubo** [NillerMedDild/Enigmatica6#3625]
### Modpack Version

0.5.17

### Describe your issue.

If i use a server pack of e6 0.5.17 downloaded from curseforge, I see expert recipes even when I have `normal` selected in `mode.json`.

Encountered on existing docker (`itzg/minecraft-server:java11`) server with  existing world. Reproduced on a fresh locally runed server with `start-server.sh` from the zip.

Examples of items with an expert recipe: 
- Terrasteel leggins
- Rune of capacity
- Gaia Mana Spreader
- Assembly Laser
- Runic Altar
 - ... ~60+ recipes according to JEI usage of "Altered Recipe" item
 
 Client zip file does not show this issue when starting a single player world.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll investigate the issue asap :)

**Comment by NillerMedDild** [comment]
Found the issue and fixed it, I'll hotfix :)

**Comment by glubo** [comment]
Backporting https://github.com/NillerMedDild/Enigmatica6/commit/f5cf02d0b35b8e490c4f074227d91a00eb125aa9 to my 0.5.17 server seems to resolve the issue and no more expert recipes. Thanks a lot for a quick fix.

**Comment by NillerMedDild** [comment]
My pleasure, thanks for the confirmation 👍
