### ISSUE TITLE
FTB Chunks doesn't render the "hat"

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#3627]
### Modpack Version

0.5.18

### Describe your issue.

for several versions now (never worked on any 1.16.5 pack afaik) the head2/hat skin overlay doesn't render:

![2021-11-01_21 26 03](https://user-images.githubusercontent.com/3179271/139737540-69dc2f61-7185-49d4-9906-bab837337cac.png)

me with my ears: (notice how they're not pink here)

![2021-11-01_21 26 23](https://user-images.githubusercontent.com/3179271/139737558-77394711-cd03-4e05-9b0a-1c02e9f73dd5.png)

it's simply mildly annoying when you need to open that map to claim chunks & seeing your own skin misrepresented.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Would you mind reporting this to https://github.com/FTBTeam/FTB-Mods-Issues/issues? :)

**Comment by Quezler** [comment]
should be fixed when the above pull request gets merged & released ^

**Comment by Quezler** [comment]
can be labeled as fixed in next release: https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files/3514173
