### ISSUE TITLE
Neptunium bow with endless quiver shooting shulker arrows causes infinite levitation

### ISSUE THREAD

**Issue by glaive120** [NillerMedDild/Enigmatica6#3629]
### Modpack Version

0.5.14

### Describe your issue.

should all be in the title but the timer on levitation doesnt go past 00:00

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
This doesn't happen on 0.5.19, so I believe this issue has been fixed at some point :)
