### ISSUE TITLE
Environmental Kiln Time to Bake Incorrect

### ISSUE THREAD

**Issue by tipmon** [NillerMedDild/Enigmatica6#3633]
### Modpack Version

Enigmatica 6 0.5.17

### Describe your issue.

The Kiln block from the mod Environmental is slower than it should be. I noticed with sand -> glass but didn't bother timing it. I was smelting nether bricks from netherrack and noticed it was very slow again. Timing it a couple times showed a per item baking time of approximately 13 seconds when it should be 5 seconds per JEI recipes and as standard for the specialized smelting blocks (smoker and blast furnace from vanilla).

I thought this might be an issue with the tick rate on my server but was unable to get anyone in the discord to double check the values in their own instances to confirm.

### Have you modified the modpack?

Yes

### User Modifications

Minecolonies-1.0.85-ALPHA-universal, Structurize-0.13.252-ALPHA-universal, and Ironshulkerboxes-1.16.4-5.1.11.jar. None of them should interact with the Kiln from Environmental. All configs are default from the server files provided.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
This seems to be caused by Polymorph: https://github.com/TheIllusiveC4/Polymorph/issues/69
