### ISSUE TITLE
Mekanism advanced -> elite factory recipe exists

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#3634]
### Modpack Version

0.5.19

### Describe your issue.

only the advanced to elite crafting recipe shows up, other tiers cannot be crafted at all: (to enforce in-world upgrades?)
![Screen Shot 2021-11-02 at 11 20 19](https://user-images.githubusercontent.com/3179271/139829013-c988944b-e731-40c8-aeb9-7985e907b378.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
I swesr I got those...

**Comment by MuteTiefling** [comment]
Had the removals in the wrong script. Sorry!

**Comment by Quezler** [comment]
no hard feelings, initially made the issue since it looked like even the base factories were uncraftable, it's actually sorta an improvement to have to use the upgrade installer cards 100% of the time 😋
