### ISSUE TITLE
Occultism summon endermite purple chalk bypass

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#3637]
### Modpack Version

0.5.19

### Describe your issue.

in order to get purple chalk you need some endstone dust, so you can summon an endermite that drops endstone.

however the questbook puts purple chalk as a requirement for summoning the endermite, despite not using purple.

also the advancement (endermite) unlocks only after getting the purple chalk, so perhaps it's a mod progression issue as well? (did enigmatica or occultism chance the purple chalk recipe? did the required pentacle change?) 🤔 

![2021-11-02_13 12 29](https://user-images.githubusercontent.com/3179271/139911490-db348eb9-a677-447c-8262-40d9adcef566.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
Endermite may have changed rituals? Weird...... Also none of the hidden advancements should need anything prior to unlock, they are there purely for pack dev and quest making

**Comment by Quezler** [comment]
ah, i guess the quest didn't do the advancement check before the purple chalk was claimed, guess i mistook it unlocking as an advancement toast instead of an ftbquest toast 👍

**Comment by MuteTiefling** [comment]
If the problem is just that you don't need the end chalk to get this, it's been like that for ages in the mod. I always kind of assumed it was intended, actually, as an alternate way to get to the purple chalk.

**Comment by MuteTiefling** [comment]
Oh, nevermind. I see we have the wrong pentacle compared to base occultism
