### ISSUE TITLE
Sophisticated bowls

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#3638]
### Modpack Version

0.5.19

### Describe your issue.

if you have stacked food (that returns a bowl when eaten) in your backpack with a feeding upgrade the bowl will appear in your main inventory instead of somewhere (else) in the backpack, only the last item from a stack stays in place.

issue spotted before, but reproducible with e.g. squid ink pasta from farmer's delight: (inv. bowls already removed)
![2021-11-02_18 03 25](https://user-images.githubusercontent.com/3179271/139912104-a49249bf-5153-4e6c-b9d6-b34215aa8e94.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Would you mind reporting this yourself? :x 
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues

**Comment by Quezler** [comment]
> This can't be fixed without adding support to forge for both the stack that's eaten from and container to be returned at the same time.
At this point any item that can stack and has container needs to add the container to player's inventory if it's not eaten fully yet. The other potential option would be to hack this logic into the method that handles putting items in player's inventory and potentially breaking other mods or if broken breaking stuff like player picking up items. Honestly both of these are significant changes for something as small as a few container items ending up in player's inventory so I am not planning to "fix" that.

**Comment by NillerMedDild** [comment]
Alright 👍
