### ISSUE TITLE
making the chapter-start checkbox quests optional

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#3641]
### Describe your suggestion

Currently each time i start a new game with my friends i'm often the one to go through all the chapter quests to click their checkboxes, this is since some of the players on the team "forget" to do so before starting a mod, which basically results in ftbquests not keeping track of the progression, and in order to actually complete the quests we'd have to check the checkbox and then pickup all the blocks/items in order so the questing tree does properly reflect what we have.

Also its a bit of a shame that so many of the chapter quests reward xp, if you claim it early on losing it through death is basically guaranteed, so what happens is that i don't use the claim all and will see the red exclamation points for each of them until i finally get enough of them & claim all quests, and inevitably dying and losing all that xp anyways.

(That & waiting for refined storage being up so all the quest rewards don't need several double chests of space)

### Why would you like this added/changed?

Would streamline the pack a bit and avoids having to backtrack quests.

**Comment by Wishbone1977** [comment]
I do the same. I have tons of quests with unclaimed rewards because I don't want that XP until I have some way to store it. The solution might be to either drop some sort of XP storage as a quest reward early on, or simply make an early quest line for making an XP storage solution. The problem is not so much the XP rewards as the lack of XP storage early on.

**Comment by NillerMedDild** [comment]
Excellent idea. I would prefer to replace the checkbox quests with an entry quest that actually requires an item that starts the mod, but this is a nice step 1.
