### ISSUE TITLE
Thermal Series: Insightful Crystal will accept any fluid as xp fluid

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#3645]
### Modpack Version

0.5.14 via curseforge

### Describe your issue.

Insightful Crystal doesn't care what fluid it absorbs, it'll treat it as fluid xp.

Easiest and most striking way to reproduce this: Right click an empty Insightful Crystal on a Cooking For Blockheads sink. Fills it to 100% because the sink has unlimited water.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Duplicate of #3356
