### ISSUE TITLE
Refined Storage

### ISSUE THREAD

**Issue by ThaMonsta** [NillerMedDild/Enigmatica6#3647]
### Modpack Version

0.5.14

### Describe your issue.

the Infinity and dimensional cards don't work when either of them is placed in the rs system access point for cross-dimensional support of accessing the system to retrieve items or use it at all.  went into the nether and couldn't take out anything, went to spawn and the same thing happened, however, the infinity card works fine alone. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Did you chunkload it? Can you supply enough power to sustain it? Is your energy generation chunkloaded?
