### ISSUE TITLE
Pumpkin pie has a recipe a lot easier than the other 

### ISSUE THREAD

**Issue by Rafael-RD** [NillerMedDild/Enigmatica6#3648]
### Modpack Version

0.5.17

### Describe your issue.

The second recipe is added by atum

![image](https://user-images.githubusercontent.com/89175493/140001511-3ca62314-9e91-45dc-b813-99e3e832376c.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
We'll get that fixed, ty :)
