### ISSUE TITLE
Thermal integral component quest should not have the induction smelter as a requirement

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#3654]
### Modpack Version

0.5.20

### Describe your issue.

you can obtain the hardened integral components without the induction smelter (which is a quest requirement):

![2021-11-03_16 32 48](https://user-images.githubusercontent.com/3179271/140092063-83a0077c-3922-4d15-8b90-8db331d24dc8.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
True enough. I guess I thought they needed hardened glass already at that stage.
