### ISSUE TITLE
Mekanism Sorter

### ISSUE THREAD

**Issue by FooterMan14** [NillerMedDild/Enigmatica6#3658]
### Modpack Version

0.5.17 (could be in later versions)

### Describe your issue.

When changing the filtered output of the Logistical Sorter (Mekanism) can sometimes crash the game. This could be a bug on their side. I have repeated the process 10 times and 3 times the game crashed.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by FooterMan14** [comment]
These are the only crash reports that appear, none of them are correct
![image](https://user-images.githubusercontent.com/71946346/140173464-3acab37d-cbe2-44d9-9279-31c2bf0738a1.png)

**Comment by FooterMan14** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7470045/latest.log)
I guess that works

**Comment by NillerMedDild** [comment]
There's no crash in there I'm afraid.

**Comment by FooterMan14** [comment]
Sorry, I don't really know what to do to show the crash(s)

**Comment by FooterMan14** [comment]
Okay, right on it.

**Comment by NillerMedDild** [comment]
No worries, glad it's not crashing so far 😄
