### ISSUE TITLE
Sophisticated Backpacks Auto-Feed not working

### ISSUE THREAD

**Issue by Accurian** [NillerMedDild/Enigmatica6#3661]
### Modpack Version

0.5.20

### Describe your issue.

The upgrade just doesn't work when you slot it into your backpack. I've tried re-equipping the backpack, turning the upgrade off and on, trying the basic version as well as the advanced one, and nothing works.

TLDR: Auto-feed broken in Sophisticated Backpacks.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report.

Silly question, but you placed food inside the backpack right? Which kind of food?

**Comment by Accurian** [comment]
> 
> 
> Thanks for the report.
> 
> Silly question, but you placed food inside the backpack right? Which kind of food?

Glad you asked a silly question, because the food was in fact not inside. I could have sworn it worked outside of it at one point.
