### ISSUE TITLE
Wither skull fragment recipe issue

### ISSUE THREAD

**Issue by StarBanger69** [NillerMedDild/Enigmatica6#3666]
### Modpack Version

0.5.20

### Describe your issue.

The wither skull fragments from the wither skeleton tweaks mod are not crafting into a full skull. The pack even erased the recipe I had set up for it in 0.5.19, where it did work. 

### Have you modified the modpack?

Yes

### User Modifications

I updated the version of farmers delight. 

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
I'm afraid I can't reproduce this in Dev or in 0.5.20. 

You don't see this recipe at all? 

![image](https://user-images.githubusercontent.com/9543430/140564314-6e0f2592-a956-4c78-9f45-9e8f9e4262be.png)

I've tried in RS grid, tinkers, and a vanilla crafting bench. Are you using any particular crafter?

**Comment by StarBanger69** [comment]
that...is strange. No, I cannot see that recipe at all. I'm using the refined storage crafting grid, and portable crafting grid bot
![2021-11-05_14 41 15](https://user-images.githubusercontent.com/39132142/140564812-4ee268e0-da13-476c-83b2-52fecb13d95e.png)
h.

**Comment by StarBanger69** [comment]
Just to make sure I also did it in a crafting station from tinkers, and that didn't work either

**Comment by MuteTiefling** [comment]
Would you be able to delete your `wstweaks-common.toml` file and let it regenerate? 

We aren't shipping this config, but I'm wondering if maybe yours got messed up somehow.

**Comment by StarBanger69** [comment]
I assume I am going to have to shut down the game to do that one?

**Comment by MuteTiefling** [comment]
You got it :D

**Comment by StarBanger69** [comment]
alright, world is loading again. will be about 15-20 minutes. Then I can give you the answer.

**Comment by StarBanger69** [comment]
okay, and now the recipe is back...sigh. thanks Tiefling lol

**Comment by MuteTiefling** [comment]
huzzah!
