### ISSUE TITLE
JEI as for the Configured mod to be installed, which is in the pack already.

### ISSUE THREAD

**Issue by soepie7** [NillerMedDild/Enigmatica6#3667]
### Modpack Version

0.5.20

### Describe your issue.

When clicking the configure button in JEI, bottom right of the UI, I get a message that says this:

> Install the "Configured" mod to access the in-game config

The pack already contains configured-1.2.0-1.16.3.jar

I wanted to access the configs to remove the prefix-requirement on mod name searches, but even though this is already set that way in jei-client.toml, it still needs an @-prefix.

The latest.log exceeded Pastebin's filesize limit by being 5 MB.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Looks like there might be an update that fixes this:
https://github.com/mezz/JustEnoughItems/issues/2552

**Comment by soepie7** [comment]
Will do, give me a moment.

**Comment by soepie7** [comment]
Tested with the lastest version, jei-1.16.5-7.7.1.130.jar, which is also the only version higher than E6's:

It works, however, the config I was after still doesn't function.
