### ISSUE TITLE
[Suggestion] Make Scoria/Jasper/Slate chiselable

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#3668]
### Describe your suggestion

Create Scoria can be freely switch between multiple variants (like Bricks) in the Stonecutter. It would be nice if they could be also switched with any of the Chisels for convenience.

EDIT: Looks like Jasper and Slate are in a similar case, can be freely Stonecut between their variants but not Chiseled.

### Why would you like this added/changed?

It adds convenience and consistency with the other stones like Marble that can both be switched in the Stonecutter and with Chisel.

**Comment by NillerMedDild** [comment]
Sure thing 👍

**Comment by MuteTiefling** [comment]
Took a brief look at this and I'm not 100% sure how chisel is registering what blocks can chisel. Seems like it might be tag based but my first few tests were failures. Will keep looking at it though.

**Comment by MuteTiefling** [comment]
Ok, ran some more tests tonight and it really just seems you can't make your own categories. I can easily add blocks to the existing categories like `chisel:redstone` but creating and populating an item/block tag of `chisel:slate` doesn't work

On the plus side, Portable Stonecutter at least shares the mass chisel feature (chisel all blocks in your inventory in one shot) so it's quite handy for mass conversion.

**Comment by NillerMedDild** [comment]
Myeah you're right, we can't do this :/
