### ISSUE TITLE
BYG Scoria Stone can't be switched back to Create Scoria

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#3669]
### Modpack Version

0.5.17

### Describe your issue.

Create Scoria generates in the world. In the Stonecutter, it can be turned into its variants, but also into Biomes You'll Go Scoria Cobblestone, which can be smelted into BYG Scoria Stone.

Neither BYG Scoria Cobblestone or Scoria Stone can be Stonecuttered back to Create Scoria, or any variant, in the Stonecutter directly. It can be done by smelting into Scoria Stone, then crafting them into BYG Scoria Stonebricks, which can be Stonecut into Create Scoria or its variants.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
Should be good with this.
