### ISSUE TITLE
Mod Suggestion: Can't Sleep Clowns Will Eat Me

### ISSUE THREAD

**Issue by werwerwsx** [NillerMedDild/Enigmatica6#3670]
### URL

https://www.curseforge.com/minecraft/mc-mods/cant-sleep-clowns-will-eat-me

### Why would you like the mod added?

Makes it so any mobs preventing the player from sleeping are highlighted with the glowing potion effect for a default of 3 seconds.

Would be a nice QOL to help players with that one zombie hiding under the floor they didn't even know was there.

![the_clowns_that_will_eat_you_if_you_sleep](https://user-images.githubusercontent.com/22715665/140596460-fed45f65-eebc-4ec6-97dc-ede66facb47a.png)

**Comment by NillerMedDild** [comment]
Sure, seems like a nice addition.

**Comment by RobuxShooters** [comment]
That's a very interesting name for a mod though

**Comment by NillerMedDild** [comment]
True, might be a bit off-putting to some 🤔

**Comment by Trostmm** [comment]
Was a great Simpsons episode
