### ISSUE TITLE
ProjectEX for 1.16.5

### ISSUE THREAD

**Issue by AceDrago** [NillerMedDild/Enigmatica6#3671]
### URL

https://www.curseforge.com/minecraft/mc-mods/projectex-forge

### Why would you like the mod added?

it is the 1.16.5 updated version of projectex that adds the block to allow for refine storage to access projecte and put items into it remotely and also it has the single block passive power flowers.

**Comment by NillerMedDild** [comment]
I don't think Project E has any place in E6, or any kitchen sink pack for that matter 😄 no thank you.
