### ISSUE TITLE
McCrayfish Furniture Drawers shouldn't be in $storage/bulk tab

### ISSUE THREAD

**Issue by telemenar** [NillerMedDild/Enigmatica6#3680]
### Describe your suggestion

McCrayfish Furniture Drawers shouldn't be in $storage/bulk tag.

### Why would you like this added/changed?

There are a lot of the drawers and in that tag they crowd the other options.

**Comment by MuteTiefling** [comment]
Yep definitely shouldn't be in bulk. Moved them to basic. 

As for the clutter, that's unavoidable I'm afraid. These tags are meant for searching options, so excluding items that fit the bill would be counter productive.
