### ISSUE TITLE
Furnaces won't open when right clicked.

### ISSUE THREAD

**Issue by Dunnie97** [NillerMedDild/Enigmatica6#3681]
### Modpack Version

0.5.20

### Describe your issue.

Certain furnaces can't be opened after updating to the 1.16.5. Affects: Smoker; Furnace; Redstone Furnace from Thermal; Godforge, Kiln, glassblower furnace, and limestone furnace from Atum 2; Endstone, Violecite and sulfuric rock furnaces from BetterEnd Forge. Didn't Crash but can't smelt anything unless I set up hoppers to feed it.

![2021-11-08_08 33 13](https://user-images.githubusercontent.com/28661980/140709291-9163c3ee-9ad8-4ffb-b318-119dc0225ce0.png)

### Latest Log

https://github.com/Dunnie97/EnigmaticaLog-Dunnie

### Have you modified the modpack?

Yes

### User Modifications

Turned off the Quark Variant wooden items, New Stone Types and Speleothems.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Quezler** [comment]
that's a minecraft version, not a modpack version ^

**Comment by Dunnie97** [comment]
My bad. Fixed now.

**Comment by Darkere** [comment]
Try a restart.

**Comment by Dunnie97** [comment]
Restarting the app worked. Thank you.
