### ISSUE TITLE
Server crash an missing grave

### ISSUE THREAD

**Issue by M3wM3w** [NillerMedDild/Enigmatica6#3688]
### Modpack Version

0.5.20 (expert mode)

### Describe your issue.

A player was killed by an Atum 2 "boss" mob in the overworld caves.
The server crashed and after the server resumed, no grave for the player was to be found. 
The grave marker item was leading to an empty spot in an ocean.
We had to rollback the player's character file to prevent loss of all items.

### Crash Report

https://pastebin.com/LeqiQjHG

### Have you modified the modpack?

Yes

### User Modifications

dcintegration (discord chat)

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
Crash was caused by discord integration. As it crashed during the players death processing it is fairly certain that this is the reason why no grave was created.
