### ISSUE TITLE
AE2 & Towers Of The Wild world generation conflict.

### ISSUE THREAD

**Issue by poprosian** [NillerMedDild/Enigmatica6#369]
**Modpack version**
0.2.17

**Issue**
A world generation problem caused by a conflict of Applied Energistics 2 and Towers Of The Wild. From my understanding, a meteorite and tower were trying to spawn in the same place when generating a chunk, and it basically created a deadzone that when entered would crash the whole server.

**Logs**
https://pastebin.com/EQTf2fK8

**Comment by Darkere** [comment]
How did you come to that conclusion?

**Comment by poprosian** [comment]
That chunk was supposed to have a meteorite as I can across it when searching for one using the compass. After many tried, my friend that's handling the server took off AE2 and noticed there was a tower in the exact spot where the meteorite was supposed to be.

**Comment by NillerMedDild** [comment]
AE2 won't be in the next update, so this is sorta fixed ^^
But, that log exert doesn't show any sign of an issue between AE2 and Towers of the Wild. Please, in the future, attach a complete latest.log or crash report.
