### ISSUE TITLE
industrial foregoing plant sower only does saplings

### ISSUE THREAD

**Issue by wallasaurus** [NillerMedDild/Enigmatica6#3692]
### Modpack Version

0.5.20

### Describe your issue.

When using the plant sower machine, it will only work with samplings.  all the different seeds both modded and native minecraft like wheat do not get planted.

I tried to check all the dumb things I might have done wrong, but I have trees happily getting grown and processed next door, but my wheat/potato/wasabi/whatever I try simply doesnt wanna get planted.  I can manually plant the seed with a hoe as you'd expect so the dirt seems to be compatible.

<edit>  Oh, and I was googling around and someone mentioned that protecting chunks might mess with it so I removed all that ownership of chunks and it still refused to obey my decrees

Maybe this is part of the pack, to encourage use of other mods, but I wanted to bug it just in case it is a bug.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It seems like the Plant Sower in unable to till the soil, would you mind trying to till it yourself and see if it starts working?

**Comment by NillerMedDild** [comment]
I asked the mod developer, and apparently the Plant Sower is not supposed to till the dirt, you have to do that yourself.
