### ISSUE TITLE
Can't craft Flax Bale, recipe doesn't exist.

### ISSUE THREAD

**Issue by JoaGamo** [NillerMedDild/Enigmatica6#3693]
### Modpack Version

0.5.20

### Describe your issue.

Flax Bale, the block similar to Hay Bale that is normally crafted with 9 flax from Supplementaries mod, can't be crafted.
Recipe does not exist, even trying in the crafting table shows nothing.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
Seems to be a bug in supplementaries: https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/165

Looks like their recipe has the wrong condition on it: 

```js
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "000",
    "000",
    "000"
  ],
  "key": {
    "0": {
      "item": "supplementaries:flax"
    }
  },
  "result": {
    "item": "supplementaries:flint_block",
    "count": 1
  },
  "conditions": [
    {
      "type": "supplementaries:flag",
      "flag": "flint_block"
    }
  ]
}
```

**Comment by MuteTiefling** [comment]
went ahead and PRd a fix.

https://github.com/MehVahdJukaar/Supplementaries/pull/134
