### ISSUE TITLE
pneumaticraft item life in PNC armor book <> reality discrepancy

### ISSUE THREAD

**Issue by DoomSquirter** [NillerMedDild/Enigmatica6#3700]
### Modpack Version

5.20

### Describe your issue.

pnc book says you can put 6 item life upgrades in each piece of armor but the upgrades only stack to 5 when they are put in.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Actually I just relayed it 😄
