### ISSUE TITLE
Iridium Ore is obtainable through ore generators

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#3702]
### Modpack Version

0.5.20

### Describe your issue.

Iridium Ore can be obtained with the IF ore laser. Most likely also NA and AS.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Quezler** [comment]
Thank you for the report, I will investigate the issue.
