### ISSUE TITLE
Arboreal Extractor doesn't recognize Menril trees

### ISSUE THREAD

**Issue by kosma** [NillerMedDild/Enigmatica6#3704]
### Modpack Version

0.5.20

### Describe your issue.

Despite there being a recipe, Arboreal Extractor fails to recognize Menril trees. Checked with naturally generated trees, bonemeal-grown trees, and manually built trees.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
You'll likely need to break one of the logs at the base so you can get it right up against the main column of the trunk.

**Comment by MuteTiefling** [comment]
Like so:
![2021-11-11_21 49 49](https://user-images.githubusercontent.com/9543430/141400650-aeeccda6-2d07-4724-9b3c-986ea65349a6.png)

**Comment by kosma** [comment]
I did more testing and found out that even with the above placement, the extractor only detects about 80% of the trees - this must be why it slipped through my testing. It seems to be confused by the Enriched Menril Logs, though I haven't been able to find the exact conditions that cause it to fail. In any case - the above setup usually works, and if it fails, replanting usually fixes the issue. I guess this is a good enough solution.

**Comment by MuteTiefling** [comment]
It fails to detect if the bottom block is Enriched Menril, yes. Not much to do about that, the recipe structure doesn't allow for them.
