### ISSUE TITLE
Apotheosis flethcing table Duping quartz

### ISSUE THREAD

**Issue by aeshos** [NillerMedDild/Enigmatica6#3706]
### Modpack Version

Enigmatica6-0.5.20

### Describe your issue.

step 1 - Make 1 craft of 6 Quartz tipped arrows in the apotheosis fletchers table
             recipe will bug out for further crafts to only make 4 instead of 6
step 2 - remove all ingredients other than Minecraft Nether quartz and replace quartz to a full stack of 64 in top left slot
step 3 - craft 1 BYG nether quartz on the right and watch the stack in the top left double minus the 1 used to craft.

### Have you modified the modpack?

Yes

### User Modifications

edited waystone cost distance to 800blocks. no other changes

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by aeshos** [comment]
also appears to be conflict with the regular arrow recipe as well says 6 should be made in the table but bugs down to 4 after first craft, may be possible conflict with vanilla table recipes.

**Comment by MuteTiefling** [comment]
Thanks for the report. 

Reproduced easily in 0.5.20, but can no longer reproduce in Dev. Assuming some mod update fixed this.
