### ISSUE TITLE
Water in the Nether - Warped Coral Fan

### ISSUE THREAD

**Issue by kosma** [NillerMedDild/Enigmatica6#3707]
### Modpack Version

0.5.20

### Describe your issue.

The Warped Desert biome generates with waterlogged Warped Coral Fans, which can be broken to create a water sources.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
byg nether biomes are disabled in e6 by default, i'm assuming you're in a non-terraforged world?

**Comment by kosma** [comment]
I don't know. I have `level-type=default` in my `server.properties`.

**Comment by kosma** [comment]
To elaborate: when I was setting up the server back in 0.5.11, I asked in Discord and people told me I don't have to set any specific `level-type` in `server.properties`. I am using the "server files" package, using serverstarter.jar.  Did I configure the server incorrectly?

**Comment by NillerMedDild** [comment]
TerraForged has to be enabled manually sadly :/ 
https://github.com/NillerMedDild/Enigmatica6/wiki/Installing-A-Server#serverproperties

**Comment by Darkere** [comment]
We set the default world Type to Terraforged in the forge-common.toml. And from the reports we are getting it seems to be working? Might be a faulty install.

**Comment by NillerMedDild** [comment]
Ah, alright - Marking as support then.
