### ISSUE TITLE
No more fall damage and slime boots won't bounce

### ISSUE THREAD

**Issue by LucAsl14** [NillerMedDild/Enigmatica6#3717]
### Modpack Version

0.5.20

### Describe your issue.

As stated in the title, I can't take fall damage anymore and my slime boots won't bounce. I found this when I opened the world and jumped off a tower hoping to bounce, but it didn't. I took the boots off and jumped and still didn't take damage. I can still take damage from other sources such as lava, just not fall damage. Also, gamerule FallDamage is set to true. What can I do to fix that?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report.

Could you please provide screenshots of your inventory + curios and Lost Trinkets?

**Comment by LucAsl14** [comment]
![2021-11-13_10 30 16](https://user-images.githubusercontent.com/94207449/141649639-be807079-517a-4039-ab03-7bb54377c520.png)
![2021-11-13_10 30 24](https://user-images.githubusercontent.com/94207449/141649642-2af22cd1-54d2-4858-9f5f-93d96b916396.png)
![2021-11-13_10 30 08](https://user-images.githubusercontent.com/94207449/141649645-f9a37c5e-0fc6-4b9e-ae38-571157d04a7d.png)

**Comment by LucAsl14** [comment]
Also it seems fall damage and slime boots work in other dimensions, such as the Nether and the Undergarden, just not in the overworld.

**Comment by LucAsl14** [comment]
Oh I found the problem. I had a Vicio ritual running and it cancels fall damage. I removed the ritual and it fixed everything.
