### ISSUE TITLE
Cannot craft Quark Oddities Item Pipes (Meant to be disabled, hidden from JEI)

### ISSUE THREAD

**Issue by mzrimsek** [NillerMedDild/Enigmatica6#372]
**Modpack version**
0.2.17

**Issue**
Item pipes appear in JEI but have no recipe you can craft them with.

**Comment by NillerMedDild** [comment]
Hmm, they're actually meant to be disabled, I'll look into it :) Thanks for the report!

**Comment by NillerMedDild** [comment]
Looks like it's intended that the items aren't completely gone: https://github.com/Vazkii/Quark/issues/1668

**Comment by Darkere** [comment]
We should be able to hide them in JEI.

**Comment by NillerMedDild** [comment]
I... totally forgot that was possible ^^'
