### ISSUE TITLE
Rotten Flesh to Occulism Tallow Issue in Thermal Series Redstone Furnace

### ISSUE THREAD

**Issue by CASHMON3Y1297** [NillerMedDild/Enigmatica6#3721]
### Modpack Version

0.5.20

### Describe your issue.

In JEI it shows that Tallow from Occultism can be made by smelting rotten flesh in a Thermal Series Redstone Furnace. When I place rotten flesh in a Redstone Furnace, it does nothing.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
Got a screenshot of the JEI page?

**Comment by CASHMON3Y1297** [comment]
![Tallow](https://user-images.githubusercontent.com/94239785/141679012-a59d2396-2572-4cdb-83af-f8f73c9a0d8d.png)

**Comment by CASHMON3Y1297** [comment]
The recipe does work in a vanilla furnace

**Comment by MuteTiefling** [comment]
Recipe conflict due to the default flesh to leather recipe in the redstone furnace. I'll take a look later and see if we can't improve this somehow.

**Comment by CASHMON3Y1297** [comment]
ok cool Thanks!!
