### ISSUE TITLE
Questing: Bees Section

### ISSUE THREAD

**Issue by Litorom** [NillerMedDild/Enigmatica6#3722]
### Modpack Version

0.5.20

### Describe your issue.

Quest Items such as the Tiered Beehives are unobtainable due to the mod creator disabling them for depreciation.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
We'll get that fixed, ty 👍

**Comment by Litorom** [comment]
No, thank you for the modpack! 😊

**Comment by NillerMedDild** [comment]
Actually... I don't see them anywhere in the quests?

**Comment by Litorom** [comment]
The issue is here, Tiered Hives are depreciated.
https://github.com/NillerMedDild/Enigmatica6/blob/master/config/ftbquests/quests/chapters/resourceful_bees.snbt

**Comment by NillerMedDild** [comment]
Ahh the tiered hives are still accepted. Is that an issue?

**Comment by Litorom** [comment]
Well Tiered Hives being there is the issue. Since they are depreciated they are unobtainable. This tab should be redone to work with the mod. Otherwise the tab is useless and impossible to do in survival.

**Comment by NillerMedDild** [comment]
It accepts any of those hives though? the majority of which are obtainable.
You are talking about the `Bee Nests` quest right?

**Comment by Litorom** [comment]
This changelog explains it. https://www.curseforge.com/minecraft/mc-mods/resourceful-bees/files/3478990
The T1-4 Bee Hives.

**Comment by TemperedFool** [comment]
I'm a little confused; the changes Team Resourceful made in that changelog don't effect our quests? Our file you linked to above has our updated quests, which are looking for the Tiered Hive Upgrades, not the Tiered Hives (which we've depreciated).

**Comment by Litorom** [comment]
Is this data in 0.5.20? Or is it available for a newer version.

**Comment by TemperedFool** [comment]
Yes; we've depreciated Tiered Hives, and updated the quests to reflect that. You can't craft new tiered hives but the ones you've got will still work fine. Use the Tiered Hive Upgrades in-world on Resourceful Bee Nests (the one you find by exploring) to upgrade them. Also go into your quest book - we added a checkmark quest noting these changes.

**Comment by Litorom** [comment]
Ok, then this must be a server issue. I’ll talk to them, thanks.
