### ISSUE TITLE
[Mod Suggestion] Wyrmroost

### ISSUE THREAD

**Issue by Dasavanth** [NillerMedDild/Enigmatica6#373]
https://www.curseforge.com/minecraft/mc-mods/wyrmroost/files
looks pretty neat and i was thinking it would fill the mob variety void maybe? as ice and fire is out of the question (sad noises)

**Comment by Dasavanth** [comment]
https://www.youtube.com/watch?v=ed8rLRDNVDQ&t=22s
found this awesome mod showcase, might give better insights into this

**Comment by NillerMedDild** [comment]
Awesome mod, loved the showcase, thanks for the suggestion. I'm thinking about adding it once the dimension is done, so they don't run rampant in the overworld :D

**Comment by MuteTiefling** [comment]
These things are adorable o_O

**Comment by NillerMedDild** [comment]
This doesn't really fit into my plans for the modpack after all.
