### ISSUE TITLE
[MOD SUGGESTION]: More Mounted Storages

### ISSUE THREAD

**Issue by juh9870** [NillerMedDild/Enigmatica6#3731]
### URL

https://www.curseforge.com/minecraft/mc-mods/more-mounted-storages

### Why would you like the mod added?

This mod allows some modded storage to be used as a part of Create moving contraption.
I started this mod for personal use in my playtroughs, but people found it interesting, so I added more mods support and published it on Curseforge.
Despite what the big text on mod page saying, I'm fairly sure that the mod is fairly stable, but if you find any issue, feel free to create an issue on its GitHub page or notify me here, so I can fix it.
If you find that some storage are too powerful to be used as a part of a moving contraption, you can disable them in configs

**Comment by NillerMedDild** [comment]
Seems like a solid addition, I'll try it out once it's marked as beta :) thanks for the suggestion

**Comment by juh9870** [comment]
I did some more testing, fixed two bugh i managed to find, and I'm sure it's not going to cause world-breaking situations now, so I'm uploading new file with Beta status, it will be ready once Curseforge approves it

**Comment by NillerMedDild** [comment]
Awesome 👍

**Comment by juh9870** [comment]
I released an update (hopefully the last one for at least this week), adding storages priority system, more mods support and revamped config file structure. If you already started testing it I recommend switching to the new version for better results

**Comment by juh9870** [comment]
Note that config format changed after an update, so if you plan on disabling certain storages, you should do it after the mod update, otherwise all changes will be lost

**Comment by NillerMedDild** [comment]
Duely noted, ty 👍
