### ISSUE TITLE
Pedestals Exp dropper speed enchant not working properly

### ISSUE THREAD

**Issue by staviq** [NillerMedDild/Enigmatica6#3733]
### Modpack Version

0.5.20

### Describe your issue.

When using pedestals to convert Essence to xp orbs that player can pick up, basic setup works fine:

Mob crusher -> Ender tank -> pedestal Fluid import upgrade -> pedestal Fluid to XP upgrade -> pedestal Exp dropper upgrade.

But if the Exp dropper upgrade is enchanted with any level of Pedestals speed, it generates orbs, and does it faster, but those orbs when picked up by a player do not change players xp at all.

https://i.imgur.com/8NMwfa6.png

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
What enchants are on the dropper upgrade? Did it happen to get a range/area enchant making it drop the orbs elsewhere? Or in range of the mob crusher work area maybe?

**Comment by staviq** [comment]
I'm an idiot, didn't notice that i have my crystal pickaxe, with mending, that has about 20k worth of durability to repair and it was eating all the xp :)

Sorry for the confusion :)
