### ISSUE TITLE
Add recipes for Ars Nouveau archwood leaves

### ISSUE THREAD

**Issue by oleg-py** [NillerMedDild/Enigmatica6#3737]
### Describe your suggestion

The four types of archwood leaves from Ars Nouveau can't be used for any crafting where `minecraft:leaves` is expected.

### Why would you like this added/changed?

If using a plant machine like botany pot, garden cloche or phytogenic insolator, archwood saplings produce leaves as one of the products, and Ars woods are useful in the mod itself apart from generic wood uses, making it a good choice for such a machine. Having options like composting them or using in botania rune recipe would be nice.

**Comment by NillerMedDild** [comment]
Fixed, thanks :)
