### ISSUE TITLE
Crash if a player joins

### ISSUE THREAD

**Issue by shukari** [NillerMedDild/Enigmatica6#3741]
### Modpack Version

0.5.20

### Describe your issue.

If a player joins after 30sec the game does not longer respond and after 300sec the server crashes.
I have the crashreports i hope it helps.

### Crash Report
[crash-2021-11-17_21.31.13-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/7558344/crash-2021-11-17_21.31.13-server.txt)
[crash-reports.zip](https://github.com/NillerMedDild/Enigmatica6/files/7558342/crash-reports.zip)

### Latest Log
[2021-11-17-1.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/7558343/2021-11-17-1.log.gz)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you use pastebin, gist.github or put the file here directly please? :)

**Comment by shukari** [comment]
@NillerMedDild done

**Comment by NillerMedDild** [comment]
Oh boy, I'm having a hard time reading those crash reports. Not really getting anything meaningful out of them.

Did you perhaps increase random tick rate?

**Comment by shukari** [comment]
How? And how much?

**Comment by NillerMedDild** [comment]
If you're unsure then you most likely didn't 😄 It's through a gamerule.

**Comment by shukari** [comment]
A player say that it happens if he goes to his home. It seams to be connected to Astral soccery and something with Ritual Pedestal an with the konstilation Aevitas.
