### ISSUE TITLE
Dupe glitch: Mekanism Cardboard box with Astral Sorcery Constellation Papers in Gold Chest

### ISSUE THREAD

**Issue by Pastycrimper1** [NillerMedDild/Enigmatica6#3743]
### Modpack Version

0.5.20

### Describe your issue.

I have a "Gold Chest" containing 'paperwork items' - mainly enchanted books, maps, and other books etc. including 8 Astral Sorcery "Constellation Papers".

When I place a Mekanism cardboard box on this chest, a copy of each of the Astral Sorcery Constellation papers contained within the gold chest pops out into the world. If I remove the cardboard box, revealing the gold chest, the original "Constellation Papers" are still in the gold chest (thereby causing a duplication of all of the constellation papers in the chest). [Similar to this issue I guess?? https://github.com/NillerMedDild/Enigmatica6/issues/1847]

### Have you modified the modpack?

No

### User Modifications

None

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
#1847
