### ISSUE TITLE
Lens of Ender fails to craft

### ISSUE THREAD

**Issue by MechanicalDragon0687** [NillerMedDild/Enigmatica6#3744]
### Modpack Version

0.5.20

### Describe your issue.

Lens of ender still randomly fails to craft.
Had this happen to me to in 0.5.20 in overworld.
Angered enderman by looking at face, lured to boat him
After he was boated, used the photoelectric pane and both the enderman and pane disappeared

This was single player.

I had changed video settings causing a reload of resources directly after joining the world, but this was about 20 minutes prior.
I am using the standard modpack with no modifications
The logs did not mention anything at all at that point, so that wont help either.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Can you double check that it didn't get picked up by a backpack or dank? It drops as an item when it converts.

**Comment by MechanicalDragon0687** [comment]
I can be certain as i have not made a dank or backpack

**Comment by RobuxShooters** [comment]
What if you had 2 photoelectric panes stacked together when right-clicking on an Enderman?

**Comment by MechanicalDragon0687** [comment]
fun fact, when i had 2 panes, it did indeed create one.  When i had 1 pane i could see the lens generated momentarily then disappear from the inventory (which was odd)

The issue didnt seem to occur when the enderman was not boated but further testing is likely warranted

**Comment by MechanicalDragon0687** [comment]
This seems to be a duplicate of #2254 which seems to have already been reported https://github.com/owmii/Powah/issues/180 here and not yet addressed. This can be closed, sorry for the duplicate
