### ISSUE TITLE
bug with using polymorphs recipe conflict button in an occultism crafting interface

### ISSUE THREAD

**Issue by Anniebe11** [NillerMedDild/Enigmatica6#3750]
### Modpack Version

0.5.20

### Describe your issue.

when crafting stone bricks from 4 andesite in the crafting interface of the occultism storage accessor or the occultism dimensional storage actuator, a shift click creates a stack of rock path instead of the stone bricks.  
This problem does not occur in the inventory 2x2 crafting grid or in a vanilla crafting table.

steps to recreate:
open the interface of an occultism dimensional storage actuator or storage accessor
create a 2x2 pattern of andesite in the crafting grid
have enough andesite in the crafting grid or in the storage actuator to craft more than one recipe
click the double arrow button from polymorph to chose stone bricks as the recipe result
hold shift and click on the stone bricks in the recipe result slot

actual result: up to a stack of rock path with be crafted
expected result: up to a stack of stone brick blocks should be crafted

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report.

I can't seem to reproduce this in-dev, or even use Polymorph with Occultism storage. We have updated Polymorph and Occultism in-dev, so it might've been fixed/disabled.

![image](https://user-images.githubusercontent.com/21295394/142731506-45234c88-d995-4c93-b65f-429a4297af54.png)
