### ISSUE TITLE
Simple Farming Seeds in Marketplace

### ISSUE THREAD

**Issue by Subtle-Banshee** [NillerMedDild/Enigmatica6#3751]
### Modpack Version

0.5.20

### Describe your issue.

Seeds from the Simple Farming modpack don't seem to be available in the Market.
![image](https://user-images.githubusercontent.com/91931913/142743717-26fc9e21-f900-44ad-8a9d-df9fcde06a7f.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
