### ISSUE TITLE
Change the discord invite and github link in the server packs to the enigmatica github/discord

### ISSUE THREAD

**Issue by Dsmario64** [NillerMedDild/Enigmatica6#3753]
### Describe your suggestion

The server pack currently has links to Team RAM's discord/Github. Right now our github and discord are inactive and non-operational, so users are seeking us out for questions despite no one there being able to answer.  

### Why would you like this added/changed?

Because I want to see users actually get the help they need instead of shouting into the void of a dead github/discord.

**Comment by Dsmario64** [comment]
Small correction, only the Discord link is depreciated. The creator (BloodworkGaming) does still update the serverpack and the github is still active.

**Comment by NillerMedDild** [comment]
We'll get that fixed, sorry for the trouble :)

**Comment by NillerMedDild** [comment]
Fixed in-dev :)
