### ISSUE TITLE
Unable to set redstone sensitivity on Mekanism logistical transporter

### ISSUE THREAD

**Issue by Foxtrot2Nov** [NillerMedDild/Enigmatica6#3755]
### Modpack Version

0.5.20

### Describe your issue.

Doesn't matter what version of the logistical transporter pipes - Basic, Advanced, Elite, or Ultimate - but cannot change the redstone sensitivity. It tries to change color instead. Works fine with all the other types of Mekanism pumps.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
There's a special redstone sensitive version of the item pipes. You'd need to use that to make this work.
