### ISSUE TITLE
Blood magic

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#376]
released an alpha for `1.16` 4 days ago: https://www.curseforge.com/minecraft/mc-mods/blood-magic

(maybe worth waiting till a `.4` release or a beta, but it would still be a lovely addition ❤️)

**Comment by NillerMedDild** [comment]
We're keeping our eye on it, but waiting till it's more fleshed out :) pre-alpha is too early for modpack addition imo.

**Comment by Quezler** [comment]
> pre-alpha is too early for modpack addition imo.

> > maybe worth waiting till a .4 release or a beta

yea i agree, just throwing it out there, i do hope the mod becomes stable before the next e6 release 😃

**Comment by Trostmm** [comment]
+1 for Blood Magic, Love that mod, Happy to test the heck out of it...
