### ISSUE TITLE
Add Ender IO Conduits

### ISSUE THREAD

**Issue by shoutingacorn** [NillerMedDild/Enigmatica6#3780]
### URL

https://www.curseforge.com/minecraft/mc-mods/ender-io-conduits

### Why would you like the mod added?

Personally I'm a neat freak, and not having a mod that can cover the cables (Forge Microblocks for example) makes the viewing experience less desirable. I understand that adding Forge Multipart MicroBlocks would require managing and configuring textures with blocks from other mods and may take too long, so I think a good alternative is the one offered by Ender IO. 
In particular, the possibility of passing multiple cables through the same block, which greatly reduces the space required to set up complex machinery, would be great!

**Comment by NillerMedDild** [comment]
That mod is not available for Minecraft 1.16.5 :)
