### ISSUE TITLE
[0.5.20] Induction Smelter Inconsistent Ore Chunk Output

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#3783]
### Modpack Version

0.5.20

### Describe your issue.

When using Thermal's Induction Smelter some ore chunks appear to not be effected by the catalysts. Catalysts tested were cinnabar, rich slag, and sand.

Using cinnabar the expected main output per ore chunk is three ingots, i.e. one iron ore chunk with a cinnabar catalyst should result in three iron ingots.

Ore chunks that did result in three ingots: Iron, Lead, Silver, Copper, Tin, & Gold.
Ore chunks that only gave one ingot: Osmium, Aluminum, Uranium, & Zinc.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It appears to be because we're adding those recipes through KubeJS, not sure why they can't output more with catalysts.
