### ISSUE TITLE
Pam's HarvestCraft 2 Suite

### ISSUE THREAD

**Issue by Subtle-Banshee** [NillerMedDild/Enigmatica6#3789]
### URL

https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core

### Why would you like the mod added?

There are four mods in total for Pam's HarvestCraft 2, and I would like to request all of them to be added.
- Pam's HarvestCraft 2 - Food Core
- Pam's HarvestCraft 2 - Crops
- Pam's HarvestCraft 2 - Trees
- Pam's HarvestCraft 2 - Food Extended

I'm not personally one for exploration too much, and so I like having things to do at the base while I'm waiting for other mods to do their things, and Pam's HarvestCraft has always been one of my more favorite "busybody" mods to play around with.

Cooking for Blockheads already includes support for the Pam's tools, such as the pot and pan, and Pam's 2 has included support for Simple Farming and other such modpacks. With the sheer amount of meals that it adds, it's just a fun little modpack to work on, especially when you like to make "feasts" for your friends on your server for occasions such as Thanksgiving and Christmas.

**Comment by MuteTiefling** [comment]
duplicate: https://github.com/NillerMedDild/Enigmatica6/issues/227
