### ISSUE TITLE
Expert StorageDrawer script forgot check for expert

### ISSUE THREAD

**Issue by joklbash** [NillerMedDild/Enigmatica6#3792]
### Modpack Version

Dev as of 11/26

### Describe your issue.

Issue 3720 added an expert set of stuff for storage drawers. There's no check for expert mode, so it bleeds over to normal.

### Have you modified the modpack?

Yes

### User Modifications

Using latest dev version.

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
Good catch, thanks.
