### ISSUE TITLE
Flint and Bronze recipe needs to use tag + flare stack recipe broken

### ISSUE THREAD

**Issue by Darkere** [NillerMedDild/Enigmatica6#3795]
### Modpack Version

dev

### Describe your issue.

uses tinkers bronze

flare stack relies on a certain type of flint and bronze it seems? At least doesn't craft for me with cheated in flint and bronze. 

EDIT: After checking I see that tinkers bronze is a different item than regular bronze. We should unify regardless. 

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Tinkers bronze is probably fine, it has it's own properties.

The flare stack is more worrying, since there's nothing funny going on in that recipe. just needs the item. I'll just swap it to something different though.

**Comment by MuteTiefling** [comment]
![image](https://user-images.githubusercontent.com/9543430/143691928-42fc2c2e-9658-4e9a-90b8-dcbc675d435d.png)

**Comment by Darkere** [comment]
The tinkers bronze name is confusing. Looks like bronze. Says its bronze. But is a different bronze.
Unless you specifically happen to look at how to make bronze you'll assume the recipe is broken.

**Comment by NillerMedDild** [comment]
I agree that Tinkers' Bronze is confusing, but don't think we should change it :)
