### ISSUE TITLE
cant smelt dusts

### ISSUE THREAD

**Issue by zzyzzyzzx** [NillerMedDild/Enigmatica6#38]
**Modpack version**
0.2.1

**Issue**
Cant smelt ores after putting through enrichment chamber, ores comes out as pedestals dust which cant be smelted except by arc furnace

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
Does using the /reload command fix it?

**Comment by DakSevkla** [comment]
Dirty Nickle Dust in an Enrichment factory spits out Pedestals Nickel Dust.

Getting Immersive Engineering dusts from the enrichment factory as well, lead, uranium, copper are all doing it right now.  I'd test more but my system is backed up entirely by pedestals nickel

**Comment by DakSevkla** [comment]
> Thank you for the report, I will investigate the issue.
> Does using the /reload command fix it?

/reload did not fix, still turning JAOPCA dirty nickel into pedestals dust

**Comment by DakSevkla** [comment]
Looks like it should be going to Nickel Grit from Immersive Engineering, but that has a different name than dust which may be the cause?

**Comment by DakSevkla** [comment]
Dirty Copper Dust from Mekanism becomes Copper Grit from Immersive Engineering in an Enrichment Chamber as well instead of Copper Dust from Mekanism.

**Comment by NillerMedDild** [comment]
I'm not exactly sure what the cause of this issue is, but I should have a solution soon.

**Comment by DakSevkla** [comment]
> I'm not exactly sure what the cause of this issue is, but I should have a solution soon.

Getting Iron Grit from Dirty Iron Dust, but that smelts to Iron Ingots from Minecraft so it's OK I guess.

Lead, Copper, Nickel, and Uranium seem to be the culprits of the ores I have right now.

**Comment by DakSevkla** [comment]
Steel Ingots as well, creates Immersive Engineering, used to create Mekanism.

**Comment by DakSevkla** [comment]
Sorry to keep updating here but I keep finding more.  Enriched Iron in an Infuser creates the Steel Grit instead of Steel Dust

**Comment by NillerMedDild** [comment]
The intended output is from Immersive Engineering whenever possible :)
