### ISSUE TITLE
Thermal Foundation, Thermal Expansion and Thermal Dynamics

### ISSUE THREAD

**Issue by excodex** [NillerMedDild/Enigmatica6#381]
The Thermal series has been updated to 1.16, it would be nice if you can add to the pack :) 

- https://www.curseforge.com/minecraft/mc-mods/thermal-foundation
- https://www.curseforge.com/minecraft/mc-mods/thermal-expansion
- https://www.curseforge.com/minecraft/mc-mods/thermal-dynamics

**Comment by NillerMedDild** [comment]
will be added in next update :)
