### ISSUE TITLE
Ars Nouveau's source gems spawning in desert temple chests (rather than EmendatusEnigmatica's source gem)

### ISSUE THREAD

**Issue by Iris-xii** [NillerMedDild/Enigmatica6#3815]
### Modpack Version

Enigmatica 6 0.5.21+ (commit 0dfcb4604ca8327f09d8ff45cda001caae9b6f31 dev branch, expert pack mode)

### Describe your issue.

**Regular Ars Nouveau source gems are spawning in desert temples rather than their EE counterpart.**

![image](https://user-images.githubusercontent.com/48930896/144107358-aeca94aa-65a9-409a-a18d-806c53d4981e.png)

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

Yes

### User Modifications

Disabled Alex's mobs crimson mosquito spawns through config, removed Tips and PackMenu

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
gonna take a look at this now that we have some new tools in kubejs.

https://github.com/baileyholl/Ars-Nouveau/blob/ef274855dc9efc336139d2ffe7b9cd8e47235eda/src/main/java/com/hollingsworth/arsnouveau/api/loot/LootTables.java#L35
https://github.com/baileyholl/Ars-Nouveau/blob/b3df4715c7da988f733858ea8355134ee45bc69d/src/main/java/com/hollingsworth/arsnouveau/common/datagen/DungeonLootGenerator.java

**Comment by MuteTiefling** [comment]
I'm afraid the new tools we have in kubejs are not up to the task currently. So we can't really fix this right now.
