### ISSUE TITLE
Disable Living Armor from Blood Magic until TickingPlayer exception is fixed

### ISSUE THREAD

**Issue by tac-owo** [NillerMedDild/Enigmatica6#3816]
### Describe your suggestion

The Living Armor set from BloodMagic crashes servers on login, as logged in [this](https://github.com/WayofTime/BloodMagic/issues/1853) issue thread on Blood Magic's github. Disabling the crafting of this armor set will bodge the issue until the mod is updated / fixed. 

### Why would you like this added/changed?

To make running a server a bit easier, and so players don't accidentally kill their playthroughs by crafting a bugged armor that seems like a clear upgrade.

**Comment by NillerMedDild** [comment]
A Blood Magic update released yesterday should fix this issue luckily 😀
