### ISSUE TITLE
Ultimine Not Distinguishing Between Stone Varieties

### ISSUE THREAD

**Issue by Tsilkani** [NillerMedDild/Enigmatica6#3825]
### Modpack Version

0.5.21

### Describe your issue.

With the newest update, a change was made so Ultimine will grab all of an ore seam across different stone types. However, this also means I can no longer mine just a specific type of stone when I'm using shapeless to grab whatever I can.  For example, I'm mining out a Deepslate layer above Limestone. Previously, I could simply target the Deepslate, use shapeless Ultimine, and get a full stack. Now it will grab the Limestone as well, possibly the stone directly beneath me.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
This was done intentionally. Without it, things like the 3x3 mining mode or stairs mode fail to work through strata, causing a lot of frustration.
