### ISSUE TITLE
bone mealing BYG Overgrown Blocks does not work properly / dispensing bone meal corrupts world

### ISSUE THREAD

**Issue by mrmechanik** [NillerMedDild/Enigmatica6#3827]
### Modpack Version

0.5.21

### Describe your issue.

While playing on my server I first stumbled upon this problem by trying to use a dispenser with bone meal on the overgrown stone from BYG thus, loosing ~2 hrs of play time but anyways...
In a singeplayer world I grabbed overgrown stone. Using bone meal on the block causes a single flower to appear after a random amount of tries, never grass.
Upon using a vanilla dispenser below the overgrown stone facing upwards, putting in bone meal and using a lever on said dispenser the game crashes and becomes corrupted.

I assume that this is rather a problem of BYG and not Enigmatica 6.
The latest.log is trimmed as it does not fit in pastebin...

### Crash Report

https://pastebin.com/GXuW6aaF

### Latest Log

https://pastebin.com/bkcimRQ9

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Would you mind removing RoadRunner and see if the issue still happens?
