### ISSUE TITLE
Turtlemancy

### ISSUE THREAD

**Issue by YashTFEM** [NillerMedDild/Enigmatica6#3831]
### URL

https://www.curseforge.com/minecraft/mc-mods/click-machine#:~:text=Click%20Machine%20is%20a%20standalone,click%20both%20blocks%20and%20entities.

### Why would you like the mod added?

Turtlemancy is a relatively small magic mod themed around turtles. The purpose of this mod is to add a magical way to help you with your minecraft adventure. 

It's a pretty cool magic mod and there is no reason it shouldn't be added to the pack especially since it gives more uses for our beloved turtles. Please consider this mod.

**Comment by Darkere** [comment]
wrong link?

**Comment by YashTFEM** [comment]
https://www.curseforge.com/minecraft/mc-mods/turtlemancy

Sorry, here's the correct link

**Comment by NillerMedDild** [comment]
It does look cool but it doesn't really add anything we don't have in the pack already. It's going to be a no :)

**Comment by theboo** [comment]
But the turtle boat tho!!

(Also it has no GitHub or CF issue tracker and no discord link either as far as I can see)
