### ISSUE TITLE
Botania: Mana Liquidizer

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#384]
this mod has received some attention in the e6 discord channel:

https://www.curseforge.com/minecraft/mc-mods/mana-liquidizer
https://github.com/MostafaSabry55/Mana-Liquidizer

this would make mana transport a lot more practical, and it has a stable `16.4` release 😃

**Comment by NillerMedDild** [comment]
Hmm I don't know, Botania's own mana transport systems aren't half bad, and require more ingenuity. I'll think it over :)

**Comment by Quezler** [comment]
> and require more ingenuity

its annoying to have to use mana carts / cycling around tablets / maximizing spark range / etc 😅

**Comment by NillerMedDild** [comment]
I've decided against this for the time being, sorry.

**Comment by Quezler** [comment]
no hard feelings 👍
