### ISSUE TITLE
Quartz ore with Minecraft mod tag was mined by digital miner. 

### ISSUE THREAD

**Issue by YashTFEM** [NillerMedDild/Enigmatica6#3843]
### Modpack Version

0.5.20

### Describe your issue.

I was mining quartz ore using my digital miner. It was getting ore chunks fine, until it suddenly started mining quartz ore with the minecraft mod tag. There should be only enigmatica ores right? 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Hmm yes :/ not sure how that happened. This script should remove it: https://github.com/NillerMedDild/Enigmatica6/blob/master/kubejs/startup_scripts/worldgen_remove.js

**Comment by Darkere** [comment]
Structures can still spawn it, I'm pretty sure.

**Comment by NillerMedDild** [comment]
Ah right, not much we can do about that. Fingers crossed that's the reason 😅

**Comment by TelepathicGrunt** [comment]
Repurposed Structures’s Nether Wells and Nether Strongholds spawn Nether Quartz Ore which can be remove easily by replacing these processor json files with a datapack. Set probability to 1 and change the output state to the other kind of quartz block you want to spawn instead or remove the entry entirely so no block is replaced with quartz. 
https://github.com/TelepathicGrunt/RepurposedStructures/blob/72889c71b868c30f44e5a914ba1daf928ec5a7fc/src/main/resources/data/repurposed_structures/worldgen/processor_list/wells/nether.json#L33

https://github.com/TelepathicGrunt/RepurposedStructures/blob/72889c71b868c30f44e5a914ba1daf928ec5a7fc/src/main/resources/data/repurposed_structures/worldgen/processor_list/strongholds/nether_library_randomize.json#L137

there are some quartz in RS loot tables which you could just do a quartz search for and override with datapack. Dunno if the scripts in E6 already handles that. 

This is just for RS quartz stuff but other structures may be similar where if it isn’t hardcoded, you could override their nbt files by datapacks too to remove vanilla quartz.

**Comment by NillerMedDild** [comment]
Thanks a lot for the info TelepathicGrunt :)
