### ISSUE TITLE
rendering problem

### ISSUE THREAD

**Issue by bbbucka** [NillerMedDild/Enigmatica6#3850]
### Modpack Version

1.16.5

### Describe your issue.

placed a waystone and my world tuned pink and not rendering
![Untitled](https://user-images.githubusercontent.com/94885822/144756415-d90a922b-8227-4cf3-ada4-61b4aa21dd2e.jpg)
.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by bbbucka** [comment]
i tried that, they were not helpful

**Comment by NillerMedDild** [comment]
Alright, I replied to you in there just now.
