### ISSUE TITLE
Missing Create mixer dough recipe

### ISSUE THREAD

**Issue by misterzirillo** [NillerMedDild/Enigmatica6#3851]
### Modpack Version

0.5.21

### Describe your issue.

Some time ago I could make dough in a Create mixer: 1b water + 1x flour. Looks like that recipe is missing now. It is missing from JEI and putting the ingredients in the mixing basin does nothing. 

### Have you modified the modpack?

Yes

### User Modifications

Optifine

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Sounds like it was an auto shapeless recipe, and since the 3x3 dough recipe is no longer shapeless, that's gone.

Create already allows 'free' washing of flour to dough, which is easier than the mixer recipe. I'm not sure we really need to bring back the shapeless recipe?

**Comment by misterzirillo** [comment]
Sounds like it's not a bug. That's fine with me!
