### ISSUE TITLE
Tinker Hammer and Marble.

### ISSUE THREAD

**Issue by HeavyDeception** [NillerMedDild/Enigmatica6#3862]
### Modpack Version

0.5.21

### Describe your issue.

The tinker hammer does not mine marble with the other stones making it kind of annoying to use I can understand ores but why does marble from AS seem to bug out with it.

If this is not a bug plz let me know what going on at least.

### Crash Report

No Crahs N/A

### Latest Log

N/A

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
AS marble has a higher mining level than other stones :)

**Comment by HeavyDeception** [comment]
I have a hammer that can mine level of netherite.

**Comment by HeavyDeception** [comment]
So even if the tool has a minning level of  netherite it will still mine it separately?

**Comment by NillerMedDild** [comment]
If you target the Marble it will mine it all, if you target the "softer" block it won't mine the Marble.

**Comment by HeavyDeception** [comment]
Ok I get it now thanks sorry about the confusion.

**Comment by NillerMedDild** [comment]
No worries 👍
