### ISSUE TITLE
Redstone Pen

### ISSUE THREAD

**Issue by YashTFEM** [NillerMedDild/Enigmatica6#3877]
### URL

https://www.curseforge.com/minecraft/mc-mods/click-machine#:~:text=Click%20Machine%20is%20a%20standalone,click%20both%20blocks%20and%20entities.

### Why would you like the mod added?

Its a QoL redstone mod that allows you to make compact redstone wiring, even on walls. It has a lot of customizability options to make a very compact and neat redstone circuit and allows many more possibilities using redstone. It's a really neat mod that is be amazing.

**Comment by telemenar** [comment]
Uh redstone pen is already in the pack. And your link is to Click Machine not to redstone pen.

**Comment by YashTFEM** [comment]
Why does it always paste the click machine link and not the link I want?
