### ISSUE TITLE
BloodMagic Living Armor permanently crashes world

### ISSUE THREAD

**Issue by Pilex1** [NillerMedDild/Enigmatica6#3880]
### Modpack Version

0.5.21

### Describe your issue.

When using the Bloodmagic living armour, the game crashes. Trying to load up the world again causes immediate crash again, making the world unplayable. Seems to be a null pointer exception with the hasElytra method in the ItemLivingArmor class in BloodMagic.

### Crash Report

https://gist.github.com/Pilex1/334cf389b7c81e53392fda3237999484

### Latest Log

https://gist.github.com/Pilex1/995ed32bfbe1d1757025ecb6039f9a72

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
#3494

**Comment by MuteTiefling** [comment]
Looks like this might be fixed in BM already if you want to test. Just update BM to the latest

**Comment by NillerMedDild** [comment]
Can't check atm, but isn't 0.5.21 running the fixed version?

**Comment by MuteTiefling** [comment]
No, one version behind
