### ISSUE TITLE
Error loading Tinkers mod

### ISSUE THREAD

**Issue by thiefaine** [NillerMedDild/Enigmatica6#3885]
### Modpack Version

0.5.21

### Describe your issue.

Hello,

I tried installing the modpack with Curse Forge, and during the launch of the game I had this error :
"Tinkers' Construct encountered an error during the load_registries event phase
NullPointerException. Registry Object not present: tconstruct:seared_table"

and the same error with object : "scorched_fuel_tank"
cf the image link
![bug](https://user-images.githubusercontent.com/8777573/145693818-ef3872e8-a9f8-46d8-ad5c-ecd6f20becff.PNG)

I had to close the program and launch it again to work properly

### Crash Report

https://gist.github.com/thiefaine/3c4dbf03a313a8638255bf56c2a5876e

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please provide your latestlog from the crash?
