### ISSUE TITLE
Blood Magic's Alchemy Table can enter a glitched state and crash with java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by Iris-xii** [NillerMedDild/Enigmatica6#3895]
### Modpack Version

Enigmatica 6 0.5.21+ (commit  047b59fd3c609346212aae3093e213474efbc78b dev branch, expert mode)

### Describe your issue.

To be honest I don't really know what's going on here and I can't replicate it on new alchemy tables, so not a lot of information so far. It seems that my alchemy table has entered some sort of glitched state, I'm not really sure why. It became invisible, and stays that way even after a restart.

Interacting with it may cause the crash provided below. For the time being I have just removed the alchemy table using /setblock

### Crash Report

https://gist.github.com/Iris-xii/da3b0b11e086262f7d0bb409dcb027d3

### Latest Log

https://gist.github.com/Iris-xii/d6d85b3e095875b5f5944ef65c5d89e4

### Have you modified the modpack?

Yes

### User Modifications

Disabled Alex's mobs crimson mosquito spawns through config, removed Tips and PackMenu

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report, however, unless you can reproduce this with a new table, I don't think we should investigate further :)
