### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Beralath** [NillerMedDild/Enigmatica6#39]
**Modpack version**
0.2.1

**Issue**
multiple server crashes

**Logs**
---- Minecraft Crash Report ----
// You're mean.

Time: 7/27/20 4:48 AM
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
	at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:54) ~[?:?] {re:classloading,xf:fml:randompatches:RandomPatches ServerTickList Transformer}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:329) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:endergetic:patch_server_world,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:54)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:329)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 668
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-160,66,16), Chunk: (at 0,4,0 in -10,1; contains blocks -160,0,16 to -145,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5255490 game time, 6781138 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 20975 (now: true), thunder time: 14547 (now: true)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 3.10.0-1127.13.1.el7.x86_64
	Java Version: 1.8.0_252, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1017169856 bytes (970 MB) / 2887254016 bytes (2753 MB) up to 6524764160 bytes (6222 MB)
	CPUs: 3
	JVM Flags: 1 total; -Xmx7000M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.75.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.75
	FML Language Providers: 
		javafml@32.0
		minecraft@1
		kotori_scala@2.13.2-build-2
	Mod List: 
		NetherPortalFix_1.16.1-7.0.0.jar NetherPortalFix {netherportalfix@7.0.0 DONE}
		rad-1.16-4.0.1.jar Reload Audio Driver {rad@4.0.1 DONE}
		bambooeverything-1.16-1.0.0.jar Bamboo Everything {bambooeverything@1.16-1.0.0 DONE}
		modnametooltip_1.16.1-1.14.0.jar Mod Name Tooltip {modnametooltip@1.14.0 DONE}
		KleeSlabs_1.16.1-9.0.0.jar KleeSlabs {kleeslabs@9.0.0 DONE}
		rsgauges-1.16.1-1.2.4-b1.jar Gauges and Switches {rsgauges@1.2.4-b1 DONE}
		pitg-1.16.1-1.3.0.jar Pane In The Glass {pitg@1.16.1-1.3.0 DONE}
		BetterCaves-1.16.1-1.0.jar YUNG's Better Caves {bettercaves@1.16.1-1.0 DONE}
		XaerosWorldMap_1.7.4_Forge_1.16.1.jar Xaero's World Map {xaeroworldmap@1.7.4 DONE}
		CTM-MC1.16.1-1.1.0.1.jar ConnectedTexturesMod {ctm@MC1.16.1-1.1.0.1 DONE}
		CookingForBlockheads_1.16.1-9.0.0.jar Cooking for Blockheads {cookingforblockheads@9.0.0 DONE}
		Controlling-7.0.0.2.jar Controlling {controlling@7.0.0.2 DONE}
		ReAuth-1.16-Forge-3.9.0.jar ReAuth {reauth@3.9.0 DONE}
		Placebo-1.16.1-4.0.1.jar Placebo {placebo@4.0.1 DONE}
		dankstorage-3.7a.jar Dank Storage {dankstorage@3.7a DONE}
		citadel-1.2.0.jar Citadel {citadel@1.2.0 DONE}
		Powah-1.16.1-2.1.2.jar Powah {powah@2.1.2 DONE}
		rangedpumps-0.8.jar Ranged Pumps {rangedpumps@0.8 DONE}
		culinaryconstruct-FORGE-1.16.1-3.0.jar Culinary Construct {culinaryconstruct@FORGE-1.16.1-3.0 DONE}
		Bookshelf-1.16.1-6.1.11.jar Bookshelf {bookshelf@6.1.11 DONE}
		u_team_core-1.16.1-3.1.1.163-SNAPSHOT.jar U Team Core {uteamcore@3.1.1.163-SNAPSHOT DONE}
		randompatches-1.16.1-1.22.1.0.jar RandomPatches {randompatches@1.16.1-1.22.1.0 DONE}
		mcw-doors-1.0.0-mc1.16.1.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		Morpheus-1.16.1-4.2.55.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.16.1-10.0.3.426.jar Mekanism: Generators {mekanismgenerators@10.0.3 DONE}
		SnowRealMagic-1.16.1-2.0.0.jar Snow! Real Magic! {snowrealmagic@2.0.0 DONE}
		carpetstairsmod-1.16.1_v1.4.6.jar Carpet Stairs Mod {carpetstairsmod@1.4.6 DONE}
		CauldronRecipes-1.16.1-2.0.3.jar CauldronRecipes {cauldronrecipes@2.0.3 DONE}
		Ma-Essentials-1.16.1-3.2.3.jar Ma Essentials {maessentials@1.16.1-3.2.3 DONE}
		FpsReducer-mc1.16.1-1.17.jar FPS Reducer {fpsreducer@mc1.16.1-1.17 DONE}
		JustEnoughResources-1.16.1-0.11.0.81.jar Just Enough Resources {jeresources@0.11.0.81 DONE}
		laserrelays-1.6.jar Laser Relays {laserrelays@1.6 DONE}
		refinedstorage-1.9.2.jar Refined Storage {refinedstorage@1.9.2 DONE}
		structure-gel-api-1.16.1-1.1.1.jar Structure Gel API {structure_gel@1.1.1 DONE}
		PackMenu-1.16.1-2.1.0.jar Pack Menu {packmenu@2.1.0 DONE}
		mcw-bridges-1.0.4-mc1.16.1.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.16.1-3.0.3-5935836.jar Industrial Foregoing {industrialforegoing@3.0.3 DONE}
		useful_backpacks-1.16.1-1.11.1.69-SNAPSHOT.jar Useful Backpacks {usefulbackpacks@1.11.1.69-SNAPSHOT DONE}
		torchmaster-2.3.0-alpha.jar Torchmaster {torchmaster@2.3.0-alpha DONE}
		TipTheScales-1.16.1-3.0.0.2.jar TipTheScales {tipthescales@3.0.0.2 DONE}
		BiomesOPlenty-1.16.1-11.0.0.390-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.390 DONE}
		ToolStats-1.16.1-2.0.3.jar ToolStats {toolstats@2.0.3 DONE}
		Lollipop-1.16.1-2.1.2.jar Lollipop {lollipop@2.1.2 DONE}
		LetSleepingDogsLie-1.16.1-1.1.1.jar Let Sleeping Dogs Lie {dogslie@1.1.1 DONE}
		toughnessbar-6.0.jar Toughness Bar {toughnessbar@6.0 DONE}
		dungeons-plus-1.16.1-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 DONE}
		masonry-1.16.1-0.3.5.jar Masonry {masonry@NONE DONE}
		simplylight-1.16.1-1.0.0.jar Simply Light {simplylight@1.16.1-1.0.0 DONE}
		simplefarming-1.16.1-1.3.1.jar Simple Farming {simplefarming@1.16.1-1.3.1 DONE}
		simplybackpacks-1.16.1-1.4.6.jar Simply Backpacks {simplybackpacks@1.16.1-1.4.6 DONE}
		curios-FORGE-1.16.1-3.0.jar Curios API {curios@FORGE-1.16.1-3.0 DONE}
		Patchouli-1.16-39.jar Patchouli {patchouli@1.16-39 DONE}
		cakechomps-FORGE-1.16.1-4.0.jar Cake Chomps {cakechomps@FORGE-1.16.1-4.0 DONE}
		StrongerSnowballs-1.16.1-2.0.1.jar StrongerSnowballs {strongersnowballs@2.0.1 DONE}
		elevatorid-1.16.1-1.7.3.jar Elevator Mod {elevatorid@1.16.1-1.7.3 DONE}
		ftb-ultimine-1.1.0.6.jar FTB Ultimine {ftbultimine@1.1.0.6 DONE}
		MekanismTools-1.16.1-10.0.3.426.jar Mekanism: Tools {mekanismtools@10.0.3 DONE}
		curiouselytra-FORGE-1.16.1-3.0.jar Curious Elytra {curiouselytra@FORGE-1.16.1-3.0 DONE}
		AI-Improvements-1.16.1-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		globalxp-1.16.1-v1.4.12.jar Global XP {globalxp@v1.4.12 DONE}
		cherishedworlds-FORGE-1.16.1-4.0.jar Cherished Worlds {cherishedworlds@FORGE-1.16.1-4.0 DONE}
		productivebees-1.16.1-0.1.15.2.jar Productive Bees {productivebees@1.16.1-0.1.15.2 DONE}
		cloth-config-forge-4.0.2.jar Cloth Config v4 API {cloth-config@4.0 DONE}
		trashcans-1.0.1-mc1.16.jar Trash Cans {trashcans@1.0.1 DONE}
		tramplestopper-1.15.2-2.0.0.2-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.2-universal DONE}
		InventoryEssentials_1.16.1-2.0.0.jar Inventory Essentials {inventoryessentials@2.0.0 DONE}
		BetterBurning-1.16.1-2.0.2.jar BetterBurning {betterburning@2.0.2 DONE}
		bwncr-1.16.1-3.6.15.jar Bad Wither No Cookie Reloaded {bwncr@1.16.1-3.6.15 DONE}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		ServerTabInfo-1.16.1-1.2.7-alpha.jar Server Tab Info {servertabinfo@1.2.7-alpha DONE}
		PrettyBeaches_1.16.1-5.0.0.jar Pretty Beaches {prettybeaches@5.0.0 DONE}
		BetterMineshaftsForge-1.16.1-1.3.jar YUNG's Better Mineshafts {bettermineshafts@1.16.1-1.3 DONE}
		DarkPaintings-1.16.1-2.0.1.jar DarkPaintings {darkpaintings@2.0.1 DONE}
		DangerousStoneCutter-1.16.1-1.4.jar Dangerous Stone Cutter {dangerousstonecutter@1.4 DONE}
		BetterAdvancements-1.16.1-0.1.0.100.jar Better Advancements {betteradvancements@0.1.0.100 DONE}
		dwarfcoal-1.16.1-1.2.jar Dwarf Coal {dwarfcoal@1.16.1-1.0.0 DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		Kiwi-1.16.1-3.1.3.jar Kiwi {kiwi@3.1.3 DONE}
		BedBenefits-1.16.1-1.0.1.jar BedBenefits {bedbenefits@1.0.1 DONE}
		Ma-Enchants-1.16.1-3.2.1.jar Ma Enchants {ma-enchants@1.16.1-3.2.1 DONE}
		TrashSlot_1.16.1-12.0.1.jar TrashSlot {trashslot@12.0.1 DONE}
		mining-helmet-1.16.1-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		vanillaexcavators-1.16.1-2.1.1.jar Vanilla Excavators {vanillaexcavators@2.1.1 DONE}
		Bountiful Baubles FORGE-1.16.1-0.0.1.jar Bountiful Baubles {bountifulbaubles@NONE DONE}
		OldJavaWarning-1.16.1-4.0.1.jar OldJavaWarning {oldjavawarning@4.0.1 DONE}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
		kubejs-2.7.2.51.jar KubeJS {kubejs@2.7.2.51 DONE}
		metalbarrels-3.2.jar Metal Barrels {metalbarrels@3.2 DONE}
		the-conjurer-1.16.1-1.0.6.jar The Conjurer {conjurer_illager@1.0.6 DONE}
		Abnormals-Core-1.16.1-v2.0.0.jar Abnormals Core {abnormals_core@2.0.0 DONE}
		Bamboo-Blocks-1.16.1-2.0.0.jar Bamboo Blocks {bamboo_blocks@NONE DONE}
		Buzzier-Bees-1.16.1-2.0.0.jar Buzzier Bees {buzzier_bees@2.0.0 DONE}
		Mekanism-1.16.1-10.0.3.426.jar Mekanism {mekanism@10.0.3 DONE}
		caelus-FORGE-1.16.1-2.0-beta5.jar Caelus API {caelus@FORGE-1.16.1-2.0-beta5 DONE}
		invtweaks-1.16.1-1.0.5.jar Inventory Tweaks Renewed {invtweaks@1.16.1-1.0.5 DONE}
		Waystones_1.16.1-7.0.2.jar Waystones {waystones@7.0.2 DONE}
		PassableFoliage-1.16.1-2.0.1.jar Passable Foliage {passablefoliage@2.0.1 DONE}
		Clumps-6.0.0.3.jar Clumps {clumps@6.0.0.3 DONE}
		light-overlay-5.4.1.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		comforts-FORGE-1.16.1-3.0.jar Comforts {comforts@FORGE-1.16.1-3.0 DONE}
		NaturesCompass-1.16.1-1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 DONE}
		Artifacts-1.16.1-2.4.0.jar Artifacts {artifacts@1.16.1-2.4.0 DONE}
		[1.16.1]-additionalbars-1.5.0.jar Additional Bars {additionalbars@1.5.0 DONE}
		decorative_blocks-7a.jar Decorative Blocks {decorative_blocks@7a DONE}
		BotanyPots-1.16.1-3.0.4.jar BotanyPots {botanypots@3.0.4 DONE}
		engineerstools-1.16.1-1.0.9-b2.jar Engineer's Tools {engineerstools@1.0.9-b2 DONE}
		curioofundying-FORGE-1.16.1-4.0.jar Curio of Undying {curioofundying@FORGE-1.16.1-4.0 DONE}
		FarmingForBlockheads_1.16.1-7.0.1.jar Farming for Blockheads {farmingforblockheads@7.0.1 DONE}
		snowundertrees-1.16.1-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		pedestals-0.5a.jar Pedestals {pedestals@0.5a DONE}
		bedspreads-FORGE-1.16.1-4.0.jar Bedspreads {bedspreads@FORGE-1.16.1-4.0 DONE}
		additional_lights-1.16.1-2.1.0.jar Additional Lights {additional_lights@1.16.1-2.1.0 DONE}
		environmentalcreepers-forge-1.16.1-1.6.1.jar Environmental Creepers {environmentalcreepers@1.6.1 DONE}
		Interactio-1.16.1-2.0.4.jar Interactio {interactio@1.16.1-2.0.4 DONE}
		ToastControl-1.16.1-4.0.0.jar Toast Control {toastcontrol@4.0.0 DONE}
		PackingTape-1.16.1-0.9.6.jar Packing Tape {packingtape@0.9.6 DONE}
		extradisks-1.16.1-1.3.jar Extra Disks {extradisks@1.3 DONE}
		campfiretorches-1.16.1-1.0.2.jar Campfire Torches {campfiretorches@1.16.1-1.0.2 DONE}
		forge-1.16.1-32.0.75-universal.jar Forge {forge@32.0.75 DONE}
		Waddles-1.16.1-0.8.7.jar Waddles {waddles@1.16.1-0.8.7 DONE}
		PassthroughSigns-1.16.1-2.3.5.jar Passthrough Signs {passthroughsigns@1.16.1-2.3.5 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		CraftingTweaks_1.16.1-12.0.4.jar Crafting Tweaks {craftingtweaks@12.0.4 DONE}
		forge-1.16.1-32.0.75-server.jar Minecraft {minecraft@1.16.1 DONE}
		The-Endergetic-Expansion-1.16.1-2.0.0.jar The Endergetic Expansion {endergetic@2.0.0 DONE}
		EnchantmentDescriptions-1.16.1-3.0.2.jar EnchantmentDescriptions {enchdesc@3.0.2 DONE}
		theoneprobe-1.16-3.0.1-beta.jar The One Probe {theoneprobe@1.16-3.0.1-beta DONE}
		MouseTweaks-2.13-mc1.16.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.16.1-1.14.2.jar Tool Belt {toolbelt@1.14.2 DONE}
		titanium-1.16.1-3.0.2.jar Titanium {titanium@3.0.2 DONE}
		ImmersiveEngineering-0.16-109.jar Immersive Engineering {immersiveengineering@0.16-109 DONE}
		morevanillalib-1.16.1-1.2.8.jar MoreVanillaLib {morevanillalib@1.2.8 DONE}
		LargeFluidTank-16.0.2.jar FluidTank {fluidtank@16.0.2 DONE}
		Xaeros_Minimap_20.17.0_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.17.0 DONE}
		JAOPCA-1.16.1-3.3.0.2.jar JAOPCA {jaopca@3.3.0.2 DONE}
		rats-6.0.4-1.16.1.jar Rats {rats@6.0.4 DONE}
		serverconfigupdater-1.2.jar ServerConfig Updater {serverconfigupdater@1.2 DONE}
		FastWorkbench-1.16.1-4.1.1.jar FastWorkbench {fastbench@4.1.1 DONE}
		AutoRegLib-1.6-42.jar AutoRegLib {autoreglib@1.6-42 DONE}
		Quark-r2.2-255.jar Quark {quark@r2.2-255 DONE}
		StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 DONE}
		vanillahammers-1.16.1-2.1.1.jar Vanilla Hammers {vanillahammers@2.1.1 DONE}
		scaffoldingpower-1.16.1-1.2.1.jar Scaffolding power {scaffoldingpower@1.16.1-1.2.1 DONE}
		FastFurnace-1.16.1-4.0.0.jar FastFurnace {fastfurnace@4.0.0 DONE}
		Actually Useful Stonecutter-1.0.1 mc 1.16.1.jar Actually Useful Stonecutter {actuallyusefulstonecutter@1.0.1 mc 1.16.1 DONE}
		World-Stripper-1.7.2-1.16.1.jar World Stripper {worldstripper@1.7.2 DONE}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.16.1-1.1.1-b4.jar Engineer's Decor {engineersdecor@1.1.1-b4 DONE}
		connectedglass-1.0.6-mc1.16.jar Connected Glass {connectedglass@1.0.6 DONE}
		modular-routers-1.16.1-7.0.0-24.jar Modular Routers {modularrouters@1.16.1-7.0.0-24 DONE}
		refinedstorageaddons-0.7.jar Refined Storage Addons {refinedstorageaddons@0.7 DONE}
		CosmeticArmorReworked-1.16.1-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.1-v1a DONE}
		overloadedarmorbar-5.0.0.jar Overloaded Armor Bar {overloadedarmorbar@5.0.0 DONE}
		EnderMail-1.16.1-1.1.2.jar Ender Mail {endermail@1.16.1-1.1.2 DONE}
		DefaultOptions_1.16.1-12.0.1.jar Default Options {defaultoptions@12.0.1 DONE}
		bigbuckets-1.1.1.jar BigBuckets {bigbuckets@1.1.1 DONE}
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
	Player Count: 2 / 20; [ServerPlayerEntity['PlayerOne'/1026, l='ServerLevel[world]', x=-139.99, y=11.00, z=96.41], ServerPlayerEntity['PlayerTwo'/2049, l='ServerLevel[world]', x=-153.07, y=60.00, z=165.46]]
	Data Packs: vanilla, mod:netherportalfix (incompatible), mod:rad, mod:bambooeverything (incompatible), mod:modnametooltip (incompatible), mod:kleeslabs (incompatible), mod:rsgauges, mod:pitg, mod:bettercaves, mod:xaeroworldmap, mod:ctm, mod:cookingforblockheads (incompatible), mod:controlling, mod:reauth, mod:placebo (incompatible), mod:dankstorage (incompatible), mod:citadel (incompatible), mod:powah, mod:rangedpumps, mod:culinaryconstruct (incompatible), mod:bookshelf (incompatible), mod:uteamcore, mod:randompatches (incompatible), mod:mcwdoors, mod:morpheus (incompatible), mod:mekanismgenerators, mod:carpetstairsmod, mod:cauldronrecipes (incompatible), mod:maessentials (incompatible), mod:fpsreducer, mod:jeresources (incompatible), mod:laserrelays (incompatible), mod:refinedstorage, mod:structure_gel, mod:packmenu (incompatible), mod:mcwbridges, mod:industrialforegoing (incompatible), mod:usefulbackpacks, mod:tipthescales, mod:biomesoplenty, mod:toolstats (incompatible), mod:lollipop, mod:dogslie, mod:dungeons_plus, mod:masonry, mod:simplylight, mod:curios (incompatible), mod:patchouli (incompatible), mod:cakechomps (incompatible), mod:elevatorid, mod:ftbultimine, mod:mekanismtools, mod:curiouselytra (incompatible), mod:aiimprovements (incompatible), mod:globalxp, mod:cherishedworlds (incompatible), mod:productivebees, mod:cloth-config, mod:trashcans, mod:tramplestopper (incompatible), mod:inventoryessentials (incompatible), mod:betterburning (incompatible), mod:bwncr (incompatible), mod:fastleafdecay, mod:servertabinfo, mod:prettybeaches (incompatible), mod:bettermineshafts, mod:darkpaintings (incompatible), mod:dangerousstonecutter, mod:betteradvancements (incompatible), mod:dwarfcoal (incompatible), mod:bedbenefits (incompatible), mod:ma-enchants (incompatible), mod:trashslot (incompatible), mod:mining_helmet (incompatible), mod:vanillaexcavators, mod:oldjavawarning (incompatible), mod:jei (incompatible), mod:kubejs (incompatible), mod:metalbarrels, mod:conjurer_illager, mod:abnormals_core, mod:bamboo_blocks (incompatible), mod:buzzier_bees, mod:mekanism, mod:caelus (incompatible), mod:invtweaks (incompatible), mod:waystones (incompatible), mod:passablefoliage, mod:clumps (incompatible), mod:lightoverlay-forge (incompatible), mod:comforts (incompatible), mod:naturescompass (incompatible), mod:artifacts, mod:additionalbars, mod:decorative_blocks, mod:botanypots (incompatible), mod:engineerstools, mod:curioofundying (incompatible), mod:farmingforblockheads (incompatible), mod:snowundertrees, mod:pedestals, mod:bedspreads (incompatible), mod:additional_lights, mod:interactio, mod:toastcontrol (incompatible), mod:packingtape, mod:extradisks, mod:campfiretorches, mod:forge, mod:waddles (incompatible), mod:passthroughsigns, mod:ironchest, mod:craftingtweaks (incompatible), mod:enchdesc (incompatible), mod:theoneprobe (incompatible), mod:mousetweaks (incompatible), mod:toolbelt (incompatible), mod:titanium (incompatible), mod:immersiveengineering (incompatible), mod:morevanillalib, mod:fluidtank, mod:xaerominimap, mod:rats (incompatible), mod:serverconfigupdater, mod:fastbench (incompatible), mod:storagedrawers (incompatible), mod:vanillahammers, mod:fastfurnace (incompatible), mod:actuallyusefulstonecutter (incompatible), mod:worldstripper (incompatible), mod:appleskin, mod:engineersdecor, mod:connectedglass, mod:modularrouters, mod:refinedstorageaddons, mod:cosmeticarmorreworked (incompatible), mod:overloadedarmorbar (incompatible), mod:endermail (incompatible), mod:defaultoptions (incompatible), mod:bigbuckets (incompatible), mod:snowrealmagic, mod:torchmaster (incompatible), mod:toughnessbar (incompatible), mod:simplefarming, mod:simplybackpacks (incompatible), mod:strongersnowballs (incompatible), mod:quarkoddities, mod:kiwi, mod:bountifulbaubles (incompatible), mod:environmentalcreepers (incompatible), mod:endergetic (incompatible), mod:jaopca (incompatible), mod:autoreglib (incompatible), mod:quark, mod:scaffoldingpower (incompatible), inmemory:jaopca (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Shindur** [comment]
This was being caused by RandomPatches. I put an issue on their github about it and it has been fixed, Niller just needs to update the mod in the next release. Until then, you can update the mod yourself if you're playing by yourself or on a private server
https://github.com/TheRandomLabs/RandomPatches/issues/115

**Comment by NillerMedDild** [comment]
Thanks @Shindur, and thanks Beralath for the bug report :)
@Beralath, please don't ever paste logs into an issue, it's very hard to read. Instead use a pasting website such as gist.github.com or pastebin.com

**Comment by nepphhh** [comment]
I don't believe it's caused by RandomPatches, it's a bug in the vanilla codebase somehow exposed by something modded. RandomPatches seeks to fix it, but it doesn't seem to quite yet be fixed. I opened a new thread for its discussion at TheRandomLabs/RandomPatches#116, as non-Enigmatica users are also suffering from it.
