### ISSUE TITLE
[Expert] quest dependency change - mutiservo press

### ISSUE THREAD

**Issue by gruff8** [NillerMedDild/Enigmatica6#3901]
### Describe your suggestion

Change multiservo press quest dependency.
Currently it is dependent on superheated steel ingot, but there is no superheated steel ingot involved in the craft, neither a comressed iron ingot.
It is just steel, which is obtainable without having to do superheater steel.

### Why would you like this added/changed?

Quest is currently gated (albeit slightly) by an unrelated quest.
You could always add it to the requirements for the next quest (Hot compressed iron) or just mention that it is needed to make hot compressed iron.
Or maybe it is fine as it is...

**Comment by TemperedFool** [comment]
The (temporary) tech quests are laid out to help you through the progress you need to progress. After you produce superheated ingots you'll need the multiservo press to pack them, so the quest comes after.

**Comment by gruff8** [comment]
Fair enough. 
I think for craftable items it is anoying if you have to go through the process again, but I guess the multiservo press can just be broken and replaced to complete so not a bit thing.
