### ISSUE TITLE
Additional Lanterns:E6 and E8

### ISSUE THREAD

**Issue by YashTFEM** [NillerMedDild/Enigmatica6#3902]
### URL

https://www.curseforge.com/minecraft/mc-mods/additional-lanterns.

### Why would you like the mod added?

It's QoL building mod that adds a whole bunch of dyeable lanterns, and many different types of material based lanterns to go with your base. For example a sandstone lantern. Also adds redstone controlled lanterns.

**Comment by HopeNotDespair** [comment]
Seconded

**Comment by NillerMedDild** [comment]
> Seconded

Noted, but please use thumbs up to upvote/agree 😀

**Comment by YashTFEM** [comment]
So will it be considered?

**Comment by NillerMedDild** [comment]
Of course, haven't had time to have a look yet  though.

**Comment by NillerMedDild** [comment]
Iirc we already had this at one point but removed it due to feature overlap. Sorry but no.
