### ISSUE TITLE
Passive Shield Mod

### ISSUE THREAD

**Issue by juh9870** [NillerMedDild/Enigmatica6#3906]
### URL

https://www.curseforge.com/minecraft/mc-mods/passive-shield

### Why would you like the mod added?

This mod makes shields better by hiding them from view when they are on off-hand but not held up, and also allows configuring damage negation of a shield that is held on off-hand but not actively used.

**Comment by NillerMedDild** [comment]
Hmm. Have you tested this in E6? ClientTweaks already lowers the shield when it's not used.

**Comment by juh9870** [comment]
Will test this mod tomorrow. Current shield lowering still quite annoying on a screen, but I guess it's depends on player preferences

**Comment by juh9870** [comment]
Tested it a bit. All shields except for IE Heavy Plated Shield work fine, as in being completely hidden from screen when held in off-hand, and also reducing received damage by 33%. IE shield is not affected by this mod at all, it seems like - no hiding and no passive damage mitigation

**Comment by NillerMedDild** [comment]
Thanks for testing. I don't really want that to be honest :/ completely hidden and passive damage reduction that is.
