### ISSUE TITLE
Fix Resourceful Bees

### ISSUE THREAD

**Issue by FooterMan14** [NillerMedDild/Enigmatica6#3915]
### Describe your suggestion

With the change to not allow for Beehives to be used/crafted, that also makes the player unable to harvest the combs in any way with the tiered nest, shears don't work neither do scrapers.

### Why would you like this added/changed?

Makes the entire mod useless without this functionality.

**Comment by TemperedFool** [comment]
As indicated by the quests, use the world-gen bee nests (from the mod), these produce resourceful combs and are harvestable with shears or scrapers.
