### ISSUE TITLE
connection closed - mismatched mod channel list

### ISSUE THREAD

**Issue by ChrisVisser** [NillerMedDild/Enigmatica6#3918]
### Modpack Version

Enigmatica 6 - E6 - 1.16.5 (0.5.21)

### Describe your issue.

Loaded up Enigmatica 6 - E6 - 1.16.5 (0.5.21) both on our server and client side via curseforge and we're getting this error on log in, "connection closed - mismatched mod channel list".

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by YashTFEM** [comment]
That happens to me sometimes. I just go back and relogin after repairing the instance on curse. Works all the time

**Comment by ChrisVisser** [comment]
Unfortunately that didn't fix the problem. We have two clients trying to log into the server from different parts of the continent and both have this error.

**Comment by ChrisVisser** [comment]
![support](https://user-images.githubusercontent.com/24770351/146487872-c56f1359-9654-4ead-938c-85e7a6761bfc.png)
This is what your discord support page looks like.

**Comment by YashTFEM** [comment]
Firstly you need to read the welcome rules, and react to the first picture to gain access
