### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by xLilRaiderx** [NillerMedDild/Enigmatica6#3927]
### Modpack Version

0.5.21

### Describe your issue.

Trying to host this modpack on a server. The server host explained that for some reason Enigmatica 6 keeps resetting the Max Tick Time on the server, which then causes it to crash.

### Crash Report

https://gist.github.com/xLilRaiderx/4ed91f051888668a52967c2766c985f4

### Latest Log

https://gist.github.com/xLilRaiderx/b9c5f13ecc1bff2ced295d71d64ad99e

### Have you modified the modpack?

Yes

### User Modifications

Added Advanced Performance Tweaks mod.
Modified config for Alex's Mobs to turn down mob spawns.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
I recommend that you try removing Advanced Performance Tweaks, if that doesn't help please reach out on our support channel on Discord linked above :)
