### ISSUE TITLE
Astral Sorcery Cave illuminator breaks nearby Mekanism multiblock machines

### ISSUE THREAD

**Issue by Samfucious** [NillerMedDild/Enigmatica6#3930]
### Modpack Version

Enigmatica6_0.5.11

### Describe your issue.

I have a large 11x18x11 Mekanism thermoelectic boiler and 11x18x11 turbine in the basement of my base.

- When I place a Astral Sorcery cave illuminator, it places illumination powder instances inside the machines, breaking them until manually removed.
- Once manually removed, the illumination powder is replaced by the cave illuminator within a few moments.

The only current workaround seems to be to remove the cave illuminator.

### Have you modified the modpack?

Yes

### User Modifications

On my server, I've added woot-1.16.5-1.0.8.0.jar

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
This is normal. Those multiblocks break if there are any invalid blocks inside them... And the cave illuminator places blocks.

Just keep them away from each other.
