### ISSUE TITLE
Crash when looking up Tank or Ender In JEI.

### ISSUE THREAD

**Issue by HeavyDeception** [NillerMedDild/Enigmatica6#3931]
### Modpack Version

0.5.21

### Describe your issue.

I crash every time I look up ender or tank in JEI.

### Crash Report

https://puu.sh/IxaRk/89488d6497.txt

### Latest Log

I don't know were this is.

### Have you modified the modpack?

Yes

### User Modifications

[Better Than Mending](https://www.curseforge.com/minecraft/mc-mods/better-than-mending), [Bountiful Baubles](https://www.curseforge.com/minecraft/mc-mods/bountifulbaubles), [Enigmatic Legacy](https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy) and, [Diagonal Fences](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences).

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by HeavyDeception** [comment]
I have optifine to and I tried running it with it uninstalled but it still crashed just looking in the files and it was still in there so it's most likely the cause of the crash so I'm removing it now.

**Comment by MuteTiefling** [comment]
You should really try this without all the extra mods as I'm not seeing this in the base pack.

**Comment by HeavyDeception** [comment]
I did must have missed one will try and see what's going on but I'm not at my pc right now.

**Comment by HeavyDeception** [comment]
I removed everything 1 at a time then I removed the ender storage mod and it works now.

**Comment by HeavyDeception** [comment]
I don't know what's going on right now.

**Comment by MuteTiefling** [comment]
Now that it's fixed, are you able to reproduce the issue upon re-adding enderstorage?

I thinking here is that something you added broke it badly enough that even removing the faulty mod didn't correct it; you needed to actually remove the faulting tank from the world. Removing Enderstorage was a heavy handed, but effective way to do so. Should be able to add it back now, however.

**Comment by HeavyDeception** [comment]
Ya when I readd the mod it crashes when I look for it in jei I wish I could read the crash reports better.

**Comment by NillerMedDild** [comment]
Crash report without OptiFine would be helpful :)

**Comment by HeavyDeception** [comment]
https://puu.sh/IxeyE/09440fe4ab.txt I will have to test it when I wake up tomorrow. even when I remove all the mods it happens.

**Comment by Darkere** [comment]
Please also make sure you have no items from tinkers on your person when you try next time. (armor, inventory, baubles)

**Comment by HeavyDeception** [comment]
I have no items from T.C. on me.

**Comment by HeavyDeception** [comment]
@Darkere ok, so I fixed it thank you. Because you said that I downgraded TC and Mantal I had updated them to mess with the armor and stuff. so if you go to update it look out for that.
