### ISSUE TITLE
Oreo Bees don't work in regular Nests.

### ISSUE THREAD

**Issue by FooterMan14** [NillerMedDild/Enigmatica6#3934]
### Describe your suggestion

Oreo Bees cannot produce oreos in regular nests, as I have seen on a server that I found one on. Not even when you upgrade the nests, it still doesn't do anything. Sped it up with a Time in a Bottle, nothing happened. Just bee noises. Can we get a fix?

### Why would you like this added/changed?

Oreo bees are useless now.

**Comment by MuteTiefling** [comment]
They appear to be working fine for me in a Resourceful Bees Oak Nest. What sort of nest are you trying exactly? Can you post screenshots of your setup?

**Comment by HopeNotDespair** [comment]
When he says regular nest, I believe he means minecraft nest and not resourceful bees nest

**Comment by FooterMan14** [comment]
I mean Resourceful Bees Spruce Nest, upgraded to Iron tier.

**Comment by HopeNotDespair** [comment]
Why didn't you submit this in issue format? Which version BTW?

**Comment by FooterMan14** [comment]
0.5.21

**Comment by MuteTiefling** [comment]
Ok. There were some changes around that whole system not long ago. It may be best to pick up and re-place the nest to just sort of reset its NBT. 

I'll try upgrading mine to iron tier as well and double check.

**Comment by FooterMan14** [comment]
didn't think this was worth a bug tag

**Comment by MuteTiefling** [comment]
It's fine... Hope is not the police ^_~

**Comment by FooterMan14** [comment]
![unknown](https://user-images.githubusercontent.com/71946346/146801842-24a913b8-dc39-4062-8df8-585f23ae14a2.png)

**Comment by HopeNotDespair** [comment]
Is there a block in front of the face?

**Comment by FooterMan14** [comment]
Nope

**Comment by FooterMan14** [comment]
Front is next to the flower

**Comment by FooterMan14** [comment]
I just left so I can't get more images

**Comment by FooterMan14** [comment]
I'll get back on one moment

**Comment by MuteTiefling** [comment]
Yeah, not having any trouble with a fresh spruce hive upgraded to tier 1. They're making oreos in there and they eventually pop out as expected. 
![2021-12-20_11 49 26](https://user-images.githubusercontent.com/9543430/146802932-99a1fc2c-9a52-42c5-9512-d9dd8fd8207c.png)

**Comment by FooterMan14** [comment]
Face is not covered correct?

**Comment by FooterMan14** [comment]
on your nest

**Comment by MuteTiefling** [comment]
nah, that's the back of my setup. the front is around the other side inside the box

**Comment by FooterMan14** [comment]
Joining back to the server to make sure its correct

**Comment by FooterMan14** [comment]
If not placed correctly I can probably smack it with a thermal hammer

**Comment by MuteTiefling** [comment]
Only thing that should keep the bees from popping out is if the face is covered or it's night, really.

**Comment by MuteTiefling** [comment]
![2021-12-20_11 52 41](https://user-images.githubusercontent.com/9543430/146803320-9bee324a-6940-4ff7-86de-093f75f1480c.png)
this is the front, btw. I've upgraded to emerald tier at this point

**Comment by FooterMan14** [comment]
![image](https://user-images.githubusercontent.com/71946346/146803383-c1cab300-d333-4e0c-b60a-0bddce756e4a.png)

**Comment by FooterMan14** [comment]
working on it

**Comment by FooterMan14** [comment]
![2021-12-20_11 54 47](https://user-images.githubusercontent.com/71946346/146803622-89180abd-52ff-48ca-bca1-0ac0c228f46a.png)
oh it is covered

**Comment by FooterMan14** [comment]
Yeah that was the issue, I smacked it with a thermal wrench and it fixed.
