### ISSUE TITLE
EE Unifications

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#394]
Notes on a few things I'm finding while hiding stuff

Coal Coke might need an extra pass. Seems like everything is using IE's instead of EEs

Precision Sawmill is still producing Mek saw dust instead of EE's

Thermal Sawmill is producing Thermal's saw dust for Warped Stems and Crimson Stems only.

**Comment by NillerMedDild** [comment]
Actually EE doesn't have Coal Coke, maybe worth adding @Ridanisaurus ?

**Comment by NillerMedDild** [comment]
Sawdust fixed, thanks!

**Comment by NillerMedDild** [comment]
Coal Coke not fixed yet, but we can live with it for now :D
