### ISSUE TITLE
Null Pointer Exception Error

### ISSUE THREAD

**Issue by ItsChase7** [NillerMedDild/Enigmatica6#3941]
### Modpack Version

0.5.21

### Describe your issue.

When trying to join a server for Enigmatica 6, it gets to loading terrain and it crashes. I get the crash report below, and I don't know what it means

### Crash Report

[crash-2021-12-22_11.55.06-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/7764131/crash-2021-12-22_11.55.06-client.txt)

### Have you modified the modpack?

Yes

### User Modifications

I have optifine

### Did the issue happen in singleplayer or on a server?

Server

**Comment by ItsChase7** [comment]
I also tried removing optifine

**Comment by Darkere** [comment]
I'm pretty certain we don't have mobgriding utils in the pack...
