### ISSUE TITLE
Can't craft expert Token of Anger

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#3944]
### Modpack Version

Expert dev 23/dec

### Describe your issue.

For some reason, I just can't craft a Token of Anger, in my main world or test, legit or cheated in items. Nothing showing up in the log. The recipe is showing up in JEI, and seems to match whats in my copy of tree_ritual.js, and I've re-applied /mode expert.

![image](https://user-images.githubusercontent.com/2611674/147297765-dd7dbc43-ddfa-4717-b138-9b0aaaa46692.png)

![image](https://user-images.githubusercontent.com/2611674/147297779-55aac4b3-0a00-4c61-9bc2-160e1bc9c803.png)

Token of Joy works:
![image](https://user-images.githubusercontent.com/2611674/147298116-7c23fb5e-fc34-4317-bbc4-378f6178b1b6.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Looks like I missed a few more things with the refactor. Should be good now. Can you pull again and give it a try?

**Comment by Rodg88** [comment]
yep, fixed it
