### ISSUE TITLE
/sethome isnt working

### ISSUE THREAD

**Issue by SpoopyPumpkin** [NillerMedDild/Enigmatica6#3949]
### Modpack Version

enigmatica6 0.5.21

### Describe your issue.

The commands /sethome and /back are no longer working for me. Am I doing something wrong or have the commands been removed, please help.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
These are disabled by default. The wiki explains how to re enable them.

**Comment by SpoopyPumpkin** [comment]
Do I search a modpack for that ? I dont know which one it comes on

**Comment by Darkere** [comment]
https://github.com/NillerMedDild/Enigmatica6/wiki/Commands
