### ISSUE TITLE
Aquaculture Fillet Knife Blasting Recipe

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#395]
Conflicting recipe here. All fillet knives can be blasted to iron nuggets (including the wood one). 

They each have multiple potential outputs too. 

![image](https://user-images.githubusercontent.com/9543430/99884548-13923000-2bfd-11eb-9cce-e832d86a7697.png)

**Comment by NillerMedDild** [comment]
This bug makes zero sense, Aquaculture doesn't add these recipes :s

**Comment by MuteTiefling** [comment]
I can only guess it's coming from the tags somehow. The neptunium one should recycle to a bar though.

**Comment by NillerMedDild** [comment]
Yup I can confirm tag weirdness, removed the knife recycle recipes completely.
