### ISSUE TITLE
SushiGo nori recipe not working

### ISSUE THREAD

**Issue by timidbacon** [NillerMedDild/Enigmatica6#3955]
### Modpack Version

0.5.21

### Describe your issue.

When trying to make nori sheets from SushiGo pack and I have the setup as described/how I've set it up in previous packs but when I pull the lever, nothing happens.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Why did you close this issue? :)
