### ISSUE TITLE
Mud ball recipe bug

### ISSUE THREAD

**Issue by Mana97** [NillerMedDild/Enigmatica6#3957]
### Modpack Version

0.5.21

### Describe your issue.

When trying to craft mud ball from Environmental i place on the crafting table 8 dirt and a bucket of water like the recipe, but instead of 16 mud balls i obtain 8 mud blocks from Oh The Biomes You'll Go. I'm playing Expert mode.  I have notice that both mud ball (Environmental) and Mud Blocks (Oh The Biomes You'll Go) have the same recipe.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment]
This should be fixed indev by #3823.

Also, we would very strongly suggest playing on the dev version from GitHub for expert, if at all - the curseforge release is very far behind at this point.

**Comment by Mana97** [comment]
Am i supposed to use the stonecutter? It doesnt work

**Comment by TemperedFool** [comment]
Are you playing the version off curseforge (0.5.21) or pulling the develop branch and playing on that? The fixes have not been published to CF yet.

**Comment by Mana97** [comment]
Im playing the forge version. How can i pull the develop branch?

**Comment by TemperedFool** [comment]
https://github.com/NillerMedDild/Enigmatica6#setup

You should update once a week or so, at least - outside of quiet holiday time stuff is changed every day or two.

**Comment by Mana97** [comment]
I'm struggling with point 6: fork and clone. What i'm supposed to do? Sorry for my bad understanding..

**Comment by hofmannk69** [comment]
You did point 6, now just do the commands below that and use the url to your github repository ( https://github.com/Mana97/Enigmatica6 )

**Comment by MuteTiefling** [comment]
You'd be best bringing this discussion to the support channel in Discord.
