### ISSUE TITLE
Wrong Recipe Crusher : mana gem -> mana powder (botania)

### ISSUE THREAD

**Issue by FutureLegion** [NillerMedDild/Enigmatica6#404]
![image](https://user-images.githubusercontent.com/39351347/99921768-36bffb00-2d35-11eb-8c06-be19d5ca4988.png)

e6 0.3.0

**Comment by NillerMedDild** [comment]
We're aware of the issue, I didn't realize non-Botania mana dust was a thing though, will look into it.
