### ISSUE TITLE
Steel can be created in a vanilla blast furnace non-coal fuel

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#405]
**Modpack version**
Enigmatica 6 0.3.0

**Issue**
You can create steel in a vanilla blast furnace. Not 100% sure this is an issue, but the fact that it can be created with a lava bucket as fuel seems fishy. Also it seems that this is only possible with an iron block and not iron ingots, which also leads me to believe something is weird here.

https://media.discordapp.net/attachments/726178356143456287/780250177067024394/unknown.png

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Not meant to happen, thanks for letting us know!

**Comment by KrAzYGEEK32** [comment]
found 2 more steel conficts, iron nugget -> steel nugget, iron plate -> steel plate in vanilla blast furnace
