### ISSUE TITLE
artifacts 1.16.4

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#406]
the mod got a release for it a few days before the pack updated, and was probably removed before that happened, looks like at least 3+ people in the discord would welcome its return with open arms: https://www.curseforge.com/minecraft/mc-mods/artifacts/files

**Comment by Ridanisaurus** [comment]
This has my vote. I found Artifacts made exploring, and risking death to Mimics, quite rewarding.
As far as the power level of these Artifacts, then that's a whole different story :D

**Comment by NillerMedDild** [comment]
Consider it done! I was a bit unsure whether to readd it tbh, now that we have Lost Trinkets.
