### ISSUE TITLE
[Mod suggestion] Immersive Petroleum

### ISSUE THREAD

**Issue by Dasavanth** [NillerMedDild/Enigmatica6#407]
just mentioning it updated to 1.16.4, i love the mod and would love to see it in the pack
https://www.curseforge.com/minecraft/mc-mods/immersive-petroleum/files/3109197

**Comment by NillerMedDild** [comment]
I'll think about it :)

**Comment by NillerMedDild** [comment]
This will be added but not in 0.3.1, because it currently does not work with the latest IE update.
