### ISSUE TITLE
Quest for Latex Processing Unit

### ISSUE THREAD

**Issue by Master2Mind88** [NillerMedDild/Enigmatica6#412]
**Modpack version**
0.3.0

**Issue**
The Quest for Latex Processing Unit Is Not Finding the Item that I have in inventory.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Found and fixed the issue, thanks again :)

**Comment by Dasavanth** [comment]
just to make sure, the bug was it being dependant on an obscure IE quest right?

**Comment by NillerMedDild** [comment]
Some obscure dependency yup :)
