### ISSUE TITLE
Unification cleanup appears to have broken

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#415]
**Modpack version**
0.3.0

**Issue**
Could've sworn this was working before. Still seeing all plates/gears/ingots other than EE ones. 

**Logs**

**Comment by NillerMedDild** [comment]
Hmm, works fine on my end :s could I have a latest log from you please?

**Comment by MuteTiefling** [comment]
Sure, attached below.

Just restarted my client and hopped on the server again today and seeing the same thing. Have not checked single player yet.

![image](https://user-images.githubusercontent.com/9543430/100158694-9673ee80-2e7a-11eb-9768-91e298ea9c90.png)


[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5593101/latest.log)

**Comment by MuteTiefling** [comment]
Hmm, yes, it's working fine on single player, just not on the official server.

**Comment by NillerMedDild** [comment]
Hm alright :/

**Comment by NillerMedDild** [comment]
Dammit, also confirmed on dev server :P

**Comment by NillerMedDild** [comment]
I think this may be because of me using global variables from startup in client scripts, I asked Lat on le Discords.

**Comment by NillerMedDild** [comment]
should be good now, I went back to your method, so thanks :D
