### ISSUE TITLE
Grass shows as white on (mini)map

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica6#416]
**Modpack version**
0.3.0

**Issue**
![java_iv3x63bhvc](https://user-images.githubusercontent.com/13875/100080733-7a565a00-2e46-11eb-9d4d-371d496bf4f8.png)

Both byg:grassland_plateau and biomesoplenty:scrubland, so it's not biome specific

**Comment by hvdklauw** [comment]
Related: https://github.com/FTBTeam/FTB-Chunks/issues/52

**Comment by hvdklauw** [comment]
What's really weird is that it was working fine in one world, then I created a new one and things broke.

**Comment by hvdklauw** [comment]
Created a new world and it doesn't have the problem

**Comment by hvdklauw** [comment]
Reloading the instance fixed it for that world... so weird

**Comment by hvdklauw** [comment]
Gonna close this, couldn't reproduce it

**Comment by NillerMedDild** [comment]
Thanks for the report regardless :)
