### ISSUE TITLE
Multiple steel recipe issues

### ISSUE THREAD

**Issue by Aelphais** [NillerMedDild/Enigmatica6#417]
**Modpack version**
0.3.0

**Issue**
JEI is showing me both Immersive Engineering Steel Fence and Mapper Base Steel Fence. Both have the same recipe, but it seems as if the Mapper Base fence is the one that actually gets produced. Which wouldn't be much of an issue except the quest for Immersive Engineering's Crusher wants the IE version of the fence in inventory, as does the IE book. In addition, the Crusher cannot be constructed with Mapper Base fences. I had to cheat in the IE ones.

Crafting a steel rod via a crafting table is listed in JEI as two steel ingots, one on top of the other. However, this seems to change the version of steel, producing two steel ingots from a different mod (not EE, not sure which, but it cycles through if I put the two back into the crafting table). However, two different types of steel ingots can be used to craft a steel rod (ie. one EE ingot and one IE ingot in the usual rod recipe). So there is that oddity.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Ridanisaurus** [comment]
I also noticed that attempting to craft Steel Armor gets you the Helmet + Boots from Mekanism Steel Armor, and Chest + Leggings from MapperBase.

**Comment by NillerMedDild** [comment]
Damn random lib items :P

**Comment by Aelphais** [comment]
Just downloaded the development branch and noticed that the fence issue has been fixed, however the ingot->rod issue is still present.

https://i.imgur.com/wggxgaq.png

**Comment by NillerMedDild** [comment]
Ah right, I forgot this was a two-part bug report, thanks for the reminder :)
