### ISSUE TITLE
Oil Generation in Byg-End bioms

### ISSUE THREAD

**Issue by FutureLegion** [NillerMedDild/Enigmatica6#419]
![image](https://user-images.githubusercontent.com/39351347/100238931-70f9ea00-2f39-11eb-8481-3d71fe403c40.png)

1.16.4

**Comment by FutureLegion** [comment]
It's hapening with nether too, byg biomes

**Comment by NillerMedDild** [comment]
Thanks, we'll get that fixed :)

**Comment by MuteTiefling** [comment]
I should have a fairly complete list of BYG biomes to update this now. The IF Laser Drill will also need the same list.
