### ISSUE TITLE
0.2.2 - Server blows up on player login - Related to Crafting Station/Extra Tags

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica6#42]
**Modpack version**
0.2.2

**Issue**
Server blows up on player login - Related to Crafting Station/Extra Tags

**Logs**
https://pastebin.com/hzw0JCqj
Note, that's from user Atropo, but I verified on my machine as well. 

If you remove crafting station and extra tags, users can log in normally.

**Comment by NillerMedDild** [comment]
That's strange, I was able to join my server without issues :s anyhow, thanks for the report, I'll investigate.

**Comment by NillerMedDild** [comment]
I removed them too, sorry about that.

**Comment by NillerMedDild** [comment]
@tfarcenim Since Extra Tags doesn't have an issue tracker, I hope it's okay that I just mention you. Extra Tags for 1.16 crashes on player login on servers.

**Comment by Shindur** [comment]
@NillerMedDild Not sure if this helps, but going to his github profile and going to Extra Tags repo you can get to the issue tracker. https://github.com/Tfarcenim/ExtraTags/issues
