### ISSUE TITLE
No End Dragon or End Fountain (See last comment for fixing worlds updated to 0.3.1, made in 0.3.0)

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#420]
**Modpack version**
E6 0.3.0

**Issue**
This seems to be a known Forge issue for Servers, but the end generates without a Dragon, or an End Fountain. I tried to manually spawn it, and to reset the End, but both didn't work.
It seems that a fix is available, but not 100% sure if it was released yet.
Initial Report: https://github.com/MinecraftForge/MinecraftForge/issues/7510

**Comment by NillerMedDild** [comment]
Spicy bug :P thanks for reporting Rid!

**Comment by ViRb3** [comment]
Check here for workaround: https://github.com/AllTheMods/ATM-6/issues/396
