### ISSUE TITLE
Quark Dungeon and Burred Dungeon spawn in the end

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#423]
**Modpack version**
E6 0.3.0

**Issue**
I forgot to report this when I reported the issue with the end Dim but both Quark Dungeon and Burred Dungeons are spawning in the end.

**Comment by NillerMedDild** [comment]
Oh shit, will get that fixed ^^'

**Comment by NillerMedDild** [comment]
> Burred Dungeons
what's that? :P
