### ISSUE TITLE
Storage Drawers : Make the capacities of full and half the same.

### ISSUE THREAD

**Issue by Esteria** [NillerMedDild/Enigmatica6#4252]
### Describe your suggestion

Make the capacities of full size and half size the same.

### Why would you like this added/changed?

I want to use half the size for decorative reasons.
I don't think the drawback of half the capacity is necessary there.

**Comment by MuteTiefling** [comment]
For as amazingly good as these are, I think it's a fair trade off that a half sized drawer holds... half as much :D

A fully upgraded Half Drawer 1x1 already holds 3.5k stacks, or over a quarter million items and nothing in the pack comes close to requiring that amount of stock on hand.
