### ISSUE TITLE
Mods Suggestion - Environmental Tech , Environmental Energy and Environmental Core

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#426]
They were transplanted to minecraft 1.16.4
https://www.curseforge.com/minecraft/mc-mods/environmental-tech
https://www.curseforge.com/minecraft/mc-mods/environmental-energy
https://www.curseforge.com/minecraft/mc-mods/environmental-core

**Comment by NillerMedDild** [comment]
I'll think on it :)

**Comment by NillerMedDild** [comment]
It's a no for now :)
