### ISSUE TITLE
Stonecutter renamed to Bench Saw by unknown mod

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#427]
**Modpack version**
0.3.0

**Issue**
Tried crafting some vertical half-slabs and they have no recipes. I recalled that being part of the stonecutter and went looking for that but it's not showing in JEI. 

**Logs**

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5605790/latest.log)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MaxFirestorm** [comment]
Just wanted to make a point that the "Stonecutter" is called "Bench Saw" in the pack, just in case.

**Comment by NillerMedDild** [comment]
It's super weird, I wonder  what's renaming it.

**Comment by MaxFirestorm** [comment]
Uncertain. I know there's a mod that's called Actually Useful Stonecutter in the pack so that *might* be it, though I'm not sure.

**Comment by NillerMedDild** [comment]
That isn't it sadly,  I checked  :/

**Comment by MuteTiefling** [comment]
So, Rid has informed me that the lack of vertical slabs is intentional. However, that actually breaks a lot of recipes for Builder's Crafts & Additions. things like book shelves and cupboards all require vertical slabs to craft. Maybe a suitable replacement would be the equivalent wood's trap door?

![image](https://user-images.githubusercontent.com/9543430/100524272-b100dd00-3184-11eb-8e98-787df7141aaa.png)

**Comment by NillerMedDild** [comment]
I'll track the stonecutter recipe issue above in #441

**Comment by DarkAngel22579** [comment]
https://www.curseforge.com/minecraft/mc-mods/buildersaddition Is the mod that's renaming the stonecutter

**Comment by NillerMedDild** [comment]
Awesome, thanks!
