### ISSUE TITLE
simplefarming:raw_bacon recipe uses up the knife

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica6#428]
**Modpack version**
0.3.0

**Issue**
When crafting raw bacon the knife is used up, I think it's either suppose to receive damage or stay (I think the latter tbh).

The knife from Farmers Delight doesn't work, neither the undamage as the damaged one.
The knife from aquaculture totally disappears.

The knife from Xerca Mod is support to craft into Raw sausage but doesn't work at all although JEI says it should.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Seems to be an issue with aquaculture knives only.
The Xerca mod issue is that I disabled the food module of Xerca mod but it's still showing for some reason.
