### ISSUE TITLE
Simple Farming seeds don't work with IE machines

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#429]
**Modpack version**
0.3.0

**Issue**
The Industrial Squeezer and Garden Cloche from IE do not have recipes with the Simple Farming seeds (Plant Oil and farming). The Farmer's Delight seeds are properly supported by both. The similar PnC Thermopneumatic Processing Plant and Botany Pots seem to support the seeds.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Figulus88** [comment]
Simple Farming crops, seeds, and foods also lack recipes for Mekanism's Crusher for making Bio Fuel.

Same with Farmer's Delight crops, seeds, and foods.

They all seem to have recipes for Mek's Nutritional Liquifier though.

**Comment by MuteTiefling** [comment]
I'll take a look at the garden cloche tonight. Looks like it supports datapacks now, so that's a major plus.
