### ISSUE TITLE
Mod Suggestion: Auraddons

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#430]
**Modpack version**
E6 0.3.0

**Enhancement**
This mod was actually suggested by Ellpeck, and it looks cool as an addon to Nature's Aura. Could be worth exploring, and considering.
Link: https://www.curseforge.com/minecraft/mc-mods/auraddons

**Comment by NillerMedDild** [comment]
I've given it a once-over in the past, and I feel like it doesn't add anything unique enough to warrant adding :/

**Comment by Ridanisaurus** [comment]
It seems to be more of a QoL, but yes, nothing essential, just a little more flavor for NA.
However, I can also see why you would flag it as clutter, or non-essential.
