### ISSUE TITLE
Decorative blocks: most beams don't have a recipe

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica6#431]
**Modpack version**
0.3.0

**Issue**
No recipes for most of the beams of decorative blocks
The crimson beam and Warped beam uses 2 stripped log version to craft them, for all the others make sticks.

Either make the rest of the beams the same or add a Bench saw version for the logs to turn them into beams.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
