### ISSUE TITLE
Update mining gadgets to 1.7.1

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica6#434]
**Modpack version**
0.3.0

**Issue**
It crashed when you scroll in the settings screen, this was fixed in 1.7.1.
https://github.com/Direwolf20-MC/MiningGadgets/commit/29ca85a3f1143a04f1bd5cac36f454a8a7f52f0b

**Logs**
[crash-2020-11-28_12.01.55-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/5610459/crash-2020-11-28_12.01.55-client.txt)

**Comment by NillerMedDild** [comment]
Please don't make issues about updating. We will :)
