### ISSUE TITLE
Emendatus Enigmatica Arcane gem can't be used in enchanting aparatus

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica6#435]
**Modpack version**
0.3.0

**Issue**
Tried to make a trinket and those mana gems didn't work.
Good thing the crystalizer gives the original mana gems.

Maybe it's just that those gems are missing the tag: `forge:gems/mana_gem`

**Comment by NillerMedDild** [comment]
Fixed in https://github.com/NillerMedDild/Enigmatica6/pull/410
