### ISSUE TITLE
Mod Suggestion: ExtraStorage (No discs though)

### ISSUE THREAD

**Issue by MaxFirestorm** [NillerMedDild/Enigmatica6#436]
Mod Link: https://www.curseforge.com/minecraft/mc-mods/extrastorage

Reason: Adds extra tiers of crafters (Iron, Gold, Diamond, Netherite) that hold more slots for patterns (as well as working faster in the higher tiers), as well as an Advanced Importer/Exporter that holds more slots too.

The mod also adds extra disks, storage blocks and fluid storage blocks that were in RebornStorage (as well in ExtraDisks) but I believe there is some cross-compat with ED as the modpack TNP Limitless 3 uses both mods together with no recipe conflicts, though I'm not sure if that's by design of the mods or the pack.

Mostly asking for the upgradable crafters and advanced importer/exporter though, so >>;

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I'll think about it :)

**Comment by NillerMedDild** [comment]
We will be adding this :)

**Comment by MaxFirestorm** [comment]
Yaaaaaaaaaaaay!
