### ISSUE TITLE
Breaking Blocks/Items While Holding A Dank Storage Item Voids The Block/Item

### ISSUE THREAD

**Issue by MaxFirestorm** [NillerMedDild/Enigmatica6#437]
**Modpack version**
0.3.0

**Issue**
When breaking blocks or items while holding a Dank Storage item, the block or item you break will be voided instead of dropping, regardless of whether or not the item should drop. For example, breaking a torch with it held should drop the torch. Instead the torch breaks but doesn't drop. This also works with other items that should drop when broken by fist (dirt, gravel, etc). 

This is also regardless of whether or not the item exists within the Dank Storage itself (Torches, for example, aren't contained within my storage so they shouldn't be voided at all. Dirt *is* contained within my storage, but the item doesn't drop into it, the item simply vanishes)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I cannot reproduce this. SP or server?

**Comment by hvdklauw** [comment]
Oh, I think I had the same issue, try with the dank configured to void pickup (the red pickup state)

**Comment by MaxFirestorm** [comment]
Niller - Single player opened to LAN with one other person
Hvd - I'll have to double check what mode it's in when I can get at my PC

**Comment by hvdklauw** [comment]
I just tested it, it's actually when the dank is set to construction mode (not bag mode)

**Comment by MaxFirestorm** [comment]
That would make sense since more often than not I'm using construction mode.

**Comment by MaxFirestorm** [comment]
Confirmed that it is when in Construction Mode. Bag Mode drops the item as normal.

**Comment by NillerMedDild** [comment]
Found it reported here: https://github.com/Tfarcenim/Dank-Storage/issues/80
