### ISSUE TITLE
Powah Lens Of Ender Crafting Bug

### ISSUE THREAD

**Issue by MaxFirestorm** [NillerMedDild/Enigmatica6#438]
**Modpack version**
0.3.0

**Issue**
Normally, to craft a Lens of Ender from Powah, you need to right click an Enderman with a Photoelectric Pane. On doing this, the Enderman dies and the Photoelectric Pane turns into a Lens of Ender.
Currently, if you right click an Enderman with a Photoelectric Pane, the Enderman dies, but the Lens of Ender doesn't appear. Strangely, the quest for the Lens of Ender completes when the Enderman dies, but the Lens doesn't go into your inventory or onto the ground; the Photoelectric Pane simply vanishes as it should, but doesn't get repleaced with the Lens of Ender.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Was this in SP or a server?

**Comment by MaxFirestorm** [comment]
Single player opened to LAN with one other person

**Comment by NillerMedDild** [comment]
Ah that's probably the reason then, I'll try again. I highly recommend that you don't use LAN in modded though, you will come across a lot of weird bugs.

**Comment by MaxFirestorm** [comment]
Any ideas on what I should use instead of LAN? We usually use LAN and Hamachi because it's just the two of us when I do streaming.

**Comment by Darkere** [comment]
You can run a local server instead. The overhead is not that large.

**Comment by MaxFirestorm** [comment]
Server will want to use 8GB, client will want to use 8GB, not to mention the resources that streaming will want to take up.

I've only got 16GB of RAM.

**Comment by Darkere** [comment]
For 2 people server will run with less than 4gb

**Comment by NillerMedDild** [comment]
A cheap Bisect Server would do just fine: https://www.bisecthosting.com/minecraft-server-hosting.php
2-3GB should do it. You can use the code `niller` or `enigmatica` for 25% off your first month too :P

**Comment by MaxFirestorm** [comment]
Okay, just tried hosting a server locally and I'm still getting the same bug =/ I can fire up a stream if you want to show you directly

**Comment by MaxFirestorm** [comment]
OKAY, now I'm confused. When we were both connected to the local server, it didn't work.
My friend disconnected and i tried it on my own and it didn't work.
He connected again, I disconnected and it worked.
I re-connected, tried it again and it worked.

I have *NO* idea what the hell si going on any more.

**Comment by NillerMedDild** [comment]
No idea :P

**Comment by Porcy** [comment]
Still there in E6E 1.3.0 :/ 
Tried to right-click an enderman with the pane, enderman went poof, pane got consumed, droped nothing... Resorted to using alternate recipe with create.
SMP, 2 players, no LAN (I host my own server locally)

**Comment by MuteTiefling** [comment]
Yes, that alternate recipe is the 'fix'. It's the only thing we can really do about it.

**Comment by VirtueAvatar** [comment]
Not sure why this bug is closed as cannot reproduce, it can be replicated with a 100% failure rate - right-click a photoelectric pane on an enderman. In Vault Hunters, a lot of people won't have access to Create as a workaround.

Someone said you need more than 1 pane in your inventory to get a Lens of Ender, but I haven't tested this yet.

**Comment by NielsPilgaard** [comment]
> Not sure why this bug is closed as cannot reproduce, it can be replicated with a 100% failure rate - right-click a photoelectric pane on an enderman. In Vault Hunters, a lot of people won't have access to Create as a workaround.

That's an oversight, I've updated the labels.
