### ISSUE TITLE
Dupe bug with gear recycling in an arc furnace and multiservo press

### ISSUE THREAD

**Issue by Dasavanth** [NillerMedDild/Enigmatica6#440]
**Modpack version**
0.3.0

**Issue**
ingots can be duped by making gears in a multiservo press (3:1) and recycling them in arc furnace (1:4) with a net gain of 1 ingot

**Comment by NillerMedDild** [comment]
Recycling and melting down components always risks duping, I've gone ahead and disabled recycling all together to prevent this and any future issues like it :)

Thanks for the report!

**Comment by NillerMedDild** [comment]
I have managed to remove a few of the gear recipes, but it's proving to be a lot more difficult than I had anticipated.
