### ISSUE TITLE
Recipe conflict between vertical dark oak wood planks and dark oak panels

### ISSUE THREAD

**Issue by brckts** [NillerMedDild/Enigmatica6#441]
**Modpack version**
0.3.0

**Issue**
They have the same recipe, making dark oak panels uncraftable in a crafting station. Recipe with the stonecutter still works though.
![201129-0028-43](https://user-images.githubusercontent.com/51674867/100528222-96595300-31da-11eb-94e4-620d4efc787a.png)
![201129-0029-06](https://user-images.githubusercontent.com/51674867/100528223-9b1e0700-31da-11eb-9b00-108f59ee5131.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, I think I'll remove one of the recipes (and similar ones ofc)
