### ISSUE TITLE
Mekanism heat generators are waterloggable with lava

### ISSUE THREAD

**Issue by brckts** [NillerMedDild/Enigmatica6#443]
**Modpack version**
0.3.0

**Issue**
Mek's heat generators are waterloggable with lava.
![201129-1536-10](https://user-images.githubusercontent.com/51674867/100544866-fbec2480-3258-11eb-9dea-3cf91573ebe9.png)
![201129-1536-20](https://user-images.githubusercontent.com/51674867/100544867-fdb5e800-3258-11eb-8088-25bc96914746.png)

No idea if intended or not, looks weird with the lava glitching through it.

**Comment by Darkere** [comment]
Very much intended. They had to do a lot of stuff to make that work.

**Comment by brckts** [comment]
got it, still looks really cursed
