### ISSUE TITLE
Stonecutting can turn any stone into any other stone breaking balance

### ISSUE THREAD

**Issue by brckts** [NillerMedDild/Enigmatica6#445]
**Modpack version**
0.3.0

**Issue**
I've only looked at it from diorite, the worst ones I found are:
diorite -> stone bypassing the need for a furnace or silk touch
diorite -> reinforced stone bypassing the need for a furnace and compressed iron

there's also a lot of the recipes that don't make much sense but don't break balance like diorite -> andesite

diorite -> infested stone is also a fun one

**Comment by NillerMedDild** [comment]
I know, I added that ^^' it was to avoid having 900 stone types in worldgen, but we have a decent option for that now, so this'll be removed. Thanks for the report.
