### ISSUE TITLE
bucket duping when converting memory essence bucket to essence bucket and vice versa (Disabled recipe, pending custom recipetype for consuming buckets)

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#446]
**Modpack version**
0.3.0

**Issue**
when crafting both the types of essences from each other, the input bucket doesnt get consumed and output produces a new bucket. dupe galore ;P

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue. Buckets for all!!!!1

**Comment by NillerMedDild** [comment]
No way to fix this bug at the moment, had to disable the recipe :/

**Comment by KrAzYGEEK32** [comment]
I have an idea which might work regarding this recipe, why not make it so that, memory essence in dissolution chamber converts to essence for some power, essence is thermo pneumatic processing plant converts to memory essence for some pressure or heat or both. This would make it more easily automatable and wouldn't involve buckets. I really love the thought behind the recipe so that why as king for it. Anyway, just an idea :P

**Comment by KrAzYGEEK32** [comment]
Also, this dupe might happen for any other bucket conversions as well, if there are anymore

**Comment by NillerMedDild** [comment]
Good idea, I've made a new issue for those new recipes :)

**Comment by NillerMedDild** [comment]
Fixed with #453 by MuteTiefling :D
