### ISSUE TITLE
Immersive Engineering Treated Wood recipe voids Mekanism Tank

### ISSUE THREAD

**Issue by Figulus88** [NillerMedDild/Enigmatica6#447]
**Modpack version**
0.3.0

**Issue**
Crafting Treated Wood from Immersive Engineering with a Mekanism Ultimate Tank (almost full) of Creosote Oil gives one craft worth of Treated Wood (8) and then voids the tank.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Reported to IE and Mekanism: https://github.com/BluSunrize/ImmersiveEngineering/issues/4449 https://github.com/mekanism/Mekanism/issues/6710
Thanks for the report :)

**Comment by NillerMedDild** [comment]
It's fixed I suppose, the tank just doesn't work in the recipe anymore.
