### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by ShawnGunnels** [NillerMedDild/Enigmatica6#448]
Version 0.3.0

Furnace, Hoppers, and most Mekanism machines will not open the user interface. I haven't gotten too far into the pack to see if other blocks did this.

**Comment by NillerMedDild** [comment]
That's odd :s working just fine for me, have you added any mods? Optifine for example?

**Comment by ShawnGunnels** [comment]
No. Tomorrow I will try redownloading perhaps and copying world file? See
if maybe something messed up during download

**Comment by NillerMedDild** [comment]
Sounds good, thanks :)

**Comment by ShawnGunnels** [comment]
After redownloading everything works well. Thank you for your help

**Comment by NillerMedDild** [comment]
Glad to hear it!

**Comment by jinkhya** [comment]
Hello I know this is closed but I ran into this issue myself and a player on our server too and restarting the client (without reinstalling) fixes it. Kind of an odd issue, especially since it's not consistent, those are the worse !! :)

**Comment by Darkere** [comment]
See pinned issue :)

**Comment by jinkhya** [comment]
Derp, I searched for similar issues and didn't check pins, sorry about that :)
