### ISSUE TITLE
Crashing when using "Biomes You'll Go" mushrooms with Sylph

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#451]
**Modpack version**
Current Dev Commits

**Issue**
I was building out a test platform to see how the Sylph handled various modded mushrooms. So I made a 21x21 platform of mycelium and started filling it with BYG mushrooms. Not long after I got going, it crashed. 

**Logs**
Latest: 
[latest.log](https://github.com/baileyholl/Ars-Nouveau/files/5619821/latest.log)

Crash: 
[crash-2020-11-30_20.54.17-server.txt](https://github.com/baileyholl/Ars-Nouveau/files/5619818/crash-2020-11-30_20.54.17-server.txt)

https://github.com/baileyholl/Ars-Nouveau/issues/82

**Comment by NillerMedDild** [comment]
Damn that was a quick fix. Would you mind testing if this has been fixed when I update the dev branch?

**Comment by MuteTiefling** [comment]
Will do

**Comment by NillerMedDild** [comment]
Ready for testing on the dev server :)

**Comment by MuteTiefling** [comment]
I seem to be getting Ars Nouveau 1.7.1 on Dev.

After manually updating my SP instance to 1.8.1, I can no longer reproduce the issue. But it's still a problem on the current Dev instance.

**Comment by NillerMedDild** [comment]
Woops! Fixed in-dev, seems the CF launcher is still a bit rough around the edges for development.

**Comment by MuteTiefling** [comment]
Have tested on the server now and all is good. working beautifully
