### ISSUE TITLE
Isolated Recipes (Xerca Mod)

### ISSUE THREAD

**Issue by Syrasar** [NillerMedDild/Enigmatica6#452]
**Modpack version**
0.3.0

**Issue**
Xerca mod burgers are shown in the recipe list when using the xerca mod knife the recipes do not work (resulting items are also hidden in the JEI search bar) as such i currently beliefe that its an issue of recipes not being hidden instead of not working as intended
**Logs**
Not Applicable

**Comment by NillerMedDild** [comment]
Fixed by removing Xercamod in 0.3.1 :P
