### ISSUE TITLE
Add Sophisticated Backpacks

### ISSUE THREAD

**Issue by hipsterjazzbo** [NillerMedDild/Enigmatica6#456]
**Modpack version**
0.3.0

**Issue**
It'd be really cool if we could have [Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks) in the pack!

**Comment by NillerMedDild** [comment]
Looks interesting! Can you tell me what it can do that Useful Backpacks can't? :)

**Comment by hipsterjazzbo** [comment]
- Pretty great upgrade system, with upgrade modules for:
    - Pickup upgrade picks up items that match the filter directly into the backpack
    - Magnet upgrade is a variant of pickup that teleports items around the player into the backpack
    - Filter upgrade can be used to filter items that are input into or output from backpack using automation
    - Void upgrade does exactly what you would expect - voids items that are picked up based on its filter
    - Compacting upgrade compacts items using 2x2 or 3x3 (advanced variant of upgrade) recipes. Will only compact items that can then be uncrafted back so it won't craft quartz or glowstone dust into blocks if the modpack doesn't have uncrafting recipes for these.
    - Feeding upgrade feeds player with food from backpack when the player gets hungry.
    - Deposit upgrade makes it so that shift right clicking an inventory deposits items specified in its filter into that inventory.
    - Restock upgrade takes items defined in its filter from inventory when it's shift right clicked.
    - Refill upgrade keeps a stack of items in player's inventory filled from backpack, up to 6 stacks can be defined in its filter to refill like that.
- Can be placed and used as inventory, hopper'd in and out of etc
- CAN BE DYED TWO PRETTY COLOURS AT ONCE
- JEI icon isn't some kind of horridly ugly eldritch abomination
- Generally looks like an incredibly well-done mod that deserves more visibility

**Comment by NillerMedDild** [comment]
That does sound pretty sweet. Fingers crossed there aren't any dupe or void bugs :P
