### ISSUE TITLE
Netherite Bees Kill themselves.

### ISSUE THREAD

**Issue by Volensq** [NillerMedDild/Enigmatica6#457]
Enigmatica6-0.3.0
Minecraft- 1.16.4
Forge 35.1.0

-Netherite bees Kill themselves.   
Their flower of choice is the Wither Rose, But they do not have a Wither trait. this results in them flying to a rose and taking damage until they die.

-No logs
Is reproducible
-If this is changed by server owner I will contact them instead.

**Comment by NillerMedDild** [comment]
Damn that is sad :P thanks for the report, we'll get that fixed.

**Comment by Ridanisaurus** [comment]
https://github.com/Resourceful-Bees/ResourcefulBees/issues/32#issuecomment-718006345
