### ISSUE TITLE
Xnet wireless router not working

### ISSUE THREAD

**Issue by whatusernameisleft** [NillerMedDild/Enigmatica6#459]
Enigmatica 6 v3.0
forge-35.1.0

**Issue**
Router to router with routing network cables works properly, but wireless router setup doesn't work.

**Comment by NillerMedDild** [comment]
Thanks for the report. To be honest I've never made a Wireless Router setup, so I would have a hard time reproducing and reporting this. Would you mind reporting it on the XNet tracker? :)
https://github.com/McJtyMods/XNet/issues

**Comment by whatusernameisleft** [comment]
I've reported it, awaiting for response now.

**Comment by whatusernameisleft** [comment]
McJty said he fixed it in the next version of Xnet

**Comment by NillerMedDild** [comment]
Awesome, thanks!
