### ISSUE TITLE
Biomes O' Plenty causes old worlds to be unable to load

### ISSUE THREAD

**Issue by SilentSpyVEVO** [NillerMedDild/Enigmatica6#46]
**Modpack version**
0.2.3 but also didn't work on previous versions when it was introduced

**Issue**
Loading up an world with BoP causes it to be stuck on "reading ordinary data" indefinitely, removing the mod fixes this.

**Logs**
Input pastebin link to crash-report or latest log, if applicable N/A, doesn't crash just doesn't load

**Comment by NillerMedDild** [comment]
Does this happen with new BoP worlds? Or new vanilla worlds even?

**Comment by Seegras** [comment]
Happens on Vanilla worlds too.

**Comment by SilentSpyVEVO** [comment]
Hmmmm I'm not sure as I've removed the mod but I realized what was causing
the issue after reading a comment on the FTB subreddit here:
https://www.reddit.com/r/feedthebeast/comments/hx3alw/_/

Sorry I can't be of more help, thanks for reaching out, love the pack! :)

**Comment by Darkere** [comment]
It happens to worlds from before BoP. 

I've done a quick test and haven't been able to replicate it though. So I'm not sure what happens.

**Comment by NillerMedDild** [comment]
I'm having trouble reproducing it as well, will keep trying.

**Comment by NillerMedDild** [comment]
Hmm I can reproduce it now. Datapack error: https://gist.github.com/NillerMedDild/15628cacca18280555060fe43cd2f15e

**Comment by Darkere** [comment]
You are getting more info than I've seen. My game just got stuck on Reading world data without anything in the log and with nothing in visualvm.

**Comment by NillerMedDild** [comment]
Myeah I'm not convinced it's the same issue. The one I saw points more towards Quark's datapack being corrupt in some way.

**Comment by Darkere** [comment]
Happens to my own old testworld. Not seeing anything but here is the debug log. 

https://gist.github.com/Darkere/438478e357ea47095edcd3fda8939e94

And the world if anyone wants to try it out: https://mega.nz/file/k7Jhka5T#aoX4v9r9wLz-g6JPpbzBOzQxmpnA0StTZNEfqN9hrKk

**Comment by Seegras** [comment]
Tried out making a new world, but copying over the old level.dat. Same issue, hangs on loading.

**Comment by jester1147** [comment]
I am having similar issues with both non BOP and BOP worlds, to include a fresh install on MultiMC. 

No additional datapacks, no shaders, no texture packs.  However, works fine with Multiplayer (to include shaders and texture packs)

Looking for some suggestions? Can reproduce every time, members of my community have not (yet, still reaching out)

**Comment by Darkere** [comment]
According to the issue report it might be an issue in combination with the rats mod.

**Comment by NillerMedDild** [comment]
@jester1147 would you mind removing Rats and trying again? :)

**Comment by jester1147** [comment]
Can confirm, removal of the rats mod allows me to bring up previously started worlds. 

Thanks Niller

**Comment by NillerMedDild** [comment]
I have decided to remove Rats to remedy this issue. It was going to be cut sooner or later anyway.
