### ISSUE TITLE
Extra Material when recycling gears 

### ISSUE THREAD

**Issue by ZeeDerp** [NillerMedDild/Enigmatica6#462]
**Modpack version**
Enigmatic 6 0.3

**Issue**
Gears can be made using a Multiservo Press for 3 of any given material, and when recycled in an arc furnace, it gives 4 of the metal resulting in 1 extra material for what you put in. Not too substantial but its still giving a free item and it can be done with any gear.

**Comment by RevenantWendigo** [comment]
Mentioned here #440 . Looks like there have been a number of commits to fix this issue.

**Comment by ZeeDerp** [comment]
Oh alright! Thanks
