### ISSUE TITLE
server crash with wither interaction

### ISSUE THREAD

**Issue by JonasDBB** [NillerMedDild/Enigmatica6#463]
**Modpack version**
enigmatica 6 0.3.0

**Issue**
One person gets hit by a wither skeleton (with sword) and the server crashes. Might have something to do with his trinkets (octopus legs or withering nail maybe?)

**Logs**
https://pastebin.com/MYhPZLdQ

**Comment by NillerMedDild** [comment]
Thanks for the report, the issue was Octopus Legs, nice catch!

https://github.com/owmii/Lost-Trinkets/issues/11

**Comment by NillerMedDild** [comment]
Octopus Leggings will have their functionality removed while the dev works on the bug :)
