### ISSUE TITLE
non EE ore spawns when using Nature's Aura powder of bountiful core (ore gen)

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#465]
**Modpack version**
0.3.0

**Issue**
minor issue but mentioning it for unification purposes
for example
![2020-12-03_18 13 55](https://user-images.githubusercontent.com/59537798/101020588-bf8c3180-3594-11eb-8f0a-221d265f2439.png)
Tinkermechworks copper spawned instead of EE copper

**Comment by NillerMedDild** [comment]
Thanks for the report, that screenshot made this extra easy to fix :P do you know of any other ores that generate?

**Comment by KrAzYGEEK32** [comment]
Not yet, but I'll will let you know if I find other ores

**Comment by MuteTiefling** [comment]
Looks like I forgot tinker's mechworks entirely, so `tmechworks:aluminum_ore` also needs to be removed.
