### ISSUE TITLE
Visual glitch with Chunk borders

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#466]
**Modpack version**
0.3.0

**Issue**
when it third person perspective, the second variant of it, which shows your face, chuck borders seem to stick to the camera angle, i know my explanation is "subpar" so here is a picture
![2020-12-03_12 19 15](https://user-images.githubusercontent.com/59537798/101020974-44774b00-3595-11eb-8191-3dc53da46054.png)
chunk:"oh, i dont think so, that half block is mine" XD

**Comment by NillerMedDild** [comment]
Ha, cool bug :D thanks for reporting, will relay it.

**Comment by NillerMedDild** [comment]
Relayed by someone else \o/
https://github.com/r8420/MoreOverlays-1.15/issues/10

**Comment by NillerMedDild** [comment]
Sorta fixed, they don't display in 3rd person as of E6 0.3.7 :P
