### ISSUE TITLE
Tetra Workbench Dupe Bug

### ISSUE THREAD

**Issue by ZeeDerp** [NillerMedDild/Enigmatica6#469]
**Modpack version**
0.3.0

**Issue**
If you obtain a tetra workbench, then have an inventory with things you want to dupe, then middle mouse to sort, it will fill the slot with a bunch of items, continuing to press the middle mouse button will dupe forever.

**Comment by ZeeDerp** [comment]
A little more info : The item with the first letter alphabetically is not duped, but every subsequent item in the inventory is duped based on the amount when you first sorted it. I believe this can only dupe 3 items at a time, but it will dupe backpacks which opens it to dupe an almost infinite amount.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Fixed!

link to issue: https://github.com/mickelus/tetra/issues/243
