### ISSUE TITLE
Terrasteel Recipe Conflict

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#470]
**Modpack version**
E6 0.3.0

**Issue**
Terrasword is unobtainable. The standard recipe gives you a Terrasteel Hoe, and there is another conflict with a Terrasteel Shovel

**Screenshots**
![image](https://user-images.githubusercontent.com/64355028/101079080-48ac6400-35a7-11eb-86f3-1a7f9370ef70.png)

**Comment by NillerMedDild** [comment]
Fixed in-dev luckily, thanks for the report Rid!
