### ISSUE TITLE
Ender chests recipes can't be automated with one RS pattern because of the foliots names on satchels when crafted

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica6#4714]
### Modpack Version

1.1.2

### Describe your issue.

Hello ! 
When making a pattern non-exact for enderchests it won't work. RS crafting monitor can't find the satchels present in the system.
I think I could set one pattern per folliot satchel with the exact setting but that's a bit much :P 
Thanks in advance ! ^^
![image](https://user-images.githubusercontent.com/10158963/165117163-4a11d47c-0ff8-40c2-ac3e-052f1d3b1ce5.png)
![image](https://user-images.githubusercontent.com/10158963/165117884-5fe74861-c859-4260-8a5b-b6d1f709ae6c.png)
![image](https://user-images.githubusercontent.com/10158963/165117757-1221e8d6-d294-42b3-8fe4-8c14f11c39d1.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment]
This is an automation challenge! You'll need to handle this step outside of RS, as it can't really handle the NBT from the name. So your pattern will want to be the ingredients for the chest + the ingredients for the satchel -> ender chest; craft the satchel, send that to something like a Wixie or Formulaic Assemblicator to craft the ender chest, then send that back to RS.

**Comment by jinkhya** [comment]
I see thank you !! :)

**Comment by MuteTiefling** [comment]
We have a nice article on our wiki to help us you want to have a look : https://wiki.enigmatica.net/enigmatica6/gameplay/how-to.../occultism-automating-rituals

**Comment by jinkhya** [comment]
Awesome I'll have a look !

**Comment by demethan** [comment]
Could you use an equivalent item that is not using an nbt tag.  This is not an expert mode thing, in my opinion, it's just annoying because  RS can't handle some tags.
