### ISSUE TITLE
Mod Suggestion: Demagnetize 

### ISSUE THREAD

**Issue by BillboardEric** [NillerMedDild/Enigmatica6#473]
RFTools Power: https://www.curseforge.com/minecraft/mc-mods/rftools-power
I know the Dimensional Cells can be redundant because of Powah but the Endergenic generator and the new Blazing Generator are fun ways of making power

Demagnetize: https://www.curseforge.com/minecraft/mc-mods/demagnetize

**Comment by NillerMedDild** [comment]
Could you explain what the Blazing Generator is/does? :)

**Comment by BillboardEric** [comment]
McJty has a video on it :)
https://www.youtube.com/watch?v=eQUB3jKrWVQ

**Comment by NillerMedDild** [comment]
Adding Demagnitize, haven't had time to give RFTools Power a thorough look yet, will move it to a new issue :)

**Comment by HalJordan** [comment]
Without the dimensional transciever in mekansim(guess it hasn't been ported up to 1.16 yet?) the powah mod is the only way to get power across long distances. I'm not fond of the recipe for the rftools power cell, but this would at least give some choice to the matter.

**Comment by NillerMedDild** [comment]
The Dimensional Transceiver is a block from EnderIO, the Mekanism variety is called the Quantum Entangloporter :)
