### ISSUE TITLE
Sound loss

### ISSUE THREAD

**Issue by Altowolf** [NillerMedDild/Enigmatica6#476]
**Modpack version**
Enigmatica 0.3.0 (release) (current)

**Issue**
have server set up through bisect. but sound is client side. but all users including myself find the issue of sound loss occurring. 
ambient and music still are their. but all sounds connected to your character -aka chests, items, mining, and monsters, eating and dmg are gone. f3+ r doesn't work. f3 t same. restarting the server, and repairing the files via curse launcher result in the same. I'm not technologically inclined which is why I pay Bisect extra to do everything for me but they cant help with this. any reason this could happen and anything i can do to fix it?
**Logs**
none sorry

**Comment by NillerMedDild** [comment]
Has it been like this all the time, or did it happen after a certain event or something like that?

**Comment by Altowolf** [comment]
I was told by one other guy his sound goes in and out. Mine unfortunately worked perfectly till two days ago when I used a chrome plug in to watch a YouTube video while I was playing. After that the sounds that don't work  were turned on and off with the player being on and off. Then I restarted my pc and lost the sounds permanently.

**Comment by NillerMedDild** [comment]
I'm afraid I can't really help with that :P
