### ISSUE TITLE
Simple Farming and Farmer's Delight fried egg conflict

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#480]
**Modpack version**
0.3.0

**Issue**
Both Farmer's Delight and Simple Farming add a cooked egg (and Xerca Mod). Smelting an egg gives the Farmer's Delight one, which can be used for Farmer's Delight Egg Sandwiches, but this makes the Simple Farming one (required for Simple Farming Egg Sandwiches and Fried Rice) unobtainable.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
