### ISSUE TITLE
Transferring world from 0.2.17 to 0.3.0

### ISSUE THREAD

**Issue by blarghhh** [NillerMedDild/Enigmatica6#481]
**Modpack version**
0.3.0

**Issue**
I know the main page says that it is better to make a new world but so far my attempt to move the world to the new version seems to lack any issues. So far. 

Any idea how to get around these errors?
[Server thread/ERROR] [net.minecraft.world.chunk.storage.ChunkSerializer/]: Unknown structure start: appliedenergistics2:meteorite

[net.minecraft.tileentity.TileEntity/]: Skipping BlockEntity with id productivebees:solitary_nest

my world runs fine. it's just weird to see those appearing when the mods are not around anymore

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Darkere** [comment]
You would need to re-add these mods to get rid of them. 

Also make sure your world saves. There is a vanilla bug, where removing features from the world makes it no longer save. I'm not certain if that bug is fixed in forge yet.

**Comment by blarghhh** [comment]
ah. i guess manually running ftbbackups is the best way to mitigate at the moment?

**Comment by Darkere** [comment]
A backup backs up what you've saved.. its not gonna fix the saving.
