### ISSUE TITLE
Mod Suggestion - End Remastered

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica6#482]
Saw this mod and it looks like an interesting way to add some and adventure & change up getting to the end. I'm not sure how customizable/stable it is, and I'm not sure how much exploration/adventure you're looking to add, but I figured I'd bring it to your attention!

https://www.curseforge.com/minecraft/mc-mods/endremastered

**Comment by NillerMedDild** [comment]
Hmm interesting, thanks for the suggestion.

**Comment by NillerMedDild** [comment]
It's gonna be a no, I think that mod is more suited for vanilla+ packs.
