### ISSUE TITLE
Mod suggestion: Scannable

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#483]
[CF link](https://www.curseforge.com/minecraft/mc-mods/scannable)

It's a small mod that adds a RF powered handheld scanner that shows you were nearby stuff is, like ores, mobs, specific blocks and stuff depending on the cards you put inside. It's really nice for mining and says it's performance friendly on servers.

**Comment by NillerMedDild** [comment]
Thinking about it, but I believe PNC offers similar capabilities on the Pneumatic Helmet.

**Comment by MuteTiefling** [comment]
The PNC helm does indeed cover a good deal of the use cases for Scannable. It'll let you search inventories, RF powered blocks, spawners, and 'hackables' (things like levers that the helm let's you activate remotely).

It doesn't let you scan for specific blocks like scannable does, however. So while scannable can be used to find ore, the PNC helmet isn't going to help there.

**Comment by NillerMedDild** [comment]
It'll be a no based on duplicate feature, primarily :)
