### ISSUE TITLE
Mekanism Coal/Gunpowder - Sulfur issues

### ISSUE THREAD

**Issue by Cheisu** [NillerMedDild/Enigmatica6#485]
Enigmatica 6

**Issue**
I noticed this the other day when helping a buddy set up a Fission reactor in Mekanism and mentioned it to a contributor who said I should post a log here. In Mekanism you should be able to make sulfur by running coal through a Pressurized Reaction Chamber with water/Oxygen and or by running gunpowder through a Chemical Injection Chamber with Hydrogen Chloride, but both of those options seem to be non-functional in this release.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I forgot to rename the sulfur dust in our datapack when it changes registry name, woops :D

**Comment by Cheisu** [comment]
Dope man thanks a lot for the quick reply :) Really digging E6 so far, my players thank you kindly!
