### ISSUE TITLE
Mod suggestion: Mana and Artifice

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#486]
Ars Magica 2 developer released this a few hours ago. Looks like it has lots of content already. The gist of the mod is crafting spells like Ars Nouveau and doing other magic things. Definitely worth taking a look at imo.

https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice

**Comment by NillerMedDild** [comment]
Duplicate of #275 :)
