### ISSUE TITLE
BYG sapling support in Botany Pots

### ISSUE THREAD

**Issue by OrdinatorStouff** [NillerMedDild/Enigmatica6#489]
**Modpack version**
E6 0.3.0 (official smp server)

**Issue**
Lament sapling `byg:lament_sapling` doesn't function in the botany pot

**Comment by OrdinatorStouff** [comment]
Also:
```
byg:withering_oak_sapling
byg:araucaria_sapling
byg:brown_zelkova_sapling
byg:palm_sapling
byg:ether_sapling
byg:nightshade_sapling
```

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
