### ISSUE TITLE
Cardboard Box voids items when used with FTB Ultimine

### ISSUE THREAD

**Issue by HunterGiannini** [NillerMedDild/Enigmatica6#4898]
### Modpack Version

1.3.0

### Describe your issue.

When the Mekanism cardboard box interaction that would normally store a block is used in conjunction with FTB Ultimine, all blocks that would be mined are voided, allowing for quick excavation without tool durability use.

Here is a video example of what happens
https://drive.google.com/file/d/15UVEfKooASbfOdFiWCq6AJwgqNakSjdA/view?usp=sharing

### Crash Report

None

### Have you modified the modpack?

Yes

### User Modifications

-Added Easy Villagers v1.0.13

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report, possibly fixed in-dev 😄

**Comment by MuteTiefling** [comment]
Cannot replicate with the fix in place. Seems good.
