### ISSUE TITLE
Suggestion: Portable Stonecutter

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#490]
**Modpack version**
E6 0.3.0

**Enhancement**
I have had this idea for a while, and was talking to @brckts (aka. []) on Discord about it the other day, so he decided to go ahead and do it. Looks pretty good, and seems to work wonderfully.
This mod would make such a huge difference for builders by removing the need to going back and forth to the Stonecutter. Consider it as Chisel 2.0.

At the moment there is a slight bug regarding deletion of input if not removed before closing the GUI but he is aware of it, so if it is considered for E6, then maybe hold on until that issue is fixed before including it.

Link: https://www.curseforge.com/minecraft/mc-mods/portable-stonecutter

**Comment by Ridanisaurus** [comment]
![image](https://user-images.githubusercontent.com/64355028/101283603-b8a33000-37db-11eb-856a-3c961e7530b6.png)
I missing being able to do this on the go

**Comment by NillerMedDild** [comment]
Very nice, we totally need that. Gonna wait for the update though :)

**Comment by brckts** [comment]
bug is fixed and mod is updated

**Comment by NillerMedDild** [comment]
damn that was fast :P
