### ISSUE TITLE
Mod suggestion: the Undergarden

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#491]
[CF Link](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)

It's a nice looking dimension mod that could add some extra biomes, decorations and mobs. I don't know exactly how complete it is and if it performs well on servers, but it looks cool enough to maybe check out.

**Comment by NillerMedDild** [comment]
I'll have a look down the line :)
