### ISSUE TITLE
BYG fruits aren't tagged as fruits for the cooking mods

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#492]
**Modpack version**
0.3.0

**Issue**
Most of the fruits added by Oh The Biomes You'll Go are not tagged as `forge:fruits` and so can't be used in the Simple Farming recipes. Might be worth reporting it to BYG too if it's a common tag among the cooking mods and not like something from the modpack.

BYG fruits that aren't tagged:
* Baobab Fruit
* Holly Berries
* Joshua Fruit
* Nightshade Berries

BYG fruits that ARE tagged:
* Green Apple
* Crimson Berries
* Blueberries

**Comment by MuteTiefling** [comment]
Nightshade is deadly. ;D

**Comment by NillerMedDild** [comment]
PR'd to BYG: https://github.com/CorgiTaco/BYG/pull/184
