### ISSUE TITLE
Cannot crush Zinc Chunks in a Pedestal with the Crusher upgrade

### ISSUE THREAD

**Issue by kosakriszi** [NillerMedDild/Enigmatica6#495]
**Modpack version**
0.3.0

**Issue**
Cannot crush Zinc Chunks in a crusher pedestal. This seems to work fine for every other ore chunk I've tried. Zinc is crushable in blocks like the Thermal Pulverizer.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/Mowmaster/Pedestals/issues/31

**Comment by NillerMedDild** [comment]
aaaand fixed \o/
