### ISSUE TITLE
Mekanism Reactor Extreme Non-Destructive Explosion Loop

### ISSUE THREAD

**Issue by Cheisu** [NillerMedDild/Enigmatica6#496]
**Modpack version**
Enigmatica 6

**Issue**
So this is a funny one, my buddy CitrusFruit constructed a fission reactor in Mekanism and it ended up backing up the turbine resulting in an "explosion". This is normal and isn't fully the issue, but for some reason the reactor entered a state of continuously and "harmlessly" exploding tens of times per second in what seemed to be a permanent loop of reactor explosions. Here's a video of it: https://www.youtube.com/watch?v=blxQ5leCuY8&ab_channel=CitrusFruit
![damage](https://user-images.githubusercontent.com/75545619/101325386-8536c480-3820-11eb-88b1-e93c9811cb4c.jpg)
OFC the normal behavior is it would get to 100% damage and explode resulting in a ton of damage, as this picture from an old server showcases
![2020-11-28_15 31 23](https://user-images.githubusercontent.com/75545619/101325482-b0211880-3820-11eb-9784-77a5773ce5b8.png)
Some other small details I could think to add: His reactor is in claimed FTB Chunks set to be force-loaded.

**Comment by Cheisu** [comment]
Later note, we did some testing on the server and found that reactors in unclaimed areas do explode normally when in unclaimed chunks, the issues is recreatable within claimed chunks whether force-loaded or not, the reactors explode in an endless loop. It seems larger reactors also tend to have higher frequency of explosions/second.

**Comment by NillerMedDild** [comment]
Awesome :P I'm not so sure I would call this a bug to be honest. More of an unfortunate mod interaction.

**Comment by NillerMedDild** [comment]
What do you think? Was this unforseen behaviour an annoyance? :)

**Comment by Cheisu** [comment]
Honestly it's not that annoying of an interaction :) 3/4 of me posted it because of how funny it was hahaha.
I'd honestly rate it better than the reactor exploding therefor destroying hours of work. 
My new server rule is that if you overheat your reactor, you deserve to listen to hours of explosions anyway :3 jk I just pop into creative and fix it real quick.

**Comment by NillerMedDild** [comment]
Haha, alright :D
