### ISSUE TITLE
Powah quests suggestion

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#497]
**Modpack version**
0.3.0

**Issue**
right now, uraninite is gated behind all of the other power sources, this doesnt make sense as only one type of power source is required to make uraninite. i feel like all the power sources of powah should be optional quests and uraninite should be gated behind the energizing orb as thats the only way to get it.

![2020-12-07_14 04 18](https://user-images.githubusercontent.com/59537798/101327748-1fd0eb00-3895-11eb-8e1b-e7a0ce51eaa2.png)
pic for better context

**Comment by KrAzYGEEK32** [comment]
uraninite is gated behind all the 4 power sources for some reason, i bet they are cheap resource wise, but noetheless they are annoying to craft :D

**Comment by NillerMedDild** [comment]
Hmm I agree, that needs to be changed a bit.
