### ISSUE TITLE
Server crash in ocean monument with mirror shield.

### ISSUE THREAD

**Issue by alanbaumgartner** [NillerMedDild/Enigmatica6#498]
**Modpack version**
0.3.0

**Issue**
When in an ocean monument with a mirror shield, when a guardian attacks you, the server crashes. I took off the mirror shield before going in and no crash happened. It may not be the direct cause but its the only relation I could find without having logs.

**Logs**
The server crashes with no logs being written, I have tried to get them directly from the console but unsuccessfully.

**Comment by Ridanisaurus** [comment]
Known Issue: https://github.com/owmii/Lost-Trinkets/issues/9
