### ISSUE TITLE
Mana Bloom recipe does not ore-dict

### ISSUE THREAD

**Issue by blarghhh** [NillerMedDild/Enigmatica6#499]
**Modpack version**
0.3.0

**Issue**
Ars Nouveau enchanting apparatus only accepts the smelted version of the arcane ore ie mana gem from Ars.

Problem: trying to craft the mana bloom

1.  Go mining for arcane ore and break them which drops the non original mana gem (the one from emendatus enigmatica)
2. The crafting recipe for the mana bloom does not accept that.
3. Silk touch the arcane ore, use the stone cutter to convert it to original arcane ore from Ars and smelt it in a vanilla furnace to get the mana gem from Ars.
4. The mana bloom recipe crafts successfully.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Ridanisaurus** [comment]
This has been fixed in 0.3.1.
Until then, there is a simple work around with the Crystallizer which creates AN Mana Gems.
