### ISSUE TITLE
Fluorite duping using broken combiner recipe

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#50]
**Modpack version**
   0.2.3

**Issue**
Fluorite can be duped by looping an enrichment chamber - crusher - combiner, i've talked to the mekanism dev, and seems like its a pack issue, so im reporting it here 
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Errrr... I've disabled the Combiner completely, so errr... I'll have a look in game.

**Comment by KrAzYGEEK32** [comment]
im really sorry for disturbing you then, i just noticed that in JEI, as i was searching for fluorite processing, i shouldve tested this before reporting, my bad. ill take one last look to see if i can actually do it and then close this issue :)

**Comment by NillerMedDild** [comment]
No worries, I appreciate the report regardless :D

**Comment by KrAzYGEEK32** [comment]
yea it seems like combiner isnt craftable at all, so my bad, sorry again, im closing the issue
