### ISSUE TITLE
[Mod Suggestion] Enigmatic Legacy

### ISSUE THREAD

**Issue by IgorDejavu** [NillerMedDild/Enigmatica6#500]
Enigmatic Legacy
https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy
Adds new mechanics, various jewelry with beautiful textures. Plus it's hard to get them.

**Comment by NillerMedDild** [comment]
We already have Artifacts and Lost Trophies, I think we're covered in the loot/artifact department :)

**Comment by IgorDejavu** [comment]
Thanks for attention
