### ISSUE TITLE
Shrink

### ISSUE THREAD

**Issue by Darkere** [NillerMedDild/Enigmatica6#501]
Cool little mod. Pun Intended 
[Shrink Mod CF page](https://www.curseforge.com/minecraft/mc-mods/shrink_)

**Comment by Ridanisaurus** [comment]
YES! I saw Dire playing with it, and while it's very early version, it can be very handy when wiring things around the base and you want to access all those tiny places and whatnot.

**Comment by NillerMedDild** [comment]
Sure why not :P

**Comment by Colton-Slayden** [comment]
I have tried to look at this mod and the curseforge page is not found?

**Comment by NillerMedDild** [comment]
Attach a `_` to the end of the url, not sure why browsers trim that.

**Comment by Darkere** [comment]
should work now :)
