### ISSUE TITLE
Op can't run gamemode command

### ISSUE THREAD

**Issue by jamescalver** [NillerMedDild/Enigmatica6#502]
**Modpack version**
0.3.0

**Issue**
My player is an Op, but I can't run the gamemode command. I have rebooted after op-ing my player, and the command works from the console.

Player's op level is 4, and server function permission level is 2

Thanks for any help!

**Comment by NillerMedDild** [comment]
Which command exactly did you try to run? Gamemode has changed a bit in 1.12+, it doesn't take a number anymore.

**Comment by jamescalver** [comment]
I’ve been looking into this more, and think it might not be specifically an Enigmatica issue. I know about the change to uses words, creative etc. When I go to start typing the command, /gamemode, MC starts trying to auto complete, but it doesn’t show the game mode command.

**Comment by NillerMedDild** [comment]
Hm alright :/ I wonder what the issue is. I can't reproduce it in Enigmatica sadly.

**Comment by jamescalver** [comment]
Just a follow up.  I deleted the ops.json file, restarted the server, and then it started working as expected.  Very strange!
