### ISSUE TITLE
[ Bug ] Xercamod Foods aren't disabled in the SoL: Carrot Food Book

### ISSUE THREAD

**Issue by MasterOfBob777** [NillerMedDild/Enigmatica6#505]
**Modpack version**
v0.3.0

**Issue**
Pretty much the title but you can't obtain the foods nor are they available in JEI but they still are in the SoL: Carrot Food Book 

**Logs**
N / A

**Comment by NillerMedDild** [comment]
Fixed by removing the mod in 0.3.1 :)
