### ISSUE TITLE
Cannot enter the nether and massive amounts of warnings/errors on startup

### ISSUE THREAD

**Issue by CoroNaut** [NillerMedDild/Enigmatica6#507]
**Modpack version**
Enigmatica 6 0.3.0
https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/3120142
Also tried this github setup with multimc with same results

**Issue**
To preface, Ive added the mods

```
pamhc2foodcore-1.16.3-1.0.0
https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core/files/3068560
CodeChickenLib-1.16.4-3.5.0.398-universal
https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files/3125157
EnderStorage-1.16.4-2.7.0.159-universal
https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8/files/3125158
appliedenergistics2-8.1.0.jar
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/3106770
ae2extras-1.0a-1.16.4.jar
https://www.curseforge.com/minecraft/mc-mods/ae2-extras/files/3120250

ftb-ultimine-1603.1.1.custom (This comes with the pack but I modified it so blocks go straight into the inventory instead of onto the ground, this was working completely as intended and been using it for most of my 30hrs in my world with no issues) 
```
Also, applied energistics and ender storage havent been used yet
To initially use the modpack, I downloaded the pack from curse, created an instance in multi-mc, imported the pack zip and then changed the "minecraft" folder to ".minecraft." which windows 7 corrects to ".minecraft". Then launched and everything worked fine. As I've been progressing in my world after about 30hrs, I noticed I cannot enter the nether even after entering it many times prior. I just get swirling effect and sound effects but do not travel to the nether. I searched and found this issue happened when air blocks appeared inside the refined storage system ~2years ago, not sure it applies. I can play the game normally in the over world and haven't noticed anything not working as intended otherwise. There is nothing popping up in the multi-mc log window when I try to go to the nether or anything. I believe the issue is with the save file and have run the broken save on a fresh instance of enigmatica 6 with the same results.

I have created new creative worlds (no survival ones) and testing going to the nether and it works all fine.

I am perfectly fine with starting a new world but I noticed there's tons of warnings and errors in the log that may be causing the issue? They are also making me worry that it will break another save if I do start another. Maybe they are all just normal warnings/errors and I stumbled into an edge-case save file corruption.

**Logs**
https://paste.ee/p/pYKEZ  (launch to the main menu using multi-mc log)
https://paste.ee/p/TttVl  (main menu to a loaded world log)

**Comment by NillerMedDild** [comment]
As far as I can see most of the errors in your log are normal. Modded Minecraft is a bit spammy :P

Deleting the nether folder from your world might fix this issue. 

This isn't something we've ever seen, so I'm gonna write it off as random world corruption and/or the mods you added.

**Comment by CoroNaut** [comment]
Ive already tried deleting Dim-1 to no effect. Those
```
no data fixer...
Exception loading blockstate definition...
Unable to load model:...
java.io.IOException: Server returned HTTP response code: 403 for URL: http://myurl.me/
Unable to resolve texture due to reference chain trim->trim in...
```
are like most of the log so i assumed something was going on. Lets hope it doesn't corrupt again I suppose.
