### ISSUE TITLE
Investigate Lithium

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#508]
https://www.curseforge.com/minecraft/mc-mods/lithium-forge-unofficial

**Comment by alanbaumgartner** [comment]
Wouldn't recommend investigating this mod, all it does is spawn mobs with random inappropriate names. Here is a snippet from one of its two classes.

![image](https://user-images.githubusercontent.com/2768746/101949416-350d8880-3bb9-11eb-98ba-07349e8c82cd.png)

**Comment by NillerMedDild** [comment]
Wow, thanks for the heads up.
