### ISSUE TITLE
[Suggestion] Alex's Mobs

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#509]
**Modpack version**
E6 0.3.1

**Suggestion**
This mod looks very interesting. All the mobs seems to have functionality, decent enough behaviour, and should add a lot of life to the world which should fill some of the exploration gap we have. 
Link: https://www.curseforge.com/minecraft/mc-mods/alexs-mobs
Video by Boodlyneck: https://www.youtube.com/watch?v=eoHnr-0Ev60&ab_channel=Boodlyneck

**Comment by MuteTiefling** [comment]
I was looking at this one too, thinking it might be interesting. I do very much like the idea of more monsters and these seem well thought out.

**Comment by Ridanisaurus** [comment]
I also love how well textured, and that every added animal has a purpose, not just clutter to the world. I love the potions system, I love that you can use some of the drops for alternative recipes like the Slime from the Komodo Dragon ..etc.
I also love that they can be mounted, and that they feel somewhat true to the Minecraft as they are all based on real-life animals. 
Imagine that now you will have to protect your Bee farms from Bears, so it will require the player to re-think having everything in the open, or exploring the Desert without Poison Protection is a bad idea due to the Rattle Snakes and Komodo Dragons. 

I honestly think it would be a huge upgrade to E6.

**Comment by NillerMedDild** [comment]
Sounds pretty sweet, I'll have a look soon :)
