### ISSUE TITLE
Manual Install Instructions

### ISSUE THREAD

**Issue by Hubok** [NillerMedDild/Enigmatica6#51]
I've just downloaded the source and I'm a bit lost as to how to install this manually. I'm on Linux, the Twitch launcher is not an option sadly.

**Comment by Darkere** [comment]
Use GD launcher or MultiMc to install the pack. The scripts are only used to launch a server. 

It is possible to use git and launch with the vanilla launcher but I do no recommend doing so.

**Comment by Hubok** [comment]
@Darkere Thank you for that, I forgot MultiMC supported loading Twitch-formatted packs. I had actually just gotten it to work through vanilla by grabbing the server pack and adding the 4 missing mods, but that's far less ideal and could've had other bugs.

I only had to modify these settings, and drop the Java 8 version checker because OpenJDK didn't like it.
![image](https://user-images.githubusercontent.com/1284419/88950737-0d013680-d263-11ea-944a-04e620e2e6f6.png)
