### ISSUE TITLE
Dupe with Pneumaticraft and Quark

### ISSUE THREAD

**Issue by AndrewFrye** [NillerMedDild/Enigmatica6#511]
**Modpack version**
0.3.0

**Issue**
Dupe with pneumaticraft logistics frames and quark extract from inventory button, you can click in items to the inventory frame without them pulling from the player inventory and the quark extraction button pulls the ghost items into the player inventory.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
