### ISSUE TITLE
Frost Walker effect when enchantment not used

### ISSUE THREAD

**Issue by Earendilgrey** [NillerMedDild/Enigmatica6#512]
**Modpack version**
0.3.0

**Issue**
Frost Walker effect is in use even though it is not equipped on any items.

https://youtu.be/zC38SoNxJi8

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by MaxFirestorm** [comment]
You don't have the Ice Shard Trinket from Lost Trinkets active do you? That gives you the Frost Walker effect at all times when active. The Trinket menu was probably the only thing I *didn't* see you go into in the video xD

**Comment by Earendilgrey** [comment]
Opps, that was it.  I forgot I even got that one.
