### ISSUE TITLE
Blood Magic Alchemy Table

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#518]
InDev

Need to change the Plant Oil recipe to use 3x any forge:crops instead of hard coded crops.

Gravel to Flint Recipe is broken as well, using 1 gravel and 1 flint to generate 1 flint. 

I'll work on these soon.

**Comment by MuteTiefling** [comment]
Hrm, something is breaking somewhere. I see the scripts are still in place, but they're not loading in the dev instance.

**Comment by MuteTiefling** [comment]
same with the ore processing for Astral... hrm, probably the unification script

**Comment by NillerMedDild** [comment]
I've found the cause, I think :) fixing now

**Comment by MuteTiefling** [comment]
Yeah, that fixes the issue with them being missing, but re-introduces one I was trying to avoid. Namely, the alchemy table now crushes gem ores like lapis and fluorite to mostly useless dust.

**Comment by NillerMedDild** [comment]
Ah my bad, didn't think about that :)
