### ISSUE TITLE
[Mod Suggestion] Serene Seasons

### ISSUE THREAD

**Issue by SQbuilder** [NillerMedDild/Enigmatica6#526]
Beta released yesterday.

https://www.curseforge.com/minecraft/mc-mods/serene-seasons

**Comment by NillerMedDild** [comment]
No thank you :) Last I added it to a pack good times were not had.

**Comment by SQbuilder** [comment]
I respect the decision 👍

**Comment by Erysch** [comment]
> No thank you :) Last I added it to a pack good times were not had.

Could I ask you where the problems were?
First problems I had with this mod was the incompatibility with the "greener grass" function from quark so I had to disable it. Some trees didn't lose color in winter but these trees were some winter trees like fir or spruce.

Another thing might be, that some "seasonal" biomes would be weird if you already had seasons everywhere. For example there is autumnity which would be weird to have an autumn forest in summer and spring.

I can imagine that the crop speed changes may be a bit weird and maybe not applicable on some modded crops but you can disable it complety in the config, if i remember correctly.

It would be interesting to know if any of these reasons hadn't given you a good time. 

Greetings (:

**Comment by NillerMedDild** [comment]
They were plentiful. For starters, the configs didn't work, so it was stuck on default.
