### ISSUE TITLE
Mod Suggestion - Out of Sight

### ISSUE THREAD

**Issue by MaxFirestorm** [NillerMedDild/Enigmatica6#529]
Mod link - https://www.curseforge.com/minecraft/mc-mods/out-of-sight

Unsure of the inner workings of it (I'm not technically minded >>; ) but the video comparison makes it look like it improves performance quite a bit!

**Comment by NillerMedDild** [comment]
While that looks interesting, I think it would have a very negative impact if we set it to a value that would actually help with FPS.
