### ISSUE TITLE
[Mod Suggestion] Variant16x

### ISSUE THREAD

**Issue by SQbuilder** [NillerMedDild/Enigmatica6#53]
https://www.curseforge.com/minecraft/mc-mods/variant16x

Stairs, slabs, buttons, fences, and etc for every block.

Includes addons for integration with Biomes O' plenty and Buzzier Bees.

Integration with BYG and Quark [coming soon*](https://www.curseforge.com/minecraft/mc-mods/variant16x?comment=55)

**Comment by NillerMedDild** [comment]
To be honest I'd rather wait for a mod like Carpenter's Blocks, as adding this many blocks has a noticeable performance impact.
