### ISSUE TITLE
Dupe/Delete items in RF Tools Modular Storage when activating Inventory Tweaks Sort function

### ISSUE THREAD

**Issue by taotau** [NillerMedDild/Enigmatica6#530]
**Modpack version**
0.3.0

**Issue**
Using RF Tools Modular Storage Block, with a Tier 2 Storage Module in it, middle clicking in the player inventory (by default this is bound to inventory tweaks sort function) causes all the items in storage to be transferred to the player inventory, including the Storage Module which will contain duplicates of its original contents.

If there are too many stacks in the Storage Module for the player to hold in their inventory, the excess items are deleted.  Based on the sort order of the items, if the Storage Module doesnt fit in the player inventory, it is also deleted.

**Logs**
https://pastebin.com/hSWqutxj

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
