### ISSUE TITLE
Can't craft Enchanted Crafting Table

### ISSUE THREAD

**Issue by kyleedwardsny** [NillerMedDild/Enigmatica6#531]
**Modpack version**
0.3.0

**Issue**
The JEI interface for the Enchanted Crafting Table (blue and green) shows that it can be crafted with four Enchanted Planks (blue or green respectively.) However, putting them in the crafting grid yields a vanilla crafting table.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Hmm, I'm not sure yet how to fix this issue. For the time being, you can use a Metal Crafting Table from Engineer's Decor to craft the Enchanted Crafting Table :)

**Comment by NillerMedDild** [comment]
To be honest I might just remove Enchanted Crafting Table, it doesn't add much. Would that "solution" be satisfactory?

**Comment by kyleedwardsny** [comment]
To be honest, I mainly wanted to craft this for aesthetic reasons (unless it serves some utility function beyond what the vanilla crafting table offers), so removing it would not be satisfactory, though I understand if you remove it for the sake of maintaining the quality of the modpack. I haven't yet tried the Metal Crafting Table workaround, but if it works then that would be sufficient.

**Comment by kyleedwardsny** [comment]
Update: I just tried the Metal Crafting Table workaround, and it worked. The metal table isn't too expensive either, so I consider this workaround satisfactory.
