### ISSUE TITLE
[Mod Suggestion] Jellyfishing

### ISSUE THREAD

**Issue by BlueDuckYT** [NillerMedDild/Enigmatica6#533]
https://www.curseforge.com/minecraft/mc-mods/jellyfishing
Jellyfishing adds a new colorful biome, jellyfish catching from Spongebob, new configurable weapons (Spatulas that flip your enemies into the air, karate gloves that have quick attack speeds) and an armorset (The Air Suit, based on Sandy's suit, which provides water breathing when underwater).  It also adds a ton of food.

**Comment by NillerMedDild** [comment]
No thanks, while it has some cool things I don't think it really fits in E6.

**Comment by BlueDuckYT** [comment]
Ok, no problem
