### ISSUE TITLE
[Mod Suggestion] 'Dustrial Decor

### ISSUE THREAD

**Issue by BlueDuckYT** [NillerMedDild/Enigmatica6#536]
https://www.curseforge.com/minecraft/mc-mods/dustrial-decor
Adds a ton of building blocks which should fit the modpack's theme very well.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I'll have a look when I get some time :)

**Comment by NillerMedDild** [comment]
Loving the textures, nice work!
