### ISSUE TITLE
Nether biome we cant enter

### ISSUE THREAD

**Issue by Apwalchan** [NillerMedDild/Enigmatica6#539]
**Modpack version**
0.3.0

**Issue**
in the nether when we go into the white biome, i think it has Endu mushrooms, it lags out the whole server, times out and then restarts but only after we tp the player away from the biome.

**Logs**
no crash log cause it doesnt crash just lags out

**Comment by NillerMedDild** [comment]
Thanks for the report, may I have the server's latest.log please? :)

**Comment by Apwalchan** [comment]
it didnt have anything on it about that crash its all about the day nothing to do with the lag and nothing ever pops up when we go into it, if you still want it let me know cause ill have to ask the server owner for it

**Comment by NillerMedDild** [comment]
I would still like it :)

**Comment by Apwalchan** [comment]
ok idk when he'll get back to me but ill keep ya posted, and give it to you when i get it thanks!

**Comment by Apwalchan** [comment]
well, he says there's no logs because it didn't crash and to just drop it cause we can just avoid the area, sorry

**Comment by NillerMedDild** [comment]
Err okay :/
