### ISSUE TITLE
[Mod Suggestion] Towers of The Wild

### ISSUE THREAD

**Issue by SQbuilder** [NillerMedDild/Enigmatica6#54]
https://www.curseforge.com/minecraft/mc-mods/towers-of-the-wild

Configurable tower structures (similar to the ones from Legend of Zelda: Breath of The Wild) that spawn in the world.
Includes compatibility with Waystones; a waystone will spawn on the top of each tower.

Currently Waystones are rare, as they mostly spawn in villages*. These towers make Waystones more common, which provides convenience and other benefits for exploration.

**Comment by NillerMedDild** [comment]
I've had my eye on that mod for a while, didn't know they spawned with Waystones though, that's damn nice!
