### ISSUE TITLE
Non-EE Ingot as Output

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#541]
**Modpack version**
E6 0.3.0

**Issue**
I noticed this issue where on my personal server the Osmium Ore/Chunk were smelted into Mekanism Osmium instead of EE. I tested it on Single Player and on the Official Server, and both smelted into the correct ingot. I wrote it as 1 off case, and was gonna wait to 0.3.1 to test it. However, someone on Discord just reported that they got Tinker's Mechwork Copper Ingot from smelting EE Copper Chunk, and only their server. It smelted correctly on a Single Player world, and I can confirm it works correctly on the Official Server.

Curious if this has something to do with some KubeJS and Configs being overwritten in the Server Instance.

Let me know if you need anything specific from my server to investigate this, or whether we want to until until 0.3.1 is out for further testing as it is working on the Dev Server.

**Comment by NillerMedDild** [comment]
I think I've fixed this by fixing a larger bug in our KJS unification. Let's see by 0.3.1 :D

**Comment by Ridanisaurus** [comment]
yea, I suspected as much. Thought I would report it just to we can keep track of it.

**Comment by NillerMedDild** [comment]
I still haven't seen this, any more reports of it? :)
