### ISSUE TITLE
Looking for help forking/ cloning the development version as a contributor (Windows)

### ISSUE THREAD

**Issue by toastonrye** [NillerMedDild/Enigmatica6#543]
Hi, I have tried following the instructions here: https://github.com/NillerMedDild/Enigmatica6
But I have not been able to figure it out, also I think Twitch moved Minecraft modding to a different platform?

I'm using Windows and MultiMC(which is my preferred launcher). I have installed GitHub desktop and successfully been able to clone it to my PC. However, I can't figure out how to get MultiMC to launch it. The only file I have tried running is setup.bat, which seems to download the mods fine.

Any suggestions? Thanks,

**Comment by toastonrye** [comment]
Update - So I installed Git, and was able to follow the Linux instructions and everything seemed to install correctly. However I have an error message:
![e6booterror](https://user-images.githubusercontent.com/26075330/102387952-aae96980-3f96-11eb-9aae-42ebbfcf6665.PNG)

Also the Forge version I picked was 34.1.42 and Minecraft 1.16.3 in MultiMC.

The log: https://pastebin.com/jiTewFZm

**Comment by toastonrye** [comment]
So I realized my mistake, the previous error I had javafml:35 is a hint (I'm new to this).
I remade my MultiMC instance with Minecraft version 1.16.4, then it gave me access to newer builds of forge. I chose 35.1.13 (the newest at the time of typing this) and it boots up fine!

**Comment by NillerMedDild** [comment]
Nice work :D admittedly the documentation for setting up the dev environment is not up to date.

**Comment by toastonrye** [comment]
> Nice work :D admittedly the documentation for setting up the dev environment is not up to date.

I've updated the steps I used here, https://github.com/toastonrye/Enigmatica6/tree/develop .
But I don't know how to submit it for consideration?

**Comment by NillerMedDild** [comment]
You make a Pull request, I believe you can do so here: https://github.com/NillerMedDild/Enigmatica6/compare/develop...toastonrye:develop?expand=1

**Comment by NillerMedDild** [comment]
I'mma reopen this to remind myself to give the README a once over :)
