### ISSUE TITLE
Tinker's Mechworks Drawbridge not retracting/extending

### ISSUE THREAD

**Issue by jeshyboi** [NillerMedDild/Enigmatica6#544]
**Modpack version**
0.3.0

**Issue**
The drawbridge block from Tinker's Mechworks seems to be having issues extending/retracting, even when powered by a redstone signal and with no blocks blocking its path. In my specific case, it worked only once, extending its blocks when supplied a redstone signal and then retracting them when the signal was removed, but when the signal was supplied again after that the drawbridge failed to extend.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Hm, I can't reproduce this. Could you supply pictures of your setup please?

**Comment by jeshyboi** [comment]
Hey, sorry for the late reply! Attached are pictures of the setup and inventory of the Drawbridge block.
![2020-12-18_01 28 40](https://user-images.githubusercontent.com/32647640/102732114-cb3d6d80-4374-11eb-82a8-112166d7db3f.png)
![2020-12-18_01 28 45](https://user-images.githubusercontent.com/32647640/102732118-cd9fc780-4374-11eb-9fba-d1e8c45435f6.png)

**Comment by NillerMedDild** [comment]
Redstone torches do not supply power to the block they're attached to, use a lever :)

**Comment by jeshyboi** [comment]
Hi sorry, I tried a lever (I did it before but didn't take snapshots) and it still doesn't seem to be working? Sorry to bother!
![2020-12-22_00 04 14](https://user-images.githubusercontent.com/32647640/102796548-68d28480-43e9-11eb-8c3c-de06ae627ae7.png)
![2020-12-22_00 04 17](https://user-images.githubusercontent.com/32647640/102796550-6a03b180-43e9-11eb-885d-313bccd5af8f.png)


![2020-12-22_00 03 55](https://user-images.githubusercontent.com/32647640/102796541-66702a80-43e9-11eb-8dab-87820aa6b8f5.png)

**Comment by NillerMedDild** [comment]
Hmm, was this on a server or singleplayer?

**Comment by jeshyboi** [comment]
This was on a server, I haven't tested the problem in single player - would that help?

**Comment by NillerMedDild** [comment]
Yeah no, still can't reproduce it :s which block do you have in there?

**Comment by MuteTiefling** [comment]
This is a fake player issue. The chunk you're using it in is claimed, so you'll need to add Tinker's Mechworks as an ally.
