### ISSUE TITLE
Immersive Engineering Mineral Survey Tools doesnt provide a readout

### ISSUE THREAD

**Issue by scott-dunbar** [NillerMedDild/Enigmatica6#546]
**Modpack version**
0.3.0
Using Forge-1.16.4-35.1.0

**Issue**
Immersive Engineering Mineral Survey Tools doesnt provide a readout when right clicking on ground.

It will correctly readout when right-clicking on something that it cannot be used on

1. Equip the Mineral Survey Tools
2. Right click on grass, dirt or stone block
3. Observe no output
4. Right click on tall grass or woodplank block
5. Observe correct error message displayed

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report!

In step 2, did you hold right click?

**Comment by scott-dunbar** [comment]
Oh you know what - I didnt hold it long enough, good call. Apologies. Works fine after like 3 seconds.
