### ISSUE TITLE
(Xerca Mod) Croissant is not craftable

### ISSUE THREAD

**Issue by xenoflot** [NillerMedDild/Enigmatica6#548]
**Modpack version**
6-030

**Issue**
Recipe shown in JEI for the croissant, two sugar and four wheat, is not craftable in either workstation or vanilla crafting bench. It can be shift-clicked into the bench, but no output is given.

**Logs**
n/a

**Comment by MuteTiefling** [comment]
The mod is being removed entirely in 0.3.1.

**Comment by xenoflot** [comment]
Right then. I shalln't build with its blocks :P
