### ISSUE TITLE
Not seeing any Biomes O' Plenty biomes on multiplayer server

### ISSUE THREAD

**Issue by DragonScale6** [NillerMedDild/Enigmatica6#549]
**Modpack version**
0.3.0

**Issue**
Not seeing any Biomes O' Plenty biomes on the multiplayer server I made

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
This will be fixed in 0.3.1, please see the top of the changelog when it's released. I hope to get it out tomorrow evening, ~22 hours from now :)
