### ISSUE TITLE
[Mod Suggestion] CC:Tweaked

### ISSUE THREAD

**Issue by ben-mkiv** [NillerMedDild/Enigmatica6#55]
some computer mod would be neat, and as OpenComputers probably wont be ported soon (still on 1.12.2) CC:Tweaked is the only alternative
https://www.curseforge.com/minecraft/mc-mods/cc-tweaked

**Comment by NillerMedDild** [comment]
duplicate of #29 :)

**Comment by ben-mkiv** [comment]
nvm, sorry
