### ISSUE TITLE
Ars Nouveau Enchanting Apparatus Crash

### ISSUE THREAD

**Issue by creepystalker2** [NillerMedDild/Enigmatica6#557]
Version: 3.0.0

When attempting to right click an enchanting apparatus from ars nouveau while it is crafting, the game crashes.

[https://pastebin.pl/view/c7a7399f](https://pastebin.pl/view/c7a7399f)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Found it reported here: https://github.com/baileyholl/Ars-Nouveau/issues/97
