### ISSUE TITLE
[Create] Chocolate and Honey are showing as direct replacements for water in many machines

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#559]
**Modpack version**
indev

https://github.com/Creators-of-Create/Create/issues/548

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5719815/latest.log)

Confirmed it's happening in a test pack with only Create/Mek/Immersive/JEI

**Comment by NillerMedDild** [comment]
That is.. rather alarming. Do the recipes work?

**Comment by MuteTiefling** [comment]
Indeed they do: 
![image](https://user-images.githubusercontent.com/9543430/102700271-f52e4d00-4219-11eb-80ef-cc6c84c8f060.png)

**Comment by NillerMedDild** [comment]
Oh my. What about the normal recipes?

**Comment by MuteTiefling** [comment]
Yeah, the normal stuff appears fine still. it's just like they somehow tagged their fluids as water

**Comment by Darkere** [comment]
They probably did. For a reason too. Not a great one but it's a reason

**Comment by NillerMedDild** [comment]
I feel like we're missing a great story here :P
