### ISSUE TITLE
[Mod Suggestion] Ender Storage

### ISSUE THREAD

**Issue by EntropyRiot** [NillerMedDild/Enigmatica6#56]
http://www.9minecraft.net/ender-storage-mod/

Ender Storage Mod 1.15.2/1.12.2 adds multiple Ender Chests with separate inventories. It also adds the Ender Pouch, an item that allows access to the contents of a corresponding Ender Chest from anywhere. This mod overrides the vanilla Ender Chest.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, but a few things:

1) 9minecraft.net is a website that steals mods. Please don't not ever use it. You can read details here: https://stopmodreposts.org/

2) Enigmatica 6 is for Minecraft 1.16, and EnderStorage does not have a version that is compatible with 1.16, so it is impossible to add.

**Comment by EntropyRiot** [comment]
Cheers for the heads up.
