### ISSUE TITLE
[Create] Ore processing with Create produces Create-brand crushed ore

### ISSUE THREAD

**Issue by Aelphais** [NillerMedDild/Enigmatica6#561]
**Modpack version**
dev build 93e41b4

**Issue**
Creating the crusher setup and tossing in EE chunks or vanilla ores produces the Create mod version of Crushed [material] Ore rather than the expected EE dust.

I assume this has been noticed already, but just thought I would make an issue regarding it just to be sure. I also assume that other Create recipes need to be altered, but haven't found anything else that warrants an issue just yet. I honestly don't know much about how the mod works or everything that it can do. Just thought I would check what I assumed to be the big things.

**Comment by NillerMedDild** [comment]
Thanks for the report o/

Even though Create Crushed materials are very similar to dusts, they're not the same. They can be cooled down into 10 nuggets with a chance of 5 extra, so they're a bit better than dust really. So we're not unifying them.

I appreciate the report regardless! :)
