### ISSUE TITLE
Apparent Dupe issue w/ RS, the 'big' disks from Extra Disks and a Disk manipulator

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica6#564]
**Modpack version**
E6 0.3.0 - On the pack server

**Issue**
While purging off storage from a couple 256k disks in a disk manipulator to the network, It rapidly began to consume more space than expected and drove the server to 1 TPS. After Darkere fixed it, I logged back and noted that many of the resources appear to have duplicated themselves exponentially. 
For example - 125k black lotus, 30k bread, etc.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Trostmm** [comment]
Note - I tried exporting all the items, it may in fact just be a visual glitch as I didn't get 30k bread out to a bin. So possibly just phantom items.

**Comment by NillerMedDild** [comment]
That doesn't sound good, we'll see if we can reproduce it - Thanks for reporting!

**Comment by Trostmm** [comment]
An update, it just mostly seems to have fuxored my RS inventory display. 
The actual amounts seem to be a touch inflated, but not the crazy amount it is displaying.
After exporting all of 1 'type' and breaking the controller and replacing it it will display the quantity for that item correctly.

**Comment by NillerMedDild** [comment]
I cannot reproduce this :/ not even the visual glitch. Can you?

**Comment by Trostmm** [comment]
Well, now that the server updated to 0.3.1 the visuals went away as well. Everything went back to normal... So i'll try to reproduce, but it may be moot now.

**Comment by NillerMedDild** [comment]
Will close for now, let me know if you can reproduce :)
