### ISSUE TITLE
Productive Bee Issue

### ISSUE THREAD

**Issue by tonyvans** [NillerMedDild/Enigmatica6#57]
**Modpack version**
Enigmatica 6 Version: 0.2.3

**Issue**
Iron Bee and Tin Bee have the same recipe (combining a crystalline bee and an ashy mining bee) not sure if deliberate 

also when you look at bee description you get this (also not sure if deliberate) 
![image](https://user-images.githubusercontent.com/6739653/89107870-e10fbd80-d3e8-11ea-8f79-7674182485ba.png)

Thanks

**Comment by NillerMedDild** [comment]
I'll look into the first issue, thanks. The huge tooltip is normal :)

**Comment by tonyvans** [comment]
I had never seen a huge code ish type text in a tool tip before. I figured it was missing some sort of formatting overlay or something. 
Keep up the awesome work.
Thank you

**Comment by NillerMedDild** [comment]
I asked over there and they let me know that is intentional, one of the bees will be chosen at random.

**Comment by tonyvans** [comment]
guess I was just unlucky, will keep trying. thanks
