### ISSUE TITLE
[Suggestion] Dungeon Gear and Dungeon Mobs

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#574]
**Modpack version**
E6 0.3.*

**Suggestion**
These 2 mods technically can be added separately, but they fit together perfectly. They add the mobs and gear that was introduced in Minecraft Dungeons which should add a nice variety to the game. 
It should help the adventuring and exploration play style quite a bit, and with the usage of cosmetic armor, they can also be collected just to change the look of the standard armor in game. The models look fantastic, and apparently the mod devs are working to keep everything updated, including additional mobs and items when available, and the animation of mobs.

Dungeon Mobs: https://www.curseforge.com/minecraft/mc-mods/dungeons-mobs
Video Showcase: https://www.youtube.com/watch?v=NxogJuhUAZ8&t=124s&ab_channel=Boodlyneck

Dungeon Gear: https://www.curseforge.com/minecraft/mc-mods/dungeons-gear
Video Showcase: https://www.youtube.com/watch?v=NxogJuhUAZ8&t=163s&ab_channel=Boodlyneck

**Comment by NillerMedDild** [comment]
While it does look really cool, I'm not sure how well it would blend into E6. Do you know where/when/how the mobs spawn?

**Comment by Ridanisaurus** [comment]
This is from their CF Page `There are extensive spawn configuration options for most mobs to allow them to spawn throughout your world, even in modded biomes, right out of the box.`

I'll download it, and play with it locally for a bit and see all the configs and what is possible and not possible.

**Comment by Ridanisaurus** [comment]
Okay, I had enough time to play around with this mod, and .. I like it. It has some minor textural issues here and there, but I would assume these will be fixed in time. 
The overall feel is pretty decent, and the mobs and loot are heavily configurable. It adds A LOT of cool weapons, armors, and talismans which I feel would add another level of reward to players, and the numbers seems to be pretty decent.

I encountered only a handful of special mobs that spawn naturally but it does make the standard mobs a little harder with armor and weapons. It adds the little version of other mobs like the Creeper and Skeleton, which is fairly threatening.
The special mobs seem to only spawn as part of raids, which is also heavily configurable.

I would say give it a look, and see how you feel about it.
Personally, I really like it, and I think it adds pretty good reward to those that like to explore and play immersive over being bunkered down in a hole and just expanding with machines. It also seems not affect that play style, so those that don't want to partake in exploration and adventure, they can just ignore it all together.

**Comment by NillerMedDild** [comment]
Alright, I'll have a look. 
Full disclosure, I would prefer not to add this, as it's a ton of new items and entities to add without a specific purpose in the pack.

**Comment by Ridanisaurus** [comment]
Makes sense, and that's quite fair.

**Comment by NillerMedDild** [comment]
very full mods, but I don't think they really fit.
