### ISSUE TITLE
Tetra: Alternatives to Diorite as T2 hammer

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#579]
Diorite might not generate in the future, so we need alternatives to Diorite for T2 hammer. 

Remember to update the T2 hammer quest accordingly.

**Comment by MuteTiefling** [comment]
Lead, perhaps?

**Comment by NillerMedDild** [comment]
I was thinking worldgen stones, slate, marble, andesite etc :)

**Comment by Oliverr100** [comment]
Sandstone / Red Sandstone or maybe Bricks
