### ISSUE TITLE
Botania & AIOT Botania 

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#58]
Now **Botania** and **AIOT Botania** release in **Curseforge** for **Minecraft 1.16.1**
https://www.curseforge.com/minecraft/mc-mods/botania/files/3020428 (Botania)
https://www.curseforge.com/minecraft/mc-mods/aiot-botania/files/3020442 (AIOT Botania)

**Comment by NillerMedDild** [comment]
Already have Botania added in my own instance, not AIOT though :)
