### ISSUE TITLE
Odd Quest Dependency

### ISSUE THREAD

**Issue by bunnyman14** [NillerMedDild/Enigmatica6#581]
**Modpack version**
0.3.0

**Issue**
Latex Processing Unit requires Heavy  Plated Shield as a dependency... for some reason? I have made the unity without making the shield and should not have to make the shield to make latex.

**Logs**
![2020-12-20_20 07 13](https://user-images.githubusercontent.com/7276888/102729636-7dd2e900-42ff-11eb-8811-32725f05e209.png)

**Comment by MuteTiefling** [comment]
Please update. This has been fixed :D
