### ISSUE TITLE
Crafting Table recipes for gears missing (for me, but not other people)

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#585]
**Modpack version**
0.3.1

**Issue**
The recipes for gears in a crafting table do not show up for me. The recipe still works but it gives a different gear for me than other people (it works just fine in recipes though).

In the discord people showed me that they got a regular thermal iron gear, but I get a iron gear from Titanium.

https://i.imgur.com/fqHDwdt.png

https://i.imgur.com/XGZwQNP.png

Fresh world on 0.3.1 other people may have been on a 0.3.0 world that updated to 0.3.1, if that makes a difference.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

May I have your latest.log please?

**Comment by RevenantWendigo** [comment]
Downloaded with the 0.3.1 zip from Curseforge and then through MultiMC. 

latest.log: https://gist.github.com/RevenantWendigo/6c7b011eb1478563cc0dd90f290b5957

**Comment by NillerMedDild** [comment]
I'm not sure what's going wrong to be honest. Have you tried restarting and/or redownloading the update?

**Comment by RevenantWendigo** [comment]
I tried a reset with no luck. I'll try a reinstall tomorrow.

Also, I got this server up and running by generating the server files on my PC and then zipped and uploaded them to Bisect (I was too impatient to wait for Curseforge to update when 0.3.1 went live). Any chance that could have caused this problem?

**Comment by NillerMedDild** [comment]
Depends, did you remember to include the KubeJS folder?

**Comment by RevenantWendigo** [comment]
Yeah here is the full directory. 

https://i.imgur.com/z9PU9Sx.png

Then I configured the server to run the forge jar.

**Comment by NillerMedDild** [comment]
Actually.. The gear isn't supposed to be from thermal either. Are you sure others got that?

**Comment by RevenantWendigo** [comment]
https://cdn.discordapp.com/attachments/726178356143456287/790454468729634836/unknown.png

Talked with the others in the discord this is the gear they got. Looks like it is the proper one. I thought that was the thermal one, sorry about that.

**Comment by RevenantWendigo** [comment]
Ahh I know where I got mixed up. MINE are the thermal ones when I craft it despite not being able to see the recipe. I think my server is just borked. Hopefully once I do the 0.3.2 update it works out.

**Comment by NillerMedDild** [comment]
Alright, I'll close this for now, we can reopen if needed when you've updated :)
