### ISSUE TITLE
Mod Suggestion: Rats

### ISSUE THREAD

**Issue by KangyKSLG** [NillerMedDild/Enigmatica6#587]
No issue, just wondering if anyone has suggested adding rats and if not can I be considered please? :)

**Comment by NillerMedDild** [comment]
Rats was in the pack but was removed because of critical issues with world loading :)

**Comment by KangyKSLG** [comment]
Fair enough, thank you for the response!

I know this is closed now but can I request Cyclic be added if it's not already being looked at or been rejected already?

**Comment by NillerMedDild** [comment]
https://github.com/NillerMedDild/Enigmatica6/issues/37 - Please search for existing suggestions before making new ones :)

**Comment by Darkere** [comment]
Although tbf. We've since discovered that the world loading issue is actually a Vanilla problem. 
Not that I think rats would fit in a serious pack.

**Comment by KangyKSLG** [comment]
> #37 - Please search for existing suggestions before making new ones :)

Sorry I normally do search as well. Oops haha

**Comment by toothmonsterr** [comment]
> Although tbf. We've since discovered that the world loading issue is actually a Vanilla problem.
If this is the case, would it be possible to reconsider for 0.4.0? It seems to add an interesting diversity to managing storage and farms and I'm not sure we have very many animal companion mods.

**Comment by Darkere** [comment]
Rats is a fun mod don't get me wrong. However fitting it into a bigger modpack just doesn't work that well. 

I've unfortunately still not seen the rats actually work and not break when making farms. Balancing the mod would be a nightmare and combined with the fact that entities are the biggest lag factors in 1.16, it just isn't a good idea. 

Additionally Ars Nouveau does also provide entity based item transport and such.
