### ISSUE TITLE
Ram use

### ISSUE THREAD

**Issue by ryanj1792** [NillerMedDild/Enigmatica6#588]
**Modpack version**
0.3.1

**Issue**
I keep getting random lag spikes I was running off a server on 0.3.0 and now running a single player world and its pushing well over 10 gigs of ram. Any ideas?

**Comment by Darkere** [comment]
There is a known memory leak. We will be updating to fix it soonish.

**Comment by ryanj1792** [comment]
oh okay cool :) thought it was me breaking something xD

**Comment by stefment** [comment]
Is there anything we can do in the meantime? for me it gets unplayable after about 15 minutes :P

**Comment by gh-joliver** [comment]
Issue is with Astral sorcery. Downgrade it, or upgrade if they fixed it already.

**Comment by stefment** [comment]
Im tempted to remove the mod for now

**Comment by bunnyman14** [comment]
Glad I found there was an update that fixed this. It made the game completely unplayable.

**Comment by NillerMedDild** [comment]
It did indeed :P
