### ISSUE TITLE
Applied Energistics 2 

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#59]
Release on **Curseforge** but only alpha ver. 
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/3020576

**Comment by NillerMedDild** [comment]
Also have that added in my instance, thanks for the suggestion anywho!

**Comment by NillerMedDild** [comment]
AE2 doesn't load on servers, so I'm gonna hold off a bit on adding it.

**Comment by TGMax233Michael** [comment]
Maybe wait until this bug is fixed？
I will wait patiently :)

**Comment by TGMax233Michael** [comment]
**Applied Energistics 2** Now update to **Alpha 2** ver. , maybe try to put it into this modpack again?

**Comment by TGMax233Michael** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/releases (Github)
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/3024462 (CurseForge)

**Comment by nfowler** [comment]
The newest release specifically fixes the serverside issue. Mentioned among the bugfixes is this:

#4531: Not able to launch dedicated server due to usage of client-only classes.

**Comment by TGMax233Michael** [comment]
I also saw that :)

**Comment by TGMax233Michael** [comment]
Hope to join soon
