### ISSUE TITLE
mod suggestion: woot

### ISSUE THREAD

**Issue by MercilessArchitect** [NillerMedDild/Enigmatica6#590]
less laggy mob farms

**Comment by Quezler** [comment]
looks like [woot](https://www.curseforge.com/minecraft/mc-mods/woot) has an stable release build for 16.4 on the 12th of december 👍

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I'll have a look.

**Comment by NillerMedDild** [comment]
This is gonna be a nope :)
