### ISSUE TITLE
mod suggestion: caged mobs

### ISSUE THREAD

**Issue by MercilessArchitect** [NillerMedDild/Enigmatica6#591]
https://www.curseforge.com/minecraft/mc-mods/caged-mobs
easier mob farming, with less lag. the blocks are very pretty, too

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I'll have a look.

**Comment by NillerMedDild** [comment]
I've reconsidered, and will not be adding this. It's simply too easy.
