### ISSUE TITLE
Optifine Crash when Searching in Creative Inventory Screen

### ISSUE THREAD

**Issue by KeeganStandifer** [NillerMedDild/Enigmatica6#603]
**Modpack version**
0.30

**Issue**
I am able to consistently crash the game with OptiFine HD U G5 installed.

1. Join a fresh Enigmatica 6 Server
2. OP myself
3. /gamemode creative
4. Open inventory
5. Search for berry
6. Crash

**Logs**
https://pastebin.com/U9846Fu5

**Comment by NillerMedDild** [comment]
Thanks for the report. Does this also happen on 0.3.2? :)

**Comment by KeeganStandifer** [comment]
No problem! It does. Just tested and confirmed. 

Crash Report: https://pastebin.com/jk2jHs8J

**Comment by NillerMedDild** [comment]
As a temporary workaround you can unbind or change the Find Me keybinding - It's set to Y atm :)

**Comment by KeeganStandifer** [comment]
Thanks, that worked for me! I did run into a similar crash when clicking the recipe for the mana condenser in the quests window. Paste bin here: https://pastebin.com/epMXGe9H Seems unrelated to the findme pack this time.

**Comment by NillerMedDild** [comment]
Awesome, another Optifine crash :P ty

**Comment by NillerMedDild** [comment]
Reported that here: https://github.com/FTBTeam/FTB-Quests/issues/508
