### ISSUE TITLE
Compression dynamo bugged

### ISSUE THREAD

**Issue by CjayIsBack** [NillerMedDild/Enigmatica6#604]
**Modpack version**
3.2

**Issue**
Immersive engineering's gasoline does not work in the compression dynamo, neither does LPG, nor liquid ethylene 

**Logs**
no logs

**Comment by NillerMedDild** [comment]
We'll get support for that added :)

**Comment by MuteTiefling** [comment]
Or re-added. Probably needs a re-do as a result of the new kjs thermal integration. Will look at that later today. Been going through a multitude of other broken recipes.

**Comment by MuteTiefling** [comment]
Looks like the fuel values for ethylene and lpg are simply too high for the dynamo. It works if lowered.
