### ISSUE TITLE
Unable to travel to nether after newest update

### ISSUE THREAD

**Issue by Mars455** [NillerMedDild/Enigmatica6#606]
**Modpack version**
Enigmatica6-0.3.2
**Issue**
Unable to travel to nether, get nausea effect, nether not in level.dat either

**Comment by Darkere** [comment]
Check the changelog for 0.3.1

**Comment by NillerMedDild** [comment]
Did following the instructions in the changelog resolve your issue?

**Comment by Mars455** [comment]
I ended up copying data across to a new world (basically resetting)
