### ISSUE TITLE
0.3.2 Server semi locks up after running for several hours, users get kicked, cant log back in

### ISSUE THREAD

**Issue by Arcitect-X** [NillerMedDild/Enigmatica6#607]
**Modpack version**
0.3.2 Server

**Issue**
After several hours minecraft server it kicks the players and when logging back in it gets stuck on the encryption stage.  No commands can be run from minecraft player chat, cant TP, Floor switches dont work, doors can only be opened with right click.  Chunks that are pregenned dont load

This issue started happening in 0.3.1 and was not an issue in 0.3.0

Workaround is to reboot the server

(Server is hosted by Bisect)

**Logs**
[debug.log](https://github.com/NillerMedDild/Enigmatica6/files/5730503/debug.log)
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5730510/latest.log)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Does it only happen when `Arconaute` is around? :P

**Comment by Arcitect-X** [comment]
lol Arconaute is me

**Comment by NillerMedDild** [comment]
Does it happen when your region of the world isn't loaded?

**Comment by Arcitect-X** [comment]
I am not sure.  I guess I would have to try that out.   Right now I can not reproduce the issue.   I had removed Towers of the wild as we were getting lots of errors with that mod.   I put the towers for the wild mod from the Curse Forge app client onto the server and I can no longer reproduce.   I'll see if it happens again when everyone gets on.  If it doesnt then we can probably close this issue.

**Comment by Arcitect-X** [comment]
I did fly around both where it was pregenned and outside that area with no issues just now

**Comment by NillerMedDild** [comment]
Alright, fingers crossed :D

**Comment by Arcitect-X** [comment]
thx

**Comment by Arcitect-X** [comment]
So we are still having the issue.  It seems to happen the most when near a specific players base (his base has lots of machines).  It happens to me more because I am on more than other players (I'm one of the admins).  I will TP to the players base and then same issues, cant run commands, switches dont work etc.   I see the waiting on server message and then I get kicked.  We have noticed that the server is way behind at this point, like 4000 ticks.  Even with just me on the server.  Once I get kicked I can not log in  as it gets stuck on encryption.  The bisect console does show me trying to log in.  Not sure where to begin to troubleshoot this.  I am not sure that we can roll back to .3.0

Only messages I see are a bunch of:
[23.12 09:41:47] [Server] [Server thread/ERROR] [minecraft/Structure]: Unknown structure piece id: dungeons_plus:bigger_dungeon_

**Comment by Arcitect-X** [comment]
When trying to log back in after getting kicked I said it was getting stuck on encryption, it turn out that it eventually fails.

**Comment by Arcitect-X** [comment]
[latest2.log](https://github.com/NillerMedDild/Enigmatica6/files/5737143/latest2.log)
 Today's log

**Comment by NillerMedDild** [comment]
Sounds like severe server lag caused by something awful in that players base :P
Does have anything crazy? Fast spawners for example?

**Comment by Darkere** [comment]
Does the ingame chat continue to work when this happens?

**Comment by Arcitect-X** [comment]
We do have a blaze farm there and several powerplants,   Automated sheep sheering farm, bee farm, nether portal

**Comment by Arcitect-X** [comment]
the in-game chat does not continue.  I am unable to send any commands

**Comment by Arcitect-X** [comment]
We did add the discord integration mod.  That was working fine with 0.3.0.  We have not had an issues with it either

**Comment by Darkere** [comment]
There is a known issue with IF Fluid extractors causing a lockup. However, I was able to easily diagnose the issue because commands were still working fine. Running some spark profiling revealed the culprit.

Where is this server running? How much access to you have?

**Comment by KangyKSLG** [comment]
Hi Guys, the base in question is my base. I do have a fast blaze spawner from Apothiosus but you have to be next to it for it to work so it isn't running constantly. 
I also have various Mekanism machines, a couple of Powah reactors and 3 thermal machines.
Along with a basic RS system.
I have 1 Mekanism Turbine and 2 Mekanism fission reactors + the setup for Polodium (or whatever it's called haha)

**Comment by Darkere** [comment]
To confirm it is not the spawner going wrong you could set the game to peaceful temporarily.

**Comment by KangyKSLG** [comment]
Sure thing

**Comment by Arcitect-X** [comment]
So we were unable to recreate this issue once we removed the spawner, putting it back did not recreate the issue.   Maybe it was just a one-off.  Closing issue
