### ISSUE TITLE
Ars/RS crash, breaking block with gui

### ISSUE THREAD

**Issue by Flabort** [NillerMedDild/Enigmatica6#609]
**Modpack version**
3.2

**Issue**
Breaking a Refined Storage block (such as an Exporter) with a GUI connected to an active network using Ars spell Touch-Break-Extract causes a crash.

A gui breifly opens of the block that was broken, after the break has already happened, and then the server shuts down. 

**Logs**
I don't have access to server crash logs, ask Darkere.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Reported by others here: https://github.com/baileyholl/Ars-Nouveau/issues/87
