### ISSUE TITLE
0.3.2 Quest text makes a consistent grammar mistake all over the place.

### ISSUE THREAD

**Issue by EXPErdelfavero** [NillerMedDild/Enigmatica6#610]
**Modpack version**
0.3.2

**Issue**
Quest text consistently uses "it's" (contraction of "it is") when it should be using "its" (third person possessive).

I don't recall seeing  "it's" used properly. Change them all to "its" and you're guaranteed to have fewer errors.

If you want a proofreader, I do that for a living and would be willing to help out here 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by MuteTiefling** [comment]
If you can provide a list of the ones you've noticed, that would be appreciated. I can take a pass through and double check as well.

**Comment by MuteTiefling** [comment]
Scratch that. I've gone through the whole lot and found less than half of them were improperly used : D This stuff happens when you're writing late at night. Should be fixed next update.
