### ISSUE TITLE
[Suggestion] Eidolon - Dark Magic Mod

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#613]
**Modpack version**
E6 0.3.*

**Suggestion**
This looks pretty freaking good, and it seems to be fairly flushed out for a first release. Feels like a simplified Thaumcraft but without all the boring Research :P
Link: https://www.curseforge.com/minecraft/mc-mods/eidolon
Videos by Elucent: https://www.youtube.com/playlist?list=PLstuBTi-VKdtX65GGvwLKLV7wFxHGM4T2

**Comment by NillerMedDild** [comment]
That does look good, will most likely add it.
