### ISSUE TITLE
Ancient Debris Enrichment Chamber Recipes

### ISSUE THREAD

**Issue by GarethCarew** [NillerMedDild/Enigmatica6#614]
**Modpack version**
0.3.2

**Issue**
Ancient Debris has two recipes in Mekanism's Enrichment Chamber.

![image](https://user-images.githubusercontent.com/50182665/102963374-89b0dd80-44ae-11eb-9ade-0e0521d815fb.png)

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
