### ISSUE TITLE
Curio button not working

### ISSUE THREAD

**Issue by waldorf66** [NillerMedDild/Enigmatica6#617]
**Modpack version**
0.3.2

**Issue**
curio button is not opening curio inventory, nor the shortcut.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Thanks for the report.

Unfortunately I cannot reproduce this, it works just fine for me. Did you change anything with the modpack?

**Comment by waldorf66** [comment]
Hi, I guess it was caused by a faulty installation upon update. A fresh installation fixed my issue
