### ISSUE TITLE
Activating a holding rail from Transport with any minecart crashes the game.

### ISSUE THREAD

**Issue by TheHyperMagi** [NillerMedDild/Enigmatica6#618]
**Modpack version**
0.3.2

**Issue**
Encountered in multiplayer where if you place a modular minecart with item loader and fuel engine modules and placed on a holding rail and activating rail crashes the game.

Can be replicated in single player and multiplayer by making a modular minecart with those modules and placing them on a holding rail and activating it with a button.

**Logs**
Multiplayer crash log.

I have replaced your crash report dump with a link to it, so it doesn't take forever to scroll to the bottom of the issue :P
https://gist.github.com/NillerMedDild/f3f38517cbba922a8b3543e7a179786b

**Comment by TheHyperMagi** [comment]
On further investigation it's just any minecart on a holding rail being activated.

**Comment by NillerMedDild** [comment]
Thanks for report, I'll relay as soon as I can :)

**Comment by NillerMedDild** [comment]
Ah, reported here: https://github.com/BrassGoggledCoders/Transport/issues/19
They recommend you do not use Transport rails at this time.

**Comment by TheHyperMagi** [comment]
Ah, should have checked their repo first, thanks for the effort 🤗
