### ISSUE TITLE
[Quest] Bee Nests Issue

### ISSUE THREAD

**Issue by Octr** [NillerMedDild/Enigmatica6#619]
**Modpack version**
Enigmatica 6: 0.3.2

**Issue**
bee nests quest in feed the bees does not complete until the player creates a Tier 1 Beehive (for Tier 1 Beehive quest in the chain)

https://discord.com/channels/195234321836146688/544589452492931076/791313542527320084

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
