### ISSUE TITLE
[Mod Suggestion] The Outer End

### ISSUE THREAD

**Issue by BlueDuckYT** [NillerMedDild/Enigmatica6#620]
https://www.curseforge.com/minecraft/mc-mods/the-outer-end
Brand new and in beta, but it adds a new biome to the End (with BetterEnd compat)
and slows down end progression.  
Also adds a new structure, the End Tower, which will eventually contain a boss but currently has giant procedurally generated labyrinths underneath.

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by NillerMedDild** [comment]
So I had a look and I like The Outer End, feels like a high quality mod that does what it says on the tin, and does it well,

That being said, I think Enigmatica 6's End dimension is overly diverse as it is, so it's going to be a no for the time being. It's possible I'll disable Biomes You Go End biomes and add The Outer End in the future.

**Comment by NillerMedDild** [comment]
We will not be adding more End Biome mods, BYG is plenty :)

**Comment by BlueDuckYT** [comment]
Will this be reconsidered with the removal of BYG’s end biomes in 0.5.0?

**Comment by CletusMAngo** [comment]
BetterEnd will still have its biomes so id assume not, up to the bossman tho

**Comment by NillerMedDild** [comment]
I'm afraid not.
