### ISSUE TITLE
no recipe for cheese slice

### ISSUE THREAD

**Issue by stefment** [NillerMedDild/Enigmatica6#621]
**Modpack version**
3.1

**Issue**
i wanted to make pizza and it requires a cheese slice but there seems to be no recipe to make it

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by stefment** [comment]
Argh. Sorry about that. I didnt realise you had to place it in the world to cut the cheese up. Sorry.

**Comment by NillerMedDild** [comment]
No worries! :)

**Comment by NillerMedDild** [comment]
Actually I think that's a hard thing to guess, I'll add a JEI description page
