### ISSUE TITLE
PNC: Memory Stick XP Dupe Bug

### ISSUE THREAD

**Issue by Figulus88** [NillerMedDild/Enigmatica6#623]
**Modpack version**
0.3.2

**Issue**
If you have empty PNC Memory Sticks stacked together when storing XP, they will not separate automatically when you store the XP, and if you manually separate the stack afterward, you can get back multiples of what you stored (2 sticks doubles, 3 sticks triples, etc.)

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
