### ISSUE TITLE
Potential fps drops

### ISSUE THREAD

**Issue by ryanj1792** [NillerMedDild/Enigmatica6#626]
**Modpack version**
0.3.2

**Issue**
The game runs fine for me but my mate with a slightly lower end PC seems to having alot of random FPS drops. Despite his machine being a bit lower rated than mine task manager still shows that he isn't maxing out on anything and have plenty of ram allocated. Was just wondering if it could be a potential issue on the pack? He did update from the last version while i installed a fresh copy so not sure if an issue was maybe carried over. Any idea would be welcome.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Please see https://gist.github.com/NillerMedDild/40b4992b7a3e5e653a353fe1d45f2185 for a setup guide :)
Diagnoseing random FPS drops isn't really something we can do, there could be thousands of potential causes.
