### ISSUE TITLE
Add Alex's mobs to Megatorch/Dread Lamp configs

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#628]
**Modpack version**
0.3.1

**Issue**
These guys are apparently a bit out of control in places. Mosquitos in particular. They ought to be added to the configs for the megatorch/dread lamp so players can prevent them spawning.

**Comment by glubo** [comment]
On 0.3.2 freshly generated world, crimson mosquitos feel pretty cruel as with default config there spawns like 5 mosquitos in 10s after entering nether in crimson forrest. An ingame way to block their spawn would be great.

**Comment by NillerMedDild** [comment]
Will both decrease the spawn weight (if possible) and add to Torchmaster configs, thanks for the feedback :D
