### ISSUE TITLE
[Mod Suggestion] Forbidden and Arcanus

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#63]
A new kind of **Magic-themed Mod** 
https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus/files/3000579

**Comment by NillerMedDild** [comment]
Do you know if their wiki is up to date?
https://github.com/stal111/Forbidden-Arcanus/wiki

**Comment by TGMax233Michael** [comment]
Don't seem to know 🤦‍♂️

**Comment by NillerMedDild** [comment]
Have you played with the mod?

**Comment by TGMax233Michael** [comment]
I have played most of them, (the magic part is not done yet?) mainly for adventure and upgrading equipment

**Comment by TGMax233Michael** [comment]
Actually I feel that this mod is more adventurous

**Comment by NillerMedDild** [comment]
Very nice textures, but it looks like another sorta random mod with ores, tools and building blocks.

**Comment by Rithenar** [comment]
There are a couple of items from this mod that are very useful. The Stella Arcana can be combined with items like the Apotheosis charms to make them indestructible. Also, the Xpetrified Ore is a good mod to combine with Apotheosis as it allows another method to add xp gain

**Comment by Ridanisaurus** [comment]
There are already plenty of mods in E6 that facilitates most of these features.
This mod feels like Cyclic but magic based.
