### ISSUE TITLE
Emerald Honeycomb 

### ISSUE THREAD

**Issue by Octr** [NillerMedDild/Enigmatica6#630]
**Modpack version**
E6 0.3.2

**Issue**
The majority of honeycomb were balanced to have percentage rates in the centrifuge but emeralds are 1:1 (100% return) I think they might have been missed or bugged.

![image](https://user-images.githubusercontent.com/22117945/103098302-30f25980-4602-11eb-87c8-155565c5440b.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I think you're right :p
