### ISSUE TITLE
Extra Storage Disks/Parts have no crafting recipe 0.3.2

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica6#631]
**Modpack version**
0.3.2

**Issue**
Extra Storage Disks/Parts have no crafting recipe.
From looking at the 'future' changes, it appears that Extra Storage is intended to replace Extra Disks so it seems like currently the wrong set of recipes is disabled to facilitate this. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
This is intended, we won't be switching to Extra Storage disks/parts before Extra Disks is removed :)
