### ISSUE TITLE
Ore Processing Compat for The Undergarden

### ISSUE THREAD

**Issue by Dasavanth** [NillerMedDild/Enigmatica6#632]
would be lovely if undergarden ores could be processed via other mods like create, thermal or mekanism. right now they can only be smelted.

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by NillerMedDild** [comment]
I suggested it to JAOPCA here: https://github.com/TheLMiffy1111/JAOPCA/issues/183

**Comment by NillerMedDild** [comment]
Tags need to be present in Undergarden first: https://github.com/quek04/The-Undergarden/pull/53
