### ISSUE TITLE
[Mod suggestion] Refined pipes

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#635]
great standalone pipes mod which would pair pretty well with thermal and for general purpose piping
https://www.curseforge.com/minecraft/mc-mods/refined-pipes

**Comment by NillerMedDild** [comment]
We're waiting for Thermal Dynamics for additional pipes :)

**Comment by KrAzYGEEK32** [comment]
![Capture](https://user-images.githubusercontent.com/59537798/103141195-0b0aa900-4717-11eb-809a-00545a104173.PNG)
this is from the COFH discord, seems like it will be a while until it ports. could you please add this mod until then?

**Comment by NillerMedDild** [comment]
I'd really rather not. We already have options :) I suggest either XNet or Mekanism pipes.

**Comment by KrAzYGEEK32** [comment]
![Capture](https://user-images.githubusercontent.com/59537798/103141249-f24ec300-4717-11eb-9524-5e5f9f36e6ef.PNG)
this was a small discussion in the suggestions channel of the enigmatica discord, could this maybe have a small chance of changing your mind? :P

**Comment by NillerMedDild** [comment]
Not really, no - Kudos for trying though :P

**Comment by KrAzYGEEK32** [comment]
oh well, thanks for taking the time to reply ❤️
