### ISSUE TITLE
0.3.2 - BYG buttons are not tagged with minecraft:wooden_buttons

### ISSUE THREAD

**Issue by Thiana** [NillerMedDild/Enigmatica6#636]
**Modpack version**
E6 v0.3.2

**Issue**
BYG wood buttons are not tagged as minecraft:wooden_buttons so they can't be used in create/etc recipes.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Fixed in the modpack and PR submitted to fix it in BYG :)
