### ISSUE TITLE
Suggestion: Easy Villagers

### ISSUE THREAD

**Issue by Thiana** [NillerMedDild/Enigmatica6#640]
Since we have Botany Pots and Caged Mobs it might be nice to include [Easy Villagers](https://www.curseforge.com/minecraft/mc-mods/easy-villagers) to allow a similar lag reduction for Villager Halls. I would suggest either disabling (or increasing the processing time via the config) the Farmer and Iron Farm blocks.

Thanks :)

**Comment by NillerMedDild** [comment]
I think that's a bit too cheesy tbh, Caged Mobs was right on the edge.
