### ISSUE TITLE
Botania Fertilizer can only be made with Cyan Dye

### ISSUE THREAD

**Issue by Landozo** [NillerMedDild/Enigmatica6#641]
Enigmatica6-0.3.2

I noticed that e6 0.3.2, Botania fertilizer can only be made with cyan dye, even though in vanilla Botania and in e2e, it could be made with any dye combo, and the Lexica Botania in e6 says as such.

It seems to be caused by the script changes in the kubejs\server_scripts\enigmatica\kubejs\base\recipes\replace_input.js file. When I remove it, I can then craft with any combination of dyes like in base botania and old enigmatica.

With replace_input.js:
![image](https://user-images.githubusercontent.com/76003066/103143585-28c01a00-46e7-11eb-81f1-14202b466392.png)

Without replace_input.js:
![image](https://user-images.githubusercontent.com/76003066/103143583-0fb76900-46e7-11eb-8466-84b808094c1e.png)

Is this intended behavior in the pack? And if so, the Lexica Botania in e6 still refers to the vanilla Botania behavior and might need to be changed:

![image](https://user-images.githubusercontent.com/76003066/103143588-53aa6e00-46e7-11eb-8f86-2536e7d98032.png)

Thanks!

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
