### ISSUE TITLE
Skeleton Horse spawning on seafloor crashed server

### ISSUE THREAD

**Issue by seansackowitz** [NillerMedDild/Enigmatica6#643]
**Modpack version**
0.3.2

**Issue**
I was swimming around in the ocean, and a skeleton horse spawned on the seafloor, and the server locked up and hard crashed.

**Logs**
https://pastebin.com/QuYp4CVZ

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm not really sure what to do here to be honest, I don't know which mod could be causing it.

**Comment by Darkere** [comment]
This is a known vanilla issue when something modifies the goals of the skeleton horse. 

Enabling remove erroring entities in the forge server config might work. Otherwise removing the horse in some other way is the solution.

**Comment by leemmcc** [comment]
FWIW, found some similar reports, one in [DW20's 1.16 pack](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/40) and a link there back to a [Forge pull req that may fix it](https://github.com/MinecraftForge/MinecraftForge/pull/7509).  I don't know enough to understand what "It's easy to fix with a Mixin for now" means but maybe it's something that would help here too?

**Comment by Sanguinely** [comment]
https://pastebin.com/g1Ese4dg same error

**Comment by Darkere** [comment]
Temporarily changing to peaceful will remove the horse.
