### ISSUE TITLE
Crash with Lost Trinkets Mirror Shard Trinket and Guardians

### ISSUE THREAD

**Issue by Boodlyneck** [NillerMedDild/Enigmatica6#644]
**Modpack version**
0.3.2

**Issue**
A player with this trinket equipped crashed our server while in an Ocean Monument.
The crash log points to this trinket.

**Logs**
[crash-2020-12-26_11.44.03-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/5743398/crash-2020-12-26_11.44.03-server.txt)

**Comment by NillerMedDild** [comment]
Thanks for the bug report! The bug has been reported to the mod developer, but we will be disabling while we wait for a permanent solution.
