### ISSUE TITLE
Sophisticated Backpacks duplication bug

### ISSUE THREAD

**Issue by Kleinszar** [NillerMedDild/Enigmatica6#645]
**Modpack version**
0.3.2+ Develop branch, up to commit b30bda93856c4ba255a58ead08109600fb7ab9ed

**Issue**
Dupe Bug
To reproduce:
1. Open Backpack with hotkey.
2. Swap unstackable? item with same item in held slot. (Backpack closes automatically)
3. Reopen backpack and repeat.

https://user-images.githubusercontent.com/21229718/103157910-0ffa4780-476d-11eb-9812-5ea01f903628.mp4

**Comment by NillerMedDild** [comment]
This was patched by the mod developer, but thank you for the report!
