### ISSUE TITLE
[Mod Suggestion] Flux Networks

### ISSUE THREAD

**Issue by AbedMir31** [NillerMedDild/Enigmatica6#646]
Flux Networks Mod

**Comment by NillerMedDild** [comment]
We have other means of doing very similar things, so it's a no :)

**Comment by hvdklauw** [comment]
One argument I have is that the other options (RFtools multiblock cell, Powah Ender gate) lack the monitoring on power generation/consumption that flux would bring.

These points from their page is what I'm missing:
- Name each connection for easier identification. 
- Graphs to monitor recent energy spikes/drops 

Now I have some generation setups (windmills, heat gens, even Blazing generator, Mek reactor) and therse is no way to keep an eye on if you have enough or not.

**Comment by NillerMedDild** [comment]
Good points, I will have a look.
