### ISSUE TITLE
Unable to craft Industrial Foregoing Ore Laser Drill

### ISSUE THREAD

**Issue by KangyKSLG** [NillerMedDild/Enigmatica6#648]
**Modpack version**
0.3.2

**Issue**
Can't craft Industrial Foregoing Ore Laser Drill due to Emendatus Engimatica replacing vanilla Silk Touched ores with ore chunks

**Logs**
Input pastebin link to crash-report or latest log, if applicable

![image](https://user-images.githubusercontent.com/42292756/103162738-07952180-47ec-11eb-8e05-a97548b5e8ff.png)
![image](https://user-images.githubusercontent.com/42292756/103162743-12e84d00-47ec-11eb-89b8-7e921a0a5b90.png)

**Comment by Shindur** [comment]
Place the ore chunks into a stonecutter and make the vanilla iron ore. That's the how you obtain the vanilla style ores.

**Comment by KangyKSLG** [comment]
> Place the ore chunks into a stonecutter and make the vanilla iron ore. That's the how you obtain the vanilla style ores.

Didn't know that, thanks very much!

**Comment by RevenantWendigo** [comment]
Also with the mining laser I keep getting these: https://i.imgur.com/LBzohvM.png

Another thing with the laser drill is that I get lapis chunks instead of just regular lapis. Is that intended? I know the digital miner just gives straight lapis instead of chunks.

**Comment by KangyKSLG** [comment]
> Also with the mining laser I keep getting these: https://i.imgur.com/LBzohvM.png
> 
> Another thing with the laser drill is that I get lapis chunks instead of just regular lapis. Is that intended? I know the digital miner just gives straight lapis instead of chunks.

I believe the lapis chunks are intended as the laser drill "spawns" ore as if it's been silk touched. If you use a silk touch tool on lapis or your get a chunk

**Comment by NillerMedDild** [comment]
Submitted pull request to Industrial Foregoing that fixes this issue: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/pull/923

**Comment by KangyKSLG** [comment]
> Submitted pull request to Industrial Foregoing that fixes this issue: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/pull/923

Has anyone ever told you you're an awesome developer?

**Comment by NillerMedDild** [comment]
Thank you 😄 

Also thanks @RevenantWendigo, fixed that empty tag issue you mentioned. Lapis Chunks are indeed intended as Kangy points out.
