### ISSUE TITLE
[Suggestion] Occultism - Magic Mod about Summoning (Utility) Spirits 

### ISSUE THREAD

**Issue by klikli-dev** [NillerMedDild/Enigmatica6#652]
**Modpack version**
E6 0.3.*

**Suggestion**
_Disclaimer: I am the creator of Occultism. Occultism is already part of E5, so you may be familiar._ 

Occultism is a mod about _indirectly_ using magic by summoning spirits.  The spirits fulfill functions of basic machines such as ore crushing, provide infrastructure (transporting items), classical magic functionality (influencing weather and time of day), as well as automation and a simple magical AE2 alternative. A feature overview can be found in the [feature diagram](https://klikli.app.link/occultism-features).

The 1.16 upgrade comes with some small features, and finally includes @Ridanisaurus fantastic textures (instead of the abysmal high-res programmer's art from before :) )

Link: https://www.curseforge.com/minecraft/mc-mods/occultism
GitHub: https://github.com/klikli-dev/occultism
Some impressions: https://www.curseforge.com/minecraft/mc-mods/occultism/screenshots

**Comment by NillerMedDild** [comment]
We'll be adding Occultism soon, thanks for the "suggestion" :)

I actually thought it was still in alpha on 1.16, that's why it hasn't been added yet.
