### ISSUE TITLE
Dupe Bug with 2x2 Crafting

### ISSUE THREAD

**Issue by Hamsypotter** [NillerMedDild/Enigmatica6#653]
**Modpack version**
e6 0.3.2

**Issue**
slot-crafting in an open hotbar slot and then shift-crafting results in many more items than you should get
for example: pressing 3 to put torches in your 3rd slot and then shift crafting to make a stack of them

can post a video if needed but its super easy to replicate

steps for replicating (using torches for example)
1. empty inventory is ideal but should work with any amount of inventory
2. torch recipe with more than 1 set of materials (edit: doesnt work well with smaller numbers, >8-10 seems to work best)
3. press 5 to craft one set into the 5th slot, then quickly shift-click to craft the rest
4. should have more torches than you would by just shift-clicking normally

in my testing it worked in both singleplayer superflat and on a server (bisect-7gb), tps doesnt appear to be a factor
**Logs**
not a crash

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Jesus christ, that is one efficient dupe bug.

**Comment by NillerMedDild** [comment]
I'm not sure which mod is causing this :/
 I suspected Crafting Tweaks, but I was not able to reproduce the issue with only Crafting Tweaks.

**Comment by leemmcc** [comment]
I did some brute force narrowing down to help out - I am able to reproduce it repeatedly with nothing other than FastWorkbench-1.16.3-4.4.1 and Placebo-1.16.3-4.3.3 (Required Dep of FWB). I didn't try any other versions of those mods other than what comes with the E6 install from GDLauncher. 

Also, you don't have to be fast. All it seems to take is the first craft using a keybind to your hotbar, you can then wait 5-10 seconds if you want, and then shift-click to dupe the rest. Seems very easy to reproduce now.

**Comment by leemmcc** [comment]
I opened https://github.com/Shadows-of-Fire/FastWorkbench/issues/62 for you guys.

**Comment by NillerMedDild** [comment]
Thank you, much appreciated!!
