### ISSUE TITLE
IE Arc furnace Recycling recipe wrong 

### ISSUE THREAD

**Issue by Eivun159** [NillerMedDild/Enigmatica6#654]
**Modpack version**
0.3.2

**Issue**
Immersive Engineering's Arc furnace Recycling recipe is wrong.
Iron armors or tools smelt to tin
![2020-12-27_23 50 06](https://user-images.githubusercontent.com/76654914/103173444-54393500-489e-11eb-82b5-729fd58eef4b.png)
gold armors or tools smelt to copper
![2020-12-27_23 41 33](https://user-images.githubusercontent.com/76654914/103173395-189e6b00-489e-11eb-8379-25351d2a7289.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report, we know :/ we've even tried to disable recycling completely, with no luck. Will try again :)

**Comment by NillerMedDild** [comment]
Reported the issue here: https://github.com/BluSunrize/ImmersiveEngineering/issues/4534
