### ISSUE TITLE
Lost cities dimension

### ISSUE THREAD

**Issue by CletusMAngo** [NillerMedDild/Enigmatica6#656]
It was in Enigmatica 2 so id think it would fit here :)
https://www.curseforge.com/minecraft/mc-mods/the-lost-cities

**Comment by Darkere** [comment]
The dimension part of lost cities is not yet in the mod.

**Comment by CletusMAngo** [comment]
Awww didnt know that lol

**Comment by NillerMedDild** [comment]
This will most likely be a no even when the dimension begins to work, it doesn't really fit in imo.
