### ISSUE TITLE
Cat Jammies

### ISSUE THREAD

**Issue by Buuz135** [NillerMedDild/Enigmatica6#657]
https://www.curseforge.com/minecraft/mc-mods/cat-jammies

They just like to jam

![](https://i.imgur.com/j82ghe3.gif)

**Comment by NillerMedDild** [comment]
Did Rid commission this?

**Comment by Ridanisaurus** [comment]
Rid approved this suggestion 👍🏻

**Comment by Buuz135** [comment]
I wasn't forced to do this, I made this on my free will

**Comment by MaxFirestorm** [comment]
Buuz, blink twice if you need help.

**Comment by Merlo17** [comment]
I think these two are working together you guys
