### ISSUE TITLE
FTBChunks Crashing with fake player (drones)

### ISSUE THREAD

**Issue by ManiacRobert1** [NillerMedDild/Enigmatica6#660]
If the drones dig / do something in ftbchunks claim, the server will crash.

Darkere reported here https://github.com/FTBTeam/FTB-Chunks/issues/75 and redirect to https://github.com/FTBTeam/FTB-Chunks/issues/57

Buuut, the issue was "fixed" there https://www.curseforge.com/minecraft/mc-mods/ftb-chunks/files/3134599, the crash still exist.

I tested the bug in single-player world, claimed chunk, but it's not crashing, the crash is happening only on e6 server.

![image](https://user-images.githubusercontent.com/39351347/103181262-0d503d00-48a8-11eb-9421-301327309d19.png)

**Comment by NillerMedDild** [comment]
Was this with E6 v0.3.2?

**Comment by FutureLegion** [comment]
I mean... i can test it..

**Comment by FutureLegion** [comment]
Yes, still crashing.

**Comment by NillerMedDild** [comment]
Thanks :P

**Comment by ManiacRobert1** [comment]
Maybe a fix in next release? can be tested on temp server ? https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/112/

**Comment by telemenar** [comment]
I filed the PNC issue -- if you want an issue on their side to track: https://github.com/TeamPneumatic/pnc-repressurized/issues/706

**Comment by ManiacRobert1** [comment]
Pneumatic was updated to new version.
