### ISSUE TITLE
Titel Screen menu buttons duplicated

### ISSUE THREAD

**Issue by 1Yunis1** [NillerMedDild/Enigmatica6#661]
**Version**
0.3.2

**Issue**
The buttons in the main menu are duplicted

[`Image here`](https://cdn.discordapp.com/attachments/732733890917302355/792916716271304714/EM6Menu.png)

**Comment by NillerMedDild** [comment]
Why did you close this issue? :)

**Comment by 1Yunis1** [comment]
It resolved itself, it appeard after I downloaded the pack, but after I loaded it again, it was gone
