### ISSUE TITLE
Pneumatic helmet hacking/night vision not working?

### ISSUE THREAD

**Issue by IcarusWhite** [NillerMedDild/Enigmatica6#664]
**Modpack version**
0.3.2

**Issue**
Expected: after installing night vision and hacking upgrades into helmet, and activating them from the armor settings, I should be able to see in the dark and hack things (e.g. doors, spawners, etc.)

Result: armor reports night vision is on, but no visual change; block tracker highlights hackable blocks, but using the keybind on a block does nothing, even after rebinding "hack" to a non-conflicting key.

**Logs**
N/A

**Comment by IcarusWhite** [comment]
Sorry, I restarted the game and it's working now...? I apologize for being frustrating.

**Comment by NillerMedDild** [comment]
No worries, it must've been a client desync :)
