### ISSUE TITLE
Laser Drill is not generating ore properly

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#666]
**Modpack version**
inDev

**Issue**
Ran it for a few minutes, and despite being in the overworld, all I was getting was end dimensional shard ore. 

took out our kubejs scripts and started getting no ore at all.

Cannot replicate in a world with only IF, JEI, and Mek, so it seems like something on our side. 

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5748290/latest.log)

**Comment by NillerMedDild** [comment]
I'll investigate :)

**Comment by NillerMedDild** [comment]
Hm, I can't reproduce that, which Y level, and biome were you in?

**Comment by MuteTiefling** [comment]
Oh, duh. Biome.

I was in a void superflat.

**Comment by NillerMedDild** [comment]
Phew :D
