### ISSUE TITLE
[Mod Suggestion] Charging Gadgets

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#67]
By the man himself!
seems pretty cool as a charging option, without delving deep into other tech mods
https://www.curseforge.com/minecraft/mc-mods/charging-gadgets

**Comment by NillerMedDild** [comment]
I don't know, I'd rather people just use the IE or Mekanism alternatives.

**Comment by KrAzYGEEK32** [comment]
well, as i said above the both alternatives require progressing through either of the mods, which will be a tedium for people unfamiliar with those. that said, i do like your preferences as evidenced by E2 and E2E being my favorite packs, so its up to you i guess, ill keep the issue open a little longer just in case you have a change of mind ^^.

**Comment by Darkere** [comment]
Meh. I hope dire has plans for this one. Is this not a downgrade of a simple furnator?

**Comment by KrAzYGEEK32** [comment]
i feel powah stuff is just annoying to craft, it depends on the recipe of the charger i guess, if its a downgrade or not.

**Comment by NillerMedDild** [comment]
We can revisit this if new stuff is added to the mod :)
