### ISSUE TITLE
[Bug] Icy Bee Breeding

### ISSUE THREAD

**Issue by Octr** [NillerMedDild/Enigmatica6#670]
**Modpack version**
E6: 0.3.2

**Issue**
The Icy Bee uses snowballs to breed (x16) but trying to use them with shift or without will throw the snowball at the bee causing it to aggro and sting the player.

**Suggestion**
Change the breeding item from snowballs to snowblocks instead.

Video Here:
https://discord.com/channels/195234321836146688/544589452492931076/793268323612622848

**Comment by NillerMedDild** [comment]
Oh sorry about that, must've felt like we were trolling you :P will be fixed in 0.3.3
