### ISSUE TITLE
[Bug] Resonant Wand from Astral is not Obtainable

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#671]
**Modpack version**
E6 0.3.2

**Issue**
When using Astral Sorcery marble, the Resonant Wand is not craftable. It only crafts when using Quark Marble.

**Screenshots**
![image](https://user-images.githubusercontent.com/64355028/103250532-95037d80-4974-11eb-9d94-c86c2c7b27e9.png)
![image](https://user-images.githubusercontent.com/64355028/103250546-aa78a780-4974-11eb-84d1-453281a7b7e3.png)

**Comment by NillerMedDild** [comment]
Fixed in-dev :) #634

**Comment by Ridanisaurus** [comment]
Whoops, sorry.
