### ISSUE TITLE
Astral Sorcery Crash

### ISSUE THREAD

**Issue by Ninjayatsu** [NillerMedDild/Enigmatica6#672]
**Modpack version**
e6 0.3.2 Server

**Issue**
The server crashed after I connected a Crystel lens from Astral Sorcery to a Collecter Crystal(type is unknown, and is also from Astral Sorcery) with the Linking Tool. Then when I try to start the server up again I get the error listed below, which if you read enlists Astral Sorcery being wonky.
**Logs**
Edit: I put your log in a gist
https://gist.github.com/NillerMedDild/7f542ba95b7e5e92825cc3982fa0ec8e

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
This issue appears to have been fixed by an Astral Sorcery update, I cannot reproduce it in singleplayer or on a server.

**Comment by Ninjayatsu** [comment]
ok thanks
