### ISSUE TITLE
Steel Rod Recipe Conflict Present - 0.3.2

### ISSUE THREAD

**Issue by MetalFrog** [NillerMedDild/Enigmatica6#675]
**Modpack version**
0.3.2

**Issue**
Steel recipes are still conflicting with Immersive Engineering. The recipe in JEI says to use any steel ingots or steel rods, but instead of the IE steel fence being created, I get the mapperbase version, which is incompatible with the multi-block structures in IE. (For reference I am building a squeezer, and it will not convert when hitting the correct block with the engineer's hammer). 

Hitting "U" over the mapperbase steel fence I get takes me to an information dialog saying the item has been disabled, which lead me to this issues page.

**Video Attached**

https://user-images.githubusercontent.com/689815/103263900-1cea8700-4977-11eb-8b8f-354d05ef0408.mp4

**Comment by NillerMedDild** [comment]
This makes me very sad :P I'll try to reproduce. Thanks for the report.

**Comment by NillerMedDild** [comment]
I cannot reproduce this, so my guess is I fixed it after 0.3.2 and forgot? Either way, apologies for the trouble, hope it's properly fixed for you in 0.3.3
