### ISSUE TITLE
[Mod Suggestions] Integrated Dynamics, Tunnels, Crafting, Terminals

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#678]
Seems like the Integrated suite got updated to 1.16, we all ID nerds would appreciate it, if they get added :P.
https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics
https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels
https://www.curseforge.com/minecraft/mc-mods/integrated-crafting
https://www.curseforge.com/minecraft/mc-mods/integrated-terminals

**Comment by NillerMedDild** [comment]
I'm not sure yet, will consider it :)

**Comment by Merlo17** [comment]
https://www.curseforge.com/minecraft/mc-mods/integrated-nbt

just in case, this one is a nice addition as well

**Comment by NillerMedDild** [comment]
The Integrated mods are nice, but I'm not sure enough players use them to warrant adding *5* mods. Every mod added makes the modpack just a little harder to run, so we need to be a bit conservative in regards to what we add.

**Comment by TemperedFool** [comment]
Dynamics, NBT, and tunnels seem like shoe-ins for an expert pack; someone else can tell me if any of them make sense in kitchen sink ^_^

**Comment by KrAzYGEEK32** [comment]
so... this is my case: integrated dynamics is, on its own, one of the most powerful logic mods in MC. integrated tunnels utilizes this power for more practical purposes like transfering and interactions. integrated terminals adds just 2 items (and nothing else)to the suite but creates a whole new dimension with regards to network management. integrated crafting adds 2 items (and nothing else) as well, and just completes the whole Integrated package by providing autocrafting to the network. personally i'd be happy to see atleast ID in the pack, but all of them together just make a wholesome package. and they are just sooo gooood together!! please consider them all :P

**Comment by NillerMedDild** [comment]
What about Crafting? I've never used that before.

**Comment by Merlo17** [comment]
I would argue ID and company are now pretty mainstream, everybody seems to know them and want them. While it's true that not many would use them to their full extent, I think having them will enable weird setups and open up cool possibilites for automations that would otherwise be tricky, and that's always welcome in my book.
Personally I would add them. They're popular and requested mods anyways, and they add logic and features we have no way of doing in the pack yet (besides maybe CC, but I'd argue even less players would use it properly).
It might be a bit of a niche, but I'd say it's large enough to be filled, especially in a pack like ours that, even in its kitchen sink version, is still very much dedicated to automation. It fits the pack perfectly and I don't really see a good reason to leave it out, especially because many players on discord already asked for it :D

**Comment by NillerMedDild** [comment]
Alright. Valid points, I'll have a look asap.

**Comment by KrAzYGEEK32** [comment]
> What about Crafting? I've never used that before.

Integrated crafting basically adds AE like interface for autocrafting purposes(it just takes recipes and provides autocraft requesting for the network, doesn't do other jobs the AE interface does). the crafting writer is the second item which is basically used to auto request recipes for stock keeping in the network.

**Comment by NillerMedDild** [comment]
ID and all addons except Integrated REST will most likely be added, but we're currently waiting to see if this suggestion is accepted: https://github.com/CyclopsMC/IntegratedDynamics/issues/976

**Comment by TGMax233Michael** [comment]
https://github.com/CyclopsMC/IntegratedDynamics/issues/976
Maybe it was added in these ver.?
https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics/files/3179476

**Comment by TGMax233Michael** [comment]
Will these mods be added in 0.3.10(or 0.4.0) soon?

**Comment by NillerMedDild** [comment]
Most likely in version 0.3.11, in a week or two.

**Comment by Quick27Draw** [comment]
Are these mods still scheduled to be added?

**Comment by NillerMedDild** [comment]
They are yes, I just want to stabilize first - Expect them in 0.4.0 :)

**Comment by Merlo17** [comment]
@NillerMedDild missing integrated NBT, small addition but big difference :P

**Comment by NillerMedDild** [comment]
I know, it's not marked as 1.16.5 compatible :(

**Comment by sciguyryan** [comment]
> 
> 
> I know, it's not marked as 1.16.5 compatible :(

It seems to be working fine in my test instance, if that helps at all.

**Comment by NillerMedDild** [comment]
It doesn't I'm afraid, but thanks!

**Comment by Merlo17** [comment]
https://www.curseforge.com/minecraft/mc-mods/integrated-nbt/files/3192227

looks like this release is flagged for .5, so we should be good ^^

**Comment by NillerMedDild** [comment]
I wonder how that happened :P
