### ISSUE TITLE
Mod Suggestion: Extra Bows

### ISSUE THREAD

**Issue by KangyKSLG** [NillerMedDild/Enigmatica6#679]
Hi,

Would you consider adding Extra Bows? Just to add a bit extra variety to bows that doesn't require getting knee deep into another mod to make

**Comment by CletusMAngo** [comment]
Tetra already has hundreds of different bow customizations tho

**Comment by KangyKSLG** [comment]
True but not everyone may want to do the tetra progression of leveling hammers, axes, cutting tools etc just to get a decent bow. Specially considering the RNG element of finding a forge hammer then finding the upgrade modules for said hammer to get higher level gear

That's why I said without getting knee deep into other mods.

However, I understand if it's not added because Tetra is in there :)

**Comment by NillerMedDild** [comment]
I'd rather not add this, because of, you guessed it, Tetra :P I'd rather make the Tetra bows more accessible.

**Comment by KangyKSLG** [comment]
> I'd rather not add this, because of, you guessed it, Tetra :P I'd rather make the Tetra bows more accessible.

Understandable haha. I have a suggestion for making things more accessible in that case.

How do you feel about adding recipes for the Tetra items that don't have recipes?

For example, a recipe for the Forged Hammer and accompanying upgrades, recipes for the various machines so you can make your own Tetra setup in a location of your choosing?

It would also mean adding in a way to make the seeping bedrock (I think it's called) obtainable as the  "charger" block extraction pipes extract energy from it. Maybe make it minable if possible.

Yes I know this changes the core features of the mod but I think it would be worth it

**Comment by NillerMedDild** [comment]
There is a recipe for the Forged Hammer, and Thermal Charges for powering it :P not the upgrades though.

**Comment by KangyKSLG** [comment]
> There is a recipe for the Forged Hammer, and Thermal Charges for powering it :P not the upgrades though.

Oh, I swear I checked that and it didn't show haha. 

Well ignore the bits that are already a thing :P

**Comment by NillerMedDild** [comment]
I added a recipe for the Combustion Chamber, the other upgrades will remain worldgen gated :)
