### ISSUE TITLE
Quest Loot showing "Loot Reward" item rather than assigned KubeJS loot table 

### ISSUE THREAD

**Issue by kil0byt3** [NillerMedDild/Enigmatica6#680]
**Modpack version**
Enigmatica 6 - 0.3.2

**Issue**
Loot tables for FTB Quests are acting a little strange. Any quest that's supposed to pull from a KubeJS loot table shows as "Loot Reward" red die item, rather than the specific loot table item. When clicked, they show a blank loot screen. 

Still new to 1.14+ modding, so I think those are the correct terms. Let me know if I should be looking elsewhere here.

This works normally/correctly on Singleplayer in our instance, but not in Multiplayer. This screenshot is what we see on the multiplayer server, running with Pterodactyl. I've attempted resetting the FTB Quests and KubeJS folders as well.

We've added a few mods, they're listed below. Not sure which, if any, would mess with the loot tables but if you see a potential culprit, please let me know and I can test as needed. 

![image](https://user-images.githubusercontent.com/39413400/103301510-6c03dc80-49b6-11eb-8795-754c376a168b.png)

- FreeLook-1.16.4-1.3.2.jar
- totaldarkness-1.2-1.16.3.jar
- cookiecore-1.16.2-3.0.0-4d69840.jar
- eidolon-0.2.3.jar
- Paraglider-1.16.2-1.3.1.0.jar
- polymorph-forge-1.16.4-0.21.jar
- neoncraft-2.1.jar
- extlights-3.3.jar
- supplementaries-0.9.15-1.jar
- configurablebeacons-1.16.2-2.0.1.jar
- magicfeather-1.16.2-3.1.0.jar
- camera-1.16.4-1.0.5.jar
- SoundFilters-0.14_for_1.16.2.jar
- Ping-1.16.4-1.6.8.jar
- DynamicSurroundings-1.16.4-4.0.1.3.jar
- upstream-1.0.jar
- cc-tweaked-1.16.4-1.95.0.jar
- OptiFine_1.16.4_HD_U_G5.jar
- economyinc-1.6.9.4.jar

**Logs**
My latest.log is both too long and doesn't have relevant info; I don't think FTBQuest actions are posted to the log. Here's the relevant part from me joining the server, claiming the above quest, then disconnecting. 
https://pastebin.com/PaAPCcjx

**Comment by MuteTiefling** [comment]
This is a known issue, and already fixed in the next version.

As a result of the fix, you and your players will not only get all the loot you missed, but will be able to reclaim all of the loot boxes. Merry Christmas!

**Comment by kil0byt3** [comment]
What a gift ;) Thanks guys! I'll see if I can contribute at some point here with some PRs, been wanting to learn 1.16 anyway. Have a good one!
