### ISSUE TITLE
[Suggestion] Paraglider

### ISSUE THREAD

**Issue by kil0byt3** [NillerMedDild/Enigmatica6#681]
Just thought I'd show you it if you hadn't already seen it - it's a modern OpenGlider mod, like the one that was used in E2...sort of? But it also has options for stamina use (like in Breath of the Wild) as well as stamina upgrades that you could make craftable or lootable. 

Just thought it made a good early-game travel option with some nice limitations if wanted. Of course, stamina system can be disabled as well.

The heart containers don't work, from my testing. 

https://www.curseforge.com/minecraft/mc-mods/paragliders

**Comment by NillerMedDild** [comment]
I'll have a look, thanks for the suggestion :)
