### ISSUE TITLE
[Bug] Blood Magic Crash with Mek

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica6#682]
**Modpack version**
0.3.2

**Issue**
Game crashes in Single and Server when extracting blood from Blood Alter with Mekanism basic mechanical pipe (fluid). It will continue to crash every restart.

Steps to replicate:
1. Place a Blood Alter
2. Sacrifice some blood into the alter
3. place a single basic mechanical pipe to the side of the alter
4. use the configurator to change it to pull
5. as soon as blood enters the pipe, Crash!

**Logs**
https://pastebin.com/QNZQh4cg

**Comment by NillerMedDild** [comment]
Thanks for the report! Do you have a full crash report? :)

**Comment by NillerMedDild** [comment]
Ah no need, found the issue reported here: https://github.com/WayofTime/BloodMagic/issues/1729

**Comment by Trostmm** [comment]
That's interesting.. because I am doing exactly this using a Mek pipe to a Quantum Tank.. hmm.

**Comment by Dracos99** [comment]
It works fine if the pipe has something to pump into, like a tank, before changing the pipe to pull...but if you change the pipe to pull before there is a place for it to go, it crashes trying to just fill up the pipe.  Also, if you disconnect/pickup the tank, leaving just the pipe connected to the alter, and it is still pumping, it will also crash.

**Comment by Dracos99** [comment]
> That's interesting.. because I am doing exactly this using a Mek pipe to a Quantum Tank.. hmm.

It works fine if the pipe has something to pump into, like a tank, before changing the pipe to pull...but if you change the pipe to pull before there is a place for it to go, it crashes trying to just fill up the pipe. Also, if you disconnect/pickup the tank, leaving just the pipe connected to the alter, and it is still pumping, it will also crash.
