### ISSUE TITLE
Zinc is now useful, but is not generated by the ore laser and can't be used in dust form for alloys.

### ISSUE THREAD

**Issue by Grath** [NillerMedDild/Enigmatica6#684]
**Modpack version**
0.3.2

**Issue**
Zinc is now useful for Create, but is the only chunk from Emendatus Enigmatica which isn't generated by the Industrial Foregoing ore laser. Also, the use for Zinc (to make Brass for Create) is only achievable via alloy smelting processes rather than via dust mixing unlike other alloys.

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get both of those things fixed.

**Comment by RevenantWendigo** [comment]
I also noticed that Apatite is not generated by the ore laser.
