### ISSUE TITLE
[Suggestion]: Waddles

### ISSUE THREAD

**Issue by Ninjayatsu** [NillerMedDild/Enigmatica6#686]
Super simple, adds as the mod title suggests, penguins which spawn in Snow Tundra, and Ice spikes, but also any modded biome that is snowy. Super smol and super cute add it 🔫 🐧 

https://www.curseforge.com/minecraft/mc-mods/waddles

**Comment by NillerMedDild** [comment]
No thank you, I don't see much point other than they're cute :P

**Comment by Ninjayatsu** [comment]
😔
