### ISSUE TITLE
Arc Furnace Recipe Issue

### ISSUE THREAD

**Issue by KangyKSLG** [NillerMedDild/Enigmatica6#688]
**Modpack version**
0.3.2

**Issue**
Arc Furnace only wants Immersive Engineering Block of Steel. Emandatus Enigmatica Blocks of steel don't work

I know it can be changed with the stone cutter but thought it work reporting anyway

**Comment by NillerMedDild** [comment]
Thanks for the report, we will not be changing that :)

**Comment by Darkere** [comment]
A solution would be to make IE multiblocks accept all steelblock types via tag.

**Comment by NillerMedDild** [comment]
I don't think they accept block tags, looks like registry ids only.

**Comment by Darkere** [comment]
Well yeah we would need to bother the IE devs for this :)

**Comment by Darkere** [comment]
@KangyKSLG Seems to be working just fine for me. Did you use the projector to build it?

**Comment by KangyKSLG** [comment]
Strange, yeah I did. I'm on now, I'll give it another shot

**Comment by Darkere** [comment]
The projector shows them as incompatible. Which is something we should report :)
