### ISSUE TITLE
Astral Mineralis Ore Gen

### ISSUE THREAD

**Issue by Surnyy** [NillerMedDild/Enigmatica6#689]
**Modpack version**
0.3.2

**Issue**
From my (albeit somewhat limited) testing it seemed like the Mineralis Ritual only generates Vanilla ores. Either that or it's drowned out by the fact that it generates any variation of Ore (Marble, Scoria, Stone, etc..), not just normal Stone, like Nature's Aura. Dunno if it's just not configured yet or there is no option to cause the mod's still on beta in 1.16 or whatever but I thought I ought to mention it.

**Comment by NillerMedDild** [comment]
We have not yet configured it, but we will, thanks for reminding us :D
