### ISSUE TITLE
[Suggestion] Dungeon Crawl

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica6#690]
Having Dungeon Crawl in this mod pack could add some needed difficulty and challenge to underground areas that the current towers and red spawners dont. It is a a spiritual successor to Roguelike Dungeons. These dungeons can spawn as massive sprawling labyrinths with cool rooms, some traps, and spawners that spit out more difficulty armed and armored mobs.
The mod also includes a bunch of customizable features for loot/treasures as well as the ability to change or create themes that could add blocks from other mods in the pack 

https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl

As the site notes, you would also likely need https://www.curseforge.com/minecraft/mc-mods/spawner-fix since Mojang doesnt plan to fix some mob spawners causing lag due to log writes (specifically enderme) until 1.17.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I'll think on it :)

**Comment by NillerMedDild** [comment]
I thought this seemed well made, it has improved since I last used it :D

I look forward to using the theming system.
