### ISSUE TITLE
[Suggestion] Increase base range of range upgrades for the wireless transmitter (Refined Storage)

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#693]
**Modpack version**
0.3.2

**Issue**
The base range of 8 per range upgrade seems low. I feel like having a wireless transmitter maxed out with range upgrades should be 128 instead of 48. 48 just seems really low. My current predicament is that my friends and myself live on a giant mountain. In order to maintain decent coverage without super long cables spanning hundreds of blocks I have to set up lots of the wireless network transmitter / receivers. Ignoring the cost completely (which is quite expensive for early / mid-game players but trivial for end-game players) it is still quite time consuming and tedious setting all of these things up. 

Changing the base range of the upgrades to 28 would make the max range 128.

Additionally, if the addon eventually gets made that adds the infinite range upgrade like the AE2 one from 1.12 that would work as well. 

The config option can be found in refinedstorage-server.toml line 167.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Absolutely will implement this, though the exact range increase might differ :)
