### ISSUE TITLE
Enchant Duping with Enchantment Extraction Mechanics

### ISSUE THREAD

**Issue by SpaceWyvern** [NillerMedDild/Enigmatica6#697]
**Modpack version**
0.3.2

**Issue**
It is possible to enchant multiple pedestal upgrades with one book and taking all of those upgrades, and using enchantment extractor, stripping each upgrade to their books, meaning using one book to make many.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report. You still need to "pay" for every enchant, right?

**Comment by MuteTiefling** [comment]
If I understand right, it goes like this:
Get Pedestal enchant on book
Place stack up upgrades in anvil with book
Pay once to enchant all 64 upgrades.

Those upgrades can then have the enchants stripped through various means and re-applied. But the main issue is that the upgrades are stackable, and so can all be enchanted at once.

**Comment by NillerMedDild** [comment]
Slightly silly question. How on earth do I supply levels to the Pedestal with Exp Enchanter Upgrade?

**Comment by SpaceWyvern** [comment]
> Thanks for the report. You still need to "pay" for every enchant, right?

The amount is the same for one and, let's say, ten

**Comment by SpaceWyvern** [comment]
> If I understand right, it goes like this:
> Get Pedestal enchant on book
> Place stack up upgrades in anvil with book
> Pay once to enchant all 64 upgrades.
> 
> Those upgrades can then have the enchants stripped through various means and re-applied. But the main issue is that the upgrades are stackable, and so can all be enchanted at once.

Indeed

**Comment by SpaceWyvern** [comment]
> Slightly silly question. How on earth do I supply levels to the Pedestal with Exp Enchanter Upgrade?

I don't know. Never used that upgrade, only used the exp dropper, exp tank, and autokiller

**Comment by NillerMedDild** [comment]
Ahh now I get it, thanks for your patience :P

**Comment by SpaceWyvern** [comment]
> Ahh now I get it, thanks for your patience :P

Np

**Comment by NillerMedDild** [comment]
Hmm. This dupe doesn't require Pedestals at all, vanilla enchants and books can do it too.

**Comment by SpaceWyvern** [comment]
> Hmm. This dupe doesn't require Pedestals at all, vanilla enchants and books can do it too.

So as long as it is a stackable, enchantable item?

**Comment by NillerMedDild** [comment]
Yup ><

**Comment by Mowmaster** [comment]
Im going to assume this is an old bug, OR some mod is modifying the anvil behavior and ignoring the methods that would normally restrict this from happening.
As far as I can tell, From pedestals by itself, this isnt possible. (In current Pedestal versions)
![image](https://user-images.githubusercontent.com/10681506/116884645-9677d780-abec-11eb-8e44-692affe2385e.png)

**Comment by MuteTiefling** [comment]
Yeah, I can't reproduce in Dev either. Same as above, the anvil won't let me apply Speed to a stack of upgrades, only to individuals.
