### ISSUE TITLE
[Suggestion] Smithing table recipe to turn a terrasteel AIOT into an alfsteel AIOT

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#700]
**Modpack version**
0.3.2

**Issue**
The terrasteel AIOT can't be turned into an Alfsteel AIOT. The recipe could be: Terrasteel AIOT + Double Alfsteel Ingot in a smithing table.

**Logs**
N/A

**Comment by RevenantWendigo** [comment]
Actually just having the one double alfsteel ingot makes it quite a bit cheaper to make. Is there any way to make a bigger alfsteel ingot?  Like a quintuple alfsteel ingot or something? haha

**Comment by SpaceWyvern** [comment]
> Actually just having the one double alfsteel ingot makes it quite a bit cheaper to make. Is there any way to make a bigger alfsteel ingot? Like a quintuple alfsteel ingot or something? haha

I wholeheartedly agree with the idea of another level of alfsteel, because without it it would be too easy to make.

**Comment by NillerMedDild** [comment]
We'll look into it :)

**Comment by NillerMedDild** [comment]
There's no elegant way to implement this, in my opinion. You'll have to make due with the normal recipe :)

**Comment by AdamNisbett** [comment]
Came across this issue today in my own playthrough - would some method of splitting the Terrasteel AIOT back into its component tools be sufficiently doable?  Then each could be upgraded to alfsteel and recombined.
