### ISSUE TITLE
Possible worldgen issues

### ISSUE THREAD

**Issue by Octr** [NillerMedDild/Enigmatica6#701]
**Modpack version**
E6: 0.3.2

**Issue**
We started our server in 0.3.0 and did the upgrade to 0.3.1 and the forge "fix" for dimensions, after resetting both my end and nether dimensions additionally for the server.

What I immediately noticed is our nether biomes had changed, only till now did I realise, it was generating vanilla biomes.

We created our world using the biomesop generator settings (in 0.3.0) and we had modded nether biomes BEFORE 0.3.1

now when i create a singleplayer world in 0.3.2 using biomesop the overworld generates correctly with both BYG and BOP but the nether and I assume the end is using vanilla generation for biomes only.

using the Default setting generates byg (AND NO BIOMESOP) in overworld but generates BIOMESOP and BYG in the nether

I would prefer to use both byg and biomesop in all dimensions but this doesn't seem to be possible with the current profiles.

Our Server 0.3.0 fixed in 0.3.1 originally created with biomesop gen
![image](https://user-images.githubusercontent.com/22117945/103388678-56033280-4b02-11eb-9b82-7f38a339e65e.png)

Singleplayer with biomesop in 0.3.2
![image](https://user-images.githubusercontent.com/22117945/103388769-d6299800-4b02-11eb-8ee6-779c95d80169.png)

Singleplayer with default in 0.3.2
![NBTExplorer_VREwyW8JbN](https://user-images.githubusercontent.com/22117945/103388733-a7abbd00-4b02-11eb-83db-1087ff3d1109.png)

It seems like I will have to leave the overworld with biomesop gen settings as it generates both byg and biomes op and manually copy over the byg nether/end settings as a hotfix for our serverworld. (and then reset those dimensions)

using default gen settings I did search two different worlds with creative flight and rockcandy trinket for speed using both the natures compass and /locatebiome to try and get biomesop results and found only byg biomes (overworld)

The main issue is the nether and end generating vanilla biomes only when using biomesop gen settings
The secondary issue is the default gen settings not generating any biomesop biomes in the overworld.

**Comment by NillerMedDild** [comment]
Hi there!

We're aware that selecting Biomes O' Plenty world type results in issues, that's why it's not the default :)
To get both BYG and BoP, selecting default used to work, not sure what has changed, I will have a look in-game at that part.

We plan to remove BoP in a future major update, which will alleviate this issue... kind of :P

**Comment by Skar78** [comment]
I used quark_realistic and it worked out well so far (0.3.2).

Not a fan of byg - especially the nether.

**Comment by NillerMedDild** [comment]
So I'm seeing the same behaviour as you, the dimension thing is intended, either BoP has full control of End/Nether or none.

I'm unsure whether BoP removed their mods from the default worldtype on purpose or not, but I suspect it was on a purpose. 

There's not much we can do here, nor won't to do really, as we will be removing BoP in the future as mentioned above.
