### ISSUE TITLE
Cant Claim in Chunks the End

### ISSUE THREAD

**Issue by 1Yunis1** [NillerMedDild/Enigmatica6#704]
**Modpack version**
0.3.2

**Issue**
Claiming Chunks in the End isnt possible, every time I try claiming a chunk in the menu nothing happens.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Apparently it's a server config option and not a bug - You can change it yourself :)
