### ISSUE TITLE
Astral Sorcery Starlight Transmution of Iron Ore to Starmetal Ore broken

### ISSUE THREAD

**Issue by CuboidDroid** [NillerMedDild/Enigmatica6#706]
**Modpack version**
0.3.2

**Issue**
Astral Sorcery transmutation of Iron Ore -> Starmetal Ore not working. Possibly this is due to Astral Sorcery expecting vanilla Minecraft Iron Ore to be placed down, but converting Iron Chunks to Ore results in only the "Emendatus ..." version. Basically means you get stuck in progression with AS.

p.s. Really enjoying the pack

**Comment by Ridanisaurus** [comment]
You can obtain the Vanilla Iron Ore through the Stonecutter.

**Comment by MuteTiefling** [comment]
It does expect vanilla ore, yes. I've already expanded it to work with the basic emendatus ore too (not all the stone variations). Should make this a little less annoying next update.

**Comment by CuboidDroid** [comment]
Thanks to you both. I'm now unstuck, and glad to hear it'll be easier for others on future. Thanks again! I assume you'll close this off when next update is released, and in the meantime of anyone else faces the problem, they can use the same stonecutter workaround mentioned here.
