### ISSUE TITLE
Naturally spawned collection crystals from Astral Sorcery can be mined

### ISSUE THREAD

**Issue by SpaceWyvern** [NillerMedDild/Enigmatica6#707]
**Modpack version**
0.3.2

**Issue**
Naturally generated collection crystals from Astral Sorcery can be mined using (The only method tested) IF block breaker

**Comment by Darkere** [comment]
Have you tried using the crystal? Afaik it becomes unusable after it was moved.

**Comment by SpaceWyvern** [comment]
> Have you tried using the crystal? Afaik it becomes unusable after it was moved.

I haven't started with Astral yet so I don't know how to test them

**Comment by MuteTiefling** [comment]
The crystal does still function, yes. Just tested it in dev.

**Comment by MuteTiefling** [comment]
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/936

**Comment by MuteTiefling** [comment]
cannot reproduce with Modular Routers or the Engineer's Decor breaker.

**Comment by stefment** [comment]
can i get an invite to the testing discord? i just installed the test version and stone tools seem not to work. just wondering whats up

**Comment by NillerMedDild** [comment]
@stefment I'm guessing you wrote that in the wrong place?
