### ISSUE TITLE
PneumaticCraft Pressure Chamber leaks air on startup

### ISSUE THREAD

**Issue by kyleedwardsny** [NillerMedDild/Enigmatica6#708]
**Modpack version**
0.3.0

**Issue**
When you build the Pressure Chamber, it retains air and successfully compresses items. However, when you exit the world and reload, the chamber leaks air until it reduces to zero pressure. This can be fixed by breaking and rebuilding the chamber.

**Comment by NillerMedDild** [comment]
I recommend you update to 0.3.2 and see if that resolves the issue :)

**Comment by kyleedwardsny** [comment]
So, I was not able to reproduce this in a brand new creative superflat world in either 0.3.0 or 0.3.2 - it worked as expected both times. However, porting my 0.3.0 survival world to 0.3.2 still shows the issue. (I did use the Creative Compressor in the superflat test, I wonder if that had anything to do with it.)

**Comment by kyleedwardsny** [comment]
I tried a number of things to reproduce the issue in creative, including replacing the Creative Compressor with an Air Compressor, making sure the Pressure Chamber Valve was on the west side of the multiblock (it was in my survival world), reproducing the exact pipe configuration I had in survival, and even removing the Security Upgrade I had in survival to see if that would cause the issue to go away. And as I said before, upgrading from 0.3.0 to 0.3.2 changes nothing.

**Comment by MuteTiefling** [comment]
This is one of those recurring issues that Desht has had trouble reproducing to be able fix. I've had it happen in 1.15 and I saw a streamer have the same issue recently in 0.3.2 of e6. 


https://github.com/TeamPneumatic/pnc-repressurized/issues/544

**Comment by kyleedwardsny** [comment]
@MuteTiefling Thanks for the info. I just checked my survival world - my Pressure Chamber and its Air Compressor are actually smack dab in the middle of a chunk, so no chunk boundary issues here.

**Comment by MuteTiefling** [comment]
Yeah, there's obviously something more going on there than a simple chunk boundary issue.

It's very hard to reproduce as well. I've yet to come up with the magic formula for failure.

**Comment by kyleedwardsny** [comment]
I'm tempted to take a stab at debugging it myself, but that would involve hacking up Enigmatica with a debug version of PNC. Has anyone created a world with only vanilla + Forge + PNC? That would make debugging easy.

**Comment by NillerMedDild** [comment]
> I'm tempted to take a stab at debugging it myself, but that would involve hacking up Enigmatica with a debug version of PNC. Has anyone created a world with only vanilla + Forge + PNC? That would make debugging easy.

Can't you just make an instance with only PNC and JEI? :) And Forge of course.

**Comment by kyleedwardsny** [comment]
I've created a PNC/Forge-only instance and imported my world into it. It sure made quite a mess of the world (as expected)! Nevertheless, I am able to reproduce the issue in this world, and am going to start debugging it.

**Comment by desht** [comment]
I should just mention that the latest 2.9.0 beta of PNC should hopefully fix this.  I've added some code to the valve TE to make the server re-check the multiblock structure and reform it if there is a leaking valve. The check is only done once, so there shouldn't be any performance issues.
