### ISSUE TITLE
Issue with setting ram via settings.cfg / server-start.bat?

### ISSUE THREAD

**Issue by Axanthic** [NillerMedDild/Enigmatica6#709]
**Modpack version**
0.3.2 (With a ton of mods added on top)

**Issue**
Setting 'MAX_RAM=10G;' in settings.cfg doesn't seem to take effect?
This leads to low tps.

**Behavior**
Changing that setting doesn't appear to allow the server to use more ram. Stays at 4ish gb.

**My theories**
-Potentially unable to read the file thus using the defaults?
I didn't start server-start.bat as admin thus perhaps it was unable to read the settings.cfg file?

-Something wrong with the bat file itself?
It's kinda a complex mess written in batch so I can't tell.

-Potentially a mod I added? or a memeory leak or something?

**Comment by Darkere** [comment]
How did you determine whether your change to ram was applied?

**Comment by Axanthic** [comment]
> How did you determine whether your change to ram was applied?

Task manager

**Comment by NillerMedDild** [comment]
Used RAM and allocated RAM are two entirely different things :)
Using more RAM doesn't automatically improve TPS I'm afraid, one can assign a very large amount of RAM and still see TPS issues.
