### ISSUE TITLE
Feeding Upgrade Eaten Food Doesn't Count as Eaten for Spice of Life Carrot Edition

### ISSUE THREAD

**Issue by TopPercentageRattata** [NillerMedDild/Enigmatica6#710]
**Modpack version**
0.3.2

**Issue**
Not sure if it's Sophisticated Backpacks mod's fault or SoL:CE or both, but eaten foods via Feeding Upgrade don't count as eaten for the extra hp milestones from SoL:CE

**Comment by KrAzYGEEK32** [comment]
i've also noticed that gourmand enchant doesn't affect the food from the backpack

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by P3pp3rF1y** [comment]
That issue with Gourmand enchant should be fixed in the latest version as well as it relies on the same event that SoL does
