### ISSUE TITLE
silk touch dont working

### ISSUE THREAD

**Issue by baumwurzel73** [NillerMedDild/Enigmatica6#716]
**Modpack version**
Enigmatica 6  Minecraft 1.16 
latest update on curse 02.01.2021

**Issue**

Silk touch does not work Mining Gadget, which is very annoying because I need large amounts of resources for Mekanism. Please repair. I haven't tested it yet for enchantments.

edit: digital miner works with silk toutch, thanks

**Comment by NillerMedDild** [comment]
I believe the Mining Gadget has a Silk Touch upgrade, it doesn't just silk touch out-of-the-box.
