### ISSUE TITLE
Quest Rewards: Random Loot/Loot Reward not giving an item

### ISSUE THREAD

**Issue by SpatenWueste252** [NillerMedDild/Enigmatica6#717]
**Modpack version**
Enigmatica 6 0.3.2

**Issue**
We are playing on a server and no one gets items from rewards that are "Loot Reward" or "Random Reward"

**Comment by Merlo17** [comment]
Known issue, fixed in next release :D

**Comment by NillerMedDild** [comment]
Duplicate of #680
