### ISSUE TITLE
Astral Sorcery marbles are not oredicted to forge:stones/marble

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#718]
**Modpack version**
0.3.2

**Issue**
As title. I found this while crafting Resonating Wand on vanilla crafting bench

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by KrAzYGEEK32** [comment]
https://github.com/NillerMedDild/Enigmatica6/issues?page=3&q=is%3Aissue+is%3Aopen already known and fixed
