### ISSUE TITLE
[Bug] Globetrotter's Sash makes the elevators from Elevator Mod inconsistent

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#720]
**Modpack version**
0.3.2

**Issue**
The Globetrotter's Sash increases your movement capabilities (speed, jump height, etc) and because of the increased jump height the elevators become very inconsistent. Sometimes it feels like the elevator doesn't work at all. Here is a video demonstrating the bug: https://www.youtube.com/watch?v=9o1dqAezTA0

Also, I asked in the discord if this is the correct place to report this (versus the Botania github or the Elevator Mod github) but I didn't get a response so I figured I would just post it here. If it should be posted elsewhere let me know. Thanks!

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll have a look and relay :)

**Comment by NillerMedDild** [comment]
Looks like it has been reported and has a potential fix already: https://github.com/VsnGamer/ElevatorMod/issues/63

**Comment by RevenantWendigo** [comment]
Nice! Also wanted to ask, is it okay to do bug reports like this here? I have another nasty bug that I've experienced that I would like to report.

**Comment by NillerMedDild** [comment]
Yes definitely :)
