### ISSUE TITLE
[Bug] Using a Mekanism cardboard box on a Refined Storage crafter will delete the contents of the crafter

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#722]
**Modpack version**
0.3.2

**Issue**
To replicate: Make a crafter with patterns inside of it, use the cardboard box on it, break it, replace it, take the cardboard box off, the contents of the crafter will now be empty.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue. 

Would it be an acceptable solution for you to not be able to pick up the Crafter the a Cardboard box in the future?

**Comment by RevenantWendigo** [comment]
Yep! I won't make that mistake again! Hopefully it gets fixed though, I don't want others to suffer the same fate I did. It was truly tragic.

**Comment by NillerMedDild** [comment]
@Darkere I'm guessing you have an interest in this issue. Would you deem it on RS's side, or should we simply blacklist RS from the Cardboard box?

**Comment by Darkere** [comment]
Tagging everything with that forge "not movable" tag is on the to do list

Feel free to do it though. Next update is probably ways away :/
