### ISSUE TITLE
[Suggestion] Create Ore Buff

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica6#725]
Currently, Create ore processing feels like it's quite a bit behind everything else. Doubling with just about any other mod is quite simple and available pretty early on. The initial Create ore processing, however, yields a roughly 1.5x bonus to start and 2.2x bonus at the high end, which involves a fair amount of progression.

I'd propose a slight boost to the primary output and an addition of secondary outputs similar to Thermal.

First, every ore would be paired with a secondary ore following the table below:

| Ore      | Primary  | Secondary |
|----------|----------|-----------|
| Iron     | Iron     | Nickel    |
| Nickel   | Nickel   | Iron      |
| Gold     | Gold     | Zinc      |
| Copper   | Copper   | Gold      |
| Aluminum | Aluminum | Osmium    |
| Silver   | Silver   | Lead      |
| Uranium  | Uranium  | Lead      |
| Osmium   | Osmium   | Aluminum  |
| Zinc     | Zinc     | Gold      |

From here, we boost the numbers of the outputs.

The Millstone currently gives 1 crushed ore per ore. This would be boosted to 1 crushed ore + 25% chance of 2 more crushed ores, resulting in an expected average yield of 2.08x ingots per ore.

In addition, it would have a 5% chance to produce 2 crushed ores of the secondary output. This results in an expected average yield of 0.14 ingots per ore. This is just a bit higher than the IE crusher goes (10% extra) and the Thermal pulverizer is capable of getting up to about 40% bonus material by comparison (requires a basalz farm, effectively).

This all assumes the crushed ores are washed (no changes to the crushed > nugget ratios).

So that gets us a little bit over 2x ore processing, with a fair amount of logistics involved.

The Crusher would see a similar boost to bring it up to 3x processing. This would entail the primary being raised from it's current state (1 guaranteed + 30% chance of 2 more) to 1 guaranteed plus a 60% chance of 2 more crushed ores. This results in an expected average yield of 3.06 x ingots per ore.

Lastly, this too would be granted secondary outputs similar to the Millstone, but at a better rate. Here it would be a 10% chance of 2 secondary crushed ores, resulting in an expected average yield of 0.28 x ingots per ore.

I'm perfectly happy to write the scripts for this, but figured this is a big enough change to warrant discussion. 

I think it would also be interesting to bring these secondary outputs to more of the ore processing systems. Thermal, for instance, has no secondary for Aluminum, Zinc, or Osmium in the pulverizer. Similarly, the IE crusher has secondary outputs for a few of the ores, but not all. I've always been a fan of these extra outputs as it just feels nice to get those surprise bits of extra material when you're processing your ores.

**Comment by philipxjm** [comment]
I really like this idea! Create ore processing is really fun to set up and I think this would encourage a lot more players to use it instead of Mekanism or Thermal. The 2x is accessible early enough in the game and the 3x would still need a relatively length progression to get to. I would also suggest maybe an interaction between Create and Immersive Engineering (crushed ore processed by arc furnace etc.) to reach an even higher output rate like 4x. These two mods have a similar feel and the progression from a Create setup into Create + IE setup feels like an almost natural progression from early industrial revolution to late industrial revolution.

**Comment by NillerMedDild** [comment]
I think this is an excellent idea, and the numbers look solid. I have a few changes and additions to the primary/secondary table though:

| Ore      | Primary  | Secondary |
|----------|----------|-----------|
| Iron     | Iron     | Nickel    |
| Nickel   | Nickel   | Iron      |
| Gold     | Gold     | Zinc      |
| Copper   | Copper   | Gold      |
| Aluminum | Aluminum | Iron    |
| Silver   | Silver   | Lead      |
| Lead      | Lead      | Silver   |
| Uranium  | Uranium  | Lead      |
| Osmium   | Osmium   | Tin  |
| Tin   | Tin   |   Osmium
| Zinc     | Zinc     | Gold      |

Note: Reacting with Thumbs Up / Down is very helpful when reviewing suggestions and enhancements, please keep doing so 👍

**Comment by MuteTiefling** [comment]
Awesome, I'll put it together right away
