### ISSUE TITLE
Backback duplicates crafting upgrade

### ISSUE THREAD

**Issue by BrassHart** [NillerMedDild/Enigmatica6#726]
**Modpack version**
Enigmatica 6 0.3.2

**Issue**
When using invtweak with sophisticated backpacks that have a crafting upgrade installed, the crafting upgrade is duplicated into the backpacks inventory. This is the only upgrade that I know duplicates.

**Logs**
N/A

**Comment by Ridanisaurus** [comment]
This has already been fixed by the mod dev: https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/2

**Comment by BrassHart** [comment]
Thank you. I didn't see that post.

**Comment by NillerMedDild** [comment]
Duplicate of #645
