### ISSUE TITLE
Ticking entity Lost trinket mirror + Guardian

### ISSUE THREAD

**Issue by Sanguinely** [NillerMedDild/Enigmatica6#728]
**Modpack version**
0.3.2

**Issue**
Found a ocean monument, got hit by the guardians. console freaked, server crashed

**Logs**
https://pastebin.com/PWGbmf5j

I trimmed some of the log cause pastebin wouldn't let me post the whole thing, it was just repeating over and over. bottom bit is still intact, as well as the top.

**Comment by Flabort** [comment]
Duplication of #644

I am pretty sure the team said there they will be disabling the mirror shard until the mod author fixes it.

**Comment by NillerMedDild** [comment]
> I am pretty sure the team said there they will be disabling the mirror shard until the mod author fixes it.

We will indeed :)
