### ISSUE TITLE
minecraft:flower_pot becomes invisible with flowers from byg mod

### ISSUE THREAD

**Issue by Ilanea** [NillerMedDild/Enigmatica6#729]
**Modpack version**
0.3.2

**Issue**
Minecraft Flower Pots will bug out and become invisible blocks when you place flowers from byg in them.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Found it reported here: https://github.com/CorgiTaco/BYG/issues/179

**Comment by Zosu** [comment]
This also happens with the saplings from that mod. You can get the items back by doing something that would destroy a flower pot, like placing water on top of it.
