### ISSUE TITLE
[Mod Suggestion] CraftPresence

### ISSUE THREAD

**Issue by novaexe** [NillerMedDild/Enigmatica6#73]
Better than Simple Discord Rich Presence
https://www.curseforge.com/minecraft/mc-mods/craftpresence
Has Forge files

**Comment by NillerMedDild** [comment]
I'll have a look, but could you please give an example of how/why it's better?

**Comment by novaexe** [comment]
in game customization, support/help (discord, curse, email and github), server support, time spent in game, automatic detection of the pack your playing via launcher files, icon support and more I'm sure but those are the ones that stood out to me the most. 

Pros- extremely simple to understand and customize to your liking while playing, feature packed with significantly more than simple discord rich presence, multiple places to go for help if you have questions or need to troubleshoot.

Cons- none that I've discovered so far but it is 1.16 after all I'm sure there will be bugs.

**Comment by NillerMedDild** [comment]
While it does look awesome, I don't have the time required to set it up at the moment :/
