### ISSUE TITLE
Random loot reward always empty

### ISSUE THREAD

**Issue by dgobi** [NillerMedDild/Enigmatica6#730]
**Modpack version**
Enigmatica 6 0.32 / Minecraft 1.16

**Issue**
The random loot reward (red die icon) in the quest book always produces no reward. The screen for the reward is blank.

**Comment by MuteTiefling** [comment]
There's an issue with the quest loot tables being read properly on servers. This is already fixed in the next update.

**Comment by NillerMedDild** [comment]
Duplicate of #717
