### ISSUE TITLE
[Server Crash] Exception in server tick loop - Portable Stonecutter

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#739]
**Modpack version**
E6 0.3.3

**Issue**
Clicking `All` in the Portable Stonecutter GUI crashes the server. I've already reported it to Brackets.
https://github.com/brckts/Portable-Stonecutter/issues/6
Maybe until it's fixed we look into downgrading to the previous version?

**Logs**
https://gist.github.com/Ridanisaurus/ad4eaef7215c0f2d167a3858f3eddda2

**Comment by NillerMedDild** [comment]
Downgraded to 1.1.1 :)
