### ISSUE TITLE
found certus quartz in newly generated world

### ISSUE THREAD

**Issue by stefment** [NillerMedDild/Enigmatica6#746]
**Modpack version**
0.3.4

**Issue**
i was looking around in the cave and came across Certus Quartz and Charged Certus Quartz. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Sorry about that, looks like our config was overriden. As a sorry Certus will be convertable to something useful in the next update :)

**Comment by stefment** [comment]
That is very kind :) But no need to do that for me at least. There are probably more important things to do! Also it could create problems in the future if certus was ever to be added back and the patch was forgotten about. Its causes unnecessary complication. Its just my humble opinion.
