### ISSUE TITLE
Mob slaughter factory - client side crash

### ISSUE THREAD

**Issue by Ninjayatsu** [NillerMedDild/Enigmatica6#747]
**Modpack version**
0.3.2 server
**Issue**
1 person unexpectedly crashed, we don't know much other then what's said in the crash log, which is something with the mob slaughter factory from industrial foregoing.
**Logs**
Edit: I put your log in a gist
https://gist.github.com/NillerMedDild/b52cec0abf398bb6d05fec12c98e76c2

**Comment by NillerMedDild** [comment]
Would you mind updating to Enigmatica 6 v0.3.4 and see if the issue persists?

**Comment by Ninjayatsu** [comment]
Ok, but we are not sure how to recreate it lol. If we can I will update you
