### ISSUE TITLE
[Suggestion] Supplementaries 

### ISSUE THREAD

**Issue by kil0byt3** [NillerMedDild/Enigmatica6#751]
Just another suggestion I've been testing! Supplementaries has some nice vanilla-feeling decor and redstone items that showcase some of the nicer 1.13+ features for those coming from 1.12, such as waterlogging and lanterns. 

It also has a few functional decorative blocks (hanging signposts, sign posts, wall lanterns [with automatic other mod compat]) and a few functional redstone blocks (some of which could be disabled - for instance the Crank is basically the same as the similar block from Create). 

https://www.curseforge.com/minecraft/mc-mods/supplementaries

Also, if you do take a look, and like it, I'd be more than willing to practice my 1.16 skills by making a PR - Rebirth of the Night will be 1.12 only for the foreseeable future, and I'd like to expand my modpack-making knowledge to newer versions. Just let me know!

**Comment by Merlo17** [comment]
I checked it out super briefly and it looks pretty nice, just a harmless decoration mod. Texture and models are also sweet. I'm all for it personally

**Comment by MuteTiefling** [comment]
I wouldn't say it's a harmless deco mod, a lot of these things have redstone interactions. Still, looks like a pretty sweet mod. Might be a bit of overlap though.

**Comment by NillerMedDild** [comment]
I like it a lot, looks very well made. Will most likely add it.

> Also, if you do take a look, and like it, I'd be more than willing to practice my 1.16 skills by making a PR - Rebirth of the Night will be 1.12 only for the foreseeable future, and I'd like to expand my modpack-making knowledge to newer versions. Just let me know!

What would this PR be exactly? 😄

**Comment by kil0byt3** [comment]
I was thinking disable/hide:

- Jars (less confusion, as don't work with Forge liquids) 
- Turn Table (Create)
- Crank (Create) 
- perhaps Pedestals (E6 already has a Pedestals mod with features)
- Redstone Illuminator (I believe there are blocks with this feature that also look nicer)
- Item Shelves (Tetra?)
- cog block (wireless redstone options make this mostly useless, but maybe?)

Tweaks:
- adding Fireflies to more BYG/BoP biomes if they don't spawn there already
- check for recipe conflicts
- unify recipes to use other items already present in the modpack
- candelabra recipe (CF page says the recipe is temporary)

of course if you want to implement yourself, I wouldn't stop you; I just want to see the mod added, and I wanted to help if possible :D

**Comment by NillerMedDild** [comment]
Yes please on all counts, except I would like to keep Item Shelves :D

> cog block (wireless redstone options make this mostly useless, but maybe?) 

disable imo

**Comment by NillerMedDild** [comment]
There, files should be ready for modification on the dev branch, and the mod is present - Have at it :D

**Comment by willbattel** [comment]
> I was thinking disable/hide:
> 
> * Jars (less confusion, as don't work with Forge liquids)
> ...

Does Supplementaries intend to add support for Forge liquids to jars? I searched their repo but didn't see any issues regarding this. Am I blind or is this not being tracked?

https://github.com/MehVahdJukaar/Supplementaries/issues?q=is%3Aissue+jar

**Comment by NillerMedDild** [comment]
I think Jars already support Forge liquids, could be wrong though.

**Comment by kil0byt3** [comment]
Niller is correct, but it was added(relatively) recently. the developer reworked the Jar system [here](https://www.curseforge.com/minecraft/mc-mods/supplementaries/files/3218015) adding support for Forge liquids among other things. Originally it used its own system entirely.

**Comment by willbattel** [comment]
That's fantastic. Can we reconsider their inclusion in the pack? Supplementaries' jars are really neat and my friends and I want to use them in E6.

**Comment by kil0byt3** [comment]
Up to Niller and the team, but I don't see why not now that there's Forge liquids support - as an early game fluid storage and transport option. If I recall correctly, they only hold something like ~4 buckets. Plus - with jars + faucets in Supplementaries I believe there are some other interaction options possible. I'll leave the decision to Niller though 😄

**Comment by NillerMedDild** [comment]
Sure, I'll just give them a quick test and add them if they check out.
