### ISSUE TITLE
Apotheosis does not increase level cap of Ars Noveue Enchantments. 

### ISSUE THREAD

**Issue by Flabort** [NillerMedDild/Enigmatica6#753]
**Modpack version**
3.4

**Issue**
The armor Enchantments from the Ars mod are currently capped at III. Apoth does recognize the enchants, but is not configured to increase the max level like it does other enchants. 

**Logs**
NA

**Comment by MuteTiefling** [comment]
I'll be honest here, some of the apotheosis limits probably need to be brought down instead of bringing everything up.

**Comment by NillerMedDild** [comment]
We'll look into whether or not we think AN enchants should be capped higher :)

**Comment by NillerMedDild** [comment]
Hmm, what makes you say Apotheosis recognizes the enchants?

**Comment by NillerMedDild** [comment]
I didn't have AN entries for some reason, luckily TheBoo did 😄
