### ISSUE TITLE
Apotheosis spawner config set to use Max INT for many limits. Intended?

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica6#754]
**Modpack version**
0.3.4

**Issue**
Apotheosis spawner config set to use Max INT for many limits. This can lead to rather silly amounts of mobs,speed, etc. Intended?

**Comment by NillerMedDild** [comment]
Not really intended, but the mod seemed to limit the max to other values than specified. Looks better now :P
