### ISSUE TITLE
Eidolon Enchantment Table breaks Apotheosis advancements 

### ISSUE THREAD

**Issue by Flabort** [NillerMedDild/Enigmatica6#756]
**Modpack version**
3.4

**Issue**
Using Eidolon progression to enchant items gives every Apotheosis enchanting related advancement at once, as if using a table that is at 100% Arcana, 100% Quanta, and 100% Eterna, while being simultaneously at 0% Quanta. 

**Logs**
NA

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
