### ISSUE TITLE
Cannot make "Silky Cobble Gen" pedestal upgrade

### ISSUE THREAD

**Issue by MJohnny09** [NillerMedDild/Enigmatica6#757]
**Modpack version**
0.3.4

**Issue**
Several pedestal recipes require the "Silky Cobble Gen" (i.e. Dacite, Granite, Brimstone, etc.), but there doesn't seem to be a way to obtain an upgrade with silk touch. A silk touch book cannot be combined with it in an anvil and I've tried simply enchanting a few, but only get the pedestal capacity and speed upgrades. I'm not sure if this is an not fully-implemented feature of pedestals or an error within Enigmatica 6. I don't see any open issues on Pedestals' github regarding this.

**Comment by MuteTiefling** [comment]
The wiki is a little out of date, but for this it is still accurate: https://github.com/Mowmaster/Pedestals/wiki/Enchantments

You need to apply silk touch with pedestals.

**Comment by MJohnny09** [comment]
Oh, ok thanks for clarifying that. There is no issue then, I'll try that out later today after work!
