### ISSUE TITLE
Botania's "Spark Augmenter banner patterns" are bugged

### ISSUE THREAD

**Issue by SiragusWolf** [NillerMedDild/Enigmatica6#758]
**Modpack version**
0.3.4

**Issue**
In theory, you should be able to combine a spark augmenter with a banner and a dye to put the augmenter symbol in the banner. When you do this, the whole banner becomes a missing texture.

**Comment by Darkere** [comment]
I've received reports that RS somehow breaks banners in some cases.

I don't see how that could possibly be the case but it might be a lead.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by SiragusWolf** [comment]
Sure thing! I'll try it out as soon as I wake up and come back to you. Sorry for taking so long. 
Enviado desde Yahoo Mail para Android 
 
  El mar., 5 de ene. de 2021 a la(s) 18:31, Niels Pilgaard Grøndahl<notifications@github.com> escribió:   


@SiragusWolf Would you mind trying this with only Botania + JEI installed? :)

**Comment by SiragusWolf** [comment]
Hello again, I apologize for taking so long. I tried it on a fresh install of Botania + JEI on forge version 35.1.32 and the bug was still the same. I also found that, depending on the dye used, the colors of the banner would change, but it's always a missing texture. I can provide a screenshot or more details if you need me to.

**Comment by NillerMedDild** [comment]
You didn't take long at all, thanks a lot for testing!

**Comment by NillerMedDild** [comment]
Screenshots would be helpful by the way :)

**Comment by SiragusWolf** [comment]
![2021-01-07_17 07 28](https://user-images.githubusercontent.com/76983197/103939663-e0532400-510a-11eb-910c-048a07f1ade0.png)
These are the dyes that I tried. As you can see, they don't change the color of the banner to the color of the dye directly, but each appears to have a random color to it. Also, changing the type of augmenter doesn't change the banner at all (it's the same for all of them)
