### ISSUE TITLE
[Mod Suggestion] Mystical Agriculture

### ISSUE THREAD

**Issue by nfowler** [NillerMedDild/Enigmatica6#76]
Mystical Agriculture has been updated to 1.16. As of writing, only a beta release is available.
https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture

In addition, Mystical Agradditions has been updated.
https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions

And another addon I haven't seen before but appears to be aimed at pack authors.
https://www.curseforge.com/minecraft/mc-mods/mystical-customization

**Comment by TGMax233Michael** [comment]
The third mod is used to customize some new crops and some other things, may be useful

**Comment by NillerMedDild** [comment]
I'd rather go with bees for resource generation this time around :)

**Comment by Quezler** [comment]
sidenote, just played another pack that happend to have it, and its now painfully slow in garden clothes, not sure if mystical agriculture "fixed" that or that e2e boosted it intentionally, but it was not fun in the slightest 👀 

though i have yet to understand bees, guess i should read up on the mod 😅

**Comment by NillerMedDild** [comment]
E2E boosted Cloches by a ton, so players wouldn't have to stack them, they weren't good for server TPS at the time :)
