### ISSUE TITLE
Bees won't go in new hives if they're carrying pollen

### ISSUE THREAD

**Issue by stupex** [NillerMedDild/Enigmatica6#763]
**Modpack version**
0.3.4

**Issue**
If you change a beehive (to a different tier or type) while a bee that currently lives their still has pollen, then the bee won't accept the new hive. They have to go back to the same type/tier hive and make a honeycomb before they can accept the new hives as their new home. In short: the bee needs to have no pollen to accept a new type of beehive.

Edit: Just found out that the bees need to have no accessible flowers too when they come out of their current hives before you put them in a jar and do the hive swap

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
