### ISSUE TITLE
Can't select-all text in JEI search box

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica6#765]
**Modpack version**
0.3.0-0.3.4

**Issue**
I'm on MacOSX, this is running both 10.15 & 11 (the most recent release). Running Oracle Java 8 Update 271 Build 09.
Hitting cmd-A doesn't select text in the JEI search box. I've also tried control-A to no avail. I asked in the E6 Discord channel, and it sounds like I'm not the only one seeing this, with at least one Windows user reporting similar behavior. I'm assuming the issue here lies with JEI, so I reported it at the following issue:

https://github.com/mezz/JustEnoughItems/issues/2203#issue-779135910

I'm not sure what logs would come in handy, but if there's anything I can supply please let me know!

**Logs**
N/A, I think?

**Comment by KangyKSLG** [comment]
This has been a thing since 1.12.2 so if a fix happens that would be great. I've just adapted to use CTRL+Backspace now instead

**Comment by Merlo17** [comment]
Here's what happens in my experience: CTRL+A works if you hit Backspace while you're still holding CTRL+A, otherwise if you do it and then let go before deleting it bugs out. I'm used to it nowadays and I just hold, but it's still fairly annoying

**Comment by TemperedFool** [comment]
It just doesn't work at all for me. This is a post-1.12 issue for me, it works fine in E2E and other 1.12 modpacks.

**Comment by Merlo17** [comment]
I can confirm, I didn't have it in E2E but did have it in E5, and I just tested it on E6 and for me on Windows it works like I described. Overall, definitively some weirdness going on there

**Comment by Ridanisaurus** [comment]
It seems to be released to which container is open. For example I'm unable to select all when I have a Crafting Table open, or but I'm able to when just in my Inv.

**Comment by TemperedFool** [comment]
This has apparently been fixed in JEI version ending .65:

https://github.com/mezz/JustEnoughItems/issues/2203#issuecomment-757092927

Not sure if you've updated to that yet (I'm sticking with 0.3.2 until my new server computer arrives and I need to reinstall stuff anyway), but if not maybe that can happen in 0.3.6. Is there any reason hand-updating would be an issue? I assume server & client versions need to match.

**Comment by Darkere** [comment]
They don't need to match but the networking needs to be compatible across versions. So it depends on the particular mod and what changes have been done.

**Comment by TemperedFool** [comment]
Can confirm, upgrading it to .65 seems to fix it.
