### ISSUE TITLE
[Mod Suggestion] Simple Magnets

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#766]
https://www.curseforge.com/minecraft/mc-mods/simple-magnets
adds 2 magnet variants, basic tier is a simple magnet, advanced one has configurable range and has a blacklist.
the best parts of the mod are
- magnets are curio compatible
- and they have a HOTKEY!! to disable/enable them from curio slot

i've been playing with the mod, and its very nice!

**Comment by theboo** [comment]
hotkey for magnet is a huge plus

**Comment by NillerMedDild** [comment]
I don't know, we already have several magnets :/ the PneumaticCraft Magnet Upgrade even has a hotkey.
I suggested Curious & hotkey for Thermal Innovation magnet here: https://discord.com/channels/399037120930512897/413979575056597003/796104488045903933
