### ISSUE TITLE
Blaze Bees doesn't use any flower, fungus, or netherwart

### ISSUE THREAD

**Issue by stupex** [NillerMedDild/Enigmatica6#768]
**Modpack version**
0.3.4

**Issue**
JEI says blaze bees use netherwarts but they don't. Tried all possible flowers and fungi and nothing worked so the blaze bees can't produce anything atm. They work previously with netherwarts though.

**Logs**
N/A

**Comment by Ridanisaurus** [comment]
Interesting. This is with the current flower setup, and it seems to work.
![image](https://user-images.githubusercontent.com/64355028/103676505-752a1600-4f81-11eb-9cf4-9446eb99eed8.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
