### ISSUE TITLE
[Mod Suggestion] Mahou Tsukai

### ISSUE THREAD

**Issue by lamb3664** [NillerMedDild/Enigmatica6#769]
https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai

This mod has a unique magic system and provides spells with unique functionality that don't compete with stuff from vanilla and other magic mods. I doubt much configuration would be needed to fit in this mod, as it doesn't add new world-gen stuff to my knowledge.

**Comment by Ridanisaurus** [comment]
This was already requested, and denied. #81

**Comment by lamb3664** [comment]
Oh, didn't know that when I made the suggestion. Oh well, I've managed to easily add it to the modpack manually.
