### ISSUE TITLE
[Mod Suggestion] Aquaculture 2

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#77]
This is a fishing mod. (Enigmatica 5 has this mod, so does this modpack need to add this mod?)
https://www.curseforge.com/minecraft/mc-mods/aquaculture/files/3024910

**Comment by NillerMedDild** [comment]
I will be adding this. You don't have to suggest everything you know, I look at every single mod update for 1.15+ :)
