### ISSUE TITLE
Tome of Blood

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#771]
https://www.curseforge.com/minecraft/mc-mods/tome-of-blood

Ehehe, I beat you to it Rid!

**Comment by Ridanisaurus** [comment]
Aw man! 
Damn cool mod.
Don't add it yet, there is a crash if you try to cast a spell without the LP, and ToxicMintTea is aware. They are looking into it.

**Comment by Trostmm** [comment]
OH that's neat, looks like they added living armor upgrades to boost mana as well...

**Comment by Ridanisaurus** [comment]
Alright, it looks like most of the issues I found have been fixed with 1.0.2 release.

**Comment by NillerMedDild** [comment]
Blocked: https://github.com/MintTeaTx/Tome-of-Blood/issues/1

**Comment by Merlo17** [comment]
I mean Rid warned you :P

**Comment by NillerMedDild** [comment]
Rid also told most issues had been fixed :P

**Comment by NillerMedDild** [comment]
Removed from CurseForge, removed from pack. Will be back hopefully.
