### ISSUE TITLE
Mod suggestion: Ice And Fire

### ISSUE THREAD

**Issue by KovekA** [NillerMedDild/Enigmatica6#773]
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons

I think this mod should be added, it contains a lot of amazing creatures.

**Comment by KangyKSLG** [comment]
I'd love to see ice and fire in this pack, even if the dragons are restricted to only spawning in the Undergarden or something

**Comment by Ridanisaurus** [comment]
Duplicate on #312
