### ISSUE TITLE
Machine Infuser ONLY accepts Dimensional Shards from RFToolsBase, no other Dimensional Shards (aka Emendatus Enigmatica)

### ISSUE THREAD

**Issue by kil0byt3** [NillerMedDild/Enigmatica6#776]
**Modpack version**
dev

**Issue**
See linked issue here for description and pictures. 
https://github.com/McJtyMods/RFToolsBase/issues/34

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Added a conversion recipe until this is fixed :)
