### ISSUE TITLE
Create Recipe Conflict

### ISSUE THREAD

**Issue by KangyKSLG** [NillerMedDild/Enigmatica6#779]
**Modpack version**
0.3.4

**Issue**
To create Otherstone from the Occultism mod you need to put 4 stone in an Automated Packing setup.
4 stone for 1 Otherstone.
4 stone also creates stone brick

![image](https://user-images.githubusercontent.com/42292756/103711724-eb457180-4faf-11eb-9d40-94a9ac42eb9c.png)

**Comment by MuteTiefling** [comment]
https://github.com/Creators-of-Create/Create/issues/674

Not seeing a good way to fix this with configs/scripts either. Can't target the recipe because it gets the same ID as the base mod, and Create doesn't appear to have a blacklist for these, it's either all on or all off.

**Comment by theboo** [comment]
the otherstone recipe should not exist, for some reason create is seeing it as a crafting recipe, the recipes for this machine take any 2x2 crafting recipe where all 4 are the same ingredients... the real recipe is trading 4 stone for 1 otherstone with the spirit trader...

https://i.imgur.com/rDwQHPG.png

**Comment by KangyKSLG** [comment]
Ahhh, I had a feeling the otherstone recipe wasn't intended.

Now I need to travel far enough from my base to cause the otherworld stuff to spawn when using the third eye

So far I'm getting nothing so either I haven't travelled far enough, I'm not understanding where to find it, or there is a bug haha
