### ISSUE TITLE
[Mod Suggestion] Crash Utilities

### ISSUE THREAD

**Issue by TGMax233Michael** [NillerMedDild/Enigmatica6#78]
**Crash Utilities** adds a number of tools for finding and fixing common server problems.(For Server Administrator）
https://www.curseforge.com/minecraft/mc-mods/crash-utilities/files/3008071 (File)
https://www.curseforge.com/minecraft/mc-mods/crash-utilities (Introduction)

**Comment by NillerMedDild** [comment]
I leave it up to server owners whether they want/need this tool.
