### ISSUE TITLE
[Mod Suggestion] Iron Furnaces

### ISSUE THREAD

**Issue by KangyKSLG** [NillerMedDild/Enigmatica6#783]
So when it comes to furnaces there aren't really a lot options that don't require FE

I suggest adding Iron Furnaces to add upgradable furnaces without the need for the to be FE powered

https://www.curseforge.com/minecraft/mc-mods/iron-furnaces

**Comment by MuteTiefling** [comment]
RF free smelting methods:
Astral Sorcery: Ignition Lenses smelt items that fall in the light beam
Create: Fan behind lava smelting
PNC: Heat generated by the mod will power a Furnace. Alternately, a Heat Frame can smelt items in chests.
Botania: Exoflame's power furnaces with mana
Nature's Aura: Extraneous Firestarter will power a furnace with Aura

I'm sure I'm missing a few, but that's just to show that there are plenty of non RF based smelting methods to explore. Iron Furnaces always felt kinda boring to me.

**Comment by Trostmm** [comment]
Blood magic lava crystal for LP fueled smelting.

**Comment by NillerMedDild** [comment]
I agree with Mute :)
