### ISSUE TITLE
Bug: Tha Ghost Trinket not-functional

### ISSUE THREAD

**Issue by Sanguinely** [NillerMedDild/Enigmatica6#784]
**Modpack version**
0.3.4

**Issue**
Tha Ghost states that all entities including players cannot see armor/held items. they can https://github.com/owmii/Lost-Trinkets/issues/20 have posted issue on the trinket page

**Comment by spdkils** [comment]
That Ghost trinket with INVIS is just god mode anyway. Nothing will even attack you if you attack it and you're invis. Basically creative mode combat.
I'm going to guess its a conflict with cosmetic armor... just hide your armor.

**Comment by Sanguinely** [comment]
not with cosmetic armor, it is held items as well

**Comment by NillerMedDild** [comment]
I'm just going to disable this now then :)

**Comment by BlueAgent** [comment]
With the above PR, Tha Ghost was fixed/nerfed to let mobs retaliate when hurt by the ghosted player.
