### ISSUE TITLE
Carbuncles hate being captured

### ISSUE THREAD

**Issue by Sanguinely** [NillerMedDild/Enigmatica6#785]
**Modpack version**
0.3.4

**Issue**
Carbuncles cannot be picked up with the mob imprisonment tool

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Ridanisaurus** [comment]
If I'm not mistaken, this is on purpose as they are not meant to be captured by such means as they require a specific mechanic to capture their shard with a Gold Nugget, and then turning them into tamed Carbuncles through the use of the Apparatus.

**Comment by MuteTiefling** [comment]
If this is intended, it should probably be extended to Sylphs too, as they're currently still capturable

**Comment by Ridanisaurus** [comment]
I asked Bailey, and he confirmed that it's not on purpose. so I guess I was wrong with my assumption.

**Comment by Flabort** [comment]
Huh. I was able to capture and move one with a mob imprisonment tool - albeit, in 3.2, not 3.4; after the updates he's still in the cage I built in order to have him pose for me so I could make a sculpture of him.
