### ISSUE TITLE
CurseForge project '328085' file '3143387' no longer exists, please update Create reference

### ISSUE THREAD

**Issue by olagarde** [NillerMedDild/Enigmatica6#786]
**Modpack version**
E6 0.3.2

**Issue**
Modpack json references curseforge project 328085 file 3143387 which no longer exists.  This should be updated to either fileid 3158185 (Create 4_v0.3c, mc 1.16.3+4) or fileid 3146074 (Create 4_v0.3b, mc 1.16.3+4).

**Logs**
Not applicable.

E6 0.3.2 modpack json references Create mod as projectid 328085, fileid 3143387.

Curseforge project 328085 (Create) now has:

    fileid 3158185 (Create - mc1.16.3+4_v0.3c.jar) (latest)
    fileid 3158179 (Create - mc1.15.2_v0.3c.jar)
    fileid 3146075 (Create - mc1.15.2_v0.3b.jar)
    fileid 3146074 (Create - mc1.16.3+4_v0.3b.jar)
    fileid 3066060 (Create - mc1.15.2_v0.2.4e)
    fileid 2952509 (create-mc1.14.4_v0.2.3.jar)
    fileid 2184006 (create-mc1.14.4_v0.1.1a.jar)

**Comment by NillerMedDild** [comment]
This is probably fixed in 0.3.3 or 0.3.4, either way, CurseForge usually keeps the files so mod packs don't break after being released. Is this causing issues?

**Comment by olagarde** [comment]
I'm only considering the release versions, which is why I'm using 0.3.2.  This version won't install because curseforge project 328085 file 3143387 no longer exists -- the download attempts to pull the referenced file and 404's because the referenced link isn't there.  I do see that the lowest fileid for a Create for MC1.16 is well above the referenced fileid, so I can only assume that the mod author intentionally removed the version(s) prior to 0.3b.  I'm not aware of any Curseforge automation to retain or remove prior file uploads, only that authors sometimes either re-use prior filenames (which still results in a newer fileid because these are allocated next-available and ascending) or intentionally remove prior versions.  Create appears to have done the latter.  I'll try the E6 beta versions, see what they reference....

**Comment by NillerMedDild** [comment]
I can install 0.3.2 just fine, did you try more than once? :)

**Comment by olagarde** [comment]
Yep.  What do you see starting at line 32 of the 0.3.2 manifest.json?  I see this:

{
      "projectID": 328085,
      "fileID": 3143387,
      "required": true
    },

Projectid 328085 is the Create mod, and as I've already noted that mod's public facing links do not include that fileid.

**Comment by NillerMedDild** [comment]
That doesn't matter, the file is still available albeit not visible on the site. I already told you, CurseForge usually keeps the files so mod packs don't break after being released.

**Comment by olagarde** [comment]
Give me a few to run two verbose installs and I'll post the logs of the curseforge project deref's as the URLs are constructed, that'll show the diff.  FWIW I do see that E6 0.3.5 references the projectid/fileid for Create 0.3c, which is available, so I'd expect that to work fine.
