### ISSUE TITLE
Mining feels like a breeze

### ISSUE THREAD

**Issue by stefment** [NillerMedDild/Enigmatica6#788]
**Modpack version**
0.3.4 Beta

**Issue**
Because of veinminer and because of ore doubling mining is a breeze. Ores also spawn relatively few blocks apart. So I was thinking about making ores a little bit rarer to slightly extend the early game.

Before: 
![2021-01-06_07 56 14](https://user-images.githubusercontent.com/8888420/103738678-b6a7d900-4ff4-11eb-9ceb-5597a2d022a3.png)

After:
![2021-01-06_07 56 20](https://user-images.githubusercontent.com/8888420/103738685-b90a3300-4ff4-11eb-855d-ab15be19000d.png)

Before; 
![2021-01-06_07 47 47](https://user-images.githubusercontent.com/8888420/103738243-f1f5d800-4ff3-11eb-9047-ace3120a7c98.png)
After:
![2021-01-06_07 47 41](https://user-images.githubusercontent.com/8888420/103738256-f621f580-4ff3-11eb-9428-18f0e1074987.png)

**Comment by hvdklauw** [comment]
I think redstone can use a nerf too

**Comment by NillerMedDild** [comment]
I agree, decreased it a little.
