### ISSUE TITLE
Removed Fishing Real

### ISSUE THREAD

**Issue by Gayanfalor** [NillerMedDild/Enigmatica6#790]
**Modpack version**
0.3.2

**Issue**
I think the mod real fishing , blocking or not really wokring well with the tinkets that gives 3 rolls form fishing plus the anglers bounty enchant.

I have not tested too wiht the combo fishing rod from aquaculutre 2 with a double hook+ triple trinket+ anglers bounty but i think it should not work.

i think we losing much stuff form fishing coz of that if its not intended.

thanks

**Comment by KangyKSLG** [comment]
Judging by the roadmap laid out for the 0.4.0 in #528 release it's set to be removed

**Comment by Gayanfalor** [comment]
oh nice, but why removing aquaculure 2 ?

**Comment by KangyKSLG** [comment]
Pass, sorry. That'll be a question for the devs.

I'm just a helpful chap haha

**Comment by NillerMedDild** [comment]
Because it doesn't really serve much of a purpose in the pack, and I want to keep the mod count relatively low to limit performance issues.

**Comment by NillerMedDild** [comment]
Fishing Real will be removed in 0.3.5 instead of 0.4.0, thanks for the report :)
