### ISSUE TITLE
Mekanism Blocks

### ISSUE THREAD

**Issue by NoobGamerHD** [NillerMedDild/Enigmatica6#791]
**Modpack version**
0.3.2

**Issue**
Unable to access any mekanism machine/block gui by right-clicking

**Logs**
----------

**Comment by Merlo17** [comment]
Are you by chance in a claimed chunk?

**Comment by NoobGamerHD** [comment]
> Are you by chance in a claimed chunk?

no

**Comment by Darkere** [comment]
Please try restarting client.

**Comment by NoobGamerHD** [comment]
> Please try restarting client.

ok

**Comment by NoobGamerHD** [comment]
> Please try restarting client.

It worked, thanks bud.

**Comment by NoobGamerHD** [comment]
Issue closed, the fix was simple lol
