### ISSUE TITLE
Thermal Pulverizer doesn't accept Ancient Debris

### ISSUE THREAD

**Issue by lamb3664** [NillerMedDild/Enigmatica6#793]
**Modpack version**
Enig 6 0.3.4

**Issue**
The Thermal pulverizer, unlike any other source of ore doubling in the modpack (such as the enrichment chamber or starlight infusion), does not accept Ancient Debris to be doubled.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
