### ISSUE TITLE
Recipe conflict when smelting stone bricks

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica6#796]
**Modpack version**
0.3.4

**Issue**
Smelting stone bricks can give both Cracked stone bricks and Eidolon Smooth bricks.

So maybe add cracked stone bricks to the stonecutter as the eidelon smooth bricks are also obtainable by stonecutting Smooth stone

**Comment by NillerMedDild** [comment]
Thanks for the report, someone beat me to it on the Eidolon tracker 😄 
https://github.com/elucent/eidolon/issues/34
