### ISSUE TITLE
Crafting from JEI with Refined Storage provides blank output

### ISSUE THREAD

**Issue by KangyKSLG** [NillerMedDild/Enigmatica6#798]
**Modpack version**
0.3.4

**Issue**
As description, autofilling crafts from refined storage makes output blank until 1 item is picked up and replaced

**Logs**
Input pastebin link to crash-report or latest log, if applicable
![image](https://user-images.githubusercontent.com/42292756/103823499-1db3a500-506a-11eb-9a0f-ffac92877782.png)

**Comment by Darkere** [comment]
Reopening the grid also makes the item appear. Not sure what happened there but will investigate.

**Comment by KangyKSLG** [comment]
> Reopening the grid also makes the item appear. Not sure what happened there but will investigate.

Great! Happy to help if you need a tester :)

**Comment by anivlys** [comment]
In my experience you can still actually click on the blank output and get the item. Not ideal, but appears to be more of a visual bug than any recipes actually being messed up.

**Comment by DannyDan4** [comment]
the only time this bug is a problem is if setting up autocrafting, where it doesn't let you make a pattern until you exit and reopen the menu.

**Comment by kil0byt3** [comment]
> the only time this bug is a problem is if setting up autocrafting, where it doesn't let you make a pattern until you exit and reopen the menu, as the 'ghost' item can be picked up in regular crafting scenarios.

Can also press R/U on any item in JEI/etc, then close the recipe shown and the "ghost item" will reappear. That's been my workaround so far :)

**Comment by NillerMedDild** [comment]
@Darkere any idea if this has been resolved?

**Comment by Darkere** [comment]
Yes. This was caused by Polymorph and has been fixed since.
