### ISSUE TITLE
Prevent Creepers from destroying items

### ISSUE THREAD

**Issue by DreaminBoi** [NillerMedDild/Enigmatica6#8]
https://www.curseforge.com/minecraft/mc-mods/environmental-creepers
https://www.curseforge.com/minecraft/mc-mods/creeper-confetti

Because creeper's suck when they blow up your hardworked base

**Comment by NillerMedDild** [comment]
Sorry but no, Creepers provide incentive to fortify your base and stay alert, and we think that's good :)

**Comment by NillerMedDild** [comment]
... However, blocks not getting destroyed by creeper explosions would be nice, semi accepted!

**Comment by DreaminBoi** [comment]
All is good :)

**Comment by ben-mkiv** [comment]
advertising my own mod here ;)
https://www.curseforge.com/minecraft/mc-mods/creeperfix

**Comment by NillerMedDild** [comment]
Nice try :P
but Environmental Creepers has an additional config that I would like, configurable chance for blocks to drop when destroyed by creeper explosions.
