### ISSUE TITLE
Mekanism Textures sometimes disappear

### ISSUE THREAD

**Issue by KangyKSLG** [NillerMedDild/Enigmatica6#800]
**Modpack version**
0.3.4

**Issue**
As title, Mekanism item textures in the inventory sometimes don't render. I'm using the official Enigmatica texture pack but it also happened with Faithful texture pack and vanilla

![image](https://user-images.githubusercontent.com/42292756/103837997-e2be6b00-5083-11eb-8131-e9a2d4e478cc.png)

**Comment by Merlo17** [comment]
Are you using optifine?

**Comment by KangyKSLG** [comment]
Yes along with OptiForge.

I assume that's the cause of this? I always forget I have optifine.. haha

**Comment by NillerMedDild** [comment]
Yeah probably :P wanna try removing it to confirm?

**Comment by KangyKSLG** [comment]
> Yeah probably :P wanna try removing it to confirm?

Sure will do! I'll be on later to test

**Comment by KangyKSLG** [comment]
Okay i'ma close this, seems okay without OptiFine :) many apologies!

**Comment by NillerMedDild** [comment]
No worries!
