### ISSUE TITLE
Dank Construction Mode Bug

### ISSUE THREAD

**Issue by IllegalCharacter** [NillerMedDild/Enigmatica6#801]
**Modpack version**
Enigmatica6 0.3.2

**Issue**
Placing Mekanism Universal Cables in the Dank and trying to place them in construction mode will place the whole dank as a single wire, losing all items inside the dank, and the dank itself.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Universal Cables no longer go in the Dank: I highly recommend that you don't put anything "complex" in there :P
