### ISSUE TITLE
Cant interact /right click on my base

### ISSUE THREAD

**Issue by Gayanfalor** [NillerMedDild/Enigmatica6#803]
**Modpack version**
0.3.2

**Issue**
Dunno what happened but i cant interact wit things in my base( chest, grid etc) i was crafting drone blades from pneumaticraft to make the spawner extractor i opened a wooden door with the blades in hand and the door was acting strange only the top part was moving a bit like if i was not allowed in the claim.

**Logs**

**Comment by Darkere** [comment]
Try client restart

**Comment by Gayanfalor** [comment]
i got that yesterday i tried to play this morning and it was the same, wich log you want ?
