### ISSUE TITLE
block diversity mod suggestion

### ISSUE THREAD

**Issue by Ninjayatsu** [NillerMedDild/Enigmatica6#804]
**Modpack version**
next update ples
**Issue**
Add a mod called block diversity, it adds tons of really cool blocks, that look really good. and it adds tons of different variants for vanilla blocks. some new blocks are added like limestone, basalt, gabro, dasite, and new colors for wool that look 👌  like different colored wools, etc. some new things they add, are pillars, quarter stairs and slabs, and like I said before, for nearly every block, that you will build with. I really think it should be added, cause it look sooooo gud please add thank u. also all the stone recipes are added to the stone cutter already (:
https://www.curseforge.com/minecraft/mc-mods/block-diversity

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by NillerMedDild** [comment]
I have a bad feeling about the additional colors tbh, I doubt that'll play well with other mods. I don't think Block Diversity adds anything we're distinctively lacking, on those two counts, this is a no :)
