### ISSUE TITLE
[SUGGESTION] Various client-side mods/tweaks

### ISSUE THREAD

**Issue by kil0byt3** [NillerMedDild/Enigmatica6#805]
Hey, it's me, your friendly neighbourhood suggestion guy.

A few little QoL/client-side things - take or leave each, as you will. I searched #suggestions in discord and don't think these were mentioned, but Discord search sort of sucks (and I prefer GH anyway). :D

[Nimble](https://www.curseforge.com/minecraft/mc-mods/nimble) is a camera qol change that adds a transition on the third-person camera, auto-third person for Elytra/cart/horse etc riding, and camera rolling when flying with Elytra (it's very cool). Clientside only

[Sound Filters](https://www.curseforge.com/minecraft/mc-mods/sound-filters) - well, we all know what Sound Filters does :) But basically, makes all sound in Minecraft better - reverb in caves, slightly mutes sounds behind walls etc. (very nice for loud machines). Clientside only

[Dynamic Surroundings](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings) - Makes the world more lively in general, both visually and audibly. _Incompatible with Sound Filters_ as per the note on the CF page, so should have one or the other (or, it's possible to disable DynSurround's implementation of this if you'd like both). Clientside only 

[Ping](https://www.curseforge.com/minecraft/mc-mods/ping) - Yes, it's another keybind, but this mod is very lightweight and useful for co-op - pointing things out to other players. Required on server and client

[Spark](https://www.curseforge.com/minecraft/mc-mods/spark) - Shipping this in the server pack would just be helpful to the server admins out there!

My server of 16 people has been testing all of these for the last two weeks alongside E6 base with no issues :)

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by KangyKSLG** [comment]
+1 for dynamic surroundings :)

**Comment by Thiana** [comment]
-1 for dynamic surroundings unless they have fixed the big fps hit the 1.12 version had?

**Comment by kil0byt3** [comment]
> -1 for dynamic surroundings unless they have fixed the big fps hit the 1.12 version had?

A great question. I have not personally experienced issues but my computer specs are not a good indicator of the average user. The CF page does indicate a "total rewrite" occured at some point prior to the 1.16 releases, including quite a few GH issues I see that were in regards to FPS/performance. Probably just worth testing.

**Comment by Merlo17** [comment]
We were using dynamic surroundings in E5 already and it wasn't impacting much, at least that I could see. It might need more investingating then

**Comment by NillerMedDild** [comment]
We used Ambient Sounds, like we do in E6 atm :P

**Comment by NillerMedDild** [comment]
I would personally play with Nimble, but since it's a clientside mod I will let people add it if they want it. I think many would be confused by it.

Sound Filters / Dynamic Surroundings are a no, we already have Ambient Sounds which is similar and doesn't impact FPS

Spark will be added.

Ping will be added if it passes my testing :)

**Comment by NillerMedDild** [comment]
And it did, added!

**Comment by kil0byt3** [comment]
Sounds good! Thanks for reviewing!
