### ISSUE TITLE
Excessive Cave Generation

### ISSUE THREAD

**Issue by Shumaan** [NillerMedDild/Enigmatica6#809]
0.3.5

Maybe it's just bad world spawns, but I swear cave generation has increase drastically on the surface. It's actually kind of difficult finding a nice flat area that isn't cratered or sitting above a cavern two blocks below.

**Comment by NillerMedDild** [comment]
Hm, that's odd. Would you mind providing screenshots?

**Comment by KangyKSLG** [comment]
The only biome I've experienced this on is the prairie biome

**Comment by Shumaan** [comment]
So I haven't done extensive testing, but the first world I loaded into on a fresh install seems to have a lot of surface caves. 

![2021-01-08_14 39 49](https://user-images.githubusercontent.com/2516230/104063112-439f8d80-51c1-11eb-9546-90d1dcd6b48f.png)
![2021-01-08_14 44 01](https://user-images.githubusercontent.com/2516230/104063120-4601e780-51c1-11eb-8567-c7b1ca4ceed0.png)
![2021-01-08_14 44 12](https://user-images.githubusercontent.com/2516230/104063125-47cbab00-51c1-11eb-89ec-90c380cd54dd.png)

**Comment by lamb3664** [comment]
From personal experience, the caves like to cut into structures too - it is not unusual to find a village with barely any solid ground.

**Comment by NillerMedDild** [comment]
This issue seems to be caused by YUNG's Better Caves. Not sure what to do about it just yet.

**Comment by Thiana** [comment]
In `bettercaves-1_16.toml`, maybe lowering`"Surface Cave Density" = 17` would help.

```			["Better Caves"."Underground Generation".Caves."Surface Caves"]
				# The minimum y-coordinate at which surface caves can generate.
				# Default: 40
				#Range: 0 ~ 255
				"Surface Cave Minimum Altitude" = 40
				# Set to true to enable vanilla-like caves which provide nice, natural-looking openings at the surface.
				# Default: true
				"Enable Surface Caves" = true
				# The maximum y-coordinate at which surface caves can generate.
				# Default: 128
				#Range: 0 ~ 255
				"Surface Cave Maximum Altitude" = 128
				# The density of surface caves. Higher = more caves, closer together. 
				# Default: 17
				#Range: 0 ~ 100
				"Surface Cave Density" = 17```

**Comment by NillerMedDild** [comment]
... Right that'll do it :P thanks!

**Comment by Shumaan** [comment]
Thanks mate!

**Comment by Shumaan** [comment]
Not an exhaustive test, but it looks like that did indeed help.
