### ISSUE TITLE
[Mod Suggestion] Mahou Tsukai

### ISSUE THREAD

**Issue by casteremrys** [NillerMedDild/Enigmatica6#81]
one of the only big magic mods other than botania on the newer versions and has nice aesthetic

https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai

**Comment by NillerMedDild** [comment]
I thought that mod would be meh if you didn't know the media reference, but looking reading it's description proves me wrong :P will definitely check it out.

**Comment by NillerMedDild** [comment]
It's gonna be a no, the overall feel I got was not good. And it has a dimension that's worse than the Twilight Forest in terms of lag :P

**Comment by casteremrys** [comment]
too bad really, the spells there are very unique (and pretty) compared to other magic mods. that dimension is a 1v1 combat spell so ppl dont go in there too often, and you can configure it to have less swords for less lag
