### ISSUE TITLE
[Client Crash] Latest Create (v0.3c) has an NPE for some users (not all)  

### ISSUE THREAD

**Issue by kil0byt3** [NillerMedDild/Enigmatica6#810]
**Modpack version**
Enigmatica 6 - 0.3.5

**Issue**
Only happens for some users - for me it's 1 out of 16. Just thought it might be good to track here, as that version of Create is in the latest E6 release. 

**Logs**
Linked issue on Create GH for reference https://github.com/Creators-of-Create/Create/issues/684

**Comment by kil0byt3** [comment]
https://github.com/henkelmax/easy-villagers/issues/32#issuecomment-756644178 

Describes the issue. Create devs need to fix :)

**Comment by NillerMedDild** [comment]
Do you have the crash report btw?

**Comment by kil0byt3** [comment]
Yes, oops: https://gist.github.com/kil0byt3/54fa2fdd25a98e032fc84ff7844898c6

It's more similar to the first issue I linked than the second in my comment, but according to the Create Discord they are all linked to the same cause (?)

**Comment by kil0byt3** [comment]
Fixed in https://github.com/Creators-of-Create/Create/commit/9d5ae97a0a517aff2958d3f8fb2ee827f5900358 

:)
