### ISSUE TITLE
World Map

### ISSUE THREAD

**Issue by NarghileEnjoy** [NillerMedDild/Enigmatica6#811]
**Modpack version**
6

**Issue**
'M' does not open world map.
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
I need the version of Enigmatica 6 please :)

**Comment by NarghileEnjoy** [comment]
![image](https://user-images.githubusercontent.com/72301200/104000753-74e08380-51ea-11eb-97bc-f2087e5a0337.png)

**Comment by Dasavanth** [comment]
did you check your keybinds? some other key might be using m and therefore conflicting with the map

**Comment by Merlo17** [comment]
You should try looking at that and also updating the pack to 0.3.5 and see if the issue persists

**Comment by theboo** [comment]
It had a keybind conflict for me in 0.3.3 when I fresh installed. I ended up just changing it since I don't use m anyway, but the conflict does keep it open (I don't remember what the conflicting bind or binds was for)

**Comment by NillerMedDild** [comment]
The default key conflict was fixed in 0.3.4 iirc :) If you have the issue, you will have to rebind it yourself though, sadly.
