### ISSUE TITLE
[Suggestion] Better End

### ISSUE THREAD

**Issue by Crackthebox** [NillerMedDild/Enigmatica6#812]
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice
https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port

First is just a nice magic mod and the other adds some end generation. I could not believe it was ported to forge.

**Comment by NillerMedDild** [comment]
first mod is a duplicate #275 
I'll have a look at the other one.

**Comment by Merlo17** [comment]
I've tested this in creative. At first I was a bit worried by the fact that it's a forge port of a fabric mod not done by the original author and by the disclaimer saying the mod is not done yet on the curse page. After trying it, it's honestly a resounding yes. It looks stunning and worked perfectly for me, and a lot of features already seem to be in place, and if there's more to come I'm all for it. I believe the pictures speak for themselves here.

https://imgur.com/a/4ONA2h9

**Comment by BlueDuckYT** [comment]
I have heard of some issues/world corruption w/ the way they register biomes, though.

**Comment by NillerMedDild** [comment]
Seems like BlueDuck is right, I will have a look at this mod later on :)

**Comment by Beethoven92** [comment]
> 
> 
> I have heard of some issues/world corruption w/ the way they register biomes, though.

BetterEnd does not corrupt the world, at least not in a way that i know (if you refer to end biomes spawning in the overworld when installing the mod in a world that was already generated, thats biome id shift, a plague that all world generation mods have). For sure it is not a finished mod though, and of course many things need to be improved, as you can see the content is huge and the original authors are working like crazy, so we are struggling to keep the pace. Anyway if you can provide example of world corruption or any issue related to biomes i will be very happy to look into those. Thank you

**Comment by NillerMedDild** [comment]
I was mostly worried about the biome shift issue, but I guess that is unavoidable, as you point out :)

> Anyway if you can provide example of world corruption or any issue related to biomes i will be very happy to look into how to solve them.

I can't, I got my information from your issue tracker, but most of those issues seem a bit invalid 😄

**Comment by Beethoven92** [comment]
So, chocolate fix mod could solve the biome id issue, and for example, i heard that BYG is now forcing the dependency to that mod. Regarding our past issues, many were solved in the last two betas, so i'd say the mod is pretty stable now. But still, BetterEnd remains a huge work in progress at the moment, i am not sure how many stuff the authors still plan to add but being in their discord development chat i can say what BetterEnd has right now in terms of content is just the top of the iceberg :D

**Comment by NillerMedDild** [comment]
We will not be adding more End Biome mods, BYG is plenty :)

**Comment by Beethoven92** [comment]
Its fine ;-) remember tough that in case you are interested in the endgame stuff of BetterEnd but not the biomes, all biomes can be individually disabled (things like portals will still spawn in all available End biomes)

**Comment by NillerMedDild** [comment]
Oh while I have you, you may want to add the 1.16.5 checkmark to the latest mod file of yours :)

**Comment by NillerMedDild** [comment]
I jumped the gun on this one, will investigate further :)
