### ISSUE TITLE
[Crafting Station] Cannot create the Crafting Station

### ISSUE THREAD

**Issue by sniggyfigbat** [NillerMedDild/Enigmatica6#815]
**Modpack version**
0.3.2

**Issue**
In JEI, the crafting station (from mod 'Crafting Station') has a recipe of one vanilla crafting table. However, in practice, a crafting table produces a simple crafting table. This probably indicates a recipe conflict.

![image](https://user-images.githubusercontent.com/3359069/104021091-1c8f8e80-51b6-11eb-877f-a0319ef4e5d9.png)

![image](https://user-images.githubusercontent.com/3359069/104021169-4052d480-51b6-11eb-9424-ac9558a2f91e.png)

**Comment by KrAzYGEEK32** [comment]
Update the pack, it fixes the issue. If you can't , for some reason you can make crafting station via a metal crafting table

**Comment by sniggyfigbat** [comment]
Shoot, forgot to remove 'is:open' from my search. This is a duplicate of #602.
