### ISSUE TITLE
[Mod Suggestion] Just Enough Calculation

### ISSUE THREAD

**Issue by telemenar** [NillerMedDild/Enigmatica6#816]
Often when trying to deal with a big expensive craft especially if I'm not super deep into automated crafting I find this mod to be super helpful to figure out resource gathering and the number of intermediate crafts that I need to do. Looks like they have a 1.16.4 update out so I can suggest them. 

https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation

**Comment by NillerMedDild** [comment]
While this is a pretty cool mod, I think the vast majority of players would not use it, so it's a no :)

**Comment by NillerMedDild** [comment]
I have been persuaded to look at this after all :)
