### ISSUE TITLE
Bits, from chisel and bits, wont place currectly

### ISSUE THREAD

**Issue by SpaceWyvern** [NillerMedDild/Enigmatica6#818]
**Modpack version**
0.3.5

**Issue**
The bits don't place where I put them. Video: https://streamable.com/651rxq

**Comment by NillerMedDild** [comment]
Thanks for the report, it has been reported here by someone else: https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/572

**Comment by NillerMedDild** [comment]
Are you using Optifine btw?

**Comment by SpaceWyvern** [comment]
> Are you using Optifine btw?

No

**Comment by NillerMedDild** [comment]
I made this report instead: https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/575
