### ISSUE TITLE
[Mod Suggestion] C.O.M.B.A.T

### ISSUE THREAD

**Issue by ghost** [NillerMedDild/Enigmatica6#82]
adds some weapons and magic stuff, pretty decent mod

https://www.curseforge.com/minecraft/mc-mods/c-o-m-b-a-t

**Comment by NillerMedDild** [comment]
Pretty decent? :P That's not a great sales pitch tbh.

**Comment by casteremrys** [comment]
it like lets you pick an affinity and you get a subset of the total spell so it adds a nice rpg feel

**Comment by NillerMedDild** [comment]
Based on the open issues on the mod's issue tracker this is a no :)
