### ISSUE TITLE
Investigate Nuclear Science

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica6#820]
https://www.curseforge.com/minecraft/mc-mods/nuclear-science

**Comment by drscience0912** [comment]
This looks promising and would love to see it in the pack someday. Or at least something like it. (I miss nuclear craft)

**Comment by NillerMedDild** [comment]
Me too 😞

**Comment by TemperedFool** [comment]
Hopefully this provides some hope long term:

https://youtu.be/ORo0V550ifA

**Comment by drscience0912** [comment]
This was very informative thank you

**Comment by NillerMedDild** [comment]
This will not be added.
To name a few reasons
- No in-game documentation of any kind
- No JEI integration for machines
- Functionality of the mod appears to be mostly in it's library mod Electrodynamics?
