### ISSUE TITLE
Switch Rail crashes Client - Enigmatica 6

### ISSUE THREAD

**Issue by TyroTheFox** [NillerMedDild/Enigmatica6#821]
**Modpack version**
Enigmatica 6 0.3.2

**Issue**
Looking at a placed switch rail from 'Transport' mod  when flicked on with a switch crashes the Minecraft client. Outright crash, client side, not server side.

1) Place rail and switch
2) Flick on switch (possibly switch again, unsure on how many times it was done)
3) Suddenly dead client

**Logs**
https://pastebin.com/TnQiJgMu

**Comment by scotty9090** [comment]
Had the same or similar issue, and also had it with Useful Rail's Holding Rail.  From what I can tell from the log, it seems like it is related to Quark's feature of linking carts together with chains (regardless of not linking any carts).  I tried disabling the feature in the Quark config but it still occurs. 

I just reported this on the Quark github here: https://github.com/Vazkii/Quark/issues/2854.  Please feel free to add your log / info if you want.

**Comment by RixMixed** [comment]
See #618 this issue has been resolved in Enigmatica 6 0.3.3 and up

**Comment by NillerMedDild** [comment]
Please update to 0.3.5 :)
