### ISSUE TITLE
Dimensional Shard Ore From RFTools & Enigmatica Both Generate

### ISSUE THREAD

**Issue by r-mc2** [NillerMedDild/Enigmatica6#822]
**Modpack version**
v0.3.4

**Issue**
Noticed the continued unification of ores under Enigmatica's banner and on a fresh End generation noticed both Dimensional Shards generating next to each other:
![MC-Enigmatica6-Dupilicate_Dimensional_Shard_Ore_ v0 3 4](https://user-images.githubusercontent.com/36780233/104078508-714dfc00-51ec-11eb-86d4-8a43c0cd90ed.png)
It's harder to see, but the RFTools ore is on the left, the faint white patch.

**Additional Info**
I can't see it affecting anything, but to note I have added the following mods to the pack:
* Cyclic-1.16.4-1.0.2
* JustEnoughResources-1.16.4-0.12.0.103 (was having trouble finding emeralds, but see you have the additional info page in JEI now, thanks!)
* SimplyJetpacks2-1.16.4-2.6.5.2

**Logs**
(N/A)

If this was addressed in a v0.3.5 or an upcoming update feel free to close.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It should be adressed in 0.3.5, I updated server configs incorrectly ^^'
