### ISSUE TITLE
Ore gen on Server not fully functioning

### ISSUE THREAD

**Issue by Laserman2** [NillerMedDild/Enigmatica6#825]
**Modpack version**
Enigmatica 6 - 0.3.5

**Issue**
Only when creating a world on a multiplayer server, the ore gen does not properly disable the ore gen from other mods. Only applies on servers, singleplayer appears to be functioning properly.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I'm not seeing this issue on my server, how did you install yours? :)

**Comment by Laserman2** [comment]
Yeah, this might have been more of a apex server issue. I tried to do a custom server on their website to use the beta version of E6, but it didn't seem to want to read the configs properly until I manually installed each file. I don't think its the server files themselves that are the issue. I'll probably report this later over on their site. Thanks for the response though.
