### ISSUE TITLE
Cannot place Animal Dictionary in Bookshelf

### ISSUE THREAD

**Issue by aharbis** [NillerMedDild/Enigmatica6#826]
**Modpack version**
0.3.5

**Issue**
Trying to insert an **Animal Dictionary** (from Alex's Mobs) into a Bookshelf (from Buildersaddition) does not work.

I can open the Bookshelf inventory and place other books in there, but the Animal Dictionary will not place into a slot.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Reported here: https://www.curseforge.com/minecraft/mc-mods/buildersaddition/issues/12

**Comment by RixMixed** [comment]
> Reported here: https://www.curseforge.com/minecraft/mc-mods/buildersaddition/issues/12
> 
> > **[Attention Required! | Cloudflare](https://www.curseforge.com/minecraft/mc-mods/buildersaddition/issues/12)**

FYI: looks like your report has disappeared and their issues tab now links to github instead of the curseforge issue tracker. https://github.com/mrh0/buildersaddition/issues
