### ISSUE TITLE
Mekanism Cardboard Boxes are not removed with shift right click.

### ISSUE THREAD

**Issue by dmitry-diolan** [NillerMedDild/Enigmatica6#827]
**Modpack version**
0.3.2

**Issue**
Mekanism Cardboard Boxes are not removed with shift right click.

I created the cardboard box and wrapped the drawer with it. I can break the box and get it into the inventory. It correctly writes that it contains the drawer. I can place the box back in the world, but I can't remove it with shift right click. I tried to use configurator without any success.

It seems there is now way to remove the cardboard box and release the entity that is wrapped. 

I've also opened the issued in Mekanism github - https://github.com/mekanism/Mekanism/issues/6858.

**Comment by Octr** [comment]
Drawers should be blacklisted as they retain their inventories already.

**Comment by dmitry-diolan** [comment]
The problem was with food in my off-hand. The off-hand should be empty. Sorry for bothering your.
