### ISSUE TITLE
Occultism is hard to get started with

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica6#829]
**Modpack version**
0.3.5

The new Strata seems to break Occultism's groves and other sources of otherstone, which normally spawn as Andesite (that we remove) but that can be turned into otherstone and mined after eating the demon fruit. Hit reported this on discord, so we should look into it, as it reportedly makes the mod near unusable because of the lack of resources.
Unfortunately I'm not too familiar with the mod so that's the best I can do, but they wouldn't post to github so I had to do it for them

**Comment by Merlo17** [comment]
https://media.discordapp.net/attachments/726178356143456287/797433504521650196/unknown.png

Image by him to show what the issue is

**Comment by MuteTiefling** [comment]
I think we should just make some easy recipes for other stone, honestly.

I think the trees are available in the market still, right?

The stone and trees are required to start the mod but depend on weird world Gen that's super rare even before the strata change

**Comment by NillerMedDild** [comment]
Completely agree, nice one Mute 👍
