### ISSUE TITLE
Create Windmill not working?

### ISSUE THREAD

**Issue by Fenris235** [NillerMedDild/Enigmatica6#830]
**Modpack version**
Enigmatica6 - 0.3.2

**Issue**
Building a Create mod windmill but it wont turn
Ive looked at as many youtube tutorials as i can find as to how to make one, im doing everything i see the tutorial explain, using all the right parts, ive even jumped into creative to try and troubleshoot the issue, but no matter what i try, the windmill wont turn.

**Comment by Merlo17** [comment]
Are you using an actual windmill block? They're now separated from the chassis you had to use in 1.15. The tutorials might be outdated, since the mod changed a bit when moving to 1.16

**Comment by Fenris235** [comment]
ahh that might be it, let me have a check
the lack of a guidebook within the create mod itself makes it complicated

**Comment by Fenris235** [comment]
> Are you using an actual windmill block? They're now separated from the chassis you had to use in 1.15. The tutorials might be outdated, since the mod changed a bit when moving to 1.16

ive got it working now, thank you for the help
