### ISSUE TITLE
Tetra quest tree is incorrect. 

### ISSUE THREAD

**Issue by sniggyfigbat** [NillerMedDild/Enigmatica6#831]
**Modpack version**
0.3.5

**Issue**
The Tetra questline is incorrect for the current progression path through Tetra - specifically 'the Forge'. The Forge hammer seems to require a tetra:forged_workbench not a regular one, and requires both power cells **and** two upgrades to function. As such, creating the forge hammer and thermal cells through the Enigmatica recipe is useless unless you've found upgrades and metal workbench.

As far as I can tell, this is a change from a recent Tetra update. Personally, I would appreciate it if Enigmatica could add recipes for upgrades and the workbench; finding a functional forge was extremely tedious (it took until our fifth forge ruin), and the 'make-your-own' route is much less unreliable.

**Comment by sniggyfigbat** [comment]
Update: I'm incorrect, you do not need the forged workbench, only a normal one. Also, you can make combustion engine upgrades comparatively trivially. What needs to be updated is the quest book, which doesn't explain that forges only work with 2 upgrades.

**Comment by NillerMedDild** [comment]
Alright, I wasn't aware of that change, thank you :)
