### ISSUE TITLE
Progression Skip/Vanilla Cobble Gen randomized

### ISSUE THREAD

**Issue by DocHuzz** [NillerMedDild/Enigmatica6#833]
**Modpack version**
0.3.5 Beta

**Issue**
When creating the bog standard vanilla cobble gen (Water and Lava), the created cobblestone is randomized.  It creates ANYTHING that is tagged cobblestone.  Undergarden, nether stuff, even blackstone.

Blackstone is a requirement for progression in Tetra and is meant to be taken after going to the nether for a T4 hammer and tools.  See video

https://www.youtube.com/watch?v=blw7T9gUCNo

**Comment by NillerMedDild** [comment]
Thanks for the report.

MuteTiefling removed the Blackstone from the list of stones that can be generated, and changed the block that needs to be under the generated block for the randomizing effect to occur.
