### ISSUE TITLE
[Optifine] Crash when opening video settings

### ISSUE THREAD

**Issue by jpie726** [NillerMedDild/Enigmatica6#84]
**Modpack version**
2.0.3

**Issue**
On MultiMC with OptiFine_1.16.1_HD_U_G2 added. Anywhere in Minecraft, try to go to video settings, it crashes
minimum memory: 1028 MB
maximum memory: 12096 MB
**Logs**
https://0bin.net/paste/0qJzToB28WqvOcFP#yHXgVTs4sn940xbgkQ0RTUV1Ein+R9aaddTyAM1Njxb
pastebin didnt work so I did this

**Comment by Darkere** [comment]
Disable Tip the Scales if you want to use Optifine.

**Comment by NillerMedDild** [comment]
I'm going to remove Tip the Scales in order to make Optifine viable.

**Comment by Darkere** [comment]
Tip the Scales now disables itself if optifine is detected.
