### ISSUE TITLE
[Mod Suggestion] Camera Mod

### ISSUE THREAD

**Issue by KangyKSLG** [NillerMedDild/Enigmatica6#843]
Can we get the camera mod for taking and displaying pictures in game please?

https://www.curseforge.com/minecraft/mc-mods/camera-mod

**Comment by NillerMedDild** [comment]
No, I don't think it really fits, sorry.

**Comment by KangyKSLG** [comment]
Fair enough :)

What exactly is the theme you're going for? Just so I can help suggest mods that fit

**Comment by NillerMedDild** [comment]
Not modern enough for cameras, I guess :P I don't have a good explaination other than a gut feeling, and the fact that more mods = heavier modpack to run. I'm gonna reject the majority of mods at this point tbh, so the pack doesn't become impossible to run a server for.

**Comment by KangyKSLG** [comment]
I understand haha. My server struggles with 5 people but that only has 6gb ram assigned to it
