### ISSUE TITLE
Guns without roses' sniper crashes other player's game

### ISSUE THREAD

**Issue by glubo** [NillerMedDild/Enigmatica6#846]
**Modpack version**
0.3.5

**Issue**
Whenever I take a diamond sniper (Impact IV, Unbreaking III) into my hand, other player's client crashes while trying to render my character. Interestingly enough, it does not work other way around (when he takes it in hand and my client tries to render it).

Crashing client is on nvidia gpu and windows, non-crashing client is on linux and amd gpu.

**Logs**
https://gist.github.com/glubo/cffd75507ed2065d4bf83e8a06a5b0e0

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Is the log you linked his crash report?

**Comment by glubo** [comment]
Yes, that is his crash report, but I have took second look on it and it looks like his installation has some underlaying severe issues. So this is quite possibly just random consequence of that.

This spam before the crash seems like serious installation problem.
```
[16:16:23] [ForkJoinPool.commonPool-worker-31/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: software.bernie.shadowed.fasterxml.jackson.databind.Module
```

Sorry for taking your time with probably irrelevant issue. Will try to work out this issue with him first, but feel free to close this issue as invalid before that.

**Comment by Merlo17** [comment]
If you want some pointers, having Java 11 can possibly cause some issues, as modded expects you to have 8. I'll close it for now but feel free to reopen it if you have news and need more help ^^

**Comment by Darkere** [comment]
I have seen this crash reported on Discord as well, however the player didn't know what caused it.

Something with backpack tools. From what I saw it was conflicting with @Buuz135 's  Seals player render.

**Comment by glubo** [comment]
It looks like the problem is gone after replacing jdk 11 with jdk 8, as Merlo pointed out (thanks).
