### ISSUE TITLE
[Suggestion] Macaw's Furniture was recently ported to 1.16

### ISSUE THREAD

**Issue by willbattel** [NillerMedDild/Enigmatica6#848]
The final piece of Macaw's suite has been released for 1.16. As an alternative to #203 and knowing the quality of Macaw's mods, as well as E6's lack of furniture, I suggest its addition to the pack.

https://www.curseforge.com/minecraft/mc-mods/macaws-furniture

**Comment by Ridanisaurus** [comment]
Curious if they have the same amazing hitboxes as the Bridges and Windows, or the same non-matching textures of wood, or whether he addressed some of these issues. 
I noticed that he didn't in the other mods, so I don't expect him to have touched these either.

**Comment by NillerMedDild** [comment]
Last time I used Macaw's Furniture it was very very unpolished, I'd rather not add it to be honest.

**Comment by willbattel** [comment]
Fair. Do you have any plans for furniture? That is the one thing from the building category of E6 that my friends and I have been missing. It looks like MrCrayfish is still working on getting a stable 1.16 release, is that still being considered?

**Comment by NillerMedDild** [comment]
Well we do have EmbellishCraft and Builder's Crafts and Additions.

MrCrayfish will be considered once it gets a stable release :)
