### ISSUE TITLE
profile backup in the main update?

### ISSUE THREAD

**Issue by LunaDoll** [NillerMedDild/Enigmatica6#849]
will there be a transfer of any items to the new main update on the official Enigmatica 6 server, or should I wait and start playing with the new version 4.0?

**Comment by Merlo17** [comment]
Probably not, but also the next big update is likely at least a month away, so I wouldn't worry much about it

**Comment by NillerMedDild** [comment]
Yeah sorry, I don't have time to help with that at least :(
