### ISSUE TITLE
Locking a villager's trades with item routers

### ISSUE THREAD

**Issue by SpaceWyvern** [NillerMedDild/Enigmatica6#853]
**Modpack version**
0.3.5

**Issue**
Item routers can lock the player from trading with a villager. The trades can be unlocked by reloading the world. This has been tested in single player

Video:
https://streamable.com/3nh4vz

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
This is so incredibly edge case, I'm not sure it's worth relaying tbh :P

**Comment by Darkere** [comment]
Hmm do report it. That it doesn't start working afterwards is worrying and could mean other bugs could be caused by this.
