### ISSUE TITLE
[Enhancement] Advanced Hook Launcher

### ISSUE THREAD

**Issue by XLuma** [NillerMedDild/Enigmatica6#857]
Link: https://www.curseforge.com/minecraft/mc-mods/advanced-hook-launchers

Could be a really fun addition for exploring. Access in early stages of a playthrough, recipes are not overly expensive,.. I can see this in the modpack :)

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by NillerMedDild** [comment]
I tested this out and had a lot of fun to be honest, I think many people will enjoy this addition :D

**Comment by XLuma** [comment]
Hell yes, can’t wait for the .7 !
