### ISSUE TITLE
[Suggestion] The Outer End

### ISSUE THREAD

**Issue by mikehoyle** [NillerMedDild/Enigmatica6#858]
A new mod compatible with 1.16.4.

Link: https://www.curseforge.com/minecraft/mc-mods/the-outer-end

Based on the reddit post is compatible with other End mods in the pack: https://www.reddit.com/r/feedthebeast/comments/kv3lck/announcing_the_outer_end_an_end_expansion_mod

**Comment by NillerMedDild** [comment]
Duplicate of #620
