### ISSUE TITLE
IF breakers can break anything

### ISSUE THREAD

**Issue by SpaceWyvern** [NillerMedDild/Enigmatica6#859]
**Modpack version**
0.3.5

**Issue**
I have already made a report on IF breakers being able to mine naturally spawned Astral collection crystals, but they are able to mine any block in the game, not all blocks are collected but all are broken.

![2021-01-12_12 05 12](https://user-images.githubusercontent.com/76791096/104300715-81f1c100-54cf-11eb-94ef-0004273a727d.png)
![2021-01-12_12 12 19](https://user-images.githubusercontent.com/76791096/104300718-8322ee00-54cf-11eb-818d-2e1f065c0e8e.png)

**Comment by MuteTiefling** [comment]
Think Buuz already got this one: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/936
