### ISSUE TITLE
Description: Initializing game

### ISSUE THREAD

**Issue by TheKingOmar** [NillerMedDild/Enigmatica6#862]
**Modpack version**
Input modpack version here
1.16.4
**Issue**
Input short description of the issue here
Initializing game
**Logs**https://pastebin.com/uApMaqK1
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report - It looks like Optifine crashed your game on startup, I suggest you try removing it.

Also, I see you're using outdated java, which can cause severe issues, please see this guide on how to set your game to use newer java:
https://gist.github.com/NillerMedDild/40b4992b7a3e5e653a353fe1d45f2185

**Comment by TheKingOmar** [comment]
> Thanks for the report - It looks like Optifine crashed your game on startup, I suggest you try removing it.
> Edit: Please let me know if it helps or not.
> 
> Also, I see you're using outdated java, which can cause severe issues, please see this guide on how to set your game to use newer java:
> https://gist.github.com/NillerMedDild/40b4992b7a3e5e653a353fe1d45f2185
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e249f005c9359542c16b3dc40dbe3e950c23c49a86601d5d2461a59834675446/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> Gist**[Setting up the modpack.md](https://gist.github.com/NillerMedDild/40b4992b7a3e5e653a353fe1d45f2185)**GitHub Gist: instantly share code, notes, and snippets.

First thanks for quick reply and yup after i removed optifine the game seems to load and i will update my java version too

**Comment by NillerMedDild** [comment]
Awesome, I hope you'll enjoy the pack :D
