### ISSUE TITLE
Emerald generation in 0.3.5 baseline 156?

### ISSUE THREAD

**Issue by Marxone** [NillerMedDild/Enigmatica6#863]
**Modpack version**
0.3.5

**Issue**
0 Emeralds found in new chunks, emendatus config says Emerald baseline = 156

Hi, 
I was wondering why I haven't found a single emerald regardless of biome post my 0.3.5 update and I went through configs and emendatus has baseline for Emerald in overworld set to 156 - not even tallest mountains I found have this height. 
Is this intentional?

**Comment by Merlo17** [comment]
@Ridanisaurus probably knows more about it

**Comment by Marxone** [comment]
I might have wrong idea, but the baseline seems to be the height on which it can generate - meaning that Emeralds now have to be generated only on top of tallest mountains. It was changed in the changelog in 0.3.5 "to increase generation of emeralds in the mountains".

Previous value 96 actually caused them to generate on surfaces rather than in depths (i started my world on 0.3.3) .
I would get restricted generation if the purpose behind the decision was to use Villagers to get them. Might not be bug.

**Comment by NillerMedDild** [comment]
Baseline 156 and spread 56 means it can generate between 100 and 212, so tall mountains - This change is intentional :)
