### ISSUE TITLE
Buried Dungeons spawning in the End?

### ISSUE THREAD

**Issue by lamb3664** [NillerMedDild/Enigmatica6#866]
**Modpack version**
0.3.5

**Issue**
In my 0.3.5 world, I was travelling the End and found a Buried Dungeon, which normally only spawns in the Overworld. This area does not have any maps to additional dungeons (like Buried Dungeons normally do), and it spawns overworld mobs. I'm pretty sure this is a worldgen glitch.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report.

Hmm, that shouldn't be possible :s It was a Buried Dungeon from Dungeons Plus I take it?

**Comment by NillerMedDild** [comment]
Right, it seems to have been an issue with Dungeons Plus, 0.3.6 should resolve it when it's out :)
