### ISSUE TITLE
RFTools spawner

### ISSUE THREAD

**Issue by Arthua1** [NillerMedDild/Enigmatica6#868]
**Modpack version**
Input modpack version here

**Issue**
Input short description of the issue here

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Arthua1** [comment]
Hi
Don't know is it issue or "future" but spawner from rftools doesn't show ingredients/items and amount RF to spawn.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It works now, version 0.3.13 :)
