### ISSUE TITLE
Crash when attempting to load certain chunks

### ISSUE THREAD

**Issue by dixonw2** [NillerMedDild/Enigmatica6#869]
**Modpack version**
0.3.5

**Issue**
I've had a few instances where moving and loading presumably new/unloaded for a while chunks will freeze the game for about 10-15 seconds before crashing. 

**Logs**
https://pastebin.com/SCCua4CD

**Comment by NillerMedDild** [comment]
Thanks for the report!
duplicate of #813 though.

**Comment by dixonw2** [comment]
> Thanks for the report!
> duplicate of #813 though.

Oh sorry hadn't seen that, my bad! Glad you're aware!
