### ISSUE TITLE
Additional Apiary Glass Types

### ISSUE THREAD

**Issue by amateil** [NillerMedDild/Enigmatica6#871]
**Modpack version**
0.3.5

**Issue**
Resourceful Bees - Apiary
Can only use normal or connecting glass, I would love to be able to use it with ethereal glass / other glass types

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
fixed in #839 :)

**Comment by NillerMedDild** [comment]
Woops wrong link, https://github.com/NillerMedDild/Enigmatica6/commit/9989a6433d14c806a366372ecfdd9edfecfb82c1

**Comment by MelanX** [comment]
Don't work in 0.3.6.
I made an Apiary with Mana Glass - not working.I made an Apiary with Ethereal Glass - not working.
I think it's because only the items do have the tag and not the blocks itself?
