### ISSUE TITLE
Incompatiblity with Powershell on Linux

### ISSUE THREAD

**Issue by NamesAreAPain** [NillerMedDild/Enigmatica6#873]
**Modpack version**
0.3.5

Due to case sensitivity on POSIX systems, the lower-case version of the mod filepaths do not find the appropriate mod files when using powershell on linux. 

This problem is easily solved by replacing the
```powershell
Remove-Item "$Modfolder/$Mod" -Force
```
with
```powershell
Remove-Item "$Modfolder/$_" -Force
```
in remove-client-mods.ps1. 

Besides that, the only other incompatible script is the update-and-start-server.ps1 script, which I've editted to use bash to launch start-server.sh, but there could be another solution I haven't considered.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get that fixed.
Would you mind supplying your edit of `update-and-start-server.ps1` please? I'll include that as well :)
