### ISSUE TITLE
Painting create a visual glitch

### ISSUE THREAD

**Issue by SpaceWyvern** [NillerMedDild/Enigmatica6#876]
**Modpack version**
0.3.5

**Issue**
When looking at a painting and opening inventory, makes inventory not have UI, only items

Video:
https://streamable.com/rf8kdl
https://streamable.com/11154l

**Comment by Darkere** [comment]
Can you check this from further away? This looks like it might be an error in The One Probe

**Comment by SpaceWyvern** [comment]
> Can you check this from further away? This looks like it might be an error in The One Probe

From further away one probe starts appearing and it works fine, but from close up one probe vanishes and it starts glitching

**Comment by SpaceWyvern** [comment]
Even the minimap dissapears

**Comment by SpaceWyvern** [comment]
> **Modpack version**
> 0.3.5
> 
> **Issue**
> When looking at a painting and opening inventory, makes inventory not have UI, only items
> 
> Video:
> https://streamable.com/rf8kdl

`

**Comment by SpaceWyvern** [comment]
Here is a better video:
https://streamable.com/11154l

**Comment by NillerMedDild** [comment]
It has been reported here: https://github.com/McJtyMods/TheOneProbe/issues/440
