### ISSUE TITLE
No Recipe For Mekanism Tanks

### ISSUE THREAD

**Issue by Pie101504** [NillerMedDild/Enigmatica6#878]
**Modpack version**
0.3.2

**Issue**
Jei won't show mekanism tank recipe, and unless the recipe was changed the original recipe does not work.

**Comment by MuteTiefling** [comment]
This isn't an issue in 0.3.5 at least. And I'm guessing that your pack is missing some files or didn't load up properly. I saw at least one other person on Discord have a similar issue where tags weren't loaded properly. For instance, if you look at Iron Ingots, you should see an extra tag of `ingots/iron_aluminum` which that recipe is looking for. 

If you can attach your Latest.Log that would confirm it, but simply redownloading the pack will likely correct the issue.

**Comment by tatehaga** [comment]
update your server scripts

**Comment by MuteTiefling** [comment]
@Pie101504 Along with the latest.log, could you please let us know how your server is hosted? Assuming this is a server, that is.
