### ISSUE TITLE
Server crash after flying with paraglider over newly generated chunk

### ISSUE THREAD

**Issue by dan1707** [NillerMedDild/Enigmatica6#882]
**Modpack version**
0.3.5

**Issue**
Our server crashed when I flew over a newly generated chunk with a paraglider in my hand.
Now the server crashes all the time when I try to login after starting it again.

**Logs**
This is the log when I try to login.
https://pastebin.com/PWXNVNiS

This is the log when the server crashed for the first time.
https://pastebin.com/HF7s4Eyi

**Comment by Darkere** [comment]
You should be able to fix this by removing the tnt minecraft causing the issue using Nbt explorer.

Here's a guide on how to do that: <https://gist.github.com/Darkere/9e2ebda80a92a91d9257cfc2bcc016a5>

Worst case you could also move your player away using that method. 


@Ridanisaurus any ideas? Tnt Minecraft running over redstone. But the redstone isn't there yet?

**Comment by dan1707** [comment]
Thanks @Darkere !
But I wasn't able to follow the guide as the affected chunk was never saved in the region file. It seems to be that server is crashing when generating  the chunk.
The only way to "fix" it was to set myself to other coordinates and clean the affected region.
Hopefully no other member of the server will wander into this region until this bug is fixed ;)

**Comment by GeoTerra** [comment]
Just wanted to chime in and say that I seem to be running into the same issue (https://pastebin.com/JziFfBH0), a TNT Minecart running over Redstone Ore, except the chunk is question is generated and is crashing when I try to enter the chunk. I have attempted the fix from above and it has worked. I am able to enter the chunk in question. Thanks for that!
