### ISSUE TITLE
Unconfigurable forge dictionary data in inventory tooltips

### ISSUE THREAD

**Issue by IceCaps97** [NillerMedDild/Enigmatica6#885]
**Modpack version**
0.3.2

**Issue**
Inventory tooltips have extra forge dictionary data listed for all items and blocks. There does not seem to be an option to disable or configure this behavior when looking through the inventory mod configs.

![image](https://user-images.githubusercontent.com/959377/104494061-f302a880-55a3-11eb-9ad0-71dcf2c05e43.png)

![image](https://user-images.githubusercontent.com/959377/104494505-889e3800-55a4-11eb-9be8-7518a7188436.png)

**Comment by Darkere** [comment]
Press F3 + h.

**Comment by IceCaps97** [comment]
> 
> 
> Press F3 + h.

Ah, previously I was trying that when the inventory was open. Looks like it has to be closed for it to toggle. Thanks for the help.
