### ISSUE TITLE
How do I get rid of the green text to the right of my screen?

### ISSUE THREAD

**Issue by FruitPom** [NillerMedDild/Enigmatica6#887]
I'm on Engimatica 6 and I did something now I have these items in green text to the right of my screen and its just being annoying clutter. I'm sure this is an easy fix. 
![green](https://user-images.githubusercontent.com/77417618/104520664-7da9ce80-55c9-11eb-8216-878cb6eaa9aa.PNG)

**Comment by MuteTiefling** [comment]
Go find those quests again and click the pushpin in the upper right corner.
