### ISSUE TITLE
Bug with Quantumstorage

### ISSUE THREAD

**Issue by ImParadocks** [NillerMedDild/Enigmatica6#888]
Have fun while you can boys, sorry if this has been already reported, I looked but didn't see anyone else. 
**Modpack version**
0.3.2

**Issue**
Multiplying items in multiplayer with Quantumstorage crates while breaking the crate while someone is still in the inventory. Works with any crate.

(was TOTALLY NOT abusing it here AT ALL): https://user-images.githubusercontent.com/77418462/104525454-35d97600-55ce-11eb-9fad-7bfa2aa1a0d3.mp4

NillerMedDild: Edited slightly to limit searchability for this type of issue.

**Comment by NillerMedDild** [comment]
Thanks for the report, that totally non-cheaty video is very helpful!

Reported here: https://github.com/gigabit101/QuantumStorage/issues/239
