### ISSUE TITLE
Smoker displays misleading animation with Resourceful Bees Hives

### ISSUE THREAD

**Issue by Zosu** [NillerMedDild/Enigmatica6#892]
**Modpack version**
0.35

**Issue**
The smoker displays a misleading particle effect when used on a resourceful bee hive where it shows the smoking particles when shift right clicked on a bee hive while hive isn't actually smoked. Just standard right clicking on a bee hive does smoke it, but it doesn't display the smoking particles.  

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
