### ISSUE TITLE
No recipe for adjustable chain gearshift

### ISSUE THREAD

**Issue by SpaceWyvern** [NillerMedDild/Enigmatica6#893]
**Modpack version**
0.3.6

**Issue**
adjustable chain gearshift doesn't have a recipe. JEI doesn't come up with anything upon trying to check how to make it.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by clienthax** [comment]
Same for sequenced gearshift

**Comment by MuteTiefling** [comment]
Think I've figured this out. It's the regex gear recipe removal. Should be able to limit the regex match by adding a $ to the end. Will test in a bit.

**Comment by NillerMedDild** [comment]
Nice catch!
