### ISSUE TITLE
[0.3.6] Create Crushing Wheels eat sandstone don't make sand

### ISSUE THREAD

**Issue by telemenar** [NillerMedDild/Enigmatica6#894]
**Modpack version**
0.3.6

**Issue**
JEI shows a recipe for making sand from sandstone in the Create Crushing Wheels, they instead just eat the sandstone and don't emit anything.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
Been testing this and cannot reproduce. I put a stack of sandstone in and get a stack of sand out.

**Comment by telemenar** [comment]
Huh, I fed in 4 stacks last night and got nothing... Trying today it worked fine...
