### ISSUE TITLE
Duplication bug for Buildersaddition

### ISSUE THREAD

**Issue by useenzhekoay** [NillerMedDild/Enigmatica6#896]
**Modpack version**
0.3.6

**Issue**
Duplication bug for Buildersaddition's redstone comparator and repeator when place at side.

**Logs**

**Proof**

https://user-images.githubusercontent.com/5300396/104733696-0ebfa780-577a-11eb-9a0a-fad70c2129ac.mp4

**Comment by Larandar** [comment]
Notable in that video is also that comparator can no longer be used to activate Redstone control on spawner. 

I suspect the 2 are linked, do you want that I open another bug report for that?

**Comment by useenzhekoay** [comment]
> Notable in that video is also that comparator can no longer be used to activate Redstone control on spawner.
> 
> I suspect the 2 are linked, do you want that I open another bug report for that?

Still able to use it by standing on top of the spawner and use the comparator.

**Comment by Larandar** [comment]
Indeed, just tested it, can't do anymore from the sides (possible in 0.3.5 and 0.3.4) but it work if clicked on the top

**Comment by NillerMedDild** [comment]
Interestingly enough, these do not appear to be in the mod anymore?

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/mrh0/buildersaddition/issues/19
