### ISSUE TITLE
It is impossible to pick up supplementaries safe even if it is yours

### ISSUE THREAD

**Issue by SpaceWyvern** [NillerMedDild/Enigmatica6#897]
**Modpack version**
0.3.6

**Issue**
It is impossible to pick up the safe even tho I was the one who placed it and Im in singleplayer.

Video:
https://streamable.com/8pwpjo

**Comment by MuteTiefling** [comment]
I'm able to reproduce this. 

1) Place new safe
2) Pick up Safe with pick
3) Place safe again
4) Attempts to break now state it's owned by MuteTiefling

**Comment by MuteTiefling** [comment]
https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/21

**Comment by MehVahdJukaar** [comment]
I'll fix this as soon as possible. For now remember you can unlock a safe using a tripwire took

**Comment by Porcy** [comment]
I have this exact problem in Enigmatica 6 Expert. Supplementaries 0.18.4 seems to be the last for 1.16.5 :(

**Comment by Quezler** [comment]
If the contents aren't important to you you might be able to get rid of it with the setblock command 🤔

**Comment by Porcy** [comment]
There is nothing in it. I can open it, 'cause it's mine. It just wont let me pick it up. Setblock is an option. I would have tried using the exchanging gadget but I'm affraid it could corrupt something, if it works at all. But, as modpacks in 1.16.5 are getting more and more popular and numerous, I'd suggest correcting this bug in the 1.16.5 version. I know it's a lot of work to maintain many versions, but as of now and for the foreseable future, there won't be a lot of packs for 1.18+
