### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by JustLiam040** [NillerMedDild/Enigmatica6#9]
This isn't really an issue but more of a question, i cannot seem to find the answer on the mod page; I understand this is a very very early build of this pack and as such multiple features etc will be missing/not implemented. I was just curious as to whether there are any plans to make an expert mode of this mod pack when the number of mods for 1.16 increases! 

As mentioned, i understand this feature will not be in the works for quite some time considering the small amount of mods out for 1.16 and the huge amount of effort involved in creating a game mode of such volume

**Comment by NillerMedDild** [comment]
We hope 1.16 will remain "active" for long enough for us to make an Expert pack, but we cannot make any promises sadly :)
