### ISSUE TITLE
ResourcefulBees getting stuck in apiary walls

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica6#900]
**Modpack version**
0.3.6

**Issue**
Larger bees (Ghast and Oreo) seem to get stuck in the Apiary wall when they exit the apiary block and take suffocation damage (and eventually die).  They also sometimes pop to the outside of the apiary enclosure due to getting stuck in the wall. I dont remember this happening in 0.3.5, but cant confirm at this time.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Mod author's response: 
> This one is going to take some finessing to figure out a good solution. The bees should be spawning in the block space directly in front of the apiary entrance so I’m a bit curious how/why they are getting stuck in walls. Thank you for letting me know

Do you have any additional info to provide that might help him out? :)

**Comment by Dracos99** [comment]
I am not sure about the Oreo bee size, since it is an easter egg bee and i dont see a config file for it, but it is larger than a normal bee...maybe 1.5 size?  The Ghast bee has a size modifier set to 2 in the config making it very large and may be contributing to the clipping.
![image](https://user-images.githubusercontent.com/46051093/104981450-4030b100-59ce-11eb-86d8-c06716961673.png)
