### ISSUE TITLE
World/Server crashes w/ dark vex from Dark Egg & PneumaticCraft

### ISSUE THREAD

**Issue by DatBanana32** [NillerMedDild/Enigmatica6#903]
**Modpack version**
0.3.6

**Issue**
Basically, if you have a dark vex that is spawned from the dark egg trinket. If you accidentally trap it in a spawner core from Pneumaticcraft: Repressurized and then release it, it'll crash the world. I did this because I was trying to make a creeper spawner but one of the vex got near my vacuum trap, so I tried to get rid of it by right-clicking blocks with the spawner core to empty it and then the world crashes.

**Logs**
Game itself does not crash but the world does, so I do not have any logs.

**Comment by MuteTiefling** [comment]
Taking a look now. Should be a simple fix :D Thank you!
