### ISSUE TITLE
Refined Obsidian is unbalanced

### ISSUE THREAD

**Issue by telemenar** [NillerMedDild/Enigmatica6#907]
As armor particularly but also as a Tetra material. 

As armor for the chest plate it has:
12 Armor 4 Armor Toughness

There is nothing else in the entire pack with even 10 armor, and only 1 other armor in the pack has toughness 4 which is icesteel which comes with a significant downside of slowness. 

On top of that the close competitors to refined obsidian are things like Alfsteel which to make a set requires a huge amount of mana which would need a huge amount of time and resources. On the other hand refined obsidian you could get your hands on enough to make an armor set very very quickly. Starting from nothing you need:
6 Obsidian
6 Diamonds (including 3 to mine the obsidian, only 3 needed to actually make it)
6 Gold (for a windmill for power)
34 Redstone (includes using some redstone for power from before you have the windmill)
36 Iron (including the iron to make the pickax to mine the diamonds)
35 Osmium 
9 Coal (for making steel)

Some logs, some cobble, some food. (Probably extra coal for torches too -- though I suppose if we are going minimal you could get away with extra logs for charcoal for torches instead.)

Once you have the resources it only takes 20 minutes or less to tech tree up to getting your 24 refined obsidian ingots. And if you got only slightly lucky with a low y level cave or chasm you could get those resources from nothing in less than an hour. The hardest part is actually the osmium but even that isn't that hard. 

And for another 8 ingots all you need is:
1 Diamond
2 Obsidian
8 Osmium

Similarly in Tetra materials, unless you are optimizing for very specific attributes only 2 other materials in the pack (Gaia Ingot, Alfsteel) have the same damage level and nothing has better. After this the next 2 closest are Refined Glowstone (at least you have to had progressed to the nether) and Enderium.

**Comment by NillerMedDild** [comment]
Thanks for the feedback, we'll dial it down :)

**Comment by TemperedFool** [comment]
I would suggest the tools are also overpowered, for the same reasons. Why fuss with Tetra when you can just make a refined obsidian paxel?

I wonder if maybe you can gate the heck out of the osmium compressor? I'm not sure that gating back refined glowstone with it is an issue for anything, really.

**Comment by NillerMedDild** [comment]
I don't want to gate intended mod progression in normal mode, that should be limited to Expert imo.

**Comment by Figulus88** [comment]
Since we're talking about it, the previous nerfings of Refined Obsidian Tools were overdone in one case, a Refined Obsidian Hoe does -4 damage.
