### ISSUE TITLE
QuantumStorage doesn’t retain inventory on upgrade 

### ISSUE THREAD

**Issue by adh1310** [NillerMedDild/Enigmatica6#908]
**Modpack version**
Enigmatica 6 0.3.6

**Issue**
QuantumStorage crates don’t retain inventory when upgraded to different tiers. Is this something that can be added to the quest book notes for the tree to make people aware before they upgrade? Just lost a bunch of stuff because of the issue. It’s even referenced on the mod authors repo but he closed the issue in August but it doesn’t look like it was resolved: https://github.com/gigabit101/QuantumStorage/issues/133

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Skar78** [comment]
Is that mod still neded now that IF has the blackhole storage options? (Did not test them tho.)

**Comment by NillerMedDild** [comment]
@Skar78 Not at all, nice catch ty!
