### ISSUE TITLE
Mod suggestion: Lootr

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica6#911]
[Curseforge page](https://www.curseforge.com/minecraft/mc-mods/lootr)

This awesome mod just got updated to 1.16+. It makes loot chests in generated structures to behave a bit like ender chests, making each player able to receive their own loot from the same generated loot chest. It's amazing in big servers (even if it's maybe too late for the current public server but should be in time for newly found structures or if the server world needs another reset).

The 1.16 release is brand new and is marked as alpha, and so may have some issues, but still amazing mod that would make big servers even more enjoyable.

**Comment by NillerMedDild** [comment]
Will add once it moves into beta/release :)

**Comment by Lykrast** [comment]
It just moved into a beta, just to let you know.
