### ISSUE TITLE
[Suggestion] Create Integration (Rotation -> FE)

### ISSUE THREAD

**Issue by sniggyfigbat** [NillerMedDild/Enigmatica6#914]
Past a certain point, Pneumaticraft and Create content just isn't worth integrating into large bases because each requires an entirely separate power infrastructure to literally everything else.

A good way to fix this would be to have an electric motor block to turn RF into torque and an electric compressor to turn RF into pressure. In order to preserve the original progression of the mods, the recipes for these should require resources/capabilities only available through normal progression (so they should probably require the Create mechanical crafters and the Pneumaticraft assembly machine, respectively).

**Comment by TemperedFool** [comment]
PN:R already has an electric compressor that runs on RF, so half your issue is solved 😉

For Create, I personally don't want it ruined by this kind of thing, but I can also choose not to craft it. If anything, I want a Furnace Engine that can just run all the time without actually producing anything but torque, but that's an issue for the mod creator ^_^

**Comment by Merlo17** [comment]
https://www.curseforge.com/minecraft/mc-mods/create-integration

this was suggested for create back in E5 and I still think it would be a very cool addition. Personally I would even disable FE->Rotation, but I definitively want Rotation->FE. The other gadgets also look like they could be interesting to have, especially the ender crate

**Comment by TemperedFool** [comment]
That looks awesome; I also personally agree that disabling RF -> rotation is what I would do, but tbh that may be more about the RF power in the pack needing balancing ^_^

**Comment by sniggyfigbat** [comment]
For anyone finding this at a later date, the Pneumaticraft item that fills this role is the 'flux compressor'; I'd somehow missed it.

**Comment by Merlo17** [comment]
Just having the option to go full create would be very cool imo, I would totally jump on that. It needs to be balanced so that we're sure that it's viable for sure though

**Comment by sniggyfigbat** [comment]
The option to go full Create would indeed be nice, but the reality is that almost all mods use RF, and if my options are to build a Create base with RF stuff inefficiently spliced in, or build an RF base with literally everything else working as intended, I'd always go with the latter. Which is a shame, because I'd really like to be able to splice Create stuff in.

**Comment by sniggyfigbat** [comment]
Alternatively, might it be possible to implement a create generator that runs off Mekanism biofuel?

**Comment by Merlo17** [comment]
I don't really understand your point too well, the mod I linked gives options to have create rotation generate RF, so the whole base could effectively be powered by create. My issue with being able to use FE to power Create is that you would end up "cheating" the mod and break the intended progression, it would just feel out of place for me, since the entire point of the mod is build huge fun contraptions powered by rotation, and being able to make it from power would be a bit underwhelming and unbalanced for me

**Comment by MuteTiefling** [comment]
Here's the problem...

With Immersive Engineering, you can run the furnace engine for about 7 rf/t.

That's a high stress engine that can be sped up easily by using a speed controller.


No matter how much you tweak the rotation to Rf conversion, this is just silly. Sure, you can probably majorly nerf the External Heater that's enabling this, but then it becomes useless for its intended purpose.

Similarly, PNC can run a furnace engine with a vortex tube given a steady 0.5 bar of pressure. That's pretty darn cheap. Again, it could be nerfed to prevent a power loop, but at the risk of making PNC unplayable.

The idea of the mod is neat, but it's just impossible to balance here. You either get free infinite power loops, or you break other mods.

**Comment by TemperedFool** [comment]
Oooh, so even if you can only convert rotation -> RF, your simple loop example is:

IE Windmill -> External Heater (~7rf/t) powering Furnace Engine -> lots of rotation into CI torque:RF block -> more than 7rf/t out.

Given the already noted kinda-broken nature of RF power in the pack, this doesn't seem terrible, but is one example and could be even worse. But I'll say, it seems pretty Rube Goldberg when you could just make a basic Powah reactor ^_^

Maybe it's worth playing with it to see what other things you could loop, how unbalanced they are, and how they could fit into a balanced power structure?

**Comment by MuteTiefling** [comment]
That basic Powah reactor requires fuel at least.

Most of the easy, free power things tend to be low output. Windmills, Powah heat or solar gens, etc. If this system were to be at all useful however, it would need to be comparatively high output. Like, if you want to run some thermal machines with it, it needs to be able to produce a few hundred Rf per tick. Maybe even a few thousand.

If you can freely convert 7 Rf/t to 1000 rf/t with a small contraption (and the ie method is tiny), people will.

However, even without this mod, it's easy to pretend this is happening. Just the other day I was planning out a big moving thing that would look a bit like an industrial centrifuge with create. Of course, create can't handle that type of recipe, so it was going to just have a hidden thermal centrifuge inside that did all the work. But the façade would have been integral to getting stuff in and out of that machine. Power would've been fed in wirelessly so the end result would like create is doing it all.

**Comment by NillerMedDild** [comment]
I don't see any way to get this properly balanced, as Mute points out. I'd like to keep the infinite loop generation options as few as possible :P
