### ISSUE TITLE
Mod Suggestion: Jousting

### ISSUE THREAD

**Issue by biskygoat** [NillerMedDild/Enigmatica6#915]
My friends and I were playing with this one yesterday: https://www.curseforge.com/minecraft/mc-mods/jousting

Basically you and a friend charge at each other with these lances. each lance has like a weight that lets you charge for longer if it's less weight (and goes on cooldown when you finish charging), and then some calculation is done involving how fast you were going and the damage of the lance, and whoever loses gets thrown off their mount. And if you run out of charge time, you lose by default cause the other guy was charging and you weren't.

Even in SP you can run around and smash into stuff and knock skeletons off their spiders. Its actually really fun

**Comment by Merlo17** [comment]
That seems a bit weird to me. I'm not really sure if it has a place in a pack like this. We'll see what Niller thinks though ^^

**Comment by NillerMedDild** [comment]
It does sound like fun, but I don't really think it fits in to be honest.
