### ISSUE TITLE
Tetra crash/freeze when placing forge hammer

### ISSUE THREAD

**Issue by HorribleNerd** [NillerMedDild/Enigmatica6#916]
**Modpack version**
0.3.6

**Issue**
Placing a Tetra Forge Hammer on another Forge Hammer crashes/freezes the game.

**Logs**
[Log](https://gitlab.com/-/snippets/2062024)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I relayed to the mod author :)
