### ISSUE TITLE
Some ore chunks no longer work in Mek machines for ore multiplying

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica6#917]
**Modpack version**
0.3.6

**Issue**
so far, Aluminum, silver,nickel chunks no longer work in any of the machines. Sulfur, mana gems, and apatite also no longer go in enriching for doubling.

May need to check other chunk crushing/doubling as those are the only ones i have tried that didnt work so far.

**Comment by MuteTiefling** [comment]
At first glance, this looks like an issue with our jaopca configs. Can reproduce in Dev with no KJS scripts. Resetting Jaopca's configs, however, resolves the problem.
