### ISSUE TITLE
0.2.5 farmland isn't craftable

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#92]
**Modpack version**
0.2.5

**Issue**
In the update change log it says that farmland is now craftable with a hoe and dirt. This does not work nor does a recipe show up in JEI if you click on it to check.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Huh, weird. Do you have the Enigmatica Companion mod in your instance?

**Comment by Shindur** [comment]
I do not, nor is it in the server files from what I can see.

**Comment by NillerMedDild** [comment]
God I hate Twitch sometimes. Will be fixed in 0.2.6 - You can fix it by adding that mod: https://www.curseforge.com/minecraft/mc-mods/enigmatica-companion-mod/files/3025390

**Comment by Shindur** [comment]
Sounds good, thank you for the work you put into the pack <3

**Comment by NillerMedDild** [comment]
My pleasure, thanks for reporting and for sticking with Enigmatica :P
