### ISSUE TITLE
Issues with recipies that use Farmer's Delight knife with Cooking for Blockheads and Refined Storage.

### ISSUE THREAD

**Issue by NeoDohko** [NillerMedDild/Enigmatica6#920]
**Modpack version**
0.3.6

**Issue**
1. Farmer's Delight recipies using the knife don't work with the Cooking for Blockheads multiblock kitchen (for example Raw Bacon is created but the knife is destoryed instead of using durability). No error log.

2. Using the Farmer's Delight knife to craft on the Wirless Crafting Table from Refined Storage or using the crafting grid the knife doesn't lose durablity and the raw porkshop is not consumed, the logs on the pastebin link are for an exception that happens when this method is used. Crafting table works as expected

**Logs**
https://pastebin.pl/view/4b0c5d41

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Darkere** [comment]
Going to fix the second one. Shift crafting should work but there was an oversight for normal crafting.
