### ISSUE TITLE
Dark Utilities Mod Filter

### ISSUE THREAD

**Issue by tatehaga** [NillerMedDild/Enigmatica6#923]
**Modpack version**
0.3.6
**Describe the bug**
None of the recipes for mob filters accept any type of wooden gate.  Tested several different wood materials, and none work.  The recipe exists in JEI, and shows that it accepts wooden gates, however no crafting apparatus will complete the recipe.

**Comment by MuteTiefling** [comment]
Cannot reproduce in Dev. Worked fine with a Dead Fence Gate from BOP in a vanilla crafting table, for instance.  Will test in 0.3.6

**Comment by MuteTiefling** [comment]
Can't reproduce in 0.3.6 either. Just made an undead filter with grongle fence gates and polished diorite.

Would you mind uploading your latest.log, please? Perhaps restart the game as well.

**Comment by tatehaga** [comment]
Just tested again, worked fine with fence gates made of wood from vanilla and biomes o' plenty, just not oh the biomes you'll go.  Might be intentional but no mistake of Dark Utilities mod.

**Comment by NillerMedDild** [comment]
Ah my bad, we'll get that fixed :)

**Comment by NillerMedDild** [comment]
Fixed it in the modpack and reported to BYG devs here: https://discord.com/channels/636017992265891846/636020488480489480/801548191694585938
