### ISSUE TITLE
Alex's Mobs Excessive Spawning

### ISSUE THREAD

**Issue by Figulus88** [NillerMedDild/Enigmatica6#925]
**Modpack version**
0.3.6

**Describe the bug**
Had a couple dozen Orcas near my base on the official server, I killed them all (that took a while) and waited. 26+ new Orcas spawned in under 5 hours (the screenshot below shows the majority of them, but there were more not far away).

Another player on the Discord last night spoke about a couple dozen Bone Serpents in the Nether in one area/lava lake on their SP world.

I haven't done significant exploring on 0.3.6 yet, but 0.3.5 had IMO far too many flies spawning in the Overworld while I was searching for bees.

**Logs**
N/A

**Screenshots**
![2021-01-16_20 49 16](https://user-images.githubusercontent.com/75228236/104831317-7a6a4900-583c-11eb-8382-8ed57b2aca44.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
