### ISSUE TITLE
Weird bounding box around BotanyPots crops

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#93]
**Modpack version**
0.2.5

**Issue**
Botany Pots have a weird rendering box around the crops when growing. Tested with/without optifine, persists through both.

I went ahead and made the issue on Botany Pots github already: https://github.com/Darkhax-Minecraft/BotanyPots/issues/65

**Comment by Shindur** [comment]
Botany pots has updated and has fixed this issue :)

**Comment by NillerMedDild** [comment]
Woohoo!
