### ISSUE TITLE
JEI tag searches don't work on server client

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica6#934]
**Modpack version**
0.3.6

**Describe the bug**
A quest helpfully points out that you can search for storage and lists some sample searches.  But, typing $storage into the JEI search bar doesn't work.  Tag searching is turned on (by default) in the JEI config.  Talking with folks on the discord E6 channel, I was told that this works fine in single player, but is a known issue with servers. 

![image](https://user-images.githubusercontent.com/8292929/104845478-5722b680-589b-11eb-9b32-6ab9dedbe36b.png)

**Comment by TemperedFool** [comment]
Looks like the team reported this:

https://github.com/mezz/JustEnoughItems/issues/2165

Definitely annoying behavior ^_^
