### ISSUE TITLE
Recipes for BYG Grass/dirt variants

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica6#935]
**Modpack version**
0.3.6

**Describe the bug**
Meadow grass blocks don't spread to adjacent dirt blocks
![image](https://user-images.githubusercontent.com/8292929/104845848-2e9bbc00-589d-11eb-813a-b048db860908.png)

**Comment by NillerMedDild** [comment]
Meadow Grass only spreads to Meadow Dirt, it is intentional :)

**Comment by ArbitraryHubris** [comment]
suggestion, maybe there could be a circular crafting recipe so you can change to different types of dirt so I could keep my place looking nicer.  Not a big deal.

**Comment by NillerMedDild** [comment]
Sure thing, will add that right away :)
