### ISSUE TITLE
Mining gadget can't mine redstone

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica6#936]
**Modpack version**
0.3.6

**Describe the bug**
When mining with the mining gadget, redstone shows up as unminable - requiring diamond mining level.  There is a workaround where you can start mining the block next to redstone and strafe over the redstone, mining it.  

![image](https://user-images.githubusercontent.com/8292929/104849753-0cac3480-58b1-11eb-8281-0b9ee8870afe.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. I have a feeling this is fixed in the latest EE update, will verify when it's available :)

**Comment by NillerMedDild** [comment]
Yup it's fixed \o/
