### ISSUE TITLE
Quest typo in "Tier 1 Beehive" - Missing the A in Apiaries

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica6#938]
**Modpack version**
0.3.6

**Describe the bug**
Quest: Tier 1 Beehive has a typo.  piaries should be Apiaries
![image](https://user-images.githubusercontent.com/8292929/104854640-7f2b0d80-58cd-11eb-97ce-7a970bcf40f9.png)

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by NillerMedDild** [comment]
Thanks!
