### ISSUE TITLE
Redstone Comparator dupe

### ISSUE THREAD

**Issue by SeaSaltStar** [NillerMedDild/Enigmatica6#939]
In 0.3.6 when a comparator is placed vertically it doesn't consume the item in your hand, but when broken gives you another. Haven't tested it with other redstone blocks.

**Comment by SeaSaltStar** [comment]
Oh no I didn't check through the list thoroughly enough. I'm unsure how to delete this

**Comment by Merlo17** [comment]
Duplicate https://github.com/NillerMedDild/Enigmatica6/issues/896

**Comment by NillerMedDild** [comment]
No worries, thanks for the report anyway :)
