### ISSUE TITLE
Programmable drones can be crafted without pcb

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica6#94]
**Modpack version**
0.2.4

**Issue**
programmable drones can be crafted without the requirement of a pcb, even though jei specifies otherwise, dont know if this is a mod issue thats why i am reporting this here
![2020-08-07_10 36 54](https://user-images.githubusercontent.com/59537798/89611265-5cb2b400-d89a-11ea-86c1-2bff81651cf4.png)
![2020-08-07_10 39 47](https://user-images.githubusercontent.com/59537798/89611279-64725880-d89a-11ea-9779-6fe25320cb20.png)
im talking about the third recipe

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
