### ISSUE TITLE
Pneumatic Craft armor gui Nether Portal glitch

### ISSUE THREAD

**Issue by Awstheepic** [NillerMedDild/Enigmatica6#942]
**Modpack version**
0.3.6

**Describe the bug**
when you use the pneumatic armor, it has a gui, right? that gui causes nether portal (and might other portals) purple screen to be glitched, more explaination in screenshots

**Logs**
No need.

**Screenshots**
https://streamable.com/4xe5jm

**Comment by NillerMedDild** [comment]
Thanks for the report! Which upgrades do you have in the armor, if any? :)
