### ISSUE TITLE
unable to insert repeater into glyph press 

### ISSUE THREAD

**Issue by boneskull** [NillerMedDild/Enigmatica6#943]
**Modpack version**

v0.3.6

**Describe the bug**

Unable to insert a `Redstone Repeater` into Ars Noveau's `Glyph Press` to create `Glyph: Delay`.  Normally, you'd right-click the repeater to insert it into the press.  The repeater affixes itself to the _side_ of the glyph press, instead.  

The probe says the repeater is a Builder's Addition item, so maybe the problem is there.

(Further, I was seeing some item duplication after breaking the repeater, but I cannot replicate it.  If you try this, keep an eye out.)

Workaround: Place a different non-block item (e.g., a torch) in front of the glyph press.  Click "through" this item to insert the repeater, since the repeater will not be able to place itself in the space the torch is occupying.

**Screenshots**

![image](https://user-images.githubusercontent.com/924465/104883887-4c5b3680-591a-11eb-80b4-ca4a6dabf195.png)

**Comment by Awstheepic** [comment]
arent you supposed to put the clay first?

**Comment by useenzhekoay** [comment]
Probably same issue with #896 which reported to mod author.

**Comment by Awstheepic** [comment]
> Probably the same issue with #896 which reported to the mod author.

might be true if they are the same mod dev

**Comment by boneskull** [comment]
yes, you are supposed to put the clay first. that works fine; just the repeater doesn't.  other items will insert

**Comment by mrh0** [comment]
I believe a workaround would be to right-click the top of the Glyph Press with the repeater.
