### ISSUE TITLE
Building Gadget templates different from quest parts

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica6#946]
**Modpack version**
0.3.6
**Describe the bug**
The building gadget templates that are included (and referenced by the quests) dont use the same block configuration as the quests have you make.  the 2 examples i have found so far is that the Mek wind turbine doesnt ask for, use, or place the turbine blades in the structure. also, the fusion reactor uses more casings and less glass than the quest has produced. Also, the fusion reactor has an extra block in the top corner of its blueprint.

I havent looked at the other templates.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
The turbine blades are tiles that the building gadget can't place. You've got no choice but to place them manually. 

The rest sounds like oversights. I'll take a look at them.

**Comment by MuteTiefling** [comment]
Added a note to the Turbine quest about the blades as well the fix to the template.
