### ISSUE TITLE
Some Mekanism fluid recipes are not shown in JEI when using "Show Use" Key.

### ISSUE THREAD

**Issue by new-3** [NillerMedDild/Enigmatica6#947]
**Modpack version**
0.3.6

**Describe the bug**
When you press 'show usage' key at Brine and Liquid Lithium in JEI list, their usage in Electrolytic Separator is not shown.
Their usages exist in JEI(when checking Electrolytic Separator, Chlorine, Lithum Dust), seems just not properly linked.
People who get into Mekanism for first time could be confused.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

*
*Screenshots**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Hmm, I can't reproduce this issue. Were you in singleplayer or on a server?

**Comment by Figulus88** [comment]
the same applies to the infuse types at least from certain screens, like this one:
![2021-01-18_18 24 36](https://user-images.githubusercontent.com/75228236/104980011-782df900-59ba-11eb-9107-e6096da2142f.png)
I'm on the official server, 0.3.6, but it's been on ongoing issue for a few versions now.

**Comment by new-3** [comment]
> Hmm, I can't reproduce this issue. Were you in singleplayer or on a server?

I am on my server, apologize for not saying that. 
My server has been updated from older versions, and just checked that same issue happens on a newly downloaded server too.

**Comment by theboo** [comment]
can confirm for at least brine on the dev server it doesnt show the rotary condenstratatator and thermal evap recipes when right clicking in jei or a in a recipe
