### ISSUE TITLE
Astral Sorcery structures doesn't generate in the amplified world type

### ISSUE THREAD

**Issue by AndersBennedsgaard** [NillerMedDild/Enigmatica6#948]
**Modpack version**
0.3.6

**Describe the bug**
I am not completely sure this is true, but I can't seem to get AS structures to spawn in amplified terrain. I also tried in a new world, where I just flew around to no avail. 
Perhaps they are below ground, but I don't know how to test this.

Edit: Also seems to be true for the caves world type. Flying through the world as spectator, I can't find them under the ground either. It seems they just don't generate

Edit2: Also seems to be true for floating islands. Using /locate as suggested by @Danklor, doesn't give the location of any structure. 
In the default world type, they do generate, so is this a bug for non-default world types? Can anyone reproduce this?

**Comment by Danklor** [comment]
You can use the /locate command to find the closest structure of the specified name. (Just a suggestion, I have not tried to duplicate the issue yet.)

**Comment by AndersBennedsgaard** [comment]
I have tried this, and it can't seem to find any structure in amplified, caves, or floating islands. It does work in the normal world type though..
