### ISSUE TITLE
Blood Needles

### ISSUE THREAD

**Issue by honcongjung4** [NillerMedDild/Enigmatica6#949]
https://www.curseforge.com/minecraft/mc-mods/blood-needles
Easy slime

the mod is cool and add slime from needle blood

**Comment by Merlo17** [comment]
Personally I see no need for this one, it just seems pretty redundant and unnecessary. We have tons of ways to make slime already and this one is just boring

**Comment by NillerMedDild** [comment]
I also feel that this would be redundant, but thanks for the suggestion.
