### ISSUE TITLE
Ultimate Powah! achievement bug

### ISSUE THREAD

**Issue by lunulu** [NillerMedDild/Enigmatica6#952]
**Modpack version**
0.35

**Describe the bug**
Can't achieve last Powah! achievement "Ultimate Powah". I have 2 Nitro Reactors, 9 Nitro Energy Cells for more than 1 billion energy, I even tried to put in my inventory 7 Nitro batteries. The achievement doesn't count.

**Screenshots**
![2021-01-18_22 09 40](https://user-images.githubusercontent.com/65171793/104955139-c226d700-59da-11eb-92d1-323c99a23ad2.png)
![2021-01-18_22 09 50](https://user-images.githubusercontent.com/65171793/104955143-c3f09a80-59da-11eb-8035-c2f471933044.png)
![2021-01-18_22 09 54](https://user-images.githubusercontent.com/65171793/104955147-c521c780-59da-11eb-89f9-4d561e46944d.png)
![2021-01-18_22 10 12](https://user-images.githubusercontent.com/65171793/104955148-c5ba5e00-59da-11eb-8386-0e2b46d4ec7c.png)

**Comment by Merlo17** [comment]
Unfortunately FTB Quests hasn't implemented a way to hand in that type of quest yet. I'll leave this open as a reminder that we should probably hide that quest until it is. I've said this before but I always forget c.c

**Comment by NillerMedDild** [comment]
No running from it now Merlo, you're assigned 😄

**Comment by Merlo17** [comment]
Already hidden on the dev server ^^

**Comment by lunulu** [comment]
I have an idea. What if you add a requirement for 7 fully charged batteries or energy cells in the inventory? It is 7 * 140kk = 980 kk RF.
