### ISSUE TITLE
Sanguine Scientiem glitched

### ISSUE THREAD

**Issue by KOgamer9012** [NillerMedDild/Enigmatica6#955]
Version 0.3.5

When opening the Sanguine Scientiem book from Blood Magic, a large portion of pages are unavailable, and are replaced with a generic alchemical sign. 
![2021-01-18_16 32 52](https://user-images.githubusercontent.com/61663680/104973826-dce15780-59aa-11eb-9ce1-a78fe39d2396.png)
On the front page of the book there is red text displaying "Loading Error"
![2021-01-18_16 33 41](https://user-images.githubusercontent.com/61663680/104973851-f5517200-59aa-11eb-8576-f185b9e9c9c7.png)

**Comment by r-mc2** [comment]
I noticed this back in 0.3.4 myself. There was talk of some of this being fixed over in #823 although I may have misinterpreted the fixes that were to come ? (The PR connected was mostly recipe changes if I recall)

**Comment by Merlo17** [comment]
Could you please update to 0.3.6 and see if the problem persists?

**Comment by MuteTiefling** [comment]
> I noticed this back in 0.3.4 myself. There was talk of some of this being fixed over in #823 although I may have misinterpreted the fixes that were to come ? (The PR connected was mostly recipe changes if I recall)

It's the way we were doing the changes that broke the book.

Patchouli recipe previews are linked to a recipe ID. If that ID is removed, the book breaks. So to fix it, we had to change the recipes in a way that keeps the same ID
