### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by NotCvmo** [NillerMedDild/Enigmatica6#957]
**Modpack version**
Enigmatica6-0.3.6

**Describe the bug**
I just recently encountered a duplication bug when plonking items in claimed territory other than my own, when not allied. The bug is somewhat intermittent but easily replicable. It seems that the stack will appear its original number when picked up, but then place in to the players inventory twice. For example, plonk a stack of 64, pick up the stack, click the first slot in inventory, stack places 64 in inventory but there is still 64 being held under the cursor, place the next stack and have 2x the amount.

**Logs**
N/A

**Screenshots**
Here is a detailed collection of screenshots with descriptions: https://imgur.com/a/FOuRZQ0

**Comment by BlueAgent** [comment]
This is pretty interesting, just testing this now and the block placement successfully goes through, but shortly after the block gets broken. So what's going on is block is being placed even though it reported that it failed to be placed. (Plonk restores the held item if the block wasn't successfully placed).

**Comment by BlueAgent** [comment]
Okay, just released a fix for it [here](https://www.curseforge.com/minecraft/mc-mods/plonk/files/3173536).
If anyone's curious, here's more information about why it happened: https://github.com/breakinblocks/Plonk/issues/9

**Comment by NillerMedDild** [comment]
Damn that was fast, thanks!
