### ISSUE TITLE
Vanilla chest recipe not using different variants of plank.

### ISSUE THREAD

**Issue by himehimetan** [NillerMedDild/Enigmatica6#959]
**Version: 0.3.6**

**Describe the bug**
Vanilla chest recipe is using stripped wood log variants and wood log variants. Is it not possible to make the old recipe of using plank variants to craft chest by switching recipe from modded chest to vanilla chest? There is a recipe change button.
I'm sure people would considered this a bug if they can't use BYG wood plank variants to craft regular chest.

**Screenshots**
![2021-01-19_01 44 39](https://user-images.githubusercontent.com/73065673/105003181-f492fd00-59f7-11eb-8fdf-a428caf8bdd9.png)

**Comment by MuteTiefling** [comment]
I'm having trouble finding the actual commit to link here, but this is already fixed in Dev.

**Comment by himehimetan** [comment]
Awesome!
Just checking in if this is intentional or not.
