### ISSUE TITLE
Botania materials are duplicated in Tetra

### ISSUE THREAD

**Issue by eJar0k** [NillerMedDild/Enigmatica6#960]
**Version:** 0.3.6

**Description:** All Botania metals except Gaia are duplicated as Tetra materials, with different stats. Importantly, Manasteel and Elementium have versions with different tool levels, meaning that pick heads do not match actual Botania pickaxes in mining level. For example, the Manasteel Pickaxe from Botania can mine diamond-level blocks like gold and silver, while two Manasteel pick heads are one level lower.

**Screenshots:**
![image](https://user-images.githubusercontent.com/21207875/105004217-7c710b00-59e8-11eb-83af-e3741e5ad5ea.png)
![image](https://user-images.githubusercontent.com/21207875/105004051-4764b880-59e8-11eb-8bb8-2f9511e26377.png)
![image](https://user-images.githubusercontent.com/21207875/105004064-4c296c80-59e8-11eb-92d3-a8933af741cb.png)
![image](https://user-images.githubusercontent.com/21207875/105004079-50558a00-59e8-11eb-980d-3844fdd5ca7a.png)
![image](https://user-images.githubusercontent.com/21207875/105004102-551a3e00-59e8-11eb-8e2e-3acd0765ec90.png)
![image](https://user-images.githubusercontent.com/21207875/105004128-5a778880-59e8-11eb-8621-bfc009d1556b.png)
![image](https://user-images.githubusercontent.com/21207875/105004143-5ea3a600-59e8-11eb-95ca-a903f0234e90.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Both issues fixed, thanks :)
