### ISSUE TITLE
Mekanism Turbine Valve

### ISSUE THREAD

**Issue by lunulu** [NillerMedDild/Enigmatica6#962]
**Modpack version**
0.35
**Describe the bug**
The mechanical pipe doesn't connect to turbine valve.

**Screenshots**
![2021-01-19_15 33 11](https://user-images.githubusercontent.com/65171793/105035966-dd422700-5a6c-11eb-8075-67c46a7298f8.png)

**Comment by Darkere** [comment]
The Turbine Valve ouputs steam which is a gas. So fluid pipes are not going to work.

**Comment by lunulu** [comment]
> The Turbine Valve ouputs steam which is a gas. So fluid pipes are not going to work.

I've tried  Pressurized Tubes too, but they didn't work either. And all the guides use mechanical pipes.

**Comment by KrAzYGEEK32** [comment]
are you sure the turbine has a valid structure? it doesnt look like that to me, and tubes only connect when structure is valid

**Comment by lunulu** [comment]
> are you sure the turbine has a valid structure? it doesnt look like that to me, and tubes only connect when structure is valid

Pretty sure, because I was building it according to the guide, and the red effects of a successful line also appeared.

**Comment by Darkere** [comment]
Does the Turbine GUI open if you rightclick it?

**Comment by lunulu** [comment]
> Does the Turbine GUI open if you rightclick it?
Yes

**Comment by Darkere** [comment]
Well according to some digging on discord it seems like they did change to using Pressurized Tubes for this fairly recently. So ignore old tutorials. 

Not sure what else could be wrong. Maybe someone around can try to replicate this.

**Comment by lunulu** [comment]
What am I doing wrong?
https://youtu.be/vSN24LTzjdo

**Comment by DarkAngel22579** [comment]
Shift right-clicker the boiler valve with a configurator to change it to output mode

**Comment by lunulu** [comment]
@DarkAngel22579, oh, thanks, I'm an... just thank you!
