### ISSUE TITLE
When exploring some nether and end biomes server becomes offline.

### ISSUE THREAD

**Issue by TheAnimaDust** [NillerMedDild/Enigmatica6#964]
Server don't crash but becomes offline and then after some minutes, crash.
[crash-2021-01-19_17.00.36-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/5838347/crash-2021-01-19_17.00.36-server.txt)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Actually, which modpack version? Please use the bug report template in the future.

**Comment by NillerMedDild** [comment]
Looks like this issue: #958

**Comment by TheAnimaDust** [comment]
It seens like its a end biome and the server gives a warning unknow biome id.
modpack version is 3,6

**Comment by TheAnimaDust** [comment]
[Server thread/WARN] [corgiaoc.byg.BYG/]: BYG's End Void Layer: Unknown biome id: -1

**Comment by TheAnimaDust** [comment]
we don't have in the server any rituals in astral sorcery

**Comment by NillerMedDild** [comment]
Ah I see, could you please supply the latest log?

**Comment by TheAnimaDust** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5838536/latest.log)

**Comment by NillerMedDild** [comment]
In which modpack version was this world generated?

**Comment by TheAnimaDust** [comment]
0.3.6

**Comment by NillerMedDild** [comment]
May I have the debug.log as well please?

**Comment by TheAnimaDust** [comment]
[debug.log](https://github.com/NillerMedDild/Enigmatica6/files/5838693/debug.log)
we are trying to get away from the biome but it crashes every time the player got in the server

**Comment by NillerMedDild** [comment]
Which biome is it?

**Comment by Darkere** [comment]
You can use NBT explorer (or my mod crash utlities heh) to move the player to a different place/dimension.

**Comment by TheAnimaDust** [comment]
we can't see as it won't load any chunks

**Comment by TheAnimaDust** [comment]
even with render distance in 1 still crashes the surrounding biomes are cryptic wastes

**Comment by TheAnimaDust** [comment]
in fact every chunk in the area of the crash are cryptic wastes

**Comment by TheAnimaDust** [comment]
in the direction of the crash have some viscal isles 
![2021-01-19_19 43 50](https://user-images.githubusercontent.com/40836876/105096899-834e5b00-5a86-11eb-88ef-816a4d0fbc10.png)
![2021-01-19_19 43 54](https://user-images.githubusercontent.com/40836876/105096906-85181e80-5a86-11eb-85a4-86d2a4391dd6.png)
as you can see the big island to the west are unloaded and after that have a small rendered area in the map that is viscal isles

**Comment by TheAnimaDust** [comment]
> You can use NBT explorer (or my mod crash utlities heh) to move the player to a different place/dimension.

we are doing this right, thank you for the suggestion

**Comment by CorgiTaco** [comment]
It is as I feared

**Comment by Grant-K** [comment]
Im playing on a server that also has this issue the server freezes and crashes after a minuet or two when loading certain biomes in the end (Dont know which ones yet will upload server logs when I can get them)
