### ISSUE TITLE
Crashing when opening chat

### ISSUE THREAD

**Issue by TheBookAjah** [NillerMedDild/Enigmatica6#965]
Version 0.3.6

When I open chat, either with / for a command, t like normal or even sleeping in a bed the game crashes. The crash report looks like it is to do with emojiful

Crash reports on three separate days (also three plays in a row):
https://pastebin.com/NM2duwdz
https://pastebin.com/xSwiXCsB
https://pastebin.com/HhHLQjqv

EDIT: apparently the issue has been reported here: https://github.com/InnovativeOnlineIndustries/Emojiful/issues/16
but I don't know.

**Screenshots**

**Comment by NillerMedDild** [comment]
Thanks for the report! May I ask which language you have the game set to, and which language your PC is set to show? When it comes to chat/text related crashes locale is often important.

**Comment by TheBookAjah** [comment]
The language is English UK for both. Also I ended up deleting that world and also changing to using Forge 36.0.1 and the issue no longer happens in the new world, so I don't know whether it is world-specific or something to do with Forge or what. The world was a brand new world, though, and it was fairly shortly after creating it that I tried to open chat and it crashed (the first time).
