### ISSUE TITLE
Wrong order of quests for uranium.

### ISSUE THREAD

**Issue by lunulu** [NillerMedDild/Enigmatica6#968]
**Modpack version**
0.35

**Describe the bug**
Wrong order of quests for uranium.

**Screenshots**
![2021-01-20_17 35 25](https://user-images.githubusercontent.com/65171793/105194332-86ab1a80-5b4a-11eb-863e-4bef26cae032.png)

**Comment by MuteTiefling** [comment]
Oops! Fixed in next update thanks for the report :D
