### ISSUE TITLE
Potential Biome Shuffling Issue

### ISSUE THREAD

**Issue by kythorn** [NillerMedDild/Enigmatica6#971]
This isn't true a bug report or a mod suggestion, but rather a heads up on a 1.16 issue you may want to be aware of.  If you're already tracking this, apologies for being a nuisance.

I observed the DW20 1.16 pack update caused a lot of biome shuffling/corruption for people because an update added new IDs. This is completely different from the dimensional registry issue you already encountered.

Mojang issue: https://bugs.mojang.com/browse/MC-202036 (more about data packs there, but same concept)

FTB issue: https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/99

Mod that can allegedly prevent this by adding a biome palette to each chunk, but has to be added (and the chunk loaded) BEFORE the issue happens: https://www.curseforge.com/minecraft/mc-mods/chocolate-fix

**Comment by Darkere** [comment]
BYOG has that mod as dependency so we should already have it.

**Comment by kythorn** [comment]
Awesome. Glad to hear it!

**Comment by NillerMedDild** [comment]
We do indeed, but thanks for the heads up.
