### ISSUE TITLE
Wrong quest description for Tier 1 Beehive

### ISSUE THREAD

**Issue by Scorch-Mechanic** [NillerMedDild/Enigmatica6#977]
**Modpack version**
Enigmatica 6 0.3.7

**Describe the bug**
The quest description for the "Tier 1 Beehive" quest is identical to the quest description for the "Tier 1 Apiary" quest. Which is a little bit confusing.

**Comment by NillerMedDild** [comment]
Huh, I wonder what happened there :P thanks for the report!
