### ISSUE TITLE
Mekanism Teleporter in the Nether

### ISSUE THREAD

**Issue by lunulu** [NillerMedDild/Enigmatica6#982]
**Modpack version**
0.35

**Describe the bug**
After restarting the server, the teleporter in the nether is unavailable, although the anchor improvement is installed, and you need to load chunks with a regular portal to the nether. There is no such problem with the teleporter in the End.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Is this still happening? If yes, does it happen every time? :)

**Comment by lunulu** [comment]
Version - 0.3.11
I restarted the server, everything seems to work, thank you!
