### ISSUE TITLE
Memory Leak with C&B

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica6#983]
**Modpack version**
E6 0.3.7

**Describe the bug**
There seems to be a Memory Leak in Chisel & Bits. Gef did some testing as he was encountering it often, and Orion confirmed the issue. 

**Logs**
N/A

**Screenshots-type of deal**
https://youtu.be/2BaXOeWZkTY?t=120

**Comment by Buuz135** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/chisels-bits/files/3176033
