### ISSUE TITLE
buildersaddition redstone-logic blocks duplication

### ISSUE THREAD

**Issue by Dr-DaNk** [NillerMedDild/Enigmatica6#984]
**Modpack version** 0.3.6

**Describe the bug**
buildersaddition provides the functionality to place Redstone-logic blocks such as comparators, repeaters, etc on walls. When you right-click a wall with a comparator, it places down a comparator on the wall but doesn't consume the item from your inventory. Upon breaking the comparator from the wall, you get another comparator. This works for all vanilla Redstone-logic blocks.

**Comment by Dr-DaNk** [comment]
I don't know if this is an issue with the modpack or the mod but I put the issue here

**Comment by NillerMedDild** [comment]
Fixed in 0.3.7, thanks for the report anyway :)
