### ISSUE TITLE
Quantum Storage Chest

### ISSUE THREAD

**Issue by Master2Mind88** [NillerMedDild/Enigmatica6#985]
**Modpack version**
0.3.7
**Describe the bug**
When you are in quantum storage and you create a iron one. To go to gold you need an iron block and 
quantum storage iron = 4 Wood, 3 Chest, 2 Iron,
quantum storage gold = 6 Wood, 1 Iron block, 2 Gold
quantum storage diamond = 6 Wood, 1 Gold Block, 2 Diamonds

![image](https://user-images.githubusercontent.com/12238607/105407319-cd505180-5bea-11eb-94b0-93b588902fe9.png)

![image](https://user-images.githubusercontent.com/12238607/105407372-e1944e80-5bea-11eb-9a93-f2969207b71d.png)

**Comment by NillerMedDild** [comment]
I'm not sure what the bug is? That they're expensive?

**Comment by Master2Mind88** [comment]
Where the block are should be the quantum storage iron in the gold one and the diamond one.

**Comment by MuteTiefling** [comment]
Pretty sure this was done because upgrading them voids the contents.

**Comment by NillerMedDild** [comment]
Yup, that's the reason :) #908

**Comment by Master2Mind88** [comment]
It is not the same reason. It is a different one. In 0.3.6 it was able to be able to craft this way but in 0.3.7 it is like the images above.

**Comment by Master2Mind88** [comment]
It make it so that you can skip the iron and gold ones and go straight to diamonds since they don't upgrade on them self anymore.

**Comment by MuteTiefling** [comment]
Let's say you crafted an iron one. Then you filled it with nether stars.

You pick up that crate (which keeps items on break) , then use it in the recipe to make a gold crate.

You've now lost all the those nether stars. Not fun, right?

That's why it was changed.
