### ISSUE TITLE
Unable to start server Enigmatica6-0.3.6 due to EULA

### ISSUE THREAD

**Issue by hatchett927** [NillerMedDild/Enigmatica6#986]
**Enigmatica6-0.3.6**

**Describe the bug**
It seems that the server-start.bat does recognize that I have changed the ELUA.txt to true. I have changed the to "eula=true" in elua.txt

**Screenshots**
![server error pic](https://user-images.githubusercontent.com/12092872/105419127-3ac0aa00-5c0c-11eb-8efe-cb1ddb9e399e.png)

**Comment by Darkere** [comment]
make sure there aren't any spaces behind the text you put in. Worst case make a new file

**Comment by hatchett927** [comment]
That worked! Thank you, would have never thought to check that.
