### ISSUE TITLE
Cannot craft signpost with BYF planks

### ISSUE THREAD

**Issue by toothmonsterr** [NillerMedDild/Enigmatica6#987]
**0.3.7 BETA**

**Describe the bug**
When using maple, fir, or mangroove (these are the ones I've tested), I cannot craft signposts, despite them showing up as an option in JEI recipes for the various vanilla signposts.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
There is no such thing as Vanilla Sign Post afaik, do you mean a Sign?

**Comment by toothmonsterr** [comment]
Yup, that's the one.
