### ISSUE TITLE
Suggestion: Add Use to Thermal Creosote 

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#988]
**Modpack version**
0.3.7

**Describe the bug(?)**
Thermal added Pyrolyzer, which allows you to make Creosote. It doesn't have any use, unlike IE Creosote, which can be used to make Treated Wood

**Comment by HaxtonSale1** [comment]
Apologies for the wrong label, should I resubmit this?

**Comment by MuteTiefling** [comment]
The label is automatic. No worries there.

Creosote should be useful as a weak fuel already. Can it not also be used in place of IE creosote for treated wood?

**Comment by HaxtonSale1** [comment]
![2021-01-22_11 06 22](https://user-images.githubusercontent.com/13237198/105436093-eb2cbd80-5ca1-11eb-86cf-aa974903fb4e.png)
While it is usable as a fuel it doesn't show on JEI

**Comment by MuteTiefling** [comment]
Alrighty. Il see what we can do here. Thanks!
