### ISSUE TITLE
[Mod Suggestion] Extreme sound muffler forge

### ISSUE THREAD

**Issue by TupacTheLazy** [NillerMedDild/Enigmatica6#99]
https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler

it was in Enigmatica 4 and 5 and i really miss it in enigmatica 6.

**Comment by NillerMedDild** [comment]
Huh, I thought I added that already, weird :P

**Comment by TupacTheLazy** [comment]
Thank you 😄
