### ISSUE TITLE
Create Handheld Blockzapper Requires Create Brass

### ISSUE THREAD

**Issue by r-mc2** [NillerMedDild/Enigmatica6#991]
**Modpack version**
v0.3.6

**Describe the bug**
The Handheld Blockzapper in Create is something like an exchanging tool but with the added benefit of having some randomness which is great when designing walls/floors and not having to place the "random" by hand. However to get any decent use out of it you need to upgrade it. The upgrades are fairly straightforward, however some upgrades require you to use brass ingots:
![image](https://user-images.githubusercontent.com/36780233/105433613-f2af8080-5c27-11eb-8ffe-08d71203f279.png)
Currently due to the unification of brass these recipes aren't being recognized:
![image](https://user-images.githubusercontent.com/36780233/105433654-0c50c800-5c28-11eb-8b62-eaaacf54ad63.png)

I'm able to work around it for the moment with Mekanism's Oredictionificator to obtain Create's original ingots:
![image](https://user-images.githubusercontent.com/36780233/105434016-bf212600-5c28-11eb-900c-047bcf8d14b5.png)

I double-checked any previous PRs and didn't see this mentioned getting touched in v0.3.7 or in anything I saw in a cursory look in the changes upcoming for v0.3.8. But if I missed it and it's already on the way feel free to ignore me 😄

**Comment by NillerMedDild** [comment]
We'll get that fixed, thanks for the report :)
