### ISSUE TITLE
Incompletable quest in Immersive Engineering due to unobtainable item

### ISSUE THREAD

**Issue by TheExistingOne** [NillerMedDild/Enigmatica6#992]
Enigmatica 6: 0.3.6

Description
Immersive Engineering quest "Coke Oven" requires coal coke from immersive engineering, but only emendatus enigmatica coal coke is obtainable without cheats.

Screenshots
![Quest](https://user-images.githubusercontent.com/49994945/105443883-a3fee800-5c21-11eb-813a-6c6cceb1231e.PNG)
Screenshot of quest in question

![CokeOven](https://user-images.githubusercontent.com/49994945/105443887-a5c8ab80-5c21-11eb-92f8-8e3faaf629ef.PNG)
Screenshot of coal coke produced by coke oven

Suggestion
Either change the quest to accept any variety of coal coke (Haven't worked with questing mods much so I don't know if this is possible) or change the quest to accept emendatus enigmatica coal coke

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed.

**Comment by Merlo17** [comment]
Fix ready on the dev server ^^
